Fix for source-highlight package to detect installed boost lib
LLNL/spack pull request #16102
Opened 2020-04-16 20:25 UTC by servesh

Source highlight configure script doesn't detect the boost regex library installed through Spack. So as suggested https://www.gnu.org/software/src-highlite/source-highlight.html#Tips-on-installing-Boost-Regex-library I added a fix for configure script that resolves the issue.

2020-04-17 09:31 UTC, alalazo requested changes

2020-04-17 09:31 UTC, alalazo commented on var/spack/repos/builtin/packages/source-highlight/package.py
> +        args = ["--with-boost=" + format(self.spec['boost'].prefix)]
```suggestion
        args = ["--with-boost={0}".format(self.spec['boost'].prefix)]
```

2020-04-20 21:53 UTC, adamjstewart approved these changes

2020-04-22 09:42 UTC, alalazo approved these changes

2020-04-22 09:43 UTC, merged