spack test: collect errors
LLNL/spack pull request #16109
Opened 2020-04-17 00:25 UTC by becker33

Feature to collect spack test failures within an individual package's tests and only fail at the end with an error message displaying messages and context for all of the errors.

2020-04-20 23:08 UTC, tldahlgren requested changes
I understand the desire to use a hash but it could be more "user friendly" to include the version in the output file name.

More importantly, this does not flag failing tests as "FAILED", which is useful if one is `grep`ing test results to find failures.

For example, 

```
$ spack test openmpi
==> Spack test at 2020-04-20_15:50:38
==> Testing package openmpi-2iikagi
==> Error: TestFailure: 1 tests failed.

Failed to find executable 'prun'
...
```

**does** include the traceback in the output file but does not flag the test case as `FAILED`.  Similarly, if I change the expected return code so it is not valid for a test, the test will fail as expected but is not flagged as `FAILED` in the test output file.

2020-04-21 18:33 UTC, becker33 commented
Do you care that the key-word be `FAILED` instead of `Error`? We have to print `Error` anyway to get CDash to pick up the errors properly, so I thought that should be the key-word for errors.

2020-04-22 17:12 UTC, tldahlgren commented
> Do you care that the key-word be `FAILED` instead of `Error`? We have to print `Error` anyway to get CDash to pick up the errors properly, so I thought that should be the key-word for errors.


Well, `FAILED` provides "symmetry" and consistency with the unit test framework approach we'd discussed.

Also, I assumed part of the goal was to allow tests that fail -- so maybe trigger `Errors` -- to actually be successful tests.  The point being whether `Error` (or `Error:`) is an appropriate pattern to `grep`.

2020-04-22 17:20 UTC, becker33 commented
> Also, I assumed part of the goal was to allow tests that fail -- so maybe trigger `Errors` -- to actually be successful tests. The point being whether `Error` (or `Error:`) is an appropriate pattern to `grep`.

We catch all errors in the `run_test` method, and if it's an expected error we don't re-raise it or print it to the log file.

I can't say with any certainty whether the executable they ran itself might print `Error:` or `Error` or `FAILED`. If it does, it will produce spurious errors when grepping.

The reason I removed the `print('FAILED')` call originally is because it seemed redundant to have code

```
print('Error: %s' %s)
print_stack()
print('FAILED')
```

If `FAILED` is also parsed by the cdash error parsing, we could maybe change the `print('Error...')` line to include `FAILED`.

2020-04-23 21:56 UTC, tldahlgren approved these changes
I like seeing 'FAILED'.  It's also nice seeing the error message, though that is _not_ consistent with the *unit test outputs I thought were being emulated.

The_ modified tests work for me.  The `openmpi` smoke test is failing due to missing `prun` but that's another issue.

2020-04-23 21:58 UTC, merged