py-pyproj: New version
LLNL/spack pull request #16176
Opened 2020-04-20 15:53 UTC by citibeth

Added latest version of `py-proj`, to work successfully with latest version of `proj`.

2020-04-20 20:20 UTC, adamjstewart requested changes

2020-04-20 20:20 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyproj/package.py
>      version('1.9.6',   sha256='e0c02b1554b20c710d16d673817b2a89ff94738b0b537aead8ecb2edc4c4487b')
For dependencies, it looks like the latest version requires Python 3.5+ and Cython 0.28.4+.

2020-04-20 21:04 UTC, adamjstewart approved these changes

2020-04-22 09:50 UTC, alalazo approved these changes

2020-04-22 09:50 UTC, merged