cdo: Update for use with proj@6
LLNL/spack pull request #16177
Opened 2020-04-20 15:54 UTC by citibeth

Added new version to work with `proj@6`.  No official releases work with `proj@6` yet, but the RC2 version is pretty close.  When there is an official release, we should replace the RC2 version with it.

2020-04-20 20:18 UTC, adamjstewart requested changes

2020-04-20 20:18 UTC, adamjstewart commented on var/spack/repos/builtin/packages/cdo/package.py
>      version('1.9.8', sha256='f2660ac6f8bf3fa071cf2a3a196b3ec75ad007deb3a782455e80f28680c5252a', url='https://code.mpimet.mpg.de/attachments/download/20286/cdo-1.9.8.tar.gz')
Can you make the previous version `preferred=True` so that it will be chosen by default?

2020-04-20 20:18 UTC, adamjstewart commented on var/spack/repos/builtin/packages/cdo/package.py
> +    # https://launchpad.net/ubuntu/+source/cdo/+changelog
I would move this comment down to the `depends_on` statements you modified below.

2020-04-20 21:03 UTC, adamjstewart approved these changes
@skosukhin may want to review this

2020-04-21 11:45 UTC, skosukhin commented
As far as I understand, we have three cases here:
1. `cdo@:1.9.6` needs the old API of `proj` to be available unconditionally and `proj@:5` satisfies that constraint.
2. `cdo@1.9.7` still needs the old API of `proj` but also knows how to switch to it explicitly, therefore, we can use any version of `proj` that offers the old API: `proj@:7` ([version `7` will be the last major version offering the old API](https://proj.org/news.html#release-notes)).
3. `cdo@1.9.8:` uses the new API, therefore, we need to use `proj@5:`.

I write something like:
```python
depends_on('proj@:5', when='@:1.9.6+proj')
depends_on('proj@:7', when='@1.9.7+proj')
depends_on('proj@5:', when='@1.9.8:+proj')
```

I don't mind adding version `1.9.9.rc2` but there are official releases that are compatible with `PROJ 6`.

2020-05-04 21:33 UTC, adamjstewart commented
LGTM if @skosukhin approves. @citibeth can you confirm that 1.9.8 builds with PROJ.6? Do you still need to add the release candidate?

2020-05-04 21:57 UTC, citibeth commented
> I don't mind adding version `1.9.9.rc2` but there are official releases that are compatible with `PROJ 6`.

Such as...?  I was having trouble with the latest official release.

2020-06-18 16:36 UTC, skosukhin requested changes
@citibeth sorry for the delay. Could you, please, address my comments, rebase and add the following:
```python
# Help the concretizer (see also https://github.com/spack/spack/pull/16719)
depends_on('hdf5+hl', when='+netcdf')
```

2020-06-18 16:36 UTC, skosukhin commented on var/spack/repos/builtin/packages/cdo/package.py
> +    version('1.9.9.rc2', sha256='2328299c43ecd10f8283056b6a65e6f205fb64e988ce360fc2b30672e7491e66',
`cdo` is supposed to work with `PROJ6` starting version `1.9.7` (by switching to the old API). Starting version `1.9.8` `cdo` officially supports the new API of `PROJ6`. Therefore, we don't really need the release candidate. Could you, please, remove it?

2020-06-18 16:36 UTC, skosukhin commented on var/spack/repos/builtin/packages/cdo/package.py
> +    # https://launchpad.net/ubuntu/+source/cdo/+changelog
Officially, there is no version `1.9.8.1`: https://code.mpimet.mpg.de/projects/cdo/files
Could you, please, replace the reference link with https://code.mpimet.mpg.de/projects/cdo/news?

2020-08-22 18:01 UTC, adamjstewart commented
@citibeth can you rebase and address @skosukhin's requests?

2020-08-25 02:48 UTC, citibeth commented on var/spack/repos/builtin/packages/cdo/package.py
> +    version('1.9.9.rc2', sha256='2328299c43ecd10f8283056b6a65e6f205fb64e988ce360fc2b30672e7491e66',
The only reason I would use an `rc` version is if the official release didn't work for me in this situation.

2020-10-19 04:21 UTC, adamjstewart commented
No response from @citibeth so I'm assuming this PR is stale. Feel free to reopen if you still want to add these changes.

2020-10-19 04:21 UTC, closed without merging