update compiler config with bootstrapped compiler when already installed
LLNL/spack pull request #16221
Opened 2020-04-21 21:40 UTC by becker33

When `config:install_missing_compilers` is True, `spack install foo %compiler_not_available` works if the compiler is not installed, but fails if the compiler is already installed.

This PR adds logic to update the compiler config upon finding that a needed compiler is already installed, in addition to doing so after installing it if it were not already installed.

2020-04-21 22:46 UTC, tldahlgren requested changes
Reviewed the code in context and see why this should've been added.

LGTM.  It just needs a unit test.

2020-04-22 20:15 UTC, becker33 commented
@tldahlgren test added and ready to go.

2020-04-22 21:24 UTC, tldahlgren approved these changes
LGTM and new tests run for me.

2020-04-22 21:26 UTC, merged

2020-04-22 21:26 UTC, tldahlgren commented
Thank you for your contribution.