bclib: New package.
LLNL/spack pull request #16271
Opened 2020-04-24 03:06 UTC by tkameyama

2020-04-24 17:02 UTC, adamjstewart requested changes

2020-04-24 17:02 UTC, adamjstewart commented on var/spack/repos/builtin/packages/xabclib/package.py
> +        copy('libOpenAT.a', prefix.lib)
```suggestion
        install('libOpenAT.a', prefix.lib)
```

2020-04-24 17:02 UTC, adamjstewart commented on var/spack/repos/builtin/packages/xabclib/package.py
> +        copy('Readme.pdf', prefix.doc)
```suggestion
        install('Readme.pdf', prefix.doc)
```

2020-04-24 17:02 UTC, adamjstewart commented on var/spack/repos/builtin/packages/xabclib/package.py
> +        return find_libraries('libOpenAT.a', self.prefix.lib)
```suggestion
        return find_libraries('libOpenAT', self.prefix.lib, shared=False)
```

2020-04-27 02:51 UTC, tkameyama commented on var/spack/repos/builtin/packages/xabclib/package.py
> +        return find_libraries('libOpenAT.a', self.prefix.lib)
fixed.

2020-04-27 03:08 UTC, adamjstewart requested changes

2020-04-27 03:08 UTC, adamjstewart commented on var/spack/repos/builtin/packages/xabclib/package.py
> +        return find_libraries('libOpenAT.a', self.prefix.lib, shared=False)
```suggestion
        return find_libraries('libOpenAT', self.prefix.lib, shared=False)
```

2020-04-27 03:18 UTC, adamjstewart approved these changes

2020-04-27 11:33 UTC, alalazo approved these changes

2020-04-27 11:33 UTC, merged