database/spec: Keep track of dependents using object identity instead
LLNL/spack pull request #16447
Opened 2020-05-04 14:35 UTC by aweits

Fixes #11983

2020-05-04 21:51 UTC, adamjstewart commented
Once the semester is over (before or after this PR gets merged) I'll check to see if this fixes #3690.

2020-05-05 22:05 UTC, adamjstewart commented
Just tested this out. I still have an error when uninstalling a lot of packages.

2020-05-12 09:33 UTC, alalazo requested changes
I'm not really sure `id` is the right granularity for this reason:
```console
Spack version 0.14.2
Python 3.6.9, Linux x86_64
>>> import spack.spec
>>> hdf5 = spack.spec.Spec('hdf5')
>>> hdf5.concretize()
>>> zlib = hdf5['zlib']
>>> zlib_copy = zlib.copy()
>>> id(zlib)
140656426554088
>>> id (zlib_copy)
140656426527712
>>> zlib.dag_hash()
'os3djb57dqdzhaqsl2n7iefz3gwombyi'
>>> zlib_copy.dag_hash()
'os3djb57dqdzhaqsl2n7iefz3gwombyi'
```
In my opinion we don't care whether it's the same Python object, but if it represents the same build. 

Another thing to consider is how we want to use `_dependents`. Using `Spec.dag_hash` instead of `id` is fine way to solve the issue above and get a consistent data structure. Another way to solve #11983 would be to continue indexing by name but use a list of specs as a value. I guess what is the best solution depends on how do we envision using `_dependents`. Thoughts?

2020-05-12 14:05 UTC, aweits commented
> Another thing to consider is how we want to use `_dependents`. Using `Spec.dag_hash` instead of `id` is fine way to solve the issue above and get a consistent data structure. Another way to solve #11983 would be to continue indexing by name but use a list of specs as a value. I guess what is the best solution depends on how do we envision using `_dependents`. Thoughts?

Long-term, I do concur, I have another branch where I'm working on this - Spec needs to be much more defensive with respect to how things that are a part of the hash are changed/altered (i.e. simply using dag_hash() inside of _add_dependencies is fraught with peril). I felt I should at least put this forward as an potential interim fix.

2020-05-13 02:23 UTC, scheibelp reviewed
Currently I don't see any issue with using `id`, but I want to consider the possible issues a bit more before approving.

I’m wondering if we could replace the dictionary with a list, or some custom object which mostly behaves like a list but would offer the ability to access elements based on object-id or spec equality (or for concrete specs, the DAG hash). This would also help track down possible reference issues e.g. right now `_replace_with` still refers to the keys as "name" (which doesn't cause a bug because they aren't used, but may confuse future readers).

2020-05-13 02:23 UTC, scheibelp commented on lib/spack/spack/test/spec_dag.py
> -        assert s['e']._dependencies['f'].deptypes == ('run',)
Why are the `._dependencies` calls removed?

2020-05-13 02:23 UTC, scheibelp commented on lib/spack/spack/test/database.py
> +    assert len(specs) == 1
This assertion feels somewhat fragile: we are depending on the fake installation to maintain a single `dyninst` install going forward. That being said, if there were multiple that would also cause a problem for this test since the `callpath` dependents might change. Ideally then this could start with a mock database and repo, and install multiple versions of some simple package `X` depending on package `Y`

2020-05-13 02:23 UTC, scheibelp commented on lib/spack/spack/spec.py
> +            for dspec in sorted(where.values()):
I don't think the sorting is still needed if `name` is omitted (or rather no longer present).

2020-05-14 11:15 UTC, aweits commented on lib/spack/spack/test/spec_dag.py
> -        assert s['e']._dependencies['f'].deptypes == ('run',)
There were two sets of the same assertions. Is there somthing subtle about that I missed?

2020-05-14 11:15 UTC, aweits commented on lib/spack/spack/test/database.py
> +    assert len(specs) == 1
I can certainly change that.

2020-05-14 11:18 UTC, aweits commented on lib/spack/spack/spec.py
> +            for dspec in sorted(where.values()):
I believe the sorting is necessary to get the same reproducible ordered results for a traverse()(DependencySpec has the @lang.key_ordering decorator) - I'll double check.

2020-05-14 17:38 UTC, scheibelp commented on lib/spack/spack/test/spec_dag.py
> -        assert s['e']._dependencies['f'].deptypes == ('run',)
I see three sets of references in this diff:

```
        assert s['b']._dependencies['c'].deptypes == ('build',)
        assert s['d']._dependencies['e'].deptypes == ('build', 'link')
        assert s['e']._dependencies['f'].deptypes == ('run',)
```

and 

```
        assert s['c']._dependents['b'].deptypes == ('build',)
        assert s['e']._dependents['d'].deptypes == ('build', 'link')
        assert s['f']._dependents['e'].deptypes == ('run',)
```

the latter is repeated twice. I was curious why the first one was removed.

2020-05-14 19:46 UTC, aweits commented on lib/spack/spack/test/spec_dag.py
> -        assert s['e']._dependencies['f'].deptypes == ('run',)
I restated the _dependents test once in terms of making it function post-change. I also removed one block of the _dependencies assertions as they seem to be testing the same things twice. Now there should be one set of assertions for _dependents and one for _dependencies.

This was the complete block prior:
```
        assert s['b']._dependencies['c'].deptypes == ('build',)
        assert s['d']._dependencies['e'].deptypes == ('build', 'link')
        assert s['e']._dependencies['f'].deptypes == ('run',)

        assert s['b']._dependencies['c'].deptypes == ('build',)
        assert s['d']._dependencies['e'].deptypes == ('build', 'link')
        assert s['e']._dependencies['f'].deptypes == ('run',)

        assert s['c']._dependents['b'].deptypes == ('build',)
        assert s['e']._dependents['d'].deptypes == ('build', 'link')
        assert s['f']._dependents['e'].deptypes == ('run',)

        assert s['c']._dependents['b'].deptypes == ('build',)
        assert s['e']._dependents['d'].deptypes == ('build', 'link')
        assert s['f']._dependents['e'].deptypes == ('run',)
```

2020-05-14 19:48 UTC, aweits commented on lib/spack/spack/spec.py
> +            for dspec in sorted(where.values()):
A quick test of removing sorted() and running 'spack test lib/spack/spack/test/spec_dag.py' indicates that it *is* necessary

2020-05-14 21:25 UTC, scheibelp commented on lib/spack/spack/spec.py
> +            for dspec in sorted(where.values()):
Thanks for confirming! This looks good

2020-05-14 21:26 UTC, scheibelp commented on lib/spack/spack/test/spec_dag.py
> -        assert s['e']._dependencies['f'].deptypes == ('run',)
Thanks, and apologies - I did not read that carefully

2021-09-16 10:47 UTC, alalazo commented
Closing this one in favor of #21683

2021-09-16 10:47 UTC, closed without merging