blis: FIX threads option
LLNL/spack pull request #16476
Opened 2020-05-05 19:31 UTC by yellowhat

Patch blis package to look for the libblis-mt.so library

Thanks to jlow2016 for the hint

2020-05-05 20:56 UTC, adamjstewart requested changes

2020-05-05 20:56 UTC, adamjstewart commented on var/spack/repos/builtin/packages/hpl/package.py
> +            config = ['CFLAGS=-O3 -fopenmp']
```suggestion
            config = ['CFLAGS=-O3 ' + self.compiler.openmp_flag]
```
This will work regardless of which compiler you are using.

2020-05-06 09:30 UTC, yellowhat commented
Unfortunately `spec` is not exposed by `configure_args` how can I check for `spec` in this function?

Thanks

2020-05-06 20:36 UTC, adamjstewart approved these changes

2020-05-06 20:36 UTC, merged