Fix dependency of geant4 (amends #16497)
LLNL/spack pull request #16504
Opened 2020-05-07 09:19 UTC by iarspider

2020-05-08 17:29 UTC, adamjstewart approved these changes
Let me actually wait for maintainer approval this time instead of merging things quickly

2020-05-09 15:27 UTC, drbenmorgan requested changes
The 10.6.1 patch also requires g4emlow 7.9.1 patch, so that version needs adding to the g4emlow `package.py`, and the `depends_on` in `geant4-data` updating accordingly.

2020-05-09 16:45 UTC, adamjstewart commented on var/spack/repos/builtin/packages/geant4-data/package.py
> +    depends_on("g4emlow@7.9", when='@10.6.0:10.6.9999')
```suggestion
    depends_on("g4emlow@7.9", when='@10.6.0')
```

2020-05-09 18:04 UTC, drbenmorgan approved these changes

2020-05-09 18:04 UTC, merged