py-plotly: unfix dependency versions (fixes #16544)
LLNL/spack pull request #16546
Opened 2020-05-09 22:14 UTC by omsai

2020-05-10 02:32 UTC, adamjstewart commented
Actually, according to the `setup.py`, the correct dependencies and versions should be:
```python
      install_requires=['decorator>=4.0.6',                                     
                        'nbformat>=4.2',                                        
                        'pytz',                                                 
                        'requests',                                             
                        'six'],   
```
Can you change it to these?

2020-05-12 16:44 UTC, adamjstewart requested changes

2020-05-12 16:44 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-plotly/package.py
> +    depends_on('py-pytz@2014.9:', type=('build', 'run'))
```suggestion
    depends_on('py-requests', type=('build', 'run'))
    depends_on('py-six', type=('build', 'run'))
    depends_on('py-pytz', type=('build', 'run'))
```

2020-05-12 16:53 UTC, omsai commented on var/spack/repos/builtin/packages/py-plotly/package.py
> +    depends_on('py-pytz@2014.9:', type=('build', 'run'))
Applied to 835065e

2020-05-12 16:56 UTC, adamjstewart approved these changes

2020-05-12 22:06 UTC, merged