py-fastcluster: new package at 1.1.26
LLNL/spack pull request #16588
Opened 2020-05-11 19:10 UTC by codeandkey

2020-05-11 22:07 UTC, adamjstewart requested changes

2020-05-11 22:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-fastcluster/package.py
> +    depends_on('py-numpy@1.9:', type=('build', 'run'))
Missing build dep on setuptools

2020-05-12 19:29 UTC, codeandkey commented on var/spack/repos/builtin/packages/py-fastcluster/package.py
> +    depends_on('py-numpy@1.9:', type=('build', 'run'))
added!

2020-05-12 19:35 UTC, adamjstewart approved these changes

2020-05-16 21:12 UTC, merged