isescan: new package at 1.7.2.1
LLNL/spack pull request #16589
Opened 2020-05-11 19:13 UTC by codeandkey

depends on `fraggenescan` in #16587, `py-fastcluster` in #16588

2020-05-11 22:02 UTC, adamjstewart requested changes

2020-05-11 22:02 UTC, adamjstewart commented on var/spack/repos/builtin/packages/isescan/package.py
> +            which('gcc')(
Doesn't this only work for the GCC compiler? You should use `Executable(spack_cc)` to use the compiler wrappers.

2020-05-11 22:02 UTC, adamjstewart commented on var/spack/repos/builtin/packages/isescan/package.py
> +                '-O3', '-pipe', '-fPIC', '-shared', '-rdynamic',
```suggestion
                '-O3', '-pipe', self.compiler.cc_pic_flag, '-shared', '-rdynamic',
```

2020-05-11 22:02 UTC, adamjstewart commented on var/spack/repos/builtin/packages/isescan/package.py
> +                '-o', 'libssw.so', 'ssw.c', 'ssw.h',
```suggestion
                '-o', 'libssw.' + dso_suffix, 'ssw.c', 'ssw.h',
```

2020-05-11 22:02 UTC, adamjstewart commented on var/spack/repos/builtin/packages/isescan/package.py
> +        blastn_path = join_path(blast_pfx, 'blastn')
```suggestion
        blastn_path = blast_pfx.blastn
```
Same for other lines

2020-05-12 19:43 UTC, codeandkey commented
Updated -- I switched the PIC flag and DSO suffix, but is there a generic alternative for `-rdynamic` and `-shared`?

2020-08-07 00:15 UTC, codeandkey commented
Restarting for CI now that dependencies have been merged.

2020-08-07 00:55 UTC, adamjstewart approved these changes

2020-08-07 00:58 UTC, codeandkey commented
Oops, forgot to push rebase. Should be safe to merge now if ready.

2020-08-07 03:26 UTC, merged