hwloc: Add libudev variant.
LLNL/spack pull request #16615
Opened 2020-05-13 03:23 UTC by tkameyama

This PR add libudev variant in hwloc.
On rhel8, libudev dose not link with spack build libuuid.
So I want to libudev default to False.

libudev.so depend libblkid.so:
<pre>
$ ldd  /lib64/libudev.so
        linux-vdso.so.1 (0x0000ffffad450000)
        libmount.so.1 => /lib64/libmount.so.1 (0x0000ffffad360000)
        libgcc_s.so.1 => /opt/arm/reports-20.0.3/lib/libgcc_s.so.1 (0x0000ffffad320000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x0000ffffad2e0000)
        libc.so.6 => /lib64/libc.so.6 (0x0000ffffad160000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffffad460000)
        libblkid.so.1 => /lib64/libblkid.so.1 (0x0000ffffad0f0000)
        libuuid.so.1 => /lib64/libuuid.so.1 (0x0000ffffad0c0000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x0000ffffad070000)
        librt.so.1 => /lib64/librt.so.1 (0x0000ffffad040000)
        libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x0000ffffacfa0000)
        libdl.so.2 => /lib64/libdl.so.2 (0x0000ffffacf70000)
</pre>
libblkid need uuid_unparse@UUID_1.0.
But uuid_unparse@UUID_1.0 is not found in spack provided libuuid.
So the package depends hwloc and libuuid is faild to build.
<pre>
/bin/ld: /lib64/libblkid.so.1: undefined reference to `uuid_unparse@UUID_1.0
</pre>

2020-05-13 17:51 UTC, adamjstewart requested changes
@hppritcha are you interested in maintaining this package as well?

2020-05-13 17:51 UTC, adamjstewart commented on var/spack/repos/builtin/packages/hwloc/package.py
> +    variant('libudev', default=False, description="Build with libhudev")
```suggestion
    variant('libudev', default=False, description="Build with libudev")
```

2020-05-14 02:12 UTC, adamjstewart approved these changes

2020-05-14 18:24 UTC, hppritcha commented
@adamjstewart may be better to rope in @bgoglin for maintaining the hwloc package.

2020-05-14 18:37 UTC, bgoglin commented on var/spack/repos/builtin/packages/hwloc/package.py
> +    conflicts('+libudev', when="@:1.10.0")
hwloc added libudev in 1.11.0 afaik. So both lines look wrong?

2020-05-14 18:38 UTC, bgoglin commented
I am not sure I want to maintain it since I don't know much about hwloc, but I can review patches.

2020-05-15 00:51 UTC, adamjstewart commented
@bgoglin don't worry, you don't have to be a Spack expert, it just gives us someone to ping when someone reports a build issue or submits a PR to modify the package.

2020-05-15 06:12 UTC, bgoglin commented
Ok we can try that then.

2020-05-16 21:12 UTC, adamjstewart commented
@tkameyama can you add the following to the package:
```python
maintainers = ['bgoglin']
```

2020-05-18 01:00 UTC, merged