compilers: add opt_flags and debug_flags properties
LLNL/spack pull request #16710
Opened 2020-05-18 23:46 UTC by becker33

Allow packages to query the optimization and debug flags for a compiler.

For example:

```
def flag_handler(self, name, flags):
    if name == 'cxxflags':
        opt_flag_found = any(f in self.compiler.opt_flags for f in flags)
        debug_flag_found = any(f in self.compiler.debug_flags for f in flags)

        if '+debug' in self.spec:
            debug_flag_found or flags.append('-g')
            opt_flag_found or flags.append('-O0')
        else:
            opt_flag_found or flags.append('-O2')

    return (flags, None, None)
```

2020-05-19 02:51 UTC, adamjstewart commented
It should be easy to get 100% coverage by adding to the `test_*_flags` tests in `lib/spack/spack/tests/compilers.py`.

2020-05-19 04:14 UTC, becker33 commented
I will question the value of tests that just test hardcoded values, but in the interest of high codecov numbers I've added them.

2020-05-19 12:00 UTC, alalazo requested changes
Same comment as in #16634 for the unit tests. The parts that are unique to this PR looks good to me.

2020-05-19 12:00 UTC, alalazo commented on lib/spack/spack/compiler.py
> +                flags.append('fflags')
I see that there's a fair amount of overlap with #16634

2020-05-19 16:32 UTC, mwkrentel commented
@becker33 Is this a first attempt to address the issues I raised in #14430 ?

Spack has never handled compiler and optimization flags for autotools
cleanly.  IMO, the only solution is to choose the flags at the spack
level and then pass them to configure.

A full solution would be to add variants, eg, `debug_symbols` and
`opt_flags` to all autotools packages, something similar to cmake's
`build_type`.  (Well, not all, it would break some packages.)

----------

Btw, I understand your example is just an example.  But I don't really
like the pairing of `-g` with `-O0`.  IMO `-g -O2` is a legitimate
configuration and usually the default for both cmake (RelWithDebInfo)
and autotools.

2020-05-19 16:49 UTC, becker33 commented
@mwkrentel I don't think this provides a full solution to the issues you posted in #14430, but I believe it (in conjunction with the `flag_handler` method) can resolve some of the most severe of those issues.

2020-05-19 18:46 UTC, becker33 commented on lib/spack/spack/compiler.py
> +                flags.append('fflags')
It's based on #16634, I can rebase on develop, they're orthogonal but they were both needed for a use-case I was supporting.

2020-05-29 00:23 UTC, becker33 commented
@alalazo the other PR is merged and this is rebased, hopefully nothing looks out of place to you now.

2020-05-29 08:52 UTC, alalazo approved these changes

2020-05-29 08:52 UTC, merged