julia: Add perf profiling support
LLNL/spack pull request #16740
Opened 2020-05-20 08:31 UTC by zzzoom

This PR adds a `perf` variant (disabled by default) to Julia that is able to generate `perf` data for [external profiling](https://docs.julialang.org/en/v1/manual/profile/#External-Profiling-1).

2020-05-21 03:38 UTC, adamjstewart approved these changes
@glennpj can you review?

2020-05-22 14:46 UTC, glennpj commented
This variant would not be valid for julia versions <1.0.

2020-05-22 14:48 UTC, glennpj requested changes
Add a `conflicts` statement for julia versions <1.0.

2020-05-23 02:09 UTC, zzzoom commented
Done

2020-05-25 12:26 UTC, alalazo approved these changes

2020-07-17 18:52 UTC, zzzoom commented
@glennpj could you give this a quick look please?

2020-07-18 21:15 UTC, glennpj commented
Using `USE_BINARYBUILDER_LLVM=0` will not work with python-3, in my testing, and so would require the python version constraints to be tweaked. However, `julia@1.4.0+perf` will build with python-3 if `USE_BINARYBUILDER_LLVM=0` is removed. It is probably better to not make the python constraints more confusing so I propose the following changes:

1. remove `USE_BINARYBUILDER_LLVM=0`
1. set the conflict to
```
conflicts('+perf', when='@:0.1.3',                                                                                    
              msg='Variant perf requires Julia >= 1.4.0')   
```

If `+perf` is really needed for the older versions, in addition to python version constraint tweaks, there should also be logic to remove `USE_BINARYBUILDER_LLVM=0` for version 1.4.0 and greater.

2020-07-30 05:33 UTC, zzzoom commented
https://github.com/JuliaLang/julia/issues/33417 remains open, so >=1.4.0 probably isn't a good constraint to avoid setting `USE_BINARYBUILDER_LLVM=0`.

2020-09-17 21:49 UTC, glennpj commented
@zzzoom Sorry for the delayed response. This completely fell off of my radar. 

I do think that setting the constraint for versions >=1.4.0 is the best way to go. That said, I am not opposed to pulling in python-2 constraints to make the `perf` variant work for older versions. One of the two needs to be done though.

2021-02-19 09:56 UTC, alalazo commented
@zzzoom

2021-02-24 04:24 UTC, zzzoom commented
I got it fixed today, but the feature remains poorly documented and the profiling data it stores isn't that useful (perf needs help mapping back to julia source), so I'll close this.

Thank you for your patience.

2021-02-24 04:24 UTC, closed without merging