Add new package: blogbench
LLNL/spack pull request #16793
Opened 2020-05-25 01:58 UTC by darmac

2020-05-25 09:13 UTC, alalazo approved these changes

2020-05-25 09:18 UTC, alalazo requested changes
Uh, recipe looks fine, but I get 404 consistently on the homepage. Should we use [this](https://openbenchmarking.org/test/pts/blogbench) instead?

2020-05-25 09:23 UTC, darmac commented
I'm not sure it's official link or not, but if you think it's better than the official page in `Readme.md`(404 Error), I will change it.

2020-05-26 09:16 UTC, alalazo approved these changes

2020-05-26 09:16 UTC, merged