Add new package: quicksilver
LLNL/spack pull request #16792
Opened 2020-05-25 01:57 UTC by darmac

2020-05-25 09:25 UTC, alalazo requested changes
A few request for changes.  Can you also tag this application as a `proxy-app`? You can check which others are tagged by looking at:
```console
$ spack list -t proxy-app
```

2020-05-25 09:25 UTC, alalazo commented on var/spack/repos/builtin/packages/quicksilver/package.py
> +    divergence of Mercury for problems using multigroup cross sections."""
Can you separate the docstring into a short first sentence and a longer description in another paragraph?

2020-05-25 09:25 UTC, alalazo commented on var/spack/repos/builtin/packages/quicksilver/package.py
> +    git      = "https://github.com/LLNL/Quicksilver.git"
According to Quicksilver's Github repository:

> Instructions to build Quicksilver can be found in the Makefile. Quicksilver is a relatively easy to build code with no external dependencies (except MPI and OpenMP)

Should we add MPI as a dependency then? Maybe conditional on a variant?

2020-05-25 09:26 UTC, alalazo commented
Pinging @richards12 in case he's interested in giving a few more hints on how the package for "Quicksilver" should look like.

2020-05-26 23:24 UTC, junghans commented
@alalazo I added mpi and openmp support in #16811.

2020-05-27 07:06 UTC, closed without merging

2020-05-27 07:08 UTC, alalazo commented
@darmac I went with @junghans version of the package since it was ready to be merged, hope you don't mind (and thanks for all your contributions!)

2020-05-27 07:15 UTC, darmac commented
That's OK, I'll test it on my platform. : )