Added Gridlab-d package.
LLNL/spack pull request #16816
Opened 2020-05-26 20:51 UTC by 0t1s1

Not including Matlab support at this time.

2020-05-27 07:34 UTC, alalazo requested changes
A minor request, otherwise LGTM.

2020-05-27 07:34 UTC, alalazo commented on var/spack/repos/builtin/packages/gridlab-d/package.py
> +    Autotools package for Gridlab-D. One day the devs will convert to Cmake!
Can you change the docstring to be more descriptive?

2020-05-28 10:52 UTC, alalazo approved these changes

2020-05-28 10:56 UTC, alalazo commented
@yee29 @afisher1 If you're fine with being maintainers of the `gridlab-d` Spack package I'll merge this PR. This means that you'll be pinged for review hwen somebody will update this build recipe.

2020-05-28 14:45 UTC, yee29 commented
That is fine with me

2020-05-29 07:36 UTC, alalazo approved these changes

2020-05-29 07:37 UTC, merged