[py-mdanalysis] new version and added dependencies
LLNL/spack pull request #16819
Opened 2020-05-26 21:13 UTC by qwertos

cc: @aweits 

Original commit message:

Author: Andrew Elble <aweits@rit.edu>
Date:   Thu Nov 14 08:35:14 2019 -0500

    mdanalysis

2020-05-30 07:18 UTC, scheibelp commented
The unit tests are failing because some of the mentioned dependencies don't yet exist in Spack. Could you add pointers to them here (assuming there are PRs for them)?

2020-05-31 02:26 UTC, adamjstewart requested changes

2020-05-31 02:26 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mdanalysis/package.py
>      depends_on('py-six@1.4.0:', type=('build', 'run'))
For `python`, can you add type=build/run?

For `numpy`, it looks like 1.13.3 is required now.

2020-05-31 02:26 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mdanalysis/package.py
>      depends_on('py-biopython@1.59:', type=('build', 'run'))
```suggestion
    depends_on('py-biopython@1.71:', type=('build', 'run'))
```

2020-05-31 02:26 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mdanalysis/package.py
> +    depends_on('py-mmtf-python', type=('build', 'run'))
```suggestion
    depends_on('py-mmtf-python@1:', type=('build', 'run'))
```

2020-05-31 02:26 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mdanalysis/package.py
Missing dependencies on joblib, scipy, matplotlib, and mock, which are all required, at least in the latest release.

2020-05-31 02:26 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mdanalysis/package.py
> +    depends_on('py-scikit-learn', type=('build', 'run'))
```suggestion
    depends_on('py-scikit-learn', when='+analysis', type=('build', 'run'))
```

2020-05-31 02:26 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mdanalysis/package.py
>      depends_on('py-scipy', when='+analysis', type=('build', 'run'))
These are now unconditionally required

2020-06-22 19:29 UTC, qwertos commented
Depends on #17200 and #17201

2020-06-30 14:29 UTC, adamjstewart approved these changes

2020-06-30 14:29 UTC, merged