fix satisfaction checks for exluding variants from matrices
LLNL/spack pull request #16893
Opened 2020-06-01 18:14 UTC by becker33

Because of the way abstract variants are implemented, the following spec matrix does not work as intended.

```
matrix:
- [foo]
- [bar=a, bar=b]
exclude:
- bar=a
```

This should output one spec `foo bar=b`, but it now outputs zero specs, because abstract variants always satisfy any variant of the same name, regardless of values.

This PR converts abstract variants to whatever their appropriate type is before running satisfaction checks for the `excludes` clause in a matrix. 

Fixes #16841 
Closes #16853

2020-06-01 19:36 UTC, alalazo requested changes
The `multivalue-variant` package has been deleted apparently, and that makes tests fail.

2020-06-01 19:36 UTC, alalazo commented on lib/spack/spack/spec_list.py
> +            pass
This seems the right fix to me. For the record, the semantics intended for `AbstractVariant` is that of a name-value variant when no package information is attached. As such it "could satisfy" every other name-value variant with the same name. The `strict` parameter, iirc was not added on purpose - `AbstractVariant` was not meant to be called with `strict=True` and not adding the variant was ensuring an exception is raised if that ever happened.

There's an old discussion at https://github.com/spack/spack/issues/4135#issuecomment-299514214 on which changes we might do to make the code less "surprising" and naming more appropriate. Don't know if everything still applies.

2020-06-01 19:54 UTC, becker33 commented
@alalazo I renamed the package from `multivalue_variant` to multivalue-variant` to satisfy our normal naming scheme. The renamed version is re-added now.

2020-06-02 08:59 UTC, alalazo approved these changes

2020-06-02 09:02 UTC, merged