Package/py-lmfit: add new version
LLNL/spack pull request #16975
Opened 2020-06-05 23:08 UTC by Sinan81

add new versions, and add new dependencies

Dependency `py-asteval` will be created soon.

2020-06-06 21:09 UTC, adamjstewart requested changes

2020-06-06 21:09 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-lmfit/package.py
> +    depends_on('py-six@1.11:',              type=('build', 'run'), when='@0.9.15: ^python@2.7:2.8')
```suggestion
    depends_on('py-six@1.11:',              type=('build', 'run'), when='@0.9.15')
```
It isn't needed for 1.0.1, and it is needed for 0.9.15 when Python 3.

2020-06-06 21:09 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-lmfit/package.py
> +    depends_on('py-uncertainties@3.0.1:',   type=('build', 'run'), when='@0.9.15:')
Can you add:
```python
depends_on('python@3.5:', type=('build', 'run'), when='@1:')
depends_on('python@2.7:2.8,3.5:', type=('build', 'run'), when='@0.9.15')
```

2020-06-07 14:37 UTC, adamjstewart approved these changes

2020-06-07 14:39 UTC, adamjstewart commented
py-uncertainties doesn’t seem to have a Spack package yet

2020-06-13 01:39 UTC, adamjstewart commented
Can you rebase now that `py-uncertainties` has been merged?

2020-06-13 23:31 UTC, Sinan81 commented
@adamjstewart Do you know why the  macos test is failing? The CI details didn't make sense to me.

2020-06-14 13:35 UTC, adamjstewart commented
That’s a known bug we’re working on. You can ignore it.

2020-06-14 13:36 UTC, merged