new package: py-uncertainties
LLNL/spack pull request #16997
Opened 2020-06-08 05:04 UTC by Sinan81

A dependency of #16975

2020-06-08 17:54 UTC, scheibelp commented on var/spack/repos/builtin/packages/py-uncertainties/package.py
> +    depends_on('py-future',     type=('build', 'run'), when='python@:2')
This needs to be `when=^python@:2`

2020-06-09 03:35 UTC, adamjstewart requested changes

2020-06-09 03:35 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-uncertainties/package.py
> +    depends_on('py-future',     type=('build', 'run'), when='^python@:2')
```suggestion
    depends_on('py-future',     type=('build', 'run'))
```

2020-06-09 03:35 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-uncertainties/package.py
> +    depends_on('py-sphinx',     type=('build', 'run'), when='+docs')
These two are both optional, I would either remove them or add variants for `+optional` and `+docs` and make them default to False

2020-06-09 21:14 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-uncertainties/package.py
> +    depends_on('py-sphinx',     type=('build', 'run'), when='+docs')
```suggestion
    depends_on('py-sphinx',     type='build', when='+docs')
```

2020-06-09 21:42 UTC, adamjstewart approved these changes

2020-06-11 15:26 UTC, merged