py-healpy: a new package.
LLNL/spack pull request #17001
Opened 2020-06-08 09:53 UTC by weijianwen

2020-06-09 03:46 UTC, adamjstewart requested changes

2020-06-09 03:46 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-healpy/package.py
> +    depends_on('python@2.6:2.7.99', type=('build', 'run'))
I think Python 3 is supported, at least in 1.13.0, since there is a dependency on six.

2020-06-09 03:46 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-healpy/package.py
> +    depends_on('py-setuptools@:45.0', type='build')
```suggestion
    depends_on('py-setuptools@3.2:', type='build')
```

2020-06-09 03:46 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-healpy/package.py
> +    depends_on('py-numpy@:1.16')
```suggestion
    depends_on('py-numpy@1.13:', type=('build', 'run'))
```

2020-06-09 03:46 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-healpy/package.py
> +    depends_on('py-matplotlib@:2')
```suggestion
    depends_on('py-matplotlib', type=('build', 'run'))
```

2020-06-09 03:46 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-healpy/package.py
> +    depends_on('py-wheel')
These last 3 aren't needed, at least for 1.13.0.

You're missing the following dependencies:
* six
* astropy
* scipy

2020-06-10 15:17 UTC, weijianwen commented
The updated py-healpy has been built succesfully against python@3.7 via

```
spack install py-healpy %gcc@4.8.5 target=x86_64 ^openblas
```

Or, if python@2.7 is preferred, more version specifications are required to avoid python3-dependent libraries:

```
spack install py-healpy %gcc@4.8.5 target=x86_64 ^python@2.7.18 ^py-setuptools@44.1.0 ^py-numpy@1.16.6 ^py-scipy@1.2.3 ^py-astropy@2.0.14 ^py-matplotlib@2.2.5 ^py-pillow@6.2.2 ^openblas
```

2020-06-12 14:28 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-healpy/package.py
> +    depends_on('py-six')
```suggestion
    depends_on('py-six', type=('build', 'run'))
```

2020-06-12 14:30 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-healpy/package.py
> +    depends_on('python@2.6:2.7.99,3.6:3.7', type=('build', 'run'))
I would remove the version constraints from this. There is nothing in the `setup.py` that prevents you from trying to build with a different version of Python.

2020-06-12 17:00 UTC, adamjstewart approved these changes

2020-06-13 01:36 UTC, merged