search for compiler names in order
LLNL/spack pull request #17449
Opened 2020-07-09 17:12 UTC by becker33

for compilers that have multiple executable names, search the names
in the priority order in `compilers/*.py` under <lang>_names to ensure
that newer names are caught before backwards compatibility names.

Fixes #518
Supersedes #6327

@adamjstewart

2020-07-10 03:20 UTC, adamjstewart commented on lib/spack/spack/compilers/__init__.py
> +        # Order already respecs priority from compiler class
```suggestion
        # Order already respects priority from compiler class
```

2020-07-23 18:40 UTC, scheibelp requested changes
There is a sync issue

This looks great but I have several suggestions for naming/docstrings

2020-07-23 18:40 UTC, scheibelp commented on lib/spack/spack/compilers/__init__.py
> +        # Order already respects priority from compiler class
Generally when you remove a comment and replace it with a new one, the new comment shouldn't "respond" to the old one. In other words, I would rephrase like:

> Return command arguments using the order specified by the compiler class (i.e. leave them unchanged)

2020-07-23 18:40 UTC, scheibelp commented on lib/spack/spack/test/cmd/compiler.py
> +def mock_two_compiler_dirs(tmpdir, mock_compiler_version):
Can the name be updated to include more detail about the issue:

`def mock_two_compilers_with_same_spec`

2020-07-23 18:40 UTC, scheibelp commented on lib/spack/spack/test/cmd/compiler.py
> +def mock_pgi_dir(tmpdir, mock_pgi_version_string):
Can the name include more details:

`def mock_pgi_old_and_new_fortran`

2020-07-23 18:40 UTC, scheibelp commented on lib/spack/spack/test/cmd/compiler.py
> +    # Find compilers
This `#` comment is unnecessary given that `compiler_find` is called right after. The test could use a docstring though (something like "When two compilers are detected with the same spec, make sure Spack uses the first one that appears in the ordered list of paths provided").

2020-07-23 18:40 UTC, scheibelp commented on lib/spack/spack/test/cmd/compiler.py
> +def test_compiler_add_multiple_names(
`def test_pgi_use_latest_fortran_name`?

2020-07-23 18:40 UTC, scheibelp commented on lib/spack/spack/test/cmd/compiler.py
> +):
Docstring, e.g.:

> Ensure that the `pgi` compiler returns "pgfortran" as the fortran compiler, preferring it over "pgf90" when both names are present (likewise for "pgf77")

2021-01-23 03:01 UTC, adamjstewart commented
Is this ever going to be merged or should we just close this and #518? It's my oldest Spack issue, so I would love to see it disappear.

2022-11-08 00:44 UTC, becker33 commented
#17967 made the same change

2022-11-08 00:44 UTC, closed without merging