abyss 2.1.4: fails to build with GCC 8
LLNL/spack pull request #17614
Opened 2020-07-21 06:12 UTC by t-nojiri

1) abyss 2.1.4: fails to build with GCC 8
    Change strncpy function to memcpy.
    The description of  allowed value of variant was changed.

2020-07-22 00:16 UTC, t-nojiri commented
Add fix_BloomFilter.hpp.patch file.

2020-07-24 22:59 UTC, scheibelp commented
Is there an issue open on the ABySS github page (https://github.com/bcgsc/abyss)? We might want to open one and reference it with the patch that is applied here.

2020-08-02 21:25 UTC, adamjstewart requested changes
Has this patch been upstreamed?

2020-08-02 21:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/abyss/package.py
> +            description='''set the maximum k-mer length.''')
```suggestion
            description='set the maximum k-mer length.')
```

2020-08-02 21:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/abyss/package.py
> +def is_integral(x):
This might be better named as `is_multiple_32` or something like that.

2020-08-03 02:06 UTC, t-nojiri commented
@scheibelp 
> Is there an issue open on the ABySS github page (https://github.com/bcgsc/abyss)? We might want to open one and reference it with the patch that is applied here.

There is issue at https://github.com/bcgsc/abyss/issues/264.

2020-08-03 05:30 UTC, t-nojiri commented
@adamjstewart 

> Has this patch been upstreamed?

Since it has been fixed in version 2.1.5, upstream will not be performed.

2020-08-04 17:11 UTC, adamjstewart approved these changes

2020-08-04 17:11 UTC, merged