Updates to jsonschema to include newer versions.
LLNL/spack pull request #17613
Opened 2020-07-21 05:09 UTC by FrankD412

Maestro's install fails due to too old of a version of jsonschema being available. This PR adds many of the newer version of jsonschema to Spack.

2020-07-21 06:08 UTC, alalazo commented
There's a `flake8` issue to be fixed:
```
var/spack/repos/builtin/packages/py-jsonschema/package.py:34: [W293] blank line contains whitespace
```

2020-07-24 15:01 UTC, alalazo approved these changes

2020-08-02 21:28 UTC, adamjstewart requested changes

2020-08-02 21:28 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-jsonschema/package.py
> +    depends_on('py-importlib-metadata', when='^python@:3.7.99', type=('build', 'run'))
I think you meant to combine these:
```suggestion
    depends_on('py-importlib-metadata', when='@3.1.1: ^python@:3.7.99', type=('build', 'run'))
```

2020-08-03 00:42 UTC, adamjstewart approved these changes

2020-08-03 00:42 UTC, merged