Packages/py sphinx removed in
LLNL/spack pull request #17634
Opened 2020-07-21 17:35 UTC by Bidibulke

Adding recipe for `sphinx-removed-in` (a python package)

2020-07-23 00:21 UTC, tldahlgren requested changes
Please change the Copyright year for both files from 2019 to 2020.

2020-07-23 06:32 UTC, Bidibulke commented
copyright changed as requested

2020-08-02 21:21 UTC, adamjstewart requested changes

2020-08-02 21:21 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-sphinx-removed-in/package.py
> +    depends_on('py-sphinx')
```suggestion
    depends_on('py-setuptools', type='build')
    depends_on('py-sphinx', type=('build', 'run'))
```

2020-08-04 04:01 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-sphinx-removed-in/package.py
> +    ."""
```suggestion
    """
```

2020-08-04 14:15 UTC, adamjstewart approved these changes

2021-06-11 16:40 UTC, alalazo commented
Closing as stale, but feel free to rebase and reopen (in the meanwhile the copyright year has changed to 2021 :grimacing: )

2021-06-11 16:40 UTC, closed without merging