Packages/py sphinxcontrib mermaid
LLNL/spack pull request #17630
Opened 2020-07-21 17:27 UTC by Bidibulke

Adding recipe for `sphinxcontrib-mermaid` (a python package)

2020-07-24 14:08 UTC, alalazo requested changes

2020-07-24 14:08 UTC, alalazo commented on lib/spack/docs/basic_usage.rst
> +.. Copyright 2013-2019 Lawrence Livermore National Security, LLC and other
Please revert this change

2020-07-27 08:31 UTC, Bidibulke commented on lib/spack/docs/basic_usage.rst
> +.. Copyright 2013-2019 Lawrence Livermore National Security, LLC and other
Done

2020-07-27 15:29 UTC, alalazo approved these changes

2020-07-27 15:30 UTC, merged