[py-smart-open] fixing dependencies
LLNL/spack pull request #17640
Opened 2020-07-21 18:52 UTC by qwertos

2020-07-23 01:01 UTC, tldahlgren requested changes
Please merge develop and re-push (so `py-boto` picked up from previous PR).  This is needed for the tests to pass, specifically for `test_all_dependencies_exist`'s catching the missing `py-boto` dependency.

2020-08-02 21:20 UTC, adamjstewart requested changes

2020-08-02 21:20 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-smart-open/package.py
> +    depends_on('py-boto', when='@1.8.4', type=('build', 'run'))
```suggestion
    depends_on('py-boto@2.32:', when='@1.8.4', type=('build', 'run'))
```

2020-08-04 19:47 UTC, adamjstewart approved these changes

2020-08-04 23:42 UTC, tldahlgren approved these changes
LGTM.  I am able to successfully build the package.

2020-08-04 23:44 UTC, merged

2020-08-04 23:44 UTC, tldahlgren commented
Thank you for your contribution.