Smoke test: Add test of a sequence of hdf5 commands
LLNL/spack pull request #17686
Opened 2020-07-24 02:51 UTC by tldahlgren

Fixes #17680 

This PR adds a simple example-based test that takes an `hdf5` file through the dump, copy, and diff commands.

This PR has been tested against the following version(s):  1.10.1

TODO:
- [ ] Install and run the tests against additional versions of the software

2020-07-30 03:21 UTC, adamjstewart commented
@lrknox can you review?

2020-08-04 16:14 UTC, becker33 requested changes
Mostly LGTM. A couple changes to use `self.test_dir` instead of the cwd.

2020-08-04 16:14 UTC, becker33 commented on var/spack/repos/builtin/packages/hdf5/package.py
> +        h5_file = os.path.join(curr_dir, 'data', 'spack.h5')
```suggestion
        curr_dir = os.getcwd()
        h5_file = os.path.join(self.test_dir, 'data', 'spack.h5')
```

2020-08-04 16:14 UTC, becker33 commented on var/spack/repos/builtin/packages/hdf5/package.py
> +        dump_file = os.path.join(curr_dir, 'data', 'dump.out')
```suggestion
        dump_file = os.path.join(self.test_dir, 'data', 'dump.out')
```

2020-08-05 18:00 UTC, tldahlgren commented on var/spack/repos/builtin/packages/hdf5/package.py
> +        h5_file = os.path.join(curr_dir, 'data', 'spack.h5')
Also need to remove `curr_dir` then.

2020-08-05 23:29 UTC, merged