Add variants to squashfs for different compression algorithms
LLNL/spack pull request #17755
Opened 2020-07-28 23:28 UTC by haampie

Currently squashfs only provides `gzip`, but the default on e.g. Ubuntu 20.04 is to provide `gzip (default)`, `lzma`, `lzo`, `lz4`, `xz`, `zstd`. With this PR we have those available as well, but the user has to enable them with variants.

2020-07-30 01:37 UTC, adamjstewart requested changes

2020-07-30 01:37 UTC, adamjstewart commented on var/spack/repos/builtin/packages/squashfs/package.py
> +                'GZIP_SUPPORT={}'.format(1 if '+gzip' in spec else 0),
```suggestion
                'GZIP_SUPPORT={0}'.format(1 if '+gzip' in spec else 0),
```
This is needed for Python 2.6 support

2020-07-30 07:26 UTC, haampie commented
Weird, when I run vermin locally it tells me the minimum version is 2.6 now:

```
$ vermin --backport argparse -t=2.6- -t=3.5- -v var/spack/repos | grep squashfs
2.6, 3.0     /home/harmen/spack/var/spack/repos/builtin/packages/squashfs/package.py
```

But the Github action is failing.

2020-07-30 07:44 UTC, haampie commented
Ok, CI runs properly after squashing the commits and force pushing.

2020-07-31 03:01 UTC, adamjstewart approved these changes

2020-07-31 03:01 UTC, merged