Buildcache create: change overwrite exception back to a warning as in v0.14
LLNL/spack pull request #17832
Opened 2020-08-01 15:58 UTC by gartung

2020-08-01 16:38 UTC, adamjstewart commented on lib/spack/spack/cmd/buildcache.py
> +            pass
```suggestion
            tty.warn(e)
```
This should be equivalent.

2020-08-02 05:13 UTC, tgamblin requested changes

2020-08-02 05:13 UTC, tgamblin commented on lib/spack/spack/cmd/buildcache.py
> +        except Exception as e:
can this be made more specific?

2020-08-02 14:16 UTC, gartung commented on lib/spack/spack/cmd/buildcache.py
> +        except Exception as e:
Changed to NoOverwriteException

2020-08-02 18:55 UTC, tgamblin approved these changes

2020-08-02 18:56 UTC, tgamblin commented
Still failing on `flake8` because `NoOverwriteException` isn't imported

2020-08-02 20:52 UTC, merged