openfoam-org: support aarch64 platform
LLNL/spack pull request #17906
Opened 2020-08-06 05:51 UTC by darmac

`openfoam-org` cannot support aarch64 now,
so we added a patch for aarch64-patch and create an issue for upstream:
https://github.com/OpenFOAM/OpenFOAM-7/issues/1

2020-08-09 19:03 UTC, adamjstewart commented
@olesenm can you review this PR?

2020-08-10 09:36 UTC, olesenm commented
I don't think that this should be patched with a file. The change set corresponds to a git commit from their repository
Eg,
```
    patch('https://github.com/OpenFOAM/OpenFOAM-dev/commit/ed9e420ea1f1926115a8b93c10266cb80b05a58d',
          when='@7 target=aarch64:',
          sha256='....'
         )
```
This is how I patched openfoam-1806 for fixing the kahip configuration. This approach saves us having tons of patch files cluttering up things in a few years.

@adamjstewart - the changes themselves are OK, roughly reflects what we put into openfoam-1712 (Dec 2017).

2020-08-10 10:10 UTC, olesenm requested changes
I don't think that this should be patched with a file. The change set corresponds to a git commit from their repository
Eg,

    patch('https://github.com/OpenFOAM/OpenFOAM-dev/commit/ed9e420ea1f1926115a8b93c10266cb80b05a58d',
          when='@7 target=aarch64:',
          sha256='....'
         )

This is how I patched openfoam-1806 for fixing the kahip configuration. This approach saves us having tons of patch files cluttering up things in a few years.

@adamjstewart - the changes themselves are OK, roughly reflects what we put into openfoam-1712 (Dec 2017).

2020-08-10 11:49 UTC, darmac commented
> I don't think that this should be patched with a file. The change set corresponds to a git commit from their repository
Well, looks we should wait for a while and check if upstream receive this patch?

2020-08-11 02:31 UTC, adamjstewart commented
@darmac I think what @olesenm means is that if you change your patch statement to the sample he provided, it should be good to merge. That way we download the patch instead of storing it in the Spack repo.

2020-08-12 06:52 UTC, olesenm commented
@darmac - as @adamjstewart said, it is preferable to downloading the patch instead of storing it in the spack repo.
If you try to get this patched upstream, you stumble into the next dilemma. The patched upstream would then correspond to a different version with a different sha and you would need to update the spack recipe again.

2020-08-12 08:39 UTC, darmac commented
@adamjstewart  @olesenm 
Got it, I'll refine this patch later.

2020-09-24 02:12 UTC, adamjstewart commented
Ping @darmac, is this still a WIP?

2020-09-25 08:26 UTC, darmac commented
@adamjstewart  We found some error by using a url patch, and we have not feedback to `openfoam-org` community yet.

2020-11-03 03:30 UTC, darmac commented
I found `openfoam-8` can support ARM64 now, so we can update the version.
But there is still a issue for `openfoam-8` as below:
```
==> Installing openfoam-org
==> No binary for openfoam-org found: installing from source
==> Using cached archive: /home/xiaojun/spack/var/spack/cache/_source-cache/archive/94/94ba11cbaaa12fbb5b356e01758df403ac8832d69da309a5d79f76f42eb008fc.tar.gz
==> renamed spack-src -> OpenFOAM-8
==> Added file spack-Allwmake
==> Added file README-spack
==> Added file bin/foamEtcFile
==> openfoam-org: Executing phase: 'configure'
==> [2020-11-03-11:00:17.237558] FILTER FILE: etc/bashrc [replacing "^(\s*export\s+WM_COMPILER)=.*$"]
==> [2020-11-03-11:00:17.241145] FILTER FILE: etc/bashrc [replacing "^(\s*export\s+WM_LABEL_SIZE)=.*$"]
==> [2020-11-03-11:00:17.243734] FILTER FILE: etc/bashrc [replacing "^(\s*export\s+WM_PRECISION_OPTION)=.*$"]
==> [2020-11-03-11:00:17.246196] FILTER FILE: etc/bashrc [replacing "^(\s*export\s+WM_COMPILE_OPTION)=.*$"]
==> [2020-11-03-11:00:17.248756] FILTER FILE: etc/bashrc [replacing "^(\s*export\s+WM_MPLIB)=.*$"]
==> [2020-11-03-11:00:17.251205] FILTER FILE: etc/cshrc [replacing "^(\s*setenv\s+WM_COMPILER)\s+.*$"]
==> [2020-11-03-11:00:17.253741] FILTER FILE: etc/cshrc [replacing "^(\s*setenv\s+WM_LABEL_SIZE)\s+.*$"]
==> [2020-11-03-11:00:17.256363] FILTER FILE: etc/cshrc [replacing "^(\s*setenv\s+WM_PRECISION_OPTION)\s+.*$"]
==> [2020-11-03-11:00:17.258892] FILTER FILE: etc/cshrc [replacing "^(\s*setenv\s+WM_COMPILE_OPTION)\s+.*$"]
==> [2020-11-03-11:00:17.261437] FILTER FILE: etc/cshrc [replacing "^(\s*setenv\s+WM_MPLIB)\s+.*$"]
==> openfoam-org: Executing phase: 'build'
==> Error: InstallError: No wmake rule for linuxARM64 Gcc

/home/xiaojun/spack/var/spack/repos/builtin/packages/openfoam-org/package.py:303, in build:
        300        its environment first.
        301        Only build if the compiler is known to be supported.
        302        """
  >>    303        self.foam_arch.has_rule(self.stage.source_path)
        304        self.foam_arch.create_rules(self.stage.source_path, self)
        305
        306        args = []

See build log for details:
  /tmp/root/spack-stage/spack-stage-openfoam-org-8-zj5ojam67uyo7j434msadfkmrvs2b6xz/spack-build-out.txt
```

When `spack` build `openfoam-org@8`, it will check `wmake/rules/linuxARM64Gcc/` dir, but unfortunately, what `openfoam-org` has is a `wmake/rules/linuxArm64Gcc/`, the upper case `ARM` makes it build fail.

I tried move the `wmake/rules/linuxArm64Gcc/` to `wmake/rules/linuxARM64Gcc/` then it will install successfully.

2020-11-03 08:46 UTC, olesenm requested changes
Can likely reduce this patch and drop most (all?) of the following exports:

- export WM_CC
- export WM_CXX
- export WM_CFLAGS
- export WM_CXXFLAGS
- export WM_LDFLAGS

These are normally only used as a hack to pass on values to third-party software builds. Eg, could have `CC="$WM_CXX"  make ...`

However, we do not need to chain off this type of information within spack (it already delivers everything), no need to have these.

2020-11-03 08:52 UTC, olesenm requested changes
I think patching in all of the wmake rules is extremely fragile, and a bit messy.

Would much prefer if this could be handled directly within the packages.py instead. Please take a look at the `make_fujitsu` method in the openfoam/packages.py file for an example approach. 
In your case, this is even simpler. Check for existence/non-existence of linuxArm64 and linuxARM64 respectively, and then copy_tree or make a symlink. 

Could probably call this `fix_wmake_rules` and call it regardless of the current architecture

2020-11-03 08:54 UTC, olesenm requested changes

2020-11-03 08:54 UTC, olesenm commented on var/spack/repos/builtin/packages/openfoam-org/70-linuxARM64Gcc.patch
> ++        export WM_CC='gcc'
strip out - more comment in main discussion

2020-11-03 08:54 UTC, olesenm commented on var/spack/repos/builtin/packages/openfoam-org/70-linuxARM64Gcc.patch
> ++++ OpenFOAM-7-new/wmake/rules/linuxARM64Gcc/c	2020-07-29 02:42:21.460000000 +0000
symlink or copy_tree within package.py - see comment in main discussion

2020-11-03 10:56 UTC, darmac commented
I think we should not supply any patch to `openfoam-org`, we can just change `spack` code to fix the build issue:
```
[root@Estuary-CentOS8 packages]# git diff openfoam/package.py
diff --git a/var/spack/repos/builtin/packages/openfoam/package.py b/var/spack/repos/builtin/packages/openfoam/package.py
index 8947decc1..0910789ae 100644
--- a/var/spack/repos/builtin/packages/openfoam/package.py
+++ b/var/spack/repos/builtin/packages/openfoam/package.py
@@ -892,7 +892,7 @@ def __init__(self, spec, **kwargs):
             elif target == 'armv7l':
                 platform += 'ARM7'
             elif target == 'aarch64':
-                platform += 'ARM64'
+                platform += 'Arm64'
             elif target == 'ppc64':
                 platform += 'PPC64'
             elif target == 'ppc64le':
```

2020-11-03 13:30 UTC, olesenm commented
> I think we should not supply any patch to `openfoam-org`, we can just change `spack` code to fix the build issue:
> 
> [root@Estuary-CentOS8 packages]# git diff openfoam/package.py
> -                platform += 'ARM64'
> +                platform += 'Arm64'

No, do **not** do that. This will break the openfoam.com (spack openfoam package) in favour of patching up the openfoam.org (spack openfoam-com package).  The openfoam/package.py is filled with numerous commonly used routines (which is why it is much larger than the openfoam-org package). 

- Dec-2017 :  `ARM64` support was added to openfoam.com (for the v1712 release)
- Jan-2018 : added support for ARM64 to the spack package.
- Jun-2020 : `Arm64` support was added to openfoam.org

I don't know why they (openfoam.org) decided for "Arm64" instead of "ARM64" - maybe they didn't want to look like they were copying from the openfoam.com, maybe they just don't care about people who need to package things. In any case, I see no justification in breaking things after 2-1/2 to accommodate their choices.

2020-11-04 01:16 UTC, darmac commented
So, how about we copy the `Arm64` to `ARM64` in spack `openfoam-org` package (only at version 8 and arm64 platform)?

2020-11-04 16:07 UTC, olesenm commented
> So, how about we copy the `Arm64` to `ARM64` in spack `openfoam-org` package (only at version 8 and arm64 platform)?

This is close to what I had suggested. Make a **symlink** (not a copy) from `ARM64` to `Arm64` the _openfoam-org_ package. This is a cheap operation - can do it for any/all versions that have wmake linuxArm64xxx directories.

2020-11-04 16:11 UTC, olesenm commented
@darmac 
just looked at the settings in their code base. Not really consist naming I'd say:

- aarch64 : WM_ARCH=linuxArm64
- armv7l : WM_ARCH=linuxARM7

2020-11-05 06:09 UTC, t-nojiri commented
My following fix was incorrect.
https://github.com/spack/spack/pull/19622

Please wait for a while as I will redo the fix.

2020-11-05 06:35 UTC, t-nojiri commented
I fixed it again with the following pull request.
https://github.com/spack/spack/pull/19743

2020-11-05 10:54 UTC, darmac commented
> I fixed it again with the following pull request.
> #19743

Thanks for your help, so we can just waiting your patch and then close this PR?

2020-11-09 02:26 UTC, closed without merging