ocaml: fix assembler to use spack_cc
LLNL/spack pull request #17918
Opened 2020-08-07 01:55 UTC by ketsubouchi

Patch assembler setting to use `speck_cc`.

This patch is for aarch64-fj only.
However, similar patch is probably needed for other architectue/compiler.
From `configure`
>   amd64,*|arm,*|arm64,*|i386,*) :
    default_as="${toolpref}as"
    case $ocaml_cv_cc_vendor in #(
  clang-*) :
    default_aspp="${toolpref}clang -c -Wno-trigraphs" ;; #( // I patched this line
  *) :
    default_aspp="${toolpref}gcc -c" ;;

2020-08-09 13:11 UTC, alalazo commented
@scemama

2020-08-09 21:38 UTC, scemama requested changes
I can't test because I don't have access to the compiler, but I have a comment:
The `-Wno-trigraphs` option of Clang is to remove warnings. It would be safer to use spack_cc without the `-Wno-trigraphs` option because it might not be recognized by all compilers, and if spack_cc is Clang, then there will be no harm.

2020-08-09 21:57 UTC, scemama commented
Thanks for the patch!
Are you aware of this discussion:
https://github.com/ocaml/ocaml/pull/9437
?
I think it is not really related to the architecture, but more to the operating system (Linux vs FreeBSD). Are you sure that your patch is not specific to your particular environment? My doubt is on the filter of the spec that could be wrong if the problem depends on the OS and not on the architecture.

2020-08-11 00:06 UTC, ketsubouchi commented
Sorry, I can not access our system and update the patch this week due to summer vacation.

1. spack_cc without the '-Wno-trigraphs' seems safer.
2. `default_as` should be override
3. `default_as` and `default_aspp` is switched by architecture, OS, and CC type
Fujitsu compiler on spack is only available in arm64-linux now. So no problem in `%fj` now.
However, such as `gcc@(older version)` may be problem. More patch is needed.

2020-08-12 00:04 UTC, scemama commented
OK, so I guess you can leave the `%fj` as it is for now, and add a comment next to it to refer to this discussion for the next contributor.

2020-08-17 02:05 UTC, ketsubouchi commented
I removed  '-Wno-trigraphs' and add comments.
Patch to default_as is not needed.(if patch, build failed)

2020-08-17 10:53 UTC, scemama approved these changes

2020-08-18 07:50 UTC, scemama commented
@alalazo We can merge, but the merging is blocked because of +0.16% in codecov.

2020-08-18 07:51 UTC, scemama approved these changes

2020-08-18 09:47 UTC, alalazo commented
> We can merge, but the merging is blocked because of +0.16% in codecov.

I'll go on merging. The merging is not blocked on codecov (which sometimes gives false negatives), it's blocked on a missing approving reviewer.

2020-08-18 09:48 UTC, alalazo approved these changes

2020-08-18 09:49 UTC, merged