Dakota: update versions, add hdf5 support, define supported boost versions
LLNL/spack pull request #18020
Opened 2020-08-12 15:37 UTC by liphardt

2020-08-23 03:22 UTC, adamjstewart requested changes

2020-08-23 03:22 UTC, adamjstewart commented on var/spack/repos/builtin/packages/dakota/package.py
>      version('6.9', sha256='ede7149843707f4b07e76aae27e6a6826734131938da8a6c1b7ed11865c7ee84', url='https://dakota.sandia.gov/sites/default/files/distributions/public/dakota-6.9-release-public-src.zip
I would update the `url` at the package-level, then you can specify a url for `6.3` and no other version.

2020-08-23 03:22 UTC, adamjstewart commented on var/spack/repos/builtin/packages/dakota/package.py
>      depends_on('boost')
```suggestion
    depends_on('boost@:1.69')
```

2020-08-23 03:22 UTC, adamjstewart commented on var/spack/repos/builtin/packages/dakota/package.py
> +            args.extend(['DAKOTA_HAVE_HDF5:BOOL=ON'])
```suggestion
            args.append('DAKOTA_HAVE_HDF5:BOOL=ON')
```
Can you explicitly disable this in an else clause?

2020-12-07 22:42 UTC, adamjstewart commented
Why did you remove dakota?

2020-12-07 22:49 UTC, liphardt commented
@adamjstewart I'm sorry. Because I messed up.

2020-12-11 19:21 UTC, liphardt commented on var/spack/repos/builtin/packages/dakota/package.py
>      version('6.9', sha256='ede7149843707f4b07e76aae27e6a6826734131938da8a6c1b7ed11865c7ee84', url='https://dakota.sandia.gov/sites/default/files/distributions/public/dakota-6.9-release-public-src.zip
I fixed the `url` at the package level so I am only defining it for `6.3`

2020-12-11 19:21 UTC, liphardt commented on var/spack/repos/builtin/packages/dakota/package.py
>      depends_on('boost')
I incorporated this suggestion.

2020-12-11 19:23 UTC, liphardt commented on var/spack/repos/builtin/packages/dakota/package.py
> +            args.extend(['DAKOTA_HAVE_HDF5:BOOL=ON'])
I explicitly disabled this in an else clause with the same syntax as shared libraries.

2020-12-11 19:26 UTC, liphardt commented
@adamjstewart Sorry about the git mess up previously. In order to get the old 6.3 version to build correctly I had to change the python version based on whether we were building 6.3 or >=6.8 and add a conflict for MPI.

2020-12-11 19:30 UTC, adamjstewart commented on var/spack/repos/builtin/packages/dakota/package.py
> +    depends_on('python@:2', when='@:6.8')
Version ranges are inclusive, so this will require both Python 2 and 3 for 6.8, which isn't possible.

2021-02-19 10:38 UTC, alalazo commented
@liphardt

2021-06-12 09:38 UTC, alalazo commented
Closing as stale, but feel free to reopen if you want to continue working on this.

2021-06-12 09:38 UTC, closed without merging