fujitsu: added new package
LLNL/spack pull request #18021
Opened 2020-08-12 15:48 UTC by alalazo

The package provides proprietary Fujitsu compilers. At at the moment it's not installable, just detectable.

2020-08-12 15:49 UTC, alalazo commented
@tkameyama Can you please check this draft package? It's in preparation for a change that will happen in the future where we'll turn compilers like `%fj` into proper dependencies. The functionality added here should be enough to generate appropriate entries in `packages.yaml` if the command:
```console
$ spack external find fj
```
is run. Feel free to ping me with any question you might have related to this.

2020-08-13 02:02 UTC, takahiroogura commented
Please wait a moment as we will review this.
In order to support the Fujitsu cross compiler, the concretizer function and hardware.yaml are required. So our review will be scope only the native compiler. In the future, I think it will be necessary to include architecture information in this package with consideration with cross compilation.

2020-09-02 09:28 UTC, tkameyama requested changes

2020-09-02 09:28 UTC, tkameyama commented on var/spack/repos/builtin/packages/fj/package.py
> +    homepage = "https://www.fujitsu.com/global/Images/openmp-compiler-datasheet-v5.pdf"
```suggestion
    homepage = "https://www.fujitsu.com/global/us"
```
The pdf file is too old, but description of Fujitsu compiler is not found yet in Fujitsu web page...

2020-09-02 09:28 UTC, tkameyama commented on var/spack/repos/builtin/packages/fj/package.py
> +    executables = ['fcc', 'FCC', 'frt']
```suggestion
    executables = ['^fcc', '^FCC', '^frt']
```
Fujitsu MPI has mpifcc, mpiFCC and mpifrt as compiler wrapper.

2020-09-02 09:28 UTC, tkameyama commented on var/spack/repos/builtin/packages/fj/package.py
> +        version_regex = re.compile(r'\((?:FCC|FRT)\) ([\d.]+)')
```suggestion
        version_regex = re.compile(r'\((?:FCC|FRT)\) ([a-z\d.]+)')
```
Version_regex is changed to #17890

2020-09-02 13:59 UTC, alalazo commented
@tkameyama Suggestions applied, thanks!

2020-09-04 01:27 UTC, tkameyama approved these changes

2020-09-05 08:40 UTC, alalazo commented
Thanks for the review!

2020-09-05 08:40 UTC, merged