Added optimized version of Blis, FFTW and Libflame for AMD
LLNL/spack pull request #18155
Opened 2020-08-18 16:06 UTC by vkallesh

Incorporated spack community review comments

Review - https://github.com/spack/spack/pull/17392

amdblis:
    Removed function which invokes explicity make check

amdfftw:
    Rephrased spack product description
    Removed duplicate function used in base fftw

amdlibflame:
    Rephrased spack product description.
    Factor the differences under configure function with spack super function.

2020-08-21 22:39 UTC, adamjstewart requested changes

2020-08-21 22:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/amdfftw/package.py
> +            '--enable-avx2',
These 3 flags might depend on the hardware you are compiling on. It might be better to leave them out and let Spack's microarch support add the optimal flags on its own.

2020-08-21 22:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/fftw/package.py
> +                    raise InstallError("Apple's clang does not support OpenMP")
Remove this, add back the `conflicts` above

2020-08-21 22:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/amdfftw/package.py
> +                    raise InstallError("Apple's clang does not support OpenMP")
This should be converted to a `conflicts` statement

2020-08-21 22:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/amdfftw/package.py
> +            options.append("--enable-single")
Can these be explicitly disabled in an else clause?

2020-08-21 22:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/amdlibflame/package.py
> +        make()
This isn't needed, it's already run during the `build` phase

2020-08-21 22:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/amdfftw/package.py
> +            opts = (enable_precision[precision] or []) + options[:]
Does the `[:]` here actually do anything? I think it just makes a copy of the list, but I'm not sure if that's necessary.

2020-08-21 22:41 UTC, adamjstewart commented
Flake8:
```
var/spack/repos/builtin/packages/amdfftw/package.py:6: [F401] 'os.path' imported but unused
var/spack/repos/builtin/packages/amdfftw/package.py:7: [F401] 'llnl.util.lang' imported but unused
var/spack/repos/builtin/packages/amdfftw/package.py:34: [E303] too many blank lines (2)
var/spack/repos/builtin/packages/amdfftw/package.py:35: [W293] blank line contains whitespace
var/spack/repos/builtin/packages/amdfftw/package.py:44: [W191] indentation contains tabs
var/spack/repos/builtin/packages/amdfftw/package.py:44: [E101] indentation contains mixed spaces and tabs
var/spack/repos/builtin/packages/amdlibflame/package.py:41: [E303] too many blank lines (2)
var/spack/repos/builtin/packages/fftw/package.py:11: [E302] expected 2 blank lines, found 1
var/spack/repos/builtin/packages/fftw/package.py:188: [E302] expected 2 blank lines, found 1
var/spack/repos/builtin/packages/libflame/package.py:110: [E302] expected 2 blank lines, found 1
```

2020-10-22 00:39 UTC, closed without merging

2020-10-22 00:43 UTC, vkallesh commented
AMD's AOCC compiler is now added SPACK community (#19345).
Will be raising another pull request for AMD libraries with AOCC compiler support.