microarchitectures: Fix icelake
LLNL/spack pull request #18151
Opened 2020-08-18 13:42 UTC by michaelkuhn

Some of the feature flags are named differently and clwb is missing on my i7-1065G7. cascadelake and cannonlake might have similar problems but I do not have access to those architectures to test.

2020-08-18 13:58 UTC, alalazo requested changes
Can you please add a unit test by:

- Adding a sample of `/proc/cpuinfo` to `/lib/spack/test/data/targets`
- Adding the corresponding parameter to `lib/spack/test/llnl/util/cpu.py`

? Bonus if you can replicate the PR in the archspec repositories:

- https://github.com/archspec/archspec-json
- https://github.com/archspec/archspec

Thanks!

2020-08-19 08:49 UTC, michaelkuhn commented
I pushed a new version with the sample data and test. Hope that covers everything. Once this PR is merged, I will also open PRs in the archspec repositories.

2020-08-19 09:49 UTC, alalazo approved these changes

2020-08-19 09:49 UTC, merged

2020-08-19 09:50 UTC, alalazo commented
Thanks!