mvapich2: Adding external find support.
LLNL/spack pull request #18177
Opened 2020-08-19 18:26 UTC by rblake-llnl

This picks up all the options that are currently settable by
the spack package. It also detects the compiler and sets it
appropriately.

2020-08-20 22:09 UTC, adamjstewart commented
@nithintsk @harisubramoni can you review this PR? The changes in this PR allows users to run `spack external find mvapich2` and have Spack automatically populate `packages.yaml` with external mvapich2 installations.

2020-08-25 00:23 UTC, nithintsk requested changes
I have noticed some details that might need edits. Do let me know what you think.

2020-08-25 00:23 UTC, nithintsk commented on var/spack/repos/builtin/packages/mvapich2/package.py
> +                variants += " +threads=" + match.group(1)
The + symbols next to threads can be avoided, I believe.

2020-08-25 00:23 UTC, nithintsk commented on var/spack/repos/builtin/packages/mvapich2/package.py
> +                'nemesistcpib': 'ch3:nemesis:tcp:ib',
The last colon for the below two symbols might have to be a comma, when comparing with the current package.py file
```
ch3:nemesis:tcp:ib --> ch3:nemesis:tcp,ib
ch3:nemesis:ib:tcp --> ch3:nemesis:ib,tcp
```
```
        elif 'fabrics=nemesistcpib' in self.spec:
            opts = ["--with-device=ch3:nemesis:tcp,ib"]
        elif 'fabrics=nemesisibtcp' in self.spec:
            opts = ["--with-device=ch3:nemesis:ib,tcp"]
```

2020-08-25 00:32 UTC, rblake-llnl commented
@nithintsk Added your changes.  Thanks!

2020-08-25 01:52 UTC, nithintsk approved these changes
Thanks for making the changes. Looks good to me.

2020-08-25 01:53 UTC, adamjstewart approved these changes

2020-08-25 01:53 UTC, merged