new package/py deap
LLNL/spack pull request #18378
Opened 2020-08-29 05:02 UTC by Sinan81

2020-08-29 05:03 UTC, Sinan81 commented
related to #12233

2020-08-29 21:02 UTC, adamjstewart requested changes

2020-08-29 21:02 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-deap/package.py
> +    depends_on('py-setuptools', type='build')
Missing dep:
```python
         install_requires=['numpy'],                                            
```

2020-08-30 15:44 UTC, adamjstewart approved these changes

2020-08-30 15:44 UTC, merged