new package: py-planet
LLNL/spack pull request #18377
Opened 2020-08-29 05:00 UTC by Sinan81

2020-08-29 05:03 UTC, Sinan81 commented
related to #12233

2020-08-29 21:03 UTC, adamjstewart requested changes

2020-08-29 21:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-planet/package.py
> +    depends_on('py-requests')
Missing dep:
```python
          'requests_futures == 0.9.7',                                          
```
Also, need to be type=build/run

2020-08-30 15:45 UTC, adamjstewart approved these changes

2020-08-30 15:45 UTC, merged