new package: py-gitpython
LLNL/spack pull request #18387
Opened 2020-08-29 06:38 UTC by Sinan81

Related to #12233 
depends on #18386

2020-08-29 20:44 UTC, adamjstewart requested changes

2020-08-29 20:44 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-gitpython/package.py
> +    depends_on('py-gitdb',      type=('build', 'run'))
```suggestion
    depends_on('py-gitdb@4.0.1:4.999', type=('build', 'run'))
```

2020-08-30 15:39 UTC, adamjstewart approved these changes

2020-09-29 01:41 UTC, Sinan81 commented
Can this be merged?

2020-09-29 16:19 UTC, merged