Package/py python fmask
LLNL/spack pull request #18382
Opened 2020-08-29 05:51 UTC by Sinan81

related to #12233

2020-08-29 05:52 UTC, Sinan81 commented
depends on #18381

2020-08-29 20:53 UTC, adamjstewart requested changes

2020-08-29 20:53 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-python-fmask/package.py
> +    depends_on('python@2.7:2.8,3.4:', type=('build', 'run'))
Missing dependency on `gdal+python`. Not sure why their deps are so poorly documented...

2020-08-30 15:42 UTC, adamjstewart approved these changes

2020-09-02 15:29 UTC, merged