Spec: fix multiple generator iteration in satisfies_dependencies (#18527)
LLNL/spack pull request #18559
Opened 2020-09-08 04:00 UTC by omor1

A saved instanced of `self.traverse()` was iterated multiple times, resulting in incorrect behavior, particularly around database searches. We should ensure that this fix doesn't break other use cases of `Spec.satisfies_dependencies` or `Spec.satisfies`.

Fixes #18527.

2020-09-08 06:23 UTC, alalazo requested changes
Can you add a unit test to prevent future regressions?

2020-09-08 16:03 UTC, omor1 commented
@alalazo that would be in `lib/spack/spack/test/spec_semantics.py`?

2020-09-08 16:25 UTC, alalazo commented
@omor1 Yes, that would be a good place to add the test - thanks! You can add it at the bottom, and mark it like:
```python
@pytest.mark.regression('18527')
def test_somename():
```

2020-09-08 21:12 UTC, omor1 commented
Do the packages specified by the spec need to be 'real' (in the sense of existing in `builtin.mock`)? Actually triggering this bug is a bit difficult, as it a) requires multiple dependencies and b) requires that the second dependency of the constraint be ordered after its location in the list of dependencies of the spec. If I can just make up package names it will be easier to ensure the spec and constraint are ordered correctly.

2020-09-08 22:18 UTC, omor1 commented
@alalazo I'm currently using `Spec._add_dependency` in the test to ensure ordering is correct, let me know if there's a better way of achieving the required goal.

2020-10-08 22:27 UTC, adamjstewart commented
Ping @alalazo @scheibelp

2020-10-08 22:35 UTC, omor1 commented
Alternatively we can save it as a `list`. I don't know if that's a better solution:
```Python
selfdeps = list(self.traverse(root=False))
otherdeps = list(other.traverse(root=False))
if not all(any(d.satisfies(dep, strict=True) for d in selfdeps)
    for dep in otherdeps):
```

2020-10-13 08:59 UTC, alalazo commented
@omor1 The test looks fine and in case can be improved in the future. I find saving to a list slightly more readable, so I'd go with that. Ping me after you've done this last change and I'll merge. Sorry this PR fell off my radar!

2020-10-16 23:59 UTC, omor1 commented
@alalazo done

2020-10-17 09:40 UTC, alalazo approved these changes

2020-10-17 09:40 UTC, merged

2020-10-17 09:40 UTC, alalazo commented
Thanks @omor1 !