iwyu: Add llvm +all_targets variant for non-x86_64.
LLNL/spack pull request #18710
Opened 2020-09-17 08:36 UTC by tkameyama

iwyu use X86AsmParser in llvm.
But this is not found to build llvm on non-x86 host.
This PR add +all_target variant to llvm.

2020-09-17 16:39 UTC, adamjstewart approved these changes
@sethrj can you review?

2020-09-17 17:42 UTC, sethrj requested changes
This change is too restrictive: `iwyu` works when `~all_targets` as long as the architecture is based on `x86_64`, so we don't want to exclude that use case. @alalazo this is a sort of micro-architecture related-question: can the necessary change be phrased as
```python
conflicts(`llvm ~all_targets target=arm`)
...
```
and iterate over all non-x86 processor types? Or is there a better way to do this?

2020-09-18 01:38 UTC, tkameyama commented
> 
> 
> This change is too restrictive: `iwyu` works when `~all_targets` as long as the architecture is based on `x86_64`, so we don't want to exclude that use case. @alalazo this is a sort of micro-architecture related-question: can the necessary change be phrased as
> 
> ```python
> conflicts(`llvm ~all_targets target=arm`)
> ...
> ```
> 
> and iterate over all non-x86 processor types? Or is there a better way to do this?

fixed.
I Add `depends_on` insted of `conflicts`

2020-09-18 14:28 UTC, sethrj approved these changes
Excellent, thanks for the change!

2020-09-18 14:31 UTC, merged