Add new package: byteman
LLNL/spack pull request #18736
Opened 2020-09-18 09:25 UTC by darmac

2020-09-18 21:49 UTC, michaelkuhn requested changes
What about the dependencies? The website mentions this needs a JDK.

2020-09-24 02:04 UTC, adamjstewart approved these changes

2020-09-30 07:18 UTC, darmac commented
> What about the dependencies? ~The website mentions this needs a JDK.~ Looks like the JDK is implied by `MavenPackage`. The repository lists additional external dependencies, though. Do we need to add them?

@michaelkuhn 
`MavenPackage` depends on `Maven` and `Java` by default. And if there is any more dependents, it will appear in `pom.xml`'s requirement block or `readme` doc.

So I thinks there is no more dependents for this package.

2020-10-13 12:14 UTC, darmac commented
@michaelkuhn  @adamjstewart  Is there anything need to modify for this package?

2020-10-13 12:19 UTC, michaelkuhn approved these changes

2020-10-13 12:19 UTC, merged