Add new package: acpica-tools
LLNL/spack pull request #18739
Opened 2020-09-18 10:16 UTC by darmac

2020-09-18 21:47 UTC, michaelkuhn requested changes
https://github.com/ahs3/acpica-tools/blob/master/debian/control lists flex and bison as dependencies. Please check whether they are necessary here as well.

2020-10-20 14:10 UTC, michaelkuhn commented
When trying to build it, there is the following output:
```
-  m4           Preprocess main iASL parser
```
So, do we need m4 as well?

2020-10-23 02:47 UTC, darmac commented
> When trying to build it, there is the following output:
> 
> ```
> -  m4           Preprocess main iASL parser
> ```
> 
> So, do we need m4 as well?

I found that in `source/compiler/readme`:
```

1a) Notes for Linux/Unix generation
-----------------------------------

iASL has been generated with these versions of Flex/Bison:

    flex:  Version 2.5.32
    bison: Version 2.6.2

Other required packages:

    make
    gcc C compiler
    m4 (macro processor required by bison)
```

So I think `m4` is just a dependency of bison , it's no need to add in `dovecot` package.

And you can also found `bison` already depends on `m4` as here:
```
depends_on('m4', type=('build', 'run'))
```

2020-10-23 07:23 UTC, michaelkuhn approved these changes

2020-10-23 08:17 UTC, merged