Add new package: junit4
LLNL/spack pull request #18769
Opened 2020-09-19 07:39 UTC by darmac

2020-09-24 01:53 UTC, adamjstewart requested changes

2020-09-24 01:53 UTC, adamjstewart commented on var/spack/repos/builtin/packages/junit4/package.py
> +    depends_on('maven@3.0.4')
```suggestion
    depends_on('java@5:', type=('build', 'run'))
    depends_on('maven@3.0.4:', type='build')
```

2020-10-19 03:58 UTC, adamjstewart approved these changes

2020-10-19 08:10 UTC, alalazo approved these changes

2020-10-19 08:11 UTC, merged