Add new package: dovecot
LLNL/spack pull request #18775
Opened 2020-09-19 08:44 UTC by darmac

2020-09-19 12:54 UTC, michaelkuhn requested changes
If we use the proper release tarballs, we can get rid of the autotools dependencies.

Also, according to https://wiki2.dovecot.org/CompilingSource, Dovecot probably needs at least OpenSSL and has some more optional dependencies.

2020-09-24 01:49 UTC, adamjstewart commented
Can you add the missing dependencies?

2020-10-19 08:10 UTC, darmac commented
> Can you add the missing dependencies?

I added those dependencies:
```
    depends_on('pkg-config', type='build')
    depends_on('gettext',    type='build')
    depends_on('pandoc',     type='build')
```

But `pandoc` build fail because `texlive` build failed.
```
==> [2020-10-19-14:23:50.999527] '/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/texlive-20200406-gzo55ewgkzkkaeowcehiyep4kixfjbfv/bin/aarch64-linux/mtxrun' '--generate'
/usr/bin/env: 'texlua': No such file or directory
==> Error: ProcessError: Command exited with status 127:
    '/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/texlive-20200406-gzo55ewgkzkkaeowcehiyep4kixfjbfv/bin/aarch64-linux/mtxrun' '--generate'

1 error found in build log:
     41583    fmtutil [INFO]: /home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.1/texlive-20200406
              -gzo55ewgkzkkaeowcehiyep4kixfjbfv/texmf-var/web2c/tex/lollipop.fmt installed.
     41584    fmtutil [INFO]: disabled formats: 5
     41585    fmtutil [INFO]: successfully rebuilt formats: 55
     41586    fmtutil [INFO]: total formats: 60
     41587    fmtutil [INFO]: exiting with status 0
     41588    ==> [2020-10-19-14:23:50.999527] '/home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.2.
              1/texlive-20200406-gzo55ewgkzkkaeowcehiyep4kixfjbfv/bin/aarch64-linux/mtxrun' '--generate'
  >> 41589    /usr/bin/env: 'texlua': No such file or directory

See build log for details:
  /tmp/root/spack-stage/spack-stage-texlive-20200406-gzo55ewgkzkkaeowcehiyep4kixfjbfv/spack-build-out.txt

==> Warning: Skipping build of pandoc since texlive failed
==> Warning: Skipping build of dovecot since pandoc failed
==> Error: Installation of dovecot failed.  Review log for details
```

2020-10-19 15:16 UTC, adamjstewart commented
In that case, you should still add the dependencies so this can be merged, but you can open a separate issue to try to figure out how to solve the texlive build issue.

2020-11-03 11:34 UTC, darmac commented
I opened an issue for `texlive`, https://github.com/spack/spack/issues/19704
I'll keep testing this patch after this issue be fixed.

2020-11-15 09:55 UTC, michaelkuhn commented
How about adding a `doc` variant (that defaults to `False`) so we can get rid of the `pandoc`/`texlive` dependencies by default? I guess `pandoc` is only required for building the documentation?

2021-01-03 07:19 UTC, darmac commented
Updated in https://github.com/spack/spack/pull/18775/commits/3257ca591e9c4dba3b0691cb12a2511499479290

2021-01-03 17:19 UTC, adamjstewart commented on var/spack/repos/builtin/packages/dovecot/package.py
> +    depends_on('pkg-config', type='build')
```suggestion
    depends_on('pkgconfig', type='build')
```
We have a virtual package for this

2021-01-04 03:57 UTC, adamjstewart approved these changes

2021-01-04 09:24 UTC, michaelkuhn commented
I still think we should add an OpenSSL dependency. Otherwise, I am not sure how useful this is. Would you use a mail server without encryption? From a quick test, adding `depends_on('openssl')` seems to be enough.

2021-02-19 12:57 UTC, alalazo commented
@darmac Can you address https://github.com/spack/spack/pull/18775#issuecomment-753861905 ?

2021-06-12 10:48 UTC, alalazo commented
Closing as stale

2021-06-12 10:48 UTC, closed without merging