ROCm 3.8 Stage1 Components
LLNL/spack pull request #18830
Opened 2020-09-21 08:10 UTC by gkathirv

2020-09-21 08:19 UTC, gkathirv commented
@adamjstewart @srekolam @arjun-raj-kuppala

2020-09-21 15:25 UTC, adamjstewart approved these changes
@haampie may also be interested in reviewing this.

2020-09-21 15:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/hip/package.py
> +        if name == 'cxxflags' and not ('@3.5.0' in self.spec):
You could also use:
```suggestion
        if name == 'cxxflags' and '@3.7.0:' in self.spec:
```
The trailing colon means an open-ended version range.

2020-09-21 15:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/hsa-rocr-dev/package.py
> +        if not ('@3.5.0' in self.spec):
Same here

2020-09-21 20:04 UTC, srekolam requested changes
verify that 3.5.0 ,3.7.0 also builds

2020-09-21 20:04 UTC, srekolam commented on var/spack/repos/builtin/packages/rocclr/package.py
>      depends_on('cmake@3:', type='build')
can you make the link dependency for numactl for 3.7.0:   That way it is not required for 3.5.0, same for libelf

2020-09-21 20:04 UTC, srekolam commented on var/spack/repos/builtin/packages/hsa-rocr-dev/package.py
> +        depends_on('llvm-amdgpu@' + ver, type=('link', 'run'), when='@' + ver)
llvm-amdgpu is not required for 3.5.0. it is required from 3.7.0 onwards...

2020-09-22 04:47 UTC, srekolam approved these changes

2020-09-22 16:09 UTC, merged

2020-09-23 08:53 UTC, haampie commented on var/spack/repos/builtin/packages/hsa-rocr-dev/package.py
> +        if '@3.7.0:' in ver:
A bit late to review here, but this looks incorrect... `ver` is just a string here