Add new package: py-coapthon3
LLNL/spack pull request #18990
Opened 2020-09-27 02:30 UTC by darmac

2020-10-08 20:01 UTC, adamjstewart approved these changes

2020-10-08 20:01 UTC, adamjstewart commented
Can you rebase/merge develop to fix the vermin tests?

2020-10-13 14:16 UTC, alalazo requested changes
Can you please double check the version in the comment?

2020-10-13 14:16 UTC, alalazo commented on var/spack/repos/builtin/packages/py-coapthon3/package.py
> +    version('1.01',  sha256='b90a410cf35f18c0fb2620baf44a3283a640d40a299c31c7d184a69c1dbec105')
I would remove this version. It's not listed among the releases (only tags), so I assume it was committed by mistake?

2020-10-19 08:21 UTC, darmac commented on var/spack/repos/builtin/packages/py-coapthon3/package.py
> +    version('1.01',  sha256='b90a410cf35f18c0fb2620baf44a3283a640d40a299c31c7d184a69c1dbec105')
Fixed in https://github.com/spack/spack/pull/18990/commits/45d4588dc189ca628f576a0676e4f01c07d9b0db

2020-10-19 08:26 UTC, alalazo approved these changes

2020-10-19 09:42 UTC, merged