Added slurm version 20-02-4-1 and support to build slurmrestd
LLNL/spack pull request #19249
Opened 2020-10-09 19:52 UTC by bollig

2020-10-09 21:00 UTC, bollig commented
What does this failure mean? Codecov passed on previous attempts. Why would it fail now? How does one fix the macos failures? Looks like an issue with the unittests rather than something caused by the edits.

2020-10-10 21:55 UTC, adamjstewart requested changes

2020-10-10 21:55 UTC, adamjstewart commented on var/spack/repos/builtin/packages/libjwt/package.py
> +        make('install')
This is the default install method, you can remove this

2020-10-10 21:56 UTC, adamjstewart commented
> What does this failure mean? Codecov passed on previous attempts. Why would it fail now? 

See the note at the bottom of https://spack.readthedocs.io/en/latest/contribution_guide.html#coverage

> How does one fix the macos failures? Looks like an issue with the unittests rather than something caused by the edits.

Yes, this is a transient failure. You can reboot the tests by opening and closing the issue, adding a new commit, or asking a maintainer like me to restart the tests for you.

2020-10-12 18:52 UTC, adamjstewart approved these changes

2020-10-12 18:52 UTC, merged