shell support: make `which spack` output intelligible
LLNL/spack pull request #19256
Opened 2020-10-11 06:19 UTC by tgamblin

Zsh and newer versions of bash have a builtin `which` function that will show you if a command is actually an alias or a function. For functions, the entire function is printed, and our `spack()` function is quite long. Instead of printing out all that, make the `spack()` function a wrapper around `_spack()`, and include some no-ops in the definition so that users can see where it was created and where Spack is installed.

Here's what the new output looks like in zsh:

```console
$ which spack
spack () {
	: this is a shell function from: /Users/gamblin2/src/spack/share/spack/setup-env.sh
	: the real spack script is here: /Users/gamblin2/src/spack/bin/spack
	_spack "$@"
	return $?
}
```

Note that `:` is a no-op in Bourne shell; it just discards anything after it on the line. We use it here to embed paths in the function definition (as comments are stripped).

2020-10-11 06:21 UTC, tgamblin commented
@sameershende FYI

2020-10-11 13:55 UTC, adamjstewart approved these changes

2020-10-12 12:05 UTC, alalazo commented
Closed/reopen to get the `mpich` hotfix that was merged for Github's CI

2020-10-12 14:28 UTC, michaelkuhn approved these changes
works for me

2020-10-12 14:39 UTC, alalazo approved these changes
Works for me too on MacOS Catalina

2020-10-12 16:08 UTC, tldahlgren requested changes, later dismissed
Please address the patch coverage failure IF it is real.

2020-10-12 16:08 UTC, tldahlgren commented on share/spack/setup-env.sh
> +eval "spack() {
LGTM.  

If this a *real* lack of coverage issue, please add a test for the `eval` here to get the patch coverage up.

2020-10-22 00:04 UTC, tgamblin commented
Coverage issue here is not real, so I'm going to go ahead and merge.

2020-10-22 00:04 UTC, merged