pexsi: Add -fopenmp flag to fortran flags if dependencies use OpenMP
LLNL/spack pull request #19274
Opened 2020-10-12 17:17 UTC by payerle

See #18578
This patch causes OpenMP flags to be added to fortran compilation
flags if superlu-dist or openblas dependencies use openmp.

2020-10-12 19:10 UTC, adamjstewart requested changes

2020-10-12 19:10 UTC, adamjstewart commented on var/spack/repos/builtin/packages/pexsi/package.py
> +            fldflags += ' -fopenmp'
```suggestion
            fldflags += ' ' + self.compiler.openmp_flag
```
Not all compilers use `-fopenmp`

2020-10-13 16:44 UTC, adamjstewart approved these changes

2020-10-15 13:40 UTC, alalazo approved these changes

2020-10-15 13:41 UTC, merged