Replace Madgraph 2.8.0 -> 2.8.1
LLNL/spack pull request #19400
Opened 2020-10-20 16:31 UTC by iarspider

Split from #19394

2020-10-20 20:01 UTC, adamjstewart requested changes
Can we keep the old version too?

2020-10-21 05:20 UTC, iarspider commented
2.8.0 was removed from launchpad, so I'm not sure it makes sense to keep it.

2020-10-21 15:21 UTC, adamjstewart commented
There may be users who have it cached in their downloads cache and want to reproduce an old installation. Ideally I agree that we should remove it, but until #15896 is resolved we don't have a good procedure to do that.

2020-10-21 15:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/madgraph5amc/package.py
> +    patch('madgraph5amc-2.8.0.atlas.patch', level=0, when='@2.8.1+atlas')
I think we can simplify this patch stuff by removing `@X.Y.Z` from the when args since the patch is always needed for all versions.

2020-10-21 15:58 UTC, adamjstewart approved these changes

2020-10-21 22:13 UTC, merged