Add herwig3
LLNL/spack pull request #19406
Opened 2020-10-20 16:52 UTC by iarspider

Split from #19394

2020-10-20 21:36 UTC, adamjstewart requested changes

2020-10-20 21:36 UTC, adamjstewart commented on var/spack/repos/builtin/packages/herwig3/package.py
> +            url='http://lcgpackages.web.cern.ch/lcgpackages/tarFiles/sources/MCGeneratorsTarFiles/Herwig-7.2.1.tar.bz2')
Why two different URLs?

2020-10-20 21:36 UTC, adamjstewart commented on var/spack/repos/builtin/packages/herwig3/package.py
> +    depends_on('boost', type='build')
If it links to the headers, this should be a `type='link'` dep

2020-10-20 21:36 UTC, adamjstewart commented on var/spack/repos/builtin/packages/herwig3/package.py
> +    depends_on('openloops', type=('build', 'run'))
type=build/run is usually only used for things like Python that don't link to libraries. I assume the default deptype is what you want.

2020-10-20 21:36 UTC, adamjstewart commented on var/spack/repos/builtin/packages/herwig3/package.py
> +        autoreconf('--install', '--verbose', '--force')
Does the default not work?

2020-10-20 21:36 UTC, adamjstewart commented on var/spack/repos/builtin/packages/herwig3/package.py
> +        if self.spec.satisfies('@7.2.0:'):
I think you can get rid of this if statement since all versions satisfy this

2020-10-20 21:36 UTC, adamjstewart commented on var/spack/repos/builtin/packages/herwig3/package.py
> +    # depends_on('gosam', type=('build', 'run'))
Why is this commented out?

2020-10-20 21:36 UTC, adamjstewart commented on var/spack/repos/builtin/packages/herwig3/package.py
> +                make()
These versions don't exist in the package

2020-10-21 05:36 UTC, iarspider commented on var/spack/repos/builtin/packages/herwig3/package.py
> +    # depends_on('gosam', type=('build', 'run'))
Replaced with `when(...)`

2020-10-21 10:56 UTC, iarspider commented
For most Herwig dependencies their type doesn't seem to exactly fit into any of the existing categories (`build`, `link` or `run`, judging by the description in the docs): the build system sets the compile (`-I`) and link (`-L`, `-R`) flags by itself, without relying on things like `(DY)LD_LIBRARY_PATH` or external compiler flags. So, I guess in this case all dependencies should  be maked as `build`, right?

2020-10-21 15:11 UTC, adamjstewart commented
`build` implies that the dependency can be uninstalled after installation, which is not the case for shared library deps. It also implies that the specific compiler/version should not affect concretization, which is not the case with includes. `build` also means that you want to add the `prefix.bin` to the `PATH`, which isn't needed for any of these deps. So I would use `type='link'`, even if the build system happens to be smart.

2020-10-21 15:32 UTC, iarspider commented
> build implies that the dependency can be uninstalled after installation
Maybe mention this in the docs?

2020-10-21 15:37 UTC, adamjstewart commented
From https://spack.readthedocs.io/en/latest/packaging_guide.html#dependency-types:

> One of the advantages of the build dependency type is that although the dependency needs to be installed in order for the package to be built, it can be uninstalled without concern afterwards.

2020-10-21 15:37 UTC, adamjstewart commented on var/spack/repos/builtin/packages/herwig3/package.py
> +        import shutil
Imports should be at the top of the file

2020-10-21 15:42 UTC, adamjstewart approved these changes

2020-10-21 20:40 UTC, iarspider commented
> 
> 
> From https://spack.readthedocs.io/en/latest/packaging_guide.html#dependency-types:
> 
> > One of the advantages of the build dependency type is that although the dependency needs to be installed in order for the package to be built, it can be uninstalled without concern afterwards.

Yup, totally missed that. Sorry!

2020-10-22 15:56 UTC, merged