New package: orc
LLNL/spack pull request #19441
Opened 2020-10-21 14:39 UTC by qwertos

2020-10-21 16:40 UTC, adamjstewart requested changes
Is the third party patch something that would be possible to contribute upstream?

2020-10-21 16:40 UTC, adamjstewart commented on var/spack/repos/builtin/packages/orc/package.py
> +        args.append('-DCMAKE_C_FLAGS=-fPIC')
```suggestion
        args.append('-DCMAKE_CXX_FLAGS=' + self.compiler.cxx_pic_flag)
        args.append('-DCMAKE_C_FLAGS=' + self.compiler.cc_pic_flag)
```

2020-10-21 16:52 UTC, qwertos commented
> 
> 
> Is the third party patch something that would be possible to contribute upstream?

Uh... I don't think so. The purpose of it is to disable their auto building of third party dependencies, forcing it to look for the dependencies elsewhere and error if not found. I'm assuming that auto building of third party dependencies was an intentional choice on their part. 

I could probably remove the patch at this point now that lines 39-41 of package.py are there. It might be a bit safer to leave it though.

2020-10-22 19:05 UTC, adamjstewart approved these changes

2020-10-22 19:05 UTC, merged