py-tomlkit: new package at 0.7.0
LLNL/spack pull request #19450
Opened 2020-10-21 20:27 UTC by codeandkey

2020-10-21 21:55 UTC, adamjstewart requested changes

2020-10-21 21:55 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-tomlkit/package.py
> +    depends_on('py-setuptools', type='build')
Can you also add:
```python
depends_on('py-enum34@1.1:1.999', when='^python@:2', type=('build', 'run'))
depends_on('py-functools32@3.2.3:3.999', when='^python@:2', type=('build', 'run'))
depends_on('py-typing@3.6:3.999', when='^python@:3.4', type=('build', 'run'))
```

2020-10-22 17:34 UTC, codeandkey commented on var/spack/repos/builtin/packages/py-tomlkit/package.py
> +    depends_on('py-setuptools', type='build')
Added!

2020-10-22 19:01 UTC, adamjstewart approved these changes

2020-10-22 19:01 UTC, merged