spack recipe for stream with aocc compiler support
LLNL/spack pull request #19540
Opened 2020-10-27 10:36 UTC by amd-toolchain-support

spack recipe for stream with aocc compiler support and optimization settings for AMD architecture

2020-10-27 14:46 UTC, adamjstewart requested changes

2020-10-27 14:46 UTC, adamjstewart commented on var/spack/repos/builtin/packages/stream/package.py
> +    variant('STREAM_ARRAY_SIZE', default=2500000000, description='Please note that this is system specific setting, please modify it if you want to compile it with different STREAM ARRAY SIZE other t
```suggestion
    variant('STREAM_ARRAY_SIZE', default=2500000000, description='Please note that this is system specific setting, please modify it if you want to compile it with different STREAM ARRAY SIZE other than "2500000000". Currently this variant has effect only with AOCC compiler. General recommendation is that STREAM_ARRAY_SIZE must be at least 4x the size of the sum of all the last-level caches in the system')
```
You may want to break this up on multiple lines as well.

2020-10-27 14:46 UTC, adamjstewart commented on var/spack/repos/builtin/packages/stream/package.py
> +            omp_flag = self.compiler.openmp_flag
Here you are adding the openmp flag regardless of whether `+openmp` or `~openmp` is requested. I think you should remove the openmp logic from this block and keep it in the subsequent block for all compilers.

2020-10-27 14:46 UTC, adamjstewart commented on var/spack/repos/builtin/packages/stream/package.py
> +    variant('STREAM_ARRAY_SIZE', default=2500000000, description='Please note that this is system specific setting, please modify it if you want to compile it with different STREAM ARRAY SIZE other t
I would also make this lowercase to be consistent with other variant names.

2020-12-14 15:23 UTC, closed without merging

2020-12-14 15:25 UTC, amd-toolchain-support commented
With default stream recipe and after passing the flags in the command line, we achieved the desired output.