Keep output machine readable using `spack find --format` in an env
LLNL/spack pull request #19698
Opened 2020-11-03 01:46 UTC by becker33

Currently, full json output is the only machine readable option for `spack find` in an environment.

`spack find --format` is also designed to be machine readable, so we avoid printing portions that are not machine readable when using that option.

2020-11-04 21:33 UTC, tgamblin requested changes
Minor change request

2020-11-04 21:33 UTC, tgamblin commented on lib/spack/spack/cmd/find.py
> +        cmd.display_specs(results, args, decorator=decorator, all_headers=True)
Can you integrate this into the `else:` block below?

Like this:

```python
    else:
        if not args.format:
            if env:
                display_env(env, args, decorator)
            if sys.stdout.isatty() and args.groups:
                tty.msg("%s" % plural(len(results), 'installed package'))
        cmd.display_specs(
            results, args, decorator=decorator, all_headers=True)
```

2020-11-05 18:54 UTC, becker33 commented
@tgamblin done

2020-11-12 06:07 UTC, tgamblin approved these changes

2020-11-12 06:13 UTC, merged