[WIP] Features/parallel relocate
LLNL/spack pull request #19690
Opened 2020-11-02 22:10 UTC by nhanford

Internal PR to my own repo

2021-01-11 19:52 UTC, becker33 requested changes
Two stray commits in addition to needing a new sbang test

2021-01-11 19:52 UTC, becker33 commented on lib/spack/spack/directory_layout.py
> +        self.deploy_file_name    = 'deploy.yaml'
Is this accidentally included from another PR?

2021-01-11 19:52 UTC, becker33 commented on spack.code-workspace
> +}
I think this shouldn't be included in the PR.

2021-01-14 19:19 UTC, eugeneswalker commented
I realize the point of this PR is to parallelize test replacement logic, but I thought it would make sense to note here that `sbang` relocation does not work in the particular case that `install_tree: padded_length:` is set in conjunction with a non-default `install_tree: root:` as of 03f6717c3883b12705a3f3598eb49ce02cecb16c from `2021-01-24`.

This problem is described in Issue https://github.com/spack/spack/issues/20766
One solution to the problem is in PR https://github.com/spack/spack/pull/20768

I'm really, really hoping we can address the sbang issue in some form for the next tag release of Spack, such as `0.16.1`. Whether that is done using my PR, or a better solution proposed by others.

2021-01-20 17:15 UTC, becker33 approved these changes

2021-01-20 17:17 UTC, merged