New package: py-pydmd
LLNL/spack pull request #19809
Opened 2020-11-09 07:03 UTC by a-saitoh-fj

New package: py-pydmd

2020-11-09 22:41 UTC, adamjstewart requested changes

2020-11-09 22:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pydmd/package.py
> +    )
Please remove this. If there's a bug with a dependent package, we can fix that package. This package builds just fine if `py-sphinx-rtd-theme@0.5.0` is built. It builds fine on my laptop for example.

2020-11-09 22:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pydmd/package.py
> +    depends_on('py-sphinx-rtd-theme', type=('build', 'run'), when='+docs')
```suggestion
    depends_on('py-nose', type='test')
    depends_on('py-sphinx@1.4.0:1.4.999', type='build', when='+docs')
    depends_on('py-sphinx-rtd-theme', type='build', when='+docs')
```

2020-11-09 22:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pydmd/package.py
> +    phases = ['build', 'install']
This is already the default, you can remove this

2020-11-09 22:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pydmd/package.py
> +            install_tree('docs', prefix.docs)
I would do this as:
```python
@run_after('build'):
def build_docs(self):
    if '+docs' in self.spec:
        with working_dir('docs'):
            make('html')

@run_after('install')
def install_docs(self):
    if '+docs' in self.spec:
        install_tree('docs', self.prefix.docs)
```
Then you can get the default install args used.

2020-11-09 22:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pydmd/package.py
> +        python('test.py')
```suggestion
    def test(self):
        python('test.py')
```
This will override the default `python setup.py test` call.

2020-11-10 00:27 UTC, a-saitoh-fj commented
Thank you for your advice.
I will check and fix these and then request again.
Please give me some time.

2020-12-22 00:59 UTC, a-saitoh-fj commented
Fixed the problem that was pointed out.

-Removed conflicts processing for py-sphinx-rtd-theme@0.5.0.
-Modify the type set in depends_on.
-Deleted the description of phases.
-Correct the name of the function that installs the document.
-Correct the name of the function that executes the test.

2020-12-22 01:58 UTC, adamjstewart requested changes

2020-12-22 01:58 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pydmd/package.py
> +    import_modules = ['pydmd']
Now that #20023 has been merged, `import_modules` should be auto-detected. You may not need this line anymore.

2020-12-22 01:58 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pydmd/package.py
> +        python('test.py')
Now that #20023 has been merged, `PythonPackage` no longer has a test method. You can either remove this and the test dependencies, or add it explicitly:
```suggestion
    @run_after('build')
    @on_package_attributes(run_tests=True)
    def build_test(self):
        python('test.py')
```

2020-12-25 04:39 UTC, adamjstewart approved these changes

2020-12-25 04:41 UTC, a-saitoh-fj commented
Fixed the issue that was pointed out.
- Since "import_modules" is automatically detected by merging #20023, this description has been deleted.
- Since the test method of PythonPackage has disappeared due to the merge of #20023, I added the test explicitly.

2020-12-25 06:01 UTC, merged