Rocm 3.9.0 hip extra
LLNL/spack pull request #19832
Opened 2020-11-10 01:10 UTC by arjun-raj-kuppala

2020-11-11 06:38 UTC, srekolam commented on var/spack/repos/builtin/packages/hip/package.py
> +                '--rocm-path={}'.format(self.prefix))
--rocm-path={}  -change to --rocm-path={0}.format

2020-11-11 06:39 UTC, srekolam requested changes
i have added a comment for hip package.py,please address it.

2020-11-11 20:09 UTC, srekolam approved these changes

2020-11-12 22:17 UTC, adamjstewart requested changes

2020-11-12 22:17 UTC, adamjstewart commented on var/spack/repos/builtin/packages/hip/package.py
> +                '--rocm-path={}'.format(self.prefix))
```suggestion
                '--rocm-path={0}'.format(self.prefix))
```

2020-11-12 22:19 UTC, adamjstewart approved these changes

2020-11-13 18:24 UTC, arjun-raj-kuppala commented
@adamjstewart Can you help merge this ?

2020-11-13 18:25 UTC, merged