ROCm 3.9 Stage2 recipe
LLNL/spack pull request #19838
Opened 2020-11-10 06:04 UTC by gkathirv

2020-11-10 07:10 UTC, gkathirv commented
@adamjstewart @srekolam @arjun-raj-kuppala

2020-11-10 18:51 UTC, adamjstewart approved these changes

2020-11-11 06:44 UTC, srekolam requested changes
can you update the url for each of the packages where ever applicable..

2020-11-11 16:08 UTC, adamjstewart commented
From Spack's side of things, it doesn't matter which version the URL is for, it will work. So there's really no need to update the URL if you don't want to, but you can if you want.

2020-11-13 04:54 UTC, srekolam approved these changes

2020-11-13 05:04 UTC, merged