Bugfixes for lbann sw stack
LLNL/spack pull request #19903
Opened 2020-11-13 19:43 UTC by bvanessen

Update Aluminum for building without CUDA and DiHydrogen for building with OpenMP on OSX.

2020-11-13 19:54 UTC, adamjstewart reviewed
W.r.t. the macOS Clang OpenMP stuff:

This doesn't make a lot of sense to me. First of all, I think this is specific to `%apple-clang`, I don't think it affects `%clang`. Second, my `clang` is found in `/usr/bin`, but there is no `/usr/lib/libomp.dylib`. I think you want to add a dependency on `llvm-openmp`. See what I did in `py-scikit-learn` for an example.

2020-11-13 19:58 UTC, bvanessen commented
> W.r.t. the macOS Clang OpenMP stuff:
> 
> This doesn't make a lot of sense to me. First of all, I think this is specific to `%apple-clang`, I don't think it affects `%clang`. Second, my `clang` is found in `/usr/bin`, but there is no `/usr/lib/libomp.dylib`. I think you want to add a dependency on `llvm-openmp`. See what I did in `py-scikit-learn` for an example.

I will take a look at `py-scikit-learn`, but I am relying on a `brew` installed clang that has `openmp` support rather than allowing `spack` to install clang.

2020-11-13 20:01 UTC, adamjstewart commented
That's fine, but I don't think it will work for anyone using Apple Clang.

2020-11-14 14:35 UTC, adamjstewart requested changes

2020-11-14 14:35 UTC, adamjstewart commented on var/spack/repos/builtin/packages/aluminum/package.py
>          if '@:0.1,0.6.0:':
This is missing an `in spec` or `spec.satisfies()`. Python strings always evaluate to True if non-empty. You can actually combine this line and the one below it.

2020-11-14 18:22 UTC, adamjstewart approved these changes

2020-11-14 19:05 UTC, bvanessen commented
@adamjstewart Thanks for all of the feedback on how to make LLVM and OpenMP work better with `apple-clang`  as you can see I am trying to incorporate all of your suggestions to the whole LBANN software stack.

2020-11-15 00:59 UTC, merged