Add new package: lz4-java
LLNL/spack pull request #19913
Opened 2020-11-14 07:37 UTC by darmac

2020-11-14 15:46 UTC, adamjstewart requested changes

2020-11-14 15:46 UTC, adamjstewart commented on var/spack/repos/builtin/packages/lz4-java/package.py
> +    depends_on('xxhash', type='build')
If you are linking to these libraries/headers, these should be `type='link'`. If you also need them in `PATH` at build-time, they should be `type=('build', 'link')`.

2021-02-19 13:11 UTC, alalazo commented
@darmac

2021-06-12 10:57 UTC, alalazo commented
Closing as stale. Feel free to reopen if you want to continue working on this.

2021-06-12 10:57 UTC, closed without merging