add new version py-wavelets@1.1.1
LLNL/spack pull request #19930
Opened 2020-11-15 17:54 UTC by healther

2020-11-15 17:56 UTC, adamjstewart requested changes
It looks like the required dependency versions have been updated:
```python
        install_requires=["numpy>=1.13.3"],                                     
        setup_requires=["numpy>=1.13.3"],                                       
        python_requires=">=3.5",    
```
Can you add these?

2020-11-15 19:06 UTC, healther commented
Done, I assumed that we fixed the edge case where the `when` clauses needed to be mutually exclusive, if that's not the case I'd need to add that too

2020-11-15 21:50 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pywavelets/package.py
> +    depends_on('python@3.5:', when='@1.1.1:')
type=build/run

2020-11-16 16:07 UTC, adamjstewart approved these changes

2020-11-16 16:41 UTC, merged