Path utilities: use pwd for usernames on unix
LLNL/spack pull request #19980
Opened 2020-11-18 18:25 UTC by becker33

Fixes #19977 

`getpass.getuser()` does not respect username changes via `ksu`. `pwd.getpwuid(os.getuid())` does.

@nicholas-sly

2020-11-18 19:30 UTC, becker33 commented
The untested lines of code will not be exercised until we start testing on windows, all of our test systems support the python `pwd` module.

2020-11-20 09:12 UTC, tgamblin requested changes
Some feedback. I think this could use a test.

2020-11-20 09:12 UTC, tgamblin commented on lib/spack/spack/util/path.py
> +        return pwd.getpwuid(os.getuid()).pw_name
Two things:

1. This should be outside the try/except, as it's really the import you're checking here.
2. Shouldn't this be `os.geteuid()` for the effective uid? I think this one fails with setuid, doesn't it?

2020-11-20 09:12 UTC, tgamblin commented on lib/spack/spack/util/path.py
> +def get_user():
some comment in the function should explain why we do this (i.e., b/c sudo)

2022-11-08 00:59 UTC, tgamblin submitted a review, later dismissed

2022-11-08 04:46 UTC, becker33 commented
@spackbot fix style

2022-11-08 18:36 UTC, tgamblin approved these changes

2022-11-08 18:36 UTC, merged