docker: adding ubuntu20.10
LLNL/spack pull request #19991
Opened 2020-11-19 00:13 UTC by RikkiButler20

2020-11-19 09:16 UTC, alalazo commented on share/spack/docker/ubuntu-2010.dockerfile
> +FROM ubuntu:20.10
Having a recent Ubuntu is great, thanks! Wondering if we should:
```suggestion
FROM ubuntu:20.04
```
to have all our Spack + Ubuntu images based on LTS.

2020-12-14 19:26 UTC, alalazo requested changes
Can you check if the image builds for you?

2020-12-14 19:26 UTC, alalazo commented on share/spack/docker/ubuntu-2004.dockerfile
> +RUN ln -s posix_c.so /usr/lib/x86_64-linux-gnu/lua/5.2/posix.so
Are you able to build this image? For me it fails with:
```
Step 17/22 : RUN ln -s posix_c.so /usr/lib/x86_64-linux-gnu/lua/5.2/posix.so
 ---> Running in 1fe0af8be2ab
ln: failed to create symbolic link '/usr/lib/x86_64-linux-gnu/lua/5.2/posix.so': File exists
The command '/bin/sh -c ln -s posix_c.so /usr/lib/x86_64-linux-gnu/lua/5.2/posix.so' returned a non-zero code: 1
```
Maybe the bug was specific to Ubuntu 18.04.

2021-09-09 18:17 UTC, vsoch commented
Any updates here? I'd like this added.

2022-01-05 17:35 UTC, tldahlgren commented
@RikkiButler20 Please resolve conflicts.  There are also some questions here.

2022-04-22 06:51 UTC, closed without merging