h5cpp: Correct checksum and build instructions
LLNL/spack pull request #20053
Opened 2020-11-23 17:50 UTC by eschnett

Closes https://github.com/spack/spack/issues/20046.

2020-11-23 18:38 UTC, adamjstewart commented
Any idea why the checksum changed? Is there any way we can verify that the new tarball doesn't contain a virus?

2020-11-23 20:02 UTC, eschnett commented
I don't know why it changed. However, I recall that github repackages (or used to repackage?) the tarfiles from time to time, and that changes the checksums. I don't know whether there is a way to get immutable tarballs.

I notice that some repos have tarballs with a `releases/download` url, while others just have an `archive` url. Maybe there's a difference?

2020-11-24 02:21 UTC, adamjstewart commented
The `archive` tarball is automatically generated, while the `releases/download` tarballs are user generated.

2020-11-24 02:24 UTC, adamjstewart requested changes

2020-11-24 02:24 UTC, adamjstewart commented on var/spack/repos/builtin/packages/h5cpp/package.py
> +                ]
```suggestion
        return [
            '-DHDF5_INCLUDE_DIRS=%s' % self.spec['hdf5'].headers.directories[0],
            '-DHDF5_LIBRARIES=%s' % self.spec['hdf5'].libs.directories[0],
            '-DH5CPP_BUILD_TESTS=OFF',
        ]
```
Libraries may be in `prefix.lib` or `prefix.lib64`.

2020-11-24 17:06 UTC, adamjstewart approved these changes

2020-11-24 17:06 UTC, adamjstewart commented
Flake8:
```
var/spack/repos/builtin/packages/h5cpp/package.py:31: [E501] line too long (80 > 79 characters)
```

2020-11-24 18:17 UTC, eschnett commented
`style and docs` failure is unrelated.

2020-11-24 19:37 UTC, merged