lsdalton: New package.
LLNL/spack pull request #20129
Opened 2020-11-26 22:46 UTC by fcannini

2020-12-25 05:56 UTC, adamjstewart requested changes

2020-12-25 05:56 UTC, adamjstewart commented on var/spack/repos/builtin/packages/lsdalton/package.py
> +                    spec['mpi'].prefix.bin.mpif90),
```suggestion
                    spec['mpi'].mpicc),
                '-DCMAKE_CXX_COMPILER={0}'.format(
                    spec['mpi'].mpicxx),
                '-DCMAKE_Fortran_COMPILER={0}'.format(
                    spec['mpi'].mpifc),
```

2020-12-25 05:56 UTC, adamjstewart commented on var/spack/repos/builtin/packages/lsdalton/package.py
> +    conflicts('%gcc@10')
```suggestion
    conflicts('%gcc@10:')
```

2021-06-12 11:01 UTC, alalazo commented
Closing as stale. Feel free to reopen if you want to continue working on this.

2021-06-12 11:01 UTC, closed without merging