Add procenv
LLNL/spack pull request #20121
Opened 2020-11-26 10:49 UTC by loveshack

2020-11-30 11:29 UTC, michaelkuhn requested changes
There is one flake8 error that has to be fixed (missing newline above the class).

Moreover, procenv currently does not compile with GCC 10, so we should add a conflict or apply the following patch: https://github.com/jamesodhunt/procenv/pull/16

2020-12-09 21:58 UTC, michaelkuhn commented
I think you forgot to actually add the patch. You can also just do something like this:
```
patch('https://github.com/jamesodhunt/procenv/pull/16.patch', sha256='7a2b34c754a80ba5fde53626290f9955ec341cd00dbeb45212e6e20d617c7029')
```

2020-12-14 21:36 UTC, loveshack commented
I realized this was outstanding. I did add the patch.  Thanks for the hint about using a url, which I didn't know.

2020-12-25 05:58 UTC, adamjstewart commented on var/spack/repos/builtin/packages/procenv/package.py
> +comparing system environments."""
Can you indent this?

2020-12-28 20:28 UTC, michaelkuhn approved these changes
LGTM (once Adam's change request has been incorporated)

2021-01-04 21:08 UTC, merged