Improve gcc detection in llvm.
LLNL/spack pull request #20189
Opened 2020-11-30 22:59 UTC by tomgreen66

Have hit this issue on a few systems now where location of gcc cannot be trusted to give a consistent location for the install prefix.  By querying the gcc execuable itself it seems it provides a better approach.

Errors I would get during llvm build would be:
```
     80847        /apps/spack/opt/linux-rhel7-skylake_avx512/gcc-8.1.0/llvm-11.
              0.0-s4pz3g4h3dladmlwlrldac5eflo44izh/bin/clang      -rdynamic CMa
              keFiles/cmTC_b709c.dir/testCCompiler.c.o  -o cmTC_b709c
  >> 80848    ld: cannot find crtbegin.o: No such file or directory
  >> 80849        ld: cannot find -lgcc
  >> 80850        ld: cannot find -lgcc_s
  >> 80851        clang-11: error: linker command failed with exit code 1 (use
              -v to see invocation)
  >> 80852        gmake[1]: *** [cmTC_b709c] Error 1
```

By applying this patch it helps.

2020-11-30 23:44 UTC, haampie commented
This is very useful! Can you check the merge conflict?

2020-12-02 19:39 UTC, naromero77 commented
This PR is also adding `flang `which is not a functioning Fortran compiler at this time, it is only a frontend. I don't think it should be included in this PR and in fact we spoke explicitly about not adding it to Spack until it is ready and can at least compile Fortran77.

2020-12-02 20:41 UTC, tomgreen66 commented
Apologies for leaving in the flang option.  Used to hate people who do more than the ticket describes.  Have edited the branch to reduce change to what it should only fix.

2020-12-02 22:22 UTC, naromero77 approved these changes

2020-12-02 22:22 UTC, naromero77 commented
no problem. 

Let's give @trws a day or two to look the change over.

2020-12-03 22:19 UTC, trws requested changes
Love it, just remove the comment line, and possibly add a fallback or error message for if the `install:` line isn't there? I'm almost tempted to actually check for something in that prefix too, but really this is better than where we were and I'd like to see it in soon.

2020-12-03 22:19 UTC, trws commented on var/spack/repos/builtin/packages/llvm/package.py
> +            #gcc_prefix = ancestor(self.compiler.cc, 2)
```suggestion

```

2020-12-04 13:25 UTC, tomgreen66 commented
I wasnt sure how to handle the reporting of the logic hence I left the assumption `install:` always exist.  Is it better to leave the existing as the initial value for `gcc_prefix` so if `install:` isnt found it defaults back to the old value?  I couldnt see any existing method to output to say its using the `install:` value - do we want to quietly do the logic or assume `install:` method is the default and report if the old value is used.

2020-12-11 04:46 UTC, naromero77 commented
I think if `install:` is not found we need to throw a hard error, e.g.
```
raise InstallError(
                    'llvm: cannot find GCC installation prefix')
```

2021-01-05 21:31 UTC, tldahlgren commented
Closing and re-opening the PR to force re-running checks since `style` is still `Waiting for status to be reported`.

2021-01-05 21:55 UTC, trws approved these changes

2021-01-06 05:21 UTC, naromero77 commented
There is still one flake8 error:
```
var/spack/repos/builtin/packages/llvm/package.py:507: [W291] trailing whitespace
```

2021-01-13 22:49 UTC, tomgreen66 commented
Hi, apologies for all the confusion with this change.  Fixed up the remaining issue.  Will make sure I take more care in the future.

2021-01-14 21:59 UTC, trws commented
No worries, we all do it.  LGTM.

2021-01-15 08:21 UTC, alalazo approved these changes
Merging, since it has the approval of both `llvm` maintainers.

2021-01-15 08:22 UTC, merged