minimal zsh completion
LLNL/spack pull request #20253
Opened 2020-12-04 22:55 UTC by trws

Since zsh can load bash completion files natively, seems reasonable to just turn this on.  The only changes are to switch from `type -t` which zsh doesn't support to using `type` with a regex and adding a new arm to the sourcing of the completions to allow it to work for zsh as well as bash.

Could use more bash/dash/etc testing probably, but everything I've thought to try has worked so far.

2020-12-06 01:01 UTC, tgamblin requested changes
not sure what, but something is breaking with the shell tests.

2020-12-07 20:00 UTC, trws commented
It turned out to be a difference in the requirements for quoting of the regex match operator.  In fixing it, I added zsh completion to the unit tests and fixed some follow-on bugs caused by needing bash-isms in the test harness and some functions that weren't getting used for interactive completion.

2020-12-08 17:55 UTC, trws commented
Ok, this is now passing all but coverage testing for the completion script.  As of now, kcov does not [support coverage for zsh](https://github.com/shellspec/shellspec/pull/64) except through a non-upstreamed [extension](https://github.com/shellspec/shellspec/pull/64).  The code is covered by unit testing, but not in a way that I can report to codecov at the moment.  Is that a blocking issue such that I should include the workaround to get zsh coverage in here as well?

2020-12-10 20:52 UTC, trws commented
@adamjstewart, @tgamblin, thoughts on the coverage issue?

2020-12-10 20:56 UTC, adamjstewart approved these changes
LGTM. It's too bad about the lack of coverage, but hopefully that will be resolved someday. Tests without coverage are better than no tests in my mind.

2020-12-10 21:01 UTC, trws commented
If you want, we can set up another issue to track this, and we could add it with the workaround above, it just isn't going to be officially supported by kcov.

2020-12-19 01:24 UTC, tgamblin approved these changes

2020-12-19 01:26 UTC, merged