Feature/r-genefilter updated to version 1.72.0
LLNL/spack pull request #20311
Opened 2020-12-09 20:26 UTC by ajxander12

2020-12-11 19:08 UTC, baberlevi commented on var/spack/repos/builtin/packages/r-genefilter/package.py
> +    #  git      = "https://git.bioconductor.org/packages/genefilter.git"
What's the reason behind changing from the git commits to the release archive ?

2020-12-11 19:08 UTC, baberlevi commented on var/spack/repos/builtin/packages/r-genefilter/package.py
> +##############################################################################
```suggestion
```

2020-12-16 17:42 UTC, ajxander12 commented on var/spack/repos/builtin/packages/r-genefilter/package.py
> +    #  git      = "https://git.bioconductor.org/packages/genefilter.git"
Ran into some problems with the git commits, working on changing it back now.

2020-12-17 16:18 UTC, alalazo requested changes

2020-12-17 16:18 UTC, alalazo commented on var/spack/repos/builtin/packages/r-genefilter/package.py
> +
```suggestion
```

2020-12-17 16:18 UTC, alalazo commented on var/spack/repos/builtin/packages/r-genefilter/package.py
> +    # url      = "https://bioconductor.org/packages/release/bioc/src/contrib/genefilter_1.72.0.tar.gz"
Why adding a commented out url?

2020-12-25 05:27 UTC, adamjstewart commented
Hmm, https://bioconductor.org/packages/release/bioc/html/genefilter.html only lists the previous release. Anyway, it looks like the dependencies are out-of-date and need to be updated.

2020-12-25 05:27 UTC, adamjstewart commented on var/spack/repos/builtin/packages/r-genefilter/package.py
> +    version('1.73.0', commit='154bc907d2d84884ab3c5c19c1da73d3ba61aad7')
```suggestion
    version('1.72.0', commit='154bc907d2d84884ab3c5c19c1da73d3ba61aad7')
```
?

2021-01-06 09:23 UTC, closed without merging