Update of Eccodes to 2.19.1
LLNL/spack pull request #20368
Opened 2020-12-14 11:23 UTC by MBlaschek

Update of Eccodes to version 2.19.1

Confirmed working:
eccodes@2.19.1~aec+fortran~ipo+memfs+netcdf+openmp+png~pthreads~python build_type=RelWithDebInfo jp2k=openjpeg
with 
intel-parallel-studio@composer.2020.2~advisor~clck+daal~gdb~ilp64~inspector+ipp~itac+mkl~mpi~newdtags+rpath+shared+tbb~vtune auto_dispatch=none threads=none

2020-12-25 05:02 UTC, adamjstewart requested changes
@skosukhin can you review?

2020-12-25 05:02 UTC, adamjstewart commented on var/spack/repos/builtin/packages/eccodes/package.py
> +    depends_on('cmake@3.12.0:', when='@:2.19', type=('build'))
```suggestion
    depends_on('cmake@3.6:', type='build')
    depends_on('cmake@3.12:', when='@2.19:', type='build')
```

2021-01-04 22:15 UTC, adamjstewart approved these changes
Still hoping for a review from @skosukhin. If he doesn't get back to you in a week let me know and I'll merge.

2021-01-05 08:12 UTC, skosukhin commented
@adamjstewart LGTM

2021-01-05 16:09 UTC, merged