Mypy setup and fixing what falls out
LLNL/spack pull request #20384
Opened 2020-12-14 21:38 UTC by trws

I lost my mind a bit after getting the completion stuff working and decided to get Mypy working for spack as well.  This adds a `.mypy.ini` that checks all of the `spack` and `llnl` modules, though not yet packages, and fixes all of the identified missing types and type issues for the spack library.

Depends on #20376 because of how I built this up, but could probably rebase that out if it's an issue.

In a related note, how would folks feel about having a Mypy run in CI?

2020-12-14 22:19 UTC, adamjstewart commented
It would be nice to rebase out #20376, otherwise we have to wait for it to be merged before this can be reviewed.

I would love to have mypy run in CI! My naive understanding on mypy was that it used Python's new `typing` system (Python 3.5+), but I guess you can also use it via comments. How does it work if not all variables/function args have an explicitly defined type? I know Sphinx is setup to read type hints to function documentation. Does this work with comment type hints as well? I don't want to have to duplicate everything, but it would be nice to check types on everything.

2020-12-14 22:42 UTC, trws commented
Sure, I'll rebase that out shortly.

As to typing, yes that's exactly what it does.  That's part of why I have to do the funny try/import/catch dance, since there's no backport of typing to 2.6 but the types have to be imported in the version being checked.  For variables, it infers a type based on the type of the first assignment, and for functions it assumes something like `Any`.  It's very permissive until you give it some type annotations, but as you add more annotations it gets progressively more strict.  Most of the changes in this PR are actually clarifying types it couldn't infer, or that it inferred incorrectly based on first assignment.

The sphinx thing I'm not sure, I would think the comment type hints would work, but have never tried that TBH.

2020-12-14 22:47 UTC, adamjstewart commented
With Mypy, is there a "strict mode" to ensure that all variables and functions are properly typed? We're obviously nowhere near ready for this, but if we ever drop Python 2 support I would love to enforce that for all functions.

2020-12-14 22:49 UTC, trws commented
Rebased here, I meant.   Should not work on two similar patches quite like this.

Yep, there is definitely a strict mode:

```
  --strict                  Strict mode; enables the following flags: --warn-unused-configs, --disallow-any-generics, --disallow-subclassing-any, --disallow-untyped-calls, --disallow-untyped-defs, --disallow-incomplete-defs, --check-untyped-defs, --disallow-untyped-decorators, --no-implicit-optional, --warn-redundant-casts, --warn-unused-ignores, --warn-return-any, --no-implicit-reexport, --strict-equality
```

One upside to the approach they took to gradual typing is that the vast majority of this stuff can be done on a per-module basis, so if some things are ready earlier than others we can make the checking on them stricter without impacting the whole codebase.

2020-12-14 22:53 UTC, adamjstewart commented
I've been using Python 3.5+ type hints in all of my research code for a while, so I've wanted them for Spack too. Unfortunately, until we drop Python 2 support, we can't use those directly, only the comments. I would rather not push for the use of comments (other than the minimal changes you made here).

The other complaint I have about Mypy is that it doesn't work unless all of your dependencies also use Mypy. Like, my research code was mostly numpy/pandas, and those libraries don't yet have full type hint support yet, so that was frustrating.

2020-12-15 06:20 UTC, trws commented
Generally I'd agree.  It would be nice to have some type annotations on high use APIs for scripts and packages, but probably not globally.

The dependency issue is one place where Spack's vendoring policy actually helps a lot.  Since all the source is included in the project, rather than installed and accessed through a site-packages or something, the stubs are unnecessary because mypy will follow the import and do type inference through all the externals as well.  At the moment, I have it ignoring `jinja2` because there's a module in there that needs the `async` syntax, but every other external has its internal errors ignored but contributes inferred types to checking spack.

2020-12-15 17:51 UTC, trws commented
Looks like everything is happy but gitlab, and I don't seem to have access to the results to see why. Should probably figure out how to get access.

I dug into getting Mypy working on packages.  There is no good way to do this, at all, because it doesn't support loading multiple modules with the same name in the same invocation and all packages are treated as being named "package", their directories also don't have valid module names.  We could make a `spack mypy` command that would generate a directory of symlinks renamed to module-compatible names to run it on, but that's not a very nice solution.  The pyright type checker can type-check all of the packages as they are in a single invocation, but throws a huge number of errors on some spack library code for dynamic fields and naming conventions where Mypy does not.  Probably need to put some thought into how to deal with that.

2020-12-15 20:12 UTC, adamjstewart commented
I don't think I have access to Gitlab either, I've just been ignoring it cuz it isn't required in order for the PR to be merged.

2020-12-15 20:16 UTC, trws commented
Did a bit more digging, it seems like two packages being built in the pipeline that spuriously fail to build failed.

2020-12-22 17:40 UTC, tgamblin requested changes
LGTM but 3 change requests:

- [x] Integrate mypy checking with `spack flake8` (if `mypy` is available)
- [x] Change `spack flake8` to `spack style` and leave the old `flake8` command so that it prints out that it's deprecated.
- [x] Add a dummy `typing` module in `lib/spack/external/py26/` so that we don't have to catch `ImportError` for every `typing` import

2020-12-22 18:00 UTC, adamjstewart commented
I support renaming `spack flake8` to `spack style`, especially since we plan to add `black` someday.

2020-12-22 21:06 UTC, trws commented
All checked off.  The last one I went a slightly different direction with it and added another directory like py26 for python2, so we can just do `import typing` and have it do something sane.

2020-12-22 22:35 UTC, tgamblin requested changes
This looks great -- minor change requests.

2020-12-22 22:35 UTC, tgamblin commented on lib/spack/spack/cmd/flake8.py
> +description = spack.cmd.style.description
This should probably say something about deprecation instead of just passing through the `spack style` description.

2020-12-22 22:35 UTC, tgamblin commented on lib/spack/spack/cmd/flake8.py
> +    print("=======================================================")
can this stuff be `tty.warn`?  Users will recognize that.  Suggest replacing everything with:

```python
tty.warn("`spack flake8` is deprecated", "please use `spack style` to run style checks.")
```

2020-12-22 22:35 UTC, tgamblin commented on lib/spack/spack/package.py
> +    _InstallPhase_run_after = {}  # type: Dict[str, List[Callable]]
This is actually awesome because previously I had to remember how this was structured.

2020-12-22 22:39 UTC, tgamblin requested changes
One more thing.  We should update this in CI and update the docs.  Specifically:

- [ ] [`share/spack/qa/run-flake8-tests`](https://github.com/spack/spack/blob/develop/share/spack/qa/run-flake8-tests)
- [ ] [`.github/workflows/style_and_docs.yaml`](https://github.com/spack/spack/blob/develop/.github/workflows/style_and_docs.yaml)
- [ ] [`lib/spack/docs/contribution_guide.rst`](https://github.com/spack/spack/blob/develop/lib/spack/docs/contribution_guide.rst#flake8-tests) ([these docs](https://spack.readthedocs.io/en/latest/contribution_guide.html#flake8-tests))

2020-12-22 22:58 UTC, trws commented
Ok, I think that covers the comments.  Have a look when you get a chance.  Hopefully this will also cover the completion and other issues I was seeing in the CI.

2020-12-22 23:32 UTC, tgamblin approved these changes

2020-12-23 05:39 UTC, merged