Change the NEST official releases archives url to the current one.
LLNL/spack pull request #20395
Opened 2020-12-15 02:20 UTC by ikitayama

The NEST development community has changed the `url` to the new one. To build the latest and older
releases set the `url` to an appropriate one.

2020-12-15 02:21 UTC, ikitayama commented
again kindly asking @adamjstewart for the review work.

2020-12-15 04:03 UTC, adamjstewart requested changes

2020-12-15 04:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/nest/package.py
> +    url      = "https://github.com/nest/nest-simulator/archive/v2.12.0.tar.gz"
This new URL will result in different checksums for all versions. Can you update those checksums?

2020-12-15 04:09 UTC, ikitayama commented
Adam,
Actually, I was able to build an older release, without changing the
checksum. Hmm?

On Tue, Dec 15, 2020 at 1:03 PM Adam J. Stewart <notifications@github.com>
wrote:

> *@adamjstewart* requested changes on this pull request.
> ------------------------------
>
> In var/spack/repos/builtin/packages/nest/package.py
> <https://github.com/spack/spack/pull/20395#discussion_r543029181>:
>
> > @@ -13,7 +13,7 @@ class Nest(CMakePackage):
>      than on the exact morphology of individual neurons."""
>
>      homepage = "http://www.nest-simulator.org"
> -    url      = "https://github.com/nest/nest-simulator/releases/download/v2.12.0/nest-2.12.0.tar.gz"
> +    url      = "https://github.com/nest/nest-simulator/archive/v2.12.0.tar.gz"
>
> This new URL will result in different checksums for all versions. Can you
> update those checksums?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/spack/spack/pull/20395#pullrequestreview-552089261>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHLBZZDG7QGGRWJZKIPDBLSU3NZXANCNFSM4U3UEVMQ>
> .
>

2020-12-15 04:29 UTC, adamjstewart commented
Maybe that release was already in your downloads cache? I downloaded the files manually and the checksums are definitely different.

2020-12-15 04:49 UTC, ikitayama commented
Ah!

On Tue, Dec 15, 2020 at 1:29 PM Adam J. Stewart
<notifications@github.com> wrote:
>
> Maybe that release was already in your downloads cache? I downloaded the files manually and the checksums are definitely different.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-06-12 11:05 UTC, alalazo commented
Closing as stale. Feel free to reopen if you want to continue working on this.

2021-06-12 11:05 UTC, closed without merging