Add spack test support for Qthreads
LLNL/spack pull request #20437
Opened 2020-12-17 00:38 UTC by janciesko

2020-12-17 18:42 UTC, tldahlgren commented on var/spack/repos/builtin/packages/qthreads/package.py
> +
FWIW. From a static analysis standpoint, there should be only 1 line between the `return` and the properties.

2020-12-17 18:55 UTC, tldahlgren commented
FYI.  I'm checking out and running the test tests.

2020-12-17 18:57 UTC, tldahlgren commented on var/spack/repos/builtin/packages/qthreads/package.py
> +        self.cache_extra_test_sources(tests_to_cpy)
You could combine calls to `self.cache_extra_test_sources` to provide a single list with all of the files you want to copy to reduce the copy overhead.

2020-12-17 21:21 UTC, tldahlgren commented on var/spack/repos/builtin/packages/qthreads/package.py
> +               '-I{0}'.format(self.prefix.include),
FWIW. I had to add `'-std=c11'` as an option to get this to compile for gcc@8.1.0 on a linux box and actually run the tests.

As I mentioned in email, I get more focused error message in the test output with the default scheduler *and* the all of the tests pass for me when the library is built with the `distrib` scheduler.  (Thanks for pointing me to it!)

2020-12-17 21:24 UTC, tldahlgren commented
This is *really* close!

2020-12-18 00:28 UTC, tldahlgren commented on var/spack/repos/builtin/packages/qthreads/package.py
> +
```suggestion
    test_requires_compiler = True
```

2020-12-18 00:29 UTC, tldahlgren commented on var/spack/repos/builtin/packages/qthreads/package.py
> +
You'll need this property set to `True` to get the right compiler for the build.

2020-12-18 00:30 UTC, tldahlgren commented on var/spack/repos/builtin/packages/qthreads/package.py
> +    test_base_path = 'test/basics/'
For readability, the three properties -- `test_requires_compiler` *and* the two here -- should be moved to under the `url` property at the top of the package.

2020-12-18 00:31 UTC, tldahlgren requested changes
Please fix the flake8 failures and add the `test_requires_compiler = True` property.

2020-12-18 17:32 UTC, janciesko commented
Comments addressed. Thanks @tldahlgren.

2020-12-18 20:17 UTC, tldahlgren commented on var/spack/repos/builtin/packages/qthreads/package.py
> +                                     self.prefix.lib ]
You need a closing paren (')') before the closing square bracket here.

2020-12-18 20:21 UTC, tldahlgren commented on var/spack/repos/builtin/packages/qthreads/package.py
> +                      '-I{0}'.format(self.prefix.include),
Python is picky.  Lines 113 to 121 should be indented 4 spaces relative to line 112, with two exceptions.

The first letter of `test` in line 116 should appear under the `s` in line 115.  A similar alignment is needed on line 122.

2020-12-18 20:23 UTC, tldahlgren commented on var/spack/repos/builtin/packages/qthreads/package.py
> +            reason = 'test:{0}: Checking ability to link to the library.'.format(test)
You can add a slash ('\') after the apostrophe in `library.'` so Python knows to continue this statement on the next line to pick up `.format(test)`, which needs to be indented 4 spaces relative to `reason` in line 123.

2020-12-18 20:33 UTC, tldahlgren approved these changes
I'm able to successfully build and run the smoke tests (which pass when I build with `scheduler=distrib`).

This can be merged once the flake8 checks pass.

2020-12-18 20:56 UTC, janciesko commented
Flake8 passes. Commits squashed.

2020-12-18 20:59 UTC, tldahlgren commented
> Flake8 passes. Commits squashed.

Great!  Thanks.

This PR can be merged once all the required checks pass.

2020-12-18 21:38 UTC, merged

2020-12-18 21:38 UTC, tldahlgren commented
Thank you for your contribution!