New package py-picrust2 version 2.3.0-b with py-biom-format dep. fixed
LLNL/spack pull request #20455
Opened 2020-12-17 22:03 UTC by dorton21

2020-12-23 18:39 UTC, dorton21 commented
Can I get an update regarding the ability of this pull request to go through?

2020-12-23 19:12 UTC, scheibelp approved these changes

2020-12-23 19:13 UTC, scheibelp commented
Sorry the PR can be merged without the pipeline reporting, I have approved it and will merge once CI completes. Thanks for the ping!

2020-12-23 20:29 UTC, adamjstewart requested changes

2020-12-23 20:29 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-biom-format/package.py
>      depends_on('py-numpy@1.3.0:', type=('build', 'run'))
```suggestion
    depends_on('py-numpy@1.9.2:', type=('build', 'run'))
```

2020-12-23 20:29 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-biom-format/package.py
>      depends_on('py-scipy@0.13.0:', type=('build', 'run'))
```suggestion
    depends_on('py-scipy@1.3.1:', type=('build', 'run'))
```

2020-12-23 20:29 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-biom-format/package.py
>      depends_on('py-pandas@0.19.2:', type=('build', 'run'))
```suggestion
    depends_on('py-pandas@0.20.0:', type=('build', 'run'))
```

2020-12-23 20:29 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-biom-format/package.py
>      depends_on('py-cython', type='build')
```suggestion
    depends_on('py-cython@0.29:', type='build')
```

2020-12-23 20:29 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-biom-format/package.py
>      depends_on('py-h5py', type=('build', 'run'), when='+h5py')
Seems like this is now required?

2020-12-23 20:29 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-biom-format/package.py
Add this:
```python
depends_on('python@2.7:')
depends_on('python@3:', when='@2.1.9:')
```

2020-12-23 20:29 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-biom-format/package.py
> +    depends_on('py-pyqi', type=('build', 'run'), when='@:2.1.4')
```suggestion
    depends_on('py-pyqi', type=('build', 'run'), when='^python@:2')
```

2020-12-24 02:56 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-biom-format/package.py
> +    depends_on('python@3:', when='@2.1.9:')
```suggestion
    depends_on('python@2.7:', type=('build', 'run'))
    depends_on('python@3:', when='@2.1.9:', type=('build', 'run'))
```

2021-01-04 16:47 UTC, dorton21 commented
Any other fixes needed for this?

2021-01-04 22:10 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-picrust2/package.py
> +    depends_on('py-biom-format@2.1.5:', type=('build', 'run'))
Where do you see that 2.1.5+ is needed?

2021-01-04 22:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-biom-format/package.py
>      depends_on('py-h5py', type=('build', 'run'), when='+h5py')
Since this is now required, we might want to remove the variant.

2021-01-05 19:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-biom-format/package.py
>      depends_on('py-h5py', type=('build', 'run'), when='+h5py')
You can also remove the when arg.

2021-01-05 20:02 UTC, adamjstewart approved these changes

2021-01-05 21:20 UTC, dorton21 commented
What is the unit test failure?

2021-01-06 00:07 UTC, adamjstewart commented
Looks like a transient failure, I restarted the tests.

2021-01-06 07:54 UTC, alalazo approved these changes

2021-01-06 07:54 UTC, merged