New Feature/r-circstats at version 0.2-6
LLNL/spack pull request #20479
Opened 2020-12-18 17:13 UTC by ajxander12

2020-12-24 23:35 UTC, adamjstewart requested changes

2020-12-24 23:35 UTC, adamjstewart commented on var/spack/repos/builtin/packages/r-circstats/package.py
> +    url      = "https://cran.r-project.org/src/contrib/CircStats_0.2-6.tar.gz"
Needs `list_url`, should use `cloud` instead of `cran`. See https://spack.readthedocs.io/en/latest/build_systems/rpackage.html#list-url

2020-12-24 23:35 UTC, adamjstewart commented on var/spack/repos/builtin/packages/r-circstats/package.py
> +    depends_on('r-mass')
Needs to be `type=('build', 'run')`

2020-12-29 16:14 UTC, adamjstewart commented on var/spack/repos/builtin/packages/r-circstats/package.py
> +    url      = "https://cran.r-project.org/src/contrib/CircStats_0.2-6.tar.gz"
Can you use cloud for the homepage and url too?

2021-01-25 21:59 UTC, haampie commented
Hm, gitlab-ci status persists after closing and reopening, could you have another look @adamjstewart?

2021-01-25 23:59 UTC, adamjstewart commented
gitlab-ci is not required for merger. It's pretty broken at the moment. I don't even have access to it.

2021-01-26 00:00 UTC, adamjstewart commented
@glennpj

2021-01-26 02:15 UTC, glennpj commented
I think with the change from `cran.r-project` to `cloud.r-project` in the urls this should be good to go.

2021-06-12 11:10 UTC, alalazo commented
Closing since this was added in #21966. Apologies for getting back late to this and thanks for the PR.

2021-06-12 11:10 UTC, closed without merging