VTK: add -no-ipo for builds using intel compiler
LLNL/spack pull request #20480
Opened 2020-12-18 17:44 UTC by andymwood

Fixes 20471, avoiding an internal compiler error.

2020-12-24 23:33 UTC, adamjstewart requested changes
@chuckatkins @danlipsa can you review?

2020-12-24 23:33 UTC, adamjstewart commented on var/spack/repos/builtin/packages/vtk/package.py
> +                '-DCMAKE_CXX_FLAGS="{}"'.format(compile_flags)
```suggestion
                '-DCMAKE_C_FLAGS={0}'.format(compile_flags),
                '-DCMAKE_CXX_FLAGS={0}'.format(compile_flags)
```
Needed for Python 2.6 support

2020-12-25 04:40 UTC, adamjstewart approved these changes

2020-12-25 15:14 UTC, adamjstewart commented
Double quotes shouldn't be needed. If you were building this on the command line, bash would strip the double quotes, but we aren't using bash.

2021-01-05 21:11 UTC, merged

2021-01-05 21:11 UTC, tldahlgren commented
Thank you for your contribution!