Added new package r-fasterize at verion 1.0.3
LLNL/spack pull request #20496
Opened 2020-12-21 19:14 UTC by ajxander12

2020-12-24 23:15 UTC, adamjstewart requested changes

2020-12-24 23:15 UTC, adamjstewart commented on var/spack/repos/builtin/packages/r-fasterize/package.py
> +    depends_on('r-rcpparmadillo')
Need to add `type=('build', 'run')` to all of these

2020-12-24 23:15 UTC, adamjstewart commented on var/spack/repos/builtin/packages/r-fasterize/package.py
> +    url      = "https://cran.r-project.org/src/contrib/fasterize_1.0.3.tar.gz"
Needs a `list_url`: https://spack.readthedocs.io/en/latest/build_systems/rpackage.html#list-url

Also, you should use `cloud` over `cran` for mirrors

2020-12-29 16:13 UTC, adamjstewart commented on var/spack/repos/builtin/packages/r-fasterize/package.py
> +    url      = "https://cran.r-project.org/src/contrib/fasterize_1.0.3.tar.gz"
Can you use cloud for the homepage and url too?

2021-01-25 22:51 UTC, adamjstewart commented
@glennpj

2021-01-26 02:21 UTC, glennpj commented on var/spack/repos/builtin/packages/r-fasterize/package.py
> +    homepage = "https://cran.r-project.org/package=fasterize"
This should reflect the URL, if there is one, in the DESCRIPTION file. This should also be reflected on the CRAN packages page. The URL, and homepage for spack, should be:

https://github.com/ecohealthalliance/fasterize

2021-06-12 11:11 UTC, alalazo commented
@alexander-baumgarten What is the status of this PR?

2022-02-11 13:53 UTC, alalazo commented
Closing since there was no reply in  a few months. Feel free to reopen in case you want to continue working on the PR.

2022-02-11 13:53 UTC, closed without merging