Clean up .gitignore, add Python.gitignore
LLNL/spack pull request #20613
Opened 2020-12-30 00:05 UTC by adamjstewart

We recently added `spack style`, which runs `mypy`, but we weren't ignoring the `.mypy_cache` directory. We also weren't ignoring the debug logs created by `spack debug create-db-tarball`. This PR includes the following changes:

- [x] Add all ignores from https://github.com/github/gitignore/blob/master/Python.gitignore (includes mypy)
- [x] Ignore file created by `spack debug create-db-tarball`
- [x] Remove ignores that have nothing to do with Spack or Python (OS- or editor-specific)
- [x] Remove ignores for ancient versions of Spack (dotkit)

I can undo the last 2 if they aren't desirable. Personally, I think OS- and editor-specific ignores should go in `~/.gitignore`, not in a project-specific `.gitignore`. There are far too many editors out there.

Let me know if any of the weird things like `/db`, `/etc/spackconfig`, or `/bin/spackc` were there for a reason.

2020-12-30 23:32 UTC, trws requested changes, later dismissed
Looks good generally, a couple of the dict paths won't work with the way spack is laid out but otherwise: 👍 

As to the swap and tags file entries though, I'd prefer to leave them in, but wouldn't fight taking them out.  The actually specific ones like `.project` kinda make sense, but there are a lot of editors that follow either the vim or emacs conventions of `.swp` or `*~` files, and use `TAGS` such that those cover a good bit of ground.  More to the point, they're good defense against `git add var` sucking swap files into someone's PR and having to tell them to fix it.  Really, I'd add *more* of that stuff, but that's enough of a preference thing that I wouldn't fight either way.

2020-12-30 23:32 UTC, trws commented on .gitignore
> +var/
This one will not work. It will make `git add` complain about all packages, and stuff under var in general.

```suggestion
```

2020-12-30 23:32 UTC, trws commented on .gitignore
> +lib/
Will not be able to add files in the lib directory without overrides.

```suggestion
```

2020-12-30 23:49 UTC, adamjstewart commented
If we do want to add editor- and OS-specific files to the mix, should we concatenate a selection of `.gitignore` files from https://github.com/github/gitignore? Which do we care about? (vim, emacs, eclipse, VScode, sublime text, macOS, Linux, Windows)?

The way their repo is set up is that common language-specific ignores are at the top-level, while the editor/tool/OS-specific ignores are in the `Global` directory. I wish we could keep these files separate in some way instead of concatenating them though.

2021-01-11 18:45 UTC, adamjstewart commented
Ping @tgamblin

2021-02-01 17:31 UTC, adamjstewart commented
Ping ping @spack/merge-to-develop

2021-02-01 18:57 UTC, sethrj submitted a review, later dismissed
Looks good to me. I'm ambivalent about having environment-specific code in git repos -- I agree it should be in everyone's `~/.gitignore` but since some people don't have one, we'll have to be vigilant about not letting `.DS_Store` etc. creep into new PRs.

2021-02-05 18:22 UTC, adamjstewart commented
Ping @tgamblin

2021-02-05 18:23 UTC, adamjstewart commented
@sethrj I disabled auto-merge as this is likely a controversial PR. I'd prefer multiple reviews of this before it gets merged.

2021-02-05 20:58 UTC, ax3l approved these changes, later dismissed

2021-02-05 20:59 UTC, ax3l commented
Just a note: I am ok to add `ignores that have nothing to do with Spack or Python (OS- or editor-specific)` in a project's `.gitignore`.

2021-02-08 22:09 UTC, michaelkuhn submitted a review, later dismissed
I don't have a strong opinion about the OS-/editor-specific ignores, the rest LGTM.

2021-02-09 18:48 UTC, chuckatkins commented
I'm pretty hard on the "should ignore editor tmp files" camp.  Making a commit while something is open in vim and having the `.swp` file slurped in is pretty irritating.  Typically I use:
```
# Vi(m) temporary buffer files
*.sw?

# Emacs temporary files
*~
```

2021-02-09 18:51 UTC, chuckatkins commented
> As to the swap and tags file entries though, I'd prefer to leave them in.

I'm pretty hard in the "should ignore editor tmp files" camp. Making a commit while something is open in vim and having the `.swp` file slurped in is pretty irritating. Typically I use:
```
# Vi(m) temporary buffer files
*.sw?

# Emacs temporary files
*~
```

2021-02-09 18:51 UTC, chuckatkins commented
> As to the swap and tags file entries though, I'd prefer to leave them in.

I'm pretty hard in the "should ignore editor tmp files" camp. Making a commit while something is open in vim and having the `.swp` file slurped in is pretty irritating. Typically I use:
```
# Vi(m) temporary buffer files
*.sw?

# Emacs temporary files
*~
```

2021-02-09 18:57 UTC, becker33 commented
@adamjstewart I am pretty strongly on the side of leaving the editor-specific files in `.gitignore`.  Otherwise LGTM.

2021-02-09 19:00 UTC, adamjstewart commented
If we do want to add editor- and OS-specific files to the mix, should we concatenate a selection of .gitignore files from https://github.com/github/gitignore? Which do we care about? (vim, emacs, eclipse, VScode, sublime text, macOS, Linux, Windows)?

2021-02-09 19:36 UTC, adamjstewart commented
Okay, I added ignores for common editors and OSes. Let me know if there are any other editors that you want me to add. I'm hoping that this will be better structured now, and should be easy to update/keep track of.

2021-02-09 19:38 UTC, alalazo commented
@adamjstewart Did you add back Pycharm `.idea` folder? :slightly_smiling_face:

2021-02-09 19:40 UTC, adamjstewart commented
Surprisingly, `Python.gitignore` does not include PyCharm, and there's no editor-specific ignores for it. I'll add it.

2021-02-09 19:46 UTC, adamjstewart commented
Found the editor-specific ignores in `JetBrains.gitignore`

2021-02-09 19:46 UTC, becker33 commented
That is incredibly thorough.

2021-02-09 19:46 UTC, becker33 approved these changes

2021-02-09 20:55 UTC, merged