New Package fparser@2015/09/25
LLNL/spack pull request #20628
Opened 2020-12-30 22:00 UTC by dorton21

2021-01-04 17:54 UTC, baberlevi approved these changes

2021-01-06 09:27 UTC, alalazo requested changes
Just a minor request

2021-01-06 09:27 UTC, alalazo commented on var/spack/repos/builtin/packages/fparser/package.py
> +    evaluate a mathematical function from a string (which might be eg
Can we have a short one-line description first and a longer description as a separate paragraph:
```suggestion
    """Parse and evaluate a mathematical function from a string.
    
    This C++ library offers a class which can be used to parse and
    evaluate a mathematical function from a string (which might be eg
```
?

2021-01-11 10:08 UTC, alalazo approved these changes

2021-01-11 10:09 UTC, alalazo commented
There's a flake8 issue, sorry:
```
var/spack/repos/builtin/packages/fparser/package.py:11: [W293] blank line contains whitespace
```
Ping me when you solved that and I'll merge.

2021-01-27 22:01 UTC, closed without merging

2021-01-27 22:01 UTC, dorton21 commented
In hindsight this isn't needed and it is a minor package.