RFC: make package build reproducible
LLNL/spack pull request #20629
Opened 2020-12-30 22:26 UTC by bmwiedemann

without this patch, `spack-0.16.0/lib/spack/docs/_build/texinfo/Spack.texi`
varied in

```
@deffn {Data} spack.config.config_defaults = @{'config': @{'build_jobs': 4, 'build_stage': '$tempdir/spack@w{-}stage', 'checksum': True, 'concretizer': 'original', 'connect_timeout': 10, 'debug': False, 'dirty': False, 'verify_ssl': True@}@}
```

that caused resulting `Spack.info` and `spack.1` files to differ as well.

It would probably be more appropriate to drop the `build_jobs`
default value when generating the `Spack.texi` file
but this code was hard to locate.

2021-01-19 05:18 UTC, adamjstewart requested changes
I don't think this change is something that we want, as it changes the default parallelism for all users on all systems.

2021-01-19 05:21 UTC, bmwiedemann commented
Maybe you know how/where the `Spack.texi` file is generated, so we could strip this number out?

2021-01-19 16:41 UTC, adamjstewart commented
It looks like this file is generated when you run:
```console
$ cd spack-0.16.0/lib/spack/docs
$ make texinfo
```
I'm not familiar with OpenSUSE's Reproducible Builds effort, maybe you can give me more info on what its goal is. When you say "package build", do you mean installation of Spack, or the usage of Spack as a package manager to install other software? Building the documentation certainly isn't necessary for running Spack, so if you could remove that then that would be an easy way to resolve the unreproducible problem.

2021-02-11 07:44 UTC, bmwiedemann commented
We 'build' the spack sources into an openSUSE rpm package.
I think, our users appreciate having documentation. And it is probably not hard to have reproducible docs, when you look at this 1-line-patch. Worst case, we could do post-processing of the output, though the result would be more brittle.

2021-02-11 17:25 UTC, adamjstewart commented
Thanks for the explanation!

> And it is probably not hard to have reproducible docs, when you look at this 1-line-patch.

This 1-line-patch completely breaks Spack's ability to adapt to different platforms. While my laptop has 4 cores, my supercomputer may have 64 or 128 cores, and I would like to take advantage of them when building software.

@becker33 @alalazo @scheibelp I recall some talk of removing this variable and instead relying on the config files. Another option would be to make this a hidden variable so it doesn't end up in the documentation. Thoughts on this?

2021-06-12 11:13 UTC, alalazo commented
Closing as stale. Feel free to reopen if you want to continue the discussion on this.

2021-06-12 11:13 UTC, closed without merging