py-mikado: Add version 1.2.4
LLNL/spack pull request #20678
Opened 2021-01-05 07:00 UTC by t-nojiri

This PR is for the following issues:
　https://github.com/spack/spack/issues/20552

I specified the version number for py-pandas because the following message was output at build time.
py-pandas requires python version 3.7.1:, but spec asked for 3.6.12

2021-01-05 20:51 UTC, adamjstewart requested changes

2021-01-05 20:51 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-biopython/package.py
>      version('1.65', sha256='463cc81db84e9bfcdfb15629511c81ed556a6c0287e670dbfe80f03c65d2a88e')
The latest version requires:
```python
depends_on('python@3.6:', type=('build', 'run'))
```

2021-01-05 20:51 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mikado/package.py
> +    url = "https://pypi.io/packages/source/M/Mikado/Mikado-1.2.4.tar.gz"
```suggestion
    pypi = "Mikado/Mikado-1.2.4.tar.gz"
```

2021-01-05 20:51 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mikado/package.py
>      depends_on('py-tabulate', type=('build', 'run'))
Check the `requirements.txt`, many of these versions have changed

2021-01-05 20:52 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mikado/package.py
> +    depends_on('py-pandas@:1.1.5', type=('build', 'run'))
I would undo this change. If you're using Python 3.8, then any version of pandas should work. If you're having concretization issues, you may want to try the new concretizer, or explicitly set things like this in your `packages.yaml`.

2021-01-06 00:40 UTC, t-nojiri commented
I'm using Python 3.8.6.
Reverting the py-pandas fix causes conflicts.
$ spack debug report
* ** Spack: ** 0.16.0-448-e6d462589
* ** Python: ** 3.8.6
* ** Platform: ** linux-rhel8-thunderx2
* ** Concreteizer: ** original
$ spack install py-mikado %gcc@8.3.1
:
py-pandas requires python version 3.7.1:, but spec asked for 3.6.12


The new concretizer gave the following error.
$ spack debug report
* **Spack:** 0.16.0-448-e6d462589
* **Python:** 3.8.7
* **Platform:** linux-rhel8-thunderx2
* **Concretizer:** clingo
$ spack install py-mikado %gcc@8.3.1
==> Error: 'gdb'


Should I undo the py-pandas fix?

2021-01-06 01:17 UTC, t-nojiri commented
I didn't check requirements.txt.
frozendict wasn't in the spack list, but I modified everything else and I was able to build py-mikado.

I will push this fix again.

2021-01-12 00:19 UTC, t-nojiri commented on var/spack/repos/builtin/packages/py-biopython/package.py
>      version('1.65', sha256='463cc81db84e9bfcdfb15629511c81ed556a6c0287e670dbfe80f03c65d2a88e')
I reflected the fix for py-biopython.

2021-01-12 18:24 UTC, adamjstewart requested changes

2021-01-12 18:24 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mikado/package.py
> +    depends_on('python@3.6:', type=('build', 'run'))
```suggestion
    depends_on('python@3.4:', type=('build', 'run'))
```

2021-01-12 18:24 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mikado/package.py
>      depends_on('py-wheel@0.28.0:', type=('build', 'run'))
```suggestion
    depends_on('py-wheel@0.28.0:', type='build')
```

2021-01-12 18:24 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mikado/package.py
>      depends_on('py-docutils@0.13.2:', type=('build', 'run'))
```suggestion
    depends_on('py-docutils@:0.13.0,0.13.2:', type=('build', 'run'))
```

2021-01-12 18:24 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mikado/package.py
> -    depends_on('py-tomlkit', type=('build', 'run'))
Missing a dep on `py-tabulate`

2021-01-12 18:24 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mikado/package.py
> +    depends_on('py-simplejson', type=('build', 'run'))
Missing:
```python
depends_on('py-typing', when='^python@:3.4', type=('build', 'run'))
```

2021-01-14 07:54 UTC, t-nojiri commented
I have fixed what was pointed out in the review.

2021-01-14 17:14 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mikado/package.py
> -    depends_on('py-tomlkit', type=('build', 'run'))
Still missing

2021-01-20 05:54 UTC, t-nojiri commented on var/spack/repos/builtin/packages/py-mikado/package.py
> -    depends_on('py-tomlkit', type=('build', 'run'))
I added a py-tabulate depend.

2021-01-20 19:21 UTC, adamjstewart approved these changes

2021-01-20 19:22 UTC, merged