intel-xed: add version 12.0.1
LLNL/spack pull request #20676
Opened 2021-01-05 06:05 UTC by mwkrentel

Rework the version numbers for intel-xed, now that xed has actual
releases and tags.  Add releases 11.2.0 and 12.0.1.  Rename 2019.03.01
to 10.2019.03 as a legacy version that fits in the new order.

Add variant +pic to compile libxed.a with PIC code so that it can be
linked into another shared library.

Add conflict for aarch64.
Add myself as maintainer.

----------

Again, my project (hpctoolkit) is the only other package that
explicitly depends on intel-xed, so reworking the version numbers is
unlikely to cause trouble.

2021-01-11 18:10 UTC, mwkrentel commented
ping @tldahlgren Would you be willing to review and commit this?

Intel changed their version numbers and a small change in the 
install step, but otherwise it's really just add a new version.
XED builds easily and quickly with no prereqs.
Thanks

2021-01-13 17:34 UTC, becker33 requested changes
Mostly LGTM, one request @mwkrentel

2021-01-13 17:34 UTC, becker33 commented on var/spack/repos/builtin/packages/intel-xed/package.py
> +    depends_on('python+pythoncmd@3.4:', type='build')
If it uses `python3` by name, it should not need `+pythoncmd`. That's only needed if it refers to it as `python`.

2021-01-13 19:02 UTC, mwkrentel commented
@becker33 
Ok, I removed +pythoncmd.  `spack info python` describes +pythoncmd as:

```
Symlink 'python3' executable to 'python'
```

I was reading the direction of the symlink backwards.
You have to focus on 'executable' as opposed to 'to'.  :-)

Thanks !!

2021-01-13 19:08 UTC, becker33 approved these changes

2021-01-13 19:46 UTC, merged