parallelio: New Package.
LLNL/spack pull request #20673
Opened 2021-01-05 04:35 UTC by tkameyama

2021-01-05 17:43 UTC, tldahlgren commented on var/spack/repos/builtin/packages/parallelio/package.py
> +    """he Parallel IO libraries (PIO) are high-level parallel I/O C and
```suggestion
    """The Parallel IO libraries (PIO) are high-level parallel I/O C and
```

2021-01-05 18:04 UTC, tldahlgren commented on var/spack/repos/builtin/packages/parallelio/package.py
> +
```suggestion

        maintainer = ['tkameyama']
```

2021-01-05 18:19 UTC, tldahlgren requested changes
LGTM.  Just a couple of suggestions.

2021-01-06 07:25 UTC, tkameyama commented on var/spack/repos/builtin/packages/parallelio/package.py
> +    """he Parallel IO libraries (PIO) are high-level parallel I/O C and
fixed.

2021-01-06 07:25 UTC, tkameyama commented on var/spack/repos/builtin/packages/parallelio/package.py
> +
done.

2021-01-06 18:05 UTC, tldahlgren approved these changes
LGTM

2021-01-06 18:05 UTC, merged

2021-01-06 18:05 UTC, tldahlgren commented
Thank you for your contribution!