amrex: fix missing hdf5 dependency
LLNL/spack pull request #20714
Opened 2021-01-06 21:17 UTC by mic84

2021-01-06 21:26 UTC, tldahlgren approved these changes
LGTM.

2021-01-06 21:29 UTC, tldahlgren requested changes
Please fix the `flake8` errors:

- var/spack/repos/builtin/packages/amrex/package.py:86: [E231] missing whitespace after ','
15
- var/spack/repos/builtin/packages/amrex/package.py:86: [E231] missing whitespace after ','

2021-01-06 21:30 UTC, tldahlgren commented on var/spack/repos/builtin/packages/amrex/package.py
> +    depends_on('hdf5@1.10.4:',type='build',when='+hdf5')
```suggestion
    depends_on('hdf5@1.10.4:', type='build', when='+hdf5')
```

2021-01-06 21:50 UTC, eschnett commented
I think the `type=build` is wrong; it shouldn't be there.

Which HDF5 bindings do you require (just C, or also C++)? Do you require parallel I/O?

2021-01-06 23:51 UTC, mic84 commented
@eschnett it should be good now

2021-01-13 22:46 UTC, eschnett commented
I confirm that this PR works for me.

2021-01-20 14:05 UTC, eschnett commented
Ping! This patch is almost good to go, just needs a rebase or merge.

2021-01-21 00:06 UTC, mic84 commented
@tldahlgren can you review again, please? Thanks!

2021-01-22 00:16 UTC, tldahlgren approved these changes
LGTM.

2021-01-22 00:16 UTC, merged

2021-01-22 00:17 UTC, tldahlgren commented
Thank you for your contribution!