New package: py-memprof
LLNL/spack pull request #20730
Opened 2021-01-07 17:02 UTC by qwertos

2021-01-10 23:29 UTC, adamjstewart requested changes

2021-01-10 23:29 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-memprof/package.py
> +    depends_on('py-cython',     type=('build', 'run'))
This is probably only needed at build-time

2021-01-10 23:29 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-memprof/package.py
> +    depends_on('py-argparse',   type=('build', 'run'))
This is probably only needed `when='^python@:2.6'`

2021-01-10 23:29 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-memprof/package.py
> +    url      = "https://github.com/jmdana/memprof/archive/v0.3.6.tar.gz"
https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#pypi-vs-github

2021-01-21 23:00 UTC, adamjstewart approved these changes

2021-01-22 13:06 UTC, alalazo approved these changes

2021-01-22 13:07 UTC, merged