New package: py-filterpy
LLNL/spack pull request #20747
Opened 2021-01-08 16:02 UTC by qwertos

2021-01-10 23:32 UTC, adamjstewart requested changes

2021-01-10 23:32 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-filterpy/package.py
> +    url      = "https://github.com/rlabbe/filterpy/archive/1.4.5.tar.gz"
https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#pypi-vs-github

2021-01-12 18:13 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-filterpy/package.py
> +    url = "https://pypi.io/packages/source/f/filterpy/filterpy-1.4.5.zip"
```suggestion
    pypi = "filterpy/filterpy-1.4.5.zip"
```

2021-01-21 23:02 UTC, adamjstewart approved these changes

2021-01-22 13:06 UTC, alalazo approved these changes

2021-01-22 13:06 UTC, merged