include libpng configuration in R spec
LLNL/spack pull request #20753
Opened 2021-01-08 17:06 UTC by jasonbuechler

appears (http://www.libpng.org/pub/png/libpng.html) libpng depends on zlib which is already a dependency for this spec so just added the variant, virtual dep, and args

2021-01-08 23:08 UTC, adamjstewart commented on var/spack/repos/builtin/packages/r/package.py
> +            config_args.append('--with-libpng')
Can you add an else clause that adds `--without-libpng`? Explicit is always better than implicit 😄

2021-01-11 08:30 UTC, alalazo commented on var/spack/repos/builtin/packages/r/package.py
> +            config_args.append('--with-libpng')
@jasonbuechler This case is so frequent in packaging (having a variant that triggers a `--with/--without` at configure time) that we have a one line convenience function for that:
```suggestion
        config_args += self.with_or_without('libpng')
```

2021-01-11 22:42 UTC, adamjstewart approved these changes

2021-01-17 20:14 UTC, adamjstewart commented
Flake8:
```
var/spack/repos/builtin/packages/r/package.py:58: [W291] trailing whitespace
```

2021-02-09 22:17 UTC, glennpj requested changes
As I commented in https://github.com/spack/spack/issues/20731#issuecomment-769470037, this PR does not enable graphics support without the `+X` variant. I think the best way to go is to not have a variant for `libpng` but to have the dependency for `libpng` set when the `+X` variant is set. That would also apply for `libtiff` and `jpeg` support.

2021-02-17 23:39 UTC, closed without merging