Zoltan: source code location change
LLNL/spack pull request #20787
Opened 2021-01-11 23:17 UTC by quellyn

Zoltan source code has been moved to GitHub. The old URL is no longer alive:

```shell
[quellyn@darwin-fe3 spack]$ spack stage zoltan
==> Fetching http://www.cs.sandia.gov/~kddevin/Zoltan_Distributions/zoltan_distrib_v3.83.tar.gz
######################################################################## 100.0%
==> Warning: The contents of the archive look like HTML.  Either the URL you are trying to use does not exist or you have an internet gateway issue.  You can remove the bad archive using 'spack clean <package>', then try again using the correct URL.
==> Error: sha256 checksum failed for /tmp/quellyn/spack-stage/spack-stage-zoltan-3.83-spri6lp5qiu4wov4mrj5k6rjys2urgs4/zoltan_distrib_v3.83.tar.gz
Expected d0d78fdeab7a385c87d3666b8a8dc748994ff04d3fd846872a4845e12d79c1bb but got 6680eb0d927e377c65177e20758407e42970f9a5036c73d7bd5121150edc0406
```

Thanks!
Quellyn

2021-01-12 12:38 UTC, alalazo requested changes
There's only one tarball in the repository. Also, why the tarballs are stored in a git repo instead of being independent artifacts?

2021-01-12 16:39 UTC, quellyn commented
> There's only one tarball in the repository. Also, why the tarballs are stored in a git repo instead of being independent artifacts?

Hi Massimiliano,

I'm not a maintainer of Zoltan, actually -- just a user. So I don't know why they adopted this approach. Perhaps we could ask @kddevin ?

Until recently they used to have the releases at the project page here: https://cs.sandia.gov/Zoltan/. Now it looks like they  are attempting to move the code to GitHub as they did with Trilinos.

Quellyn

2021-01-12 16:43 UTC, kddevin commented
Hi, @quellyn .  Sandia is retiring the server that we used for Zoltan downloads, so we moved the tarball to github.  

I am not familiar with how Zoltan is used in  spack/spack.   What do you need?  I can try to accommodate.

2021-01-12 16:46 UTC, alalazo commented
@kddevin Are the tarballs supposed to be stored within a git repository? Also, do you plan to publish other versions than just 3.83?

2021-01-12 17:21 UTC, quellyn commented
Hi Karen!

Thank you for the quick reply. @alalazo, perhaps if Zoltan followed the same structure as Trilinos? i.e., with a separate "Releases" page (https://github.com/trilinos/Trilinos/releases) that contained the source tarballs?

Q

2021-01-12 17:42 UTC, kddevin commented
I can make a separate releases page like Trilinos, if that is easier for Spack.
Which versions of Zoltan do you need?  By when do you need the change?

2021-01-12 17:51 UTC, quellyn commented
> I can make a separate releases page like Trilinos, if that is easier for Spack.

Great! @alalazo, would that suit? Moving the tarball to a Releases page would allow Karen to use the `.git` repo itself (where the tarball is currently located) to host Zoltan's source code development repository -- or she can simply delete the contents and point a user to the Trilinos project for the definitive Zoltan source code, if that's appropriate for them.

> Which versions of Zoltan do you need? By when do you need the change?

We are using version 3.83. I see that the Spack "recipe" for fetching and building Zoltan has entries for other releases:

> Preferred version:  
>     3.83    https://github.com/sandialabs/Zoltan/raw/main/zoltan_distrib_v3.83.tar.gz
> 
> Safe versions:  
>     3.83    https://github.com/sandialabs/Zoltan/raw/main/zoltan_distrib_v3.83.tar.gz
>     3.8     https://github.com/sandialabs/Zoltan/raw/main/zoltan_distrib_v3.8.tar.gz
>     3.6     https://github.com/sandialabs/Zoltan/raw/main/zoltan_distrib_v3.6.tar.gz
>     3.3     https://github.com/sandialabs/Zoltan/raw/main/zoltan_distrib_v3.3.tar.gz

If you'd rather only offer 3.83, I can remove the other versions from the recipe.

Thanks all!

Q

2021-01-12 20:09 UTC, kddevin commented
Does this release page work better for you?
https://github.com/sandialabs/Zoltan/releases/tag/v3.83

I will have only this release for now; please remove the "other safe versions."

2021-01-15 09:53 UTC, alalazo approved these changes

2021-01-15 09:59 UTC, alalazo commented
Thanks! Trying to check our built-in repository I didn't find any package depending explicitly on specific versions of Zoltan, so I'll go ahead and merge this PR as is. If people complain about missing versions that may still be found e.g. in our mirror I may get back to you and ask to re-add the old versions and hashes.

2021-01-15 09:59 UTC, merged

2021-01-19 19:21 UTC, quellyn commented
> Thanks! Trying to check our built-in repository I didn't find any package depending explicitly on specific versions of 
> Zoltan, so I'll go ahead and merge this PR as is. If people complain about missing versions that may still be found e.g. in 
> our mirror I may get back to you and ask to re-add the old versions and hashes.

Thanks, Massimiliano! Those older versions are pretty old, so I'd be surprised if anyone is using them -- but if so, perhaps @kddevin would be willing to put them up on the new downloads page.