rdma-core: require GCC 10+
LLNL/spack pull request #20783
Opened 2021-01-11 21:19 UTC by maxim-belkin

I believe rdma-core requires gcc 10 because symver attribute was added in GCC 10.
Related links:
 - https://gcc.gnu.org/onlinedocs/gcc-10.2.0/gcc/Common-Function-Attributes.html
 - https://github.com/linux-rdma/rdma-core/commit/f03f7022901466b6d6ead01e48a7057fa574cc3b

Not sure if this should be limited to some specific versions.

2021-01-13 19:06 UTC, adamjstewart commented
> Not sure if this should be limited to some specific versions.

This should definitely be limited to some specific versions, there have to be versions that can be built with older versions of GCC. You'll have to figure out when `symver` was added to the codebase.

2021-01-27 23:41 UTC, michaelkuhn requested changes
I don't think this change is correct. I managed to build rdma-core 33.1 (which includes the mentioned change) with both GCC 10.2 and 7.5.

2021-02-10 22:12 UTC, michaelkuhn commented
Can we close this?

2021-02-10 22:26 UTC, adamjstewart commented
I'm leaning towards closing this, unless @maxim-belkin has any other possible ideas for why `rdma-core` doesn't build on BW. Basically, there is a system/compiler combo for which this doesn't build, but it doesn't seem to be older GCC that's the problem. So the current conflict in this PR is definitely wrong, but there may be a different conflict that is more correct.

From what I can tell, @maxim-belkin has been a bit busy lately, so hasn't had as much time for Spack + BW stuff. Let's close this for now and we can reopen later or open a new PR if we do figure out what the exact build issue is. @maxim-belkin maybe you can open an issue with the build error and someone can take a look.

2021-02-10 22:26 UTC, closed without merging

2021-02-10 22:28 UTC, maxim-belkin commented
Can I see a log of a successful build with gcc below 10?