ssht: New version 1.3.4
LLNL/spack pull request #20880
Opened 2021-01-13 23:16 UTC by eschnett

ssht changed configuration mechanism from "home-grown" to "cmake. The previously current version 1.2b1 (a beta release) is thus unfortunately not available any more.

2021-01-15 08:58 UTC, alalazo requested changes
Just a minor comment, otherwise LGTM.

2021-01-15 08:58 UTC, alalazo commented on var/spack/repos/builtin/packages/ssht/package.py
> +        return args
You should be able to omit this:
```suggestion
```
since it's taken care of by the base class.

2021-01-15 13:56 UTC, alalazo approved these changes

2021-01-19 04:57 UTC, adamjstewart approved these changes
The usual discussion of "should we drop the old version or should we support multiple build systems" applies here, but @eschnett is the maintainer of this package, so I'll defer to his decision to drop the old version instead of supporting both.

2021-01-19 04:57 UTC, merged