fixing outdated metis link
LLNL/spack pull request #21003
Opened 2021-01-16 05:17 UTC by mlawsonca

2021-01-16 19:21 UTC, adamjstewart requested changes
I'm not sure what happened to the download link. It looks like the GitHub page now only has a newer release, so maybe they simply removed the last release? http://glaros.dtc.umn.edu/gkhome/metis/metis/download has the 5.1.0 release as well, while http://glaros.dtc.umn.edu/gkhome/fsroot/sw/metis/OLD has older versions. I wonder if we should consider that website more stable than the GitHub if they decide to keep removing old releases.

2021-01-16 19:21 UTC, adamjstewart commented on var/spack/repos/builtin/packages/metis/package.py
> +    #url      = "https://github.com/scivision/METIS/raw/master/metis-5.1.0.tar.gz"
Delete this line

2021-01-16 19:28 UTC, adamjstewart commented
Opened https://github.com/scivision/METIS/issues/3 to investigate more.

2021-01-16 19:36 UTC, adamjstewart commented
It looks like the current URL was introduced by @cyrush in #13709. From what I can tell, this GitHub repo is an unofficial mirror and only contains the latest version. Now that we have Spack mirrors for things, I think it would be better to switch back to the old `url`/`list_url`. @cyrush thoughts?

2021-01-16 19:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/metis/package.py
> +    #url      = "https://github.com/scivision/METIS/raw/master/metis-5.1.0.tar.gz"
Also, can you switch to:
```python
    homepage = "http://glaros.dtc.umn.edu/gkhome/metis/metis/overview"
    url      = "http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz"
    list_url = "http://glaros.dtc.umn.edu/gkhome/fsroot/sw/metis/OLD"
```
Then you can remove the URL from 4.0.3.

2021-01-19 18:49 UTC, cyrush commented
@adamjstewart I also vote for using the official urls + spack mirror.

2021-01-19 22:58 UTC, adamjstewart approved these changes

2021-01-19 22:58 UTC, merged

2021-01-19 22:58 UTC, adamjstewart commented
Thanks @mlawsonca!