sortmerna: Fix for aarch64
LLNL/spack pull request #21126
Opened 2021-01-18 06:30 UTC by t-nojiri

I made a fix to be able to install on aarch64.
I also fixed the following installation error that was also occurring on x86_64.
         20    def install(self, spec, prefix):
         21        mkdirp(prefix.bin)
  >>     22        with working_dir(join_path('spack-build', 'src', 'indexdb')):
         23            install('indexdb', prefix.bin)

2021-01-18 18:51 UTC, adamjstewart requested changes

2021-01-18 18:51 UTC, adamjstewart commented on var/spack/repos/builtin/packages/sortmerna/package.py
> +    build_directory = 'spack-build'
Instead of changing this, let's use `self.build_directory` below instead of `'spack-build'`.

2021-01-19 04:25 UTC, t-nojiri commented
I modified it to use self.build_directory.

2021-01-19 04:49 UTC, adamjstewart commented on var/spack/repos/builtin/packages/sortmerna/package.py
> +    build_directory = 'spack-build'
You can remove this line now.

2021-01-19 06:56 UTC, t-nojiri commented
I have confirmed that I can remove the build_directory and build.

2021-01-19 15:01 UTC, adamjstewart approved these changes

2021-01-19 15:01 UTC, merged