py-iminuit: update version to fix test error
LLNL/spack pull request #21143
Opened 2021-01-19 07:03 UTC by darmac

`python setup.py test` failed as follow in version `1.3.6`:
![image](https://user-images.githubusercontent.com/29532367/104999198-6d7d6d80-5a67-11eb-918c-9cf0def8ba06.png)

And `1.3.7` is OK now.

2021-01-19 07:26 UTC, alalazo approved these changes

2021-01-19 15:54 UTC, adamjstewart requested changes
Could you make the numpy dependency more specific: `py-numpy@1.11.3:`

2021-01-20 03:09 UTC, darmac commented
How about this?
https://github.com/spack/spack/pull/21143/commits/a698f570994d0c046648919fff7d109f74366318

2021-01-20 03:47 UTC, adamjstewart commented
I meant the version of numpy, not the when arg.

2021-01-20 05:46 UTC, darmac commented
> I meant the version of numpy, not the when arg.

sorry, that's a mistake XD

2021-01-20 19:22 UTC, adamjstewart approved these changes

2021-01-20 19:22 UTC, merged