systemtap: Add depend
LLNL/spack pull request #21163
Opened 2021-01-20 06:24 UTC by t-nojiri

When I built this OSS on x86_64 and aarch64 machines, I got the following error:
coveragedb.cxx:20:10: fatal error: sqlite3.h: No such file or directory
     240     #include <sqlite3.h>

I confirmed that it can be built by adding depend of sqlite and py-setuptools.

2021-01-20 19:43 UTC, adamjstewart requested changes

2021-01-20 19:43 UTC, adamjstewart commented on var/spack/repos/builtin/packages/systemtap/package.py
>      depends_on('elfutils')
```suggestion
    depends_on('elfutils@0.151:')
```

2021-01-20 19:43 UTC, adamjstewart commented on var/spack/repos/builtin/packages/systemtap/package.py
> +    depends_on('py-setuptools')
```suggestion
    depends_on('py-setuptools', type='build')
    depends_on('python', type=('build', 'run'))
```

2021-01-21 02:20 UTC, t-nojiri commented
I've confirmed that I can fix and build as pointed out.

2021-01-21 03:30 UTC, adamjstewart approved these changes

2021-01-21 03:31 UTC, merged