Spack checkout command
LLNL/spack pull request #21231
Opened 2021-01-23 02:19 UTC by becker33

This PR adds a `spack checkout` command to update the spack source to a particular git revision.

This PR builds on the "deployment mode" feature to restrict `spack checkout` to the origin remote when in deployment mode. This will allow users with permission to run Spack, but not to modify the source, to select a git revision to use.

Requires #21189

2021-04-01 07:26 UTC, tgamblin requested changes
@becker33: some requests for simplification, some comments, and can you please expand on the PR description?  I am not sure I fully understand the use cases this is meant to support, so if you could list them in the description that would be useful.

2021-04-01 07:26 UTC, tgamblin commented on lib/spack/spack/cmd/checkout.py
> +        remote_url = git('remote', 'get-url', remote, output=str, error=str)
Instead of calling `git` N times, just use `git remote -v`. You can split on `\n` and then `\t` and filter for `(fetch)`.

2021-04-01 07:26 UTC, tgamblin commented on lib/spack/spack/cmd/checkout.py
> +        git('remote', 'add', remote, url)
Can this be simplified?  I don't think we should add remotes here -- the user can do that themselves.  Git can already fetch from a remote by URL (no name required), so why not:

1. make `--url` and `-r` mutually exclusive
2. disable both in deployment mode

That avoids the kind of weird semantics where Spack adds the remote to the repo.

This also avoids the need to validate that a URL matches what is on file for a remote.

2021-04-01 07:26 UTC, tgamblin commented on lib/spack/spack/cmd/checkout.py
> +    git = which('git', required=True)
can you just move the `which` into a memoized function and avoid the global?

```
git = get_git()
```

2021-04-01 07:26 UTC, tgamblin commented on lib/spack/spack/cmd/checkout.py
> +_SPACK_UPSTREAM = 'https://github.com/spack/spack'
is this used?

2021-04-01 07:26 UTC, tgamblin commented on lib/spack/spack/cmd/checkout.py
> +description = "update the spack prefix or subcomponent to a git ref"
what's a subcomponent?

2021-04-01 07:26 UTC, tgamblin commented on lib/spack/spack/cmd/checkout.py
> +        help="checkout an environment instead of the Spack source")
Where does the environment go?  This one's confusing to me -- what's it supposed to do?  Check out a named env within spack?

2021-04-01 07:26 UTC, tgamblin commented on lib/spack/spack/cmd/checkout.py
> +    # Set the appropriate workdir if we are modifying an environment or repo
don't use "appropriate" -- be specific -- what makes it appropriate?  "appropriate" assumes the reader of your comment knows what is appropriate already.

2021-04-01 07:26 UTC, tgamblin commented on lib/spack/spack/cmd/checkout.py
> +            raise ValueError("'%s' is not a valid Spack environment." %
can just omit "valid" here -- just say it's not an environment.

2021-04-01 07:26 UTC, tgamblin commented on lib/spack/spack/cmd/checkout.py
> +                             args.repo)
Does the repo have to be registered?  It looks like it here.  `--repo` just says to update that particular repo from some git URL?

2023-02-20 10:31 UTC, alalazo commented
Can we close this one, since the required PR has been closed?

2023-06-22 23:19 UTC, alecbcs commented
@becker33 should we close this PR in favor of #37549? Is there any particular functionality you'd like from this PR that isn't covered by `spack update -b`?

2024-03-06 22:44 UTC, closed without merging