New package: py-pythonsollya
LLNL/spack pull request #21241
Opened 2021-01-23 09:44 UTC by iarspider

Split from #21218. Depends on #21240 (sollya),  #21238 (mpfi) and #21239 (py-bigfloat)

2021-01-23 17:07 UTC, adamjstewart requested changes

2021-01-23 17:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pythonsollya/package.py
> +    version('0.4.0-alpha0', sha256='faac899744c92b1d20980cadef309cd5610d79722322e97940ff142c207c41b5')
I don't know if we want to default to an alpha release, as it likely isn't stable. It would be better to add `preferred=True` to 0.3.0

2021-01-23 17:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pythonsollya/package.py
> +    depends_on('py-pip', type='build')
Pip isn't needed

2021-01-23 17:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pythonsollya/package.py
> +    depends_on('mpfi', type=('build', 'link'))
Missing a dep on `py-six`

2021-01-23 22:28 UTC, adamjstewart approved these changes

2021-01-25 12:44 UTC, alalazo approved these changes

2021-01-25 12:44 UTC, merged