pbbam: Fix install_tree
LLNL/spack pull request #21252
Opened 2021-01-25 06:38 UTC by t-nojiri

I fixed the following error.
OSError: No such file or directory: 'pbbam'

./spack/var/spack/repos/builtin/packages/pbbam/package.py:40, in install:
         37        with working_dir(self.build_directory):
         38            install_tree('bin', prefix.bin)
         39            install_tree('lib', prefix.lib)
  >>     40            install_tree('pbbam', prefix.include.pbbam)

I have confirmed that it can be built on x86_64 and aarch64 machines.

2021-01-25 06:57 UTC, alalazo requested changes
Is it correct to rename a subdirectory named "generated" into "pbbam" in prefix? Or should it be called "generated" as well?

As an aside not (not requiring to do it in this PR), the current version we ship for this package (v0.18.0) is from 2018.  currently `pbbam` is at version 1.6.0.

2021-01-25 07:24 UTC, t-nojiri commented
I recognized the name "generated" as a temporary name at build time.
I didn't change the installation location.

2021-01-25 07:54 UTC, t-nojiri commented
I did a build of version 1.6.0.
Under include was pbbam.
$ ls ./spack/opt/spack/linux-rhel8-haswell/gcc-8.3.1/pbbam-1.6.0-biqdaagqrccq5noln5ydjuzxlf5krbv7/include/
pbbam

Should I change to a PR that adds version 1.6.0?

2021-01-25 08:16 UTC, alalazo commented
> Should I change to a PR that adds version 1.6.0?

@t-nojiri That would be good, thanks.

2021-01-26 02:40 UTC, t-nojiri commented
I'm going to fix it to a recipe for 1.6.0 only, should I keep version 0.18.0 as well?

2021-01-27 08:33 UTC, alalazo commented
> I'm going to fix it to a recipe for 1.6.0 only, should I keep version 0.18.0 as well?

Yes, please. We should do that until we have a clear deprecation policy.

2021-01-28 01:10 UTC, t-nojiri commented
The v1.6.0 build script uses the Meson Package. 
The 0.18.0 build script is CMakePackage.
I have different build scripts for each of the two versions, so I would like to change to a recipe that is only v1.6.0.
Is that okay?

2022-02-11 14:09 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2022-02-11 14:09 UTC, closed without merging