allow multiple identical deps from CLI
LLNL/spack pull request #21262
Opened 2021-01-25 18:49 UTC by becker33

Currently, Spack can fail for a valid spec if the spec is constructed from overlapping, but not conflicting, concrete specs via the hash.

For example, if `abcdef` and `ghijkl` are the hashes of specs that both depend on `zlib/mnopqr`, then `foo ^/abcdef ^/ghijkl` will fail to construct a spec, with the error message "Cannot depend on zlib... twice".

This PR changes this behavior to check whether the specs are identical before failing.

With this PR, `foo ^/abcdef ^/ghijkl` will concretize.

As a side-effect, so will `foo ^zlib ^zlib` and other specs that are redundant on their dependencies.

2021-01-25 20:15 UTC, becker33 commented
@Paul-Ferrell I had to make a couple changes for a bug the unit tests turned up, this should still cover your use case from slack.

2021-01-28 13:33 UTC, sethrj approved these changes, later dismissed
Excellent! I think this will fix https://github.com/spack/spack/issues/19694 , which I come across from time to time when trying to install new packages based on existing specs after having updated spack.

2021-05-11 00:35 UTC, omor1 commented on lib/spack/spack/spec.py
> +            if dspec.spec != orig.spec or dspec.deptypes != orig.deptypes:
if `spec.name` is already in `self._dependencies` _and_ `orig.spec == spec and orig.deptypes == deptypes`, why do we need to reset `self._dependencies[spec.name]` and `spec._dependents[self.name]`?

2021-05-11 00:35 UTC, omor1 commented on lib/spack/spack/spec.py
> +            if dspec.spec != orig.spec or dspec.deptypes != orig.deptypes:
```python
if spec.name in self._dependencies:
    orig = self._dependencies[spec.name]
    if orig.spec == spec and orig.deptypes == deptypes:
        return
    else:
        raise DuplicateDependencyError(
            "Cannot depend on conflicting abstract specs %s and %s" %
            (spec, orig.spec))

# create an edge and add to parent and child
dspec = DependencySpec(self, spec, deptypes)
self._dependencies[spec.name] = dspec
spec._dependents[self.name] = dspec
```

2021-05-11 00:40 UTC, omor1 commented
My original fix suggestion (in #19782) used `self._dependencies[spec.name].spec.satisfies(spec, strict=True)`; I don't know if that's more or less correct.

2022-11-04 18:34 UTC, becker33 commented
@spackbot fix style

2022-11-05 10:31 UTC, haampie requested changes
To me this is still too pedantic, why not constrain the original dep with the new dep? That way `x ^y ^y@1` works and `x ^y@1: ^y@:2` becomes `x ^y@1:2` etc.

2022-11-05 17:38 UTC, becker33 commented
@haampie I modified it to constrain if the deptypes are the same, I think that should be enough for most reasonable use cases, and I think with changing deptypes we need to consider what we want the behavior to be in light of our plans to add cross compiling support. Does this work for you?

2022-11-05 18:42 UTC, becker33 commented
For reference, the untested code in this PR is currently unreachable, but is defensive against future changes in how we handle deptypes.

2022-11-05 22:24 UTC, haampie approved these changes

2022-11-05 22:43 UTC, haampie commented on lib/spack/spack/spec.py
> +                raise DuplicateDependencyError("Cannot depend on '%s' twice" % spec)
```suggestion
            orig = self._dependencies[spec.name]

            try:
                dspec = next(dspec in orig if deptypes == dspec.deptypes)
            except StopIteration:
                raise DuplicateDependencyError("Cannot depend on '%s' twice" % spec)

            try:
                dspec.spec.constrain(spec)
            except spack.error.UnsatisfiableSpecError:
                raise DuplicateDependencyError(
                    "Cannot depend on incompatible specs '%s' and '%s'" % (dspec.spec, spec)
                )
```

i still don't like deeply nested control flow, just leaving this as a suggestion.

2022-11-06 19:30 UTC, merged