ParaView: add ParaView-5.9.0 new release
LLNL/spack pull request #21268
Opened 2021-01-25 20:34 UTC by vicentebolea

Finally! ParaView 5.9.0 release is out :tada: :tada: :tada:

This PR updates the ParaView Spack package to use this new release instead of its last Release Candidate that was very recently added.

This also changes the preferred release from the version 5.8.1 -> 5.9.0

Let me know if we need to change anything else in the package

2021-01-25 21:11 UTC, haampie commented
Hi @vicentebolea, you can drop the `preferred=True` altogether, it is selected by default

2021-01-25 21:48 UTC, chuckatkins requested changes
Echoing @haampie to drop the `preferred=True` now that the RCs are done

2021-01-26 19:34 UTC, vicentebolea commented
@chuckatkins @haampie please find the `preferred=True` removed in the last push

2021-01-26 19:34 UTC, chuckatkins approved these changes

2021-01-26 19:51 UTC, haampie approved these changes

2021-01-26 21:58 UTC, merged