mxnet: Add optional cuda_arch support, allows building against a subset of cuda architectures
LLNL/spack pull request #21266
Opened 2021-01-25 20:03 UTC by jonglezb

2021-01-25 20:07 UTC, adamjstewart requested changes
Can you remove the `cuda` variant from the package since it is now added by `CudaPackage` instead?

2021-01-25 20:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/mxnet/package.py
> +                args.append('CUDA_ARCH={}'.format(' '.join(self.cuda_flags(cuda_arch))))
```suggestion
                args.append('CUDA_ARCH={0}'.format(' '.join(self.cuda_flags(cuda_arch))))
```
Needed for Python 2.6 support

2021-01-25 20:10 UTC, jonglezb commented on var/spack/repos/builtin/packages/mxnet/package.py
> +                args.append('CUDA_ARCH={}'.format(' '.join(self.cuda_flags(cuda_arch))))
Indeed, thanks.

2021-01-25 20:12 UTC, jonglezb commented
> Can you remove the `cuda` variant from the package since it is now added by `CudaPackage` instead?

Good catch, I thought it would change the default, but in fact it's fine (the cuda variant is disabled by default)

2021-01-25 20:12 UTC, adamjstewart approved these changes

2021-01-25 20:14 UTC, adamjstewart commented
We can change the default to True if you want, that's how PyTorch and TF are.

2021-01-25 20:16 UTC, jonglezb commented
> We can change the default to True if you want, that's how PyTorch and TF are.

Good idea. I would also disable opencv by default, because it's currently broken (at least on ppc64le, I haven't checked x86_64).

2021-01-25 20:30 UTC, adamjstewart commented
mxnet + opencv is broken or you just can't build opencv on your system? I don't have access to ppc64le, but it should work on x86_64.

2021-01-25 20:34 UTC, jonglezb commented
It's mxnet that fails to build against opencv (but opencv is also picky about GCC version on ppc64le, it doesn't build with GCC 8 while it builds with GCC 10.2)

I'll try again and open a separate bug report about it.

2021-01-25 21:45 UTC, jonglezb commented
Let's merge this and change the default value in another PR?

2021-01-26 00:06 UTC, adamjstewart commented
Just to be clear, I'm proposing changing the default for `mxnet`, not for `CudaPackage`. So this would involve adding back the line that gets deleted here and switching the default to True. Might be easier to do that in this PR instead of deleting the line.

2021-01-26 07:28 UTC, jonglezb commented
> Just to be clear, I'm proposing changing the default for `mxnet`, not for `CudaPackage`. So this would involve adding back the line that gets deleted here and switching the default to True. Might be easier to do that in this PR instead of deleting the line.

Ok, done.

2021-01-26 13:58 UTC, merged