New package: py-deeplabcut
LLNL/spack pull request #21300
Opened 2021-01-26 19:24 UTC by qwertos

2021-01-26 21:22 UTC, adamjstewart requested changes

2021-01-26 21:22 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-deeplabcut/package.py
> +    depends_on("py-numpy@1.16.4:1.999", type=('build', 'run'))
```suggestion
    depends_on("py-numpy@1.16.4", type=('build', 'run'))
```

2021-01-26 21:22 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-deeplabcut/package.py
> +    depends_on("py-setuptools", type=('build', 'run'))
You can remove this above so it's not duplicated

2021-06-12 11:40 UTC, alalazo commented
@qwertos Can you please rebase and ping me and @adamjstewart back?

2021-06-14 14:32 UTC, qwertos commented
@alalazo @adamjstewart rebased and pinged

2021-06-14 15:00 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-deeplabcut/package.py
> +    depends_on("opencv+python", type=('build', 'run'))
I changed the `opencv` package so now there is no `+python` variant. As far as I can tell, `deeplabcut` only supports Python 3? So I would change this:
```suggestion
    depends_on("opencv+python3", type=('build', 'run'))
```

2021-06-14 15:00 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-deeplabcut/package.py
> +    depends_on("py-pandas@1.0.1:1.1.999", type=('build', 'run'))
Where does this upper bound come from?

2021-06-14 15:00 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-deeplabcut/package.py
> +    depends_on('py-setuptools', type='build')
Can you check if this is needed at run-time?

2021-06-14 15:00 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-deeplabcut/package.py
> +    depends_on("py-cython", type=('build', 'run'))
Can you check if this is needed at run-time?

2021-09-08 12:56 UTC, alalazo commented
@qwertos

2022-01-25 11:16 UTC, alalazo commented
Closing this PR as stale, but feel free to reopen if you want to continue working on it.

2022-01-25 11:16 UTC, closed without merging