py-atpublic: new recipe
LLNL/spack pull request #21332
Opened 2021-01-27 14:18 UTC by Andrew-Dunning-NNL

add py-atpublic recipie

2021-01-27 20:44 UTC, adamjstewart requested changes

2021-01-27 20:44 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-atpublic/package.py
> +    depends_on('py-typing-extensions@:3.8', type=('build', 'run'))
```suggestion
    depends_on('py-typing-extensions', when='^python@:3.7.999', type=('build', 'run'))
```

2021-02-02 12:51 UTC, Andrew-Dunning-NNL commented on var/spack/repos/builtin/packages/py-atpublic/package.py
> +    depends_on('py-typing-extensions@:3.8', type=('build', 'run'))
Corrected py-typing-extensions dependency

2021-02-02 17:18 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-atpublic/package.py
> +    depends_on('py-typing-extensions', when='^python@:3.8', type=('build', 'run'))
```suggestion
    depends_on('py-typing-extensions', when='^python@:3.7.999', type=('build', 'run'))
```
It isn't needed in 3.8, version ranges are inclusive in Spack

2021-02-02 18:21 UTC, adamjstewart approved these changes

2021-02-03 19:53 UTC, Andrew-Dunning-NNL commented
@adamjstewart Hello Adam! Did this package need something else to be merged?

2021-02-03 19:53 UTC, merged