py-ftfy: new recipe
LLNL/spack pull request #21333
Opened 2021-01-27 14:18 UTC by Andrew-Dunning-NNL

ad py-ftfy recipe

2021-01-27 20:43 UTC, adamjstewart requested changes

2021-01-27 20:43 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ftfy/package.py
> +    depends_on('python@3:', type=('build', 'run'))
```suggestion
    depends_on('python@3.5:', type=('build', 'run'))
```

2021-02-02 12:50 UTC, Andrew-Dunning-NNL commented on var/spack/repos/builtin/packages/py-ftfy/package.py
> +    depends_on('python@3:', type=('build', 'run'))
Added python 3.5 dependency

2021-02-02 17:18 UTC, adamjstewart approved these changes

2021-02-02 17:19 UTC, merged