py-dulwich: new recipe
LLNL/spack pull request #21330
Opened 2021-01-27 14:17 UTC by Andrew-Dunning-NNL

Add py-dulwich python package

2021-01-27 20:49 UTC, adamjstewart requested changes

2021-01-27 20:49 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-dulwich/package.py
> +
Add:
```python
depends_on('python@3.5:', type=('build', 'run'))
```

2021-02-02 12:53 UTC, Andrew-Dunning-NNL commented on var/spack/repos/builtin/packages/py-dulwich/package.py
> +
Added python Dependency

2021-02-02 17:15 UTC, adamjstewart approved these changes

2021-02-02 17:15 UTC, merged