py-flufl-lock: new recipe
LLNL/spack pull request #21334
Opened 2021-01-27 14:18 UTC by Andrew-Dunning-NNL

add py-flufl-lock recipe

2021-01-27 20:42 UTC, adamjstewart requested changes

2021-01-27 20:42 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-flufl-lock/package.py
> +    depends_on('py-typing-extensions@:3.8', type=('build', 'run'))
```suggestion
    depends_on('py-typing-extensions', when='^python@:3.7.999', type=('build', 'run'))
```

2021-02-02 12:48 UTC, Andrew-Dunning-NNL commented on var/spack/repos/builtin/packages/py-flufl-lock/package.py
> +    depends_on('py-typing-extensions@:3.8', type=('build', 'run'))
fixed py-typing-extensions dependency

2021-02-02 17:20 UTC, adamjstewart submitted a review, later dismissed

2021-02-04 01:19 UTC, Andrew-Dunning-NNL commented
I rebased now that this packages dependencies are in develop

2021-02-04 03:15 UTC, adamjstewart approved these changes

2021-02-04 03:15 UTC, merged