py-grandalf: new recipe
LLNL/spack pull request #21348
Opened 2021-01-27 16:25 UTC by Andrew-Dunning-NNL

add new package py-grandalf

2021-01-27 16:28 UTC, Andrew-Dunning-NNL commented
This python package recipe uses github because the grandalf source tar is not in pypi

2021-01-27 19:47 UTC, tldahlgren approved these changes, later dismissed
Confirmed the versions are available at the specified URL.

2021-01-27 19:47 UTC, tldahlgren commented
@adamjstewart Do you want to review this package?

2021-01-27 20:24 UTC, adamjstewart requested changes

2021-01-27 20:24 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-grandalf/package.py
> +    depends_on('py-pyparsing', type='build')
```suggestion
    depends_on('py-pyparsing', type=('build', 'run'))
```

2021-02-02 12:42 UTC, Andrew-Dunning-NNL commented on var/spack/repos/builtin/packages/py-grandalf/package.py
> +    depends_on('py-pyparsing', type='build')
added runtime dependency

2021-02-02 17:22 UTC, adamjstewart approved these changes

2021-02-02 17:22 UTC, merged