add new package: bloaty
LLNL/spack pull request #21355
Opened 2021-01-27 19:12 UTC by cyrush

2021-01-27 19:30 UTC, tldahlgren commented on var/spack/repos/builtin/packages/bloaty/package.py
> +    depends_on('cmake')
This should not be necessary when you inherit from `CMakePackage` since it is already specified as a `build` dependency.

2021-01-27 19:35 UTC, tldahlgren commented on var/spack/repos/builtin/packages/bloaty/package.py
> +    depends_on('cmake')
Also confirmed the version of the package is available at the specified URL.

2021-01-27 19:39 UTC, tldahlgren requested changes
Suggest remove dependency `CMake` dependency unless needed for more than `build` dependency.

2021-01-27 21:24 UTC, cyrush commented
@tldahlgren thanks -- I'll remove the cmake dep. 
( stuck in my old spack ways )

2021-01-27 21:35 UTC, tldahlgren commented
> @tldahlgren thanks -- I'll remove the cmake dep.
> ( stuck in my old spack ways )

Np.

2021-01-27 21:35 UTC, tldahlgren requested changes
Please resolve the flake8 error (too):

- var/spack/repos/builtin/packages/bloaty/package.py:22: [W391] blank line at end of file

2021-01-29 00:38 UTC, cyrush commented
@tldahlgren made the suggested changes + I think things look good now.

2021-01-29 00:43 UTC, tldahlgren approved these changes
LGTM.

2021-01-29 00:44 UTC, merged

2021-01-29 00:44 UTC, tldahlgren commented
Thank you for your contribution!

2021-01-29 00:57 UTC, cyrush commented
@tldahlgren  thanks!