py-cheetah: Add python2 depend and version 2.4.4
LLNL/spack pull request #21363
Opened 2021-01-28 02:48 UTC by t-nojiri

I have fixed the following issues:
  File "./spack-stage/spack-stage-py-cheetah-2.3.0-turnatpttuedmc2gm5dzckrsabw5nhgw/spack-src/SetupTools.py", line 50
    except DistutilsPlatformError, x:
                                                 ^
SyntaxError: invalid syntax

I also verified the latest version of 2.4.4 during the course of this investigation.
Include a fix that adds 2.4.4 to this PR.

2021-01-28 02:53 UTC, adamjstewart requested changes
It looks like there is also a Cheetah3 on PyPI if anyone needs Python 3 support. Cheetah2 is apparently no longer maintained: https://cheetahtemplate.org/roadmap.html#cheetah-v2

2021-01-28 02:53 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cheetah/package.py
> +    depends_on('python@2:2.99.999', type=('build', 'run'))
Missing dependencies:
```python
depends_on('py-setuptools', type='build')
depends_on('py-markdown@2.0.1:', type=('build', 'run'))
```

2021-01-28 04:05 UTC, t-nojiri commented on var/spack/repos/builtin/packages/py-cheetah/package.py
> +    depends_on('python@2:2.99.999', type=('build', 'run'))
I make a fix that adds version 3.2.6.

2021-01-28 04:52 UTC, adamjstewart commented
Cheetah3 should be a different package since it was renamed on PyPI.

2021-01-29 04:36 UTC, t-nojiri commented
I was misunderstanding.
I will undo the fix for this PR.
I will add Cheetah3 as a separate package.

2021-01-29 04:37 UTC, adamjstewart approved these changes

2021-01-29 08:43 UTC, alalazo approved these changes

2021-01-29 08:43 UTC, merged