r-rmariadb: add mariadb library path
LLNL/spack pull request #21406
Opened 2021-01-30 09:14 UTC by darmac

`r-rmariadb` build failed caused by the mariadb lib path error:
```
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'RMariaDB' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/spack-develop/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-rmariadb-1.0.8-sopsqypom7c4mfpzrwtgu5ftrq3ggnrg/rlib/R/library/00LOCK-spack-src/00new/RMariaDB/libs/RMariaDB.so':
  libmariadb.so.3: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing '/home/spack-develop/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-rmariadb-1.0.8-sopsqypom7c4mfpzrwtgu5ftrq3ggnrg/rlib/R/library/RMariaDB'
```

2021-01-30 19:47 UTC, glennpj commented
This looks like a problem with getting `libmariadb` in the RPATH. It may be picking up system libraries instead. Setting LD_LIBRARY_PATH is not correct though. Instead, pass `--configure-vars='INCLUDE_DIR=/.../include LIB_DIR=/.../lib` to set the path to the mariadb library and include directories in a `configure_args` function.

2021-01-30 19:48 UTC, glennpj requested changes

2021-01-30 19:48 UTC, glennpj commented on var/spack/repos/builtin/packages/r-rmariadb/package.py
> +                         self.spec['mariadb-client'].prefix.lib.mariadb)
Set the library and include directories in
```
def configure_args(self, spec, prefix):
```

2021-02-02 06:31 UTC, darmac commented
I added a config like this:
```
    def configure_vars(self):
        args = ['LIB_DIR=%s' % self.spec['mariadb-client'].prefix.lib.mariadb,
                'INCLUDE_DIR=%s' % self.spec['mariadb-client'].prefix.include.mariadb]                                                                                                                                                           
        return args
```

But it still cannot work, any sugesttion for that?
```
==> r-rmariadb: Executing phase: 'install'
==> [2021-02-02-14:23:28.673051] '/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/bin/R' 'CMD' 'INSTALL' '--configure-vars=LIB_DIR=/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/mariadb-c-client-3.1.9-p634wzoiiwxvtgkmzoejdbkjcpav5w5g/lib/mariadb INCLUDE_DIR=/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/mariadb-c-client-3.1.9-p634wzoiiwxvtgkmzoejdbkjcpav5w5g/include/mariadb' '--library=/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-rmariadb-1.0.8-dqxjmgknej6jkeu3vkglpkcdsc5dkgli/rlib/R/library' '/home/stage/root/spack-stage-r-rmariadb-1.0.8-dqxjmgknej6jkeu3vkglpkcdsc5dkgli/spack-src'
* installing *source* package 'RMariaDB' ...
** package 'RMariaDB' successfully unpacked and MD5 sums checked
** using staged installation
Using mariadb_config
WARNING: Connector versions prior to 2.3.4/3.0.3 have a known problem with retrieving string and blob data. See https://github.com/r-dbi/RMariaDB/issues/53 for details.
Found INCLUDE_DIR and/or LIB_DIR!
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf.spack:172: warning: overriding recipe for target '.c.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf:172: warning: ignoring old recipe for target '.c.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf.spack:174: warning: overriding recipe for target '.c.d'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf:174: warning: ignoring old recipe for target '.c.d'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf.spack:177: warning: overriding recipe for target '.m.d'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf:177: warning: ignoring old recipe for target '.m.d'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf.spack:179: warning: overriding recipe for target '.cc.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf:179: warning: ignoring old recipe for target '.cc.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf.spack:181: warning: overriding recipe for target '.cpp.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf:181: warning: ignoring old recipe for target '.cpp.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf.spack:183: warning: overriding recipe for target '.cc.d'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf:183: warning: ignoring old recipe for target '.cc.d'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf.spack:186: warning: overriding recipe for target '.cpp.d'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf:186: warning: ignoring old recipe for target '.cpp.d'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf.spack:189: warning: overriding recipe for target '.m.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf:189: warning: ignoring old recipe for target '.m.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf.spack:191: warning: overriding recipe for target '.mm.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf:191: warning: ignoring old recipe for target '.mm.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf.spack:193: warning: overriding recipe for target '.M.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf:193: warning: ignoring old recipe for target '.M.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf.spack:195: warning: overriding recipe for target '.f.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf:195: warning: ignoring old recipe for target '.f.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf.spack:198: warning: overriding recipe for target '.f95.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf:198: warning: ignoring old recipe for target '.f95.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf.spack:200: warning: overriding recipe for target '.f90.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf:200: warning: ignoring old recipe for target '.f90.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf.spack:172: warning: overriding recipe for target '.c.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf:172: warning: ignoring old recipe for target '.c.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf.spack:174: warning: overriding recipe for target '.c.d'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf:174: warning: ignoring old recipe for target '.c.d'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf.spack:177: warning: overriding recipe for target '.m.d'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf:177: warning: ignoring old recipe for target '.m.d'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf.spack:179: warning: overriding recipe for target '.cc.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf:179: warning: ignoring old recipe for target '.cc.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf.spack:181: warning: overriding recipe for target '.cpp.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf:181: warning: ignoring old recipe for target '.cpp.o'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf.spack:183: warning: overriding recipe for target '.cc.d'
/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/r-4.0.3-rrhlzbbvznxhirnfag66fwfach6a77ma/rlib/R/etc/Makeconf:183: warning: ignoring old recipe for target '.cc.d'
/home/spack/opt/sp [...]

2021-02-03 01:37 UTC, glennpj commented
@darmac I am going to have to poke at this a bit. I am not sure why it is still failing.

2021-02-03 02:49 UTC, darmac commented
> @darmac I am going to have to poke at this a bit. I am not sure why it is still failing.

Got, thanks so much, anyway, change `LD_LIBRARY_PATH` could work. 
So I think the upstream source code is OK.

2021-02-03 05:00 UTC, glennpj commented
The configure script is not setting RPATH. Add the following patch:
```
--- a/configure 2021-01-05 23:26:04.000000000 -0600
+++ b/configure 2021-02-02 22:19:12.494164119 -0600
@@ -27,7 +27,7 @@
 if [ "$INCLUDE_DIR" ] || [ "$LIB_DIR" ]; then
   echo "Found INCLUDE_DIR and/or LIB_DIR!"
   PKG_CFLAGS="-I$INCLUDE_DIR $PKG_CFLAGS"
-  PKG_LIBS="-L$LIB_DIR $PKG_LIBS"
+  PKG_LIBS="-L$LIB_DIR -Wl,-rpath,$LIB_DIR $PKG_LIBS"
 elif [ "$PKGCONFIG_CFLAGS" ] || [ "$PKGCONFIG_LIBS" ]; then
   echo "Found mysql_config cflags and libs!"
   PKG_CFLAGS=${PKGCONFIG_CFLAGS}
```
If you call that `configure.patch`, for example, also add the patch line to the package file.
```
patch('configure.patch')
```

2021-02-03 05:03 UTC, glennpj commented
> def configure_vars(self):
>         args = ['LIB_DIR=%s' % self.spec['mariadb-client'].prefix.lib.mariadb,
>                 'INCLUDE_DIR=%s' % self.spec['mariadb-client'].prefix.include.mariadb]                                                                                                                                                           
>         return args

Could you use the new style formatting here?
```python
   def configure_vars(self):
        args = [
            'LIB_DIR={0}'.format(self.spec['mariadb-client'].prefix.lib.mariadb),
            'INCLUDE_DIR={0}'.format(self.spec['mariadb-client'].prefix.include.mariadb)
        ]
        return args
```

2021-02-03 06:20 UTC, darmac commented
> ```diff
> -Wl,-rpath,$LIB_DIR $PKG_LIBS
> ```

Should we make a PR to the upstream?

2021-02-04 01:58 UTC, glennpj commented
> > ```diff
> > -Wl,-rpath,$LIB_DIR $PKG_LIBS
> > ```
> 
> Should we make a PR to the upstream?

It could be submitted upstream, but it may not be the best option outside of Spack. The reason I say that is because the configure script could also look for `mysql_config` and `mariadb_config`, which would not be covered by the patch. For Spack, we would be building specifically with the directory specifications, which matches with the patch.

2021-02-04 02:19 UTC, darmac commented
OK, at last, I have another question: Is that error caused by the `dyn.load(file, DLLpath = DLLpath, ...)` cannot recognize the `gcc -L` options, and it can only understand `LD_LIBRARY_PATH` and rpath info?

2021-02-04 02:34 UTC, glennpj commented
The `gcc -L` option works. When R is testing the library it fails because it was not linked with rpath, and, as you noted, LD_LIBRARY_PATH is not set.

2021-02-07 02:26 UTC, glennpj approved these changes
LGTM

2021-02-07 02:49 UTC, merged