ldak: build only x86_64 linux.
LLNL/spack pull request #21414
Opened 2021-02-01 05:31 UTC by tkameyama

ldak include libspotliux*.a
This files can be linkes only x86_64 only.
This PR add conflicts other than x86_64 linux.

2021-02-01 17:53 UTC, tldahlgren commented on var/spack/repos/builtin/packages/ldak/package.py
> +    conflicts('target=aarch64:', msg='libspot is avilable linux x86_64 only')
```suggestion
    conflicts('target=aarch64:', msg='libspot is available linux x86_64 only')
```

2021-02-01 17:55 UTC, tldahlgren requested changes
You could put this in a loop iterating over target args, especially since the message is identical.

There is a typo in the message.  Please add the missing 'a' in 'avilable'.

2021-02-01 17:57 UTC, tldahlgren commented
@njbooher Did you want to review this change?

2021-02-02 17:26 UTC, njbooher commented
Seems fine to me. The hash for the package might need updated too. The software creator seems to have produced a new version, still called 5.1, and put it at the same URL.

2021-02-03 09:06 UTC, tkameyama commented on var/spack/repos/builtin/packages/ldak/package.py
> +    conflicts('target=aarch64:', msg='libspot is avilable linux x86_64 only')
fixed.

2021-02-03 09:13 UTC, tkameyama commented
> The hash for the package might need updated too. The software creator seems to have produced a new version, still called 5.1, and put it at the same URL.



> 
> 
> Seems fine to me. The hash for the package might need updated too. The software creator seems to have produced a new version, still called 5.1, and put it at the same URL.

Updated.
The ldak_slow.c file is not found in new package.
So I change in install function.

2021-02-07 11:17 UTC, haampie commented
Are we sure the domain wasn't compromised? I can confirm the hash has changed. Doesn't seem like a very reliable website in general, download speed is close to 0, doesn't use https.

2021-02-08 18:01 UTC, tldahlgren approved these changes
Thanks for the updates.

2021-02-08 18:22 UTC, merged

2021-02-08 18:24 UTC, tldahlgren commented
Thank you for your contribution!