Package/r require and subpackage dep fix
LLNL/spack pull request #21433
Opened 2021-02-01 22:42 UTC by dorton21

Deps. in r-remote are not specified as required and "subversion" actually causes the package to fail.

2021-02-01 23:33 UTC, glennpj commented
> Deps. in r-remote are not specified as required and "subversion" actually causes the package to fail.

They are listed in the `SytemRequirements:` field. 
What is the failure that you are seeing?

2021-02-01 23:54 UTC, glennpj requested changes

2021-02-01 23:54 UTC, glennpj commented on var/spack/repos/builtin/packages/r-remotes/package.py
> -    depends_on('git', type='run')
These are listed under the `SystemRequirements:` field so should not be removed.

2021-02-01 23:54 UTC, glennpj commented on var/spack/repos/builtin/packages/r-require/package.py
> +
This depends on R (≥ 3.5).

2021-02-01 23:54 UTC, glennpj commented on var/spack/repos/builtin/packages/r-require/package.py
> +    depends_on('r-data-table', type=('build', 'run'))
```suggestion
    depends_on('r-data-table@1.10.4:', type=('build', 'run'))
```

2021-02-03 01:00 UTC, dorton21 commented
> > Deps. in r-remote are not specified as required and "subversion" actually causes the package to fail.
> 
> They are listed in the `SytemRequirements:` field.
> What is the failure that you are seeing?

`Installing serf-1.3.9-wcnvgruzfd4o7cmawa5jtw5vvrfq2g4p
==> No binary for serf-1.3.9-wcnvgruzfd4o7cmawa5jtw5vvrfq2g4p found: installing from source
==> Using cached archive: /home/las_djorton/spack/var/spack/cache/_source-cache/archive/54/549c2d21c577a8a9c0450facb5cca809f26591f048e466552240947bdf7a87cc.tar.bz2
==> serf: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'scons' '-j8' 'PREFIX=/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/serf-1.3.9-wcnvgruzfd4o7cmawa5jtw5vvrfq2g4p' 'APR=/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/apr-1.7.0-l6q2flyxdbue5f5y42vcffxgbhv3jln3' 'APU=/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/apr-util-1.6.1-uftpb43lsdb3brh6l3vkk26jrcplamim' 'OPENSSL=/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/openssl-1.1.1i-g6bqsubimay3lzgfhypft2lrfn6o43ya' 'ZLIB=/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/zlib-1.2.11-yhnqaydlekve6ylpw26na367nutfo3yf' 'LINKFLAGS=-L/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/zlib-1.2.11-yhnqaydlekve6ylpw26na367nutfo3yf/lib -Wl,-rpath,/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/zlib-1.2.11-yhnqaydlekve6ylpw26na367nutfo3yf/lib' 'CPPFLAGS=-I/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/zlib-1.2.11-yhnqaydlekve6ylpw26na367nutfo3yf/include' 'DEBUG=no' 'CC=/usr/bin/gcc'

2 errors found in build log:
     115                     from /home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/apr-1.7.0-l6q2flyxdbue5f5y42vcffxgbhv3jln3/include/apr-1/apr_pools.h:47,
     116                     from buckets/ssl_buckets.c:25:
     117    /usr/include/string.h:391:35: note: expected 'const char *' but argument is of type 'unsigned char *'
     118      391 | extern size_t strlen (const char *__s)
     119          |                       ~~~~~~~~~~~~^~~
     120    /usr/bin/gcc -o libserf-1.so.1.3.0 -L/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/zlib-1.2.11-yhnqaydlekve6ylpw26na367nutfo3yf/lib -Wl,-rpath,/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gc
            c-10.2.1/zlib-1.2.11-yhnqaydlekve6ylpw26na367nutfo3yf/lib -pthread -shared -Wl,-Bsymbolic -Wl,-soname=libserf-1.so.1 -Wl,-rpath=/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/serf-1.3.9-wcnvgruzfd4o7cmaw
            a5jtw5vvrfq2g4p/lib -Wl,-rpath=/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/apr-1.7.0-l6q2flyxdbue5f5y42vcffxgbhv3jln3/lib -Wl,-rpath=/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1
            /openssl-1.1.1i-g6bqsubimay3lzgfhypft2lrfn6o43ya/lib -Wl,-rpath=/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/expat-2.2.10-y72rsb25zezn5uj5y4wpdhsyiwpen3oq/lib -Wl,-rpath=/home/las_djorton/spack/opt/spa
            ck/linux-fedora33-skylake/gcc-10.2.1/libiconv-1.16-klbkz7feqabojowdk5yxk734qvplgl7i/lib -Wl,-rpath=/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/apr-util-1.6.1-uftpb43lsdb3brh6l3vkk26jrcplamim/lib -Wl,-
            rpath=/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/openssl-1.1.1i-g6bqsubimay3lzgfhypft2lrfn6o43ya/lib context.os incoming.os outgoing.os ssltunnel.os buckets/aggregate_buckets.os buckets/allocator.os
            buckets/barrier_buckets.os buckets/buckets.os buckets/bwtp_buckets.os buckets/chunk_buckets.os buckets/dechunk_buckets.os buckets/deflate_buckets.os buckets/file_buckets.os buckets/headers_buckets.os buckets/iovec_buckets.os
             buckets/limit_buckets.os buckets/mmap_buckets.os buckets/request_buckets.os buckets/response_body_buckets.os buckets/response_buckets.os buckets/simple_buckets.os buckets/socket_buckets.os buckets/ssl_buckets.os auth/auth.o
            s auth/auth_basic.os auth/auth_digest.os auth/auth_spnego.os auth/auth_spnego_gss.os auth/auth_spnego_sspi.os -L/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/apr-1.7.0-l6q2flyxdbue5f5y42vcffxgbhv3jln3/l
            ib -L/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/openssl-1.1.1i-g6bqsubimay3lzgfhypft2lrfn6o43ya/lib -L/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/expat-2.2.10-y72rsb25zezn5uj5
            y4wpdhsyiwpen3oq/lib -L/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/libiconv-1.16-klbkz7feqabojowdk5yxk734qvplgl7i/lib -L/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/apr-util-1.6
            .1-uftpb43lsdb3brh6l3vkk26jrcplamim/lib -L/home/las_djorton/spack/opt/spack/linux-fedora33-skylake/gcc-10.2.1/openssl-1.1.1i-g6bqsubimay3lzgfhypft2lrfn6o43ya/lib -lssl -lcrypto -lz -lapr-1 -luuid -lrt -lcrypt -lpthread -ldl
            -laprutil-1 -lexpat -liconv
  >> 121    /bin/ld: cannot find -luuid
  >> 122    collect2: error: ld returned 1 exit status
     123    scons: *** [libserf-1.so.1.3.0] Error 1
     124    scons: building terminated because of errors.`

2021-02-04 02:20 UTC, glennpj commented
> This is the error given. Serfs does not work which is called by subversion. I suppose this means serf needs some fixing. Do you have any ideas?

Yes, the problem is with `serf`. I will point out that this works fine for me using gcc-8.4.0, on CentOS-7. This could be an issue with gcc-10 so maybe try gcc-8 or gcc-9.

2021-02-07 02:20 UTC, glennpj commented
Were you able to resolve the problem with `serf`?

2021-02-07 19:47 UTC, glennpj approved these changes

2021-02-07 19:48 UTC, merged