New Package r-reproducible
LLNL/spack pull request #21434
Opened 2021-02-01 22:52 UTC by dorton21

2021-02-01 23:46 UTC, glennpj commented
This depends on #21433.

2021-02-02 22:55 UTC, tldahlgren requested changes
At a minimum there are some flake8 issues needing to be resolved:

- var/spack/repos/builtin/packages/r-reproducible/package.py:15: [W291] trailing whitespace
15
- var/spack/repos/builtin/packages/r-reproducible/package.py:22: [W291] trailing whitespace

2021-02-02 22:55 UTC, tldahlgren commented on var/spack/repos/builtin/packages/r-reproducible/package.py
> +    for sharing between users. Several advanced options are
```suggestion
    for sharing between users. Several advanced options are
```

2021-02-02 22:57 UTC, tldahlgren commented
Confirmed the given version is available at the URL.

2021-02-03 00:03 UTC, glennpj requested changes
This package also has System Requirements.

SystemRequirements: | 'unrar' (Linux/macOS)

2021-02-03 01:03 UTC, dorton21 commented
I'm also confused by all the failing tests.

2021-02-04 02:09 UTC, glennpj commented
> I'm also confused by all the failing tests.

Some of the tests are failing because this has a dependency on `r-require`, which is not in Spack yet, #21433. For example:
```console
>       assert not missing, "These packages have missing dependencies:\n" + (
            "\n".join(lines)
        )
E       AssertionError: These packages have missing dependencies:
E         r-reproducible: [r-require]
E       assert not {'r-reproducible': set(['r-require'])}

lib/spack/spack/test/package_sanity.py:241: AssertionError
!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!
== 1 failed, 972 passed, 17 skipped, 18 xfailed, 1 xpassed in 588.17 seconds ===
Error: Process completed with exit code 2.
```

2021-02-04 02:10 UTC, glennpj approved these changes
LGTM

2021-02-07 19:50 UTC, glennpj commented
Restarting tests now that #21433 has been merged.

2021-02-08 08:30 UTC, alalazo approved these changes

2021-02-08 13:17 UTC, glennpj approved these changes
I had already approved the changes so I am not sure why another review was requested.

2021-02-09 22:07 UTC, glennpj commented
@tldahlgren It looks like this just needs your approval.

2021-02-09 22:11 UTC, tldahlgren approved these changes

2021-02-09 22:11 UTC, merged