New Package: py-xgboost
LLNL/spack pull request #21470
Opened 2021-02-03 21:04 UTC by kean-smullen-nnl

Creating a py-xgboost package for spack to install the python api for xgboost similar to the r package.

2021-02-03 21:47 UTC, adamjstewart requested changes

2021-02-03 21:47 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-xgboost/package.py
> +    extends('python')
This line isn't needed as it's already added by the base class

2021-02-03 21:47 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-xgboost/package.py
> +    variant('plotting',     default=False)
These variants need descriptions

2021-02-03 21:47 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-xgboost/package.py
> +    depends_on('py-scikit-learn', when='+py-scikit-learn', type=('build', 'run'))
```suggestion
    depends_on('py-scikit-learn', when='+scikit-learn', type=('build', 'run'))
```

2021-02-03 21:52 UTC, adamjstewart commented
Looks like the `setup.py` has some interesting options:
```python
# Options only effect `python setup.py install`, building `bdist_wheel`         
# requires using CMake directly.                                                
USER_OPTIONS = {                                                                
    # libxgboost options.                                                       
    'use-openmp': (None, 'Build with OpenMP support.', 1),                      
    'use-cuda':   (None, 'Build with GPU acceleration.', 0),                    
    'use-nccl':   (None, 'Build with NCCL to enable distributed GPU support.', 0),
    'build-with-shared-nccl': (None, 'Build with shared NCCL library.', 0),     
    'hide-cxx-symbols':       (None, 'Hide all C++ symbols during build.', 1),  
    'use-hdfs':   (None, 'Build with HDFS support', 0),                         
    'use-azure':  (None, 'Build with AZURE support.', 0),                       
    'use-s3':     (None, 'Build with S3 support', 0),                           
    'plugin-lz4': (None, 'Build lz4 plugin.', 0),                               
    'plugin-dense-parser': (None, 'Build dense parser plugin.', 0),             
    # Python specific                                                           
    'use-system-libxgboost': (None, 'Use libxgboost.so in system path.', 0)     
}                          
```
For example, we may be able to add `--use-system-libxgboost` and add a dependency on `xgboost` so that we don't need to build it twice to get the Python API. These other flags could have variants as well. This is completely up to you, as I don't currently use `xgboost`. If I decide to use it in the future, I may add these myself.

2021-02-08 20:06 UTC, kean-smullen-nnl commented
@adamjstewart I pushed a new commit to address your comments and change request to fix the py-scikit-learn dependency (good catch there haha).
As for the --use-system-xgboost flag, I hadn't configured it that way because I wanted to mimic the r-xgboost setup.

2021-02-08 20:35 UTC, adamjstewart approved these changes

2021-02-09 23:12 UTC, merged

2021-02-12 21:04 UTC, adamjstewart commented
It just so happens that I need to use `py-xgboost` for a project now, so I'll stress test the recipe and let you know if I needed to make any modifications. Thanks for adding this, and good timing!