paraview: fix issues with paraview 5.7 build
LLNL/spack pull request #21484
Opened 2021-02-04 13:49 UTC by danlipsa

2021-02-11 21:44 UTC, danlipsa commented
Fixes https://github.com/spack/spack/issues/21445

2021-02-11 23:14 UTC, mathstuf approved these changes, later dismissed

2021-02-12 14:16 UTC, danlipsa commented
@chuckatkins Please review and if OK merge! Thanks!

2021-02-12 16:10 UTC, alalazo requested changes
CI is complaining that package changes are not compatible with Python 2.6

2021-02-12 16:10 UTC, alalazo commented on var/spack/repos/builtin/packages/paraview/package.py
> +                cmake_args.append('-DPython3_ROOT_DIR:PATH={}'.format(
```suggestion
                cmake_args.append('-DPython3_ROOT_DIR:PATH={0}'.format(
```

2021-06-12 11:46 UTC, alalazo commented
@danlipsa Can you please rebase this PR and address the issue with Python 2.6 compatibility?

2022-02-11 14:17 UTC, alalazo commented
Closing, since there has been no activity in a while (and currently we are at v5.10). Feel free to reopen if you want to continue work on this.

2022-02-11 14:17 UTC, closed without merging