Added RHEL 8.3 support
LLNL/spack pull request #21563
Opened 2021-02-09 12:29 UTC by amd-toolchain-support

- Fixed SHA256 value for version 2.6.5 (merged on: 21-Nov-2020)
- Added RHEL 8.3 support for kernel 4.18.0-240.1.1.el8_3.x86_64

2021-02-09 12:40 UTC, haampie commented
Can you turn that patch into a PR for xpmem too?

2021-02-09 12:40 UTC, haampie approved these changes

2021-02-09 12:52 UTC, haampie requested changes
Actually no, you shouldn't change the commit for version 2.6.5, your patch should apply to `master` or you should add a new version like `2.6.5-1` for commit `0d0bad4e1d07b38d53ecc8f20786bb1328c446da`.

2021-02-09 17:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/xpmem/package.py
> +    version('2.6.5', commit='0d0bad4e1d07b38d53ecc8f20786bb1328c446da')
Why did the hash need to be changed?

2021-02-10 05:39 UTC, amd-toolchain-support commented
> Actually no, you shouldn't change the commit for version 2.6.5, your patch should apply to `master` or you should add a new version like `2.6.5-1` for commit `0d0bad4e1d07b38d53ecc8f20786bb1328c

In present spack downloads below commit id and was merged in the year of 2017.
commit 4efeed9cbaabe971f3766d67cb108e2c3316d4b8
Author: Nathan Hjelm <hjelmn@me.com>
Date:   Mon Aug 28 23:10:08 2017
This commit id was the first release version of 2.6.5.  (You can find version  here “kernel/xpmem_private.h:#define XPMEM_CURRENT_VERSION_STRING     "2.6.5")

The one we proposed and the newer commit id and was merged on Nov 2020. 
commit 0d0bad4e1d07b38d53ecc8f20786bb1328c446da (HEAD -> master, origin/master, origin/HEAD)
Merge: cae8601 2e2fa69
Author: Nathan Hjelm <hjelmn@google.com>
Date:   Sat Nov 21 08:45:11 2020 -0700
Versions can be found here 
dkms.conf:PACKAGE_VERSION="2.6.5"
xpmem-kmod.spec:Version: 2.6.5

This commit id was the 7th revision of version 2.6.5 and merged in Nov 2020. And XPMEM authors havent changed version numbers but updated their source codes. Existing spack recipe with commit id 4efeed9cbaabe971f3766d67cb108e2c3316d4b8 isn’t compatible with many recent Operating Systems.  So we have used latest commit id and created spack recipe with the same version number. 

As per previous communication  you have asked us to change the version number to 2.6.5-1. Please suggest if you want us to change our new recipe to 2.6.5.-1 version, then we will change.

2021-02-10 08:30 UTC, haampie commented
Pinging @alalazo / @adamjstewart for an opinion. The situation is that both `2.6.4` and `2.6.5` were never tagged (I"ve created an issue https://github.com/hjelmn/xpmem/issues/41), and our 2.6.4 and 2.6.5 refer to the first commits that changed the version numbers in the source code. The patch provided by @amd-toolchain-support refers to the latest commit on `master`. Should we add our own `2.6.5-1` version for a recent commit so that it's easier to apply this patch? And should we set `preferred=True` on 2.6.5?

2021-02-11 16:39 UTC, alalazo commented
> The patch provided by @amd-toolchain-support refers to the latest commit on master

I'd really rather avoid patching moving versions, since the patch is bound to be outdated as the development of the software progresses.

2021-02-11 17:18 UTC, haampie commented on var/spack/repos/builtin/packages/xpmem/package.py
> +    version('2.6.5', commit='0d0bad4e1d07b38d53ecc8f20786bb1328c446da')
```suggestion
    version('2.6.5-0d0bad4', commit='0d0bad4e1d07b38d53ecc8f20786bb1328c446da')
    version('2.6.5', commit='4efeed9cbaabe971f3766d67cb108e2c3316d4b8')
```

2021-02-11 17:18 UTC, haampie commented on var/spack/repos/builtin/packages/xpmem/package.py
> +    patch('xpmem_v2.6.5.patch', when="@2.6.5", level=1)
```suggestion
    patch('xpmem_v2.6.5.patch', when="@2.6.5-0d0bad4", level=1)
```

2021-02-11 17:20 UTC, haampie commented
My proposal is to use `[version]-[short git sha]` instead of `[version]-1` since numbering from 1 starting at an arbitrary commit doesn't make much sense either.

2021-02-11 17:26 UTC, adamjstewart commented
> numbering from 1 starting at an arbitrary commit doesn't make much sense either.

It makes less sense, although it does allow version sorting to work. As long as this is the only random commit we add that doesn't matter though.

2021-02-11 17:44 UTC, haampie commented
```
$ git describe --tags 4efeed9cbaabe971f3766d67cb108e2c3316d4b8 # spack version 2.6.5
v2.6.3-20-g4efeed9
$ git describe --tags 0d0bad4e1d07b38d53ecc8f20786bb1328c446da # new amd version
v2.6.3-56-g0d0bad4
```

so 36 commits after "2.6.5", then `v2.6.5-36` makes sense, maybe. It allows sorting and adding an older version.

2021-02-12 08:49 UTC, amd-toolchain-support commented
> so 36 commits after "2.6.5", then `v2.6.5-36` makes sense, maybe. It allows sorting and adding an older version.

Could you please finalize the naming convention. So, that we will make required changes.

2021-02-12 08:56 UTC, haampie commented
The -36 suffix is fine, you can use that

2021-02-12 09:11 UTC, haampie approved these changes

2021-02-12 09:43 UTC, alalazo approved these changes

2021-02-12 10:01 UTC, merged