New package: py-dask-xgboost
LLNL/spack pull request #21583
Opened 2021-02-10 07:27 UTC by a-saitoh-fj

New package: py-dask-xgboost

2021-02-10 16:00 UTC, adamjstewart requested changes

2021-02-10 16:00 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-dask-xgboost/package.py
> +    depends_on('python', type=('build', 'run'))
You can remove this line, it's implied by the base class

2021-02-10 16:00 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-dask-xgboost/package.py
> +    variant('sparse', default=False, description='Extras require')
I think a better description would be something like "add sparse support" or something like that

2021-02-10 16:00 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-dask-xgboost/package.py
> +    depends_on('xgboost@:0.90', type=('build', 'run'))
```suggestion
    depends_on('py-xgboost@:0.90', type=('build', 'run'))
```

2021-02-14 18:42 UTC, adamjstewart commented
As mentioned in #21661, according to https://github.com/dask/dask-xgboost/issues/80, `py-dask-xgboost` is actually deprecated, and the functionality has been migrated to `py-xgboost+dask`. Is this package still necessary, or can it be removed?

2021-02-22 06:31 UTC, a-saitoh-fj commented
py-dask-xgboost: Fixed what was pointed out

- Deleted the description of "depends_on('python', type=('build', 'run'))"
- Change description
- Fix dependency from xgboost to py-xgboost

Submit this recipe as it may be used in py-dask-ml.
I think it may change in the discussion of #21661, but I will submit it first.

2021-02-22 16:39 UTC, adamjstewart approved these changes

2021-02-22 16:39 UTC, merged