hpctoolkit: pre-release update
LLNL/spack pull request #21613
Opened 2021-02-11 03:55 UTC by mwkrentel

Update some things in hpctoolkit to prepare for a 2021.02.x release:

  1. allow binutils to be built with +nls.
  2. require libmonitor to be built with +dlopen.
  3. allow rocm in more than just develop branch.
  4. remove some conflicting setenv's in hpctoolkit module.
  
----------

I have a little bit of a chicken and egg problem.  We're heading to a
release and I need to merge our develop branch into master, but the
new master won't build without these changes.  (don't ask)

My plan is to make these updates and merge hpctoolkit develop into
master.  Then I can fully test with everything in place.  Finally,
when ready, I can tag the next release and update package.py with
minimal changes.  But it takes two commits.

----------

We do need to modify the module environment to remove some setenvs.
I didn't want to dig into the internals of a spack env_modifications,
but I couldn't find a more structured way of doing this.

2021-02-11 08:11 UTC, haampie commented
Just out of curiosity, what's the problem with those environment variables at runtime?

2021-02-11 15:21 UTC, alalazo requested changes, later dismissed
A question on removing modifications from the list under construction.

2021-02-11 15:21 UTC, alalazo commented on var/spack/repos/builtin/packages/hpctoolkit/package.py
> +                keeplist.append(elt)
I would rather:
- Search for the variables you want to remove
- Explicitly unset those variables

In this way you won't remove actions added by callbacks before this one (which may be more difficult to track or debug) but you will nullify them with an `unset`. Is this approach viable in your case?

2021-02-11 16:27 UTC, mwkrentel commented
@haampie I think it's HIP_PATH.  It gives an error message:

```
clang-12: error: cannot find ROCm device library. 
Provide its path via --rocm-path or --rocm-device-lib-path, 
or pass -nogpulib to build without ROCm device library.
make: *** [<builtin>: BitonicSort.o] Error 1
```

But I'm checking on the exact conditions that lead to this error.

2021-02-11 16:29 UTC, mwkrentel commented
@alalazo Do you mean that you want the output in the module file to be
something like:

```
setenv HIP_PATH "/opt/rocm-4.0.0/hip"
unsetenv HIP_PATH
```

That would be incorrect.  The problem is not that HIP_PATH is set in
the environ, but that hpctoolkit overrides the user's value.  What we
need is for our module to leave it alone so that we don't break the
user's value.

Hpctoolkit is a profiling tool.  We don't want to drive how the app
builds itself.  Instead, we want to sit back, let the app build itself
natively and then adapt to that.

Also, `env.env_modifications` is just a python list.  Instead, I could
scan the list, collect all the items that I need to delete, then use
the list remove() method to delete them from the original list.

If you prefer, I could write it that way, but you'd end up with the
same answer.  (Plus it would run a little longer.)

Actually, the best solution would be for spack to provide a more
structured way to delete things from the generated environment.
Something that would give me a callback function to say yes/no if I
want to keep or delete it from the module.  That way, I don't have to
rely on `env.env_modifications` being a list, etc.  That wouldn't be
too hard to write, but it currently doesn't exist.

2021-02-11 16:58 UTC, alalazo commented
> Actually, the best solution would be for spack to provide a more
structured way to delete things from the generated environment.
Something that would give me a callback function to say yes/no if I
want to keep or delete it from the module. That way, I don't have to
rely on env.env_modifications being a list, etc. That wouldn't be
too hard to write, but it currently doesn't exist.

That would do. I may open an issue for that, or if you beat me to it feel free to assign it to me.

2021-02-11 17:12 UTC, mwkrentel commented
@alalazo Is there anything else?

I agree that the `package.py` file should not expose the internals of
`env_modifications`.  But I couldn't find a way without doing that
with the current spack tools.

2021-02-11 17:13 UTC, mwkrentel commented
@alalazo  @haampie Btw, I'm curious, do either of you ever use hpctoolkit?

2021-02-11 17:27 UTC, haampie commented
> @alalazo @haampie Btw, I'm curious, do either of you ever use hpctoolkit?

No, just following this package because it runs into issues with hip ;)

2021-02-11 17:28 UTC, alalazo commented
> do either of you ever use hpctoolkit?

Me neither, I am just trying to lower the amount of PRs waiting for review :sweat_smile:

2021-02-16 06:10 UTC, mwkrentel commented
@alalazo Ok, I added issue #21694 and ping'ed you.
Is there anything else, or can we merge now ?
Thanks.

2021-02-16 07:47 UTC, alalazo approved these changes

2021-02-16 07:47 UTC, merged