eospac: add cpuinfo_comp_flags_key.patch
LLNL/spack pull request #21626
Opened 2021-02-11 16:26 UTC by gaber

Patch eospac's Makefile.-linux-gnu.hashes to consider only `$(notdir $(F90))` when constructing a key to look up compiler flags in the _F90-CPUINFO_COMP_FLAGS associative array.

This patch was accepted into eospac itself after the release of 6.4.2beta, so apply it only to 6.4.2beta and earlier releases.

2021-02-16 16:01 UTC, haampie commented
If this only applies to a patch version and is going to be fixed upstream in the next patch release, I'd say it's better to wait for that. But if that takes a long time and you really need this patch, then we could merge this PR.

2021-02-16 18:03 UTC, tldahlgren commented
Closing and re-opening the PR to force re-running required checks.

2021-02-22 14:34 UTC, gaber commented
> If this only applies to a patch version and is going to be fixed upstream in the next patch release, I'd say it's better to wait for that. But if that takes a long time and you really need this patch, then we could merge this PR.

To maybe clarify: this patch applies to the previous patch release (6.4.2beta), to the previous major release (6.4.1), and to earlier versions at least some distance back in history. It's not needed for 6.4.2 (#21476) and newer releases. I certainly agree that, if this patch applied only to 6.4.2beta, it probably wouldn't make sense to record it in Spack, but in fact it's needed for a larger range of versions.

2021-03-03 00:54 UTC, gaber commented
Just wanted to check in on this PR; if it's possible, I'd still like to see this merged. Can I provide any more information to help?

2021-03-10 10:53 UTC, alalazo requested changes
Restarted test. I have one minor request

2021-03-10 10:53 UTC, alalazo commented on var/spack/repos/builtin/packages/eospac/package.py
> +    patch('cpuinfo_comp_flags_key.patch', when='@:6.4.1,6.4.2beta')
Can you please add a brief comment explaining what the patch does and why it is needed?

2021-03-10 16:47 UTC, gaber commented on var/spack/repos/builtin/packages/eospac/package.py
> +    patch('cpuinfo_comp_flags_key.patch', when='@:6.4.1,6.4.2beta')
Absolutely; just added a comment, probably erring on the side of brevity. I'm happy to expand that further if you think it's still not clear.

2021-03-10 18:51 UTC, alalazo commented on var/spack/repos/builtin/packages/eospac/package.py
> +    patch('cpuinfo_comp_flags_key.patch', when='@:6.4.1,6.4.2beta')
Thanks! That's absolutely fine like this.

2021-03-10 18:51 UTC, alalazo approved these changes

2021-03-11 01:47 UTC, merged