New package: w3m
LLNL/spack pull request #21641
Opened 2021-02-12 02:54 UTC by ronin-gw

2021-02-16 18:48 UTC, tldahlgren approved these changes
LGTM *except* the validation issue.

2021-02-16 18:50 UTC, tldahlgren commented on var/spack/repos/builtin/packages/w3m/package.py
> +                args.append('--with-{}={}'.format(variant, avail_lib))
```suggestion
                args.append('--with-{0}={1}'.format(variant, avail_lib))
```

2021-02-16 18:51 UTC, tldahlgren commented on var/spack/repos/builtin/packages/w3m/package.py
> +                args.append('--with-{}={}'.format(variant, avail_lib))
This change will address at least part of the validation error.

2021-02-16 18:51 UTC, tldahlgren requested changes, later dismissed
Please resolve the validation check issue.

2021-02-25 12:31 UTC, ronin-gw commented
@tldahlgren Thank you for your suggestion. I confirmed that the latest commit passed the `vermin` validation.

2021-02-25 12:42 UTC, alalazo approved these changes

2021-02-25 12:42 UTC, merged