py-prompt-toolkit: add 3.0.16
LLNL/spack pull request #21657
Opened 2021-02-13 00:00 UTC by michaelkuhn

2021-02-13 18:27 UTC, adamjstewart requested changes

2021-02-13 18:27 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-prompt-toolkit/package.py
>      version('1.0.9',  sha256='cd6523b36adc174cc10d54b1193eb626b4268609ff6ea92c15bcf1996609599c')
Can you add/modify the following:
```python
depends_on('python@3.6.1:', when='@3:', type=('build', 'run'))
depends_on('python@2.6:2.8,3.3:', when='@:2.999', type=('build', 'run'))
depends_on('py-six@1.9.0:', when='@:2.999', type=('build', 'run'))
```

2021-02-14 13:16 UTC, michaelkuhn commented on var/spack/repos/builtin/packages/py-prompt-toolkit/package.py
>      version('1.0.9',  sha256='cd6523b36adc174cc10d54b1193eb626b4268609ff6ea92c15bcf1996609599c')
Done!

2021-02-14 14:36 UTC, adamjstewart approved these changes

2021-02-14 14:36 UTC, merged