py-horovod: new versions
LLNL/spack pull request #21681
Opened 2021-02-15 15:47 UTC by aweits

@adamjstewart @tgaddair

2021-02-15 15:55 UTC, tgaddair commented
Thanks @aweits!  Just a heads up, we'll also be releasing v0.21.3 today, which has a bugfix for TensorFlow 2.4 users:

https://github.com/horovod/horovod/pull/2667

2021-02-15 16:03 UTC, aweits commented
> Thanks @aweits! Just a heads up, we'll also be releasing v0.21.3 today, which has a bugfix for TensorFlow 2.4 users:
> 
> [horovod/horovod#2667](https://github.com/horovod/horovod/pull/2667)

Cool! Let's hold off on merging this until that's tagged then...

2021-02-15 20:53 UTC, tgaddair commented
Thanks @aweits, v0.21.3 is now released.

2021-02-15 21:14 UTC, aweits commented
> Thanks @aweits, v0.21.3 is now released.

Builds, lightly tested against just the tensorflow framework (tensorflow@2.4.0), using tensorflow2_synthetic_benchmark.py on a standalone single-gpu machine.

2021-02-15 22:57 UTC, adamjstewart requested changes
Required version of py-petastorm has changed, py-h5py should probably be :2.999, not 2.9:. I forget where the required versions of TF/PyTorch/mxnet/etc are documented.

2021-02-16 17:19 UTC, adamjstewart requested changes

2021-02-16 17:19 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-horovod/package.py
> +    depends_on('py-h5py@2.999:',        type=('build', 'run'),         when='frameworks=spark')
```suggestion
    depends_on('py-h5py@:2.999',        type=('build', 'run'),         when='frameworks=spark')
```

2021-02-16 17:19 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-petastorm/package.py
Can you also add:
```python
depends_on('python@3:', when='@0.9.8:', type=('build', 'run'))
```

2021-02-16 17:30 UTC, adamjstewart approved these changes

2021-02-16 18:40 UTC, merged