New package r-qs at 0.23.5
LLNL/spack pull request #21779
Opened 2021-02-19 00:16 UTC by dorton21

2021-02-19 00:50 UTC, dorton21 commented
depends on @21780

2021-02-19 00:52 UTC, dorton21 commented
depends on #21785

2021-02-19 01:16 UTC, glennpj requested changes

2021-02-19 01:16 UTC, glennpj commented on var/spack/repos/builtin/packages/r-qs/package.py
> +    depends_on('r-rapiserializer', type=('build', 'run'))
```suggestion
    depends_on('r-rapiserialize', type=('build', 'run'))
```

2021-02-19 01:16 UTC, glennpj requested changes

2021-02-19 01:16 UTC, glennpj commented on var/spack/repos/builtin/packages/r-qs/package.py
> +    homepage = "https://cran.r-project.org/web/packages/qs/index.html"
```suggestion
    homepage = "https://cloud.r-project.org/web/packages/qs/index.html"
```

2021-02-24 02:52 UTC, glennpj approved these changes

2021-02-24 23:12 UTC, merged