New package at r-spades at 2.0.6
LLNL/spack pull request #21784
Opened 2021-02-19 00:43 UTC by dorton21

2021-02-19 00:55 UTC, dorton21 commented
depends on #21783

2021-02-19 00:55 UTC, dorton21 commented
depends on #21782

2021-02-19 00:55 UTC, dorton21 commented
depends on #21781

2021-02-19 01:40 UTC, glennpj requested changes

2021-02-19 01:40 UTC, glennpj commented on var/spack/repos/builtin/packages/r-spades/package.py
> +
Include the description.

2021-02-19 01:40 UTC, glennpj commented on var/spack/repos/builtin/packages/r-spades/package.py
> +    depends_on('r-codetools', type=('build', 'run'))
This dependency is not listed and should be removed.

2021-02-24 02:28 UTC, glennpj requested changes

2021-02-24 02:28 UTC, glennpj commented on var/spack/repos/builtin/packages/r-spades/package.py
> +    """Develop and Run Spatially Explicit Discrete Event Simulation Modelsi
```suggestion
    """Develop and Run Spatially Explicit Discrete Event Simulation Models
```

2021-03-02 18:08 UTC, glennpj approved these changes

2021-03-02 18:10 UTC, merged