New package r-spades-core at 1.0.5
LLNL/spack pull request #21782
Opened 2021-02-19 00:32 UTC by dorton21

2021-02-19 00:54 UTC, dorton21 commented
depends on #21779

2021-02-19 00:54 UTC, dorton21 commented
depends on #21778

2021-02-19 01:31 UTC, glennpj requested changes

2021-02-19 01:31 UTC, glennpj commented on var/spack/repos/builtin/packages/r-spades-core/package.py
> +    depends_on('r-qs@0.21.1', type=('build', 'run'))
```suggestion
    depends_on('r-qs@0.21.1:', type=('build', 'run'))
```

2021-02-19 01:31 UTC, glennpj commented on var/spack/repos/builtin/packages/r-spades-core/package.py
> +    depends_on('r-fastdigest', type=('build', 'run'))
Move this dependency to be immediately after the `r-data-table` dependency so that the order reflects what is in the DESCRIPTION file.

2021-02-24 02:37 UTC, glennpj approved these changes

2021-02-25 05:04 UTC, merged