nim: Fix checksum of 0.20.0
LLNL/spack pull request #21790
Opened 2021-02-19 07:16 UTC by t-nojiri

Version 0.20.0 was released on June 7, 2019.
A pull request (# 11649) was also made on June 7, 2019.
I think there was a fix to github after issuing the pull request.

@xfzhao Did you build after the PRs were merged?

2021-02-19 08:13 UTC, alalazo requested changes
It seems we are really behind, since in the download page I see v1.4.2 Can we update the versions with a few of the latest and just deprecate these old versions?

2021-02-22 02:42 UTC, t-nojiri commented
I added version 1.4.2 and changed the previous version to deprecated.

2021-02-22 08:30 UTC, alalazo approved these changes

2021-02-22 08:30 UTC, merged

2021-02-22 08:30 UTC, alalazo commented
Thanks!