Improve error message for inconsistencies in package.py
LLNL/spack pull request #21811
Opened 2021-02-19 15:08 UTC by alalazo

refers to https://github.com/spack/spack/pull/21787#issuecomment-781920135

Sometimes directives refer to variants that do not exist. Make it such that:

1. The name of the variant
2. The name of the package which is supposed to have such variant
3. The name of the package making this assumption

are all printed in the error message for easier debugging.

**Before this PR**
```console
% spack solve warpx
==> Error: 'pic'
```

**After this PR**
```console
% spack solve warpx
==> Error: variant "pic" not found in package "vtk-m"
```

2021-02-19 16:07 UTC, ax3l submitted a review, later dismissed
Oh this is great, thank you!

2021-02-19 17:13 UTC, tgamblin requested changes
LGTM but needs patch coverage...

2021-02-22 16:55 UTC, alalazo commented
@tgamblin Coverage *should* be there, but since the`clingo` runner doesn't upload the coverage file correctly we either need to fix that or merge #21446 to see a coverage raise in the notifications

2021-02-23 02:45 UTC, ax3l approved these changes

2021-02-23 03:09 UTC, tgamblin approved these changes

2021-02-23 03:09 UTC, merged

2021-09-17 12:43 UTC, haampie commented
I'm dropping this from the backports for 0.16.x since it requires all kinds of refactoring of the asp solver to be pulled in, even though the pr itself is small