Make CMake a bit smaller
LLNL/spack pull request #21958
Opened 2021-02-25 12:57 UTC by haampie

Use MinSizeRel `-Os` instead of Release as build type, which reduces the size by 30% on my machine and makes it a bit lighter for use in containers

2021-02-25 12:58 UTC, alalazo approved these changes, later dismissed

2021-02-25 13:05 UTC, chuckatkins commented
Have you looked at the runtime difference for generating large projects?  It can be significant since Release typically uses `O2`.  Why not just change your package defaults in a local `packages.yml`?

2021-02-25 13:20 UTC, haampie commented
Do you have an example large project? I would presume the bottleneck is the compiler invocations, file systems scans etc, not cmake itself. Also ` -Os enables all -O2 optimizations except those that often increase code size` https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html, so I guess it's still relatively fast?

2021-02-25 14:10 UTC, chuckatkins commented
> Do you have an example large project? I would presume the bottleneck is the compiler invocations, file systems scans etc, not cmake itself. Also ` -Os enables all -O2 optimizations except those that often increase code size` https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html, so I guess it's still relatively fast?

I got that wrong, `Release` is usually `O3`.  For large projects like trillinos, paraview, vtk, visit, the generation time can be 50% or more (60s vs 20s, for example).  Compliler invocations certainly dominate when doing the initial configure but if using it as an end-user for development than that generation time becomes a significant part of your workflow.  There are different scenarios where it would matter and where it wouldn't, in general though it shouldn't be forced onto users.

The gains are also pretty minimal.  Sure you're saving ~30% for the CMake install, but with respect to the overall install it's not particularly significant:  With gcc 9 on EL8 the spack install tree for the default cmake spec is 325MB, so this only reduces that by 6%.  You can get a much bigger bang for the buck by adding a variant to berkeley-db to disable docs, which take up 100MB of a 110MB installation, which would reduce your spack install footprint significantly rather than just marginally.

2021-02-25 14:16 UTC, chuckatkins requested changes
Re: https://github.com/spack/spack/pull/21958#issuecomment-785922680

This should really be implemented as variant, if event at all, and not forced on by default.

2021-02-25 14:54 UTC, haampie commented
>  You can get a much bigger bang for the buck by adding a variant to berkeley-db to disable docs

Only ncurses (30mb), openssl (30mb) and zlib (<1mb) are relevant, the rest is build deps and therefore irrelevant. Sure we can try to make berkeley-db small, but that's for another pr.

> Compliler invocations certainly dominate when doing the initial configure but if using it as an end-user for development than that generation time becomes a significant part of your workflow

Hm, I think I run cmake once and then make/ninja multiple times, unless I really have to move sources around. And at the second invocation of cmake most of the config is cached already, so it's fast. No experience with trillinos though.

2021-02-25 15:42 UTC, chuckatkins commented
> > You can get a much bigger bang for the buck by adding a variant to berkeley-db to disable docs
> 
> Only ncurses (30mb), openssl (30mb) and zlib (<1mb) are relevant, the rest is build deps and therefore irrelevant. Sure we can try to make berkeley-db small, but that's for another pr. Also berkeley-db seems to install docs unconditionally, so it would require a patch
> 
> > Compliler invocations certainly dominate when doing the initial configure but if using it as an end-user for development than that generation time becomes a significant part of your workflow
> 
> Hm, I think I run cmake once and then make/ninja multiple times, unless I really have to move sources around. And at the second invocation of cmake most of the config is cached already, so it's fast. No experience with trillinos though.

It's really project specific.  The "configure" part it pretty fast but the final generation step is where where the real time is spent.  That's when CMake is doing all of it's DAG solving, property propagation, generator expression evaluation, etc. to figure out what to actually put in the make / ninja files.  Running make will also automatically re-run cmake to configure and re-generate if it detects necessary dependencies are out-of date, mtimes have been altered, etc.

My main point is that that the build configuration shouldn't be unconditionally changed, especially given that it's targeting a specific use case and not a universal use case.  Adding a variant should give you the capability you're seeking and let it be made default with a spack config in the use case in question while keeping the most performant configuration the default for most users.

2021-02-25 16:15 UTC, chuckatkins approved these changes

2021-02-26 08:47 UTC, alalazo approved these changes

2021-02-26 08:49 UTC, merged