Raise InstallError if explicit specs skipped
LLNL/spack pull request #21980
Opened 2021-02-26 02:38 UTC by tldahlgren

Fixes #20510 
Fixes #21319 
Fixes #21937 

This PR ensures an `InstallError` exception is raise whenever explicitly specified specs are not installed due to being skipped, which happens if at least one of the spec's dependencies fails to install.

A snippet of the output from an example run shows the new error messages:
```
...
==> Warning: Skipping build of openmpi-4.0.5-rgz2d54hzfvum2gkoagdzp7mfenarnij since numactl-2.0.14-idnmkmkh7uwnwpaclcv7tlvolwa47yyx failed
==> Warning: Skipping build of hypre-2.20.0-qnmb33bsqzztdashqm2lf5pdyt2yzy46 since openmpi-4.0.5-rgz2d54hzfvum2gkoagdzp7mfenarnij failed
[+] $SPACK_ROOT/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/hwloc-2.4.0-fdlrsz4cmfy37ktq6sxyokps4yjzvtgp
==> Error: hypre-2.20.0-qnmb33bsqzztdashqm2lf5pdyt2yzy46: Package was not installed
==> Error: Installation request failed.  Refer to reported errors for failing package(s).
23.256u 2.905s 0:28.56 91.5%	0+0k 88+31704io 1pf+0w
```

This PR includes modifications to existing tests that were needed to handle the newly raised exception

2021-02-26 02:46 UTC, tldahlgren commented
@mdorier @haampie Can you confirm this PR fixes your problems?

2021-02-26 08:23 UTC, alalazo approved these changes
Thanks @tldahlgren! Waiting for other people to confirm before merging.

2021-02-26 09:20 UTC, haampie commented
Can confirm that it fixes #21319

2021-02-26 09:23 UTC, alalazo requested changes
It seems a few tests are still failing, like `test_dev_build_before_until`

2021-02-26 17:58 UTC, tldahlgren commented
> It seems a few tests are still failing, like `test_dev_build_before_until`

That's what I get for only running the `install` tests before pushing to the repo.

2021-02-27 08:21 UTC, alalazo approved these changes
Thanks @tldahlgren !

2021-02-27 08:21 UTC, merged