Allow $env to evaluate to current environment in configs
LLNL/spack pull request #21996
Opened 2021-02-26 18:23 UTC by becker33

This will allow users to have relative paths for mirrors and repos and other things that may be part of a Spack environment.

```
spack:
  repos:
  - $env/repo
```
The construction above will allow users to put a spack environment and a repo of packages relevant to that environment in the same directory or git repository, and the environment is automatically configured to use the repo.

The $env variable will not be evaluated if there is no active environment. This generally means that it should not be used outside of an environment's spack.yaml file. However, if other aspects of your workflow guarantee that there is always an active environment, it may be used in other config scopes.

2021-02-26 18:32 UTC, psakievich reviewed
This looks great to me! Thanks for turning this around so fast @becker33

2021-02-26 19:47 UTC, tgamblin requested changes
@becker33: one question: why do we need `$env`?  We could do this generally for any config file if we just looked at the file/line annotations that we get from the config system.  They should be preserved.

2021-02-26 21:00 UTC, becker33 commented
@tgamblin three reasons. One is that this is much easier to support. Two is that our line annotations are not always correct, especially for nested data structures. Three is that I think users will want to use $env even if we allow relative paths as well.

Consider a team that uses Spack with two environments, with different module trees. The user of their Spack setup might want to add
```
module_roots:
  lmod: $env/modules
```
to their config.yaml in the "system" ($spack/etc/spack) scope. (we should probably rename that scope)

That would reduce code duplication among environments, and mean that whatever environment they were using, it would get the correct module root.

That won't work for users who ever use Spack outside of an environment, but that's not everyone.

2021-02-26 21:35 UTC, rblake-llnl commented
I think, from a developer mental load point of view, including a relative path could be better. I mean, `spack develop` uses a relative path, so there's a slight inconsistency there.  

That said, I don't mind $env as it makes things explicit.  I'd worry more about consistency with `spack:develop:path:`

2021-02-26 21:41 UTC, becker33 commented
The big question to resolve if we want to do relative paths is what to do if there is no line info. For example, if someone writes a spack-python script that says `spack.config.override('config:install_tree:foo`)`, what does that mean? Do we just error out if we have a relative path and no line annotation? Do we use the working directory? The active environment? The spack prefix? Other than that it should be pretty doable to support. Although I think we would want to support the $env variable as well in case people want to use included files but have paths relative to the environment, for example, or the use case I outlined above.

2021-02-28 00:16 UTC, tgamblin commented
> For example, if someone writes a spack-python script that says `spack.config.override('config:install_tree:foo)`, do we just error out if we have a relative path and no line annotation? Do we use the working directory? The active environment? The spack prefix?

I think `spack.config.override('config:install_tree:foo)` is a corner case, so I think it's fine if that errors out. In general I think an implementation that just fails with no file info would be fine.  Note that you *could * annotate things that come from `spack.config.override`, if you wanted to be uniform about it, but I don't really think it's worth doing, and it's not clear to me that a script author wouldn't expect the path to be relative to the current working directory.  I don't know which is better but I think making them be explicit in a script is also fine.

For the config file case, it is very common to treat relative paths as relative to the file that they're in.  Dockerfiles, apache configs, `#include` in C files, etc. etc.  I think it will be surprising to people for `$env` to be required.  That said, I can see the argument for keeping `$env` for people who explicitly want that.

> Two is that our line annotations are not always correct, especially for nested data structures. 

I think we need some tests for this but if this is wrong I think it is also fixable (and maintainable with tests).  The place I have seen annotations get confused is with dictionary keys, not values.

2021-03-04 19:47 UTC, becker33 commented
Ok, so apparently the old code made relative paths absolute already, just relative to the pwd. I've retained that (probably useless) behavior for strings that do not have line annotations, and made the paths relative to the file where we do have the relevant information.

I think the `$env` key should be kept in addition to the relative paths, do you have any objection to that?

2021-03-05 05:06 UTC, tgamblin commented
> I think the $env key should be kept in addition to the relative paths, do you have any objection to that?

I like it.  I think it makes sense to give people the option to be specific in, say, included files.

2021-03-05 06:28 UTC, tgamblin approved these changes
LGTM!

2021-03-05 06:29 UTC, merged