abinit: fix patch for Fujitsu compiler
LLNL/spack pull request #22009
Opened 2021-03-01 03:16 UTC by m-shunji

The ABINIT configure collects linker options from the linker command which the compiler driver actually executes, and passes them on to the compiler driver.
When building with Fujitsu compiler ver.4.3.0 or later, one of the options causes an error in linking Fujitsu libraries.
To avoid this error I fixed the configure. This PR adds the change to the patch file.
I confirmed this patch works for both of the Fujitsu compiler ver.4.3.0 or earlier and later.

2021-03-09 10:49 UTC, alalazo requested changes

2021-03-09 10:49 UTC, alalazo commented on var/spack/repos/builtin/packages/abinit/package.py
> -    patch('fix_for_fujitsu.patch', level=0, when='%fj')
Would it be easy to describe succinctly, in a line or two of comments, what the patch above needs to do for Fujitsu compilers?

2021-03-10 07:48 UTC, m-shunji commented on var/spack/repos/builtin/packages/abinit/package.py
> -    patch('fix_for_fujitsu.patch', level=0, when='%fj')
Thank you for your review. I've added comments.

2021-03-10 08:58 UTC, alalazo approved these changes

2021-03-10 08:58 UTC, merged