xsdk-examples: add new version
LLNL/spack pull request #22090
Opened 2021-03-04 19:23 UTC by balos1

CC: @osborn9 @ulrikeyang @luszczek

2021-03-04 19:32 UTC, luszczek submitted a review, later dismissed

2021-03-04 19:50 UTC, osborn9 approved these changes, later dismissed

2021-03-04 19:51 UTC, balay commented
This has been a recurring problem with the concretizer
```
balay@xsdk:/data/balay/spack>spack spec xsdk-examples
<snip>
xsdk requires petsc variant +trilinos, but spec asked for ~trilinos
```
This must be a new one
```
balay@xsdk:/data/balay/spack>spack spec xsdk-examples+cuda
<snip>
xsdk requires mfem variant +superlu-dist, but spec asked for ~superlu-dist
```

2021-03-04 20:34 UTC, balay commented
I'm unable to use `xsdk-examples+cuda`
```
balay@xsdk:/data/balay/spack.x>spack spec xsdk-examples+cuda ^mfem+superlu-dist
==> Error: ~superlu-dist does not satisfy +superlu-dist
```
now trying a build with (well the conretizer is happy - and the build started):
```
./bin/spack install --fail-fast -j64 xsdk-examples ^xsdk+cuda+trilinos ^mfem+cuda ^magma cuda_arch=60 ^cuda@10.1.243 ^openblas@0.3.5 ^openmpi+cuda ^boost@1.74.0
```

2021-03-04 21:47 UTC, balay commented
And go the following error:
```
/usr/bin/ld: /data/balay/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.4.0/mfem-4.2.0-jegabnknxmqo44z26lz3v4q4rla4zztg/lib/libmfem.a(mem_manager.o): undefined reference to symbol 'cudaStreamSynchronize@@libcudart.so.10.1'
/nfs/apps/spacks/2021-02-09/opt/spack/linux-centos7-x86_64/gcc-7.3.0/cuda-10.1.243-kh3kzn4uiajmhy5oiofd6rmo7ube3q3p/lib64/libcudart.so.10.1: error adding symbols: DSO missing from command line
```
mfem requires a newer version of cuda? [but then some other xsdk packages won't build]

2021-03-04 23:25 UTC, balay commented
Build without cuda works for me.
```
./bin/spack install --fail-fast -j64 xsdk-examples ^xsdk+trilinos ^openblas@0.3.5 ^boost@1.74.0
```

2021-03-05 11:08 UTC, balos1 commented
@balay Can you try 

```
spack install xsdk-examples+cuda ^xsdk~precice~dealii~trilinos~libensemble ^magma cuda_arch=70 ^mfem+cuda
```

with the latest commit I pushed? The concretizer does not like having `^mfem+cuda` in the xsdk examples package.py, but this seemed to work for me (very late in the build stage currently).

2021-03-05 11:10 UTC, alalazo approved these changes, later dismissed
LGTM looking just at Spack's idioms. Let me know when you think this is ready to be merged

2021-03-05 15:04 UTC, balay commented
@balos1 Thanks! I'm able to use `xsdk+cuda` now.  [If I help the conretizer with the additional `^petsc@3.14.1+cuda`

```
./bin/spack install --fail-fast -j64 xsdk-examples+cuda ^xsdk+trilinos  ^magma cuda_arch=60 ^cuda@10.1.243 ^openblas@0.3.5 ^openmpi+cuda ^boost@1.74.0 ^petsc@3.14.1+cuda
```
`^mfem+cuda` gives me errors. [ - mentioned in earlier comment - I think its missing `-lcudart` at link time  as mfem is compiled static - attaching the log]

[spack-build-out.txt](https://github.com/spack/spack/files/6091320/spack-build-out.txt)

2021-03-05 16:35 UTC, balay approved these changes, later dismissed

2021-03-05 20:49 UTC, balos1 commented
I think this is ready to merge.

2021-03-05 20:55 UTC, balay submitted a review, later dismissed

2021-03-08 19:12 UTC, tldahlgren approved these changes

2021-03-08 19:13 UTC, tldahlgren requested changes
LGTM but please resolve the flake8 error:

```
var/spack/repos/builtin/packages/xsdk-examples/package.py:9: [E302] expected 2 blank lines, found 1
```

2021-03-09 00:21 UTC, balos1 commented
> Please resolve the flake8 error:
> 
> ```
> var/spack/repos/builtin/packages/xsdk-examples/package.py:9: [E302] expected 2 blank lines, found 1
> ```

Fixed.

2021-03-18 18:31 UTC, luszczek approved these changes

2021-03-18 18:31 UTC, balos1 commented
@tldahlgren This is ready to merge.

2021-03-18 21:12 UTC, balay approved these changes

2021-03-18 21:57 UTC, tldahlgren commented on var/spack/repos/builtin/packages/xsdk-examples/package.py
> +    version('develop', branch='master')
We discourage naming a `master` branch `develop` even when there is no `develop` branch as that can be confusing to users who are used to having the two as separate branches in their workflows.

```suggestion
    version('master', branch='master')
```

2021-03-18 22:07 UTC, tldahlgren commented on var/spack/repos/builtin/packages/xsdk-examples/package.py
> +        if 'trilinos' in spec:  # if trilinos variant was activated for xsdk
I suspect this will be true whether `trilinos` is activated or not.

2021-03-18 22:09 UTC, tldahlgren commented on var/spack/repos/builtin/packages/xsdk-examples/package.py
> +        if 'zlib' in spec:  # if zlib variant was activated for MFEM
I suspect this will have the same issue as `trilinos`.

2021-03-18 22:10 UTC, tldahlgren reviewed
Is there an assumption here that `xsdk` has already been installed when one installs `xsdk-examples` or that it is explicitly specified on the command line as a dependency?

I ask because if I try `spack install xsdk-examples` without first installing `xsdk` I get a concretization failure:

```
xsdk requires petsc variant +trilinos, but spec asked for ~trilinos
```

2021-03-18 22:16 UTC, balay commented
> xsdk requires petsc variant +trilinos, but spec asked for ~trilinos

This is weird concretizer issue that always causes us grief.

```
spack spec xsdk-examples ^xsdk+trilinos ^boost@1.74.0
```

2021-03-18 22:24 UTC, tldahlgren commented on var/spack/repos/builtin/packages/xsdk-examples/package.py
> +    version('develop', branch='master')
I will "waive" this suggestion for now but do recommend it be changed in a subsequent PR.

2021-03-18 22:25 UTC, tldahlgren approved these changes

2021-03-18 22:25 UTC, merged

2021-03-18 22:25 UTC, tldahlgren commented
Thank you for your contribution.