Add new package: libuinputplus
LLNL/spack pull request #22129
Opened 2021-03-06 07:05 UTC by darmac

2021-03-10 10:29 UTC, alalazo requested changes
Curious if there is a reason to add only old versions of the package?

2021-03-10 10:29 UTC, alalazo commented on var/spack/repos/builtin/packages/libuinputplus/package.py
> +    version('0.1.4', sha256='a537e156d11ad00c643b93cbd9b712d3ec9d0ae8e40731ff763fe9a6ffe97458')
Can you also add newer versions? It seems there are v0.2.1 and v0.2.0 available.

2021-03-13 02:43 UTC, darmac commented on var/spack/repos/builtin/packages/libuinputplus/package.py
> +    version('0.1.4', sha256='a537e156d11ad00c643b93cbd9b712d3ec9d0ae8e40731ff763fe9a6ffe97458')
Emmm, there're build errors in `0.2.1` and `0.2.0` in the `install` phase.

2021-03-13 02:44 UTC, darmac commented on var/spack/repos/builtin/packages/libuinputplus/package.py
> +    version('0.1.4', sha256='a537e156d11ad00c643b93cbd9b712d3ec9d0ae8e40731ff763fe9a6ffe97458')
see as:
```
make: *** No rule to make target 'install'.  Stop.
==> Error: ProcessError: Command exited with status 2:
    'make' '-j4' 'install'

1 error found in build log:
     56    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-libuinputplus-0.2.0-7yrqnoun6kbaed7huybjdxp2cyhyhbk5/spack-build-7yrqnou'
     57    [100%] Built target uInputPlus_test
     58    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-libuinputplus-0.2.0-7yrqnoun6kbaed7huybjdxp2cyhyhbk5/spack-build-7yrqnou'
     59    /home/xiaojun/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/cmake-3.19.2-v4kxpjumu6q2sn357hshnf4zmhn4nj45/bin/cmake -E cmake_progress_start /tmp/root/spack-stage/spack-stage-libuinputplus-0.2.0-7yrqnoun6kbaed7huybjdxp2cyhyhbk5/
           spack-build-7yrqnou/CMakeFiles 0
     60    ==> libuinputplus: Executing phase: 'install'
     61    ==> [2021-03-13-10:40:46.229196] 'make' '-j4' 'install'
  >> 62    make: *** No rule to make target 'install'.  Stop.
```

I think the `cmake` is not generate `install` aim.

2021-05-10 02:26 UTC, closed without merging