Add new package: icoutils
LLNL/spack pull request #22159
Opened 2021-03-06 09:24 UTC by darmac

2021-03-08 23:14 UTC, tldahlgren commented on var/spack/repos/builtin/packages/icoutils/package.py
> +    homepage = "http://www.nongnu.org/icoutils"
```suggestion
    homepage = "https://www.nongnu.org/icoutils"
```

2021-03-08 23:14 UTC, tldahlgren commented on var/spack/repos/builtin/packages/icoutils/package.py
> +    url      = "http://nongnu.askapache.com/icoutils/icoutils-0.32.3.tar.bz2"
```suggestion
    url      = "https://nongnu.askapache.com/icoutils/icoutils-0.32.3.tar.bz2"
```

2021-03-08 23:15 UTC, tldahlgren commented
Please use `https` for these packages.

2021-03-08 23:41 UTC, tldahlgren commented on var/spack/repos/builtin/packages/icoutils/package.py
> +    depends_on('libpng')
FWIW. The dependencies can be further constrained per https://archlinux.org/packages/community/x86_64/icoutils/.

2021-03-20 12:32 UTC, alalazo requested changes
Can you use the `GnuMirrorPackage` mixin for this one? You may have a look at `automake` as an example.

2021-03-21 07:28 UTC, darmac commented
Of cource, but why we should add that, I didn't found the gnu url and there's no explanation for `GNUMirrorPackage` in spack manu.

2021-05-10 02:30 UTC, closed without merging