bugfix: ensure spack test list still works
LLNL/spack pull request #22203
Opened 2021-03-09 21:06 UTC by tldahlgren

Was getting the following error:

```
$ spack test list
==> Error: issubclass() arg 1 must be a class
```

This PR adds a check in `has_test_method` (in case it is re-used elsewhere such as #22097) and ensures a class is passed to the method from `spack test list`.

2021-03-10 01:56 UTC, tgamblin approved these changes

2021-03-10 01:56 UTC, tgamblin requested changes
LGTM! Needs patch coverage.

2021-03-10 19:48 UTC, tldahlgren commented
> LGTM! Needs patch coverage.

Yeah.  I only covered the method body, not the new exception.

2021-03-12 17:56 UTC, tgamblin approved these changes

2021-03-12 17:56 UTC, tldahlgren commented
@tgamblin Only thing left is project coverage that seems to typically be broken.

2021-03-12 17:56 UTC, merged