py-pytest-html recipe
LLNL/spack pull request #22221
Opened 2021-03-10 12:18 UTC by BerengerBerthoul

Recipe for the pure Python pytest-html package

2021-03-10 17:58 UTC, adamjstewart requested changes

2021-03-10 17:58 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pytest-html/package.py
> +from spack import *
Missing a license. You can copy the text from any other file in Spack.

2021-03-10 17:58 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pytest-html/package.py
> +    depends_on('py-setuptools', type='build')
Missing deps:
```python
    setup_requires=["setuptools_scm"],                                                   
    install_requires=["pytest>=5.0,!=6.0.0", "pytest-metadata"],
```

2021-03-10 20:39 UTC, adamjstewart requested changes

2021-03-10 20:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pytest-html/package.py
> +    depends_on('py-pytest@5.0:5.9,6.1:', type=('build', 'run'))
```suggestion
    depends_on('py-pytest@5.0:5.999,6.0.1:', type=('build', 'run'))
```

2021-03-10 20:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pytest-metadata/package.py
> +    depends_on('python@3.6:', type=('build', 'run'))
```suggestion
    depends_on('python@2.7:2.8,3.6:', type=('build', 'run'))
```

2021-03-10 20:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pytest-metadata/package.py
> +
This blank line at the end of the file will cause flake8 to fail

2021-03-10 21:07 UTC, adamjstewart submitted a review, later dismissed

2021-03-10 21:11 UTC, BerengerBerthoul commented
Thanks for the quick feed

2021-03-11 19:32 UTC, adamjstewart approved these changes

2021-03-12 02:17 UTC, merged