abinit: fix detection of Fujitsu compiler
LLNL/spack pull request #22239
Opened 2021-03-11 08:31 UTC by m-shunji

The ABINIT configure script doesn't detect newer version of Fujitsu compiler and doen't set compiler options intended for fujitsu compiler.
This PR fix fujitsu patch to detect Fujitsu compiler correctly and set appropriate compiler options according to its version.

2021-03-16 08:50 UTC, t-karatsu submitted a review, later dismissed
LGTM.

2021-03-17 10:26 UTC, alalazo requested changes
Can you also update the comment above the patch directive in `package.py`? Currently it doesn't mention detection of the Fujitsu compiler.

2021-03-18 06:54 UTC, t-karatsu approved these changes

2021-03-18 07:00 UTC, alalazo approved these changes

2021-03-19 00:16 UTC, tldahlgren commented
Appears to be an intermittent failure in `linux tests / unittests (3.6, clingo)` so closing and re-opening to force re-running the tests.

2021-03-19 12:27 UTC, merged