py-aioitertools: New package
LLNL/spack pull request #22256
Opened 2021-03-12 10:53 UTC by a-saitoh-fj

py-aioitertools: New package

2021-03-12 17:37 UTC, adamjstewart requested changes

2021-03-12 17:37 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-aioitertools/package.py
> +    url      = "https://files.pythonhosted.org/packages/32/0b/3260ac050de07bf6e91871944583bb8598091da19155c34f7ef02244709c/aioitertools-0.7.1-py3-none-any.whl"
Can you switch to the source build?

2021-03-12 17:37 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-aioitertools/package.py
> +    depends_on('python@3.6:3.7.999', type=('build', 'run'))
```suggestion
    depends_on('python@3.6:', type=('build', 'run'))
```

2021-03-15 01:47 UTC, a-saitoh-fj commented
Fixed the pointed out point.
- Fixed python dependencies.

And,
I'm sorry, I didn't have enough confirmation.
- The description was too long, so I put a line break
- I deleted it because there was extra space.

"Can you switch to the source build?"
I also tried a source build with tar.gz, but I couldn't build this oss because setup.py isn't available.

2021-03-15 02:11 UTC, adamjstewart commented
If I download https://files.pythonhosted.org/packages/dc/a0/f149e54ea082e5f4ae71c68e8e72cab8749283329a7c2747336ef7b68dc0/aioitertools-0.7.1.tar.gz and extract it, there is a `setup.py` file right at the top level.

2021-03-15 04:03 UTC, a-saitoh-fj commented
py-aioitertools: Switch to the source build

I'm sorry. The source code I was referring to was different.
I changed to the source build, so please check here.

2021-03-15 04:08 UTC, adamjstewart approved these changes

2021-03-15 04:58 UTC, merged