py-aiobotocore: New package
LLNL/spack pull request #22258
Opened 2021-03-12 11:02 UTC by a-saitoh-fj

py-aiobotocore: New package
You need py-botocore(#22257) and py-aioitertools(#22256) to build this OSS.

2021-03-12 17:32 UTC, adamjstewart requested changes

2021-03-12 17:32 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-aiobotocore/package.py
> +
Can you add:
```python
depends_on('python@3.6:', type=('build', 'run'))
```

2021-03-14 05:39 UTC, a-saitoh-fj commented
Fixed the pointed out point.
- Added python dependencies

And,
I'm sorry, I didn't have enough confirmation.
I deleted it because there was extra space.

2021-03-14 06:03 UTC, adamjstewart approved these changes

2021-03-16 08:45 UTC, a-saitoh-fj commented
All checks seem to be fine.
If your review is okay, I hope it will be merged.

2021-03-16 13:57 UTC, merged