spack recipes for AOCL-3.0 release
LLNL/spack pull request #22276
Opened 2021-03-13 11:09 UTC by amd-toolchain-support

2021-03-15 17:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/aocl-sparse/package.py
> +    def cmake(self, spec, prefix):
Why not implement `cmake_args` to create and return the list of arguments and leave lines 86-87 to the base class?

2021-03-15 17:41 UTC, tldahlgren commented on var/spack/repos/builtin/packages/aocl-sparse/package.py
> +    depends_on('boost', when='@2.2')
Is `boost` really a dependency only for version 2.2?

2021-03-15 17:43 UTC, tldahlgren commented on var/spack/repos/builtin/packages/amdblis/package.py
> +    def configure(self, spec, prefix):
There's a lot of duplication here with `BlisBase`'s `configure`.  Why not add an `configure_args` method here and in `BlisBase` to eliminate the duplication?

2021-03-16 19:36 UTC, tldahlgren commented
Closing and re-opening to force re-running tests since there is a strange gateway error from the clingo tests:

```
Err:50 https://dl.bintray.com/sbt/debian  Release 
63  502  Bad Gateway [IP: 52.35.223.108 443]
64  Reading package lists...
65  E: The repository 'https://dl.bintray.com/sbt/debian  Release' no longer has a Release file.
```

2021-03-16 21:51 UTC, tldahlgren commented
This is a known issue -- https://github.com/actions/runner/issues/932 -- will try to close and re-open again.

2021-03-16 22:49 UTC, tldahlgren requested changes
Some of the failures being reported *appear* to be intermittent.  

Please resolve the conflicts for `aocl-parse` caused by merging #22079 .  Hopefully either they'll resolve the runner action issue or we'll get lucky on the next round.

2021-03-18 08:38 UTC, amd-toolchain-support commented
Closing this pull request has rebase of aocl-sparse resulting in below error:

Your branch and 'origin/aocl_3_0_0' have diverged,
and have 56 and 3 different commits each, respectively.

Will raise another pull request and give this reference.

2021-03-18 08:38 UTC, closed without merging

2021-03-18 08:38 UTC, amd-toolchain-support commented
Closing this pull request has rebase of aocl-sparse resulting in below error:

Your branch and 'origin/aocl_3_0_0' have diverged,
and have 56 and 3 different commits each, respectively.

Will raise another pull request and give this reference.

2021-03-18 09:21 UTC, amd-toolchain-support commented
New pull request:
https://github.com/spack/spack/pull/22376