py-dask-glm: Added document build
LLNL/spack pull request #22293
Opened 2021-03-15 02:31 UTC by a-saitoh-fj

py-dask-glm: Added document build

2021-03-16 21:44 UTC, adamjstewart requested changes

2021-03-16 21:44 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-dask-glm/package.py
> +    depends_on('harfbuzz+graphite2', type=('build', 'run'), when='+docs')
All doc deps should be type=build, the deps aren't needed at run-time.

2021-03-22 23:16 UTC, a-saitoh-fj commented
py-dask-glm
Push again for testing with git.

In the same way as #22260, I did the following:
I deleted the branch and recreated it with the same name, and, I pushed 'git push --force'.

2021-03-23 02:32 UTC, a-saitoh-fj commented
@adamjstewart 

py-dask-glm
Fixed the pointed out OSS dependency setting to type=build.

Sorry for the late response.

2021-03-23 17:08 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-dask-glm/package.py
> +    depends_on('py-s3fs', type=('build', 'run'), when='+docs')
The rest of these doc deps should be type=build, right?

2021-03-24 03:00 UTC, a-saitoh-fj commented
@adamjstewart 
I'm sorry, I misunderstood the meaning of 'all'.

py-dask-glm
Set depends_on to type=build in the OSS to be built when building the document.

2021-03-24 15:46 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-dask-glm/package.py
> +    depends_on('py-scikit-learn@0.18:0.21.999', type='build', when='+docs')
```suggestion
    depends_on('py-scikit-learn@0.18:0.21.999', type=('build', 'run'), when='+docs')
```
Even if docs are built, sklearn is still needed at run-time.

2021-03-25 00:20 UTC, a-saitoh-fj commented
@adamjstewart 
What you pointed out is correct.
I fixed it.

2021-03-25 00:21 UTC, adamjstewart approved these changes

2021-03-25 00:32 UTC, merged