Make stage use concrete specs from environment
LLNL/spack pull request #22320
Opened 2021-03-16 12:35 UTC by haampie

Same as in https://github.com/spack/spack/pull/21642, the idea is that
we want to easily stage a package that fails to build in a complex
environment. Instead of making the user create a spec by hand (basically
transforming all the rules in the environment manifest into a spec,
defying the purpose of the environment...), use the provided spec as a
filter for the already concretized specs. This also speeds up things,
cause we don't have to reconcretize.

2021-03-24 20:03 UTC, becker33 requested changes
This needs a test. Otherwise LGTM

2021-03-26 13:51 UTC, haampie commented
Okay, I don't know how to test this other than mocking do_stage. Let me know if you want something better (and how).

2021-03-26 13:52 UTC, haampie commented on lib/spack/spack/test/cmd/stage.py
> +    """Verify that stage filters specs in environment."""
```suggestion
    """Verify that a full environment is staged when no specs are provided."""
```

2021-03-29 17:57 UTC, becker33 approved these changes

2021-03-29 17:57 UTC, becker33 commented on lib/spack/spack/test/cmd/stage.py
> +    assert len(expected) == 0
That's a fun way of mocking this test to only test the command, not the underlying functionality. +1

2021-03-29 18:10 UTC, merged