bump mochi-margo to 0.9.2
LLNL/spack pull request #22368
Opened 2021-03-17 21:14 UTC by carns

Adds new version 0.9.2 to mochi-margo and deprecated margo packages.

2021-03-20 09:48 UTC, alalazo requested changes

2021-03-20 09:48 UTC, alalazo commented on var/spack/repos/builtin/packages/margo/package.py
> +    version('0.9.1', sha256='3fe933f2d758ef23d582bc776e4f8cfae9bf9d0849b8b1f9d73ee024e218f2bc', deprecated=True)
Ugh, are we adding versions and deprecating them at the same time?

2021-03-25 14:25 UTC, carns reviewed
FYI, I just added version 0.9.3 as well (this is a bug fix release that has been produced since this PR was first opened).

2021-03-25 14:25 UTC, carns commented on var/spack/repos/builtin/packages/margo/package.py
> +    version('0.9.1', sha256='3fe933f2d758ef23d582bc776e4f8cfae9bf9d0849b8b1f9d73ee024e218f2bc', deprecated=True)
I just pushed a redo of this PR that doesn't add a new version there (though it does still touch the margo package because I noticed I accidentally omitted the deprecated tag on a version that was already there).

As soon as a Spack release is made that has margo deprecated I'll submit a PR to remove it.

2021-03-27 12:22 UTC, carns commented
Added one more point release (another bug fix) and also rebased to origin/develop again.

2021-03-27 13:29 UTC, alalazo approved these changes

2021-03-27 13:29 UTC, merged