Archxlith/py scikit image
LLNL/spack pull request #22363
Opened 2021-03-17 19:17 UTC by archxlith

2021-03-19 03:15 UTC, adamjstewart requested changes

2021-03-19 03:15 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-scikit-image/package.py
>      depends_on('python@3.6:', when='@0.16.1:')
```suggestion
    depends_on('python@3.7:', when='@0.18:', type=('build', 'run'))
    depends_on('python@3.6:', when='@0.16.1:', type=('build', 'run'))
```

2021-03-19 03:15 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-scikit-image/package.py
>      depends_on('py-numpy@1.14.1:', type=('build', 'run'), when='@0.16.1:')
Can you add:
```python
depends_on('py-numpy@1.16.5:', type=('build', 'run'), when='@0.18:')
```

2021-03-22 13:54 UTC, archxlith commented
Made requested change.

2021-03-29 20:14 UTC, archxlith commented on var/spack/repos/builtin/packages/py-scikit-image/package.py
>      depends_on('python@3.6:', when='@0.16.1:')
python version dependencies updated.

2021-03-29 20:24 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-scikit-image/package.py
> +    depends_on('python@3.7:', when='@0.18:', type=('build', 'run')))
```suggestion
    depends_on('python@3.7:', when='@0.18:', type=('build', 'run'))
```

2021-04-07 01:38 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-scikit-image/package.py
> +    depends_on('python@3.7:', when='@0.18:', type=('build', 'run')))
Ping @archxlith

2021-04-07 03:04 UTC, adamjstewart approved these changes, later dismissed

2021-04-07 03:13 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-scikit-image/package.py
> +    depends_on('python@3.6:', when='@0.16.1:', type=('build', 'run'))
```suggestion
    depends_on('python@3.7:', when='@0.18:', type=('build', 'link', 'run'))
    depends_on('python@3.6:', when='@0.16.1:', type=('build', 'link', 'run'))
```

2021-04-07 03:14 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-scikit-image/package.py
> +    depends_on('py-numpy@1.16.5:', type=('build', 'run'), when='@0.18:')
```suggestion
    depends_on('py-numpy@1.14.1:', type=('build', 'link', 'run'), when='@0.16.1:')
    depends_on('py-numpy@1.15.1:', type=('build', 'link', 'run'), when='@0.17.1:')
    depends_on('py-numpy@1.16.5:', type=('build', 'link', 'run'), when='@0.18:')
```

2021-04-07 03:16 UTC, adamjstewart approved these changes

2021-04-07 03:20 UTC, adamjstewart commented
Successfully builds on macOS 10.15.7 with Python 3.8.8 and Apple Clang 12.0.0. The previous version of `py-scikit-image` seems to have some build errors, not sure why.

2021-04-07 03:32 UTC, merged