Exclude Python 3.5 3.6 3.7 3.8 from PRs
LLNL/spack pull request #22408
Opened 2021-03-19 11:30 UTC by haampie

CI runs unbearably slow, so why don't stick to testing newest and oldest supported python in PRs, and test all support versions when merged.

2021-03-19 11:36 UTC, alalazo requested changes
Would it be possible to require certain tests to pass with this? I think we can't require both `is_pr: true` and `is_pr: false` since one won't run on pushes the other won't run on prs

2021-03-19 11:39 UTC, haampie commented
¯\_(ツ)_/¯

2021-03-19 13:14 UTC, alalazo commented
Due to how Github Actions work changing the job names require a restart and re-run of all the PRs that are pending, if we want to have a green light on required checks. I'm wondering if we can rework conditionals so that they don't affect the current names and require only to uncheck things, not to check new ones.

2021-03-19 17:40 UTC, tgamblin commented
I'm hesitant to do this one first but we do need to do something.  Let's try Max's PRs (#22410, #22421), as well as reducing the amount of testing on the old concretizer, first.

2021-03-21 10:47 UTC, haampie commented
Closing this for now

2021-03-21 10:47 UTC, closed without merging