new package py-pyem
LLNL/spack pull request #22425
Opened 2021-03-19 20:22 UTC by dorton21

2021-03-19 21:35 UTC, adamjstewart reviewed
The empty line on the last line and the long line will probably cause flake8 to fail.

2021-03-19 21:35 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyem/package.py
> +    homepage = "https://pypi.org/project/pyem/#description"
You can drop this line, it's inferred from the `pypi` attribute

2021-03-19 21:35 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyem/package.py
> +        filter_file(r'from distutils.core import setup', 'from setuptools import setup', 'setup.py')
I would add a comment explaining why this patch is necessary:
```python
# distutils does not support entry_points, setuptools needed to install pyem binary
```

2021-03-22 18:24 UTC, alalazo requested changes
Flake8 issues:
```
var/spack/repos/builtin/packages/py-pyem/package.py:26: [E501] line too long (100 > 88 characters)
var/spack/repos/builtin/packages/py-pyem/package.py:27: [W391] blank line at end of file
```

2021-03-22 21:22 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyem/package.py
> +    version('2.1.0', sha256='5234a20427ab2813a8a0bf1e9112d4d854b1b0502b3e63d17c1b1a3c4be9340e')
Can you move the version above depends_on?

2021-03-23 19:58 UTC, adamjstewart approved these changes

2021-03-23 20:25 UTC, alalazo approved these changes

2021-03-23 20:25 UTC, merged