New package py-gffutils
LLNL/spack pull request #22552
Opened 2021-03-25 17:09 UTC by dorton21

depends on #22551

2021-03-26 23:44 UTC, adamjstewart requested changes

2021-03-26 23:44 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-gffutils/package.py
> +    url      = "https://github.com/daler/gffutils/archive/refs/tags/v0.10.1.tar.gz"
https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#pypi-vs-github

2021-03-30 18:19 UTC, adamjstewart approved these changes

2021-04-01 12:08 UTC, haampie approved these changes

2021-04-02 18:40 UTC, dorton21 commented
Can I get an update on this?

2021-04-02 18:42 UTC, haampie commented
``` 
E       AssertionError: These packages have missing dependencies:
E         py-gffutils: [py-argh]
E       assert not {'py-gffutils': {'py-argh'}}
```

2021-04-02 18:43 UTC, haampie commented
normally ci runs on a merge commit with develop, not sure what's wrong here. can you maybe rebase on develop and  push again?

2021-04-02 19:10 UTC, adamjstewart commented
You just have to close and reopen the PR to get it to rerun with dependent packages that have already been merged into develop.

2021-04-02 19:54 UTC, dorton21 commented
Thanks

2021-04-02 20:33 UTC, merged