bugfix for active when pkg is already active error
LLNL/spack pull request #22587
Opened 2021-03-26 23:30 UTC by cyrush

resolves #22530

instead of throwing an error for an already active package, prints a message and returns to avoid an attempt to re-activate.

2021-03-26 23:38 UTC, cyrush commented on lib/spack/spack/package.py
> +            extensions_layout.check_extension_conflict(
Continuation line over-indented for hanging indent (E126) for this, not sure where it needs to line up?

2021-03-26 23:42 UTC, becker33 requested changes
Otherwist LGTM, when the code style error is fixed I'll turn automerge on.

2021-03-26 23:42 UTC, becker33 commented on lib/spack/spack/package.py
> +                    self.extendee_spec, self.spec)
```suggestion
            extensions_layout.check_extension_conflict(
               self.extendee_spec, self.spec)
```

2021-03-26 23:46 UTC, cyrush commented
thanks @becker33 !

2021-03-26 23:47 UTC, becker33 approved these changes

2021-03-28 04:56 UTC, becker33 requested changes
@cyrus we were off by one space on the previous commit

2021-03-28 04:56 UTC, becker33 commented on lib/spack/spack/package.py
> +               self.extendee_spec, self.spec)
```suggestion
            extensions_layout.check_extension_conflict(
                self.extendee_spec, self.spec)
```

2021-03-30 00:02 UTC, cyrush commented
codecov not happy, but that makes sense -- how can we create a test that exercises this?

2021-03-30 00:09 UTC, becker33 approved these changes

2021-03-30 00:09 UTC, merged

2021-03-30 00:10 UTC, becker33 commented
Just merged -- we didn't reduce coverage, and it is likely to only affect a few users, since `spack activate` is not the most common way to handle python packages anymore.

2021-03-30 17:12 UTC, cyrush commented
thanks @becker33 !