Documentation and new method for `CachedCMakePackage` build system
LLNL/spack pull request #22706
Opened 2021-04-01 00:53 UTC by becker33

#19316 introduced a new build system class `CachedCMakePackage` to handle an alternative workflow for CMake packages.

This PR adds documentation for that functionality.

2021-04-01 04:14 UTC, ax3l commented on lib/spack/docs/build_systems/cachedcmakepackage.rst
> +       if `+mpi` in self.spec:
Typo?
```suggestion
       if '+mpi' in self.spec:
```

2021-04-01 05:40 UTC, becker33 commented on lib/spack/docs/build_systems/cachedcmakepackage.rst
> +       if `+mpi` in self.spec:
Yep, thanks! Too much RST on the brain!

2021-09-09 22:26 UTC, ax3l approved these changes, later dismissed
LGTM, let's get this in.

2021-09-09 22:26 UTC, ax3l commented
restarting CI

2021-09-09 22:29 UTC, ax3l commented on lib/spack/docs/build_systems/cachedcmakepackage.rst
> +   # includes information on mpi and cuda if applicable
I wonder if the new CMake preset files can be used for this in the future: https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html

2022-03-18 15:45 UTC, sethrj commented on lib/spack/docs/build_systems/cachedcmakepackage.rst
> +   # includes information on mpi and cuda if applicable
Yes -- they're designed partly to replace these sort of cache configurations.

2022-05-05 13:26 UTC, alalazo commented
@becker33 Let me know if this PR is still up to date. I think we can merge it before v0.18

2022-05-23 19:50 UTC, becker33 commented
I believe this is still current

2022-05-23 20:20 UTC, alalazo requested changes
Two typos, then this will be mergeable.

2022-05-23 20:20 UTC, alalazo commented on lib/spack/docs/build_systems/cachedcmakepackage.rst
> +The ``CachedCMakePackage base class comes with the following phases:
```suggestion
The ``CachedCMakePackage`` base class comes with the following phases:
```

2022-05-23 20:20 UTC, alalazo commented on lib/spack/docs/build_systems/cachedcmakepackage.rst
> +for :ref:`CMakePackage <_cmakepackage>`.
```suggestion
for :ref:`CMakePackage <cmakepackage>`.
```

2022-05-23 20:21 UTC, alalazo approved these changes

2022-05-23 22:48 UTC, merged