Create ExaGO Package
LLNL/spack pull request #22734
Opened 2021-04-01 21:05 UTC by CameronRutherford

Creating the ExaGO spack package along with release version 1.0.0.

cc @haampie as you were generous to review @ashermancinelli 's previous PRs

cc @pelesh @cnpetra

2021-04-02 15:53 UTC, haampie requested changes

2021-04-02 15:53 UTC, haampie commented on var/spack/repos/builtin/packages/exago/package.py
> +            args.append("-DEXAGO_ENABLE_MPI=OFF")
```suggestion
        args.append(self.define_from_variant('EXAGO_ENABLE_MPI', 'mpi'))
```

2021-04-02 15:53 UTC, haampie commented on var/spack/repos/builtin/packages/exago/package.py
> +                    "-DCMAKE_CUDA_ARCHITECTURES={0}".format(cuda_arch))
This requires cmake 3.18 but above you require 3.15

2021-04-02 15:56 UTC, haampie commented
Notice that you likely don't need to set `*_DIR` and that would let you simplify a lot of config options to one-liners:

```diff
-         if '+raja' in spec:
-             args.append("-DEXAGO_ENABLE_RAJA=ON")
-             args.append("-Dumpire_DIR='{0}'".format(spec['umpire'].prefix))
-             args.append("-DRAJA_DIR='{0}'".format(spec['raja'].prefix))
-         else:
-             args.append("-DEXAGO_ENABLE_RAJA=OFF")
+         args.append(self.define_from_variant('EXAGO_ENABLE_RAJA', 'raja'))
```

as long as your cmake uses `find_*` it will consider the spack provided search paths (through CMAKE_PREFIX_PATH)

2021-04-02 16:45 UTC, ashermancinelli commented
@haampie `self.define_from_variant` looks very cool and helpful - thanks for pointing this out! @CameronRutherford, could you test out our stack after incorporating @haampie 's suggestions?

2021-04-02 19:10 UTC, CameronRutherford commented
@haampie I incorporated your suggestions, and they seem to work! Thanks for the feedback, and hopefully this should be good to go.

2021-04-07 11:48 UTC, haampie approved these changes

2021-04-07 11:48 UTC, haampie commented
very pretty :relieved:

2021-04-07 11:48 UTC, merged