collectd: add dependencies
LLNL/spack pull request #22746
Opened 2021-04-02 06:56 UTC by darmac

Add `flex` and `bison` to fix build error like that:
![image](https://user-images.githubusercontent.com/29532367/113389852-4f1ae300-93c3-11eb-82ee-be6b42c70438.png)

According to `readme` in collectd, we can get that `flex` and `bison` are required too, when we use git repository.
![image](https://user-images.githubusercontent.com/29532367/113390015-8e493400-93c3-11eb-9244-f883ef5cf8fc.png)

2021-04-06 08:23 UTC, alalazo commented
The portion of the README highlighted here says they are needed when building from the Git repository, but it seems to me we are building from release tarballs instead.

2021-04-06 12:10 UTC, darmac commented
> The portion of the README highlighted here says they are needed when building from the Git repository, but it seems to me we are building from release tarballs instead.

Yes, but we still met this issue, so I think we should add that too.

2021-04-07 10:26 UTC, alalazo commented
> Yes, but we still met this issue, so I think we should add that too.

I double checked. We should use a different `url`:
```
https://github.com/collectd/collectd/releases/download/collectd-5.12.0/collectd-5.12.0.tar.bz2
``` 
and retrieve the tarball with configure already generated. I think we may be able to remove other build deps as well.

2021-04-08 09:06 UTC, alalazo requested changes
Can you take care of https://github.com/spack/spack/pull/22746#issuecomment-814799049https://github.com/spack/spack/pull/22746#issuecomment-814799049 ? I think we may noot need any build deps if we build from the official release tarballs.

2021-04-08 11:06 UTC, darmac commented
> Can you take care of [#22746 (comment)](https://github.com/spack/spack/pull/22746#issuecomment-814799049https) ? I think we may noot need any build deps if we build from the official release tarballs.

OK, I will update this patch

2021-04-08 11:47 UTC, alalazo approved these changes

2021-04-08 11:47 UTC, merged