fix spack location [spec] without args
LLNL/spack pull request #22755
Opened 2021-04-02 15:48 UTC by haampie

should return source dir

Fixes #22738

2021-04-02 16:00 UTC, adamjstewart approved these changes, later dismissed

2021-04-06 05:16 UTC, alalazo approved these changes

2021-04-06 05:18 UTC, alalazo requested changes
Looking at the associated issue, a very minor request.

2021-04-06 05:18 UTC, alalazo commented on lib/spack/spack/test/cmd/location.py
> +    assert location(spec.name).strip() == pkg.stage.source_path
Can you add on top of this test:
```
@pytest.mark.regression('22738')
```

2021-04-06 08:03 UTC, alalazo approved these changes

2021-04-06 08:17 UTC, merged