When perl is @5.32.1, building it with intel@19.1.2.254 leads to an e…
LLNL/spack pull request #22771
Opened 2021-04-04 11:17 UTC by ikitayama

…rror,

add a conflicts line.

@haampie could you review this?

2021-04-04 11:19 UTC, haampie commented
Did you test other intel compilers too? The conflict looks a bit too specific to me

2021-04-04 11:20 UTC, ikitayama commented
No, but this is the module JURECA DC admins are providing to the users, thus I am stumbled upon.

2021-04-04 11:21 UTC, ikitayama commented
`intel@2021.1` which I built with Spack works fine with `perl@5.32.1`

2021-04-04 11:23 UTC, ikitayama commented
Too specific, but it'd help others wondering why intel@19.1.2.254 does not work.

2021-04-04 22:07 UTC, ikitayama commented
@haampie so I make the package build to fail, but wonder tests are supposed to understand the failure?

2021-04-06 11:53 UTC, haampie commented on var/spack/repos/builtin/packages/perl/package.py
> +    # Avoid build of 5.32.1 with intel@19.1.2.254
```suggestion
    # Avoid build of 5.32.1 with intel@19.1.2.254
```

2021-04-06 11:54 UTC, haampie requested changes
There's a style issue, see the failing github action. Can you actually update the comment to something more descriptive as to why it conflicts?

2021-04-09 21:32 UTC, ikitayama commented
See #22813, this proposed patch is quite incomplete, turned out.

2021-04-09 21:32 UTC, closed without merging