Fixed Python Dep and Missing Versions of Exodusii
LLNL/spack pull request #22819
Opened 2021-04-06 22:15 UTC by rspavel

Fixed previously unspecified python dependency and ensured that spack's
python is what exodus@v2016 uses. Also, in the process, identified many
missing versions

2021-04-07 07:12 UTC, alalazo requested changes
I see that this package seems to duplicate part of what the `seacas` package already does + it points to the same repository. Is there a reason for that? @gsjaardema

2021-04-07 13:41 UTC, rspavel commented
My understanding is that exodusii is a sub-package of seacas (which may also be a sub-package of trilinos?). Purely based on conjecture and use cases, I would suspect they were split up because the super-packages add considerably more dependencies (that may be exposed in a way that can be disabled now) and potentially introduce a LOT of concretization issues in spack as the method to reduce unnecessary dependencies (e.g. `foo~bar~baz+qux` as we only need `qux` from the spackage) invariably introduces a lot of conflicts (e.g. `foo+bar~baz~qux` same as before but we only need `bar`)

2021-04-08 09:12 UTC, alalazo commented
@rspavel Thanks for the explanation. I am not a fan of duplicating recipes from the same repository, but I understand why this was done. Waiting for @gsjaardema opinion on this PR. Feel free to ping me in a few days if this conversation seems to be stale.

2021-04-08 14:00 UTC, gsjaardema commented
I wasn't aware of the existance of this package (or have forgotten...). Exodus is a sub-package of seacas.   Seacas also exists in Trilinos, but the main development repository is the seacas repository. 

There is a way to build `seacas` with just the `exodus`, `exodus-fortran`, and `Ioss` libraries; but I don't have a variant for just `exodus` (C API Only), but one could be added if needed.

Also, not sure there is a python dependency...  There is a python exodus interface, but there is nothing in the build of `exodus` that requires python?  There is a check for the default python version to see whether to install the python3 or python2 exodus python interface, so I guess that could be a dependence on python...

2021-04-08 14:08 UTC, rspavel commented
Yeah. I am not 100% sure what (if anything) changed but we were running in to build issues because the seacas/exodus version of tribits does look for python and errors out if it is too old. My suspicion is that on other platforms the system python was sufficiently new and we never noticed but we needed to manually specify to build in this case because of something a local sysadmin might have done.

I think the long term solution will need to be some middle ground for specifying the spec in spack. Being able to say "I would prefer these features be disabled but they don't impact me" would probably work well with The New Concretizer. We might be able to get away with just setting default offs but a lot of the actual users of the super-spackages likely want all of those features enabled.

Short term: I am kind of in favor of fixing the existing kludges since a few spackages (and apps) depend on it.

2021-04-08 14:25 UTC, gsjaardema commented
@rspavel Yes, agreed.   I will check the "python check" since if the build does error out for an old python, it does essentially depend on python...

I am fine with keeping the package existing since, as you note, there may be people depending on it currently.

2021-04-08 14:35 UTC, alalazo approved these changes
@gsjaardema approved. Changes are fine.

2021-04-08 14:36 UTC, merged