Octave Optim: making the proper dependencies
LLNL/spack pull request #22909
Opened 2021-04-09 15:36 UTC by cessenat

Dependencies were not correct.
It's a bug correction.

2021-04-15 12:49 UTC, alalazo requested changes

2021-04-15 12:49 UTC, alalazo commented on var/spack/repos/builtin/packages/octave-optim/package.py
> +    extends('octave@4.0.0:', when='@1.6.2:')
We have v1.6.1 listed which falls out of these boundaries but it's clearly an octave extension.

2021-04-16 07:17 UTC, alalazo approved these changes

2021-04-16 07:17 UTC, merged

2021-04-16 08:44 UTC, cessenat commented
Thank you