libsakura: Change precision for fftw dependency depending on libsakura version
LLNL/spack pull request #22924
Opened 2021-04-11 19:31 UTC by mpokorny

libsakura version determines whether FFTW dependency needs single or double precision variant

2021-04-11 20:40 UTC, haampie requested changes

2021-04-11 20:40 UTC, haampie commented on var/spack/repos/builtin/packages/libsakura/package.py
> +    depends_on('fftw@3.3.2: precision=float', when='@:4.0.0')
```suggestion
    depends_on('fftw@3.3.2: precision=float', when='@:3.99.99')
```

2021-04-12 06:36 UTC, haampie approved these changes

2021-04-12 06:38 UTC, haampie commented
Last comment: if you want to support more than just `fftw`, depend on `fftw-api` instead

2021-04-12 06:38 UTC, merged

2021-04-12 19:34 UTC, mpokorny commented
Thanks, @haampie . I did notice the `fftw-api` virtual package recently. Seemed like I'd be going out on a limb a bit if I used the `fftw-api` dependency without some testing.  Sounds like a good idea, though, and I'll consider it for a future update.