New package: py-tensorflow-hub
LLNL/spack pull request #23034
Opened 2021-04-16 14:42 UTC by qwertos

2021-04-16 21:07 UTC, adamjstewart requested changes

2021-04-16 21:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-tensorflow-hub/package.py
> +    url = "https://pypi.io/packages/py2.py3/t/tensorflow_hub/tensorflow_hub-0.11.0-py2.py3-none-any.whl"
Since PyPI only has wheels, let's download and install from GitHub instead: https://github.com/tensorflow/hub/archive/refs/tags/v0.12.0.tar.gz

2021-04-16 21:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-tensorflow-hub/package.py
> +    depends_on('py-tensorflow-estimator',   type=('build', 'run'))
Missing some deps:
https://github.com/tensorflow/hub/blob/master/tensorflow_hub/pip_package/setup.py#L28,L31

2021-04-27 18:59 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-tensorflow-hub/package.py
> +    depends_on('py-protobuf@3.8.0:',   type=('build', 'run'))
Missing build dep on setuptools

2021-04-29 21:01 UTC, adamjstewart submitted a review, later dismissed
@aweits can you review?

2021-04-29 22:20 UTC, aweits commented on var/spack/repos/builtin/packages/py-tensorflow-hub/package.py
> +        install_tree(join_path(runfiles, tensorflow_hub),
```suggestion
        install_tree(join_path(runfiles, 'tensorflow_hub'),
```

2021-05-03 15:58 UTC, adamjstewart approved these changes

2021-05-03 16:04 UTC, merged