rocm-4.1.0 release-add git repo path, modify hipfft package recipe
LLNL/spack pull request #23119
Opened 2021-04-19 19:18 UTC by srekolam

2021-04-19 19:27 UTC, haampie commented
depends_on(..., when='master')?

2021-04-19 20:15 UTC, haampie requested changes

2021-04-19 20:15 UTC, haampie commented on var/spack/repos/builtin/packages/hipfft/package.py
> +    for ver in ['4.1.0']:
```suggestion
    for ver in ['4.1.0', 'master']:
```

2021-04-19 20:19 UTC, srekolam commented on var/spack/repos/builtin/packages/hipfft/package.py
> +    for ver in ['4.1.0']:
@haampie , i have not tested the master for rocfft etc.. hence did not want to add it at this moment. its a work in progress.

2021-04-29 19:15 UTC, srekolam commented
@haampie , can you please approve this PR.

2021-04-29 19:24 UTC, haampie approved these changes

2021-04-29 19:24 UTC, merged