argobots: changed 'no' into 'none' for variant
LLNL/spack pull request #23171
Opened 2021-04-21 15:48 UTC by mdorier

This PR fixes a problem (see https://github.com/spack/spack/issues/23168) introduced by a recent change to the Argobots package (https://github.com/spack/spack/pull/23133). The PR replaces the value `no` with `none` for the `stackguard` variant, as `no` seems to produce a faulty behavior from Spack.

@shintaro-iwasaki

2021-04-21 15:49 UTC, shintaro-iwasaki commented
@mdorier Thanks! It looks good to me.

2021-04-23 01:12 UTC, tldahlgren requested changes, later dismissed
Please change line 64 to reflect the modified value.

2021-04-23 08:20 UTC, mdorier commented
Thanks for pointing this out; it's corrected.

2021-04-23 12:11 UTC, alalazo approved these changes

2021-04-23 21:47 UTC, merged