WIP: Adds Paraview 5.9.1-RC1
LLNL/spack pull request #23226
Opened 2021-04-23 17:55 UTC by vicentebolea

2021-04-26 08:07 UTC, alalazo requested changes
I think there's a typo, other than that LGTM

2021-04-26 08:07 UTC, alalazo commented on var/spack/repos/builtin/packages/paraview/package.py
> +    version('5.9.0-RC1', sha256='bb3f12bd3d31bcb52455e1393e45f81a18754d3c3e8199d51532b0c067dc1595')
I think there's a typo:
```suggestion
    version('5.9.1-RC1', sha256='bb3f12bd3d31bcb52455e1393e45f81a18754d3c3e8199d51532b0c067dc1595')
```

2021-04-26 18:03 UTC, tldahlgren approved these changes
Confirmed sha256 for both versions.

2021-04-27 23:33 UTC, vicentebolea commented
@alalazo I think the PR got stuck somehow, I applied the requested changes but it is still waiting on that.

2021-04-28 11:38 UTC, alalazo approved these changes

2021-04-28 11:39 UTC, merged