root: Add variant for veccore option
LLNL/spack pull request #23237
Opened 2021-04-24 00:51 UTC by plexoos

Obviously, having this variant allows users to install ROOT with SIMD support
which is turned off by default

2021-04-25 09:48 UTC, vvolkl commented
This is missing a 

```
depends_on('veccore', when='+veccore')
```

otherwise, lgtm. Pinging fellow maintainers  @chissg @HadrienG2 @drbenmorgan

2021-04-25 09:58 UTC, HadrienG2 requested changes
Ok for me, with depencency change suggested by @vvolkl .

2021-04-26 17:19 UTC, plexoos commented
Dependency addressed. Please merge if looks good

2021-04-26 17:44 UTC, vvolkl approved these changes

2021-04-27 16:22 UTC, plexoos commented
ping @HadrienG2

2021-04-27 17:24 UTC, HadrienG2 approved these changes

2021-04-28 02:07 UTC, plexoos commented
@adamjstewart "All checks have passed" Can you please merge?

2021-04-28 02:09 UTC, adamjstewart approved these changes

2021-04-28 02:09 UTC, merged