kvtree 1.1.1: updated checksum
LLNL/spack pull request #23262
Opened 2021-04-26 18:40 UTC by eugeneswalker

The remote checksum for `kvtree@1.1.1` changed.

Kinda sketch that the checksum on a versioned release tarball would change -- Anyone know about this?

@CamStan @frankwillmore

2021-04-26 18:49 UTC, CamStan commented
@eugeneswalker, That was likely me. I believe this was caught and fixed when I updated the other ECP-VeloC packages I updated, but I missed this one.
My last PR (https://github.com/spack/spack/pull/22852) updated the url while adding new versions and I was unaware of the effects at the time.
I believe I ran the checksum on the old url. The checksums on the old versions are likely wrong as well.

2021-04-26 18:54 UTC, CamStan commented
Hmm, I might have missed `rankstr` as well https://github.com/spack/spack/pull/22763.
I'm running some tests today (which I should have done earlier) and can update it.

2021-04-26 19:47 UTC, tldahlgren requested changes
It looks like the checksums for the remaining versions are wrong too.

2021-04-26 19:50 UTC, tldahlgren commented
> It looks like the checksums for the remaining versions are wrong too.

I'm getting: 
- 1.1.0  3e6c003e7b8094d7c2d1529a973d68a68f953ffa63dcde5f4c7c7e81ddf06564
- 1.0.3  c742cdb1241ef4cb13767019204d5350a3c4383384bed9fb66680b93ff44b0d4
- 1.0.2  56fb5b747758c24a907a8380e8748d296900d94de9547bc15f6b427ac4ae2ec4

2021-04-26 19:51 UTC, tldahlgren commented
> I believe I ran the checksum on the old url.

I likely did the same thing.

2021-04-27 16:34 UTC, tldahlgren approved these changes

2021-04-27 16:34 UTC, merged