New package: blender
LLNL/spack pull request #23321
Opened 2021-04-28 15:05 UTC by qwertos

2021-04-28 18:33 UTC, tldahlgren requested changes

2021-04-28 18:33 UTC, tldahlgren commented on var/spack/repos/builtin/packages/blender/package.py
> +# Copyright 2013-2019 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
```

2021-04-28 18:33 UTC, tldahlgren commented on var/spack/repos/builtin/packages/blender/package.py
> +    # depends_on('openglu')
Is there a reason to retain commented-out dependencies here and below?

2021-04-28 18:34 UTC, tldahlgren commented
Oops.  Should've waited until after you removed "Draft".

2021-09-21 20:14 UTC, dylex commented
Thanks for putting this together -- it'd be great to see it get in.

I know you're still working on it, but in case it's helpful, this fails for me when using `intel-oneapi-tbb` (rather than `intel-tbb`) -- I think this might be a blender limitation that should just have a conflict or something.

It also fails with the (default) `~ffmpeg`, as it tries to build the ffmpeg plugin anyway.  I think it needs an explicit `WITH_CODEC_FFMPEG=OFF` for this.

Build 3 worked fine.

2022-05-05 13:35 UTC, alalazo commented
@qwertos Is this still a work in progress?

2022-05-05 13:46 UTC, qwertos commented
Not active. I'm gonna close and resubmit when I pick this up again.

2022-05-05 13:46 UTC, closed without merging