SLATE: Add e4s testsuite-inspired smoke test
LLNL/spack pull request #23376
Opened 2021-04-30 23:06 UTC by sshudler

This PR represents a preliminary smoke test for the `slate` package and is intended to serve the following purposes:

- leverage the current E4S test suite for the software; and
- demonstrate to package maintainers how to start a Spack smoke test.

2021-05-12 16:09 UTC, tldahlgren requested changes

2021-05-12 16:09 UTC, tldahlgren commented on var/spack/repos/builtin/packages/slate/package.py
> +        if '@master' in self.spec:
```suggestion
        if self.spec.satisfies('@master'):
```

2021-05-12 16:09 UTC, tldahlgren commented on var/spack/repos/builtin/packages/slate/package.py
> +        if '@master' in self.spec and '+mpi' in self.spec:
```suggestion
        if self.spec.satisfies('@master') and '+mpi' in self.spec:
```

2021-05-14 01:01 UTC, sshudler commented on var/spack/repos/builtin/packages/slate/package.py
> +        if '@master' in self.spec:
Thanks for pointing it out! I thought the same check as for variants will be enough, but your suggestion makes more sense

2021-05-21 17:26 UTC, tldahlgren commented on var/spack/repos/builtin/packages/slate/package.py
> +        if self.spec.satisfies('@master') and '+mpi' in self.spec:
Please output that the tests are being skipped if these criteria are *not* met to help with debugging.  

Perhaps print something like "Skipping: Stand-alone tests only run on master with +mpi" and return.  Then you can move the remaining lines in 4 spaces (so more readable and consistent with style preferences).

2021-05-21 17:27 UTC, tldahlgren requested changes

2021-05-21 17:27 UTC, tldahlgren commented on var/spack/repos/builtin/packages/slate/package.py
> +        if self.spec.satisfies('@master') and '+mpi' in self.spec:
Please output that the tests are being skipped if these criteria are *not* met to help with debugging.  

Perhaps print something like "Skipping: Stand-alone tests only run on master with +mpi" and return.  Then you can move the remaining lines in 4 spaces (so more readable and consistent with style preferences).

2021-06-18 17:49 UTC, tldahlgren approved these changes

2021-06-18 17:50 UTC, merged