Add `py-numpy` dependency where CoreNEURON is supported
LLNL/spack pull request #23375
Opened 2021-04-30 21:28 UTC by ikitayama

@pramodk

2021-04-30 21:34 UTC, pramodk requested changes

2021-04-30 21:34 UTC, pramodk commented on var/spack/repos/builtin/packages/neuron/package.py
> +    depends_on("py-numpy",    when="+coreneuron", type='run')
@ikitayama : numpy is needed for neuron and not anything specific for coreneuron. So I would drop when clause.

2021-04-30 21:48 UTC, pramodk approved these changes
LGTM

2021-05-03 13:17 UTC, alalazo approved these changes

2021-05-03 13:18 UTC, merged