Fixes to flex
LLNL/spack pull request #23408
Opened 2021-05-03 19:51 UTC by haampie

- Prefer the version that doesn't need all the patches and extra build
tools
- Make dependency on gettext optional under the nls variant (off by
default)
- Drop the dependency on help2man if we don't have to regenerate the man
pages (when no patches are necessary)

2021-05-03 20:55 UTC, michaelkuhn requested changes
If I try to build flex@2.6.4 with this applied, I get:
```
autoreconf: failed to run autopoint: No such file or directory
autoreconf: autopoint is needed because this package uses Gettext
```
If I enable +nls, it works again.

2021-05-03 20:58 UTC, michaelkuhn commented
One more thing: Will 2.6.3 build on systems where 2.6.4 (without patches) doesn't? If not, preferring 2.6.3 will break the out-of-the-box builds on those systems.

2021-05-03 22:49 UTC, haampie commented
Weird, i didnt have that on centos 7 and gcc 10

2021-05-04 21:12 UTC, haampie commented
@michaelkuhn in my previous reply I didn't realize you were testing the bit where you need to generate the configure script again; I could reproduce and added gettext back in that case.

2021-05-11 19:27 UTC, michaelkuhn approved these changes

2021-05-11 19:27 UTC, merged