Version Update to 2.12.0
LLNL/spack pull request #23430
Opened 2021-05-04 20:07 UTC by dorton21

2021-05-05 19:18 UTC, dorton21 commented
Depends on #23457

2021-05-10 21:43 UTC, dorton21 commented
Is this failing simply due to "Depends on #23457"?

2021-05-11 00:14 UTC, tldahlgren requested changes

2021-05-11 00:14 UTC, tldahlgren commented on var/spack/repos/builtin/packages/trinity/package.py
> +    depends_on("r-tximportdata", type="run")
Do these dependencies apply to `2.6.6`?  If not, then a `when` argument should be provided (e.g., `when='@2.12')`).

2021-05-11 00:14 UTC, tldahlgren commented on var/spack/repos/builtin/packages/trinity/package.py
> +    url      = "https://github.com/trinityrnaseq/trinityrnaseq/releases/download/v2.12.0/trinityrnaseq-v2.12.0.FULL.tar.gz"
This change breaks the `2.6.6` build.

2021-05-11 00:14 UTC, tldahlgren commented on var/spack/repos/builtin/packages/trinity/package.py
> +    url      = "https://github.com/trinityrnaseq/trinityrnaseq/releases/download/v2.12.0/trinityrnaseq-v2.12.0.FULL.tar.gz"
Given the differences in urls between versions, you may want to consider either the `url_for_version` method or adding the `url` argument to the `version` directive.

See the docs at https://spack.readthedocs.io/en/latest/packaging_guide.html?highlight=version%20url%3D#version-urls

2021-05-13 16:49 UTC, dorton21 commented
#23457 Has been merged

2021-05-18 17:48 UTC, dorton21 commented
Which requirement is not being met for auto-merge?

2021-05-18 18:12 UTC, tldahlgren approved these changes

2021-05-18 18:12 UTC, merged

2021-05-18 18:12 UTC, tldahlgren commented
> Which requirement is not being met for auto-merge?

An approval.