Update the CCE compiler module's CXX standard flags
LLNL/spack pull request #23444
Opened 2021-05-05 10:23 UTC by jjellio

This adds definitions for clang-based CCE up to what I know is officially supported.

The logic will throw for non-clang CCE, as I don't know what that supports (probably stopped at C++11)

Tested on Cray platform using CCE 12

Closes #23443

2021-05-07 22:02 UTC, lukebroskop requested changes
Just a minor change -- C++14 should be fully implemented @clang 3.4

2021-05-07 22:02 UTC, lukebroskop commented on lib/spack/spack/compilers/cce.py
> +            if self.real_version < ver('3.5'):
I know this is nit-picky, but I think you want to use "... < ver('3.4'):"
see [https://clang.llvm.org/cxx_status.html#cxx14](https://clang.llvm.org/cxx_status.html#cxx14)

2021-05-08 14:39 UTC, jjellio commented on lib/spack/spack/compilers/cce.py
> +            if self.real_version < ver('3.5'):
Thanks Luke, glad you reviewed.

I want to say I copied that from the spack clang thing - but I'll update it to 3.4

2021-05-08 21:47 UTC, jjellio commented on lib/spack/spack/compilers/cce.py
> +            if self.real_version < ver('3.5'):
I've fixed this

2021-05-08 21:59 UTC, lukebroskop approved these changes
Looks good to me

2021-05-09 17:31 UTC, jjellio commented
@lukebroskop I guess you need to 'review' again and approve. It seems to think the review is missing.

2021-05-10 15:42 UTC, lukebroskop commented
@jjellio Looks like the review needs to be done with someone with write access. I added @becker33, hopefully he has the time to push this through.

2021-05-17 09:24 UTC, haampie commented
> The Cray C++ compiler also contains support for the C++14 version of the C++ language as defined by the  ISO/IEC 14882:2014 standard. This support can be enabled with the –hstd=c++14 command-line flag.

Regarding cray classic, see https://pubs.cray.com/bundle/Cray_C_and_Cplusplus_Reference_Manual_S-2179-91_C_CPlusPlus_ditaval.xml/page/The_Cray_Compiling_Environment.html

2021-05-17 15:10 UTC, jjellio commented
I am pretty skeptical about full ISO C++ support from Cray classic - can you confirm it works? (Trilinos has a pretty long history of not working with Cray classic C++ due to standards issues).

I'd say demonstrate support or leave it be (noone has bumped into this except me, and I'm on cray clang)

2021-10-04 12:39 UTC, sethrj commented
@jjellio It looks like this was partially duplicated by #24127 . Can you rebase on develop to add the extra C++17 functionality and clang version detection that this PR provides? Thanks.

2022-01-26 13:08 UTC, sethrj commented
Closing from inactivity and assuming this got implemented by the other commit.

2022-01-26 13:08 UTC, closed without merging