Enable cmake option -optimal for rocsolver
LLNL/spack pull request #23448
Opened 2021-05-05 16:55 UTC by srekolam

this is added based on the inputs from the internal team. the code uses this flag .

2021-05-05 17:41 UTC, cgmb commented
`OPTIMAL=ON` improves performance at the cost of increased binary size and compile time by adding specialized kernels for small matrix sizes. The flag first appeared in rocm-3.7.0.

2021-05-05 18:02 UTC, haampie requested changes

2021-05-05 18:02 UTC, haampie commented on var/spack/repos/builtin/packages/rocsolver/package.py
> +            args.append('-DOPTIMAL={0}'.format('OFF'))
```suggestion
        if self.spec.satisfies('@3.7.0:'):
            args.append(self.define_from_variant('OPTIMAL', 'optimal'))
```

2021-05-05 22:10 UTC, haampie commented
Sorry, last request, can you put @cgmb 's comment as the description of the variant? That'll make it a bit more clear. Right now it looks like it is about cmake's build type

2021-05-06 06:42 UTC, haampie approved these changes

2021-05-06 06:42 UTC, merged