CrayPE fix for binutils
LLNL/spack pull request #23500
Opened 2021-05-07 18:55 UTC by lukebroskop

Allow for multiple definitions at link time (for CrayPE)

2021-05-10 18:44 UTC, tldahlgren commented on var/spack/repos/builtin/packages/binutils/package.py
> +    def setup_environment(self, spack_env, run_env):
Do you mean to use `setup_build_environment(self, env)` here?  The `setup_environment` method is a legacy function.

2021-05-10 18:44 UTC, tldahlgren commented on var/spack/repos/builtin/packages/binutils/package.py
> +    def setup_environment(self, spack_env, run_env):
Or `setup_run_environment(self, env)`?

2021-05-10 21:32 UTC, tldahlgren requested changes
Refer to previous questions/comments.

2021-05-10 22:12 UTC, lukebroskop commented on var/spack/repos/builtin/packages/binutils/package.py
> +    def setup_environment(self, spack_env, run_env):
Thanks @tldahlgren , I would be adding these flags during the build step. However I did not see a reference to setup_build_environment (or setup_run_environment) in [https://spack-tutorial.readthedocs.io/en/latest/search.html?q=setup_build_environment&check_keywords=yes&area=default#](https://spack-tutorial.readthedocs.io/en/latest/search.html?q=setup_build_environment&check_keywords=yes&area=default#)

The current spack documentation indicates that setup_environment should be used: [https://spack-tutorial.readthedocs.io/en/latest/search.html?q=setup_build_environment&check_keywords=yes&area=default#](https://spack-tutorial.readthedocs.io/en/latest/search.html?q=setup_build_environment&check_keywords=yes&area=default#).

Perhaps the updated features are not documented yet or I'm looking at the wrong documents page?

2021-05-11 00:46 UTC, tldahlgren commented on var/spack/repos/builtin/packages/binutils/package.py
> +    def setup_environment(self, spack_env, run_env):
> Thanks @tldahlgren , I would be adding these flags during the build step. However I did not see a reference to setup_build_environment (or setup_run_environment) in https://spack-tutorial.readthedocs.io/en/latest/search.html?q=setup_build_environment&check_keywords=yes&area=default#
> 
> The current spack documentation indicates that setup_environment should be used: https://spack-tutorial.readthedocs.io/en/latest/search.html?q=setup_build_environment&check_keywords=yes&area=default#.
> 
> Perhaps the updated features are not documented yet or I'm looking at the wrong documents page?

That's good to know, thanks!  There are *no* buillt-in packages using `setup_environment` anymore.  The tutorial is out-of-date and needs to be updated.

2021-05-11 00:53 UTC, tldahlgren commented
FWIW. I created an issue in the Spack tutorial (https://github.com/spack/spack-tutorial/issues/125) to address this problem.  Thanks for letting us know.

2021-05-11 04:18 UTC, lukebroskop commented on var/spack/repos/builtin/packages/binutils/package.py
> +    def setup_environment(self, spack_env, run_env):
@tldahlgren thanks for the review, I've made your suggested change.

2021-05-11 23:40 UTC, tldahlgren requested changes
Need to use the proper argument

2021-05-11 23:40 UTC, tldahlgren commented on var/spack/repos/builtin/packages/binutils/package.py
> +            setup_env.append_flags('LDFLAGS', '-Wl,-z,muldefs')
```suggestion
            env.append_flags('LDFLAGS', '-Wl,-z,muldefs')
```

2021-05-11 23:40 UTC, tldahlgren commented on var/spack/repos/builtin/packages/binutils/package.py
> +            setup_env.append_flags('LDFLAGS', '-lintl')
```suggestion
            env.append_flags('LDFLAGS', '-lintl')
```

2021-05-17 09:16 UTC, haampie commented on var/spack/repos/builtin/packages/binutils/package.py
> +
```suggestion
```

2021-05-17 16:25 UTC, tldahlgren approved these changes

2021-05-17 16:26 UTC, merged