craype fix for rempi
LLNL/spack pull request #23507
Opened 2021-05-07 19:36 UTC by lukebroskop

when comping with cce, use the mpi wrappers

2021-05-10 19:32 UTC, tldahlgren requested changes

2021-05-10 19:32 UTC, tldahlgren commented on var/spack/repos/builtin/packages/rempi/package.py
> +    def setup_environment(self, spack_env, run_env):
This method is legacy/deprecated.  Do you mean to use `setup_build_environment(self, env)` here?

2021-05-11 04:25 UTC, lukebroskop commented on var/spack/repos/builtin/packages/rempi/package.py
> +    def setup_environment(self, spack_env, run_env):
yep! thanks for the suggestion.

2021-05-11 23:07 UTC, tldahlgren approved these changes
LGTM.

2021-05-11 23:08 UTC, merged