CrayPE fixes for the slepc package
LLNL/spack pull request #23503
Opened 2021-05-07 19:22 UTC by lukebroskop

Use the gold linker for CCE (this may change later)

2021-05-10 19:35 UTC, tldahlgren requested changes

2021-05-10 19:35 UTC, tldahlgren commented on var/spack/repos/builtin/packages/slepc/package.py
> +        if '%cce' in self.spec:
```suggestion
        if self.spec.satisfies('%cce'):
```

2021-05-11 23:10 UTC, tldahlgren commented
LGTM.

@joseeroman @balay Did you want to comment on this PR?

2021-05-11 23:11 UTC, tldahlgren approved these changes

2021-05-11 23:12 UTC, tldahlgren commented
Approved but would like to wait for comment(s) from one or both maintainers before merging.

2021-05-12 09:11 UTC, joseeroman commented
Why is the gold linker necessary? Does the default linker fail? If this is the case, shouldn't it be fixed upstream in SLEPc?

2021-05-17 14:01 UTC, lukebroskop commented
> Why is the gold linker necessary? Does the default linker fail? If this is the case, shouldn't it be fixed upstream in SLEPc?

Yes, the default lld linker failed.

2021-05-17 16:18 UTC, tldahlgren commented
> > Why is the gold linker necessary? Does the default linker fail? If this is the case, shouldn't it be fixed upstream in SLEPc?
> 
> Yes, the default lld linker failed.

@joseeroman So are you okay with this PR being merged until SLEPc can resolve this issue (assuming someone reported it)?

2021-05-17 16:21 UTC, joseeroman commented
Ok, go ahead and merge it. I cannot fix this in SLEPc because I cannot reproduce the issue, don't have access to a Cray machine. On the other hand, I don't understand why this issue appears in SLEPc and not in PETSc, since in SLEPc we use the same linker as PETSc.

2021-05-17 16:30 UTC, merged