craype fixes for scr
LLNL/spack pull request #23510
Opened 2021-05-07 19:53 UTC by lukebroskop

turn off static linking, add -ldl flag

2021-05-08 00:01 UTC, eugeneswalker approved these changes, later dismissed

2021-05-10 19:28 UTC, tldahlgren requested changes

2021-05-10 19:28 UTC, tldahlgren commented on var/spack/repos/builtin/packages/scr/package.py
> +        if '%cce' in self.spec:
```suggestion
        if self.spec.satisfies('%cce'):
```

2021-05-11 23:05 UTC, tldahlgren commented
@gonsie @CamStan Did you want to comment on this PR?

2021-05-11 23:06 UTC, tldahlgren approved these changes
LGTM.

2021-05-11 23:07 UTC, tldahlgren commented
Would prefer to hold off on merging until Elsa and or Cameron weigh in on the changes.

2021-05-12 00:27 UTC, tldahlgren commented on var/spack/repos/builtin/packages/scr/package.py
> +            return (flags, None, None)
```suggestion
        return (flags, None, None)
```

2021-05-12 00:28 UTC, tldahlgren requested changes

2021-05-12 00:28 UTC, tldahlgren commented on var/spack/repos/builtin/packages/scr/package.py
> +            return (flags, None, None)
```suggestion
        return (flags, None, None)
```

2021-05-12 00:28 UTC, tldahlgren requested changes

2021-05-12 00:28 UTC, tldahlgren commented on var/spack/repos/builtin/packages/scr/package.py
> +            return (flags, None, None)
```suggestion
        return (flags, None, None)
```

2021-05-12 17:48 UTC, CamStan submitted a review, later dismissed
We're good with this once the suggested change is in.

2021-05-17 16:13 UTC, tldahlgren approved these changes

2021-05-17 16:14 UTC, merged