CrayPE patch for conduit
LLNL/spack pull request #23516
Opened 2021-05-07 20:55 UTC by lukebroskop

Pass -ef to the CCE Frotran compiler

2021-05-08 00:53 UTC, white238 commented
@cyrush

2021-05-08 00:55 UTC, white238 commented on var/spack/repos/builtin/packages/conduit/package.py
> +        if '%cce' in self.spec:
To follow this package's convention of handling compiler flags, you should do to this down around line 360 or so.

2021-05-08 02:57 UTC, lukebroskop commented on var/spack/repos/builtin/packages/conduit/package.py
> +        if '%cce' in self.spec:
thanks, I've gone ahead and made the necessary changes

2021-05-10 15:34 UTC, cyrush submitted a review, later dismissed
thanks for this change!

2021-05-10 18:40 UTC, white238 commented on var/spack/repos/builtin/packages/conduit/package.py
> +            fflags += "-ef"
This needs a space in the front.

2021-05-10 19:03 UTC, tldahlgren requested changes

2021-05-10 19:03 UTC, tldahlgren commented on var/spack/repos/builtin/packages/conduit/package.py
> +        if '%cce' in self.spec:
```suggestion
        if self.spec.satisfies('%cce'):
```

2021-05-11 15:56 UTC, white238 commented on var/spack/repos/builtin/packages/conduit/package.py
> +            fflags += "-ef"
This will start with `-some-flag -another-flag` from line 350 then end up with `-some-flag -another-flag-ef` (notice the lack of a space)

2021-05-11 16:16 UTC, lukebroskop commented on var/spack/repos/builtin/packages/conduit/package.py
> +            fflags += "-ef"
I misunderstood your previous request. Thanks for your patience @white238 .

2021-05-11 18:12 UTC, white238 approved these changes

2021-05-11 22:25 UTC, tldahlgren approved these changes

2021-05-11 22:25 UTC, merged