CrayPE fix for libcircle
LLNL/spack pull request #23526
Opened 2021-05-08 05:17 UTC by lukebroskop

disable mpi search when using cce (the CCE compiler wrappers do not behave like the conventional mpi compiler wrappers)

2021-05-10 17:46 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libcircle/package.py
> +    def autoreconf(self, spec, prefix):
Have you considered using `force_autoreconf` as described with the second example at https://spack.readthedocs.io/en/latest/build_systems/autotoolspackage.html?highlight=force_autoreconf#force-autoreconf?

2021-05-10 17:46 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libcircle/package.py
> +    def autoreconf(self, spec, prefix):
In other words, something along the lines:

```
    @property
    def force_autoreconf(self):
        return self.spec.satisfies('%cce')
```

2021-05-10 19:01 UTC, tldahlgren requested changes
See suggestion

2021-05-11 03:54 UTC, lukebroskop commented on var/spack/repos/builtin/packages/libcircle/package.py
> +    def autoreconf(self, spec, prefix):
I like this approach better, thanks! I did have to add a couple additional dependencies (e.g. autoconf and automake).

2021-05-11 16:33 UTC, tldahlgren approved these changes

2021-05-11 16:33 UTC, merged