Enhancing package gmsh with more options, new version
LLNL/spack pull request #23544
Opened 2021-05-10 16:27 UTC by cessenat

CGNS dependency was forgotten, defaults were very far from those of the pre-compiled packages for Linux distros such as Ubuntu, more options from the gmsh web page https://gmsh.info/doc/texinfo/gmsh.html#Compiling-the-source-code are added, new version 4.8.4 as well.

2021-05-10 20:56 UTC, tldahlgren commented on var/spack/repos/builtin/packages/gmsh/package.py
> +    version('4.8.4', sha256='760dbdc072eaa3c82d066c5ba3b06eacdd3304eb2a97373fe4ada9509f0b6ace')
Confirmed the sha256 for this version.

2021-05-10 20:56 UTC, tldahlgren commented on var/spack/repos/builtin/packages/gmsh/package.py
> +    version('develop', branch='master')
FYI. We generally discourage naming a version `develop` when it's tied to the `master` branch.  Why not call this version `master`?

2021-05-10 20:56 UTC, tldahlgren commented on var/spack/repos/builtin/packages/gmsh/package.py
> +        options.append('-DCMAKE_INSTALL_NAME_DIR:PATH=%s/lib' % self.prefix)
Great catch!

2021-05-11 06:02 UTC, cessenat commented on var/spack/repos/builtin/packages/gmsh/package.py
> +    version('develop', branch='master')
Right.

2021-05-11 06:03 UTC, cessenat commented on var/spack/repos/builtin/packages/gmsh/package.py
> +        options.append('-DCMAKE_INSTALL_NAME_DIR:PATH=%s/lib' % self.prefix)
Indeed I should write :
options.append('-DCMAKE_INSTALL_NAME_DIR:PATH=%s' % self.prefix.lib)

2021-05-11 11:15 UTC, sethrj requested changes

2021-05-11 11:15 UTC, sethrj commented on var/spack/repos/builtin/packages/gmsh/package.py
> +                   for var, opt in var_opt_list]
`self.define_from_variant` helps here and protects against both typos and nonexistent variants:
```suggestion
        options = [
            self.define_from_variant('CAIRO'),
            self.define_from_variant('CGNS'),
            self.define_from_variant('FLTK'),
            self.define_from_variant('GMP') ,
            self.define_from_variant('METIS'),
            self.define_from_variant('MPI'),
            self.define_from_variant('OPENMP'),
            self.define_from_variant('PRIVATE_API', 'privateapi'),
        ]
```

2021-05-11 11:15 UTC, sethrj commented on var/spack/repos/builtin/packages/gmsh/package.py
> +            options.append('-DENABLE_EIGEN=ON')
Recommend `define_from_variant` or `define` here too

2021-05-11 13:07 UTC, cessenat commented
Hello @davydden, do you agree that gmsh brings its own netgen (and before or equal 3.0.6 tetgen) so that it does not depend on these packages ? I do not see trace of NETGEN_DIR (neither TETGEN_DIR) is CMakeLists.txt. Thanks for advising me.
All reviewers : I found that 2.12.0 checksum is wrong. Is it only me ? Shall we deprecate it, change the checksum, remove it, do nothing ?

2021-05-11 13:34 UTC, sethrj commented on var/spack/repos/builtin/packages/gmsh/package.py
> +            env['CASROOT'] = spec['opencascade'].prefix
Changes to environment variables should generally be done as part of `setup_build_environment`, not modified at a system level.

2021-05-11 13:34 UTC, sethrj commented on var/spack/repos/builtin/packages/gmsh/package.py
> +                options.append('-DENABLE_MMG3D=OFF')
```suggestion
            options.append(self.define_from_variant('ENABLE_MMG3D', 'mmg'))
```

2021-05-11 14:35 UTC, cessenat commented on var/spack/repos/builtin/packages/gmsh/package.py
> +            env['CASROOT'] = spec['opencascade'].prefix
I removed all env var settings since they in fact were not needed.
Added "med" dependecy since med hdf5 dep is no longer too tight.
Added "freetype" when OpenCascade (through oce or opencascade) since searched by gmsh CMake.
I also removed the netgen and tetgen dependency since compilation with or without them produced exactly the same output : GMSH brings these as submodules, so it is sure of the compatibility of the API.

2021-05-11 15:11 UTC, sethrj approved these changes

2021-05-11 15:12 UTC, merged