new package for openvdb
LLNL/spack pull request #23581
Opened 2021-05-12 05:36 UTC by eloop

A package the OpenVDB sparse volume data format library.

2021-05-17 09:10 UTC, haampie commented on var/spack/repos/builtin/packages/openvdb/package.py
> +            ])
```suggestion
        ...
        self.define_from_variant('BUILD_SHARED_LIBS', 'shared'),
        ...
```
Can you simplify this a bit?

2021-05-17 09:11 UTC, haampie requested changes
Would be better to simplify the cmake args

2021-05-18 01:17 UTC, eloop commented
Thanks for the heads up on that method Harmen, I hadn't seen it before. Much nicer!

2021-05-22 21:05 UTC, haampie approved these changes

2021-05-22 21:05 UTC, merged