AMD ROCm release 4.3: core components part-1
LLNL/spack pull request #23613
Opened 2021-05-13 05:03 UTC by arjun-raj-kuppala

2021-05-13 08:14 UTC, alalazo requested changes
Minor requests, otherwise LGTM

2021-05-13 08:14 UTC, alalazo commented on var/spack/repos/builtin/packages/hsakmt-roct/package.py
> +            return ['-DDBUILD_SHARED_LIBS=OFF']
```suggestion
        return [
            self.define_from_variant('BUILD_SHARED_LIBS', 'shared')
        ]
```

2021-05-13 08:14 UTC, alalazo commented on var/spack/repos/builtin/packages/rocm-cmake/package.py
> +            return ['-DROCM_DISABLE_LDCONFIG=OFF']
Same as comment above

2021-05-13 08:14 UTC, alalazo commented on var/spack/repos/builtin/packages/rocm-smi-lib/package.py
> +            return ['-DDBUILD_SHARED_LIBS=OFF']
Same as comment above

2021-05-14 10:46 UTC, haampie approved these changes

2021-05-14 21:55 UTC, arjun-raj-kuppala commented
@alalazo 
Can you help review and merge this change

2021-05-17 21:42 UTC, arjun-raj-kuppala commented
@alalazo can you help merge this?

2021-05-18 13:53 UTC, alalazo approved these changes

2021-05-18 13:53 UTC, merged