charmpp: avoid setting MPICC for mpi backend
LLNL/spack pull request #23645
Opened 2021-05-14 21:44 UTC by matthiasdiener

Fixes #18535

2021-11-02 08:33 UTC, hpcnpatel commented
any update on this fix to be merged? We have been facing the same issue and would be interested to know if any progress can be made. Of course, we can implement the fix locally but it's nice to have it in Spack upstream.

2021-11-02 18:06 UTC, matthiasdiener commented
> any update on this fix to be merged? We have been facing the same issue and would be interested to know if any progress can be made. Of course, we can implement the fix locally but it's nice to have it in Spack upstream.

Does the fix proposed in this PR fix this issue for you?

2021-11-02 20:19 UTC, hpcnpatel commented
> > any update on this fix to be merged? We have been facing the same issue and would be interested to know if any progress can be made. Of course, we can implement the fix locally but it's nice to have it in Spack upstream.
> 
> Does the fix proposed in this PR fix this issue for you?

yes

2021-11-15 12:56 UTC, alalazo requested changes
Can you please rebase and ping me back?

2021-11-16 04:34 UTC, matthiasdiener commented
> Can you please rebase and ping me back?

I rebased the PR.

2021-11-16 06:59 UTC, alalazo requested changes
This is just for my knowledge, but why do we need to set `MPICC` etc. if we __do not__ have `mpi` as a backend?

2021-11-16 06:59 UTC, alalazo commented on var/spack/repos/builtin/packages/charmpp/package.py
> +        if not("backend=mpi" in self.spec):
Can you try:
```suggestion
        if not self.spec.satisfies("backend=mpi"):
```
?

2021-11-17 16:53 UTC, matthiasdiener commented
> This is just for my knowledge, but why do we need to set `MPICC` etc. if we **do not** have `mpi` as a backend?

Charm++ contains its own MPI implementation, AMPI, which provides a set of shell scripts for MPICC etc., like a normal MPI implementation. Although Charm++ can be built using MPI as the network layer, you can not build Charm++ using AMPI (the Charm++ build scripts check for that). When building packages that depend on Charm++ (with the option to use the MPI network layer), MPICC etc. get set to use AMPI, thus failing the build.

2022-03-31 20:26 UTC, jcphill commented
@alalazo Can we please get this merged?

2022-04-04 08:51 UTC, alalazo approved these changes

2022-04-04 08:52 UTC, alalazo approved these changes

2022-04-04 09:49 UTC, merged