Adding support to tag a build
LLNL/spack pull request #23712
Opened 2021-05-17 23:34 UTC by vsoch

This will be useful to run multiple build experiments and organize by name. cc @trws - I'll let you know when the monitor server is updated to support testing this.

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

2021-05-18 00:03 UTC, tgamblin requested changes
Can tags be a list of strings instead of a single string?

2021-05-18 00:11 UTC, vsoch commented
@tgamblin so you mean like:

```bash
spack install --monitor --monitor-tag <tag1> --monitor-tag <tag2> wget

# or shorthand

spack install --monitor --mt <tag1> --mt <tag2> wget
```

2021-05-18 00:12 UTC, tgamblin commented
yep that would work -- or comma-separated, e.g.:

```
spack install --monitor --monitor-tags foo,bar,baz
```

2021-05-18 00:12 UTC, tgamblin commented
Let's keep it `--monitor-tag`, as I think we might allow people to install packages by package tags eventually.

2021-05-18 01:42 UTC, vsoch commented
Okay, updated here to support tags! Changes to the server (after discussion here is done) are at https://github.com/spack/spack-monitor/pull/24.

I made one additional change in this PR - the token generated after the 401 request to ask for is not kept for the next request, so there are many more server <-> client interactions than there need to be, because one token should last a good 100 minutes.

2021-05-18 01:45 UTC, vsoch commented
Here is how that looks - note that some builds have multiple tags:

![image](https://user-images.githubusercontent.com/814322/118577771-3f274a80-b748-11eb-8117-2f3e7c52a500.png)

I think we soon need to refactor the front / dashboard page, either to use pagination from the server (instead of browser which is getting slow since there are many records) or a different kind of view that shows a subset / asks for tag first (or something like that). If this is a database with hundreds of thousands of builds we will need to do better than a single paginated table :)

2021-05-19 14:00 UTC, tgamblin approved these changes

2021-05-19 14:01 UTC, merged

2021-05-19 20:41 UTC, trws commented
Looks awesome, I'll definitely use this!

2021-05-19 21:36 UTC, vsoch commented
@trws @tgamblin the core functionality that @alecbcs needs to start his work is to have containerize work with spack monitor, which is added in this PR. https://github.com/spack/spack/pull/23777 There is some weird error on the RHEL build (should I re-run it?) but otherwise I think this is good for a first test. We can't do a full test until a spack container base is deployed, so we'd need to merge, do that, and then (possibly if there are any issues) do a quick second PR. Let me know what you'd like to do!