Fix cross references in inteloneapipackage doc
LLNL/spack pull request #23744
Opened 2021-05-18 14:19 UTC by rscohn2

2021-05-18 23:00 UTC, tldahlgren requested changes

2021-05-18 23:00 UTC, tldahlgren commented on lib/spack/docs/build_systems/inteloneapipackage.rst
> +:ref:`intel-unrelated-packages>`,
```suggestion
:ref:`intel-unrelated-packages`,
```

2021-05-25 11:22 UTC, rscohn2 commented
@tldahlgren: I made the requested change. Does it need anything else before merge?

2021-05-25 16:57 UTC, tldahlgren approved these changes

2021-05-25 16:57 UTC, merged

2021-05-25 16:58 UTC, tldahlgren commented
Thank you for your contribution!