New Package:py-sierrapy@0.3.0
LLNL/spack pull request #23768
Opened 2021-05-18 22:16 UTC by dorton21

2021-05-19 19:29 UTC, adamjstewart requested changes

2021-05-19 19:29 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-sierrapy/package.py
> +
Missing build dep on setuptools, missing a few other dependencies (note that these all need to be exact versions, not version ranges):
```python
certifi==2020.4.5.1
chardet==3.0.4
click==7.1.2
gql==0.4.0
graphql-core==2.3.1
idna==2.9
promise==2.3
requests==2.23.0
rx==1.6.1
six==1.14.0
tqdm==4.46.0
urllib3==1.25.9
voluptuous==0.11.7
```

2021-05-26 17:26 UTC, adamjstewart requested changes

2021-05-26 17:26 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-sierrapy/package.py
> +    depends_on('py-tqdm@4.51.0', type=('build', 'run'))
```suggestion
    depends_on('py-tqdm@4.46.0', type=('build', 'run'))
```

2021-05-26 17:26 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-sierrapy/package.py
> +    depends_on('py-urllib3@1.25.10', type=('build', 'run'))
```suggestion
    depends_on('py-urllib3@1.25.9', type=('build', 'run'))
```

2021-05-26 17:34 UTC, dorton21 commented
Depends on updates to: #23927, #23928
Depends on new package: #23929

2021-05-26 18:57 UTC, adamjstewart approved these changes

2021-06-02 01:47 UTC, adamjstewart approved these changes

2021-06-02 02:13 UTC, merged

2021-10-08 16:43 UTC, bernhardkaindl commented on var/spack/repos/builtin/packages/py-sierrapy/package.py
> +
@adamjstewart We don't have these versions in spack, @dorton21 just took your remands to get it merged.

(@tldahlgren JFYI ) Neither you, nor @dorton21 could have ever built the package with these versions, or the versions would have had to be submitted as well. Pinning this large number of versions must have been clear to be not satisfiable just by pure luck.

2021-10-08 16:48 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-sierrapy/package.py
> +
Yes, we really need better build tests through GitLab CI in the future. We get far too many PRs for me to manually build all of them, so it's not really possible to catch these kinds of mistakes at review time.