New Package:gsutil-feedstock@4.59
LLNL/spack pull request #23766
Opened 2021-05-18 22:11 UTC by dorton21

2021-05-19 19:22 UTC, adamjstewart requested changes

2021-05-19 19:22 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-gsutil-feedstock/package.py
> +    homepage = "https://github.com/conda-forge/gsutil-feedstock"
```suggestion
    homepage = "https://cloud.google.com/storage/docs/gsutil"
```

2021-05-19 19:22 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-gsutil-feedstock/package.py
> +class PyGsutilFeedstock(PythonPackage):
```suggestion
class PyGsutil(PythonPackage):
```
Will need to update file name too.

2021-05-19 19:22 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-gsutil-feedstock/package.py
> +    depends_on('py-setuptools', type=('build', 'run'))
Many dependencies missing:
```python
requires = [                                                                             
    'argcomplete>=1.9.4',                                                                
    'crcmod>=1.7',                                                                       
    'fasteners>=0.14.1',                                                                 
    'gcs-oauth2-boto-plugin>=2.7',                                                       
    'google-apitools>=0.5.30',                                                           
    'httplib2>=0.18',                                                                    
    'google-reauth>=0.1.0',                                                              
    # TODO: Sync submodule with tag referenced here once #339 is fixed in mock.          
    'mock==2.0.0',                                                                       
    'monotonic>=1.4',                                                                    
    'pyOpenSSL>=0.13',                                                                   
    'retry_decorator>=1.0.0',                                                            
    'six>=1.12.0',                                                                       
]    
...
    python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <4',                 
```

2021-05-26 19:00 UTC, closed without merging

2021-05-26 19:01 UTC, dorton21 commented
Package is no longer needed