New Package: modeltest-ng@0.1.7
LLNL/spack pull request #23765
Opened 2021-05-18 22:08 UTC by dorton21

2021-05-19 05:47 UTC, alalazo requested changes
Left a f few comments, let me know if anything needs clarification.

2021-05-19 05:47 UTC, alalazo commented on var/spack/repos/builtin/packages/modeltest-ng/package.py
> +    depends_on('openmpi', type=('build', 'run'))
The dependency types seem odd here. Simplifying a bit:
- `build` is for build tools e.g. system calls to executable needed during the build
- `link` is for libraries that are linked by this package
-  `run` is for run time only dependencies e.g. system calls to executable needed at runtime

Can you double check dependencies?

2021-05-19 05:47 UTC, alalazo commented on var/spack/repos/builtin/packages/modeltest-ng/package.py
> +        return args
```suggestion
        return = [
            self.define_from_variant('ENABLE_MPI', 'mpi')
        ]
```

2021-05-19 19:27 UTC, adamjstewart commented on var/spack/repos/builtin/packages/modeltest-ng/package.py
> +    depends_on('cmake', type='build')
This line can be removed, it's already added by the base class

2021-05-19 19:27 UTC, adamjstewart commented on var/spack/repos/builtin/packages/modeltest-ng/package.py
> +    version('0.1.7', commit="cc028888f1d4222aaa53b99c6b02cd934a279001", submodules=True)
Could we download from the URL instead of from git? This would allow us to checksum the tarball.

2021-05-26 17:52 UTC, dorton21 commented on var/spack/repos/builtin/packages/modeltest-ng/package.py
> +    version('0.1.7', commit="cc028888f1d4222aaa53b99c6b02cd934a279001", submodules=True)
@adamjstewart without specifying submodules=True, installation fails. I don't believe using the URL allows submodules to be specified. Unless there's some Spack functionality I'm not aware of.

2021-05-26 18:55 UTC, adamjstewart commented on var/spack/repos/builtin/packages/modeltest-ng/package.py
> +    version('0.1.7', commit="cc028888f1d4222aaa53b99c6b02cd934a279001", submodules=True)
Nah, I was hoping the submodules would be included in the tarball but if not this is fine.

2021-05-26 18:56 UTC, adamjstewart commented on var/spack/repos/builtin/packages/modeltest-ng/package.py
> +    depends_on('flex')
These are usually just build deps, does the package link to them too?

2021-05-27 17:43 UTC, adamjstewart approved these changes

2021-05-28 14:34 UTC, alalazo approved these changes

2021-05-28 14:35 UTC, merged