Package update to version 1.0.2
LLNL/spack pull request #23764
Opened 2021-05-18 21:59 UTC by dorton21

2021-05-19 06:07 UTC, alalazo commented on var/spack/repos/builtin/packages/raxml-ng/package.py
> +    version('1.0.2', submodules=True)
Small OCD, but for v1.0.1 we have a string instead of a Boolean. Can you fix that too?

2021-05-19 19:25 UTC, adamjstewart requested changes

2021-05-19 19:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/raxml-ng/package.py
>      version('1.0.1', submodules='True')
```suggestion
    version('1.0.2', submodules=True)
    version('1.0.1', submodules=True)
```

2021-05-20 16:31 UTC, alalazo commented on var/spack/repos/builtin/packages/raxml-ng/package.py
> +    version('1.0.2', submodules=True)
See @adamjstewart comment below, they should both be Boolean

2021-05-24 18:54 UTC, adamjstewart approved these changes

2021-05-24 18:54 UTC, merged