AMD ROCm 4.2.0: Bump up rocm recipes part 2
LLNL/spack pull request #23779
Opened 2021-05-19 03:56 UTC by arjun-raj-kuppala

AMD ROCm 4.2.0: Bump up rocm-cmake hsakmt-roct rocm-smi-lib hsa-rocr-dev llvm-amdgpu rocm-debug-agent rocm-gdb rocalution rocm-validation-suite

2021-05-19 11:24 UTC, haampie requested changes
1. Can you remove all occurrences of if's in for loops and just turn them into two for loops? It is better to make package.py's declarative and reduce control flow to a minimum.

2. I'm rather confused by the fact that clang is now aware of spack and how that went through reviews in llvm; skimming through the code it seems it makes multiple incorrect assumptions about the folder structure. I don't think it's a good idea at all for clang to be aware of spack, but well... it's done released already.

2021-05-19 14:30 UTC, haampie requested changes

2021-05-19 14:30 UTC, haampie commented on var/spack/repos/builtin/packages/hsa-rocr-dev/package.py
> +            args.append('-DBUILD_SHARED_LIBS=OFF')
Can you use `self.define_from_variant(.., ..)` where applicable to reduce code bloat?

2021-05-19 16:44 UTC, arjun-raj-kuppala commented
> 1. Can you remove all occurrences of if's in for loops and just turn them into two for loops? It is better to make package.py's declarative and reduce control flow to a minimum.**(I have addressed this with new patch)**
> 2. I'm rather confused by the fact that clang is now aware of spack and how that went through reviews in llvm; skimming through the code it seems it makes multiple incorrect assumptions about the folder structure. I don't think it's a good idea at all for clang to be aware of spack, but well... it's released already.**(I will pass this suggestion to the concerned team.)**

2021-05-20 10:45 UTC, haampie submitted a review, later dismissed

2021-05-20 10:46 UTC, haampie commented on var/spack/repos/builtin/packages/hsa-rocr-dev/package.py
> +            args.append('-DBITCODE_DIR={}'.format(bitcode_dir))
```suggestion
            args.append('-DBITCODE_DIR={0}'.format(bitcode_dir))
```

2021-05-20 10:48 UTC, haampie approved these changes

2021-05-20 10:58 UTC, merged