Freebayes version update 1.3.5
LLNL/spack pull request #23772
Opened 2021-05-18 23:20 UTC by dorton21

The freebayes devs switched build packages from Makefile to Meson.

2021-05-19 05:38 UTC, alalazo requested changes

2021-05-19 05:38 UTC, alalazo commented on var/spack/repos/builtin/packages/freebayes/package.py
> +    depends_on('samtools', type=('build', 'run'), when='@1.3.5')
Can we use an open range in the conditions:
```suggestion
    # Deps for @1.3.5
    depends_on('htslib', when='@1.3.5:')
    depends_on('zlib', type=('build', 'run'), when='@1.3.5:')
    depends_on('xz', type=('build', 'run'), when='@1.3.5:')
    depends_on('parallel', type=('build', 'run'), when='@1.3.5:')
    depends_on('ninja', type=('build', 'run'), when='@1.3.5:')
    depends_on('vcftools', type=('build', 'run'), when='@1.3.5:')
    depends_on('bc', type=('build', 'run'), when='@1.3.5:')
    depends_on('samtools', type=('build', 'run'), when='@1.3.5:')
```
?

2021-05-19 05:38 UTC, alalazo commented on var/spack/repos/builtin/packages/freebayes/package.py
> +    version('1.3.5', sha256='7e2635690e916ed85cec36b3263e6e5357413a4f2bf3035362d9749335e8a696')
If it makes sense you can also add `deprecated=True` to v1.1.0

2021-05-19 19:33 UTC, adamjstewart requested changes

2021-05-19 19:33 UTC, adamjstewart commented on var/spack/repos/builtin/packages/freebayes/package.py
> +    depends_on('samtools', type=('build', 'run'), when='@1.3.5:')
Many of these have no `prefix.bin` directory, so `type=('build', 'run')` won't do anything. I think you want to leave it as the default deptype. `ninja` might be `type='build'`. You'll have to see how the build system actually uses these tools (whether or not it links to them).

2021-05-24 18:55 UTC, adamjstewart commented on var/spack/repos/builtin/packages/freebayes/package.py
> +    @when('@1.1.0:')
Should this be `@:1.1.0`? We're now using Meson to generate the Makefile, right?

2021-05-26 18:56 UTC, adamjstewart approved these changes

2021-05-28 15:07 UTC, alalazo approved these changes

2021-05-28 15:07 UTC, merged