Allow for saving local results with spack monitor
LLNL/spack pull request #23804
Opened 2021-05-20 00:57 UTC by vsoch

We would want to be able to run monitoring, and generate all metadata that can be updated to a monitor server later. This is the goal of this PR, and the work will come in two phases. The first here is to allow saving of a local result with spack monitor, and the second will add a spack monitor command so the user can do spack monitor upload. You would run like:

```bash
$ spack install --monitor --monitor-save-local zlib
```
And then upload later (probably with a little more granularity but the gist is:

```bash
$ spack monitor upload <some identifier>
```
I'm wondering what the best way is to organize these builds in .spack/reports/monitor. Right now I have based on timestamp, and we will only be able to tell if a result has already been uploaded by providing the server with the same information we use to generate a build id (e.g., look up a build) so arguably the user could just provide some match string of dates to upload, and we would check them all. E.g.,

```bash
$ spack monitor upload 2021-05-19
```
To upload all results from today. Here is an example save:

```
 tree /home/vanessa/.spack/reports/monitor/2021-05-19-18-40-58-1621471258/
/home/vanessa/.spack/reports/monitor/2021-05-19-18-40-58-1621471258/
├── build-a2f7cad8ba1c7c7242b8eca4700b62b8-phase-autoreconf.json
├── build-a2f7cad8ba1c7c7242b8eca4700b62b8-phase-build.json
├── build-a2f7cad8ba1c7c7242b8eca4700b62b8-phase-configure.json
├── build-a2f7cad8ba1c7c7242b8eca4700b62b8-phase-install.json
├── build-a2f7cad8ba1c7c7242b8eca4700b62b8-status.json
├── build-c400d10c94e88f8fbd92d0c858d1e0dd-phase-autoreconf.json
├── build-c400d10c94e88f8fbd92d0c858d1e0dd-phase-build.json
├── build-c400d10c94e88f8fbd92d0c858d1e0dd-phase-configure.json
├── build-c400d10c94e88f8fbd92d0c858d1e0dd-phase-install.json
├── build-c400d10c94e88f8fbd92d0c858d1e0dd-status.json
├── build-metadata-6p56pf7j6bgi36akjsiur53ynst3idun.json
├── build-metadata-mgdfbpj36meas7alzf7sgbsuntpid2ob.json
└── spec-rpm-4.16.1.2-config.json
```
The PR also adds a new flag to clean up reports as requested by @tgamblin.

```bash
$ spack clean --reports
```
cc @alecbcs

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

2021-05-24 19:02 UTC, vsoch commented
The failing tests works locally for me - there must be some issue with a mirror, especially because we don't touch that part of the code and the tests were previously passing. I'll just keep trying to rerun!

2021-05-24 19:32 UTC, vsoch commented
No idea why everything is failing, everything was passing before https://github.com/spack/spack/actions/runs/872182250

2021-05-25 02:11 UTC, vsoch commented
Confirmed that removing monitor.py entirely under tests... tests pass. Oy vey! There is something about the test / running it that messes other tests up, it seems.

2021-05-25 07:03 UTC, tgamblin requested changes
Ok one change request, and then a question.

Doesn't saving locally let you test the monitor command better?  i.e., can't you test the code in `monitor.py` effectively now that it spits out files?  Seems like you could create dummy installs with mock packages, run the analysis phases, save a monitor result, and parse it in a test.  You would not need to mock it -- just monkeypatch the save location to something that is not `~/.spack` and read from there.

Would that work?

2021-05-25 07:03 UTC, tgamblin commented on lib/spack/spack/monitor.py
> +        default=False, help="save monitor results to .spack instead of server.")
Instead of adding an option to save locally, wouldn't it make more sense to:

1. Save locally by default.
2. Don't have a default `127.0.0.1` monitor host (just make it `None`)
3. Only upload if `--monitor-host` is provided


You could also fall back to saving locally if upload fails.

I think this would simplify the options.

2021-05-25 15:10 UTC, vsoch commented on lib/spack/spack/monitor.py
> +        default=False, help="save monitor results to .spack instead of server.")
I think the default should be the server - the local save is really just to save files when you want to upload to a server later. I've only run into this use case for @alecbcs to run during a PR and then upload artifacts to find later and upload to a server.  Spack Monitor is a server, not a folder on the filesystem.

2021-05-25 15:19 UTC, vsoch commented on lib/spack/spack/monitor.py
> +        default=False, help="save monitor results to .spack instead of server.")
And I do want to try testing the monitor API by mocking it, but I'll add those tests to https://github.com/spack/spack/pull/23777.

2021-05-25 18:29 UTC, tgamblin approved these changes

2021-05-25 18:29 UTC, merged