[openfst] Added variant for python extension. Added new version.
LLNL/spack pull request #23850
Opened 2021-05-21 19:53 UTC by archxlith

2021-05-24 07:26 UTC, alalazo requested changes
Just a minor comment, otherwise LGTM.

2021-05-24 07:26 UTC, alalazo commented on var/spack/repos/builtin/packages/openfst/package.py
> +        if '+python' in spec:
I think this would work too:
```python
def configure_args(self):
    return self.enable_or_disable('far') + self.enable_or_disable('python)
```

2021-05-24 14:07 UTC, alalazo commented on var/spack/repos/builtin/packages/openfst/package.py
> +         return self.enable_or_disable('far') + self.enable_or_disable('python')
I think there's a space too much:
```suggestion
        return self.enable_or_disable('far') + self.enable_or_disable('python')
```

2021-05-27 13:39 UTC, archxlith commented on var/spack/repos/builtin/packages/openfst/package.py
> +         return self.enable_or_disable('far') + self.enable_or_disable('python')
Addition space removed.

2021-05-28 14:45 UTC, alalazo approved these changes

2021-05-28 14:46 UTC, merged