New packages to be added
LLNL/spack pull request #23868
Opened 2021-05-24 11:47 UTC by samcom12

2021-05-24 12:02 UTC, samcom12 commented
@alalazo Kindly review

2021-05-25 00:23 UTC, tldahlgren requested changes
I am just providing some basic comments but will defer to the overarching Python package owner (@adamjstewart) and or @alalazo for more detailed feedback.

2021-05-25 00:23 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-pymetis/package.py
> +# Copyright 2013-2020 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
```

2021-05-25 00:23 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-meshpy/package.py
> +
Please add the standard package copyright page.

2021-05-25 00:23 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-pysph/package.py
> +from spack import *
Please add the standard package copyright page.

2021-05-25 00:23 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-pysph/package.py
> +    """FIXME: Put a proper description of your package here."""
Description is needed here.

2021-05-25 00:23 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-pysph/package.py
> +class PyPysph(Package):
Why is this package not inheriting from `PythonPackage`?

2021-05-25 00:23 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-triangle/package.py
> +class PyTriangle(PythonPackage):
Please add the standard package copyright here.

2021-05-25 00:23 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-anuga/package.py
> -# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
Why was the standard package copyright removed?

2021-05-25 00:35 UTC, adamjstewart commented
This would be much easier for me to review if you could split each package into a separate PR.

2021-05-25 00:37 UTC, tldahlgren commented on var/spack/repos/builtin/packages/abinit/package.py
> +    version('9.4.1', sha256='ec74133ef9d247cb6ad44c205675694919cf36d7f1682a9b85cae8bdecdc22a8')
Confirmed the sha258.

2021-05-25 02:37 UTC, sethrj commented
There are a handful of new packages, new versions to existing packages, and changes to existing packages all in this one MR, with no comments about how they're related. To echo @adamjstewart , please separate these out to make them easier to review.

2021-05-27 09:51 UTC, samcom12 commented
It might be difficult for a reviewer to review it. 
Will reopen new PR for each new package with proper description.

2021-06-11 19:28 UTC, closed without merging