Simplified the spack.util.gpg implementation
LLNL/spack pull request #23889
Opened 2021-05-25 15:56 UTC by alalazo

Modifications:
- [x] Removed a lot of complexity from classes + singleton + convenience functions
- [x] State is now recorded in 4 global variables that are not hidden in classes, API is unchanged
- [x] Fixed calls in a few tests accordingly

2021-05-25 16:02 UTC, alalazo commented on lib/spack/spack/util/gpg.py
> +    GPG, GPGCONF = _gpg(), _gpgconf()
For reviewers. I started this refactoring to have a single place to modify (the line above) when adding bootstrapping for GnuPG. While I was at it I figured out I could simplify the implementation in this module without changing the API exposed to clients, so I took a stab at it.

2021-05-31 20:48 UTC, alalazo commented
@opadron @scottwittenburg Do you have time to review this PR and tell me what you think? I ended up working on `spack.util.gpg` as part of a broader modification to enable `GnuPG` bootstrapping. Reading this module I figured out I could simplify a bit the implementation without modifying too much the external API, and so I took a stab at it and added docstrings.

2021-06-01 01:58 UTC, opadron approved these changes, later dismissed
LGTM.  Thanks for the cleanup pass! :+1:

2021-06-01 01:58 UTC, opadron commented on lib/spack/spack/util/gpg.py
> +        # Set the socket dir is not using GnuPG defaults
`s/is/if/`

2021-06-01 08:30 UTC, alalazo commented
@opadron @scottwittenburg Github is merciless in dismissing reviews, so I'm in need of another one :slightly_smiling_face:

2021-06-01 15:05 UTC, scottwittenburg approved these changes

2021-06-01 16:45 UTC, tgamblin approved these changes

2021-06-01 16:46 UTC, tgamblin requested changes

2021-06-01 16:46 UTC, tgamblin commented on lib/spack/spack/test/ci.py
> -                    reason='This test requires gpg')
I think we should put this back.

2021-06-01 16:47 UTC, tgamblin approved these changes

2021-06-01 17:05 UTC, becker33 approved these changes

2021-06-01 17:05 UTC, merged

2021-06-01 17:12 UTC, alalazo commented
Thanks all!