Don't search for Python when SPACK_PYTHON is set
LLNL/spack pull request #23942
Opened 2021-05-26 22:10 UTC by maxim-belkin

I propose to not search for Python if `SPACK_PYTHON` is set.
I also synced up lists of Python interpreters in `setup-env.*` scripts with that in `bin/spack`.

2021-05-28 14:55 UTC, alalazo commented
Is this done for performance reasons? If so can you post some numbers?

2021-05-28 20:34 UTC, maxim-belkin commented
> Is this done for performance reasons?

There might be minor performance improvements associated with this change but that was not my goal. If `SPACK_PYTHON` is set but points to a non-functional interpreter, I'd prefer Spack to fail and notify me/user about it rather than look for the next available interpreter.

2021-06-11 08:31 UTC, haampie approved these changes
I would be a fan of this, no fallbacks if you are explicit about what python to use.

2021-07-13 00:30 UTC, tgamblin requested changes
I like it -- can you add a test in the shell tests in share/spack/qa?  I think it should be fairly easy to check there that `spack python --path` returns what `SPACK_PYTHON` is set to.

2021-07-13 09:51 UTC, maxim-belkin commented
I can mock something up. By the way, Blue Waters doesn't provide `realpath` shell function  -- we use `readlink -f` but there are pure Bash solutions([1](https://stackoverflow.com/a/66468913/7410631)).

2022-05-05 13:56 UTC, alalazo commented
@maxim-belkin Any news on this PR?

2023-11-19 00:18 UTC, alecbcs commented
Closing due to no response. @maxim-belkin happy to reopen if you'd like to continue working on this PR.

2023-11-19 00:18 UTC, closed without merging