New package:py-gsutil
LLNL/spack pull request #23970
Opened 2021-05-27 18:28 UTC by dorton21

depends on: #23968, #23967, #23969

2021-05-27 19:24 UTC, adamjstewart requested changes

2021-05-27 19:24 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-gsutil/package.py
> +    depends_on('python@3.4.0:')
```suggestion
    depends_on('python@2.7:2.8,3.5:3.999', type=('build', 'run'))
```

2021-05-27 19:24 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-gsutil/package.py
> +    depends_on('py-google-apitools@0.5.30:', type=('build', 'run'))
```suggestion
    depends_on('py-google-apitools@0.5.32:', type=('build', 'run'))
```

2021-05-27 19:29 UTC, adamjstewart submitted a review, later dismissed

2021-05-28 16:46 UTC, adamjstewart approved these changes

2021-06-02 01:44 UTC, adamjstewart approved these changes

2021-06-02 15:44 UTC, dorton21 commented
I believe this is failing because of new packages that have recently been merged.

2021-06-03 09:40 UTC, merged