New Package:py-responses
LLNL/spack pull request #23972
Opened 2021-05-27 18:39 UTC by dorton21

2021-05-27 19:21 UTC, adamjstewart requested changes

2021-05-27 19:21 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-responses/package.py
> +
```python
depends_on('python@2.7:2.8,3.5:', type=('build', 'run'))
```

2021-05-27 19:21 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-responses/package.py
> +    depends_on('py-mock', type=('build', 'run'))
```suggestion
    depends_on('py-mock', when='^python@:3.2.999', type=('build', 'run'))
```

2021-05-27 19:21 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-responses/package.py
> +    depends_on('py-setuptools', type='build')
Missing dep:
```python
depends_on('py-cookies', when='^python@:3.3.999', type=('build', 'run'))
```

2021-05-27 19:24 UTC, adamjstewart approved these changes

2021-06-02 01:46 UTC, adamjstewart commented
Tests are failing because the `py-cookies` package does not yet exist.

2021-06-02 15:40 UTC, dorton21 commented
> Tests are failing because the `py-cookies` package does not yet exist.

My bad. This is the related PR for py-cookies: #24084

2021-06-03 03:21 UTC, adamjstewart approved these changes

2021-06-03 03:43 UTC, merged