r-afex: add new package
LLNL/spack pull request #24004
Opened 2021-05-28 17:31 UTC by manuelakuhn

This package has a dependency on #24000

2021-05-30 03:15 UTC, glennpj requested changes

2021-05-30 03:15 UTC, glennpj commented on var/spack/repos/builtin/packages/r-afex/package.py
> +    url      = "https://cran.r-project.org/src/contrib/afex_0.28-1.tar.gz"
```suggestion
    url      = "https://cloud.r-project.org/src/contrib/afex_0.28-1.tar.gz"
```
Also, note that `url` and `list_url` can be dropped if using the `cran` attribute.

2021-06-03 02:26 UTC, glennpj approved these changes

2021-06-03 07:17 UTC, alalazo approved these changes

2021-06-03 09:22 UTC, merged