flibcpp: add new version and smoke test
LLNL/spack pull request #24050
Opened 2021-06-01 00:48 UTC by sethrj

2021-06-01 01:19 UTC, aprokop reviewed
Looks fine to me, but I have not tested it.

2021-06-01 01:19 UTC, aprokop commented on var/spack/repos/builtin/packages/flibcpp/package.py
>      url = "https://github.com/swig-fortran/flibcpp/archive/v0.3.1.tar.gz"
I know it's not necessary, but wanna update url to 1.0.1 too?

2021-06-01 07:31 UTC, alalazo requested changes
Style tests are failing

2021-06-03 09:21 UTC, alalazo approved these changes

2021-06-03 09:21 UTC, alalazo commented
Fyi @tldahlgren

2021-06-03 09:22 UTC, merged