spack ci: use return codes to signal exit status
LLNL/spack pull request #24090
Opened 2021-06-02 21:18 UTC by scottwittenburg

Fixes an issue where gitlab job traces always contain a stack trace resulting from calling `sys.exit()`, even if the exit value is `0`, while preserving the proper exit code from `spack ci` subcommands.

2021-06-02 21:19 UTC, scottwittenburg commented
@tgamblin This is the tweak you requested yesterday.

2021-06-02 22:09 UTC, tgamblin commented
@vsoch FYI -- this is the stack trace you pointed out.

2021-06-02 22:11 UTC, tgamblin requested changes
@scottwittenburg: LGTM but I think we can take out the `return 0`'s

2021-06-02 22:11 UTC, tgamblin commented on lib/spack/spack/cmd/ci.py
> +    return 0
I think the `return 0`'s can be removed -- as `None` is equivalent as far as the command dispatch logic is concerned.

2021-06-24 00:09 UTC, tgamblin approved these changes

2021-06-24 00:09 UTC, merged