Use ENABLE_RUNTIMES CMake option
LLNL/spack pull request #24132
Opened 2021-06-04 01:43 UTC by ikitayama

It's clearer to configure a build with ENABLE_RUNTIMES to build libomp and libomptarget runtimes when the "clang" variant is enabled.

2021-06-04 02:03 UTC, ikitayama commented
I've encountered a build error; reviewers, please wait until I find the workaround. Thanks.

2021-06-04 05:41 UTC, ikitayama commented
Another build attempt on X86 (JURECA) succeeded, but `spack load libelf` was needed.

Should we change to:

```
depends_on("libelf")
```

?

2021-06-04 05:55 UTC, ikitayama commented
My build command is:
```
spack install llvm+omp_debug+cuda cuda_arch=80
```

so I dont understand why during the build, libelf 's header file wasn't found.

2021-06-04 07:51 UTC, alalazo requested changes
Is this the correct commit? I see you mention `ENABLE_RUNTIME` but the changes only affect `BUILD_SHARED_LIBS`...

2021-06-04 08:21 UTC, ikitayama commented
This is orthogonal to the previous PR which was retracted.

On Fri, Jun 4, 2021 at 16:51 Massimiliano Culpo ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Is this the correct commit? I see you mention ENABLE_RUNTIME but the
> changes only affect BUILD_SHARED_LIBS...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/spack/spack/pull/24132#pullrequestreview-676013547>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHLBZ7AK5EV23KXAQYLKKDTRCAXNANCNFSM46B26X4Q>
> .
>

2022-08-22 12:23 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2022-08-22 12:23 UTC, closed without merging