Apply a patch for FJ compiler to fix a cmake error (similar to #12392 for cce).
LLNL/spack pull request #24172
Opened 2021-06-07 01:01 UTC by h-murai

The error discussed in #12392 is found also for FJ compiler. This patch is the same as for #12392 and fixes the error.

2021-10-07 13:27 UTC, bernhardkaindl commented
@h-murai This needs a rebase to current develop (sorry for the delay) and you should request review from someone who changed this package in the past, if possible the maintainer of that package.

You can request the review from the "Reviewers" field on the top right corner in github's PR view.

2022-05-05 13:59 UTC, alalazo requested changes
Apologies for the long delay in review! I missed this and am going through old PRs today.

2022-05-05 13:59 UTC, alalazo commented on var/spack/repos/builtin/packages/netlib-lapack/package.py
> +    patch('fj.patch', when='@3.7: %fj')
Can you add a comment above the directive explaining briefly what the patch does and where does it come from?

2022-12-22 11:31 UTC, alalazo commented on var/spack/repos/builtin/packages/netlib-lapack/package.py
> +    patch('fj.patch', when='@3.7: %fj')
@h-murai

2023-02-20 11:24 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2023-02-20 11:24 UTC, closed without merging