uchardet: new release + lib image was not found on Mac OSX
LLNL/spack pull request #24212
Opened 2021-06-09 06:23 UTC by cessenat

On Mac OS BigSur, cmake complained about CMAKE_MACOSX_RPATH not being set and when linking with uchardet lib from another package it was not found (there will be a PR for groff new release 1.22.4 where this was problematic).
Added new release 0.0.7 and git location.

2021-06-09 07:59 UTC, alalazo requested changes

2021-06-09 07:59 UTC, alalazo commented on var/spack/repos/builtin/packages/uchardet/package.py
> +        return args
I'd avoid the `when` decorator and use `CMakePackage` convenience functions. Something similar to:
```suggestion
    def cmake_args(self):
        args = []
        if self.spec.satisfies('platform=darwin'):
            args += [
                # From https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/uchardet.rb
                self.define('CMAKE_INSTALL_NAME_DIR', self.prefix.lib),
                # From https://github.com/mutationpp/Mutationpp/issues/26
                self.define('CMAKE_MACOSX_RPATH', 'ON')
            ]
        return args
```
(beware I didn't try the code above, so there might be typos).

2021-06-09 08:14 UTC, alalazo approved these changes

2021-06-10 09:52 UTC, cessenat commented
Seems merge is blocked

2021-06-10 09:52 UTC, cessenat commented
Reopenning to see if auto-merge can be done

2021-06-10 14:50 UTC, merged