New python packages added
LLNL/spack pull request #24352
Opened 2021-06-16 07:43 UTC by samcom12

Added new python packages - py-metis, py-triangle, and py-meshpy

2021-06-16 07:44 UTC, samcom12 commented
@alalazo Review and merge so that I can create new PR for the dependant package.

2021-06-16 19:05 UTC, tldahlgren commented
Note there is overlap between this PR and #24269

2021-06-16 19:07 UTC, tldahlgren requested changes

2021-06-16 19:07 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-meshpy/package.py
> +# Copyright 2013-2020 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
```

2021-06-16 19:07 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-pymetis/package.py
> +# Copyright 2013-2020 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
```

2021-06-16 19:37 UTC, adamjstewart commented
@samcom12 can you submit a separate PR for each package.py file you add/modify? This makes it easier for me to review and prevents overlap between PRs.

2021-07-15 10:25 UTC, samcom12 commented
Okay ... will use separate PR for each package.

2021-07-15 10:25 UTC, closed without merging