Add FTObjectLibrary package
LLNL/spack pull request #24423
Opened 2021-06-18 23:12 UTC by schoonovernumerics

Add the new FTObjectLibrary package from trixi-framework to support spectral element methods mesh generators and other tools.

2021-06-19 09:00 UTC, alalazo requested changes
A minor request, but otherwise LGTM

2021-06-19 09:00 UTC, alalazo commented on var/spack/repos/builtin/packages/ftobjectlibrary/package.py
> +        return args
This method can be omitted

2021-06-20 14:49 UTC, schoonovernumerics commented on var/spack/repos/builtin/packages/ftobjectlibrary/package.py
> +        return args
I've pushed up a change to remove `cmake_args` definition from this package.

2021-06-20 14:53 UTC, alalazo approved these changes

2021-06-24 04:55 UTC, merged