hypre: new version 2.21.0, variant fortran, becomes AutotoolsPackage
LLNL/spack pull request #24445
Opened 2021-06-21 15:07 UTC by cessenat

Adds version 2.21.0, adds variant fortran (hypre can be compiled and used without fortran), splitting phases using the autoconf package since Hypre uses the classical phases configure/make/make install.

2021-06-22 03:56 UTC, eugeneswalker commented
Pinging maintainers @ulrikeyang @osborn9 @balay

2021-06-23 15:26 UTC, cessenat commented
Hypre Changelog:
https://github.com/hypre-space/hypre/blob/master/CHANGELOG

#====================================

Version 2.22.0 released 2021/06/22

- Added GPU support for AMS, ADS, and AME solvers.
- Added mixedint support for GPUs.
- Fixed GPU issues with AMG-DD solver.
- Various bug fixes.

#====================================

Version 2.21.0 released 2021/05/25

- Changed GPU defaults and changed default CUDA arch to 70.
- Added new interfaces: HYPRE_SetSpGemmUseCusparse(1) to select cuSPARSE SpGeMM
  or hypre's MM (if 0); HYPRE_SetUseGpuRand(1) to use cuRand for PMIS or CPU RNG
  (if 0); HYPRE_SetMemoryLocation to select default memory location;
  HYPRE_SetExecutionPolicy to select default execution policy.
- Changed configure option: --enable-cub --> --enable-device-memory-pool;
  --enable-nvtx --> --enable-gpu-profiling
- Added new configure options: --with-cuda-home=DIR; --with-gpu-arch=ARG
- Added GPU build options to CMake.
- Added a new HYPRE_RELEASE_NUMBER macro.
- Improved support for ParCSR matrices with many zero rows.
- Improved BoomerAMG setup efficiency when there are many off-diagonal coefficients.
- Fixed a bug in the strength matrix generation for nodal AMG.
- Removed unified virtual memory (UVM) requirement from GPU implementation.
- Removed --enable-global-partition option.
- Added UMPIRE support for memory pooling on GPUs.
- Added HIP/AMD support.
- New CUDA based triangular smoothers.
- New parallel ILU solver features and GPU support.
- Added CUDA 11 support.
- Various bug fixes.

2021-06-23 21:20 UTC, osborn9 submitted a review, later dismissed
This looks good to me! Thanks for also updating to include the release from yesterday.

2021-06-28 08:42 UTC, alalazo requested changes
Pipelines are failing on an `mfem` build: https://gitlab.spack.io/spack/spack/-/jobs/465438 Can you please try:
```console
To reproduce this build locally, run:
    spack ci reproduce-build https://gitlab.spack.io/api/v4/projects/2/jobs/465438/artifacts [--working-dir <dir>]
```
to see if you can reproduce the issue locally, and then report back here?

2021-06-28 09:58 UTC, cessenat commented
Yes, I too encounter an error:
[ci_repro_mfem_cessenat.txt](https://github.com/spack/spack/files/6725220/ci_repro_mfem_cessenat.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/6725268/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/6725269/spack-build-out.txt)

2021-06-28 10:03 UTC, cessenat commented
> Yes, I too encounter an error:
> [ci_repro_mfem_cessenat.txt](https://github.com/spack/spack/files/6725220/ci_repro_mfem_cessenat.txt)
> [spack-build-env.txt](https://github.com/spack/spack/files/6725268/spack-build-env.txt)
> [spack-build-out.txt](https://github.com/spack/spack/files/6725269/spack-build-out.txt)

I get the error outside docker as well for both new relases 2.21.0 and 2.22.0.
Sorry for that !

2021-06-28 10:47 UTC, cessenat commented
Another hint is that : if MFEM is compiled without MPI, but with hypre (adding a hypre variant), then it compiles against both new versions of hypre.

2021-06-28 12:11 UTC, cessenat commented
Found MFEM pull request https://github.com/mfem/mfem/pull/2348 with @v-dobrev

2021-07-01 20:34 UTC, junghans approved these changes

2021-07-01 20:37 UTC, junghans commented
Hypre 2.22.0 also supports CMake and when installing with Autotools, cmake Modules (`HYPRE_config.h.cmake`) don't get installed.

2021-07-01 20:43 UTC, junghans requested changes
Could you build v2.22 with cmake?

2021-07-02 05:36 UTC, cessenat commented
> Could you build v2.22 with cmake?

Hello @junghans it is a bit of work and would make a lot of changes to that package, implying reviews again.
What about simply adding an install line for the missing `HYPRE_config.h.cmake` ?

2021-07-02 12:17 UTC, junghans commented
Sorry, I meant `HYPREConfig.cmake` that is generated by CMake.

2021-07-09 22:23 UTC, junghans commented
We could also create a hypre-cmake package in addition.

2021-09-03 13:40 UTC, cessenat commented
This PR is superseeded by https://github.com/spack/spack/pull/25781 ; I will close it in a while.

2021-10-01 18:32 UTC, scheibelp commented
Closing this since #25781 was merged

2021-10-01 18:32 UTC, closed without merging