Sensei repo update
LLNL/spack pull request #24487
Opened 2021-06-23 16:25 UTC by kwryankrattiger

Update `url` and `git` attributes in Sensei package to point to new locations on [Github](https://github.com/SENSEI-insitu/SENSEI/)

2021-06-23 16:27 UTC, kwryankrattiger commented
Tested using `spack fetch` for all semantic versions and `develop`

2021-06-25 12:33 UTC, alalazo requested changes
Can you please double check if the list of maintainers is correct?

2021-06-25 12:33 UTC, alalazo commented on var/spack/repos/builtin/packages/sensei/package.py
> +    maintainers = ['sshudler','rkrattiger']
```suggestion
    maintainers = ['sshudler', 'kwryankrattiger']
```

2021-06-25 14:44 UTC, alalazo approved these changes

2021-06-25 14:45 UTC, kwryankrattiger commented on var/spack/repos/builtin/packages/sensei/package.py
> +    maintainers = ['sshudler','rkrattiger']
Fixed this, sorry about that!

2021-06-26 08:48 UTC, alalazo commented
Giving some time to @sshudler to review this. If it stays stale for more than a few days ping me and I'll merge.

2021-06-30 22:03 UTC, kwryankrattiger commented
@alalazo Just checking in on this

2021-07-01 07:15 UTC, merged