update simgrid package
LLNL/spack pull request #24513
Opened 2021-06-24 22:48 UTC by viniciusvgp

2021-06-25 08:52 UTC, alalazo requested changes
A few issues:
- Style checks are failing
- We usually don't remove old versions, but deprecate them first, would that be possible here?

2021-06-25 19:04 UTC, viniciusvgp commented
> A few issues:
> 
>     * Style checks are failing
> 
>     * We usually don't remove old versions, but deprecate them first, would that be possible here?

done!

2021-06-28 07:13 UTC, alalazo requested changes

2021-06-28 07:13 UTC, alalazo commented on var/spack/repos/builtin/packages/simgrid/package.py
> +            url='https://github.com/simgrid/simgrid/releases/download/v3.26/simgrid-3.26.tar.gz')
We can possibly drop the `url` argument in the latest version directives:
```suggestion
    version('3.27', sha256='51aeb9de0434066e5fec40e785f5ea9fa934afe7f6bfb4aa627246e765f1d6d7')
    version('3.26', sha256='ac50da1eacc5a53b094a988a8ecde09962c29320f346b45e74dd32ab9d9f3e96')
```
and use the default `url`.

2021-06-29 04:34 UTC, alalazo approved these changes

2021-06-29 18:07 UTC, merged