Version update to 4.0.1
LLNL/spack pull request #24569
Opened 2021-06-28 18:14 UTC by dorton21

2021-06-28 21:47 UTC, tldahlgren submitted a review, later dismissed
Confirmed sha256.

2021-06-29 14:58 UTC, adamjstewart requested changes

2021-06-29 14:58 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-wxpython/package.py
>      depends_on('wxwidgets')
I think the "needed at runtime" dependencies should actually be `type=('build', 'run')`

2021-06-30 18:19 UTC, adamjstewart approved these changes

2021-06-30 22:55 UTC, merged