darshan-runtime,darshan-util: new version released + move to github
LLNL/spack pull request #24574
Opened 2021-06-28 22:15 UTC by shanedsnyder

- add 3.3.1 tag for runtime/util components
- remove preferred tag to make sure we use our most recent release
- add url_for_version() for each package to pick right URL based on version number (pre 3.3.1 versions not available on GitHub)

2021-06-29 04:00 UTC, alalazo requested changes
Due to a style check introduced in #23947 there's need to tweak the import order in this PR:
```python
import os

from spack import *
```

2021-06-29 14:47 UTC, shanedsnyder commented
Should have the import order fixed, as well as a small update to the `git` field in each package and a change from master->main branches -- last 2 were needed to complete transition from gitlab to github.

2021-06-29 16:18 UTC, carns submitted a review, later dismissed
looks good to me

2021-06-29 18:30 UTC, shanedsnyder commented
Sorry for the late commits here...we just realized GitHub doesn't support all we need to use it for managing our releases, so we will continue to maintain our releases on our own FTP server. Most recent commit redirected the `url` back to our FTP server and also recalculated the version checksum for there.

I think I'm actually done now :)

2021-06-29 18:38 UTC, carns approved these changes

2021-06-30 07:08 UTC, alalazo approved these changes

2021-06-30 07:11 UTC, merged