openfoam: RELEASE https://www.openfoam.com/news/main-news/openfoam-v2106
LLNL/spack pull request #24579
Opened 2021-06-29 07:01 UTC by olesenm

2021-06-30 07:24 UTC, alalazo approved these changes

2021-06-30 07:26 UTC, alalazo requested changes
Due to a new style check #23947 the import order at the top needs to be changed:
```python
import glob
import os
import re

import llnl.util.tty as tty
from spack import *
from spack.util.environment import EnvironmentModifications
```

2021-06-30 10:01 UTC, olesenm commented
@alalazo - hope it now fits the requirements.

2021-07-06 06:53 UTC, alalazo approved these changes

2021-07-06 06:54 UTC, merged

2021-07-06 08:50 UTC, olesenm commented
Thanks!