Add cxxstd to abseil-cpp
LLNL/spack pull request #24577
Opened 2021-06-28 23:54 UTC by nicmcd

Abseil wasn't designed to be a shared library. They guarantee API compatibility but not ABI compatibility. Users compiling with -std=c++17 will need a version of abseil-cpp with the same ABI. This PR adds the 'cxxstd' variant to abseil-cpp

2021-06-29 03:52 UTC, alalazo requested changes
A comment on style that will also fix Python 2.6 compatibility issues (that's what makes CI fail currently)

2021-06-29 03:52 UTC, alalazo commented on var/spack/repos/builtin/packages/abseil-cpp/package.py
> +        ]
I think you can rewrite this entire part as:
```python
    return [
        self.define('BUILD_TESTING', 'OFF'),
        self.define('CMAKE_CXX_STANDARD', cxxstd),
        self.define_from_variant('BUILD_SHARED_LIBS', 'shared')
    ]
```
and remove the `args.append` below.

2021-06-29 16:58 UTC, nicmcd commented
@alalazo, I made the change, but just slightly different than requested. Please take a look.

2021-06-30 07:13 UTC, alalazo approved these changes

2021-07-06 22:51 UTC, nicmcd commented
It looks like the CI pipeline failed on something unrelated to my changes.

2021-07-08 18:18 UTC, nicmcd commented
@alalazo Can we merge this?

2021-07-09 08:54 UTC, merged