Added AWS-AHUG ubuntu pipeline
LLNL/spack pull request #24601
Opened 2021-06-29 21:35 UTC by bollig

Testing new pipeline for ARM (Ubuntu1804)

2021-07-13 16:33 UTC, bollig commented
Test rebuild from comments

2022-05-06 21:37 UTC, bollig commented
will squash once pipeline builds

2022-05-19 14:59 UTC, scottwittenburg commented on share/spack/gitlab/cloud_pipelines/stacks/aws-ahug/spack.yaml
> +    - gcc
Version?

2022-05-19 15:43 UTC, scottwittenburg requested changes
This looks good, thanks @bollig, just a couple questions/requests.

2022-05-19 15:43 UTC, scottwittenburg commented on share/spack/gitlab/cloud_pipelines/stacks/aws-ahug-aarch64/spack.yaml
> +    - gcc
Version here?

2022-05-19 15:43 UTC, scottwittenburg commented on share/spack/gitlab/cloud_pipelines/stacks/aws-ahug-aarch64/spack.yaml
> +# TODO:
Are these comments still relevant, i.e. to be done?  If resolved, can they be removed?

2022-05-19 15:43 UTC, scottwittenburg commented on share/spack/gitlab/cloud_pipelines/stacks/aws-ahug/spack.yaml
> +# TODO:
Still todo?  Or can these comments be removed?

2022-05-19 16:11 UTC, bollig commented on share/spack/gitlab/cloud_pipelines/stacks/aws-ahug-aarch64/spack.yaml
> +    - gcc
In this case, gcc is the package that is built. I'd prefer the pipeline to track the latest version and continuously rebuild as new versions and hashes are populated. The `compiler:` block governs which version of gcc (gcc@7.3.1) is used to build packages.

2022-05-19 16:16 UTC, scottwittenburg approved these changes, later dismissed
Ok looks good, thanks @bollig :+1:

2022-05-19 16:16 UTC, scottwittenburg commented on share/spack/gitlab/cloud_pipelines/stacks/aws-ahug-aarch64/spack.yaml
> +    - gcc
Yeah, ok, that makes sense.

2022-05-24 04:07 UTC, bollig commented
Looks like this pipeline is failing on the same issues resolved by #30798

2022-05-27 20:03 UTC, scottwittenburg approved these changes, later dismissed
LGTM pending CI

2022-05-29 01:46 UTC, bollig commented
@spackbot re-run pipeline

2022-05-29 19:15 UTC, scottwittenburg commented
@spackbot run pipeline

2022-05-30 16:23 UTC, scottwittenburg approved these changes

2022-05-30 16:26 UTC, merged