Dask: 2021.06.2
LLNL/spack pull request #24606
Opened 2021-06-30 05:10 UTC by ax3l

Add the latest DASK release.

2021-06-30 10:32 UTC, skosukhin requested changes
The dependencies of `bag` and `delayed` became non-optional (see https://github.com/dask/dask/commit/a62fced2396a54446a1aca66e5a8ab7bd6853b0e), therefore I suggest adding two conflicts:
```diff
+    conflicts('~bag', when='@2021.3.1:')
     conflicts('+distributed', when='@:0.4.0,0.7.6:0.8.1')
     conflicts('+diagnostics', when='@:0.5.0')
+    conflicts('~delayed', when='@2021.3.1:')
```

2021-06-30 10:32 UTC, skosukhin commented on var/spack/repos/builtin/packages/py-dask/package.py
> +    depends_on('python@3.7:',           type=('build', 'run'), when='@2021.4.0:')
https://github.com/dask/dask/commit/1767fedd2f0662ba2fd6a9caebf2d3595ca8046c
```suggestion
    depends_on('python@3.7:',           type=('build', 'run'), when='@2021.3.1:')
```

2021-06-30 10:32 UTC, skosukhin commented on var/spack/repos/builtin/packages/py-dask/package.py
https://github.com/dask/dask/commit/a62fced2396a54446a1aca66e5a8ab7bd6853b0e
```suggestion

# Common requirements
depends_on('py-pyyaml',             type=('build', 'run'), when='@2.17.1:')
depends_on('py-cloudpickle@1.1.1:', type=('build', 'run'), when='@2021.3.1:')
depends_on('py-fsspec@0.6.0:',      type=('build', 'run'), when='@2021.3.1:')
depends_on('py-toolz@0.8.2:',       type=('build', 'run'), when='@2021.3.1:')
depends_on('py-partd@0.3.10:',      type=('build', 'run'), when='@2021.3.1:')

```

2021-06-30 10:32 UTC, skosukhin commented on var/spack/repos/builtin/packages/py-dask/package.py
> +    depends_on('py-numpy@1.16.0:',      type=('build', 'run'), when='@2021.4.0: +array')
https://github.com/dask/dask/commit/2598af25fd2ba3dd11482194928b48efb327f637
```suggestion
    depends_on('py-numpy@1.16.0:',      type=('build', 'run'), when='@2021.3.1: +array')
```

Also above (GitHub does not let me make a suggestion):
```diff
-    depends_on('py-numpy@1.10.4:',      type=('build', 'run'), when='+array')
+    depends_on('py-numpy',              type=('build', 'run'), when='@:0.17.1 +array')
+    depends_on('py-numpy@1.10.4:',      type=('build', 'run'), when='@0.17.2: +array')
```

2021-06-30 10:32 UTC, skosukhin commented on var/spack/repos/builtin/packages/py-dask/package.py
>      depends_on('py-toolz',              type=('build', 'run'), when='+array')
```suggestion
    depends_on('py-toolz',              type=('build', 'run'), when='@:0.6.1 +array')
```
Also below:
```diff
-    depends_on('py-toolz@0.8.2:',       type=('build', 'run'), when='@2.13.0: +array')
+    # The dependency on py-toolz is non-optional starting version 2021.3.1
+    depends_on('py-toolz@0.8.2:',       type=('build', 'run'), when='@2.13.0:2021.3.0 +array')
```

2021-06-30 10:32 UTC, skosukhin commented on var/spack/repos/builtin/packages/py-dask/package.py
> +    depends_on('py-cloudpickle@1.1.1:', type=('build', 'run'), when='@2021.4.0: +bag')
```suggestion
    # The dependency on py-cloudpickle is non-optional starting version 2021.3.1
    depends_on('py-cloudpickle@0.2.2:', type=('build', 'run'), when='@2.13.0:2021.3.0 +bag')
```

Also below:
```diff
-    depends_on('py-fsspec@0.6.0:',      type=('build', 'run'), when='@2.8.0: +bag')
+    # The dependency on py-fsspec is non-optional starting version 2021.3.1
+    depends_on('py-fsspec@0.6.0:',      type=('build', 'run'), when='@2.8.0:2021.3.0 +bag')
 
-    depends_on('py-toolz',              type=('build', 'run'), when='+bag')
+    depends_on('py-toolz',              type=('build', 'run'), when='@:0.6.1 +bag')
     depends_on('py-toolz@0.7.2:',       type=('build', 'run'), when='@0.7.0: +bag')
     depends_on('py-toolz@0.7.3:',       type=('build', 'run'), when='@0.14.1: +bag')
-    depends_on('py-toolz@0.8.2:',       type=('build', 'run'), when='@2.13.0: +bag')
+    # The dependency on py-toolz is non-optional starting version 2021.3.1
+    depends_on('py-toolz@0.8.2:',       type=('build', 'run'), when='@2.13.0:2021.3.0 +bag')
 
-    depends_on('py-partd',              type=('build', 'run'), when='+bag')
     depends_on('py-partd@0.3.2:',       type=('build', 'run'), when='@0.6.0: +bag')
     depends_on('py-partd@0.3.3:',       type=('build', 'run'), when='@0.9.0: +bag')
     depends_on('py-partd@0.3.5:',       type=('build', 'run'), when='@0.10.2: +bag')
     depends_on('py-partd@0.3.6:',       type=('build', 'run'), when='@0.12.0: +bag')
     depends_on('py-partd@0.3.7:',       type=('build', 'run'), when='@0.13.0: +bag')
     depends_on('py-partd@0.3.8:',       type=('build', 'run'), when='@0.15.0: +bag')
-    depends_on('py-partd@0.3.10:',      type=('build', 'run'), when='@2.0.0: +bag')
+    # The dependency on py-partd is non-optional starting version 2021.3.1
+    depends_on('py-partd@0.3.10:',      type=('build', 'run'), when='@2.0.0:2021.3.0 +bag')
```

2021-06-30 10:32 UTC, skosukhin commented on var/spack/repos/builtin/packages/py-dask/package.py
> +    depends_on('py-numpy@1.16.0:',      type=('build', 'run'), when='@2021.4.0: +dataframe')
https://github.com/dask/dask/commit/2598af25fd2ba3dd11482194928b48efb327f637
```suggestion
    depends_on('py-numpy@1.16.0:',      type=('build', 'run'), when='@2021.3.1: +dataframe')
```
Also above:
```diff
-    depends_on('py-numpy@1.10.4:',      type=('build', 'run'), when='+dataframe')
+    depends_on('py-numpy',              type=('build', 'run'), when='@:0.17.1 +dataframe')
+    depends_on('py-numpy@1.10.4:',      type=('build', 'run'), when='@0.17.2: +dataframe')
```
And below:
```diff
-    depends_on('py-toolz',              type=('build', 'run'), when='+dataframe')
+    depends_on('py-toolz',              type=('build', 'run'), when='@:0.6.1 +dataframe')
     depends_on('py-toolz@0.7.2:',       type=('build', 'run'), when='@0.7.0: +dataframe')
     depends_on('py-toolz@0.7.3:',       type=('build', 'run'), when='@0.14.1: +dataframe')
-    depends_on('py-toolz@0.8.2:',       type=('build', 'run'), when='@2.13.0: +dataframe')
+    # The dependency on py-toolz is non-optional starting version 2021.3.1
+    depends_on('py-toolz@0.8.2:',       type=('build', 'run'), when='@2.13.0:2021.3.0 +dataframe')
 
-    depends_on('py-partd',              type=('build', 'run'), when='+dataframe')
     depends_on('py-partd@0.3.2:',       type=('build', 'run'), when='@0.6.0: +dataframe')
     depends_on('py-partd@0.3.3:',       type=('build', 'run'), when='@0.9.0: +dataframe')
     depends_on('py-partd@0.3.5:',       type=('build', 'run'), when='@0.10.2: +dataframe')
     depends_on('py-partd@0.3.7:',       type=('build', 'run'), when='@0.13.0: +dataframe')
     depends_on('py-partd@0.3.8:',       type=('build', 'run'), when='@0.15.0: +dataframe')
-    depends_on('py-partd@0.3.10:',      type=('build', 'run'), when='@2.0.0: +dataframe')
+    # The dependency on py-partd is non-optional starting version 2021.3.1
+    depends_on('py-partd@0.3.10:',      type=('build', 'run'), when='@2.0.0:2021.3.0 +dataframe')
 
     depends_on('py-cloudpickle@0.2.1:', type=('build', 'run'), when='@0.8.2:2.6.0 +dataframe')
 
     depends_on('py-fsspec@0.3.3:',      type=('build', 'run'), when='@2.2.0: +dataframe')
     depends_on('py-fsspec@0.5.1:',      type=('build', 'run'), when='@2.5.0: +dataframe')
-    depends_on('py-fsspec@0.6.0:',      type=('build', 'run'), when='@2.8.0: +dataframe')
+    # The dependency on py-fsspec is non-optional starting version 2021.3.1
+    depends_on('py-fsspec@0.6.0:',      type=('build', 'run'), when='@2.8.0::2021.3.0 +dataframe')
```

2021-06-30 10:32 UTC, skosukhin commented on var/spack/repos/builtin/packages/py-dask/package.py
> +    depends_on('py-distributed@2021.6.2',   type=('build', 'run'), when='@2021.6.2 +distributed')
```suggestion
    depends_on('py-distributed@2021.3.0:',   type=('build', 'run'), when='@2021.3.0: +distributed')
    depends_on('py-distributed@2021.4.1:',   type=('build', 'run'), when='@2021.4.1: +distributed')
    depends_on('py-distributed@2021.5.0',   type=('build', 'run'), when='@2021.5.0: +distributed')
    depends_on('py-distributed@2021.5.1',   type=('build', 'run'), when='@2021.5.1: +distributed')
    depends_on('py-distributed@2021.6.0',   type=('build', 'run'), when='@2021.6.0: +distributed')
    depends_on('py-distributed@2021.6.1',   type=('build', 'run'), when='@2021.6.1: +distributed')
    depends_on('py-distributed@2021.6.2',   type=('build', 'run'), when='@2021.6.2: +distributed')
```

2021-06-30 10:32 UTC, skosukhin commented on var/spack/repos/builtin/packages/py-dask/package.py
>      depends_on('py-bokeh',              type=('build', 'run'), when='+diagnostics')
```suggestion
```
Also below:
```diff
-    depends_on('py-cloudpickle@0.2.1:', type=('build', 'run'), when='@2,7.0: +delayed')
-    depends_on('py-cloudpickle@0.2.2:', type=('build', 'run'), when='@2.13.0: +delayed')
+    depends_on('py-cloudpickle@0.2.1:', type=('build', 'run'), when='@2.7.0: +delayed')
+    # The dependency on py-cloudpickle is non-optional starting version 2021.3.1
+    depends_on('py-cloudpickle@0.2.2:', type=('build', 'run'), when='@2.13.0:2021.3.0 +delayed')
 
     depends_on('py-toolz@0.7.2:',       type=('build', 'run'), when='@0.8.1: +delayed')
     depends_on('py-toolz@0.7.3:',       type=('build', 'run'), when='@0.14.1: +delayed')
-    depends_on('py-toolz@0.8.2:',       type=('build', 'run'), when='@2.13.0: +delayed')
+    # The dependency on py-toolz is non-optional starting version 2021.3.1
+    depends_on('py-toolz@0.8.2:',       type=('build', 'run'), when='@2.13.0:2021.3.0 +delayed')
 
     # Support for YAML configuration files
-    depends_on('py-pyyaml',             type=('build', 'run'), when='+yaml')
+    # The dependency on py-pyyaml is non-optional starting version 2.17.1
+    depends_on('py-pyyaml',             type=('build', 'run'), when='@0.18.0:2.17.0 +yaml')
```

2021-07-02 05:26 UTC, ax3l commented on var/spack/repos/builtin/packages/py-dask/package.py
> +    depends_on('py-distributed@2021.6.1:',   type=('build', 'run'), when='@2021.6.1: +distributed')
I wonder if we really need all those, since we don't add them (yet)
```suggestion
```

2021-07-02 05:26 UTC, ax3l commented on var/spack/repos/builtin/packages/py-distributed/package.py
> +    version('2021.3.0', sha256='427fe7e047bbad7413c65d57e56fa4d6b1cf921fd206a3d2caab94bf9153c3db')
as comment above:
```suggestion
```

2021-07-02 05:27 UTC, ax3l commented
@skosukhin thanks a lot for the detailed review, please see the update in the PR :)

2021-07-14 19:38 UTC, ax3l commented
@skosukhin does this look good to you? :)

I think the CI pipeline fail is unrelated...

2021-07-14 19:54 UTC, skosukhin approved these changes

2021-07-14 19:58 UTC, adamjstewart approved these changes
Didn't look at this in much detail but I'm trusting @skosukhin

2021-07-14 19:58 UTC, merged