fix buffered download
LLNL/spack pull request #24623
Opened 2021-06-30 17:00 UTC by haampie

Closes https://github.com/spack/spack/issues/24589

2021-06-30 17:06 UTC, adamjstewart commented
This may be of interest, but this is how PyTorch/torchvision handle large downloads with urlib:
https://github.com/pytorch/vision/blob/master/torchvision/datasets/utils.py#L30,L38

2021-06-30 17:09 UTC, haampie commented
shutil has the advantage that we don't have to define the buffer size

2021-07-01 20:48 UTC, becker33 approved these changes, later dismissed

2021-07-01 20:57 UTC, loulawrence submitted a review, later dismissed

2021-07-05 15:36 UTC, eugeneswalker commented
Pipeline failing at least in part here because of network/infrastructure issues. @scottwittenburg 
* https://gitlab.spack.io/spack/spack/-/jobs/555763
* https://gitlab.spack.io/spack/spack/-/jobs/555758

2021-07-05 15:41 UTC, eugeneswalker commented
> Pipeline failing at least in part here because of network/infrastructure issues on `uo-godzilla` runner. @scottwittenburg
> 
> * https://gitlab.spack.io/spack/spack/-/jobs/555763
> * https://gitlab.spack.io/spack/spack/-/jobs/555758

I've disabled `uo-godzilla` and am re-starting the failed jobs manually.

2021-07-05 15:51 UTC, haampie commented
@alalazo can you hit merge again? the last commit is about whitespace

2021-07-06 06:24 UTC, alalazo requested changes
Since CI is failing, can you rebase and keep only changes that are relevant to the PR?

2021-07-06 06:24 UTC, alalazo commented on lib/spack/spack/cmd/ci.py
> -
This change is spurious and can be removed from the PR

2021-07-06 06:24 UTC, alalazo commented on lib/spack/spack/test/ci.py
> +
I think also changes in this file are spurious and can be removed.

2021-07-06 10:43 UTC, alalazo approved these changes

2021-07-06 12:12 UTC, merged