Use a context manager to group common constraints in packages
LLNL/spack pull request #24650
Opened 2021-07-01 12:30 UTC by alalazo

This PR adds a context manager that permit to group the common part of a `when=` argument and add that to the context:
```python
class Gcc(AutotoolsPackage):
    with constraint_met('+nvptx'):
        depends_on('cuda')
        conflicts('@:6', msg='NVPTX only supported in gcc 7 and above')
        conflicts('languages=ada')
        conflicts('languages=brig')
        conflicts('languages=go')
```
The above snippet is equivalent to:
```python
class Gcc(AutotoolsPackage):
    depends_on('cuda', when='+nvptx')
    conflicts('@:6', when='+nvptx', msg='NVPTX only supported in gcc 7 and above')
    conflicts('languages=ada', when='+nvptx')
    conflicts('languages=brig', when='+nvptx')
    conflicts('languages=go', when='+nvptx')
```
which needs a repetition of the `when='+nvptx'` argument. The context manager might help improving readability and permits to group together directives related to the same semantic aspect (e.g. all the directives needed to model the behavior of `gcc` when `+nvptx` is active). 

Modifications:

- [x] Added a `constraint_met` context manager to be used with package directives
- [x] Add unit tests and documentation for the new feature
- [x] Modified `cp2k` and `gcc` to show the use of the context manager

2021-07-01 12:41 UTC, alalazo commented
@tgamblin I know we discussed calling the context manager `when`, but it turns out we already have a decorator in scope wwith that name:
```python
@when('@1.0')
def config_args(self):
    pass
```

2021-07-01 14:35 UTC, haampie commented
This looks neat :)

2021-07-01 15:32 UTC, tgamblin commented
> I know we discussed calling the context manager when, but it turns out we already have a decorator in scope with that name

@alalazo does it matter?  the decorator is currently callable (which makes it a decorator) but why can't it also be a context manager?  I don't think overloading is bad here -- it's clear from context (ha) what's meant.

2021-07-01 15:33 UTC, tgamblin commented
Also, both the decorator and the context manager do a similar thing and take similar args.

2021-07-01 16:04 UTC, tgamblin commented
Hoping that if @adamjstewart sees this it will trigger a flood of OCD changes.

2021-07-01 16:05 UTC, adamjstewart commented
Don't tell my manager I'm working on Spack during my internship 😜

2021-07-01 17:51 UTC, alalazo commented
> I don't think overloading is bad here -- it's clear from context (ha) what's meant

Since you asked me to abuse Python, I don't see why I should say "no" :smirk: Now "when" is both a context manager AND a decorator.

2021-07-01 18:51 UTC, tgamblin commented
> context manager AND a decorator

Eeeeexcellent.  A `contanorator`?  We clearly need a term for this.

2021-07-01 19:05 UTC, tgamblin requested changes

2021-07-01 19:05 UTC, tgamblin commented on lib/spack/docs/packaging_guide.rst
> +Group ``when=`` constraints together
Can we call this "Common `when=` constraints"?

2021-07-01 19:05 UTC, tgamblin commented on lib/spack/docs/packaging_guide.rst
> +argument, or just part of it, Spack permits to group the common part
Instead of "permits to" can you say "allows you to"? (here and elsewhere)

2021-07-01 19:05 UTC, tgamblin commented
@alalazo just a couple really small requests

2021-07-01 19:26 UTC, alalazo commented on lib/spack/docs/packaging_guide.rst
> +Group ``when=`` constraints together
See e0e1d74

2021-07-01 19:26 UTC, alalazo commented on lib/spack/docs/packaging_guide.rst
> +argument, or just part of it, Spack permits to group the common part
See e0e1d74

2021-07-02 15:42 UTC, tgamblin approved these changes

2021-07-02 15:43 UTC, merged