Relocate spack_cmd and scripts from installer to root bin
LLNL/spack pull request #24651
Opened 2021-07-01 14:52 UTC by johnwparent

Remove superfluous copy operation needed to move spack batch launcher and associated scripts by refactoring spack to handle the invocation of the script from the root level bin directory. Refactor the installer to reflect this change.

2021-07-01 16:34 UTC, johnwparent commented
@BetsyMcPhail Let me know if there is anyone else I should tag here.

2021-07-01 21:00 UTC, BetsyMcPhail requested changes
The shortcuts seem to be broken. My desktop shortcut, for example, is looking for `C:\Users\betsy.mcphail\Desktop\spack_cmd.bat` instead of the actual installed location.

Running directly from the bin directory works as expected

2021-07-01 21:00 UTC, BetsyMcPhail commented on lib/spack/docs/getting_started.rst
> +from the spack soure tree root. This will provide a Windows command prompt
typo 'spack source tree root`

2021-07-01 21:20 UTC, johnwparent commented
> The shortcuts seem to be broken. My desktop shortcut, for example, is looking for `C:\Users\betsy.mcphail\Desktop\spack_cmd.bat` instead of the actual installed location.
> 
> Running directly from the bin directory works as expected

How did the start menu shortcut work? 

This behaved as expected locally, so it's most likely how I set the target w.r.t the install target file system.

2021-07-01 21:30 UTC, BetsyMcPhail commented
> > The shortcuts seem to be broken. My desktop shortcut, for example, is looking for `C:\Users\betsy.mcphail\Desktop\spack_cmd.bat` instead of the actual installed location.
> > Running directly from the bin directory works as expected
> 
> How did the start menu shortcut work? Also to what directory did you attempt to install spack?
> 
> This behaved as expected locally, so it's most likely how I set the shortcut target w.r.t the install target file system.

The start menu shortcut is failing the same way. I installed into `C:\Spack 0.16.0_NEW1`

2021-07-01 23:01 UTC, johnwparent commented
@BetsyMcPhail Thanks for the direction. It looks like the directory ids generated by CPack are not consistent enough to be referenced explicitly in the shortcut target. The new targets should be generic enough.  Sorry for the delay/incorrect targets.

2021-07-06 20:29 UTC, johnwparent commented
@BetsyMcPhail whenever you get a chance, this update should work.

2021-07-07 12:32 UTC, BetsyMcPhail approved these changes

2021-07-07 12:32 UTC, merged