bugfix: `spack config edit` should work in a bad environment
LLNL/spack pull request #24689
Opened 2021-07-03 20:50 UTC by tgamblin

Fixes #2468. (this may have been fixed already but it's related)

This PR fixes a number of bugs (one per commit -- this should be rebased not squashed) to get to the main one:

1. `spack --debug` wasn't in the right place and wouldn't take effect for things at the beginning of `main()`.
2. Config errors had gotten really verbose -- they print a full stack trace and don't just show the user where the error is like they used to.
3. `spack config get <section>` and `spack config --scope <scope> edit <section>` weren't working in environments. `spack config get <section>  should return the combined configuration for that section (including anything from `spack.yaml`), even in an environment, and `spack config edit` should respect the scope argument.
4. If you don't format `spack.yaml` correctly, `spack config edit` still fails and you have to edit your `spack.yaml` manually. Spack should be smarter than this.

- [x] Rework `_main()` and add some notes for maintainers on where things need to go for configuration to work properly.
- [x] Move config setup to *after* command-line parsing is done.
- [x] Add some code to `_main()` to defer `ConfigFormatError` when loading the environment, until we know what command is being run.  
- [x] Make `spack config edit` use `SPACK_ENV` instead of the config scope object to find `spack.yaml`, so it can work even if the environment is bad.
- [x] Reorder conditions in `cmd/config.py` to fix environment issues.

2021-10-25 20:05 UTC, scheibelp requested changes
I started looking through this in detail but noticed an error (perhaps things got out of sync) where I think most commands are broken: I prefixed that comment with "major".

2021-10-25 20:05 UTC, scheibelp commented on lib/spack/spack/main.py
> +            env_format_error = e
(minor: naming) I'm not sure why this is called `env_format_error` since it could be an issue with other config scopes (although it's true that this only occurs if we have an environment since the config is read earlier for that).

2021-10-25 20:05 UTC, scheibelp commented on lib/spack/spack/cmd/config.py
> +        spack.config.config.print_section(section)
(I didn't think this would get posted: ignore it for now)

> `spack config get <section>` was erroneously returning just the `spack.yaml`
for the environment.

FWIW `spack config --scope=user get packages` seems to work for me (i.e. it prints everything up to the user scope and excludes the env scope). Furthermore `spack config get doesn't currently define what it's supposed to do for a specified scope (i.e. should it print just that scope, or should it print everything up to that scope?).

2021-10-25 20:05 UTC, scheibelp commented on lib/spack/spack/main.py
> +                ev.activate(env, args.use_env_repo, add_view=False)
(major) Currently getting an error:

```
# spack config --scope=defaults get packages
==> Error: activate() got an unexpected keyword argument 'add_view'
```

I think you can just remove `add_view`.

There appears to be an `environment.environment.activate` and an `environment.shell.activate`; only the latter accepts an `add_view` argument (but that isn't the one being used here I think.

2021-10-26 21:35 UTC, tgamblin commented on lib/spack/spack/main.py
> +            env_format_error = e
I think this is fine to change to config_format_error or whatever

2021-10-26 23:22 UTC, scheibelp commented on lib/spack/spack/main.py
> +            env_format_error = e
From further experimentation it turns out this is only occurring when the `spack.yaml` has errors (so for example you can edit `packages.yaml` in the user scope, add errors, and still `spack config edit` it). So this variable name seems suitable.

2021-10-27 20:50 UTC, scheibelp commented on share/spack/qa/run-shell-tests
> +    kcov "$SPACK_ROOT/coverage" "$QA_DIR/test-env-cfg.sh" &> /dev/null
@tgamblin you mentioned adding coverage: AFAIK this is the way to do it, although the coverage numbers don't change at all (currently 43.18%). Did you have something else in mind for coverage?

2021-10-27 21:27 UTC, tgamblin commented on share/spack/qa/run-shell-tests
> +    kcov "$SPACK_ROOT/coverage" "$QA_DIR/test-env-cfg.sh" &> /dev/null
We use `kcov` for shell coverage, not python coverage -- and I think that makes sense for the other tests, but not for this one.  The other tests in here are supposed to cover `setup-env.sh` in various shells -- IIRC `bash` is the only one that actually does coverage properly (which is why there is only this if statement for the bash section) and `kcov` launches bash itself.  Anyway, that's not what we need here.

I think really `test-env-cfg.sh` should be called from `run-unit-tests.sh`, since it isn't actually testing shell functionality.

You should modify `test-env-cfg.sh` so that it invokes spack the way the unit test script does:

```console
$coverage_run $(which spack) ... args ...
```

`$coverage_run` is set by `setup.sh`, which all the test scripts use.  I could be wrong but I think it needs to be run from the unit test script to be included in the aggregation of coverage data -- I forget whether the shell one actually does that for `coverage.py` data or just `kcov` data.

2021-10-27 23:36 UTC, scheibelp commented
@spackbot re-run pipeline

2021-10-28 00:19 UTC, scheibelp commented on share/spack/qa/test-env-cfg.sh
> +$coverage_run spack config edit --print-file
I thought this is what you were suggesting in https://github.com/spack/spack/pull/24689#discussion_r737859729 but it doesn't affect the coverage numbers. It appears to have run, e.g. in https://github.com/spack/spack/runs/4028264529?check_suite_focus=true: 

```
...
====== 3088 passed, 107 skipped, 7 xfailed, 4 xpassed in 1954.52 seconds =======
==> Updating view at /home/runner/work/spack/spack/var/spack/environments/broken-cfg-env/.spack-env/view
==> Created environment 'broken-cfg-env' in /home/runner/work/spack/spack/var/spack/environments/broken-cfg-env
...
```

2021-10-28 00:31 UTC, tgamblin commented on share/spack/qa/test-env-cfg.sh
> +$coverage_run spack config edit --print-file
It looks like `run-unit-tests` sources `setup.sh`, but because it doesn't export the variables that get set there (like `coverage_run`), they aren't making it to your script.  I was able to determine this locally.

I think you can fix it by just sourcing setup.sh in your script.

2021-10-28 05:33 UTC, scheibelp commented on share/spack/qa/test-env-cfg.sh
> +$coverage_run spack config edit --print-file
OK excellent with that I have bumped the coverage from 43% to 59%. The details on codecov do not attribute this to `test-env-cfg.sh` (i.e. that is ignored) but instead to handling of `spack --pdb...`.

If it is agreeable not to test that, I'd say the current coverage is sufficient.

2021-10-28 05:42 UTC, tgamblin commented on share/spack/qa/test-env-cfg.sh
> +$coverage_run spack config edit --print-file
I looked at the diff on `codecov`, and it looks like the coverage numbers are off by one (+1) from the actual lines they're supposed to be covering.  I don't think we should worry about that too much right now, just saying.

The lines we care about for *this specific PR* are covered so I think we can call this good.  The rest of `main()` was poorly covered to begin with, but I think with your script it can be more covered in the near future.  I say let's save renaming `test-env-cfg.sh` to `test-main.sh` for some future PR and get all the corner cases covered then.

If you're ok with this plan go ahead and approve and let's merge this.

2021-10-28 18:34 UTC, scheibelp approved these changes

2021-10-28 22:37 UTC, merged

2021-10-29 18:56 UTC, adamjstewart commented
@tgamblin @scheibelp the first commit of this PR broke our style tests.

### Before

```console
$ git checkout 732be7dec6
$ spack style --no-isort --no-mypy
==> Running style checks on spack
  selected: flake8
==> Modified files
  ../../../var/spack/repos/builtin/packages/hdf5/package.py
==> Running flake8 checks
  ../../../var/spack/repos/builtin/packages/hdf5/package.py:30: [E303] too many blank lines (2)
  flake8 found errors
==> Error: spack style found errors
$ echo $?
1
```

### After

```console
$ git checkout 56ad721eb5
$ spack style --no-isort --no-mypy
==> Running style checks on spack
  selected: flake8
==> Modified files
  ../../../var/spack/repos/builtin/packages/hdf5/package.py
==> Running flake8 checks
  ../../../var/spack/repos/builtin/packages/hdf5/package.py:30: [E303] too many blank lines (2)
  flake8 found errors
==> Error: spack style found errors
$ echo $?
0
```
I noticed a PR where style should have failed but the tests pass just fine: https://github.com/spack/spack/runs/4049232114

2021-10-29 19:22 UTC, scheibelp commented
Thanks @adamjstewart, https://github.com/spack/spack/pull/27077 should address this