Fix fetching for Python 3.9.6
LLNL/spack pull request #24686
Opened 2021-07-02 23:52 UTC by adamjstewart

When using Python 3.9.6, Spack is no longer able to fetch anything. Commands like `spack fetch` and `spack install` all break.

Python 3.9.6 includes a [new change](https://github.com/python/cpython/pull/25853/files#diff-b3712475a413ec972134c0260c8f1eb1deefb66184f740ef00c37b4487ef873eR462) that means that `scheme` must be a string, it cannot be None. The solution is to use an empty string like the method default.

Fixes #24644. Also see https://github.com/Homebrew/homebrew-core/pull/80175 where this issue was discovered by CI. Thanks @branchvincent for reporting such a serious issue before any actual users encountered it!

2021-07-02 23:54 UTC, vsoch commented
wow, nice work @adamjstewart !

2021-07-03 00:17 UTC, tgamblin approved these changes

2021-07-03 00:18 UTC, tgamblin requested changes
looks like downloads are failing and @adamjstewart is getting bitten by his own import order issues.

2021-07-03 00:32 UTC, tgamblin submitted a review, later dismissed

2021-07-03 05:12 UTC, becker33 approved these changes

2021-07-03 05:20 UTC, merged

2021-07-03 06:41 UTC, vsoch commented
Nice work @adamjstewart, @tgamblin, and @becker33 ! The spack universe is safe again (at least until the Eye of Sauron decides to strike again).

2021-07-05 20:02 UTC, haampie commented
Can we backport this?

2021-09-16 13:48 UTC, haampie commented
@tgamblin @adamjstewart why didn't we immediately backport this? People are still running into this (e.g. installing a tagged = stable version of Spack on Fedora 34 runs right into this as it ships Python 3.9.x)