py-sphobjinv: add new package
LLNL/spack pull request #24790
Opened 2021-07-08 18:42 UTC by adamjstewart

Successfully builds on Ubuntu 20.04 with Python 3.8.11 and GCC 9.3.0.

2021-07-09 09:58 UTC, alalazo requested changes

2021-07-09 09:58 UTC, alalazo commented on var/spack/repos/builtin/packages/py-sphobjinv/package.py
> +# ----------------------------------------------------------------------------
:scream:

2021-07-09 15:42 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-sphobjinv/package.py
> +# ----------------------------------------------------------------------------
A rookie mistake 😆

2021-07-12 11:40 UTC, alalazo approved these changes

2021-07-12 11:40 UTC, merged