Bolt: Add E4S testsuite stand alone test
LLNL/spack pull request #24846
Opened 2021-07-12 21:50 UTC by RikkiButler20

This PR represents a preliminary stand alone test for the `bolt` package and is intended to serve the following purposes:

1. Leverage the current E4S test suite for the software
2. Demonstrate to package maintainers how to start a Spack stand alone test.

2021-07-12 21:59 UTC, shintaro-iwasaki commented
Thanks! It looks good to me.

2021-07-14 19:04 UTC, tldahlgren requested changes

2021-07-14 19:04 UTC, tldahlgren commented on var/spack/repos/builtin/packages/bolt/package.py
> +        test_dir = join_path(self.install_test_root, 'examples')
Please use the test stage directory copy for these tests:

```suggestion
        test_dir = join_path(self.test_suite.current_test_cache_dir, 'examples')
```

2021-07-14 19:05 UTC, tldahlgren commented
Please also resolve the style issues:

```
  var/spack/repos/builtin/packages/bolt/package.py:64: [E128] continuation line under-indented for visual indent
20
  var/spack/repos/builtin/packages/bolt/package.py:66: [E128] continuation line under-indented for visual indent
21
  var/spack/repos/builtin/packages/bolt/package.py:67: [E128] continuation line under-indented for visual indent
```

2021-07-16 22:02 UTC, tldahlgren commented on var/spack/repos/builtin/packages/bolt/package.py
> +    test_requires_compiler = True
Great catch!

2021-07-21 18:46 UTC, tldahlgren commented on var/spack/repos/builtin/packages/bolt/package.py
> +        self.run_test('gcc',
This worked for me as-is when I tested it, thanks!  

My concern in general is that the package is supposed to be buildable with a variety of compilers and this test case only checks one.  It is preferable that it use `self.compiler.cc` so the test builds with the same compiler used when the code is built.  Unfortunately, that simple change didn't work for me.  But the problem may be part of another issue.

2021-07-21 19:03 UTC, tldahlgren commented on var/spack/repos/builtin/packages/bolt/package.py
> +        self.run_test('gcc',
```suggestion
        # TODO: Either change to use self.compiler.cc (so using the build-time compiler)
        #  or add test parts that compile with the different supported compilers.
        self.run_test('gcc',
```

2021-07-21 19:04 UTC, tldahlgren approved these changes

2021-07-21 19:40 UTC, merged