add variant with compiler optimization
LLNL/spack pull request #24910
Opened 2021-07-15 17:54 UTC by ImanHosseini

Update package.py to include variant with compiler optimization, benchmarked at A-HUG hackaton shown to improve major kernel time by roughly 3%.

2021-07-15 19:42 UTC, tzanio submitted a review, later dismissed
This seems a bit minor, but I don't have problem including it.

2021-07-19 11:07 UTC, haampie commented
```
  var/spack/repos/builtin/packages/laghos/package.py:57: [W293] blank line contains whitespace
```

2021-08-01 17:32 UTC, adamjstewart requested changes

2021-08-01 17:32 UTC, adamjstewart commented on var/spack/repos/builtin/packages/laghos/package.py
> +                targets.append('CXXFLAGS = -Ofast -finline-functions')
```suggestion
        if '+ofast %gcc' in self.spec:
            targets.append('CXXFLAGS = -Ofast -finline-functions')
```

2021-08-01 18:53 UTC, adamjstewart approved these changes

2021-08-01 18:58 UTC, merged