add dock
LLNL/spack pull request #24933
Opened 2021-07-16 18:32 UTC by FindHao

update package.py to include variants with optimizations. We add optional jemalloc as the optimization, and add the support for arm and nvhpc compilers.

2021-07-20 08:05 UTC, alalazo requested changes

2021-07-20 08:05 UTC, alalazo commented on var/spack/repos/builtin/packages/dock/package.py
> +    version('opt', git='file://{0}/dock'.format(os.getcwd()))
What would be the purpose of this version?

2021-07-20 09:34 UTC, OliverPerks commented
It might be worth holding off on this.
Looking at the report from the hackathon we need to add the `arm` and `nvhpc` patch files, and the compiler config files.

As for the `jemalloc` feature, this shows a good performance gain, but again we would want to make sure we are adding it properly (rather than hard-coding it in the config files).
I'm happy to work with you to add this all in a more Spack friendly way.

2021-08-01 17:17 UTC, adamjstewart commented
> It might be worth holding off on this.

Converted to a draft, feel free to mark the PR as "Ready for review" when it's ready.

2022-05-10 16:29 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2022-05-10 16:29 UTC, closed without merging