Robodoc: Adding Robodoc documentation tool
LLNL/spack pull request #25024
Opened 2021-07-21 20:23 UTC by wscullin

Contributing the Robodoc software documentation tool.

2021-07-21 23:05 UTC, tldahlgren requested changes
We prefer the use of `https` over `http` for all urls (when possible).

2021-07-21 23:05 UTC, tldahlgren commented on var/spack/repos/builtin/packages/robodoc/package.py
> +    homepage = "http://www.xs4all.nl/~rfsber/Robo/index.html"
```suggestion
    homepage = "https://www.xs4all.nl/~rfsber/Robo/index.html"
```
Or perhaps use the URL this redirects to (i.e., https://rfsber.home.xs4all.nl/Robo/index.html)?

2021-08-01 17:06 UTC, adamjstewart commented on var/spack/repos/builtin/packages/robodoc/package.py
> +    version('develop', git='https://github.com/gumpu/ROBODoc.git')
I would add `git = ...` above where you define the url. Then you can use `branch='release'` here. This way, if someone ever adds master, you don't need to duplicate the git.

2021-08-01 17:06 UTC, adamjstewart commented on var/spack/repos/builtin/packages/robodoc/package.py
> +        autoreconf('--install', '--verbose', '--force')
Does the default implementation not work?

2021-08-01 17:06 UTC, adamjstewart commented on var/spack/repos/builtin/packages/robodoc/package.py
> +        return args
You can remove this if you aren't going to use it.

2022-05-09 18:42 UTC, tldahlgren commented
Is this PR still active?  Adam made a number of useful suggestions.

2022-12-22 11:33 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2022-12-22 11:33 UTC, closed without merging