poppler: drop splash patch for 21.07.0
LLNL/spack pull request #25032
Opened 2021-07-22 13:21 UTC by dylex

`ENABLE_SPLASH` configuration has been removed entirely so patch is no longer necessary after #24931 (I think -- I'm not entirely sure why this was disabled to begin with).  Theoretically the `-DENABLE_SPLASH=OFF` could be conditionalized out as well, but it doesn't seem to be hurting anything.

2021-07-26 08:23 UTC, alalazo requested changes
Can you check the suggestion for the patch, or explain better why `2` should be the upper bound of the condition?

2021-07-26 08:23 UTC, alalazo commented on var/spack/repos/builtin/packages/poppler/package.py
> +    patch('poppler_page_splash.0.90.1.patch', when='@0.90.1:2 ^qt@5.0:')
```suggestion
    patch('poppler_page_splash.0.90.1.patch', when='@0.90.1 ^qt@5.0:')
```

2021-07-26 14:57 UTC, dylex commented
the `2` was mainly a place holder.  It looks like the relevant code was removed between 21.06 and 21.07 so I've changed this to `21.06`. It is possible this patch is not the correct one for such versions, but seems better to leave it in as an indication that something is needed, should such versions be added later.

2021-07-28 16:23 UTC, alalazo approved these changes

2021-07-28 16:23 UTC, merged