Default config.yaml For Windows
LLNL/spack pull request #25114
Opened 2021-07-27 21:48 UTC by jpopelar

This default config.yaml is short enough to avoid long pathname errors related to cmd and uses the Posix path separator (/) instead of Windows'

2021-08-02 16:06 UTC, BetsyMcPhail commented
@jpopelar a rebase on the latest features/windows-support should fix the failing tests.

2021-08-02 16:11 UTC, BetsyMcPhail commented
Can you also update [getting started doc](https://github.com/spack/spack/blob/features/windows-support/lib/spack/docs/getting_started.rst)? The entire section about creating 'config.yaml' can probably be removed.

2021-08-02 16:26 UTC, jpopelar commented
Done and done! Waiting on tests now

2021-08-02 20:02 UTC, jpopelar commented
Just some last minute bookkeeping and code cleanup Bill Hoffman noticed

2021-08-03 21:27 UTC, BetsyMcPhail requested changes
Something seems to be off with the documentation, maybe a rebase issue? It seems like we lost some valid changes.

2021-08-03 21:27 UTC, BetsyMcPhail commented on lib/spack/docs/getting_started.rst
> +* Intel Fortran
Some of these packages should be optional (however you want to note that in the documentation): Intel Fortran, Perl, NASM. They won't be needed by all users

2021-08-03 21:27 UTC, BetsyMcPhail commented on lib/spack/docs/getting_started.rst
> -When given the option of adjusting your ``PATH``, choose the ``Git from the
This should still be valid?

2021-08-03 21:27 UTC, BetsyMcPhail commented on lib/spack/docs/getting_started.rst
> +``git checkout`` to switch to it. Then navigate to
The copying is no longer necessary (and scripts doesn't exist!)

2021-08-03 21:27 UTC, BetsyMcPhail commented on lib/spack/docs/getting_started.rst
> +Your file structure should look like this after following the above
This is no longer relevant

2021-08-03 21:27 UTC, BetsyMcPhail commented on lib/spack/docs/getting_started.rst
> +To use Spack, run ``spack_cmd.bat`` (you may need to Run as Administrator).  This will provide
To use Spack, run ``bin\spack_cmd.bat`` (you may need to Run as Administrator) from the spack source tree root.

2021-08-03 21:27 UTC, BetsyMcPhail commented on lib/spack/docs/getting_started.rst
> +This creates a ``.spack`` directory in our home directory, along with a windows subdirectory
along with a ``windows`` subdirectory

2021-08-03 21:27 UTC, BetsyMcPhail commented on lib/spack/docs/getting_started.rst
> +do this and write your own configuration files in the Configuration Files section of our
link to Configuration Files section?

2021-08-03 21:27 UTC, BetsyMcPhail commented on lib/spack/docs/getting_started.rst
> -It is important to note that the version of your Ninja and CMake could
Still want this and the next paragraph?

2021-08-03 21:27 UTC, BetsyMcPhail commented on lib/spack/docs/getting_started.rst
> +obtain it by running the Visual Studio Insaller and following the instructions
typo: Installer

2021-08-03 21:27 UTC, BetsyMcPhail commented on lib/spack/docs/getting_started.rst
> -For the ``packages.yaml`` file, there are two options. The first
The spack external find ... instructions should still be valid?

2021-08-04 14:45 UTC, jpopelar commented
Just touched up on everything you mentioned above; not sure how the spack external stuff got deleted. It's back now, with some additional proofreading edits

2021-08-04 21:14 UTC, BetsyMcPhail approved these changes
Thanks for the updates! LGTM

2021-08-04 21:15 UTC, merged