add fides package
LLNL/spack pull request #25128
Opened 2021-07-28 23:34 UTC by cyrush

2021-07-29 07:35 UTC, alalazo requested changes
A few minor points and `style` test is failing

2021-07-29 07:35 UTC, alalazo commented on var/spack/repos/builtin/packages/fides/package.py
> +    """
Optional, but triggers my OCD:
```suggestion
    """A library that provides a schema for ADIOS2 streams."""
```

2021-07-29 07:35 UTC, alalazo commented on var/spack/repos/builtin/packages/fides/package.py
> +    maintainers = ['caitlin.ross', 'dpugmire']
The first maintainer doesn't seem to be a valid Github username
```suggestion
    maintainers = ['dpugmire']
```

2021-07-29 07:35 UTC, alalazo commented on var/spack/repos/builtin/packages/fides/package.py
> +        options.append("-DFIDES_ENABLE_EXAMPLES=OFF")
You can use the more idiomatic:
```suggestion
        options = [
            self.define("VTKm_DIR", spec['vtk-m'].prefix),
            self.define("ADIOS2_DIR", spec['adios2'].prefix),
            self.define("FIDES_ENABLE_TESTING", "OFF"),            
            self.define("FIDES_ENABLE_EXAMPLES", "OFF")
        ]
```
Beware I wrote the code during review and never tried it (so there might be typos).

2021-07-29 15:51 UTC, cyrush commented
@alalazo thanks! I fixed the github name, made and tested the other suggestions.

2021-07-30 10:13 UTC, alalazo approved these changes

2021-07-30 10:14 UTC, merged

2021-07-30 16:11 UTC, cyrush commented
@alalazo thanks!