Windows lock timeout
LLNL/spack pull request #25189
Opened 2021-08-02 17:32 UTC by johnwparent

Fixes #59 on the Windows Issue Board. 

Solves two issues: The first, posix locks can be arbitrarily promoted/demoted by any handle from the same process. This is not true in Windows. Solves the issue by first unlocking the file lock (if necessary) before taking the promotion.

The second issue, is multiple instances of the same lock called one after the other are acceptable in Posix locks, but not Windows. Implement a flyweight pattern to serve one lock instance per lock path per process on Windows. This allows all calls to share the same fd handle.

2021-08-02 17:33 UTC, johnwparent commented
@BetsyMcPhail PTAL when you get a chance.

2021-08-03 21:04 UTC, BetsyMcPhail requested changes

2021-08-03 21:04 UTC, BetsyMcPhail commented on lib/spack/llnl/util/lock.py
> +    # file_map = {}
Is this line needed?

2021-08-03 21:04 UTC, BetsyMcPhail commented on lib/spack/llnl/util/lock.py
> +            self.LOCK_EX
This is a no-op? Should be `self.current_lock = self.LOCK_EX` ?

2021-08-03 21:17 UTC, johnwparent commented on lib/spack/llnl/util/lock.py
> +            self.LOCK_EX
Yes it should, thank you.

2021-08-03 21:18 UTC, johnwparent commented on lib/spack/llnl/util/lock.py
> +    # file_map = {}
No it is not, missed it during cleanup.

2021-08-03 21:29 UTC, BetsyMcPhail approved these changes
Looks good assuming CI passes

2021-08-03 21:31 UTC, johnwparent commented
I have an outstanding branch to verify that locking works on WIndows CI, do we want to merge that in here before merging into the feature branch?

2021-08-03 21:32 UTC, merged

2021-08-03 21:33 UTC, BetsyMcPhail commented
> I have an outstanding branch to verify that locking works on WIndows CI, do we want to merge that in here before merging into the feature branch?

I was too quick on the Merge button! If you do a new PR with the locking checks and that fails, we can always revert this change. I'm happy that it's not _more_ broken than the current state.