libcircle fix for CCE
LLNL/spack pull request #25224
Opened 2021-08-03 16:43 UTC by lukebroskop

Add a libtool build dependency to libcircle when building w/ CCE

2021-08-03 16:54 UTC, tldahlgren approved these changes, later dismissed
LGTM

2021-08-03 20:18 UTC, haampie commented
Why are these not marked build dependencies?

And why do they depend on the choice of compiler?

2021-08-03 21:08 UTC, lukebroskop commented
They are mark as build dependencies now. I had to make changes to the configure.ac file to compile w/ CCE.

2021-08-04 09:20 UTC, haampie requested changes

2021-08-04 09:20 UTC, haampie commented on var/spack/repos/builtin/packages/libcircle/package.py
> +    depends_on('libtool', when='%cce' type='build')
```suggestion
    depends_on('libtool', when='%cce', type='build')
```

2021-08-04 12:37 UTC, haampie approved these changes

2021-08-04 12:43 UTC, merged