SOS: add xpmem variant
LLNL/spack pull request #25260
Opened 2021-08-04 21:04 UTC by rscohn2

Add xpmem variant. Using xpmem disables ofi because it interferes with single node optimizations.

@davidozog: please review

2021-08-04 22:06 UTC, davidozog commented
FWIW, it can be advantageous to enable both `xpmem` and `ofi` if both are requested.  In that case, puts & gets to an on-node target process will go through XPMEM shared memory.

But if `ofi` and `shr-atomics` are requested, then `shr-atomics` must be disabled because remote atomics always need to go through memory that's registered with OFI.

I'm unversed in spack and not exactly sure how to capture this... Is it possible to add a `variant` for `xpmem+ofi`?

2021-08-05 12:31 UTC, rscohn2 commented
@davidozog : I made the options orthogonal so the user can choose what they want. Please look at the defaults to see if they are reasonable.

2021-08-06 19:49 UTC, davidozog commented
@rscohn2 - It's not a major concern, but it may be better to only enable `ofi` by default (not `shr-atomics`).  When enabling shared atomics _with_ OFI, the "automatic" path in SOS uses (software-based) collectives that do not rely on remote atomics.  These collectives may not perform as well on PGAS-friendly networks (OPA, Aries, IB), but it depends on message size, scale, etc.  Shared atomics will only give better performance on single node runs _without_ OFI, Portals, or UCX.  When a remote transport is enabled, all atomics must go through the transport layer even if the target is local/on-node.

2021-08-06 20:11 UTC, rscohn2 commented
I changed the defaults. If you are happy with this, I will try to get the attention of a spack maintainer so it can be merged.

2021-08-06 20:20 UTC, davidozog submitted a review, later dismissed

2021-08-09 07:55 UTC, alalazo requested changes
Add a few minor comments to make the recipe more idiomatic and explicitly disable the options if the variant is off. Didn't try the code suggested, so watch out for typos.

2021-08-09 07:55 UTC, alalazo commented on var/spack/repos/builtin/packages/sos/package.py
> +            args.append('--with-xpmem')
```suggestion
        args.extend(self.with_or_without('xpmem'))
```

2021-08-09 07:55 UTC, alalazo commented on var/spack/repos/builtin/packages/sos/package.py
> +            args.append('--with-ofi')
```suggestion
        args.extend(self.with_or_without('ofi'))
```

2021-08-09 07:55 UTC, alalazo commented on var/spack/repos/builtin/packages/sos/package.py
> +            args.append('--enable-shr-atomics')
```suggestion
        args.extend(self.with_or_without('shr-atomics'))
```

2021-08-09 12:52 UTC, alalazo approved these changes

2021-08-09 13:16 UTC, merged