Do not allow cray build system patch for later version of otf2
LLNL/spack pull request #25283
Opened 2021-08-05 20:55 UTC by lukebroskop

2021-08-05 21:12 UTC, hainest commented
@lukebroskop Looks good on Theta. Thanks again!

2021-08-06 16:11 UTC, hainest approved these changes, later dismissed

2021-08-06 18:00 UTC, hainest commented
@tldahlgren @adamjstewart This is ready to be merged at your convenience. Thanks!

2021-08-09 07:58 UTC, alalazo requested changes
A few minor requests

2021-08-09 07:58 UTC, alalazo commented on var/spack/repos/builtin/packages/otf2/package.py
> +    depends_on('m4', type='build', when='@2.2 %cce')
```suggestion
    with when('@2.2 %cce'):
        depends_on('autoconf', type='build')
        depends_on('automake', type='build')
        depends_on('libtool', type='build')
        depends_on('m4', type='build')
```

2021-08-09 07:58 UTC, alalazo commented on var/spack/repos/builtin/packages/otf2/package.py
> +    patch('cray_ac_scorep_sys_detection-m4.patch', when='@2.2 %cce')
Can you move the patch within the context manager suggested above? Doing so we'll group together all the things needed `when='@2.2 %cce'`).

2021-09-06 12:38 UTC, alalazo approved these changes

2021-09-06 12:38 UTC, merged