Add libtree deps
LLNL/spack pull request #25337
Opened 2021-08-10 15:11 UTC by haampie

- un-vendor libtree's deps
- Add master branch

2021-08-10 16:44 UTC, alalazo approved these changes

2021-08-10 17:12 UTC, alalazo requested changes
It seems `cppglob` is still missing?

2021-08-10 20:48 UTC, haampie commented
Yeah, that one was supposed to be removed in another commit, but then github had an outage :D

2021-08-11 07:25 UTC, alalazo approved these changes

2021-08-11 08:14 UTC, merged