New package: r-questionr
LLNL/spack pull request #25395
Opened 2021-08-12 17:48 UTC by qwertos

2021-08-16 17:57 UTC, glennpj requested changes

2021-08-16 17:57 UTC, glennpj commented on var/spack/repos/builtin/packages/r-questionr/package.py
> +
Need a `list_url`

2021-09-07 22:27 UTC, glennpj commented
@alalazo I actually had already reviewed this PR, and requested changes. I should also note here that this is dependent on #25399.

2021-09-08 11:06 UTC, alalazo commented
You're right @glennpj  I didn't notice the request was not addressed.

2021-09-08 14:16 UTC, qwertos commented
list_url is there now. Forgot to hit resolve thread.

2021-09-26 04:19 UTC, glennpj submitted a review, later dismissed

2021-09-27 02:35 UTC, glennpj approved these changes

2021-09-27 02:35 UTC, merged