buildcache: Add environment-aware buildcache sync command
LLNL/spack pull request #25470
Opened 2021-08-17 22:17 UTC by scottwittenburg

Add a new buildcache sub-command that copies files from a source mirror to a destination.  Requires an active environment and only copies files corresponding to specs in the environment.

2021-08-17 22:20 UTC, scottwittenburg commented
@tgamblin This is part of my plan for PR binary graduation.  So I'll find the latest pipeline for each PR, and then for each of the generate jobs in that pipeline, I'll fetch the `spack.lock` (the worker runs on a docker image with spack installed), activate the environment, and then run this new command.

2021-08-18 18:46 UTC, opadron requested changes

2021-08-18 18:46 UTC, opadron commented on lib/spack/spack/cmd/buildcache.py
> +    dest_mirror_url = args.dest_mirror
This should also accept the names of pre-configured mirrors.  See `_createtarball` for an example of how this is done.

2021-08-19 18:13 UTC, opadron approved these changes

2021-08-19 18:15 UTC, merged