Updates to Exawind packages
LLNL/spack pull request #25568
Opened 2021-08-23 16:41 UTC by psakievich

These are a bunch of updates for packages in the Exawind software stack. @jrood-nrel @eugeneswalker

2021-08-23 16:54 UTC, jrood-nrel submitted a review, later dismissed
I helped make a lot of these changes so I approve.

2021-08-24 16:38 UTC, jrood-nrel submitted a review, later dismissed

2021-08-24 16:40 UTC, eugeneswalker submitted a review, later dismissed
Thanks!

2021-08-25 15:32 UTC, eugeneswalker approved these changes, later dismissed

2021-08-25 15:34 UTC, jrood-nrel commented on var/spack/repos/builtin/packages/amr-wind/package.py
> +        if '+mpi' in self.spec:
We actually need to delete this block. This causes problems on Summit.

2021-08-27 15:02 UTC, psakievich commented on var/spack/repos/builtin/packages/amr-wind/package.py
> +        if '+mpi' in self.spec:
Done

2021-08-27 15:56 UTC, jrood-nrel submitted a review, later dismissed

2021-08-27 18:53 UTC, eugeneswalker submitted a review, later dismissed

2021-08-27 18:55 UTC, jrood-nrel submitted a review, later dismissed

2021-08-27 23:02 UTC, eugeneswalker submitted a review, later dismissed

2021-08-27 23:37 UTC, jsitaraman submitted a review, later dismissed

2021-08-30 08:07 UTC, alalazo requested changes
Only a very minor request.

2021-08-30 08:07 UTC, alalazo commented on var/spack/repos/builtin/packages/nccmp/package.py
> +        return args
This can be removed

2021-08-30 14:04 UTC, psakievich commented on var/spack/repos/builtin/packages/nccmp/package.py
> +        return args
Ah yeah. 🤦‍♂️ thanks!

2021-08-30 15:08 UTC, psakievich commented
@alalazo requested changes made

2021-08-30 15:11 UTC, alalazo approved these changes

2021-08-30 15:22 UTC, merged