SCALE: New package
LLNL/spack pull request #25574
Opened 2021-08-24 02:08 UTC by t-yamaura

SCALE (Scalable Computing for Advanced Library and Environment) is a basic library for weather and climate model of the earth and planets aimed to be widely used in various models.

2021-08-27 17:17 UTC, scheibelp reviewed
I have one suggested change but overall this looks good. If you prefer not to change the package, I'm OK with merging it .

2021-08-27 17:17 UTC, scheibelp commented on var/spack/repos/builtin/packages/scale/package.py
> +                                  stdout=subprocess.PIPE).communicate()[0]
(suggested change, not required) FYI Spack provides a `which` command which returns an `Executable` object which provides some convenience methods:

```
                nc_config = which('Rscript')
                nc_str = nc_config('--libs', '--flibs', output=str)
```

2021-08-27 17:17 UTC, scheibelp commented on var/spack/repos/builtin/packages/scale/package.py
> +            scale_sys_str = 'MacOSX-gnu-ompi'
(no change required) Right now, this is probably the easiest way to constrain the build. We also have a `conflicts` directive, but it wouldn't be useful in this case since there are many cases where this doesn't work and `conflicts` would require you to enumerate all of them.

2021-08-28 03:01 UTC, tkameyama commented on var/spack/repos/builtin/packages/scale/package.py
> +# Copyright 2013-2020 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
```

2021-08-30 06:24 UTC, t-yamaura commented
Thank you for suggestions and comments. As following your suggestion, I fixed the calling method for external program.

2021-10-23 14:07 UTC, tkameyama requested changes

2021-10-23 14:07 UTC, tkameyama commented on var/spack/repos/builtin/packages/scale/package.py
> +    depends_on('openmpi', type=('build', 'link', 'run'))
```suggestion
    depends_on('mpi@2:', type=('build', 'link', 'run'))
```

2021-10-23 14:07 UTC, tkameyama commented on var/spack/repos/builtin/packages/scale/package.py
> +    patch('fj-own_compiler.patch', when='%fj')
If you want to change compiler name, we can create edit method and use filter_file.

2021-10-23 14:07 UTC, tkameyama commented on var/spack/repos/builtin/packages/scale/package.py
> +            scale_sys_str = 'Linux64-gnu-ompi'
```suggestion
        if self.spec.satisfies('platform=linux %gcc ^openmpi'):
            scale_sys_str = 'Linux64-gnu-ompi'
```
If Makedefs.* include openmpi specific configuration, we need to ladd dependency condition.

2021-10-23 14:07 UTC, tkameyama commented on var/spack/repos/builtin/packages/scale/package.py
> +        env['SCALE_SYS'] = scale_sys_str
You want to set environment variables, you should write in `setup_build_environment`.

2021-11-05 17:56 UTC, scheibelp commented
Hi @t-yamaura this looks good to me, but do you have time to make some of the suggested changes in https://github.com/spack/spack/pull/25574#discussion_r734971504?

If not, I can merge this.

(also, I'm closing/reopening to re-run the CI)

2021-11-08 05:06 UTC, t-yamaura commented
@scheibelp I have considered modifying the comments I have received, but this will likely take some time. So, I would like to respond to the above comments in a future update. Could you please merge them once?

2021-11-08 18:00 UTC, scheibelp commented on var/spack/repos/builtin/packages/scale/package.py
> +        make('install')
This looks good but I have one question: You call `install_tree` below, so is this needed?

Usually `make install` doesn't build anything and just copies files, and it chooses a default location if one isn't specified; usually this can be adjusted by setting an environment variable like `PREFIX` (see `spack edit bowtie2` for an example of using `def install_targets` to set this).

2021-11-09 07:41 UTC, t-yamaura commented on var/spack/repos/builtin/packages/scale/package.py
> +        make('install')
Yes, it is required. I tried a few other methods, but they did not work.
It seems that due to the current SCALE specification, it is necessary to include such a trick to install with Spack.

2021-11-09 08:17 UTC, scheibelp commented on var/spack/repos/builtin/packages/scale/package.py
> +        make('install')
Got it - thanks for checking! This all looks good then

2021-11-09 08:17 UTC, scheibelp approved these changes

2021-11-09 08:19 UTC, merged