add 'develop' branch to cmake package
LLNL/spack pull request #25623
Opened 2021-08-26 13:23 UTC by germasch

And also add the latest release 3.21.2, while I was at it.

Obviously, the `develop` branch is a moving target, but it's still useful if one wants to try out the latest and greatest -- and the latest release remains the preferred version, so it doesn't interfere unless one explicitly asks for `@develop`.

@chuckatkins

2021-08-26 13:47 UTC, haampie requested changes

2021-08-26 13:47 UTC, haampie commented on var/spack/repos/builtin/packages/cmake/package.py
> +    version('develop',  branch='master')
```suggestion
    version('master',  branch='master')
```

2021-08-26 14:16 UTC, germasch commented on var/spack/repos/builtin/packages/cmake/package.py
> +    version('develop',  branch='master')
I had named it `develop` since I had come across this yesterday:
```
        # NOTE: When COMPARING VERSIONS, the '@develop' version is always
        #       larger than other versions.  BUT when CONCRETIZING,
        #       the largest NON-develop version is selected by default.
```
But looking at the code further, I see that not only `@develop` is special-cased, but also
```
infinity_versions = ['develop', 'main', 'master', 'head', 'trunk']
```
so I'm more than happy to change this. Thanks!

2021-08-28 15:52 UTC, germasch commented
@haampie I accepted your change (gentle reminder ;) )

2021-08-28 16:42 UTC, haampie approved these changes

2021-08-28 16:42 UTC, merged