kahip: update build system to cmake for v3.11, retain scons for older versions
LLNL/spack pull request #25645
Opened 2021-08-26 20:00 UTC by ma595

2021-10-01 19:07 UTC, tgamblin commented
@adamjstewart: this is a multi-build-system package -- just want to make sure it looks ok to you.

2021-10-01 19:07 UTC, tgamblin requested changes, later dismissed
No major requests -- just one note on the `git` URL.

2021-10-01 19:07 UTC, tgamblin commented on var/spack/repos/builtin/packages/kahip/package.py
>      git       = 'https://github.com/schulzchristian/KaHIP.git'
Should this be updated to match the `github` repo above, as well?

2021-10-09 10:25 UTC, ma595 commented on var/spack/repos/builtin/packages/kahip/package.py
>      git       = 'https://github.com/schulzchristian/KaHIP.git'
amended git url as suggested

2021-10-09 16:42 UTC, adamjstewart requested changes

2021-10-09 16:42 UTC, adamjstewart commented on var/spack/repos/builtin/packages/kahip/package.py
> +    @when("@:2.11")
Should these be 2.10 instead? The CMake build system was added in 2.11.

2021-10-09 16:42 UTC, adamjstewart commented on var/spack/repos/builtin/packages/kahip/package.py
>      version('2.00', sha256='1cc9e5b12fea559288d377e8b8b701af1b2b707de8e550d0bda18b36be29d21d')
This release isn't available on GitHub, can you add a `url='...'` to this version? Should we deprecate this version?

2021-10-09 16:42 UTC, adamjstewart commented on var/spack/repos/builtin/packages/kahip/package.py
> +    depends_on('scons @3.1.2 ', type='build', when='@2:2.11')
The package doesn't mention any specific required version of scons, I would remove `@3.1.2`

2021-10-10 17:29 UTC, ma595 commented on var/spack/repos/builtin/packages/kahip/package.py
> +    @when("@:2.11")
You are correct. This change has been made.

2021-10-10 17:30 UTC, ma595 commented on var/spack/repos/builtin/packages/kahip/package.py
>      version('2.00', sha256='1cc9e5b12fea559288d377e8b8b701af1b2b707de8e550d0bda18b36be29d21d')
Do you mean v2.00? I've added a URL and deprecated=True

2021-10-10 17:30 UTC, ma595 commented on var/spack/repos/builtin/packages/kahip/package.py
> +    depends_on('scons @3.1.2 ', type='build', when='@2:2.11')
Removed

2021-10-10 22:16 UTC, adamjstewart submitted a review, later dismissed

2021-10-10 22:17 UTC, adamjstewart commented
It looks like there's a merge conflict (the kahip package must have been updated since you branched off of develop). Can you resolve the merge conflicts (either through the GitHub GUI or CLI)?

2021-10-11 14:10 UTC, adamjstewart approved these changes

2021-10-11 15:20 UTC, merged