Add new symlinks for the amdclang,amdclang++ inside llvm-amdgpu package
LLNL/spack pull request #25652
Opened 2021-08-27 04:33 UTC by srekolam

from rocm-4.3.0 onwards, we have a new binary executable amdclang/amdclang++/amdflang etc . Since these were in a same /bin folder as with clang/clang++/flang, it was required to create a new symlinks in a separate /bin folder and have it link to original executable. 
I have made the changes to add a prefix path /llvm and created /bin and llvm-alt in the install prefix path for llvm-amdgpu package. 
I have verified the rocm packages for 4.3.0 and 4.2.0 . I am currently seeing a build issue with rocblas because of which 6 other packages are not verified (hipblas,rocsolver,rocalution,migraphx,rocm-validation-suite,rocm-openmp-extras) All other packages were able to build successfully. 

After this change, we need to add a new optional variant for closed source binary (A+A ) and have it symlinked through llvm-alt.

@arjun-raj-kuppala  and @haampie  , while trying to analyse the failure of rocblas, one thing that i noticed is in the cmakecache.txt for rocblas, for the CMAKE_INSTALL_RPATH i did not see the path for prefix for llvm-amdgpu/llvm/lib .. Not sure if this is causing the failure. though i added rpath etc for llvm-amdgpu package, it did not help. 
I did try with few things but did not work so far. So, any inputs

2021-08-27 08:35 UTC, haampie requested changes

2021-08-27 08:35 UTC, haampie commented on var/spack/repos/builtin/packages/llvm-amdgpu/package.py
> +            args.append("-DCMAKE_INSTALL_PREFIX:PATH={0}".
Do you really need to modify the install prefix entirely? I thought you mentioned it was just about adding some proprietary executables, and symlinking them, keeping everything else in-place?

Moving the install prefix to a subdirectory of spack's install prefix is not a good idea, since as you noted, you have to set the CMAKE_PREFIX_PATH on *every* dependent package, and we really shouldn't do that. Also, indeed, rpaths will not be setup correctly.

Also, can't you make it so that if you don't have the proprietary compilers, nothing changes for the user at all?

2021-08-27 14:35 UTC, srekolam commented on var/spack/repos/builtin/packages/llvm-amdgpu/package.py
> +            args.append("-DCMAKE_INSTALL_PREFIX:PATH={0}".
In the build scripts for the llvm-amdgpu for the /opt/rocm installation, the install prefix path is given as /opt/rocm/llvm, and the symlinks for the amdclang/amdclang++/amdflang executables are created inside the /opt/rocm/bin folder.  
For the spack too, as i did not have the /opt/rocm/bin, i added the install prefix path llvm and created the /bin that contain the symlinks only and maintained similar structure. 
The other way i thought was to rename the original /bin into llvm but that would mean changing the cmakelists.txt and i was not sure of it. i did talk to compiler team and took the first approach.

2021-08-27 17:42 UTC, srekolam commented
[rocblas_CMakeCache.txt](https://github.com/spack/spack/files/7068682/rocblas_CMakeCache.txt)
[rocblas_build_out.txt](https://github.com/spack/spack/files/7068683/rocblas_build_out.txt)
Attached is the error i am seeing with regard to the rocblas and as i noted, the cmake_cache.txt for rocblas, does not seem to add the new prefix_path for llvm-amdgpu package to the CMAKE_INSTALL_RPATH

2023-02-20 14:39 UTC, alalazo commented
Given the amount of conflicts and the fact that this PR has been stale for a long time, I'll be closing this. Feel free to reopen if you disagree and want to continue working on it.

2023-02-20 14:39 UTC, closed without merging