[py-plotly] added version 5.2.2
LLNL/spack pull request #25668
Opened 2021-08-27 19:01 UTC by qwertos

2021-08-27 20:34 UTC, adamjstewart requested changes

2021-08-27 20:34 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-plotly/package.py
> +    depends_on('py-requests',   type=('build', 'run'))
This is no longer required in the latest release

2021-08-27 20:46 UTC, qwertos commented on var/spack/repos/builtin/packages/py-plotly/package.py
> +    depends_on('py-requests',   type=('build', 'run'))
It's not listed in `install_requires` but `import requests` does show up in `setup.py`

2021-08-27 20:48 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-plotly/package.py
> +    depends_on('py-requests',   type=('build', 'run'))
Are those run when you install the package or only when installing from a git branch? I see they use lazy imports for most of those. Npm is also required when building from git I think.

2021-08-30 20:59 UTC, qwertos commented on var/spack/repos/builtin/packages/py-plotly/package.py
> +    depends_on('py-requests',   type=('build', 'run'))
just tested without it and it installed fine. removed.

2021-08-30 21:15 UTC, adamjstewart approved these changes

2021-08-30 21:15 UTC, merged