Update ExaGO to use slim petsc build
LLNL/spack pull request #25706
Opened 2021-08-30 22:40 UTC by ashermancinelli

Update ExaGO to use slim petsc build, add myself and CameronRutherford as maintainers.

2021-08-30 23:25 UTC, CameronRutherford approved these changes
LGTM

2021-09-06 14:10 UTC, alalazo requested changes
Just a doubt on whether `petsc~hypre~hdf5~metis~superlu-dist` is a preference or a requirement for this software. If it is a preference it shouldn't be expressed in a `depends_on` but in `packages.yaml`.

2021-09-06 14:10 UTC, alalazo commented on var/spack/repos/builtin/packages/exago/package.py
> +    depends_on('petsc@3.13:3.14~hypre~hdf5~metis~superlu-dist', when='+petsc')
Does this mean that I can't use at all `petsc+hypre` to build this package?

2021-09-07 01:30 UTC, ashermancinelli commented
@alalazo You're right, this is a preference. We can just use the packages.yaml for this.

2021-09-07 01:30 UTC, closed without merging

2021-09-07 06:26 UTC, alalazo commented
Thanks for the quick reply