Add py-pot with patch
LLNL/spack pull request #25712
Opened 2021-08-31 11:06 UTC by haampie

2021-09-08 20:28 UTC, bernhardkaindl approved these changes, later dismissed

2021-09-13 12:17 UTC, alalazo approved these changes

2021-09-13 12:20 UTC, alalazo requested changes
Basically LGTM. Only a minor request to rephrase a comment.

2021-09-13 12:20 UTC, alalazo commented on var/spack/repos/builtin/packages/py-pot/package.py
> +    # They're setting CC env variables :/
Can you rephrase this comment and briefly explain when CC is removed / added ?

2021-09-14 13:02 UTC, alalazo approved these changes

2021-09-14 13:03 UTC, alalazo commented
@spackbot run pipeline

2021-09-14 13:55 UTC, merged