Add systemc
LLNL/spack pull request #25761
Opened 2021-09-02 18:11 UTC by nicmcd

2021-09-03 08:28 UTC, alalazo approved these changes

2021-09-03 08:29 UTC, alalazo requested changes
There are style issues:
```
==> Error: spack style found errors
  var/spack/repos/builtin/packages/systemc/package.py:10: [E501] line too long (93 > 88 characters)
  var/spack/repos/builtin/packages/systemc/package.py:23: [E111] indentation is not a multiple of four
  var/spack/repos/builtin/packages/systemc/package.py:24: [E111] indentation is not a multiple of four
  var/spack/repos/builtin/packages/systemc/package.py:25: [E121] continuation line under-indented for hanging indent
```

2021-09-03 19:48 UTC, nicmcd commented
@alalazo, all good now?

2021-09-06 12:58 UTC, alalazo requested changes
Two minor style requests, but basically LGTM.

2021-09-06 12:58 UTC, alalazo commented on var/spack/repos/builtin/packages/systemc/package.py
> +                             'fa1f3086b1f7b3f'))
Please don't split the sha (we don't do it in any package).

2021-09-06 12:58 UTC, alalazo commented on var/spack/repos/builtin/packages/systemc/package.py
> +                "systemc-2.3.3.tar.gz")
Also the url are usually on the same line

2021-09-07 20:27 UTC, nicmcd commented
@alalazo done, PTAL

2021-09-08 12:00 UTC, alalazo commented
@spackbot run pipeline

2021-09-08 12:00 UTC, alalazo approved these changes

2021-09-08 13:08 UTC, merged