Add package Garfield++ (garfieldpp)
LLNL/spack pull request #25800
Opened 2021-09-06 02:53 UTC by mirguest

Garfield++ is used to simulate the ionisation measurement in gases and semiconductors. 

Tao Lin

2021-09-06 10:37 UTC, alalazo requested changes

2021-09-06 10:37 UTC, alalazo commented on var/spack/repos/builtin/packages/garfieldpp/package.py
> +        return args
You can remove this method.

2021-09-06 12:27 UTC, mirguest commented on var/spack/repos/builtin/packages/garfieldpp/package.py
> +        return args
Done. Thanks.

2021-09-06 12:40 UTC, alalazo submitted a review, later dismissed

2021-09-06 13:10 UTC, vvolkl commented on var/spack/repos/builtin/packages/garfieldpp/package.py
> +
```suggestion

    tags = ['hep']

    maintainers = ['mirguest']

```

2021-09-06 15:47 UTC, mirguest commented
Hi @alalazo ,
Could you help me merge this PR? Thank you very much!
Tao Lin

2021-09-07 06:15 UTC, alalazo approved these changes

2021-09-07 06:16 UTC, merged