New packages for openCARP
LLNL/spack pull request #25909
Opened 2021-09-13 10:13 UTC by MarieHouillon

Three packages are created in this pull request, all part of the [openCARP](https://opencarp.org) ecosystem.

- opencarp
- py-carputils
- meshtool

The openCARP simulation software is an open cardiac electrophysiology simulator for in-silico experiments.
Meshtool is a utility for mesh manipulation.
carputils is a Python framework to encode in silico experiments including pre- and postprocessing and run them with the openCARP simulator.

2021-09-13 19:20 UTC, tldahlgren requested changes

2021-09-13 19:20 UTC, tldahlgren commented on var/spack/repos/builtin/packages/meshtool/package.py
> +# Copyright 2013-2020 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
```

2021-09-13 19:20 UTC, tldahlgren commented on var/spack/repos/builtin/packages/opencarp/package.py
> +    # notify when the package is updated.
```suggestion
```

2021-09-13 19:20 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-carputils/package.py
> +# Copyright 2013-2020 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
```

2021-09-23 16:45 UTC, tgamblin commented
@tldahlgren is this one looking good to you?

2021-09-23 18:39 UTC, tldahlgren requested changes
I am, unfortunately, not able to test this package due to connection resets related to `qhull`, which is a dependency of `py-matplotlib`.

2021-09-23 18:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/opencarp/package.py
> +            settings_prefix = os.path.expanduser('~/.config/carputils')
```suggestion
            settings_prefix = os.path.expanduser(join_path('~', '.config', 'carputils'))
```

2021-09-23 18:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/opencarp/package.py
> +        return args
Since it's a `CMakePackage`, you could use `self.define()`.  Given the values are `ON`, are the types for the two options `STRING` or `BOOL`?  If the latter, you could:

```suggestion
        return [
            self.define('DLOPEN', True),
            self.define('SPACK_BUILD', True)
        ]
```

And `self.define()` will translate them to

```
        return [
            "-DDLOPEN:BOOL=ON",
            "-DSPACK_BUILD:BOOL=ON")
        ]
```

If you need 'STRING', then you could do the following:

```
        return [
            self.define('DLOPEN', 'ON'),
            self.define('SPACK_BUILD', 'ON')
        ]
```

2021-09-23 18:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/opencarp/package.py
> +            settings_file = os.path.join(settings_prefix, 'settings.yaml')
```suggestion
            settings_file = join_path(settings_prefix, 'settings.yaml')
```

2021-09-23 18:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/opencarp/package.py
> +                          os.path.join(
```suggestion
                          join_path(
```

2021-09-23 18:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/opencarp/package.py
> +                      + ' --flavor petsc --software-root ' + self.prefix.bin)
```suggestion
            cusettings = Executable('cusettings')
            cusettings(settings_file, '--flavor', 'petsc',
                '--software-root', self.prefix.bin)
```

2021-09-27 18:21 UTC, tldahlgren approved these changes

2021-09-27 18:21 UTC, merged