Fix mesa package: Add missing libunwind dependency
LLNL/spack pull request #25913
Opened 2021-09-13 14:51 UTC by tgymnich

There is currently a build error when building mesa without libunwind installed.
This adds a +libunwind variant.

2021-09-13 16:11 UTC, mwkrentel commented
@tgymnich libunwind definitely supports aarch64.  For my project
(hpctoolkit), we use libunwind as our primary and only unwinder for
aarch64.  We find it quite satisfactory.

I'm pretty sure it also supports arm (32-bit), but we don't
support arm, so I can't say for sure.

2021-09-13 16:26 UTC, mwkrentel commented
Also, I don't believe `%arm` is correct syntax for spack.  `%` denotes
a compiler.  For arch type, you should use target as in `target=arm`
or actually, `target=arm:` to include arm and anything derived from arm.

But as I said, I believe both conflicts are unnecessary.

2021-09-13 17:41 UTC, tgymnich commented on var/spack/repos/builtin/packages/mesa/package.py
> -        if spec.target.family == 'arm' or spec.target.family == 'aarch64':
@mwkrentel this line made me exclude arm and aarch64. Unfortunately I don't know the exact reasoning behind this line.

2021-09-13 17:42 UTC, tgymnich commented
> Also, I don't believe `%arm` is correct syntax for spack. `%` denotes
> a compiler. For arch type, you should use target as in `target=arm`
> or actually, `target=arm:` to include arm and anything derived from arm.
> 
> But as I said, I believe both conflicts are unnecessary.

fixed it thanks for the hint.

2021-09-14 06:08 UTC, mwkrentel commented
@tgymnich The logic of your patch escapes me.  You removed the
conflict for libunwind and aarch64, but you kept the if() to disable
libunwind for aarch64.

I'm not really familiar with meson build, but I would think that you
want something like:

```
if '+libunwind' in spec:
    # add spec['libunwind'].prefix to the build
else:
    # disable libunwind
```

Anyway, all I really wanted to say was that libunwind supports aarch64
and arm.  I (hpctoolkit) personally use it for aarch64 and I'm pretty
sure it also works on arm.  Long ago, aarch64 and arm were not supported,
but today they are.

2021-09-14 06:49 UTC, alalazo requested changes

2021-09-14 06:49 UTC, alalazo commented on var/spack/repos/builtin/packages/mesa/package.py
> +        if (spec.target.family == 'arm' or spec.target.family == 'aarch64' or
I think this is overly complicated. You can:
```python
unwind_args = 'enable' if '+libunwind' in spec else 'disable'
args.append('-Dlibunwind={0}'.format(unwind_args))
```

2022-08-22 12:07 UTC, alalazo commented
@kwryankrattiger Can you review these changes? @tgymnich Can you please rebase the PR?

2022-08-22 19:18 UTC, kwryankrattiger approved these changes
Much better with the conflicts!

2022-08-23 06:26 UTC, alalazo commented
@spackbot fix style

2022-08-23 07:12 UTC, alalazo commented
@spackbot fix style

2022-08-23 15:07 UTC, alalazo requested changes

2022-08-23 15:07 UTC, alalazo commented on var/spack/repos/builtin/packages/mesa/package.py
> +    depends_on("unwind", when="+libunwind")
There's a dependency on `unwind` at line 5-. The variant `libunwind` doesn't seem to be defined at all.

2023-11-19 00:17 UTC, alecbcs commented
@tgymnich did you get a chance to take a look at the review feedback. Is this PR still something you'd like to pursue?

2023-11-21 13:35 UTC, tgymnich commented
I quickly tried to reproduce the issue and ran into this: https://github.com/spack/spack/issues/41197

2023-11-22 02:26 UTC, closed without merging