add mantainer
LLNL/spack pull request #25959
Opened 2021-09-15 08:29 UTC by jacorvar

2021-09-15 23:20 UTC, tldahlgren commented on var/spack/repos/builtin/packages/bedops/package.py
> +
Style error is complaining about whitespace.  The following should fix it:

```suggestion

```

2021-09-15 23:22 UTC, tldahlgren commented
@erimar77 @alecbcs As prior contributors to the package, do you also want to be added as maintainers?

2021-09-15 23:24 UTC, tldahlgren requested changes
See prior comment about the style error.

2021-09-21 18:39 UTC, tldahlgren commented
@jacorvar Please resolve the file conflicts.

2021-09-22 08:15 UTC, jacorvar reviewed
I've just changed it.

2021-09-27 18:11 UTC, tldahlgren commented on var/spack/repos/builtin/packages/bedops/package.py
> +    version('2.4.40', sha256='0670f9ce2da4b68ab13f82c023c84509c7fce5aeb5df980c385fac76eabed4fb')
This is an invalid sha256 BUT #26141 has already been merged and it contains the maintainer and correct sha256 for this version.

2021-09-27 18:12 UTC, tldahlgren commented
Closing since these changes appear in a PR (#26141) that has already been merged.

2021-09-27 18:12 UTC, closed without merging