fontconfig: add dependency python
LLNL/spack pull request #25960
Opened 2021-09-15 08:35 UTC by kjrstory

Fontconfig needs Python, but it was missing as dependency.

2021-09-15 23:13 UTC, tldahlgren commented
@spackbot run pipeline

2021-09-16 11:06 UTC, sethrj requested changes

2021-09-16 11:06 UTC, sethrj commented on var/spack/repos/builtin/packages/fontconfig/package.py
> +    depends_on('python', type='build')
From the commit history python is only needed in `2.13.93` so this needs a `when` restriction. It also requires Python 3+.
```suggestion
    depends_on('python@3:', type='build', when='@2.13.93:')
```

2021-09-23 10:59 UTC, sethrj approved these changes
Thanks!

2021-09-24 01:39 UTC, sethrj commented
@spackbot re-run pipeline

2021-09-24 05:26 UTC, merged