Generalize mesa-demos to depend on OpenGL instead of mesa
LLNL/spack pull request #25976
Opened 2021-09-15 18:21 UTC by stephencrowell

2021-09-15 18:59 UTC, chuckatkins requested changes

2021-09-15 18:59 UTC, chuckatkins commented on var/spack/repos/builtin/packages/mesa-demos/package.py
> +    url      = "https://github.com/freedesktop/mesa-demos/archive/mesa-demos-8.3.0.tar.gz" # Should this be from free desktop gitlab?
I think this is fine to leave on gh.  Just drop the associated comment.

2021-09-15 18:59 UTC, chuckatkins commented on var/spack/repos/builtin/packages/mesa-demos/package.py
> +    url      = "https://github.com/freedesktop/mesa-demos/archive/mesa-demos-8.3.0.tar.gz"  # Should this be from free desktop gitlab?
Development is essentially halted so it's last home of GH is probably correct so the comment can be dropped.

2021-09-15 18:59 UTC, chuckatkins commented on var/spack/repos/builtin/packages/mesa-demos/package.py
> +    variant('glx', default=is_linux, description="Enable the GLX frontend.")
:+1:

2021-09-15 18:59 UTC, chuckatkins commented on var/spack/repos/builtin/packages/mesa-demos/package.py
>      depends_on('freeglut')
We can drop the freetype dependency

2021-09-15 18:59 UTC, chuckatkins commented on var/spack/repos/builtin/packages/mesa-demos/package.py
> +    depends_on('glx', when='+glx')
I believe there is also a dependency on `libx11` and `libxext` when `+glx` is enabled

2021-09-17 15:11 UTC, chuckatkins approved these changes, later dismissed

2021-09-21 15:06 UTC, chuckatkins commented
@scottwittenburg looks like the e4s cleanup job is failing.  Anything to be done on our end here?

2021-09-21 15:17 UTC, scottwittenburg commented
> @scottwittenburg looks like the e4s cleanup job is failing. Anything to be done on our end here?

We rotate the access credentials used for writing to the S3 buckets, so while I'm not sure, my hypothesis is that particular job was waiting long enough to run that the credentials expired out from under it.  If we ask spackbot to rerun, the pipeline should be provided the latest credentials and hopefully the same thing doesn't happen again.  Things have been slow in gitlab due to the `e4s-pr-generate` job generating more jobs than needed (in turn due to a bug keeping that mirror index from getting updated).

2021-09-21 15:17 UTC, scottwittenburg commented
@spackbot run pipeline

2021-09-22 16:17 UTC, chuckatkins commented
@spackbot run pipeline

2021-09-22 18:11 UTC, chuckatkins commented
@scottwittenburg Looks like the e4s pipeline is still having issues, this time in generate:
```
ERROR: Job failed (system failure): error dialing backend: dial tcp 192.168.49.125:10250: connect: connection refused
```

2021-09-22 18:48 UTC, chuckatkins approved these changes, later dismissed

2021-10-20 17:32 UTC, luigi-calori commented
First, thanks a lot for fixing opengl package version range, it is useful also for other opengl based packages such as paraview
Furthermore, I would suggest to get rid of mesa-glu dependency as well and substituting with 
depends_on('glu')
In that case, the same thing that has been done on opengl recipe must be done on openglu package.py

2024-07-08 07:50 UTC, alalazo commented
@stephencrowell Are you still interested in this PR? (I'm going through old PRs, and saw this one was set to be merged automatically, but wasn't merged in the end)

2024-11-26 06:08 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2024-11-26 06:08 UTC, closed without merging