New Package: EcoSLIM
LLNL/spack pull request #25975
Opened 2021-09-15 17:30 UTC by smithsg84

Requesting EcoSLIM particle code package addition.

2021-09-15 22:55 UTC, tldahlgren requested changes
A few questions/comments based on current contents (and assuming you didn't mean to make this a `draft` PR :grin:).

2021-09-15 22:55 UTC, tldahlgren commented on var/spack/repos/builtin/packages/ecoslim/package.py
> +        return cmake_args
Are you sure you don't want/need any `cmake_args`?  If so, change these lines to the following:

```suggestion
        return []
```

2021-09-15 22:55 UTC, tldahlgren commented on var/spack/repos/builtin/packages/ecoslim/package.py
> +    git      = "git@github.com:reedmaxwell/EcoSLIM.git"
For consistency with nearly all other Spack packages:

```suggestion
    git      = "https://github.com/reedmaxwell/EcoSLIM.git"
```

2021-09-15 22:55 UTC, tldahlgren commented on var/spack/repos/builtin/packages/ecoslim/package.py
> +    version('develop', branch='develop')
The software doesn't have a `develop` branch.  Do you mean `master`?

```suggestion
    version('master', branch='master')
```

2021-09-15 22:58 UTC, tldahlgren commented
I also confirmed the sha256 for v1.3 (using `spack checksum`).

2021-09-21 18:32 UTC, tldahlgren commented on var/spack/repos/builtin/packages/ecoslim/package.py
> +class Ecoslim(CMakePackage):
```suggestion

class Ecoslim(CMakePackage):
```

2021-09-21 18:32 UTC, tldahlgren requested changes

2021-09-21 18:32 UTC, tldahlgren commented on var/spack/repos/builtin/packages/ecoslim/package.py
> +
```suggestion
```

2021-09-21 18:33 UTC, tldahlgren commented
@smithsg84 Hope you don't mind that  I committed the two simple fixes reported by the style checker.

2021-09-21 18:53 UTC, smithsg84 commented
> @smithsg84 Hope you don't mind that I committed the two simple fixes reported by the style checker.

Sorry I forgot about the spack style command.

2021-09-27 17:38 UTC, tldahlgren approved these changes

2021-09-27 17:38 UTC, merged