Fix ONNX python version in environments
LLNL/spack pull request #26131
Opened 2021-09-21 23:01 UTC by bvanessen

When using the ONNX package inside of an environment that specifies a
python3 executable, it will attempt to use a system installed
version.  This can lead to a failure where the system python and the
environment python don't agree and the system python ends up with an
invalid environment.  Forces ONNX to use the same version of python as
the rest of the spec.

Adds hashes for the latest version of ONNX.

2021-09-21 23:01 UTC, bvanessen commented
@becker33 Here is the patch for what we were discussing

2021-09-22 00:47 UTC, becker33 approved these changes, later dismissed

2021-09-22 20:20 UTC, becker33 requested changes

2021-09-22 20:20 UTC, becker33 commented on var/spack/repos/builtin/packages/onnx/package.py
> +        args = ['-DPY_VERSION={}'.format(self.spec['python'].version.up_to(2))]
This is not python 2.6 compliant. I suggest the following:

```suggestion
        args = ['-DPY_VERSION={0}'.format(self.spec['python'].version.up_to(2))]
```

2021-09-23 00:09 UTC, becker33 approved these changes

2021-09-24 09:11 UTC, alalazo commented
@spackbot run pipeline

2021-09-26 13:48 UTC, merged