feature: new tags command
LLNL/spack pull request #26136
Opened 2021-09-22 03:53 UTC by tldahlgren

Fixes #22938 

This PR adds a `spack tags` command that is focused on outputting registered tags or (available) packages with those tags.

```
$ spack tags --help
usage: spack tags [-h] [tag [tag ...]]

list package tags

positional arguments:
  tag         find packages that provide this tag

optional arguments:
  -h, --help  show this help message and exit

If called without argument returns the list of all unique package tags.

$ spack tags
Unique package tags:
    amr            fem              high-order     neutrino
    build-tools    finite elements  hpc            proxy-app
    cfd            flow             i/o            solver
    ecp            fluid            key4hep        spectral-elements
    ecp-apps       gibbs sampler    mcmc           storage
    ecp-proxy-app  hep              navier-stokes  trace-tools

$ spack tags ecp rcp-apps ecp-proxy-app
ecp:
    axl     lammps     nektools   rankstr   filo              exawind
    chombo  latte      nwchem     redset    spath             nekrs
    er      nalu-wind  parsplice  shuffile  amr-wind          rmgdft
    kvtree  nek5000    qmcpack    veloc     ecp-data-vis-sdk

ecp-apps:
    chombo  latte      nek5000   nwchem     qmcpack   exawind  rmgdft
    lammps  nalu-wind  nektools  parsplice  amr-wind  nekrs

ecp-proxy-app:
    amg                ember      macsio   miniqmc   nekbone     swfft
    candle-benchmarks  examinimd  miniamr  minitri   picsarlite  thornado-mini
    ecp-proxy-apps     laghos     minife   minivite  sw4lite     xsbench

```

TODO
- [ ] Add an option to limit reported tags to those of installed packages

2021-09-24 09:07 UTC, alalazo reviewed
Can we rename the Python package to `spack.tag` instead of `spoack.tag_index` and move in there the logic that is currently in `spack.cmd.tag`? 

In that way we'll make the command a thin wrapper around internal API, and can code more unit-tests avoiding to use `SpackCommand` directly.

I think we also need to remove an option to the `spack list` command that becomes redundant with this PR.

2021-09-24 16:25 UTC, tldahlgren commented
> I think we also need to remove an option to the `spack list` command that becomes redundant with this PR.

Should the option also be removed from `spack find`?

2021-09-30 17:32 UTC, tldahlgren commented
Force re-running checks due to an odd `gpg` error in one.

2021-10-04 09:01 UTC, alalazo commented
@spackbot run pipeline

2021-10-04 17:27 UTC, tldahlgren commented
Note pipeline check fails for E4S stack for a known broken spec:

``Error: Pipeline generation failed due to the presence of the following specs that are known to be broken in develop``

2021-10-04 22:16 UTC, tldahlgren commented
@spackbot run pipeline

2021-10-08 02:11 UTC, tldahlgren commented
> Can we rename the Python package to `spack.tag` instead of `spoack.tag_index` and move in there the logic that is currently in `spack.cmd.tag`?
> 
> In that way we'll make the command a thin wrapper around internal API, and can code more unit-tests avoiding to use `SpackCommand` directly.
> 
> I think we also need to remove an option to the `spack list` command that becomes redundant with this PR.

@alalazo I think I made all of your requested changes.

2021-10-12 22:26 UTC, tldahlgren commented
@alalazo This PR also fixes a problem where the tags cache ends up with multiple entries for the same package under a tag.

2021-10-14 21:54 UTC, tldahlgren commented
@alalazo Are there any more changes you want to this PR?

2021-10-27 10:19 UTC, alalazo requested changes
This basically LGTM. I left a number of comments, mostly minor.

2021-10-27 10:19 UTC, alalazo commented on lib/spack/spack/cmd/tags.py
> +    )
What do you think  about calling this:
```suggestion
    subparser.add_argument(
        '--all', action='store_true', default=False,
        help="show packages for all the available tags"
    )
```
and making it such that either this option or a list of tags can be provided from the command line?

2021-10-27 10:19 UTC, alalazo commented on lib/spack/spack/cmd/tags.py
> +        help="find packages that provide this tag"
Nitpick, for consistency with other help strings:
```suggestion
        help="show packages that provide this tag"
```

2021-10-27 10:19 UTC, alalazo commented on lib/spack/spack/cmd/tags.py
> +description = "list package tags and or their packages"
Just a suggestion (not a request):
```suggestion
description = "show tags and list their packages"
```

2021-10-27 10:19 UTC, alalazo commented on lib/spack/spack/cmd/tags.py
> +    show_packages = args.tag or args.show_packages
Should we intercept if both flags are given and print an error message in that case? Asking since:
```console
$ spack tags -s
[ shows all tags ]
$ spack tags -s ecp
ecp:
    amr-wind  arborx  cabana  chombo            er       filo    kvtree  latte      nek5000  nektools  parsplice  rankstr  rmgdft    spath
    amrex     axl     chai    ecp-data-vis-sdk  exawind  heffte  lammps  nalu-wind  nekrs    nwchem    qmcpack    redset   shuffile
```
seems inconsistent.

2021-10-27 10:19 UTC, alalazo commented on lib/spack/spack/cmd/tags.py
> +            report_tags("Installed", tags)
Minor (I'd say not a request, but would be welcome). Can we improve the output in this particular case :
```console
$ spack tags -i
Installed package tags:
    None
```
? I think:
```console
$ spack tags -i
==> Installed packages have no tag
```
in case we have packages in the DB but without tags and:
```console
$ spack tags -i
==> No installed packages
```
in case we have an empty DB would look slightly better.

2021-10-27 10:19 UTC, alalazo commented on lib/spack/spack/tag.py
> +def get_installed_packages():
I'd be fine with this if it is an underscore function:
```suggestion
def _get_installed_packages():
```
If it is part of the public API, it should probably be reworked and moved into `spack.environment` or `spack.store`?. Rationale for this is that the function does not deal with tags at all, just with environments and installed specs.

2021-10-27 10:19 UTC, alalazo commented on lib/spack/spack/tag.py
> +def get_tag_packages(tags, installed, skip_empty):
What do you think of:
```suggestion
def packages_with_tags(tags, installed, skip_empty):
```
as a name for the function?

2021-10-27 10:19 UTC, alalazo commented on lib/spack/spack/test/cmd/tags.py
> +from spack.spec import Spec
Minor. Can we keep fully qualified imports:
```python
import spack.main
import spack.spec
```
?

2021-10-27 10:19 UTC, alalazo commented on lib/spack/spack/test/cmd/tags.py
> +        assert pkg in out
It's unclear to me what behavior we are testing. Is it just to hit lines of code in `cmd` and increase coverage?

2021-10-27 10:19 UTC, alalazo commented on lib/spack/spack/test/tag.py
> +        all_pkgs = spack.tag.get_tag_packages([], False, skip)
Minor. I know dynamic typing is not the best for these kind of things, but I would be consistent with the docstring:
```suggestion
        all_pkgs = spack.tag.get_tag_packages(None, False, skip)
```

2021-10-27 10:19 UTC, alalazo commented on lib/spack/spack/tag.py
> +    keys = tags or spack.repo.path.tag_index
Should we be more defensive here:
```suggestion
    keys = spack.repo.path.tag_index if tags is None else tags
```
? Asking this as a question since on the one hand I like the `or` idiom but on the other I can see the API behaving the opposite of what would be expected if we happen to call this function with an empty list. Think for instance if the list is constructed during a script and ends up being empty.

2021-10-28 19:10 UTC, tldahlgren commented on lib/spack/spack/test/cmd/tags.py
> +        assert pkg in out
Basically.  I realize two cases aren't needed so can remove.

2021-10-28 19:12 UTC, tldahlgren commented on lib/spack/spack/tag.py
> +    keys = tags or spack.repo.path.tag_index
🤔

2021-10-28 19:24 UTC, alalazo commented on lib/spack/spack/tag.py
> +    keys = tags or spack.repo.path.tag_index
The case I have in mind here is:
```python
# Assume this is the result of a computation and is empty
tags = []
result = get_tag_packages(tags, installed=False, skip_empty=True)
```
`result` will contain all the tags, while I assume the client expects it to be empty. It is also inconsistent with the documentation:
```
tags (list or None): list of tags of interest or None for all
```
because `None` is different from the empty list (but still false-ish)

2021-10-28 19:33 UTC, tldahlgren commented on lib/spack/spack/tag.py
> +    keys = tags or spack.repo.path.tag_index
You're absolutely right.  (I was side-tracked by something else so am now getting back to this.)

2021-10-28 20:23 UTC, tldahlgren commented on lib/spack/spack/cmd/tags.py
> +    )
IIRC I was having sub parser problems with mutual exclusion but will give it another try.

2021-10-28 20:29 UTC, tldahlgren commented on lib/spack/spack/cmd/tags.py
> +            report_tags("Installed", tags)
I was following the `spack info` precedent but can switch.

2021-10-28 21:49 UTC, RikkiButler20 commented
Could you update the documentation under Command Reference

2021-10-28 22:58 UTC, tldahlgren commented on lib/spack/spack/cmd/tags.py
> +    )
I don't appear (Python 3.7?) to be able to have the packages option mutually exclusive with the positional tag arguments *unless* I'm willing to support only a single tag and that was not the intention.

2021-10-29 02:32 UTC, tldahlgren commented
@alalazo I had problems rebasing that resulted in skipping a commit so I ended up trying to reproduce part of what was here.  Hopefully I've been successful at that *and* in addressing the concerns and suggestions you raised.

2021-10-29 02:33 UTC, tldahlgren commented
> Could you update the documentation under Command Reference

I expanded on the documentation that should get automatically picked up but I will check on this next chance I get.

2021-10-29 05:40 UTC, alalazo commented on lib/spack/spack/cmd/tags.py
> +    )
https://github.com/spack/spack/blob/361d98c4ec93f9b682b949a111958df38e70f46b/lib/spack/spack/cmd/tags.py#L61-L64 

This is absolutely fine, thanks!

2021-10-29 06:21 UTC, alalazo commented on lib/spack/spack/cmd/tags.py
> +            report_tags("Installed", tags)
I think everything is great in the output with this single exception. Start from an empty DB then:
```console
$ spack install zlib
[ ... ]
$ spack tags -i
0 installed package tags:
    None
```
Can we easily output something like:
```console
$ spack tags -i
==> Installed packages have no tag
```
?

2021-10-29 06:35 UTC, alalazo requested changes
Thanks this looks great. I have just one comment on the output in https://github.com/spack/spack/pull/26136#discussion_r738961700 and a few very minor code comments.

2021-10-29 06:35 UTC, alalazo commented on lib/spack/spack/tag.py
> +    return len(specs) > 0
I think this is unnecessary. Aren't:
```python
if spack.environment.get_installed_package_specs():
    pass
```
and:
```python
if spack.tag.has_installed_packages():
    pass
```
equivalent? Can we remove this function?

2021-10-29 06:35 UTC, alalazo commented on lib/spack/spack/tag.py
> +def get_installed_package_names():
Can we rename it to:
```suggestion
def _get_installed_package_names():
```
or inline it in the only place where it's used?

2021-10-29 06:35 UTC, alalazo commented on lib/spack/spack/environment/environment.py
> +def get_installed_package_specs():
Nitpick. We can avoid `get_` and possibly `package` in the name:
```suggestion
def installed_specs():
```
When a client calls this function I think:
```python
spack.environment.installed_specs()
```
will still make sense. What do you think?

2021-11-01 16:56 UTC, tldahlgren commented on lib/spack/spack/environment/environment.py
> +def get_installed_package_specs():
It does have a kind of symmetry with `uninstalled_specs`.  My concern was there is an `installed_specs` in `cmd/common/arguments.py` and it is used in a number of contexts as a variable but I will assume that won't cause problems.

2021-11-01 17:09 UTC, tldahlgren commented on lib/spack/spack/tag.py
> +    return len(specs) > 0
> > Could you update the documentation under Command Reference
> 
> I expanded on the documentation that should get automatically picked up but I will check on this next chance I get.

@RikkiButler20 FYI. The Spack PR process already adds the new command to the table (see https://spack--26136.org.readthedocs.build/en/26136/command_index.html) and the documentation extracted from the comments (see https://spack--26136.org.readthedocs.build/en/26136/command_index.html#spack-tags).

Did you want more documentation than this?

2021-11-01 17:42 UTC, alalazo approved these changes

2021-11-01 20:40 UTC, merged