added NOAAs UPP package
LLNL/spack pull request #26198
Opened 2021-09-23 17:15 UTC by edwardhartnett

added NOAAs UPP package

2021-09-23 18:58 UTC, tldahlgren requested changes

2021-09-23 18:58 UTC, tldahlgren commented on var/spack/repos/builtin/packages/upp/package.py
> +    version('10.0.9', branch='upp_v10.0.9', submodules=True)
The general practice for numbered branches is to use the `tag` or, less often, the commit.  The former would look like:

```suggestion
    version('10.0.9', tag='upp_v10.0.9', submodules=True)
```

2021-09-23 19:49 UTC, t-brown commented
Quick question, has EMC stored out the naming issues? As in there was [EMC_post](https://github.com/NOAA-EMC/EMC_post), with documentation referring to itself as UPP and the final binary built was `ncep_post`.

If we want to have UPP then I am all for it and will deprecate the [ncep_post](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/ncep-post/package.py) package.

2021-09-23 19:58 UTC, edwardhartnett commented
Sorry, I was not aware of the ncep_post package.

EMC_Post officially changed names to "UPP". Documentation should use UPP. It would be best if the spack name were "upp" as well.

If that can be more easily accommodated by a change to the existing ncep_post package, let me know.

2021-09-23 20:17 UTC, t-brown commented
I'm happy pulling [ncep-post](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/ncep-post/package.py), as this UPP package has more `variant` options. I also see you've cleaned up the installed binary installed name to `upp.x` (I still really hate the use of that suffix) and pulled in a common CMake modules (so the package doesn't need to be patched.

2021-09-27 11:42 UTC, edwardhartnett commented
Looks like this CI has gotten stuck - how to unstick it?

2021-09-27 15:49 UTC, tldahlgren commented
@spackbot run pipeline

2021-09-27 15:56 UTC, tldahlgren approved these changes

2021-09-27 15:56 UTC, merged