added package g2c from NOAAs NCEPLIBS project
LLNL/spack pull request #26190
Opened 2021-09-23 15:42 UTC by edwardhartnett

added package g2c from NOAAs NCEPLIBS project

2021-09-23 19:22 UTC, tldahlgren requested changes

2021-09-23 19:22 UTC, tldahlgren commented on var/spack/repos/builtin/packages/g2c/package.py
> +        return args
This is not needed if you aren't going to provide custom arguments as this is equivalent to the inherited methods.

```suggestion
```

2021-09-23 19:22 UTC, tldahlgren commented on var/spack/repos/builtin/packages/g2c/package.py
> +    version('1.6.2', sha256='b5384b48e108293d7f764cdad458ac8ce436f26be330b02c69c2a75bb7eb9a2c')
Confirmed the sha256.

2021-09-27 11:41 UTC, edwardhartnett commented
Looks like the CI has hanged - can it be restarted?

2021-09-27 18:03 UTC, tldahlgren approved these changes

2021-09-27 18:03 UTC, merged