Add hoppet package
LLNL/spack pull request #26297
Opened 2021-09-28 10:53 UTC by haralmha

2021-09-28 10:54 UTC, haralmha commented
@vvolkl

2021-09-28 12:34 UTC, vvolkl commented on var/spack/repos/builtin/packages/hoppet/package.py
> +#
>  If you submit this package back to Spack as a pull request,
>  please first remove this boilerplate and all FIXME comments.

2021-09-28 12:35 UTC, vvolkl commented on var/spack/repos/builtin/packages/hoppet/package.py
> +
please add a hep tag, like:
 `tags = ['hep']`

2021-09-28 12:36 UTC, vvolkl commented on var/spack/repos/builtin/packages/hoppet/package.py
> +    # maintainers = ['haralmha']
If you are ok, with being pinged for reviews for this recipe, uncomment, if not, remove this line

2021-09-28 12:36 UTC, vvolkl commented on var/spack/repos/builtin/packages/hoppet/package.py
> +        # FIXME: If not needed delete this function
> FIXME: If not needed delete this function

2021-09-28 12:39 UTC, vvolkl commented
There are issues with the code style, see https://spack.readthedocs.io/en/latest/contribution_guide.html#style-tests to fix them.

2021-09-28 12:48 UTC, vvolkl requested changes
See above. Also, can you change the title? Most PRs use a format similar to 
"hoppet: add new package"
and
"hoppet: add version xyz"

Did you try to run the tests with `spack install --test=root hoppet`?

2021-09-28 12:51 UTC, vvolkl commented
Your first commit does not seem to have proper author information, maybe rebase to squash all of them?

2021-09-29 13:07 UTC, vvolkl approved these changes

2021-10-01 15:24 UTC, alalazo approved these changes

2021-10-01 15:24 UTC, merged