Add hdf5 vols
LLNL/spack pull request #26305
Opened 2021-09-28 17:23 UTC by lrknox

2021-09-28 21:38 UTC, hyoklee submitted a review, later dismissed

2021-09-28 21:38 UTC, hyoklee commented on var/spack/repos/builtin/packages/hdf5-vol-cache/package.py
> +    # Set hdf5-cmake package option.
Remove next 4 lines.

2021-09-28 21:38 UTC, hyoklee commented on var/spack/repos/builtin/packages/hdf5-vol-async/package.py
> +    version('develop', branch='develop')
Add a different version until https://github.com/hpc-io/vol-async/pull/13 is accepted.
```
    version('develop', branch='develop')
    version('hyoklee.develop',
            branch='develop',
            git='https://github.com/hyoklee/vol-async', preferred=True)
```

2021-09-28 21:51 UTC, lrknox commented
There were 2 PR checks that failed before – one was an ubuntu download, the other a test in an e4s pipeline – it wasn’t clear from a quick scan of the log whether it had anything to do with the PR.

The e4s pipeline is not required for the PR, the ubuntu test is.

The tests are queued and waiting to run.  I’m going to click the Ready for review button and see what happens.

Hmmm, it says “Merging can be performed automatically with 1 approving review.”
But also “You’re not authorized to merge this pull request.”
Taking both under consideration – I don’t know what that means.  Maybe automatically is someone with sufficient privilege clicking the “Merge pull request” button.

Anyway, it might be a while before these tests run.


From: H. Joe Lee ***@***.***>
Sent: Tuesday, September 28, 2021 4:39 PM
To: spack/spack ***@***.***>
Cc: Larry Knox ***@***.***>; Author ***@***.***>
Subject: Re: [spack/spack] Add hdf5 vols (#26305)


@hyoklee approved this pull request.

________________________________

In var/spack/repos/builtin/packages/hdf5-vol-cache/package.py<https://github.com/spack/spack/pull/26305#discussion_r717981037>:

> +#

+# SPDX-License-Identifier: (Apache-2.0 OR MIT)

+from spack import *

+

+

+class Hdf5VolCache(CMakePackage):

+    """Package for HDF5 cache VOL."""

+

+    homepage = "https://sdm.lbl.gov/"

+    git      = "https://github.com/hpc-io/vol-cache.git"

+

+    maintainers = ['hyoklee']

+

+    version('default', branch='develop')

+

+    # Set hdf5-cmake package option.

Remove next 4 lines.

________________________________

In var/spack/repos/builtin/packages/hdf5-vol-async/package.py<https://github.com/spack/spack/pull/26305#discussion_r717982238>:

> +# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other

+# Spack Project Developers. See the top-level COPYRIGHT file for details.

+#

+# SPDX-License-Identifier: (Apache-2.0 OR MIT)

+

+from spack import *

+

+

+class Hdf5VolAsync(CMakePackage):

+    """This package enables asynchronous IO in HDF5."""

+

+    homepage = "https://sdm.lbl.gov/"

+    git      = "https://github.com/hpc-io/vol-async"

+    maintainers = ['hyoklee']

+

+    version('develop', branch='develop')

Add a different version until hpc-io/vol-async#13<https://github.com/hpc-io/vol-async/pull/13> is accepted.

    version('develop', branch='develop')

    version('hyoklee.develop',

            branch='develop',

            git='https://github.com/hyoklee/vol-async', preferred=True)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/spack/spack/pull/26305#pullrequestreview-765986184>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ADGMWCWQWC3G2UHPBQJ576TUEIYXJANCNFSM5E55263A>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

2021-09-30 15:02 UTC, hyoklee approved these changes

2021-10-02 22:07 UTC, bernhardkaindl requested changes
@lrknox @hyoklee I, and I assume other maintainers would have too, have several issues with this PR.
* Just to mention it: You are submitting 4, not 3 packages as written with a single PR.
* So far, you needed 11 commits changing these 4 packages, not in an organized way.
* You are using only using develop branches, no stable branches.
* You are applying a patch on top of the develop branch for one of these packages
```
    version('default', branch='develop')
    depends_on('hdf5@develop-1.13')
    patch('CMakeLists.patch',
         sha256='09876179329cbc7d925055c714cabe05511ba7a9a8e9d5e029cc9acfdac5ffa7')
```
* The review comments by @hyoklee have not been answered and not fixed.
* There are too many not helpful blank lines in the package.py files in my opinion.

Reviews like this are too large to be effective and manageable for a reviewer.

Small PRs are the norm, one PR per package. But don't open 4 new PRs just yet:

I propose this plan:

1. Open one PR for hdf5-vol-async/package.py
2. Work on getting hdf5-vol-external-passthrough/CMakeLists.patch upstream.
3. While 1 and 2 are in progess, check this
```
grep -r depends_on.*hdf5 hdf5-vol-*hdf5-vol-async/package.py:    depends_on('hdf5@develop-1.13+mpi+threadsafe')
hdf5-vol-cache/package.py:    depends_on('hdf5-vol-async')
hdf5-vol-external-passthrough/package.py:    depends_on('hdf5@develop-1.13')
hdf5-vol-log/package.py:    depends_on('hdf5@1.12.1')
```
Do you really want 3 different variants/versions of hdf5 for this group of packages?
Besides prolonged compilation time, I am sure how it is the use different versions.

hdf5-vol-async needs to be merged first, as vol-cache depends on it.
vol-cache should only be submitted whith vol-async merged into spack.

2021-10-21 15:43 UTC, lrknox commented
Thanks, @bernhardkaindl.  Step 1 of your proposed plan is done in PR #26874, using stable version tags instead of develop.
The upstream CMakeLists.txt patch has been merged, and another PR for hdf5-vol-external-passthrough will follow soon, probably with the same version tags.
hdf5-vol-cache will require a different tag which is not yet available, but when it is all three packages should be updated to use the new tag.
hdf5-vol-log may or may not be updated from hdf5 version 1.12.1.  At present it will not build with the 1.13.0-rc6 tag.

2023-02-20 14:27 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2023-02-20 14:27 UTC, closed without merging