Add pmix variant to openmpi package
LLNL/spack pull request #26342
Opened 2021-09-29 15:07 UTC by MisterFruits

Allows to compile openmpi against pmix, relates to '--with-pmix=' configure option.

See #19925

2021-09-29 20:13 UTC, hppritcha commented
👍

2021-09-30 09:38 UTC, MisterFruits commented
I saw that the gitlabci failed due to some connection refused at the end of the job (it doesn't seem to relate to modifications I made in the PR)

```
ERROR: Job failed (system failure): error dialing backend: dial tcp 192.168.58.124:10250: connect: connection refused
```

Is there an action I can do?

2021-09-30 13:43 UTC, hppritcha commented
@alalazo could you rerun the gitlabci job?

2021-09-30 13:44 UTC, haampie requested changes

2021-09-30 13:44 UTC, haampie commented on var/spack/repos/builtin/packages/openmpi/package.py
> +    conflicts('+pmix', when='@:1.999.999')
```suggestion
    conflicts('+pmix', when='@:1')
```

2021-10-01 12:16 UTC, haampie requested changes

2021-10-01 12:16 UTC, haampie commented on var/spack/repos/builtin/packages/openmpi/package.py
> +                config_args.extend(self.with_or_without('pmix'))
```suggestion
            config_args += self.with_or_without('pmix', activation_value='prefix')
```

2021-10-01 16:43 UTC, haampie approved these changes

2021-10-01 16:43 UTC, merged

2021-10-17 14:13 UTC, dylex commented
This breaks the build for openmpi 2, as pmix is required, but building with external pmix also requires external libevent, which isn't enabled for <4.  It would be nice to have an option to use the previous default of using the internal pmix (rather than disabling it completely), or even to make this the default for <4 as it is for libevent.