[dd4hep] prepend_path ROOT_INCLUDE_PATH
LLNL/spack pull request #26361
Opened 2021-09-29 23:26 UTC by wdconinc

Including the headers in ROOT_INCLUDE_PATH ensures that they are found by the cling autoloader. This avoids warnings such as:
```
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for DDRec/ISurface.h
   requested to autoload type dd4hep::rec::ISurface
```
A similar approach is applied in [gaudi](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/gaudi/package.py#L116).

2021-09-30 08:14 UTC, vvolkl approved these changes
Good catch, thanks!

2021-09-30 14:35 UTC, vvolkl commented
It seems that this was previously working because Spack was populating the CPATH (which is also searched by root) for all packages, but it has since stopped (https://github.com/spack/spack/commit/e3f97b37e64d4de70baf8e58fcd747b021d8f2f9#diff-259adc895c0b2e8fca42ffb99d8051eec0712c868d12d8da255d32f1663acdc7). There will probably be a few more packages where explicitly setting the ROOT_INCLUDE_PATH is required

2021-09-30 14:41 UTC, wdconinc commented
Thanks @vvolkl for identifying that. I was just wondering why this stopped working for me (typically I can attribute it to using views at `/usr/local`, so `/usr/local/include` easily ends up in the required search paths).

Maybe this is something that should go into ROOT's `setup_dependent_run_environment` (https://spack.readthedocs.io/en/latest/spack.html#spack.package.PackageBase.setup_dependent_build_environment) as
```
    def setup_dependent_build_environment(self, env, dependent_spec):
        #...
        env.prepend_path('ROOT_INCLUDE_PATH', dependent_spec.prefix.include)
```

2021-09-30 14:48 UTC, vvolkl commented
I really like this suggestion - it will add a few packages that don't really need it to the ROOT_INCLUDE_PATH, but it will massively simplify the maintenance of the recipes for those that do. Could you add this to the ROOT recipe?

2021-09-30 15:11 UTC, wdconinc commented
https://github.com/spack/spack/pull/26379

2021-10-01 14:46 UTC, alalazo requested changes
Waiting on #26379

2021-10-20 03:22 UTC, wdconinc commented
Closing for more fundamental solution in https://github.com/spack/spack/pull/26379

2021-10-20 03:22 UTC, closed without merging