Add shared library option + static lib fix
LLNL/spack pull request #26419
Opened 2021-10-01 23:42 UTC by he-b

Added option for shared libraries.

Also fixed circular dependency when only using static libraries.

2021-10-02 23:09 UTC, bernhardkaindl commented
Run `flake8` on your package.py (and even better `spack style <path/to/package.py>`)
```py
flake8-3.8.2-ag7jbfdh2m25uv6ignnwfkl7e7dioirh
  var/spack/repos/builtin/packages/intel-oneapi-mkl/package.py:68: [E501] line too long (94 > 88 characters)
  var/spack/repos/builtin/packages/intel-oneapi-mkl/package.py:70: [E501] line too long (92 > 88 characters)
  flake8 found errors
```

2021-10-03 08:58 UTC, bernhardkaindl requested changes
I assume this could make the flake8 tool happy (you can install it with pip3 as well).

You can apply this suggestion witth button next to, but run it yourself after pulling the commit.

2021-10-03 08:58 UTC, bernhardkaindl commented on var/spack/repos/builtin/packages/intel-oneapi-mkl/package.py
> +            libs = LibraryList(['-Wl,--start-group'] + libs.libraries + ['-Wl,--end-group'])
```suggestion
                              join_path(self.component_path, 'lib', 'intel64'),
                                        shared=shared)
        if not shared:
            libs = LibraryList(['-Wl,--start-group'] + libs.libraries +
                               ['-Wl,--end-group'])
```

2021-10-03 14:07 UTC, rscohn2 commented
@he-b: I have a pending PR that overlaps with your changes because it adds the libraries for scalapack interfaces. Could you submit these changes as a PR against that branch? Then we could request the changes be merged with both commits. I usually add tests and can add a test for static linking.

2021-10-03 21:28 UTC, he-b commented
@rscohn2 thank you for your comments, I created a PR  in your branch as you requested.

2021-12-22 12:26 UTC, closed without merging