Improve compilation of source-highlight with gcc11
LLNL/spack pull request #26412
Opened 2021-10-01 16:13 UTC by he-b

Follow-up for PR #25947 

Added conflict of versions depending on the version of gcc used.

Added version tied to last commit done on 2020-06-10 from source-highlight repo. So this will be the default version compiled and it will be compatible with gcc 11.

`cgit` repository did not work for me, I got the message:
```
fatal: repository 'https://git.savannah.gnu.org/cgit/src-highlite.git/' not found
==> Error: FetchError: All fetchers failed
```

I did not have problems with the `git` repo.

2021-10-02 08:10 UTC, michaelkuhn requested changes
I would propose to simply add a patch to fix the problem:
```
patch('https://git.savannah.gnu.org/cgit/src-highlite.git/patch/lib?id=904949c9026cb772dc93fbe0947a252ef47127f4', sha256='45087b174b2b128a8dc81b0728f8ae63213d255ceef6dabfcba27c94e2a75ce9', when='%gcc@11:')
```

2021-10-03 12:27 UTC, sethrj submitted a review, later dismissed
Looks good, verified that the updated git URL is correct as is the new commit.

2021-10-03 12:28 UTC, sethrj commented
Didn't see @michaelkuhn 's review -- he suggests a better approach!

2021-10-03 15:44 UTC, michaelkuhn approved these changes

2021-10-03 16:07 UTC, merged