add hash field to spec on find --json and assert in test its there
LLNL/spack pull request #26443
Opened 2021-10-03 14:16 UTC by fakegermano

Resolves https://github.com/spack/spack/issues/26348

Added a new "hash" field to json dict spec only on `display_specs_as_json`. 

Shouldn't` break compatibility as this command is only used by the `find --json` output.

I'm deliberately being verbose on the implementation to allow people to further change (if needed) this behaviour. I have considered adding another argument to output hashed json but discarded it due to the minimal changes this implementation had.

2021-10-07 17:12 UTC, becker33 requested changes

2021-10-07 17:12 UTC, becker33 commented on lib/spack/spack/cmd/__init__.py
> +                records.append(record)
This whole change can be replaced by a call to `Spec.node_dict_with_hashes()`

2021-10-07 17:44 UTC, fakegermano commented on lib/spack/spack/cmd/__init__.py
> +                records.append(record)
you are right! (sorry for the last comment, deleted it as I was completely wrong) 

I'll get into using this function and send a commit your way,

Thanks!

2021-10-08 06:49 UTC, becker33 approved these changes

2021-10-08 06:50 UTC, merged