add patch for emacs with glibc-2.34
LLNL/spack pull request #26455
Opened 2021-10-04 05:11 UTC by joequant

2021-10-04 06:45 UTC, alalazo requested changes
One minor request and a question

2021-10-04 06:45 UTC, alalazo commented on var/spack/repos/builtin/packages/emacs/package.py
> +    patch('glibc-2.34.patch')
Can you copy the comment in the Gentoo patch over the directive? That will give people context by reading only `package.py`. Also is the patch to be applied unconditionally (i.e. is it valid for each version of emacs we support)?

2021-10-12 17:36 UTC, bernhardkaindl commented on var/spack/repos/builtin/packages/emacs/package.py
> +    patch('glibc-2.34.patch')
@joequant ping for the question on the patch

2022-05-10 16:31 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2022-05-10 16:31 UTC, closed without merging