py-templateflow: add 0.4.2
LLNL/spack pull request #26471
Opened 2021-10-04 14:39 UTC by manuelakuhn

2021-10-06 19:27 UTC, adamjstewart requested changes

2021-10-06 19:27 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-templateflow/package.py
>      depends_on('python@3.6:', type=('build', 'run'))
The older version supports Python 3.5+

2021-10-06 19:27 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-templateflow/package.py
>      depends_on('py-wheel', type='build')
Wheel is not actually required in the older version

2021-10-06 21:18 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-templateflow/package.py
>      depends_on('python@3.6:', type=('build', 'run'))
Sorry, I overlooked that. Will fix it.

2021-10-06 21:26 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-templateflow/package.py
>      depends_on('py-wheel', type='build')
I originally (for version 0.7.1) put it in because without it the package did not build.  
Because I saw it as an requirement for the old version in the [pyproject.toml](https://github.com/templateflow/python-client/blob/0.4.2/pyproject.toml), I left it in, assuming that I would get build errors for the old version as well otherwise.
I just tested it and version 0.4.2 also builds without the wheel requirement. 
Should I still remove it, or leave it in because it is in the `pyproject.toml`?

2021-10-07 00:17 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-templateflow/package.py
>      depends_on('py-wheel', type='build')
We don't actually use the `pyproject.toml` for anything in Spack, we run `setup.py` so only dependencies listed in `setup_requires` or `install_requires` are needed. In this case, even though it's in `pyproject.toml`, we don't build any wheels, so I would remove it. You'll have to keep it for newer versions though because it's in `setup.cfg` and setuptools will try to download and install it if it isn't available.

2021-10-07 16:08 UTC, bernhardkaindl commented on var/spack/repos/builtin/packages/py-templateflow/package.py
>      depends_on('py-wheel', type='build')
@manuelakuhn  Idea: We (the package.py) could remove `py-wheel` from `setup.cfg` using `filter_file()` to be sure we are not download and install it based on `setup.cfg`

@adamjstewart If that is global for all (python) packages, we could do that by default in `build_systems/python.py`

2021-10-07 19:30 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-templateflow/package.py
>      depends_on('py-wheel', type='build')
This probably wouldn't be a good idea as some packages may actually use `wheel` at build time.

2021-10-07 20:52 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-templateflow/package.py
>      depends_on('py-wheel', type='build')
Thanks @adamjstewart for the explanation.

@bernhardkaindl: I also don't think it would be a good idea because it would break things. As example `py-templateflow@0.7.1` does not build when wheel is removed as dependency.

2021-10-12 02:37 UTC, adamjstewart approved these changes

2021-10-12 02:37 UTC, merged