build_environment: clean *_ROOT variables
LLNL/spack pull request #26474
Opened 2021-10-04 15:31 UTC by vvolkl

This will otherwise lead to user variables overriding the dependencies set up by spack- which should not happen. see https://cmake.org/cmake/help/latest/variable/PackageName_ROOT.html

2021-10-04 15:36 UTC, haampie requested changes

2021-10-04 15:36 UTC, haampie commented on lib/spack/spack/build_environment.py
> +        if '_ROOT' in varname:
```suggestion
        if varname.endswith('_ROOT'):
```

2021-10-06 19:22 UTC, adamjstewart approved these changes, later dismissed
LGTM, but I'll let others comment since this affects every package in Spack.

2021-10-08 23:28 UTC, haampie approved these changes

2021-10-08 23:29 UTC, haampie requested changes
You know what other variable ends with _ROOT?

ERROR: SPACK_ROOT was not set!

(Do we *really* need this variable for Spack to work though?)

2021-11-09 10:16 UTC, haampie approved these changes

2021-11-09 10:16 UTC, merged