Update of siesta libs
LLNL/spack pull request #26489
Opened 2021-10-04 17:57 UTC by danielecesarini

Hello,

this is bunch of updates for [siesta](https://gitlab.com/siesta-project/siesta)'s dependencies. Now the latest version of siesta can solve all the dependencies with spack.

2021-10-06 19:14 UTC, adamjstewart requested changes

2021-10-06 19:14 UTC, adamjstewart commented on var/spack/repos/builtin/packages/libgridxc/package.py
> +    depends_on('m4')
I'm guessing that these should be `type='build'` dependencies?

2021-10-06 19:14 UTC, adamjstewart commented on var/spack/repos/builtin/packages/libgridxc/package.py
> +    phases = ['configure', 'build']
I would add a `'install'` phase to this list and rename `fix_mk` to `install`

2021-10-06 19:14 UTC, adamjstewart commented on var/spack/repos/builtin/packages/libpsml/package.py
> +    depends_on('m4')
`type='build'`

2021-10-06 19:14 UTC, adamjstewart commented on var/spack/repos/builtin/packages/xmlf90/package.py
> +            url='https://launchpad.net/xmlf90/trunk/1.5/+download/xmlf90-1.5.4.tar.gz')
I don't think these need to be version-specific URLs. Since the major.minor version appears in the URL, you're better off adding the following:
```python
def url_for_version(self, version):
    url = 'https://launchpad.net/xmlf90/trunk/{0}/+download/xmlf90-{1}.tar.gz'
    return url.format(version.up_to(2), version)
```
You should still keep the top-level `url` attribute since it's used by `spack versions` and `spack checksum`.

2021-10-09 12:56 UTC, danielecesarini commented on var/spack/repos/builtin/packages/libgridxc/package.py
> +    depends_on('m4')
See commit  5cfebb40b2544605cacad6acb7da22fa6f2b8da8

2021-10-09 12:57 UTC, danielecesarini commented on var/spack/repos/builtin/packages/libgridxc/package.py
> +    phases = ['configure', 'build']
See commit 47885fdfb368de55203735a8adfce6fb1eb080d4

2021-10-09 12:58 UTC, danielecesarini commented on var/spack/repos/builtin/packages/libpsml/package.py
> +    depends_on('m4')
See commit 5cfebb40b2544605cacad6acb7da22fa6f2b8da8

2021-10-09 12:58 UTC, danielecesarini commented on var/spack/repos/builtin/packages/xmlf90/package.py
> +            url='https://launchpad.net/xmlf90/trunk/1.5/+download/xmlf90-1.5.4.tar.gz')
See commit 3e68cb63718cef853fc5262a0362eb053050159c

2021-10-09 16:33 UTC, adamjstewart commented
This PR includes a bunch of unrelated changes that were already merged in master. Did you mess up a merge/rebase?

2021-10-10 13:07 UTC, danielecesarini commented
> This PR includes a bunch of unrelated changes that were already merged in master. Did you mess up a merge/rebase?

Sorry, it's a broken rebase, I am trying to fix.

2021-10-10 22:19 UTC, adamjstewart commented on var/spack/repos/builtin/packages/xmlf90/package.py
> -    url      = "https://launchpad.net/xmlf90/trunk/1.5/+download/xmlf90-1.5.2.tgz"
I would still keep this package-level url. It's used for `spack checksum` and `spack versions`, while `url_for_version` is only used for `spack fetch` and `spack install`.

2021-10-11 08:48 UTC, danielecesarini commented on var/spack/repos/builtin/packages/xmlf90/package.py
> -    url      = "https://launchpad.net/xmlf90/trunk/1.5/+download/xmlf90-1.5.2.tgz"
Done, see f93bb316e08919a14d91b1fd4cc94911e05e4819

2021-10-11 14:09 UTC, adamjstewart approved these changes

2021-10-11 14:09 UTC, merged