SEACAS: add a Faodel variant
LLNL/spack pull request #26583
Opened 2021-10-07 19:19 UTC by tkordenbrock

SEACAS has supported Faodel as a TPL since the 2021-04-05 release.  Add it as a variant of the SEACAS package.

2021-10-07 19:21 UTC, tkordenbrock commented
@gsjaardema This is draft until the #26516 is merged.

2021-10-07 21:19 UTC, sethrj requested changes

2021-10-07 21:19 UTC, sethrj commented on var/spack/repos/builtin/packages/seacas/package.py
> +
For safety (variant checking and dependency usage and more error-free code), use the CMakePackage helper macros:
```suggestion
        define = CMakePackage.define
        from_variant = self.define_from_variant

        options.append(from_variant('TPL_ENABLE_Faodel', 'faodel'))
        for pkg in ('Faodel', 'BOOST'):
            if pkg.lower() in spec:
                options.append(define(pkg + '_ROOT', spec[pkg.lower()].prefix]))

```

2021-10-07 21:19 UTC, sethrj commented on var/spack/repos/builtin/packages/seacas/package.py
> +    depends_on('faodel@1.2108.1:+mpi', when='+faodel +mpi')
There should be either a `~mpi` pair for this or a `conflicts('+faodel', when='~mpi')`.

2021-10-11 20:46 UTC, tkordenbrock commented on var/spack/repos/builtin/packages/seacas/package.py
> +
@sethrj Thanks for the review.  I wasn't aware of these packages.  I have pushed updates to use them.

2021-10-11 20:47 UTC, tkordenbrock commented on var/spack/repos/builtin/packages/seacas/package.py
> +    depends_on('faodel@1.2108.1:+mpi', when='+faodel +mpi')
@sethrj I have added a depends_on() for "+faodel ~mpi" in the latest update.

2021-10-11 21:00 UTC, gsjaardema commented on var/spack/repos/builtin/packages/seacas/package.py
> +        for pkg in ('Faodel', 'BOOST'):
Why is the `BOOST` listed here?

2021-10-12 09:57 UTC, sethrj commented on var/spack/repos/builtin/packages/seacas/package.py
> +        for pkg in ('Faodel', 'BOOST'):
Good catch, it was probably a copy-paste error in an earlier version (see https://github.com/spack/spack/pull/26583#discussion_r724540693)

2021-10-12 12:19 UTC, tkordenbrock commented on var/spack/repos/builtin/packages/seacas/package.py
> +        for pkg in ('Faodel', 'BOOST'):
Some of the installed Faodel headers include Boost headers, so FaodelTPLs.cmake checks that a supported Boost is available at $BOOST_ROOT.

2021-10-13 13:39 UTC, sethrj approved these changes

2021-10-13 15:03 UTC, gsjaardema approved these changes
Looks good to me.  Thanks for adding this.

2021-10-13 16:39 UTC, merged