libical: Add missing deps: pkgconfig, glib and libxml2
LLNL/spack pull request #26618
Opened 2021-10-08 22:05 UTC by bernhardkaindl

Libical needs pkgconfig, glib and libxml2 to build.

2021-10-09 15:33 UTC, michaelkuhn requested changes

2021-10-09 15:33 UTC, michaelkuhn commented on var/spack/repos/builtin/packages/libical/package.py
>      depends_on('cmake@3.11.0:', type='build')
Not related to your changes, but according to https://github.com/libical/libical/blob/v3.0.8/CMakeLists.txt#L82, this should be `@3.1.0:`.

2021-10-09 15:33 UTC, michaelkuhn commented on var/spack/repos/builtin/packages/libical/package.py
> +    depends_on('glib')
```suggestion
    depends_on('glib@2.32:')
```
https://github.com/libical/libical/blob/v3.0.8/CMakeLists.txt#L395

2021-10-09 15:33 UTC, michaelkuhn commented on var/spack/repos/builtin/packages/libical/package.py
> +    depends_on('libxml2')
```suggestion
    depends_on('libxml2@2.7.3:')
```
https://github.com/libical/libical/blob/v3.0.8/CMakeLists.txt#L396

2021-10-12 16:45 UTC, bernhardkaindl commented
@michaelkuhn The changes are applied and new version 3.0.11 is added as well.

2021-10-12 21:22 UTC, michaelkuhn approved these changes

2021-10-12 21:22 UTC, merged