whizard: add libtirpc for rpc/types.h
LLNL/spack pull request #26628
Opened 2021-10-09 10:54 UTC by joequant

rpc/types.h has been removed in recent glibc

2021-10-12 15:09 UTC, bernhardkaindl requested changes
`spack install -v --test=root whizard` (use -v as it takes very long) fails with:
```
  >> 5102    FAIL: whizard_lha.run
  >> 5103    FAIL: pythia8.run
```
Is it possible to remove the tests which fails due to missing reference output?
```py
grep reference .../spack-stage-whizard-3.0.1-zkyegedygw7rioitsyhr2ddbwzkg3x4y/spack-src/tests/unit_tests/test-suite.log
Running test: whizard_lha_2 ... no reference output available ... failure.  See: err-output/whizard_lha_2.out
Running test: pythia8_1 ... no reference output available ... failure.  See: err-output/pythia8_1.out
Running test: pythia8_2 ... no reference output available ... failure.  See: err-output/pythia8_2.out
```
Their recorded output looks ok. The testsuite also is not run in parallel, and takes a lot of time.
Is it possible to run it in parallel?

2021-10-15 08:23 UTC, tmadlener commented
> Is it possible to run it in parallel?

We have disabled building (and by that probably also testing) due to: https://github.com/key4hep/key4hep-spack/issues/71#issuecomment-706303646

2021-10-15 21:03 UTC, vvolkl commented
This patch is not enough for me to build whizard on arch, I have to add `self.spec['libtirpc'].prefix.include.tirpc` to the CPATH in the build environment as well. Not sure why, as https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/libtirpc/package.py#L31 tries to fix the include paths. Maybe because we hardcode the compiler we also need to set this explicitly?

2021-11-04 15:58 UTC, bernhardkaindl approved these changes
Ok I don't want to hold back merging this longer.

I confirm that this fixes the build in a freshly installed Arch linux container (used the tar.xz from this release) for me:

https://gitlab.archlinux.org/archlinux/archlinux-docker/-/releases/v20211017.0.36769
```
lsb_release -av
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```
@vvolkl About your issue: As I could not confirm your issue (of build on arch failing) and the fix of this PR being enough which also means that I cannot make and test your comment, I have no basis on taking further action your comment.

If you really need an additional change, speak up or open a PR for it.
But I guess since the current arch linux docker image (run in singularity) does not exhibit your issue, it is likely something specific for your arch linux or spack installation, or an older version of arch linux. Either way, the build in arch-linux worked for me.

2021-11-09 10:14 UTC, merged