py-nilearn: add 0.4.2 and 0.6.2
LLNL/spack pull request #26635
Opened 2021-10-09 19:45 UTC by manuelakuhn

2021-10-09 20:49 UTC, adamjstewart requested changes

2021-10-09 20:49 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-nilearn/package.py
> +    depends_on('py-matplotlib@1.1.1:3.3', when='@:0.6', type='test')
I would remove this and change which modules are imported depending on variant.

2021-10-09 21:09 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-nilearn/package.py
> +    depends_on('py-matplotlib@1.1.1:3.3', when='@:0.6', type='test')
The problem is that e.g. `spack install --test=root py-nilearn@0.6.2` fails if `py-matplotlib` is not included, although the (documentation)[https://github.com/nilearn/nilearn#readme] says that plotting is an additional functionality not needed by default.

2021-10-09 21:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-nilearn/package.py
> +    depends_on('py-matplotlib@1.1.1:3.3', when='@:0.6', type='test')
Yes, and your fix doesn't change the fact that `spack test py-nilearn` will still fail. You'll need to override `import_modules` to only import things depending on `+plotting`. See `py-dask` for how we handle this in other packages.

2021-10-09 21:52 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-nilearn/package.py
> +    depends_on('py-matplotlib@1.1.1:3.3', when='@:0.6', type='test')
Ok, you are right `spack test run py-nilearn@0.6.2 ` indeed fails, but `spack install --test=root py-nilearn@0.6.2` passes. I thought they execute the same tests, why is the result different?

2021-10-09 21:57 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-nilearn/package.py
> +    depends_on('py-matplotlib@1.1.1:3.3', when='@:0.6', type='test')
Because of https://github.com/spack/spack/issues/20553. Even if that is fixed, it doesn't make sense to test optional features that we didn't install, and we don't want to have to duplicate these deps for every optional feature in every package.

2021-10-09 22:26 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-nilearn/package.py
> +    depends_on('py-matplotlib@1.1.1:3.3', when='@:0.6', type='test')
`import_modules` is overwritten and all tests (`install --test=root` and `test run`) for all versions pass now.

2021-10-10 00:14 UTC, adamjstewart approved these changes

2021-10-10 00:14 UTC, merged