recola: fix compilation
LLNL/spack pull request #26634
Opened 2021-10-09 19:07 UTC by vvolkl

2021-10-25 00:57 UTC, sethrj requested changes

2021-10-25 00:57 UTC, sethrj commented on var/spack/repos/builtin/packages/recola-sm/package.py
> +                '-Dcollier_path=%s' % self.spec['collier'].prefix.lib.cmake]
```suggestion
        args = [self.define('static', True),
                self.define('collier_path', self.spec['collier'].prefix.lib.cmake)]
```

2021-10-25 00:57 UTC, sethrj commented on var/spack/repos/builtin/packages/recola/package.py
> +             '-Dmodelfile_path=%s' % self.spec['recola-sm'].prefix.lib.cmake,
Same comments. Also the indentation here is causing spack style to fail.

2021-10-25 11:08 UTC, sethrj requested changes

2021-10-25 11:08 UTC, sethrj commented on var/spack/repos/builtin/packages/recola/package.py
> +            self.define(modelfile_path, self.spec['recola-sm'].prefix.lib.cmake),
These should all be quoted: they're strings becoming cmake variables, not python variables. How is this not causing the ci pipeline to fail??

2021-10-26 02:01 UTC, scottwittenburg commented on var/spack/repos/builtin/packages/recola/package.py
> +            self.define(modelfile_path, self.spec['recola-sm'].prefix.lib.cmake),
Is this package in one of the stacks?  I don't recognize it, but that doesn't mean much.  For it to get tested in the gitlab pipelines it would need to appear as a root or dependency in one of the tested stacks in `share/spack/gitlab/cloud_pipelines/stacks/`.

2021-10-26 08:15 UTC, sethrj commented on var/spack/repos/builtin/packages/recola/package.py
> +            self.define(modelfile_path, self.spec['recola-sm'].prefix.lib.cmake),
No it's not in any of E4S or it's dependencies. I just thought the regular Python unit tests would catch basic errors in the package recipe.

2021-10-26 08:19 UTC, vvolkl commented
Right, I was a bit too quick with the modifications and forgot the quotes. Thanks for catching that!

2021-10-26 08:21 UTC, vvolkl commented on var/spack/repos/builtin/packages/recola/package.py
> +            self.define(modelfile_path, self.spec['recola-sm'].prefix.lib.cmake),
Probably only syntax errors are caught - these lines would have to be evaluated to throw an error

2021-10-26 09:32 UTC, sethrj commented on var/spack/repos/builtin/packages/recola/package.py
> +            self.define(modelfile_path, self.spec['recola-sm'].prefix.lib.cmake),
@vvolkl I'm still seeing `static` and `modelfile_path` that need quotes. Also, `CMAKE_VERBOSE_MAKEFILE` is set by the default CMakePackage so you can delete that line.

2021-10-27 12:45 UTC, sethrj approved these changes

2021-10-27 13:19 UTC, merged