[acts] new versions 14.0.0, 14.1.0; new variants python, analysis
LLNL/spack pull request #26657
Opened 2021-10-11 16:44 UTC by wdconinc

Added variant python to support new CMake ACTS_BUILD_EXAMPLES_PYTHON_BINDINGS.

Ref. https://github.com/acts-project/acts/releases/tag/v14.0.0

Maintainer @HadrienG2

2021-10-12 07:13 UTC, HadrienG2 requested changes
Let me use this review as an opportunity to thank you for contributing to the ACTS package. It's so nice not to be the only one doing all the packaging work anymore...

2021-10-12 07:13 UTC, HadrienG2 commented on var/spack/repos/builtin/packages/acts/package.py
>      # FIXME: Use spack's autodiff package once there is one
Consider adding a FIXME along the lines of the other ones which points out that we cannot enable the newly introduced [ACTS_USE_SYSTEM_VECMEM](https://github.com/acts-project/acts/pull/998) yet (as we would normally want to, since spack likes to control the whole dependency chain).

2021-10-12 07:13 UTC, HadrienG2 commented on var/spack/repos/builtin/packages/acts/package.py
> +    conflicts('+python', when='@:13.0.0')
Please use `@:13` instead, this way the conflicts statement will still behave as expected if we need to tag a v13.0.y bugfix later on.

2021-10-12 07:13 UTC, HadrienG2 commented on var/spack/repos/builtin/packages/acts/package.py
> +    depends_on('python', when='+python')
The new Python-based unit tests ( https://github.com/acts-project/acts/pull/975 ) also require pytest as an extra dependency. It might be a good idea to add that dependency when `+python +unit_tests` is specified.

2021-10-12 07:13 UTC, HadrienG2 commented on var/spack/repos/builtin/packages/acts/package.py
> +    variant('python', default=False, description='Build python bindings for the examples')
Given that we already have quite a few build options for examples, we might also want to add a spack variant pointing to the recently introduced [ACTS_BUILD_ANALYSIS_APPS](https://github.com/acts-project/acts/pull/1001) CMake build option.

2021-10-17 01:49 UTC, wdconinc commented on var/spack/repos/builtin/packages/acts/package.py
> +    variant('python', default=False, description='Build python bindings for the examples')
Addressed in 3106922cb97f78e97fd8247ecb397d49d22f6c56.

2021-10-17 01:49 UTC, wdconinc commented on var/spack/repos/builtin/packages/acts/package.py
> +    depends_on('python', when='+python')
Addressed in 3106922cb97f78e97fd8247ecb397d49d22f6c56.

2021-10-17 01:49 UTC, wdconinc commented on var/spack/repos/builtin/packages/acts/package.py
> +    conflicts('+python', when='@:13.0.0')
Addressed in 3106922cb97f78e97fd8247ecb397d49d22f6c56.

2021-10-17 01:49 UTC, wdconinc commented on var/spack/repos/builtin/packages/acts/package.py
>      # FIXME: Use spack's autodiff package once there is one
Added a FIXME in 3106922cb97f78e97fd8247ecb397d49d22f6c56 (and wrote a vecmem package to be added in a different PR).

2021-10-17 17:06 UTC, HadrienG2 submitted a review, later dismissed
Looks good to me!

2021-10-18 17:34 UTC, wdconinc commented
Added acts@14.1.0. No build system or dependency changes.

2021-10-19 05:37 UTC, HadrienG2 approved these changes

2021-10-22 15:40 UTC, HadrienG2 commented
Ping @alalazo (this is not the PR you were interested in, which is still WIP, but I would still appreciate seeing this one in :))

2021-10-22 15:42 UTC, alalazo approved these changes

2021-10-22 15:43 UTC, merged

2021-10-22 15:45 UTC, HadrienG2 commented
Thanks for the prompt merge!

2021-10-22 16:00 UTC, wdconinc commented on var/spack/repos/builtin/packages/acts/package.py
> +    depends_on('py-pytest', when='+python +unit_test')
Argh, just missed the merge when I noticed that this should be `+unit_tests`...

2021-10-22 16:06 UTC, alalazo commented on var/spack/repos/builtin/packages/acts/package.py
> +    depends_on('py-pytest', when='+python +unit_test')
@wdconinc Feel free to submit a new PR and ping me.