Add Gromacs 2020.6 and Plumed 2.7.2
LLNL/spack pull request #26663
Opened 2021-10-11 19:03 UTC by w8jcik

- [x] Adds two hashes for Gromacs and Plumed
- [x] Adds Plumed 2.7.2 to Gromacs version constraints 

# Tests

- `spack spec gromacs@2020.6+plumed` pulls Plumed 2.7.2
- `spack spec gromacs@2021+plumed` pulls Plumed 2.7.2
- `spack spec gromacs@2020.5+plumed` pulls Plumed 2.7.1
- `spack install gromacs@2020.6~mpi+plumed` installs successfully
- `spack load gromacs@2020.6~mpi+plumed` `gmx` runs successfully

2021-10-11 21:44 UTC, junghans approved these changes

2021-10-12 02:40 UTC, bernhardkaindl requested changes
I don't want to be a pain, but in the interest of users of new gcc compilers:
>     * `spack install gromacs@2020.6~mpi+plumed` installs successfully

I tried this command didn't succeed in my Ubuntu 18.04 container using a spack instance with a spack-built gcc-11.2.0 loaded. It shows that in that version, at least `src/gromacs/modularsimulato/modularsimulator.h` misses a `#include <limits>`:

```yaml
spack install gcc@11.2.0
spack load gcc@11.2.0
spack compiler find
spack install --test=root gromacs@2020.6~mpi+plumed %gcc@11.2.0
...
spack-src/src/gromacs/modularsimulator/modularsimulator.h:26
            9:31: error: 'numeric_limits' is not a member of 'std'                                                                                                   
     521      269 |         Step lastStep_ = std::numeric_limits<Step>::max();
     522          |                               ^~~~~~~~~~~~~~
```
You could fix that by using a patch or `filter_file()` to replace a known include in that file with that line and `'\n#include <limits>'` or by adding a conflicts for newer compilers but I think it's easier and faster to test to add the `#include`.

2021-10-12 03:43 UTC, junghans commented
@bernhardkaindl does that have anything to do with plumed or does it fail with vanilla gromacs as well?

2021-10-12 08:41 UTC, marvinbernhardt approved these changes

2021-10-12 10:00 UTC, w8jcik commented
> @bernhardkaindl does that have anything to do with plumed or does it fail with vanilla gromacs as well?

It is not Plumed-related. Gromacs itself fails with this compiler version

```
spack install gromacs@2020.6~mpi %gcc@11.2.0 ^fftw~mpi
```

while with GCC 8 it builds fine.

```
spack install gromacs@2020.6~mpi %gcc@8.4.0 ^fftw~mpi
```

The issue is that I don't know which compiler versions are affected, to apply such path.

2021-10-12 10:21 UTC, bernhardkaindl commented
> @bernhardkaindl does that have anything to do with plumed or does it fail with vanilla gromacs as well?

It's a bug in vanilla gromacs-2020.6:

The missing the required include of `#include <limits>` is a bug in `gromacs-2020.6/src/gromacs/modularsimulator/modularsimulator.h` itself, this fails with the same error (if you have no `gcc@11.2.0`, spack builds it as a dependency, so not separate build of it outside of this command is needed, it just takes a long time to build gcc-11.2.0 if it's not built or installed yet, so you'd have to be patient and add `-v` to see that there is progress in the command):

`spack install -v gromacs@2020.6~mpi %gcc@11.2.0`

2021-10-12 10:35 UTC, w8jcik commented
I did more trials
- Gromacs `2020:2020.6` are affected by lack of this header.
- Gromacs `2021.2:2021.3` are fine with GCC 11.
- Gromacs `2021:2021.2` fail on something else with GCC 11

```cpp
src/gromacs/applied_forces/densityfitting/densityfitting.cpp:257:56:   required from here
  >> 2168    /home/user/.spack/root/opt/spack/linux-ubuntu21.10-skylake/gcc-11.2.0/gcc-11.2.0-bq4gxbw4tvajxa7t7qlxw5v34jhzg3zk/include/
             c++/11.2.0/type_traits:2954:7: error: static assertion failed: each argument type must be a complete class or an unbounded
              array
     2169     2954 |       static_assert((std::__is_complete_or_unbounded(
     2170          |       ^~~~~~~~~~~~~
```

2021-10-12 10:41 UTC, bernhardkaindl commented
> I did more trials

Good data, for 2020.06, this helps:
```py
     def patch(self):
+        filter_file('#include <queue>', '#include <queue>\n#include <limits>',
+                    'src/gromacs/modularsimulator/modularsimulator.h')
+        filter_file('#include <vector>', '#include <vector>\n#include <limits>',
+                    'src/gromacs/awh/biasparams.h')
```
Would you include this, possibly with a version check before it?

@w8jcik  I guess for the failed `static_assert`, could you make an upstream bug report? (independent of this PR or course)

2021-10-12 10:43 UTC, w8jcik commented
> Sure, but let me check GCC 10 as well. Or did you test it already?

No I didn't check GCC 10, but knowing about it would just be for updating the commit message.

Adding adding (if it already exists, a second) `#include <limits>` should always be OK, independent of the compiler, even independent on the gromacs version.

This would be good (no compiler check needed of course!):

```py
      def patch(self):
+        if self.spec.satisfies('@2020:2020.6'):
+            filter_file('#include <queue>', '#include <queue>\n#include <limits>',
+                        'src/gromacs/modularsimulator/modularsimulator.h')
+            filter_file('#include <vector>', '#include <vector>\n#include <limits>',
+                        'src/gromacs/awh/biasparams.h')
```
It works as expected here.

If you'd like, it would be ok for me approve this PR as-is, and run a 2nd PR for the gcc issue of 2020.x (and let 2021.x handled by upstream).

Would you add your review with an approval if I'd submit this as a new PR, requesting you as reviewer? Then we wouldn't mix two items into one PR.

2021-10-12 10:59 UTC, w8jcik commented
> Would you add your review with an approval if I'd submit this as a new PR, requesting you as reviewer? Then we wouldn't mix two items into one PR.

Yes, we can finish this PR and you can apply path separately.

2021-10-12 11:00 UTC, bernhardkaindl approved these changes

2021-10-12 11:00 UTC, bernhardkaindl commented
Done, can merge.

2021-10-12 11:01 UTC, merged