damask-{grid,mesh}: Use hdf5+hl as py-h5py uses it, cleanup LDFLAGS
LLNL/spack pull request #26680
Opened 2021-10-12 13:50 UTC by bernhardkaindl

@sethrj This PR is ready for **merge** or ***final merge-review***

# Latest Status: 
spack-maintainer and upstream approval by @MarDiehl:

@MarDiehl did a final rebuild from scratch no a new computer as well and reported (emphasis mine):
> installing from scratch works like a charm, ***green lights from my side.***

---
---
# Description

For reproduibility, this build-only update cleans up the build of the individual packages to use the same concretization of hdf5 for all packages, even when built independenty.

As a minor improvement, it cleans up the how the build flags are passed, pending further improvements in upstream `CMakeLists.txt` to enable passing which FFTW Libs to use flags as CMake variables without patching `CMakeLists.txt`

# Original message

@MarDiehl - I've built alpha4 and alpha5 with this. I it should explain and fix remaining issues:

> The package damask depends on py-damask which depends on py-h5py,
which depends hdf5@1.8.4:+hl. As spack can only use one concretisation
a build, 'spack install damask', spack is forced to use hdf5@1.8.4:+hl.
>
> When damask-grid is built without that concretisation in the picture,
e.g using 'spack install damask-grid', spack would use the hdf5~hl instead.
>
> To avoid producing two different builds of hdf5 (and damask-grid as result),
add +hl to the list of requested variants of damask-grid and -mesh.

Further explanation: the hdf5 libs are now added by CMake itself thru pkg-config, you should install pkg-config on your host as well if you build without spack. But some build machines might not have it, therefore keep is also as a depends_on in the recipes.

But it means you would not have to add -lhdf5_fortran to the CMakeLists, cmake and pkgconfig would take care of this as long as hdf5 provide the pkg-config file that enable it.

This cleanup therefore removes it. I hope it works for you too, at least in spack!

Using LDFLAGS to pass the FFTW libs didn't work, but to enable passing them without patching in the future, this cleanup uses a CMake variable which can be set as a CMake argument to add FFTW libs.

Ideally, the next improvement would be that the Alpha release should add `${FFTW_LIBS}` to the patched line. Then the damask recipes in `spack` don't have to filter the `CMakeLists.txt` to add it, and you can use it `-DFFTW_LIBS="..."` for other builds as well.

I hope this helps. If it works for you and you'd approve it, please add a comment that you approve this PR, we can then try to find a spack maintainer for merging it to develop.

2021-10-12 20:36 UTC, MarDiehl commented on var/spack/repos/builtin/packages/damask-grid/package.py
> -        filter_file(' -lhdf5 ', ' -lhdf5_fortran -lhdf5 ', 'CMakeLists.txt')
I am a little bit surprised that this patch is not required anymore. PETSc 3.16 does not add the Fortran library to the linker command anymore. This would work only if PETSc is build with `--download-hdf5-fortran-bindings=1` which will most likely change to `--with-hdf5-fortran-bindings` in the next release.

2021-10-12 20:40 UTC, MarDiehl commented on var/spack/repos/builtin/packages/damask-grid/package.py
>      depends_on('petsc@3.14.0:3.14,3.15.1:3.15', when='@3.0.0-alpha4')
DAMASK Grid and DAMASK mesh need MPI, so I believe `petsc+mpi` is needed (I was not aware of `petsc~mpi` when writing the package)

2021-10-12 20:48 UTC, MarDiehl commented
> Further explanation: the hdf5 libs are now added by CMake itself thru pkg-config, you should install pkg-config on your host as well if you build without spack. But some build machines might not have it, therefore keep is also as a depends_on in the recipes.

How does CMake/pkg-config takes care of this? Wouldn't that require to have something like `pkg_check_modules (HDF5 REQUIRED)` in `CMakeLists.txt`? Or is that a feature of `depends_on` when using cmake and having pkg-config available?

It still need to test, but so far it looks good to me.

2021-10-12 20:56 UTC, bernhardkaindl commented on var/spack/repos/builtin/packages/damask-grid/package.py
> -        filter_file(' -lhdf5 ', ' -lhdf5_fortran -lhdf5 ', 'CMakeLists.txt')
Hi, `-lhdf5_fortran` is already added by CMake because it runs pkg-config (which wasn't in `depends_on() initially, so that method failed at first) but now CMake and pkgconfig team up to get the linker flags which petsc wants you to use:
CMakeLists.txt:
```cmake
include (FindPkgConfig REQUIRED)
...
# Dummy project to determine compiler names and version
project (Prerequisites LANGUAGES)
set(ENV{PKG_CONFIG_PATH} "$ENV{PETSC_DIR}/$ENV{PETSC_ARCH}/lib/pkgconfig")
pkg_check_modules (PETSC REQUIRED PETSc>=3.12.0 PETSc<3.17.0)
```
This is enough, together with petsc delivering the flags using it's petsc.pc file for pkg-config:
```json
$ grep lhdf5_fortran `find ./opt/ -name petsc.pc
-lhdf5_hl_fortran -lhdf5_hl_f90cstub -lhdf5_hl -lhdf5_fortran -lhdf5_f90cstub -lhdf5 -lparmetis -lmetis -lm 
```
As you can see, your information *"PETSc 3.16 does not add the Fortran library to the linker command anymore.* is wrong.

Likewise the sentence *"This would work only if PETSc is build with --download-hdf5-fortran-bindings=1 which will most likely change to --with-hdf5-fortran-bindings in the next release"* does not appear to apply to spack:

Such flags don't appear in the spack recipe to build petsc from source (I hope you use it and not no load a precompiled petsc!) In spack, petsc does not download hdf5 bindings or so, everthing is compiled by separate build recipes from source.

2021-10-12 21:01 UTC, bernhardkaindl commented on var/spack/repos/builtin/packages/damask-grid/package.py
> -        filter_file(' -lhdf5 ', ' -lhdf5_fortran -lhdf5 ', 'CMakeLists.txt')
You can test my branch from scratch in a new spack installation in a clean way and it should just work (On a freash install of Ubuntu 18.04, just python3, make, patch and gcc (etc - maybe build-essential) need to be installed - it will take quite a while of course)
```py
mkdir spack-damask
cd spack-damask
HOME=$PWD # Yes, this is to skip any settings you might have in your normal $HOME, to be sure.
git clone https://github.com/bernhardkaindl/spack/tree/bk/cleanup/damask
cd spack
bin/spack install --verbose damask
```
I the build log, you should find the added hdf5_fortran library linker flags.
Otherwise, you can checkout my branch (if your git tree is clean - you can use `git stash` to clean it) using:
```py
spack install gh
spack load gh
gh co 26680
```

2021-10-12 21:10 UTC, bernhardkaindl commented
> How does CMake/pkg-config takes care of this? Wouldn't that require to have something like `pkg_check_modules (HDF5 REQUIRED)` in `CMakeLists.txt`? Or is that a feature of `depends_on` when using cmake and having pkg-config available?

This line is in `CMakeLists.txt`: `pkg_check_modules (PETSC REQUIRED PETSc>=3.12.0 PETSc<3.17.0)`

2021-10-12 21:31 UTC, bernhardkaindl commented
This is the core of the new pushed commit (likewise for `damask-mesh`)
```py
@@ -17,8 +17,8 @@ class DamaskGrid(CMakePackage):
 
     depends_on('pkgconfig', type='build')
     depends_on('cmake@3.10:', type='build')
-    depends_on('petsc@3.14.0:3.14,3.15.1:3.15', when='@3.0.0-alpha4')
-    depends_on('petsc@3.14.0:3.14,3.15.1:3.16', when='@3.0.0-alpha5')
+    depends_on('petsc+hdf5+mpi@3.14.0:3.14,3.15.1:3.15', when='@3.0.0-alpha4')
+    depends_on('petsc+hdf5+mpi@3.14.0:3.14,3.15.1:3.16', when='@3.0.0-alpha5')
 
     #
     # The package damask depends on py-damask which depends on py-h5py,
@@ -29,7 +29,8 @@ class DamaskGrid(CMakePackage):
     # e.g using 'spack install damask-grid', spack would use the hdf5~hl instead.
     #
     # To avoid producing two different builds of hdf5 (and damask-grid as result),
-    # add +hl to the list of requested variants.
+    # add +hl to the list of requested variants. This also selects +fortran+hl for
+    # the hdf5 depencency of petsc+hdf5+mpi above (only one concretisatiion of hdf5):
     #
     depends_on('hdf5+fortran+hl')
     depends_on('fftw+mpi')
```
It is actually
```py
     depends_on('hdf5+fortran+hl')
```
Which updates the `petsc+hdf5+mpi` variant of petsc to use the fortran+mpi variant of hdf5 - because there can only be one concretizatin of the hdf5 recipe in a single `spack install` command - which forces the complete build to use the hdf5 library which you want: `+fortran`, because you grid/mesh needs it and `+hl` becuase when building `damask-py`, `py-h4py` selects `+hl` as well.

2021-10-12 21:42 UTC, MarDiehl commented
> As you can see, your information "PETSc 3.16 does not add the Fortran library to the linker command anymore. is wrong.

> Likewise the sentence "This would work only if PETSc is build with --download-hdf5-fortran-bindings=1 which will most likely change to --with-hdf5-fortran-bindings in the next release" does not appear to apply to spack:

> Such flags don't appear in the spack recipe to build petsc from source (I hope you use it and not no load a precompiled petsc!) In spack, petsc does not download hdf5 bindings or so, everthing is compiled by separate build recipes from source.

I can confirm that I have `-lhdf5_fortran` in my PETSc link command when I install it with spack. This still surprises me because the hand-build PETSc does not add it to the linker command even if an existing HDF5 installation with Fortran bindings is used. I've checked the `package.py` from PETSc and it seems to do the same thing as I do during a manual installation. Anyways, I'm glad that spack does the right thing here and the build instructions can be simplified.

2021-10-12 21:49 UTC, bernhardkaindl commented
> One common hdf5+fortran+hl build for all of Damask:
> *   `+fortran`, because you grid/mesh needs it and
> *   `+hl` because when building py-damask, it's dependency py-h4py selects +hl. So we use the same variant for grid/mesh too.

I had to push a final commit to make the hdf5 pulled in by `py-h5py` of `py-damask` use the same `hdf5+fortran+hl` variant, even when `spack install py-damask` is used for an isolated build of `py-damask` and not build a different variant of `hdf5`:
```py
@@ -22,5 +22,8 @@ class PyDamask(PythonPackage):
     depends_on('py-h5py')
     depends_on('py-matplotlib')
     depends_on('py-pyyaml')
+    # Force the hdf5+hl variant added by py-h5py to also have +fortan.
+    # This makes that hdf5 to use the same variants as damask-grid and damask-mesh:
+    depends_on('hdf5+fortran')
 
     build_directory = 'python'
```

2021-10-12 21:55 UTC, bernhardkaindl commented
> I can confirm that I have `-lhdf5_fortran` in my PETSc link command when I install it with spack. This still surprises me because the hand-build PETSc does not add it to the linker command even if an existing HDF5 installation with Fortran bindings is used. I've checked the `package.py` from PETSc and it seems to do the same thing as I do during a manual installation. Anyways, I'm glad that spack does the right thing here and the build instructions can be simplified.

Thanks for the comment. It could be that `spack` or some special tool employed in the build adds the used linker command to the `petsc.pc` file for pkg-config.

2021-10-13 09:31 UTC, MarDiehl commented
I tried installing, but when I use `spack install damask` it tries to install `mesa` with `llvm@13` which does not work (https://github.com/spack/spack/commit/2e9512fe8b5127a1748959738af2549b9a325914#diff-790ecc62e3386b743c402daf170e736edf53a04af996e9422dd98afcf6d0865e). `spack install mesa` works as expected, i.e. it uses `llvm@12`.
Installing packages into two environments, i.e. `spack install damask-grid damask-mesh` and `spack install py-damask` (after manual installation of `mesa`) works fine. Some package needed for `py-damask` seems to require `llvm@13`.

2021-10-13 10:56 UTC, bernhardkaindl commented
> I tried installing, but when I use `spack install damask` it tries to install `mesa` with `llvm@13` which does not work ([2e9512f#diff-790ecc62e3386b743c402daf170e736edf53a04af996e9422dd98afcf6d0865e](https://github.com/spack/spack/commit/2e9512fe8b5127a1748959738af2549b9a325914#diff-790ecc62e3386b743c402daf170e736edf53a04af996e9422dd98afcf6d0865e)). `spack install mesa` works as expected, i.e. it uses `llvm@12`. Installing packages into two environments, i.e. `spack install damask-grid damask-mesh` and `spack install py-damask` (after manual installation of `mesa`) works fine. Some package needed for `py-damask` seems to require `llvm@13`.

@MarDiehl I've seen only mesa which needs llvm, and without my fix linked above, it tries to use llvm@13.0.0 simply because it is the newest version. With my commit which you link above, mesa is restricted to llvm@12 and uses it instead. I didn't encounter another use of llvm in the build. My commit fixing mesa to limit itself to llvm@12 is in develop and in the branch of this PR AFAICS.

2021-10-13 20:24 UTC, MarDiehl commented
> @MarDiehl I've seen only mesa which needs llvm, and without my fix linked above, it tries to use llvm@13.0.0 simply because it is the newest version. With my commit which you link above, mesa is restricted to llvm@12 and uses it instead. I didn't encounter another use of llvm in the build. My commit fixing mesa to limit itself to llvm@12 is in develop and in the branch of this PR AFAICS.

I'm now building from scratch (even on a different computer) using your branch and `spack install damask` installs `llvm@12.0.1`. It will still take a while until the installation is finished, but I think everything is working as expected.

2021-10-14 06:00 UTC, MarDiehl commented
installing from scratch works like a charm, green lights from my side.

2021-10-14 12:13 UTC, sethrj requested changes

2021-10-14 12:13 UTC, sethrj commented on var/spack/repos/builtin/packages/damask-grid/package.py
> +                '-DFFTW_LIBS={0}'.format(fftw_libs)]
```suggestion
        args = [self.define('DAMASK_SOLVER', 'grid'),
                self.define('FFTW_LIBS', fftw_libs)]                
```

2021-10-14 12:13 UTC, sethrj commented on var/spack/repos/builtin/packages/damask-grid/package.py
> +    depends_on('hdf5+fortran+hl')
The canonical way to do this is either install damask and damask-grid together in an environment, or to use `packages.yaml` to set default variants for HDF5 that fit your site installation's particular needs. Package dependencies should reflect *requirements*, rather than defaults. Would you be ok with reverting this and adding a note for users? We can't anticipate all the possible "make life easier when users install packages separately" cases.

2021-10-14 12:13 UTC, sethrj commented on var/spack/repos/builtin/packages/damask-grid/package.py
> +    depends_on('petsc+hdf5+mpi@3.14.0:3.14,3.15.1:3.16', when='@3.0.0-alpha5')
Alternatively you could leave the original for versioning, and add an additional requirement for the variants:
```suggestion
      depends_on('petsc+hdf5+mpi')
      depends_on('petsc@3.14.0:3.14,3.15.1:3.15', when='@3.0.0-alpha4')
      depends_on('petsc@3.14.0:3.14,3.15.1:3.16', when='@3.0.0-alpha5')
```

2021-10-14 12:13 UTC, sethrj commented on var/spack/repos/builtin/packages/py-damask/package.py
> +    depends_on('hdf5+fortran')
See comments above

2021-10-14 12:13 UTC, sethrj commented on var/spack/repos/builtin/packages/damask-mesh/package.py
> +    depends_on('hdf5+fortran+hl')
See coments above

2021-10-14 14:17 UTC, bernhardkaindl commented on var/spack/repos/builtin/packages/damask-grid/package.py
> +    depends_on('hdf5+fortran+hl')
No, damask needs `hdf5+fortran`, and nothing is gained by building hdf5 twice in two different ways. It required conduct a really deep analysis to understand what
was going on here, and after all, spack is for convenience, to build software without having to know all the details how it is built. It *is* about making life easier, and while we can't do magic, spack can (it is it's mission) and should make it easier.

2021-10-14 14:37 UTC, bernhardkaindl commented on var/spack/repos/builtin/packages/damask-mesh/package.py
> +    depends_on('hdf5+fortran+hl')
See my comment above likewise, and thanks for leaving me the option!

2021-10-14 14:41 UTC, bernhardkaindl commented on var/spack/repos/builtin/packages/damask-grid/package.py
> +                '-DFFTW_LIBS={0}'.format(fftw_libs)]
applied.

2021-10-14 17:54 UTC, sethrj commented on var/spack/repos/builtin/packages/damask-grid/package.py
> +    depends_on('hdf5+fortran+hl')
> It required conduct a really deep analysis to understand what was going on here

This issue isn't specific to HDF5: if you want to guarantee that multiple spack packages work together without subtle conflicts, they *need* to be part of the same DAG. You do that by either creating an environment with `concretization: together` or having a package that depends on both of them. It looks indeed like the package `damask` is designed with exactly that purpose.

The "convenience" factor of not having similar HDF5 builds is a secondary issue that is easily solved with a `packages.yaml` tweak, or letting the concretizer prefer existing HDF5 installations. Your real problem is that spack can't know from isolated installs that you want two packages to use the same version of HDF5. Indeed, your proposed solution isn't even a complete fix: if you install damask-grid, then update spack and it defines a new HDF5 version, and then install `damask-mesh`, you'll end up with two different *conflicting* HDF5 versions even though both will have `+fortran+hl`.

I really must insist that `depends_on` means that it's a real dependency and not a hint to make it work better with other packages.

2021-12-28 09:08 UTC, MarDiehl commented
I suggest to close this, I'll implement the accepted changes in a new branch

2021-12-28 15:58 UTC, sethrj commented on var/spack/repos/builtin/packages/damask-grid/package.py
> +    depends_on('hdf5+fortran+hl')
@bernhardkaindl I don't see how my point above has been addressed. Again, building the `damask` metapackage automatically builds `hdf5+fortran+hl`, as would building in an environment with "together" concretizations. No other sets of packages can guarantee they are sharing exactly the same dependencies: this is particularly a problem if you install one set of software (e.g. python and jupyterlab) then update spack and then update another software dependency, leading to multiple conflicting versions of the toolchain.

2021-12-29 14:47 UTC, alalazo commented
@MarDiehl Feel free to go ahead and submit a new PR. In the description you can say that it:
```
closes #26680
```
to have this PR closed automatically once the new PR is merged.

2022-01-08 11:50 UTC, closed without merging