r-imager: add depends_on('r+X') and bump version
LLNL/spack pull request #26697
Opened 2021-10-13 01:43 UTC by bernhardkaindl

Add depends_on('x11') to fix the build and bump the version

2021-10-13 04:17 UTC, glennpj requested changes
~~The `r-cairo` and `r-plyr` dependencies are no longer required beginning with version `0.42.3`. Can you set the appropriate constraints on those dependencies?~~

**Update**: Sorry, ignore the comment above. The constraints are already there.

2021-10-13 04:17 UTC, glennpj commented on var/spack/repos/builtin/packages/r-imager/package.py
> +    depends_on('libx11')
We need to make sure that R was built with X11 support. That could be more than just `libx11`. Do the following instead:
```suggestion
    depends_on('r+X')
```

2021-10-13 08:47 UTC, bernhardkaindl commented
@glennpj I applied your 'r+X' change, it still builds. re-requesting review, thanks!

2021-10-14 00:02 UTC, glennpj approved these changes

2021-10-14 00:02 UTC, merged