glib: Pass --test=root: Skip tests which we cannot make pass
LLNL/spack pull request #26693
Opened 2021-10-12 23:52 UTC by bernhardkaindl

glib has a few tests which have external dependices or
try to access the X server. We cannot run those.

This commit makes up pass the glib testuite! With it, other
packages which depend on glib can be build with --test=all!

2021-10-15 05:40 UTC, alalazo requested changes
LGTM. Only a typo.

2021-10-15 05:40 UTC, alalazo commented on var/spack/repos/builtin/packages/glib/package.py
> +        """A few glib tests have external dependices / try to access the X server"""
```suggestion
        """A few glib tests have external dependencies / try to access the X server"""
```

2021-10-22 22:37 UTC, michaelkuhn requested changes

2021-10-22 22:37 UTC, michaelkuhn commented on var/spack/repos/builtin/packages/glib/package.py
> +
This does not fix the test failures for me. Previously, I got the following failures:
```
 36/273 glib:glib / fileutils                           FAIL             1.67s   killed by signal 6 SIGABRT
109/273 glib:gio / appinfo                              FAIL             0.92s   killed by signal 5 SIGTRAP
124/273 glib:gio / desktop-app-info                     FAIL             0.75s   killed by signal 5 SIGTRAP
```
With this change, I still get:
```
 35/266 glib:glib / fileutils                           FAIL             1.33s   killed by signal 6 SIGABRT
```
The `fileutils` failure might be due to NFS, the other two are due to `update-desktop-database` not being available. I would prefer to only remove those instead of disabling unrelated tests (replacing `host_machine.system() != 'windows'` seems to disable quite a bit).

2021-10-23 16:33 UTC, bernhardkaindl commented on var/spack/repos/builtin/packages/glib/package.py
> +
@michaelkuhn Adressed your requested changes: reverted skipping `gio: !windows` tests, skip `glib/tests/fileutils`.
This should be all, even on your machine.

2021-10-28 22:02 UTC, michaelkuhn requested changes

2021-10-28 22:02 UTC, michaelkuhn commented on var/spack/repos/builtin/packages/glib/package.py
> +        filter_file("'fileutils' : {},", '', 'gobject/tests/meson.build')
`fileutils` is in `glib/tests/meson.build`.

2021-10-29 14:16 UTC, bernhardkaindl commented on var/spack/repos/builtin/packages/glib/package.py
> +        filter_file("'fileutils' : {},", '', 'gobject/tests/meson.build')
@michaelkuhn fixed: 
```patch
diff -U0 spack-src/glib/tests/meson.build{~,}
--- spack-src/glib/tests/meson.build~
+++ spack-src/glib/tests/meson.build
@@ -25 +25 @@
-  'fileutils' : {},
+  
```

2021-10-29 14:18 UTC, bernhardkaindl commented
@alalazo @michaelkuhn Your requested changes are applied: Ready for approve of your requested changes, thanks!

2021-10-29 14:20 UTC, michaelkuhn approved these changes
LGTM

2021-10-29 15:58 UTC, glennpj approved these changes
LGTM

2021-11-01 16:32 UTC, alalazo approved these changes

2021-11-01 16:33 UTC, merged