scr/veloc: component releases
LLNL/spack pull request #26716
Opened 2021-10-13 17:00 UTC by CamStan

Update the ECP-VeloC component packages in preparation for an
upcoming scr@3.0rc2 release.

All
- Add new release versions
- Add new `shared` variant for all components
- Add zlib link dependency to packages that were missing it

axl
- Add independent vendor async support variants

rankstr
- Update older version sha that fails checksum on install

#### Update
All
- Add maintainers
- Use `self.define` and `self.define_from_variant` to clean up `cmake_args`

2021-10-13 17:13 UTC, CamStan commented
I can add myself as a maintainer.

2021-10-13 18:56 UTC, tldahlgren requested changes
Confirmed all of the new sha256 values.

Recommend using `CMakePackage`'s `self.define_from_variant`.

2021-10-13 18:56 UTC, tldahlgren commented on var/spack/repos/builtin/packages/axl/package.py
> +        variant_bool = lambda option: 'ON' if (option in self.spec) else 'OFF'
Why not use `CMakePackage`'s `define_from_variant` (i.e., `self.define_from_variant(<cmake-var>[, <variant>)`)?

See https://spack.readthedocs.io/en/latest/build_systems/cmakepackage.html#adding-flags-to-cmake.

2021-10-13 18:56 UTC, tldahlgren commented on var/spack/repos/builtin/packages/axl/package.py
> +            args.append('-DBUILD_SHARED_LIBS=%s' % variant_bool('+shared'))
As mentioned above, you could be using `self.define_from_variant` here, e.g., `self.defined_from_variant('ENABLE_BBAPI_FALLBACK', 'bbapi_fallback')`.

2021-10-13 18:56 UTC, tldahlgren commented on var/spack/repos/builtin/packages/er/package.py
> +                args.append('-DBUILD_SHARED_LIBS=OFF')
```suggestion
            args.append(self.define_from_variant('BUILD_SHARED_LIBS', 'shared'))
```

2021-10-13 18:56 UTC, tldahlgren commented on var/spack/repos/builtin/packages/kvtree/package.py
> +        if '+mpi' in self.spec:
You *could* use `args.append(self.define_from_variant('MPI'))` here in place of being explicit with `-DMPI=`.

Spack will automatically associate the `mpi` variant (i.e., <cmake-var>.lower() for the name of the variant).

2021-10-13 18:56 UTC, tldahlgren commented on var/spack/repos/builtin/packages/kvtree/package.py
> +        if '+mpi' in self.spec:
Same goes for setting the argument in the `spath` package below.

2021-10-13 18:56 UTC, tldahlgren commented on var/spack/repos/builtin/packages/er/package.py
> +                args.append('-DBUILD_SHARED_LIBS=OFF')
Same goes for setting the argument in the following packages (below):
- `kvtree`
- `rankstr`
- `shuffile`
- `spath`

2021-10-13 21:15 UTC, CamStan commented on var/spack/repos/builtin/packages/axl/package.py
> +        variant_bool = lambda option: 'ON' if (option in self.spec) else 'OFF'
That is so much better! Thank you for the link. I'll make these changes.

2021-10-15 19:10 UTC, CamStan commented
@tldahlgren, this is ready for another look.

2021-10-18 17:34 UTC, tldahlgren commented
Looks like the `scr` build failed.  See https://cdash.spack.io/buildSummary.php?buildid=337976.

2021-10-18 19:41 UTC, tldahlgren reviewed
Confirmed the sha256 for all new/modified versions.

Would appreciate insight into why the pipeline build (linked above) failed.

2021-10-18 19:41 UTC, tldahlgren commented on var/spack/repos/builtin/packages/er/package.py
> +    depends_on('shuffile~shared', when='@0.1: ~shared')
FWIW You could put this in a `for` loop over the variants to tighten the code.

2021-10-18 19:41 UTC, tldahlgren commented on var/spack/repos/builtin/packages/er/package.py
> +                args.append(self.define('ER_LINK_STATIC', True))
So I understand, this option does not need to be set if the build occurs on a `cray` for version `0.1.0` on?

2021-10-18 19:41 UTC, tldahlgren commented on var/spack/repos/builtin/packages/rankstr/package.py
> +    version('0.0.2', sha256='b88357bf88cdda9565472543225d6b0fa50f0726f6e2d464c92d31a98b493abb')
Why did the hash/checksum for this version change?

2021-10-19 23:59 UTC, CamStan commented on var/spack/repos/builtin/packages/rankstr/package.py
> +    version('0.0.2', sha256='b88357bf88cdda9565472543225d6b0fa50f0726f6e2d464c92d31a98b493abb')
This was a mistake I'd made last time these components were updated. I had changed the url for each component, but forgot to update the checksums. All the others got fixed back then, but in testing the checksums this time around I discovered I missed this one.

https://github.com/spack/spack/pull/22763/files

2021-10-19 23:59 UTC, CamStan commented on var/spack/repos/builtin/packages/er/package.py
> +                args.append(self.define('ER_LINK_STATIC', True))
That is correct as these `<name>_LINK_STATIC` options are no longer exposed to the user in latest version as this is one thing `~shared` will enable automatically.

Now, whether `~shared` is now needed for `cray`, I don't have a solid answer, but I don't think so. A recent update was made to the `scr` package to disable this by default, even on `cray`, so this might true for the components as well, but we haven't been able to test on a `cray` system as of yet (hopefully soon, whereafter adjustments might need to be made).
**Note:** The `scr` package will be getting updated with the `shared` variant soon as well.

@gonsie will likely have better insight on this.

2021-10-20 00:18 UTC, CamStan commented
> Would appreciate insight into why the pipeline build (linked above) failed.

The latest version of `axl` removed support for a particular async interface (`CPPR`),
https://github.com/ECP-VeloC/AXL/commit/1afef9ac19c9307498b5db54eabafbf70d81359c#diff-b8ab8c9a715f1fed4fec1206c88b3c33cf0ba2df394cf2f00d43ac2a673d3674

 but `scr@3.0rc1` still attempts to reference it
https://github.com/LLNL/scr/blob/5273576b2836b1990a6771bb1e1ddd5fdc1a4eec/src/scr_util_mpi.c#L310

I added the `scr` package to this PR to simply lock in dependency versions for `scr@3.0rc1` to the component versions released at the same time, so this should pass now. 🤞 
A bigger update to the `scr` package is coming soon where I'll do the same for the `scr@3.0rc2` release with these component releases.

2021-10-22 01:05 UTC, tldahlgren approved these changes

2021-10-22 01:05 UTC, merged