py-pygraphviz: Add version 1.7
LLNL/spack pull request #26712
Opened 2021-10-13 15:33 UTC by haralmha

2021-10-13 19:24 UTC, adamjstewart requested changes

2021-10-13 19:24 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pygraphviz/package.py
> +    maintainer = 'haralmha'
```suggestion
    maintainers = ['haralmha']
```

2021-10-13 19:24 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pygraphviz/package.py
> +    depends_on('graphviz')
```suggestion
    depends_on('python@3.7:', type=('build', 'run'))
    depends_on('py-setuptools', type='build')
    depends_on('graphviz')
```

2021-11-02 15:38 UTC, adamjstewart approved these changes, later dismissed

2021-11-02 15:39 UTC, adamjstewart commented
@spackbot re-run pipeline

2021-11-11 09:34 UTC, iarspider commented
@spackbot re-run pipeline

2021-11-11 16:32 UTC, adamjstewart commented
@spackbot re-run pipeline

2021-11-16 08:06 UTC, iarspider commented
@spackbot re-run pipeline

2021-11-16 18:52 UTC, adamjstewart commented
@haralmha can you try rebasing on develop? I think GitLab is stuck with an old commit.

2021-11-18 05:08 UTC, adamjstewart approved these changes

2021-11-18 05:08 UTC, merged