Improved error messages from clingo
LLNL/spack pull request #26719
Opened 2021-10-13 19:16 UTC by becker33

Generating legible error messages from the new clingo concretizer has proven challenging, in part because the unsatisfiable cores returned from clingo solves are not minimal and cannot be minimized with reasonable performance so far.

This PR adds error message sentinels to the solve, attached to the rules that could fail a solve. The unsat core is then restricted to these messages, which makes the minimization problem tractable. Errors that can only be generated by a bug in the logic program or generating code are prefaced with `Internal error` to make clear to users that something has gone wrong on the Spack side of things.

Examples:
```
$ spack spec hdf5 ^mpich ^openmpi
Input spec
--------------------------------
hdf5
    ^mpich
    ^openmpi

Concretized
--------------------------------
==> Error: hdf5 ^mpich ^openmpi is unsatisfiable, conflicts are:
  error("All dependencies must be reachable from root")
  error("Virtual packages must be satisfied by a unique provider")
```

On an x86_64 system
```
$ spack spec zlib target=power9
Input spec
--------------------------------
zlib arch=darwin-None-power9

Concretized
--------------------------------
==> Error: zlib arch=darwin-None-power9 is unsatisfiable, conflicts are:
  error("Each node must have exactly one compiler")
  error("No satisfying compiler available is compatible with a satisfying target")
```

2021-10-27 19:16 UTC, tldahlgren requested changes

2021-10-27 19:16 UTC, tldahlgren commented on lib/spack/spack/error.py
> +        if required is not None:
Is it sufficient to just use `if required:` here?

2021-10-27 19:16 UTC, tldahlgren commented on lib/spack/spack/error.py
> +            assert not conflicts  # can't mix formats
Per Todd, we should be raising exceptions outside of test modules.  Should this be raising a different SpackError exception?

2021-10-27 19:16 UTC, tldahlgren commented on lib/spack/spack/solver/asp.py
> +        assert self.control
Same assert issue mentioned for `error.py`.

2021-10-27 19:16 UTC, tldahlgren commented on lib/spack/spack/solver/asp.py
> +        assert self.control
Replace with SpackError exception.

2021-10-27 19:16 UTC, tldahlgren commented on lib/spack/spack/concretize.py
>      return [s.copy() for s in result.specs]
Given the duplicated code, should this be refactored into a common method used by `cmd/solve.py` (above changes) and `concretize.py`?

2021-10-27 22:45 UTC, tgamblin requested changes

2021-10-27 22:45 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> +
So the unfortunate thing about this is that it's error prone: we have to write these strings in two places.  We can get around this by inspecting the `clingo` AST through the API -- this code got all the error strings for me:

```python
        from clingo.ast import ASTType, ProgramBuilder, parse_string
        with ProgramBuilder(self.control) as bld:
            def visit(node):
                if node.ast_type == ASTType.Rule:
                    for term in node.body:
                        if term.ast_type == ASTType.Literal:
                            if term.atom.ast_type == ASTType.SymbolicAtom:
                                if term.atom.symbol.name == "error":
                                    print(term.atom.symbol.arguments[0])
            path = os.path.join(parent_dir, 'concretize.lp')
            parse_string(open(path).read(), visit)
```

I put that right before the place we load `concretize.lp` in `PyclingoDriver.solve()`.  Can you test that with both the bootstrapped `clingo` and a build of latest `clingo`?  I guess I've already done the latter.

If you do that you should be able to generate your facts (or rather assumptions) right after loading `concretize.lp`.  I think to do this inspection at the same time as loading (i.e., not load twice) we would need to add AST components ourselves as part of traversal, but we can skip that -- I think sticking this in a method on `PyclingoDriver` to get the errors separately from loading the file is fine right now since parsing `concretize.lp` takes no time.

I think this will make it more natural to add more error messages to `concretize.lp` -- we can just add more `error()` lines to rules.  If we need to add messages to more than just rules I think we can worry about that in a follow-on PR.

I think `PyclingoDriver` is the right place for this vs. setup b/c it's really part of the logic program -- not part of the input facts (even if `error()` assumptions are added in a similar way).

2021-10-27 22:45 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> +    def minimize_core(self, core):
This needs a good docstring.

2021-10-27 22:45 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> +    def format_core(self, core):
This needs a good docstring

2021-10-27 22:45 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> +        return [self.minimize_core(core) for core in self.cores]
Do you ever see more than one?  I never have but it doesn't mean it couldn't happen.

2021-10-27 22:45 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> +        self.error_messages()
Delete with move of error setup to `PyclingoDriver`

2021-10-27 22:45 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> +    def fact(self, head, assumption=False):
update docstring with arg descriptions

2021-10-27 22:45 UTC, tgamblin commented on lib/spack/spack/concretize.py
> +        tty.die("Unsatisfiable spec generated the following core(s):", *conflicts)
I think we should print out something like:

```python
tty.error("Unsatisfiable spec.", "Analyzing conflicts. This may take some time...")
conflicts = result.format_minimal_cores()
tty.die("Concretization failed with the following issues:", *conflicts)
```

So that you know before the core minimization that it's going to happen (you could also Ctrl-C at this point if you know what the problem likely is).

2021-10-27 22:55 UTC, becker33 commented on lib/spack/spack/error.py
> +        if required is not None:
No -- the required value could be `False`.

2021-10-27 22:58 UTC, becker33 commented on lib/spack/spack/solver/asp.py
> +        return [self.minimize_core(core) for core in self.cores]
You can see more than one, but I don't remember what I did that made that happen. I haven't seen it with the most recent version of the code though, so I'm not certain whether it was an artifact of an earlier error.

2021-10-28 01:39 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> +        return [self.minimize_core(core) for core in self.cores]
I think it’s just data-dependent. I just hadn’t seen it at all. Cool!

2021-10-28 04:50 UTC, tgamblin commented on lib/spack/spack/error.py
> +            assert not conflicts  # can't mix formats
If this happens it's a programming error. i.e., you should change your code to avoid it, not handle it in an exception block.  So an assertion is fine.

That said, this should have documentation for the parameters, and the split parameter thing going on here is kind of awkward.  I think it is ok in this instance because it will go away when the old concretizer does.

2021-10-28 15:22 UTC, becker33 commented on lib/spack/spack/concretize.py
> +        tty.die("Unsatisfiable spec generated the following core(s):", *conflicts)
With only the error messages in the core, core minimization is only taking <2 seconds for solves that take >10 seconds. I'm not sure how useful that message is given the relative runtimes.

2021-10-28 20:05 UTC, tldahlgren reviewed
Thanks for the refactor.

2021-10-29 00:15 UTC, tgamblin commented on lib/spack/spack/concretize.py
> +        tty.die("Unsatisfiable spec generated the following core(s):", *conflicts)
I think it's still useful *in case* it starts taking more time.

2021-10-29 00:23 UTC, tgamblin submitted a review, later dismissed

2021-10-29 00:28 UTC, tldahlgren submitted a review, later dismissed

2021-10-29 03:46 UTC, tgamblin submitted a review, later dismissed

2021-10-29 04:03 UTC, tgamblin submitted a review, later dismissed

2021-10-29 09:13 UTC, haampie commented
parse_files is top-level clingo.parse_files, but even with that change tests do not pass (    'clingo.ast.AST' object has no attribute 'ast_type')

2021-11-02 13:50 UTC, tgamblin approved these changes
@becker33 this is ready IMO. Can you squash it?

2021-11-02 17:55 UTC, merged