py-jupytext: add new package
LLNL/spack pull request #26732
Opened 2021-10-14 08:46 UTC by vvolkl

2021-10-14 18:45 UTC, adamjstewart requested changes

2021-10-14 18:45 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-jupytext/package.py
> +    depends_on('py-markdown-it-py', type=('build', 'run'))
```suggestion
    depends_on('py-markdown-it-py@1.0:1', type=('build', 'run'))
```

2021-10-14 18:45 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-jupytext/package.py
> +    depends_on('py-jupyter-packaging', type=('build', 'run'))
It doesn't seem like this dep is used unless we are building the jupyterlab extensions?

2021-10-14 18:45 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-markdown-it-py/package.py
> +    depends_on('py-setuptools', type='build')
The deps for this one are hidden in `setup.cfg`:
```
install_requires =
        attrs>=19,<22
        typing_extensions>=3.7.4;python_version<'3.8'
python_requires = ~=3.6
```

2021-10-14 18:45 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mdit-py-plugins/package.py
> +    depends_on('py-setuptools', type='build')
Same here:
```
install_requires =
        markdown-it-py~=1.0
python_requires = ~=3.6
```

2021-10-15 21:50 UTC, vvolkl commented
@adamjstewart Thanks for the comments! Updated now.

2021-10-15 21:54 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-markdown-it-py/package.py
> +    depends_on('py-typing-extensions@3.7.4:', type=('build', 'run'), when='^python@:3.8')
```suggestion
    depends_on('py-attrs@19:21', type=('build', 'run'))
    depends_on('py-typing-extensions@3.7.4:', type=('build', 'run'), when='^python@:3.7')
```
Spack version ranges are inclusive.

2021-10-15 21:54 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-markdown-it-py/package.py
> +    depends_on('python@3.6:',   type=('build', 'run'))
```suggestion
    depends_on('python@3.6:3',   type=('build', 'run'))
```
`~=` is different than `>=`

2021-10-15 21:54 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mdit-py-plugins/package.py
> +    depends_on('python@3.6:', type=('build', 'run'))
```suggestion
    depends_on('py-markdown-it-py@1.0:1', type=('build', 'run'))
    depends_on('python@3.6:3', type=('build', 'run'))
```

2021-10-15 22:26 UTC, vvolkl commented on var/spack/repos/builtin/packages/py-markdown-it-py/package.py
> +    depends_on('python@3.6:',   type=('build', 'run'))
Planning for python 4 already? That's futureproof :)

2021-10-16 16:30 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-jupytext/package.py
> +    depends_on('py-jupyterlab', type=('build', 'run'))
Is this dependency actually needed? I don't see it listed in the `setup.py`.

2021-10-16 17:47 UTC, vvolkl commented on var/spack/repos/builtin/packages/py-jupytext/package.py
> +    depends_on('py-jupyterlab', type=('build', 'run'))
Not sure if it's actually needed, have it from here: https://github.com/mwouts/jupytext/blob/main/pyproject.toml#L2

2021-10-17 16:06 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-jupytext/package.py
> +    depends_on('py-jupyterlab', type=('build', 'run'))
Spack doesn't currently use that file, we run `python setup.py install` instead. Can you remove it and see if the build succeeds without downloading that dependency?

2021-10-17 20:21 UTC, vvolkl commented on var/spack/repos/builtin/packages/py-jupytext/package.py
> +    depends_on('py-jupyterlab', type=('build', 'run'))
Works indeed without `py-jupyterlab`, so I removed it as a dependency.

2021-10-17 23:51 UTC, adamjstewart approved these changes

2021-10-17 23:51 UTC, merged