py-gevent: add version 1.5
LLNL/spack pull request #26731
Opened 2021-10-14 08:43 UTC by vvolkl

2021-10-14 16:16 UTC, tldahlgren reviewed
Confirmed the sha256.

2021-10-14 16:59 UTC, adamjstewart requested changes
Dependencies need to be updated too

2021-10-14 17:18 UTC, vvolkl commented
@adamjstewart ok I'll check -- I was mostly trying to fix a build failure I encountered with the previous version 1.3. It seemed to work ok now, but I'll take a look at the repo to catch any range changes and optional ones

2021-10-15 21:39 UTC, adamjstewart requested changes
It's unclear to me if cffi is actually required on systems other than Windows, but I'm fine with leaving it in there like it already was.

2021-10-15 21:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-gevent/package.py
> +    depends_on('py-cffi@1.12.3:',        type=('build', 'run'), when='@1.5.0:')
```suggestion
    depends_on('py-cffi@1.12.2:',        type=('build', 'run'), when='@1.5.0:')
```

2021-10-15 21:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-gevent/package.py
>      depends_on('python@2.7:2.8,3.4:',   type=('build', 'run'))
```suggestion
    depends_on('python@2.7:2.8,3.4:',   type=('build', 'run'))
    depends_on('python@2.7:2.8,3.5:',   type=('build', 'run'), when='@1.5:')
```

2021-10-15 21:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-gevent/package.py
> +    depends_on('py-setuptools@24.2:',   type='build', when='@:1.4.99')
```suggestion
    depends_on('py-setuptools@24.2:',   type='build', when='@:1.4')
```
Same for others

2021-10-16 16:26 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-gevent/package.py
> +    depends_on('py-greenlet@0.4.14:',   type=('build', 'run'), when='@1.5.0:')
```suggestion
    depends_on('py-setuptools@24.2:',   type='build', when='@:1.4')
    depends_on('py-setuptools@40.8:', type='build', when='@1.5:')
    depends_on('py-cython@0.27:',       type='build', when='@:1.4')
    depends_on('py-cython@0.29.14:',    type='build', when='@1.5:')
    depends_on('py-cffi@1.4:',        type=('build', 'run'), when='@:1.4')
    depends_on('py-cffi@1.12.2:',        type=('build', 'run'), when='@1.5:')
    depends_on('py-greenlet@0.4.13:',   type=('build', 'run'), when='@:1.4')
    depends_on('py-greenlet@0.4.14:',   type=('build', 'run'), when='@1.5:')
```
Some further simplifications you can make.

2021-10-17 16:07 UTC, adamjstewart approved these changes

2021-10-17 16:07 UTC, merged