silo: new release
LLNL/spack pull request #26748
Opened 2021-10-14 20:19 UTC by cessenat

Well, that is Silo, from @markcmiller86 
I did not dare set it it as the preferred release, should be in a while.

2021-10-15 05:04 UTC, alalazo approved these changes

2021-10-15 05:05 UTC, alalazo requested changes

2021-10-15 05:05 UTC, alalazo commented on var/spack/repos/builtin/packages/silo/package.py
> +    version('4.11-bsd', sha256='',
Double checking the PR I see a missing sha256?

2021-10-15 06:18 UTC, cessenat commented on var/spack/repos/builtin/packages/silo/package.py
> +    version('4.11-bsd', sha256='',
Oh ! Terribly sorry !

2021-10-15 07:02 UTC, cessenat commented on var/spack/repos/builtin/packages/silo/package.py
> +    version('4.11-bsd', sha256='',
Hum it seems I do not manage to fetch 4.11, there is a problem

2021-10-15 07:11 UTC, cessenat commented on var/spack/repos/builtin/packages/silo/package.py
> +    version('4.11-bsd', sha256='',
I get the following message
```
==> [2021-10-15-09:09:12.784629] Checking existence of https://wci.llnl.gov/sites/wci/files/2021-01/silo-4.11.tgz
==> [2021-10-15-09:09:12.966072] FailedDownloadError: Failed to fetch file from URL: https://wci.llnl.gov/sites/wci/files/2021-01/silo-4.11.tgz
    Urllib fetch failed to verify url https://wci.llnl.gov/sites/wci/files/2021-01/silo-4.11.tgz
==> [2021-10-15-09:09:12.966447] Fetching from https://cache.e4s.io/silo/silo-4.11.tgz failed.
==> [2021-10-15-09:09:12.966572] Fetching from https://mirror.spack.io/silo/silo-4.11.tgz failed.
==> [2021-10-15-09:09:12.966630] Fetching from https://wci.llnl.gov/sites/wci/files/2021-01/silo-4.11.tgz failed.
```
So sorry for wasting your time, I should have tested before (I only made a wget).

2021-10-15 13:30 UTC, sethrj submitted a review, later dismissed
Thanks! Checksums are good. Testing a build now.

2021-10-15 13:33 UTC, sethrj reviewed
Sorry didn't see that alalazo already was reviewing this. For some reason the `url` isn't working either: it doesn't look like spack is trying to fetch it from the given URL...

2021-10-15 16:26 UTC, markcmiller86 commented
Sorry I haven't had time to take a look at this.

Regarding fetching issues and the URL, be aware that we've also moved silo from its subversion repo behind LLNL firewalls to [GitHub](https://github.com/LLNL/Silo) now and the [4.11 Release](https://github.com/LLNL/Silo/releases/tag/v4.11) is also available there.

2021-10-15 16:48 UTC, sethrj commented on var/spack/repos/builtin/packages/silo/package.py
> +            url="https://github.com/LLNL/Silo/releases/download/v4.11/silo-4.11-bsd.tar.gz")
Might be better to change the url schema? That should also allow the other versions to be captured (although I don't know if it'll change their hashes)

2021-10-15 17:19 UTC, cessenat commented on var/spack/repos/builtin/packages/silo/package.py
> +            url="https://github.com/LLNL/Silo/releases/download/v4.11/silo-4.11-bsd.tar.gz")
I cannot answer @sethrj since 4.8:4.10.2 all are on mirror.spack.io so I do not see a difference.
But I opt for that, I too think it is better.

2021-10-15 17:43 UTC, cessenat commented on var/spack/repos/builtin/packages/silo/package.py
> +            url="https://github.com/LLNL/Silo/releases/download/v4.11/silo-4.11-bsd.tar.gz")
Hashes between https://github.com/LLNL/Silo/releases/download/v4.11/silo-4.11.tar.gz and https://github.com/LLNL/Silo/archive/refs/tags/4.11.tar.gz differ.
We'd better wait for @markcmiller86 advise.

2021-10-15 19:25 UTC, markcmiller86 commented on var/spack/repos/builtin/packages/silo/package.py
> +            url="https://github.com/LLNL/Silo/releases/download/v4.11/silo-4.11-bsd.tar.gz")
Hmmm...I don't honestly know where the `archives/refs/tags/4.11.tar.gz` comes from...I think that is GitHub auto-generated. Which is cool. But, note the difference in case in the names of the downloaded files. When I download and compare both untar'd archives with `diff -r` I don't see any diffs.

Now, the _release_ I created there *manually* before the Silo code base itself was actually on GitHub. I had a repo with just issues in it and added the 4.11 release *manually* to that repo. So, I suspect I didn't follow the *GitHub* way and created a difference (certainly in the case, `Silo` vs. `silo`). For this release, I advise that you use the *release* and not the *tag*. In future, I'll be sure to follow GitHub release naming conventions. Ok?

2021-10-16 07:46 UTC, cessenat commented on var/spack/repos/builtin/packages/silo/package.py
> +            url="https://github.com/LLNL/Silo/releases/download/v4.11/silo-4.11-bsd.tar.gz")
Thanks @markcmiller86 for the explanation. So finally I would opt to step back to previous commit with legacy url, i.e. to forget about commit f5a76e44b98b90a4488ee66acc12f56b919060f6.
@sethrj Should I make another commit to get back to previous or is it possible to forget about the latest before merging ?

2021-10-16 13:54 UTC, sethrj requested changes
I'm getting a build failure for `silo@4.11%apple-clang@13.0.0+fortran+fpzip+hdf5+hzip~mpi+pic+shared~silex arch=darwin-bigsur-x86_64`:
```
  >> 660    silo_hdf5.c:2173:5: error: implicit declaration of function 'zfp_init_zfp' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
     661        zfp_init_zfp();
     662        ^
```

2021-10-16 13:59 UTC, sethrj commented
@markcmiller86 it looks like Silo is now including a vendored copy of ZFP (or maybe H5zZfp, which has its own LLNL package in spack)? Besides apparently breaking this build, this could cause link errors for apps that want to use both Silo and another ZFP dependent.

2021-10-16 15:34 UTC, cessenat commented
> I'm getting a build failure for `silo@4.11%apple-clang@13.0.0+fortran+fpzip+hdf5+hzip~mpi+pic+shared~silex arch=darwin-bigsur-x86_64`:
> 
> ```
>   >> 660    silo_hdf5.c:2173:5: error: implicit declaration of function 'zfp_init_zfp' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>      661        zfp_init_zfp();
>      662        ^
> ```

I get into the same trouble.
Sorry for not checking before.

2021-10-16 17:27 UTC, cessenat commented
Hello dear @sethrj and @markcmiller86, if it helps, here is what I get on MaxOSBigSur with 4.1-bsd.
I get the same message on Ubuntu 18.04 %gcc@7.5.
Apologies again to @sethrj  and @markcmiller86 for not checking before.

```
cessenat@imac spack % spack install silo@4.11-bsd
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/libsigsegv-2.13-c4v2yr3rpy32j3ggtkfmaikpiz7cmnoi
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/berkeley-db-18.1.40-e7c7qfnfax7q55dnjrq324zftznjux24
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/libiconv-1.16-xjpymr7nr6pfktwoeu5t5gzsuyski6i5
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/pkgconf-1.8.0-jhpfdnnwzrczbkxpfzk6f5lxwqv26ort
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/zlib-1.2.11-oxbqjbkh6mcwysmhkghs566zenfctwri
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/xz-5.2.5-m45wgwkvfr32jnidfcwwrenziezltnq5
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/m4-1.4.19-hqtcq2l7sxyere6uhxhnkgftvs5bj6ml
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/diffutils-3.8-3j3bbqtd62b53le5zzugazua74ksgqmr
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/ncurses-6.2-ziztza47jy2kbexyygt77ny2ntqkpj3s
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/libxml2-2.9.12-53e6v43eseasv6gjp2aw3gv5jrrrgt5n
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/libtool-2.4.6-4qsbhl6kjweqetan53gzo7blybjv7o3q
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/bzip2-1.0.8-75t7wftsse365gjb2sf6aikzal6itvoq
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/readline-8.1-6qvrxp2m3cfnod2sbmtut3gepooip2rz
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/libedit-3.1-20210216-hvzwzqaq3hcih5cixahr46l2qemg6gwg
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/hwloc-2.5.0-p6cr4d2y7ltynpc7ff4eqay7qmu6vfws
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/gdbm-1.19-hbzxkx4sbnhy5tlwfyxjspo3j6jxgeah
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/perl-5.34.0-tc64zyeehyf664ludf7su2fmml6ed7bp
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/openssl-1.1.1l-qa4dbppjfb2kkrefxp7n6s663q4n3qmx
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/autoconf-2.69-n6egc5opistjdyrhwpaaz4y2uuenk2yu
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/libevent-2.1.12-jnqa7xewq7etjdclictixslb7iueaefs
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/openssh-8.7p1-6undq6vglp7fbc3zp2avovdvq7lj5bp7
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/cmake-3.21.3-cqx5uizudlsriyfhkpamqaggp3pmlw4u
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/automake-1.16.3-q3fiogttcd5yaki4xxyiafmq46b7fv7p
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/openmpi-4.1.1-fd3c2p3d2xlha7kulmymmy2kv4vg47hs
[+] /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/hdf5-1.10.7-5ocpa6maogrxobcald7ybjh56lxgdzyc
==> Installing silo-4.11-bsd-uijsays4ge3hm3jstvjmsqoi2lnmzfka
==> No binary for silo-4.11-bsd-uijsays4ge3hm3jstvjmsqoi2lnmzfka found: installing from source
/Users/cessenat/Softs/spack/lib/spack/spack/target.py:137: UserWarning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check apple-clang@11.0.0 for further details]
  warnings.warn(msg.format(compiler))
==> Fetching https://github.com/LLNL/Silo/releases/download/v4.11/silo-4.11-bsd.tar.gz
==> No patches needed for silo
==> silo: Executing phase: 'autoreconf'
==> Error: ProcessError: Command exited with status 1:
    '/Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/autoconf-2.69-n6egc5opistjdyrhwpaaz4y2uuenk2yu/bin/autoreconf' '-ivf' '-I' '/Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/automake-1.16.3-q3fiogttcd5yaki4xxyiafmq46b7fv7p/share/aclocal' '-I' '/Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/libtool-2.4.6-4qsbhl6kjweqetan53gzo7blybjv7o3q/share/aclocal'

8 errors found in build log:
     20    libtoolize: copying file 'config/lt~obsolete.m4'
     21    libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([config])' to configure.ac,
     22    libtoolize: and rerunning libtoolize and aclocal.
     23    autoreconf: running: /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/autoconf-2.69-n6egc5opistjdyrhwpaaz4y2uu
           enk2yu/bin/autoconf --include=/Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/automake-1.16.3-q3fiogttcd5yaki
           4xxyiafmq46b7fv7p/share/aclocal --include=/Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/libtool-2.4.6-4qsbh
           l6kjweqetan53gzo7blybjv7o3q/share/aclocal --force
     24    autoreconf: running: /Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/autoconf-2.69-n6egc5opistjdyrhwpaaz4y2uu
           enk2yu/bin/autoheader --include=/Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/automake-1.16.3-q3fiogttcd5ya
           ki4xxyiafmq46b7fv7p/share/aclocal --include=/Users/cessenat/Softs/spack/opt/spack/darwin-bigsur-skylake/apple-clang-11.0.0/libtool-2.4.6-4qs
           bhl6kjweqetan53gzo7blybjv7o3q/share/aclocal --force
     25    autoreconf: running: automake --add-missing --copy --force-missing
  >> 26    configure.ac:368: installing 'config/compile'
  >> 27    configure.ac:170: installing 'config/missing'
  >> 28    configure.ac:1209: error: required file 'src/hzip/Makefile.in' not found
  >> 29    configure.ac:1212: error: required file 'src/fpzip/Makefile.in' not found
     30    src/Makefile.am: installing 'config/depcomp'
  >> 31    src/Makefile.am:79: error: required directory src/hzip does not exist
  >> 32    src/Makefile.am:83: error: required directory src/fpzip does not exist
  >> 33    src/Makefile.am:95: error: required directory src/hzip does not exist
  >> 34    src/Makefile.am:98: error: required directory src/fpzip does not exist
     35    autoreconf: automake failed with exit status: 1

See build log for details:
  /var/folders/53/vwnr5jhj4h3cgvt1y6w3wgmh0000gn/T/cessenat/spack-stage/spack-stage-silo-4.11-bsd-uijsays4ge3hm3jstvjmsqoi2lnmzfka/spack-build-out.txt


```

2021-10-17 05:02 UTC, markcmiller86 commented
> this could cause link errors for apps that want to use both Silo and another ZFP dependent.

not so fast @sethrj ... the version embedded in silo is [name mangled](https://github.com/LLNL/Silo/wiki/Using-C-structs-as-a-kind-of-namespace-mechanism-to-reduce-global-symbol-bloat) so that no symbol there will collide with the *real* zfp library. 

Regarding the build failure...we're aware of that. Will have to be fixed in an upcoming point release by end of CY

2021-10-17 12:10 UTC, sethrj commented
> not so fast @sethrj ... the version embedded in silo is [name mangled](https://github.com/LLNL/Silo/wiki/Using-C-structs-as-a-kind-of-namespace-mechanism-to-reduce-global-symbol-bloat) so that no symbol there will collide with the *real* zfp library.

Aha, good to know. It still might be worth having an option for an external zfp (provided by spack) to cleanly document version dependencies. 

> Regarding the build failure...we're aware of that. Will have to be fixed in an upcoming point release by end of CY

Gotcha, thanks for looking into it! If it's simply a C99 error from running on a new compiler we could probably add a flag in the package recipe

2021-10-17 17:04 UTC, cessenat commented
Now reverting to legacy global url, adding a -Wno-implicit-function-declaration in case of apple-clang compiler.
So 4.11 compiles fine on Linux and OSX.
Still 4.11-bsd has the above mentioned errors which I rewrite below:
```
$spack install silo@4.11-bsd
[+] /home/cessenat/Softs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/hdf5-1.10.7-3kbcjsg7qce2yn5vq2ozbxd4cavgnlmf
==> Installing silo-4.11-bsd-4qd6lps6cw2apfy2srjrka6l5tvvlwrh
==> No binary for silo-4.11-bsd-4qd6lps6cw2apfy2srjrka6l5tvvlwrh found: installing from source
==> Using cached archive: /home/cessenat/Softs/spack/var/spack/cache/_source-cache/archive/6d/6d0a85a079d48fcdcc0084ecb5fc4cfdcc64852edee780c60cb244d16f4bc4ec.tar.gz
==> No patches needed for silo
==> silo: Executing phase: 'autoreconf'
==> Error: ProcessError: Command exited with status 1:
    '/home/cessenat/Softs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/autoconf-2.69-r3w2s3a3fu5ejybyzkzjjspkozgvbiuo/bin/autoreconf' '-ivf' '-I' '/home/cessenat/Softs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/automake-1.16.3-67lbooo72ugek25iky4iex42quphwm4q/share/aclocal' '-I' '/home/cessenat/Softs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/libtool-2.4.6-w4tsujnnraal6ovlwzoj5czdf2vvfenk/share/aclocal'

8 errors found in build log:
     20    libtoolize: copying file 'config/lt~obsolete.m4'
     21    libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([config])' to configure.ac,
     22    libtoolize: and rerunning libtoolize and aclocal.
     23    autoreconf: running: /home/cessenat/Softs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/autoconf-2.69-r3w2s3a3fu5ejyb
           yzkzjjspkozgvbiuo/bin/autoconf --include=/home/cessenat/Softs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/automake-
           1.16.3-67lbooo72ugek25iky4iex42quphwm4q/share/aclocal --include=/home/cessenat/Softs/spack/opt/spack/linux-ubuntu18.04-
           zen/gcc-7.5.0/libtool-2.4.6-w4tsujnnraal6ovlwzoj5czdf2vvfenk/share/aclocal --force
     24    autoreconf: running: /home/cessenat/Softs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/autoconf-2.69-r3w2s3a3fu5ejyb
           yzkzjjspkozgvbiuo/bin/autoheader --include=/home/cessenat/Softs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/automak
           e-1.16.3-67lbooo72ugek25iky4iex42quphwm4q/share/aclocal --include=/home/cessenat/Softs/spack/opt/spack/linux-ubuntu18.0
           4-zen/gcc-7.5.0/libtool-2.4.6-w4tsujnnraal6ovlwzoj5czdf2vvfenk/share/aclocal --force
     25    autoreconf: running: automake --add-missing --copy --force-missing
  >> 26    configure.ac:368: installing 'config/compile'
  >> 27    configure.ac:170: installing 'config/missing'
  >> 28    configure.ac:1209: error: required file 'src/hzip/Makefile.in' not found
  >> 29    configure.ac:1212: error: required file 'src/fpzip/Makefile.in' not found
     30    src/Makefile.am: installing 'config/depcomp'
  >> 31    src/Makefile.am:79: error: required directory src/hzip does not exist
  >> 32    src/Makefile.am:83: error: required directory src/fpzip does not exist
  >> 33    src/Makefile.am:95: error: required directory src/hzip does not exist
  >> 34    src/Makefile.am:98: error: required directory src/fpzip does not exist
     35    autoreconf: automake failed with exit status: 1

See build log for details:
  /tmp/cessenat/spack-stage/spack-stage-silo-4.11-bsd-4qd6lps6cw2apfy2srjrka6l5tvvlwrh/spack-build-out.txt

```

2021-10-17 17:12 UTC, cessenat commented
BTW spack install silo@4.10.2-bsd has the same issue as 4.11-bsd.

2021-10-18 11:53 UTC, sethrj reviewed
Two small comments: mainly we should *avoid* adding the new broken `-bsd` build and mark  the existing broken `-bsd` build as deprecated.

2021-10-18 11:53 UTC, sethrj commented on var/spack/repos/builtin/packages/silo/package.py
> +            url="https://github.com/LLNL/Silo/releases/download/v4.11/silo-4.11-bsd.tar.gz")
Yes, the legacy URL is fine for now, though we may want to switch to using the git release mechanism for future versions using `def url_for_version` or the like.

2021-10-18 11:53 UTC, sethrj commented on var/spack/repos/builtin/packages/silo/package.py
> +            if spec.satisfies('%apple-clang'):
This will undoubtedly happen with the other clang compilers too: can you change to
```suggestion
            if spec.compiler.name in ['clang', 'apple-clang']:
```
and then others can append to this list as needed? Once the implicit declaration is fixed we can restrict the HDF5 version as well.

2021-10-18 15:29 UTC, cessenat commented
> Two small comments: mainly we should _avoid_ adding the new broken `-bsd` build and mark the existing broken `-bsd` build as deprecated.

What about silo-bsd being another package ? There would be a silo package and another one silo-bsd ? 
What do you think Mark @markcmiller86 ?

2021-10-18 15:33 UTC, sethrj commented
> > Two small comments: mainly we should _avoid_ adding the new broken `-bsd` build and mark the existing broken `-bsd` build as deprecated.
> 
> What about silo-bsd being another package ? There would be a silo package and another one silo-bsd ? What do you think Mark @markcmiller86 ?

I think they're functionally the same -- IIRC the BSD-licensed version is only missing some data files? The installed Silo should be essentially equivalent.

2021-10-20 18:19 UTC, cessenat commented
Oh completely messed up this commit with github regurlarly wrecking my ability to push (complaining for "passwd auth"...).

I found a way to make bsd work: simply not force autoreconf !
```
    @property
    def force_autoreconf(self):
        # Update autoconf's tests whether libtool supports shared libraries.
        # (Otherwise, shared libraries are always disabled on Darwin.)
        if self.spec.satisfies('@4.11-bsd') or self.spec.satisfies('@4.10.2-bsd'):
            return False
        else:
            return self.spec.satisfies('+shared')

```

2021-10-20 18:30 UTC, markcmiller86 commented on var/spack/repos/builtin/packages/silo/package.py
> +        if self.spec.satisfies('@4.11-bsd') or self.spec.satisfies('@4.10.2-bsd'):
I wasn't aware of any issues with `bsd` variant and `autoreconf`. That said, I don't honestly know if Silo's AutoTools usage is such that it really supports `autoreconf`ing except from some limited versions of AutoTools available on LLNL systems.

The `bsd` variant of the release removes a couple of builtin compression libs, fpzip (in `src/fpzip`) and hzip (in `src/hzip`), and does so I think by simply removing those paths from the source code tree. It could potentially break top level `makefile.in` or `configure.in` for `autoreconf`ing operations. Come to think of it, I don't think I've ever tested that.

All that said, be aware that we are working in a CMake for next release of Silo and will soon be abandoning AutoTools all together.

2021-10-20 18:57 UTC, sethrj commented
@cessenat it looks like your commit history broke in a recent push. Can you please rebase off develop and only include the silo commits>

2021-10-20 19:13 UTC, cessenat commented
> @cessenat it looks like your commit history broke in a recent push. Can you please rebase off develop and only include the silo commits>

Sorry @sethrj I would need help for that I'm not smart enough with git.
Following @markcmiller86 remark, one should also add a conflict to *zip when release is a bsd one.
Maybe it would be simpler to make another PR ?
I do not understand why I get into auth troubles, since recently and from time to time, this shivers me.

2021-10-21 00:10 UTC, sethrj commented
> Sorry @sethrj I would need help for that I'm not smart enough with git. Following @markcmiller86 remark, one should also add a conflict to *zip when release is a bsd one. Maybe it would be simpler to make another PR ? I do not understand why I get into auth troubles, since recently and from time to time, this shivers me.

```console
$ git fetch upstream
$ git rebase upstream/develop
```

2021-10-21 14:48 UTC, cessenat commented
Hello @sethrj,
I did what you said. Sorry it is French :
1) rebase said it applies things,
2) git push is rejected (I replayed it in English)

```
$ git rebase upstream/develop
Rembobinage préalable de head pour pouvoir rejouer votre travail par-dessus...
Application de  silo: new release
Application de  silo: oops sha256 was missing
Application de  silo: oops sha256 was wrong
Application de  silo: url for 4.11 on github
Application de  silo: update url to github
Application de  silo: revert url to legacy, add flag for Apple clang
Application de  Update var/spack/repos/builtin/packages/silo/package.py
Application de  silo: bsd no longer autoreconfs
$ git add silo/package.py
$ git commit --message 'silo: rebase'
Sur la branche silo_newrelease
rien à valider, la copie de travail est propre
$ git push origin silo_newrelease
Username for 'https://github.com': cessenat@gmail.com
Password for 'https://cessenat@gmail.com@github.com': 
To https://github.com/cessenat/spack.git
 ! [rejected]              silo_newrelease -> silo_newrelease (non-fast-forward)
error: failed to push some refs to 'https://github.com/cessenat/spack.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

2021-10-21 15:10 UTC, sethrj commented
@cessenat Sorry, I forgot to mention that when you rebase, you must `git push -f` to "force" the push.

2021-10-21 15:14 UTC, sethrj commented
By the way, to allow git to remember your username and password:
```console
$ git config --global credential.https://github.com.username cessenat
$ git config --global credential.helper store
```

2021-10-21 15:26 UTC, cessenat commented
Sorry @sethrj it seems I'm completely lost; I probably did too many stupid things. I even tried to restart from scratch (i.e. from git clone...)

```
$ git push --force origin silo_newrelease
Username for 'https://github.com': cessenat@gmail.com
Password for 'https://cessenat@gmail.com@github.com': 
Everything up-to-date
$ git add silo/package.py
$ git rebase --continue
Applying: silo: new release
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".

```
From scratch:
```
$ cd /tmp/cessenat/yyy
$ git clone https://github.com/cessenat/spack.git
Cloning into 'spack'...
remote: Enumerating objects: 308595, done.
remote: Counting objects: 100% (120/120), done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 308595 (delta 51), reused 60 (delta 10), pack-reused 308475
Receiving objects: 100% (308595/308595), 128.50 MiB | 4.79 MiB/s, done.
Resolving deltas: 100% (132654/132654), done.
$ cd spack ; git checkout develop
Already on 'develop'
Your branch is up to date with 'origin/develop'.
$ git remote add upstream https://github.com/spack/spack.git
$ git pull upstream develop
From https://github.com/spack/spack
 * branch                  develop    -> FETCH_HEAD
 * [new branch]            develop    -> upstream/develop
Already up to date.
$ git fetch upstream
remote: Enumerating objects: 16911, done.
remote: Counting objects: 100% (8278/8278), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 16911 (delta 8180), reused 8260 (delta 8171), pack-reused 8633
Receiving objects: 100% (16911/16911), 6.07 MiB | 4.81 MiB/s, done.
Resolving deltas: 100% (8776/8776), completed with 5492 local objects.
From https://github.com/spack/spack
 * [new branch]            FASTMath/ATPESC18                                 -> upstream/FASTMath/ATPESC18
 * [new branch]            FASTMath/ATPESC19                                 -> upstream/FASTMath/ATPESC19
 * [new branch]            PR/openblas                                       -> upstream/PR/openblas
 * [new branch]            PR/pymock                                         -> upstream/PR/pymock
... many lines cut here ...
 * [new tag]               e4s-21.02                                         -> e4s-21.02
 * [new tag]               v0.16.1                                           -> v0.16.1
 * [new tag]               v0.16.2                                           -> v0.16.2
 * [new tag]               v0.16.3                                           -> v0.16.3
$ git checkout silo_newrelease
Branch 'silo_newrelease' set up to track remote branch 'silo_newrelease' from 'origin'.
Switched to a new branch 'silo_newrelease'
$  git rebase upstream/develop
First, rewinding head to replay your work on top of it...
Applying: silo: new release
Applying: silo: oops sha256 was missing
Applying: silo: oops sha256 was wrong
Applying: silo: url for 4.11 on github
Applying: silo: update url to github
Applying: silo: revert url to legacy, add flag for Apple clang
Applying: Update var/spack/repos/builtin/packages/silo/package.py
Applying: silo: bsd no longer autoreconfs
Applying: silo: new release
Using index info to reconstruct a base tree...
M	var/spack/repos/builtin/packages/silo/package.py
Falling back to patching base and 3-way merge...
Auto-merging var/spack/repos/builtin/packages/silo/package.py
CONFLICT (content): Merge conflict in var/spack/repos/builtin/packages/silo/package.py
error: Failed to merge in the changes.
Patch failed at 0009 silo: new release
Use 'git am --show-current-patch' to see the failed patch

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".

$ cp ~/Softs/spack/var/spack/repos/builtin/packages/silo/package.py var/spack/repos/builtin/packages/silo/package.py
$ git add var/spack/repos/builtin/packages/silo/package.py
$ git rebase --continue
Applying: silo: new release
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".

$ git status | more
rebase in progress; onto 3720d06e26
You are currently rebasing branch 'silo_newrelease' on '3720d06e26'.
  (all conflicts fixed: run "git rebase --continue")

nothing to commit, working tree clean
$  git push --force origin silo_newrelease
Username for 'https://github.com': cessenat@gmail.com
Password for 'https://cessenat@gmail.com@github.com': 
Everything up-to-date

```

2021-10-21 15:53 UTC, sethrj commented
Your `push` isn't working because your rebase is still in progress. You still need to do `git rebase --skip` because it's an empty commit. Then `git push` should work then.

2021-10-21 15:59 UTC, cessenat commented
> Your `push` isn't working because your rebase is still in progress. You still need to do `git rebase --skip` because it's an empty commit. Then `git push` should work then.

I failed again.

2021-10-21 16:06 UTC, sethrj commented
Replaced by https://github.com/spack/spack/pull/26876

2021-10-21 16:06 UTC, closed without merging

2021-10-21 16:11 UTC, cessenat commented
> Replaced by #26876

Thanks @sethrj and so sorry for your time, I'm confused.