ants: fix build by setting BUILD_TESTING=OFF
LLNL/spack pull request #26768
Opened 2021-10-15 17:51 UTC by bcdarwin

Due to Kitware API changes, default ANTs builds were failing, presumably for all versions (https://github.com/ANTsX/ANTs/issues/1236).
This commit defaults BUILD_TESTING to OFF, preventing calls against
these APIs and fixing all versions.
Note that the ANTs test suite was not clean anyway (e.g. ANTs/#842).

2021-10-21 07:37 UTC, alalazo requested changes

2021-10-21 07:37 UTC, alalazo commented on var/spack/repos/builtin/packages/ants/package.py
> +            description='Build tests and fetch data')
Variants enter the hash so I think it would make more sense to turn BUILD_TESTING always OFF and don't add a variant, in particular considering the comment pointing to https://github.com/ANTsX/ANTs/issues/842 Would that be an issue?

2021-10-29 20:01 UTC, bcdarwin commented on var/spack/repos/builtin/packages/ants/package.py
> +            description='Build tests and fetch data')
Sure, done.

2021-11-01 16:23 UTC, alalazo approved these changes

2021-11-01 16:23 UTC, alalazo commented
@spackbot run pipeline

2021-11-01 16:25 UTC, alalazo commented
@spackbot run pipeline

2021-11-02 09:54 UTC, alalazo commented
@spackbot run pipeline

2021-11-09 10:19 UTC, merged