patches: make re-applied patches idempotent
LLNL/spack pull request #26784
Opened 2021-10-17 10:46 UTC by tgamblin

We use POSIX `patch` to apply patches to files when building, but `patch` by default prompts the user when it looks like a patch has already been applied. This means that:

1. If a patch lands in upstream and we don't disable it in a package, the build will start failing.
2. `spack develop` builds (which keep the stage around) will fail the second time you try to use them.

To avoid that, we can run `patch` with `-N` (also called `--forward`, but the long option is not in POSIX). `-N` causes `patch` to just ignore patches that have already been applied. This *almost* makes `patch` idempotent, except that it returns 1 when it detects already applied patches with `-N`, so we have to look at the output of the command to see if it's safe to ignore the error.

- [x] Remove non-POSIX `-s` option from `patch` call
- [x] Add `-N` option to `patch`
- [x] Ignore error status when `patch` returns 1 due to `-N`
- [x] Add tests for applying a patch twice and applying a bad patch
- [x] Tweak `spack.util.executable` so that it saves the error that *would have been* raised with `fail_on_error=True`. This lets us easily re-raise it.

2021-10-17 13:58 UTC, haampie commented
I think it makes sense to have idempotent behavior for applying patches.

I also think it's good to step back a little and look at the use cases. There are these two:

1. The user manages sources (--path ... or directly changing the yaml)
2. Spack manages sources

In (1) I don't think people expect Spack to apply patches, it would likely fail because the user already modified sources or changed branches.

In (2) sources are downloaded on `spack develop pkg@x`. But at that point patches cannot be applied, as they need concrete specs.

So it seems the current behavior is to apply patches only on install, because then we have concrete specs.

This can make sense for the initial install, but once you actually start modifying sources and do a second install, the situation is much like (1): you don't expect Spack to modify sources you are now in control of, you want Spack to install from sources you point it to as they are.

Another way to approach this is to wait with downloading Spack managed sources until after concretization, apply patches once, and then in subsequent spack install's skip the stage + patch step.

So the workflow would be:
```
spack -e . add pkg
spack -e . develop pkg (just modifies the yaml)
spack -e . concretize
```

And then either:

```
spack -e . install (downloads missing pkg sources, puts them in ./pkg, applies patches for concrete spec)
```

or, say:

```
spack -e . stage --develop
```

to avoid an immediate install

2021-10-17 17:23 UTC, vsoch commented
@haampie the first approach you suggested with add, develop, and install is what I was already doing (and it led to the patch error)
```
. /opt/spack/share/spack/setup-env.sh
spack env create -d .
spack env activate .
spack develop --path /code/libabigail libabigail@master
spack add libabigail@master
spack --debug install
```
And the --develop flag doesn't seem to work:

```bash
 spack -e . stage --develop
==> Error: unrecognized arguments: --develop
```
So I'm going to try the fix in the PR here - it takes a while to get to the libabigail install but I'll update after.

2021-10-17 18:19 UTC, vsoch submitted a review, later dismissed
This resolved my patch issues!

2021-10-18 18:37 UTC, vsoch commented
@haampie can we merge this?

2021-10-18 19:15 UTC, becker33 requested changes

2021-10-18 19:15 UTC, becker33 commented on lib/spack/spack/util/executable.py
> +        self.saved_error = None  # saved ProcessError when fail_on_error
I think `self.error` would make more sense than `self.saved_error`.

2021-10-18 19:15 UTC, becker33 commented on lib/spack/spack/util/executable.py
> +            if rc != 0 and (rc not in ignore_errors):
```suggestion
            if rc != 0:
```
I think that Executable.error should be set regardless of whether we ignore the error, and push this check down to where we determine whether to raise.

2021-10-18 19:15 UTC, becker33 commented on lib/spack/spack/util/executable.py
> +                if fail_on_error:
```suggestion
                if fail_on_error and (rc not in ignore_errors):
```

2021-10-18 19:25 UTC, haampie commented
My comment wasn't really a review, but rather pointing out that this pr seems to fix a symptom of an issue. So I don't want to block it but just share my thoughts ;)

2021-10-18 19:30 UTC, tgamblin commented
I don't disagree w/ @haampie's thoughts but I think they're a larger workflow improvement vs.a quick fix here.

2021-10-18 19:32 UTC, tgamblin commented
@becker33: nice catch -- added your changes.

2021-10-18 19:33 UTC, tgamblin commented on lib/spack/spack/util/executable.py
> +        self.saved_error = None  # saved ProcessError when fail_on_error
ok fixed this too

2021-10-18 21:44 UTC, becker33 approved these changes

2021-10-18 23:11 UTC, merged

2021-10-19 00:14 UTC, vsoch commented
Thanks y'all for the quick fix!

2021-11-01 15:41 UTC, haampie commented
@tgamblin this causes a regression where a failing patch due to missing file is ignored. Previously it halted:

```
Applied patch /home/harmen/spack/var/spack/repos/builtin/packages/julia/llvm-12.0.1.patch
The text leading up to this was:
--------------------------
[description]
--------------------------
File to patch: 
```

now it simply continues.

2021-11-01 16:41 UTC, tgamblin commented
@haampie: what's the output from the patch command there?  Annoyingly, POSIX doesn't give any specific return code to distinguish an already-applied patch from a failed one.  So we look at the output.  But I guess we should also look at whether the patch exists.

2021-11-12 16:44 UTC, haampie commented
Should we consider reverting this? I'm hitting this again while packaging : (

2021-11-13 16:15 UTC, tgamblin commented
what's the output from patch?

2021-11-13 17:05 UTC, haampie commented
Try this nonsensical patch to zlib from a spack commit:

```
diff --git a/var/spack/repos/builtin/packages/zlib/package.py b/var/spack/repos/builtin/packages/zlib/package.py
index 7ca45d4215..5e2d5eff95 100644
--- a/var/spack/repos/builtin/packages/zlib/package.py
+++ b/var/spack/repos/builtin/packages/zlib/package.py
@@ -29,6 +29,7 @@ class Zlib(Package):
             description='Enable -O2 for a more optimized lib')
 
     patch('w_patch.patch', when="@1.2.11%cce")
+    patch('https://github.com/spack/spack/commit/984715e859c701c28499d495b9e9be341a7cbcc0.patch', sha256='7b48fe6dac80abef3de85f5a1b588a9575211114865edae03ddb3bec9a24f61c')
 
     @property
     def libs(self):
```

```
$ spack install zlib
==> Installing zlib-1.2.11-zibzu5yx5tr6g46sreceqy4z72qky25w
==> No binary for zlib-1.2.11-zibzu5yx5tr6g46sreceqy4z72qky25w found: installing from source
==> Using cached archive: /home/harmen/spack/var/spack/cache/_source-cache/archive/c3/c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1.tar.gz
==> Using cached archive: /home/harmen/spack/var/spack/cache/_source-cache/archive/7b/7b48fe6dac80abef3de85f5a1b588a9575211114865edae03ddb3bec9a24f61c
==> Applied patch https://github.com/spack/spack/commit/984715e859c701c28499d495b9e9be341a7cbcc0.patch
==> zlib: Executing phase: 'install'
==> zlib: Successfully installed zlib-1.2.11-zibzu5yx5tr6g46sreceqy4z72qky25w
  Fetch: 0.00s.  Build: 1.12s.  Total: 1.12s.
```