Allow non-UTF-8 encoding in sbang hook
LLNL/spack pull request #26793
Opened 2021-10-18 11:00 UTC by haampie

Closes https://github.com/spack/sbang/issues/8

Treat shebangs as bytes, cap spack's limit, add luajit

Currently Spack reads full files containing shebangs to memory as
strings, meaning Spack would have to guess their encoding. Currently
Spack has a fixed guess of UTF-8.

This is unnecessary, since e.g. the Linux kernel does not assume an
encoding on paths at all, it's just bytes and some delimiters on the
byte level.

This commit does the following:

1. Shebangs are treated as bytes, so that e.g. latin1 encoded files do
not throw UnicodeEncoding errors, and adds a test for this.
2. No more bytes than necessary are read to memory, we only have to read
until the first newline, and from there on we an copy the file byte by byte
instead of decoding and re-encoding text.
3. We cap the number of bytes read to 4096, if no newline is found
before that, we don't attempt to patch the file.
4. Add support for luajit too.

This should make Spack both more efficient and usable for non-UTF8
files.

2021-10-18 16:28 UTC, haampie commented
Btw @tgamblin we could also use this PR to fix the forced-utf8-encoding-issue; another attempt was in #24231, but this PR just avoids reading the whole file, so it shouldn't have those issues.

It's just that the shebang line has to be read with some kind of encoding, but maybe there are some rules about the shebang line I'm not aware of that would resolve this problem?

2021-10-18 22:13 UTC, haampie commented
~I believe the encoding issue is now fixed, see the last commit message. We can just treat the interpreter path as a sequence of bytes, and we don't have to worry about utf-16 or whatever weird encoding.~

Edit: What I believed about paths and encoding seems wrong. So, you can't just decide to store your script in utf-16 encoding, because the `#!` preamble should be two bytes `b'#!'` aka `\x23\x21`. If you would save your file as utf-16 and `#!` is interpreted as text, it would 4 be bytes, and the thing exec'ing would not see the magic bytes for shebang. Or if you would add a byte order mark (using .encode('utf-16') instead of .encode('utf-16le') or .encode('utf-16be')), the file doesn't start with `b'#!'` anymore, and it wouldn't work.

After `b'#!'` you get the path to the interpreter. To decode paths, the general recommendation is `os.fsdecode`, but this is Python 3.x only? However, on Linux, there is no such thing as file path encoding, paths are just any non-null bytes `b'\x00'` and are separated by the byte `b'/'`. Not sure about macos, but probably the same? Then for the shebang line, I suppose the path to the interpreter also stops at `b'\n'` and `b' '` or other whitespace. And if we have to check for lua/php/node at the end of the interpreter, we could just use `b'lua'`, `b'php'` and `b'node'`? Note that any utf-16 encoding would not really fly on linux, because they add `b'\x00'` bytes before or after ascii / single-byte-representable characters, which would mark the end of the path on linux (?). It probably does not make a whole lot of sense to read files as utf-16 or so if that's native on Windows when shebang lines apply to unix?

My findings on Linux:

1. What counts for the character limit is just the `#! ... /interpreter` length, not the arguments passed to it
2. The interpreter path starts after the first non-space/tab character after `#!` and ends at the first space/tab, that means that  executables in paths including whitespace can't be in a shebang.
3. We should just check for lua/php/node as bytes at the end of the interpreter.

2021-10-19 10:46 UTC, haampie commented
@tgamblin I just realized that this means that

```
#!/bin/sh /very/long/path/.../to/bin/sbang
```

is just fine, we were just overly strict.

The reason is that what counts is the length of `#!/bin/sh`, and `/very/long/path/.../to/bin/sbang` is an argument -- it's truncated to 128 bytes in the kernel, but the kernel doesn't care, because the interpreter rereads the argument passed to it, if I understand correctly.

Edit: seems like the issue is still there, the kernel comments suggest the interpreter *can* retrieve the remainder of the truncated arguments, it's just that `/bin/sh` apparently does not.

2021-10-22 16:49 UTC, haampie commented on lib/spack/spack/hooks/sbang.py
> +interpreter_regex = re.compile(b'#![ \t]*?([^ \t\0\n]+?)([ \t\0\n]|$)')
Uh, not sure why I did `([...]|$)`. That group can just be removed. I think this was because I started out with just `[ \t\0\n]` and later realized there may just be an interpreter and then end of file. Let me fix.
```suggestion
interpreter_regex = re.compile(b'#![ \t]*?([^ \t\0\n]+)')
```

2021-10-22 17:23 UTC, haampie commented on lib/spack/spack/hooks/sbang.py
> +        new_sbang_line = sbang_shebang_line().encode('utf-8') + b'\n'
@tgamblin this is the last place where we force a UTF-8 encoding, of our new sbang-shebang line. In a perfect world we would use `b'#!' + os.fsencode("/bin/sh") + b' ' + os.fsencode(sbang_install_path())` in case sbang itself in some path with weird symbols, but this is python 3.x. But at the same time, some googling told me "File system paths on Linux are always treated as UTF-8" in Firefox, so it's common to just use utf-8.

2021-10-22 19:00 UTC, haampie commented
@spackbot run pipeline

2021-10-22 23:21 UTC, tgamblin requested changes
Mostly LGTM! Some minor requests.

2021-10-22 23:21 UTC, tgamblin commented on lib/spack/spack/hooks/sbang.py
> +    containing a newline character will be read into memory entirely.
We should probably limit this to something like 4096 chars or, I dunno, 40x the shebang limit, as nothing's going to work in paths that deep (for other, non-shebang reasons) anyway. No point in reading in giant files.

2021-10-22 23:21 UTC, tgamblin commented on lib/spack/spack/hooks/sbang.py
> +        if interpreter[-4:] == b'/lua':
This can also be luajit

2021-10-23 22:01 UTC, haampie commented on lib/spack/spack/hooks/sbang.py
> +    containing a newline character will be read into memory entirely.
Agreed, so now there is a limit of 4KB. Note that I'm keeping things simple: don't patch if there is no newline or end of file before 4KB. In principle we can relax this for the non-PHP case if only arguments are truncated but the interpreter is not. But that seems not worth it to me.

2021-10-23 22:01 UTC, haampie commented on lib/spack/spack/hooks/sbang.py
> +        if interpreter[-4:] == b'/lua':
Added that

2021-10-27 09:58 UTC, tgamblin approved these changes

2021-10-27 09:59 UTC, merged