Change sbang install error into a warning by using /usr/bin/env sbang when sbang itself is nested too deeply
LLNL/spack pull request #26792
Opened 2021-10-18 09:01 UTC by haampie

When using spack install tree's with long paths, as is rather common in conintuous integration setups, spack often fails with an sbang-error where it can't shorten shebang lines because the path to sbang itself is too long.

This PR makes Spack use `#!/usr/bin/env sbang` as the shebang in those cases, and changes the error into a warning:

```
==> Warning: Failed to shorten shebang lines of 6 files ['autoheader', 'autoscan', 'autom4te', '...', 'autoreconf'], because sbang's install path (/tmp/tmp.xyLJCF9DeK/aaaaaaaaaaaa/aaaaaaaaaaaa/aaaaaaaaaaaa/aaaaaaaaaaaa/aaaaaaaaaaaa/aaaaaaaaaaaa/aaaaaaaaaaaa/aaaaaaaaaaaa/aaaaaaaaaaaa/aaaaaaaaaaaa/aaaaaaaaaaaa/aaaaaaaaaaaa/aaaaaaaaaaaa/here/bin) is too long. For the installation to work, it is required to have sbang in your PATH. Alternatively, you can shorten the install root (config:install_tree:root).
```

As a small improvement it skips over symlinks as it always recurses over the install prefix now, so whatever the symlinks point to will be visited anyways.

Todo:

- [x] Some relocation code relies on `sbang_install_path` raising an error when it's too long (I think?). With this PR it does not anymore.
- [ ] Maybe add `<install root>/bin` to PATH on spack load / env activate / module load by default iff sbang path too long? Or unconditionally? Note that `sbang` is by default in the PATH when `spack` is.

2021-10-18 09:34 UTC, haampie commented
@opadron, can you have a look at the relocation code?

We should have the same behavior in the relocation code as in normal installs: if you install from a binary cache but your `sbang` is in a path thats too long, then use `#!/usr/bin/env sbang` but issue a warning, otherwise use `#!/bin/sh <path to sbang bin folder>`.

Also there's now a new case when uploading binaries: the shebang lines can start with `#!/usr/bin/env sbang` instead of `#!/bin/sh <path to sbang bin folder>`. Should we allow that? If so, then installing from binaries should probably rewrite `#!/usr/bin/env sbang` to `#!/bin/sh <path to sbang bin folder>` if that path is short enough.

2021-10-18 15:05 UTC, gartung commented
This is where the old style sbang relocation was done and could still work `#!/usr/bin/env sbang`
https://github.com/spack/spack/blob/047c95aa8d2ff665d4788cb02b965ab3fa9bfc90/lib/spack/spack/binary_distribution.py#L1285

2021-10-18 15:07 UTC, gartung commented
You would  need to decide which type of sbang to use and then add a dictionary entry to map the old sbang line to the new sbang line.

2021-10-18 16:09 UTC, haampie commented
How do you currently deal with the case of a failing install from binary cache because the user location of sbang is too long to fit in a shebang line?

Or: are there tests covering it?

2021-10-18 17:00 UTC, becker33 commented
@haampie do you think this should have a config option to make it fail instead of warning?

Otherwise this looks great

2021-10-18 17:52 UTC, gartung commented
The short answer is that the relocation code does not check the shebang string. It just replaces the test blindly.

2021-10-19 10:51 UTC, haampie commented
Hey @becker33, I think this PR is redundant and we are just too strict. What matters on Linux is that the `#!` + whitespace + interpreter path together are not truncated in 128 bytes (that is, before byte 128 there should be a `\0`, `\n`, `\t` or ` ` character.

If you look at our shebang lines, they are:

```
#!/bin/sh /path/to/sbang
```

and as you may notice, the length of `#!/bin/sh` is only 9 bytes. :upside_down_face:

2021-10-19 15:31 UTC, becker33 commented
@haampie yeah I think it does depend on the version of the kernel, it'll come up a lot less often with newer linux versions. It's  a shame they're keeping the restriction less than MAX_PATH_LENGTH, but I guess that's why we have sbang.

2021-10-21 12:10 UTC, haampie commented
@gartung I've chosen to just error out at the entry points (relocate_package / build_tarball) if local sbang is nested too deeply. Even though this is strict, this should be no change from prior to this PR, cause somewhere down the line `sbang_install_path()` was called in both code paths, which used to raise an error if sbang's path was too long. I've added two tests to cover these cases now.

Optimally I'd like folks maintaining the binary distribution bits of Spack to implement something proper that parses the shebang lines and updates both `#!/usr/bin/env sbang` and `#!/path/to/bin/sbang` to the user install of sbang, following the same logic as in the sbang hook (if the user path is too long, use `env sbang` and warn.) That way we don't have to be so terribly strict. One might also argue that `#!/usr/bin/env sbang` is relocatable already, so we should use that when creating a tarball, and not modify it upon install at all... but well.

Otherwise I'd prefer to not touch the binary_distribution code further in this PR :grimacing:

2021-10-21 12:13 UTC, haampie commented
@becker33 what do we do with `spack load`, `spack env activate` and module files? Should they add `dirname sbang` to the PATH?

2021-11-18 14:11 UTC, haampie commented
@becker33 do you have time for this? it's time to revive it now that 0.17 is done

2021-12-13 10:42 UTC, haampie commented
bump @becker33

2022-02-15 09:07 UTC, becker33 requested changes
One request and two minor questions

2022-02-15 09:07 UTC, becker33 commented on lib/spack/spack/hooks/sbang.py
> -    if not os.path.isfile(path):
Why remove this guard? Is trying to open and read a non-file better performing than checking whether it's a file?

2022-02-15 09:07 UTC, becker33 commented on lib/spack/spack/hooks/sbang.py
> +                 len(paths), short_list, sbang_bin))
This warning should mention that the packages will not be relocatable.

as long as you're modifying it, some newlines might make it easier for users to read also.

2022-02-15 09:07 UTC, becker33 commented on lib/spack/spack/hooks/sbang.py
> +        msg = fmt.format(shebang_len, shebang_limit)
Should we include the sbang path in this error message?

2024-02-17 21:56 UTC, alecbcs commented
@haampie @becker33 is this PR still relevant? @haampie do you have time to address the feedback from Greg?

2026-01-05 16:58 UTC, closed without merging