Fix alpgen's cms recipe
LLNL/spack pull request #26812
Opened 2021-10-19 10:37 UTC by iarspider

2021-10-19 14:13 UTC, alalazo requested changes

2021-10-19 14:13 UTC, alalazo commented on var/spack/repos/builtin/packages/alpgen/package.py
> +        copy(join_path(os.path.dirname(__file__), 'cms_install.sh'), 'cms_install.sh')
These two copies seem better suited for a `patch` method since they change the files in the stage area.

2021-10-19 14:15 UTC, iarspider commented on var/spack/repos/builtin/packages/alpgen/package.py
> +        copy(join_path(os.path.dirname(__file__), 'cms_install.sh'), 'cms_install.sh')
I agree. And also they are not needed for SFT recipe

2021-10-21 07:20 UTC, alalazo requested changes
Style tests are failing

2021-10-29 21:25 UTC, iarspider commented
@alalazo gentle ping

2021-11-01 14:13 UTC, alalazo approved these changes

2021-11-01 14:13 UTC, merged