Paraview: Allow +shared +cuda
LLNL/spack pull request #26818
Opened 2021-10-19 14:54 UTC by kwryankrattiger

It seems this was added for vtk-m once, but is no longer a requirement of vtk-m and therefore can be removed from paraview.

2021-10-19 15:50 UTC, vicentebolea commented
@kwryankrattiger can we hold on on this until we merge and makes its way to PV: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7864

I noticed that for the vtkm wrapper library in VTK (vtkmAccelator) there are issues with static at this moment,

2021-10-19 19:34 UTC, kwryankrattiger commented
@vicentebolea 
> I noticed that for the vtkm wrapper library in VTK (vtkmAccelator) there are issues with static at this moment,

If there are issues with static, wouldn't it be better to merge this so we can disable static when building paraview+cuda? Or do you mean there is an issue with shared?

2021-10-21 00:27 UTC, vicentebolea commented
@kwryankrattiger I said it in reverse :facepalm:  Yeah the issue was observed with shared libraries few months ago, but that was also a known issue in VTKm which I fixed later on, but for that we need to make some changes in the used vtkm flags in VTK (novirtuals). 

I will be back in vtkm in a couple of weeks, so how about we come  can come back to this issue then

2021-10-21 07:11 UTC, alalazo commented
> I will be back in vtkm in a couple of weeks, so how about we come can come back to this issue then

Feel free to ping me when this is ready to be merged

2021-12-14 19:47 UTC, vicentebolea commented
@kwryankrattiger VTK+VTKm+CUDA (with shared library) support finally made it way to VTK current master https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7864

2022-01-27 01:59 UTC, vicentebolea requested changes

2022-01-27 02:00 UTC, vicentebolea commented
@kwryankrattiger my apologizes, I made the review but I left it `pending for a few months without noticing.

2022-02-14 17:59 UTC, kwryankrattiger commented
This is resovled in #28877 for VTK-m.

@vicentebolea Will ParaView 5.10.1 get this update for VTK-m as well or will that have to wait for 5.11?

@chuckatkins

2022-02-14 18:33 UTC, vicentebolea commented
There are no plans for this, but I plan to push to move this to ParaView 5.10.1, incoming VTK release will be compatible with VTK-m 1.7

2022-02-14 18:36 UTC, vicentebolea approved these changes
Thanks for this!

2022-03-02 18:45 UTC, kwryankrattiger commented
Closing this, redundant with #29054

2022-03-02 18:45 UTC, closed without merging