tasmanian: fix the spack test dir
LLNL/spack pull request #26816
Opened 2021-10-19 14:18 UTC by mkstoyanov

fix the spack test dir as suggested by @tldahlgren

2021-10-22 01:01 UTC, tldahlgren requested changes

2021-10-22 01:01 UTC, tldahlgren commented on var/spack/repos/builtin/packages/tasmanian/package.py
>              make('test')
The tests aren't in the `testing` subdirectory but appear to be in `examples`, at least for v7.5 .  The generated makefile also doesn't apparently have a `test` target.  The following appears to be a minimal way of getting things to work with what is being built now:

```
        cmake_dir = join_path(self.prefix, 'share', 'Tasmanian', 'examples')
        with working_dir(self.test_suite.current_test_cache_dir, create=True):
            cmake(cmake_dir)
            make()
            
            for exe in ['./example_dream', './example_sparse_grids']:
                self.run_test(exe, purpose='test: running {0}'.format(exe))
```

2021-10-22 11:38 UTC, mkstoyanov commented on var/spack/repos/builtin/packages/tasmanian/package.py
>              make('test')
This isn't supposed to work for 7.5. We changed the resting so it will work for the future.

We just tagged a new release (7.7) and I was trying to get the spack testing done before tagging. Now I'm waiting for this to be merged before making the PR for the release.

2021-10-26 20:04 UTC, tldahlgren commented on var/spack/repos/builtin/packages/tasmanian/package.py
>              make('test')
Okay.  You could use Spack's `find()` command to handle directory changes across versions.  See https://spack.readthedocs.io/en/latest/llnl.util.html?highlight=find()#llnl.util.filesystem.find.

2021-10-26 20:05 UTC, tldahlgren commented on var/spack/repos/builtin/packages/tasmanian/package.py
>              make('test')
Also, in that case it is better to check that the directory and or executable exists and, if not, printing that the tests are being skipped (and why).

2021-10-26 20:06 UTC, tldahlgren approved these changes
Accepting that the tests here are only intended for a given version and there will be a follow-up PR to address newer versions.

2021-10-26 20:07 UTC, merged