hpcviewer: add support for macosx, add version 2021.10
LLNL/spack pull request #26823
Opened 2021-10-19 16:56 UTC by mwkrentel

closes #23056

Add support for binary install on macos darwin on x86_64.
Add version 2021.10.
Begin to deprecate old versions.

2021-10-19 17:02 UTC, mwkrentel commented
@pramodk I rewrote your old PR #23056 and cleaned up a few things.
I think this version is more in line with Apple standards.

2021-10-21 05:49 UTC, alalazo commented
@mwkrentel Can you rebase this branch?

2021-10-21 05:56 UTC, alalazo reviewed
I left a few comments, let me know if those are feasible.

2021-10-21 05:56 UTC, alalazo commented on var/spack/repos/builtin/packages/hpcviewer/package.py
> +    common to run hpcrun and hpcviewer on different machines."""
```suggestion
    x86_64).  
    
    Note: hpctoolkit databases are platform independent, so
    you don't need to install hpctoolkit to run the viewers and it's
    common to run hpcrun and hpcviewer on different machines."""
```

2021-10-21 05:56 UTC, alalazo commented on var/spack/repos/builtin/packages/hpcviewer/package.py
> +    machine = platform.machine().lower()
Can we use Spack's API? For instance:
```python
platform = spack.platforms.host()
```
?

2021-10-21 05:56 UTC, alalazo commented on var/spack/repos/builtin/packages/hpcviewer/package.py
> +        machine = 'aarch64'
This can be avoided if we code in terms of Spack `target=...`.

2021-10-21 21:37 UTC, mwkrentel commented on var/spack/repos/builtin/packages/hpcviewer/package.py
> +    common to run hpcrun and hpcviewer on different machines."""
I tried this and it didn't make any difference, so I put it back.

You were trying to insert a blank line and put 'Note:' at the start of
a new paragraph?  AFAIK, spack doesn't do this.  It collapses all of
the whitespace into one big paragraph.

Is there some special escape sequence for this that I don't know about?

2021-10-21 21:39 UTC, mwkrentel commented on var/spack/repos/builtin/packages/hpcviewer/package.py
> +    machine = platform.machine().lower()
I tried this and got this error.  So, I guess the spack version is
returning a different type, maybe a list or something.

```
==> Error: 'str' object has no attribute '_cmp_iter'
```

But the real problem is that I tried it on Cray, and platforms returned
'cray' and I really need 'linux' in this case.  So, I'd have to test
for cray and reset it back to linux.

This is the difference between python and spack.  Spack distinguishes
between cray and linux, but python doesn't.  And in this case, I need
the answer linux.

2021-10-21 21:40 UTC, mwkrentel commented on var/spack/repos/builtin/packages/hpcviewer/package.py
> +        machine = 'aarch64'
I decided to just remove this (for now).  Not for spite or anything.
I had left it in only for future work (we currently don't acutally use it).

I don't have an Apple M1, so this is hard for me to test.  But the real
problem is that spack doesn't have pre-built clingo binaries for Macos M1.
So, for hpcviewer, we decided not to support M1 via spack for now.
The manual install of hpcviewer is *much* easier.  Just download one
`.dmg` file and open it.

When spack adds the pre-built binaries for clingo on Macos M1, then
I'll revisit this.

2021-10-21 21:41 UTC, mwkrentel commented
@alalazo 

> Can you rebase this branch?

Sure.  I didn't see any conflicts or overlap with develop.

Anything else?

2021-10-26 07:15 UTC, mwkrentel commented
@alalazo Anything else, or are we ready to merge?

2021-10-27 16:09 UTC, alalazo requested changes
One minor comment on the docstring change. Otherwise LGTM.

2021-10-27 16:09 UTC, alalazo commented on var/spack/repos/builtin/packages/hpcviewer/package.py
> +    common to run hpcrun and hpcviewer on different machines."""
Sorry, I wasn't explicit about why I asked for this change. Spack uses the first paragraph in the docstring as a short description of the package in certain contexts. It uses the entire docstring as a long description. This is true at least when generating module files:

https://github.com/spack/spack/blob/acb8ab338d3df901ec430daa073eff7c1a845b9b/lib/spack/spack/modules/common.py#L659-L671

2021-10-27 16:09 UTC, alalazo commented on var/spack/repos/builtin/packages/hpcviewer/package.py
> +    machine = platform.machine().lower()
> This is the difference between python and spack. Spack distinguishes
between cray and linux, but python doesn't. And in this case, I need
the answer linux.

Fair enough :sweat: We can revisit this at a later point.

2021-10-27 18:43 UTC, mwkrentel commented
@alalazo Ok, I split the docstring into a second paragraph.
I think that's everything.
But it seems the automated checks are stuck or something.

2021-10-27 19:03 UTC, alalazo approved these changes

2021-10-27 19:51 UTC, merged