Feature: Add tag filters to `spack test list`
LLNL/spack pull request #26842
Opened 2021-10-20 01:28 UTC by tldahlgren

@wspear @shahzebsiddiqui 

This PR adds support for one or more tags to be provided on the command line to filter `spack test list` results.

```
$ spack test list --help
usage: spack test list [-ha] [tag [tag ...]]

List installed packages with available tests.

positional arguments:
  tag         limit packages to those with all listed tags

optional arguments:
  -h, --help  show this help message and exit
  -a, --all   list all packages with tests (not just installed)

$ spack test list -a e4s ecp
==> 2 tagged packages with tests.
arborx  heffte

$ spack test list e4s
-- linux-rhel7-broadwell / gcc@8.3.1 ----------------------------
qax6x57 aml@master      32owbus swig@fortran  6ohwphk umpire@5.0.1
eudzg7h hypre@2.20.0    vsgppwe swig@4.0.2    6wfdlow umpire@develop
ploc3n2 kokkos@develop  i43hck4 umpire@1.1.0  tnscabn upcxx@2019.3.2
ddngphs openmpi@4.1.1   2xjsztl umpire@2.0.0  ehjj2qb upcxx@2021.3.0
vngwd6m openmpi@4.1.1   svz25qg umpire@2.0.0  ejt5z4d upcxx@2021.3.0
4ibfg3c raja@develop    2b3i7cy umpire@4.1.2

-- linux-rhel7-skylake_avx512 / gcc@8.3.1 -----------------------
piknyyb mpich@3.4.2  mrheofe raja@0.14.0  ewsohjo strumpack@5.1.1
2bnxajb mpich@3.4.2  eyih3vk raja@0.14.0  duhzjng strumpack@5.1.1
```

2021-10-20 11:59 UTC, alalazo requested changes

2021-10-20 11:59 UTC, alalazo commented on lib/spack/spack/cmd/test.py
> +    )
Modifications from:
```console
$ spack commands --update-completion
```
are missing.

2021-10-20 13:58 UTC, shahzebsiddiqui commented
Tags are specified as positional arguments which is good. Let's assume if a package like strumpack contains multiple tags lets say `e4s` and `radiuss` and one specifies `spack test list e4s radiuss` will spack show one or two entries for the spec and how can one see in output which specs belong to which tag. With the following output it is clear they are all e4s products but i would be curious how output will change with multi tag input. I think there needs to be some indication perhaps show specs by tag name and have some indicator in title ` linux-rhel7-broadwell / gcc@8.3.1 `. 

 

```
$ spack test list e4s
-- linux-rhel7-broadwell / gcc@8.3.1 ----------------------------
qax6x57 aml@master      32owbus swig@fortran  6ohwphk umpire@5.0.1
eudzg7h hypre@2.20.0    vsgppwe swig@4.0.2    6wfdlow umpire@develop
ploc3n2 kokkos@develop  i43hck4 umpire@1.1.0  tnscabn upcxx@2019.3.2
ddngphs openmpi@4.1.1   2xjsztl umpire@2.0.0  ehjj2qb upcxx@2021.3.0
vngwd6m openmpi@4.1.1   svz25qg umpire@2.0.0  ejt5z4d upcxx@2021.3.0
4ibfg3c raja@develop    2b3i7cy umpire@4.1.2

-- linux-rhel7-skylake_avx512 / gcc@8.3.1 -----------------------
piknyyb mpich@3.4.2  mrheofe raja@0.14.0  ewsohjo strumpack@5.1.1
2bnxajb mpich@3.4.2  eyih3vk raja@0.14.0  duhzjng strumpack@5.1.1
```

2021-10-20 18:29 UTC, tldahlgren commented on lib/spack/spack/cmd/test.py
> +    )
I also didn't address any changes to the unit tests last night.

2021-10-20 18:32 UTC, tldahlgren commented
> Tags are specified as positional arguments which is good. Let's assume if a package like strumpack contains multiple tags lets say `e4s` and `radiuss` and one specifies `spack test list e4s radiuss` will spack show one or two entries for the spec and how can one see in output which specs belong to which tag. With the following output it is clear they are all e4s products but i would be curious how output will change with multi tag input. I think there needs to be some indication perhaps show specs by tag name and have some indicator in title `linux-rhel7-broadwell / gcc@8.3.1`.
> 
> ```
> $ spack test list e4s
> -- linux-rhel7-broadwell / gcc@8.3.1 ----------------------------
> qax6x57 aml@master      32owbus swig@fortran  6ohwphk umpire@5.0.1
> eudzg7h hypre@2.20.0    vsgppwe swig@4.0.2    6wfdlow umpire@develop
> ploc3n2 kokkos@develop  i43hck4 umpire@1.1.0  tnscabn upcxx@2019.3.2
> ddngphs openmpi@4.1.1   2xjsztl umpire@2.0.0  ehjj2qb upcxx@2021.3.0
> vngwd6m openmpi@4.1.1   svz25qg umpire@2.0.0  ejt5z4d upcxx@2021.3.0
> 4ibfg3c raja@develop    2b3i7cy umpire@4.1.2
> 
> -- linux-rhel7-skylake_avx512 / gcc@8.3.1 -----------------------
> piknyyb mpich@3.4.2  mrheofe raja@0.14.0  ewsohjo strumpack@5.1.1
> 2bnxajb mpich@3.4.2  eyih3vk raja@0.14.0  duhzjng strumpack@5.1.1
> ```

Per `--help`, the command will only output packages that satisfy *all* of the tags provided on the command line.  So the tags are `and`'d together.

2021-11-02 09:00 UTC, alalazo approved these changes

2021-11-02 09:00 UTC, merged