Homomorphic encryption libraries: Palisade, HELib, SEAL, and NTL.
LLNL/spack pull request #26856
Opened 2021-10-20 17:49 UTC by wohlbier

Add packages for https://github.com/homenc/HElib and it's dependency https://github.com/libntl/ntl.

2021-10-21 05:39 UTC, alalazo requested changes
Thanks for the contribution. I left a few comments, let me know what you think.

2021-10-21 05:39 UTC, alalazo commented on var/spack/repos/builtin/packages/helib/package.py
> +    library."""
Can you have a short first paragraph, followed by a longer description later (disclaimer, I didn't check the snippet below for style) e.g.
```suggestion
    """HElib is an open-source (Apache License v2.0) software library that
    implements homomorphic encryption (HE). 
    
    Currently available schemes are the implementations of the 
    Brakerski-Gentry-Vaikuntanathan (BGV) scheme
    with bootstrapping and the Approximate Number scheme of Cheon-Kim-Kim-Song
    (CKKS), along with many optimizations to make homomorphic evaluation run
    faster, focusing mostly on effective use of the Smart-Vercauteren
    ciphertext packing techniques and the Gentry-Halevi-Smart optimizations.
    See this report for a description of a few of the algorithms using in this
    library."""
```
Spack will use the short paragraph in contexts where a short description is needed, and the full docstring where more info needs to be provided to users.

2021-10-21 05:39 UTC, alalazo commented on var/spack/repos/builtin/packages/helib/package.py
> +    See this report for a description of a few of the algorithms using in this
This last sentence can be removed since we don't have any handle to "this" report.

2021-10-21 05:39 UTC, alalazo commented on var/spack/repos/builtin/packages/helib/package.py
> +    # notify when the package is updated.
```suggestion
```

2021-10-21 05:39 UTC, alalazo commented on var/spack/repos/builtin/packages/helib/package.py
> +            description='Build shared library.')
```suggestion
    variant('shared', default=False, description='Build shared library.')
```

2021-10-21 05:39 UTC, alalazo commented on var/spack/repos/builtin/packages/helib/package.py
> +            args.append('-DBUILD_SHARED=ON')
Can you try:
```suggestion
        args = [
            self.define('ENABLE_TEST', 'ON'),
            self.define('GMP_DIR', spec['gmp'].prefix),
            self.define('NTL_DIR', spec['ntl'].prefix),
            self.define_from_variant('BUILD_SHARED', 'shared')
        ]
```
? This is the idiomatic way to define properties for CMake.

2021-10-21 05:39 UTC, alalazo commented on var/spack/repos/builtin/packages/ntl/package.py
> +    # notify when the package is updated.
```suggestion
```

2021-10-21 05:39 UTC, alalazo commented on var/spack/repos/builtin/packages/ntl/package.py
> +    Author: Victor Shoup (victor@shoup.net)
Would it be possible to use:
```suggestion
    NTL  -- a library for doing numbery theory
```
? The information removed is subject to more frequent changes and should be found in the homepage of the package that is reported below.

2021-10-21 05:39 UTC, alalazo commented on var/spack/repos/builtin/packages/ntl/package.py
> +    The latest version of NTL is available at http://www.shoup.net.
Can we also remove this:
```suggestion
```
?

2021-10-21 05:39 UTC, alalazo commented on var/spack/repos/builtin/packages/ntl/package.py
> +            description='Build shared library.')
```suggestion
    variant('shared', default=False, description='Build shared library.')
```

2021-10-21 05:39 UTC, alalazo commented on var/spack/repos/builtin/packages/ntl/package.py
> +            # make('check')
Can you either remove this or leave in the code an explanation why it was commented out?

2021-10-21 15:08 UTC, wohlbier commented on var/spack/repos/builtin/packages/helib/package.py
> +    See this report for a description of a few of the algorithms using in this
Making suggested change.

2021-10-21 15:11 UTC, wohlbier commented on var/spack/repos/builtin/packages/ntl/package.py
> +            # make('check')
Will make suggested change.

2021-10-23 15:47 UTC, wohlbier commented
Hi, is there something that I need to do to address `codecov/patch` and `codecov/project`?

Also, I made the mistake of rebasing my feature branch between pushes. Is this Ok, or do I need to clean things up. Thanks.

jgw

2021-10-29 14:05 UTC, wohlbier commented
I'm going to close this and do a new PR that has one commit on top of the tip of develop.

2021-10-29 14:05 UTC, closed without merging