nsimd: Determine SIMD variant automatically by default
LLNL/spack pull request #26850
Opened 2021-10-20 13:28 UTC by eschnett

Manually setting the SIMD variant is still possible.
Also remove default setting `simd=none` which doesn't work with the clingo concretizer.
Also add new version 3.0.1.

2021-10-21 07:29 UTC, alalazo reviewed
I left a few suggestions (beware the snippet have not been tested, so there might be typos/style issues). At a high-level I wonder if we can get completely rid of the variant, since SIMD would be implied by the target and e.g. it doesn't make sense to require `simd=neon` if building for icelake.

2021-10-21 07:29 UTC, alalazo commented on var/spack/repos/builtin/packages/nsimd/package.py
> +                  'avx512vl' in self.spec.target):
Can this be expressed more concisely as `self.spec.satisfies('target=mic_knl')`?

2021-10-21 07:29 UTC, alalazo commented on var/spack/repos/builtin/packages/nsimd/package.py
> +            elif self.spec.target.microarchitecture == 'aarch64':
Maybe:
```suggestion
            elif self.spec.satisfies('target=aarch64'):
```
?

2021-10-21 07:29 UTC, alalazo commented on var/spack/repos/builtin/packages/nsimd/package.py
> +            elif self.spec.target.microarchitecture in ['ppc64', 'ppc64le']:
```suggestion
            elif self.spec.satisfies('target=ppc64:') or self.spec.satisfies('target=ppc64le:']:
```

2021-10-21 14:05 UTC, eschnett commented
I don't think we can get rid completely of the variant. People might want to disable `nsimd` by setting `simd=CPU`. I find this useful when writing code that should run both on a CPU (with SIMD vectorization) and on a GPU (need to disable SIMD vectorization there since the code will be passed on to `nvcc`). There are also variants such as `SVE1024` which select a particular vector size which cannot be auto-detected. Finally, I sometimes wonder whether `simd=AVX2` would lead to better performance than `simd=AVX512` in certain cases, although one could argue that changing this setting for all of Spack would make more sense.

2021-10-21 14:06 UTC, eschnett commented on var/spack/repos/builtin/packages/nsimd/package.py
> +                  'avx512vl' in self.spec.target):
Ooh, yes.

2021-10-21 14:09 UTC, eschnett commented on var/spack/repos/builtin/packages/nsimd/package.py
> +            elif self.spec.target.microarchitecture == 'aarch64':
Done.

2021-10-21 14:09 UTC, eschnett commented on var/spack/repos/builtin/packages/nsimd/package.py
> +            elif self.spec.target.microarchitecture in ['ppc64', 'ppc64le']:
Done.

2021-10-26 15:03 UTC, eschnett commented
The current failure is a "runner system failure; please try again". Can you rerun the tests?

2021-10-26 15:04 UTC, eschnett commented
@spackbot help

2021-10-26 15:04 UTC, eschnett commented
@spackbot re-run pipeline

2021-10-27 15:56 UTC, alalazo requested changes
Just a question, but otherwise LGTM.

2021-10-27 15:56 UTC, alalazo commented on var/spack/repos/builtin/packages/nsimd/package.py
> +                  self.spec.satisfies('target=ppc64le')):
I think there is a typo here:
```suggestion
            elif (self.spec.satisfies('target=ppc64:') or
                  self.spec.satisfies('target=ppc64le:')):
```
What I proposed is "generic ppc64 or higher", so it includes power8, power9 etc. What is currently encoded is "exactly matches generic ppc64".

2021-10-27 15:56 UTC, alalazo commented on var/spack/repos/builtin/packages/nsimd/package.py
> +            elif self.spec.satisfies('target=aarch64'):
Same as the other comment, but for AArch64:
```suggestion
            elif self.spec.satisfies('target=aarch64:'):
```

2021-10-27 19:03 UTC, eschnett commented on var/spack/repos/builtin/packages/nsimd/package.py
> +                  self.spec.satisfies('target=ppc64le')):
Oh; since you said "there might be typos" I thought that was one. I'll update.

2021-10-27 19:05 UTC, eschnett commented on var/spack/repos/builtin/packages/nsimd/package.py
> +                  self.spec.satisfies('target=ppc64le')):
Done.

2021-10-27 19:05 UTC, eschnett commented on var/spack/repos/builtin/packages/nsimd/package.py
> +            elif self.spec.satisfies('target=aarch64'):
Done.

2021-10-28 12:38 UTC, alalazo approved these changes

2021-10-28 12:38 UTC, merged