BigDFT packages
LLNL/spack pull request #26853
Opened 2021-10-20 16:15 UTC by danielecesarini

This is a set of packages for [BigDFT](https://bigdft.org/) suite

2021-10-25 11:55 UTC, danielecesarini commented
Nobody's home?

2021-10-26 00:57 UTC, scheibelp requested changes
I have a few suggestions. I think they could be applied to most of the packages introduced here. Let me know if you disagree or would prefer more explanation.

2021-10-26 00:57 UTC, scheibelp commented on var/spack/repos/builtin/packages/py-bigdft/package.py
> +        with working_dir('PyBigDFT'):
If you set `build_directory = "PyBigDFT"` then you don't have to define `build`/`install` - `PythonPackage` already provides these for you:

```
    phases = ['build', 'install']

    build_directory = "PyBigDFT"
```

2021-10-26 00:57 UTC, scheibelp commented on var/spack/repos/builtin/packages/bigdft-suite/package.py
> +    depends_on('bigdft-futile@develop',    when='@develop')
FWIW if you plan to keep the versions in lockstep in the future you can define these constraints in a for loop:

```
for version in ['1.8.1', ..., '1.9.1']:
    depends_on('bigdft-futile@{0}'.format(version), when='@{0}'.format(version))
```

It looks like not every dependency fits this precisely (e.g. `bigdft-atlab` isn't a dependency for `bigdft-suite@1.8.1`) but this looks like it would work for several of the dependencies.

2021-10-26 00:57 UTC, scheibelp commented on var/spack/repos/builtin/packages/bigdft-spred/package.py
> +        with working_dir('spred'):
You can set `build_directory` at the package level to avoid redefining several of these functions. Most of the logic in this function would probably stick around but likely move to a `configure_args` function.

2021-10-26 00:57 UTC, scheibelp commented on var/spack/repos/builtin/packages/bigdft-psolver/package.py
> +            "FCFLAGS=%s"            % " ".join(fcflags),
It looks like you are explicitly setting `FCFLAGS=` (i.e. empty) here. Note that Spack has mechanisms to translate flags specified on the command line to build system arguments and this would bypass that.

2021-11-03 20:18 UTC, scheibelp commented
Hi @danielecesarini do you think you'll have a chance to address https://github.com/spack/spack/pull/26853#pullrequestreview-788734432 in the next few days?

2021-11-03 20:23 UTC, danielecesarini commented
I am sorry but I need another couple of weeks before to continue this work, too busy with other projects.

Is there something urgent to address on this PR?

2021-11-03 20:32 UTC, danielecesarini commented
> I have a few suggestions. I think they could be applied to most of the packages introduced here. Let me know if you disagree or would prefer more explanation.

Agree with your suggestions, unfortunately I don't have too much time to work on this PR in this period.

2021-11-03 20:34 UTC, scheibelp commented
> Agree with your suggestions, unfortunately I don't have too much time to work on this PR in this period.

No problem! I was just checking in. I'm fine waiting until you get a chance to update this.

2021-12-26 14:31 UTC, danielecesarini commented on var/spack/repos/builtin/packages/py-bigdft/package.py
> +        with working_dir('PyBigDFT'):
It doesn't work, I also tried to define a function with the corresponding property but I still receive an error that I am in the wrong directory to call the _setup.py_

2021-12-26 15:58 UTC, danielecesarini commented on var/spack/repos/builtin/packages/py-bigdft/package.py
> +        with working_dir('PyBigDFT'):
When I overload a phase function the _build_directory_ does not work, I have to explicitly move in a directory. However, see #3150622

2021-12-26 15:59 UTC, danielecesarini commented on var/spack/repos/builtin/packages/bigdft-suite/package.py
> +    depends_on('bigdft-futile@develop',    when='@develop')
done see e34f3d93e19d0b0184581c41a2f8b23538733e3e

2021-12-26 16:00 UTC, danielecesarini commented on var/spack/repos/builtin/packages/bigdft-spred/package.py
> +        with working_dir('spred'):
done see 3150622c8c973ac4131083720ec394e829133e79

2021-12-26 16:07 UTC, danielecesarini commented on var/spack/repos/builtin/packages/bigdft-psolver/package.py
> +            "FCFLAGS=%s"            % " ".join(fcflags),
I have to pass the openmp flag to the configure, what do you suggest?

2022-01-20 11:28 UTC, danielecesarini commented
@scheibelp what do you think?

2022-01-20 23:03 UTC, scheibelp commented on var/spack/repos/builtin/packages/py-bigdft/package.py
> +    def build(self, spec, prefix):
Since you inherit from `PythonPackage`, I would have thought there wouldn't be a need to define `build`/`install` - did you end up needing to do that?

2022-01-20 23:03 UTC, scheibelp commented on var/spack/repos/builtin/packages/bigdft-suite/package.py
> +        install_tree(spec['bigdft-futile'].prefix,    prefix)
Is this package intended to function like an SDK? Generally we don't copy files from dependencies, although that doesn't strictly go against our model to do that. I'm curious if the idea is to expose all of the dependencies together. If this doesn't need to install its own distinct sources you could consider making it a `BundlePackage` (like `xsdk`).

2022-01-20 23:03 UTC, scheibelp commented on var/spack/repos/builtin/packages/bigdft-psolver/package.py
> +            "FCFLAGS=%s"            % " ".join(fcflags),
Sorry I got mixed up - what you have will work fine given our default flag handling (by default we inject flags into the compiler wrapper invocation, which will not conflict with this).

2022-01-20 23:03 UTC, scheibelp requested changes
I have a couple other suggestions. Let me know if they are unclear.

2022-01-21 09:44 UTC, danielecesarini commented on var/spack/repos/builtin/packages/py-bigdft/package.py
> +    def build(self, spec, prefix):
You are right, here we go #ab6ef7d

2022-01-21 09:47 UTC, danielecesarini commented on var/spack/repos/builtin/packages/bigdft-suite/package.py
> +        install_tree(spec['bigdft-futile'].prefix,    prefix)
I didn't know about the BudlePackage, [here](https://github.com/spack/spack/pull/26853/commits/ab6ef7d0e2a75589564ef154ed5f56d3a6f11179) the fix

2022-01-25 12:46 UTC, danielecesarini commented
@scheibelp what do you think?

2022-01-25 18:33 UTC, scheibelp approved these changes

2022-01-25 18:35 UTC, merged

2022-01-25 18:35 UTC, scheibelp commented
This looks great: thanks for all the edits!