draco: new version 7_12_0
LLNL/spack pull request #26907
Opened 2021-10-22 19:48 UTC by keadyk

This adds the tag for our latest draco release to the package file. :)

2021-10-22 23:06 UTC, KineticTheory requested changes

2021-10-22 23:06 UTC, KineticTheory commented on var/spack/repos/builtin/packages/draco/package.py
> +    version('7.12.0',  sha256='37ed8ae851b06ef6206e51b38145734d735ca4ea9f9a71e299e630e7e24ee129')
@keadyk The hash you provided doesn't work for me.  I needed `a127c1c0af44b72775902e2386ed58ff0ebb1907d229e1300176142274c9abc2`.  The Draco recipe uses a `.zip` files instead of a `.tar.gz` file.  I don't remember why this is, but I've continued to use `.zip`.

2021-10-25 13:17 UTC, keadyk commented on var/spack/repos/builtin/packages/draco/package.py
> +    version('7.12.0',  sha256='37ed8ae851b06ef6206e51b38145734d735ca4ea9f9a71e299e630e7e24ee129')
Ok, I'll make this change.

2021-10-25 15:33 UTC, KineticTheory approved these changes
Looks good.  My test build was successful.

2021-10-25 15:33 UTC, KineticTheory approved these changes

2021-10-25 15:34 UTC, KineticTheory commented
@sethrj This looks good to me.  Can you merge it?

2021-10-25 15:35 UTC, sethrj approved these changes

2021-10-25 15:35 UTC, merged