omega-h: add support for stand-alone testing
LLNL/spack pull request #26931
Opened 2021-10-25 14:39 UTC by cwsmith

This PR adds support for `spack test` stand-alone testing.

It also updates the repo url and sets me as the package maintainer.

2021-10-25 18:03 UTC, ibaned submitted a review, later dismissed

2021-10-26 19:26 UTC, ibaned submitted a review, later dismissed

2021-10-26 21:39 UTC, tldahlgren requested changes
Confirmed a few of the sha256 values remain unchanged.

Requested changes for stand-alone test run directory.

2021-10-26 21:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/omega-h/package.py
> +            return
```suggestion
            print('Skipping tests since only relevant for versions > 9.34.1')
            return
```

2021-10-26 21:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/omega-h/package.py
> +            return
Please "log" a message that the tests are being skipped.  It helps know why the test was skipped as opposed to some other issue when debugging tests.

2021-10-26 21:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/omega-h/package.py
> +        if self.spec.version <= Version('9.34.1'):
Are the tests supposed to work for the preferred version (i.e. 9.34.1)?

2021-10-26 21:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/omega-h/package.py
> +        if self.spec.version <= Version('9.34.1'):
```suggestion
        if self.spec.version < Version('9.34.1'):
```

2021-10-26 21:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/omega-h/package.py
> +                      work_dir=self.prefix.bin)
Stand-alone tests should not run under the install prefix *especially* if they generate files.  Otherwise, facility deployments and shared Spack instances will have permissions-related issues.

In this case, it appears you can get away with simply removing `, work_dir=self.prefix.bin`; however, to be safe, you could initialize `exe` so it includes the prefix (e.g., `exe = join_path(self.prefix.bin, 'osh_box')`) *and* remove the `work_dir`.

2021-10-26 21:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/omega-h/package.py
> +                      work_dir=self.prefix.bin)
Same fix as above.

2021-10-26 21:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/omega-h/package.py
> +                      work_dir=self.prefix.bin)
Ditto.

2021-10-27 14:26 UTC, cwsmith commented on var/spack/repos/builtin/packages/omega-h/package.py
> +                      work_dir=self.prefix.bin)
fixed with https://github.com/spack/spack/pull/26931/commits/b0af714d999eff26f5eb1a12cc7ad18ea720258d

2021-10-27 14:26 UTC, cwsmith commented on var/spack/repos/builtin/packages/omega-h/package.py
> +                      work_dir=self.prefix.bin)
Thank you.  This is fixed with https://github.com/spack/spack/pull/26931/commits/b0af714d999eff26f5eb1a12cc7ad18ea720258d .

2021-10-27 14:36 UTC, cwsmith commented on var/spack/repos/builtin/packages/omega-h/package.py
> +                      work_dir=self.prefix.bin)
fixed with https://github.com/spack/spack/pull/26931/commits/b0af714d999eff26f5eb1a12cc7ad18ea720258d

2021-11-02 01:48 UTC, bernhardkaindl commented
@cwsmith When you addressed all requests by tldahlgren, re-request her review by clicking the circle-arrows next to her red +- box (indicating her requesting changes) in the top-right corner of the web page of this PR.

2021-11-02 12:02 UTC, cwsmith commented
@bernhardkaindl Thank you.

2021-11-04 19:01 UTC, tldahlgren approved these changes

2021-11-04 19:02 UTC, merged