py-slurm-pipeline: Add 4.0.4, Fix base.py: import six for @:3
LLNL/spack pull request #26968
Opened 2021-10-27 03:39 UTC by bernhardkaindl

Before 4.0.0, slurm_pipeline/base.py has: `from six import string_types`

In case you want to see it yourself: https://github.com/acorg/slurm-pipeline/commit/f4ea680cc3b9bcacceb14c154d51b5d4003f9598

2021-10-27 16:53 UTC, adamjstewart requested changes
This new version has a dependency on `py-pytest@6.2.2:`. Since it's listed in `install_requires`, we can't ignore it or setuptools/pip will download it for us, which won't work on air-gapped systems. So we need to add an explicit dependency on this. It can be `type='build'` since it isn't actually used at run-time.

2021-10-29 16:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-slurm-pipeline/package.py
> +    # test dependencies are omitted as we don't run unit tests, see #7681
I think this comment can be removed, the package doesn't list any test deps other than pytest.

2021-10-29 16:48 UTC, bernhardkaindl commented on var/spack/repos/builtin/packages/py-slurm-pipeline/package.py
> +    # test dependencies are omitted as we don't run unit tests, see #7681
removed it.

2021-10-29 16:52 UTC, adamjstewart approved these changes

2021-10-29 20:52 UTC, merged