Fix deps of gtk packages: pkgconfig, m4, libtool, libintl
LLNL/spack pull request #26960
Opened 2021-10-27 01:37 UTC by bernhardkaindl

gconf depends on gettext and libintl (dep: intltool)
glibmm, gtkmm, libcanberra and cups need pkgconfig
glibmm needs libsigc++ < 2.9x(which are 3.x pre-releases)
libsigc++@:2.9 depends on m4 for the build

2021-10-27 14:26 UTC, alalazo reviewed
Are there references for the upper bounds in libsigcpp? If there are can you add links in a comment on top of the dependencies with the constraint?

2021-11-01 19:06 UTC, bernhardkaindl commented
> Are there references for the upper bounds in libsigcpp? If there are can you add links in a comment on top of the dependencies with the constraint?

@alalazo done, references added with 2nd, dedicated commit: https://github.com/spack/spack/pull/26960/commits/8e11099675c21347609a36427917c7f3c8015d8d
```py
+    depends_on('libsigcpp')
+    # https://libsigcplusplus.github.io/libsigcplusplus/index.html
+    # sigc++-2.0 and sigc++-3.0 are different parallel-installable ABIs,
+    # libsigcpp@:2.99: are pre-releases of 3.0 and glibmm@:2.19 is not updated for @2.99,
+    # The newer glibmm releases have dependencies which are not yet in spack:
+    depends_on('libsigcpp@:2.9', when='@:2.19')
-    depends_on('libsigcpp@:2.9')
```
Adding current releases like `glibmm-2.70` which work with `libsigcpp-3.0.pc` are a larger task (includes adding new packages).

2021-11-02 09:21 UTC, alalazo requested changes
LGTM, just a possible typo

2021-11-02 09:21 UTC, alalazo commented on var/spack/repos/builtin/packages/libcanberra/package.py
> +    depends_on('libtool')
Should it be:
```suggestion
    depends_on('libtool', type='build')
```
?

2021-11-02 09:23 UTC, bernhardkaindl commented
@alalazo Thanks! applied.

2021-11-02 09:29 UTC, alalazo submitted a review, later dismissed

2021-11-02 09:51 UTC, bernhardkaindl commented
@alalazo I missed a flake8 style error in the comment added before. Fixed now.

2021-11-02 10:29 UTC, alalazo approved these changes

2021-11-02 10:39 UTC, merged