py-ipyparallel: add 7.1.0
LLNL/spack pull request #26984
Opened 2021-10-27 15:29 UTC by genric

Also take releases from pypi.

2021-10-27 16:45 UTC, adamjstewart requested changes

2021-10-27 16:45 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ipyparallel/package.py
> +    depends_on('py-jupyter-packaging', type='build')
I don't think this dependency is actually needed. The only reference I see is that `setup.py` imports `setupbase.py` which was generated by `jupyter-packaging`

2021-10-28 08:57 UTC, genric commented on var/spack/repos/builtin/packages/py-ipyparallel/package.py
> +    depends_on('py-jupyter-packaging', type='build')
It was failing without it when doing `spack install ...` in setupbase.py:
```
    from packaging.version import VERSION_PATTERN
ModuleNotFoundError: No module named 'packaging'
```

2021-10-28 19:37 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ipyparallel/package.py
> +    depends_on('py-jupyter-packaging', type='build')
Ah, then just add a build dep on `py-packaging`? Not sure why they didn't add that to `setup_requires` in `setup.py` but it's in the `pyproject.toml`.

2021-10-29 08:32 UTC, genric commented on var/spack/repos/builtin/packages/py-ipyparallel/package.py
> +    depends_on('py-jupyter-packaging', type='build')
With `py-packaging` I get this:
```
setupbase.py, line 128, in _make_wrapper
    class _Wrapped(klass):
TypeError: NoneType takes no arguments
```

2021-10-29 19:10 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ipyparallel/package.py
> +    depends_on('py-jupyter-packaging', type='build')
Hmm, I don't see what could cause that. `py-jupyter-packaging` isn't aliasing `py-packaging` or anything. Let's keep it your way for now.

2021-10-29 19:10 UTC, adamjstewart approved these changes

2021-10-29 19:10 UTC, merged