py-torch: Add a breakpad variant, disable it for ppc64 and ppc64le
LLNL/spack pull request #26990
Opened 2021-10-27 17:24 UTC by jonglezb

Breakpad is a new dependency (since pytorch 1.9.0). It doesn't build on ppc64le:

    FAILED: third_party/breakpad/CMakeFiles/breakpad_common.dir/src/common/linux/breakpad_getcontext.S.o
    spack-src/third_party/breakpad/src/common/linux/ucontext_constants.h:150:2: error: #error "This header has not been ported for your CPU"
    spack-src/third_party/breakpad/src/common/linux/breakpad_getcontext.S:485:2: error: #error "This file has not been ported for your CPU!"

Add a variant to be able to enable/disable it (only possible since pytorch 1.10.0), and disable it by default on ppc64 and ppc64le.

2021-10-27 17:26 UTC, jonglezb commented
@adamjstewart hi, I'm doing my irregular spack update on ppc64 ;) I expect a few more fixes

2021-10-27 20:04 UTC, adamjstewart requested changes

2021-10-27 20:04 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-torch/package.py
> +        enable_or_disable('breakpad')
```suggestion
        if self.spec.satisfies('@1.10:'):
            enable_or_disable('breakpad')
```

2021-10-28 18:07 UTC, adamjstewart approved these changes

2021-10-28 18:07 UTC, adamjstewart commented
> I expect a few more fixes

Did you want to do these in this PR, or should I merge this and they can be added in followup PRs?

2021-10-29 17:41 UTC, jonglezb commented
Please merge this, other fixes are unrelated (and for now I'm still struggling with build failures and won't have time to sort them out immediately)

2021-10-29 18:00 UTC, merged