New version: py-deprecation 2.1.0
LLNL/spack pull request #27001
Opened 2021-10-28 08:13 UTC by iarspider

2021-10-28 19:40 UTC, adamjstewart requested changes

2021-10-28 19:40 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-deprecation/package.py
>      depends_on('py-setuptools', type='build')
I believe packaging is also needed at run-time

2021-10-28 19:45 UTC, iarspider commented on var/spack/repos/builtin/packages/py-deprecation/package.py
>      depends_on('py-setuptools', type='build')
Yes.

2021-10-28 19:46 UTC, adamjstewart approved these changes

2021-10-30 11:15 UTC, iarspider commented
@spackbot run pipeline

2021-10-30 13:25 UTC, merged