New version: py-html5lib 1.1
LLNL/spack pull request #27059
Opened 2021-10-29 13:58 UTC by iarspider

* Fix URL construction (the default URL generator treats '5lib' as part of the version)
* Fix version comparision

2021-10-29 16:52 UTC, adamjstewart requested changes

2021-10-29 16:52 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-html5lib/package.py
>      pypi = "html5lib/html5lib-099.tar.gz"
```suggestion
    pypi = "html5lib/html5lib-1.1.tar.gz"
```
If you make this change, it will fix the URL parsing issue and you won't need to use `url_for_version`

2021-10-29 16:52 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-html5lib/package.py
> +            url='https://files.pythonhosted.org/packages/source/h/html5lib/html5lib-099.tar.gz')
This URL does not exist. There is a version for `0.99` at `html5lib-0.99.tar.gz` although the checksum is different. I would mark `099` as deprecated, add `0.99`, and mark `1.1` as preferred.

2021-10-29 16:52 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-html5lib/package.py
> +    depends_on('python@2.6:2.8,3.5:', when='@1.1:', type=('build', 'run'))
```suggestion
    depends_on('python@2.7:2.8,3.3:', when='@1.0.1:', type=('build', 'run'))
    depends_on('python@2.7:2.8,3.5:', when='@1.1:', type=('build', 'run'))
```

2021-10-29 16:57 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-html5lib/package.py
> +            url='https://files.pythonhosted.org/packages/source/h/html5lib/html5lib-0.99.tar.gz')
This version shouldn't need a custom URL

2021-10-29 16:59 UTC, adamjstewart submitted a review, later dismissed
I think flake8 will ask for an additional space of indentation

2021-10-29 18:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-html5lib/package.py
> +           preferred=True)
```suggestion
            preferred=True)
```

2021-10-29 18:49 UTC, iarspider commented on var/spack/repos/builtin/packages/py-html5lib/package.py
> +           preferred=True)
@adamjstewart done already :)

2021-10-29 18:57 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-html5lib/package.py
>      depends_on('python@2.6:2.8,3.2:', when='@099', type=('build', 'run'))
```suggestion
    depends_on('python@2.6:2.8,3.2:', when='@0.99', type=('build', 'run'))
```

2021-10-29 19:00 UTC, adamjstewart approved these changes

2021-10-30 11:13 UTC, iarspider commented
@spackbot run pipeline

2021-10-30 12:10 UTC, merged