New versions of py-gitpython: 3.1.13 - 3.1.24
LLNL/spack pull request #27052
Opened 2021-10-29 08:21 UTC by iarspider

2021-10-29 19:13 UTC, adamjstewart requested changes

2021-10-29 19:13 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-gitpython/package.py
> +    depends_on('python@3.6:',   type=('build', 'run'), when='@3.1.18:')
Python 3.7+ is required in the latest version, not sure when that requirement was added

2021-10-30 11:14 UTC, iarspider commented
@spackbot run pipeline

2021-10-30 16:19 UTC, adamjstewart approved these changes

2021-10-30 16:19 UTC, merged