New versions of py-google-auth and py-google-auth-oauthlib
LLNL/spack pull request #27056
Opened 2021-10-29 12:58 UTC by iarspider

2021-10-29 16:57 UTC, adamjstewart requested changes

2021-10-29 16:57 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-google-auth/package.py
> +    depends_on('python@3.6:', type=('build', 'run'), when='@2.3.2:')
`python_requires` still says 2.7 is supported:
```suggestion
    depends_on('python@2.7:2.8,3.6:', type=('build', 'run'), when='@2.3.2:')
```

2021-10-29 16:59 UTC, iarspider commented on var/spack/repos/builtin/packages/py-google-auth/package.py
> +    depends_on('python@3.6:', type=('build', 'run'), when='@2.3.2:')
But the README says otherwise: https://github.com/googleapis/google-auth-library-python/blob/main/README.rst#supported-python-versions 

Supported Python Versions
^^^^^^^^^^^^^^^^^^^^^^^^^
Python >= 3.6

Unsupported Python Versions
^^^^^^^^^^^^^^^^^^^^^^^^^^^
- Python == 2.7:  The last version of this library with support for Python 2.7
  was `google.auth == 1.34.0`.

- Python 3.5:   The last version of this library with support for Python 3.5
  was `google.auth == 1.23.0`.

2021-10-29 19:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-google-auth/package.py
> +    depends_on('python@3.6:', type=('build', 'run'), when='@2.3.2:')
Hmm, someone should tell the developers to update the important files, the README isn't checked by pip lol.

In that case I think you want:
```suggestion
    depends_on('python@3.6:', type=('build', 'run'), when='@1.35:')
    depends_on('python@2.7:2.8,3.6:', type=('build', 'run'), when='@1.24:')
```
Not sure when Python 3.4 support was dropped without digging through the history.

2021-10-30 11:14 UTC, iarspider commented
@spackbot run pipeline

2021-10-30 16:18 UTC, adamjstewart approved these changes

2021-10-30 16:18 UTC, merged