r-dtplyr: add new package
LLNL/spack pull request #27112
Opened 2021-11-01 10:20 UTC by manuelakuhn

2021-11-01 10:50 UTC, manuelakuhn commented
ping @glennpj

2021-11-01 16:58 UTC, manuelakuhn commented
@spackbot run pipeline

2021-11-02 08:58 UTC, manuelakuhn commented
@spackbot run pipeline

2021-11-02 16:26 UTC, glennpj requested changes

2021-11-02 16:26 UTC, glennpj commented on var/spack/repos/builtin/packages/r-dtplyr/package.py
> +    Provides a data.table backend for 'dplyr'. The goal of 'dtplyr' is to
Add a blank line after the first.
```suggestion
    """Data Table Back-End for 'dplyr'.
    
    Provides a data.table backend for 'dplyr'. The goal of 'dtplyr' is to
```

2021-11-02 16:31 UTC, glennpj approved these changes, later dismissed

2021-11-02 20:47 UTC, glennpj approved these changes
Sorry, github's suggested change feature added extra spaces. Looks good.

2021-11-03 00:24 UTC, merged