gcc: Support Darwin 21 (aka Monterey)
LLNL/spack pull request #27133
Opened 2021-11-01 21:06 UTC by eschnett

2021-11-23 07:17 UTC, bernd1995 commented
👍

2021-11-29 16:15 UTC, alalazo requested changes
Left a minor comment. Will try building GCC later. Is it possible to reuse a remote patch?

2021-11-29 16:15 UTC, alalazo commented on var/spack/repos/builtin/packages/gcc/package.py
> +            patch('darwin/patch-darwin21-support.diff', when='@11:')
Does this work too:
```suggestion
        patch('darwin/patch-darwin21-support.diff', when='@11: platform=darwin os=monterey')
```
?

2021-11-29 17:17 UTC, eschnett commented on var/spack/repos/builtin/packages/gcc/package.py
> +            patch('darwin/patch-darwin21-support.diff', when='@11:')
This should work too.

2021-11-29 17:18 UTC, eschnett commented
I am not aware of a remote patch, although either MacPorts or Homebrew might have one that we could reuse.

2021-11-29 19:35 UTC, briederer commented
In case it is helpful. Found these in the [Homebrew repo for gcc][https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gcc.rb]:

General patch ([L17-L20](https://github.com/Homebrew/homebrew-core/blob/7e1d5046945620245be075f23caf2d23646ee3e3/Formula/gcc.rb#L17-L20)): https://github.com/iains/gcc-darwin-arm64/commit/20f61faaed3b335d792e38892d826054d2ac9f15.patch?full_index=1

And a patch which I honestly don't get what it does 😅 ([L62-L67](https://github.com/Homebrew/homebrew-core/blob/7e1d5046945620245be075f23caf2d23646ee3e3/Formula/gcc.rb#L62-67-L20)): https://gcc.gnu.org/git/?p=gcc.git;a=patch;h=fabe8cc41e9b01913e2016861237d1d99d7567bf

2021-11-29 21:01 UTC, eschnett commented
The general Homebrew patch above looks good. We could use it instead of mine.

2021-12-01 10:45 UTC, alalazo commented
> The general Homebrew patch above looks good. We could use it instead of mine.

Yeah, let's go ahead with these two minor modifications and merge this :slightly_smiling_face:

2022-02-05 20:18 UTC, sethrj commented
Superseded by #28662

2022-02-05 20:18 UTC, closed without merging