Update docs how to display loaded modules
LLNL/spack pull request #27159
Opened 2021-11-02 17:33 UTC by RikkiButler20

Refers [#25249 ](https://github.com/spack/spack/issues/25249)

Update the documentation on how to display a list of all modules loaded by `spack find --loaded`

2021-11-02 19:01 UTC, tldahlgren commented
I also recommend adding reminders of `spack find --loaded` at the end of the `Using Extensions` section.

You *might* also want to add a note at the bottom of `Using 'spack load' to Manage the User Environment` (`workflows.rst`) that the `spack find --loaded` command can be used to check what is actually loaded after running the shell script.

2021-11-02 19:01 UTC, tldahlgren requested changes, later dismissed

2021-11-02 19:01 UTC, tldahlgren commented on lib/spack/docs/basic_usage.rst
> +    libelf@0.8.12
IMO. This would flow better after the `Ambiguous specs` section BUT using the context of the previous load command(s).

2021-11-02 19:01 UTC, tldahlgren commented on lib/spack/docs/basic_usage.rst
> +   $ spack find --loaded
The use of `spack find --loaded` seems out of the blue here.

The content might flow better as a separate subsection (as I mentioned in my previous comment).

I also suggest, FWIW, making `When you no longer...` at line 889 a separate paragraph to further emphasize its purpose.

2021-11-02 19:07 UTC, adamjstewart commented
This looks great, thanks!

2021-11-02 19:45 UTC, RikkiButler20 commented
@tldahlgren 
For referencing `spack find --loaded` in `Using Extensions`, should I just add what the output would be if the user ran `spack find --loaded`?

2021-11-02 19:50 UTC, tldahlgren commented
> @tldahlgren
> For referencing `spack find --loaded` in `Using Extensions`, should I just add what the output would be if the user ran `spack find --loaded`?

I would be good to check but not necessary.  It would likely be sufficient to mention the loaded packages can be checked using `spack find --loaded` with a link to the subsection where you introduce `spack find --loaded`.

2021-11-02 21:02 UTC, mwkrentel commented
> You might also want to add a note at the bottom of Using 'spack load' to
> Manage the User Environment (workflows.rst) that the spack find --loaded
> command can be used to check what is actually loaded after running the
> shell script.

Second.  But if it were me, I would go farther.  I would put a line in
the output of `spack load -h` that `spack find --loaded` is how you
get a list of the currently loaded modules.

As I mentioned in #25249, I looked all through spack load, unload and
module for how to do this and eventually gave up, never once thinking
that it would be in the command find.

I would go farther and make `spack load --list` run the same command.

IMO, this is misplaced in find.  `spack load` and `unload` are how you
load and unload spack modules.  So, why is list way off in another place?

2021-11-03 04:23 UTC, tgamblin approved these changes

2021-11-03 05:11 UTC, tgamblin commented
Going to merge this as-is and do `spack load --list` in a separate PR.  I actually have a version of that written up, but it'll need review, too.

2021-11-03 05:12 UTC, merged