sina: add 1.11 version
LLNL/spack pull request #27161
Opened 2021-11-02 17:52 UTC by HaluskaR

2021-11-02 19:45 UTC, estebanpauli submitted a review, later dismissed

2021-11-02 20:52 UTC, murray55 commented
Changes look good! Although I can't approve for some reason.

2021-11-03 22:50 UTC, tldahlgren requested changes

2021-11-03 22:50 UTC, tldahlgren commented on var/spack/repos/builtin/packages/sina/package.py
> +    version('1.11.0', sha256='a080f6583101696a6354940f00646ef892e1b2f8fc3f1b1907ba1c3ade6d4b47')
The Spack convention is for newer versions to appear before older ones.  Please move this *above* `1.10.0`.

2021-11-03 22:50 UTC, tldahlgren commented on var/spack/repos/builtin/packages/sina/package.py
> +    version('1.11.0', sha256='a080f6583101696a6354940f00646ef892e1b2f8fc3f1b1907ba1c3ade6d4b47')
Confirmed the sha256.

2021-11-04 18:10 UTC, tldahlgren submitted a review, later dismissed

2021-11-09 10:36 UTC, haampie commented
@spackbot run pipeline

2021-11-16 21:02 UTC, tldahlgren commented
Please rebase to develop so you can pick up the pipeline fix.

2022-05-09 18:24 UTC, tldahlgren commented
Closing and re-opening to force required audit checks to be re-run.

2022-05-09 18:44 UTC, tldahlgren approved these changes
LGTM

2022-05-09 19:27 UTC, merged