commands: `spack load --list` alias for `spack find --loaded`
LLNL/spack pull request #27184
Opened 2021-11-03 05:48 UTC by tgamblin

See #25249 and https://github.com/spack/spack/pull/27159#issuecomment-958163679.
This adds `spack load --list` as an alias for `spack find --loaded`.  The new command is
not as powerful as `spack find --loaded`, as you can't combine it with all the queries or
formats that `spack find` provides.  However, it is more intuitively located in the command
structure in that it appears in the output of `spack load --help`.

The idea here is that people can use `spack load --list`  for simple stuff but fall back to
`spack find --loaded` if they need more.

- [x] add help to `spack load --list` that references `spack find`
- [x] factor some parts of `spack find` out to be called from `spack load`
- [x] add shell integration
- [x] add shell test
- [x] update completion
- [x] update docs

2021-11-03 14:37 UTC, mwkrentel submitted a review, later dismissed
LGTM, I approve.

2021-11-03 15:23 UTC, adamjstewart approved these changes, later dismissed

2021-11-04 20:08 UTC, RikkiButler20 requested changes

2021-11-04 20:08 UTC, RikkiButler20 commented on share/spack/qa/setup-env-test.sh
> +contains "b@" echo $LIST_CONTENT
```suggestion
contains "b@" echo $LIST_CONTENT
does_not_contain "a@" echo $LIST_CONTENT
```

2021-11-04 20:35 UTC, scheibelp commented on share/spack/qa/setup-env-test.sh
> +contains "b@" echo $LIST_CONTENT
That is now added

2021-11-04 22:42 UTC, RikkiButler20 requested changes

2021-11-04 22:42 UTC, RikkiButler20 commented on share/spack/qa/setup-env-test.fish
> +spt_contains "b@" echo $LIST_CONTENT
```suggestion
spt_contains "b@" echo $LIST_CONTENT
spt_does_not_contain "a@" echo $LIST_CONTENT
```

2021-11-04 23:26 UTC, RikkiButler20 submitted a review, later dismissed
LGTM

2021-11-05 00:17 UTC, tldahlgren requested changes

2021-11-05 00:17 UTC, tldahlgren commented on lib/spack/spack/cmd/load.py
> +        spack.cmd.display_specs(results)
My understanding is this cross-command re-use is frowned upon in Spack.  Instead, the `filter_loaded_specs` and `print_how_many_packages` should be moved out of the commands to a suitable (core) module.

2021-11-05 01:24 UTC, tldahlgren approved these changes, later dismissed

2021-11-05 07:56 UTC, scheibelp approved these changes
(Prior review was approval and the only changes since are for style checks)

2021-11-05 07:58 UTC, merged