[New Package] Add Restic v0.12.1
LLNL/spack pull request #27208
Opened 2021-11-03 23:18 UTC by alecbcs

Restic is a great backup program written in Go that handles secure end-to-end encrypted backups that can be uploaded to multiple cloud providers automatically. If you're interested checkout [restic.net](https://restic.net) for more information.

2021-11-04 18:00 UTC, tldahlgren requested changes
Confirmed the sha256.  Needs the stye error resolved.

2021-11-04 18:00 UTC, tldahlgren commented on var/spack/repos/builtin/packages/restic/package.py
> +    def install(self, spec, prefix):
The following should fix the style error:

```suggestion
    def install(self, spec, prefix):
```

2021-11-04 19:06 UTC, tldahlgren commented
You probably also want to rebase to develop to avoid an issue with the pipeline that was fixed earlier today.

2021-11-04 22:07 UTC, alecbcs commented
@tldahlgren thanks for the catch! So funny a space was hiding out at the end of a line!

2021-11-05 00:12 UTC, tldahlgren approved these changes

2021-11-05 00:12 UTC, merged