mesa: Use the llvm-config of spec['llvm'] for '+llvm'
LLNL/spack pull request #27235
Opened 2021-11-05 00:50 UTC by bernhardkaindl

Fix builds on hosts where /usr/bin/llvm-config-* is found and provides an
incompatible version: Ensure that the llvm-config of spec['llvm'] is used.

2021-11-09 10:44 UTC, haampie submitted a review, later dismissed

2021-11-15 12:32 UTC, alalazo requested changes
There seem to be a legitimate failure in the pipeline: https://gitlab.spack.io/spack/spack/-/jobs/1210117

2021-11-15 21:43 UTC, bernhardkaindl commented
> There seem to be a legitimate failure in the pipeline: https://gitlab.spack.io/spack/spack/-/jobs/1210117

Thanks! Fixed now.

2021-11-16 07:07 UTC, alalazo approved these changes

2021-11-16 07:07 UTC, merged