Add variant for the --enable-two-level-namespace option in MPICH
LLNL/spack pull request #27230
Opened 2021-11-04 20:35 UTC by kgerheiser

We have mixed C/C++ and Fortran in several libraries, and -flat_namespace leads to aborts when exceptions are thrown on macOS.

2021-11-05 15:05 UTC, raffenet submitted a review, later dismissed

2021-11-05 15:14 UTC, raffenet approved these changes, later dismissed

2021-11-09 10:45 UTC, haampie commented on var/spack/repos/builtin/packages/mpich/package.py
> +        'two-level-namespace',
```suggestion
        'two_level_namespace',
```

`-` in variants are confusing

2021-11-09 10:45 UTC, haampie requested changes
see above

2021-11-09 14:00 UTC, kgerheiser commented on var/spack/repos/builtin/packages/mpich/package.py
> +        'two-level-namespace',
Fixed

2021-11-09 14:01 UTC, haampie approved these changes

2021-11-09 15:48 UTC, merged