Backports 0.17.1
LLNL/spack pull request #27261
Opened 2021-11-07 19:43 UTC by haampie

PR with backports cherrypicked from the develop branch for the 0.17.1 release

Included PRs:
- [nothing yet]

2021-11-15 13:26 UTC, alalazo requested changes

2021-11-15 13:26 UTC, alalazo commented on .github/workflows/unit_tests.yaml
> +        . .github/workflows/setup_git.sh
Here we are trying to source a file before cloning the Spack repository. I think this line needs to be added twice in each branch of the test (with and without coverage). 

It's unfortunate, but `centos6` is so old that we can't use the `actions/checkout` action inside it if I recall correctly, so we resort to cloning Spack manually.

2021-12-21 09:29 UTC, alalazo commented
@bonachea We are releasing a patch version of Spack at the end of the week. I have backported 159f4c13f6e6bc57f59bc085cd29a8ce7bea7694 for UPC++. Is that fine with you or are there any more updates needed for the package?

2021-12-21 17:40 UTC, bonachea commented
> @bonachea We are releasing a patch version of Spack at the end of the week. I have backported [159f4c1](https://github.com/spack/spack/commit/159f4c13f6e6bc57f59bc085cd29a8ce7bea7694) for UPC++. Is that fine with you or are there any more updates needed for the package?

@alalazo Looks good to me - thanks! 
We don't have any other changes immediately pending.

2021-12-23 12:21 UTC, alalazo commented
@spackbot run pipeline

2021-12-23 15:01 UTC, alalazo approved these changes

2021-12-23 15:02 UTC, merged