Updated Versions
LLNL/spack pull request #27268
Opened 2021-11-07 22:23 UTC by tuxfan

- Added 7.1 release
- Added master git branch

2021-11-07 22:34 UTC, junghans requested changes

2021-11-07 22:34 UTC, junghans commented on var/spack/repos/builtin/packages/cgdb/package.py
> +    depends_on('autoconf', type='build')
Aren’t these just deps when building master.

2021-11-07 22:34 UTC, junghans commented on var/spack/repos/builtin/packages/cgdb/package.py
> +    version('master', branch='master', submodule=False, preferred=False)
This should go on top.

2021-11-07 23:03 UTC, tuxfan commented on var/spack/repos/builtin/packages/cgdb/package.py
> +    depends_on('autoconf', type='build')
Added.

2021-11-07 23:05 UTC, tuxfan commented on var/spack/repos/builtin/packages/cgdb/package.py
> +    version('master', branch='master', submodule=False, preferred=False)
Done.

2021-11-08 02:41 UTC, junghans approved these changes

2021-11-08 02:41 UTC, merged