Initial Support for CMake Modules
LLNL/spack pull request #27447
Opened 2021-11-14 06:54 UTC by tuxfan

Several projects have not yet added modern CMake support. This package
adds find_package support for some of these projects.

2021-11-14 11:50 UTC, haampie commented
I don't see the point. CMake is open to contributions and it's trivial to install the latest cmake, also without spack. Suppose you manage to upstream these, why would anyone want to use this package instead of a one-line change to cmake_minimum_required(VERSION ...)?

2021-11-14 12:46 UTC, tgamblin commented
@haampie is it just the name you care about? I may not agree with the approach but I don’t think that prevents us from allowing a package like this. We’re not here to tell people how to use CMake - just to support the packages they need.

2021-11-14 12:54 UTC, haampie commented
Well, I have my opinions about this approach. But *if* it's gonna be merged, then please under a more specific name.

There are enough other repos with [extra](https://github.com/vector-of-bool/CMakeCM) [modules](https://github.com/rpavlik/cmake-modules) for cmake and even for these repo's, you'll find [forks of them](https://github.com/bilke/cmake-modules) that don't even get upstreamed to the non-official cmake repo of extra modules.

2021-11-14 17:43 UTC, tgamblin commented
@tuxfan can this have a more specific name?  Like `flecsi-cmake-modules` or `lanl-cmake-modules` or something?

2021-11-15 09:53 UTC, alalazo approved these changes

2021-11-15 09:54 UTC, alalazo requested changes
@tuxfan Can you fix style issues and address other comments in the PR?

2021-11-15 18:54 UTC, tuxfan commented
I renamed the package to `lanl-cmake-modules`. I also added the format bot.

2021-11-15 18:57 UTC, tuxfan commented
@spack-bot format

2021-11-15 20:10 UTC, junghans commented
@spackbot format

2021-11-16 06:30 UTC, alalazo approved these changes

2021-11-16 06:31 UTC, merged