[parallelio] add variant to turn off timing messages.
LLNL/spack pull request #27590
Opened 2021-11-22 17:32 UTC by t-brown

2021-12-06 22:50 UTC, tkameyama submitted a review, later dismissed
I like insert top of cmake_args:
    `define_from_veriant = self.define_from_variant`
and add:
    `define_from_variant('PIO_ENABLE_TIMING', 'timing')`
into args =[]

2021-12-06 22:53 UTC, t-brown commented
> I like insert top of cmake_args: `define_from_veriant = self.define_from_variant` and add: `define_from_variant('PIO_ENABLE_TIMING', 'timing')` into args =[]

I do too, if it is used more than once, however in this case it is not. Would you prefer I did it that way anyway?

2021-12-07 09:31 UTC, tkameyama requested changes

2021-12-07 09:31 UTC, tkameyama commented on var/spack/repos/builtin/packages/wrf/package.py
> +
```suggestion
```
This change should not be made in this PR

2021-12-09 10:22 UTC, tkameyama approved these changes

2021-12-10 22:58 UTC, becker33 approved these changes

2021-12-10 22:58 UTC, merged