Do rpath parsing/replacing in Python, not patchelf
LLNL/spack pull request #27610
Opened 2021-11-23 12:22 UTC by haampie

It turns out patchelf is *very* slow, for some reason I don't entirely understand. I think it has to do with them mmap'ing and still loading entire libraries to memory.

This is not required when you just have to find / replace rpaths, since that requires just a handful of seeks and reads.

This PR adds simple ELF parsing for 32/64 bit BE/LE ELF files.

Note that this means that we don't have to bootstrap patchelf at all for most users, unless the rpath section has to grow. And we can avoid that almost always by adding padding to the bootstrapped binaries (which we currently do not do, hopefully @alalazo can fix https://github.com/alalazo/spack-bootstrap-mirrors/issues/10).

2021-11-23 12:59 UTC, haampie commented
With this:

```python
def _elf_rpaths_for(path):
    return spack.object_file.elf.get_rpaths(path)


def _set_elf_rpaths(target, rpaths):
    assert spack.object_file.elf.replace_rpaths(target, rpaths)
```

```
$ spack clean -db && time spack spec zlib
==> Removing bootstrapped software and configuration in "/tmp/tmp.ylfs25IL9g/bootstrap"
Input spec
--------------------------------
zlib

Concretized
--------------------------------
==> Bootstrapping clingo from pre-built binaries
zlib@1.2.11%gcc@10.3.0+optimize+pic+shared arch=linux-ubuntu20.04-zen2


real	0m2.405s
```

:upside_down_face:

2021-11-23 16:41 UTC, haampie commented
https://github.com/spack/spack/pull/27616 is required for this, so rebased on top of that.

2021-11-24 16:47 UTC, haampie commented
On a slower filesystem:
```
$ ./spack/bin/spack clean -db
$ time ./spack/bin/spack spec zlib
real	0m30.651s
user	0m13.970s
sys	0m2.632s


$ ./spack/bin/spack clean -db
$ time ./spack/bin/spack spec zlib
real	0m14.648s
user	0m5.419s
sys	0m1.395s
```

2021-11-24 17:01 UTC, bernhardkaindl submitted a review, later dismissed
My approval - But I only reviewed the in-place update of the rpath string in ELF.

LGTM! I worked on ELF files/parsing/modifying before, I can attest that this works and is safe.

The other aspects are better reviewed by a spack core developer of course!

2021-11-24 17:05 UTC, haampie commented
Some defensive programming (`f.read(n)` actually returning `n` bytes, and certain offsets/sizes not being `0`) in various places wouldn't hurt, I'll add that later

2021-11-26 11:15 UTC, haampie commented
I've added a --force-rpath equivalent now, as well as making the python-version exit when multiple DT_RPATH/DT_RUNPATH tags exist in the dynamic array, so that we fall back to patchelf in those cases.

2021-11-26 16:09 UTC, haampie commented
Installing LLVM from a binary cache: `88.9` seconds down to `61.8` seconds. That's a 30% reduction in install time.

I also noticed that `patchelf` can't handle some of the cases that I thought it could:

```
==> [2021-11-26-17:03:36.248942] '/home/user/.spack/bootstrap/store/linux-ubuntu20.04-x86_64/gcc-10.3.0/patchelf-0.13-djm2fh7ipgk2vm6ndxqqof4uft2rroai/bin/patchelf' '--force-rpath' '--set-rpath' '' '/tmp/tmp.82RfP3XQ0J/linux-ubuntu20.04-zen2/gcc-10.3.0/llvm-12.0.1-7cwfjliqenxix7axw3fxxr65wda6p34m/lib/libarcher.so'
==> [2021-11-26-17:03:36.365471] Warning: patchelf --force-rpath --set-rpath /tmp/tmp.82RfP3XQ0J/linux-ubuntu20.04-zen2/gcc-10.3.0/llvm-12.0.1-7cwfjliqenxix7axw3fxxr65wda6p34m/lib/libarcher.so failed with error Command exited with status -11:
    '/home/user/.spack/bootstrap/store/linux-ubuntu20.04-x86_64/gcc-10.3.0/patchelf-0.13-djm2fh7ipgk2vm6ndxqqof4uft2rroai/bin/patchelf' '--force-rpath' '--set-rpath' '' '/tmp/tmp.82RfP3XQ0J/linux-ubuntu20.04-zen2/gcc-10.3.0/llvm-12.0.1-7cwfjliqenxix7axw3fxxr65wda6p34m/lib/libarcher.so'
==> [2021-11-26-17:03:36.371928] '/home/user/.spack/bootstrap/store/linux-ubuntu20.04-x86_64/gcc-10.3.0/patchelf-0.13-djm2fh7ipgk2vm6ndxqqof4uft2rroai/bin/patchelf' '--force-rpath' '--set-rpath' '' '/tmp/tmp.82RfP3XQ0J/linux-ubuntu20.04-zen2/gcc-10.3.0/llvm-12.0.1-7cwfjliqenxix7axw3fxxr65wda6p34m/lib/libomp.so'
==> [2021-11-26-17:03:36.491700] Warning: patchelf --force-rpath --set-rpath /tmp/tmp.82RfP3XQ0J/linux-ubuntu20.04-zen2/gcc-10.3.0/llvm-12.0.1-7cwfjliqenxix7axw3fxxr65wda6p34m/lib/libomp.so failed with error Command exited with status -11:
    '/home/user/.spack/bootstrap/store/linux-ubuntu20.04-x86_64/gcc-10.3.0/patchelf-0.13-djm2fh7ipgk2vm6ndxqqof4uft2rroai/bin/patchelf' '--force-rpath' '--set-rpath' '' '/tmp/tmp.82RfP3XQ0J/linux-ubuntu20.04-zen2/gcc-10.3.0/llvm-12.0.1-7cwfjliqenxix7axw3fxxr65wda6p34m/lib/libomp.so'
```

The problem with those libs is that they don't have an rpath to start with, and apparently patchelf cannot handle that case (?). This is because they are runtime LLVM libraries, meaning they are compiled with the just-compiled clang compiler, not with the original gcc, so they're missing spack's compiler wrapper and end up without rpaths.

2021-12-03 09:44 UTC, bernhardkaindl requested changes

2021-12-03 09:44 UTC, bernhardkaindl commented on lib/spack/spack/object_file/elf.py
> +        # Find PT_LOAD to get the
```suggestion
        # For PT_LOAD entries: Save the offsets and virtual addrs of the loaded ELF segments
```
(Unless my guess is wrong our you know a better way to comment this)

2021-12-04 12:45 UTC, bernhardkaindl reviewed
Hi Harmen, I applied my guess to complete the comment so we can merge this soon.

2021-12-04 12:46 UTC, bernhardkaindl submitted a review, later dismissed

2021-12-04 12:48 UTC, bernhardkaindl commented on lib/spack/spack/object_file/elf.py
> +        # For PT_LOAD entries: Save the offsets and virtual addrs of the loaded ELF segments
```suggestion
        # For PT_LOAD entries: Save offsets and virtual addrs of the loaded ELF segments
```

2022-10-31 22:49 UTC, haampie commented
Moved the ELF parsing business into #33628, then a separate PR can be made to actually implement pure-python rpath replacement.

2022-11-02 11:36 UTC, haampie commented
PR now rebased on develop

2022-11-02 12:20 UTC, haampie commented
@spackbot rebuild everything

2022-11-02 13:42 UTC, haampie commented
@scottwittenburg gitlab CI ran on the wrong commit again. This is a huge problem...

2022-11-02 16:39 UTC, haampie commented
@spackbot rebuild everything

2022-11-02 23:00 UTC, haampie commented
@spackbot rebuild everything

2022-11-03 10:19 UTC, haampie commented
@tgamblin: this successfully built the e4s pipeline with 1,000+ jobs without the need for `patchelf`, which makes it good to go. Note that linking requires rpaths to be set correctly too, it's not just a runtime thing, so it's thoroughly tested.

The failures are all `silo`, which is due to a the bug on develop fixed by c716c6ca95e300ac247f668237fc13f75e1b5289.

2022-11-04 09:29 UTC, tgamblin approved these changes

2022-11-04 09:30 UTC, merged