Update portcullis to 1.2.3
LLNL/spack pull request #27661
Opened 2021-11-25 15:50 UTC by ljyanesm

2021-11-29 14:44 UTC, alalazo requested changes

2021-11-29 14:44 UTC, alalazo commented on var/spack/repos/builtin/packages/portcullis/package.py
> +    url      = "https://github.com/ei-corebioinformatics/archive/refs/tags/Release-1.2.3.tar.gz"
The `url` seems incorrect. The correct one has the form:
```
https://github.com/EI-CoreBioinformatics/portcullis/archive/refs/tags/Release-1.1.2.tar.gz
```

2021-12-01 10:52 UTC, alalazo requested changes
Only a minor request

2021-12-01 10:52 UTC, alalazo commented on var/spack/repos/builtin/packages/portcullis/package.py
> +    depends_on('boost', type='build')
```suggestion
    depends_on('boost')
```
In our current dependency model header only libraries are still of `link` type. Roughly `build` and `run` identify dependencies on executables that are used in a separate process at either build-time or run-time.

2021-12-01 11:12 UTC, ljyanesm commented
@alalazo, thank you for reviewing these changes

2021-12-01 11:29 UTC, alalazo approved these changes
Thanks!

2021-12-01 12:34 UTC, merged