Add sphinx-tabs package
LLNL/spack pull request #27698
Opened 2021-11-29 18:05 UTC by schmitts

2021-11-30 16:51 UTC, adamjstewart requested changes

2021-11-30 16:51 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-sphinx-tabs/package.py
> +    depends_on('python@3.6:',       type=('build', 'run'))
```suggestion
    depends_on('python@3.6:3',       type=('build', 'run'))
```

2021-11-30 16:51 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-sphinx-tabs/package.py
> +    depends_on('py-sphinx@2:',      type=('build', 'run'))
```suggestion
    depends_on('py-sphinx@2:4',      type=('build', 'run'))
```

2021-11-30 16:51 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-sphinx-tabs/package.py
> +    depends_on('py-docutils@0.17:', type=('build', 'run'))
```suggestion
    depends_on('py-docutils@0.16.0:0.16', type=('build', 'run'))
```

2021-11-30 16:51 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-sphinx-tabs/package.py
> +    depends_on('py-docutils@0.17:', type=('build', 'run'))
You'll also need to add version 0.16 to the py-docutils package

2022-05-05 15:57 UTC, alalazo commented
@schmitts

2022-05-05 16:53 UTC, schmitts commented
> @schmitts

Forgot about the PR. Will update.

2022-05-06 15:33 UTC, adamjstewart approved these changes

2022-05-06 15:33 UTC, merged