Prevent S3 information on non-S3 mirrors
LLNL/spack pull request #27701
Opened 2021-11-29 18:14 UTC by josephsnyder

Switch from looking at the presence of the S3 information keys to
determine if the dictionary URL is used to instead look at the value
in the keys.

Add s3_endpoint_url as an additional key value for the S3 information.

See https://github.com/spack/spack/pull/27694#issuecomment-981780696

2021-12-07 15:39 UTC, opadron approved these changes, later dismissed

2021-12-07 19:40 UTC, scheibelp commented
Does this fix https://github.com/spack/spack/pull/27694? If so, you can add `Fixes #27694` to the initial post in this thread and it will be automatically closed when this is merged.

2021-12-08 19:45 UTC, josephsnyder commented
@scheibelp, #27694 is a pull request and the reason it is linked is that there is a comment requesting this particular change.  I separated them to make things easier.

2021-12-21 18:25 UTC, josephsnyder commented
@opadron,  I'd like to keep these moving.  Do you have the time for a review on this and #27694?

2021-12-21 20:35 UTC, opadron approved these changes, later dismissed

2021-12-22 18:42 UTC, alalazo commented
Can you also fix printing mirrors to screen? After #27694 I get:
```console
$ spack mirror list
tmp1            CommentedMap([('url', 'file:///tmp/mirror'), ('access_pair', [None, None]), ('access_token', None), ('profile', None), ('endpoint_url', None)]) (fetch)
tmp1            CommentedMap([('url', 'file:///tmp/mirror'), ('access_pair', [None, None]), ('access_token', None), ('profile', None), ('endpoint_url', None)]) (push)
spack-public    https://mirror.spack.io
```

2021-12-22 19:05 UTC, josephsnyder commented
@alalazo, I don't see that happening on the `develop` branch (commit SHA: b7b654280485c0e84692b4706abe0ef97f01535c)

```
(spack_env) snyder@irune-journal:~/Work/ECP/spack$ ./bin/spack mirror add  minio s3://sample --s3-endpoint-url http://10.50.57.119:9000 --s3-access-key-id 892W696SB0HMCPS2BDIA --s3-access-key-secret 5UNcUWqOyWmQGIZ5qOj7RiRyY4m5EnixXdUCzhFt
(spack_env) snyder@irune-journal:~/Work/ECP/spack$ ./bin/spack mirror add  miniolocal file:///tmp/mirror
(spack_env) snyder@irune-journal:~/Work/ECP/spack$ ./bin/spack mirror list
spack-public    https://mirror.spack.io
miniolocal      file:///tmp/mirror (fetch)
miniolocal      file:///tmp/mirror (push)
minio           s3://sample (fetch)
minio           s3://sample (push)

```

2021-12-22 21:04 UTC, alalazo commented
@josephsnyder Yeah, sorry for the noise. I could reproduce the error I posted reliably until I tried:
```console
$ spack clean -a
```
and cleaning the cache made it disappear somehow. I am not sure what could have caused it in the first place though I have been moving across branches a lot...

2022-05-23 18:36 UTC, opadron requested changes

2022-05-23 18:36 UTC, opadron commented on lib/spack/spack/mirror.py
> +    if any(vars(args)[value] for value in key_values if value in args):
I seem to recall that `args` is now supposed to be a `namespace` object with attributes instead of a mapping with keys.  (That would explain the use of `vars`, here).

I think that's fine, but something would need to be done about the default for `args`, since it doesn't make sense to default to an empty dict, anymore.

Maybe default to `None` and have some branch that handles `None`?

2022-05-24 16:16 UTC, becker33 commented on lib/spack/spack/mirror.py
> +    if any(vars(args)[value] for value in key_values if value in args):
The code is only called from one place, and it supplies `args`. Maybe it should just make `args` a required argument?

2024-07-08 08:22 UTC, closed without merging

2024-07-08 08:22 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.