Improve debug info from concretizer
LLNL/spack pull request #27707
Opened 2021-11-30 01:02 UTC by becker33

Previously, there was no way to get the full unsat core for debugging. This PR makes 2 changes to the concretizer behavior in debug mode.

1. All facts are assumptions, and therefore eligible to be in the core
2. Cores are not minimized, because the performance is prohibitive for full cores

2021-11-30 01:30 UTC, tgamblin requested changes
Looks good, but:

1. Needs a test
2. One request below (if it's tricky we can save it for another PR)

2021-11-30 01:30 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> +        conflicts = self.format_cores() if debug else self.format_minimal_cores()
Any chance that `format_cores()` could eventually call `colify()` to display the facts?

2021-11-30 07:45 UTC, schmitts commented
Hi! Thanks for making the debug output more verbose. On a system with gcc 8.3.0 it outputs now:

```
spack -d install arbor
...
spack.error.SpackError: arbor is unsatisfiable, conflicts are:
  A conflict was triggered
  condition(202)
  condition(203)
  condition(204)
  condition(205)
  conflict("arbor",202,203)
  conflict("arbor",204,205)
  node_compiler_version_satisfies("arbor","clang",":7","7.0.1")
  node_compiler_version_satisfies("arbor","gcc",":8.3","4.8")
  node_compiler_version_satisfies("arbor","gcc",":8.3","4.9.2")
  node_compiler_version_satisfies("arbor","gcc",":8.3","8.3.0")
  root("arbor")
  ```
  
This is already much better than without this commit. However, the old concretizer gave a more user friendly message already without the debug option: `1. "%gcc@:8.3" conflicts with "arbor"`.

Any chance of outputting the abridged reason for the conflict with clingo when envoking `spack install arbor`?

Don't get me wrong, I'm happy now. But I guess that new users will stumble upon:

```
spack install arbor     
==> Error: arbor is unsatisfiable, conflicts are:
  A conflict was triggered
```

If adding the reason for the conflict at this stage is difficult, could we add "Run with `spack -d` to get more information" to the Error?

(It's also not about Arbor in particular, but any conflict in conretization.)

2021-12-01 23:21 UTC, becker33 commented
@tgamblin Added a test

Also experimented with including the `conflict` function instantiations in the assumptions and add the message as a 4th argument to the `conflict` function in ASP, but that led to >2x slowdowns in failed concretizations, I believe from having to minimize the larger set.

2021-12-05 21:24 UTC, tgamblin submitted a review, later dismissed

2021-12-07 22:52 UTC, adamjstewart commented
Just tried this on a package that I know doesn't concretize. This doesn't seem to be a minimal unsat core:
```console
$ spack -d spec gdl+python
```
[gdl-python-core.txt](https://github.com/spack/spack/files/7672100/gdl-python-core.txt)

Spoiler alert: it's 138K lines long...

2021-12-09 17:14 UTC, becker33 commented
@adamjstewart yeah, it's definitely not minimal. Clingo won't give minimal cores, and it takes tens of minutes for us to use clingo to find which part of the core is minimal. That's why we're not showing the full core without debug mode, because 138k lines is too much. But that's the best clingo will give us without spending hours on computing it.

If you replace `format_cores` with `format_minimal_cores` on line 397 in asp.py, you can try it for yourself, but with 138k facts in the non-minimal core I recommend running it overnight.

2021-12-10 09:47 UTC, alalazo approved these changes

2021-12-10 09:49 UTC, merged

2021-12-10 10:01 UTC, haampie commented
Didn't have the chance to review, but hiding this behind `-d` is too obscure, and `-d` output is very verbose in general...

How about showing it by default? Or under `spack -v ...`?

2021-12-10 10:06 UTC, alalazo commented
> How about showing it by default? Or under spack -v ...?

The fact is that, right now, this can produce for certain specs 138k lines of conflicts - so not exactly what you want to have on by default :laughing:

2021-12-10 10:07 UTC, alalazo commented
To be clear, I think once we have a way to get a minimal set of cores in a sane amount of time that would be the default error handling.

2021-12-10 10:30 UTC, haampie commented
can you check https://github.com/spack/spack/pull/27906?