Adding EGL support to VTK and ParaView
LLNL/spack pull request #27726
Opened 2021-11-30 18:57 UTC by stephencrowell

- Dependent on #26301 
- Adds EGL support to VTK and ParaView using a patch to VTK
- Updates variants to allow for `egl` variant for VTK and ParaView

2022-01-12 23:55 UTC, vicentebolea commented
@stephencrowell Great work!

I would not be able to review this merge request since it changes many files outside of my area of responsibility, maybe other maintainers might also feel the same way. Some pointer to help this getting merged:

- Split this changes into multiple Pull Requests each of them targeting a single package ideally.
- Squash the commits into states that builds/works, ideally one commit per Pull Request however more if needed.

2022-01-21 18:16 UTC, EthanS94 commented
@stephencrowell Thanks for all this work! I am trying it out with `paraview+egl`. One issue I hit is the patch `egl-device.patch` failed with `paraview@5.10.0`. I get a file `vtkEGLRenderWindow.cxx.rej` with these contents if it helps:

```patch
--- VTK/Rendering/OpenGL2/vtkEGLRenderWindow.cxx
+++ VTK/Rendering/OpenGL2/vtkEGLRenderWindow.cxx
@@ -459,27 +555,10 @@ void vtkEGLRenderWindow::ResizeWindow(int width, int height)

   if (impl->Display == EGL_NO_DISPLAY)
   {
-    // eglGetDisplay(EGL_DEFAULT_DISPLAY) does not seem to work
-    // if there are several cards on a system.
-    this->SetDeviceAsDisplay(this->DeviceIndex);
-
-    // try to use the default display
-    if (impl->Display == EGL_NO_DISPLAY)
-    {
-      impl->Display = eglGetDisplay(EGL_DEFAULT_DISPLAY);
-    }
-
-    EGLint major = 0, minor = 0;
-    vtkEGLDisplayInitializationHelper::Initialize(impl->Display, &major, &minor);
-#if !defined(ANDROID)
-    if (major <= 1 && minor < 4)
-    {
-      vtkErrorMacro("Only EGL 1.4 and greater allows OpenGL as client API. "
-                    "See eglBindAPI for more information.");
-      return;
-    }
-    eglBindAPI(EGL_OPENGL_API);
-#endif
+    if (!this->SetDeviceAsDisplay(this->DeviceIndex))
+    {
+      return;
+    }  
   }

   /* Here, the application chooses the configuration it desires. In this
```

2022-01-27 02:03 UTC, vicentebolea requested changes
@stephencrowell Great work!

I would not be able to review this merge request since it changes many files outside of my area of responsibility, maybe other maintainers might also feel the same way. Some pointer to help this getting merged:

- Split this changes into multiple Pull Requests each of them targeting a single package ideally.
- Squash the commits into states that builds/works, ideally one commit per Pull Request however more if needed.

2022-11-29 17:24 UTC, toxa81 commented
Hello all! We at CSCS would like to give a try to paraview+egl. What is the status of this effort to merge the PR? Is there something we can help with?

2024-11-26 06:20 UTC, alalazo commented
What is the state of this PR?

2025-06-14 06:37 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen here https://github.com/spack/spack-packages if you want to continue work on this.

2025-06-14 06:37 UTC, closed without merging