Superlu: Update Spack test dir
LLNL/spack pull request #27844
Opened 2021-12-07 20:50 UTC by RikkiButler20

Re-work parallel-netcdf from building in the install test root to using the test suite cache directory.

2022-01-05 17:32 UTC, tldahlgren requested changes
Not sure if this is still in DRAFT mode, but providing a couple of suggested fixes.

2022-01-05 17:32 UTC, tldahlgren commented on var/spack/repos/builtin/packages/superlu/package.py
> +            print('Skipping superlu test')
This needs a more informative message, perhaps:

```suggestion
            print('Skipping superlu test: missing required {0}'.format(test_dir))
```

2022-01-05 17:32 UTC, tldahlgren commented on var/spack/repos/builtin/packages/superlu/package.py
> +                          options=['-I{0}'.format(join_path(self.prefix, 'include'))],
Recommend using the approach at line 184:

```suggestion
                          options=['-I{0}'.format(self.prefix.include)],
```

2022-02-25 01:48 UTC, RikkiButler20 commented
I've tried running the test using the the `Makefile` that was copied over during the installation, but I get this error that I have attached. I believe that the order that the libraries are aren't in the right order. The recent versions of GCC require that you put the object files and libraries in the order that they depend on each other.
I've been able to run the stand alone test when I use `run_superlu_test` and run the test manually. 

https://stackoverflow.com/questions/12748837/c-shared-library-undefined-reference-to-fooclasssayhello
[superlu_error.log](https://github.com/spack/spack/files/8137702/superlu_error.log)

2022-02-25 02:41 UTC, sethrj commented
> @sethrj I've tried running the test using the the `Makefile` that was copied over during the installation, but I get this error that I have attached. I believe that the order that the libraries are aren't in the right order. The recent versions of GCC require that you put the object files and libraries in the order that they depend on each other. I've been able to run the stand alone test when I use `run_superlu_test` and run the test manually. Do you have any suggestions?
> 
[superlu_error.log](https://github.com/spack/spack/files/8137702/superlu_error.log)

I haven't built the SuperLU tests before, but the line
```
/g/g0/butler59/.spack/test/d5st62plmsbrbq3n55gyhazaybbdwpij/superlu-5.3.0-nja4n2k/cache/superlu/EXAMPLE/superlu: error while loading shared libraries: libopenblas.so.0: cannot openshared object file: No such file or directory
```
is a classic indicator of a missing [rpath](https://spack.readthedocs.io/en/latest/packaging_guide.html#handling-rpaths). Normally you wouldn't see this because you'd have an environment module for superlu that would set either `LD_RUN_PATH` (which would add the rpath to your test executable) or `LD_LIBRARY_PATH` (which would let the linker find it when you run the test exe). The key thing is that linking your exe and running it require information about its dependent libraries in different ways. Given the simplicity of the test makefile I'm not sure the right solution -- CMake would be able to handle this automatically, as would the spack compiler wrappers. Maybe @tldahlgren could offer help in that direction for the smoke tests.

2022-03-01 18:57 UTC, tldahlgren approved these changes
Tests work for me against non-deprecated versions.

2022-03-01 19:00 UTC, tldahlgren commented
@sethrj @sshudler @jrood-nrel As past (significant) contributors to this package, did you want to comment on this PR before it is merged?

2022-03-01 20:12 UTC, jrood-nrel commented
We do not use SuperLU in my project any longer in which I have curated SuperLU in the past, so I don't have any opposition to this PR.

2022-03-02 00:18 UTC, sethrj approved these changes
LGTM

2022-03-02 00:20 UTC, merged