PICMI: 0.16 & 0.18 & WarpX 1D
LLNL/spack pull request #27876
Opened 2021-12-09 00:16 UTC by ax3l

Update the `py-picmistandard` and the latest WarpX release.
Preparing 1D support (testable inputs coming for 22.01+).

Follow-up to #27800

2021-12-09 17:33 UTC, dpgrote submitted a review, later dismissed
The changes look good to me.

2021-12-09 19:00 UTC, ax3l commented on var/spack/repos/builtin/packages/warpx/package.py
> +        inputs_nD = {'1': 'inputs_1d', '2': 'inputs_2d', '3': 'inputs_3d', 'rz': 'inputs_2d_rz'}
```suggestion
        inputs_nD = {'1': 'inputs_1d', '2': 'inputs_2d', '3': 'inputs_3d',
                     'rz': 'inputs_2d_rz'}
```

2021-12-09 19:00 UTC, ax3l commented on var/spack/repos/builtin/packages/py-picmistandard/package.py
> +    pypi     = 'picmistandard/picmistandard-0.0.17.tar.gz'
```suggestion
    pypi     = 'picmistandard/picmistandard-0.0.18.tar.gz'
```

2021-12-09 19:04 UTC, adamjstewart requested changes

2021-12-09 19:04 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-picmistandard/package.py
> +    pypi     = 'picmistandard/picmistandard-0.0.17.tar.gz'
```suggestion
    pypi     = 'picmistandard/picmistandard-0.0.18.tar.gz'
```

2021-12-09 19:04 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-picmistandard/package.py
>      depends_on('py-numpy', type=('build', 'run'))
```suggestion
    depends_on('py-numpy@1.15:1', type=('build', 'run'))
    depends_on('py-scipy@1.5:1', type=('build', 'run'))
```
Haven't checked older versions, but this is the requirement in 0.0.18.

2021-12-09 19:04 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-warpx/package.py
>      depends_on('py-setuptools@38.6:', type='build')
```suggestion
    depends_on('py-setuptools@42:', type='build')
    depends_on('py-cmake@3.15:3', type='build')
```
From the `pyproject.toml`

2021-12-09 19:04 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-warpx/package.py
>      depends_on('py-mpi4py@2.0.0:', type=('build', 'run'), when='+mpi')
```suggestion
    depends_on('py-mpi4py@2.1.0:', type=('build', 'run'), when='+mpi')
```

2021-12-11 06:54 UTC, ax3l commented on var/spack/repos/builtin/packages/py-picmistandard/package.py
> +
```suggestion
```

2021-12-11 19:02 UTC, ax3l commented
Ready for merge :)

2021-12-11 19:33 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-warpx/package.py
>      depends_on('python@3.6:', type=('build', 'run'))
```suggestion
    depends_on('python@3.6:3.9', type=('build', 'run'))
```

2021-12-11 21:05 UTC, adamjstewart approved these changes

2021-12-11 21:14 UTC, merged