[mesa] meson stage needs python3.8+
LLNL/spack pull request #28018
Opened 2021-12-15 09:48 UTC by stephenmsachs

`importlib.metadata` is only available from python3.8

Maintainers: @chuckatkins, @v-dobrev

2021-12-15 13:11 UTC, v-dobrev approved these changes

2021-12-15 14:40 UTC, mwkrentel commented
I'm sure I've built meson with python 3.6.x some months ago.
Could we check if 3.8 is only required for more recent meson and add `when` to the depends?

2021-12-15 15:35 UTC, alalazo requested changes
I assume this requirements is not true for all the versions in the package file. Can you be more specific and list minimum requirements per version range of `mesa` using a `when=` argument?

2021-12-20 14:24 UTC, stephenmsachs commented
I digged down more into this issue and it seems to be way deeper. Adding adamjstewart@  and skosukhin@ as python/package.py maintainers.

While installing `meson`, the default python build_system will add  `--install-purelib=$PREFIX/lib/python3.7/site-packages` and `--install-platlib=$PREFIX/lib64/python3.7/site-packages'`.  These two location are determined by calling `get_python_lib(False,False)` and `get_python_lib(True,False)`, respectively. 

The meson libraries all go into the `lib` subdirectories, while the `lib64` subdirs remain empty.

For the `mesa` installation envrionment the function `setup_dependent_build_environment()` in `python/package.py` will add `$PREFIX/lib64/python3.7/site-packages` to the PYTHONPATH. This is defined by calling get_python_lib(True,False) in `site_packages_dir()`. So, mesa cannot find the meson libraries because its `PYTHONPATH` is configured fot the wrong library paths.

2022-01-13 09:24 UTC, stephenmsachs commented
This ecxact issue is tracked in https://github.com/spack/spack/issues/26546. Closing in favor of the other issue.

2022-01-13 09:24 UTC, closed without merging