[Axom] New version numbers
LLNL/spack pull request #28067
Opened 2021-12-17 22:44 UTC by white238

Just adding the new releases, and very slight changes

2021-12-18 00:18 UTC, white238 commented on var/spack/repos/builtin/packages/axom/package.py
> +        depends_on('umpire@5:5.0.1', when='@:0.5.0')
Looking over previous change and the issue that it was referencing, Axom pre 0.6.0 worked with Umpire 5.0.0 and 5.0.1.  I thinks this change is more accurate.  

It also adds the newer umpire for axom@0.6.0+

2021-12-18 00:24 UTC, tldahlgren commented on var/spack/repos/builtin/packages/axom/package.py
> +    depends_on("kvtree@main", when="+scr")
Great catch!

2021-12-20 07:06 UTC, alalazo requested changes
It seems Gitlab pipelines failed compiling the new version of `axom` on some template argument deduction error

2021-12-20 20:44 UTC, white238 commented
> It seems Gitlab pipelines failed compiling the new version of `axom` on some template argument deduction error

I found one error where it was defaulting to raja 0.13.0 which definitely doesn't work with the Axom versions.  This should fix that. Hopefully it's the only problem.

2021-12-21 02:46 UTC, white238 commented
> > It seems Gitlab pipelines failed compiling the new version of `axom` on some template argument deduction error
> 
> I found one error where it was defaulting to raja 0.13.0 which definitely doesn't work with the Axom versions. This should fix that. Hopefully it's the only problem.

... insert narrator's voice ... It was not.

2021-12-21 03:12 UTC, white238 commented
This now passes!

2021-12-21 09:30 UTC, alalazo approved these changes

2021-12-21 09:40 UTC, merged