Docs: Add developer workflow to main docs
LLNL/spack pull request #28062
Opened 2021-12-17 03:39 UTC by tldahlgren

This PR adds documentation for developer workflows.  It reflects a project-based, pared down version of the current tutorial.

TODO:
- [ ] Update/correct GPG information
- [ ] Add discussion of using the `-k` key
- [ ] Ensure the process flow is correct and complete

2022-03-29 00:16 UTC, tldahlgren commented
@becker33 Rebased

2024-11-26 06:25 UTC, alalazo commented
@tldahlgren What is the status of this PR?

2025-01-08 22:29 UTC, tldahlgren commented
> @tldahlgren What is the status of this PR?

Haven 't worked on it since I was waiting on more feedback from @becker33 back in early 2022. Clearly needs a rebase.

What do you think @becker33?

2025-01-15 01:04 UTC, becker33 requested changes

2025-01-15 01:04 UTC, becker33 commented on lib/spack/docs/developer_workflow.rst
> +by Spack) environment specifying potentially constrained packages that the
developer workflows can work just as well in managed environments -- it's usually the other, but I don't think we need to specify that in the docs.

2025-01-15 01:04 UTC, becker33 commented on lib/spack/docs/developer_workflow.rst
> +    $ spack develop $PACKAGE@$VERSION
We should probably show this using a git branch version like `develop`, as that's the overwhelmingly likely default case.

2025-01-15 01:04 UTC, becker33 commented on lib/spack/docs/developer_workflow.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
All of the buildcache related content seems misplaced here -- This would seem like a good place for a pointer to content somewhere else on how to create binary caches if you want them, but the binary cache and the developer workflow are not inherently entwined. 

I'm pretty sure we already have a docs section on binary caches that this could move to or be merged with, depending how the coverage there is so far.

2025-01-15 01:04 UTC, becker33 commented on lib/spack/docs/developer_workflow.rst
> +
There should be coverage in this section of the `dev_path` variable and how it creates provenance for developer builds. There should also be coverage here for how we manage rebuilds based on time of install for developer builds.

It might also be worth working in a mention of how these builds are analogous to `spack dev-build`, but with the additional infrastructure of an environment.

2025-01-15 01:04 UTC, becker33 commented on lib/spack/docs/environments.rst
> +* Environments can be used to manage large software deployments.
This list should also mention pushing to a build cache

2025-01-15 01:04 UTC, becker33 commented on lib/spack/docs/environments.rst
> +directory, enter:
I think this is expressed backwards -- the example is creating a managed environment from an existing independent environment, not the other way around.

It may also be worth mentioning the new `spack env track/untrack` feature here.

2025-01-15 01:04 UTC, becker33 commented on lib/spack/docs/environments.rst
> +   environment.
```suggestion
   A Spack environment created from a ``spack.lock`` lockfile
   is guaranteed to have the same abstract and concrete specs as the original
   environment, but it will not preserve configuration options.
```

2025-01-15 01:04 UTC, becker33 commented on lib/spack/docs/environments.rst
> +   $ spack env activate -d /path/to/myenv/directory
You don't actually need the `-d` argument here, which makes the distinction between this section and the previous seem unnecessary. You can list a path or name directly.

2025-08-20 00:32 UTC, tldahlgren commented
Closing since we can point ppl to the tutorial at https://spack-tutorial.readthedocs.io/en/latest/tutorial_developer_workflows.html.

2025-08-20 00:32 UTC, closed without merging