for Cray's libsci in blaspp, set BLA_VENDOR=all
LLNL/spack pull request #28104
Opened 2021-12-21 04:13 UTC by lukebroskop

2021-12-22 06:41 UTC, teonnik submitted a review, later dismissed

2021-12-22 07:57 UTC, Sely85 submitted a review, later dismissed

2021-12-23 17:00 UTC, mgates3 commented
I don't understand this PR. Spack is requesting to use a specific BLAS library (Cray libsci), but then this is circumventing that to do a general search using BLA_VENDOR=all (where "all" is not even a listed option at https://cmake.org/cmake/help/latest/module/FindBLAS.html#blas-lapack-vendors). The search may find Cray libsci, but it may find something else like OpenBLAS — just depends on what is available. Can @lukebroskop please describe what this was suppose to be fixing & how?

We can investigate more after the holidays and submit a correction.

2022-01-03 02:21 UTC, sethrj requested changes
Same as https://github.com/spack/spack/pull/28125: instead of adding empty flags, make `args` a local variable and `args.append(self.define('BLA_VENDOR', 'all'))`.

Also are you sure it should be `all` instead of `cray`? because that's the one you require in `lapackpp`.

2022-01-05 17:10 UTC, lukebroskop commented
Thanks @mgates3 , I used `BLA_VENDOR=all` to work around a cmake configure error on spock. I will change `BLA_VENDOR=all` to `BLA_VENDOR=CRAY` which should have the same effect. Do you have another suggestion?

2022-01-05 17:11 UTC, lukebroskop commented
Thanks @sethrj

2022-01-05 18:18 UTC, sethrj requested changes

2022-01-05 18:18 UTC, sethrj commented on var/spack/repos/builtin/packages/blaspp/package.py
> +            args
This is not right, and you'll also note the style tests are failing due to lines 59 and probably for the superfluous parens in 58. Do:
```
        args = [
            '-Dbuild_tests=%s'       % self.run_tests,
            '-Duse_openmp=%s'        % ('+openmp' in spec),
            '-DBUILD_SHARED_LIBS=%s' % ('+shared' in spec),
            backend_config,
            '-DBLAS_LIBRARIES=%s'    % spec['blas'].libs.joined(';'),
        ]

        if spec['blas'].name == 'cray-libsci':
            args.append(self.define('BLA_VENDOR', 'CRAY'))

        return args
```

2022-01-05 19:19 UTC, sethrj approved these changes

2022-01-05 20:51 UTC, teonnik approved these changes
I tested this on Piz Daint with `cray-libsci` explicitly set as a dependency and it builds fine.

2022-01-08 20:41 UTC, merged