[py-aiohttp] added new version
LLNL/spack pull request #28132
Opened 2021-12-22 14:14 UTC by mdorier

New versions for the py-aiohttp package.

2021-12-22 15:42 UTC, adamjstewart requested changes

2021-12-22 15:42 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-aiohttp/package.py
>      depends_on('py-setuptools', type='build')
```suggestion
    depends_on('py-setuptools@46.4:', type='build')
```

2021-12-22 15:42 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-aiohttp/package.py
>      depends_on('py-setuptools', type='build')
Other deps need to be updated too, see `setup.cfg`

2021-12-30 17:57 UTC, adamjstewart approved these changes

2021-12-30 17:58 UTC, merged

2021-12-30 18:17 UTC, mdorier commented
I think there were still dependencies to be added.

2021-12-30 18:31 UTC, adamjstewart commented
Ah yes, there are definitely missing deps, can you submit another PR?

2021-12-30 18:39 UTC, mdorier commented
I was looking into it this afternoon but saw that some deps aren't yet in spack (or at least not a recent-enough version), and got discouraged. I need to find the time to look again into it.

2021-12-30 18:51 UTC, adamjstewart commented
We could also revert this PR if you don't have time to add the deps and don't want a broken package in develop.

2021-12-30 19:07 UTC, mdorier commented
I think that would be best, it's going to take me a few days before I can circle back to it. Thanks!

2021-12-31 08:59 UTC, mdorier commented
Updating the py-aiohttp package with correct dependencies for the new version will require the following PRs to be merged:
- https://github.com/spack/spack/pull/28194
- https://github.com/spack/spack/pull/28195

2021-12-31 16:56 UTC, adamjstewart commented
Just so you know, we used to have a policy where we tried to keep each PR to only a single package, but we've recently relaxed this so that packages that depend on changes in another package can be bundled in a single PR. You're welcome to continue submitting separate PRs for each change, but you don't have to anymore.

2021-12-31 17:19 UTC, mdorier commented
That's good to know!