[py-asynctest] Added py-asynctest package
LLNL/spack pull request #28194
Opened 2021-12-31 08:50 UTC by mdorier

Adds the py-asynctest package.

2022-01-02 22:27 UTC, adamjstewart requested changes

2022-01-02 22:27 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-asynctest/package.py
> +    depends_on('python@3.5:', type=('build', 'run'))
```python
depends_on('py-setuptools@30.3:', type='build')
```

2022-01-03 08:39 UTC, mdorier commented on var/spack/repos/builtin/packages/py-asynctest/package.py
> +    depends_on('python@3.5:', type=('build', 'run'))
Added, thanks!

2022-01-03 17:25 UTC, adamjstewart approved these changes

2022-01-03 17:25 UTC, merged