Address legion package build issue on macOS with apple-clang-12
LLNL/spack pull request #28241
Opened 2022-01-04 20:55 UTC by pmccormick

Work-around for apple-clang-12 build issue -- clang does not appear to default to the documented C++ standard as stated in the clang man page.  This fix introduces a variant for C++ standard support/selection (defaulting to `-std=c++11` to match Legion's current CI configurations).

Should resolve #21261.

2022-01-04 21:35 UTC, tldahlgren requested changes

2022-01-04 21:35 UTC, tldahlgren commented on var/spack/repos/builtin/packages/legion/package.py
> +    variant('c++std', default="11", values=cpp_stds, multi=False)
For consistency with other packages, I recommend:

```suggestion
    variant('cxxstd', default="11", values=cpp_stds, multi=False)
```

2022-01-04 21:35 UTC, tldahlgren commented on var/spack/repos/builtin/packages/legion/package.py
> +            from_variant("CMAKE_CXX_STANDARD", "c++std")
See reason above.

```suggestion
            from_variant("CMAKE_CXX_STANDARD", "cxxstd")
```

2022-01-04 21:40 UTC, pmccormick commented on var/spack/repos/builtin/packages/legion/package.py
> +            from_variant("CMAKE_CXX_STANDARD", "c++std")
Thanks @tldahlgren!  Done.

2022-01-05 18:20 UTC, tldahlgren approved these changes

2022-01-05 18:20 UTC, merged

2022-01-05 18:41 UTC, pbrady commented
It worked!  Thanks @pmccormick