Add epics packages
LLNL/spack pull request #28270
Opened 2022-01-05 21:49 UTC by glenn-horton-smith

This adds packages for epics-base (the core of the Experimental Physics and Industrial Control System) and for some extensions and drivers (epics-snmp for SNMP drivers, epics-ca-gateway for the Channel Access Gateway, and epics-pcas for the Portable Channel Access library that is required by epics-ca-gateway.)

I am not a developer of any of these, but I'm willing to maintain the packages.

2022-01-08 02:07 UTC, scheibelp requested changes
Thanks for the PR! I have a couple of (hopefully minor) requests. Let me know if you have any questions/criticisms.

2022-01-08 02:07 UTC, scheibelp commented on var/spack/repos/builtin/packages/epics-base/package.py
> +            shell=True).decode('utf8').strip()
Could you use the `Executable` object provided by Spack? That will automatically be available. You can also construct this object with `which` like:


```
perl = which('perl')
return perl("perl %s/perl/EpicsHostArch.pl" % self.prefix.lib, output=str, error=str)
```

Also, since you are using perl, this should add `depends_on(perl, type=(build, run))` - it looks like it is used at run time at least.

2022-01-08 02:07 UTC, scheibelp commented on var/spack/repos/builtin/packages/epics-pcas/package.py
> +        envmod.set('EPICS_BASE', env['EPICS_BASE'])
You should not have to set the `EPICS_BASE` variable here since it is set in the dependency - were you encountering an issue if you did not do this?

2022-01-12 08:36 UTC, glenn-horton-smith commented on var/spack/repos/builtin/packages/epics-base/package.py
> +            shell=True).decode('utf8').strip()
OK, I have done this.

2022-01-12 08:39 UTC, glenn-horton-smith commented on var/spack/repos/builtin/packages/epics-pcas/package.py
> +        envmod.set('EPICS_BASE', env['EPICS_BASE'])
I did encounter an issue if I did not do this. I added a setup_dependent_build_environment() method to the epics-base package setup to set the EPICS_BASE variable for dependents, and then I was able to remove the setting of EPICS_BASE from the epics-pcas package. This is done now.

2022-02-04 23:53 UTC, glenn-horton-smith commented on var/spack/repos/builtin/packages/epics-pcas/package.py
> +        envmod.set('EPICS_BASE', env['EPICS_BASE'])
So I think I have implemented your requested change. Do you disagree?

2022-02-04 23:53 UTC, glenn-horton-smith commented on var/spack/repos/builtin/packages/epics-base/package.py
> +            shell=True).decode('utf8').strip()
So I think this change is made. Do you agree?

2022-03-03 21:53 UTC, glenn-horton-smith commented
> Thanks for the PR! I have a couple of (hopefully minor) requests. Let me know if you have any questions/criticisms.

I think I've done all you asked. Sorry, I'm not quite sure I know the right way to communicate that.

2022-06-20 16:28 UTC, valmar commented
I am also interested in this. Please let me know if I can help with the PR

2022-06-20 18:33 UTC, glenn-horton-smith commented
I think I have made all the requested changes to the PR some time ago, but
nothing seems to be happening on it...

On Mon, Jun 20, 2022, 11:29 valmar ***@***.***> wrote:

> I am also interested in this. Please let me know if I can help with the PR
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/spack/spack/pull/28270#issuecomment-1160646475>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABJM6ZHDJJUX63EHW67FK2TVQCL5LANCNFSM5LK5LSAQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2022-06-29 20:35 UTC, scheibelp approved these changes

2022-06-29 20:36 UTC, merged

2022-06-29 20:40 UTC, scheibelp commented
Thanks! Apologies for losing track of this. If you ping me (@scheibelp) then that stands out amongst my other notifications (although that isn't strictly required: I should be monitoring PRs that I review).

2022-06-30 15:33 UTC, glenn-horton-smith commented
Thanks for the merge! Nice to know it's ok to ping. I was not sure about
the etiquette.
  Cheers,
  =Glenn

On Wed, Jun 29, 2022 at 3:40 PM Peter Scheibel ***@***.***>
wrote:

> Thanks! Apologies for losing track of this. If you ping me ***@***.***
> <https://github.com/scheibelp>) then that stands out amongst my other
> notifications (although that isn't strictly required: I should be
> monitoring PRs that I review).
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/spack/spack/pull/28270#issuecomment-1170472835>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABJM6ZHM5QCPMAFNEQIO7UTVRSYEHANCNFSM5LK5LSAQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>