Add HDF5 GPU VFD package.
LLNL/spack pull request #28272
Opened 2022-01-05 23:29 UTC by hyoklee

This is a new package that allows users to install [HDF5 Nvidia GPUDirect Storage VFD](https://github.com/hpc-io/vfd-gds).

2022-01-06 10:34 UTC, alalazo requested changes

2022-01-06 10:34 UTC, alalazo commented on var/spack/repos/builtin/packages/hdf5-vfd-gds/package.py
> +    version('1.0.1', sha256='00e125fd149561be991f41e883824de826d8add604aebccf103a4fb82d5faac2', default=True)
```suggestion
    version('1.0.1', sha256='00e125fd149561be991f41e883824de826d8add604aebccf103a4fb82d5faac2')
```

2022-01-06 10:34 UTC, alalazo commented on var/spack/repos/builtin/packages/hdf5-vfd-gds/package.py
> +    """This pacakge enables GPU Direct Storage Virtual File Driver in HDF5."""
```suggestion
    """This package enables GPU Direct Storage Virtual File Driver in HDF5."""
```

2022-01-06 10:34 UTC, alalazo commented on var/spack/repos/builtin/packages/hdf5-vfd-gds/package.py
> +    depends_on('cuda')
A `CudaPackage` has already a conditional dependency on `cuda` and a `cuda` boolean variant, hence adding an unconditional dependency on `cuda` seems wrong. I think what might work here is:
```
conflicts('~cuda')
```
if the aim is to have cuda always enabled.

2022-01-06 21:37 UTC, lrknox approved these changes

2022-01-06 21:41 UTC, lrknox commented
Note:  when built and tested on thetagpu, "make test" or --test=all failed because the default stage directory was on /tmp which was a tmpfs filesystem.  Setting TMPDIR to a lustre filesystem addressed the failure.

2022-01-12 12:59 UTC, alalazo approved these changes

2022-01-12 12:59 UTC, merged