new package: scorpio
LLNL/spack pull request #28327
Opened 2022-01-07 23:12 UTC by pbrady

2022-01-11 13:09 UTC, alalazo requested changes

2022-01-11 13:09 UTC, alalazo commented on var/spack/repos/builtin/packages/scorpio/package.py
> +    version('develop-2021-12-10',
```suggestion
    version('2021-12-10',
```

2022-01-12 12:07 UTC, alalazo commented
Can you rebase to run Gitlab pipelines on a new merge commit?

2022-01-12 12:07 UTC, alalazo submitted a review, later dismissed

2022-01-12 16:35 UTC, pbrady commented
hmmm... looks like my git-fu has failed me.

2022-01-12 16:39 UTC, closed without merging