libogg: patch stdint include
LLNL/spack pull request #28332
Opened 2022-01-09 17:11 UTC by nilsleiffischer

Installing `libtheora` failed on macOS 12.0.1 before this patch, at least with AppleClang 13 and with GCC 11.2.

If anyone knows details about when `<sys/types.h>` and `<stdint.h>` are available, please speak up :)

2022-01-11 15:35 UTC, alalazo requested changes

2022-01-11 15:35 UTC, alalazo commented on var/spack/repos/builtin/packages/libogg/package.py
> +    patch('darwin-stdint.patch', when='platform=darwin')
Can you add a link to related bug reports like: https://trac.macports.org/ticket/58924 in a comment above the patch?

2022-01-11 15:55 UTC, nilsleiffischer commented on var/spack/repos/builtin/packages/libogg/package.py
> +    patch('darwin-stdint.patch', when='platform=darwin')
Thanks for the pointer, I changed this PR entirely based on this

2022-01-11 16:01 UTC, alalazo submitted a review, later dismissed

2022-01-12 12:11 UTC, alalazo commented
Can you rebase to run Gitlab pipelines on a new merge commit?

2022-01-12 12:33 UTC, alalazo approved these changes

2022-01-12 16:17 UTC, merged