New package: chaparral - radiation view factor library
LLNL/spack pull request #28343
Opened 2022-01-10 17:00 UTC by pbrady

2022-01-11 13:07 UTC, alalazo requested changes
I have a question and a suggestion, but other than that LGTM.

2022-01-11 13:07 UTC, alalazo commented on var/spack/repos/builtin/packages/chaparral/package.py
> +    version('develop-2020-08-28',
```suggestion
    version('2020-08-28',
```

2022-01-11 13:07 UTC, alalazo commented on var/spack/repos/builtin/packages/chaparral/package.py
> +    """Radiation view factor library"""
The repo description mention this is a fork of an equally named project from Sandia, can you clarify that a bit? I am trying to understand if we need to reserve the "pristine" name for the original software. Thanks!

2022-01-11 16:24 UTC, pbrady commented on var/spack/repos/builtin/packages/chaparral/package.py
> +    version('develop-2020-08-28',
Thanks for the review.  I've remove the 'develop' prefix as suggested.

2022-01-11 16:33 UTC, pbrady commented on var/spack/repos/builtin/packages/chaparral/package.py
> +    """Radiation view factor library"""
The project originated with SNL in 1995 and they sent us a lgpl'd version about 20 years ago.  From what I've heard, they had plans to release it but never did.  

My goal here is to prepare a spack recipe for an open source casting code https://gitlab.com/truchas/truchas

With that in mind, if in the future SNL does release the "true" version of chaparral, I would be fine with adjusting this package.py to default to their repo and use our forked repo as a "truchas" version.

Does that work?

2022-01-12 12:04 UTC, alalazo commented on var/spack/repos/builtin/packages/chaparral/package.py
> +    """Radiation view factor library"""
That works perfectly. Thanks!

2022-01-12 12:05 UTC, alalazo approved these changes, later dismissed

2022-01-12 12:05 UTC, alalazo commented
Can you rebase to run Gitlab pipelines on a new merge commit?

2022-01-12 16:52 UTC, pbrady commented
rebased

2022-01-12 16:55 UTC, alalazo approved these changes

2022-01-15 21:05 UTC, merged