New package: chaco - a graph partitioning library
LLNL/spack pull request #28342
Opened 2022-01-10 16:42 UTC by pbrady

2022-01-11 13:09 UTC, alalazo requested changes
Same as question as for charrapal on whether this fork is the only one currently used, but basically LGTM.

2022-01-11 13:09 UTC, alalazo commented on var/spack/repos/builtin/packages/chaco/package.py
> +    version('develop-2020-07-16', commit='92a877b381933d12b02507413897f696d81b4682', preferred=True)
```suggestion
    version('2020-07-16', commit='92a877b381933d12b02507413897f696d81b4682', preferred=True)
```

2022-01-11 16:51 UTC, pbrady commented
Unlike chaparral they are tarballs of chaco floating around but there is no "official" repo.  The closest we've found is the chaco subpackage of trilinos: https://github.com/trilinos/Trilinos/tree/64d50199f342860b00d16cb78cb5730de66438b9/packages/seacas/libraries/chaco
but that would take some work to extract and build as a separate package.

2022-01-12 12:06 UTC, alalazo commented
I'd say let's stick with the same strategy as charrapal and keep this name for the time being. Also, can you rebase to run Gitlab pipelines on a new merge commit?

2022-01-12 16:50 UTC, pbrady commented
rebased

2022-01-12 16:56 UTC, alalazo approved these changes

2022-01-15 21:08 UTC, merged