flux-core: add v0.32.0 and v0.33.0
LLNL/spack pull request #28347
Opened 2022-01-10 23:08 UTC by grondo

2022-01-11 17:58 UTC, becker33 requested changes
Two very minor requests

2022-01-11 17:58 UTC, becker33 commented on var/spack/repos/builtin/packages/flux-core/package.py
> +    depends_on("ncurses@6.2", when="@0.32.0:,master")
```suggestion
    depends_on("ncurses@6.2", when="@0.32.0:")
```

`Version('master').satisfies('@0.32.0:')`, there's no need to list it separately.

The "special" versions are `develop > main > master > head > trunk > 9999999999`.

2022-01-11 17:58 UTC, becker33 commented on var/spack/repos/builtin/packages/flux-core/package.py
> +    depends_on("py-docutils", type='build', when="@0.32.0:,master")
Same here

```suggestion
    depends_on("py-docutils", type='build', when="@0.32.0:")
```

2022-01-11 19:28 UTC, grondo commented
Thanks, @becker33! I believe I have made the requested changes.

2022-01-20 20:44 UTC, grondo commented
rebased and force-pushed to re-run CI, the gitlab `build_system-pr-generate` step failed with

```
==> Error: Pipeline generation failed due to the presence of the following specs that are known to be broken in develop:
```

2022-01-23 16:35 UTC, grondo commented
Updated with some other minor changes:

 - Remove setting of `FLUX_PMI_LIBRARY_PATH` - which was unnecessary and caused issues on some platforms
 - Fix another spot where `master` was specified unnecessarily
 - update outdated doc link

2022-01-24 17:20 UTC, becker33 approved these changes

2022-01-24 17:20 UTC, merged

2022-01-24 17:22 UTC, grondo commented
Thank you!