pindel: fixing compilation issues for gcc5+
LLNL/spack pull request #28387
Opened 2022-01-12 22:16 UTC by snehring

Cleaned this up a bit since the current implementation was breaking something in the compiler wrappers.

gcc 4.8.5 doesn't complain about this as is, but as far back as I have installed (7) complains about calling abs() on the unsigned ints, which, obviously is ambiguous.

What the code was doing in most of those was subtracting two unsigned ints and then handing that to abs(). Which to me seems like a bad idea. So what this does is replace all the calls that were making the compiler complain with a one line function that does what they had probably intended. There are other areas where they cast some unsigned ints to ints to do the subtraction, but that seemed less correct than this workaround. I've not fixed those since that goes a little farther than 'make it compile'.

The repo this pulls from is archived, so I don't think we're going to get any changes in the future.

2022-05-12 03:22 UTC, snehring commented
Switched to a patch, since that's a bit more readable.

2022-05-12 19:47 UTC, snehring commented
can I convince you to try again @spackbot run pipeline

2022-05-12 19:47 UTC, snehring commented
can I convince you to try again @spackbot run pipeline

2022-05-12 19:48 UTC, snehring commented
Cursed

2022-05-16 14:12 UTC, alalazo requested changes

2022-05-16 14:12 UTC, alalazo commented on var/spack/repos/builtin/packages/pindel/package.py
> +# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
This needs to be reverted
```suggestion
# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```

2022-05-16 14:12 UTC, alalazo commented on var/spack/repos/builtin/packages/pindel/package.py
> +    patch('gcc-5-compat.patch', when='@0.2.5b8%gcc@5:')
Can you write a comment above the directive explaining what the patch does, where it is taken from etc.?

2022-05-16 14:58 UTC, alalazo approved these changes

2022-05-17 07:45 UTC, merged