Updated recipes for 4.5.2 and corrected run style errors
LLNL/spack pull request #28413
Opened 2022-01-14 02:47 UTC by renjithravindrankannath

Updated following recipe for 4.5.2 release and corrected style errors
atmi
rocm_debug_agent
rocm_bandwidth_test
rocprofiler
roctracer-dev-api
roctracer
dbgapi
rocm-gdb

2022-01-15 03:51 UTC, srekolam approved these changes

2022-01-17 08:51 UTC, alalazo approved these changes

2022-01-17 08:53 UTC, alalazo requested changes
There are inconsistencies introduced by this PR. Please check the messages in the package audits.

2022-01-17 17:02 UTC, renjithravindrankannath commented
Hi @alalazo , I did sync up with the upstream code and audit error is not happening with the latest code.
Can you please take a look at this PR?

2022-01-18 12:24 UTC, srekolam approved these changes

2022-01-18 12:25 UTC, srekolam commented
> There are inconsistencies introduced by this PR. Please check the messages in the package audits.

this is resolved

2022-01-18 13:08 UTC, haampie approved these changes

2022-01-18 13:12 UTC, alalazo approved these changes

2022-01-18 13:12 UTC, merged