Fix command line scopes with other flags
LLNL/spack pull request #28418
Opened 2022-01-14 16:11 UTC by Jordan474

Fixes #28417

The issue I found is: since 2bd513d6591161d271221bb76bc1420bd3c2b3e3 (spack 0.17), if a config-changing flag is set, then the`spack.config.config` singleton was initialized in `setup_main_options` *before* `spack.config.command_line_scopes` had been set. So the command line scopes were not taken into account during the config initialization.

2022-01-17 11:59 UTC, alalazo requested changes
Can you add a regression test to this fix?

2022-01-17 13:23 UTC, haampie commented
@alalazo you can't easily test this as main runs as part of the tests

2022-01-17 13:24 UTC, haampie approved these changes

2022-01-17 13:36 UTC, alalazo commented
@haampie  In CI we don't run `spack unit-test` directly, but we use a wrapper script where we already invoke a few commands:

https://github.com/spack/spack/blob/7e3677db6f6b780049e65133793df65a49718395/share/spack/qa/run-unit-tests#L32-L41

If this can't be tested easily within unit tests we can at least add some simple regression test at that level.

2022-01-21 11:06 UTC, Jordan474 commented
> add some simple regression test at that level.

@alalazo Not sure those would be so simple, I tried to write only couple test, already I find them bloated, and I still thinks they are missing some messages in case of failure etc... 

```sh
tmpdir="${TMPDIR:-/tmp}/spack-run-unit-tests-${USER:-}"

ccachetrue="$tmpdir/ccachetrue"
mkdir -p "$ccachetrue"
cat <<EOF > "$ccachetrue/config.yaml"
config:
  ccache: true
EOF

bin/spack config get config | grep -q 'cache: false'
bin/spack -C "$ccachetrue" config get config | grep -q 'cache: true'
bin/spack -C "$ccachetrue" -d config get config | grep -q 'cache: true'
```

2022-01-23 10:02 UTC, alalazo approved these changes

2022-01-23 10:02 UTC, merged