New package: py-deepsig
LLNL/spack pull request #28480
Opened 2022-01-18 16:11 UTC by qwertos

2022-01-18 16:51 UTC, adamjstewart approved these changes, later dismissed
Did you report the PyPI tarball issue to the developers? Might want to make the global URL download from GitHub, otherwise every version will have to have a version-specific URL unless the devs fix this in the future.

2022-01-19 11:02 UTC, alalazo commented
@spackbot run pipeline

2022-01-27 21:23 UTC, adamjstewart commented
> Did you report the PyPI tarball issue to the developers? Might want to make the global URL download from GitHub, otherwise every version will have to have a version-specific URL unless the devs fix this in the future.

Still have this question

2022-02-16 16:12 UTC, qwertos commented
Discussing with them now.

2022-02-22 19:44 UTC, adamjstewart requested changes

2022-02-22 19:44 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-deepsig/package.py
> +    pypi     = "deepsig/deepsig-1.2.0.tar.gz"
```suggestion
    pypi     = "deepsig/deepsig-1.2.1.tar.gz"
```

2022-02-22 19:44 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-deepsig/package.py
> +                    'setup.py')
Probably simpler to do:
```suggestion
        filter_file('README_RAW.md', 'README.md', 'setup.py', string=True)
```
Alternatively:
```suggestion
        copy('README.md', 'README_RAW.md')
```

2022-02-24 22:05 UTC, adamjstewart approved these changes, later dismissed

2022-02-28 16:44 UTC, qwertos commented
@spackbot run pipeline

2022-03-01 19:46 UTC, adamjstewart approved these changes

2022-03-01 20:21 UTC, merged