Patch for version 2.40.1 and beyond
LLNL/spack pull request #28497
Opened 2022-01-18 23:54 UTC by dorton21

at-spi2-core is automatically selecting dbus-broker and enabling systemd if it finds dbus-broker-launch which some systems might have even without systemd being part of the actual spack environment. This is not ideal for a spack package.

2022-01-19 10:19 UTC, alalazo requested changes

2022-01-19 10:19 UTC, alalazo commented on var/spack/repos/builtin/packages/at-spi2-core/package.py
> +        filter_file('dbus_broker.found\(\)', 'false','bus/meson.build')
Can you fix the style issues at this line?

2022-01-19 16:53 UTC, dorton21 commented
@alalazo can you do me a favor and checkout this [PR](https://github.com/spack/spack/pull/28384)? The guy I packaged it for needs it soon. Thanks for your help.

2022-01-28 09:39 UTC, alalazo approved these changes

2022-01-28 09:40 UTC, merged