Added mosquitto e cjson packages
LLNL/spack pull request #28550
Opened 2022-01-22 14:46 UTC by danielecesarini

This PR adds [mosquitto](https://mosquitto.org/) e [cjson](https://github.com/DaveGamble/cJSON) packages to SPACK

2022-01-23 09:31 UTC, alalazo requested changes
Do we need all the versions listed here, or being new packages we could be fine only with the latest release?

2022-01-23 09:31 UTC, alalazo commented on var/spack/repos/builtin/packages/mosquitto/package.py
> +
```suggestion
        args = [
            self.define('DOCUMENTATION', 'no'),
            self.define_from_variant('WITH_CJSON', 'cjson'),
            self.define_from_variant('WITH_TLS', 'tls'),
            self.define_from_variant('WITH_STATIC_LIBRARIES', 'static'),
            self.define_from_variant('WITH_WEBSOCKETS', 'websocket')
        ]
```

2022-01-23 12:03 UTC, danielecesarini commented
> Do we need all the versions listed here, or being new packages we could be fine only with the latest release?

I have some codes that needs the support of old versions.

2022-01-23 12:26 UTC, alalazo commented
Can we get by with the latest versions of the minor releases you need?

2022-01-23 14:40 UTC, danielecesarini commented
> Can we get by with the latest versions of the minor releases you need?

[Fix]https://github.com/spack/spack/pull/28550/commits/5e47a56d8cfd2ab82e0954ac3bfe3d48a383ea84l)

2022-01-25 09:18 UTC, danielecesarini commented
@alalazo what do you think?

2022-01-25 09:53 UTC, alalazo commented
@danielecesarini There's a suggestion for more idiomatic syntax that has not been addressed at https://github.com/spack/spack/pull/28550#discussion_r790250090 Also, I think we can remove a lot of old `patch` releases. Do we need all the 15 releases in the 1.7 series or can we just use the latest (since it is a new package)?

2022-01-25 11:27 UTC, danielecesarini commented
> @danielecesarini There's a suggestion for more idiomatic syntax that has not been addressed at [#28550 (comment)](https://github.com/spack/spack/pull/28550#discussion_r790250090) Also, I think we can remove a lot of old patch releases. Do we need all the 15 releases in the 1.7 series or can we just use the latest (since it is a new package)?

My apologies, I had not realized.

I removed older versions, but unfortunately I need at least version 1.3.5 for a legacy code. My rationale is to keep old major versions down to 1.3.5, which is my dependency.

I also updated the source code repository targeting the official archive repository of mosquitto.

2022-01-25 11:30 UTC, alalazo submitted a review, later dismissed

2022-01-25 11:47 UTC, danielecesarini commented
@alalazo I am sorry, I forgot an important acceleration library for mosquitto. I've just added to this PR.

2022-01-25 11:59 UTC, alalazo approved these changes

2022-01-25 12:08 UTC, merged