adding in new version of KaHiP 3.12-3.14
LLNL/spack pull request #28594
Opened 2022-01-25 20:01 UTC by cleathart

Added in 3 new versions of KaHiP. Also added in deterministic variant that will compile the library to be deterministic instead of using a random seed for decomposition.

2022-03-18 13:33 UTC, ma595 approved these changes

2022-03-21 14:53 UTC, alalazo requested changes

2022-03-21 14:53 UTC, alalazo commented on var/spack/repos/builtin/packages/kahip/package.py
> +    variant('deterministic', default=False, description='Compile with the deterministic seed')
You can use a conditional variant and remove the conflict
```suggestion
    variant('deterministic', default=False, when='@3.12:', description='Compile with the deterministic seed')
```

2022-03-21 14:53 UTC, alalazo commented on var/spack/repos/builtin/packages/kahip/package.py
> +    conflicts('+deterministic @:3.12')
```suggestion
```

2022-08-22 11:24 UTC, alalazo commented
Superseded by #29648

2022-08-22 11:24 UTC, closed without merging