VTK-m: Add CMake definition to suppress CMP0104
LLNL/spack pull request #28668
Opened 2022-01-28 22:08 UTC by kwryankrattiger

Added CMAKE_CUDA_ARCHITECTURES=<cuda_arch[0]> to ParaView and VTK-m projects.

Warnings present on perlmutter when building `paraview +cuda`

@chuckatkins

2022-01-28 23:48 UTC, vicentebolea requested changes
Good idea @kwryankrattiger, however, it seems that VTK-m does `set(CMAKE_CUDA_ARCHITECTURES OFF)` when using CUDA. The code has to be refactored to abandon the legacy way of setting the archs using CMAKE_CUDA_FLAGS to use CUDA_ARCHITECTURES properties. Hence, until VTK-m is updated this change will not work.

2022-01-29 03:07 UTC, kwryankrattiger commented
@vicentebolea 
> Hence, until VTK-m is updated this change will not work.

I am setting it to silence the warnings that are generated by cmake. It looks like the flags are explicitly set, so I agree this doesn't actually do anything to change the build otherwise.

2022-01-31 16:08 UTC, vicentebolea commented on var/spack/repos/builtin/packages/paraview/package.py
> +            if '@3.18:' in spec['cmake']:
```suggestion
            # CMAKE_CUDA_ARCHITECTURES is ignored by VTK-m but we need to this to
            # suppress warnings which CMake (>3.18) generate in its absence. 
            if '@3.18:' in spec['cmake']:
```

2022-01-31 16:08 UTC, vicentebolea commented
@kwryankrattiger I was to fast to judge this, I just jumped to the code changes directly.

2022-01-31 16:11 UTC, vicentebolea commented
Do you think that if we set `CMP0104` behavior to "OLD", will we possibly break code which uses
VTK-m in the addition of CUDA? in other word are CMake policies transitive between projects. IF that is not the case we can resolve this at the vtk-m by setting this policy behavior to "OLD".

2022-02-02 17:55 UTC, chuckatkins approved these changes

2022-03-02 18:45 UTC, chuckatkins commented
@vicentebolea after some discussion, this should be addressed by vtk-m upstream and since it's only a noisy warning and not actually a build issue then we're closing this.  The warning will just go away once addressed by upstream vtkm and propagated to spack.

2022-03-02 18:45 UTC, closed without merging

2022-03-05 00:52 UTC, vicentebolea commented
Work in progress upstream here: https://gitlab.kitware.com/vtk/vtk-m/-/merge_requests/2724