WarpX: 22.02
LLNL/spack pull request #28742
Opened 2022-02-03 01:49 UTC by ax3l

Update `warpx` & `py-warpx` to the latest release, `22.02`.

2022-02-03 09:33 UTC, alalazo requested changes
Package audit failure:
```
py-warpx: dependency on py-picmistandard@0.0.19 cannot be satisfied by known versions of py-picmistandard
    happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/py-warpx/package.py
    known versions of py-picmistandard are develop, 0.0.18, 0.0.16, 0.0.14
```

2022-02-04 19:04 UTC, ax3l commented
Excellent catch by CI, I just did a build test but no run test :sweat_smile:

2022-02-04 19:07 UTC, alalazo commented
> Excellent catch by CI, I just did a build test but no run test

@adamjstewart idea and my execution :laughing:

2022-02-04 19:12 UTC, alalazo approved these changes

2022-02-05 06:53 UTC, merged