Fix reindex with uninstalled deps
LLNL/spack pull request #28764
Opened 2022-02-03 18:53 UTC by haampie

When a prefix of a dep is removed, and the db is reindexed, it is added
through the dependent, but until now it incorrectly listed the spec as
'installed'.

It also fixes an issue when the same spec was added multiple times, it would
always be marked installed, even though it was not.

2022-02-03 18:54 UTC, haampie commented on lib/spack/spack/database.py
> +                    layout = None if entry.spec.external else spack.store.layout
this is somewhat duplicate logic, _add takes care of it anways (and probs better).

2022-02-03 18:55 UTC, haampie commented on lib/spack/spack/database.py
> +        installed = bool(spec.external)
so, here we retrieve installed-ness from the directory layout, also when the spec had been in the db before.

2022-02-03 18:56 UTC, haampie commented on lib/spack/spack/database.py
> +            self._data[key].installed = installed
no clue why this was True previously, doesn't really make sense to me.

2022-02-04 14:26 UTC, haampie commented on lib/spack/spack/database.py
>                  self._installed_prefixes.add(path)
For those reviewing and out of the loop: the invariant of `_installed_prefixes` is: for every path in the set, there exists 1 installed and non-external spec in the database.

2022-02-04 14:39 UTC, haampie commented on lib/spack/spack/database.py
> +        if not rec.spec.external and rec.installed:
This was also a bug: only part of the invariant was checked.

It was only hit thanks to the faulty test described in https://github.com/spack/spack/issues/28779: this test added an entry to the database, but it was not considered installed on the filesystem (spec passed to database did not correspond to spec on filesystem). So it ends up as registering an entry in the database with `rec.installed==False`, `rec.spec.external==False` and `rec.ref_count = 0`...

An actual test could be: a package that somehow destructs its own install prefix after installation and before being registered in the database. Although it's quite edge-case'y and unclear what expected behavior should be.

2022-02-04 15:57 UTC, haampie commented on lib/spack/spack/database.py
> +        if not rec.spec.external and rec.installed:
This is now covered by a test.

2022-02-04 17:30 UTC, becker33 requested changes
Mostly LGTM, one bug that needs fixing with the installation time.

2022-02-04 17:30 UTC, becker33 commented on lib/spack/spack/database.py
> +            self._data[key].installation_time = installation_time
This needs to only update the installation time if the `installed` value changed.

```suggestion
            new_install = self._data[key].installed != installed
            self._data[key].installed = installed
            if new_install:
                self._data[key].installation_time = installation_time
```

2022-02-04 17:30 UTC, becker33 commented on lib/spack/spack/database.py
> +            path = None
I think this is just for compatibility with spack v0.8 at this point, I wonder if we can remove it soon.

2022-02-04 17:44 UTC, haampie commented on lib/spack/spack/database.py
> +            self._data[key].installation_time = installation_time
I think this codepath is hit for overwrite installs (like develop specs), in which case you'd want to "touch" the record to reflect the overwrite time, right?

If it goes from installed -> not installed, then probably you don't want the installation_time to be modified.

2022-02-04 17:50 UTC, becker33 commented on lib/spack/spack/database.py
> +            self._data[key].installation_time = installation_time
I'm pretty sure this code path is also hit for

```
spack install bar
spack install foo^bar  # hits this code path for bar
```

But you're right, we need something cleverer than my suggestion for the overwrite case.

2022-02-04 18:01 UTC, haampie commented on lib/spack/spack/database.py
> +            self._data[key].installation_time = installation_time
Hm okay, right now the behavior is effectively unchanged if the install time is not passed as an argument. Maybe getting install times right could work as a follow up? Seems like a few code paths have to be considered... (install-as-dependency, overwrite, re-registering through reindex...)

2022-02-04 18:03 UTC, becker33 commented on lib/spack/spack/database.py
> +            self._data[key].installation_time = installation_time
We could just stat the `spec.prefix` directory for its creation time, and only update the installation time for previously installed packages if that time is greater than the existing installation time.

```suggestion
            set_installation_time = installed and not self._data[key].installed
            if self._data[key].installed and installed:
                # On UNIX, creation times are really metadata modification times.
                # shouldn't make a difference in this case
                prefix_creation_time = os.stat(spec.prefix).st_ctime
                if prefix_creation_time > self._data[key].installation_time:
                    set_installation_time = True
                   
            self._data[key].installed = installed
            if set_installation_time:
                self._data[key].installation_time = installation_time
```

2022-02-04 18:07 UTC, becker33 commented on lib/spack/spack/database.py
> +            self._data[key].installation_time = installation_time
But I agree that this PR doesn't make this particular issue worse, so if you decide it needs to be pushed to a next PR I'm fine with that.

2022-02-04 18:12 UTC, haampie commented on lib/spack/spack/database.py
> +            self._data[key].installation_time = installation_time
I'm a bit reluctant to add this, considering `installation_time` is relied on in `installer.py`:

```
            if installed_in_db and (
                    dep.dag_hash() not in request.overwrite or
                    rec.installation_time > request.overwrite_time):
```

and I can already foresee hard to debug issues with distributed builds etc. What I'd like is to have clear bug fixes and backport it.

2022-02-04 18:25 UTC, becker33 approved these changes

2022-02-04 18:40 UTC, becker33 commented
> and ensure ensure only ensures

:)

2022-02-04 19:31 UTC, merged