Use Spec.constrain to construct spec lists for stacks
LLNL/spack pull request #28783
Opened 2022-02-04 15:32 UTC by alalazo

fixes #28749 

Before this PR the construction of a spec list for software stacks was based on string concatenation rather than constraint merging. This may cause issues like #28749 if a line in the matrix contains constrains on both the root spec and a dependency. This PR fixes the issue by using `Spec.constrain` instead of string concatenation to construct the spec list.

Nested matrices and temporarily converted back to string to allow for a sigil to be applied in front of them when they are expanded as `$^` or as `$%`.

Modifications:

- [x] Add a regression test based on #28749
- [x] Fix a bug in `Spec.constrain` that wasn't adding a name or a namespace to an anonymous spec if constrained with a named spec
- [x] Use `Spec.constrain` to merge the constraints for spec matrices

2022-02-04 16:19 UTC, alalazo commented
@g-mathias This should fix your issue.

2022-02-04 16:47 UTC, alalazo commented
Hmm, not sure how codecov computes coverage for the notification. On their website I see [100% coverage](https://app.codecov.io/gh/spack/spack/compare/28783/diff) as I would expect.

2022-02-04 16:51 UTC, haampie commented on lib/spack/spack/spec.py
> +            self.namespace = other.namespace
changed = True

2022-02-04 17:03 UTC, alalazo commented on lib/spack/spack/spec.py
> +            self.namespace = other.namespace
Fixed in 162c20d

2022-02-04 17:19 UTC, haampie commented
So, what's the definition of a matrix now?

With `Sᵢ = [root...]` the "matrix" (it's a bit of poor choice of words :p) is the product 

```
S₁ × S₂ × ... × Sₙ := {s₁ ∩ s₂ ∩ ... ∩ sₙ ∀ s₁∈S₁, s₂∈S₂, ..., sₙ∈Sₙ}
```

Where `∩` is the `Spec.constrain` function? And is `∩` now properly associative and commutative?

With associativity we get this behavior, which makes most sense to me

```
['x'] × ['^y'] × ['%gcc'] == 'x%gcc ^y' == ['x'] × ['%gcc'] × ['^y']
```

String concatenation is not commutative, so then you could get

```
['x'] × ['^y'] × ['%gcc'] == 'x ^y%gcc' ≠ 'x%gcc ^y' = ['x'] × ['%gcc'] × ['^y']
```

which is not really desirable imho.

2022-02-04 17:26 UTC, alalazo commented on lib/spack/spack/spec_list.py
> -        return 1
This removed function was trying to account for associativity when using string concatenation

2022-02-04 17:28 UTC, alalazo commented on lib/spack/spack/spec_list.py
> -        return 1
So I guess the idea was already to have the `Spec.constrain` semantics, but the implementation was failing for anonymous specs which had a constraint both on the root and on a dependency

2022-02-04 17:39 UTC, becker33 requested changes
That's so much better!

2022-02-04 17:39 UTC, becker33 commented on lib/spack/spack/spec_list.py
> +    print(results)
Vestigial print statement

2022-02-04 17:47 UTC, alalazo commented on lib/spack/spack/spec_list.py
> +    print(results)
Removed in 4d057dc

2022-02-04 17:48 UTC, becker33 approved these changes

2022-02-04 19:17 UTC, merged

2022-03-19 12:21 UTC, haampie commented
@alalazo added this to 0.17.2 too, not sure why it was not added?