New package: neko
LLNL/spack pull request #28791
Opened 2022-02-04 22:19 UTC by njansson

A modern, portable, and scalable framework for high-fidelity computational fluid dynamics

2022-03-29 16:01 UTC, alalazo requested changes
Left a few minor requests. By using `with_or_without` we'll be usre to deactivate options when the variant is false.

2022-03-29 16:01 UTC, alalazo commented on var/spack/repos/builtin/packages/neko/package.py
> +    version('0.3.0', tag='v0.3.0')
Can we pin a commit sha instead of a tag?

2022-03-29 16:01 UTC, alalazo commented on var/spack/repos/builtin/packages/neko/package.py
> +            args.append('--with-parmetis')
```suggestion
        args += self.with_or_without('parmetis')
```

2022-03-29 16:01 UTC, alalazo commented on var/spack/repos/builtin/packages/neko/package.py
> +            args.append('--with-libxsmm')
```suggestion
        args += self.with_or_without('libxsmm', variant='xsmm')
```

2022-03-29 16:01 UTC, alalazo commented on var/spack/repos/builtin/packages/neko/package.py
> +            args.append('--with-cuda={0}'.format(self.spec['cuda'].prefix))
```suggestion
        args += self.with_or_without('cuda', activation_value='prefix')
```

2022-03-29 16:01 UTC, alalazo commented on var/spack/repos/builtin/packages/neko/package.py
> +            args.append('--with-hip={0}'.format(self.spec['hip'].prefix))
This one is not much clearer that what is already there, so I'll leave it up to you if you want to update it:
```suggestion
        rocm_fn = lambda x: spec['hip'].prefix
        args += self.with_or_without('hip', variant='rocm', activation_value=rocm_fn)
```

2022-03-29 17:22 UTC, njansson commented on var/spack/repos/builtin/packages/neko/package.py
> +    version('0.3.0', tag='v0.3.0')
Yes, certainly.

2022-03-30 07:33 UTC, alalazo approved these changes

2022-03-30 07:34 UTC, merged