py-llvmlite: add 0.38.0
LLNL/spack pull request #28822
Opened 2022-02-08 10:27 UTC by manuelakuhn

see https://github.com/numba/llvmlite/tree/v0.38.0

2022-02-08 17:13 UTC, adamjstewart requested changes

2022-02-08 17:13 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-llvmlite/package.py
>      depends_on('python@3.7:3.9', type=('build', 'run'), when='@0.37.0:')
```suggestion
    depends_on('python@3.7:3.9', type=('build', 'run'), when='@0.37')
```
Otherwise this condition will also be applied to 0.38+

2022-02-08 17:15 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-llvmlite/package.py
>      depends_on('python@3.7:3.9', type=('build', 'run'), when='@0.37.0:')
Thanks

2022-02-08 17:23 UTC, adamjstewart submitted a review, later dismissed

2022-02-09 10:39 UTC, manuelakuhn commented
@spackbot run pipeline

2022-02-10 20:46 UTC, manuelakuhn commented
Rebased to try to get checks to run.

2022-02-10 20:50 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-llvmlite/package.py
>      depends_on('python@3.7:3.9', type=('build', 'run'), when='@0.37.0:')
Still waiting for this change

2022-02-10 21:02 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-llvmlite/package.py
>      depends_on('python@3.7:3.9', type=('build', 'run'), when='@0.37.0:')
The rebase must have undone that again. Sorry for that.

2022-02-10 21:26 UTC, adamjstewart approved these changes

2022-02-10 21:26 UTC, merged