extensions: allow multiple "extends" directives
LLNL/spack pull request #28853
Opened 2022-02-09 20:12 UTC by trws

This will allow multiple extends directives in a package as long as only one of
them is selected as a dependency in the concrete spec.

Noticed this when working on lua refactor, need it to be able to select which lua to extend based on the one used in the spec.

2022-02-09 22:42 UTC, adamjstewart commented
Related to #987

2022-02-10 00:04 UTC, trws commented
So, this is related to #987, but it doesn't completely solve it.  I had hoped to actually do that, but since the method currently returns *exactly one extendee* it's likely to turn into a somewhat major refactor to propagate the change once a package is allowed to have two or more active extendees.  The actual change in package would be pretty trivial though.

2022-02-16 08:19 UTC, alalazo requested changes
LGTM. Can we update [this section](https://spack.readthedocs.io/en/latest/packaging_guide.html#extensions) of the docs too before merging?

2022-02-16 18:53 UTC, alalazo approved these changes

2022-02-16 20:17 UTC, adamjstewart commented
Does the concretizer somehow enforce the fact that only a single extensions can be active at once? How much work would be required to support multiple simultaneously active extensions?

2022-02-16 20:26 UTC, trws commented
The concretizer does not, it's a limitation I currently enforce with an assert in the code.  In `package.py` the change would be trivial, but it would change the API of the `extendee_spec` property, so anywhere/everywhere that's used would break.  Currently that's roughly 30 uses, some of them are probably trivial to fix, but others pretty strongly assume there is only one.

2022-02-16 21:23 UTC, merged