add new versions of gh
LLNL/spack pull request #28958
Opened 2022-02-15 18:12 UTC by trws

What it says on the tin, add new versions for the github CLI.

2022-02-15 18:51 UTC, lcnzg requested changes
These version hashes are from the macOS_amd64 binaries, and not from the tar.gz source. Can you use the https://github.com/cli/cli/archive/refs/tags/v*.tar.gz files?

2022-02-15 19:07 UTC, trws commented
Wow, you're right.  That's a bug in spack checksum I should look into, thanks for the catch!

2022-02-15 19:33 UTC, lcnzg approved these changes
Thanks!

2022-02-16 09:37 UTC, alalazo approved these changes

2022-02-16 09:38 UTC, merged