nwchem: support Fujitsu A64FX compilers
LLNL/spack pull request #28990
Opened 2022-02-16 00:55 UTC by h-murai

Some patches are added to compile NWChem with Fujitsu compilers. These are discussed in https://github.com/nwchemgit/nwchem/issues/347 and to be merged to NWChem.

2022-02-16 08:48 UTC, alalazo requested changes
LGTM. Only a minor request.

2022-02-16 08:48 UTC, alalazo commented on var/spack/repos/builtin/packages/nwchem/package.py
> +    patch('fj.patch', when='@7.0.2 %fj')
Can you explain in a brief comment above the directive why the patch is needed and leave a reference to the issue in the description?

2022-02-17 00:36 UTC, h-murai commented on var/spack/repos/builtin/packages/nwchem/package.py
> +    patch('fj.patch', when='@7.0.2 %fj')
This patch handles the modification to the build system (e.g. compiler flags) and Fortran language syntax, and enables Fujitsu compilers to compile NWChem. You  can find the detailed discussion about it  in https://github.com/nwchemgit/nwchem/issues/347 .

2022-02-17 07:47 UTC, alalazo commented on var/spack/repos/builtin/packages/nwchem/package.py
> +    patch('fj.patch', when='@7.0.2 %fj')
Thanks @h-murai The request was to add this info in a code comment above the patch (so the next developer knows what to expect in there). Then the PR LGTM.

2022-02-20 12:04 UTC, h-murai commented
@alalazo I added the description of the patch.

2022-02-21 09:26 UTC, alalazo approved these changes

2022-02-21 09:26 UTC, merged