default gcc~bootstrap
LLNL/spack pull request #29089
Opened 2022-02-19 08:37 UTC by cosmicexplorer

### Problem

`gcc` takes much longer to build when `+bootstrap` is enabled. Since `gcc languages=jit` must be built to provide e.g. `libgccjit`, any user of `libgccjit` has to wait for gcc to build itself three times instead of two.

Is there any security concern to doing this?

### Solution

- Default the `bootstrap` variant of `gcc` to `False`.

### Result
`spack install gcc` is faster!

2022-02-19 10:52 UTC, michaelkuhn requested changes
I don't think we should change the default. Without bootstrapping, we might into problems when building GCC using other compilers or very old versions of GCC itself. Before disabling it, we should at the very least check whether GCC still compiles/works with a number of different compilers and compiler versions.

2022-02-19 11:53 UTC, sethrj commented
For a long time we defaulted to gcc to non-bootstrap, at least on mac. I was unable to build gcc11 on macos 12 last week and had to turn it off (and spent 5 hours figuring that out of course, plus another 4 due to the system shutting down in the middle of the bootstrap build). I think the main problem might be reproducibility, not security -- if a bug in another compiler changes the behavior of the built GCC, bootstrapping is the easiest way to find out.

I think the ideal solution is for spack to provide GCC binary bootstrap ;) because also https://github.com/spack/spack/issues/26317

2022-02-20 04:08 UTC, cosmicexplorer commented
Ok, thank you for giving more context @michaelkuhn! I'll close this for now and later look to instead provide a GCC binary bootstrap as @sethrj advised.

2022-02-20 04:20 UTC, cosmicexplorer commented
Well, I'll keep this open so I don't forget about it.

2022-03-02 06:28 UTC, cosmicexplorer commented
It's also possible to take an entirely separate tack, along the lines of #25863, where we might consider whether it's possible to plumb in a user config option or something to influence the type of `gcc`s we want to see; for example, a config option `config:additional_spec`, when set to the string `"gcc~bootstrap"`, might ensure that any spec used by `spack install` satisfies the value of `config:additional_spec`. I as a user could set that locally if I find myself building gcc often to test, for example. This approach would require a disjoint set of work compared to the proposal to bootstrap `gcc` binaries as proposed above by @sethrj.

2024-08-06 09:40 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2024-08-06 09:40 UTC, closed without merging