Add miktex package
LLNL/spack pull request #29096
Opened 2022-02-20 04:49 UTC by vmiheer

2022-02-26 23:58 UTC, vmiheer commented
@alalazo, @tgamblin I was wondering if you could review this pull request or please add appropriate reviewer? Thank you :)

2022-03-04 23:14 UTC, vmiheer commented
Adding George who is original author of texlive package.

2022-03-12 04:37 UTC, vmiheer commented
Gentle reminder, @tgamblin, @alalazo, @hartzell :)

2022-07-10 00:52 UTC, vmiheer commented
Ping!

2022-07-11 22:45 UTC, tldahlgren requested changes
There are `isort` issues that have to be resolved before the PR can be merged.  I also have a few questions.

In addition, it is easier to review PRs if you create a PR-specific (i.e., non-`develop`) branch for them.

2022-07-11 22:45 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libmspack/package.py
> +class Libmspack(AutotoolsPackage):
```suggestion
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class Libmspack(AutotoolsPackage):
```

2022-07-11 22:45 UTC, tldahlgren commented on var/spack/repos/builtin/packages/miktex/package.py
> +from spack import *
```suggestion
from spack.package import *
```

2022-07-11 22:45 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libmspack/package.py
> +    url = "https://www.cabextract.org.uk/libmspack/libmspack-0.10.1alpha.tar.gz"
Why not use the git repository at https://github.com/kyz/libmspack/?  

Note the sha256 is different for the same version on GitHub (`bd8537b04ebd2149819ce867e3eba50f862a8a0043fd2061360b4101eddaa382`).

2022-07-11 22:45 UTC, tldahlgren commented on var/spack/repos/builtin/packages/miktex/package.py
> +            url='https://miktex.org/download/ctan/systems/win32/miktex/source/miktex-22.1.tar.xz')
This argument duplicates the `url` at line 14 so is not needed.

2022-07-11 22:45 UTC, tldahlgren commented on var/spack/repos/builtin/packages/miktex/package.py
> +    url = "https://miktex.org/download/ctan/systems/win32/miktex/source/miktex-22.1.tar.xz"
Why not use the GitHub version (`https://github.com/MiKTeX/miktex/archive/refs/tags/22.1.tar.gz`)?

The sha256 is different (`a9013a424a5a70ddab08c6b8f1693a22d5da9081399228c37a80a2e733642df2`).

2022-07-11 22:45 UTC, tldahlgren commented on var/spack/repos/builtin/packages/miktex/package.py
> +    version('22.1', sha256='f77caf932e3405d42365438f5c735fe4765989c3442fbb0e9114ad56e7515423',
There are reported bug fixes in version `22.3` on `GitHub`.

2023-02-21 21:50 UTC, closed without merging