Add ROCmPackage to hypre
LLNL/spack pull request #29147
Opened 2022-02-22 18:02 UTC by jrood-nrel

I haven't tested this yet because Crusher is down, so I'm making it a draft while I work through it.

2022-02-23 21:00 UTC, jrood-nrel commented
I verified my changes to CUDA work on Summit as well. Hoping to get a review on this so I can start building some other things on top of this.

2022-03-02 21:46 UTC, jrood-nrel commented
Anybody able to give a review on this?

2022-03-08 02:20 UTC, osborn9 requested changes
Modulo the minor fix for the minimum version with HIP support, this PR looks good, thanks!

To digress, hypre is currently assuming `rocrand` and `rocsparse` are installed in the same location as `hip`. As pointed out in #27743, we need to change this within `hypre`, so that  having spack install these dependencies can be supported. 

Anyways, this PR works with the current assumptions of building `hypre` with ROCm.

2022-03-08 02:20 UTC, osborn9 commented on var/spack/repos/builtin/packages/hypre/package.py
> +    conflicts('+rocm', when='@:2.23.0')
HIP support added in v2.21.0
```suggestion
    conflicts('+rocm', when='@:2.20')
```

2022-03-08 18:32 UTC, jrood-nrel commented
Thanks for the review. I made the suggested change.

2022-03-08 19:12 UTC, osborn9 approved these changes

2022-03-08 19:18 UTC, ulrikeyang approved these changes

2022-03-08 19:56 UTC, osborn9 commented
@balay Could you take a look at this? There's still the outstanding issue within hypre (from #27743), which I will prioritize addressing. In the meantime, this will be helpful for users getting workflows on Spock built.

2022-03-09 08:39 UTC, alalazo approved these changes
Already approved by maintainers

2022-03-09 08:40 UTC, merged