[py-wandb] added version 0.12.10
LLNL/spack pull request #29144
Opened 2022-02-22 16:40 UTC by qwertos

2022-02-22 19:54 UTC, adamjstewart requested changes

2022-02-22 19:54 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-wandb/package.py
> +    depends_on('py-subprocess32@3.5.3:',    type=('build', 'run'))
This isn't required in the latest version

2022-02-22 19:54 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-wandb/package.py
> +    depends_on('py-dockerpy-creds@0.4:',    type=('build', 'run'))
```suggestion
    depends_on('py-docker-pycreds@0.4:',    type=('build', 'run'))
```
This package should be renamed to match PyPI.

2022-02-22 19:54 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-wandb/package.py
> +    pypi     = "wandb/wandb-0.10.1.tar.gz"
```suggestion
    pypi     = "wandb/wandb-0.12.10.tar.gz"
```

2022-10-09 16:31 UTC, adamjstewart commented
Ping @qwertos

2023-02-20 17:19 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2023-02-20 17:19 UTC, closed without merging