[py-sentry-sdk] added version 1.5.5
LLNL/spack pull request #29143
Opened 2022-02-22 16:37 UTC by qwertos

2022-02-22 19:56 UTC, adamjstewart requested changes

2022-02-22 19:56 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-sentry-sdk/package.py
> +    variant('httpx', default=False)
These variants need a description

2022-03-09 17:18 UTC, adamjstewart approved these changes, later dismissed

2022-03-16 19:34 UTC, adamjstewart submitted a review, later dismissed

2022-03-25 16:24 UTC, adamjstewart approved these changes, later dismissed

2022-03-30 08:13 UTC, alalazo commented
```
1. py-sentry-sdk: dependency on py-httpx@0.16.0: cannot be satisfied by known versions of py-httpx
    happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/py-sentry-sdk/package.py
    known versions of py-httpx are 0.15.2, 0.11.1
```

2022-06-08 18:34 UTC, adamjstewart approved these changes

2022-06-08 20:41 UTC, merged