Add 'develop' version for dmtcp
LLNL/spack pull request #29211
Opened 2022-02-25 13:21 UTC by iarspider

2022-02-25 21:17 UTC, iarspider commented
@spackbot run pipeline

2022-02-26 18:02 UTC, adamjstewart requested changes

2022-02-26 18:02 UTC, adamjstewart commented on var/spack/repos/builtin/packages/dmtcp/package.py
> +    version('develop', branch='master')
```suggestion
    version('master', branch='master')
```

2022-02-27 19:34 UTC, adamjstewart approved these changes

2022-02-27 19:34 UTC, merged