Adding Panzer as Default
LLNL/spack pull request #29256
Opened 2022-03-01 00:14 UTC by keitat

I am adding Panzer to the default packages of Trilinos.  This package has been requested by a few ORNL users and Sandia internal users.

2022-03-01 00:30 UTC, sethrj requested changes
@keitat the new variant is going to require new `conflicts` to model the tribits package dependencies. My Trilinos 13.1 dump says the direct required dependencies are:
```dot
"PanzerCore" -> "TpetraCore"
"PanzerDofMgr" -> "MPI"
"PanzerDofMgr" -> "Phalanx"
"PanzerDofMgr" -> "Tpetra"
"PanzerDofMgr" -> "Intrepid2"
"PanzerDofMgr" -> "PanzerCore"
"PanzerDiscFE" -> "PanzerDofMgr"
"PanzerDiscFE" -> "ThyraEpetraExtAdapters"
"PanzerDiscFE" -> "ThyraTpetraAdapters"
"PanzerDiscFE" -> "Zoltan"
"PanzerAdaptersSTK" -> "PanzerDiscFE"
"PanzerAdaptersSTK" -> "Rythmos"
"PanzerAdaptersSTK" -> "NOX"
"PanzerAdaptersSTK" -> "STKIO"
"PanzerAdaptersSTK" -> "Piro"
"PanzerMiniEM" -> "PanzerAdaptersSTK"
"PanzerMiniEM" -> "Teko"
"PanzerMiniEM" -> "MueLu"
"PanzerMiniEM" -> "Belos"
"PanzerExprEval" -> "KokkosCore"
"PanzerExprEval" -> "TeuchosParser"
"Panzer" -> "PanzerCore"
```
Can you add conflicts as necessary for STK, Zoltan, ... ?

Also, do you want to move toward a model where fewer trilinos packages are active by default in spack, and activated by E4S? (That way when a spack package depends on simply `trilinos+tpetra` it doesn't have to disable panzer.)

2022-03-01 01:19 UTC, keitat commented
Zoltan is required for building Exodus (SEACAS) as far as I know.  Yes, we have to set the conflicts/requirement for STK.  As for the default Trilinos for E4S, it's OK tp focus on gen-2 libraries, but we have to modify xsdk to add some gen-1 libraries (as a couple of libraries deal.II and DTK need theses).

2022-03-01 15:20 UTC, sethrj commented
> Yes, we have to set the conflicts/requirement for STK. As for the default Trilinos for E4S, it's OK tp focus on gen-2 libraries, but we have to modify xsdk to add some gen-1 libraries (as a couple of libraries deal.II and DTK need theses).

I'm asking if we can disable by default all libraries that require upstream external packages. If a code just needs Tpetra/Muelu/NOX, we don't want them to have to *disable* a new Trilinos variant just to avoid bringing in METIS etc.

2022-03-01 16:55 UTC, keitat commented
@sethrj I am not 100% sure about all E4S collection.   Yes, Metis is accessed by Zoltan 2 and Zoltan.  We can disable this.  How about SuperLU_DIST which is used by Amesos2.

2022-03-01 17:17 UTC, kuberry commented
@keitat Panzer is already a registered variant. Can the folks you are talking about add `+panzer` to their recipe rather than everyone else having to add `~panzer` to theirs?

I agree with the idea of keeping default enabled packages minimal, with people who need packages turning on those packages.

2022-03-01 17:38 UTC, sethrj commented
@kuberry I think this PR is the first to add the variant -- before this it was always off.

@keitat I'm fine with making all the solver packages off by default. The more important thing IMHO is the other library dependencies: amesos2's dependence on superlu is optional;  the `+superlu` and `+superlu-dist` flags (which conflict? I don't really know much about superlu-dist or how it relates to superlu) that are both off by default.

The biggest trouble is that right now the spack concretizer is not good at providing messages for conflicting variants within a single package.

2022-03-01 23:35 UTC, kuberry commented on var/spack/repos/builtin/packages/trilinos/package.py
> +    variant('panzer',       default=True, description='Compile with Panzer')
I would suggest the default for panzer be set to False, but agree with the variant be added.

2022-03-01 23:35 UTC, kuberry commented on var/spack/repos/builtin/packages/trilinos/package.py
> +            define_trilinos_enable('Panzer'),
This line is why I thought Panzer was already a variant for the recipe.

2022-03-02 16:04 UTC, keitat commented
I still need to add conflict stuff.

2022-03-03 18:26 UTC, keitat commented
@sethrj @kuberry I have a question. Is it possible to enable some specific packages when a user selects Panzer?  Conflict is useful to let it fail, but we may need tell the user what packages are necessary to install panzer without seeing package.py.

2022-03-07 22:59 UTC, keitat commented
@Seth I will add another PR to downsize the default packages as I need to coordinate with xSDK members.

2022-03-08 10:57 UTC, sethrj commented on var/spack/repos/builtin/packages/trilinos/package.py
> +            # options.append(define_trilinos_enable('Thyra', True))
Now that thyra is its own variant, can you remove this block and add `conflicts('~thyra', when='+muelu +stratimikos')`?

2022-03-08 17:43 UTC, sethrj approved these changes
Thanks @keitat -- sorry this PR was such a hassle; the infinite trilinos build options are not a friend to spack.

2022-03-08 19:14 UTC, merged