Added sparrow package.
LLNL/spack pull request #29291
Opened 2022-03-02 14:31 UTC by frobnitzem

Added sparrow semi-empirical quantum chemistry package.

2022-03-03 12:32 UTC, alalazo requested changes
Only one question.

2022-03-03 12:32 UTC, alalazo commented on var/spack/repos/builtin/packages/sparrow/package.py
> +    depends_on("py-pybind11@2.6.2")
Is it really necessary to pin a specific version?

2022-03-11 15:18 UTC, frobnitzem commented on var/spack/repos/builtin/packages/sparrow/package.py
> +    depends_on("py-pybind11@2.6.2")
These are pinned by the sparrow package developers. Their CMake searches specifically for this version.

2022-03-21 15:58 UTC, alalazo approved these changes

2022-03-21 15:59 UTC, merged