libdrm@2.4.110: needs meson for build
LLNL/spack pull request #29327
Opened 2022-03-03 19:34 UTC by eugeneswalker

`libdrm@2.4.110:` looks like it needs `meson` as a build dependency

Fixes https://github.com/spack/spack/issues/29326

@wdconinc

2022-03-03 20:06 UTC, wdconinc requested changes

2022-03-03 20:06 UTC, wdconinc commented on var/spack/repos/builtin/packages/libdrm/package.py
> +    depends_on('meson', type='build', when='@2.4.110:')
```suggestion
    depends_on('meson', type='build', when='@2.4.101:')
```
Thanks for the PR. Meson is required starting at 2.4.101..

2022-03-03 21:00 UTC, wdconinc submitted a review, later dismissed

2022-03-03 22:44 UTC, wdconinc commented
@spackbot run pipeline

2022-03-03 22:51 UTC, wspear submitted a review, later dismissed
Looks good!

2022-03-04 00:37 UTC, wspear approved these changes
Still looks good!

2022-03-04 03:19 UTC, mwkrentel commented
Would it be safer if there was an explicit build dependency for ninja?
Clearly, the install step runs ninja (for recent versions).

I'm concerned about a case where there's an external spec for meson
that fails to transitively pull in ninja.

I was working on an explicit counter example, but I suspect that the
modulue configuration for meson is broken.  That is, on a system
without meson/ninja, I built meson via spack, added it to
packages.yaml as an external (either prefix or module) and told spack
to use it.

I was trying to test if spack picks up ninja in this case, but the
build fails before I can get to that stage with:

```
  File "/home/krentel/elf/install/linux-rhel8-zen/gcc-8.5.0/meson-0.61.2-tkgnsfxdnctug23eog3ks72v3w4jaq4m/bin/meson", line 5, in <module>
    from mesonbuild.mesonmain import main
ModuleNotFoundError: No module named 'mesonbuild'
==> Error: ProcessError: Command exited with status 1:
    'meson' '..' '--prefix=/home/krentel/elf/install/linux-rhel8-zen/gcc-8.5.0/libdrm-2.4.110-ltwi4ulptwgxlhtsrnt6eyitpld3igds' '--libdir=/home/krentel/elf/install/linux-rhel8-zen/gcc-8.5.0/libdrm-2.4.110-ltwi4ulptwgxlhtsrnt6eyitpld3igds/lib' '-Dbuildtype=release' '-Dstrip=false' '-Ddefault_library=shared'
```

So, using the spack built meson as an external package is failing to
pull in its own modules.  Sigh.

Anyway, IMO, an explicit build dependency on ninja would be a good idea.

2022-03-04 03:53 UTC, merged