New package: py-colorio
LLNL/spack pull request #29323
Opened 2022-03-03 18:53 UTC by viv-codes

2022-03-03 20:56 UTC, adamjstewart requested changes

2022-03-03 20:56 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-colorio/package.py
> +    depends_on('py-flit-core@3.2:3.7', type='build')
```suggestion
    depends_on('py-flit-core@3.2:3.6', type='build')
```
Version ranges are inclusive

2022-03-03 20:56 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-colorio/package.py
> +    depends_on('py-setuptools', type='build')
Setuptools isn't needed, flit is used to build the project

2022-03-03 21:08 UTC, adamjstewart approved these changes, later dismissed

2022-03-04 13:14 UTC, viv-codes commented
Rebased against upstream so that now it can build with it's dependency

2022-03-04 13:16 UTC, closed without merging