Osu/mvapich 2.3.7
LLNL/spack pull request #29340
Opened 2022-03-04 15:24 UTC by natshineman

Apologizes. It appears there was a compilation error in our tarball when building with gcc 11. We have fixed this and updated the tarball. I am committing the change in the sha256 value.

2022-03-04 19:18 UTC, eugeneswalker approved these changes

2022-03-09 08:47 UTC, alalazo approved these changes

2022-03-09 08:50 UTC, alalazo requested changes

2022-03-09 08:50 UTC, alalazo commented on var/spack/repos/builtin/packages/mvapich2/package.py
> +    version('2.3.7', sha256='c39a4492f4be50df6100785748ba2894e23ce450a94128181d516da5757751ae')
Can you resolve the conflict? I think the only change wrt `develop` is the new sha256.

2023-02-20 21:17 UTC, alalazo commented
Closing in favor of #35587

2023-02-20 21:17 UTC, closed without merging