gdb: depend only on python, not python+debug
LLNL/spack pull request #29374
Opened 2022-03-07 14:33 UTC by vvolkl

Anyone debugging C extensions to python needs to manually specify they want a debug build of python, but for everyone else, this makes concretizing gdb with other packages much easier

2022-03-07 14:45 UTC, robertu94 reviewed
@vvolkl I am in principle in support of this change, but I want to make sure that we don't break C++ debugging.  I don't have time to test this until April 2nd while my team and I are busy with SC.

If you can post output of printing `v` using spack built `gdb ^ python~debug` for all supported versions of `gdb >= 9.1` in the below code I will approve the merge.

```cpp
#include <vector>

int main() {
    std::vector<int> v{1,2,3};
    return v.size()
}

2022-03-28 13:16 UTC, alalazo requested changes
@vvolkl Can you submit the output requested by maintainer?

2022-03-28 13:20 UTC, tmadlener commented
With the setup mentioned in #29738 and after adding `libstdc++.so.6.0.28-gdb.py` (from a spack installed gcc) to `auto-load-safe-path` I get the following output:

```console
$ g++ -ggdb -O0 test.cpp
$ gdb a.out
Singularity> gdb a.out
GNU gdb (GDB) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from a.out...
(gdb) start
Temporary breakpoint 1 at 0x40083f: file test.cpp, line 4.
Starting program: /nfs/dust/ilc/group/cvmfs_ilc/sw/key4hep_install/aux_dirs/singularity_install_home/a.out 

Temporary breakpoint 1, main () at test.cpp:4
4	  std::vector<int> v = {1, 2, 3};
(gdb) n
5	  return v.size();
(gdb) p v
$1 = std::vector of length 3, capacity 3 = {1, 2, 3}
(gdb) 
```

2022-03-28 13:29 UTC, robertu94 commented
Thanks @tmadlener.  IIRC, previously this worked for me out of the box, but I was using a system provided GCC.

 I wonder if we could do something to make this more transparent to the user.  Please take a look at https://github.com/spack/spack/blob/de654fdcad2da7f84affa58f4f493222a212ed74/var/spack/repos/builtin/packages/gdb/package.py#L110-L115

I'll take a crack at the former next week if you don't want to, but let's see if we can automatically add this for the gcc that built gdb.  We also need to modify this to account for `python~debug` in this logic since it won't be the default going forward.

2022-03-28 13:42 UTC, tmadlener commented
I can try and have a look at this. If I get anything done before next week, I will post the updates here.

2022-04-04 12:35 UTC, robertu94 commented
@tmadlener have you had a chance to look at this?  If you haven't I'll go ahead and write a complete patch and test it.

2022-04-04 12:50 UTC, tmadlener commented
Hi @robertu94, sorry, I was completely occupied with other things, and didn't really do anything for this.

2022-04-04 13:18 UTC, robertu94 commented
@tmadlener no, worries.  I'll take a look and see if I can close this.

2022-04-05 13:47 UTC, robertu94 approved these changes
@tmadlener upon further review and for the reasons in #29893 we can't do auto-load the std library pretty printers reliably since the spack compiler model is too weak.  We'll break off the development of that aspect in a separate PR.

@alalazo  I've done my own testing, and am satisfied that this doesn't break anything.

2022-04-06 04:52 UTC, alalazo approved these changes

2022-04-06 04:52 UTC, merged