thepeg: Add zlib dependency
LLNL/spack pull request #29370
Opened 2022-03-07 10:19 UTC by haralmha

Triggered by `configure: error: either specify a valid zlib installation with --with-zlib=DIR or disable zlib usage with --without-zlib` for thepeg@1.9.2

2022-03-07 13:04 UTC, vvolkl submitted a review, later dismissed

2022-03-08 18:53 UTC, alalazo requested changes

2022-03-08 18:53 UTC, alalazo commented on var/spack/repos/builtin/packages/thepeg/package.py
> +    depends_on('zlib',     type='build')
I think the package also links to `zlib`:
```suggestion
    depends_on('zlib')
```

2022-03-09 08:27 UTC, alalazo approved these changes

2022-03-09 09:02 UTC, merged