py-stomp-py: Add new package
LLNL/spack pull request #29380
Opened 2022-03-07 17:12 UTC by haralmha

2022-03-08 18:34 UTC, alalazo submitted a review, later dismissed

2022-03-11 04:12 UTC, adamjstewart requested changes

2022-03-11 04:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-stomp-py/package.py
> +    depends_on('python@3.6:', type=('build', 'run'))
```suggestion
    depends_on('python@3.6:3', type=('build', 'run'))
```

2022-03-11 04:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-stomp-py/package.py
> +    depends_on('py-docopt@0.6.2:', type=('build', 'run'))
```suggestion
    depends_on('py-docopt@0.6.2:0', type=('build', 'run'))
```

2022-03-14 19:48 UTC, adamjstewart approved these changes

2022-03-15 14:02 UTC, merged