ExaGO v1.4.0, v1.4.1
LLNL/spack pull request #29638
Opened 2022-03-20 23:18 UTC by ashermancinelli

2022-03-20 23:20 UTC, ashermancinelli commented
@CameronRutherford Would you mind taking a look at this before I submit to upstream? I'd like to add v1.4.1 as well, but we'll have to wait for that PR to be merged.

2022-03-21 13:10 UTC, alalazo requested changes
Style tests are failing.

2022-03-21 13:44 UTC, ashermancinelli commented
@alalazo i apologize, this was supposed to be a PR on my fork only. I'll reopen when we've finished internal review. Cheers!

2022-03-21 13:44 UTC, closed without merging

2022-03-21 14:45 UTC, cameronrutherford reviewed
LGTM apart from the mixed reference in comments.

2022-03-21 14:45 UTC, cameronrutherford commented on var/spack/repos/builtin/packages/exago/package.py
> +        #     self.define('HIOP_CTEST_LAUNCH_COMMAND', 'srun -t 10:00'))
This should probably reference the ExaGO variable instead of the HiOp one.

2022-03-21 14:45 UTC, CameronRutherford commented on var/spack/repos/builtin/packages/exago/package.py
> +        #     self.define('HIOP_CTEST_LAUNCH_COMMAND', 'srun -t 10:00'))
Also, do we have any documentation about testing a spack installed ExaGO? I don't think we support `spack test` yet, although you might be able to run ctest from the spack build folder if you build with a cache (?)