Tetgen: add new versions 1.5.1 and 1.6.0
LLNL/spack pull request #29630
Opened 2022-03-20 09:22 UTC by adamqc

Version 1.5.1 and 1.6.0 were released in 2018 and 2020, respectively, I think it's time to add them now.

Note that the `except` variant is only applicable to versions up to 1.5.0 since the newer versions already removed the use of `assert`.

2022-03-21 13:56 UTC, alalazo requested changes
One question, otherwise LGTM

2022-03-21 13:56 UTC, alalazo commented on var/spack/repos/builtin/packages/tetgen/package.py
> +    version('1.5.1', sha256='e46a4434a3e7c00044c8f4f167e18b6f4a85be7d22838c8f948ce8cc8c01b850', url='http://www.tetgen.org/1.5/src/tetgen1.5.1.tar.gz', preferred=True)
Why 1.5.1 is the preferred version?

2022-03-21 15:46 UTC, adamqc commented on var/spack/repos/builtin/packages/tetgen/package.py
> +    version('1.5.1', sha256='e46a4434a3e7c00044c8f4f167e18b6f4a85be7d22838c8f948ce8cc8c01b850', url='http://www.tetgen.org/1.5/src/tetgen1.5.1.tar.gz', preferred=True)
According to my test, version 1.6.0 generates different meshes compared with the previous versions. It is also noticeably slower.

2022-03-21 16:36 UTC, alalazo commented on var/spack/repos/builtin/packages/tetgen/package.py
> +    version('1.5.1', sha256='e46a4434a3e7c00044c8f4f167e18b6f4a85be7d22838c8f948ce8cc8c01b850', url='http://www.tetgen.org/1.5/src/tetgen1.5.1.tar.gz', preferred=True)
Well, I guess we can remove this if somebody complains about the argument being there.

2022-03-21 16:36 UTC, alalazo approved these changes

2022-03-21 16:38 UTC, alalazo requested changes
Ok, second question. Version 1.5.1 seems not to be mentioned in the release notes: https://wias-berlin.de/software/tetgen/relnotes.html ? Do you know why?

2022-03-21 16:52 UTC, adamqc commented
> Ok, second question. Version 1.5.1 seems not to be mentioned in the release notes: [wias-berlin.de/software/tetgen/relnotes.html](https://wias-berlin.de/software/tetgen/relnotes.html) ? Do you know why?

I am sorry, I don't know why it is not mentioned too. But we can see the download link on the download page.

![image](https://user-images.githubusercontent.com/5762792/159314718-867a3554-4c8a-4da2-83de-a89d7d42392d.png)

2022-03-23 09:59 UTC, alalazo approved these changes
Confirmed the two versions with `spack checksum`

2022-03-23 10:00 UTC, merged