Add files via upload
LLNL/spack pull request #29662
Opened 2022-03-22 08:40 UTC by MakotoSeino

install for Fugaku.

2022-03-22 10:16 UTC, iarspider commented
@MakotoSeino the `package.py` file is not in correct directory - it should not be in repo root

2022-03-23 02:24 UTC, MakotoSeino commented
Change the placement of the two package.py.

2022-03-23 12:41 UTC, iarspider commented on package.py
> +# ----------------------------------------------------------------------------
Please remove this boilerplate (lines 6-21)

2022-03-23 12:42 UTC, iarspider commented on var/spack/repos/builtin/packages/py-crsim/package.py
> +# ----------------------------------------------------------------------------
Same here - remove lines 6-21

2022-04-13 23:14 UTC, tldahlgren reviewed
Only addressing the dated copyright notice.

Will defer final approval to @adamjstewart and or @iarspider

2022-04-13 23:14 UTC, tldahlgren commented on package.py
> +# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```

2022-04-13 23:14 UTC, tldahlgren commented on var/spack/repos/builtin/packages/package.py
> +# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```

2022-04-13 23:14 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-crsim/package.py
> +# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```

2022-04-13 23:19 UTC, tldahlgren requested changes

2022-04-13 23:19 UTC, tldahlgren commented on var/spack/repos/builtin/packages/package.py
> +# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
You need to remove this package from this directory in your branch.

2022-04-13 23:19 UTC, tldahlgren commented on package.py
> +# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
You need to remove this file from this directory in your branch.

2022-06-02 16:36 UTC, tldahlgren commented on package.py
> +# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```

2022-06-02 16:38 UTC, tldahlgren commented on package.py
> +# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
This file needs to be removed.

2022-10-09 16:34 UTC, adamjstewart commented
@MakotoSeino is this PR still a work in progress?

2023-02-20 18:05 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2023-02-20 18:05 UTC, closed without merging