Allow to download git over ssh
LLNL/spack pull request #29674
Opened 2022-03-22 22:07 UTC by certik

This commit allows to set:

    git = "git@bitbucket.org:name/repo.git"

As is done in several builtin packages as well as very useful for
internal proprietary packages that can only be downloaded over ssh from
a private github/bitbucket/gitlab repository.

Without this commit, the following fails:

    $ spack install talass
    [...]
      File "/.../spack/lib/spack/spack/fetch_strategy.py", line 883, in mirror_id
        repo_path = url_util.parse(self.url).path
      File "/.../spack/lib/spack/spack/util/url.py", line 79, in parse
        require_url_format(url)
      File "/.../spack/lib/spack/spack/util/url.py", line 347, in require_url_format
        assert ut is not None
    AssertionError

But with this commit it works:

    $ spack install talass
    [...]
    Cloning into 'talass'...
    remote: Enumerating objects: 27704, done.
    remote: Counting objects: 100% (253/253), done.
    ...

2022-03-23 14:51 UTC, junghans approved these changes, later dismissed

2022-03-23 21:40 UTC, tgamblin requested changes

2022-03-23 21:40 UTC, tgamblin commented on lib/spack/spack/util/url.py
> +    ut = re.search(r'^(file://|http://|https://|ftp://|s3://|gs://|git@|/)', url)
Can you add a test to ensure this continues to work?  Look at https://github.com/spack/spack/pull/29592/files

2022-07-06 23:44 UTC, certik commented
Unfortunately I can't run tests locally due to #31472, so I'll use the CI to iterate until it passes.

2022-07-07 05:32 UTC, certik commented
I think this is now implemented in `develop` using the `ssh://git@bitbucket.org/name/repo.git` syntax and it seems to work. So I'll close this.

2022-07-07 05:32 UTC, closed without merging