New/xcrysden
LLNL/spack pull request #29705
Opened 2022-03-24 16:47 UTC by shahzebsiddiqui

2022-03-26 18:18 UTC, fcannini commented
@shahzebsiddiqui Hi there!
I've changed jobs and am no longer involved in any spack-related activity. Please feel free to adopt this package.

2022-03-29 23:51 UTC, shahzebsiddiqui commented
No worries @fcannini. I opened the PR so we dont lose this work. I'd prefer to get someone from xcrysden to help. I am not familiar with this package to be a maintainer.

2022-03-30 07:10 UTC, alalazo commented
@fcannini Feel free to remove yourself from the list of maintainers if you don't want to receive notifications from @spackbot

2022-04-13 23:05 UTC, tldahlgren requested changes
At a minimum, the copyright years need to be updated.

Also suggested considering at least using the `SourceforgePackage` mixin for setting the url and mirrors.

2022-04-13 23:05 UTC, tldahlgren commented on var/spack/repos/builtin/packages/tcl-bwidget/package.py
> +# Copyright 2013-2019 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```

2022-04-13 23:05 UTC, tldahlgren commented on var/spack/repos/builtin/packages/tcl-bwidget/package.py
> +class TclBwidget(Package):
All of the current packages that extend `tcl` inherit from `AutotoolsPackage`.  Is this something to consider?

Also, several packages, including `tcl`, `tclap`, and `tk`, "inherit" from `SourceforgePackage` (actually a `mixin`) for the benefits of setting the url and mirrors.  

Have you considered at least taking advantage of the mixin?

2022-04-13 23:05 UTC, tldahlgren commented on var/spack/repos/builtin/packages/togl/package.py
> +# Copyright 2013-2019 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```

2022-04-13 23:05 UTC, tldahlgren commented on var/spack/repos/builtin/packages/togl/package.py
> +    url      = homepage + "/files/Togl/2.0/Togl2.0-src.tar.gz"
Same suggestion here about considering the `SourceforgePackage` mixin.

2022-04-13 23:05 UTC, tldahlgren commented on var/spack/repos/builtin/packages/xcrysden/package.py
> +# Copyright 2013-2019 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```

2023-02-20 18:11 UTC, alalazo commented
@shahzebsiddiqui Any update on this PR?

2023-10-09 16:06 UTC, closed without merging

2023-10-09 16:06 UTC, alecbcs commented
Going to go ahead and close this PR due to a lack of response. @shahzebsiddiqui happy to reopen if you're still working on this.