Support DASK backend in XARRAY.
LLNL/spack pull request #29726
Opened 2022-03-25 21:09 UTC by naromero77

I am not super familiar with DASK or XARRAY, but I believe this is the write patch to support DASK as a backend for XARRAY. Based on my reading of this webpage:
https://xarray.pydata.org/en/stable/user-guide/dask.html

2022-03-25 21:19 UTC, adamjstewart requested changes

2022-03-25 21:19 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-xarray/package.py
> +    depends_on('py-dask',     when='+io', type=('build', 'run'))
Dask isn't needed for I/O, it's needed for parallel support. So two changes are required here. First, you'll want to add a `+parallel` variant above:
```python
variant('parallel', default=False, description='Build parallel backend')
```
Then you'll want to change this line to the following (equivalent to `dask[complete]`):
```suggestion
    depends_on('py-dask+array+bag+dataframe+distributed+diagnostics+delayed', when='+parallel', type=('build', 'run'))
```

2022-03-26 06:16 UTC, naromero77 commented
I have a question related to this package, if I do:
`spack spec py-xarray+parallel%oneapi@2022.0.0`

I get a a list of python packages that are dependencies. However, when I try to install it:
`spack install py-xarray+parallel%oneapi@2022.0.0`

I get substantially many many more packages, e.g. py-pooch, py-netcdf4, etc. --- why is this happening? its almost as I added the `+io` option.

Is this a feature or bug in the concretizer?

2022-03-26 07:42 UTC, naromero77 commented
I have resolved the issue. It looks like a previously used root spec was causing the problem. I am relatively new to environments and don't quite understand the concept of a root spec. I had to manually remove the old root spec using `spack remove <root spec>`, then did a `spack install py-xarray+parallel%oneapi@2022.0.0` -- this time it installed only the stuff I needed.

Let me know if there anything else is needed to merge this patch.

2022-03-26 16:02 UTC, adamjstewart approved these changes

2022-03-27 23:46 UTC, naromero77 commented
@adamjstewart Something in the CI appears to be stuck.

2022-03-28 00:53 UTC, adamjstewart commented
@scottwittenburg can you look into the CI problem?

2022-03-29 17:23 UTC, naromero77intel commented
Still not working -- not sure what is going on and it doesn't look like I can restart it.

2022-03-29 18:52 UTC, adamjstewart commented
@spackbot run pipeline

2022-03-29 18:59 UTC, scottwittenburg commented
This had become unstuck, I guess on it's own, yesterday when I took a look.  But it seems like the pipeline took so long, the aws credentials given to it upon triggering expired before it finished, which cause the `cleanup` job to fail.  I don't know what's going on with spackbot right now, but let's if I can just retry that job and skip re-running the whole pipeline.

2022-03-29 20:02 UTC, merged