[mochi-thallium] added mochi-thallium package
LLNL/spack pull request #29722
Opened 2022-03-25 17:56 UTC by mdorier

This PR adds the mochi-thallium package.

2022-03-25 20:45 UTC, hyoklee submitted a review, later dismissed

2022-03-27 17:54 UTC, sethrj requested changes
One minor change; otherwise the package looks good!

2022-03-27 17:54 UTC, sethrj commented on var/spack/repos/builtin/packages/mochi-thallium/package.py
> +            args.append("-DENABLE_CEREAL:BOOL=ON")
```suggestion
        args.append(self.define_from_variant("ENABLE_CEREAL", "cereal"))
```

This is simpler and prevents the accidental detection of an environment dependency (forcing the value to `off` when `~cereal`.

2022-03-27 23:27 UTC, hyoklee approved these changes

2022-03-27 23:30 UTC, sethrj approved these changes

2022-03-28 00:18 UTC, merged