simmetrix-simmodsuite: add opencascade variant and version 16.0-220312
LLNL/spack pull request #29759
Opened 2022-03-28 20:24 UTC by cwsmith

This PR adds the `opencascade` variant to support the interface with OpenCascade, and a new version with the OpenCascade resource/tarball checksum.

2022-03-29 15:06 UTC, alalazo requested changes

2022-03-29 15:06 UTC, alalazo commented on var/spack/repos/builtin/packages/simmetrix-simmodsuite/package.py
> +    variant('opencascade', default=False, description='enable opencascade modeling')
I think here you might be missing a `when=` argument:
```suggestion
    variant('opencascade', default=False, when='@16.0-220312', description='enable opencascade modeling')
```

2022-03-29 16:44 UTC, cwsmith commented on var/spack/repos/builtin/packages/simmetrix-simmodsuite/package.py
> +    variant('opencascade', default=False, description='enable opencascade modeling')
@alalazo Good catch.  Thank you.  I committed your suggestion and extended the version range to include future versions https://github.com/spack/spack/pull/29759/commits/484307bea3f6b38ac3e6850fbb8de881c036f2a1.

2022-03-30 07:34 UTC, alalazo approved these changes

2022-03-30 08:33 UTC, merged