py-pystan: Add new package
LLNL/spack pull request #29772
Opened 2022-03-29 14:28 UTC by haralmha

2022-03-29 14:30 UTC, haralmha commented
Depends on py-marshmallow, py-webargs, py-pysimdjson and py-httpstan, which are not yet added to spack. PRs made here: https://github.com/spack/spack/pull/29764, https://github.com/spack/spack/pull/29768, https://github.com/spack/spack/pull/29767 and https://github.com/spack/spack/pull/29770.

2022-03-29 19:12 UTC, adamjstewart requested changes

2022-03-29 19:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pystan/package.py
> +    depends_on('python@3.8:', type=('build', 'run'))
```suggestion
    depends_on('python@3.8:3', type=('build', 'run'))
```

2022-03-29 19:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pystan/package.py
> +    depends_on('py-aiohttp@3.6:', type=('build', 'run'))
```suggestion
    depends_on('py-aiohttp@3.6:3', type=('build', 'run'))
```

2022-03-29 19:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pystan/package.py
> +    depends_on('py-httpstan@:4.6,4.8:', type=('build', 'run'))
```suggestion
    depends_on('py-httpstan@4.7', type=('build', 'run'))
```
https://python-poetry.org/docs/dependency-specification/#tilde-requirements

2022-03-29 19:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pystan/package.py
> +    depends_on('py-pysimdjson@3.2:', type=('build', 'run'))
```suggestion
    depends_on('py-pysimdjson@3.2:3', type=('build', 'run'))
```

2022-03-29 19:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pystan/package.py
> +    depends_on('py-numpy@1.19:', type=('build', 'run'))
```suggestion
    depends_on('py-numpy@1.19:1', type=('build', 'run'))
```

2022-03-29 19:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pystan/package.py
> +    depends_on('py-clikit@0.6:', type=('build', 'run'))
```suggestion
    depends_on('py-clikit@0.6:0', type=('build', 'run'))
```

2022-03-30 19:05 UTC, adamjstewart requested changes

2022-03-30 19:05 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pystan/package.py
> +    depends_on('py-setuptools', type='build')
```suggestion
    depends_on('py-setuptools', type=('build', 'run'))
```
`pkg_resources` is needed at run-time.

2022-03-31 14:57 UTC, adamjstewart approved these changes, later dismissed

2022-04-21 18:53 UTC, adamjstewart requested changes

2022-04-21 18:53 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pystan/package.py
> +    depends_on('py-clikit@0.6:0', type=('build', 'run'))
```suggestion
    depends_on('py-clikit@0.6', type=('build', 'run'))
```
Caret requirements work differently if the major version is 0: https://python-poetry.org/docs/dependency-specification/#caret-requirements

2022-04-22 14:56 UTC, adamjstewart approved these changes

2022-04-22 14:56 UTC, merged