py-httpstan: Add new package
LLNL/spack pull request #29770
Opened 2022-03-29 13:53 UTC by haralmha

2022-03-29 13:54 UTC, haralmha commented
Depends on py-marshmallow and py-webargs, which are not yet added to spack. PRs made here: https://github.com/spack/spack/pull/29764 and here: https://github.com/spack/spack/pull/29768

2022-03-29 19:03 UTC, adamjstewart requested changes
Caret deps work a bit differently: https://python-poetry.org/docs/dependency-specification/

2022-03-29 19:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-httpstan/package.py
> +    depends_on('python@3.7:', type=('build', 'run'))
```suggestion
    depends_on('python@3.7:3', type=('build', 'run'))
```

2022-03-29 19:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-httpstan/package.py
> +    depends_on('py-aiohttp@3.7:', type=('build', 'run'))
```suggestion
    depends_on('py-aiohttp@3.7:3', type=('build', 'run'))
```

2022-03-29 19:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-httpstan/package.py
> +    depends_on('py-appdirs@1.4:', type=('build', 'run'))
```suggestion
    depends_on('py-appdirs@1.4:1', type=('build', 'run'))
```

2022-03-29 19:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-httpstan/package.py
> +    depends_on('py-webargs@8.0:', type=('build', 'run'))
```suggestion
    depends_on('py-webargs@8.0:8', type=('build', 'run'))
```

2022-03-29 19:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-httpstan/package.py
> +    depends_on('py-marshmallow@3.10:', type=('build', 'run'))
```suggestion
    depends_on('py-marshmallow@3.10:3', type=('build', 'run'))
```

2022-03-29 19:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-httpstan/package.py
> +    depends_on('py-numpy@1.16:', type=('build', 'run'))
```suggestion
    depends_on('py-numpy@1.16:1', type=('build', 'run'))
```

2022-03-30 19:07 UTC, adamjstewart requested changes

2022-03-30 19:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-httpstan/package.py
> +    depends_on('py-setuptools@41.0:', type='build')
```suggestion
    depends_on('py-setuptools@41.0:', type=('build', 'run'))
```
`setuptools` is imported at run-time

2022-03-31 14:56 UTC, adamjstewart submitted a review, later dismissed

2022-03-31 15:43 UTC, alalazo commented
@haralmha I would advise to submitting a unique PR with related software. That would make package audits pass the first time, since there will be no missing versions or missing dependencies. With that said: thanks a lot for your contributions!

2022-04-01 06:55 UTC, haralmha commented
@alalazo ah okay, thanks for your feedback! I was not sure if you wanted one PR per package or one for the whole bunch, but I'll go with the latter next time :)

2022-04-20 16:07 UTC, adamjstewart approved these changes

2022-04-20 16:07 UTC, merged