canonicalize_path: add arch information to substitutions
LLNL/spack pull request #29810
Opened 2022-03-31 01:55 UTC by becker33

This will allow users to use `include: [$arch/packages.yaml]` to include architecture-specific configs in their environments.

Requested by user Thomas Dickerson on slack.

Includes unit test

2022-03-31 14:54 UTC, elfprince13 commented
Resolves #29815.

2022-05-11 14:45 UTC, elfprince13 commented
What's the status on getting this merged?

2022-10-11 19:03 UTC, elfprince13 submitted a review, later dismissed
Apparently I can review things now? LGTM. What's the procedure on getting this merged?

2022-11-04 18:33 UTC, becker33 commented
@spackbot fix style

2022-11-05 05:04 UTC, alalazo requested changes
LGTM, but can we update https://spack.readthedocs.io/en/latest/configuration.html#spack-specific-variables too?

2022-11-06 09:11 UTC, alalazo approved these changes

2022-11-06 09:12 UTC, merged