osu-micro-benchmarks: 5.9
LLNL/spack pull request #29814
Opened 2022-03-31 13:39 UTC by haampie

2022-03-31 16:04 UTC, alalazo requested changes
I think there's a typo

2022-03-31 16:04 UTC, alalazo commented on var/spack/repos/builtin/packages/osu-micro-benchmarks/package.py
> +    version('5.7.1', sha256='cb5ce4e2e68ed012d9952e96ef880a802058c87a1d840a2093b19bddc7faa165', url="https://mvapich.cse.ohio-state.edu/download/mvapich/osu-micro-benchmarks-5.7.1.tar.gz")
```suggestion
    version('5.7.1', sha256='cb5ce4e2e68ed012d9952e96ef880a802058c87a1d840a2093b19bddc7faa165', url="https://mvapich.cse.ohio-state.edu/download/mvapich/osu-micro-benchmarks-5.7.1.tgz")
```

2022-03-31 16:15 UTC, alalazo approved these changes

2022-04-01 06:37 UTC, haampie commented
@spackbot run pipeline

2022-04-01 06:46 UTC, merged