h5bench: update versions
LLNL/spack pull request #29819
Opened 2022-03-31 15:57 UTC by jeanbez

Include versions and new variants and ensure all versions use git to get all required submodules.

2022-04-01 16:17 UTC, sbyna submitted a review, later dismissed

2022-04-04 08:34 UTC, alalazo requested changes

2022-04-04 08:34 UTC, alalazo commented on var/spack/repos/builtin/packages/h5bench/package.py
> +    version('1.0', submodules=True)
Can we pin a commit here?

2022-04-04 20:12 UTC, jeanbez commented on var/spack/repos/builtin/packages/h5bench/package.py
> +    version('1.0', submodules=True)
@alalazo done!

2022-04-06 04:30 UTC, alalazo approved these changes

2022-04-06 04:31 UTC, merged