LAPACK: add API compatibility versions
LLNL/spack pull request #29828
Opened 2022-04-01 03:56 UTC by adamjstewart

Certain packages like SciPy require minimal versions of the LAPACK API. This PR adds compatibility versions when known.

LAPACK providers:

- [ ] amdlibflame
- [ ] atlas
- [ ] cray-libsci
- [ ] flexiblas
- [ ] fujitsu-ssl2
- [ ] intel-mkl
- [ ] intel-oneapi-mkl
- [ ] intel-parallel-studio
- [ ] libflame
- [x] netlib-lapack
- [ ] nvhpc
- [ ] openblas
- [x] veclibfort

Not sure where to find compatibility versions for the other providers. The authors of https://github.com/scipy/scipy/wiki/Dropping-support-for-Accelerate seem to have some idea. @rgommers can you or anyone else who helped write that wiki help with the other packages? I would like to specify as many as possible, we don't need to get all of them.

Fixes #29808

2022-04-01 05:49 UTC, rgommers commented
Unfortunately there's no uniform way that that info is kept anywhere, it was a matter of searching release notes typically, or asking maintainers. Here are a couple more:
- Intel MKL: [release notes](https://www.intel.com/content/www/us/en/developer/articles/release-notes/intel-math-kernel-library-release-notes-and-new-features.html) say: _"Aligned Intel® MKL LAPACK functionality with Netlib LAPACK 3.9.0"_. I have asked a maintainer if there's a fixed relation between the 3 ways of installing MKL (`mkl`, `onapi-mkl`, `parallel-studio`)
- OpenBLAS `0.3.15` updated to LAPACK 3.9.1 and is still at that version I believe: https://github.com/xianyi/OpenBLAS/blob/develop/Changelog.txt#L195
- ATLAS: very hard to find, but ATLAS is no longer developed (last changes from 2018) so I'm going to assume that the info at https://github.com/scipy/scipy/wiki/Dropping-support-for-Accelerate#which-minimum-lapack-version-to-support is still up-to-date: ATLAS `3.10.3` implements LAPACK `3.6.1`.

2022-04-10 19:32 UTC, adamjstewart commented
@spackbot run pipeline

2022-05-04 12:37 UTC, alalazo requested changes
One minor request, otherwise LGTM

2022-05-04 12:37 UTC, alalazo commented on var/spack/repos/builtin/packages/netlib-lapack/package.py
> +        provides('lapack@' + ver, when='@' + ver)
Can we add a comment or something in the docstring saying that this package is the reference version for the virtual `lapack` API?

2022-05-04 16:04 UTC, alalazo approved these changes

2022-05-05 08:38 UTC, merged