Add or-tools package.
LLNL/spack pull request #29858
Opened 2022-04-03 01:51 UTC by hyoklee

This is a OR-tools package for C++ users with minimal dependency for fast installation. 
While py-or-tools package requires manual download for dependency, this one doesn't.
This package will be useful for C/C++ packages that depend on OR-Tools.

This will close #29839.

2022-04-04 07:53 UTC, alalazo reviewed
Can you explain why you decided to have a new package vs. having options to disable features in `py-or-tools`?

2022-04-04 15:32 UTC, hyoklee commented
> Can you explain why you decided to have a new package vs. having options to disable features in `py-or-tools`?

2022-04-04 15:40 UTC, hyoklee commented
I accidentally closed PR and reopened it.

2022-04-13 21:06 UTC, hyoklee commented
@alalazo , would you please approve it? My other [PR](https://github.com/spack/spack/pull/29863) is approved and it depends on this pacakge.

2022-04-14 07:59 UTC, alalazo requested changes

2022-04-14 07:59 UTC, alalazo commented on var/spack/repos/builtin/packages/or-tools/package.py
> +    variant('coin', default=False)
Please add a description to the variant

2022-04-14 07:59 UTC, alalazo commented on var/spack/repos/builtin/packages/or-tools/package.py
> +    depends_on('coinutils@2.11.4', when='+coin')
We don't use pinned versions of dependencies, can you please add ranges?

2022-04-14 07:59 UTC, alalazo commented on var/spack/repos/builtin/packages/or-tools/package.py
> +            cmake_args.append('-DUSE_COINOR=OFF')
Here you can use `self.define_from_variant` to have a more declarative statement

2022-04-19 12:11 UTC, alalazo approved these changes

2022-04-19 12:12 UTC, merged