rapidjson: Add version 1.2.0-2022-03-09
LLNL/spack pull request #29869
Opened 2022-04-04 09:30 UTC by haralmha

Includes PR https://github.com/Tencent/rapidjson/pull/1940 which fixes https://github.com/Tencent/rapidjson/issues/1924 causing errors for newer compilers on centos

2022-04-04 10:32 UTC, haampie commented
can you bump https://github.com/Tencent/rapidjson/issues/1006 again... maybe it's better to move away from rapidjson if they don't do releases.

2022-04-07 23:53 UTC, tldahlgren approved these changes
Confirmed the commit and, from the one for "1.2.0-2021-08-13", that appears to be the way this package is being handled going forward.  

IMO It still feels a bit "off" in at least the fact that this is a merge commit that doesn't even document it as a release.

2022-04-07 23:55 UTC, tldahlgren commented
Holding off on the merge to get another opinion on this approach.

2022-04-07 23:56 UTC, tldahlgren commented
> can you bump [Tencent/rapidjson#1006](https://github.com/Tencent/rapidjson/issues/1006) again... maybe it's better to move away from rapidjson if they don't do releases.

Not sure how I missed this when I added my comment and approval.

2022-04-08 00:00 UTC, tldahlgren requested changes
Based on some slack feedback, IF this is the way going forward, @sethrj suggested a different naming scheme for the version (e.g., `master-2022-03-09`) so it is more indicative of what is going on.

In that case, it would be good -- if there are no strong objections -- to also changing the name of the August 13th version as well.

2022-04-08 08:00 UTC, haampie commented
I think the [latest known version]-[date] scheme is fine, so that when they finally tag a new release, our versions are ordered correctly.

2022-04-08 08:01 UTC, haampie approved these changes

2022-04-08 20:07 UTC, tldahlgren approved these changes

2022-04-08 20:08 UTC, tldahlgren commented
> I think the [latest known version]-[date] scheme is fine, so that when they finally tag a new release, our versions are ordered correctly.

I won't stand in the way then.

2022-04-08 20:08 UTC, merged