Set resource requests on package builds
LLNL/spack pull request #29922
Opened 2022-04-06 15:08 UTC by kotfic

This explicitly sets resource requests for the Kubernetes  executor which should aid in better workload scheduling in the cluster. Values are based on tiers huge, large, medium, default, small which were derived from profile data taken from several full "from scratch" rebuilds in a separate worker pool.  Kubernetes will not schedule a job to a node whose requests (CPU/RAM) are larger than the capacity for that node minus the requests of the nodes currently running on the pod. Keep in mind that _requests_  are not the same as actual _utilization_.  This only effects how many jobs may be stacked onto a single node (which in turn affects auto scaling of resources) 

It is likely some of these requests will be inconsistent with the actual utilization and we will be monitoring/tweaking these values (and which packages fall into which tiers for which stacks) as we move forward.  For now the tiers are as follows:

|Tier | CPU | RAM | 
|--- |--- |--- |
| huge | 11 | 42 Gb |
| large | 8 | 12 Gb |
| medium | 2 | 2 Gb |
| default | 0.75 | 2 Gb |
| small | 0.5 | 500Mb |

2022-04-06 15:10 UTC, kotfic commented
@scottwittenburg PTAL!

2022-04-06 22:09 UTC, scottwittenburg requested changes
Thanks @kotfic this is looking pretty good.  

Aside from the typo I pointed out, I'm also just curious about something.  I notice that the new `CI_JOB_SIZE` variable is present in the runner attributes and always matches the "size" tag in the tag list, which somehow I thought we would no longer need.  How are those tags used now, and how is the `CI_JOB_SIZE` variable used?  Is there a requirement that the `CI_JOB_SIZE` variable and the "size" tag match, or did it just work out that way? 

Thanks again!

2022-04-06 22:09 UTC, scottwittenburg commented on share/spack/gitlab/cloud_pipelines/stacks/build_systems/spack.yaml
> -  cdash:
Removal of this space is what I think caused the failure of the generation job for this stack, [here](https://gitlab.spack.io/spack/spack/-/jobs/2247448).

2022-04-06 22:18 UTC, scottwittenburg commented
Also, yes, we'll have to keep an eye on jobs failing due to resource starvation after this.  Some of the mappings don't make sense to me (based on past experience), but I think it makes sense to kind of start fresh with the data-driven breakdown you generated, and then refine once we see how ti's going.

2022-04-06 22:21 UTC, scottwittenburg commented
fyi @eugeneswalker IIRC correctly, your runners are set up to handle jobs tagged with any size (e.g. `huge`, `large`, etc.).  But does this PR introduce some that we need to add to your runners?  I'm not sure if we've used `default` or `small` before, so you may need to add those.  Otherwise, I don't think the additional job variables will affect your runners, I'm just bringing this to your attention so you're aware.

2022-04-06 22:57 UTC, scottwittenburg commented on share/spack/gitlab/cloud_pipelines/stacks/build_systems/spack.yaml
> -  cdash:
It was clearer in the diff view, here not so much, but a space was removed before the `cdash`.

2022-04-14 12:53 UTC, kotfic commented
@scottwittenburg I've pushed a typo fix.  With regard to `CI_JOB_SIZE`  - adding this variable makes it easier to track job size in the Prometheus metrics.  The tags of a particular GitLab job aren't exposed in a simple way to Prometheus.  This should allow us to look at the mean and spread of resource usage around jobs of a particular size and make determinations if certain jobs are consistently outliers in those distributions.

2022-04-15 21:05 UTC, scottwittenburg commented on share/spack/gitlab/cloud_pipelines/stacks/build_systems/spack.yaml
> +          tags: [ "spack", "public", "medium", "x86_64" ]
Wondering if this was meant to be `small`, since the match above is also `medium`.

2022-04-19 16:04 UTC, scottwittenburg approved these changes
Thanks @kotfic!

2022-04-19 16:09 UTC, merged