frontier-client: Adapt pacparser_setmyip function to new pacparser release
LLNL/spack pull request #29936
Opened 2022-04-07 09:38 UTC by haralmha

Pacparser 1.3.9 changed the `pacparser_setmyip` function return type from void( https://github.com/manugarg/pacparser/blob/v1.3.8/src/pacparser.h#L110-L111) to int (https://github.com/manugarg/pacparser/blob/v1.3.9/src/pacparser.h#L111-L112). frontier-client hasn't had a new release recently, and hence the function implementation is not yet overridden: https://github.com/fermitools/frontier/blob/v2_9_1/client/pacparser-dlopen.c#L94-L99, which triggers this error when frontier-client depends on the newest pacparser release:
```
2 errors found in build log:
     34    gcc -Wall -g -O2 -DFRONTIER_DEBUG -fPIC -DPIC -I/build/hahansen/Spack/packages/expat/2.4.8/x86_64-centos7-gcc11.2.0-opt/zxlf6/include  -I/build/hahansen/Spack/packages/pacparser/1.3.9/x86_64-centos7-
           gcc11.2.0-opt/pi43o/include  -I./include -I. -c memdata.c
     35    gcc -Wall -g -O2 -DFRONTIER_DEBUG -fPIC -DPIC -I/build/hahansen/Spack/packages/expat/2.4.8/x86_64-centos7-gcc11.2.0-opt/zxlf6/include  -I/build/hahansen/Spack/packages/pacparser/1.3.9/x86_64-centos7-
           gcc11.2.0-opt/pi43o/include  -I./include -I. -c frontier_log.c
     36    gcc -Wall -g -O2 -DFRONTIER_DEBUG -fPIC -DPIC -I/build/hahansen/Spack/packages/expat/2.4.8/x86_64-centos7-gcc11.2.0-opt/zxlf6/include  -I/build/hahansen/Spack/packages/pacparser/1.3.9/x86_64-centos7-
           gcc11.2.0-opt/pi43o/include  -I./include -I. -c frontier_error.c
     37    gcc -DFNAPI_VERSION="\"2.9.1\"" -Wall -g -O2 -DFRONTIER_DEBUG -fPIC -DPIC -I/build/hahansen/Spack/packages/expat/2.4.8/x86_64-centos7-gcc11.2.0-opt/zxlf6/include  -I/build/hahansen/Spack/packages/pac
           parser/1.3.9/x86_64-centos7-gcc11.2.0-opt/pi43o/include  -I./include -I. -c frontier_config.c
     38    gcc -Wall -g -O2 -DFRONTIER_DEBUG -fPIC -DPIC -I/build/hahansen/Spack/packages/expat/2.4.8/x86_64-centos7-gcc11.2.0-opt/zxlf6/include  -I/build/hahansen/Spack/packages/pacparser/1.3.9/x86_64-centos7-
           gcc11.2.0-opt/pi43o/include  -I./include -I. -c fn-mem.c
     39    gcc -Wall -g -O2 -DFRONTIER_DEBUG -fPIC -DPIC -I/build/hahansen/Spack/packages/expat/2.4.8/x86_64-centos7-gcc11.2.0-opt/zxlf6/include  -I/build/hahansen/Spack/packages/pacparser/1.3.9/x86_64-centos7-
           gcc11.2.0-opt/pi43o/include  -I./include -I. -c pacparser-dlopen.c
  >> 40    pacparser-dlopen.c:94:6: error: conflicting types for 'pacparser_setmyip'; have 'void(const char *)'
     41       94 | void pacparser_setmyip(const char *ip)
     42          |      ^~~~~~~~~~~~~~~~~
     43    In file included from pacparser-dlopen.c:17:
     44    /build/hahansen/Spack/packages/pacparser/1.3.9/x86_64-centos7-gcc11.2.0-opt/pi43o/include/pacparser.h:111:5: note: previous declaration of 'pacparser_setmyip' with type 'int(const char *)'
     45      111 | int pacparser_setmyip(const char *ip                 // Custom IP address.
     46          |     ^~~~~~~~~~~~~~~~~
  >> 47    make: *** [pacparser-dlopen.o] Error 1

```

2022-04-19 11:20 UTC, iarspider approved these changes, later dismissed

2022-04-22 08:32 UTC, haralmha commented
The checks were stuck in CI again..

2022-04-22 08:33 UTC, iarspider submitted a review, later dismissed

2022-05-06 07:37 UTC, haralmha commented
@alalazo

2022-05-06 13:54 UTC, alalazo requested changes

2022-05-06 13:54 UTC, alalazo commented on var/spack/repos/builtin/packages/frontier-client/package.py
> +                    'client/pacparser-dlopen.c', string=True)
Can you add as a comment above here a brief explanation like the one in the PR description?

2022-05-16 08:41 UTC, alalazo approved these changes

2022-05-16 08:41 UTC, merged