spack ci: remove relate-CDash-builds functionality
LLNL/spack pull request #29950
Opened 2022-04-07 18:52 UTC by zackgalbreath

This was a seldom used feature. Removing it will make it easier for us to reorganize our CDash projects & build groups in the future by eliminating the needs to keep track of CDash build ids in our binary mirrors.

2022-04-07 19:13 UTC, scottwittenburg commented
Thanks for taking this on @zackgalbreath!  I'm taking a look now, but just want to ping @tldahlgren asap, in case #27877 relies on anything removed here, in which case we can coordinate before it's too late.

2022-04-07 19:17 UTC, scottwittenburg commented
Also @zackgalbreath is it easy to come up with a screenshot that depicts what we're losing by removing this functionality?  That might help people who see this and wonder about its effect.  I'm not sure I've even seen the functionality in CDash myself, so count me among that group :laughing:

2022-04-07 19:27 UTC, zackgalbreath commented
> Also @zackgalbreath is it easy to come up with a screenshot that depicts what we're losing by removing this functionality? That might help people who see this and wonder about its effect. I'm not sure I've even seen the functionality in CDash myself, so count me among that group 😆

Sure, here's an example from [a recent LLVM build](https://cdash.spack.io/build/946929)

<img width="1500" alt="Screen Shot 2022-04-07 at 3 27 01 PM" src="https://user-images.githubusercontent.com/224720/162281390-f7766b99-d844-4361-930c-7ed9cd51783a.png">

2022-04-07 19:32 UTC, tldahlgren commented
> Thanks for taking this on @zackgalbreath! I'm taking a look now, but just want to ping @tldahlgren asap, in case #27877 relies on anything removed here, in which case we can coordinate before it's too late.

Thanks for the heads up!  I rebased to recent `ci` changes and am retesting now.  Looks like I'll have more cleaning up to do when I rebase to this PR.

FWIW I spoke with Todd earlier.  He said build jobs should be failing if they cannot upload to the build cache (e.g. permission errors).  So the extra code I added to deal with job specs (re) building their dependencies needs to be removed anyway.

2022-04-12 01:06 UTC, scottwittenburg requested changes

2022-04-12 01:06 UTC, scottwittenburg commented on lib/spack/spack/ci.py
>          'deps': {},
I think this should be removed too, since we will no longer populate anything under that key.

2022-04-12 01:12 UTC, scottwittenburg commented
Meant to add a couple of additional comments/suggestions, but my finger hit the button first.

This is great, thanks @zackgalbreath!  Except for the one tiny suggestion, this looks good to me.  However, in addition to that, could you add a WIP commit that adds (or uncomments) a package with a few dependencies to one of the tested stacks?  That would let us check the logs on a few gitlab jobs for anything unexpected.  Then you can remove that WIP commit before final approval.

2022-04-14 02:34 UTC, scottwittenburg commented
Pipeline that built some radiuss specs is [here](https://gitlab.spack.io/spack/spack/-/pipelines/113335).

I was expecting it to build `git` too, but maybe putting two list entries on one line prevented it?  I would have thought it would either notice and build it, or be a syntax error.  I don't think it really matters though, it's clear the `gettext` binary was successfully pushed and the build was reported to CDash as well (see [here](https://cdash.spack.io/build/970108)).

@zackgalbreath If you can now remove that `DONOTMERGE` commit, the gitlab pipeline turnaround should be quicker (except if you have to wait for a develop pipeline).

2022-04-14 11:57 UTC, zackgalbreath commented
> I was expecting it to build `git` too, but maybe putting two list entries on one line prevented it?

My intention was "gettext with the git variant disabled", not "gettext and git" as separate specs.


> can now remove that `DONOTMERGE` commit

Will do!

2022-04-14 16:35 UTC, scottwittenburg approved these changes
Looks good to me, thanks @zackgalbreath!

2022-04-14 16:42 UTC, merged