Fixing the -lregionFaModels linking issue in OpenFOAM 2112
LLNL/spack pull request #30003
Opened 2022-04-11 12:01 UTC by amd-toolchain-support

Building `OpenFOAM 2112` with `AOCC Clang (v3.2.0)` is throwing below linker issue 

```
ld.lld: error: undefined symbol: typeinfo for Foam::regionModels::regionFaModel

>>> referenced by MPPICInterFoam.C

v2112/build/linux64AmdDPInt32Opt/applications/solvers/multiphase/MPPICInterFoam/MPPICInterFoam.o:(void Foam::SurfaceFilmModel<Foam::KinematicCloud<Foam::Cloud<Foam::KinematicParcel<Foam::particle> > > >::inject<Foam::KinematicCloud<Foam::Cloud<Foam::KinematicParcel<Foam::particle> > > >(Foam::KinematicCloud<Foam::Cloud<Foam::KinematicParcel<Foam::particle> > >&))
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)

```

Linking with `-lregionFaModels`  in `link-c++` file resolving the issue.

2022-04-20 16:25 UTC, olesenm requested changes
I understand what you are trying to achieve, but this is absolutely the wrong way to do this.

If the issue has not yet been fixed upstream (check first), then [make an issue](https://develop.openfoam.com/Development/openfoam/-/issues).  After that is done, this sha1 from that correction would be added as a source code patch for the spack recipe.

2022-04-21 05:02 UTC, amd-toolchain-support commented
Hi @olesenm 

Please note that, we have raised the concern in one of the `OpenFOAM` forums in Feb-2022.
please find the issue [here](https://www.cfd-online.com/Forums/openfoam-installation/241089-openfoam-2112-build-fails-aocc-clang.html#post821829)

As there was no response to it since then, we have taken this approach in Spack.

We will also raise the issue with the link that is shared you.

Thanks.

2022-04-22 18:01 UTC, olesenm commented
> Hi @olesenm
> 
> Please note that, we have raised the concern in one of the `OpenFOAM` forums in Feb-2022. please find the issue [here](https://www.cfd-online.com/Forums/openfoam-installation/241089-openfoam-2112-build-fails-aocc-clang.html#post821829)
> 
> As there was no response to it since then, we have taken this approach in Spack.
> 
> We will also raise the issue with the link that is shared you.

Hi @amd-toolchain-support - picked up your [openfoam issue](https://develop.openfoam.com/Development/openfoam/-/issues/2449) and it looks like there really is only that one application affected.

2022-04-25 14:48 UTC, alalazo commented
Closing after reading maintainer's review:

> I understand what you are trying to achieve, but this is absolutely the wrong way to do this.

My understanding is that we'll be seeking an alternative solution to this issue, but feel free to reopen if I got it wrong.

2022-04-25 14:48 UTC, closed without merging

2022-06-14 07:48 UTC, olesenm commented
This problem should be addressed by #31113