man-db: fix installl prefix and library runtime
LLNL/spack pull request #30031
Opened 2022-04-12 12:20 UTC by vvolkl

`man-db` installed some directories to `$prefix/$prefix` instead of `$prefix` (DESTDIR is needed for some other folders, like this everything seems to be in order)

Also adds a workaround for the `lib/man-db` libdir (while waiting for https://github.com/spack/spack/pull/29657).

2022-05-09 10:41 UTC, alalazo requested changes

2022-05-09 10:41 UTC, alalazo commented on var/spack/repos/builtin/packages/man-db/package.py
> +        env.prepend_path('LD_LIBRARY_PATH', join_path(self.prefix.lib, "man-db"))
Shouldn't we have a post install function that fixes that instead?

2022-05-09 11:03 UTC, vvolkl commented on var/spack/repos/builtin/packages/man-db/package.py
> +        env.prepend_path('LD_LIBRARY_PATH', join_path(self.prefix.lib, "man-db"))
As far as I understand, the proper fix should be https://github.com/spack/spack/pull/29657 (slack discussion: https://spackpm.slack.com/archives/C5VL7V81G/p1649764620629959)

2023-06-20 13:57 UTC, vvolkl commented
Seems like the environment for man-db has been fixed in another PR, closing this as no longer relevant.

2023-06-20 13:57 UTC, closed without merging