add external find support for which
LLNL/spack pull request #30056
Opened 2022-04-14 02:20 UTC by robertu94

It does what it says on the tin.  Added this to ease the pain with caused by adding which as a dependency for R in  #30055

2022-04-14 02:35 UTC, robertu94 commented
@sknigh You added `which` a few years ago.  Do you want to review this?

2022-04-14 08:39 UTC, alalazo requested changes
Style tests are failing

2022-04-14 11:21 UTC, robertu94 commented
Sorry @alalazo never program while asleep I guess 😴 .  Style should be fixed now.

2022-04-19 12:24 UTC, alalazo approved these changes

2022-04-19 12:24 UTC, merged