add version and pydebug patch
LLNL/spack pull request #30088
Opened 2022-04-15 08:35 UTC by joequant

2022-04-15 09:42 UTC, vvolkl requested changes
Thanks @joequant, the new version has already been added in https://github.com/spack/spack/pull/29744, please rebase on that.

Also please prepend the PR title with "py-awkward: " for a more readable commit history.

Can you add a comment motivating the patch, with a link to an upstream issue/commit if that exists?

2022-04-15 14:57 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-awkward/pydebug.patch
> ++                    'd' in sys.abiflags ? "-pydebug" : ""
Is this even valid Python?

2022-04-17 20:24 UTC, joequant commented on var/spack/repos/builtin/packages/py-awkward/pydebug.patch
> ++                    'd' in sys.abiflags ? "-pydebug" : ""
thinking c++ let me put in a fix

2022-04-17 20:35 UTC, joequant commented
yuck..  Let me force a clean patch.

2023-02-20 18:20 UTC, alalazo commented
Still waiting for:

> Also please prepend the PR title with "py-awkward: " for a more readable commit history.
>
> Can you add a comment motivating the patch, with a link to an upstream issue/commit if that exists?

Closing in the meanwhile, but feel free to reopen if you want to continue working on this.

2023-02-20 18:20 UTC, closed without merging