boost: Update list of modules
LLNL/spack pull request #30104
Opened 2022-04-15 21:00 UTC by eschnett

Add various new modules that are available in Boost, most notably "json" which is required for Meson builds.

Make list of default variants more readable, and add "json" to it.

2022-04-16 17:40 UTC, hainest commented
@eschnett I'm working on a PR that will add all of these components and update the existing ones using conditional variants. I just heard back from the Boost folks about a couple of questions I had, so that PR should be ready this week.

As an aside, we don't want to add any more default components in this package. That model has been replaced with a composable one (#28623).

Thanks!

2022-04-25 15:42 UTC, eschnett commented
@hainest Do you have a PR?

2022-04-25 16:08 UTC, hainest commented
@eschnett Sorry, I have been super busy this week and I still need to talk to Adam about a couple of items before I can move forward.

In the interim, let's merge this with a few modifications

- remove json from `with_default_variants`. The idea of default variants is scheduled to go away soon.
- add back signals to `with_default_variants`. It's super broken, but we'll at least preserve current functionality.
- remove `headers`. It isn't a real library, but a pseudo target for b2. It's defaulted ON in the Jamfile, so we don't need to expose it here. With the new composable model, installing header-only is the default, anyway.

2022-04-25 17:36 UTC, eschnett commented
@hainest Done.

2022-04-25 18:34 UTC, hainest requested changes

2022-04-25 18:34 UTC, hainest commented on var/spack/repos/builtin/packages/boost/package.py
> +        'stacktrace',
```suggestion
        'signals',
        'stacktrace',
```

It shouldn't be there, but signals is still an allowed variant.

2022-04-25 21:55 UTC, hainest approved these changes

2022-04-25 21:55 UTC, hainest commented
@eschnett Thanks!

2022-04-26 09:23 UTC, alalazo requested changes
Shouldn't we keep track when a library was added to boost? That is, shouldn't we prohibit things like:
```
boost@1.39.0 +type_erasure
```
(or anything that was added at a later version)?

2022-04-26 15:03 UTC, eschnett commented
@alalazo Ideally we should.

This PR adds the `json` package because I have another package (`reprimand`) that requires it (because the `meson` build system requires it), and my primary intent for this PR was to make `reprimand` build again.

2022-04-26 15:04 UTC, hainest commented
@alalazo I am working on a PR to convert to conditional variants for everything. This PR is a stopgap so Erik can use one of the missing libraries.

2022-04-26 15:12 UTC, alalazo approved these changes
Thanks for the context, then LGTM

2022-04-26 15:12 UTC, merged