gitlab ci: replace deprecated zlib in tutorial
LLNL/spack pull request #30148
Opened 2022-04-18 23:02 UTC by scottwittenburg

The spack tutorial refers specifically to version `1.2.8` of zlib in multiple places, but since that version is deprecated now, it can no longer be built without `--deprecated`.

2022-04-19 07:00 UTC, alalazo commented
@scottwittenburg Did you double check the tutorial? I think in a few places the v1.2.8 was used in place of the preferred one to show that you can pick and choose whichever version you want (so using the preferred v1.2.12 version won't make sense there).

2022-04-19 07:03 UTC, alalazo requested changes
With respect to the comment above, see for instance how v1.2.8 is used [here](https://spack-tutorial.readthedocs.io/en/latest/tutorial_basics.html)

2022-04-19 15:51 UTC, scottwittenburg commented
@alalazo Yes I took a quick look at the tutorial, but I wasn't 100% sure about the intent of picking `1.2.8`.  But it sounds like we might be in trouble regarding that particular goal of the tutorial, because at the moment, the preferred version of `zlib` is the only version that is not deprecated.  Any thoughts on what should be done?  Right now, if we try to build zlib in the pipeline, it fails, and we're only avoiding that because `zlib` is already in the mirror and its hash hasn't changed.

2022-04-19 15:52 UTC, scottwittenburg commented
@zackgalbreath

2022-04-19 18:07 UTC, becker33 commented
I think we should not deprecate those versions, I think it was overeager to deprecate them.

An alternative is we could just configure the tutorial to be okay with deprecated versions.

2022-05-12 17:46 UTC, scottwittenburg commented
Closing this as #30648 is a better approach for now.

2022-05-12 17:46 UTC, closed without merging