Add checksum for jupyter-console@6.4.3
LLNL/spack pull request #30156
Opened 2022-04-19 08:46 UTC by aandvalenzuela

2022-04-19 09:37 UTC, alalazo submitted a review, later dismissed

2022-04-19 16:16 UTC, adamjstewart requested changes
jupyter_client dep needs to be updated

2022-04-22 15:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-jupyter-console/package.py
> +    depends_on('py-jupyter-client@7.0.0:', type=('build', 'run'), when='@6.4.3')
```suggestion
    depends_on('py-jupyter-client@7.0.0:', type=('build', 'run'), when='@6.4.3:')
```
Presumably newer versions will also have this requirement.

2022-04-22 15:56 UTC, adamjstewart approved these changes

2022-04-22 16:42 UTC, merged