py-cinemasci: new version 1.7.0
LLNL/spack pull request #30193
Opened 2022-04-20 14:51 UTC by EthanS94

This PR adds the newest version of `py-cinemasci`

2022-04-20 15:39 UTC, eugeneswalker submitted a review, later dismissed
Checksum verified. Thanks!

2022-04-21 19:22 UTC, adamjstewart requested changes

2022-04-21 19:22 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cinemasci/package.py
> +    version('1.7.0', sha256='70e1fa494bcbefdbd9e8859cdf1b01163a94ecffcdfa3da1011e4ef2fcee6169', preferred=True)
```suggestion
    version('1.7.0', sha256='70e1fa494bcbefdbd9e8859cdf1b01163a94ecffcdfa3da1011e4ef2fcee6169')
```
Spack always prefers the latest stable release by default, no need to specify this

2022-04-21 19:22 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cinemasci/package.py
>      depends_on('py-setuptools', type=('build'))
Missing dep on py-pyyaml

2022-04-21 22:55 UTC, EthanS94 commented on var/spack/repos/builtin/packages/py-cinemasci/package.py
>      depends_on('py-setuptools', type=('build'))
@adamjstewart I built without it. Why does it need py-pyyaml?

2022-04-21 22:59 UTC, EthanS94 commented on var/spack/repos/builtin/packages/py-cinemasci/package.py
>      depends_on('py-setuptools', type=('build'))
You're right. Adding that.

2022-04-22 02:42 UTC, adamjstewart approved these changes

2022-04-22 03:34 UTC, merged