Add fix for binutils 2.38 +gas makeinfo issue
LLNL/spack pull request #30209
Opened 2022-04-21 02:01 UTC by drkrynstrng

With `spack install binutils@2.38%gcc +gas`, the build will fail with a warning:

```
>> 3579    WARNING: 'makeinfo' is missing on your system.
     3580             You should only need it if you modified a '.texi' file, or
     3581             any other file indirectly affecting the aspect of the manual.
     3582             You might want to install the Texinfo package:
     3583             <http://www.gnu.org/software/texinfo/>
     3584             The spurious makeinfo call might also be the consequence of
     3585             using a buggy 'make' (AIX, DU, IRIX), in which case you might
```

Adding the following build dependency fixes it:

```
depends_on('texinfo', type='build', when='@2.38 +gas')
```

See bug report here: https://sourceware.org/bugzilla/show_bug.cgi?id=28909

It seems a missing timestamp file is the cause. Maybe a patch could work instead of adding this build dependency, but I'm not sure how to create a patch for this.

2022-04-21 03:01 UTC, eugeneswalker commented
It looks like this might not be isolated to `+gas` variant. See https://github.com/spack/spack/issues/29168
@wspear

2022-04-21 06:56 UTC, alalazo requested changes

2022-04-21 06:56 UTC, alalazo commented on var/spack/repos/builtin/packages/binutils/package.py
> +
Style fix:
```suggestion

```

2022-04-27 10:11 UTC, alalazo approved these changes

2022-04-27 10:11 UTC, merged