yaksa: Add ROCm variant
LLNL/spack pull request #30222
Opened 2022-04-21 17:09 UTC by raffenet

Builds yaksa with HIP backend for AMD GPU device memory support.

2022-04-25 13:35 UTC, alalazo requested changes
One minor comment

2022-04-25 13:35 UTC, alalazo commented on var/spack/repos/builtin/packages/yaksa/package.py
> +    depends_on('hip', when='+rocm')
I think this is already in the `ROCmPackage` base class
```suggestion
```

2022-04-28 02:00 UTC, raffenet commented
@alalazo I committed your requested change. I think this one is good to go.

2022-05-03 14:20 UTC, raffenet commented
@alalazo ping

2022-05-03 14:52 UTC, alalazo approved these changes

2022-05-03 14:52 UTC, merged