level-zero: add new package
LLNL/spack pull request #30253
Opened 2022-04-22 16:48 UTC by raffenet

This is an attempt to get the ball rolling on Level Zero support in Spack. This package can be used to compile test code with Level Zero dependencies like MPICH. I do not know who the maintainers of the package should be, so have left that blank for now.

2022-04-27 14:47 UTC, rscohn2 commented
Thanks for contributing the package. It would be great to have l0 in spack, and I was always thinking about the difficulty of building all of the dependencies from source. I understand now that you only need a header and loader to build a package that depends on l0--provided in this package. Have you verified this with MPICH?

This package still has a runtime dependence on the actual l0 driver, which is a user mode library. I guess there is a configure option that we could expose if they are not using the l0 on the system path?

2022-04-27 14:58 UTC, raffenet commented
> Thanks for contributing the package. It would be great to have l0 in spack, and I was always thinking about the difficulty of building all of the dependencies from source. I understand now that you only need a header and loader to build a package that depends on l0--provided in this package. Have you verified this with MPICH?
> 
> This package still has a runtime dependence on the actual l0 driver, which is a user mode library. I guess there is a configure option that we could expose if they are not using the l0 on the system path?

For base-level support of Intel GPUs, this library is all that we need. As far as I know, it provides pointer query information and host->device, device->host memory copy functionality. MPICH will compile and link with this open-source package using the configure time option `--with-ze=<path/to/install>`. Actual runtime usage in my experience fails with this package on systems with Intel GPUs. I'm not well-versed enough in the details to know what is the underlying issue.

For more advanced communication support in MPICH (direct from GPU memory), we also depend on the `ocloc` compiler to build data pack/unpack kernels to run on the GPU. I have not successfully been able to install `ocloc` on my own.

2022-04-27 15:25 UTC, rscohn2 commented
> Actual runtime usage in my experience fails with this package on systems with Intel GPUs. I'm not well-versed enough in the details to know what is the underlying issue.

OK. Then we don't want to publish this package right now. If we had a procedure where you could make a spack package depend on this package for header and library, but still be required to install runtime components separately, that would be helpful for the people who do not install l0 header/libs on the system paths. I will need to do some investigation. I usually just install deb files that are part of the github releases, which includes everything.

Another issue is naming. Loader and driver are potentially 2 separate spack packages. Applications link against the loader, so  we could call the loader package level-zero (as you have done), and the driver level-zero-driver. That might be confusing.

2022-05-03 19:15 UTC, jmellorcrummey commented
@rscohn2 Having a package that has the Level 0 headers is all that we need for building performance tools that intercept functions in the Level 0 API and replace them with our wrappers. At runtime, we dlopen "libze_loader.so" that better be available in the library path or address space for the software using it so we can locate key functions in the API implementation that we need to call from our wrappers.

2022-05-03 21:04 UTC, rscohn2 commented
I talked to someone in the level zero team, and they think the approach in this PR (loader is a spack package, driver is installed outside of spack) should work. It would be the simplest solution. I will look into it some more.

2022-05-03 21:36 UTC, rscohn2 commented
The sample works ok. Can one of you provide a spack package that is set up to build with level zero that I could try it on? It does not look like the mpich spack package has a way to provide the --with-ze.

2022-05-04 00:22 UTC, wspear commented
The tau package has a level_zero variant. It doesn't take a path, it just tells the tau configure script to look for level zero in the environment so I'm not sure if it will work out of the box in this case.

Here is a relevant PR and Issue for reference:
https://github.com/spack/spack/issues/25893
https://github.com/spack/spack/pull/28066

2022-05-04 02:21 UTC, jmellorcrummey commented
@rscohn2 
@mwkrentel and I will work up a proper package.py for hpctoolkit that configures using a level-zero package. give me a day or so; i'm busy with the exascale computing project annual meeting this week.

2022-05-04 03:37 UTC, alalazo requested changes
Just a minor comment

2022-05-04 03:37 UTC, alalazo commented on var/spack/repos/builtin/packages/level-zero/package.py
> +    # maintainers = ['github_user1', 'github_user2']
Can you either remove this commented out line or add a maintainer?

2022-05-04 11:08 UTC, rscohn2 commented on var/spack/repos/builtin/packages/level-zero/package.py
> +    # maintainers = ['github_user1', 'github_user2']
```suggestion
    maintainers = ['rscohn2']
```

2022-05-04 11:11 UTC, rscohn2 commented
> @mwkrentel and I will work up a proper package.py for hpctoolkit that configures using a level-zero package. give me a day or so; i'm busy with the exascale computing project annual meeting this week.

Can you submit it as a PR to https://github.com/raffenet/spack/tree/l0-package so it can become part of this PR? It would make testing easier.

2022-05-04 11:13 UTC, rscohn2 commented
@raffenet: Can you give me write access to your fork so I can push directly to your branch and update the PR?

2022-05-04 13:19 UTC, rscohn2 commented
Tau builds ok: https://github.com/raffenet/spack/pull/1 and the configure is able to find the library
@wspear: Can you verify that it works?

2022-05-04 13:55 UTC, raffenet commented
> @raffenet: Can you give me write access to your fork so I can push directly to your branch and update the PR?

Just sent an invite to collaborate on my fork.

2022-05-04 14:41 UTC, rscohn2 commented
> Just sent an invite to collaborate on my fork.

Thanks. I merged the Tau changes into this PR. If we can get the hpckit changes and verify that both work that would be a good test.

2022-05-04 16:04 UTC, jmellorcrummey commented
@rscohn2 I've tested the level0 support by adding it to a spack repository where I also added support for level0 to hpctoolkit. I am a git novice and don't know how to best handle your request to submit a PR to @raffenet's branch. I tried that and found that this branch is stale with respect to spack develop and it has an out of date copy of our hpctoolkit package. Here is a link to my commit in my spack repository that adds a few lines to an up-to-date package.py for hpctoolkit. 

https://github.com/jmellorcrummey/spack/commit/84b4a4b8b35e70d73c4e02f2f57798980b4599f3

perhaps @rscohn2 or @raffenet can figure out how to test this in your collaborative branch

2022-05-04 16:35 UTC, raffenet commented
> perhaps @rscohn2 or @raffenet can figure out how to test this in your collaborative branch

Done. I had to rebase and fix some conflicts, so the new version is a force push. Make sure you're getting the latest copy if making any more updates.

2022-05-04 18:01 UTC, jmellorcrummey commented
@rscohn2 I hate to rock the boat here, but do you want this package named 'level-zero' or would you prefer to have it named 'intel-level-zero' like 'intel-xed', 'intel-tbb', 'intel-opeapi-compilers', ...

2022-05-04 18:27 UTC, rscohn2 commented
> do you want this package named 'level-zero'

The ubuntu package is called level-zero so the current name is ok.

2022-05-04 18:33 UTC, mwkrentel commented
> The ubuntu package is called level-zero so the current name is ok.

But the pattern here are spack names, not ubuntu names.

2022-05-04 19:08 UTC, rscohn2 commented
> But the pattern here are spack names, not ubuntu names.

The intel branding is that products are 'intel oneapi ...' and open source projects are 'oneapi ...'. All the oneapi products have a 'intel-oneapi' prefix. It would be good if all the open source projects had a 'oneapi' prefix.

2022-05-04 20:00 UTC, rscohn2 commented
hpctoolkit builds ok for me, too. Any issues other than the name? If you care what the name is, please speak up. I am ok with:
level-zero or oneapi-level-zero with a slight preference for oneapi-level-zero

2022-05-04 20:34 UTC, jmellorcrummey commented
@rscohn2 my prior opinion (name it intel-level-zero) stands, though this is a decision for you as an Intel representative to make. 

Some data about spack packages that support my view:

See https://spack.readthedocs.io/en/latest/build_systems/intelpackage.html#intel-packages-in-spack

johnmc@iris:~/hpctoolkit$ spack list -d oneAPI
==> 16 packages.
intel-oneapi-advisor    intel-oneapi-dal  intel-oneapi-inspector  intel-oneapi-mkl  intel-oneapi-vpl    onednn
intel-oneapi-ccl        intel-oneapi-dnn  intel-oneapi-ipp        intel-oneapi-mpi  intel-oneapi-vtune
intel-oneapi-compilers  intel-oneapi-dpl  intel-oneapi-ippcp      intel-oneapi-tbb 

(NOTE: there is a package onednn in the above oneAPI list as well as intel-oneapi-dnn. Perhaps that is questionable.)

Other packages described on the readthedocs page:

intel-mkl – Math Kernel Library (linear algebra and FFT),
intel-mpi – The Intel-MPI implementation (derived from MPICH),
intel-ipp – Primitives for image-, signal-, and data-processing,
intel-daal – Machine learning and data analytics.
intel-parallel-studio – the entire suite of compilers and libraries,
intel – a subset containing just the compilers and the Intel-MPI runtime [[fn2]]

intel-gpu-tools – Test suite and low-level tools for the Linux [Direct Rendering Manager]
intel-mkl-dnn – Math Kernel Library for Deep Neural Networks (CMakePackage)
intel-xed – X86 machine instructions encoder/decoder
intel-tbb – Standalone version of Intel Threading Building Blocks.

2022-05-04 20:49 UTC, jmellorcrummey commented
@rscohn2 ignore my previous comment about naming, which I deleted. I overlooked your explanation about naming of open source vs. intel products. in that case, either level-zero or oneapi-level-zero are fine. 

of course, tbb and xed are open source and they have the intel prefix. things don't seem entirely consistent.

2022-05-04 22:08 UTC, rscohn2 commented
> of course, tbb and xed are open source and they have the intel prefix. things don't seem entirely consistent.

Agreed. We stopped saying 'intel x' for the oneapi open source projects to emphasize that we invite community engagement.

2022-05-05 12:45 UTC, rscohn2 commented
I renamed it to oneapi-level-zero and added some more description. I think it is ready to go.

Thanks to @raffenet for making the package. It was requested a long time ago and I did not realize that the loader was sufficient.

2022-05-05 13:48 UTC, rscohn2 commented
@spackbot run pipeline

2022-05-06 13:28 UTC, jmellorcrummey commented
@alalazo change request has been addressed; all tests pass; please commit.

2022-05-06 14:12 UTC, alalazo approved these changes

2022-05-06 14:12 UTC, merged