build_env/test_env: add concretizer args
LLNL/spack pull request #30289
Opened 2022-04-26 00:40 UTC by becker33

Fixes #29491

2022-04-26 08:12 UTC, alalazo requested changes
I also miss this one:
```console
$ spack commands --update-completion
```
every single time :laughing:

2022-04-26 16:17 UTC, becker33 commented
@alalazo thanks! Updated.

2022-04-26 16:25 UTC, alalazo approved these changes

2022-04-28 09:37 UTC, merged

2022-04-28 10:49 UTC, haampie commented
it's a new "feature", but also an inconsistency fix backportworthy to 0.17.3?