Feature/gcta redo
LLNL/spack pull request #30286
Opened 2022-04-25 21:54 UTC by snehring

I don't know if I was feeling especially lazy when I did the original version of this, but the way they're doing binaries is more complicated now. So let's switch to proper source builds.

The latest version adds a few dependencies, including a new package 'spectra'.

The CMakeLists.txt for gcta sets -msse2, but the spack compiler wrappers still seem to do the correct thing based on the specified target, so instead of creating a variant or anything I'm going to let it ride.

2022-04-25 22:06 UTC, snehring commented
Per the original PR it sounds like the code was distributed a bit differently in the past, with the binaries being a bit ahead of the available source. Not so today.

2022-04-26 09:18 UTC, alalazo requested changes
Can you omit the explicit `(build, link)` type, since it's the default?

2022-04-26 09:18 UTC, alalazo commented on var/spack/repos/builtin/packages/gcta/package.py
> +    depends_on('openblas', type=('build', 'link'), when='target=aarch64:')
Why not:
```python
depends_on('lapack')
```
(or similar)?

2022-04-26 09:18 UTC, alalazo commented on var/spack/repos/builtin/packages/gcta/package.py
> +    depends_on('boost@1.4:', type=('build', 'link'), when='@1.94.0beta:')
Is it really `boost@1.4:` ? (Asking since now we're at 1.79.0, so 1.4 was a long time ago)

2022-04-26 16:01 UTC, snehring commented on var/spack/repos/builtin/packages/gcta/package.py
> +    depends_on('boost@1.4:', type=('build', 'link'), when='@1.94.0beta:')
That's what's listed under requirements, I mostly just went from that verbatim. They may have meant 1.40, which is also still very old.

2022-04-26 16:06 UTC, snehring commented on var/spack/repos/builtin/packages/gcta/package.py
> +    depends_on('openblas', type=('build', 'link'), when='target=aarch64:')
They look for mkl specifically, I had tried blas originally. https://github.com/jianyangqt/gcta/blob/master/CMakeLists.txt#L105

2022-04-26 19:05 UTC, snehring commented
@spackbot run pipeline

2022-04-26 19:07 UTC, snehring commented on var/spack/repos/builtin/packages/gcta/package.py
> +    depends_on('boost@1.4:', type=('build', 'link'), when='@1.94.0beta:')
I bumped it to 1.79, just to give us a definite floor of 'works'.

2022-04-26 19:09 UTC, snehring commented
Failures seem to be unrelated to my changes.

2022-04-27 08:39 UTC, alalazo approved these changes

2022-04-27 08:56 UTC, merged