SCons: added versions 4.0.0-4.3.0
LLNL/spack pull request #30296
Opened 2022-04-26 13:39 UTC by prs513rosewood

I've added new versions of SCons. I fixed the `pypi` package attribute because it was preventing fetching of the newer archives. The older (3.1.2 and below) were fetched from Spack's mirror, so I don't know how this change affects the mirroring, feel free to suggest edits if something's wrong. Cheers!

2022-04-26 14:54 UTC, prs513rosewood commented
I followed the python version requirements from the [release notes](https://scons.org/tag/releases.html), but I realize this could fail dependency resolution for packages that specify `scons@3:` and `python@:3.5`, although I don't know if there's any scons package that has these constraints.

2022-04-26 19:53 UTC, adamjstewart requested changes
I think you'll need to add a `url_for_version` function like:
```python
def url_for_version(self, version):
    url = 'https://files.pythonhosted.org/packages/source/{0}/{1}/{1}-{2}.tar.gz'
    if version >= Version('4.0.0'):
        name = 'SCons'
    else:
        name = 'scons'
    return url.format(name[0], name, version)
```

2022-04-27 07:50 UTC, prs513rosewood commented
Thanks for the pointer on `url_for_version`. Interestingly, I could still install versions prior to 4.0.0, even with `--no-cache`, because the source archive was fetched from Spack's mirror.

2022-04-27 15:40 UTC, adamjstewart commented
Yes, we first check the local downloads cache, then check Spack's download mirror, then check the original source. If anything goes wrong with the first two we want the third to still work.

2022-04-27 15:42 UTC, adamjstewart commented on var/spack/repos/builtin/packages/scons/package.py
> +    depends_on('python@3.6:', when='@4.3.0:')
Where do you see this? The `setup.cfg` still says 3.5 is supported.

2022-04-27 16:07 UTC, prs513rosewood commented on var/spack/repos/builtin/packages/scons/package.py
> +    depends_on('python@3.6:', when='@4.3.0:')
From https://scons.org/scons-430-is-available.html

> NOTE: 4.3.0 now requires Python 3.6.0 and above. Python 3.5.x is no longer supported

The description on [PyPI](https://pypi.org/project/SCons/) also mentions:

> As of SCons 4.2.0 support for Python 3.5 is deprecated and will be removed with the next major release.

They may have forgotten to update that requirement everywhere.

2022-04-27 16:08 UTC, adamjstewart approved these changes

2022-04-27 16:08 UTC, merged