minc-toolkit: fix build by updating zlib url, hash
LLNL/spack pull request #30301
Opened 2022-04-26 16:19 UTC by bcdarwin

2022-04-27 09:14 UTC, alalazo requested changes
```
PKG-DIRECTIVES: 1 issue found
1. patch URL in package minc-toolkit must end with ?full_index=1
    https://github.com/BIC-MNI/minc-toolkit-v2/commit/c7ebff42838e083e9368caebff87778d6ea27427.patch
```

2022-05-04 12:19 UTC, alalazo requested changes

2022-05-04 12:19 UTC, alalazo commented on var/spack/repos/builtin/packages/minc-toolkit/package.py
> +          sha256="42ee1d500553369a21720f18cef77b7905ef29a4f47ef8adce24c8adafbea74f")
How does this combine with the:
```python
depends_on('zlib')
```
below?

2022-05-30 17:29 UTC, bcdarwin commented
Closing this PR in favour of #30926.

I'm not sure what the issue is with zlib but my guess is that the toolkit's CMake build doesn't correctly link to the zlib it installs and in fact depends on the system version as well (presumably not noticed by upstream due to lack of build isolation).

2022-05-30 17:29 UTC, closed without merging