armpl: add new package
LLNL/spack pull request #30305
Opened 2022-04-26 18:30 UTC by annop-w

Add a new package for installing free Arm Performance Libraries.

2022-04-26 18:38 UTC, annop-w commented
This updates the armpl package scripts in #29042 and #27750. Updates for the arm package (for Arm Compiler for Linux) will follow in a separate PR.

2022-04-26 19:24 UTC, tldahlgren requested changes

2022-04-26 19:24 UTC, tldahlgren commented on var/spack/repos/builtin/packages/armpl/package.py
> +# Copyright 2013-2020 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```

2022-04-27 22:25 UTC, tldahlgren approved these changes
Style consistent with the `arm` package.  Confirmed only one of the sha256.

2022-04-27 22:25 UTC, merged