Add checksum for py-prettytable@3.2.0
LLNL/spack pull request #30329
Opened 2022-04-27 15:30 UTC by aandvalenzuela

2022-04-27 15:38 UTC, adamjstewart requested changes
Python 3.7+ is now required

2022-04-27 16:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-more-itertools/package.py
> +    version('8.12.0', sha256='7dc6ad46f05f545f900dd59e8dfb4e84a4827b97b3cfecb175ea0c7d247f6064')
I think these changes got added to the wrong PR

2022-04-28 16:30 UTC, adamjstewart commented
This PR still conflicts with #30325. Can you remove those changes or rebase the PR?

2022-04-29 07:25 UTC, aandvalenzuela commented
My bad, sorry! Now it should be solved :)

2022-04-29 15:32 UTC, adamjstewart approved these changes

2022-04-29 15:33 UTC, merged