binutils@2.38 %gcc: add -fPIC -fcommon -Wl,-z,notext
LLNL/spack pull request #30345
Opened 2022-04-27 19:45 UTC by eugeneswalker

Fixes https://github.com/spack/spack/issues/30195

2022-04-29 07:37 UTC, alalazo requested changes
LGTM as soon as the conflict with #30338 is solved

2022-04-29 21:20 UTC, eugeneswalker commented
> LGTM as soon as the conflict with #30338 is solved

I re-based and resolved the conflict. Thank you!

2022-05-01 13:58 UTC, mwkrentel commented
@eugeneswalker   While you're here, I'm concerned about

```
174    iflags.append('-fPIC -fcommon')
```

I'm concerned that something would interpret this as single argument
`'-fPIC -fcommon'` with a space in the arg.  Even if this works now,
and I guess it does, someone may come along and "fix" spack's quoting
rules and this may break.

I think it's safer and cleaner to write this as two args with `iflags.extend`.

Also, `-fPIC` should probably be `self.compiler.cc_pic_flag`.

2022-05-01 14:23 UTC, jmellorcrummey commented
I encountered the same problem last night with binutils 2.39 on ubuntu 20.04 with gcc 9.4.0.

The salient bit of information is that the problem isn’t limited to binutils 2.38.

2022-05-02 01:35 UTC, eugeneswalker commented
> I encountered the same problem last night with binutils 2.39 on ubuntu 20.04 with gcc 9.4.0.

I'm not seeing `binutils@2.39` on the FTP mirror or registered with Spack. Where did you get this?

2022-05-02 01:44 UTC, eugeneswalker commented
@mwkrentel I've implemented these changes. Thank you

2022-05-02 04:00 UTC, jmellorcrummey commented
@eugeneswalker Obviously, I should have used my large screen. I couldn't tell the difference between 2.38 and 2.39 late at night on my laptop :-). Sorry for the noise.

2022-05-02 13:38 UTC, alalazo approved these changes

2022-05-02 13:38 UTC, merged