valgrind package: added lto variant and configured arguments for cray, mpi
LLNL/spack pull request #30382
Opened 2022-04-28 20:28 UTC by francinelapid

2022-05-04 06:30 UTC, alalazo requested changes
You can use a conditional variant instead of a variant + conflict

2022-05-04 06:30 UTC, alalazo commented on var/spack/repos/builtin/packages/valgrind/package.py
> +            description='Activates link-time optimization for valgrind')
```suggestion
    variant('lto', default=False, when='@3.15:',
            description='Activates link-time optimization for valgrind')
```

2022-05-04 06:30 UTC, alalazo commented on var/spack/repos/builtin/packages/valgrind/package.py
> +              msg='Link-time Optimization only supported in 3.15.0 and above')
```suggestion
```

2022-05-05 16:39 UTC, alalazo commented on var/spack/repos/builtin/packages/valgrind/package.py
> +            env['SPACK_CC'] = "/opt/gcc/9.3.0/bin/gcc"
We should also avoid hard-coded paths.

2022-08-22 11:03 UTC, alalazo commented
@francinelapid Are you still working on this PR?

2022-08-22 17:00 UTC, francinelapid commented
Yes, I'm still working on this PR.

2023-02-20 18:25 UTC, alalazo commented
What is the status of this PR?

2023-10-09 16:05 UTC, alecbcs commented
Going to go ahead and close this PR due to a lack of response. @francinelapid happy to reopen if you're still working on this PR.

2023-10-09 16:05 UTC, closed without merging