namd: force the charmpp dependency version
LLNL/spack pull request #30397
Opened 2022-04-29 13:14 UTC by lpoirel

namd@2.14 does not build with charmpp@7

2022-04-29 13:18 UTC, lpoirel commented
no maintainers for namd package in spack, but based on the file history, I'll tag
@payerle @haampie @yellowhat

2022-05-04 06:17 UTC, alalazo requested changes

2022-05-04 06:17 UTC, alalazo commented on var/spack/repos/builtin/packages/namd/package.py
> +    depends_on('charmpp@6.10', when="@2.14:")
This includes `6.10.0` which was explicitly excluded before:
```suggestion
    depends_on('charmpp@6.10.1:6', when="@2.14:")
```

2022-05-04 11:57 UTC, alalazo approved these changes

2022-05-04 11:58 UTC, merged