oneapi 2022.2
LLNL/spack pull request #30531
Opened 2022-05-06 14:36 UTC by rscohn2

oneAPI 2022.2 release

Includes some updated descriptions and licensing information.

Testing is here: https://github.com/rscohn2/oneapi-spack-tests/actions/runs/2282150631

The __doc__ = is a little ugly, but it is the only way I found to make the 'spack info' descriptions include a common piece of license text.

2022-05-07 15:30 UTC, rscohn2 commented
@spackbot run pipeline

2022-05-09 12:51 UTC, rscohn2 commented
@alalazo : It looks like the force push you did resolved the testing error and now everything passes. vdanilin is no longer involved in the project and unavailable to review, so there is no one else at Intel to review. I tested and everything works ok, so this is ready to merge from my side.

2022-05-09 13:25 UTC, alalazo requested changes
An idea to avoid the `__doc__` hack.

2022-05-09 13:25 UTC, alalazo commented on lib/spack/spack/build_systems/oneapi.py
> +    and conditions of the software license agreements at https://intel.ly/393CijO."""
Can we turn this into a decorator:
```python
class IntelOneApiPackage(...)
    @staticmethod
    def license_footer(cls):
        cls.__doc__ = cls.__doc__ + license_text
        return cls
```
?

2022-05-09 13:25 UTC, alalazo commented on var/spack/repos/builtin/packages/intel-oneapi-advisor/package.py
>  class IntelOneapiAdvisor(IntelOneApiPackage):
Then we can use it like:
```suggestion
@IntelOneApiPackage.license_footer
class IntelOneapiAdvisor(IntelOneApiPackage):
```

2022-05-09 20:25 UTC, rscohn2 commented
> An idea to avoid the `__doc__` hack.

Great idea. It works well.

2022-05-10 05:24 UTC, alalazo approved these changes

2022-05-10 05:25 UTC, merged