update for py-elephant
LLNL/spack pull request #30613
Opened 2022-05-11 08:45 UTC by Moritz-Alexander-Kern

add new versions to py-elephant

2022-05-11 10:30 UTC, alalazo requested changes
```
PKG-DIRECTIVES: 2 issues found
1. py-elephant: dependency on py-neo@0.10.0: cannot be satisfied by known versions of py-neo
    happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/py-elephant/package.py
    known versions of py-neo are 0.8.0, 0.5.2, 0.4.1, 0.3.3
2. py-elephant: dependency on py-neo@0.[9](https://github.com/spack/spack/runs/6385190604?check_suite_focus=true#step:6:9).0 cannot be satisfied by known versions of py-neo
    happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/py-elephant/package.py
    known versions of py-neo are 0.8.0, 0.5.2, 0.4.1, 0.3.3
```

2022-05-11 16:36 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-elephant/package.py
>      variant('doc', default=False, description='Build the documentation')
```suggestion
    variant('docs', default=False, description='Install documentation dependencies')
```
This doesn't actually build the docs, it just makes sure the deps are installed. Also, let's call it `+docs` to match `pip install elephant[docs]`

2022-05-16 08:47 UTC, alalazo requested changes
```
PKG-DIRECTIVES: 3 issues found
1. py-elephant: wrong variant in "depends_on" directive
    the variant 'doc' does not exist
    in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/py-elephant/package.py
2. py-elephant: dependency on py-neo@0.10.0: cannot be satisfied by known versions of py-neo
    happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/py-elephant/package.py
    known versions of py-neo are 0.8.0, 0.5.2, 0.4.1, 0.3.3
3. py-elephant: dependency on py-neo@0.[9](https://github.com/spack/spack/runs/6401724866?check_suite_focus=true#step:6:9).0 cannot be satisfied by known versions of py-neo
    happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/py-elephant/package.py
    known versions of py-neo are 0.8.0, 0.5.2, 0.4.1, 0.3.3
```

2022-05-16 08:48 UTC, alalazo requested changes

2022-05-16 08:48 UTC, alalazo commented on var/spack/repos/builtin/packages/py-elephant/package.py
> +    depends_on('py-sphinx@1.2.2:', type=('build', 'run'), when='+doc')
```suggestion
    depends_on('py-numpydoc@0.5:', type=('build', 'run'), when='+docs')
    depends_on('py-sphinx@1.2.2:', type=('build', 'run'), when='+docs')
```

2022-06-28 17:37 UTC, adamjstewart requested changes

2022-06-28 17:37 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-elephant/package.py
> +    depends_on('py-sphinx@1.2.2:', type=('build', 'run'), when='+docs')
Looks like the docs requirements have changed in the latest release:
```
numpydoc>=1.1.0
jupyter>=1.0.0
sphinx>=3.3.0
nbsphinx>=0.8.0
sphinxcontrib-bibtex==1.0.0
sphinx-tabs>=1.3.0
matplotlib>=3.3.2
```

2022-06-29 07:53 UTC, Moritz-Alexander-Kern commented on var/spack/repos/builtin/packages/py-elephant/package.py
> +    depends_on('py-sphinx@1.2.2:', type=('build', 'run'), when='+docs')
see: https://github.com/spack/spack/pull/30613/commits/b1cc029016af2a2095a425fb4cfa672f7783f2c4

2022-06-29 17:54 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-elephant/package.py
> +    depends_on('py-sphinxcontrib-bibtex@1.0.0:', type=('build', 'run'), when='@0.7.0:+docs')
```suggestion
    depends_on('py-sphinxcontrib-bibtex@1.0.0', type=('build', 'run'), when='@0.7.0:+docs')
```

2022-06-29 17:54 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-elephant/package.py
> +    variant('extras', default=True, description='Build with extras for GPFA, ASSET', when='@0.6.4:')
Personally I would make this False by default. That would match the behavior of `pip install elephant` and minimize build times.

2022-06-30 14:37 UTC, Moritz-Alexander-Kern commented on var/spack/repos/builtin/packages/py-elephant/package.py
> +    variant('extras', default=True, description='Build with extras for GPFA, ASSET', when='@0.6.4:')
good point, see [6aeb825](https://github.com/spack/spack/pull/30613/commits/6aeb825282d9608baa37ef5cf68193fadbb04c8d)

2022-07-04 15:43 UTC, adamjstewart approved these changes

2022-07-05 06:59 UTC, alalazo approved these changes

2022-07-05 06:59 UTC, merged