[py-openslide-python] added verion 1.1.2
LLNL/spack pull request #30722
Opened 2022-05-18 13:50 UTC by qwertos

2022-05-18 16:43 UTC, tldahlgren approved these changes, later dismissed
Confirmed sha256.  Leaving merge decision to @adamjstewart

2022-05-18 20:41 UTC, adamjstewart requested changes

2022-05-18 20:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-openslide-python/package.py
>      depends_on('python@2.6:2.8,3.3:')
```suggestion
    depends_on('python@2.6:2.8,3.3:', type=('build', 'run'))
```
Presumably Python is also needed at run-time. May also be needed at link-time, you'll have to check

2022-05-18 20:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-openslide-python/package.py
> +    depends_on('py-setuptools',     type='build', when="@1.1.2")
```suggestion
    depends_on('py-setuptools',     type='build', when="@1.1.2:")
```

2022-05-18 20:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-openslide-python/package.py
>      depends_on('py-pillow-simd+jpeg+jpeg2000+tiff', type=('build', 'run'))
```suggestion
    depends_on('pil', type=('build', 'run'))
```
We have a virtual package for PIL that lets you choose between `py-pillow` and `py-pillow-simd`. The latter only builds on systems with SIMD, it doesn't work on Apple M1 for example. Unfortunately, virtual packages don't support variants yet.

2022-05-20 17:34 UTC, adamjstewart approved these changes

2022-05-20 19:25 UTC, merged