Kokkos SYCL AOT flags
LLNL/spack pull request #30723
Opened 2022-05-18 13:54 UTC by masterleinad

This pull request allows for specifying an Intel GPU architecture for the `SYCL` (and `OpenMPTarget` when added) backend to allow for AOT instead of JIT compilation.

2022-05-18 21:34 UTC, lucbv commented
@janciesko @crtrott 
Any issue with this? Otherwise it would be nice to get a review to merge it in and update our CI pipeline at ANL

2022-05-24 10:15 UTC, alalazo requested changes

2022-05-24 10:15 UTC, alalazo commented on var/spack/repos/builtin/packages/kokkos/package.py
> +                spack_microarches.append(arch)
If it is a single valued variant, we can avoid looping and just extract the value.

2022-05-25 18:31 UTC, crtrott approved these changes

2022-05-25 18:54 UTC, lucbv commented
@alalazo can you check the updated version?

2022-05-31 20:49 UTC, lucbv commented
@alalazo please review again, it's been updated last week already.

2022-06-01 18:16 UTC, lucbv commented
@tldahlgren any change you could look at this, I believe we have addressed the issue raised by @alalazo and we would like to use this new feature in our CI testing.

2022-06-01 18:40 UTC, tldahlgren approved these changes
LGTM.  Thanks for addressing @alalazo 's request.

2022-06-01 18:42 UTC, tldahlgren commented
Since @alalazo flagged as `Changes Requested`, he'll have to clear his review before this can be merged.

2022-06-06 13:41 UTC, alalazo approved these changes

2022-06-06 13:41 UTC, merged