Adjust CI workflows for Spack forks
LLNL/spack pull request #30729
Opened 2022-05-18 17:31 UTC by wyphan

Changes the following CI workflows such that they only run for the main repo `spack/spack`, or when it's not a scheduled task (e.g. a PR or manually triggered from Actions tab):
- Containers `workflows/build-containers.yml`
- MacOS builds nightly `workflows/macos_python.yml`
- Bootstrap `workflows/bootstrap.yml`

2022-05-19 12:47 UTC, alalazo requested changes
Similar modifications to `bootstrap.yaml` are missing.

2022-05-19 12:47 UTC, alalazo commented on .github/workflows/build-containers.yml
> +    if: github.action_repository == 'spack/spack' || github.event != 'schedule'
`github.action_repository` seems the wrong attribute. I'd also prefer to block this if not targeted at the main repo:
```suggestion
    if: github.repository == 'spack/spack'
```

2022-05-19 12:47 UTC, alalazo commented on .github/workflows/macos_python.yml
> +    if: github.action_repository == 'spack/spack' || github.event != 'schedule'
```suggestion
    if: github.repository == 'spack/spack'
```

2022-05-19 12:47 UTC, alalazo commented on .github/workflows/macos_python.yml
> +    if: github.action_repository == 'spack/spack' || github.event != 'schedule'
```suggestion
    if: github.repository == 'spack/spack'
```

2022-05-19 12:47 UTC, alalazo commented on .github/workflows/macos_python.yml
> +    if: github.action_repository == 'spack/spack' || github.event != 'schedule'
```suggestion
    if: github.repository == 'spack/spack'
```

2022-05-19 19:35 UTC, alalazo approved these changes

2022-05-19 19:35 UTC, merged

2022-05-25 03:03 UTC, adamjstewart commented
Can we also do this for dependabot? https://github.com/adamjstewart/spack/pulls?q=is%3Apr+is%3Aclosed