New package: py-pprintpp
LLNL/spack pull request #30764
Opened 2022-05-20 16:53 UTC by qwertos

2022-05-21 16:35 UTC, adamjstewart requested changes
Missing build dep on setuptools

2022-10-05 20:36 UTC, qwertos commented
@spackbot fix style

2022-10-06 02:44 UTC, adamjstewart approved these changes, later dismissed

2022-10-06 02:44 UTC, adamjstewart commented
@spackbot fix style

2022-10-06 07:46 UTC, alalazo approved these changes

2022-10-06 07:46 UTC, merged