New package: py-pytesseract
LLNL/spack pull request #30765
Opened 2022-05-20 16:59 UTC by qwertos

2022-05-21 16:34 UTC, adamjstewart requested changes

2022-05-21 16:34 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pytesseract/package.py
> +    """Python-tesseract is an Optical Charachter Recognition (OCR) Tool for python."""
```suggestion
    """Python-tesseract is an Optical Character Recognition (OCR) Tool for python."""
```

2022-05-21 16:34 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pytesseract/package.py
> +    depends_on('py-packaging', type=('build', 'run'))
Where do you see the packaging dep? I don't see it imported anywhere

2022-08-18 16:54 UTC, adamjstewart approved these changes, later dismissed

2022-09-08 14:04 UTC, qwertos commented
@spackbot fix style

2022-09-08 14:52 UTC, adamjstewart approved these changes

2022-09-08 15:24 UTC, merged