silo: Fix HDF5 1.13 API breakage
LLNL/spack pull request #30786
Opened 2022-05-23 15:22 UTC by chuckatkins

2022-05-23 21:19 UTC, kwryankrattiger submitted a review, later dismissed

2022-05-24 08:50 UTC, sethrj requested changes

2022-05-24 08:50 UTC, sethrj commented on var/spack/repos/builtin/packages/silo/package.py
> +    patch('hdf5-113.patch', when='@4.11:')
Make this conditional on the newer hdf5? Better not to patch code if we can help it

2022-05-24 12:46 UTC, sethrj commented on var/spack/repos/builtin/packages/silo/package.py
> +    patch('hdf5-113.patch', when='@4.11:')
(To clarify: if the patch is unconditional, it'll invalidate every current installation of silo.

```suggestion
    patch('hdf5-113.patch', when='@4.11: ^hdf5@1.13:')
```

2022-05-24 14:44 UTC, sethrj submitted a review, later dismissed
Thanks!

2022-05-24 15:07 UTC, chuckatkins commented
The updated patch just now removed some unrelated white space changes I accidentally let creep in.  I spoke with @brtnfld from The HDF Group and confirmed that this is a valid approach and works to address the API compatibility issues.  (We spoke directly but he also added his approval over on the upstream PR in https://github.com/LLNL/Silo/pull/260)

2022-05-24 15:22 UTC, kwryankrattiger approved these changes

2022-05-25 04:49 UTC, merged