wget: fixing compilation issue with gcc12 on rhel7
LLNL/spack pull request #30858
Opened 2022-05-25 21:30 UTC by snehring

gcc12's defaulting to c17 breaks compiling wget against older glibc versions with very helpful error messages such as:
```./string.h:1080:1: error: expected identifier or '(' before '__extension__'```. 

This is probably an issue with other older os versions beyond rhel/centos7, but I don't have any other hosts readily available to test against.

2022-05-26 17:01 UTC, snehring commented
Actually the std change was in 11, and indeed the issue exists with that version too.

2022-05-31 15:51 UTC, snehring commented
@spackbot run pipeline

2022-06-14 14:06 UTC, alalazo requested changes
LGTM, but can you add a comment at the beginning of the function, stating what you say in the description of the PR?

2022-06-14 15:19 UTC, alalazo approved these changes

2022-06-14 16:03 UTC, merged