No need of patch and hdf5 is optional for QE QMCPACK converter
LLNL/spack pull request #30884
Opened 2022-05-26 21:42 UTC by ye-luo

Reflect QE side of change in the current develop branch.

2022-06-02 14:50 UTC, danielecesarini submitted a review, later dismissed

2022-06-02 22:08 UTC, ye-luo commented
@spackbot run pipeline

2022-06-06 12:42 UTC, alalazo requested changes

2022-06-06 12:42 UTC, alalazo commented on var/spack/repos/builtin/packages/quantum-espresso/package.py
> +            depends_on('hdf5@1.8.16:+hl~mpi', when='hdf5=none')
I think this set of rules might be confusing. What does it mean that `quantum-espresso` depends on `hdf5` when the `hdf5=none` is the requested support?

2022-06-06 12:57 UTC, ye-luo commented on var/spack/repos/builtin/packages/quantum-espresso/package.py
> +            depends_on('hdf5@1.8.16:+hl~mpi', when='hdf5=none')
QE hdf5=none/serial/parallel refers to enable hdf5 related feature in QE.
However, when using QE doesn't use hdf5, its plugins may still carry dependency on hdf5 library.
QE hdf5 feature and dependencies are two separate concept.

2022-06-06 12:59 UTC, ye-luo commented on var/spack/repos/builtin/packages/quantum-espresso/package.py
> +            depends_on('hdf5@1.8.16:+hl~mpi', when='hdf5=none')
I can add a comment in the source to make it clear. @alalazo Do you have other suggestions?

2022-06-06 13:08 UTC, alalazo commented on var/spack/repos/builtin/packages/quantum-espresso/package.py
> +            depends_on('hdf5@1.8.16:+hl~mpi', when='hdf5=none')
> QE hdf5 feature and additional dependencies from plugins are two separate concepts.

I think we should clarify that in the variant somehow (maybe change the name or the description?). It's puzzling imho to have:
```
Builds with HDF5 support
```
as a description of the `hdf5` variant, select `hdf5=none` and still have a direct dependency from `quantum-espresso` to `hdf5`.

2022-06-06 13:23 UTC, ye-luo commented on var/spack/repos/builtin/packages/quantum-espresso/package.py
> +            depends_on('hdf5@1.8.16:+hl~mpi', when='hdf5=none')
Tends to avoid renaming the variant.
I updated the variant description and added a comment above the `depends_on` line.

2022-06-06 13:46 UTC, alalazo approved these changes

2022-06-06 13:47 UTC, merged