dbcsr: Add latest release and fix related issues
LLNL/spack pull request #30891
Opened 2022-05-27 08:16 UTC by w8jcik

2022-05-27 12:19 UTC, dev-zero submitted a review, later dismissed

2022-05-27 12:20 UTC, dev-zero commented
Not sure why testing is needed, though, can you elaborate please @w8jcik?

2022-05-27 12:58 UTC, w8jcik commented
> Not sure why testing is needed, though, can you elaborate please @w8jcik?

I am not sure what is the real reason, but without this flag CMake fails with following message

```
-- Found Python: /home/user/.spack/root/opt/spack/linux-ubuntu22.04-skylake/gcc-9.4.0/python-3.9.12-x4msfzae5cpz7r4ggq33caqlv72afasg/bin/python3.9 (found version "3.9.12") found components: Interpreter 
-- Found MPI_C: /home/user/.spack/root/opt/spack/linux-ubuntu22.04-skylake/gcc-9.4.0/openmpi-4.1.3-awkfuq5qz6p6oqwjnpa5trweop4iaika/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /home/user/.spack/root/opt/spack/linux-ubuntu22.04-skylake/gcc-9.4.0/openmpi-4.1.3-awkfuq5qz6p6oqwjnpa5trweop4iaika/lib/libmpi.so (found version "3.1") 
-- Found MPI_Fortran: /home/user/.spack/root/opt/spack/linux-ubuntu22.04-skylake/gcc-9.4.0/openmpi-4.1.3-awkfuq5qz6p6oqwjnpa5trweop4iaika/lib/libmpi_usempif08.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1") found components: C CXX Fortran 
-- Performing Test f2008-norm2
-- Performing Test f2008-norm2 - Success
-- Performing Test f2008-block_construct
-- Performing Test f2008-block_construct - Success
-- Performing Test f2008-contiguous
-- Performing Test f2008-contiguous - Success
-- Performing Test f95-reshape-order-allocatable
-- Performing Test f95-reshape-order-allocatable - Success
-- FYPP preprocessor found.
-- Configuring done
CMake Error at docs/CMakeLists.txt:17 (add_dependencies):
  The dependency target "doc_copy_tests" of target "doc" does not exist.


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Looks like some hidden dependency.

2022-05-29 18:19 UTC, w8jcik commented
@dev-zero The issue is quiet clear and here is a PR https://github.com/cp2k/dbcsr/pull/619

But we still need to handle releases 2.1 and 2.2. I have added a version-dependent fix. Is it fine?

2022-05-29 19:11 UTC, dev-zero commented
@w8jcik perfectly, yes! Thanks a lot for the fix for DBCSR itself!

2022-05-31 10:28 UTC, w8jcik commented
@dev-zero Thank you for merging the fix, but what with this Pull request? Are you concerned about something or can it be approved?

2022-05-31 11:02 UTC, dev-zero submitted a review, later dismissed

2022-05-31 11:02 UTC, dev-zero commented
sorry, I missed the dismissal of my previous review, all good from my side

2022-06-06 12:28 UTC, alalazo requested changes
One minor comment

2022-06-06 12:28 UTC, alalazo commented on var/spack/repos/builtin/packages/dbcsr/package.py
> +    depends_on('cmake@3.10:', type='build', when='@:2.0')
I think it's easier to reason in terms of increasing requests with increasing versions:
```suggestion
    depends_on('cmake@3.10:', type='build')
```

2022-06-14 13:07 UTC, alalazo approved these changes

2022-06-14 13:08 UTC, merged