New features: override version, detect git URLs, …
LLNL/spack pull request #30921
Opened 2022-05-30 10:02 UTC by iarspider

specify tags/branches/commits

2022-06-01 17:25 UTC, tldahlgren commented
Can you add unit tests related to the new functionality?  That will bring patch coverage up.  

Not sure if you can see it, but the diffs are at https://app.codecov.io/gh/spack/spack/compare/30921/diff.

2022-06-03 18:36 UTC, iarspider commented
@tldahlgren I hope codecov will be happy this time...

2022-06-09 12:16 UTC, iarspider commented
@tldahlgren gentle ping

2022-06-13 19:32 UTC, tldahlgren commented
> @tldahlgren gentle ping

IIRC I had brought some of these changes up quite a while ago so I'm pinging those who objected at the time to see if they are okay with this approach.

2022-06-13 19:32 UTC, tldahlgren commented
> @tldahlgren gentle ping

IIRC I had brought some of these changes up quite a while ago so I'm pinging those who objected at the time to see if they are okay with this approach.

2022-08-18 00:44 UTC, tldahlgren requested changes
The main issue is to not use space separation for multi-valued options.

2022-08-18 00:44 UTC, tldahlgren commented on lib/spack/spack/cmd/create.py
> +    git_line = "    git      = 'git@github.com:example/example.git'"
More than 99% of the packages that define the `git` property use the `https` protocol so this statement would be:

```suggestion
    git_line = "    git      = 'https://github.com/example/example.git'"
```

Of those that don't, the protocol is`ssh:` or

```suggestion
    git_line = "    git      = 'ssh://git@github.com/example/example.git'"
```

2022-08-18 00:44 UTC, tldahlgren commented on lib/spack/spack/cmd/create.py
> +        if git_url is not None:
Perhaps better to also not allow a blank string:

```suggestion
        if git_url:
```

2022-08-18 00:44 UTC, tldahlgren commented on lib/spack/spack/cmd/create.py
> +                           '    # git = git@example.com:example/example.git'
See suggested options for line 297.

2022-08-18 00:44 UTC, tldahlgren commented on lib/spack/spack/cmd/create.py
> +                                "Only used for git URLs.",
This guidance doesn't apply to the `tags` option:

```suggestion
                                "Separate multiple tags with space.",
```

2022-08-18 00:44 UTC, tldahlgren commented on lib/spack/spack/cmd/create.py
> +    subparser.add_argument('-T', '--tag',
Spack actually has a tag argument "standard" from `cmd/common/arguments.py`.  It is used in the following commands:

- `spack external`
- `spack find`

and added with

```
    spack.cmd.common.arguments.add_common_arguments(sub parser, ["tags"])
```

2022-08-18 00:44 UTC, tldahlgren commented on lib/spack/spack/cmd/create.py
> +                                "Separate multiple branches with space. "
Multiple `-B` (or `--branch`) options should be allowed in the same way we support `tags`.

An example where the space-separated approach doesn't work as expected:

```
$ spack create -n mpileaks-git -g https://github.com/LLNL/mpileaks.git -B master https://github.com/LLNL/mpileaks/releases/download/v1.0/mpileaks-1.0.tar.gz
```

2022-08-18 00:44 UTC, tldahlgren commented on lib/spack/spack/cmd/create.py
> +    subparser.add_argument('-C', '--commit',
This has the same problem as the other space-separated options.

2022-08-18 00:44 UTC, tldahlgren commented on lib/spack/spack/cmd/create.py
> +        return url, git
Would it be helpful to return the following (so the `url` is not the example?

```suggestion
        return args.url, git
```

2022-08-18 00:44 UTC, tldahlgren commented on lib/spack/spack/cmd/create.py
> +        args.branch is not None
This could be tightened:

```suggestion
    has_git_option = args.commit or args.tag or args.branch
```

2023-09-06 20:12 UTC, tldahlgren approved these changes

2023-11-12 08:51 UTC, closed without merging