[WIP] Add documentation about package signing model
LLNL/spack pull request #30939
Opened 2022-05-31 17:44 UTC by kotfic

This PR provides documentation for the current AWS based package signing approach and serves as part of a larger data integrity assurance case.

2022-06-01 17:40 UTC, scottwittenburg requested changes
Thanks @kotfic this is looking really great :tada: 

I've requested some minor changes, but the main issue might be that the docs build is failing.  There are a few places where double backtics are not closed, which might account for most of the doc build errors.  Also, this needs to be linked from somewhere in the table of contents or somewhere doesn't it? I think that's causing the final error.

Doc build errors:

```
/home/docs/checkouts/readthedocs.org/user_builds/spack/checkouts/30939/lib/spack/docs/signing.rst:307: WARNING: Inline literal start-string without end-string.
/home/docs/checkouts/readthedocs.org/user_builds/spack/checkouts/30939/lib/spack/docs/signing.rst:349: WARNING: Inline literal start-string without end-string.
/home/docs/checkouts/readthedocs.org/user_builds/spack/checkouts/30939/lib/spack/docs/signing.rst:427: WARNING: Inline literal start-string without end-string.
/home/docs/checkouts/readthedocs.org/user_builds/spack/checkouts/30939/lib/spack/docs/signing.rst:427: WARNING: Inline literal start-string without end-string.
/home/docs/checkouts/readthedocs.org/user_builds/spack/checkouts/30939/lib/spack/docs/signing.rst:427: WARNING: Inline literal start-string without end-string.
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/docs/checkouts/readthedocs.org/user_builds/spack/checkouts/30939/lib/spack/docs/signing.rst: WARNING: document isn't included in any toctree
```

2022-06-01 17:40 UTC, scottwittenburg commented on lib/spack/docs/signing.rst
> +and the final package may be signed by the SIgning Intermediate CI
`SIgning` -> `Signing`

2022-06-01 17:40 UTC, scottwittenburg commented on lib/spack/docs/signing.rst
> +issues new sub-keys for use in the pipeline. It is our expectation that this
`issues` -> `issue`

2022-06-01 17:40 UTC, scottwittenburg commented on lib/spack/docs/signing.rst
> +.. TODO: Table here
Does this `TODO` refer to the table below?  In that case can it be removed.  Otherwise, what table is planned here?

2022-06-01 17:40 UTC, scottwittenburg commented on lib/spack/docs/signing.rst
> +$ spack buildcache extract-spec (or similar, TBD)
I think we decided this was not needed.  But either way it's not implemented so I think removing this line and the one above makes sense.

2022-06-01 17:40 UTC, scottwittenburg commented on lib/spack/docs/signing.rst
> +zlib-1.2.12/
I think we should borrow from the nice description @tgamblin wrote for the buildcache PR (#30750).  Maybe the layout he provided under "New Format" in the PR description could just be reused here.

2022-06-01 17:40 UTC, scottwittenburg commented on lib/spack/docs/signing.rst
> +  **TODO**
Is this to be left `TODO` for the time being or completed before merging?

2022-06-01 17:40 UTC, scottwittenburg commented on lib/spack/docs/signing.rst
> +Kubernetes secret called ``spack-intermediate-ci-signing-key`. For
Missing a second backtic after `spack-intermediate-ci-signing-key`?

2022-06-01 17:40 UTC, scottwittenburg commented on lib/spack/docs/signing.rst
> +   pipeline namespace and mounts the spack-intermediate-ci-signing-key
Suggest backtics around `spack-intermediate-ci-signing-key` here.

2022-06-01 17:40 UTC, scottwittenburg commented on lib/spack/docs/signing.rst
> +(i.e. ``aws-encryption-cli`) to decrypt the Reputational Key. Permission
Second backtic missing after `aws-encryption-cli`?

2022-06-01 17:40 UTC, scottwittenburg commented on lib/spack/docs/signing.rst
> +In addition to protected runners there protected branches on the
`there protected` -> `there are protected`?

2022-06-01 17:40 UTC, scottwittenburg commented on lib/spack/docs/signing.rst
> +release branch (i.e. managed with the ``github/releases/v*`` wildcard).
We now push the branches from github directly to gitlab without first adding the `github/` prefix, so these branch names should be updated accordingly.

Additionally, we run pipelines protected tags, also defined with wildards in gitlab, to match the tag format spack uses (i.e. `v*`).

2022-06-01 17:40 UTC, scottwittenburg commented on lib/spack/docs/signing.rst
> +   branches. Because protected runners have access to secrets its
`secrets its` -> `secrets, it's`

2022-06-01 17:40 UTC, scottwittenburg commented on lib/spack/docs/signing.rst
> +   critical that they not run Jobs from the other (i.e. PR branches). If
`the other` -> `untrusted code`?

2022-06-01 17:40 UTC, scottwittenburg commented on lib/spack/docs/signing.rst
> +   pipeline originated from the ``generate`` job sets these tags. If the
`originated from` -> `originated,` ?

2022-06-03 15:12 UTC, kotfic commented on lib/spack/docs/signing.rst
> +zlib-1.2.12/
@scottwittenburg could you push a commit with that change?  i'm not as familiar with that PR or this section of the signing docs

2022-06-03 15:13 UTC, kotfic commented
This appears to be passing now except for a warning about not being included in any toctree. @tgamblin Where would you like this documentation linked from?  Thanks!

2022-06-10 01:31 UTC, scottwittenburg approved these changes, later dismissed

2023-02-15 09:09 UTC, alalazo commented
Is this PR just waiting for another review?

2023-02-15 16:44 UTC, scottwittenburg commented
> Is this PR just waiting for another review?

Also appears from a [comment](https://github.com/spack/spack/pull/30939#issuecomment-1146063367) above that @kotfic wanted to know where this should be linked from.

2023-02-15 17:09 UTC, alalazo commented
What about inserting it below the sections on CI pipelines? That seems the appropriate place to me since we would introduce CI pipelines first, and then explain how we are signing the buildcaches from our public pipelines. Does that seem fine?

2023-02-15 18:16 UTC, scottwittenburg commented
> What about inserting it below the sections on CI pipelines?

Yes, that makes sense to me.

2023-02-16 09:43 UTC, alalazo commented
@kotfic If you have time to push this forward, I'll try to prioritize review to it.

2023-06-07 09:50 UTC, alalazo commented
@scottwittenburg @zackgalbreath Can you double check if what is written here is still up to date? If so I'll take care of fixing the readthedocs failure and merge the PR.

2023-06-07 17:01 UTC, scottwittenburg commented
I just read through it again, and yes, this is still an accurate and complete description of our package signing model.

2023-06-07 17:02 UTC, alalazo commented
Thanks @scottwittenburg I'll try to merge this one asap then

2023-06-07 19:11 UTC, alalazo approved these changes

2023-06-07 21:05 UTC, merged