Add New Package:PSCMC
LLNL/spack pull request #30944
Opened 2022-06-01 02:08 UTC by Bitllion

2022-06-01 02:16 UTC, tldahlgren reviewed
Did you intend to include the `abacus` package here?  These changes are already in #30933

2022-06-01 02:25 UTC, Bitllion commented
> Did you intend to include the `abacus` package here? These changes are already in #30933

Sorry,This is a misunderstanding. 
I found a spack stytle errorr on abacus,
Reference to previous version：
`from spack import *`
I don't know when it was changed to this：
`from spack.package import *`
Now I have corrected the style error of the abacus branch, but the development branch is still wrong. Because the PSCM branch is just checked out from the development branch, it affects my pscmc branch

2022-06-02 20:30 UTC, tldahlgren requested changes
Please correct the ending copyright year.

2022-06-02 20:30 UTC, tldahlgren commented on var/spack/repos/builtin/packages/pscmc/package.py
> +# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```

2022-06-07 17:11 UTC, tldahlgren approved these changes

2022-06-07 17:11 UTC, merged