gmsh: +petsc requires ~int64 variant
LLNL/spack pull request #30969
Opened 2022-06-02 21:42 UTC by zzzoom

Building `gmsh +petsc ^petsc+int64` fails because `gmsh` assumes that `PetscInt` is an int:

```
  (...)/src/solver/linearSystemPETSc.hpp:57:38: error: cannot convert 'int*' to 'PetscInt*' {aka 'long long int*'}
```
 This PR changes the dependency on `gmsh +petsc` to `petsc~int64`.

2022-06-04 13:04 UTC, alalazo requested changes
I left a small suggestion. Let me know if that matches the semantic of this dependency.

2022-06-04 13:04 UTC, alalazo commented on var/spack/repos/builtin/packages/gmsh/package.py
> +    depends_on('petsc~int64', when='+petsc~mpi')
```suggestion
    with when('+petsc'):
        depends_on('pets~int64')
        depends_on('petsc+mpi', when='+mpi')
        depends_on('petsc~mpi', when='~mpi')
```

2022-06-06 20:12 UTC, zzzoom commented
@alalazo that works, I pushed a new commit with a small typo fix on your suggestion.

2022-06-06 20:52 UTC, alalazo approved these changes

2022-06-07 14:21 UTC, merged