Update prmon recipe, v3.0.2
LLNL/spack pull request #30979
Opened 2022-06-03 14:03 UTC by graeme-a-stewart

Update recipe to prmon v3.0.2, using the external dependency option for the build (as these are satisfied so easily with Spack).
Disable the plot variant by default, as it's rather a heavy dependency and independent of the core monitoring funcationality.

2022-06-03 15:58 UTC, tldahlgren approved these changes, later dismissed
Confirmed the sha256. Deferring merge decision to at least one package maintainer.

2022-06-04 09:31 UTC, vvolkl commented on var/spack/repos/builtin/packages/prmon/package.py
>      version('3.0.1', sha256='c4eea2849e52e501d42f8e3f837e3f250691f7e7912b7503d6ca0a0e417ea474')
```suggestion
```

2022-06-04 09:32 UTC, vvolkl requested changes
Tested and confirmed, thanks Graeme! I'd only suggest to remove v3.0.1, which never could be built with spack, as the recipe does not set up the submodules.

2022-06-06 18:23 UTC, tldahlgren commented on var/spack/repos/builtin/packages/prmon/package.py
>      version('3.0.1', sha256='c4eea2849e52e501d42f8e3f837e3f250691f7e7912b7503d6ca0a0e417ea474')
Great catch @vvolkl !

2022-06-06 18:29 UTC, tldahlgren reviewed
~Please correct the `sha256` for 3.0.1.~

2022-06-07 15:15 UTC, graeme-a-stewart commented
Thanks for that observation @vvolkl - I removed the broken 3.0.1 version now.

2022-06-07 15:57 UTC, vvolkl approved these changes

2022-06-07 16:31 UTC, tldahlgren approved these changes

2022-06-07 17:17 UTC, merged