meson: New version 0.62.2
LLNL/spack pull request #30995
Opened 2022-06-04 18:36 UTC by eschnett

2022-06-04 22:49 UTC, eschnett commented
@spackbot hello

2022-06-04 22:49 UTC, eschnett commented
@spackbot help

2022-06-04 22:50 UTC, eschnett commented
@spackbot run pipeline

2022-06-06 08:14 UTC, michaelkuhn commented
@spackbot run pipeline

2022-06-06 08:19 UTC, michaelkuhn requested changes

2022-06-06 08:19 UTC, michaelkuhn commented on var/spack/repos/builtin/packages/meson/package.py
> +    version('0.62.2', sha256='a7669e4c4110b06b743d57cc5d6432591a6677ef2402139fe4f3d42ac13380b0')
The checksum seems to be different for me. Yours seems to be from the actual release tarball, while the package downloads the autogenerated one. We can change to the proper tarballs but then you probably need to add a `url_for_version` function.
```
$ spack checksum meson 0.62.2       
==> Found 1 version of meson:
  
  0.62.2  https://github.com/mesonbuild/meson/archive/0.62.2.tar.gz

==> Fetching https://github.com/mesonbuild/meson/archive/0.62.2.tar.gz

    version('0.62.2', sha256='97108f4d9bb16bc758c44749bd25ec7d42c6a762961efbed8b7589a2a3551ea6')
```

2022-06-06 16:07 UTC, eschnett commented on var/spack/repos/builtin/packages/meson/package.py
> +    version('0.62.2', sha256='a7669e4c4110b06b743d57cc5d6432591a6677ef2402139fe4f3d42ac13380b0')
I followed Spack's guidance to add the new version (`spack checksum`). Could this lead to such an inconsistency? If I recall correctly, 

This package shouldn't need anything special. What is your recommendation here? What causes this problem? If I wanted to use a different checksum, how should I calculate it? If I wanted to add an `url_for_version`, what url should that be?

2022-06-06 16:56 UTC, eschnett commented
Superseded by https://github.com/spack/spack/pull/31005

2022-06-06 16:56 UTC, closed without merging