libaec: Update fetching url
LLNL/spack pull request #31020
Opened 2022-06-07 14:48 UTC by pab42

Fixes "Error: CommandNotFoundError: Cannot extract archive, unrecognized file extension: 'None' "

```
~> spack install libaec
[+] /dss/spack_original/opt/spack/linux-sles15-haswell/gcc-11.2.0/pkgconf-1.8.0-yqxzvyqv7lhwnq2acl55cyikozqgp4su
[+] /dss/spack_original/opt/spack/linux-sles15-haswell/gcc-11.2.0/berkeley-db-18.1.40-edodxkqiwox5e4tg2mvmhybt5apewhzf
[+] /dss/spack_original/opt/spack/linux-sles15-haswell/gcc-11.2.0/libiconv-1.16-wxsle6to5i3hjh2ftsdbfhvspclaqso2
[+] /dss/spack_original/opt/spack/linux-sles15-haswell/gcc-11.2.0/zlib-1.2.12-vzgxdgpqcp6m6ifh5so3i5vogvozke2h
[+] /dss/spack_original/opt/spack/linux-sles15-haswell/gcc-11.2.0/ncurses-6.2-vklfhfi77booblf2ldsjv2wegxob7g3f
[+] /dss/spack_original/opt/spack/linux-sles15-haswell/gcc-11.2.0/diffutils-3.8-w33kkr7hqs77o5nbxyrrmedygcphe32m
[+] /dss/spack_original/opt/spack/linux-sles15-haswell/gcc-11.2.0/readline-8.1-rkackfyyonhktztf3cq7aboz7kiispzc
[+] /dss/spack_original/opt/spack/linux-sles15-haswell/gcc-11.2.0/bzip2-1.0.8-2u3k4bs3am2324fkyhh2sar4w4odhcql
[+] /dss/spack_original/opt/spack/linux-sles15-haswell/gcc-11.2.0/gdbm-1.19-vrjlqrczcymdcffeq3us55o3yxilvmhu
[+] /dss/spack_original/opt/spack/linux-sles15-haswell/gcc-11.2.0/perl-5.34.1-tjrn4gt57hlnerznn2hqnqebrdikb4do
[+] /dss/spack_original/opt/spack/linux-sles15-haswell/gcc-11.2.0/openssl-1.1.1o-t73rgdcvju2vvdetaijgsj275gpvzv2j
[+] /dss/spack_original/opt/spack/linux-sles15-haswell/gcc-11.2.0/cmake-3.23.2-ldowipaajqg6syml3xrgyn3vqaxtyyae
==> Installing libaec-1.0.6-sxezmjpyedvhpdw2mr6tqxh36wdqw4gd
==> No binary for libaec-1.0.6-sxezmjpyedvhpdw2mr6tqxh36wdqw4gd found: installing from source
==> Using cached archive: /dss//spack_original/var/spack/cache/_source-cache/archive/ab/abab8c237d85c982bb4d6bde9b03c1f3d611dcacbd58bca55afac2496d61d4be.tar.gz
==> Error: CommandNotFoundError: Cannot extract archive, unrecognized file extension: 'None'

/dss/spack_original/lib/spack/spack/package_base.py:1570, in do_stage:
       1567
       1568        # Fetch/expand any associated code.
       1569        if self.has_code:
  >>   1570            self.do_fetch(mirror_only)
       1571            self.stage.expand_archive()
       1572
       1573            if not os.listdir(self.stage.path):
```

2022-06-07 16:21 UTC, tldahlgren requested changes

2022-06-07 16:21 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libaec/package.py
> +    url = 'https://gitlab.dkrz.de/k202009/libaec/-/archive/v1.0.6/libaec-v1.0.6.tar.gz'
Changes to the URL can affect version checksums which, in this case, it looks like it changes all of the checksums below:

```
    version('1.0.6', sha256='2675d26b24a081cdaaa48e0d085632e568e3f85f843f62b91fc51e1b3f5fe93f')
    version('1.0.5', sha256='563e3f9c614a6c848340eb070f01b4a915e9ebc8a67199254bf37712b92e24d3')
    version('1.0.4', sha256='7d85784afc0c4d82adae2d3a1ad2c0a9db700a49ad8f32674618b0089206cb5e')
    version('1.0.3', sha256='704e5b2d341c32606e21c01217100ec01e7cae05cdef5eeaf4c09ef5adb45583')
    version('1.0.2', sha256='c1aa0d6d8c070f5b1d65a42bc64334fbd69518ea38ab566fb52880bae6f1a72e')
    version('1.0.1', sha256='2495d80375817758a4f1e4b4f6b47a78a7c0d942b4f0899a87045537b0627b56')
    version('1.0.0', sha256='7f25e48a305db75427a3ff426c5f0d489821be5a533c08f3bf503522f674685f')
```

2022-06-08 07:17 UTC, pab42 commented
Thanks for pointing this out. It is even worse, most of them are then identical :-( Only 1.0.6 is correct from both URLs:
```
abab8c237d85c982bb4d6bde9b03c1f3d611dcacbd58bca55afac2496d61d4be  libaec-v1.0.0.tar.gz
abab8c237d85c982bb4d6bde9b03c1f3d611dcacbd58bca55afac2496d61d4be  libaec-v1.0.1.tar.gz
abab8c237d85c982bb4d6bde9b03c1f3d611dcacbd58bca55afac2496d61d4be  libaec-v1.0.2.tar.gz
abab8c237d85c982bb4d6bde9b03c1f3d611dcacbd58bca55afac2496d61d4be  libaec-v1.0.3.tar.gz
abab8c237d85c982bb4d6bde9b03c1f3d611dcacbd58bca55afac2496d61d4be  libaec-v1.0.4.tar.gz
abab8c237d85c982bb4d6bde9b03c1f3d611dcacbd58bca55afac2496d61d4be  libaec-v1.0.5.tar.gz
2675d26b24a081cdaaa48e0d085632e568e3f85f843f62b91fc51e1b3f5fe93f  libaec-v1.0.6.tar.gz
```
But the origin of the error was fixed in #31027

2022-06-08 07:17 UTC, closed without merging

2022-06-08 18:28 UTC, tldahlgren commented
> Thanks for pointing this out. It is even worse, most of them are then identical :-( Only 1.0.6 is correct from both URLs:
> 
> ```
> abab8c237d85c982bb4d6bde9b03c1f3d611dcacbd58bca55afac2496d61d4be  libaec-v1.0.0.tar.gz
> abab8c237d85c982bb4d6bde9b03c1f3d611dcacbd58bca55afac2496d61d4be  libaec-v1.0.1.tar.gz
> abab8c237d85c982bb4d6bde9b03c1f3d611dcacbd58bca55afac2496d61d4be  libaec-v1.0.2.tar.gz
> abab8c237d85c982bb4d6bde9b03c1f3d611dcacbd58bca55afac2496d61d4be  libaec-v1.0.3.tar.gz
> abab8c237d85c982bb4d6bde9b03c1f3d611dcacbd58bca55afac2496d61d4be  libaec-v1.0.4.tar.gz
> abab8c237d85c982bb4d6bde9b03c1f3d611dcacbd58bca55afac2496d61d4be  libaec-v1.0.5.tar.gz
> 2675d26b24a081cdaaa48e0d085632e568e3f85f843f62b91fc51e1b3f5fe93f  libaec-v1.0.6.tar.gz
> ```
> 
> But the origin of the error was fixed in #31027

Interesting.  The sha256 values I suggested were from running `spack checksum libaec` on the versions after fetching and checking out your PR branch.