gemma: Adding new package.
LLNL/spack pull request #31078
Opened 2022-06-09 18:08 UTC by dlkuehn

Adding a new package : gemma.
Current version           :  0.98.5

Description:  GEMMA is a software toolkit for fast application of linear mixed models (LMMs) and related models to genome-wide association studies (GWAS) and other large-scale data sets.

2022-06-09 21:17 UTC, snehring approved these changes, later dismissed
Checksum checks out. Installs with gcc 12.1 on my workstation and my rhel7 build container.

2022-06-13 13:43 UTC, alalazo requested changes
One question

2022-06-13 13:43 UTC, alalazo commented on var/spack/repos/builtin/packages/gemma/package.py
> +    depends_on('openblas')
Only `openblas`? Or can we:
```suggestion
    depends_on('lapack')
```
?

2022-06-13 16:08 UTC, snehring commented on var/spack/repos/builtin/packages/gemma/package.py
> +    depends_on('openblas')
It has switches in the makefile to maybe make it work with atlas. Other blas/lapack implementations seem to result in linking errors due to specifying -latlas when openblas isn't specified.

2022-06-13 16:10 UTC, alalazo commented on var/spack/repos/builtin/packages/gemma/package.py
> +    depends_on('openblas')
Thanks, can you either write that in a comment above the `depends_on` or see if we can make it work with other lapack implementations?

2022-06-13 16:49 UTC, snehring commented on var/spack/repos/builtin/packages/gemma/package.py
> +    depends_on('openblas')
The logic in the makefile is very simple, but it requires that the lapack implementor have literal clblas, lapack, and blas libraries, which many don't. netlib's libraries do, but mkl doesn't for instance.

2022-06-13 18:08 UTC, alalazo approved these changes

2022-06-14 12:53 UTC, merged