New packages: py-ford and dependencies
LLNL/spack pull request #31107
Opened 2022-06-13 13:07 UTC by lizzyd710

This PR adds the Ford documentation framework along with necessary dependencies that didn't already have spack packages:

- [ford](https://github.com/Fortran-FOSS-Programmers/ford) by @Fortran-FOSS-Programmers / @cmacmackin 
- [python-markdown-math](https://github.com/mitya57/python-markdown-math) by @mitya57
- [markdown-include](https://github.com/cmacmackin/markdown-include) by @cmacmackin 
- [md-environ](https://github.com/cmacmackin/md-environ) by @cmacmackin 

Leaving this as a draft PR until I get the maintainers squared away for the packages. In the meantime, for the tagged creators of these libraries/packages, please indicate if you are willing to be tagged as a maintainer for these spack packages.

2022-06-13 14:11 UTC, lizzyd710 commented
Are there certain workflows missing from the repo that the checks are trying to find? The logs mention some files that are supposed to be in [github-actions-v0.2](https://github.com/spack/spack/tree/f72c2ab583cf904773010e875683423f58386262/share/spack/bootstrap/github-actions-v0.2) (linking to the directory at the last commit at the time of writing this) but in my fork and the upstream, it doesn't exist.

2022-06-13 19:28 UTC, tldahlgren commented
FWIW. The failing style checks (aside from some odd sort issues) are:

```
==> Running flake8 checks
[207](https://github.com/spack/spack/runs/6868076623?check_suite_focus=true#step:6:208)
==> Error: spack style found errors
[208](https://github.com/spack/spack/runs/6868076623?check_suite_focus=true#step:6:209)
var/spack/repos/builtin/packages/py-ford/package.py:12: [E501] line too long (117 > 88 characters)
[209](https://github.com/spack/spack/runs/6868076623?check_suite_focus=true#step:6:210)
var/spack/repos/builtin/packages/py-markdown-include/package.py:12: [E501] line too long (162 > 88 characters)
[210](https://github.com/spack/spack/runs/6868076623?check_suite_focus=true#step:6:211)
var/spack/repos/builtin/packages/py-markdown-include/package.py:21: [W293] blank line contains whitespace
[211](https://github.com/spack/spack/runs/6868076623?check_suite_focus=true#step:6:212)
var/spack/repos/builtin/packages/py-md-environ/package.py:12: [E501] line too long (108 > 88 characters)
```

2022-06-14 13:20 UTC, lizzyd710 commented
Is the import statement being flagged in the style check just a result of some weirdness happening behind the scenes, or do I actually have to change it? I just used what was given when I ran `spack create`

2022-06-14 14:24 UTC, tldahlgren commented
> Is the import statement being flagged in the style check just a result of some weirdness happening behind the scenes, or do I actually have to change it? I just used what was given when I ran `spack create`

Unfortunately, it has to be changed to pass the check. That command provides a template with things that need to be filled in or removed.  If it's off then that needs to be adjusted.  (I'll take a look.)

2022-06-14 14:27 UTC, lizzyd710 commented
From the output of the GitHub action I can't really tell what change I need to make--do you have an example of what a correct import placement would look like? I thought it looked fine since I checked other packages and it looked similar, but maybe I missed something.

2022-06-14 14:46 UTC, tldahlgren commented
> From the output of the GitHub action I can't really tell what change I need to make--do you have an example of what a correct import placement would look like? I thought it looked fine since I checked other packages and it looked similar, but maybe I missed something.

`isort` doesn't like the comment line containing the dash to appear before the `import`.  The most consistent fix is to simply remove it.  Most packages also retain only a single blank line between the License Identifier comment and the first import.

2022-06-14 14:53 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-ford/package.py
> +
```suggestion
```

2022-06-14 14:54 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-ford/package.py
> +
Suggest removing this comment and have one blank line between the License Identifier comment and first import.

2022-06-14 18:37 UTC, lizzyd710 commented
I can't tell why it's failing these tests. The only thing that I can understand is the line that says it can't find the package `py-markdown-include`, despite it being added in this PR. Any insight or help as to what is going wrong would be appreciated, because when I run `spack unit-test` locally I get a slew of different errors that don't show up here.

2022-06-14 18:42 UTC, tldahlgren commented
The python 2.7 checks remind me of some failures yesterday that were fixed.  Can you rebase to develop?  (One option is to click the `Update branch` here but then you'll have to `git pull` if you make any more local changes.)

2022-06-14 18:42 UTC, tldahlgren commented
The reason you're seeing your new packages in tests is that they are automatically pulled into some existing unit tests.

2022-06-14 19:10 UTC, tldahlgren commented
@adamjstewart @alalazo Do either of you know why this PR is having problems with the unit tests (esp. 2.7)?

2022-06-14 19:14 UTC, adamjstewart commented
No idea, but I'm seeing the same issue in #30916 so I would also love to know why.

2022-06-14 19:15 UTC, adamjstewart commented
P.S. Remind me to review the Python packages before this is merged.

2022-06-14 19:19 UTC, tldahlgren commented
> P.S. Remind me to review the Python packages before this is merged.

Just added you as a reviewer.  That should help. 😉

2022-06-15 14:13 UTC, lizzyd710 commented
Would it help if I split this PR into separate ones, one for each package introduced? Could that be causing an issue, at least for the Linux test? (I still have no idea about the unicode decoding failure on the windows test)

(Sorry to be so pushy about this--this is for work and it's the last step before I can actually do my assigned task.)

2022-06-15 20:00 UTC, lizzyd710 commented
> No idea, but I'm seeing the same issue in #30916 so I would also love to know why.

For some reason, the py-markdown-include package.py was in a UTF-8 charset when all my other package files were in ASCII. When I fixed it (see latest commit) then everything worked fine.

2022-06-15 20:33 UTC, tldahlgren submitted a review, later dismissed
LGTM.  Deferring merge decision until @adamjstewart has a chance to review and, preferably, at least @wscullin.

2022-06-16 00:46 UTC, adamjstewart requested changes

2022-06-16 00:46 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ford/package.py
> +    depends_on('py-setuptools-scm@4:5', type='build')
```suggestion
    depends_on('py-setuptools-scm@4:5+toml', type='build')
```

2022-06-16 00:46 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ford/package.py
> +    depends_on('py-importlib-metadata', type=('build', 'run'))
```suggestion
    depends_on('py-importlib-metadata', when='^python@:3.7', type=('build', 'run'))
```

2022-06-16 00:46 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ford/package.py
> +    depends_on('py-pytest@3.3.0:', type='test')
This package has no tests other than the import tests, so this dep can be removed

2022-06-16 16:57 UTC, tldahlgren approved these changes
Re-confirmed sha256.  Deferring merge until @adamjstewart has a chance to revisit.

2022-06-16 19:14 UTC, adamjstewart approved these changes

2022-06-16 19:14 UTC, merged