Build static libs by default
LLNL/spack pull request #31163
Opened 2022-06-16 11:47 UTC by haralmha

Enabling both static and shared libs in clang13 leads to this error:
```
     908    /usr/bin/ld: ./interface/.libs/libgolem95_interface.a(tool_lt_to_golem.o): unable to initialize decompress status for section .debug_info
     909    /usr/bin/ld: ./interface/.libs/libgolem95_interface.a(tool_lt_to_golem.o): unable to initialize decompress status for section .debug_info
     910    ./interface/.libs/libgolem95_interface.a: member ./interface/.libs/libgolem95_interface.a(tool_lt_to_golem.o) in archive is not an object
  >> 911    clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```

2022-06-16 12:06 UTC, vvolkl commented
Title suggestion: "gosam-contrib: build static libs by default"

2022-06-16 18:12 UTC, iarspider commented
@haralmha @vvolkl how are these two related? Could it be a conflict/issue with clang13?

2022-06-17 07:29 UTC, alalazo requested changes
I would investigate this error, rather than change the default.

2022-06-17 11:29 UTC, haralmha commented
Thanks for the suggestions, I investigated further and it turned out to be an issue with my clang13 setup.. Closing

2022-06-17 11:29 UTC, closed without merging