Cray manifest: compiler duplicates
LLNL/spack pull request #31173
Opened 2022-06-17 01:22 UTC by scheibelp

`spack external read-cray-manifest` was adding duplicate compiler definitions to the configuration. This could happen if:

* The manifest files contain duplicate compiler definitions
* You run `spack external read-cray-manifest` on the same file multiple times

This adds a filtering operation for that, and also updates the tests.

2022-06-28 06:17 UTC, tgamblin approved these changes

2022-06-28 06:18 UTC, tgamblin requested changes
needs rebase

2022-06-29 22:26 UTC, scheibelp commented
@tgamblin the conflicts are now resolved

2022-06-30 00:05 UTC, tgamblin approved these changes

2022-06-30 00:05 UTC, merged