[lammps] Update md5sum for version 20201029
LLNL/spack pull request #31177
Opened 2022-06-17 11:48 UTC by stephenmsachs

2022-06-20 08:34 UTC, alalazo requested changes
Confirmed the new sha256:
```console
$ spack checksum lammps 20201029
==> Found 1 version of lammps:
  
  20201029  https://github.com/lammps/lammps/archive/patch_29Oct2020.tar.gz

==> Fetching https://github.com/lammps/lammps/archive/patch_29Oct2020.tar.gz

    version('20201029', sha256='3d347f6b512bc360505019d1c6183c969a2e1da402e31a1e26577daf5e419d95')
```
@stephenmsachs Do you have any idea why we have this change?

2022-06-20 09:21 UTC, stephenmsachs commented
> 



> @stephenmsachs Do you have any idea why we have this change?

Nope, no clue why.

2022-06-30 13:20 UTC, alalazo approved these changes

2022-06-30 13:20 UTC, alalazo commented on var/spack/repos/builtin/packages/lammps/package.py
> +    version('20201029', sha256='3d347f6b512bc360505019d1c6183c969a2e1da402e31a1e26577daf5e419d95')
Mystery solved, somebody used the stable release (as opposed to the patch release we seem to use):
```console
$ wget https://github.com/lammps/lammps/archive/refs/tags/stable_29Oct2020.tar.gz
[ ... ]
$ sha256sum stable_29Oct2020.tar.gz 
759705e16c1fedd6aa6e07d028cc0c78d73c76b76736668420946a74050c3726  stable_29Oct2020.tar.gz
```

2022-06-30 13:21 UTC, merged