Stricter compatibility rules for OS and compiler when reusing specs
LLNL/spack pull request #31170
Opened 2022-06-16 17:29 UTC by alalazo

fixes #31169

Modifications:
- [x] Add compatibility rules for operating systems
- [x] Facts to feed compatibility rules for OS are in a separate `os_facts.lp` file
- [x] Allow, for the time being, to use only compilers that are available
- [x] Add unit tests

2022-06-16 17:34 UTC, alalazo commented
In a follow up PR we could relax the requirements on compilers, and allow e.g. GCC@X to be compatible with GCC@Y if Y > X (so if I have Y on the system I can install binaries compiled with X). This is deferred because it involves:
- Reworking the installation from buildcache, to avoid requiring having the compiler available
- Change the compiler facts, because otherwise versions emitted as strings will be compared lexicographically

2022-06-17 14:25 UTC, chuckatkins commented on lib/spack/spack/solver/os_facts.lp
> +os_compatible("ubuntu18.10", "ubuntu18.04").
Is this also the place where we would put compatibility entries for `rhel` with `almalinux`, `rockylinux` and `centos`?

2022-06-17 16:16 UTC, alalazo commented on lib/spack/spack/solver/os_facts.lp
> +os_compatible("ubuntu18.10", "ubuntu18.04").
Yes, that is the idea

2022-06-21 00:30 UTC, tgamblin requested changes
LGTM save for one really minor change.

2022-06-21 00:30 UTC, tgamblin commented on lib/spack/spack/solver/os_facts.lp
> +os_compatible("ubuntu18.10", "ubuntu18.04").
Can we call this `os_compatibility.lp`?

2022-06-21 00:30 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> +        self.control.load(os.path.join(parent_dir, "os_facts.lp"))
os_compatibility.lp

2022-06-21 00:31 UTC, tgamblin approved these changes

2022-06-21 00:31 UTC, tgamblin commented
Merging as I think it's better to rename the file later than to leave this out longer.

2022-06-21 00:32 UTC, merged

2022-06-21 00:33 UTC, tgamblin commented
@alalazo can you also work on the follow-up PR?