[lammps] Adding new CMake package names
LLNL/spack pull request #31181
Opened 2022-06-17 14:56 UTC by stephenmsachs

This is a workaround that includes new and old package names. 

I currently do not see any ideal solution. You could look at every release which package names are the valid ones, but then the spack user would need to change their `variant` specifiers depending on Lammps version.

Another solution would be to have Spack translate package names. Then the question remains whether the old or new ones should be used as `variant` specifiers in Spack.

The full list of changes (with release dates) can be found here:
https://github.com/lammps/lammps/commits/patch_7Jan2022/cmake/presets/all_on.cmake

2022-06-20 08:27 UTC, alalazo requested changes
> I currently do not see any ideal solution. You could look at every release which package names are the valid ones, but then the spack user would need to change their variant specifiers depending on Lammps version.

I think we can use [conditional variant values](https://spack.readthedocs.io/en/latest/packaging_guide.html#conditional-possible-values) to model this properly.

2022-06-20 13:30 UTC, stephenmsachs commented
Hi @alalazo.  I don't think we can use conditional variants here as the packages need to be destinguishable from other variants when adding the to the CMake line. I picked all the updated package names apart and put them into three buckets (new/old/unchanged). I am having trouble extending `supported_packages` based on the version number (marked as TODO). Can you give me a hand here? I am sure this is a one-liner, but I just don't see it.

2022-06-20 13:53 UTC, alalazo commented
> Hi @alalazo. I don't think we can use conditional variants here as the packages need to be destinguishable from other variants when adding the to the CMake line. 

Can you elaborate on that (I am not super-familiar with lammps)? What is preventing us from e.g. using a single multi-valued variant and either:
1. Map a value in the variant to different CMake options depending on the version, or
2. Have conditional values exposed to users in the multi-valued variant
?

2022-06-20 14:01 UTC, stephenmsachs commented
> Can you elaborate on that (I am not super-familiar with lammps)? What is preventing us from e.g. using a single multi-valued variant and either:

I am not either. I just read through the `CmakeList.txt` and saw the changes in their github repo. We could use a single multi-valued variant but this would break existing lammps specs which use one variant per Cmake package.

> 
>     1. Map a value in the variant to different CMake options depending on the version, or
We could also do this, but (again not breaking existing specs) we would be stuck with the 'old' package names (e.g. `user-omp` instead of the now used `openmp`).
> 
>     2. Have conditional values exposed to users in the multi-valued variant
I don't fully understand this approach, but multi-valued variants would again break existing specs.

2022-06-28 09:45 UTC, alalazo commented
@junghans @payerle This LGTM, but I'm definitely not an expert on lammps. Do you have further comments? Otherwise I'll go on merging the PR.

2022-06-29 02:23 UTC, junghans commented
Duplicate of #25015

2023-02-16 20:56 UTC, rbberger commented
@alalazo with #34011 now merged, should we close this one?

2023-02-17 04:28 UTC, closed without merging