"spack external find": handle manifest with bad permissions
LLNL/spack pull request #31201
Opened 2022-06-20 21:14 UTC by scheibelp

Allow 'spack external find' (with no extra args) to proceed if the manifest file exists but without sufficient permissions; in that case, print a warning.

2022-06-21 17:35 UTC, scheibelp commented
I'm going to update this to skip all manifest errors, and also I'll update to allow the old schema (which uses `version` instead of `schema-version`.

2022-06-22 03:53 UTC, scheibelp commented
> I'm going to update this to skip all manifest errors, and also I'll update to allow the old schema (which uses version instead of schema-version.

That is also handled now

2022-06-22 04:44 UTC, scheibelp commented
@spackbot run pipeline

2022-06-22 18:02 UTC, scheibelp commented
Close/reopen to restart tests

2022-06-27 16:34 UTC, tgamblin requested changes

2022-06-27 16:34 UTC, tgamblin commented on lib/spack/spack/cmd/external.py
> +                         .format(skip_msg))
really minor: can you just make `skip_msg` the second argument?  That'll print out a slightly indented second line instead of a really long first line.

2022-06-27 16:34 UTC, tgamblin commented on lib/spack/spack/cmd/external.py
> +                         .format(str(e), skip_msg))
same here

2022-06-27 18:59 UTC, tgamblin approved these changes

2022-06-27 19:26 UTC, merged