vtk-m: update to latest release
LLNL/spack pull request #31220
Opened 2022-06-21 19:40 UTC by vicentebolea

Finally! After a quiet spring, VTK-m v1.8.0 is finally out :tada: :tada: :tada:

This bring exiting new features, and bugfixes, find the tentative release notes at https://gitlab.kitware.com/vtk/vtk-m/-/blob/master/docs/changelog/1.8/release-notes.md

Let me know if we need to change anything else in the package

ViB

2022-06-21 19:47 UTC, kmorel submitted a review, later dismissed
Looks good to me.

2022-06-22 01:19 UTC, tldahlgren reviewed
Confirmed sha256 for the new version.

Not sure if a rebase to develop will fix the `meson` issue or if that is internal.  There are 3 CI stacks that are failing at least the one I checked appears in relation to `vtk-m`.

2022-06-22 15:56 UTC, tldahlgren commented
A rebase to `develop` should fix the package-audits checks failure since the PR that addressed that problem was merged about 9 hours ago.

2022-06-29 16:19 UTC, kwryankrattiger commented
@vicentebolea Does this also need to have a constraint on the ROCm version that works with 1.8? I think I remember you saying there was a version that it needed, but I could be wrong.

2022-06-29 16:28 UTC, vicentebolea commented
@kwryankrattiger yes, 4.3 and 4.5 works but with high memory usage and long building times 8 hours. 5.1 works the best with much lower memory usage and building times.

2022-06-29 16:49 UTC, kwryankrattiger commented
Would it make sense to constrain the VTK-m build to `when='^hip@5.1:'` then? I feel like it may make sense to constrain this since it sounds like the older versions are not as useful/stable.

2022-06-29 16:51 UTC, vicentebolea commented
@kwryankrattiger sure, all of the ecp machines I tries the have support for 5.1 already :sunglasses:

2022-06-29 19:24 UTC, vicentebolea commented
I accidentally closed this while commenting :facepalm:

2022-06-29 19:31 UTC, tldahlgren approved these changes, later dismissed
Re-confirmed sha256.

2022-07-05 09:15 UTC, alalazo requested changes
Can you check the build error in the pipelines?

2022-07-05 15:27 UTC, kwryankrattiger commented
@vicentebolea It looks like vtk-m 1.8 has breaking API changes down stream. Can you also update those packages to require `@1.7:1.7`

2022-07-05 21:46 UTC, vicentebolea commented
Contributors of edited packages in this pull-request. Does your package breaks with vtk-m 1.8, if not please let me know so that I can remove the change from your package.

2022-07-06 15:03 UTC, kwryankrattiger commented on var/spack/repos/builtin/packages/ecp-data-vis-sdk/package.py
> -    dav_sdk_depends_on('vtk-m@1.7:+shared+mpi+openmp+rendering',
Leave this I think, we want to be able to build a vtk-m 1.8 with ROCm if ascent is turned off.

2022-07-12 20:02 UTC, kwryankrattiger approved these changes

2022-07-12 21:18 UTC, tldahlgren commented
@alalazo Looks like your review is blocking the merge of this PR

2022-07-13 07:21 UTC, alalazo approved these changes

2022-07-13 07:21 UTC, merged