py-cryptography@3.4.7 depends on openssl@1.1:
LLNL/spack pull request #31251
Opened 2022-06-23 00:33 UTC by rblake-llnl

This is a problem on older RHEL systems where the system openssl is 1.0.2. In these cases, you need to pin py-cryptography to 3.2.1 or go through the hassle of rebuilding openssl.

2022-06-23 00:44 UTC, adamjstewart requested changes

2022-06-23 00:44 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cryptography/package.py
> +    depends_on('openssl@1.1:', when='@3.4:')
Looking at the CHANGELOG, it seems like this should be:

* openssl 1.1.0+ for 3.2+
* openssl 1.0.2+ for 2.9+
* openssl 1.0.1+ for 1.7+
* openssl 1.0.0+ for 1.4+

2022-06-23 00:46 UTC, rblake-llnl commented
Hmm, 1.0.2 just built with py-cryptography here.  I’ll investigate.


From: "Adam J. Stewart" ***@***.***>
Reply-To: spack/spack ***@***.***>
Date: Wednesday, June 22, 2022 at 5:44 PM
To: spack/spack ***@***.***>
Cc: Robert Blake ***@***.***>, Author ***@***.***>
Subject: Re: [spack/spack] ***@***.*** depends on ***@***.***: (PR #31251)


@adamjstewart requested changes on this pull request.

________________________________

In var/spack/repos/builtin/packages/py-cryptography/package.py<https://urldefense.us/v3/__https:/github.com/spack/spack/pull/31251*discussion_r904423888__;Iw!!G2kpM7uM-TzIFchu!gmM5FfVE5jUGJw5kIgEGFfClV4Y6GAauyjlyTRa3F2jDfjnl8rG7VGijDquLKUAFuw$>:

> @@ -45,6 +45,8 @@ class PyCryptography(PythonPackage):

     depends_on('py-enum34',             type=('build', 'run'), when='^python@:3.4')

     depends_on('py-ipaddress',          type=('build', 'run'), when='^python@:3.3')

     depends_on('openssl@:1.0', when='@:1.8.1')

+    ***@***.***:', ***@***.***:')

+    ***@***.***:', ***@***.***:')

Looking at the CHANGELOG, it seems like this should be:

  *   openssl 1.1.0+ for 3.2+
  *   openssl 1.0.2+ for 2.9+
  *   openssl 1.0.1+ for 1.7+
  *   openssl 1.0.0+ for 1.4+

—
Reply to this email directly, view it on GitHub<https://urldefense.us/v3/__https:/github.com/spack/spack/pull/31251*pullrequestreview-1016205608__;Iw!!G2kpM7uM-TzIFchu!gmM5FfVE5jUGJw5kIgEGFfClV4Y6GAauyjlyTRa3F2jDfjnl8rG7VGijDqvT_k_0Qw$>, or unsubscribe<https://urldefense.us/v3/__https:/github.com/notifications/unsubscribe-auth/AF4TU5NAAGJYOLT3MJT2UZDVQOXPTANCNFSM5ZSNQZGA__;!!G2kpM7uM-TzIFchu!gmM5FfVE5jUGJw5kIgEGFfClV4Y6GAauyjlyTRa3F2jDfjnl8rG7VGijDqvVOG4COw$>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-10-09 16:01 UTC, alecbcs commented
@rblake-llnl is this PR still relevant? Or has this been fixed somewhere else?

2024-02-17 22:19 UTC, alecbcs commented
Going to close this PR due to a lack of response after review feedback. @rblake-llnl happy to reopen if you still want to get this merged and have time to work on it.

2024-02-17 22:19 UTC, closed without merging