perl: `chmod u+x Configure` before trying to run it
LLNL/spack pull request #31257
Opened 2022-06-23 06:23 UTC by blue42u

Inspired by https://github.com/spack/spack/pull/30342, fixes https://github.com/spack/spack/issues/31104.

2022-06-24 09:21 UTC, alalazo commented
@glennpj Would you have time to look at this one?

2022-06-26 18:35 UTC, glennpj commented
I am not seeing the behavior described in #31104.
```console
$ spack stage perl@5.34.0
$ ls -l $(spack location --source-dir perl@5.34.0)/Configure
-r-xr-xr-x 1 gpjohnsn gpjohnsn 592942 May  4  2021 /tmp/gpjohnsn/spack-stage/spack-stage-perl-5.34.0-223ttffgvvfx66jjnwcbcgvkwwop3xzd/spack-src/Configure
```
```console
$ spack stage perl@5.34.1
$ ls -l $(spack location --source-dir perl@5.34.1)/Configure
-r-xr-xr-x 1 gpjohnsn gpjohnsn 592942 Feb 19 06:16 /tmp/gpjohnsn/spack-stage/spack-stage-perl-5.34.1-s6evfmzb73txotq6kwj75p3zyyvbimoa/spack-src/Configure
```

It seems like there must be something else going on and that should probably identified.

2022-06-27 11:33 UTC, alalazo requested changes
I think we should get to the bottom of https://github.com/spack/spack/pull/31257#issuecomment-1166610981 before merging

2022-06-28 00:51 UTC, glennpj commented
Well, I do not think spack modifies anything during staging but just in case, here is the Configure file as it appears in the tarball.
```console
$ less $(spack location --stage-dir perl@5.34.1)/perl-5.34.1.tar.gz | grep Configure
-r-xr-xr-x steve/steve     592942 2022-02-19 06:16 perl-5.34.1/Configure
```

@blue42u Are you seeing different results?

2022-06-28 04:27 UTC, blue42u commented
@glennpj I see the same, and expanding the tarfile manually gives the correct permissions:
```console
# tar tvaf $(spack location --stage-dir perl@5.34.1)/perl-5.34.1.tar.gz | grep Configure
-r-xr-xr-x steve/steve     592942 2022-02-19 12:16 perl-5.34.1/Configure
# tar xaf $(spack location --stage-dir perl@5.34.1)/perl-5.34.1.tar.gz                 
tar: perl-5.34.1/.dir-locals.el: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: perl-5.34.1/.editorconfig: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: perl-5.34.1/.lgtm.yml: Cannot change ownership to uid 197609, gid 197609: Invalid argument
... similar errors ...
tar: Exiting with failure status due to previous errors
# ls -l perl-5.34.1/Configure 
-r-xr-xr-x 1 root root 592942 Feb 19 12:16 perl-5.34.1/Configure
# ls -l $(spack location --stage-dir perl@5.34.1)/spack-src/Configure
-rw-r--r-- 1 root root 592942 Jun 28 04:19 /tmp/root/spack-stage/spack-stage-perl-5.34.1-72vdqpcdw7vujrgobnjczz5wunyblgin/spack-src/Configure
```

2022-07-11 19:02 UTC, blue42u commented
Proper solution to this issue implemented in #31524.

2022-07-11 19:02 UTC, closed without merging