py-gtdbtk: new package
LLNL/spack pull request #31268
Opened 2022-06-23 16:01 UTC by luke-dt

2022-06-23 22:40 UTC, tldahlgren submitted a review, later dismissed
Confirmed sha256.  Deferring merge decision until @adamjstewart has a chance to comment on `py-gtdbtk`.

2022-06-23 22:40 UTC, tldahlgren commented on var/spack/repos/builtin/packages/fastani/package.py
> +# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```

2022-06-23 22:40 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-gtdbtk/package.py
> +# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```

2022-06-23 22:41 UTC, tldahlgren reviewed
Oops.  The copyright year has to be fixed first.

2022-06-23 22:57 UTC, tldahlgren approved these changes, later dismissed

2022-06-24 04:14 UTC, adamjstewart requested changes

2022-06-24 04:14 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-gtdbtk/package.py
> +    depends_on('python@3.6:', type=('build', 'run'))
Needs a build dep on setuptools

2022-06-24 14:49 UTC, adamjstewart approved these changes

2022-06-24 14:49 UTC, merged