ampt: add new package
LLNL/spack pull request #31307
Opened 2022-06-26 16:03 UTC by vvolkl

2022-06-27 13:20 UTC, alalazo requested changes

2022-06-27 13:20 UTC, alalazo commented on var/spack/repos/builtin/packages/ampt/package.py
> +    version('v2.26t9', sha256='d90e2e5a88f93baec69bc56d67ed8e35dc243fd1e5104e551e8d7e69fd09716a')
Would it be possible to simplify the version scheme used? For instance omit the "v" and have "t9" after a dash? Also what are the two versions in the URL (there's also `v1.26t9b`)?

2022-06-27 21:36 UTC, vvolkl commented on var/spack/repos/builtin/packages/ampt/package.py
> +    version('v2.26t9', sha256='d90e2e5a88f93baec69bc56d67ed8e35dc243fd1e5104e551e8d7e69fd09716a')
I'd prefer to keep the version as is, for continuity with previous non-spack builds (https://lcginfo.cern.ch/pkgver/ampt/2.26t9b_atlas/) Although I just notice that I still have to add the atlas patch.

According to the website, the v1 series uses the default model, the v2 series a model with string melting, but they are always packaged together, so I think just using the v2 as version string is ok.

2022-06-28 07:47 UTC, alalazo requested changes
I think I spotted a typo, but otherwise LGTM

2022-06-28 07:47 UTC, alalazo commented on var/spack/repos/builtin/packages/ampt/package.py
> +          when='@2.26t9b_atlas')
```suggestion
          when='@2.26-t9b_atlas')
```

2022-06-28 07:50 UTC, vvolkl commented on var/spack/repos/builtin/packages/ampt/package.py
> +          when='@2.26t9b_atlas')
Good catch, thanks!

2022-06-28 07:55 UTC, alalazo approved these changes

2022-06-28 08:46 UTC, merged