oracle-instant-client: add macOS conflict
LLNL/spack pull request #31301
Opened 2022-06-25 23:09 UTC by adamjstewart

Doesn't have M1 support yet so I didn't bother to add downloads/installs for macOS, but hopefully someday we will have them.

2022-06-27 13:58 UTC, alalazo requested changes
Does it make sense to restrict the constraint as in the suggestion?

2022-06-27 13:58 UTC, alalazo commented on var/spack/repos/builtin/packages/oracle-instant-client/package.py
> +    conflicts('platform=darwin')
```suggestion
    conflicts('platform=darwin target=aarch64:')
```

2022-06-27 15:58 UTC, adamjstewart commented on var/spack/repos/builtin/packages/oracle-instant-client/package.py
> +    conflicts('platform=darwin')
Until someone adds URLs for macOS x86_64, x86_64 and aarch64 are both not supported.

2022-06-28 08:14 UTC, alalazo approved these changes

2022-06-28 08:15 UTC, alalazo commented
@spackbot run pipeline

2022-06-28 08:21 UTC, merged