Add libfabric versions 1.15.0 and 1.15.1
LLNL/spack pull request #31314
Opened 2022-06-27 08:25 UTC by teojgo

2022-06-27 08:37 UTC, haampie requested changes

2022-06-27 08:37 UTC, haampie commented on var/spack/repos/builtin/packages/libfabric/package.py
> +               'opx',
```suggestion
               conditional('opx', when='@1.15.0:'),
```

2022-06-27 08:37 UTC, haampie commented on var/spack/repos/builtin/packages/libfabric/package.py
> +
```suggestion
```

2022-06-27 08:37 UTC, haampie commented on var/spack/repos/builtin/packages/libfabric/package.py
> +
and line 107, somehow github doesn't pick it up

2022-06-27 08:45 UTC, haampie commented on var/spack/repos/builtin/packages/libfabric/package.py
> +               'opx',
```suggestion
```

2022-06-27 08:46 UTC, haampie approved these changes

2022-06-27 12:35 UTC, alalazo commented
@spackbot run pipeline

2022-06-27 16:13 UTC, raghupazl approved these changes

2022-06-27 16:13 UTC, rajachan approved these changes

2022-06-27 16:59 UTC, alalazo commented
@spackbot run pipeline

2022-06-27 18:05 UTC, haampie commented
the gitlab failure is legit

```python
==> [2022-06-27-17:17:17.041971] Error: TypeError: can only concatenate str (not "_ConditionalVariantValues") to str
/builds/spack/spack/var/spack/repos/builtin/packages/libfabric/package.py:125, in configure_args:
        122            args.append('--with-kdreg=no')
        123
        124        for fabric in self.fabrics:
  >>    125            if 'fabrics=' + fabric in self.spec:
        126                args.append('--enable-{0}=yes'.format(fabric))
        127            else:
        128                args.append('--enable-{0}=no'.format(fabric))
See build log for details:
```

2023-02-20 19:02 UTC, alalazo requested changes

2023-02-20 19:02 UTC, alalazo commented on var/spack/repos/builtin/packages/libfabric/package.py
> +    version('1.15.0', sha256='70982c58eadeeb5b1ddb28413fd645e40b206618b56fbb2b18ab1e7f607c9bea')
These have been merged already to `develop`

2023-02-21 15:11 UTC, teojgo commented
The suggested versions are already added in the develop branch

2023-02-21 15:11 UTC, closed without merging