py-luigi: add v3.1.0
LLNL/spack pull request #31320
Opened 2022-06-27 16:37 UTC by genric

2022-06-27 16:42 UTC, tldahlgren approved these changes, later dismissed
LGTM.  Confirmed both new sha256.  Will defer merge until @adamjstewart has a chance to comment.

2022-06-28 02:06 UTC, adamjstewart requested changes

2022-06-28 02:06 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-tenacity/package.py
>      depends_on('py-setuptools-scm', type='build')
```suggestion
    depends_on('py-setuptools@21:',     type='build')
    depends_on('py-setuptools-scm@3.4:+toml', type='build')
```
From `pyproject.toml`

2022-06-28 06:50 UTC, genric commented on var/spack/repos/builtin/packages/py-tenacity/package.py
>      depends_on('py-setuptools-scm', type='build')
done

2022-06-28 14:37 UTC, adamjstewart approved these changes

2022-06-28 14:37 UTC, merged