py-cmseq: new package
LLNL/spack pull request #31375
Opened 2022-06-29 19:54 UTC by luke-dt

2022-06-29 23:43 UTC, tldahlgren requested changes
Copyright year needs to be corrected.

Confirmed the sha256.  

Will defer python-related feedback to @adamjstewart if he is interested in commenting.

2022-06-29 23:43 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-cmseq/package.py
> +# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```

2022-06-30 05:16 UTC, adamjstewart requested changes

2022-06-30 05:16 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cmseq/package.py
> +       consensus. Used as a dependency for py-metaphlan."""
```suggestion
       consensus."""
```
This package could be a dependency of many other packages, no need to mention this.

2022-06-30 05:16 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cmseq/package.py
> +    url      = "https://github.com/SegataLab/cmseq/archive/refs/tags/1.0.4.tar.gz"
Let's instead download from PyPI, see https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#pypi-vs-github

2022-06-30 05:16 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cmseq/package.py
> +    depends_on('py-biopython@:1.76')
Missing deps on scipy and bcbio-gff. These all need to be `type=('build', 'run')`

2022-06-30 17:43 UTC, adamjstewart approved these changes

2022-06-30 17:58 UTC, tldahlgren approved these changes

2022-06-30 17:58 UTC, merged