bdsim: add new package
LLNL/spack pull request #31384
Opened 2022-06-30 07:11 UTC by vvolkl

2022-06-30 07:12 UTC, vvolkl commented on var/spack/repos/builtin/bdsim/package.py
> +from spack import *
```suggestion
from spack.package import *
```

2022-06-30 07:13 UTC, vvolkl commented on var/spack/repos/builtin/bdsim/package.py
> +    maintainers = ['ganis']
```suggestion
    maintainers = ['gganis']
```

2022-06-30 07:33 UTC, vvolkl commented on var/spack/repos/builtin/bdsim/package.py
> +       to simulate both the transport of particles in an accelerator and their
```suggestion
       to simulate both the transport of particles in an accelerator and their
```

2022-07-05 09:06 UTC, alalazo requested changes
The package is in the wrong folder. It should be:
```console
var/spack/repos/builtin/packages//bdsim
```

2022-07-05 09:52 UTC, vvolkl commented
Oh, good catch, my bad copying this from another recipe repo. Thanks!

2022-07-05 10:29 UTC, alalazo approved these changes

2022-07-05 10:30 UTC, merged