Hi, this PR adds option for enabling thread support to fujitsu-fftw.
LLNL/spack pull request #31426
Opened 2022-07-04 09:01 UTC by otsukay

2022-07-05 07:13 UTC, alalazo requested changes

2022-07-05 07:13 UTC, alalazo commented on var/spack/repos/builtin/packages/fujitsu-fftw/package.py
> +    variant('threads', default=True, description="Enable thread support")
How do `openmp` and `threads` play with each other? Is it possible to have `~threads+openmp`?

2022-08-22 09:12 UTC, alalazo commented on var/spack/repos/builtin/packages/fujitsu-fftw/package.py
> +    variant('threads', default=True, description="Enable thread support")
@otsukay

2022-08-23 02:33 UTC, otsukay commented on var/spack/repos/builtin/packages/fujitsu-fftw/package.py
> +    variant('threads', default=True, description="Enable thread support")
@alalazo  I am very sorry that I forgot to reply to your comment, and thank you for the reminder. 
These two options, `opnemp` and `threads`, can be specified independently. I confirmed that it is possible to build the code in four ways `{+,~}openmp{+,~}threads`.

2022-08-23 06:51 UTC, alalazo commented on var/spack/repos/builtin/packages/fujitsu-fftw/package.py
> +    variant('threads', default=True, description="Enable thread support")
No worries, thanks for the reply!

2022-08-23 06:52 UTC, alalazo commented
@spackbot fix style

2022-08-24 09:36 UTC, alalazo approved these changes

2022-08-24 09:36 UTC, merged