m4 fixes %intel@19 build failure.
LLNL/spack pull request #31424
Opened 2022-07-04 01:28 UTC by rountree

Fixes #31423.

Sets up a conflict for %intel@19 and provides a commented-out
fix that allows a user to point the Intel compiler to a more
recent version of gcc.

2022-07-05 07:17 UTC, alalazo requested changes
I don't think this is the right way to do it. I acknowledge that currently we have limitations in modeling compilers like Intel (that depend on other compilers) properly, but the flag you suggest here should be set consistently in `compilers.yaml` to avoid using different GCC versions for different nodes.

2022-07-05 23:25 UTC, rountree commented
@alalazo That would be a better place for the flag to land.  How are you thinking of informing the user that this needs to happen?  A per-package conflict for the affected Intel versions with a message to see the package file for an explanation?  (I hope you have a better idea; there are lots of packages that are affected.)

2022-08-22 09:18 UTC, alalazo commented
@rountree Would you agree closing this and similar PRs, and continue the discussion in #31255? Asking since I am aware we don't have a clear solution yet for informing users that they encountered this issue (while _if they know what the issue is_ they can solve it with additional configuration in `compilers.yaml`)

2022-08-22 17:04 UTC, rountree commented
@alalazo That's fine.
Closing to focus conversation in #31255

2022-08-22 17:04 UTC, closed without merging

2024-05-09 16:58 UTC, markyoder commented
Summarizing what is implied above, I fix this problem (on our HPC platform) with a `module load gcc/12.1`, which is 1) the compiler used to build intel-oneapi-compilers (I think....) and 2) a newer compiler. This is one of many cases where the Intel compilers are difficult to use on CentOS, and other systems with a dinosaur of a "core" GCC (gcc@4.8.5 for CentOS-7).