Add checksum for py-pylint 2.14.4
LLNL/spack pull request #31436
Opened 2022-07-05 11:56 UTC by iarspider

2022-07-05 16:54 UTC, tldahlgren approved these changes, later dismissed
Confirmed sha256.  Delaying merge until @adamjstewart has a chance to comment.

2022-07-05 17:03 UTC, adamjstewart requested changes

2022-07-05 17:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pylint/package.py
>      depends_on('py-astroid@2.5.6:2.6', type=('build', 'run'), when='@2.8.0:2.10')
Missing the following deps:
```
        tomlkit>=0.10.1
python_requires = >=3.7.2
```

2022-07-06 06:51 UTC, iarspider commented on var/spack/repos/builtin/packages/py-pylint/package.py
>      depends_on('py-astroid@2.5.6:2.6', type=('build', 'run'), when='@2.8.0:2.10')
@adamjstewart thanks

2022-07-06 16:58 UTC, adamjstewart approved these changes

2022-07-06 16:58 UTC, merged