Add checksum for py-lazy-object-proxy 1.7.0 and 1.7.1
LLNL/spack pull request #31435
Opened 2022-07-05 11:15 UTC by iarspider

2022-07-05 16:49 UTC, tldahlgren approved these changes, later dismissed
Confirmed sha256.  Will defer merge decision until @adamjstewart has a chance to comment.

2022-07-05 17:05 UTC, adamjstewart requested changes

2022-07-05 17:05 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-lazy-object-proxy/package.py
>      depends_on('python@2.7:2.8,3.6:', type=('build', 'run'), when='@1.6.0:')
Python 3.6+ is required now

2022-07-06 17:06 UTC, adamjstewart approved these changes

2022-07-06 17:06 UTC, merged