py-panaroo: new package
LLNL/spack pull request #31452
Opened 2022-07-06 00:31 UTC by luke-dt

2022-07-06 01:28 UTC, tldahlgren commented
There are some dependencies missing.  According to the unit tests, the following should be dependencies:  `py-edlib`, `py-intbitset`, and `py-sklearn`.

2022-07-07 20:16 UTC, adamjstewart requested changes

2022-07-07 20:16 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-sklearn/package.py
> +class PySklearn(PythonPackage):
`sklearn` has been renamed to `scikit-learn`: https://pypi.org/project/sklearn/

You should use `scikit-learn` instead.

2022-07-07 20:38 UTC, luke-dt commented on var/spack/repos/builtin/packages/py-sklearn/package.py
> +class PySklearn(PythonPackage):
Yes, the developer of Panaroo probably should do that. Unfortunately for me, the depreciated sklearn is listed as a requirement in the panaroo setup.py.

It looks like it's only used for supplemental post-processing visualization (making a MDS plot):
https://github.com/gtonkinhill/panaroo/search?q=sklearn

2022-07-07 21:08 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-sklearn/package.py
> +class PySklearn(PythonPackage):
I would still use `depends_on('py-scikit-learn')`. Even if the name is different, the imports are the same, so it should work properly with the new package dependency.

2022-07-07 22:29 UTC, luke-dt commented on var/spack/repos/builtin/packages/py-sklearn/package.py
> +class PySklearn(PythonPackage):
I didn't know if would just work, that's great! Re-built and confirmed that it functions on my local machine.

2022-07-07 23:22 UTC, adamjstewart requested changes

2022-07-07 23:22 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-intbitset/package.py
> +    depends_on('python@3.Z:',     type=('build', 'run'))
This line can be removed, they seem to support Python 2 and the Z doesn't mean anything here

2022-07-07 23:22 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-intbitset/package.py
> +    depends_on('py-pytest-xdist', type=('build'))
I don't see anything to suggest that pytest is required, these lines can be removed

2022-07-07 23:54 UTC, adamjstewart approved these changes

2022-07-08 00:13 UTC, merged