lammps package: added fftw_precision variant
LLNL/spack pull request #31459
Opened 2022-07-06 09:12 UTC by marcodelapierre

Adds `fftw_precision` variant, to enable choosing between `single` and `double` precision, as per https://docs.lammps.org/Build_settings.html#fft-library .

This is an important build option when using the `kspace` package. In fact, the resulting trade-off between performance and accuracy can become a significant factor for many simulation setups.

2022-07-06 10:43 UTC, marcodelapierre commented
@alalazo one more commit for the Lammps recipe, with a new useful variant (for an old feature)

2022-07-07 14:46 UTC, alalazo requested changes
If I understand the package logic correctly, the new variant probably needs to be conditional

2022-07-07 14:46 UTC, alalazo commented on var/spack/repos/builtin/packages/lammps/package.py
> +    variant('fftw_precision', default='double',
```suggestion
    variant('fftw_precision', default='double', when='+kspace',
```

2022-07-07 14:46 UTC, alalazo commented on var/spack/repos/builtin/packages/lammps/package.py
> +            if spec.variants['fftw_precision'].value == 'single':
```suggestion
            if spec.satisfies('fftw_precision=single'):
```

2022-07-08 02:33 UTC, marcodelapierre commented on var/spack/repos/builtin/packages/lammps/package.py
> +    variant('fftw_precision', default='double',
Addressed and tested in new commit

2022-07-08 02:33 UTC, marcodelapierre commented on var/spack/repos/builtin/packages/lammps/package.py
> +            if spec.variants['fftw_precision'].value == 'single':
Addressed and tested in new commit

2022-07-08 02:34 UTC, marcodelapierre commented
Thanks for the review @alalazo , I have implemented (and tested) your comments in the new commit.

2022-07-12 14:14 UTC, alalazo approved these changes

2022-07-12 14:15 UTC, merged