file_cache.py: don't error on double delete (from multiple processes)
LLNL/spack pull request #31477
Opened 2022-07-07 14:00 UTC by haampie

Closes #31475

- file_cache.py: test double delete succeeds
- file_cache.py: allow FileNotFoundError on double delete

2022-07-07 14:13 UTC, alalazo requested changes

2022-07-07 14:13 UTC, alalazo commented on lib/spack/spack/util/file_cache.py
> +            except FileNotFoundError:
If only we supported Python >= 3.6 :sweat:

2022-07-08 09:37 UTC, haampie commented
With this PR, the following would save `hello` with the contents `second` without erroring (since the file is persisted only at the end of the write transaction).

```python
#!/usr/bin/env spack-python

from spack.util.file_cache import FileCache

cache = FileCache(".")

with cache.write_transaction("hello") as (old, new):
    new.write("first\n")

with cache.write_transaction("hello") as (old, new):
    new.write("second\n")
    cache.remove("hello")
    cache.remove("hello")
```

On `develop`, it would error out because `cache.remove` tries to delete a lock that's in use.

2022-07-12 13:03 UTC, alalazo requested changes
Just a minor comment, but otherwise LGTM

2022-07-12 13:03 UTC, alalazo commented on lib/spack/spack/test/util/file_cache.py
> +def test_delete_is_idempotent(file_cache):
```suggestion
@pytest.mark.regression('31475')
def test_delete_is_idempotent(file_cache):
```

2022-07-12 13:45 UTC, alalazo approved these changes

2022-07-12 13:52 UTC, haampie commented
Should probably be backported too

2022-07-12 15:03 UTC, merged