clp and osi depend on pkg-config
LLNL/spack pull request #31505
Opened 2022-07-09 07:31 UTC by vmiheer

2023-02-20 20:12 UTC, alalazo requested changes
`pkg-config` is usually a build dependency

2023-02-20 20:12 UTC, alalazo commented on var/spack/repos/builtin/packages/clp/package.py
> +    depends_on('pkg-config')
```suggestion
    depends_on("pkg-config", type="build")
```

2023-02-20 20:12 UTC, alalazo commented on var/spack/repos/builtin/packages/osi/package.py
> +    depends_on('pkg-config')
```suggestion
    depends_on("pkg-config", type="build")
```

2023-02-21 09:07 UTC, alalazo commented
Can you also resolve the conflicts?

2023-02-22 08:05 UTC, alalazo approved these changes, later dismissed

2023-02-22 09:05 UTC, haampie requested changes, later dismissed
pkgconfig is the provider, pkg-config and pkgconf the implementations.

2023-02-22 09:05 UTC, haampie commented on var/spack/repos/builtin/packages/clp/package.py
> +    depends_on("pkg-config", type="build")
```suggestion
    depends_on("pkgconfig", type="build")
```

2023-02-22 09:05 UTC, haampie commented on var/spack/repos/builtin/packages/osi/package.py
> +    depends_on("pkg-config", type="build")
```suggestion
    depends_on("pkgconfig", type="build")
```

2023-03-01 13:31 UTC, alalazo approved these changes

2023-06-24 13:34 UTC, merged

2023-06-26 04:26 UTC, vmiheer commented
Thank you, @alalazo!!!