Cfdem: new package
LLNL/spack pull request #31536
Opened 2022-07-12 07:45 UTC by iWangJiaxiang

> Thanks for bringing order to HPC software chaos. My organization have been using Spack since 2019 and thanks to Spack we could make software management in order without pain. During this period, we have extended Spack and now we are bringing them back to community. May our contributions be a small step in the great leap of HPC softwawre development.

This PR adds [CFDEM](https://www.cfdem.com/) package, which is kind of complex to deploy. This work took months to analyze the installation requirement and finally make everything clear. Hope the next time deploying CFDEM is one line command powered by Spack!

2022-07-12 09:12 UTC, alalazo requested changes

2022-07-12 09:12 UTC, alalazo commented on var/spack/repos/builtin/packages/cfdem/package.py
> +    """
Can you remove non-standard characters, like the `®` from the docstring description?

2022-07-12 09:12 UTC, alalazo commented on var/spack/repos/builtin/packages/cfdem/package.py
> +   # lagrangian/cfdemParticle/cfdTools/versionInfo.H in source code.
The indentation seems wrong here

2022-07-12 09:12 UTC, alalazo commented on var/spack/repos/builtin/packages/cfdem/package.py
> +    depends_on('openfoam-org@5.0',when="@3.8.0")
(minor) Are the versions of `openfoam-org` really pinned? If we can use a version range it would be better.

2022-07-12 09:12 UTC, alalazo commented on var/spack/repos/builtin/packages/cfdem/package.py
> +    phases = ['edit','build', 'install']
Please don't declare custom phases in packages. In this particular case, for instance, it seems `edit` is never used, and `build` can be merged with `install`.

2022-07-12 09:12 UTC, alalazo commented on var/spack/repos/builtin/packages/cfdem/package.py
> +        if self.spec['openfoam-org'].version == Version("5.0"):
Minor suggestion:
```suggestion
        if self.spec['openfoam-org'].satisfies("@5.0"):
```

2022-07-12 09:12 UTC, alalazo commented on var/spack/repos/builtin/packages/cfdem/package.py
> +        elif self.spec['openfoam-org'].version == Version("3.0.1"):
```suggestion
        elif self.spec['openfoam-org'].satisfies("@3.0.1"):
```

2022-07-12 09:12 UTC, alalazo commented on var/spack/repos/builtin/packages/cfdem/package.py
> +                f.write('\n')
We shouldn't be writing to any file during a call to setup the environment variables. Also, not sure if the hard-coded relative path is safe at all here.

2022-07-12 09:12 UTC, alalazo commented on var/spack/repos/builtin/packages/cfdem/package.py
> +        script()
Where is the script defined at build time? Is it different than the one that is written at run time?

2022-08-22 08:57 UTC, alalazo commented
@spackbot fix style

2022-08-22 09:06 UTC, alalazo commented
@iWangJiaxiang Do you plan to continue working on this PR?

2022-08-24 02:26 UTC, iWangJiaxiang commented on var/spack/repos/builtin/packages/cfdem/package.py
> +    depends_on('openfoam-org@5.0',when="@3.8.0")
It is really pinned according to the official CFDEM docs.

The dependent softwares are deeply coupled by the version s.

2022-08-24 02:26 UTC, iWangJiaxiang commented
Sure thing! Working on it.

2022-10-21 06:35 UTC, iWangJiaxiang commented on var/spack/repos/builtin/packages/cfdem/package.py
> +    """
Sure. Fixed.

2022-10-21 07:21 UTC, iWangJiaxiang commented on var/spack/repos/builtin/packages/cfdem/package.py
> +                f.write('\n')
Is there any built-in way to `source` env script and load to build time env?

2023-02-20 20:20 UTC, alalazo commented
Since this one depends on #31535 Let's merge the other one first and get back to this

2024-01-31 17:21 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2024-01-31 17:21 UTC, closed without merging