Add/packages nextflow tower
LLNL/spack pull request #31539
Opened 2022-07-12 14:46 UTC by marcodelapierre

This PR adds recipes for two very useful, official utilities that complement the Nextflow workflow manager:
* Tower Agent: https://github.com/seqeralabs/tower-agent
* Tower CLI: https://github.com/seqeralabs/tower-cli

On the side, I also added the most recent stable version of Nextflow in the corresponding recipe.

2022-07-12 14:47 UTC, marcodelapierre commented
@pditommaso any comment on the Spack recipes for Tower Agent and CLI? I hope they can be useful to the wider Nextflow community!

2022-07-12 15:24 UTC, pditommaso commented
Umm, we are making distribution releases via https://jreleaser.org/ which has no support for it, and I have to say I have no experience with Spack. 

Maybe you want to contribute it?

2022-07-12 16:00 UTC, marcodelapierre commented
Yes @pditommaso! So, the recipes I am providing in this PR make TW Agent and CLI available to install within the Spack package manager, which is quite popular across many HPC centres worldwide. It is very powerful for deploying both centralised and user-only installations of collections of scientific software.

The recipes I have made make use of the binary releases that are available on the Github repos of the two tools. Other than the binaries, do you think there are other components that need downloading, or general purposes configurations that need to be set? I don't think so, but I wanted to double-check with you.
At this stage, I don't think there are further integrations that are possible with Jreleaser (but thanks for mentioning the tool).

2022-07-12 16:18 UTC, pditommaso commented
Awesome! I got confused, I was thinking it was a ticket in the tower CLI repo! 

> Other than the binaries, do you think there are other components that need downloading, or general purposes configurations that need to be set?

The binaries are self-contained. Therefore should not be needed anything else.

2022-07-12 23:02 UTC, dialvarezs commented
Do tower-cli and tower-agent work on other architectures aside from x86? Because with these recipes, spack will try to install the packages on any architecture.

2022-07-13 01:54 UTC, marcodelapierre commented
Good point @dialvarezs !
They indeed only work on `x86_64` archs. I have added a condition for this in the recipes.

2022-07-13 05:00 UTC, dialvarezs requested changes
A few last suggestions on platform checking

2022-07-13 05:00 UTC, dialvarezs commented on var/spack/repos/builtin/packages/tower-agent/package.py
> +import sys
```suggestion
```

2022-07-13 05:00 UTC, dialvarezs commented on var/spack/repos/builtin/packages/tower-agent/package.py
> +        if sys.platform.startswith('linux'):
```suggestion
    if platform.machine() == 'x86_64':
        if platform.system() == 'Linux':
```

2022-07-13 05:00 UTC, dialvarezs commented on var/spack/repos/builtin/packages/tower-cli/package.py
> +        if sys.platform == 'darwin':
```suggestion
    if platform.machine() == 'x86_64':
        if platform.system() == 'Darwin':
```

2022-07-13 05:00 UTC, dialvarezs commented on var/spack/repos/builtin/packages/tower-cli/package.py
> +import sys
```suggestion
```

2022-07-13 05:00 UTC, dialvarezs commented on var/spack/repos/builtin/packages/tower-cli/package.py
> +        elif sys.platform.startswith('linux'):
```suggestion
        elif platform.system() == 'Linux':
```

2022-07-13 05:17 UTC, marcodelapierre commented
Thanks, all addressed!

2022-07-13 05:37 UTC, dialvarezs approved these changes
Great, we're ready then. Thank you!

2022-07-13 05:37 UTC, dialvarezs approved these changes

2022-07-13 07:04 UTC, alalazo approved these changes

2022-07-13 07:05 UTC, merged

2022-08-09 12:34 UTC, aalmiray commented
FWIW JReleaser has an [open ticket](https://github.com/jreleaser/jreleaser/issues/834) for adding Spack support. Any tips would be greatly appreciated to get it off the ground.
cc @pditommaso

2022-08-09 13:23 UTC, marcodelapierre commented
@aalmiray @pditommaso asking a naive question, but apart from Nextflow I am out of the Java galaxy: I can think of JReleaser a bit like the Java equivalent of pip/pypi for Python, isn't it?

Spack supports various types of packages/build systems: https://spack.readthedocs.io/en/latest/build_systems.html
Would it make sense to target the design of a new build system for Java, using JReleaser under the hood?

Note I am not part of the core dev team of Spack, at  this stage I am just throwing ideas to brainstorm.

2022-08-09 13:41 UTC, aalmiray commented
@marcodelapierre Thanks for the quick reply. I'm new to Spack so I got lost pretty quickly. Your templates have proved useful to figure out the install procedure of a generic CLI tool packaged as a zip or tar. Still looking for options to get an archive such as

```
    app-1.0.0
    ├── bin
    │   ├── app
    │   └── app.bat
    └── lib
        └── app-1.0.0.jar
```

To be installed using a basic Spack template.

2022-08-09 13:58 UTC, marcodelapierre commented
Have a look at this section of the docs:
https://spack.readthedocs.io/en/latest/packaging_guide.html ,

and in particular:
https://spack.readthedocs.io/en/latest/packaging_guide.html#file-functions

You might find useful directions.