Openfoam-org: support 3.0.1 version
LLNL/spack pull request #31534
Opened 2022-07-12 07:45 UTC by iWangJiaxiang

> Thanks for bringing order to HPC software chaos. My organization have been using Spack since 2019 and thanks to Spack we could make software management in order without pain. During this period, we have extended Spack and now we are bringing them back to community . May our contributions be a small step in the great leap of HPC softwawre development.

This PR adds support for 3.0.1 version, which is needed by CFDEM software.

2022-07-12 11:35 UTC, alalazo requested changes
Can you provide more information on the provenance of the patches?

2022-08-22 09:08 UTC, alalazo commented
@iWangJiaxiang Do you plan to continue working on this PR?

2022-08-24 01:58 UTC, iWangJiaxiang commented
Sure thing! Sorry for the late reply.

The errors occur when following the original intallation instructions, which breaks the automate software installation. We have solved this problem according to the error hints and genereted this patch.

2024-02-22 06:45 UTC, alalazo commented
Closing, since there has been no activity in a while, and the PR requiring this has been closed. Feel free to reopen if you want to continue work on this.

2024-02-22 06:45 UTC, closed without merging