gperftools: Add version 2.10 and add unwind to LDFLAGS
LLNL/spack pull request #31574
Opened 2022-07-14 08:06 UTC by haralmha

Without -lunwind in LDFLAGS on clang 14.0.6:
```
undefined reference to `_ULx86_64_init_local'
undefined reference to `_Ux86_64_getcontext'
undefined reference to `_ULx86_64_get_reg'
undefined reference to `_ULx86_64_step'
```

2022-07-14 08:30 UTC, msimberg approved these changes
This also fixes #25832.

2022-07-14 08:30 UTC, msimberg submitted a review, later dismissed

2022-07-14 15:01 UTC, eschnett requested changes

2022-07-14 15:01 UTC, eschnett commented on var/spack/repos/builtin/packages/gperftools/package.py
> +            "LDFLAGS=-lunwind"
This flag should only be given when the variant `+libunwind` is chosen.

2022-07-14 16:23 UTC, tldahlgren reviewed
Confirmed sha256.

2022-07-15 15:35 UTC, msimberg approved these changes

2022-07-15 17:34 UTC, tldahlgren approved these changes

2022-07-15 17:34 UTC, merged