py-colorcet: add new package
LLNL/spack pull request #31597
Opened 2022-07-15 12:49 UTC by vvolkl

2022-07-15 17:01 UTC, adamjstewart requested changes

2022-07-15 17:01 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-colorcet/package.py
> +
Can you also add a dep on Python 2.7+

2022-07-15 17:01 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-colorcet/package.py
> +    depends_on('py-pyct@0.4.4:', type='build')
These are also required at run-time

2022-07-15 17:01 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyct/package.py
> +
Python 2.7+

2022-07-15 17:01 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyct/package.py
> +    depends_on('py-param@1.7.0:', type='build')
run-time

2022-07-16 15:34 UTC, adamjstewart requested changes

2022-07-16 15:34 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-colorcet/package.py
> +    depends_on('python@2.7:')
Build/run

2022-07-16 15:34 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyct/package.py
> +    depends_on('python@2.7:')
Build/run

2022-07-16 15:50 UTC, adamjstewart approved these changes, later dismissed

2022-07-16 18:13 UTC, vvolkl commented
Thanks for the comments!

2022-09-24 20:51 UTC, adamjstewart approved these changes

2022-09-24 20:52 UTC, merged