perl-bignum: Adding perl module
LLNL/spack pull request #31590
Opened 2022-07-15 00:38 UTC by marcost2

The simple bignum/bigint module

2022-08-25 20:44 UTC, glennpj requested changes
There is a missing dependency on `perl-math-bigrat`, which will need a Spack package.
https://cpan.metacpan.org/authors/id/P/PJ/PJACKLAM/Math-BigRat-0.2624.tar.gz

2022-08-25 20:44 UTC, glennpj commented on var/spack/repos/builtin/packages/perl-bignum/package.py
> +    depends_on('perl-extutils-makemaker', type=('build'))
I do not see this dependency listed.

2022-08-25 21:18 UTC, marcost2 commented
> There is a missing dependency on `perl-math-bigrat`, which will need a Spack package. https://metacpan.org/pod/Math::BigRat https://cpan.metacpan.org/authors/id/P/PJ/PJACKLAM/Math-BigRat-0.2624.tar.gz
Apparently there's also a missing dependency on 'perl-math-bigint'; bad move on me for assuming the dependencies would be listed in the readme.

Will get on adding both to spack and updating this PR with that

2022-08-26 02:27 UTC, glennpj commented on var/spack/repos/builtin/packages/perl-bignum/package.py
> +    depends_on('perl-extutils-makemaker', type=('build'))
Never mind this comment, the Spack documentation recommends it to accommodate older perl versions from externals.

2022-08-26 20:11 UTC, glennpj requested changes

2022-08-26 20:11 UTC, glennpj commented on var/spack/repos/builtin/packages/perl-math-bigint/package.py
> +    version("1.999837", sha256="038f9aad6318f20a84a7b1afe3087a1b02406c9988ce5919311a797f85a32962")
Did you want to add the build system module per https://spack.readthedocs.io/en/latest/build_systems/perlpackage.html#build-system-dependencies?

2022-08-26 20:11 UTC, glennpj commented on var/spack/repos/builtin/packages/perl-bignum/package.py
> +    depends_on("perl-math-bigint", type=("build", "run"))
I do not see this dependency listed on https://cpandeps.grinnz.com/?dist=bignum. It does seem like it would be needed though.

2022-08-26 20:11 UTC, glennpj commented on var/spack/repos/builtin/packages/perl-module-install/package.py
> +    depends_on("perl-yaml-tiny", type=("build"))
It looks like there is a missing dependency for `module-corelist`

2022-08-26 20:15 UTC, marcost2 commented on var/spack/repos/builtin/packages/perl-bignum/package.py
> +    depends_on("perl-math-bigint", type=("build", "run"))
It is not listed, but without it you can use functions that are supposedly added by perl-bignum that will fail

2022-08-26 20:15 UTC, marcost2 commented on var/spack/repos/builtin/packages/perl-module-install/package.py
> +    depends_on("perl-yaml-tiny", type=("build"))
Where is that dependency listed?

2022-08-26 20:15 UTC, marcost2 commented on var/spack/repos/builtin/packages/perl-math-bigint/package.py
> +    version("1.999837", sha256="038f9aad6318f20a84a7b1afe3087a1b02406c9988ce5919311a797f85a32962")
I'm sorry i'm not quite sure i understand what you are saying?

2022-08-26 20:25 UTC, glennpj commented on var/spack/repos/builtin/packages/perl-module-install/package.py
> +    depends_on("perl-yaml-tiny", type=("build"))
https://cpandeps.grinnz.com/?dist=Module-Install

2022-08-26 21:58 UTC, marcost2 commented on var/spack/repos/builtin/packages/perl-module-install/package.py
> +    depends_on("perl-yaml-tiny", type=("build"))
Done

2022-08-27 18:50 UTC, glennpj commented on var/spack/repos/builtin/packages/perl-math-bigint/package.py
> +    version("1.999837", sha256="038f9aad6318f20a84a7b1afe3087a1b02406c9988ce5919311a797f85a32962")
Essentially, the Spack documentation recommends adding one of the build modules to ensure that older versions of perl, set as an external, will have the correct module. I do not believe it is required but just wanted to ask. From the docs:
> Although newer versions of Perl include ExtUtils::MakeMaker and Module::Build as “core” modules, you may want to add dependencies on perl-extutils-makemaker and perl-module-build anyway. Many people add Perl as an external package, and we want the build to work properly. If your package uses Makefile.PL to build, add:
>
> ```depends_on('perl-extutils-makemaker', type='build')```
> If your package uses Build.PL to build, add:
>
> ```depends_on('perl-module-build', type='build')```

2022-08-27 18:53 UTC, glennpj commented
@marcost2 Can you update your branch, with either a merge from develop or a rebase?

2022-08-27 19:07 UTC, marcost2 commented on var/spack/repos/builtin/packages/perl-math-bigint/package.py
> +    version("1.999837", sha256="038f9aad6318f20a84a7b1afe3087a1b02406c9988ce5919311a797f85a32962")
Should this be done for module-corelist, module-scandeps and yaml-tiny too? They all use makemaker

2022-08-27 19:07 UTC, marcost2 commented
@glennpj Done

2022-09-01 02:07 UTC, glennpj approved these changes

2022-09-01 02:07 UTC, merged