Fix hwloc+onepai-level-zero recipe
LLNL/spack pull request #31622
Opened 2022-07-18 12:21 UTC by mabraham

I recently added this support and erroneously managed the flags to configure twice. Removed the one that was wrong so that a configure warning is no longer issued.

2022-07-18 12:42 UTC, bgoglin approved these changes, later dismissed

2022-08-03 12:13 UTC, alalazo requested changes
LGTM, after the conflicts are solved.

2022-08-03 12:31 UTC, mabraham commented
> LGTM, after the conflicts are solved.

Solved. Rebased the upstream branch past the commit that did the linting with black, then force-pushed. No content changes needed.

2022-08-03 12:42 UTC, alalazo submitted a review, later dismissed

2022-08-05 07:18 UTC, alalazo commented
@spackbot run pipeline

2022-08-22 10:22 UTC, alalazo approved these changes

2022-08-22 18:45 UTC, merged