Added newer versions of py-torch-sparse and py-torch-geometric
LLNL/spack pull request #31682
Opened 2022-07-21 18:12 UTC by brandon-feder

2022-07-21 18:48 UTC, adamjstewart requested changes
See https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html for instructions on finding and adding Python dependencies

2022-07-21 18:48 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-torch-geometric/package.py
Can you update the list of dependencies?
```
install_requires = [                                                                     
    'tqdm',                                                                              
    'numpy',                                                                             
    'scipy',                                                                             
    'pandas',                                                                            
    'jinja2',                                                                            
    'requests',                                                                          
    'pyparsing',                                                                         
    'scikit-learn',                                                                      
]       
    python_requires='>=3.7',                                                             
```
Everything else is optional in this latest release.

2022-07-21 18:48 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-torch-sparse/package.py
Need to update dependency list:
```
install_requires = [                                                                     
    'scipy',                                                                             
]    
    python_requires='>=3.7',                                                             
```

2022-07-25 12:47 UTC, brandon-feder commented
Doesn't both`py-torch` and `py-torch-geometric` depend on more than just what you listed? 

When you write 
```
install_requires = [                                                                     
    'scipy',                                                                             
]   
```
Do you want me to remove everything but `depends_on('py-scipy', type=('build', 'run'))`?

I apologize for my misunderstanding.

2022-07-25 17:11 UTC, adamjstewart commented
In the case of `py-torch-sparse`, it looks like many of the package dependencies aren't explicitly listed but still required. I think `py-pytest-runner` isn't required (at least in the latest version) but the other dependencies are still required. See https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html for docs on how to determine which dependencies are required.

2022-07-26 01:29 UTC, tgamblin commented
@spackbot fix style

2022-07-26 22:00 UTC, scottwittenburg commented
@spackbot fix style

2022-07-26 22:01 UTC, scottwittenburg commented
@spackbot hello

2022-07-26 22:01 UTC, scottwittenburg commented
@spackbot help

2022-07-26 22:02 UTC, scottwittenburg commented
@spackbot fix style

2022-07-26 22:05 UTC, scottwittenburg commented
@spackbot fix style

2022-07-26 22:10 UTC, scottwittenburg commented
@spackbot fix style

2022-07-26 22:15 UTC, scottwittenburg commented
@spackbot fix style

2022-07-26 22:20 UTC, scottwittenburg commented
@spackbot fix style

2022-07-26 22:24 UTC, adamjstewart commented
@tgamblin @scottwittenburg should we create a new fake PR to debug spackbot instead of bogging down this real PR with comments?

2022-07-26 22:27 UTC, scottwittenburg commented
> @tgamblin @scottwittenburg should we create a new fake PR to debug spackbot instead of bogging down this real PR with comments?

Sorry about this, maybe I can delete these comments?  I did create a fake [PR](https://github.com/spack/spack/pull/31757) to test it, and it's working there.

2022-07-26 22:28 UTC, tgamblin commented
@adamjstewart probably :)

I was hoping this would work and the style would be magically fixed.  Any chance you could open a PR for @scottwittenburg to test this on?  We need one not authored by him, because the issue is permissions.  e.g., it works here: https://github.com/spack/spack/pull/31757#issuecomment-1196037483 but @scottwittenburg owns that PR.

2022-07-28 21:00 UTC, scottwittenburg commented
@spackbot fix style

2022-07-28 21:02 UTC, tgamblin commented
Ok sorry for the noise -- but now it appears that spackbot is working.  So if you want to fix style on your PR (and it's fixable) you'll be able to ask it to do so.  This PR was particularly interesting for testing as @brandon-feder is a first-time contributors and we had a harder time getting spackbot to work for this PR.  Sorry for the noise!

2022-07-28 21:10 UTC, adamjstewart commented
But isn't spackbot supposed to commit the changes? The PR hasn't been updated.

2022-07-28 21:13 UTC, scottwittenburg commented
> But isn't spackbot supposed to commit the changes

Maybe the message needs to be made clearer.  It does say it cannot fix flake8 or mypy errors, and that it wasn't able to make any further changes on this PR.  But I'm not sure that really stands out.

2022-07-28 21:15 UTC, adamjstewart commented
I guess this particular issue will be fixed once we add black, but yeah, it would be good to make it more clear that spackbot failed to fix the failing CI

2022-10-07 02:19 UTC, adamjstewart commented
What's the status of this PR? Both packages have since been updated, although these exact versions aren't yet listed. Do you want to try to rebase, or open a new PR, or abandon it?

2023-02-20 20:25 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2023-02-20 20:25 UTC, closed without merging