Add VASP 6.3.2; handle changes to makefile.include naming pattern
LLNL/spack pull request #31701
Opened 2022-07-22 20:09 UTC by alansill

Added the SHA256 for version 6.3.2 and added logic to eal with the change of naming pattern for the makefile.include files that now appears to leave out the "linux_" prefix. (Changes should be. backwards compatible.)

2022-07-22 20:51 UTC, alansill commented
I don't know what to do about the windows style tests since this package was not previously available in the build system for windows AFAICT, and this package.py was aimed specifically at Linux.

2022-08-03 11:57 UTC, alalazo requested changes
One minor request and a conflict to be fixed.

2022-08-03 11:57 UTC, alalazo commented on var/spack/repos/builtin/packages/vasp/package.py
> +            os.rename(new_make_include, 'makefile.include')
```suggestion
        if not os.path.exists(make_include):
            make_include = make_include.replace('linux_', '')
        os.rename(make_include, 'makefile.include')
```

2022-08-03 16:12 UTC, alansill commented
I don't understand why it has flagged the updated version as a conflict. The whole point of this pull request was to update the package.py file in exactly those lines. What is flagging the additions as producing a conflict?

2022-08-03 16:18 UTC, alalazo commented
@alansill We started enforcing style with [black](https://github.com/psf/black) a few days ago, and that meant reformatting the entire code base. You need to rebase against develop to resolve the conflict, sorry.

2022-08-22 08:42 UTC, alalazo commented
@spackbot fix style

2022-08-22 10:20 UTC, alalazo approved these changes

2022-08-22 10:21 UTC, merged