LLVM: Allow to set experimental_targets
LLNL/spack pull request #31768
Opened 2022-07-27 09:05 UTC by certik

Now one can enable experimental LLVM targets as follows:

    spack install llvm experimental_targets=arc

2022-07-27 09:07 UTC, certik commented
I tested this on Apple M1, it works for me:
```console
    $ spack install -j10 llvm@14.0.4 experimental_targets=arc
    [...]
      Fetch: 0.08s.  Build: 15m 35.59s.  Total: 15m 35.67s.
    [+] /Users/ondrej/repos/spack/opt/spack/darwin-monterey-m1/apple-clang-13.0.0/llvm-14.0.4-gzhudm4xzfivj6x3h25a2ozkgqcghyzi
    $ /Users/ondrej/repos/spack/opt/spack/darwin-monterey-m1/apple-clang-13.0.0/llvm-14.0.4-gzhudm4xzfivj6x3h25a2ozkgqcghyzi/bin/clang -print-targets
      Registered Targets:
        aarch64    - AArch64 (little endian)
        aarch64_32 - AArch64 (little endian ILP32)
        aarch64_be - AArch64 (big endian)
        arc        - ARC
        arm64      - ARM64 (little endian)
        arm64_32   - ARM64 (little endian ILP32)
```

2022-07-28 00:43 UTC, trws approved these changes
LGTM, @haampie how do you feel?

2022-07-29 09:52 UTC, haampie commented on var/spack/repos/builtin/packages/llvm/package.py
> +    spack_to_cmake = {
can you stick to a single `spack_to_cmake` map? that'd be easier in case an experimental target becomes a normal target later on.

2022-07-29 09:54 UTC, haampie requested changes
I think it's fine given that we can use conditional values later on if an experimental target becomes a stable target. Actually, it'd be good to verify if there are any experimental targets that should be conditional on the llvm version already?

Further it'd be good to have a single mapping from spack target name -> llvm target name instead of repeated logic.

2023-02-20 20:32 UTC, alalazo commented
@certik

2023-02-21 05:03 UTC, certik commented
I don't have the time to finish this, I am sorry.

2023-02-21 05:45 UTC, alalazo commented
Thanks for the prompt reply @certik !

2024-11-26 07:20 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2024-11-26 07:20 UTC, closed without merging