New package: trexio
LLNL/spack pull request #31769
Opened 2022-07-27 09:30 UTC by q-posev

Spack specification for the TREXIO library in C.

2022-07-27 10:19 UTC, q-posev commented
@scemama this PR is ready for review

2022-07-27 22:00 UTC, tldahlgren requested changes
Confirmed sha256.  There are a few changes that need to be made.

2022-07-27 22:00 UTC, tldahlgren commented on var/spack/repos/builtin/packages/trexio/package.py
> +# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```

2022-07-27 22:00 UTC, tldahlgren commented on var/spack/repos/builtin/packages/trexio/package.py
> +# ----------------------------------------------------------------------------
This is how-to that should be removed.

```suggestion
```

2022-07-27 22:00 UTC, tldahlgren commented on var/spack/repos/builtin/packages/trexio/package.py
> +    version('2.2.0', sha256='e6340c424fcea18ae0b643a5707e16005c7576ee21a5aac679fbc132d70b36d9')
Newer versions are listed first in Spack.

```suggestion
    version('2.2.0', sha256='e6340c424fcea18ae0b643a5707e16005c7576ee21a5aac679fbc132d70b36d9')
    version('2.1.0', sha256='232866c943b98fa8a42d34b55e940f7501634eb5bd426555ba970f5c09775e83')
    version('2.0.0', sha256='6eeef2da44259718b43991eedae4b20d4f90044e38f3b44a8beea52c38b14cb4')
```

2022-07-28 08:40 UTC, q-posev commented
Thank you @tldahlgren for the review! I have added your changes.

2022-07-28 22:05 UTC, tldahlgren approved these changes

2022-07-28 22:05 UTC, merged