WarpX: 22.08
LLNL/spack pull request #31849
Opened 2022-08-01 20:58 UTC by ax3l

Add the lastest WarpX release.

2022-08-01 21:59 UTC, dpgrote submitted a review, later dismissed
Looks good

2022-08-02 05:30 UTC, alalazo commented
@spackbot style

2022-08-02 05:30 UTC, alalazo commented
@spackbot help

2022-08-02 05:30 UTC, alalazo commented
@spackbot fix style

2022-08-02 16:21 UTC, tldahlgren submitted a review, later dismissed
Confirmed sha256.

2022-08-02 16:22 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-warpx/package.py
> +    version('22.08', sha256='5ff7fd628e8bf615c1107e6c51bc55926f3ef2a076985444b889d292fecf56d4')
Black requires:

```suggestion
    version("22.08", sha256='5ff7fd628e8bf615c1107e6c51bc55926f3ef2a076985444b889d292fecf56d4')
```

2022-08-02 17:20 UTC, alalazo commented
@spackbot fix style

2022-08-02 17:40 UTC, alalazo approved these changes

2022-08-02 20:06 UTC, alalazo requested changes
WarpX has not been updated to v22.08

2022-08-09 18:13 UTC, ax3l commented
Ouch, thank you so much for catching that :pray:

2022-08-10 08:25 UTC, alalazo approved these changes

2022-08-10 08:25 UTC, merged