py-cfgv: new versions
LLNL/spack pull request #31859
Opened 2022-08-02 08:56 UTC by haampie

2022-08-02 17:34 UTC, adamjstewart requested changes

2022-08-02 17:34 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cfgv/package.py
>      depends_on("py-six", type=("build", "run"))
Six is no longer required

2023-10-09 16:22 UTC, alecbcs commented
ping @haampie

2024-11-26 07:22 UTC, alalazo commented
Superseded by #40465

2024-11-26 07:22 UTC, closed without merging