py-nodeenv: add v1.3.4 -> v1.7.0
LLNL/spack pull request #31861
Opened 2022-08-02 09:03 UTC by haampie

2022-08-02 17:35 UTC, adamjstewart requested changes

2022-08-02 17:35 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-nodeenv/package.py
>      depends_on("py-setuptools", type="build")
Required at run-time as well, at least in the latest version

2023-10-09 16:21 UTC, alecbcs commented
ping @haampie

2024-11-26 07:23 UTC, alalazo commented
Superseded by #38383

2024-11-26 07:23 UTC, closed without merging