spack mirror: skip non-concretizable specs
LLNL/spack pull request #31897
Opened 2022-08-03 11:04 UTC by alalazo

fixes #31736

Catch errors when concretizing specs and report them as debug messages. The corresponding spec is skipped.

2022-08-03 11:05 UTC, alalazo commented
@Paul-Ferrell

2022-08-03 13:39 UTC, Paul-Ferrell commented
:+1:

2022-08-03 16:27 UTC, becker33 requested changes

2022-08-03 16:27 UTC, becker33 commented on lib/spack/spack/mirror.py
> +        return False
```suggestion
        mirror_stats.error()
        return False
```

2022-08-04 09:53 UTC, alalazo commented
@becker33

2022-08-05 16:41 UTC, becker33 approved these changes

2022-08-05 17:19 UTC, merged