Update py-numexpr
LLNL/spack pull request #31900
Opened 2022-08-03 12:22 UTC by iarspider

2022-08-03 17:01 UTC, adamjstewart requested changes

2022-08-03 17:01 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-numexpr/package.py
> +    depends_on("py-numpy@1.13.3:", type=("build", "run"), when="@2.8.3:")
Missing a dependency on `py-packaging`

2022-08-03 17:19 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-numexpr/package.py
> +    depends_on("py-packaging", type="build", when="@2.8.3:")
```suggestion
    depends_on("py-packaging", type=("build", "run"), when="@2.8.3:")
```

2022-08-03 17:22 UTC, adamjstewart submitted a review, later dismissed

2022-08-03 22:08 UTC, adamjstewart approved these changes, later dismissed

2022-08-04 08:38 UTC, iarspider commented
@adamjstewart the pipeline failure is not related to this PR: it is an issue with the combination of numpy and intel compiler https://github.com/numpy/numpy/issues/22011

2022-08-04 16:57 UTC, adamjstewart commented
Hmm, not sure what could have changed in the pipeline where that would start to break all of a sudden. @scottwittenburg?

2022-08-04 17:49 UTC, scottwittenburg commented
> Hmm, not sure what could have changed in the pipeline where that would start to break all of a sudden

Am I just reading the diff wrong, or didn't this PR explicitly change the version of numpy getting built in the pipeline?

2022-08-04 18:00 UTC, adamjstewart commented
Oh, that could be an unintentional consequence of this PR, yes.

2022-08-05 07:15 UTC, iarspider commented
@adamjstewart @scottwittenburg should I add a `conflict(...)` clause to py-numpy recipe?

2022-08-05 14:52 UTC, adamjstewart commented
Yes, I think that's the right solution. @rgommers?

2022-08-05 14:56 UTC, rgommers commented
Yes, makes sense to me. NumPy 1.23.0 shipped moved some code from C to C++ that the Intel Compiler seems to choke on, so until that is resolved there's a conflict there.

2022-08-05 15:31 UTC, adamjstewart approved these changes

2022-08-05 21:29 UTC, merged