Enforcing ncurses with 'ABI=5' as dependency for ARM HPC Compiler 22.0.1 on Rocky Linux 8.6
LLNL/spack pull request #31942
Opened 2022-08-05 06:19 UTC by fspiga

Deploying ARM HPC Compiler 22.0.1 on Rocky Linux release 8.6 was successful but unable to use the compiler due to a missing library `libtinfo.so.5`. 

Solved by enforcing new ncurses with `abi=5` variant. It may be redundant for other OSes.

Suggestions how to improve this are welcome.

2022-08-05 07:12 UTC, alalazo requested changes

2022-08-05 07:12 UTC, alalazo commented on var/spack/repos/builtin/packages/arm/package.py
> +        if "ncurses" in self.dependencies:
```suggestion
        if "ncurses" in self.spec:
```

2022-08-05 08:33 UTC, alalazo commented
@spackbot fix style

2022-08-05 10:06 UTC, OliverPerks approved these changes
This looks like a very sensible addition to me. 
I have had a brief look and I dont think this would break support for any packages at the moment.

2022-08-10 10:14 UTC, alalazo approved these changes

2022-08-10 10:15 UTC, merged