keepassxc: as an option do not build documentation
LLNL/spack pull request #32049
Opened 2022-08-11 06:29 UTC by cessenat

This avoids the dependency to asciidoctor and thus to ruby.

2022-08-11 06:35 UTC, cessenat commented
Note for reviewer : as a default, documentation is built - as is the case for linux distribution packages - but I'm not sure it is a good idea since most spack packages as a default do not build the documentation. What do you recommend ?

2022-08-11 11:54 UTC, alalazo requested changes

2022-08-11 11:54 UTC, alalazo commented on var/spack/repos/builtin/packages/keepassxc/package.py
> +            args.append("-DWITH_XC_DOCS=OFF")
```suggestion
        args.append(self.define_from_variant("WITH_XC_DOCS", "doc"))
```

2022-08-11 11:54 UTC, alalazo commented on var/spack/repos/builtin/packages/keepassxc/package.py
> +            args.append("-DWITH_XC_DOCS=OFF")
Can also be applied elsewhere in the recipe.

2022-08-11 14:47 UTC, alalazo commented
@cessenat Can you also take care of:

> Can also be applied elsewhere in the recipe.

? Should be just the other variant above your modification.

2022-08-11 14:55 UTC, cessenat commented
Oh yes, thanks.
BTW the doc option I chose is "docs" as for cmake WITH_XC_DOCS.
Some package use doc other docs...

2022-08-11 15:03 UTC, alalazo commented
> Some package use doc other docs...

True, we don't have a de facto standard for that - so I guess it's up to you :wink:

2022-08-11 15:03 UTC, alalazo approved these changes

2022-08-12 12:25 UTC, cessenat commented
Hi @alalazo can you merge to develop ?
Same for PR #32032 ?
Thanks.

2022-08-12 13:07 UTC, merged