New package: py-loguru
LLNL/spack pull request #32074
Opened 2022-08-11 18:42 UTC by qwertos

2022-08-11 23:14 UTC, adamjstewart requested changes

2022-08-11 23:14 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-loguru/package.py
> +    depends_on('python@3.5:', type='build')
Presumably Python is also needed at run-time

Also missing a build dep on setuptools

2022-08-23 11:20 UTC, alalazo commented
@spackbot fix style

2022-08-23 17:00 UTC, adamjstewart approved these changes

2022-08-23 17:00 UTC, merged