config.yaml:  Adds a few more words about $tempdir.
LLNL/spack pull request #32132
Opened 2022-08-14 15:05 UTC by rountree

Adds a description of how $tempdir is generated.

Fixes #32131

2022-08-15 17:20 UTC, tldahlgren commented on etc/spack/defaults/config.yaml
> +  # The string `$tempdir$ will be substituted with the results of a call to
```suggestion
  # The string `$tempdir` will be substituted with the results of a call to
```

2022-08-15 18:09 UTC, tldahlgren requested changes

2022-08-15 18:09 UTC, tldahlgren commented on etc/spack/defaults/config.yaml
> +  # The string `$tempdir$ will be substituted with the results of a call to
```suggestion
  # The string `$tempdir` will be substituted with the results of a call to
```

2022-08-15 18:09 UTC, tldahlgren commented on etc/spack/defaults/config.yaml
> +  # $SPACK_USER_CACHE_PATH.
```suggestion
  # `$SPACK_USER_CACHE_PATH`.
```

2022-08-15 18:09 UTC, tldahlgren commented on etc/spack/defaults/config.yaml
> +  #   5) The current working directory
I question whether we want to be elaborating on the ordering defined by the python implementation in our documentation.  

Perhaps a link to the relevant python docs (https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir) would be more suitable or a more general summary as before but with a little more elaboration?

2022-08-15 18:09 UTC, tldahlgren commented on etc/spack/defaults/config.yaml
> +  # $SPACK_USER_CACHE_PATH.
And if that variable isn't set, then Spack will use `"~%s.spack" % os.sep`.

2022-08-19 04:36 UTC, rountree commented
@tldahlgren Good points.

I'm now wondering if a better solution would be to point out early on that `$lowercase` comes from the python execution environment and `$UPPERCASE` comes from the shell environment.  I'll poke around a bit to see if this is mentioned somewhere else.  Having a list of both would be useful.

2022-08-21 13:08 UTC, closed without merging