New package: roary
LLNL/spack pull request #32217
Opened 2022-08-17 17:15 UTC by dlkuehn

Included in this pull requests are the new and modified package files which are required for roary to install and run.

Roary - Rapid large-scale prokaryote pan genome analysis

New:
perl-digest-md5-file
perl-file-find-rule
perl-file-grep
perl-number-compare
perl-text-glob

Modified:
fasttree - the current version of fasttree installs only the openmp-compatible version, that was left the default, but the non-openmp-compatible version was made a variant to fill a roary requirement.

mcl - the current version of mcl does not allow for the --blast variant (which builds the bioinformatics tools needed by roary) to be build.  +blast /  --enable-blast was added as a variant.

perl-perlio-utf8-strict - required the perl-module-build dependency to build on a fresh Spack install.

2022-08-23 10:49 UTC, alalazo commented
@glennpj Would you have some time to review this PR (it contains a few Perl packages)?

2022-08-25 03:26 UTC, glennpj commented
> @glennpj Would you have some time to review this PR (it contains a few Perl packages)?

Sure, I will take a look tomorrow.

2022-08-25 17:46 UTC, glennpj requested changes
This looks good overall, just some dependency questions.

2022-08-25 17:46 UTC, glennpj commented on var/spack/repos/builtin/packages/perl-digest-md5-file/package.py
> +    depends_on("perl-extutils-makemaker", type="build")
I only see libwww-perl listed as a dependency https://cpandeps.grinnz.com/

2022-08-25 17:46 UTC, glennpj commented on var/spack/repos/builtin/packages/perl-file-find-rule/package.py
> +    depends_on("perl-extutils-makemaker", type="build")
I do not see this listed as a dependency.

2022-08-25 17:46 UTC, glennpj commented on var/spack/repos/builtin/packages/perl-file-grep/package.py
> +    depends_on("perl-extutils-makemaker", type="build")
Same as above.

2022-08-25 17:46 UTC, glennpj commented on var/spack/repos/builtin/packages/perl-number-compare/package.py
> +    depends_on("perl-extutils-makemaker", type="build")
Same as above.

2022-08-25 17:46 UTC, glennpj commented on var/spack/repos/builtin/packages/perl-perlio-utf8-strict/package.py
> +    depends_on("perl-module-build", type="build")
It looks like this is a build dependency up to version 0.005. We should capture that here.
```suggestion
    depends_on("perl-module-build", type="build", when="@:0.005")
```

2022-08-25 17:46 UTC, glennpj commented on var/spack/repos/builtin/packages/perl-text-glob/package.py
> +    depends_on("perl-extutils-makemaker", type="build")
I do not see this listed in the dependency list.

2022-08-25 17:46 UTC, glennpj commented on var/spack/repos/builtin/packages/roary/package.py
> +    depends_on("perl-xml-writer", type="run")
Should these be only `type="run"`? The perl modules are also listed as build-time dependencies.

2022-08-25 17:46 UTC, glennpj commented on var/spack/repos/builtin/packages/perl-perlio-utf8-strict/package.py
>      version("0.002", sha256="6e3163f8a2f1d276c975f21789d7a07843586d69e3e6156ffb67ef6680ceb75f")
I was not able to build version 0.002 on my system but the latest version, 0.009 worked fine, so this should probably be updated.
```suggestion
    version("0.009", sha256="ba82cf144820655d6d4836d12dde65f8895a3d905aeb4aa0b421249f43284c14")
    version("0.002", sha256="6e3163f8a2f1d276c975f21789d7a07843586d69e3e6156ffb67ef6680ceb75f")
```

2022-08-25 18:22 UTC, dlkuehn commented on var/spack/repos/builtin/packages/perl-digest-md5-file/package.py
> +    depends_on("perl-extutils-makemaker", type="build")
It was added per the recommendation of the Spack Perl Package build systems documentation:

     https://spack.readthedocs.io/en/latest/build_systems/perlpackage.html

This applies to the all files.

2022-08-25 18:25 UTC, dlkuehn commented on var/spack/repos/builtin/packages/roary/package.py
> +    depends_on("perl-xml-writer", type="run")
Roary is a series of Perl scripts included with the tarball.  There is no build step.  I tested it twice as written with no issues.  But I can add the build type, if it is necessary.

2022-08-26 02:11 UTC, glennpj commented on var/spack/repos/builtin/packages/perl-digest-md5-file/package.py
> +    depends_on("perl-extutils-makemaker", type="build")
Ah, for older versions of perl and if perl is an external.

2022-08-26 02:14 UTC, glennpj commented on var/spack/repos/builtin/packages/roary/package.py
> +    depends_on("perl-xml-writer", type="run")
Nope, just curious because the dependency graph shows them as both.

2022-08-26 02:25 UTC, glennpj requested changes

2022-08-26 02:25 UTC, glennpj commented on var/spack/repos/builtin/packages/perl-perlio-utf8-strict/package.py
> +    depends_on("perl-module-build", type="build", when="@:0.005")
My recommendation before was inaccurate given what you pointed out in the Spack documentation. In order to follow the guidance in the Spack documentation, this should be present for all versions. So, this should be reverted to what you had before; sorry about that.

2022-08-26 20:16 UTC, glennpj approved these changes

2022-08-26 20:17 UTC, glennpj commented
@spackbot run pipeline

2022-08-26 20:20 UTC, glennpj commented
@spackbot run pipeline

2022-08-26 20:29 UTC, merged