Update ESMF from JCSDA/NOAA-EMC spack fork (
LLNL/spack pull request #32222
Opened 2022-08-17 19:19 UTC by climbfuji

Update ESMF package.py from the JCSDA/NOAA-EMC spack fork. This provides updates for ESMF 8.3.0, which uses an external parallelio.

Fixes https://github.com/spack/spack/issues/31122
Replaces https://github.com/spack/spack/pull/32038

2022-08-17 19:19 UTC, climbfuji commented
@jedwards4b FYI

2022-08-22 20:08 UTC, tldahlgren requested changes
There are some issues with the URL for the new version.

2022-08-22 20:08 UTC, tldahlgren commented on var/spack/repos/builtin/packages/esmf/package.py
> +    )
Confirmed sha256 and existence of commit for new version.

However, the sha256 confirmation was not through the usual `spack checksum esmf 8.3.0`.  See comments for `url_for_version` below for fixing the URL so it works.

2022-08-22 20:08 UTC, tldahlgren commented on var/spack/repos/builtin/packages/esmf/package.py
> +            return "[https://github.com/esmf-org/esmf/archive/v{0}.tar.gz]".format(version)
```suggestion
            return "https://github.com/esmf-org/esmf/archive/refs/tags/v{0}.tar.gz".format(version.dotted)
```

2022-08-22 20:31 UTC, climbfuji commented on var/spack/repos/builtin/packages/esmf/package.py
> +            return "[https://github.com/esmf-org/esmf/archive/v{0}.tar.gz]".format(version)
@tldahlgren Thanks for that upate.

2022-08-22 21:15 UTC, tldahlgren commented
@spackbot fix style

2022-08-23 00:36 UTC, tldahlgren approved these changes
LGTM

2022-08-23 00:36 UTC, merged