Bugfix: Compiler bootstrapping for compilers in the environment
LLNL/spack pull request #32228
Opened 2022-08-17 23:51 UTC by becker33

The compiler bootstrapping logic currently does not add a task when the compiler package is already in the install task queue. This causes failures when the compiler package is added without the additional metadata telling the task to update the compilers list.

Solution: requeue compilers for bootstrapping when needed, to update `task.compiler` metadata.

@tgamblin @tldahlgren this is the PR we've discussed earlier today in various channels.

2022-08-18 18:44 UTC, tldahlgren requested changes
Looks good.  Just some minor changes IMO.

Also, I'm not seeing the coverage report.  Any chance of getting at least one unit test added (or modified) for this?

The only reservation I have (because I haven't tested it) is whether modifying in place has an affect on the heap/priority queue properties.  My assumption ATM is the answer is "no".

2022-08-18 18:44 UTC, tldahlgren commented on lib/spack/spack/installer.py
> +                # Requeue ensuring we treat it as a compiler
This isn't really re-queueing the task (as in the work done in `_push_task`), but modifying existing tasks in place.

2022-08-18 18:44 UTC, tldahlgren commented on lib/spack/spack/installer.py
> +                        task.compiler = True
I think a `debug` message would be useful here, even if it is `level=2` to reduce noise.

2022-11-04 17:16 UTC, becker33 commented
@tldahlgren updated this for your review

2022-11-04 18:06 UTC, tldahlgren commented
@spackbot fix format

2022-11-04 18:06 UTC, tldahlgren submitted a review, later dismissed

2022-11-04 18:32 UTC, becker33 commented
@spackbot fix style

2022-11-04 22:25 UTC, tldahlgren approved these changes, later dismissed

2022-11-05 08:29 UTC, becker33 commented
@spackbot fix style

2022-11-05 11:41 UTC, haampie commented
Can you please refactor code to avoid 7 levels of indentation?

2022-11-05 17:49 UTC, becker33 commented
@haampie addressed

2022-11-05 18:24 UTC, becker33 commented
@spackbot fix style

2022-11-07 17:38 UTC, tgamblin approved these changes

2022-11-07 17:38 UTC, merged