Bumping HPX requirements for FleCSI V2.0
LLNL/spack pull request #32355
Opened 2022-08-24 14:24 UTC by hkaiser

The FleCSI v2.x HPX backend depends on fixes available with HPX v1.8.1 only.

2022-08-24 14:28 UTC, rspavel commented
Is that true for all versions of `flecsi@2`? So 1.3.1 or whatever is there currently never worked?

Or is there a changing point? Currently the public flecsi versions are pretty coarse grain. But if we can avoid breaking compatibility with actual `flecsi@2.0` for a change that only applies to `flecsi@2.1.fourMonthsLater` that would be good to get into the habit of.

2022-08-24 19:27 UTC, hkaiser commented
> Is that true for all versions of `flecsi@2`? So 1.3.1 or whatever is there currently never worked?
> 
> Or is there a changing point? Currently the public flecsi versions are pretty coarse grain. But if we can avoid breaking compatibility with actual `flecsi@2.0` for a change that only applies to `flecsi@2.1.fourMonthsLater` that would be good to get into the habit of.

Anything before HPX 1.8 was never really tested, so the 1.3.1 in the script is probably an oversight from earlier versions of FleCSI.

2022-08-25 17:31 UTC, tldahlgren approved these changes, later dismissed
LGTM

2022-08-25 17:31 UTC, tldahlgren commented
Will defer merge to give at least one maintainer a chance to comment.

2022-08-26 01:09 UTC, tldahlgren commented
Looks like there were some node/pod issues.

@spackbot run pipeline

2022-08-26 04:36 UTC, rbberger requested changes
Given that this is for the `2` branch and hasn't been merged into any flecsi/flecsi branch yet, this change should be merged at a later time. Only after a tagged `2` release that includes the HPX backend.

2023-06-27 15:41 UTC, rbberger requested changes

2023-06-27 15:41 UTC, rbberger commented on var/spack/repos/builtin/packages/flecsi/package.py
> +    depends_on("hpx@1.8.1 cxxstd=17 malloc=system", when="backend=hpx @2.0:")
This should allow 1.8.1 and newer:
```suggestion
    depends_on("hpx@1.8.1: cxxstd=17 malloc=system", when="backend=hpx @2.0:")
```

2023-06-27 15:54 UTC, hkaiser commented on var/spack/repos/builtin/packages/flecsi/package.py
> +    depends_on("hpx@1.8.1 cxxstd=17 malloc=system", when="backend=hpx @2.0:")
@rbberger thanks for this! I also think that we should make it depend on the soon to be released HPX V1.9.1 instead.

2023-06-27 19:41 UTC, rbberger commented on var/spack/repos/builtin/packages/flecsi/package.py
> +    depends_on("hpx@1.8.1 cxxstd=17 malloc=system", when="backend=hpx @2.0:")
Ok, but in any case please add the `:` to future proof it.

2023-08-23 13:36 UTC, bernhardkaindl commented on var/spack/repos/builtin/packages/flecsi/package.py
> +    depends_on("hpx@1.8.1 cxxstd=17 malloc=system", when="backend=hpx @2.0:")
@hkaiser @rbberger I tried to build 2.x with +hpx but despite having checked that hpx-1.8.1 / 1.9.1 are in the spack build of flecsi, the CMake variable FOUND_MPX was not set:
```py
  >> 61    CMake Error at cmake/hpx.cmake:30 (message):
     62      HPX is required for this configuration
```
Also it seems that flecsi-2.2.1 does not have the include files it likes to include in it's tree:
```c++
  >> spack-src/flecsi/run/backend.hh:24:10: fatal error: hpx/context.hh: No such file or directory
     100       24 | #include "hpx/context.hh"
     101          |          ^~~~~~~~~~~~~~~~
spack-src/flecsi/exec/backend.hh:58:10: fatal error: flecsi/exec/hpx/policy.hh: No such file or directory
     108       58 | #include "flecsi/exec/hpx/policy.hh"
     109          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2023-08-23 14:15 UTC, hkaiser commented on var/spack/repos/builtin/packages/flecsi/package.py
> +    depends_on("hpx@1.8.1 cxxstd=17 malloc=system", when="backend=hpx @2.0:")
I have updated the package to HPX V1.91. now.

2023-09-22 17:28 UTC, rbberger commented
@tldahlgren we can merge this. We'd rather have this already in the next Spack release.

2023-09-24 14:24 UTC, alalazo approved these changes

2023-09-24 14:24 UTC, merged