add eztrace 2.0 release
LLNL/spack pull request #32350
Opened 2022-08-24 08:59 UTC by trahay

2022-08-25 17:50 UTC, tldahlgren requested changes
The hash seems to be off.

2022-08-25 17:50 UTC, tldahlgren commented on var/spack/repos/builtin/packages/eztrace/package.py
> +    version("2.0", sha256="899788d67e651bbe54abf39099f8f28a843d6676")
How did you calculate that?  I get the following from `spack checksum`:

```suggestion
    version("2.0", sha256="67bd296f059cdfab303c62f674af3e1e858213d6945bd79cb8ede4a035c0c2d6")
```

2022-08-25 19:02 UTC, tldahlgren commented
Note the hash is being called out in the test failures:

```
E       AssertionError: assert [] == ['All packages must use sha2...ms. eztrace@2.0 uses sha1.']
E         Right contains more items, first extra item: 'All packages must use sha256 checksums. eztrace@2.0 uses sha1.'
E         Full diff:
E         - []
E         + ['All packages must use sha256 checksums. eztrace@2.0 uses sha1.']
```

2022-08-26 07:27 UTC, trahay commented
You're right ! I messed up with the hash. Sorry about that.

2022-08-26 15:44 UTC, tldahlgren commented
> You're right ! I messed up with the hash. Sorry about that.

No problem

2022-08-26 15:45 UTC, tldahlgren approved these changes

2022-08-26 15:45 UTC, merged