added STAT 4.2.0 and updated deps
LLNL/spack pull request #32385
Opened 2022-08-26 00:19 UTC by lee218llnl

2022-08-26 00:26 UTC, tldahlgren requested changes
There appears to be an issue with `launchmon`'s sha256 for `1.0.2`.

2022-08-26 00:26 UTC, tldahlgren commented on var/spack/repos/builtin/packages/launchmon/package.py
> +    version("1.0.2", sha256="68127f343df1c1e9505dee2e16726e51222c1b2a9dd18a70d8577fe9b47f64c7")
Did you mean to add a URL to this version?  Otherwise, the sha256 is unchanged.

2022-08-26 00:26 UTC, tldahlgren commented on var/spack/repos/builtin/packages/stat/package.py
> +        sha256="d244d53585b0949e308354eb024f7a89ee3467fd2866b818e8aa6c8b5d372ced",
Confirmed the sha256 for `stat`.

2022-08-26 00:29 UTC, tldahlgren commented on var/spack/repos/builtin/packages/launchmon/package.py
> +        spec = self.spec
`spec` is not used.

2022-08-26 00:30 UTC, tldahlgren commented on var/spack/repos/builtin/packages/launchmon/package.py
> +            "--with-test-rm-launcher=/usr/bin/flux",
Will this *always* be the path to `flux` executable?

2022-08-26 00:45 UTC, lee218llnl commented
Sorry, there were changes that I didn't mean to push. I think I have fixed them. Thanks for the catches!

2022-08-26 00:53 UTC, tldahlgren commented on var/spack/repos/builtin/packages/launchmon/package.py
> +        sha256="edba70b8a283337dd4fda64192ba4fa36b7ada3f150340349b8681bcddcebda4",
Confirmed this sha256.

2022-08-26 00:53 UTC, lee218llnl commented
@spackbot fix style

2022-08-26 00:53 UTC, tldahlgren submitted a review, later dismissed
LGTM

2022-08-26 00:54 UTC, tldahlgren commented on var/spack/repos/builtin/packages/launchmon/package.py
> +
```suggestion
```

2022-08-26 01:03 UTC, tldahlgren approved these changes

2022-08-30 15:08 UTC, lee218llnl commented
can this get merged or do we need the pipeline to complete?

2022-08-30 15:16 UTC, tldahlgren commented
@spackbot run pipeline

2022-08-30 15:17 UTC, tldahlgren commented
> can this get merged or do we need the pipeline to complete?

The pipeline is required.

2022-08-30 15:25 UTC, merged