Fix spack locking on some NFS systems
LLNL/spack pull request #32426
Opened 2022-08-29 16:22 UTC by sethrj

It turns out that on some filesystem/os combinations, calling `os.makedirs` can raise `PermissionError` (`errno.EPERM`) if the directory is extant and readable, but not writable. This call happened before trying to activate environments.

Fixes #17407

2022-09-05 01:39 UTC, tgamblin requested changes
I think catching `OSError` and just warning if the directory already exists is too broad.  We're trying to be really specific in `llnl.util.lock` and I think it's better to fail fast in the corner cases than to let something potentially dangerous slip through.

#17407 is giving you errno 13, which is `EACCES`.  If that is the same error you see with NFSv4, I think we should check for that `errno` specifically, and allow it if it happens that the directory exists.

This is ok since as you note, we *may* be trying to get a read-only lock.  I think we could avoid this issue altogether in Python 3 with the [`exist_ok` parameter](https://docs.python.org/3/library/os.html#os.makedirs) to `os.makedirs` but sadly we (for the time being) need to support 2.7.  It'd be interesting to know if `exist_ok` gets rid of the permissions error if you are trying this with Python 3.

2022-09-05 01:39 UTC, tgamblin commented on lib/spack/llnl/util/lock.py
> +            else:
```suggestion
            # makedirs can fail several ways when diretory already exists.
            if not (
                # directory already exists and makedirs told us about it
                (e.errno == errno.EEXIST and os.path.isdir(parent))
                # directory already exists, and mode doesn't match default makedirs mode
                # (can happen when we try to take a read lock but don't have permission
                # on the parent directory)
                or (e.errno == errno.EACCESS and os.path.isdir(parent))
                # more specific way for makedirs to tell us the directory exists
                or e.errno == errno.EISDIR
            ):
```

2022-09-05 01:46 UTC, tgamblin commented
Ok actually I just looked at the cpython source, and it's broad.  So why don't we just go with that.  [Here is what they do](s](https://docs.python.org/3/library/os.html#os.makedirs)) in Python 3:

```python
    try:
        mkdir(name, mode)
    except OSError:
        # Cannot rely on checking for EEXIST, since the operating system
        # could give priority to other errors like EACCES or EROFS
        if not exist_ok or not path.isdir(name):
            raise
```

So apparently we care about `EROFS` and maybe others too.

2022-09-05 01:55 UTC, tgamblin requested changes

2022-09-05 01:55 UTC, tgamblin commented on lib/spack/llnl/util/lock.py
> +            else:
```suggestion
            # os.makedirs can fail in a number of ways when the directory already exists.
            # With EISDIR, we know it exists, and others like EEXIST, EACCES, and EROFS
            # are fine if we ensure that the directory exists.
            # Python 3 allows an exist_ok parameter and ignores any OSError as long as
            # the directory exists.
            if not (e.errno == errno.EISDIR or os.path.isdir(parent)):
```

I don't think we need to warn if we're doing basically what cpython would do in Python 3.

2022-09-06 16:50 UTC, tgamblin approved these changes

2022-09-06 16:51 UTC, merged

2022-09-06 17:10 UTC, sethrj commented
Thanks @tgamblin !

2022-10-07 14:44 UTC, tpdownes commented
@tgamblin the way I read things, this change is not presently slated to make it into v0.18.2. Is it possible to make that happen? We have been hitting it regularly maintaining shared Spack installations for my HPC users.

https://github.com/GoogleCloudPlatform/hpc-toolkit/issues/539

2022-10-07 15:24 UTC, haampie commented
Me and @alalazo are usually the only people doing backports, but I've largely stopped doing that since #24718 because pretty much nothing applies cleanly.

This is a small fix, so we can probably do it.