Checksum: Warn if version is deprecated
LLNL/spack pull request #32438
Opened 2022-08-30 00:53 UTC by tldahlgren

This PR adds a method to check if a version is deprecated *and* will print a warning if that is the case for `spack checksum`.

The current output for a deprecated version can be confusing/misleading, especially when a deprecated package's URL is no longer valid or available.  For example:

```
$ spack info --no-dependencies --no-variants snphylo
Package:   snphylo

Description:
    A pipeline to generate a phylogenetic tree from huge SNP data

Homepage: http://chibba.pgml.uga.edu/snphylo/

Preferred version:  
    20180901      https://github.com/thlee/SNPhylo/archive/refs/tags/20180901.tar.gz

Safe versions:  
    20180901      https://github.com/thlee/SNPhylo/archive/refs/tags/20180901.tar.gz

Deprecated versions:  
    2016-02-04    https://github.com/thlee/SNPhylo/archive/refs/tags/2016-02-04.tar.gz

$ spack checksum snphylo 2016-02-04
==> Error: Could not find any versions for snphylo
```

So this PR adds a warning and elaborates a *little* on the issue.

```
spack checksum snphylo 2016-02-04
==> Warning: Version 2016-02-04 is deprecated
==> Error: Could not find any remote versions for snphylo
```

2022-08-30 00:57 UTC, tldahlgren commented
Initial attempts to add the warning to `spack fetch` and `spack stage` didn't work as the commands go straight to fetching from the cached archive then reporting the package as not found.  Perhaps that will change when a `--fresh` option is added to those commands.

In the above example, the outputs for `spack stage` is:

```
$ spack stage snphylo 2016-02-04
==> Using cached archive: /usr/WS1/dahlgren/releases/spack/var/spack/cache/_source-cache/archive/46/46273bcafc8f6cc2465fc524926af7dd122bcc7b7ce1b7c3f5c278111c3a9ddd.tar.gz
==> Staged snphylo in /var/tmp/dahlgren/spack-stage/spack-stage-snphylo-20180901-zv43ygeisio4cussgerdsgiuqlpezqar
==> Error: Package '2016-02-04' not found.
You may need to run 'spack clean -m'.
```

2022-09-22 16:23 UTC, tldahlgren commented
Here's another case of macOS 3.8 unit test check's code coverage data collection warnings/problems.

2022-10-12 22:39 UTC, tldahlgren commented
Hopefully a rebase to develop gets past the macOS failure that was preventing code coverage from being updated.

2022-10-18 16:19 UTC, alalazo requested changes
Just a minot request, but LGTM

2022-10-18 16:19 UTC, alalazo commented on lib/spack/spack/package_base.py
> +    Returns a list of the deprecated versions of the package.
```suggestion
    """Return True if the version is deprecated, False otherwise.
```

2022-10-18 16:19 UTC, alalazo commented on lib/spack/spack/package_base.py
> +    Returns: (bool) True if version is deprecated, False otherwise
(comment) We can probably omit this, since the first sentence already say that:
```suggestion
```

2022-10-18 16:30 UTC, tldahlgren commented on lib/spack/spack/package_base.py
> +    Returns a list of the deprecated versions of the package.
Thanks for catching that I didn't change the comment to match the final version of the method.

2022-10-18 16:33 UTC, alalazo approved these changes

2022-10-18 22:51 UTC, merged