charliecloud: deprecate old versions
LLNL/spack pull request #32462
Opened 2022-08-31 18:30 UTC by j-ogas

2022-08-31 18:58 UTC, reidpr requested changes

2022-08-31 18:58 UTC, reidpr commented on var/spack/repos/builtin/packages/charliecloud/package.py
>      depends_on("python@3.5:", type="run")
This should be 3.6 I think.

2022-08-31 21:23 UTC, tldahlgren commented
@spackbot fix style

2022-08-31 21:28 UTC, tldahlgren commented
@j-ogas Looks like you need to fix the style and re-push.

2022-08-31 21:29 UTC, tldahlgren submitted a review, later dismissed
LGTM (once style issues resolved).

2022-09-01 20:34 UTC, tldahlgren commented
@spackbot fix style

2022-09-06 15:26 UTC, j-ogas commented
> @j-ogas Looks like you need to fix the style and re-push.

Thanks! I totally forgot about the style linter (ugh, lol). I changed the spacing, hopefully this will work.

2022-09-12 17:34 UTC, j-ogas commented
@tldahlgren I have fixed the style issues, however, we now have another Spack CI error here. Do you have guidance on how to proceed? Hope all is well.

2022-09-12 18:16 UTC, tldahlgren commented
> @tldahlgren I have fixed the style issues, however, we now have another Spack CI error here. Do you have guidance on how to proceed? Hope all is well.

Thanks.  This is a new check organization.  I'll look into it.

2022-09-12 18:16 UTC, tldahlgren commented
@spackbot help

2022-09-12 18:22 UTC, j-ogas commented
> > @tldahlgren I have fixed the style issues, however, we now have another Spack CI error here. Do you have guidance on how to proceed? Hope all is well.
> 
> Thanks. This is a new check organization. I'll look into it.

Awesome, appreciate it!

2022-09-12 19:08 UTC, tldahlgren commented
Failure *may* be intermittent.  Unclear why a couple of required checks are (still) waiting for status to be reported.  Will close and re-open the PR.

2022-09-12 19:09 UTC, tldahlgren approved these changes

2022-09-13 15:25 UTC, merged