Manifest parsing: skip invalid manifest files
LLNL/spack pull request #32467
Opened 2022-08-31 22:14 UTC by scheibelp

`spack external read-cray-manifest` is supposed to skip manifest files if they fail to parse (unless `--fail-on-error` is specified). I did not handle the case where the JSON is not valid (if it does not parse, or if it parses but does not conform to the schema). This widens the set of exceptions caught (the manifest parsing will still terminate if `--fail-on-error` is specified).

2022-09-09 07:45 UTC, tgamblin requested changes

2022-09-09 07:45 UTC, tgamblin commented on lib/spack/spack/cray_manifest.py
> +        raise ManifestValidationError(str(e))
use `six.raise_from()` to keep e around as the cause (at least in Python 3)

2022-09-09 07:45 UTC, tgamblin commented
Minor nitpick above.

Question: does this mean that there invalid json files in recent PE releases that we should be telling HPE about?

2022-09-10 01:02 UTC, scheibelp commented
> Question: does this mean that there are invalid json files in recent PE releases that we should be telling HPE about?

Yes

* the manifest file was invalid according to the schema, but...
* in this case it was an older manifest file that failed to parse (i.e. older schema version) so I was inclined to simply ignore it. If it occurs for newer schema versions I think it would be good to bring up with HPE.

Also: review is addressed (thanks!)

2022-09-14 20:02 UTC, tgamblin approved these changes

2022-09-14 20:02 UTC, merged