e4s ci: add dealii
LLNL/spack pull request #32484
Opened 2022-09-01 19:07 UTC by eugeneswalker

Add `dealii` to E4S CI stack

FYI @wspear @jppelteret @luca-heltai

2022-09-01 19:08 UTC, wspear submitted a review, later dismissed

2022-09-12 12:37 UTC, alalazo requested changes
`dealii` fails to build https://gitlab.spack.io/spack/spack/-/jobs/3168347

2023-05-20 20:01 UTC, wspear approved these changes

2023-05-20 20:13 UTC, eugeneswalker commented
All CI green @alalazo

2023-05-21 19:25 UTC, luca-heltai approved these changes

2023-05-23 19:34 UTC, alalazo approved these changes

2023-05-23 19:34 UTC, merged