e4s ci: add chai +rocm
LLNL/spack pull request #32506
Opened 2022-09-03 10:18 UTC by eugeneswalker

Hoping the merge of https://github.com/spack/spack/pull/32469 has fixed issue with `chai +rocm` in our CI environment.

FYI @wspear @davidbeckingsale

2022-09-12 12:02 UTC, alalazo requested changes
The failure reported here seems legitimate

2022-09-12 18:22 UTC, eugeneswalker commented
> The failure reported here seems legitimate

Umpire issue described here: https://github.com/spack/spack/pull/32504#issuecomment-1242364691

2022-10-12 17:15 UTC, eugeneswalker commented
Once `umpire +rocm` issue is resolved, will move forward with this PR.

2022-10-19 21:57 UTC, wspear submitted a review, later dismissed

2022-10-19 22:39 UTC, eugeneswalker commented
Currently blocked because:
* https://github.com/spack/spack/issues/33426

2022-10-23 16:18 UTC, eugeneswalker commented
Just cherry-picked the commit from https://github.com/spack/spack/pull/33479 to verify that CMAKE_CXX_COMPILER=hipcc unblocks us here.

2022-10-24 16:13 UTC, wspear approved these changes

2022-10-24 16:16 UTC, alalazo approved these changes

2022-10-24 16:16 UTC, merged