bugfix: package hash should affect process, dag, and dunder hashes
LLNL/spack pull request #32516
Opened 2022-09-05 00:54 UTC by tgamblin

This fixes a bug where two installations that differ only by package hash will not show up in `spack find`.

The bug arose because `_cmp_node` on `Spec` didn't include the package hash in its yielded fields. So, any two `Spec` objects that were only different by package hash would appear to be equal and would overwrite each other when inserted into the same `dict`. Note that we could still *install* specs with different package hashes, and they would appear in the database, but we code that needed to put them into data structures that use `__hash__` would have issues.

This PR makes `Spec.__hash__` and `Spec.__eq__` include the `process_hash()`, and it makes `Spec._cmp_node` include the package hash. All of these *should* include all information in a spec so that we don't end up in a situation where we are blind to particular field differences.

Eventually, we should unify the `_cmp_*` methods with `to_node_dict` so there aren't two sources of truth, but this needs some thought, since the `_cmp_*` methods exist for speed. We should benchmark whether it's really worth having two types of hashing now that we use `json` instad of `yaml` for spec hashing.

- [x] Add `package_hash` to `Spec._cmp_node`
- [x] Add `package_hash` to `spack.solve.asp.spec_clauses` so that the `package_hash` will show up in `spack diff`.
- [x] Add `package_hash` to the `process_hash` (which doesn't affect abstract specs but will make concrete specs correct)
- [x] Make `_cmp_iter` report the dag_hash so that no two specs with different process hashes will be considered equal.

2022-09-15 21:46 UTC, tldahlgren requested changes
Minor requested change.  (Still want to test something out.)

2022-09-15 21:46 UTC, tldahlgren commented on lib/spack/spack/spec.py
> +        # TODO: having two types of hashing now that we use `json` instad of `yaml` for
```suggestion
        # TODO: having two types of hashing now that we use `json` instead of `yaml` for
```

2022-09-15 21:47 UTC, trws commented on lib/spack/spack/spec.py
> +        # TODO: they exist for speed.  We should benchmark whether it's really worth
Yes, and whether caching the result of to_node_dict is better or worse than using the generator.

2022-09-15 21:47 UTC, trws approved these changes, later dismissed

2022-09-15 21:56 UTC, tldahlgren commented
> Minor requested change. (Still want to test something out.)

LGTM *except* for the suggested comment typo.

2022-09-16 00:04 UTC, tgamblin commented on lib/spack/spack/spec.py
> +        # TODO: having two types of hashing now that we use `json` instad of `yaml` for
done

2022-09-16 00:04 UTC, tgamblin commented
@tldahlgren @trws ready for review again

2022-09-16 00:12 UTC, tldahlgren approved these changes
LGTM

2022-09-16 00:57 UTC, merged

2024-04-02 16:09 UTC, haampie commented
This PR makes `Spec(...) < Spec(...)` non-deterministic for abstract specs (over time).

Basically `<` compares the roots in a sensible way, and if equal, compares hashes. The latter is arbitrary by design, and also awkwardly depends on the contents of package.py, which may change over time.