Add wg21_p2300_std_execution as p2300 package
LLNL/spack pull request #32531
Opened 2022-09-06 14:07 UTC by aurianer

Just adds the minimum to package the main branch of the wg21_p2300_std_execution repo
Fixes https://github.com/pika-org/pika/issues/301

2022-09-06 14:12 UTC, msimberg requested changes
Besides not benefitting from the `ninja` dependency, this looks good to me!

2022-09-06 14:12 UTC, msimberg commented on var/spack/repos/builtin/packages/p2300/package.py
> +    depends_on("ninja", type="build")
I think this can be removed since it's header-only.

2022-09-06 14:41 UTC, msimberg commented on var/spack/repos/builtin/packages/p2300/package.py
> +    generator = "Ninja"
This line also needs to be removed.

2022-09-07 07:46 UTC, msimberg approved these changes, later dismissed

2022-09-12 07:56 UTC, msimberg submitted a review, later dismissed

2022-09-12 08:45 UTC, alalazo approved these changes

2022-09-12 09:04 UTC, merged