New package: py-scanpy
LLNL/spack pull request #32565
Opened 2022-09-07 20:42 UTC by qwertos

2022-09-09 02:59 UTC, adamjstewart requested changes

2022-09-09 02:59 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-scanpy/package.py
> +    depends_on('py-statsmodels@0.10.0rc2:', type=('build', 'run'))
```suggestion
    depends_on('py-statsmodels@0.10.0:', type=('build', 'run'))
```
Spack sorts rc versions incorrectly

2022-09-09 02:59 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-scanpy/package.py
> +    depends_on('py-tomli', type=('build', 'run'))
```suggestion
    depends_on('py-tomli', type='build')
```

2022-10-05 16:51 UTC, adamjstewart approved these changes, later dismissed

2022-10-05 16:51 UTC, adamjstewart commented
@spackbot fix style

2022-10-06 08:27 UTC, alalazo approved these changes

2022-10-06 08:27 UTC, merged