Avoid `xxmr2d:out of memory` error for scalapack-2.2.0
LLNL/spack pull request #32572
Opened 2022-09-08 03:24 UTC by m3lab-zzl

In file `scalapack-2.2.0/REDIST/SRC/pgemraux.c`, change variable n type from `Int` to `long long`,  so that `xxmr2d:out of memory` can be avoid.

The created patch file was simply generated by:

$ diff `old_pgemraux.c` `new_pgemraux.c`

Further modification may be made to complete this fix.

2022-09-12 09:38 UTC, alalazo commented
@spackbot fix style

2022-09-12 10:05 UTC, alalazo requested changes
There are flake 8 errors that our bot cannot fix. Could you take care of them?

2022-09-15 08:49 UTC, m3lab-zzl commented
> There are flake 8 errors that our bot cannot fix. Could you take care of them?

@alalazo Hi, I am not sure about the details, could you take a look and tell me what should I do to fix problems if there is any.

2022-09-20 12:27 UTC, alalazo reviewed
There are failures in our build pipelines to be fixed as well, before this can be considered. For instance: https://gitlab.spack.io/spack/spack/-/pipelines/172901/failures

2023-02-17 14:12 UTC, closed without merging