Add pika 0.8.0
LLNL/spack pull request #32577
Opened 2022-09-08 13:38 UTC by msimberg

- adds pika 0.8.0
- updates the cmake version requirement from 0.8.0 onwards
- constrains build with `hipcc` to only be applied for versions older than 0.8.0
- adds missing `hip` dependency for `+rocm` (it was always there implicitly because of hipblas/rocblas, but it should be an explicit dependency)
- constrains hip to at least 5.2.0 from pika 0.8.0 onwards

2022-09-08 13:54 UTC, aurianer submitted a review, later dismissed
LGTM thanks!

2022-09-09 08:40 UTC, albestro requested changes

2022-09-09 08:40 UTC, albestro commented on var/spack/repos/builtin/packages/pika/package.py
> +    depends_on("hip", when="+rocm")
This line is not needed since it is already enforced by the `ROCMPackage` from which pika inherits from.

https://github.com/spack/spack/blob/0d18c32bca8398e2daa736a940154caa235cbacc/lib/spack/spack/build_systems/rocm.py#L125

2022-09-09 08:45 UTC, msimberg commented on var/spack/repos/builtin/packages/pika/package.py
> +    depends_on("hip", when="+rocm")
Ah, that explains it better. Thanks @albestro for pointing this out! Removed.

2022-09-09 08:51 UTC, albestro approved these changes

2022-09-10 04:49 UTC, teonnik approved these changes

2022-09-12 08:41 UTC, alalazo approved these changes

2022-09-12 08:41 UTC, merged