packages/phist: new version 1.10
LLNL/spack pull request #32581
Opened 2022-09-08 20:33 UTC by jthies

2022-09-11 01:02 UTC, glennpj requested changes

2022-09-11 01:02 UTC, glennpj commented on var/spack/repos/builtin/packages/phist/package.py
> +    conflicts("^trilinos@:13.4", when="@1.10:")
I do not think the `conflicts` directives are correct here. The above is saying that `trilinos@13.4.x` does not work with any version of `phist`.

2022-09-12 18:30 UTC, tldahlgren approved these changes
Confirmed sha256.

2022-09-13 22:21 UTC, glennpj approved these changes

2022-09-13 22:21 UTC, merged