Fenicsx v0.5.0
LLNL/spack pull request #32611
Opened 2022-09-12 14:12 UTC by ma595

Update fenicsx packages to latest tagged releases (v0.5.0).

2022-09-12 14:18 UTC, nate-sime approved these changes, later dismissed

2022-09-12 14:28 UTC, garth-wells requested changes
Looks good, I've left some inline comments.

`(py)-fenics-dolfinx@main` no longer depends on `xtl` and `xtensor`.

Has this PR been tested using the CI at https://github.com/FEniCS/dolfinx/actions/workflows/spack.yml?

2022-09-12 14:28 UTC, garth-wells commented on var/spack/repos/builtin/packages/fenics-basix/package.py
>      depends_on("xtl@0.7.2:")
Basix v0.5 no longer depends on `xtl` or `xtensor`.

2022-09-12 14:28 UTC, garth-wells commented on var/spack/repos/builtin/packages/py-fenics-basix/package.py
> +    depends_on("fenics-basix@0.5.0", type=("build", "run"), when="@0.5.0")
v0.5 no longer depends on `xtl` or `xtensor`.

2022-09-14 09:49 UTC, garth-wells approved these changes

2022-09-14 10:09 UTC, chrisrichardson approved these changes

2022-09-14 10:17 UTC, nate-sime approved these changes

2022-09-15 06:51 UTC, garth-wells commented
@tldahlgren I think this is ready to merge now.

2022-09-15 14:12 UTC, jhale commented
I have a slightly refined version of this patch that better reflects some upcoming changes on `main` and marks some of the older versions as deprecated which will allow us to reduce complexity of these files in the future. I will push it to a new PR shortly.

2022-09-15 15:10 UTC, tldahlgren approved these changes
Confirmed all new sha256.

2022-09-15 15:11 UTC, merged