New package: Parsel
LLNL/spack pull request #32613
Opened 2022-09-12 16:36 UTC by frerappa

Parsel is a BSD-licensed Python library to extract and remove data from HTML and XML using XPath and CSS selectors, optionally combined with regular expressions.
@hyviquel

2022-09-13 15:19 UTC, adamjstewart requested changes
If this is your first time packaging Python libraries, I recommend reading through https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html

2022-09-13 15:19 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-parsel/package.py
> +    depends_on("py-w3lib", type="build")
Missing build deps on setuptools and pytest-runner

Missing dependency versions:
```python
install_requires = [                                                                     
    'w3lib>=1.19.0',                                                                     
    'lxml',                                                                              
    'six>=1.6.0',                                                                        
    'cssselect>=0.9'                                                                     
]                                                                                        
extras_require = {}                                                                      
                                                                                         
if not has_environment_marker_platform_impl_support():                                   
    if sys.version_info[0:2] < (3, 0):                                                   
        install_requires.append("functools32")                                           
else:                                                                                    
    extras_require[":python_version<'3.0'"] = ["functools32"]   
```
`install_requires` should be `type=("build", "run")`

2022-09-13 15:19 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-w3lib/package.py
> +    - extract arguments from urls
When you run `spack info`, these newline characters are removed, so this won't be very legible. I would remove everything except the first line.

2022-09-13 15:19 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-parsel/package.py
> +    url = "https://github.com/scrapy/parsel/archive/refs/tags/v1.6.0.tar.gz"
https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#pypi-vs-github

2022-09-13 15:19 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-w3lib/package.py
> +    url = "https://github.com/scrapy/w3lib/archive/refs/tags/v1.22.0.tar.gz"
https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#pypi-vs-github

2022-09-13 15:19 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-w3lib/package.py
> +    version("1.22.0", sha256="d388f06a11008c68f96c95224e224691e5ce9c13733d89bc85a550c448f83c97")
Missing build dep on setuptools

Missing build/run dep on six:
```python
    install_requires=['six >= 1.4.1'],                                                   
```

2022-11-17 02:58 UTC, bernhardkaindl commented
@frerappa Would you apply the changes from the review?

2022-11-25 23:38 UTC, bernhardkaindl commented
> @frerappa Would you apply the changes from the review?

@frerappa ping?

2023-02-21 06:31 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2023-02-21 06:31 UTC, closed without merging