Added variant to ensure Arm Forge license acceptance
LLNL/spack pull request #32635
Opened 2022-09-13 16:35 UTC by kent-cheung-arm

2022-09-13 16:43 UTC, tldahlgren requested changes

2022-09-13 16:43 UTC, tldahlgren commented on var/spack/repos/builtin/packages/arm-forge/package.py
> +        description='Accept the EULA',
Black style check doesn't like single quotes:

```suggestion
        description="Accept the EULA",
```

2022-09-13 16:43 UTC, tldahlgren commented on var/spack/repos/builtin/packages/arm-forge/package.py
> +        if not self.spec.variants['accept-eula'].value:
```suggestion
        if not self.spec.variants["accept-eula"].value:
```

2022-09-13 16:44 UTC, tldahlgren commented on var/spack/repos/builtin/packages/arm-forge/package.py
> +    license_url = "https://developer.arm.com/documentation/101169/latest/Use-Arm-Licence-Server"
Confirmed URL exists

2022-09-13 17:14 UTC, NickRF approved these changes, later dismissed

2022-09-13 17:17 UTC, tldahlgren submitted a review, later dismissed
LGTM

2022-09-15 00:20 UTC, tldahlgren commented
@spackbot run pipeline

2022-09-16 12:34 UTC, kent-cheung-arm commented
Thanks, @tldahlgren. Could I trouble you for another review approval please?

2022-09-19 20:45 UTC, tldahlgren approved these changes

2022-09-19 20:45 UTC, merged