pango: harfbuzz+coretext required on macOS
LLNL/spack pull request #32637
Opened 2022-09-13 17:02 UTC by adamjstewart

Successfully builds on macOS 10.15.7 (x86_64) with Apple Clang 12.0.0.

Without this change, the pango build was failing with:
```
../spack-src/pango/pangocoretext.c:27:10: fatal error: 'hb-coretext.h' file not found
```

2022-09-13 17:27 UTC, tldahlgren submitted a review, later dismissed
Confirmed sha256.  Rest LGTM.

2022-09-13 17:28 UTC, tldahlgren commented
@spackbot fix style

2022-09-20 17:14 UTC, becker33 requested changes

2022-09-20 17:14 UTC, becker33 commented on var/spack/repos/builtin/packages/harfbuzz/package.py
> +        elif "~coretet" in self.spec:
```suggestion
        elif "~coretext" in self.spec:
```

2022-09-20 17:14 UTC, becker33 commented on var/spack/repos/builtin/packages/harfbuzz/package.py
> +        elif "~coretet" in self.spec:
```suggestion
        elif "~coretext" in self.spec:
```

2022-09-20 17:23 UTC, becker33 approved these changes

2022-09-20 23:57 UTC, merged