added missing dependency for py-msgpack that breaks neovim
LLNL/spack pull request #32631
Opened 2022-09-13 12:15 UTC by robertu94

2022-09-13 15:38 UTC, adamjstewart requested changes
What's the error message you see? msgpack has no imports of greenlet anywhere...

2022-09-13 15:40 UTC, robertu94 commented
If you build neovim, and try to use py-nvim-remote or py-nvim you get an import error for greenlet when you call ':checkhealth'

2022-09-13 15:43 UTC, adamjstewart commented
What is the stacktrace of that import error? It doesn't seem to be coming from msgpack...

2022-09-13 20:05 UTC, robertu94 commented
@adamjstewart good catch.  Sorry for the noise.  The change should have been on py-pynvim.

Here is where the requirement is declared: https://github.com/neovim/pynvim/blob/d549371b6fb647304cff5f88a71e2bc42d2ed30a/setup.py#L33

2022-09-13 20:07 UTC, robertu94 commented
The stack trace looks like this:

```console
## Python 3 provider (optional)                                                                         
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.                  
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.            
  - INFO: Executable: /gpfs/fs1/home/runderwood/git/spack-bebop/opt/spack/linux-centos7-broadwell/gcc-    10.2.0/python-3.9.13-atmnl5spo3qj7nsu44fbhlefwjrczmtr/bin/python3                                     
  - INFO: Other python executable: /usr/bin/python3                                                     
  - ERROR: Command error (job=7, exit code 1): `'/gpfs/fs1/home/runderwood/git/spack-bebop/opt/spack/     linux-centos7-broadwell/gcc-10.2.0/python-3.9.13-atmnl5spo3qj7nsu44fbhlefwjrczmtr/bin/python3' -c       'import sys; sys.path = list(filter(lambda x: x != "", sys.path)); import neovim; print(neovim.         __file__)'` (in '/gpfs/fs1/home/runderwood/git/spack-bebop')
    stderr: Traceback (most recent call last):  File "<string>", line 1, in <module>  File "/gpfs/fs1/      home/runderwood/git/spack-bebop/opt/spack/linux-centos7-broadwell/gcc-10.2.0/py-pynvim-0.4.3-           nuu2k6amlhgdfuqp575ifdwbscjwjtbw/lib/python3.9/site-packages/neovim/__init__.py", line 5, in            <module>    import pynvim  File "/gpfs/fs1/home/runderwood/git/spack-bebop/opt/spack/linux-centos7-     broadwell/gcc-10.2.0/py-pynvim-0.4.3-nuu2k6amlhgdfuqp575ifdwbscjwjtbw/lib/python3.9/site-packages/      pynvim/__init__.py", line 11, in <module>    from pynvim.msgpack_rpc import (ErrorResponse,             child_session, socket_session,  File "/gpfs/fs1/home/runderwood/git/spack-bebop/opt/spack/linux-        centos7-broadwell/gcc-10.2.0/py-pynvim-0.4.3-nuu2k6amlhgdfuqp575ifdwbscjwjtbw/lib/python3.9/site-       packages/pynvim/msgpack_rpc/__init__.py", line 10, in <module>    from pynvim.msgpack_rpc.session       import ErrorResponse, Session  File "/gpfs/fs1/home/runderwood/git/spack-bebop/opt/spack/linux-         centos7-broadwell/gcc-10.2.0/py-pynvim-0.4.3-nuu2k6amlhgdfuqp575ifdwbscjwjtbw/lib/python3.9/site-       packages/pynvim/msgpack_rpc/session.py", line 7, in <module>    import greenletModuleNotFoundError:     No module named 'greenlet'
  - INFO: Python version: 3.9.13                                                                        
  - INFO: pynvim version: unable to load neovim Python module                                           
  - ERROR: pynvim is not installed.                                                                     
    Error: unable to load neovim Python module                                                              - ADVICE:                                                                                           
      - Run in shell: /gpfs/fs1/home/runderwood/git/spack-bebop/opt/spack/linux-centos7-broadwell/gcc-        10.2.0/python-3.9.13-atmnl5spo3qj7nsu44fbhlefwjrczmtr/bin/python3 -m pip install pynvim
```

2022-09-13 22:02 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pynvim/package.py
>      depends_on("py-msgpack", type=("build", "run"))
```suggestion
    depends_on("py-msgpack@0.5:", type=("build", "run"))
```
There are also some missing dependencies for Python 3.3 and older, not sure if you want to add them:
```python
depends_on("py-pyuv@1:", when="^python@:3.3 platform=windows", type=("build", "run"))
for platform in ["linux", "darwin", "cray"]:
    depends_on("py-trollius", when="^python@:3.3 platform=" + platform, type=("build", "run"))

2022-09-15 14:45 UTC, adamjstewart approved these changes

2022-09-15 14:45 UTC, merged