Axom: bring in changes from axom repo
LLNL/spack pull request #32643
Opened 2022-09-13 21:43 UTC by white238

It has been a while since I pulled in the updates from the Axom repo.

This mainly adds HIP support and uses a Spack's BLT instead of the internal submodule.

This also removes the the need to pull submodules with the source.  The `data` submodule is particularly large.

2022-09-13 22:03 UTC, white238 commented
@spackbot fix style

2022-09-15 00:18 UTC, tldahlgren requested changes
I have not reviewed the rest of this PR but the suggested change will at least help resolve the pipeline stack failure.

2022-09-15 00:18 UTC, tldahlgren commented on var/spack/repos/builtin/packages/axom/package.py
> +        options.append("-DBLT_SOURCE_DIR:PATH={0}".format(spec["blt"].prefix))
```suggestion
        options.append("-DBLT_SOURCE_DIR:PATH={0}".format(self.spec["blt"].prefix))
```

2022-09-28 03:41 UTC, white238 commented
I have tested this in Axom's large set of specs across many LC machines.  It should be ready to go.

2022-09-29 22:01 UTC, tldahlgren approved these changes, later dismissed
Other than my question and aversion to hard-coded paths, this LGTM.

@scheibelp Did you want to review this package, especially regarding the cray-specific changes?

2022-09-29 22:01 UTC, tldahlgren commented on var/spack/repos/builtin/packages/axom/package.py
> +    depends_on("hypre~fortran", when="+mfem+rocm")
Given the comment, should this be `when="+mfem+rocm platform=cray"`?

2022-09-29 22:01 UTC, tldahlgren commented on var/spack/repos/builtin/packages/axom/package.py
> +                    cray_exclude_path = "/opt/cray/pe/gcc/8.1.0/snos/lib64"
😱  Hard-coded paths here and below.

2022-09-29 22:13 UTC, white238 commented on var/spack/repos/builtin/packages/axom/package.py
> +                    cray_exclude_path = "/opt/cray/pe/gcc/8.1.0/snos/lib64"
I know but they are unfortunately required for our platforms and are guarded against non-existence.

Hopefully in the future I can make them less hardcoded.

2022-09-30 01:36 UTC, white238 commented on var/spack/repos/builtin/packages/axom/package.py
> +                    cray_exclude_path = "/opt/cray/pe/gcc/8.1.0/snos/lib64"
I looked it over and this is untested and possibly from an old system. I removed it.

2022-09-30 01:37 UTC, white238 commented on var/spack/repos/builtin/packages/axom/package.py
> +    depends_on("hypre~fortran", when="+mfem+rocm")
Just removed it. I think its from an old spec that we dont use/test anymore.

2022-10-03 19:11 UTC, white238 commented
> Other than my question and aversion to hard-coded paths, this LGTM.
> 
> @scheibelp Did you want to review this package, especially regarding the cray-specific changes?

This has been addressed by just removing it

2022-10-03 19:19 UTC, becker33 approved these changes

2022-10-03 19:19 UTC, becker33 commented on var/spack/repos/builtin/packages/axom/package.py
>      variant("cpp14", default=True, description="Build with C++14 support")
We should make this variant only appear for `axom@:0.6.0`

`variant("cpp14", default=True, when="@:0.6.0", ...)`

doesn't need to be part of this PR

2022-10-03 19:19 UTC, becker33 commented on var/spack/repos/builtin/packages/axom/package.py
> +        if "+devtools" in spec and "toss_4" not in self._get_sys_type(spec):
Short term hack to support a problem specific to LC systems

2022-10-03 20:02 UTC, merged