Adapt pika to use the p2300 spack package
LLNL/spack pull request #32667
Opened 2022-09-15 15:33 UTC by aurianer

2022-09-15 15:42 UTC, msimberg requested changes

2022-09-15 15:42 UTC, msimberg commented on var/spack/repos/builtin/packages/pika/package.py
> +            implementation for sender/receiver functionality", when="@0.8:")
```suggestion
            implementation for sender/receiver functionality", when="@main")
```

2022-09-15 15:42 UTC, msimberg commented on var/spack/repos/builtin/packages/pika/package.py
> +                when="cxxstd={0}".format(cxxstd))
Are the formatting changes necessary for CI to pass?

2022-09-15 15:42 UTC, msimberg commented on var/spack/repos/builtin/packages/pika/package.py
> +    depends_on("p2300", when="@0.8: +p2300")
```suggestion
    depends_on("p2300", when="+p2300")
```

2022-09-15 15:53 UTC, aurianer commented on var/spack/repos/builtin/packages/pika/package.py
> +                when="cxxstd={0}".format(cxxstd))
yes looks like, I will update

2022-09-16 09:04 UTC, msimberg commented
This looks good to me besides the formatting changes required by CI. However, I'm just waiting for us to merge https://github.com/pika-org/pika/pull/436 before actually approving this since it's required for this to actually work.

2022-09-16 09:10 UTC, teonnik approved these changes, later dismissed

2022-09-20 06:17 UTC, teonnik approved these changes, later dismissed

2022-09-20 13:02 UTC, aurianer commented
https://github.com/pika-org/pika/pull/436 has been merged, feel free to merge when ci has passed

2022-09-20 15:26 UTC, msimberg approved these changes, later dismissed

2022-09-20 15:39 UTC, msimberg commented
Is there anything required on this PR to get `waiting for style check to succeed` to finish?

2022-09-22 10:02 UTC, aurianer commented
I force pushed as the CI seemed to be stuck

2022-09-26 13:07 UTC, haampie approved these changes

2022-09-26 13:07 UTC, merged