Update py-poetry to 1.2.1
LLNL/spack pull request #32776
Opened 2022-09-23 07:28 UTC by iarspider

2022-09-23 17:23 UTC, tldahlgren submitted a review, later dismissed
Confirmed all new sha256, including for new packages.

I'm inclined to ask that the `when` options *always* be provided before the `type` since that is 1) more standard and 2) aid "readability" (as in `depends on when` is typically how the directives are read).

2022-09-23 17:55 UTC, tldahlgren approved these changes, later dismissed
Re-confirmed sha256.

Thanks for the argument ordering fix.

2022-09-23 18:23 UTC, adamjstewart requested changes

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cleo/package.py
>      version("0.8.1", sha256="3d0e22d30117851b45970b6c14aca4ab0b18b1b53c8af57bed13208147e4069f")
```suggestion
    version("0.8.1", sha256="3d0e22d30117851b45970b6c14aca4ab0b18b1b53c8af57bed13208147e4069f", preferred=True)
```
We don't want to install an alpha release by default

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cleo/package.py
> +    depends_on("py-poetry-core@1:1", when="@1.0.0a5:", type="build")
```suggestion
    depends_on("py-poetry-core@1", when="@1.0.0a5:", type="build")
```

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cleo/package.py
> +    depends_on("py-pylev@1.3.0:", when="@1.0.0a5:", type=("build", "run"))
```suggestion
    depends_on("py-pylev@1.3:1", when="@1.0.0a5:", type=("build", "run"))
```

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cleo/package.py
> +    depends_on("py-crashtest@0.3.1:0", when="@1.0.0a5:", type=("build", "run"))
```suggestion
    depends_on("py-crashtest@0.3.1:0.3", when="@1.0.0a5:", type=("build", "run"))
```
See https://python-poetry.org/docs/dependency-specification/#caret-requirements

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-hatchling-vcs/package.py
> +class PyHatchlingVcs(PythonPackage):
```suggestion
class PyHatchVcs(PythonPackage):
```
Same with directory name

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-hatchling-vcs/package.py
> +    depends_on("py-setuptools-scm@:5", when="^python@:2", type="build")
These should all be `type=("build", "run")`

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-jsonschema/package.py
> +    depends_on("py-hatchling-vcs", when="@4.10:", type="build")
```suggestion
    depends_on("py-hatch-vcs", when="@4.10:", type="build")
```

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pkgutil-resolve-name/package.py
> +    depends_on("py-flit-core@2:2", type="build")
```suggestion
    depends_on("py-flit-core@2", type="build")
```

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-platformdirs/package.py
> +    depends_on("py-hatchling-vcs", when="@2.5.2:", type="build")
```suggestion
    depends_on("py-hatch-vcs", when="@2.5.2:", type="build")
```

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-platformdirs/package.py
> +    depends_on("py-setuptools-scm@5:+toml", when="@:2.5", type="build")
```suggestion
    depends_on("py-setuptools@44:", when="@:2.5.1", type="build")
    depends_on("py-setuptools-scm@5:+toml", when="@:2.5.1", type="build")
```
`@:2.5` includes 2.5.2

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry-core/package.py
>      depends_on("py-importlib-metadata@1.7:1", when="^python@2.7,3.5:3.7", type=("build", "run"))
This is now 1.7+ in 1.2.0

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry-plugin-export/package.py
> +    depends_on("python@3.7:", type=("build", "run"))
```suggestion
    depends_on("python@3.7:3", type=("build", "run"))
```

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry-plugin-export/package.py
> +    depends_on("py-poetry-core@1.1.0:1", type="build")
```suggestion
    depends_on("py-poetry@1.2:1", type=("build", "run"))
    depends_on("py-poetry-core@1.1:1", type=("build", "run"))
```

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry/package.py
>      depends_on("python@2.7,3.5:3", type=("build", "run"))
Python 3.7:3 now

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +    depends_on("py-poetry-core@1.1.0", type=("build", "run"), when="@1.2.0:")
1.2.0 now

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +    depends_on("py-poetry-plugin-export@1.0.6:1", type=("build", "run"), when="@1.2.0:")
1.0.7:1 now

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +    depends_on("py-cleo@1.0.0a5:", type=("build", "run"), when="@1.2.0:")
Missing dep:
```
"backports.cached-property" = { version = "^1.0.2", python = "<3.8" }
```

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +    depends_on("py-dulwich@0.20.44:0", when="@1.2:")
Didn't check the rest of these, but I'm guessing not all of them are correct for 1.2.1

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-shellingham/package.py
> +    depends_on("python@3.7:", when="@1.5.0:", type=("build", "run"))
```suggestion
    depends_on("python@3.4:", when="@1.5.0:", type=("build", "run"))
```

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-tomlkit/package.py
> +    depends_on("python@3.6:", when="@0.11.0:", type=("build", "run"))
Should be 3.6:3 for the latest version, haven't checked older versions

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +    depends_on("py-cleo@1.0.0a5:", type=("build", "run"), when="@1.2.0:")
```suggestion
    depends_on("py-cleo@1:", type=("build", "run"), when="@1.2.0:")
```
Spack's version comparison is broken, and 1.0.0 is considered to be < 1.0.0a5. So if you keep the logic as is, it won't apply once cleo 1.0.0 is released

2022-09-23 18:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-xattr/package.py
>      depends_on("python@2.7:")
```suggestion
    depends_on("python@2.7:", type=("build", "run"))
```

2022-09-23 19:42 UTC, iarspider commented
@spackbot fix style

2022-09-24 20:25 UTC, adamjstewart requested changes

2022-09-24 20:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cleo/package.py
> +    depends_on("python@3.7:3", when="@1.0.0a5:", type=("build", "run"))
We should probably just say `@1:`. Once 1.0.0 is officially released, it will likely have these same dependencies

2022-09-24 20:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cleo/package.py
>      depends_on("py-clikit@0.6.0:0.6", type=("build", "run"))
clikit is no longer needed in the latest version

2022-09-24 20:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-dulwich/package.py
>      depends_on("py-urllib3@1.24.1:", type=("build", "run"))
1.25+ is needed now

2022-09-24 20:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-dulwich/package.py
>      depends_on("py-certifi", type=("build", "run"))
certifi is no longer needed

2022-09-24 20:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-jsonschema/package.py
>      depends_on("py-vcversioner", when="@:2", type="build")
setuptools-scm is no longer required

2022-09-24 20:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry-core/package.py
> +    depends_on("py-importlib-metadata@1.7.0:", when="@1.2.0: ^python@:3.7", type=("build", "run"))
```suggestion
    depends_on("py-importlib-metadata@1.7:1", when="@:1.0 ^python@2.7,3.5:3.7", type=("build", "run"))
    depends_on("py-importlib-metadata@1.7:", when="@1.1: ^python@:3.7", type=("build", "run"))
```

2022-09-24 20:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +    depends_on("py-poetry-plugin-export@1.0.7:1", when="@1.2.0:", type=("build", "run"))
```suggestion
    depends_on("py-poetry-plugin-export@1.0.7:1", when="@1.2.1:", type=("build", "run"))
```

2022-09-24 20:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +    depends_on("py-poetry-plugin-export@1.0.7:1", when="@1.2.0:", type=("build", "run"))
Missing dependency on:
```
"backports.cached-property" = { version = "^1.0.2", python = "<3.8" }
```

2022-09-24 20:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry/package.py
>      )
Cachecontrol seems wrong, there should be no conditions on Python version, at least for the latest version of poetry

2022-09-24 20:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +    depends_on("py-keyring@21.2.0:", when="@1.1.13: ^python@3.6:3", type=("build", "run"))
Should be no condition on Python version, at least in the latest version. Also, note that Spack merges all these dependency constraints, not overwrites them. So right now, you're saying that poetry depends on keyring@20 AND keryring@21: which doesn't make a lot of sense

2022-09-24 20:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +    depends_on("py-virtualenv@20.4.3:20.4.5,20.4.7:", when="@1.2:", type=("build", "run"))
```suggestion
    depends_on("py-virtualenv@20.4.3:20.4.4,20.4.7:", when="@1.2:", type=("build", "run"))
```

2022-09-24 20:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +    depends_on("py-dulwich@0.20.46:0.20", when="@1.2.1:")
This package would be much easier to review if the dependencies were listed in the same order as the `pyproject.toml`

2022-09-25 01:26 UTC, adamjstewart requested changes

2022-09-25 01:26 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-backports-cached-property/package.py
> +    depends_on("py-setuptools", type="build")
```suggestion
    depends_on("py-setuptools@42:", type="build")
    depends_on("py-setuptools-scm@3.4:+toml", type="build")
```

2022-09-25 01:26 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +        "py-backports-cached-property@1.0.2:1", when="@1.2.1: ^python@:3.8", type=("build", "run")
```suggestion
        "py-backports-cached-property@1.0.2:1", when="@1.2.1: ^python@:3.7", type=("build", "run")
```

2022-09-25 01:26 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +    depends_on("py-clikit@0.6.2:0.6", type=("build", "run"))
Not needed in the latest release

2022-09-25 17:36 UTC, adamjstewart approved these changes

2022-09-25 17:36 UTC, merged

2022-09-26 09:29 UTC, alalazo commented on var/spack/repos/builtin/packages/py-pkgutil-resolve-name/package.py
> +    """Resolve a name to an object. A backport of Python 3.9’s `pkgutil.resolve_name`"""
This one broke `develop`, see e.g. https://github.com/spack/spack/actions/runs/3126480970/jobs/5072031733 The issue is that we have a UTF-8 character that is not understood by Python 2.7 (`’` instead of `'`). I am wondering why this was not caught by CI.