py-coverage: add 6.4.4
LLNL/spack pull request #32789
Opened 2022-09-23 13:29 UTC by manuelakuhn

https://github.com/nedbat/coveragepy/tree/6.4.4

[This line](https://github.com/nedbat/coveragepy/blob/6.4.4/setup.py#L111) in the `setup.py` where they specify `python_full_version<="3.11.0a6"` was not clear to me, so I restricted the python version used when `+toml` is activated.

2022-09-23 16:30 UTC, tldahlgren approved these changes, later dismissed
Confirmed sha256.

2022-09-24 20:56 UTC, adamjstewart requested changes

2022-09-24 20:56 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-coverage/package.py
> +    depends_on("python@3.7:3.11.0a6", when="@6.4.1: +toml", type=("build", "run"))
Undo this change and use this instead:
```python
depends_on('py-tomli', when='@6: +toml ^python@:3.10', type=('build', 'run'))
```

2022-09-26 09:01 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-coverage/package.py
> +    depends_on("python@3.7:3.11.0a6", when="@6.4.1: +toml", type=("build", "run"))
Done

2022-09-26 15:46 UTC, adamjstewart approved these changes

2022-09-26 15:46 UTC, merged