estarlight, dpmjet: new packages
LLNL/spack pull request #32834
Opened 2022-09-26 22:58 UTC by wdconinc

Two new monte carlo event generators in nuclear/hadronic/high energy physics:
- [DPMJET](https://github.com/DPMJET/DPMJET), used in fluka and others,
- [estarlight](https://github.com/eic/estarlight): an electron-hadron extension of [starlight](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/starlight/package.py) (already in spack, but this package is a separate code base that does not link against the starlight package).

Sufficient for draft PR but the following is still TODO:
- dpmjet: waiting for bugfix which avoids the need for the `pylib` filter
- estarlight: waiting for 1.0.1 release with one remaining bugfix for gcc@10:

2022-11-17 03:09 UTC, bernhardkaindl commented
@wdconinc: You opened this as a draft, did you implement your TODOs now and it can be merged?

2023-02-06 12:26 UTC, alalazo requested changes
A minor cleanup requested

2023-02-06 12:26 UTC, alalazo commented on var/spack/repos/builtin/packages/dpmjet/package.py
> +        pass
```suggestion
```

2023-02-06 12:26 UTC, alalazo commented on var/spack/repos/builtin/packages/dpmjet/package.py
> +        pass
```suggestion
```

2023-02-06 15:53 UTC, alalazo approved these changes

2023-02-06 16:09 UTC, merged