Add checksum for py-ipywidgets 8.0.2, py-jupyterlab-widgets 3.0.3, add py-jupyterpackaging10
LLNL/spack pull request #32847
Opened 2022-09-27 11:59 UTC by iarspider

2022-09-27 15:30 UTC, adamjstewart requested changes

2022-09-27 15:30 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-jupyterlab-widgets/package.py
>      depends_on("py-setuptools@40.8.0:", type="build")
If we're installing from a wheel, I think you can remove all of these build-only dependencies

2022-09-27 15:30 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-widgetsnbextension/package.py
> +    depends_on("py-jupyter-packaging10", when="@4.0.3:", type="build")
I don't think you need to add a new package for this, `py-jupyter-packaging11` will satisfy `~=0.10`

2022-09-27 15:30 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-widgetsnbextension/package.py
> +    depends_on("py-setuptools", when="@:3", type="build")
Setuptools is still needed I believe

2022-09-27 15:42 UTC, iarspider commented on var/spack/repos/builtin/packages/py-widgetsnbextension/package.py
> +    depends_on("py-setuptools", when="@:3", type="build")
I didn't see any reference to setuptools in setup.{py,cfg} and pyproject.toml.

2022-09-27 15:44 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-widgetsnbextension/package.py
> +    depends_on("py-setuptools", when="@:3", type="build")
`setup.py` contains `from setuptools import setup`

2022-09-27 16:44 UTC, adamjstewart approved these changes

2022-09-28 08:01 UTC, iarspider commented
@spackbot run pipeline

2022-09-28 09:45 UTC, merged