Filter libtools when building with dpcpp
LLNL/spack pull request #32876
Opened 2022-09-28 14:20 UTC by cmacmackin

Due to a [known issue](https://community.intel.com/t5/Intel-oneAPI-Data-Parallel-C/dpcpp-and-GNU-Autotools/m-p/1296985) with dpcpp, autotool-based builds that try to use it will fail; see #32863. This pull request modifies the Autotools package class to filter spurious object files out of the libtool script, as is already done to address issues with other compilers.

2022-09-29 08:56 UTC, alalazo commented
@spackbot run pipeline

2022-10-03 07:40 UTC, haampie commented
I think the solution is alright, but is this still an issue with the latest dpcpp? If so, can you please ask for the status regarding

> We are working on your issue internally. We will get back to you soon.

Otherwise:

1. Please add a comment clearly explaining why this change was necessary, linking to the original issue.
2. Restrict the change to the lines starting with `predep_objects_...` to avoid false positives.

2022-10-03 07:40 UTC, haampie requested changes
I think the solution is alright. Also, can you please ask for the status regarding

> We are working on your issue internally. We will get back to you soon.

on their forum / helpdesk? Otherwise we're stuck with these hacks forever...

Otherwise:

1. Please add a comment clearly explaining why this change was necessary, linking to the original issue.
2. Restrict the change to the lines starting with `predep_objects_...` to avoid false positives.

2022-10-03 15:24 UTC, cmacmackin commented
> I think the solution is alright. Also, can you please ask for the status regarding
> 
> > We are working on your issue internally. We will get back to you soon.
> 
> on their forum / helpdesk? Otherwise we're stuck with these hacks forever...

I wasn't the original person to create that thread, but I've [posted a reply](community.intel.com/t5/Intel-oneAPI-Data-Parallel-C/dpcpp-and-GNU-Autotools/m-p/1419079#M2568) asking about this.
 
> Otherwise:
> 
>     1. Please add a comment clearly explaining why this change was necessary, linking to the original issue.
> 
>     2. Restrict the change to the lines starting with `predep_objects_...` to avoid false positives.

I've just pushed a new commit with these changes.

2022-10-05 10:56 UTC, haampie approved these changes

2022-10-05 11:57 UTC, merged