py-interface-meta: add 1.3.0 (incl new dependency packages)
LLNL/spack pull request #32873
Opened 2022-09-28 12:54 UTC by manuelakuhn

https://github.com/matthewwardrop/interface_meta/tree/v1.3.0
https://github.com/mtkennerly/poetry-dynamic-versioning/tree/v0.19.0
https://github.com/mtkennerly/dunamai/tree/v1.13.1

`py-poetry-dynamic-versioning` has an (optional) dependency on `py-poetry` but adding it results in an error
```
Error: Cyclic dependency detected between 'py-poetry-plugin-export' and 'py-poetry'
```
Installation (including `--test=root`) seems to work without it.

2022-09-28 15:36 UTC, adamjstewart requested changes

2022-09-28 15:36 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry-dynamic-versioning/package.py
> +    depends_on("py-dunamai@1.12:2", type=("build", "run"))
```suggestion
    depends_on("py-dunamai@1.12:1", type=("build", "run"))
```

2022-09-28 15:59 UTC, adamjstewart approved these changes

2022-09-29 10:09 UTC, manuelakuhn commented
@spackbot run pipeline

2022-09-29 10:22 UTC, merged