QMCPACK: add @3.15.0
LLNL/spack pull request #32931
Opened 2022-09-30 20:32 UTC by prckent

2022-09-30 20:33 UTC, ye-luo submitted a review, later dismissed
LGTM

2022-09-30 21:34 UTC, eugeneswalker approved these changes, later dismissed

2022-10-03 10:43 UTC, haampie commented
Can you add a conflict for GCC?

https://github.com/QMCPACK/qmcpack/commit/b82195fd058ddf993f3736343d19b57764d86322

```python
conflicts("%gcc@:8", when="@3.15.0:")
```

This is a legit failure in gitlab

2022-10-03 10:43 UTC, haampie requested changes
Can you add a conflict for GCC?

https://github.com/QMCPACK/qmcpack/commit/b82195fd058ddf993f3736343d19b57764d86322

```python
conflicts("%gcc@:8", when="@3.15.0:")
```

This is a legit failure in gitlab

2022-10-03 17:28 UTC, haampie approved these changes

2022-10-03 17:28 UTC, merged