lmod change family arch dir to arch dir
LLNL/spack pull request #32960
Opened 2022-10-03 16:29 UTC by simonleary-umass-edu

With lmod I get name conflicts for modules in different architecture because the directory structure is family based.
```
==> Error: Name clashes detected in module files:

file: /modules/spack-0.18.1/share/spack/lmod/linux-ubuntu20.04-x86_64/Core/zlib/1.2.12.lua
spec: zlib@1.2.12%gcc@9.4.0+optimize+pic+shared patches=0d38234 arch=linux-ubuntu20.04-x86_64
spec: zlib@1.2.12%gcc@9.4.0+optimize+pic+shared patches=0d38234 arch=linux-ubuntu20.04-x86_64_v3
spec: zlib@1.2.12%gcc@9.4.0+optimize+pic+shared patches=0d38234 arch=linux-ubuntu20.04-x86_64_v4
```
With this little change it makes directories for each generic architecture.

2022-10-06 09:02 UTC, alalazo requested changes
This won't allow people to mix software built for different targets, while you can already do what you ask for by configuring different roots in the `modules.yaml`, see https://spack.readthedocs.io/en/latest/module_file_support.html#changing-the-modules-root

2022-10-06 14:07 UTC, simonleary-umass-edu commented
That would result in a structure like this:
```
$spack/share/spack/modules/x86_64/linux-ubuntu-20.04/x86_64
$spack/share/spack/modules/x86_64_v3/linux-ubuntu-20.04/x86_64
$spack/share/spack/modules/x86_64_v4/linux-ubuntu-20.04/x86_64
```
which is rather ugly.

Why would anyone want to mix targets in a single directory? Can they mix like that in TCL?

2022-11-17 03:05 UTC, bernhardkaindl commented
Closing due to lack of response on the review. A different way of doing this has been suggested.
Please reopen if needed still.

2022-11-17 03:05 UTC, bernhardkaindl commented
Closing due to lack of response on the review. A different way of doing this has been suggested.
Please reopen if needed still.

2022-11-17 03:05 UTC, closed without merging

2023-02-16 03:19 UTC, simonleary-umass-edu commented
https://github.com/spack/spack/blob/85966a96b119b0ae5587e47a074f13a0a2819e39/lib/spack/spack/modules/common.py#L635
The TCL modules use the arch dir, so shouldn't the Lmod modules be consistent?

2023-02-16 20:43 UTC, simonleary-umass-edu commented
@alalazo can we revisit this?

2023-02-23 20:46 UTC, simonleary-umass-edu commented
One could mix modules from different targets by simply setting `modules:default:arch_folder=false`