Add checksum for py-astroid 2.12.7, py-setuptools 62.6.0
LLNL/spack pull request #32976
Opened 2022-10-04 11:33 UTC by iarspider

2022-10-04 17:15 UTC, adamjstewart requested changes

2022-10-04 17:15 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-astroid/package.py
> +    depends_on("py-setuptools@62.6:62", when="@2.12.7:", type=("build", "run"))
Need to lock down wheel versions too

2022-10-04 17:25 UTC, iarspider commented on var/spack/repos/builtin/packages/py-astroid/package.py
> +    depends_on("py-setuptools@62.6:62", when="@2.12.7:", type=("build", "run"))
Done

2022-10-04 17:27 UTC, adamjstewart approved these changes, later dismissed

2022-10-06 08:52 UTC, alalazo commented
@spackbot run pipeline

2022-10-06 20:11 UTC, iarspider commented
@spackbot run pipeline

2022-10-09 16:16 UTC, adamjstewart commented
@spackbot run pipeline

2022-10-09 16:25 UTC, adamjstewart commented
There will probably be conflicts between this PR and #32778

2022-10-10 06:46 UTC, iarspider commented
> There will probably be conflicts between this PR and #32778

I have added the changes from that PR here and closed it.

2022-10-10 17:33 UTC, adamjstewart approved these changes

2022-10-11 09:24 UTC, iarspider commented
Ah, I knew I have touched these packages recently! I guess I will update
the other PR with changes from this one, which you can close.

On Sun, Oct 9, 2022, 18:25 Adam J. Stewart ***@***.***> wrote:

> There will probably be conflicts between this PR and #32778
> <https://github.com/spack/spack/pull/32778>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/spack/spack/pull/32976#issuecomment-1272577761>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAE3NORHFHGN2ESFNCIHF2DWCLWXDANCNFSM6AAAAAAQ4PL7YQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-17 14:09 UTC, merged