Add checksum for py-soupsieve 2.3.2.post1
LLNL/spack pull request #32980
Opened 2022-10-04 13:33 UTC by iarspider

2022-10-04 16:18 UTC, adamjstewart requested changes

2022-10-04 16:18 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-soupsieve/package.py
>      depends_on("py-setuptools", type="build")
```suggestion
    depends_on("py-setuptools", when="@:2.1", type="build")
```

2022-10-04 17:27 UTC, adamjstewart approved these changes

2022-10-05 17:38 UTC, iarspider commented
@spackbot run pipeline

2022-10-06 08:33 UTC, alalazo commented
@spackbot run pipeline

2022-10-06 08:53 UTC, merged