Add a warning on Python 2.7 deprecation
LLNL/spack pull request #33052
Opened 2022-10-06 10:45 UTC by alalazo

We decided to remove support for running under Python 2.7 after the 0.19 release series. This PR adds a warning message to inform users.

2022-10-06 11:43 UTC, alalazo commented
@spackbot fix style

2022-10-06 13:40 UTC, adamjstewart commented on lib/spack/spack/main.py
> +            " removed after the Spack v0.19 release series."
I would say removed in 0.20 to be explicit.

2022-10-06 13:42 UTC, alalazo commented on lib/spack/spack/main.py
> +            " removed after the Spack v0.19 release series."
```suggestion
            " removed in Spack v0.20."
```

2022-10-06 13:51 UTC, adamjstewart commented on lib/spack/spack/main.py
> +            " removed in Spack v0.20."
Should we say ", use Python 3.6+ instead"?

2022-10-06 14:01 UTC, alalazo commented on lib/spack/spack/main.py
> +            " removed in Spack v0.20."
```suggestion
            " removed in Spack v0.20, use Python v3.6+ instead."
```

2022-10-06 14:38 UTC, adamjstewart commented
Message looks good now. We also have version detection logic in `bin/spack`, should we move this to there? Also, that logic seems out-of-date, it says we still support Python 3.5.

2022-10-06 14:41 UTC, alalazo commented
@adamjstewart I would just add the message here, I'm about to submit another draft PR to remove Python 2.7 specific code.

2022-10-06 14:43 UTC, adamjstewart commented
I would hold off on that, core will change so much by the time we release 0.19. I'm also planning on using pyupgrade to update everything to modern Python syntax.

2022-10-06 15:14 UTC, alalazo commented
> I would hold off on that, core will change so much by the time we release 0.19. I'm also planning on using pyupgrade to update everything to modern Python syntax.

Too late (I read your comment after submitting #33063) The  PR is a draft, to check early what fails and get comments on parts that I missed on a first try. Don't know if that is clear, but I'm looking forward to removing Python 2.7 😅

2022-10-06 19:00 UTC, tgamblin requested changes

2022-10-06 19:00 UTC, tgamblin commented on lib/spack/spack/main.py
> +        warnings.warn(msg)
This is really long -- I think it's better as:

```suggestion
        warnings.warn("Python 2.7 support is deprecated and will be removed in Spack v0.20.")
        warnings.warn("Please move to Python 3.6 or higher.")
```

or:

```suggestion
        warnings.warn(
            "Python 2.7 support is deprecated and will be removed in Spack v0.20.\n"
            "    Please move to Python 3.6 or higher."
        )
```

2022-10-06 19:21 UTC, tgamblin approved these changes

2022-10-06 21:42 UTC, merged

2022-10-08 01:01 UTC, luweizheng commented
Hi, I pulled the latest version and got the warning. I just want to know how to upgrade to python 3 using spack. Actually, there are multiple pythons on my system. Should I config in spack and let spack know the path of python 3?

2022-10-08 06:24 UTC, adamjstewart commented
There are a couple ways to tell Spack which python to use. On startup, Spack will search your PATH. It first searches for python3, then python, then python2. So as long as Python 3 is somewhere in your path, that's the one that will be used. Another way to force Spack to use a particular Python exe is to set the SPACK_PYTHON env var to the full path of the Python interpreter you want to use.