Add checksum for py-seaborn 0.12.0
LLNL/spack pull request #33145
Opened 2022-10-10 12:20 UTC by iarspider

2022-10-10 17:25 UTC, adamjstewart requested changes

2022-10-10 17:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-seaborn/package.py
>      depends_on("py-scipy", type=("build", "run"))
Looks like scipy is an optional dep now. I would add upper bounds on these, and optionally add a new stats variant with deps on scipy and statsmodels.

2022-10-10 17:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-seaborn/package.py
>      depends_on("python@3.6:", when="@0.10:", type="build")
Python 3.7+ is required now

2022-10-14 20:02 UTC, adamjstewart requested changes

2022-10-14 20:02 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-seaborn/package.py
> +    depends_on("py-scipy", type=("build", "run"))
These need upper bounds, otherwise scipy will be installed when `@0.12 ~stats`

2022-10-14 20:09 UTC, iarspider commented
@spackbot fix style

2022-10-14 20:12 UTC, adamjstewart approved these changes, later dismissed

2022-10-14 20:12 UTC, adamjstewart submitted a review, later dismissed

2022-10-15 15:34 UTC, adamjstewart approved these changes

2022-10-15 15:34 UTC, merged