Add checksum for py-virtualenv 20.16.4
LLNL/spack pull request #33154
Opened 2022-10-10 14:36 UTC by iarspider

2022-10-10 14:46 UTC, iarspider commented
@spackbot fix style

2022-10-10 16:06 UTC, tldahlgren reviewed
Confirmed sha256.

2022-10-10 16:08 UTC, iarspider commented
Can I ask for  #33047 to be merged now, since this PR kind of depends on it?

2022-10-10 16:12 UTC, adamjstewart requested changes

2022-10-10 16:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-virtualenv/package.py
> +    depends_on("py-setuptools-scm@2:", when="@20.10.0:", type=("build", "run"))
These need to be updated from `pyproject.toml`:
```toml
requires = [
    "setuptools>=59.6",
    "setuptools-scm>=6.4.2",
]
```
Also, setuptools-scm prob is only needed at build time.

2022-10-10 16:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-virtualenv/package.py
> +    depends_on("py-importlib-resources@5.4:", when="@20.10.0: ^python@:3.6", type=("build", "run"))
I wouldn't expect these `when` versions to be identical, did you mean `@20.16.4:`?

2022-10-10 17:09 UTC, adamjstewart approved these changes

2022-10-11 00:49 UTC, merged

2022-10-11 02:31 UTC, adamjstewart commented
@alalazo this PR was failing audit tests (missing dep version) but still auto-merged. Any idea what happened here?

2022-10-11 02:32 UTC, adamjstewart commented
Btw, if #33047 ever passes CI, this issue will be solved in develop.

2022-10-11 02:33 UTC, adamjstewart commented
Are our audit tests not required for CI to pass?

2022-10-11 07:50 UTC, alalazo commented
They should be, let me check