py-openssl: add version 22.1.0
LLNL/spack pull request #33189
Opened 2022-10-11 09:22 UTC by aphecetche

2022-10-12 01:51 UTC, adamjstewart requested changes

2022-10-12 01:51 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyopenssl/package.py
>      depends_on("py-setuptools", type="build")
Need to update dependencies:
```python
        python_requires=">=3.6",                                                         
        install_requires=[                                                               
            "cryptography>=38.0.0,<39",                                                  
        ],     
```

2022-10-12 08:34 UTC, aphecetche commented on var/spack/repos/builtin/packages/py-pyopenssl/package.py
>      depends_on("py-setuptools", type="build")
indeed. sorry about that. should be fixed now.

2022-10-12 15:51 UTC, adamjstewart requested changes

2022-10-12 15:51 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyopenssl/package.py
>      depends_on("py-six@1.5.2:", type=("build", "run"))
```suggestion
    depends_on("py-six@1.5.2:", when="@:19", type=("build", "run"))
```

2022-10-13 16:32 UTC, adamjstewart approved these changes

2022-10-13 16:32 UTC, merged