Add checksum for py-async-lru 1.0.3
LLNL/spack pull request #33196
Opened 2022-10-11 12:27 UTC by iarspider

2022-10-11 13:43 UTC, iarspider commented
@spackbot fix style

2022-10-12 01:49 UTC, adamjstewart requested changes

2022-10-12 01:49 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-async-lru/package.py
I would change `pypi` so Spack can still automatically find the latest version

2022-10-12 01:49 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-async-lru/package.py
> +            )
If you want to make this simpler you can do:
```suggestion
        url = "https://files.pythonhosted.org/packages/source/a/{0}/{0}-{1}.tar.gz"
        if version >= Version("1.0.3"):
            name = "async-lru"
        else:
            name = "async_lru"
        return url.format(name, version)
```

2022-10-13 16:22 UTC, adamjstewart approved these changes

2022-10-13 16:22 UTC, merged