Add checksum for py-oauthlib 3.2.1
LLNL/spack pull request #33201
Opened 2022-10-11 12:55 UTC by iarspider

2022-10-12 01:36 UTC, adamjstewart requested changes

2022-10-12 01:36 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-oauthlib/package.py
>      version("3.0.1", sha256="0ce32c5d989a1827e3f1148f98b9085ed2370fc939bf524c9c851d8714797298")
cryptography no longer has an upper bound. Honestly, we should prob split `+extras` into 3 separate variants and make them off by default to match the behavior of pip.

2022-10-13 13:30 UTC, iarspider commented
@spackbot fix style

2022-10-13 16:45 UTC, adamjstewart approved these changes

2022-10-14 18:46 UTC, merged