New packages: mlst, any2fasta, perl-carp, perl-class-method-modifiers, perl-role-tiny, perl-moo, perl-sub-quote
LLNL/spack pull request #33274
Opened 2022-10-12 22:46 UTC by luke-dt

2022-10-13 01:43 UTC, tldahlgren requested changes
Confirmed sha256 for the 7 packages, 9 versions.

The copyright for the first package needs to be corrected.

2022-10-13 01:43 UTC, tldahlgren commented on var/spack/repos/builtin/packages/any2fasta/package.py
> +# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```

2022-10-25 22:09 UTC, luke-dt commented
have I addressed all the problems, @tldahlgren ?

2022-10-25 23:08 UTC, tldahlgren approved these changes
Reconfirmed the sha256.  Thanks for the copyright fix.

2022-10-25 23:08 UTC, merged