Update the version for 5.3.0 release
LLNL/spack pull request #33405
Opened 2022-10-19 09:07 UTC by srekolam

This PR contains the version updates for some of the rocm recipes for rocm-5.3.0 release. This PR is dependent on PR #33320 .

2022-10-19 21:28 UTC, tldahlgren submitted a review, later dismissed
Confirmed the sha256 for each of the 8 packages' version directives.

2022-10-20 02:19 UTC, cgmb submitted a review, later dismissed

2022-11-03 16:03 UTC, renjithravindrankannath requested changes
Need -DCMAKE_INSTALL_LIBDIR=lib in hipsolver and hipfft 

```
        if self.spec.satisfies("@5.3.0:"):
            args.append("-DCMAKE_INSTALL_LIBDIR=lib")
```

2022-11-03 16:41 UTC, cgmb commented on var/spack/repos/builtin/packages/hipsolver/package.py
> +            self.define("BUILD_CLIENTS_TESTS", self.run_tests),
There appears to be a duplicate line introduced here.

2022-11-03 18:16 UTC, tldahlgren commented on var/spack/repos/builtin/packages/rocm-openmp-extras/package.py
> +        if self.spec.version >= Version("5.3.0"):
We generally prefer use of `self.spec.satisfies("5.3.0:")` for version range checks.  See https://spack.readthedocs.io/en/latest/packaging_guide.html#testing-spec-constraints.

2022-12-12 19:50 UTC, renjithravindrankannath commented
@spackbot run pipeline

2022-12-14 04:01 UTC, cgmb approved these changes, later dismissed

2022-12-14 04:02 UTC, cgmb commented
@spackbot run pipeline

2022-12-14 06:22 UTC, srekolam commented
@spackbot run pipeline

2022-12-15 16:43 UTC, srekolam commented
@cgmb  seeing an failure with rocprim@5.3.0 for petsc in gitlab-ci , any clues ?
https://gitlab.spack.io/spack/spack/-/jobs/4980002

2022-12-15 20:40 UTC, cgmb commented
> @cgmb seeing an failure with rocprim@5.3.0 for petsc in gitlab-ci , any clues ? https://gitlab.spack.io/spack/spack/-/jobs/4980002

I'm rather surprised, since this PR doesn't change rocthrust or rocprim.

2022-12-15 23:32 UTC, cgmb commented
To me, that looks like a legitimate bug in one of rocprim, rocthrust or petsc. It's triggered by this template instantiation:

    PetscCallThrust(thrust::merge(thrust::device, Azb, Aze, Bzb, Bze, Czb, IJCompare4()));

The key failure seems to be:

```
include/rocprim/device/detail/device_merge.hpp:77:9: note: candidate template ignored: 
 deduced conflicting types for parameter 'KeysInputIterator' ('zip_iterator<tuple<[...], thrust::detail::normal_iterator<thrust::device_ptr<int>>, [8 * ...]>>' vs. 'zip_iterator<tuple<[...],
  thrust::transform_iterator<Shift, thrust::detail::normal_iterator<thrust::device_ptr<int>>>, [8 * ...]>>')
2103    OffsetT merge_path(KeysInputIterator keys_input1,
```

2023-01-05 10:02 UTC, srekolam commented
@renjithravindrankannath , @cgmb @tldahlgren  can you please approve this PR.

2023-01-05 17:12 UTC, renjithravindrankannath approved these changes
LGTM

2023-01-05 17:30 UTC, cgmb approved these changes
This seems like a reasonable approach to addressing the problem. Ideally, we would have added rocprim@5.3.3 rather than patching rocprim@5.3.0, but that would be rather difficult given how all the rocm packages specify exact version dependencies.

2023-01-06 05:22 UTC, srekolam commented
@tldahlgren can you please review and let me know if this can be merged.
Thanks!!

2023-01-10 01:52 UTC, srekolam commented
@tldahlgren can you please review /approve this PR as this contains the changes for rocm-5.3.0 changes. This will complete the activity for rocm-5.3.0 release.

2023-01-10 02:48 UTC, tldahlgren approved these changes
Re-confirmed the `version()` sha256.  Rest LGTM.

2023-01-10 02:50 UTC, merged