gitlab: Do not use root_spec['pkg_name'] anymore
LLNL/spack pull request #33403
Opened 2022-10-19 02:26 UTC by scottwittenburg

Investigating why this `develop` pipeline [job](https://gitlab.spack.io/spack/spack/-/jobs/3741456) failed led to the discovery that some jobs in that `e4s-oneapi` pipeline were marked correctly in the pipeline generation job as needing to be rebuilt, but did appear in the generated pipeline yaml file.  The only reason it got noticed is because gitlab pipelines just recently started using `--use-buildcache dependencies:only,package:never`, so instead of installing the spec from the missing job from source, the pipeline failed.

The cause of the scheduling failure was that a single root spec in the environment had two `openssl` dependencies with different hashes, and the pipeline generation code still used the concrete root spec indexed by the package name to identify the concrete spec to schedule/build.  It may have become unsafe to index a concrete spec with a package name when spack got separate concretization of build dependencies, but that's just a guess.

This PR changes pipeline generation and spec rebuilding so that they no longer use the `root_spec["<pkg_name>"]` approach to identify specs.

2022-10-19 02:34 UTC, scottwittenburg commented
@zackgalbreath I could reproduce the `e4s-oneapi` pipeline generation errors locally, and this change fixed it for me.

2022-10-19 02:41 UTC, scottwittenburg commented
Now that we can ask spackbot to rebuild everything, let's use it on this PR tomorrow once the sync script pushes the branch.

2022-10-19 02:44 UTC, scottwittenburg commented
fyi @kwryankrattiger

2022-10-19 14:48 UTC, scottwittenburg commented
Link to pipeline that passed because all specs got pruned out: https://gitlab.spack.io/spack/spack/-/pipelines/194458

2022-10-19 14:48 UTC, scottwittenburg commented
@spackbot rebuild everything

2022-10-19 14:56 UTC, kwryankrattiger commented
I am a big fan of all the delete code!

2022-10-19 15:15 UTC, haampie requested changes

2022-10-19 15:15 UTC, haampie commented on lib/spack/spack/cmd/ci.py
> +    job_spec = env.get_by_hash(job_spec_dag_hash)[0]
Can you turn this comment into a hard requirement please? You're obtaining `job_spec_dag_hash` from some environment variable `SPACK_JOB_SPEC_DAG_HASH` so it's only true by convention and maybe the assumption breaks after a refactor, so it feels brittle.

The database has `query_one` for example, which asserts that the number of matches in <= 1. Something like that should be added to the environment.

2022-10-20 16:22 UTC, haampie approved these changes

2022-10-20 16:33 UTC, merged