gettext: Patch out bundled cdefs.h
LLNL/spack pull request #33411
Opened 2022-10-19 15:02 UTC by blue42u

`gettext` bundles a copy of `cdefs.h`. On some systems and architectures, this can conflict with the system `cdefs.h` and cause build failures such as https://github.com/spack/spack/issues/32374.

Patch these bundled copies out and instead always use the system `cdefs.h`.

Fixes https://github.com/spack/spack/issues/32374.

2022-10-27 16:52 UTC, tgamblin commented
I think this is the wrong solution.  If we are building gettext in Spack, why are we using the system `cdefs.h`?

2022-10-27 18:23 UTC, blue42u commented
@tgamblin To summarize the root issue: `cdefs.h` is a semi-internal header shipped as part of Glibc (`/usr/include/sys/cdefs.h`), but [a copy of it (with the same include guards!) was included in Gnulib for years](https://lists.gnu.org/archive/html/bug-gnulib/2021-01/msg00075.html). If the system's `cdefs.h` and the Gnulib `cdefs.h` are incompatible, the build falls apart. This was [fixed in upstream Gnulib](https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=commit;h=776af40e09b476a41073131a90022572f448c189), but Gettext ships an old version of gnulib from before this ([up until this month's 0.21.1 release](https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob;f=NEWS;h=cdbb16746c23555e70bb1e16917f5c349ce92d9e;hb=8b38ee827251cadbb90cb6cb576ae98702566288), which I only just found out existed).

So, to be honest, I'm very unclear on what a "right" solution would be. I could instead add a conflict for `gettext @:0.21.0 target=ppc64le:`, my worry is that Glibc's `cdefs.h` will shift again in the future and we'll be right back here again (unless Spack starts modelling Glibc versions before that happens).

2022-11-10 02:45 UTC, bernhardkaindl requested changes
@blue42u Thanks for the explanation. The gettext changelog you referenced says it all:
```yaml
libc-config: merge from glibc

Use a better way of keeping glibc <sys/cdefs.h> and gnulib
lib/cdefs.h mostly in sync, by using lib/cdefs.h only on platforms
where <sys/cdefs.h> does not work well enough for Gnulib.
```
So, Todd has a big point here as well:
Since Spack also supports MacOSX and Windows, this patch should only be executed on Linux platforms where we know that the system libc is in fact glibc.

For maximum caution with this change, lets add this to the patch:
```py
if spec.target.family == "ppc64le":
```

2022-11-10 02:53 UTC, bernhardkaindl approved these changes, later dismissed

2022-11-10 02:57 UTC, bernhardkaindl commented
@blue42u I think it's best to wait for a few days for another reviewer (e.g. haampie) to review this or ask him or tgamblin for review.

If you get no further comments or review in a couple of days please ping me. haampie or tgamblin.

2022-11-10 21:40 UTC, blue42u commented
Thanks for the assistance @bernhardkaindl!

One question: since this issue is fixed in `gettext@0.21.1` should this `patch` function be guarded by `@when("@:0.21.0")` (or maybe even `@when("@:0.21.0 target=ppc64le:")`)?

2022-11-11 02:59 UTC, bernhardkaindl commented
> Thanks for the assistance @bernhardkaindl!
> 
> One question: since this issue is fixed in `gettext@0.21.1` should this `patch` function be guarded by `@when("@:0.21.0")` (or maybe even `@when("@:0.21.0 target=ppc64le:")`)?

Yes, `@when("@:0.21.0 target=ppc64le:")` looks best to not negatively impact other builds.

2022-11-11 07:28 UTC, bernhardkaindl approved these changes
Perfect. Indeed I found the "@:0.21.0" is needed to not patch the files of 0.21.1 as it breaks with the patch applied on aarch64-linux.

2022-11-14 17:01 UTC, bernhardkaindl approved these changes

2022-11-17 01:53 UTC, bernhardkaindl commented
@blue42u Merging as [tgamblin](https://github.com/tgamblin)'s concerns are addressed.

2022-11-17 01:55 UTC, merged