Add py-myst-parser & update py-mdit-py-plugins and py-sphinxcontrib-mermaid
LLNL/spack pull request #33427
Opened 2022-10-20 00:10 UTC by zjibben

This adds a package for [myst-parser](https://myst-parser.readthedocs.io/en/latest/), updates a dependency (mdit-py-plugins), and updates a different package related to sphinx documentation (sphinixcontrib-mermaid).

2022-10-20 01:55 UTC, adamjstewart requested changes

2022-10-20 01:55 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mdit-py-plugins/package.py
> +    depends_on("py-flit-core@3.7.1:", type=("build", "run"))
These all need to be updated. In 0.3.1, this looks like:
```toml
requires = ["flit_core >=3.4,<4"]
requires-python = ">=3.7"
dependencies = ["markdown-it-py>=1.0.0,<3.0.0"]
```

2022-10-20 01:55 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-myst-parser/package.py
> +    depends_on("py-typing-extensions@4.0:", type=("build", "run"))
Most of these dependencies are wrong for 0.18.1, they should look like:
```toml
requires = ["flit_core >=3.4,<4"]
requires-python = ">=3.7"
dependencies = [
    "docutils>=0.15,<0.20",
    "jinja2", # required for substitutions, but let sphinx choose version
    "markdown-it-py>=1.0.0,<3.0.0",
    "mdit-py-plugins~=0.3.1",
    "pyyaml",
    "sphinx>=4,<6",
    "typing-extensions",
]
```

2022-10-20 18:03 UTC, zjibben commented on var/spack/repos/builtin/packages/py-mdit-py-plugins/package.py
> +    depends_on("py-flit-core@3.7.1:", type=("build", "run"))
Thanks @adamjstewart. I just pushed changes to address these. I added some `when` arguments so the new dependencies apply only to the new version of mdit-py-plugins. Please let me know how it looks.

2022-10-21 00:02 UTC, zjibben commented
I just added the py-exhale package as well. That should be the last thing from me. I replicated the dependencies from [here](https://github.com/svenevs/exhale/blob/master/pyproject.toml#L2) and [here](https://github.com/svenevs/exhale/blob/master/setup.cfg#L38), with some testing of my own to confirm.

2022-10-21 18:03 UTC, adamjstewart requested changes

2022-10-21 18:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-exhale/package.py
> +    homepage = "https://github.com/svenevs/exhale"
@svenevs FYI 😉

2022-10-21 18:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-exhale/package.py
> +
Can you also add:
```python
depends_on("python@3.7:", type=("build", "run"))
```

2022-10-21 18:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-exhale/package.py
> +    depends_on("py-wheel", type="build")
Wheel is added by the base class, so you don't technically need to add it here

2022-10-21 18:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-exhale/package.py
> +    depends_on("py-six", type=("build", "run"))
Missing a dep on docutils and sphinx:
```
install_requires =
        docutils>=0.12
        Sphinx>=3.0,<5
```

2022-10-21 18:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mdit-py-plugins/package.py
> +    depends_on("python@3.7:3", when="@0.3.1", type=("build", "run"))
```suggestion
    depends_on("python@3.7:", when="@0.3.1", type=("build", "run"))
```

2022-10-21 18:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mdit-py-plugins/package.py
>      depends_on("py-setuptools", type="build")
```suggestion
    depends_on("py-setuptools", when="@:0.2", type="build")
```

2022-10-21 18:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-myst-parser/package.py
> +    depends_on("py-setuptools", type="build")
Not needed

2022-10-21 18:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-myst-parser/package.py
> +
Missing dep:
```python
depends_on("python@3.7:", type=("build", "run"))
```

2022-10-21 18:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-myst-parser/package.py
> +    depends_on("py-flit-core@3.4:3", type=("build", "run"))
```suggestion
    depends_on("py-flit-core@3.4:3", type="build")
```

2022-10-21 18:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-myst-parser/package.py
> +    #depends_on("py-jinja2", type=("build", "run")) # let sphinx decide version
```suggestion
    depends_on("py-jinja2", type=("build", "run"))  # let sphinx decide version
```

2022-10-21 18:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-myst-parser/package.py
> +    depends_on("py-mdit-py-plugins@0.3.1", type=("build", "run"))
```suggestion
    depends_on("py-mdit-py-plugins@0.3.1:0.3", type=("build", "run"))
```

2022-10-21 20:22 UTC, svenevs commented on var/spack/repos/builtin/packages/py-exhale/package.py
> +    homepage = "https://github.com/svenevs/exhale"
LOL it's still limping along :upside_down_face:  Feel free to add me as a maintainer since that abomination is my responsibility after all xD

2022-10-21 20:22 UTC, svenevs commented on var/spack/repos/builtin/packages/py-exhale/package.py
> +    depends_on("py-six", type=("build", "run"))
I'm going to do a new small release soon, those requirements are too strict now and come from historical issues.  https://github.com/svenevs/exhale/pull/179

2022-10-25 00:01 UTC, zjibben commented on var/spack/repos/builtin/packages/py-exhale/package.py
> +    depends_on("py-wheel", type="build")
Good to know!

2022-10-25 00:04 UTC, zjibben commented on var/spack/repos/builtin/packages/py-exhale/package.py
> +    depends_on("py-six", type=("build", "run"))
No problem. Once the requirements are loosened in the next release we can update this too.

2022-10-25 01:38 UTC, adamjstewart approved these changes

2022-10-25 01:38 UTC, merged