ophidia-io-server: new package at v1.7
LLNL/spack pull request #33436
Opened 2022-10-20 15:55 UTC by SoniaScard

Includes the Ophidia IO Server package

2022-10-20 18:00 UTC, tldahlgren requested changes
Please remove the boiler plate comments.

2022-10-20 18:00 UTC, tldahlgren commented on var/spack/repos/builtin/packages/ophidia-io-server/package.py
> +# ----------------------------------------------------------------------------
This boiler plate should be removed

2022-10-20 18:00 UTC, tldahlgren commented on var/spack/repos/builtin/packages/ophidia-io-server/package.py
> +    version("1.7.2", sha256="8b203c44e0e5497c00f1fdb2322f0b0a41f36900b62a33d95a4570ae1ccc2971")
Confirmed sha256.

2022-10-20 18:02 UTC, tldahlgren commented
You also need to rebase to develop to pick up the primitives.

2022-10-21 08:57 UTC, SoniaScard commented on var/spack/repos/builtin/packages/ophidia-io-server/package.py
> +# ----------------------------------------------------------------------------
done!

2022-10-21 15:48 UTC, tldahlgren commented
@spackbot run pipeline

2022-10-21 17:13 UTC, tldahlgren approved these changes

2022-10-21 17:14 UTC, tldahlgren commented
Looks like one stack to go.

@spackbot run pipeline

2022-10-24 22:09 UTC, eldoo commented
Is there anything we could do for fixing the issue in the CI pipeline? Thanks

2022-10-26 01:57 UTC, tldahlgren commented
@spackbot run pipeline

2022-10-27 15:52 UTC, merged