locks: improved errors
LLNL/spack pull request #33477
Opened 2022-10-23 09:52 UTC by haampie

Instead of showing

```
==> Error: Timed out waiting for a write lock.
```

show

```
==> Error: Timed out waiting for a write lock after 1.200ms and 4 attempts on file: /some/file
```

s.t. we actually get to see where acquiring a lock failed even when not
running in debug mode.

And use pretty time units everywhere, so we don't get 1.45e-9 seconds
but 1.450ns etc.

2022-10-23 10:08 UTC, haampie commented
@cosmicexplorer friendly reminder to fix your `test_grouped_exception` test :grimacing:

2022-10-23 17:49 UTC, haampie commented
@spackbot run pipeline

2022-10-23 18:21 UTC, tgamblin requested changes
LGTM -- minor request

2022-10-23 18:21 UTC, tgamblin commented on lib/spack/llnl/util/lock.py
> +        super(LockTimeoutError, self).__init__(msg)
Can you pass the attempts and filename as a second argument?  That'll make it look like this:

```console
==> Error: Timed out waiting for a write lock after 1.200ms.
    Made 4 attempts on file: /path/to/file
```

which means the path is less likely to wrap around.

2022-10-24 08:25 UTC, tgamblin approved these changes

2022-10-24 09:54 UTC, merged