Conflict between certain openssh and clang versions
LLNL/spack pull request #33542
Opened 2022-10-27 01:59 UTC by jbigot

Introduce a conflict since openssh between 8.3 and 9.0 (included) fail to build with clang-15 and later.

Fix #33131

2022-10-27 09:08 UTC, bernhardkaindl approved these changes
I'd have preferred a patch to the configure script, and if gcc would have been affected I'd have suggested it, but I approve the conflict for clang@15: for this range. Thanks!

2022-11-10 02:00 UTC, bernhardkaindl requested changes
Checked:
```py
# echo "main() {}" >main.c
# clang-15 --std=c99 -Wall -W main.c 
main.c:1:1: warning: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
main() {}
^
int
1 warning generated.
# clang-15 --std=c2x -Wall -W main.c 
main.c:1:1: error: a type specifier is required for all declarations
main() {}
^
1 error generated.
# clang-15 --version|head -1
Ubuntu clang version 15.0.4-++20221102053248+5c68a1cb1231-1~exp1~20221102053256.89
```
At least the current Ubuntu clang-15.0.4 does not have this bug, it still supports c99 as it should.

The LLVM release notes state that they forcefully enabled -Werror-implicit-function-declaration but always even when not in C2x mode, and I assume they clearly had to revert that quickly because it must have broken countless software builds which are not compliant to -Werror-implicit-function-declaration.

2022-11-10 02:24 UTC, bernhardkaindl submitted a review, later dismissed

2023-02-21 08:17 UTC, alalazo commented
Can we resolve conflicts and push this PR forward?

2023-02-21 08:53 UTC, haampie commented
Clang reverted its behavior, let's just close.

2023-02-21 08:53 UTC, closed without merging