paraview: patch catalyst etc. to build with oneapi
LLNL/spack pull request #33562
Opened 2022-10-27 14:57 UTC by hppritcha

without this patch, build of paraview has a meltdown when reaching 3rd party catalyst and other packages with these types of errors:

   335    /tmp/foo/spack-stage/spack-stage-paraview-5.10.1-gscoqxhhakjyyfirdefuhmi2bzw4scho/spack-src/VTK/ThirdParty/fmt/vtkfmt/vtkfmt/format.h:1732:11: error: cannot capture a bi
            t-field by reference
   336          if (sign) *it++ = static_cast<Char>(data::signs[sign]);
   337              ^

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

2022-10-27 16:19 UTC, vicentebolea requested changes
Thanks for the contribution, this is indeed helpful.

Find the requested changes and please file the same changes upstream at https://github.com/fmtlib/fmt

2022-10-27 16:19 UTC, vicentebolea commented on var/spack/repos/builtin/packages/paraview/catalyst-etc_oneapi_fix.patch
> ++  auto sign = (uint)fspecs.sign;
Please change (uint) -> static_cast<unsigned int>() for wider portability

2022-10-27 16:19 UTC, vicentebolea commented on var/spack/repos/builtin/packages/paraview/catalyst-etc_oneapi_fix.patch
> ++  auto sign = (uint)fspecs.sign;
ditto

2022-10-27 16:19 UTC, vicentebolea commented on var/spack/repos/builtin/packages/paraview/catalyst-etc_oneapi_fix.patch
> ++  auto sign = (uint)fspecs.sign;
ditto

2022-10-27 16:19 UTC, vicentebolea commented on var/spack/repos/builtin/packages/paraview/catalyst-etc_oneapi_fix.patch
> ++  auto sign = (uint)fspecs.sign;
ditto

2022-10-27 21:39 UTC, hppritcha commented
the patch doesn't work on head of master on https://github.com/fmtlib/fmt namely doesn't compile.

2022-10-31 23:25 UTC, vicentebolea commented
I see, the current master of fmt has changed so that this does not apply anymore. @hppritcha could you share the spec invocation where you observed the error so that I can replicate this. Thanks!

2022-11-01 22:16 UTC, hppritcha commented
==> Concretized paraview%oneapi@2023.0.0 ^perl%gcc ^py-setuptools-scm@6.3.2 ^rust%gcc
[+]  kv37cce  paraview@5.10.1%oneapi@2023.0.0 cflags="-fPIC -Wl,--allow-multiple-definition -Qunused-arguments -Wl,-undefined,dynamic_lookup" cxxflags="-fPIC -Wl,--allow-multiple-definition -Wl,-undefined,dynamic_lookup -Qunused-arguments -std=c++14 -stdlib=libstdc++ -L/projects/opt/centos8/x86_64/gcc/11.2.0/lib64 -Wl,-rpath,/projects/opt/centos8/x86_64/gcc/11.2.0/lib64" ~adios2~advanced_debug~cuda+development_files~examples~eyedomelighting~fortran+hdf5~ipo+kits+mpi+opengl2~osmesa~pagosa~python+python3~qt+shared build_edition=catalyst_rendering build_type=RelWithDebInfo patches=730539b,acb3805 use_vtkm=off arch=linux-rhel8-skylake

2022-11-24 20:03 UTC, vicentebolea commented
@hppritcha I cannot replicate the error but I used oneapi2022 (not 23) and perhaps a different GCC version. One thing that I can state is that it does not break the build and it only applies to oneapi builds for 5.10.0-1.

As the author noticed, this is not a problem in ParaView > 5.10.1 since Catalyst is not included in PAraView Source Code Dist anymore.

2022-11-24 20:04 UTC, vicentebolea approved these changes, later dismissed

2022-11-24 20:04 UTC, vicentebolea commented
@hppritcha it has been a while please rebase to kick off the CI.

2022-11-25 23:08 UTC, bernhardkaindl submitted a review, later dismissed
@vicentebolea Because you approved and requested a re-run of the pipeline by a rebase, I've merged the changes from develop to do this.

(spack maintainers have a button for this from github which works fine),
should @hppritcha still want to make a rebase, but github will do I when it squashes and rebases automatically for the merge into develop, so it should be taken care of by github after CI has passed again.

I will also enable auto-rebase & merge to develop since as far as I can see you approved this PR.

@hppritcha @vicentebolea In case the `gitlab-ci` CI action fails for some unrelated spurious reason, please ping @bernhardkaindl with a comment (or in case I miss your ping, other reviewers/maintainers)

2022-12-20 23:51 UTC, vicentebolea commented
@hppritcha please rebase again to re-trigger the CI.

2022-12-21 18:31 UTC, hppritcha commented
@vicentebolea rebased

2022-12-21 18:34 UTC, vicentebolea approved these changes

2022-12-21 18:58 UTC, alalazo approved these changes

2022-12-22 00:07 UTC, merged