genesis: add version 2.0
LLNL/spack pull request #33605
Opened 2022-10-30 01:45 UTC by chig

Add new versions and patch for fj_compiler on Fugaku.

2022-10-31 18:35 UTC, tldahlgren approved these changes
Confirmed new tag and versions.

2022-10-31 18:35 UTC, tldahlgren commented on var/spack/repos/builtin/packages/genesis/package.py
> +# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
Want to keep the ending year up-to-date:

```suggestion
# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```

2022-10-31 18:36 UTC, tldahlgren requested changes
Please restore the ending copyright year.

2023-10-09 16:12 UTC, alecbcs commented
@chig are you still interested in getting this PR merged into develop? Looks like there's a few merge conflicts that need to be resolved.

2023-11-19 01:13 UTC, chig commented
@alecbcs Thank you for letting me know. I got your message this morning. How I should do it? I uploaded this pull request in 2022. Does this mean I should resubmit the pull request for the current develop version?

2024-05-19 01:21 UTC, wdconinc commented
@spackbot fix style

2024-05-19 01:25 UTC, wdconinc reviewed
At this point we should reduce the scope of this PR to just include v2 since python@2 required for genesis@1 is not a package in spack anymore.

2024-05-19 01:25 UTC, wdconinc commented on var/spack/repos/builtin/packages/genesis/package.py
> +    depends_on("python@2.6.9:2.8.0", type=("build", "run"), when="@:1.7.1")
Apologies for the delay, but by now no more python@2 dependencies are possible anymore for the current set of package versions in spack.

2025-06-14 06:53 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen here https://github.com/spack/spack-packages if you want to continue work on this.

2025-06-14 06:53 UTC, closed without merging