package/py-pykml: add new py3 compatible version
LLNL/spack pull request #33631
Opened 2022-11-01 06:01 UTC by Sinan81

add 0.2.0 providing py3 compatibility. otherwise package tries to import urllib2 which doesn't exist in python3.

2022-11-01 15:31 UTC, adamjstewart requested changes

2022-11-01 15:31 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pykml/package.py
> +    depends_on("python@3", type=('build', 'run'), when='@0.2.0:')
Where do you see that pykml 0.2.0 doesn't support Python 2?

Also, can you add something so that it's clear that 0.1 requires Python 2? Then I can remove that version once Python 2 is removed.

2022-11-01 15:31 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pykml/package.py
>      depends_on("py-lxml@2.2.6:", type=("build", "run"))
Dependency version needs to be updated

2022-11-02 03:46 UTC, Sinan81 commented on var/spack/repos/builtin/packages/py-pykml/package.py
> +    depends_on("python@3", type=('build', 'run'), when='@0.2.0:')
sorry for the confusion. it's fixed now.

2022-11-02 03:46 UTC, Sinan81 commented on var/spack/repos/builtin/packages/py-pykml/package.py
>      depends_on("py-lxml@2.2.6:", type=("build", "run"))
fixed.

2022-11-02 17:47 UTC, adamjstewart commented
@spackbot fix style

2022-11-02 17:47 UTC, adamjstewart submitted a review, later dismissed

2022-11-04 20:29 UTC, Sinan81 commented
Can this be merged now?

2022-11-04 21:34 UTC, adamjstewart approved these changes

2022-11-04 21:34 UTC, merged