Show time per phase
LLNL/spack pull request #33874
Opened 2022-11-13 11:18 UTC by haampie

2022-11-13 11:18 UTC, haampie commented
@spackbot fix style

2022-11-13 12:15 UTC, haampie commented
@spackbot run pipeline

2022-11-14 19:27 UTC, haampie commented
@adamjstewart do you have opinions about this?

2022-11-14 19:27 UTC, adamjstewart commented
No strong opinions from me.

2022-11-14 20:06 UTC, psakievich submitted a review, later dismissed

2022-11-15 12:23 UTC, alalazo requested changes
Waiting for #33900 to go in first, then this LGTM

2022-11-15 16:04 UTC, haampie commented
Now rebased on develop

2022-11-15 20:09 UTC, alalazo approved these changes

2022-11-15 20:10 UTC, merged