Be strict on the markers used in unit tests
LLNL/spack pull request #33884
Opened 2022-11-14 09:09 UTC by alalazo

This needs a recent `pytest` version and doesn't work with our vendored dependency

Modifications:
- [x] Add `--strict-markers` to options used to run unit tests

2022-11-14 09:13 UTC, haampie submitted a review, later dismissed

2022-11-14 09:16 UTC, alalazo commented
This might be optimized further, as it doesn't strictly need concretization. For the time being let's just take it down from 20 secs to a couple of secs.

2022-11-14 09:26 UTC, haampie approved these changes

2022-11-14 09:36 UTC, haampie requested changes
Needs to go after Python 2 is dropped and pytest is bumped

2022-12-12 13:50 UTC, alalazo commented on .github/workflows/unit_tests.yaml
> +          pip install -U pip setuptools six pytest
```suggestion
```

2022-12-13 08:21 UTC, haampie approved these changes

2022-12-13 08:21 UTC, merged