[WIP] Adding PAPI 7.0.0
LLNL/spack pull request #33940
Opened 2022-11-16 15:36 UTC by fspiga

New capabilities added, see https://icl.utk.edu/papi/news/news.html?id=384

Adapting the package recipe may require extra work. For now I am testing on Neoverse N1 and V1

2022-11-18 21:14 UTC, wyphan commented
Just tried to build `papi@7.0.0 +cuda +rocm` on Zen2 running RHEL 8, it failed with the following error messages:
```console
==> Installing papi-7.0.0-cws3pj3pf4wjpef3pdpctvqszhnurkyg
==> No binary for papi-7.0.0-cws3pj3pf4wjpef3pdpctvqszhnurkyg found: installing from source
==> Fetching https://icl.cs.utk.edu/projects/papi/downloads/papi-7.0.0.tar.gz
==> No patches needed for papi
==> papi: Executing phase: 'autoreconf'
==> papi: Executing phase: 'configure'
==> papi: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8' 'V=1'

3 errors found in build log:
     1828    /tmp/cctWuYJy.o:(.bss+0x38): multiple definition of `cuDeviceGetNamePtr'
     1829    /tmp/cc737FJV.o:(.bss+0x300): first defined here
     1830    /tmp/cctWuYJy.o:(.bss+0x30): multiple definition of `cuDeviceGetCountPtr'
     1831    /tmp/cc737FJV.o:(.bss+0x308): first defined here
     1832    /tmp/cctWuYJy.o:(.bss+0x28): multiple definition of `cuDeviceGetAttributePtr'
     1833    /tmp/cc737FJV.o:(.bss+0x2c0): first defined here
  >> 1834    collect2: error: ld returned 1 exit status
  >> 1835    make[1]: *** [Makefile.inc:68: libpapi.so.7.0.0.0] Error 1
     1836    make[1]: Leaving directory '/scratch/wp11/spack-stage/spack-stage-papi-7.0.0-cws3pj3pf4wjpef3pdpctvqszhnurkyg/spack-sr
             c/src'
  >> 1837    make: *** [Rules.pfm4_pe:43: libpfm4/lib/libpfm.a] Error 2

See build log for details:
  /scratch/wp11/spack-stage/spack-stage-papi-7.0.0-cws3pj3pf4wjpef3pdpctvqszhnurkyg/spack-build-out.txt
```

Here's the full build log: [spack-build-out.txt](https://github.com/spack/spack/files/10044841/spack-build-out.txt)

Summoning @adanalis to help troubleshoot this.

2022-11-21 18:45 UTC, G-Ragghianti commented
> 

Can you provide the full concretization?

2022-11-21 18:52 UTC, wyphan commented
@G-Ragghianti sure, here it is:
```console
wp11@ufront:~/deploy$ spack/bin/spack -e spack-env spec papi@7.0.0 +cuda
Input spec
--------------------------------
papi@7.0.0+cuda

Concretized
--------------------------------
papi@7.0.0%gcc@11.3.0+cuda+example~infiniband~lmsensors~nvml~powercap~rapl~rocm~rocm_smi~sde+shared~static_tools build_system=autotools arch=linux-rhel8-zen2
    ^cuda@11.7%gcc@11.3.0~allow-unsupported-compilers~dev build_system=generic arch=linux-rhel8-zen2
```

2022-11-22 20:05 UTC, G-Ragghianti commented
This should be resolved in papi upstream as it affects all users (not just in spack).

2022-11-22 20:08 UTC, G-Ragghianti commented
I think also some more testing will be needed before papi 7 is ready for spack, so I think this PR is premature.  I usually add the new version to the spack package once I've finished all my tests, but I was not able to finish this process since papi tagged the 7.0.0 release.

2023-05-24 16:42 UTC, naromero77 commented
Can we try to resurrect this PR? And also add PAPI 7.0.1

2023-06-04 04:15 UTC, naromero77 commented
PAPI is a widely used package. I think it would be good to get this PR merged also included 7.0.1. 

Also, can the @G-Ragghianti please review.

2023-06-05 08:21 UTC, G-Ragghianti commented
If version 7.0.0 is to be added, then version 7.0.1 also needs to be added because it includes an important fix that was delaying us from including version 7.0.0 initially.

2023-06-05 09:11 UTC, alalazo requested changes

2023-06-05 09:11 UTC, alalazo commented on var/spack/repos/builtin/packages/papi/package.py
> +    version("7.0.0", sha256="799dcc317a47da96beaeed445812ecb6ae49df7c0504a4569797c1f7d74c4fd2")
Can we add 7.0.1 directly (and remove 7.0.0), per @G-Ragghianti comment?

2023-06-14 19:13 UTC, naromero77 commented
@G-Ragghianti I may start a new PR because I have not heard back from the authors in a while. Can we add both 7.0.0 and 7.0.1?

2023-06-15 08:38 UTC, G-Ragghianti commented
I'd say yes to the new PR.  I would not add 7.0.0 because it contains a bug that prevents it from working correctly in spack.

2023-06-15 13:03 UTC, naromero77 commented
Interesting... I remember being able to build 7.0.0 with Spack, but this was just the default variant.

2023-06-15 13:27 UTC, G-Ragghianti commented
I don't remember the problem exactly, but I think it involved either the
"make test" or the smoke test.

On Thu, Jun 15, 2023 at 3:04 PM Nichols A. Romero ***@***.***>
wrote:

> Interesting... I remember being able to build 7.0.0 with Spack, but this
> was just the default variant.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/spack/spack/pull/33940#issuecomment-1593006302>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH7Q5YZXPQPG4C5UWNIVG4TXLMB4LANCNFSM6AAAAAASCLYD7M>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-15 13:52 UTC, wyphan commented
The `+cuda` variant also failed to build, like I commented above.

2023-06-16 15:09 UTC, wyphan commented
@naromero77 I just minted the PR, please take a look.

2023-06-26 11:40 UTC, alalazo commented
Closing, in favor of #38443

2023-06-26 11:40 UTC, closed without merging