Updating faiss with new versions
LLNL/spack pull request #33983
Opened 2022-11-18 01:37 UTC by rblake-llnl

Updating build system to cmake, set up python bindings.

Also adding myself as a reviewer, along with @bhatiaharsh .

2022-11-18 05:59 UTC, alalazo requested changes
There seem to be build systems related imports missing. Besides the minor comments in the review LGTM.

2022-11-18 05:59 UTC, alalazo commented on var/spack/repos/builtin/packages/faiss/package.py
> +        spack.build_systems.cmake.CMakeBuilder.install(self, pkg, spec, prefix)
Doesn't this:
```suggestion
        super().install(pkg, spec, prefix)
```
work as well?

2022-11-18 05:59 UTC, alalazo commented on var/spack/repos/builtin/packages/faiss/package.py
> +        # return self.pkg.stage.source_path
```suggestion
```

2022-11-18 05:59 UTC, alalazo commented on var/spack/repos/builtin/packages/faiss/package.py
> +class PythonPipBuilder(spack.build_systems.python.PythonPipBuilder):
This one is used as part of another object, which is fine. Maybe it's better scoped as a local class defined in the `CMakeBuilder.install` method?

2022-11-18 20:34 UTC, alalazo approved these changes
LGTM, thanks! Let me know if you have any feedback on the multiple build systems interface :slightly_smiling_face:

2022-11-18 20:43 UTC, merged

2022-11-18 21:55 UTC, rblake-llnl commented
I had to read the documentation several times to get it, and there was some strangeness with needing to specifically reconcretize when I changed the build systems around. In general it works quite well though!  Way better than if I had to use both methods simultaneously.

2023-01-02 18:08 UTC, haampie commented
@rblake-llnl is there no way to make cmake install the python part?

CMake distinguishes between build and install rpaths, if you do an ad-hoc install with pip like this, you install shared libraries with build rpaths instead of install rpaths.