berkelygw: Fix ~mpi to disable mpi (and also imply ~scalapack)
LLNL/spack pull request #34061
Opened 2022-11-22 15:07 UTC by bernhardkaindl

@glaweh opened #339448, but it needs a change and conflict-resolve with develop, and I can't push to it.

@glaweh opened it with:
The package.py assumed "+mpi" in many places, without checking for the variant. This problem went undetected, as a hard dependency on scalapack pulled an mpi implementation into the dependency chain (this is also fixed).
@migueldiascosta reacted with thumbs up emoji

I found that it also needs this to build with `~scalapack` and `~mpi`:
With #33948, `spack install berkeleygw~scalapack` results in an error, scalapack is needed for MPI:
```py
../Common/primme_interface.f90:3:4: error: #error ScaLAPACK is required for MPI builds.
```
We need to add this to make them to be selected and deselected together as a unit by the solver:
```py
+    # scalapack and mpi variants need each other, make the solver (de)select the other too:
     conflicts(
         "+scalapack", when="~mpi", msg="scalapack is a parallel library and needs MPI support"
     )
+    conflicts(
+        "~scalapack", when="+mpi", msg="ScaLAPACK is required for MPI builds of berkelygw"
+    )
```
I added this in addition to the rebase/resolve of merge conflict in due to fflag change, no other changes.

2022-11-22 15:08 UTC, bernhardkaindl reviewed
Reviewed, looks good, @migueldiascosta, for you good too?

2022-11-23 11:48 UTC, alalazo requested changes

2022-11-23 11:48 UTC, alalazo commented on var/spack/repos/builtin/packages/berkeleygw/package.py
> +    conflicts("~scalapack", when="+mpi", msg="ScaLAPACK is required for MPI builds of berkelygw")
Can you use a conditional variant? It works better when scoring possible solutions with clingo:
```python
variant("scalapack", default=True, when="+mpi", description="Build with ScaLAPACK support")
```

2022-11-23 12:33 UTC, bernhardkaindl commented on var/spack/repos/builtin/packages/berkeleygw/package.py
> +    conflicts("~scalapack", when="+mpi", msg="ScaLAPACK is required for MPI builds of berkelygw")
`scalapack` and `mpi` need each other. I'm guessing it's better to just make it one variant then.

2022-11-23 12:38 UTC, alalazo commented on var/spack/repos/builtin/packages/berkeleygw/package.py
> +    conflicts("~scalapack", when="+mpi", msg="ScaLAPACK is required for MPI builds of berkelygw")
If `~scalapack+mpi` is not possible (sorry, I didn't look carefully enough!) then I'd remove `scalapack`

2022-11-23 13:15 UTC, bernhardkaindl commented on var/spack/repos/builtin/packages/berkeleygw/package.py
> +    conflicts("~scalapack", when="+mpi", msg="ScaLAPACK is required for MPI builds of berkelygw")
I've applied your requested change! *(removed the `scalapack` variant)*

2022-11-23 14:08 UTC, bernhardkaindl commented
It was merged into #33948, closing

2022-11-23 14:08 UTC, closed without merging