`spack python`: use `execve` instead of `InteractiveConsole`
LLNL/spack pull request #34105
Opened 2022-11-23 18:35 UTC by tgamblin

… interactive

Running a `spack-python` script like this:

```python

import spack
import multiprocessing

def echo(args):
    print(args)

if __name__ == "__main__":
    pool = multiprocessing.Pool(2)
    pool.map(echo, range(10))
```

will fail in `develop` with an error like this:

```console
_pickle.PicklingError: Can't pickle <function echo at 0x104865820>: attribute lookup echo on __main__ failed
```

Python expects to be able to look up the method `echo` in `sys.path["__main__"]` in subprocesses spawned by `multiprocessing`, but because we use `InteractiveConsole` to run `spack python`, the executed file isn't considered to be the `__main__` module and lookups in subprocesses fail.

Another annoyance with `InteractiveConsole` is that `__file__` is not defined in the main script scope, so you can't use it in your scripts.

We can fix this by using `execve` to launch `spack python` instead of using `InteractiveConsole`. This makes `spack python` behave more like normal python. After this change:

```console
> ./test.py
0
1
2
3
4
5
6
7
8
9
```

- [x] Use `execve` to launch non-interactive `spack python` invocations
- [x] Only use `InteractiveConsole` for interactive `spack python`

2022-11-24 19:35 UTC, trws approved these changes, later dismissed

2023-05-30 14:19 UTC, alalazo requested changes
Basically LGTM, once tests are passing. I left a few minor comments and a diff for an import typo that I am pretty sure causes issues when running in debug mode.

2023-05-30 14:19 UTC, alalazo commented on lib/spack/spack/__init__.py
> +            import spack.repo  # noqa: F401
Instead of removing the meta-path finder, can we add a boolean state to it and record it was triggered?

2023-05-30 14:19 UTC, alalazo commented on lib/spack/spack/cmd/__init__.py
> +    import spack.environment as ev
This function can probably be moved somewhere under `spack.environment`, and then be imported where needed.

2023-05-30 14:19 UTC, alalazo commented on lib/spack/spack/cmd/__init__.py
> +    import spack.user_environment as uenv
This one instead can likely be moved to `spack.user_environment`

2023-05-30 14:19 UTC, alalazo commented on lib/spack/spack/cmd/__init__.py
> +    import spack.environment as ev
This one is a bit trickier because of the need to know the originating command :thinking:

2023-05-30 14:19 UTC, alalazo commented on lib/spack/spack/cmd/__init__.py
> +    import spack.environment as ev
This function has implicit assumptions on the `Argparse` namespace passed in as argument (it must have an `env` attribute and optionally an `end_dir` attribute).

2023-05-30 14:19 UTC, alalazo commented on lib/spack/spack/main.py
> +        import spack.util.debug
We need this:
```diff
diff --git a/lib/spack/spack/main.py b/lib/spack/spack/main.py
index 654967d34a..fb014e3527 100644
--- a/lib/spack/spack/main.py
+++ b/lib/spack/spack/main.py
@@ -569,6 +569,8 @@ def send_warning_to_tty(message, *args):
 
 def setup_main_options(args):
     """Configure spack globals based on the basic options."""
+    import spack.util.debug
+
     # Assign a custom function to show warnings
     warnings.showwarning = send_warning_to_tty
 
@@ -586,8 +588,6 @@ def setup_main_options(args):
         SHOW_BACKTRACE = True
 
     if args.debug:
-        import spack.util.debug
-
         spack.util.debug.register_interrupt_handler()
         spack.config.set("config:debug", True, scope="command_line")
         spack.util.environment.TRACING_ENABLED = True

```
to avoid a "reference before assignment" at line 584.

2023-05-30 14:19 UTC, alalazo commented on lib/spack/spack/repo.py
> +    #    return "{0}.{1}".format(spack.ROOT_PYTHON_NAMESPACE, namespace)
```suggestion
```

2023-05-30 14:19 UTC, alalazo commented on lib/spack/spack_installable/main.py
> +    sys.path[:0] = get_spack_sys_paths(spack_prefix)
:+1: This is definitely clearer

2023-05-30 14:19 UTC, alalazo commented on lib/spack/spack/cmd/python.py
> +import spack.util.executable as exe
Maybe we can do something like:
```suggestion
from spack.util import environment, executable
```
?

2023-05-30 14:19 UTC, alalazo commented on lib/spack/spack/cmd/python.py
> +    python = exe.Executable(sys.executable)
:+1:

2023-12-19 10:43 UTC, alalazo commented
There's some circular import error to be fixed (I wish Python was like Go in this respect :slightly_smiling_face: )

2023-12-19 16:42 UTC, tgamblin commented
Not sure the timeline on this because it’s *many* such errors (see history). I was just rebasing but haven’t had a chance to dive into it. I am curious whether #40262 will help.

2024-03-21 08:27 UTC, tgamblin commented
Superseded by #41789

2024-03-21 08:32 UTC, closed without merging