Fix recipe for py-onnx-runtime
LLNL/spack pull request #34130
Opened 2022-11-25 13:24 UTC by iarspider

2022-11-25 17:34 UTC, adamjstewart requested changes

2022-11-25 17:34 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-onnx-runtime/package.py
> +            py = which("python")
This won't work for `python~pythoncmd` where only the `python3` executable exists. Spack already has a `python` function injected into the module, so you can use `python(...)` without using `which(...)` first.

2022-11-25 17:34 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-onnx-runtime/package.py
> +            py("setup.py", "build")
Direct invocation of `setup.py` is deprecated, see https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html and #27798. We should instead use a build tool like pip.

2022-11-29 17:37 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-onnx-runtime/package.py
> +            pip(*args)
```suggestion
        args = std_pip_args + ["--prefix=" + prefix, "."]
        with working_dir(self.build_directory):
            pip(*args)
```
This should be sufficient. This is also what we do in `py-tensorflow` and many other packages like this.

2022-11-29 22:04 UTC, iarspider commented
@spackbot fix style

2022-11-29 23:29 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-onnx-runtime/package.py
> +import inspect
You can remove this import

2022-11-30 15:17 UTC, adamjstewart approved these changes

2022-11-30 15:17 UTC, merged