Cray manifest: automatically convert 'cray' platform to 'linux'
LLNL/spack pull request #34177
Opened 2022-11-29 01:36 UTC by scheibelp

Spack now recognizes Cray systems as being Linux (i.e. `spack arch` on Cray systems will list "linux" as the platform). For manifests which continue to list the platform as Cray, this PR automatically converts them so they are considered compatible with other packages built on the system by Spack.

2022-12-05 18:30 UTC, becker33 requested changes

2022-12-05 18:30 UTC, becker33 commented on lib/spack/spack/cray_manifest.py
> +        local_platform = spack.spec.ArchSpec.default_arch().platform
```suggestion
        local_platform = spack.platforms.host()
```

2022-12-05 18:30 UTC, becker33 commented on lib/spack/spack/cray_manifest.py
> +        if local_platform == "linux" and spec_platform.lower() == "cray":
```suggestion
        if local_platform.name == "linux" and spec_platform.lower() == "cray":
```

2022-12-07 00:18 UTC, becker33 approved these changes, later dismissed

2022-12-07 00:18 UTC, becker33 commented
@scheibelp have you tested this out locally? I know this isn't something we can add unit tests for yet.

2022-12-07 00:45 UTC, scheibelp commented
> have you tested this out locally? I know this isn't something we can add unit tests for yet.

I have. I could in fact update the tests to check this:

* I can create a manifest with the entries
* I can monkeypatch `platform.host()` to return a linux platform

would that seem like a reasonable way to do it?

2022-12-07 00:47 UTC, becker33 commented
@scheibelp yeah that seems reasonable. I think it's better if you could only generate the in-memory entry associated with the cray manifest, that way we don't suffer a performance penalty in the test for doing IO.

2022-12-08 00:35 UTC, scheibelp commented
@becker33 a test has now been added

2022-12-08 19:27 UTC, becker33 approved these changes

2022-12-08 19:28 UTC, merged