ns-3-dev: rewrite the package to use CMake
LLNL/spack pull request #34207
Opened 2022-11-30 09:38 UTC by alalazo

2022-11-30 09:39 UTC, alalazo commented
See #34084

2022-11-30 10:49 UTC, haampie commented
Is @yee29 also a developer/contributor to ns-3dev? If so, it would be get to add some cmake variables to disable looking for ccache and "fast" linkers. Like `-DNS3_DETECT_FAST_LINKER=OFF` and `-DNS3_USE_CCACHE=OFF`. The package is a mess right now.

2022-11-30 10:50 UTC, haampie commented on var/spack/repos/builtin/packages/ns-3-dev/package.py
> +    depends_on("ccache", type="run")
```suggestion
    depends_on("ccache", type="build")
```

2022-11-30 10:50 UTC, haampie requested changes
.

2022-11-30 11:05 UTC, haampie commented
I've created an issue upstream: https://gitlab.com/nsnam/ns-3-dev/-/issues/820

2022-11-30 17:29 UTC, Gabrielcarvfer commented
I'm the build system maintainer for ns-3 and I will be merging a patch to include switches for that as soon as I finish retesting everything. They will be NS3_CCACHE and NS3_FAST_LINKERS.
But I'm more interested in the failures you mentioned. Could you specify the platforms you had issues? Are they only related to Spack or ns-3?

2022-12-01 16:39 UTC, alalazo commented
> But I'm more interested in the failures you mentioned. Could you specify the platforms you had issues? Are they only related to Spack or ns-3?

I didn't investigate them in details, but during configuration the C compiler (which in Spack case is a wrapper) couldn't compile a working program due to the `-fuse-ld=...` flags. The error is surely specific to `ns-3`, as the same compiler + wrapper works for many other packages. I didn't check if it is specific to Spack (i.e. I didn't try to use the same compiler without the wrapper in the middle).

2022-12-01 17:07 UTC, Gabrielcarvfer commented
> I didn't investigate them in details, but during configuration the C compiler (which in Spack case is a wrapper over a "real" compiler) couldn't compile a working program due to the `-fuse-ld=...` flags. 

Hmm. If it isn't too much trouble, could you give me a list of commands needed to reproduce that? 

Our only real use of the C compiler is to check for some headers, and only because check_cxx_include fails with C headers on Windows. As far as I know, the linker flags are not supposed to be used in these calls, so I believe it should be something else.

2022-12-05 12:47 UTC, alalazo commented
I am on:

* **Spack:** 0.20.0.dev0 (e7fc9ea243b9bc81528a62c5f1894e4084abd69e)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

To reproduce the failure you can use this PR, comment out the `patch` method and try installing:
```console
$ spack install ns-3-dev
```
once you have the failure you can:
```console
$ spack cd ns-3-dev
$ spack build-env ns-3-dev -- bash
```
to inspect the build environment and debug the build manually.

2022-12-06 04:23 UTC, Gabrielcarvfer commented
> To reproduce the failure you can use this PR, comment out the `patch` method and try installing:
> 
> ```
> $ spack install ns-3-dev
> ```

Thanks for the steps. 

I've tried locally and the errors are mostly in different stuff.
### First try: it didn't even reach to ns-3 configuration.
<details><summary>Error due to a whitespace in the path</summary>

```
==> Installing xz-5.2.7-2oonf6f23ztvjt3tgphol7fecrm4g524
==> No binary for xz-5.2.7-2oonf6f23ztvjt3tgphol7fecrm4g524 found: installing from source
==> Fetching https://prdownloads.sourceforge.net/lzmautils/files/xz-5.2.7.tar.bz2
==> No patches needed for xz
==> xz: Executing phase: 'autoreconf'
==> xz: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 77:
    '/tmp/gabriel/spack-stage/spack-stage-xz-5.2.7-2oonf6f23ztvjt3tgphol7fecrm4g524/spack-src/configure' '--prefix=/home/gabriel/Desktop/New Folder/spack/opt/spack/linux-ubuntu22.04-zen/gcc-12.1.0/xz-5.2.7-2oonf6f23ztvjt3tgphol7fecrm4g524' '--enable-shared' '--enable-static'

2 errors found in build log:
     35    checking whether make sets $(MAKE)... yes
     36    checking whether make supports nested variables... yes
     37    checking whether ln -s works... yes
     38    checking whether make supports the include directive... yes (GNU sty
           le)
     39    checking for gcc... /home/gabriel/Desktop/New Folder/spack/lib/spack
           /env/gcc/gcc
     40    checking whether the C compiler works... no
  >> 41    configure: error: in `/tmp/gabriel/spack-stage/spack-stage-xz-5.2.7-
           2oonf6f23ztvjt3tgphol7fecrm4g524/spack-src':
  >> 42    configure: error: C compiler cannot create executables
     43    See `config.log' for more details

```
</details>

<br>

Moved everything to a path without whitespaces.
### Second try: building things normally until it stops.
<details><summary>re2c failed, but seemingly due to a missing compiler</summary>

```
==> Installing re2c-2.2-4foexdstc6cbecr776nhrxhxn62crpjd
==> No binary for re2c-2.2-4foexdstc6cbecr776nhrxhxn62crpjd found: installing from source
==> Using cached archive: /home/gabriel/Desktop/NewFolder/spack/var/spack/cache/_source-cache/archive/0f/0fc45e4130a8a555d68e230d1795de0216dfe99096b61b28e67c86dfd7d86bda.tar.xz
==> No patches needed for re2c
==> re2c: Executing phase: 'configure'
==> re2c: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

3 errors found in build log:
     158    make  all-recursive
     159    make[1]: Entering directory '/tmp/gabriel/spack-stage/spack-stage-re2c-2.2-4foexdstc6cbecr776nhrxhxn62crpjd/spack-src'
     160    Making all in .
     161    make[2]: Entering directory '/tmp/gabriel/spack-stage/spack-stage-re2c-2.2-4foexdstc6cbecr776nhrxhxn62crpjd/spack-src'
     162      CXX      src/compile.o
     163    [spack cc] ERROR: Compiler 'gcc@12.1.0' does not have a C++ compiler configured.
  >> 164    make[2]: *** [Makefile:2858: src/compile.o] Error 1
     165    make[2]: *** Waiting for unfinished jobs....
     166    make[2]: Leaving directory '/tmp/gabriel/spack-stage/spack-stage-re2c-2.2-4foexdstc6cbecr776nhrxhxn62crpjd/spack-src'
  >> 167    make[1]: *** [Makefile:4581: all-recursive] Error 1
     168    make[1]: Leaving directory '/tmp/gabriel/spack-stage/spack-stage-re2c-2.2-4foexdstc6cbecr776nhrxhxn62crpjd/spack-src'
  >> 169    make: *** [Makefile:1751: all] Error 2
```
</details>

<br>

### Third try: try to install yet again to show what failed.

<details><summary>Install log with error</summary>

```
./spack install ns-3-dev
[+] /home/gabriel/Desktop/New Folder/spack/opt/spack/linux-ubuntu22.04-zen/gcc-12.1.0/boost-1.80.0-pzq7zopqy4mpskz62hgtdiz4fsfrokuf
[+] /home/gabriel/Desktop/NewFolder/spack/opt/spack/linux-ubuntu22.04-zen/gcc-12.1.0/pkgconf-1.8.0-msy746atkzfh7pmrcfwv26iixceljpjl
[+] /home/gabriel/Desktop/New Folder/spack/opt/spack/linux-ubuntu22.04-zen/gcc-12.1.0/ca-certificates-mozilla-2022-10-11-sqfei35xpd4ci3cbzvxwk657cp6dyvnp
==> Installing berkeley-db-18.1.40-ayqdvjj6hmvnipurrvtbmv3dxct4jpu3
==> No binary for berkeley-db-18.1.40-ayqdvjj6hmvnipurrvtbmv3dxct4jpu3 found: installing from source
==> Using cached archive: /home/gabriel/Desktop/NewFolder/spack/var/spack/cache/_source-cache/archive/0c/0cecb2ef0c67b166de93732769abdeba0555086d51de1090df325e18ee8da9c8.tar.gz
==> Applied patch /home/gabriel/Desktop/NewFolder/spack/var/spack/repos/builtin/packages/berkeley-db/drop-docs.patch
==> Applied patch /home/gabriel/Desktop/NewFolder/spack/var/spack/repos/builtin/packages/berkeley-db/tls.patch
==> Ran patch() for berkeley-db
==> berkeley-db: Executing phase: 'autoreconf'
==> berkeley-db: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/tmp/gabriel/spack-stage/spack-stage-berkeley-db-18.1.40-ayqdvjj6hmvnipurrvtbmv3dxct4jpu3/spack-src/dist/configure' '--prefix=/home/gabriel/Desktop/NewFolder/spack/opt/spack/linux-ubuntu22.04-zen/gcc-12.1.0/berkeley-db-18.1.40-ayqdvjj6hmvnipurrvtbmv3dxct4jpu3' '--disable-static' '--enable-dbm' '--enable-compat185' '--with-repmgr-ssl=no' '--enable-cxx' '--enable-stl'

1 error found in build log:
     131    checking if libtool supports shared libraries... yes
     132    checking whether to build shared libraries... yes
     133    checking whether to build static libraries... no
     134    checking SOSUFFIX from libtool... .so
     135    checking MODSUFFIX from libtool... .so
     136    checking JMODSUFFIX from libtool... .so
  >> 137    checking whether the C++ compiler supports templates for STL... configure: error: no

See build log for details:
  /tmp/gabriel/spack-stage/spack-stage-berkeley-db-18.1.40-ayqdvjj6hmvnipurrvtbmv3dxct4jpu3/spack-build-out.txt

==> Warning: Skipping build of perl-5.36.0-lvgzbxlo3e6hkelya7ehtooshboieibz since berkeley-db-18.1.40-ayqdvjj6hmvnipurrvtbmv3dxct4jpu3 failed
==> Warning: Skipping build of automake-1.16.5-6iigevvgyfq2vys6p5xbwfmfvsqglyka since perl-5.36.0-lvgzbxlo3e6hkelya7ehtooshboieibz failed
==> Warning: Skipping build of cairo-1.16.0-p6nzbeho2hgghgltivsyb6hifwre2ij7 since automake-1.16.5-6iigevvgyfq2vys6p5xbwfmfvsqglyka failed
==> Warning: Skipping build of harfbuzz-5.1.0-4nduuhived6anilzvsxl3thbx3lwqb3k since cairo-1.16.0-p6nzbeho2hgghgltivsyb6hifwre2ij7 failed
==> Warning: Skipping build of ns-3-dev-3.37-jh3k6dtw7gnpwidja55733iqnilsv4nc since harfbuzz-5.1.0-4nduuhived6anilzvsxl3thbx3lwqb3k failed
==> Warning: Skipping build of gobject-introspection-1.72.0-j67vkfsybhhjcrrcsg6le5w5mtgb6xre since cairo-1.16.0-p6nzbeho2hgghgltivsyb6hifwre2ij7 failed
==> Warning: Skipping build of bison-3.8.2-jutjpvmy47czti3el7mag4j5okfv56lh since perl-5.36.0-lvgzbxlo3e6hkelya7ehtooshboieibz failed
==> Warning: Skipping build of flex-2.6.3-ctfxr2ewzsxvrccsguabhacxj55n6tap since bison-3.8.2-jutjpvmy47czti3el7mag4j5okfv56lh failed
==> Warning: Skipping build of openssl-1.1.1s-frte5zgolo7z7skog6rr24zz2biz6vzn since perl-5.36.0-lvgzbxlo3e6hkelya7ehtooshboieibz failed
==> Warning: Skipping build of cmake-3.25.0-4iey6aehtwet7nyjbnn3vnmebbobj7et since openssl-1.1.1s-frte5zgolo7z7skog6rr24zz2biz6vzn failed
==> Warning: Skipping build of ccache-4.7.4-map3hyg6twifsvbsacg7iipalcvtpphl since cmake-3.25.0-4iey6aehtwet7nyjbnn3vnmebbobj7et failed
==> Warning: Skipping build of hiredis-1.1.0-m5hxulwlcnapbkcfie6ais4pikofr6jy since cmake-3.25.0-4iey6aehtwet7nyjbnn3vnmebbobj7et failed
==> Warning: Skipping build of python-3.10.8-3e7zykwsd4mlhuyj5kk2n5ghemqang7m since openssl-1.1.1s-frte5zgolo7z7skog6rr24zz2biz6vzn failed
==> Warning: Skipping build of py-setuptools-65.5.0-rf5bspymcmcnj7cj6f66mwwcue3tn4ub since python-3.10.8-3e7zykwsd4mlhuyj5kk2n5ghemqang7m failed
==> Warning: Skipping build of meson-0.64.0-6pp6m5nlczrv6cka4ex6uz6vcimkivkm since py-setuptools-65.5.0-rf5bspymcmcnj7cj6f66mwwcue3tn4ub failed
==> Warning: Skipping build of glib-2.74.1-2xlpdrymay4x6iunmmfmnrfsp2k3pu4w since meson-0.64.0-6pp6m5nlczrv6cka4ex6uz6vcimkivkm failed
==> Warning: Skipping build of icu4c-6 [...]

2022-12-06 06:22 UTC, alalazo commented
@Gabrielcarvfer I would have focused on:

> ERROR: Compiler 'gcc@12.1.0' does not have a C++ compiler configured.

In the second stage.

2022-12-06 12:34 UTC, Gabrielcarvfer commented
I just ran the first command to install ns-3. I believe it was supposed to find the local compiler or install the one mentioned, but it failed to install it. 

Also tried cleaning everything and installing gcc first, but failed in the same way. ¯\\_(ツ)_/¯

2022-12-06 13:30 UTC, alalazo commented
Spack finds the compilers in the PATH, if there's none already configure. What I mean is that you were likely missing the C++ compiler on your system for GCC 12. To check your configuration:
```console
$ spack config get compilers
compilers:
- compiler:
    spec: gcc@9.4.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

2022-12-06 14:56 UTC, Gabrielcarvfer commented
> Spack finds the compilers in the PATH, if there's none already configure. What I mean is that you were likely missing the C++ compiler on your system for GCC 12. To check your configuration:
> 
> ```
> $ spack config get compilers
> ```

<details><summary>Hmm, my bad. Let's check it then.</summary>

```
$ ./spack config get compilers
compilers:
- compiler:
    spec: clang@11.1.0
    paths:
      cc: /usr/bin/clang-11
      cxx: /usr/bin/clang++-11
      f77: null
      fc: null
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@14.0.0
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: null
      fc: null
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@10.4.0
    paths:
      cc: /usr/bin/gcc-10
      cxx: null
      f77: /usr/bin/gfortran-10
      fc: /usr/bin/gfortran-10
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@11.3.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@12.1.0
    paths:
      cc: /usr/bin/gcc-12
      cxx: null
      f77: null
      fc: null
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```
</details>

It had 3 compilers to choose from, and it chose the one that it couldn't find cxx...
 
Installed g++-12 then tried again, didn't find the new compiler. 
Tried spack compiler find, didn't catch it. 
Tried with the path, didn't catch it. 
Changed the compilers yaml manually and it built everything.

```
==> Installing ns-3-dev-3.37-jh3k6dtw7gnpwidja55733iqnilsv4nc
==> No binary for ns-3-dev-3.37-jh3k6dtw7gnpwidja55733iqnilsv4nc found: installing from source
==> Fetching https://gitlab.com/nsnam/ns-3-dev/-/archive/ns-3.37/ns-3-dev-ns-3.37.tar.bz2
==> No patches needed for ns-3-dev
==> ns-3-dev: Executing phase: 'cmake'
==> ns-3-dev: Executing phase: 'build'
==> ns-3-dev: Executing phase: 'install'
==> ns-3-dev: Successfully installed ns-3-dev-3.37-jh3k6dtw7gnpwidja55733iqnilsv4nc
  Stage: 21.00s.  Cmake: 7.03s.  Build: 4m 48.03s.  Install: 1.27s.  Total: 5m 17.60s
[+] /home/gabriel/Desktop/NewFolder/spack/opt/spack/linux-ubuntu22.04-zen/gcc-12.1.0/ns-3-dev-3.37-jh3k6dtw7gnpwidja55733iqnilsv4nc
```

I'm going to recheck with older compilers.

2022-12-06 15:13 UTC, Gabrielcarvfer commented
Retested lld/mold support in gcc:9.5.0, gcc:10.4.0, gcc:11.3 and gcc:12.1 and all of them passed. :/

2024-01-30 16:57 UTC, haampie approved these changes

2024-01-30 16:57 UTC, merged