Drop support for older rocm releases - 4.5.0 till 5.0.2
LLNL/spack pull request #34264
Opened 2022-12-02 13:57 UTC by srekolam

this PR is meant to drop support for the older rocm-releases from 4.5.0 till 5.0.2

2022-12-02 17:12 UTC, srekolam commented
@spackbot re-run pipeline:

2022-12-02 17:48 UTC, tldahlgren requested changes
Looks like one of the deprecated options is missing.

2022-12-02 17:48 UTC, tldahlgren commented on var/spack/repos/builtin/packages/comgr/package.py
> +    )
You  forgot the `deprecated` option here.

2022-12-02 18:29 UTC, cgmb commented
What's the criteria for deciding when and what to deprecate?

2022-12-02 19:19 UTC, srekolam commented
> What's the criteria for deciding when and what to deprecate?

@cgmb , usually i email and discuss in packaging meeting to check if older releases can be deprecated.

2022-12-05 16:30 UTC, srekolam commented
@tldahlgren can i get this reviewed and merged if things look okay.

2022-12-05 18:47 UTC, tldahlgren approved these changes
LGTM

2022-12-05 18:47 UTC, merged