Fix compile errors with latest HDF5 1.13.3
LLNL/spack pull request #34337
Opened 2022-12-05 19:20 UTC by houjun

2022-12-05 19:21 UTC, hyoklee approved these changes, later dismissed

2022-12-05 19:24 UTC, jeanbez submitted a review, later dismissed

2022-12-05 19:25 UTC, jeanbez approved these changes, later dismissed

2022-12-05 19:28 UTC, lrknox approved these changes, later dismissed

2022-12-05 19:50 UTC, adamjstewart commented on var/spack/repos/builtin/packages/hdf5-vol-async/package.py
> +    depends_on("hdf5@1.13.2 +mpi +threadsafe")
```suggestion
    depends_on("hdf5@1.13.0:1.13.2 +mpi +threadsafe")
```

2022-12-05 19:54 UTC, adamjstewart submitted a review, later dismissed
Fixes the build locally for me, thanks for the quick fix!

2022-12-05 20:32 UTC, lrknox approved these changes, later dismissed
Note that code for HDF5 1.13.0 and 1.13.1 and those versions in the spack hdf5 package are no longer available.  Spack with these changes will build hdf5-vol-async when hdf5@1.13.0 (or 1.13.1) are already available, but will fail to fetch code otherwise.  hdf5 1.13.2 is being kept for the November E$S release.  HDF5 1.14.0 should be available by the end of the year, in time for the February E4S release, after which all the experimental HDF5 1.13.x releases should disappear.

2022-12-06 10:13 UTC, haampie requested changes

2022-12-06 10:13 UTC, haampie commented on var/spack/repos/builtin/packages/hdf5-vol-async/package.py
> +    depends_on("hdf5@1.13.3: +mpi +threadsafe", when="@1.4:")
This gives no possible versions for hdf5 when @1.4:
```suggestion
    depends_on("hdf5 +mpi +threadsafe")
    depends_on("hdf5@1.13.0:1.13.2", when="@:1.3")
    depends_on("hdf5@1.13.3:", when="@1.4:")
```

2022-12-06 10:28 UTC, haampie approved these changes

2022-12-06 14:15 UTC, adamjstewart approved these changes

2022-12-06 14:15 UTC, merged