libxcrypt: add perl build dependency
LLNL/spack pull request #34343
Opened 2022-12-06 00:17 UTC by michaelkuhn

Without it, the build fails with:
```
Can't locate open.pm in @INC (you may need to install the open module) (@INC contains: ...) at ./build-aux/scripts/expand-selected-hashes line 20.
BEGIN failed--compilation aborted at ./build-aux/scripts/expand-selected-hashes line 20.
configure: error: bad value 'all' for --enable-hashes
```

2022-12-06 13:05 UTC, alalazo approved these changes

2022-12-07 21:02 UTC, bernhardkaindl commented
Also have a look at #34183:

It appears that `perl-file-open` is only needed for `perl@4.3.30:` and also take a look at my comment/requested change for it:

https://github.com/spack/spack/pull/34183#pullrequestreview-1205325463

2022-12-08 01:12 UTC, bernhardkaindl requested changes
A dependency on "perl" redundant because `libxcrypt` is an `AutotoolsPackage` and autoconf requires `/usr/bin/perl`.

It's actually `perl-open` that is missing and `depends_on("perl")` would be fooled by `spack external find perl` when the external perl does not provide `perl-open`, which is the case on all RHEL8-clones and newer.

BTW, `perl-open` is only needed for `perl@4.4.30:`. Please see #34183.

2023-01-10 14:11 UTC, haampie commented
Sorry for not merging this sooner... I'm now closing in favor of #34867 which solves the issue of partial system perl installs

2023-01-10 14:11 UTC, closed without merging