new command: `spack pkg grep` to search package files
LLNL/spack pull request #34388
Opened 2022-12-08 02:21 UTC by tgamblin

It's very common for us to tell users to grep through the existing Spack packages to find examples of what they want, and it's also very common for package developers to do it. Now, searching packages is even easier.

`spack pkg grep` runs grep on all `package.py` files in repos known to Spack. It has no special options other than the search string; all options passed to it are forwarded along to `grep`.

```console
> spack pkg grep --help
usage: spack pkg grep [--help] ...

positional arguments:
  grep_args  arguments for grep

options:
  --help     show this help message and exit
```

## Examples:

```console
> spack pkg grep CMakePackage | head -3
/Users/gamblin2/src/spack/var/spack/repos/builtin/packages/3dtk/package.py:class _3dtk(CMakePackage):
/Users/gamblin2/src/spack/var/spack/repos/builtin/packages/abseil-cpp/package.py:class AbseilCpp(CMakePackage):
/Users/gamblin2/src/spack/var/spack/repos/builtin/packages/accfft/package.py:class Accfft(CMakePackage, CudaPackage):
```

```console
> spack pkg grep -Eho '(\S*)\(PythonPackage\)' | head -3
AwsParallelcluster(PythonPackage)
Awscli(PythonPackage)
Bueno(PythonPackage)
```

## Return value

This retains the return value semantics of `grep`:
* 0  for found,
* 1  for not found
* >1 for error

## Choosing a `grep`

You can set the ``SPACK_GREP`` environment variable to choose the ``grep`` executable this command should use.

2022-12-08 02:26 UTC, adamjstewart commented
Interesting! This is obviously something I do daily. I currently have a `csv` alias that Cd's to Spack's Var directory, then I run grep from there. This is slightly quicker.

This is up there with `spack edit` and `spack unit-test` in the sense that it's a tiny shortcut on top of a normal shell command. I don't think it's too ridiculous to add, doesn't have a ton of overhead to maintain, and non-power users can just ignore it. So it's fine by me.

2022-12-08 10:18 UTC, alalazo approved these changes
Agree completely with @adamjstewart review

2022-12-08 10:19 UTC, alalazo requested changes
...but tests must pass first! :laughing:

2022-12-08 17:19 UTC, trws commented
Looks good if tests pass.  Only thing I'd request, if we're doing this maybe allow the user to specify the name of their grep command? Mainly to deal with things like ggpep as default name for gnu grep on mac, wanting egrep or pt or whatever for different flags etc.

2022-12-08 18:59 UTC, adamjstewart commented
For @trws's suggestion, maybe we could rely on a `SPACK_GREP` env var like we do for `spack edit`?

2022-12-08 19:35 UTC, trws commented
I like that idea, it's similar to how FZF and others normally handle it so it would be convenient to add to existing environment setups that pick a grep for other tools.

2022-12-08 22:06 UTC, tgamblin commented
@trws added

2022-12-09 02:12 UTC, adamjstewart approved these changes, later dismissed
Works for me!

2022-12-09 10:38 UTC, alalazo approved these changes
@trws @adamjstewart If you want to have a final look this LGTM

2022-12-09 18:03 UTC, adamjstewart approved these changes

2022-12-09 18:07 UTC, merged