intel-oneapi-tbb: It is only available for x86_64
LLNL/spack pull request #34393
Opened 2022-12-08 06:37 UTC by bernhardkaindl

When trying to build other packages there were attempts to build intel-oneapi-tbb on arm64 and ppc64, but they failed as it is only provided for x86_64 by Intel. Copied from e.g. povray and others:
```py
var/spack/repos/builtin/packages/povray/package.py:    conflicts("+mkl", when="target=aarch64:", msg="Intel MKL only runs on x86")
var/spack/repos/builtin/packages/povray/package.py:    conflicts("+mkl", when="target=ppc64:", msg="Intel MKL only runs on x86")
var/spack/repos/builtin/packages/povray/package.py:    conflicts("+mkl", when="target=ppc64le:", msg="Intel MKL only runs on x86")
```

2022-12-08 10:22 UTC, alalazo approved these changes
Waiting for @rscohn2 to confirm, but conflicts LGTM

2022-12-08 12:53 UTC, rscohn2 requested changes
Thanks for the fix. Can you put it here instead:
https://github.com/spack/spack/blob/2c668f4bfd073b94c1ec09df179808e136d5fbab/lib/spack/spack/build_systems/oneapi.py#L19

2022-12-10 13:22 UTC, rscohn2 commented
I made the change in the base package instead: #34441

2022-12-12 09:39 UTC, alalazo commented
Closing as superseded by #34441

2022-12-12 09:39 UTC, closed without merging