nvhpc: add 22.11
LLNL/spack pull request #34410
Opened 2022-12-08 19:35 UTC by wyphan

SHA256 checksums are taken from https://developer.download.nvidia.com/hpc-sdk/22.11/sha256sum.txt

2022-12-08 20:10 UTC, tldahlgren requested changes
Manually checked the linked file to "confirm" the checksums match.

Still needs the syntax fix though.

2022-12-08 20:10 UTC, tldahlgren commented on var/spack/repos/builtin/packages/nvhpc/package.py
> +        },
These are tuples, so lines 28, 32, and 36 should be `),`, not `},`.

2022-12-08 20:17 UTC, tldahlgren commented on var/spack/repos/builtin/packages/nvhpc/package.py
> +            "cb91b3a04368457d5cfe3c0e9c0611591fdc8076b01ea977343fe7db7fdcfa3c",
Confirmed this commit with `spack checksum`.

2022-12-08 20:39 UTC, wyphan commented on var/spack/repos/builtin/packages/nvhpc/package.py
> +        },
Ah, right, thanks for catching that!

2022-12-08 21:07 UTC, tldahlgren approved these changes

2022-12-08 21:15 UTC, tldahlgren commented
Will defer the merge to give @samcmill and or @ax3l a chance to comment.

2022-12-09 15:33 UTC, samcmill commented
LGTM

+ @fspiga for viz

2022-12-09 15:34 UTC, samcmill approved these changes

2022-12-12 10:35 UTC, merged