New Package: py-anuga-community
LLNL/spack pull request #34417
Opened 2022-12-09 07:28 UTC by jayashripawar

2022-12-09 09:35 UTC, alalazo commented
@spackbot fix style

2022-12-10 16:07 UTC, adamjstewart requested changes
Most of my comments apply to all packages

2022-12-10 16:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-anuga-community/package.py
> +# ----------------------------------------------------------------------------
You'll need to remove this and add back the license, same for all other files

2022-12-10 16:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-anuga-community/package.py
> +    url      = "https://github.com/anuga-community/anuga_core.git"
How is this different from the `py-anuga` package? Should we combine them and make these different versions, or share a base class?

2022-12-10 16:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-anuga-community/package.py
> +    version('main',  branch='main', preferred=True)
We generally prefer stable releases since main is a moving target

2022-12-10 16:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pymetis/package.py
> +    url      = "https://pypi.io/packages/source/P/PyMetis/PyMetis-2020.1.tar.gz"
Should use the `pypi` attribute

2022-12-10 16:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-tzdata/package.py
> +    url = "https://github.com/python/tzdata/archive/refs/tags/2022.7.tar.gz"
Need to add stable release, use PyPI downloads

2024-02-17 22:03 UTC, alecbcs commented
Going to close this PR due to a lack of movement over the past year. @jayashripawar happy to reopen if you'd still like to get these changes merged and have time to address the review feedback.

2024-02-17 22:03 UTC, closed without merging