package/libproxy: fix py3 install
LLNL/spack pull request #34431
Opened 2022-12-09 20:56 UTC by Sinan81

in centos7, libproxy tries to install python under system directories. Hence, why this fix is needed.

2022-12-09 21:11 UTC, Sinan81 commented
pinging @adamjstewart since he added python variant recently. This is not urgent.

2022-12-09 22:26 UTC, Sinan81 commented
@spackbot fix style

2022-12-09 23:20 UTC, adamjstewart requested changes

2022-12-09 23:20 UTC, adamjstewart commented on var/spack/repos/builtin/packages/libproxy/package.py
>      depends_on("python", type=("build", "run"), when="+python")
You can remove this line, it's implied by `extends`

2022-12-09 23:20 UTC, adamjstewart commented on var/spack/repos/builtin/packages/libproxy/package.py
> +            args.append(self.define("PYTHON3_SITEPKG_DIR", pysite))
```suggestion
            args.append(self.define("PYTHON3_SITEPKG_DIR", python_platlib))
```
The exact directory changes depending on OS, Python version, external vs. internal, time of day, mood of your computer, etc, etc. Let me know if this doesn't work, sometimes it's finicky and thinks `python_platlib` isn't defined.

2022-12-09 23:57 UTC, Sinan81 commented
Why not disable python variant by default?

2022-12-10 00:20 UTC, adamjstewart commented
Up to you, this package has no official maintainer listed. I translate this to "no one care about the package or its defaults, so we can change whatever we want"

2022-12-10 00:21 UTC, adamjstewart approved these changes, later dismissed
LGTM, just confirm that `python_platlib` is working as expected and I'll merge.

2022-12-10 00:23 UTC, adamjstewart submitted a review, later dismissed

2022-12-10 00:30 UTC, Sinan81 commented
I confirm that python_platlib worked **during build.** when i try to import libproxy though, I am getting runtime errors due to python referring to the system installation of libproxy. Not sure if I'm importing correctly. Let me find an example.

2022-12-10 01:37 UTC, adamjstewart commented
Might need to set LD_LIBRARY_PATH, Python is a nightmare

2022-12-13 01:02 UTC, Sinan81 commented
it works after adding setup_run_env.

2022-12-13 01:02 UTC, Sinan81 commented
also noticed version 0.4.16 throws runtime errors with latest python. Hence added a conflict statement.

2022-12-13 01:04 UTC, Sinan81 commented
Does Spack CI automatically checks if after the build, python packages import just fine?

2022-12-13 03:08 UTC, adamjstewart commented on var/spack/repos/builtin/packages/libproxy/package.py
> +    conflicts("python@3.9:", when="@:0.4.16")
```suggestion
    extends("python@:3.8", when="+python")
```
I believe this works as well

2022-12-13 03:08 UTC, adamjstewart commented on var/spack/repos/builtin/packages/libproxy/package.py
> +            env.prepend_path("LD_LIBRARY_PATH", self.prefix.lib)
It's unfortunate that rpath doesn't work for Python, but we do the same thing in other packages too. Actually, can you do this for macOS too? Something like:
```python
if self.spec.satisfies("platform=darwin"):                                                  
    env.prepend_path("DYLD_FALLBACK_LIBRARY_PATH", self.prefix.lib)                                    
else:                                                                                       
    env.prepend_path("LD_LIBRARY_PATH", self.prefix.lib) 
```
See `py-cartopy` for another example of this. Any idea if the path is ever in `lib64` instead of `lib`?

2022-12-13 03:10 UTC, adamjstewart commented
> Does Spack CI automatically checks if after the build, python packages import just fine?

1. Spack CI only tests packages in our CI stack (E4S, ML, etc.), it doesn't test all packages
2. I don't believe we build with `--test=root`, but I would like to add that someday, at least for our Python stacks

2022-12-13 03:22 UTC, tgamblin commented
The main E4S stack builds with tests enabled. We could expand the number of stacks that do this.

2022-12-13 03:26 UTC, adamjstewart commented
`--test=root` should be possible for the ML stack, although I wouldn't be surprised if some bugs pop out. `--test=all` would break with a lot of circular deps. At the very least, we should run `spack test` after `spack install`. For Python packages, the main thing to be concerned about is import tests, which are included in both.

2023-01-04 05:43 UTC, Sinan81 commented
In regards to an earlier question, there's no `lib64` directory but there's libexec:
```$ tree
.
├── bin
│   └── proxy
├── include
│   └── proxy.h
├── lib
│   ├── libproxy
│   │   └── 0.4.17
│   │       └── modules
│   │           ├── config_gnome3.so
│   │           ├── config_kde.so
│   │           └── config_pacrunner.so
│   ├── libproxy.so -> libproxy.so.1
│   ├── libproxy.so.1 -> libproxy.so.1.0.0
│   ├── libproxy.so.1.0.0
│   └── pkgconfig
│       └── libproxy-1.0.pc
├── libexec
│   └── pxgsettings
└── share
    └── cmake
        └── Modules
            └── Findlibproxy.cmake

11 directories, 11 files
```

2023-01-04 17:02 UTC, adamjstewart commented
There's no lib64 directory on CentOS 7, but that doesn't mean there's no lib64 directory on other OSes...

2023-01-04 17:08 UTC, adamjstewart commented on var/spack/repos/builtin/packages/libproxy/package.py
> +            libs = self.prefix.lib
Would probably be better to use `self.spec["libproxy"].libs.directories[0]`. You may have to implement a `libs` method if the libraries aren't named `libproxy.so`.

2023-01-04 20:46 UTC, adamjstewart approved these changes

2023-01-04 21:01 UTC, merged