add_new_package: py-file-magic
LLNL/spack pull request #34486
Opened 2022-12-13 01:46 UTC by Sinan81

Note that this is a different package than `py-filemagic`

2022-12-13 03:21 UTC, adamjstewart requested changes

2022-12-13 03:21 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-file-magic/package.py
> +    depends_on('py-setuptools', type='build')
```suggestion
    depends_on('py-setuptools@61:', type='build')
```

2023-01-04 05:39 UTC, Sinan81 commented
@spackbot fix style

2023-01-04 17:08 UTC, adamjstewart approved these changes

2023-01-04 17:08 UTC, merged

2024-08-26 13:24 UTC, alalazo commented
_One year and a half later_ Do you know where the sources are located for this package?

2024-08-26 13:48 UTC, alalazo commented
Ok, these seems to come from https://github.com/file/file directly.