bacio version fix
LLNL/spack pull request #34575
Opened 2022-12-16 20:18 UTC by AlexanderRichert-NOAA

This PR patches an incorrect version in bacio's VERSION file for bacio@2.4.1. For that release, VERSION contains 2.4.**0**, which gets propagated into the cmake config files.

2022-12-19 13:58 UTC, Hang-Lei-NOAA approved these changes, later dismissed

2022-12-21 19:32 UTC, alalazo approved these changes

2022-12-21 19:35 UTC, alalazo requested changes

2022-12-21 19:35 UTC, alalazo commented on var/spack/repos/builtin/packages/bacio/package.py
> +        filter_file(".*", "2.4.1", "VERSION", when="bacio@2.4.1")
After looking at the definition of `filter_file`, I think you need to (there is no `when=` argument):
```suggestion
        if self.spec.satisifes("@2.4.1"):
            filter_file(".*", "2.4.1", "VERSION")
```

2022-12-22 08:12 UTC, alalazo approved these changes

2022-12-22 08:12 UTC, merged