Bump memory requests for e4s/ml generate jobs
LLNL/spack pull request #34648
Opened 2022-12-21 21:40 UTC by mvandenburgh

Bumps memory requests from 8G => 16G for some stacks. These particular stacks have consistently shown memory usage higher than 8G, which has led to pods being `OOMKilled`.

2022-12-21 22:04 UTC, zackgalbreath commented
This looks right to me, but let's wait and see when the pipelines run. We should be able to see these new memory requests in the relevant job logs.

2022-12-22 15:28 UTC, mvandenburgh commented
@spackbot run pipeline

2022-12-22 17:11 UTC, zackgalbreath requested changes
@mvandenburgh it looks like that worked! see here:
https://gitlab.spack.io/spack/spack/-/jobs/5037528
> "MemoryRequest" overwritten with "16G"

Would you please make the same changes for the relevant `-protected-generate` jobs too?

2023-01-03 23:53 UTC, zackgalbreath approved these changes, later dismissed

2023-01-03 23:53 UTC, zackgalbreath commented
@spackbot run pipeline

2023-01-04 00:20 UTC, scottwittenburg commented
Be aware that @haampie is doing something similar in #34784 but there he is getting the number of concretization processes to match with the cpu request.  He also did some profiling and found that about 1GB of memory per core is required for concretization (I'm not sure if that guideline is across the board or just for E4S), so the memory request is set accordingly in that PR as well.

2023-01-10 17:48 UTC, zackgalbreath submitted a review, later dismissed

2023-01-11 14:55 UTC, zackgalbreath commented
@spackbot run pipeline

2023-01-11 17:24 UTC, zackgalbreath approved these changes

2023-01-11 17:41 UTC, scottwittenburg commented
Since we have verified some of these recent jobs failing with "pod status is failed" are getting evicted due to memory pressure, let's merge this while we figure out if #34784 is a better approach or it it suffers from similar problem.

2023-01-11 17:41 UTC, merged