faiss: fixed error when importing faiss python package
LLNL/spack pull request #34672
Opened 2022-12-23 03:52 UTC by lpottier

Missing directory in `LD_LIBRARY_PATH` resulting into the following error when doing `import faiss`:
```python
ImportError: libfaiss_python_callbacks.so: cannot open shared object file: No such file or directory
```

Signed-off-by: Loïc Pottier <48072795+lpottier@users.noreply.github.com>

2023-01-02 15:31 UTC, haampie requested changes
Hm, with this interaction between cmake and pip we end up with bad rpaths pointing to the stage dir (this is due to `CMAKE_INSTALL_RPATH_USE_LINK_PATH`):

```
 0x000000000000000f (RPATH)              Library rpath: [/tmp/harmen/spack-stage/spack-stage-faiss-1.7.2-a7ouyzvscepi75hjspfdvstcrnnwoh7v/spack-build-a7ouyzv/faiss:/tmp/harmen/spack-stage/spack-stage-faiss-1.7.2-a7ouyzvscepi75hjspfdvstcrnnwoh7v/spack-build-a7ouyzv/faiss/python:/home/harmen/spack/opt/spack/linux-ubuntu22.10-zen2/gcc-12.2.0/faiss-1.7.2-a7ouyzvscepi75hjspfdvstcrnnwoh7v/lib:/home/harmen/spack/opt/spack/linux-ubuntu22.10-zen2/gcc-12.2.0/faiss-1.7.2-a7ouyzvscepi75hjspfdvstcrnnwoh7v/lib64:/home/harmen/spack/opt/spack/linux-ubuntu22.10-zen2/gcc-12.2.0/openblas-0.3.21-sluybbuclqjdcmbf73xola4lddhjncrz/lib]
```

Is faiss building the python extension in a standard way?

2023-01-02 15:31 UTC, haampie commented on var/spack/repos/builtin/packages/faiss/package.py
> +            env.append_path("LD_LIBRARY_PATH", os.path.join(python_platlib, "faiss/"))
```suggestion
            env.append_path("LD_LIBRARY_PATH", os.path.join(python_platlib, "faiss"))
```

2023-01-02 17:37 UTC, haampie commented
I did some research on macos (but didn't try to install faiss because my macbook air is too old and slow)

Shared libraries are created with install_name set to `@rpath/lib<name>.dylib` [since CMake 3.0](https://cmake.org/cmake/help/latest/policy/CMP0042.html#policy:CMP0042), so the linker always copies `@rpath/lib<name>.dylib` as a load command. That means that adding an rpath as `@loader_path` on macOS is enough:

```cmake
if(APPLE)
  set_target_properties(your_target PROPERTIES INSTALL_RPATH "@loader_path;${CMAKE_INSTALL_RPATH}")
elseif(UNIX)
  set_target_properties(your_target PROPERTIES INSTALL_RPATH "$ORIGIN;${CMAKE_INSTALL_RPATH}")
endif()
```

The `;` is there to inform cmake this is a list of strings; cmake will then concatenated them properly with `:` on linux.

2023-01-05 22:27 UTC, lpottier commented
Hi @haampie, thanks for your review! 
I will do some research tonight about how we could improve this recipe without messing up too much `LD_LIBRARY_PATH`. Right now, it works on macOS and Linux.

2023-01-10 10:55 UTC, haampie commented
Well, it turns out to be a giant mess :p 

The build system is missing support for properly installing the Python part. And right now libraries are installed by Python instead of through CMake, and that causes issues since CMake patches binaries (their rpaths) upon install.

I'm not sure if there is a better solution. Making an issue upstream would be good.

2023-01-10 10:55 UTC, haampie approved these changes

2023-01-11 21:47 UTC, lpottier commented
Okay got it, thanks @haampie . I have opened an issue upstream: https://github.com/spack/spack/issues/34893.

2023-01-17 12:43 UTC, merged