Adding recipes for py-qutip and py-qutip-qip
LLNL/spack pull request #34835
Opened 2023-01-06 03:01 UTC by marcodelapierre

These are 2 related Quantum Computing packages

2023-01-06 03:25 UTC, marcodelapierre commented
@adamjstewart pinging you on this one, thank you :-)

2023-01-06 03:41 UTC, adamjstewart requested changes

2023-01-06 03:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-qutip-qip/package.py
> +    depends_on("py-numpy@1.12:", type=("build", "run"))
```suggestion
    depends_on("py-numpy@1.16.6:", type=("build", "run"))
```

2023-01-06 03:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-qutip-qip/package.py
> +    depends_on("py-qutip@4.5:", type=("build", "run"))
```suggestion
    depends_on("py-qutip@4.6:", type=("build", "run"))
```

2023-01-06 03:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-qutip-qip/package.py
> +    depends_on("py-packaging", type="build")
```suggestion
    depends_on("py-packaging", type=("build", "run"))
```

2023-01-06 03:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-qutip/package.py
> +    depends_on("py-cython@0.29.20:", type=("build", "run"))
```suggestion
    depends_on("py-cython@0.29.20:", type="build")
```

2023-01-06 03:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-qutip/package.py
> +    depends_on("py-packaging", type="build")
```suggestion
    depends_on("py-packaging", type=("build", "run"))
```

2023-01-06 04:47 UTC, marcodelapierre commented
I have applied the requested edits

2023-01-06 17:20 UTC, adamjstewart commented
@spackbot run pipeline

2023-01-06 17:21 UTC, adamjstewart approved these changes

2023-01-07 01:09 UTC, marcodelapierre commented
@spackbot run pipeline

2023-01-07 01:22 UTC, merged