Update parallelio from NOAA-EMC fork
LLNL/spack pull request #34837
Opened 2023-01-06 05:02 UTC by AlexanderRichert-NOAA

This PR provides significant updates to the parallelio package. Improvements include:
- Change underscores to periods in version numbers
- Add a 'shared' variant to allow static-only builds
- Add an MPI-related patch for versions up 2.5.6
- Add/update several build-related variables

This PR is intended to support operations and R&D for NOAA/NWS.

2023-01-06 12:50 UTC, jedwards4b submitted a review, later dismissed

2023-01-06 16:46 UTC, AlexanderRichert-NOAA commented
@jedwards4b @climbfuji I'm working on style fixes and I just noticed there are two "url_for_version" functions defined. Should I assume that the second one is the correct one (I'm assuming that's what's actually been getting used)?

2023-01-06 16:52 UTC, jedwards4b submitted a review, later dismissed

2023-01-06 17:00 UTC, climbfuji approved these changes, later dismissed
Thanks a lot, @AlexanderRichert-NOAA !

2023-01-10 10:34 UTC, haampie requested changes

2023-01-10 10:34 UTC, haampie commented on var/spack/repos/builtin/packages/parallelio/package.py
> +    depends_on("cmake@3.7:")
```suggestion
    depends_on("cmake@3.7:", type="build")
```

2023-01-10 23:29 UTC, jedwards4b approved these changes

2023-01-11 03:18 UTC, climbfuji approved these changes

2023-01-23 21:28 UTC, haampie approved these changes

2023-01-23 21:29 UTC, merged