Update qmd-progress package.py
LLNL/spack pull request #34841
Opened 2023-01-06 15:39 UTC by jeanlucf22

2023-01-10 23:00 UTC, tldahlgren requested changes
Confirmed the homepage, branch, and new version; however, the old version hashes no longer match with the new url.

2023-01-10 23:00 UTC, tldahlgren commented on var/spack/repos/builtin/packages/qmd-progress/package.py
>      version("1.0.0", sha256="28c99eb80d9a6b09e1d01d61538b3b924850d89c6a8bfb5d3e8b6490be822296")
The sha256 for these versions are no longer valid.  Any idea why the archive version doesn't match the tarball version?

```
$ spack checksum qmd-progress 1.1.0 1.0.0
==> Found 2 versions of qmd-progress:
  
  1.1.0  https://github.com/lanl/qmd-progress/archive/refs/tags/v1.1.0.tar.gz
  1.0.0  https://github.com/lanl/qmd-progress/archive/refs/tags/v1.0.0.tar.gz

==> Fetching https://github.com/lanl/qmd-progress/archive/refs/tags/v1.1.0.tar.gz
==> Fetching https://github.com/lanl/qmd-progress/archive/refs/tags/v1.0.0.tar.gz

    version("1.1.0", sha256="757d2606d7b7f38e7f8f491bf7369b88de55062bae0b12a9928f0a5acae993bd")
    version("1.0.0", sha256="eed87e68b4a1533a3ed70c1662feca4ac890b985f3326fc94522c2f71f198fdc")
```

You could add `url_for_version` for those at or below `1.1.0` (see https://spack.readthedocs.io/en/latest/packaging_guide.html#version-urls) or update them.

2023-01-22 00:50 UTC, jeanlucf22 commented on var/spack/repos/builtin/packages/qmd-progress/package.py
>      version("1.0.0", sha256="28c99eb80d9a6b09e1d01d61538b3b924850d89c6a8bfb5d3e8b6490be822296")
I updated the old sha256

2023-01-23 22:20 UTC, tldahlgren approved these changes
Confirmed the branch (existence) and the three sha256.

2023-01-23 22:20 UTC, merged