Charliecloud: add internal SquashFUSE support
LLNL/spack pull request #34847
Opened 2023-01-06 20:38 UTC by benkirk

Charliecloud's internal SquashFUSE support is enabled with this PR as a variant.  

This requires squashfuse@0.1.105; which is also added.

2023-01-06 23:07 UTC, reidpr approved these changes
LGTM, thanks for doing this @benkirk! Very exciting to have this important feature in Spack.

IMO the squash variant should be the default, but I wouldn't want discussion of that to hold up this PR.

2023-01-06 23:16 UTC, benkirk commented
Great @reidpr; `+squash` is the default in the PR, happy that's agreeable to you!

2023-01-10 10:31 UTC, haampie commented
I'd kinda prefer to stick to the tarball with configure scripts for squashfuse, also those tarballs have a stable checksum, whereas the github download may not. So if you need the 0.1.105 version right now, please make an exception for its url: https://spack.readthedocs.io/en/latest/packaging_guide.html#version-urls

Also please bump the thread here: https://github.com/vasi/squashfuse/issues/74 the 0.1.105 release has issues in general :|

2023-01-10 22:39 UTC, tldahlgren approved these changes
Confirmed the sha256 for the 6 new versions of `squashfuse`.

2023-01-10 22:39 UTC, tldahlgren commented
Deferring merge decision to @haampie

2023-08-09 21:49 UTC, alecbcs commented
@benkirk would it be possible to add SquashFUSE support while still continuing to use the manually created tarball artifacts?

2023-08-22 18:34 UTC, j-ogas requested changes
Very nice, thank you. I believe the `configure_args` method needs something the following to build charliecloud with the auto-squashfuse auto mounting feature.

```python
    def configure_args(self):
[...]
        if "+squashfuse" in self.spec:
            squashfuse_prefix = "{0}".format(self.spec["squashfuse"].prefix)
            args.append("--with-libsquashfuse={0}".format(squashfuse_prefix))
```

2023-08-22 18:34 UTC, j-ogas commented on var/spack/repos/builtin/packages/charliecloud/package.py
> +    depends_on("squashfs", when="+squash")
```suggestion
    depends_on("squashfs", type="build", when="+squash")
```

2023-08-22 18:35 UTC, j-ogas commented on var/spack/repos/builtin/packages/charliecloud/package.py
> +    depends_on("squashfuse@0.1.105:", when="+squash")
```suggestion
    depends_on("squashfuse@0.1.105:", type="build", when="+squash")
```

2023-08-22 18:44 UTC, j-ogas commented
Also, it is worth noting that the Charliecloud auto-mounting feature will also need to link to the host `libfuse3` library at build time. It isn't clear to me how to handle such a thing in Spack. A shot in the dark would be something like:

```python
depends_on("libfuse3.so", type="link", when="+squashfuse")
```

2023-11-27 18:30 UTC, benkirk commented
Closing in deference to #41276.

2023-11-27 18:30 UTC, closed without merging