py-annoy: add 1.17.1
LLNL/spack pull request #34911
Opened 2023-01-12 21:20 UTC by ChristopherChristofi

2023-01-12 22:09 UTC, tldahlgren reviewed
Confirmed sha256.

2023-01-12 22:10 UTC, tldahlgren commented
Added PythonPackage maintainers to Reviewers list.

2023-01-13 17:41 UTC, adamjstewart requested changes

2023-01-13 17:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-annoy/package.py
> +    depends_on("py-nose", type="build")
```suggestion
    depends_on("py-nose@1:", type="build")
```

2023-01-13 23:02 UTC, adamjstewart approved these changes

2023-01-15 01:21 UTC, merged