Convert libpng to build with CMake
LLNL/spack pull request #35105
Opened 2023-01-23 20:25 UTC by johnwparent

Refactor libpng to be built with CMake instead of autotools and in doing so, support Windows.

Part of #34938

2023-01-23 20:38 UTC, AlexanderRichert-NOAA requested changes
This PR breaks existing functionality. "configure_args" should be removed and the functionality in it should be updated for cmake.

2023-01-23 20:58 UTC, johnwparent commented
> This PR breaks existing functionality. "configure_args" should be removed and the functionality in it should be updated for cmake.

Thanks for pointing that out. The proper refactor must have been dropped when I cannibalized this from a few different PRs. I've added the actual cmake args back from it's original state. Feel free to re-review.

2023-01-23 21:08 UTC, AlexanderRichert-NOAA commented
The default values for PNG_SHARED and PNG_STATIC in CMakeLists.txt are both ON. In the current version, the use of "enable_or_disable" means that when a given option isn't specified, it gets the "--no-..." configure option, so that logic should get reproduced here.

2023-01-23 21:26 UTC, johnwparent commented
> The default values for PNG_SHARED and PNG_STATIC in CMakeLists.txt are both ON. In the current version, the use of "enable_or_disable" means that when a given option isn't specified, it gets the "--no-..." configure option, so that logic should get reproduced here.

Thanks, I didn't realize that's how that helper worked. I'll refactor now.

2023-01-23 21:40 UTC, johnwparent commented
> The default values for PNG_SHARED and PNG_STATIC in CMakeLists.txt are both ON. In the current version, the use of "enable_or_disable" means that when a given option isn't specified, it gets the "--no-..." configure option, so that logic should get reproduced here.

Perhaps I'm misunderstanding.

The way the package is right now in the PR if the spec is `libpng libs=shared`, `PNG_SHARED` will be True, while `PNG_STATIC` will be false because the string `"static"` will not be present in the spec. When the spec is `libpng libs=static`, `PNG_SHARED` will be false and `PNG_STATIC` will be true for the same reason as before. The only place where I can see a potential disconnect is the default behavior. If the spec is just `libpng` then the libs default is `shared,static`, and with the behavior I add in this PR,  this means both `PNG_SHARED` and `PNG_STATIC` will be true, should this not be the case?

2023-01-23 21:47 UTC, AlexanderRichert-NOAA commented
I would suggest testing it out. From what I can tell, what's going on is that PNG_SHARED and PNG_STATIC are both default ON in CMakeLists.txt, therefore if eitheir of them is not explicitly set to OFF in package.py, then it will be ON. Does that make sense?

2023-01-23 22:46 UTC, johnwparent commented
`PNG_STATIC` and `PNG_SHARED` are on by default in the CMake interface for libpng. This is correct. However Spack is _never_ not overridding the defaults. We are _always_ providing CMake some definition for these options on the command line. As stated above, the way it is currently configured, if _neither_ `libs=shared` or `libs=static` are specified by the calling spec, the default case is triggered, where both are True. If one or the other is specified, then either `"static" in self.spec.variants["libs"].value` or `"shared" in self.spec.variants["libs"]` will evaluate to false. This sets the cmake command line to `PNG_STATIC` or `PNG_SHARED` to `OFF` depending on which was specified. 

Testing simply confirms what I have stated above.

2023-01-23 23:18 UTC, AlexanderRichert-NOAA commented
Okay this looks good. I may have tested incorrectly earlier in which case apologies for the confusion.

2023-01-23 23:19 UTC, AlexanderRichert-NOAA approved these changes

2023-03-16 23:44 UTC, scheibelp approved these changes

2023-03-16 23:44 UTC, merged

2023-05-10 16:56 UTC, climbfuji commented
@scheibelp We've run into issues building `libpng` on macOS arch64 after this PR: https://github.com/NOAA-EMC/spack-stack/issues/572

Have you encountered that? Does the spack CI system cover macOS arch64 ?

2023-05-10 18:52 UTC, climbfuji commented
@scheibelp See here for a solution: https://github.com/NOAA-EMC/spack-stack/issues/572#issuecomment-1542620688

We'll get it fixed in our fork appropriately and then push the commit for a PR to spack develop.

2023-05-11 16:27 UTC, climbfuji commented
PR is here: https://github.com/spack/spack/pull/37613