Fix awscli and deps
LLNL/spack pull request #35158
Opened 2023-01-25 09:58 UTC by haampie

- py-docutils/py-pyyaml specify python 3.11 compat
- bump awscli / py-botocore

2023-01-26 08:24 UTC, alalazo commented
@spackbot run pipeline

2023-01-26 11:20 UTC, alalazo approved these changes, later dismissed

2023-01-26 16:25 UTC, adamjstewart requested changes

2023-01-26 16:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/awscli/package.py
> +    depends_on("py-colorama@0.2.5:0.4", type=("build", "run"))
Upper bound needs patch version

2023-01-26 16:25 UTC, adamjstewart commented on var/spack/repos/builtin/packages/awscli/package.py
> +    depends_on("py-rsa@3.1.2:4.8.0", when="@1.27", type=("build", "run"))
```suggestion
    depends_on("py-rsa@3.1.2:4.7", when="@1.27", type=("build", "run"))
```

2023-01-27 16:28 UTC, adamjstewart requested changes

2023-01-27 16:28 UTC, adamjstewart commented on var/spack/repos/builtin/packages/awscli/package.py
> +    depends_on("py-colorama@0.2.5:0.4.6", when="@1.27", type=("build", "run"))
```suggestion
    depends_on("py-colorama@0.2.5:0.4.4", when="@1.27", type=("build", "run"))
```

2023-01-27 16:28 UTC, adamjstewart commented on var/spack/repos/builtin/packages/awscli/package.py
> +    depends_on("py-rsa@3.1.2:4.7.0", when="@1.27", type=("build", "run"))
```suggestion
    depends_on("py-rsa@3.1.2:4.7", when="@1.27", type=("build", "run"))
```

2023-01-27 16:28 UTC, adamjstewart commented on var/spack/repos/builtin/packages/awscli/package.py
> +    depends_on("py-nose", when="@1.16", type="test")
You can remove these test deps, we don't actually run any tests in this package

2023-01-27 16:41 UTC, adamjstewart approved these changes

2023-01-30 15:31 UTC, haampie commented
@spackbot rerun pipeline

2023-01-31 17:57 UTC, haampie commented
@spackbot run pipeline

2023-01-31 18:51 UTC, haampie commented
@spackbot run pipeline

2023-01-31 21:17 UTC, haampie commented
@spackbot run pipeline

2023-01-31 21:32 UTC, merged