py-igor: new package
LLNL/spack pull request #35229
Opened 2023-01-30 08:40 UTC by heerener

2023-01-30 19:12 UTC, adamjstewart requested changes

2023-01-30 19:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-igor/package.py
> +        setupfile.filter("distutils.core", "setuptools")
I believe pip does this automatically. Not sure about build which we're planning to switch to in the future.

2023-01-30 19:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-igor/package.py
> +    depends_on("py-nose", type="run")
Nose is only needed for unit tests, which we don't run here. I would remove it.

2023-01-30 19:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-igor/package.py
> +    depends_on("py-matplotlib", type="run")
I would make numpy and matplotlib `type=("build", "run")` so the import tests pass.

2023-01-31 15:57 UTC, adamjstewart approved these changes

2023-01-31 15:57 UTC, adamjstewart commented
@spackbot run pipeline

2023-02-03 10:34 UTC, heerener commented
@adamjstewart is that docs build something I can fix from my end?

2023-02-03 15:24 UTC, adamjstewart commented
Probably transient, let me try kicking the tests

2023-02-03 16:02 UTC, merged