py-jinja2-cli: new package
LLNL/spack pull request #35238
Opened 2023-01-30 13:12 UTC by heerener

2023-01-30 17:53 UTC, tldahlgren approved these changes, later dismissed
Confirmed both sha256.

2023-01-30 18:50 UTC, adamjstewart requested changes

2023-01-30 18:50 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-jinja2-cli/package.py
> +    depends_on("py-jinja2", type="run")
```suggestion
    depends_on("py-setuptools", type="build")

    depends_on("py-jinja2", type=("build", "run"))
```

2023-01-31 15:56 UTC, adamjstewart approved these changes

2023-01-31 15:56 UTC, adamjstewart commented
@spackbot run pipeline

2023-01-31 16:17 UTC, merged