Use setup_build_environment instead of edit in esmf/package.py
LLNL/spack pull request #35249
Opened 2023-01-30 20:35 UTC by AlexanderRichert-NOAA

This PR changes "edit" to "setup_build_environment" in the ESMF package so that the env variables set will be present when using `spack build-env esmf`.

2023-01-30 20:36 UTC, jedwards4b approved these changes, later dismissed

2023-01-30 20:42 UTC, climbfuji submitted a review, later dismissed

2023-02-06 14:39 UTC, alalazo requested changes
Can you change this to modify the environment through `env` instead of `os.environ` directly?

2023-02-06 18:23 UTC, AlexanderRichert-NOAA commented
> Can you change this to modify the environment through `env` instead of `os.environ` directly?

Yep no problem-- is there a way I can iterate over all variables in the environment using `env` instead of `os.environ`?

2023-02-16 18:01 UTC, alalazo approved these changes

2023-02-16 18:01 UTC, merged