new py-amplpy package
LLNL/spack pull request #35359
Opened 2023-02-06 18:47 UTC by sm2939

depends on !35357

2023-02-06 18:51 UTC, sm2939 commented
@spackbot fix style

2023-02-06 19:18 UTC, tldahlgren requested changes
As with #35357 , the directory for this package needs to be moved to under `var/spack/repos/builtin/packages`.

Confirmed the sha256.

2023-02-06 19:18 UTC, tldahlgren commented
Adding @adamjstewart since this is a `PythonPackage`.

2023-02-06 19:19 UTC, tldahlgren commented on var/spack/repos/builtin/py-amplpy/package.py
> +# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
```

2023-02-06 19:33 UTC, adamjstewart requested changes

2023-02-06 19:33 UTC, adamjstewart commented on var/spack/repos/builtin/py-amplpy/package.py
> +
missing build dep on setuptools

2023-02-09 21:49 UTC, adamjstewart approved these changes

2023-02-10 03:54 UTC, tldahlgren approved these changes
Reconfirmed the sha256.

2023-02-10 03:58 UTC, tldahlgren commented
Took the liberty of `Update branch` button to pick up the dependency package.

2023-02-10 19:23 UTC, merged