new ampltools package
LLNL/spack pull request #35357
Opened 2023-02-06 18:09 UTC by sm2939

2023-02-06 18:11 UTC, sm2939 commented
@spackbot fix style

2023-02-06 19:10 UTC, tldahlgren requested changes
This file is under the wrong directory and needs to be moved to `var/spack/repos/builtin/packages/py-ampltools`.

Otherwise, I confirmed the sha256.

2023-02-06 19:10 UTC, tldahlgren commented on var/spack/repos/builtin/py-ampltools/package.py
> +# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
```

2023-02-06 19:11 UTC, tldahlgren commented
Adding @adamjstewart since it is a `PythonPackage`.

2023-02-06 19:32 UTC, adamjstewart requested changes

2023-02-06 19:32 UTC, adamjstewart commented on var/spack/repos/builtin/py-ampltools/package.py
> +
Missing build dep on setuptools

2023-02-09 21:48 UTC, adamjstewart approved these changes

2023-02-10 03:57 UTC, tldahlgren approved these changes
Re-confirmed the sha256.

2023-02-10 03:57 UTC, merged