py-netcdf4: adding version 1.6.2
LLNL/spack pull request #35393
Opened 2023-02-08 14:55 UTC by snehring

Simple version update.

2023-02-08 16:34 UTC, adamjstewart requested changes

2023-02-08 16:34 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-netcdf4/package.py
>      version("1.4.2", sha256="b934af350459cf9041bcdf5472e2aa56ed7321c018d918e9f325ec9a1f9d1a30")
setuptools should now be 41.2+

2023-02-08 17:13 UTC, adamjstewart approved these changes
LGTM, will give @skosukhin a chance to review. Ping me if you haven't heard anything back in a week and I'll merge.

2023-02-08 17:18 UTC, skosukhin approved these changes

2023-02-08 18:32 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-netcdf4/package.py
> +    version("1.6.2", sha256="0382b02ff6a288419f6ffec85dec40f451f41b8755547154c575ddd9f0f4ae53")
Confirmed the sha256.

2023-02-09 01:49 UTC, snehring commented
@spackbot re-run pipeline

2023-02-09 02:10 UTC, merged