Package slate: Improved MPI launcher search for smoke tests
LLNL/spack pull request #35448
Opened 2023-02-10 21:06 UTC by G-Ragghianti

The current search for MPI launchers in the smoke test incorrectly assumes that srun can be found in the mpi bin directory. This update improves it a bit, but it isn't perfect.  This is a stopgap measure until package runtime dependencies are properly provided to the smoke test.

2023-02-10 21:08 UTC, G-Ragghianti commented
https://github.com/E4S-Project/e4s/issues/114#issuecomment-1415991273

2023-02-10 23:35 UTC, tldahlgren approved these changes, later dismissed
LGTM

2023-02-10 23:39 UTC, tldahlgren commented
Deferring merge decision to give @mgates3 time to comment.

2023-02-10 23:41 UTC, tldahlgren commented
> Deferring merge decision to give @mgates3 time to comment.

@G-Ragghianti That is unless you want me to merge it now.

2023-02-11 00:20 UTC, G-Ragghianti commented
Ideally someone working on e4s and perlmutter could test it.

On Fri, Feb 10, 2023, 6:41 PM Tamara Dahlgren ***@***.***>
wrote:

> Deferring merge decision to give @mgates3 <https://github.com/mgates3>
> time to comment.
>
> @G-Ragghianti <https://github.com/G-Ragghianti> That is unless you want
> me to merge it now.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/spack/spack/pull/35448#issuecomment-1426496223>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH7Q5Y33LI7CAU42QSBVK4TWW3G25ANCNFSM6AAAAAAUYHM6TU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-13 15:43 UTC, mgates3 approved these changes, later dismissed
Looks fine.

I'm updating the examples so they can run without `mpirun`, `srun`, etc. if it isn't available (i.e., they would run with only one MPI rank). So in the future we can remove raising an error.

2023-02-13 15:45 UTC, G-Ragghianti commented
Great.  I'll modify the logic once that feature is in place.

2023-02-13 19:09 UTC, wspear commented
I'm going to try this out. Perlmutter's degraded filesystem situation is making it take a while.

2023-02-15 20:05 UTC, wspear commented
On perlmutter this fails for me like:

```
wspear@nid008504:~/SPACK-SPACE/wspear/perlmutter/22.11/spack> spack test run /mh4tjme
==> Spack test ek4rsmfl25l6nrbp6m2tf3me5af4xuak
==> Testing package slate-2022.07.00-mh4tjme
==> Error: RuntimeError: Cannot run tests due to absence of MPI launcher

/global/cfs/cdirs/m3503/wspear/perlmutter/22.11/spack/var/spack/repos/builtin/packages/slate/package.py:141, in test:
        138            if not launcher:
        139                raise RuntimeError("Cannot run tests due to absence of MPI launcher")
        140            self.run_test(launcher.command, test_args, purpose="SLATE smoke test")
  >>    141            make("clean")

```

Here is the spec for the version of slate I was testing:

```
-- linux-sles15-zen3 / gcc@11.2.0 -------------------------------
mh4tjme slate@2022.07.00~cuda~ipo+mpi+openmp~rocm+shared build_system=cmake build_type=RelWithDebInfo
ktoan55     blaspp@2022.07.00~cuda~ipo+openmp~rocm+shared build_system=cmake build_type=RelWithDebInfo
dq73xpv     cmake@3.25.2~doc+ncurses+ownlibs~qt build_system=generic build_type=Release
igbrz2c         ncurses@6.3~symlinks+termlib abi=none build_system=autotools
savxweu             pkgconf@1.8.0 build_system=autotools
riwtjwe         openssl@1.1.1s~docs~shared build_system=generic certs=mozilla
rmyafqv     cray-libsci@22.11.1.2+mpi~openmp+shared build_system=generic
epzzbvl     cray-mpich@8.1.22+wrappers build_system=generic
mtdsn2l     lapackpp@2022.07.00~cuda~ipo~rocm+shared build_system=cmake build_type=RelWithDebInfo
```

I think the test is over-checking for slurm. This spec uses an external mpi provider, not built by a spack package, so variants like pmi and slurm dependency are not available by introspection. In my experience using srun if it is in the environment and then falling through to mpirun and mpiexec is sufficient.

2023-02-15 20:12 UTC, wspear requested changes

2023-02-15 20:12 UTC, wspear commented on var/spack/repos/builtin/packages/slate/package.py
> +        if self.spec["mpi"].satisfies("+pmi") and self.spec["slurm"]:
This will always resolve to false for an externally provided mpi since they aren't associated with variants or dependencies.

2023-02-16 20:17 UTC, G-Ragghianti commented on var/spack/repos/builtin/packages/slate/package.py
> +        if self.spec["mpi"].satisfies("+pmi") and self.spec["slurm"]:
OK I think my current checkin has resolved this.

2023-02-16 22:22 UTC, wspear commented on var/spack/repos/builtin/packages/slate/package.py
> +        if self.spec["mpi"].satisfies("+pmi") and self.spec["slurm"]:
I think that worked. Perlmutter is down. The test fails on cori, but the failure happens when a test is launched in srun so these changes should be good.

2023-02-16 22:24 UTC, wspear approved these changes

2023-02-21 21:09 UTC, tldahlgren approved these changes

2023-02-21 21:10 UTC, merged

2025-03-24 19:46 UTC, alalazo commented
@G-Ragghianti @tldahlgren When building `slate` on `cray-rhel` in CI, it may consume 6 hrs waiting to run tests:

![Screenshot from 2025-03-24 20-35-10](https://github.com/user-attachments/assets/1ee4cb07-f213-45ca-be66-472f9a6e65e4)

Can we currently set a timeout for tests from config or cli?

2025-03-24 20:38 UTC, tldahlgren commented
> @G-Ragghianti @tldahlgren When building `slate` on `cray-rhel` in CI, it may consume 6 hrs waiting to run tests:
> 
> ![Screenshot from 2025-03-24 20-35-10](https://private-user-images.githubusercontent.com/4199709/426239511-1ee4cb07-f213-45ca-be66-472f9a6e65e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI4NDg3OTYsIm5iZiI6MTc0Mjg0ODQ5NiwicGF0aCI6Ii80MTk5NzA5LzQyNjIzOTUxMS0xZWU0Y2IwNy1mMjEzLTQ1Y2EtYmU2Ni00NzJmOWE2ZTY1ZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMjRUMjAzNDU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWJiOWJhNDM5OTIwNjFlOTY0ZGM5Zjk5Mzg3NTBhYjQzMmE2OWM5YzRkODhmMThmYjMyODBkNTRlNGQzNmM4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.93GQJ8OyAyHuR-Ug0VydIBPZkee2Hn3D9YThHLdctBU)
> 
> Can we currently set a timeout for tests from config or cli?

Not at this time. Instead, the package should be added to the `broken-tests-packages` listed in ci.yaml files (see  https://spack.readthedocs.io/en/latest/pipelines.html#ci-yaml).  So update `share/spack/gitlab/cloud_piplines/configs/ci.yaml` and, if also relevant, `share/spack/gitlab/cloud_piplines/configs/darwin/ci.yaml`.