ci: re-enable macos stack, build in consistent path, do not relocate
LLNL/spack pull request #35463
Opened 2023-02-13 16:56 UTC by eugeneswalker

Try simple MacOS stack using:
* M1 Mac Studio
* MacOS Ventura
* `%apple-clang@14.0.0`

Build only `cmake` to start.

Do not perform any relocation, always build in same path, until we figure out how to deal with Apple's trusted build preventing relocation (See Issue https://github.com/spack/spack/issues/32571)

Allow this pipeline to fail, mainly due to expectation of job timeouts in periods of high activity when our runner may not be able to keep up with load -- we don't want this pipeline to hold up PRs in that case.

CC @wspear

2023-02-15 22:58 UTC, eugeneswalker commented
@spackbot run pipeline

2023-02-15 23:19 UTC, eugeneswalker commented
@spackbot run pipeline

2023-02-16 01:22 UTC, scottwittenburg requested changes
Thanks @eugeneswalker this looks pretty good, the things I mentioned are minor.  Though it's unfortunate to be adding another stack with all the boilerplate before #34272 lands.  We'll be merging that soon, but I'm not sure it can be this week.

2023-02-16 01:22 UTC, scottwittenburg commented on share/spack/gitlab/cloud_pipelines/.gitlab-ci.yml
> +  - /^github\/pr[\d]+_.*$/
No need for the `github` prefix, we don't pushes branches with that anymore.

2023-02-16 01:22 UTC, scottwittenburg commented on share/spack/gitlab/cloud_pipelines/.gitlab-ci.yml
> +  - /^github\/develop$/
Same as above, no need for the entry with the `github` prefix.

2023-02-16 01:22 UTC, scottwittenburg commented on share/spack/gitlab/cloud_pipelines/.gitlab-ci.yml
> +    SPACK_BUILDCACHE_DESTINATION: "s3://spack-binaries-prs/${CI_COMMIT_REF_NAME}"
Probably want the stack name in here too, to prevent collisions between stacks building the same hash.

2023-02-16 01:22 UTC, scottwittenburg commented on share/spack/gitlab/cloud_pipelines/.gitlab-ci.yml
> +    SPACK_BUILDCACHE_DESTINATION: "s3://spack-binaries-prs/${CI_COMMIT_REF_NAME}"
Though I can see you left it out because the original did.

2023-02-16 11:18 UTC, eugeneswalker commented
Just pushed changes which I think address the comments you made above Scott! Thank you for helping with this!

The mac rebuild jobs are failing, it looks like because `nproc` is not available and yet is used unconditionally in the `install.sh` ?
* [(specs) ca-certificates-mozilla/jijystv 2023-01-10 apple-clang@14.0.0 darwin-ventura-m1 E4S MacOS](https://gitlab.spack.io/spack/spack/-/jobs/5578095)
```
$ cd ${SPACK_CONCRETE_ENV_DIR}
$ spack env activate --without-view .
$ mkdir -p ${SPACK_ARTIFACTS_ROOT}/user_data
$ spack --color=always --backtrace ci rebuild --tests > >(tee ${SPACK_ARTIFACTS_ROOT}/user_data/pipeline_out.txt) 2> >(tee ${SPACK_ARTIFACTS_ROOT}/user_data/pipeline_err.txt >&2)
gpg: keybox '/opt/spack/opt/spack/gpg/pubring.kbx' created
gpg: /opt/spack/opt/spack/gpg/trustdb.gpg: trustdb created
./install.sh: line 5: nproc: command not found
```

Excerpt from the artifact `install.sh`, notice the `-j$(nproc)`
```
# spack install command
"spack" "-e" "/Users/gitlab-runner/builds/sG4z9VwE/0/spack/spack/jobs_scratch_dir/concrete_environment" "bootstrap" "now" && "spack" "-e" "/Users/gitlab-runner/builds/sG4z9VwE/0/spack/spack/jobs_scratch_dir/concrete_environment" "config" "add" "config:db_lock_timeout:120" && "spack" "-e" "/Users/gitlab-runner/builds/sG4z9VwE/0/spack/spack/jobs_scratch_dir/concrete_environment" "env" "depfile" "-o" "Makefile" "--use-buildcache=package:never,dependencies:only" "/jijystvkpkwdtfzv4su5p6d6oubqmtzy" && "export" "GNUMAKEFLAGS=--output-sync=recurse" && "make" "SPACK='spack' '--color=always' '--backtrace' '--verbose'" "SPACK_COLOR=always" "SPACK_INSTALL_FLAGS='--no-check-signature' '--cdash-upload-url' 'https://cdash.spack.io/submit.php?project=Spack+Testing' '--cdash-build' 'ca-certificates-mozilla@2023-01-10%apple-clang@14.0.0 hash=jijystvkpkwdtfzv4su5p6d6oubqmtzy arch=darwin-ventura-m1 (E4S MacOS)' '--cdash-site' 'Cloud Gitlab Infrastructure (uo-lambda)' '--cdash-buildstamp' '20230215-1637-E4S MacOS'" "-j$(nproc)" "install-deps/ca-certificates-mozilla-2023-01-10-jijystvkpkwdtfzv4su5p6d6oubqmtzy" ...
```

2023-02-19 16:52 UTC, eugeneswalker commented
> The mac rebuild jobs are failing, it looks like because nproc is not available and yet is used unconditionally in the install.sh ?

@spackbot run pipeline after creating `/usr/local/bin/nproc` as a shell script that runs `sysctl -n hw.logicalcpu` (equivalent of `nproc` on macOS)

2023-02-19 21:19 UTC, eugeneswalker commented
Several pipeline jobs failing because dependency specs built in earlier stages cannot be installed from cache. Description here:
* https://spackpm.slack.com/archives/C02N33GM28H/p1676841489638899

2023-03-06 16:24 UTC, eugeneswalker commented
I think this is ready for merge!

2023-04-24 15:44 UTC, closed without merging