Pull in external module dependencies when writing modulefiles
LLNL/spack pull request #35498
Opened 2023-02-15 22:53 UTC by koysean

Fix for https://github.com/spack/spack/issues/35212

This PR modifies spack's module APIs to partially support multiple modulefiles for a single spec. These changes allow Spack to handle an external package with multiple modulefiles.

The primary API changes are in `spack.modules.common.get_module()` and `spack.modules.common.BaseFileLayout.use_name`. The return types were changed from `str` to `List[str]` to accomodate a single spec having multiple module names.

In addition, modulefiles are no longer created for external packages with modules, and modulefiles which depend on external modules will now directly load the external modules (if autoload is enabled).

One possible issue is that the module index will not be updated with external modules. This doesn't seem like a problem to me since Spack isn't managing the external modules anyways, but I'm not very familiar with how Spack uses the module index. Is this an issue?

2023-02-17 20:22 UTC, becker33 requested changes

2023-02-17 20:22 UTC, becker33 commented on lib/spack/spack/cmd/modules/__init__.py
> +        for module in spack.modules.common.get_module(
If this is going to return multiple modules, it should be renamed to `get_modules`.

2023-02-17 20:22 UTC, becker33 commented on lib/spack/spack/cmd/modules/__init__.py
> +        )
Oh goodness this is hard to read... if the style checker is going to format it like this we might need to have a comment explaining what's going on here.

2023-02-17 20:22 UTC, becker33 commented on lib/spack/spack/modules/common.py
> +        """Returns a list of the 'use' names of the module i.e. the names you
Another method that should be pluralized with the changes you're making.

2023-02-20 15:16 UTC, koysean commented on lib/spack/spack/cmd/modules/__init__.py
> +        )
Added a comment - the style checker also changed its mind (?) and wants the tuple (spec, module) on one line now, so it's a lot easier to read.

2023-02-20 20:37 UTC, closed without merging