apptainer use the --with-suid configure option
LLNL/spack pull request #35513
Opened 2023-02-16 14:41 UTC by simonleary-umass-edu

This is a continuation of my [last PR](https://github.com/spack/spack/pull/35243) which broke when I deleted the head.

2023-02-16 16:08 UTC, simonleary-umass-edu commented
@spackbot fix style

2023-02-20 08:52 UTC, haampie requested changes

2023-02-20 08:52 UTC, haampie commented on var/spack/repos/builtin/packages/apptainer/package.py
> +            options += ["--with-suid"]
```suggestion
        if spec.satisfies("@1.1.0: +suid"):
            options.append("--with-suid")
```

2023-02-20 16:39 UTC, haampie approved these changes

2023-02-20 16:39 UTC, merged