environment.matching_spec: linear time traversal
LLNL/spack pull request #35534
Opened 2023-02-17 12:50 UTC by haampie

... and use colors in disambiguate message for clarity.

This commit avoid the loop:

```
for root in roots:
  for dep in deps(root):
    ...
```

instead it ensures each node is visited once and only once.

Also adds a small optimization when searching for concrete specs, since
we can assume uniqueness of dag hash, so it's fine to early exit.

The order of traversal is breadth first over the roots, so that we're
guaranteed to find matching specs as roots first, instead of as deps of
other roots.

2023-02-24 19:50 UTC, scheibelp requested changes
I have one concern about the logic for identifying specs as being roots, and a request about clarifying a comment.

2023-02-24 19:50 UTC, scheibelp commented on lib/spack/spack/environment/environment.py
> +            if i < len(self.concretized_user_specs):
If some roots are deps of other roots, I'm not sure if this check will do what you want. For example if you have:

```
X
|\
Y |
|/
Z
```

and X, Z are roots (i.e. user specs) but Y is not (in that sense, calling them roots is potentially confusing)

Either way, I think it is more straightforward to say:

`if env_spec in set(roots)`

which should be O(1) (make the set before the loop)

Likewise for the subsequent:

`root_matches.append((env_spec, self.concretized_user_specs[i]))`

2023-02-24 19:50 UTC, scheibelp commented on lib/spack/spack/environment/environment.py
> +            # Early exit for concrete specs, exploit uniqueness of dag hash.
Could this comment be expanded, something like:

> If the spec is concrete, then there is no possibility of multiple matches, and we can return the single match

seems clearer to me

2023-02-24 21:37 UTC, haampie commented on lib/spack/spack/environment/environment.py
> +            if i < len(self.concretized_user_specs):
It does what I want but yeah, it can be improved. Is hash(spec) and spec_a == spec_b O(1). I never verified that. If it's by object id then yes, otherwise I hope it uses dag hash for both the hash key and the equality check, but I never verified that.

2023-02-27 12:40 UTC, haampie commented on lib/spack/spack/environment/environment.py
> +            if i < len(self.concretized_user_specs):
I checked: calling `set(roots)` triggers a process_hash to be calculated on the roots. I think I'm happy with the current implementation and don't see the point of yet another DAG traversal.

2023-03-04 02:29 UTC, scheibelp commented on lib/spack/spack/environment/environment.py
> +            if i < len(self.concretized_user_specs):
> calling set(roots) triggers a process_hash to be calculated on the environment roots, which triggers traversal including build/test deps and computes package hash. 

Yes: this is needed to execute `__hash__` on a `Spec`. This shouldn't incur `O(n^2)` operations though so I don't see how the request conflicts with the PR's stated intent.

If it were clear to me that the current strategy worked, I would be fine with it staying as it is, but I don't see how a breadth-first traversal is guaranteed to avoid issues with the example I listed above (in particular, there are valid breadth-first orderings that run into problems), nor anything in the documentation of the `traverse.traverse_nodes` function which guarantees that the roots are visited first (and I assume it couldn't make any such guarantees anyway when complying with a requested ordering).

2023-03-04 09:07 UTC, haampie commented on lib/spack/spack/environment/environment.py
> +            if i < len(self.concretized_user_specs):
I don't get why it's not clear to you. Breadth first initializes the queue with the environment roots, and newly discovered nodes get pushed to the back. 😕

2023-03-06 18:04 UTC, scheibelp commented on lib/spack/spack/environment/environment.py
> +            if i < len(self.concretized_user_specs):
> Breadth first traversal is queue based, and the queue is initialized with the environment roots, newly discovered nodes get pushed to the back. 

Put that in the docstring for `traverse_nodes` (actually not exactly that, but that the roots are guarantees to be visited first): you are saying you know this works because of underlying, undocumented details of these functions. Whoever reads this next should find it easy to reason about, they cannot (based simply on a reading of the associated function docstrings) know that this strategy would work.

> The bfs behavior with multiple sources is natural to me

Not to me, and in particular not when some nodes are children of others (which I've suggested prohibiting before). None of the tests in `test/traverse.py` explicitly state testing this aspect of behavior. `test_breadth_first_traversal_multiple_input_specs` appears to touch that - if not thoroughly - but I had to read through the entire module including all the code in each test to figure that out, and ideally someone reading this in the future doesn't have to do that.

I'd like to state on top of all of this that if there are two approaches that work, and one of them is clearer (and I have argued in this case that it is not more expensive in a big-O sense), then why not use that? Reasoning about traversals by inferring properties of elements based on their index is confusing.

2023-03-07 10:04 UTC, haampie commented on lib/spack/spack/environment/environment.py
> +            if i < len(self.concretized_user_specs):
Hm, bfs was written with these use cases in mind, since dfs doesn't have that property. And as you notice it's tested. So adding a set is just a waste of CPU cycles. Are you fine with a comment instead?

2023-03-14 12:42 UTC, haampie commented
ping @scheibelp

2023-03-14 18:16 UTC, scheibelp approved these changes

2023-03-14 18:18 UTC, merged

2023-03-14 18:21 UTC, scheibelp commented
Thanks!