acts: new versions 23.1.0, 23.2.0, 23.2.1
LLNL/spack pull request #35540
Opened 2023-02-17 15:46 UTC by wdconinc

- https://github.com/acts-project/acts/compare/v23.0.0...v23.1.0: no changes needed to package.py
- https://github.com/acts-project/acts/compare/v23.1.0...v23.2.0: no changes needed to package.py
- https://github.com/acts-project/acts/compare/v23.2.0...v23.2.1: no changes needed to package.py

2023-02-18 06:15 UTC, HadrienG2 requested changes
Looking at the release notes, I see that Acts v23.2.0 [bumped the internally bundled actsvg version](https://github.com/acts-project/acts/pull/1797). Since actsvg is very much Acts-specific, this means that old actsvg versions won't be tested in CI anymore and will drift out of sync at some point, so we'll probably want to do the same, updating the actsvg package as needed.

2023-02-20 01:11 UTC, wdconinc commented
I figured out why I overlooked the actsvg upgrade, and realized the same bug of course affects two other acts dependencies: vecmem and autodiff. I'm just adding those new versions here too (at the risk of making this PR a bit heavy).

These new versions (actsvg, vecmem, autodiff) build for me:
<details><summary>autodiff</summary>

```console
19:04:34 wdconinc@menelaos ~ $ spack find -l -v 
==> In environment autodiff
==> Root specs
------- autodiff@0.6.5  ------- autodiff@0.6.6  ------- autodiff@0.6.7  ------- autodiff@0.6.8  ------- autodiff@0.6.9  ------- autodiff@0.6.10  ------- autodiff@0.6.11  ------- autodiff@0.6.12 +examples+python

==> Installed packages
-- linux-ubuntu22.10-skylake / gcc@12.2.0 -----------------------
6w55ps3 autodiff@0.6.5~examples~ipo~python build_system=cmake build_type=RelWithDebInfo
eppinyi autodiff@0.6.6~examples~ipo~python build_system=cmake build_type=RelWithDebInfo
c4qbjcj autodiff@0.6.7~examples~ipo~python build_system=cmake build_type=RelWithDebInfo
nvsn4is autodiff@0.6.8~examples~ipo~python build_system=cmake build_type=RelWithDebInfo
mnyoxvs autodiff@0.6.9~examples~ipo~python build_system=cmake build_type=RelWithDebInfo
fppuly3 autodiff@0.6.10~examples~ipo~python build_system=cmake build_type=RelWithDebInfo
oihxg2a autodiff@0.6.11~examples~ipo~python build_system=cmake build_type=RelWithDebInfo
7r4srov autodiff@0.6.12+examples~ipo+python build_system=cmake build_type=RelWithDebInfo
q5eauf6 berkeley-db@18.1.40+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc
4wb2p57 bzip2@1.0.8~debug~pic+shared build_system=generic
4dxysjc ca-certificates-mozilla@2023-01-10 build_system=generic
og7d342 cmake@3.25.2~doc+ncurses+ownlibs~qt build_system=generic build_type=Release
zsh6vs3 diffutils@3.8 build_system=autotools
3eeutmo eigen@3.4.0~ipo build_system=cmake build_type=RelWithDebInfo
azxc2jf expat@2.5.0+libbsd build_system=autotools
552fqhg gdbm@1.23 build_system=autotools
zntvyct gettext@0.21.1+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools
ikahixk libbsd@0.11.7 build_system=autotools
ao44gct libffi@3.4.4 build_system=autotools
45jm3xu libiconv@1.17 build_system=autotools libs=shared,static
p34w56z libmd@1.0.4 build_system=autotools
wt2rdt5 libxcrypt@4.4.33~obsolete_api build_system=autotools
6axl3as libxml2@2.10.3~python build_system=autotools
dj4mdec ncurses@6.4~symlinks+termlib abi=none build_system=autotools
q4igfwf ninja@1.11.1+re2c build_system=generic
nlwmceq openssl@1.1.1t~docs~shared build_system=generic certs=mozilla
w7w5ft6 perl@5.36.0+cpanm+open+shared+threads build_system=generic
fezcfme pigz@2.7 build_system=makefile
l7agxyw pkgconf@1.8.0 build_system=autotools
ta5r4ni py-pip@23.0 build_system=generic
ye4l6mn py-pybind11@2.10.1~ipo build_system=cmake build_type=RelWithDebInfo
rgz7hhb py-setuptools@65.5.0 build_system=generic
i76tg6g py-wheel@0.37.1 build_system=generic
ucohqwu python@3.10.8+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060
2fxvclj re2c@2.2 build_system=generic
u6uj5ti readline@8.2 build_system=autotools patches=bbf97f1
ojb4iwl sqlite@3.40.1+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools
rwvdxr5 tar@1.34 build_system=autotools zip=pigz
veimqlq util-linux-uuid@2.38.1 build_system=autotools
6ocy5dp xz@5.4.1~pic build_system=autotools libs=shared,static
7ppfx4x zlib@1.2.13+optimize+pic+shared build_system=makefile
exhnx5g zstd@1.5.2+programs build_system=makefile compression=none libs=shared,static
==> 42 installed packages
```

</details>

<details><summary>vecmem (well... without cuda, hip, sycl, this really only tests the concretization)</summary>

```console
19:01:27 wdconinc@menelaos ~/git/spack (develop *$%>) $ spack find -l -v 
==> In environment vecmem
==> Root specs
------- vecmem@0.13.0  ------- vecmem@0.14.0  ------- vecmem@0.15.0  ------- vecmem@0.16.0  ------- vecmem@0.17.0  ------- vecmem@0.18.0  ------- vecmem@0.19.0  ------- vecmem@0.20.0  ------- vecmem@0.21.0  ------- vecmem@0.22.0

==> Installed packages
-- linux-ubuntu22.10-skylake / gcc@12.2.0 -----------------------
q5eauf6 berkeley-db@18.1.40+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc  y3el53r vecmem@0.13.0~cuda~hip~ipo~sycl build_system=cmake build_type=RelWithDebInfo
4wb2p57 bzip2@1.0.8~debug~pic+shared build_system=generic                                ba4ztyg vecmem@0.14.0~cuda~hip~ipo~sycl build_system=cmake build_type=RelWithDebInfo
4dxysjc ca-certificates-mozilla@2023-01-10 build_system=generic                          ovi6aaa vecmem@0.15.0~cuda~hip~ipo~sycl build_system=cmake build_type=RelWithDebInfo
og7d342 cmake@3.25.2~doc+ncurses+ownlibs~qt build_system=generic build_type=Release      uzgb5y4 vecmem@0.16.0~cuda~hip~ipo~sycl build_system=cmake build_type=RelWithDebInfo
zsh6vs3 diffutils@3.8 build_system=autotools                                             gpzpmgb vecmem@0.17.0~cuda~hip~ipo~sycl build_system=cmake build_type=RelWithDebInfo
552fqhg gdbm@1.23 build_system=autotools                                                 6pacgjx vecmem@0.18.0~cuda~hip~ipo~sycl build_system=cmake build_type=RelWithDebInfo
45jm3xu libiconv@1.17 build_system=autotools libs=shared,static                          24ygvbu vecmem@0.19.0~cuda~hip~ipo~sycl build_system=cmake build_type=RelWithDebInfo
dj4mdec ncurses@6.4~symlinks+termlib abi=none build_system=autotools                     ol4jhpw vecmem@0.20.0~cuda~hip~ipo~sycl build_system=cmake build_type=RelWithDebInfo
nlwmceq openssl@1.1.1t~docs~shared build_system=generic certs=mozilla                    n5b5dbd vecmem@0.21.0~cuda~hip~ipo~sycl build_system=cmake build_type=RelWithDebInfo
w7w5ft6 perl@5.36.0+cpanm+open+shared+threads build_system=generic                       yvhf7us vecmem@0.22.0~cuda~hip~ipo~sycl build_system=cmake build_type=RelWithDebInfo
l7agxyw pkgconf@1.8.0 build_system=autotools                                             7ppfx4x zlib@1.2.13+optimize+pic+shared build_system=makefile
u6uj5ti readline@8.2 build_system=autotools patches=bbf97f1
==> 23 installed packages
```

</details>

<details><summary>actsvg</summary>

```console
19:06:46 wdconinc@menelaos ~ $ spack find -l -v
==> In environment actsvg
==> Root specs
------- actsvg@0.4.27  ------- actsvg@0.4.28

==> Installed packages
-- linux-ubuntu22.10-skylake / gcc@12.2.0 -----------------------
jr34dgj actsvg@0.4.27~examples~ipo+meta build_system=cmake build_type=RelWithDebInfo     45jm3xu libiconv@1.17 build_system=autotools libs=shared,static
djosggz actsvg@0.4.28~examples~ipo+meta build_system=cmake build_type=RelWithDebInfo     dj4mdec ncurses@6.4~symlinks+termlib abi=none build_system=autotools
q5eauf6 berkeley-db@18.1.40+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc  nlwmceq openssl@1.1.1t~docs~shared build_system=generic certs=mozilla
4wb2p57 bzip2@1.0.8~debug~pic+shared build_system=generic                                w7w5ft6 perl@5.36.0+cpanm+open+shared+threads build_system=generic
4dxysjc ca-certificates-mozilla@2023-01-10 build_system=generic                          l7agxyw pkgconf@1.8.0 build_system=autotools
og7d342 cmake@3.25.2~doc+ncurses+ownlibs~qt build_system=generic build_type=Release      u6uj5ti readline@8.2 build_system=autotools patches=bbf97f1
zsh6vs3 diffutils@3.8 build_system=autotools                                             7ppfx4x zlib@1.2.13+optimize+pic+shared build_system=makefile
552fqhg gdbm@1.23 build_system=autotools
==> 15 installed packages
```

</details>

2023-02-20 06:41 UTC, HadrienG2 approved these changes

2023-02-20 08:42 UTC, haampie approved these changes

2023-02-20 08:42 UTC, merged