py-uproot: new versions 4.3.*, 5.0.*
LLNL/spack pull request #35548
Opened 2023-02-17 16:50 UTC by wdconinc

Changelogs at https://github.com/scikit-hep/uproot5/releases.

TODO:
- [ ] PR #TBD: `uproot@5` depends on `awkward@2`, which will need to be merged first.

2023-02-17 20:48 UTC, adamjstewart requested changes

2023-02-17 20:48 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-uproot/package.py
>      depends_on("py-setuptools@42:", type=("build", "run"), when="@4.1.8:")
Build system uses hatchling now

2023-02-17 20:48 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-uproot/package.py
>      depends_on("py-numpy", type=("build", "run"))
Missing deps:
```toml
dependencies = [
    "awkward>=2.0.0",
    "importlib-metadata;python_version<\"3.8\"",
    "numpy",
    "packaging",
]
```

2023-02-17 20:53 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-uproot/package.py
>      depends_on("py-setuptools@42:", type=("build", "run"), when="@4.1.8:")
Yeah, saw that in testing just now 🤣

2023-02-25 23:49 UTC, wdconinc commented
```console
==> Installed packages
-- linux-ubuntu22.10-skylake / gcc@12.2.0 -----------------------
ryie3bg py-uproot@5.0.3+lz4+xrootd+zstd build_system=python_pip
==> 1 installed package
17:48:25 wdconinc@menelaos ~/git/spack (develop *+$%>) $ python
Python 3.10.8 (main, Feb 17 2023, 16:53:57) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import uproot
>>> print(uproot.__version__)
5.0.3
```

2023-02-25 23:49 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-uproot/package.py
>      depends_on("py-numpy", type=("build", "run"))
Added these deps.

2023-02-25 23:49 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-uproot/package.py
>      depends_on("py-setuptools@42:", type=("build", "run"), when="@4.1.8:")
Changed to hatchling.

2023-02-26 05:06 UTC, adamjstewart approved these changes

2023-03-01 10:53 UTC, merged