Variant and conflict fixes on intel-mpi-benchmarks
LLNL/spack pull request #35670
Opened 2023-02-24 08:53 UTC by besnardjb

When installing the IMB you can only get `IMB-MPI1` the reason is that the variants are somehow mutually-exclusive. This fixes this issues by removing some `elif`. I have also added some conflicts and inhibited parallel build for older versions.

2023-02-24 13:52 UTC, carsonwoods approved these changes
This looks good, thanks for catching this and submitting a fix.

2023-02-27 21:40 UTC, carsonwoods submitted a review, later dismissed

2023-03-01 10:12 UTC, alalazo requested changes

2023-03-01 10:12 UTC, alalazo commented on var/spack/repos/builtin/packages/intel-mpi-benchmarks/package.py
> +        parallel = False
This ought to be a `property` (`parallel` is not a directive, so the context manager has no effect)

2023-03-01 10:21 UTC, besnardjb commented on var/spack/repos/builtin/packages/intel-mpi-benchmarks/package.py
> +        parallel = False
Was not sure of how to handle this conditional parallel build from other package examples. I can look further tonight if needed.

2023-03-06 15:13 UTC, besnardjb commented on var/spack/repos/builtin/packages/intel-mpi-benchmarks/package.py
> +        parallel = False
I had a try in 2573ef7. I had to manually pass to the individual make targets to inhibit parallel build. I also factorized the variants in the process. Feel free to comment, if it is too complex, we can revert to a single `parallel=False`.

2023-03-08 08:43 UTC, alalazo commented on var/spack/repos/builtin/packages/intel-mpi-benchmarks/package.py
> +        parallel = False
@besnardjb Why not keeping that as before and just:
```python
@property
def parallel(self):
    if self.spec.satisfies("@:2019"):
        return False
    return True
```
?

2023-03-08 08:55 UTC, besnardjb commented on var/spack/repos/builtin/packages/intel-mpi-benchmarks/package.py
> +        parallel = False
You are right it is just me being overcomplicated, AFAIK did not find another package doing such an override. Just pushed the fix as per your recommendation and checked that all versions are building.

2023-03-08 09:02 UTC, alalazo approved these changes

2023-03-08 20:33 UTC, merged