pegtl: add latest version
LLNL/spack pull request #35687
Opened 2023-02-24 23:34 UTC by nazavode

This PR adds `v3.2.7` and changes the `url` package property to use GitHub tag archive URLs (the previous one made `spack checksum` to retrieve a lot of HTML garbage instead of actual packages).

2023-03-01 10:54 UTC, alalazo commented
@spackbot run pipeline

2023-03-01 11:00 UTC, alalazo requested changes
What is the issue with the current URL? Since [this](https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/) we prefer not to rely on auto-generated archives where possible :slightly_smiling_face:

2023-03-01 11:00 UTC, alalazo commented on var/spack/repos/builtin/packages/pegtl/package.py
> +    url = "https://github.com/taocpp/PEGTL/archive/refs/tags/2.1.4.tar.gz"
With this change, previous checksums change too:
```console
$ spack checksum pegtl 3.2.7 3.2.0
==> Found 2 versions of pegtl:
  
  3.2.7  https://github.com/taocpp/PEGTL/archive/refs/tags/3.2.7.tar.gz
  3.2.0  https://github.com/taocpp/PEGTL/archive/refs/tags/3.2.0.tar.gz

==> Fetching https://github.com/taocpp/PEGTL/archive/refs/tags/3.2.7.tar.gz
==> Fetching https://github.com/taocpp/PEGTL/archive/refs/tags/3.2.0.tar.gz

    version("3.2.7", sha256="d6cd113d8bd14e98bcbe7b7f8fc1e1e33448dc359e8cd4cca30e034ec2f0642d")
    version("3.2.0", sha256="3816d1a26afc04513df172678444377e0e35b9473f1f7ff85189589b831298f1")
```

2023-03-01 17:42 UTC, nazavode commented
> What is the issue with the current URL? Since [this](https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/) we prefer not to rely on auto-generated archives where possible 🙂

Urgh, completely missed this nice move by GitHub. Anyway, this is what I'm getting with the old URL:

```shell
$ spack checksum pegtl
==> Found 18 versions of pegtl:
  
  1643777c2d8cfe01668e217aa7d4cbd6b9f173ba  https://github.com/taocpp/PEGTL/commit/1643777c2d8cfe01668e217aa7d4cbd6b9f173ba
  25aee1f074907cace72e11f72afaab9339e12ad3  https://github.com/taocpp/PEGTL/commit/25aee1f074907cace72e11f72afaab9339e12ad3
  464d866d8bbf4c8ddc5b67422d09b60ad3b918fc  https://github.com/taocpp/PEGTL/commit/464d866d8bbf4c8ddc5b67422d09b60ad3b918fc
  558757e0018e58063701247b5d8795806d82af40  https://github.com/taocpp/PEGTL/commit/558757e0018e58063701247b5d8795806d82af40
  6d03c8decc22b4ddd51115e2170e0e82413c7104  https://github.com/taocpp/PEGTL/commit/6d03c8decc22b4ddd51115e2170e0e82413c7104
  7d039707cf835cea63daa78a717e18fcc5bcf95b  https://github.com/taocpp/PEGTL/commit/7d039707cf835cea63daa78a717e18fcc5bcf95b
  12                                        https://isocpp.org/blog/2020/12/remembering-beman-dawes
  3.2.7                                     https://github.com/taocpp/PEGTL/tree/3.2.7
  3.2.6                                     https://github.com/taocpp/PEGTL/tree/3.2.6
  ...
  2.1.4                                     https://github.com/taocpp/PEGTL/tarball/2.1.4
```

While, with the *new* URL, the command gives a reasonable reply:

```shell
$ spack checksum pegtl
==> Found 1 version of pegtl:

  2.1.4  https://github.com/taocpp/PEGTL/archive/refs/tags/2.1.4.tar.gz
```

2023-03-08 08:07 UTC, alalazo commented
> If that sounds reasonable I will revert the commit about the class url.

Sure. Ping me when done and I'll merge this.

2023-08-24 16:50 UTC, alecbcs commented
Ping @nazavode. Are you still interested in working on this pull request?

2023-08-24 16:59 UTC, nazavode commented
> Ping @nazavode. Are you still interested in working on this pull request?

Sure, thanks for the ping, completely forgot about it! Fixing this asap.

2023-10-12 06:08 UTC, alecbcs commented
@nazavode I think we're waiting on a commit to modify the URL back to its previous value? Let me know if I'm misunderstanding the situation and I'll take another look.

2023-10-30 11:12 UTC, alalazo approved these changes

2023-10-30 11:12 UTC, merged