SanguMbekelu/py-wheel
LLNL/spack pull request #35717
Opened 2023-02-27 14:44 UTC by Sangu-Mbekelu

updating py-wheel package for newer versions

2023-02-27 14:48 UTC, Sangu-Mbekelu commented
@spackbot fix style

2023-02-27 16:03 UTC, Sangu-Mbekelu commented
@spackbot fix style

2023-02-27 16:04 UTC, Sangu-Mbekelu commented
Can't get around this style error

2023-02-27 18:22 UTC, tldahlgren submitted a review, later dismissed
Confirmed sha256.

2023-02-27 20:46 UTC, adamjstewart requested changes

2023-02-27 20:46 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-wheel/package.py
> +        url="https://files.pythonhosted.org/packages/bd/7c/d38a0b30ce22fc26ed7dbc087c6d00851fb3395e9d0dac40bec1f905030c/wheel-0.38.4-py3-none-any.whl",
Remove this line, update the URL above to https://files.pythonhosted.org/packages/py3/w/wheel/wheel-0.38.4-py3-none-any.whl, and add the following function before install:
```python
def url_for_version(self, version):
    url = "https://files.pythonhosted.org/packages/{0}/w/wheel/wheel-{1}-{0}-none-any.whl"
    if version >= Version("0.38"):
        python = "py3"
    else:
        python = "py2.py3"
    return url.format(python, version)
```

2023-03-03 14:12 UTC, Sangu-Mbekelu commented
@spackbot fix style

2023-03-03 15:42 UTC, adamjstewart commented
You lost the new version. I only meant to remove the url override for that version.

2023-03-03 15:49 UTC, adamjstewart commented
Now you added back the URL override and undid the base class URL change. You'll want to undo this.

2023-03-03 15:59 UTC, Sangu-Mbekelu commented
@spackbot fix style

2023-03-03 18:41 UTC, adamjstewart submitted a review, later dismissed

2023-09-25 14:31 UTC, closed without merging