ADD: xalt package
LLNL/spack pull request #35736
Opened 2023-02-28 16:27 UTC by germanne

This PR is to add the xalt package as described in issue #17199

2023-03-01 00:04 UTC, tldahlgren approved these changes, later dismissed
Confirmed the tag exists, variants are referenced.

2023-03-01 00:04 UTC, tldahlgren commented on var/spack/repos/builtin/packages/xalt/package.py
> +# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
```

2023-03-01 00:06 UTC, tldahlgren approved these changes

2023-03-01 00:13 UTC, tldahlgren commented
I think you're missing at least one dependency:

```
$ spack install xalt
==> Error: Package 'mvapich' not found.
```

You're going to want to ensure all the dependencies needed for the variants are specified.

2023-03-01 00:14 UTC, tldahlgren requested changes
Need dependencies associated with variants.

2023-03-01 08:08 UTC, germanne commented
$ spack install xalt
==> Error: Package 'mvapich' not found.

Mpi is definitely not a dependency of xalt. Also I unfortunately can't reproduce your error, either locally or on multiple clusters...

2023-03-01 16:44 UTC, tldahlgren commented
> $ spack install xalt ==> Error: Package 'mvapich' not found.
> 
> Mpi is definitely not a dependency of xalt. Also I unfortunately can't reproduce your error, either locally or on multiple clusters...

Okay.  I didn't dig into this but assumed it *might* be relevant given the `+trackMPI` default.

2023-03-21 01:15 UTC, tldahlgren commented
I'm able to get further now BUT am still having issues:

```
$ spack install salt
...
==> No patches needed for xalt
==> xalt: Executing phase: 'autoreconf'
==> xalt: Executing phase: 'configure'
==> xalt: Executing phase: 'build'
==> xalt: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'install'

1 error found in build log:
     152                    all
     153    install -m 0600  /var/tmp/dahlgren/spack-stage/spack-stage-xalt-2.1
            0.45-h46wl6f5a3xtxiy2qoi2j3eycbhdlyus/spack-src/src/util/xalt_obfus
            cate.h   /usr/WS1/dahlgren/spack/opt/spack/linux-rhel7-broadwell/gc
            c-8.3.1/xalt-2.10.45-h46wl6f5a3xtxiy2qoi2j3eycbhdlyus/xalt/2.10.45/
            include
     154    make -f makefile  --jobserver-fds=3,4 -j FILELIST=" /var/tmp/dahlgr
            en/spack-stage/spack-stage-xalt-2.10.45-h46wl6f5a3xtxiy2qoi2j3eycbh
            dlyus/spack-src/py_src/XALTdb.py  /var/tmp/dahlgren/spack-stage/spa
            ck-stage-xalt-2.10.45-h46wl6f5a3xtxiy2qoi2j3eycbhdlyus/spack-src/py
            _src/progressBar.py  /var/tmp/dahlgren/spack-stage/spack-stage-xalt
            -2.10.45-h46wl6f5a3xtxiy2qoi2j3eycbhdlyus/spack-src/py_src/xalt_sta
            ck.py  /var/tmp/dahlgren/spack-stage/spack-stage-xalt-2.10.45-h46wl
            6f5a3xtxiy2qoi2j3eycbhdlyus/spack-src/py_src/BeautifulTbl.py  /var/
            tmp/dahlgren/spack-stage/spack-stage-xalt-2.10.45-h46wl6f5a3xtxiy2q
            oi2j3eycbhdlyus/spack-src/py_src/xalt_global.py  /var/tmp/dahlgren/
            spack-stage/spack-stage-xalt-2.10.45-h46wl6f5a3xtxiy2qoi2j3eycbhdly
            us/spack-src/py_src/Rmap_XALT.py  /var/tmp/dahlgren/spack-stage/spa
            ck-stage-xalt-2.10.45-h46wl6f5a3xtxiy2qoi2j3eycbhdlyus/spack-src/py
            _src/xalt_util.py  /var/tmp/dahlgren/spack-stage/spack-stage-xalt-2
            .10.45-h46wl6f5a3xtxiy2qoi2j3eycbhdlyus/spack-src/py_src/xalt_name_
            mapping.py" DIRLOC=/usr/WS1/dahlgren/spack/opt/spack/linux-rhel7-br
            oadwell/gcc-8.3.1/xalt-2.10.45-h46wl6f5a3xtxiy2qoi2j3eycbhdlyus/xal
            t/2.10.45/libexec GIT_VERSION="xalt-2.10.45" __installMe
     155    make[1]: Entering directory `/tmp/dahlgren/spack-stage/spack-stage-
            xalt-2.10.45-h46wl6f5a3xtxiy2qoi2j3eycbhdlyus/spack-src/src'
     156    make -f makefile  --jobserver-fds=3,4 -j FILELIST=" /var/tmp/dahlgr
            en/spack-stage/spack-stage-xalt-2.10.45-h46wl6f5a3xtxiy2qoi2j3eycbh
            dlyus/spack-src/sh_src/ld.in  /var/tmp/dahlgren/spack-stage/spack-s
            tage-xalt-2.10.45-h46wl6f5a3xtxiy2qoi2j3eycbhdlyus/spack-src/sh_src
            /ld.xalt.in  /var/tmp/dahlgren/spack-stage/spack-stage-xalt-2.10.45
            -h46wl6f5a3xtxiy2qoi2j3eycbhdlyus/spack-src/sh_src/ld.gold.in  /var
            /tmp/dahlgren/spack-stage/spack-stage-xalt-2.10.45-h46wl6f5a3xtxiy2
            qoi2j3eycbhdlyus/spack-src/sh_src/x86_64-linux-gnu-ld.in  /var/tmp/
            dahlgren/spack-stage/spack-stage-xalt-2.10.45-h46wl6f5a3xtxiy2qoi2j
            3eycbhdlyus/spack-src/sh_src/xalt_helper_functions.sh  /var/tmp/dah
            lgren/spack-stage/spack-stage-xalt-2.10.45-h46wl6f5a3xtxiy2qoi2j3ey
            cbhdlyus/spack-src/sh_src/xalt_extract_record.in  /var/tmp/dahlgren
            /spack-stage/spack-stage-xalt-2.10.45-h46wl6f5a3xtxiy2qoi2j3eycbhdl
            yus/spack-src/sh_src/xalt_configuration_report.in  /var/tmp/dahlgre
            n/spack-stage/spack-stage-xalt-2.10.45-h46wl6f5a3xtxiy2qoi2j3eycbhd
            lyus/spack-src/sh_src/xalt_print_os.in"     DIRLOC=/usr/WS1/dahlgre
            n/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/xalt-2.10.45-h46w
            l6f5a3xtxiy2qoi2j3eycbhdlyus/xalt/2.10.45/bin     GIT_VERSION="xalt
            -2.10.45" __installMe
     157    install: cannot create regular file '/usr/WS1/dahlgren/spack/opt/sp
            ack/linux-rhel7-broadwell/gcc-8.3.1/xalt-2.10.45-h46wl6f5a3xtxiy2qo
            i2j3eycbhdlyus/xalt/2.10.45/include': File exists
  >> 158    make: *** [inst_obfuscate] Error 1
     159    make: *** Waiting for unfinished jobs....
     160    make[1]: Entering directory `/tmp/dahlgren/spack-stage/spack-stage-
            xalt-2.10.45-h46wl6f5a3xtxiy2qoi2j3eycbhdlyus/spack-src'
     161    for i in /var/tmp/dahlgren/spack-stage/spack-stage-xalt-2.10.45-h46
            wl6f5a3xtxiy2qoi2j3eycbhdlyus/spack-src/py_src/XALTdb.py  /var/tmp/
            dahlgren/spack-stage/spack-stage-xalt-2.10.45-h46wl6f5a3xtxiy2qoi2j
            3eycbhdlyus/spack-src/py_src/progressBar.py  /var/tmp/dahlgren/spac
            k-stage/spack-stage-xalt-2.10.45-h46wl6f5a3xtxiy2qoi2j3eycbhdlyus/s
            pack-src/py_src/xalt_stack.py  /var/tmp/dahlgren/spack-stage/spack-
            stage-xalt-2.10.45-h46wl6f5a3xtxiy2qoi2j3eycbhdlyus/spack-src/py_sr
            c/BeautifulTbl.py  /var/tmp/dahlgren/spack-stage/spack-stage-xalt-2
            .10.45-h46wl6f5a3xtxiy2qoi2j3eycbhdlyus/spack-src/py_src/xalt_globa
            l.py  /var/tmp/dahlgren/spack-stage/spack-stage-xalt-2.10.45-h46wl6
            f5a3xtxiy2qoi2j3eycbhdlyus/spack-src/py_src/Rmap_XALT.py  /var/tmp/
            dahlgren/spack-stage/spack-stage-xalt-2.10.45-h46wl6f5a3xtxiy2qoi2j
            3eycbhdlyus/spack-src/py_src/xalt_util.py  /var/tmp/dahlgren/spack-
            stage/spack-stage-xalt-2.10.45-h46wl6f5a3xtxiy2qoi2j3eycbhdlyus/spa
            ck-src/py_src/xalt_name_mapping.py; do                             
                    	   	  \
     162               bareN=${i##*/};                                         
              	   	  \
     163               fn=${bareN%%.in*};                                      
              	   	  \
     164       ext=${bareN#$fn.} 	                                            	
              \
...
```

2023-04-24 18:50 UTC, tldahlgren reviewed
I'm not able to build the package due to problems with a dependency of `mysql`.

2023-04-24 18:50 UTC, tldahlgren commented on var/spack/repos/builtin/packages/xalt/package.py
> +        "xaltFilePrefix", default="$HOME", description="Prefix where the json files are written"
Why are the json files written by default to the `$HOME` directory instead of the under the installation directory (`self.prefix`)?

2023-04-24 18:50 UTC, tldahlgren commented on var/spack/repos/builtin/packages/xalt/package.py
> +        "tmpdir", default="/dev/shm", description="The tmp directory to use with package records"
Not everyone will be able to write to `/dev/shm`.  Why not use a subdirectory of `self.stage` for portability?

2023-04-24 18:54 UTC, tldahlgren commented
This package is also appearing in #37094 .

2025-06-06 12:03 UTC, haampie commented
Hi @germanne, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2026-01-04 01:52 UTC, closed without merging