braket: new package
LLNL/spack pull request #35733
Opened 2023-02-28 11:30 UTC by N-tomoyasu

2023-03-01 00:45 UTC, tldahlgren requested changes
Confirmed the branch and tag exist.  Able to build with `spack install braket`; however, there are some issues with the logic used to set the arguments (see previous comments).

2023-03-01 00:45 UTC, tldahlgren commented on var/spack/repos/builtin/packages/braket/package.py
> +                  args = ['release-long']
You won't reach this check with `fp` containing `long-double`.  Same goes for the checks at line 75, 83, and 90.

2023-03-01 00:45 UTC, tldahlgren commented on var/spack/repos/builtin/packages/braket/package.py
> +        return args
You could simplify this with something along the lines of below (which assumes the current set of variant values:

```suggestion
        build = self.spec.variants["build"].value
        fp = self.spec.variants["fp"].value
        mpi_part = "" if '+mpi' in self.spec else "nompi-"
        prec_part = {
            "single": "-float",
            "double": "",
            "long-double": "-long",
        }
        return ["{0}{1}{2}".format(mpi_part, build, prec[fp])]
```

2023-03-01 00:48 UTC, tldahlgren commented
@naoki-yoshioka Are you okay with being listed as a maintainer on this package (see https://spack.readthedocs.io/en/latest/packaging_guide.html#maintainers)?

2023-03-01 00:51 UTC, tldahlgren commented on var/spack/repos/builtin/packages/braket/package.py
> +                  args = ['release-long']
If you want to keep this structure, you'll want to move the 'long-double' checks to *before* their 'double' checks.

2023-03-01 00:52 UTC, tldahlgren commented
This PR is going to fail the style checks because `black` wants double quotes (`"`), not single (`'`).

2023-03-01 09:03 UTC, N-tomoyasu commented
Thank you for your comment.
I fixed it including the single (') fix.

2023-10-09 16:27 UTC, alecbcs commented
@tldahlgren looks like this got stuck waiting on CI forever. Might be worth merging main into this or rebasing.

2023-10-09 17:49 UTC, tldahlgren commented
> @tldahlgren looks like this got stuck waiting on CI forever. Might be worth merging main into this or rebasing.

Thanks for the ping.  I don't know how I missed the updates.

2023-10-09 17:50 UTC, tldahlgren commented
Updating using `Update branch`.

2023-10-09 17:59 UTC, tldahlgren commented
Looks like there are (new) style issues:

```
==> Running black checks
--- var/spack/repos/builtin/packages/braket/package.py	2023-10-09 17:51:09.264776+00:00
+++ var/spack/repos/builtin/packages/braket/package.py	2023-10-09 17:51:26.353806+00:00
@@ -28,44 +28,40 @@
         "fp",
         default="double",
         description="Floating point mode uses single or double or long-double",
         values=("single", "double", "long-double"),
         multi=False,
-    )    
+    )
 
     depends_on("boost", type=("build", "link"))
     depends_on("mpi", when="+mpi", type=("build", "run"))
 
     build_directory = "bra"
 
     def edit(self, spec, prefix):
         makefile = FileFilter("bra/Makefile")
         if spec.satisfies("%fj"):
-           if "~mpi" in self.spec:
-               makefile.filter("g\+\+", "FCC")
-           else:
-               makefile.filter("mpiCC", "mpiFCC")
+            if "~mpi" in self.spec:
+                makefile.filter("g\+\+", "FCC")
+            else:
+                makefile.filter("mpiCC", "mpiFCC")
 
         else:
-           if "~mpi" in self.spec:
-              makefile.filter("FCCpx", "g++")
-           else:
-              makefile.filter("mpiFCCpx", "mpicxx")
-              makefile.filter("mpiCC", "mpicxx")
+            if "~mpi" in self.spec:
+                makefile.filter("FCCpx", "g++")
+            else:
+                makefile.filter("mpiFCCpx", "mpicxx")
+                makefile.filter("mpiCC", "mpicxx")
 
-           makefile.filter("-Nclang", "")
+            makefile.filter("-Nclang", "")
 
     @property
     def build_targets(self):
         build = self.spec.variants["build"].value
         fp = self.spec.variants["fp"].value
         mpi_part = "" if "+mpi" in self.spec else "nompi-"
-        prec_part = {
-            "single": "-float",
-            "double": "",
-            "long-double": "-long",
-        }
+        prec_part = {"single": "-float", "double": "", "long-double": "-long"}
         return ["{0}{1}{2}".format(mpi_part, build, prec_part[fp])]
 
     def install(self, spec, prefix):
         mkdirp(prefix.bin)
         install("bra/bin/bra", prefix.bin)
would reformat var/spack/repos/builtin/packages/braket/package.py
Oh no! 💥 💔 💥
1 file would be reformatted.
  black found errors
==> Running flake8 checks
var/spack/repos/builtin/packages/braket/package.py:10: [E501] line too long (171 > 99 characters)
var/spack/repos/builtin/packages/braket/package.py:33: [W291] trailing whitespace
var/spack/repos/builtin/packages/braket/package.py:43: [E111] indentation is not a multiple of 4
var/spack/repos/builtin/packages/braket/package.py:44: [E111] indentation is not a multiple of 4
var/spack/repos/builtin/packages/braket/package.py:44: [W605] invalid escape sequence '\+'
var/spack/repos/builtin/packages/braket/package.py:44: [W605] invalid escape sequence '\+'
var/spack/repos/builtin/packages/braket/package.py:45: [E111] indentation is not a multiple of 4
var/spack/repos/builtin/packages/braket/package.py:46: [E111] indentation is not a multiple of 4
var/spack/repos/builtin/packages/braket/package.py:49: [E111] indentation is not a multiple of 4
var/spack/repos/builtin/packages/braket/package.py:50: [E111] indentation is not a multiple of 4
var/spack/repos/builtin/packages/braket/package.py:51: [E111] indentation is not a multiple of 4
var/spack/repos/builtin/packages/braket/package.py:52: [E111] indentation is not a multiple of 4
var/spack/repos/builtin/packages/braket/package.py:53: [E111] indentation is not a multiple of 4
var/spack/repos/builtin/packages/braket/package.py:55: [E111] indentation is not a multiple of 4
  flake8 found errors
```

2023-10-09 18:00 UTC, tldahlgren commented on var/spack/repos/builtin/packages/braket/package.py
> +               makefile.filter("g\+\+", "FCC")
The escape character style fix:

```suggestion
               makefile.filter("g\\+\\+", "FCC")
```

2023-10-09 18:08 UTC, tldahlgren requested changes
Please resolve the style issues.

2023-10-09 18:08 UTC, tldahlgren commented on var/spack/repos/builtin/packages/braket/package.py
> +        return ["{0}{1}{2}".format(mpi_part, build, prec_part[fp])]
Optional.  You can now use f-strings to shorten this:

```suggestion
        return [f"{mpi_part}{build}{prec_part[fp]}"]
```

2023-10-09 18:10 UTC, tldahlgren commented
I am able to successfully built the package with `~mpi` and `+mpi` with the style changes.

2025-06-06 12:03 UTC, haampie commented
Hi @N-tomoyasu, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2026-01-04 01:52 UTC, closed without merging