libdistributed, sz*, plus: converted to new stand-alone test process; removed unnecessary make(test)
LLNL/spack pull request #35777
Opened 2023-03-02 01:15 UTC by tldahlgren

Depends on #34236 

Several packages simply had their post-`build` phase methods that run `make("test")` removed since they inherit from `CMakePackage`, which automatically runs that check if it is found in the makefile.

The rest have been converted to the new stand-alone test process.

2023-03-02 13:41 UTC, robertu94 requested changes
@tldahlgren something isn't right here.  I tried to run the tests (build and standalone) on your branch (commit d880a0fcc5a6153deb77cf9d694991d5c2cc6a55), and all I get i that no-tests exist for libpressio and sz.

2023-03-02 17:29 UTC, tldahlgren commented
> @tldahlgren something isn't right here. I tried to run the tests (build and standalone) on your branch (commit [d880a0f](https://github.com/spack/spack/commit/d880a0fcc5a6153deb77cf9d694991d5c2cc6a55)), and all I get i that no-tests exist for libpressio and sz.

@robertu94 Apologies for the confusion.  This PR depends on #34236 getting merged.  At this point I'm pulling out the converted/updated packages from that PR to make reviewing the change less onerous.

2024-05-13 17:13 UTC, robertu94 commented
Should we revive this and merge it into https://github.com/spack/spack/pull/44076

2024-08-26 23:03 UTC, tldahlgren commented
Superseded by #44572 #44691 #44725 #45151 #45363

2024-08-26 23:03 UTC, closed without merging