aws-parallelcluster: add v3.5.0
LLNL/spack pull request #35835
Opened 2023-03-05 22:26 UTC by alecbcs

Add aws-parallelcluster v3.5.0 which includes multiple bug fixes.

**Summarized Changelog:**
- Fix cluster DB creation by verifying the cluster name is no longer than 40 characters when Slurm accounting is enabled.
- Fix an issue in clustermgtd that caused compute nodes rebooted via Slurm to be replaced if the EC2 instance status checks fail.
- Fix an issue where compute nodes could not launch with capacity reservations shared by other accounts because of a wrong IAM policy on head node.
- Fix an issue where custom AMI creation failed in Ubuntu 20.04 on MySQL packages installation.
- Fix an issue where pcluster configure command failed when the account had no IPv4 CIDR subnet.

Full changelog [here](https://github.com/aws/aws-parallelcluster/releases/tag/v3.5.0).

2023-03-06 16:18 UTC, adamjstewart requested changes
You also need to update the dependencies:
```python
CDK_VERSION = "1.137,!=1.153.0"                                                          
REQUIRES = [                                                                             
    "setuptools",                                                                        
    "boto3>=1.16.14",                                                                    
    "tabulate>=0.8.8,<=0.8.10",                                                          
    "PyYAML~=5.3",                                                                       
    "jinja2~=3.0",                                                                       
    "marshmallow~=3.10",                                                                 
    "aws-cdk.core~=" + CDK_VERSION,                                                      
    "aws-cdk.aws-batch~=" + CDK_VERSION,                                                 
    "aws_cdk.aws-cloudwatch~=" + CDK_VERSION,                                            
    "aws-cdk.aws-codebuild~=" + CDK_VERSION,                                             
    "aws-cdk.aws-dynamodb~=" + CDK_VERSION,                                              
    "aws-cdk.aws-ec2~=" + CDK_VERSION,                                                   
    "aws-cdk.aws-efs~=" + CDK_VERSION,                                                   
    "aws-cdk.aws-events~=" + CDK_VERSION,                                                
    "aws-cdk.aws-fsx~=" + CDK_VERSION,                                                   
    "aws-cdk.aws-imagebuilder~=" + CDK_VERSION,                                          
    "aws-cdk.aws-iam~=" + CDK_VERSION,                                                   
    "aws_cdk.aws-lambda~=" + CDK_VERSION,                                                
    "aws-cdk.aws-logs~=" + CDK_VERSION,                                                  
    "aws-cdk.aws-route53~=" + CDK_VERSION,                                               
    "aws-cdk.aws-ssm~=" + CDK_VERSION,                                                   
    "aws-cdk.aws-sqs~=" + CDK_VERSION,                                                   
    "aws-cdk.aws-cloudformation~=" + CDK_VERSION,                                        
    "werkzeug~=2.0",                                                                     
    "connexion~=2.13.0",                                                                 
    "flask~=2.0",                                                                        
    "jmespath~=0.10",                                                                    
]                 
```

2023-03-06 16:43 UTC, enrico-usai commented
Hi @alecbcs version 3.x of ParallelCluster cannot work because of missing deps. See: https://github.com/spack/spack/pull/25892

2023-03-06 16:58 UTC, adamjstewart commented
Yep, someone just needs to add packages for the new dependencies. Should take about 5 min.

2023-05-06 04:51 UTC, alecbcs commented
Closing since I don't have the time to work on this at the moment. If someone else would like to work on this feel free to pick up where I'd left off.

2023-05-06 04:51 UTC, closed without merging