awscli: add v1.27.84
LLNL/spack pull request #35836
Opened 2023-03-05 22:30 UTC by alecbcs

Add awscli v1.27.84.

**Changelog:**
https://github.com/aws/aws-cli/compare/1.27.56...1.27.84

2023-03-06 16:20 UTC, adamjstewart requested changes

2023-03-06 16:20 UTC, adamjstewart commented on var/spack/repos/builtin/packages/awscli/package.py
>      version("1.16.179", sha256="6a87114d1325358d000abe22b2103baae7b91f053ff245b9fde33cb0affb5e4f")
Need to update botocore dep:
```python
    'botocore==1.29.84',                                                                 
```

2023-03-06 18:25 UTC, alecbcs commented on var/spack/repos/builtin/packages/awscli/package.py
>      version("1.16.179", sha256="6a87114d1325358d000abe22b2103baae7b91f053ff245b9fde33cb0affb5e4f")
Added! Thanks for double checking this PR!

2023-03-06 20:09 UTC, adamjstewart commented on var/spack/repos/builtin/packages/awscli/package.py
>      depends_on("py-botocore@1.29.56", when="@1.27", type=("build", "run"))
```suggestion
    depends_on("py-botocore@1.29.56", when="@1.27.56", type=("build", "run"))
```

2023-03-06 23:08 UTC, adamjstewart approved these changes

2023-03-07 19:37 UTC, alecbcs commented
@adamjstewart looks like auto-merge was disabled. Can you take a look at this again.

2023-03-07 19:38 UTC, merged