Install xz's dll in bin
LLNL/spack pull request #35888
Opened 2023-03-06 14:47 UTC by danlipsa

2023-03-06 14:48 UTC, danlipsa commented
@johnwparent Please review

2023-03-13 23:46 UTC, danlipsa commented
@johnwparent any idea what is wrong with ci/gitlab-ci? Thanks!

2023-03-14 04:46 UTC, johnwparent commented
@spackbot run pipeline

2023-06-05 23:15 UTC, scheibelp requested changes
I have a couple minor requests

2023-06-05 23:15 UTC, scheibelp commented on var/spack/repos/builtin/packages/xz/package.py
> +                mkdirp(prefix.bin)
`mkdirp` works whether or not dir has already been made: please remove from `if` statement.

2023-06-05 23:15 UTC, scheibelp commented on var/spack/repos/builtin/packages/xz/package.py
> -            if "libs=shared" in self.pkg.spec:
Less-redundant rewrite:

```
if self.pkg.spec.satisfies("libs=shared"):
  dlls_to_find.append(...)
if self.pkg.spec.satisfies("libs=static"): #this is not an elif
  libs_to_find.append(...)
```

2023-06-05 23:15 UTC, scheibelp requested changes
I have a couple minor requests

2023-06-07 15:34 UTC, danlipsa commented
@scheibelp Thanks for the review. All changes you requested have been pushed.

2023-06-16 19:38 UTC, danlipsa commented
@johnwparent Any ideas what is wrong with the pipeline that failed? Thanks!

2023-06-22 16:21 UTC, scheibelp commented
spackbot run pipeline

2023-06-22 16:21 UTC, scheibelp commented
@spackbot run pipeline

2023-06-23 13:20 UTC, kwryankrattiger commented
This is stuck on a generate issue that is thinking it found or could prune xz from rebuilding. Maybe this needs a rebase on the latest?

@scottwittenburg fyi

2023-06-23 20:18 UTC, scottwittenburg commented
It seems that `xz/rv46efa` is truly not present on any configured mirror.  But when I attempt to reproduce this pipeline generation generation issue locally, I get different behavior.  Specifically, `xz/rv46efa` along with many other specs are scheduled for rebuild.  This is just what happened in another attempt to reproduce a similar issue a couple weeks ago.  In that case, I asked spackbot to re-run the pipeline, and suddenly all the missing jobs were generated.

Let's see if that happens again here.

2023-06-23 20:18 UTC, scottwittenburg commented
@spackbot run pipeline

2023-06-23 20:40 UTC, scottwittenburg commented
Ugh, so this time `xz/rv46efa` and other dependents were scheduled to be built.  This makes me think that #38185 isn't going to help the way it is, since asking to run again with extra environment variables may not result in the same behavior.  Instead, as we discussed on the call today, I'll just print more information in the staging summary by default.

2023-06-29 13:42 UTC, danlipsa commented
@scheibelp Please review. All tests pass now.

2023-06-30 12:28 UTC, danlipsa commented
@scheibelp This passes all tests. Please review.

2023-06-30 17:07 UTC, scheibelp approved these changes

2023-06-30 17:10 UTC, merged

2023-06-30 17:11 UTC, scheibelp commented
Thanks!