New package: py-imbalanced-learn
LLNL/spack pull request #35895
Opened 2023-03-06 18:01 UTC by meyersbs

2023-03-06 18:03 UTC, meyersbs commented
@spackbot fix style

2023-03-06 18:15 UTC, meyersbs commented
@spackbot fix style

2023-03-06 23:23 UTC, tldahlgren reviewed
Confirmed the sha256.

2023-03-07 16:30 UTC, adamjstewart requested changes

2023-03-07 16:30 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-imbalanced-learn/package.py
> +    depends_on("py-cython@0.29.24:", type=("build", "run"))
```suggestion
    depends_on("py-cython@0.29.24:", type="build")
```

2023-03-07 21:07 UTC, adamjstewart approved these changes

2023-03-08 12:00 UTC, merged