new py-ultralytics package
LLNL/spack pull request #35890
Opened 2023-03-06 15:23 UTC by Sangu-Mbekelu

depends on !35889

2023-03-06 15:23 UTC, Sangu-Mbekelu commented
@spackbot fix style

2023-03-06 23:26 UTC, tldahlgren reviewed
Confirmed the sha256.

2023-03-07 16:34 UTC, adamjstewart requested changes

2023-03-07 16:34 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ultralytics/package.py
> +    depends_on("py-thop@0.1.1:", type=("build", "run"))
Missing deps on `py-certifi@2022.12.7:` and `py-sentry-sdk`

2023-03-07 16:34 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ultralytics/package.py
> +    depends_on("py-pillow@7.1.2:", type=("build", "run"))
```suggestion
    depends_on("pil@7.1.2:", type=("build", "run"))
```
We have a virtual provider for this

2023-03-08 15:15 UTC, adamjstewart approved these changes, later dismissed

2023-03-13 03:36 UTC, bernhardkaindl submitted a review, later dismissed
Rebased onto the new develop branch to have `py-certifi@2022.12.7` which was just merged.

2023-03-13 03:41 UTC, adamjstewart requested changes

2023-03-13 03:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ultralytics/package.py
> +    depends_on("opencv@4.6.0:", type=("build", "run"))
```suggestion
    depends_on("opencv@4.6.0:+python3", type=("build", "run"))
```

2023-03-13 16:32 UTC, adamjstewart approved these changes

2023-03-14 13:33 UTC, merged