py-openmesh: new package
LLNL/spack pull request #35907
Opened 2023-03-07 13:53 UTC by heerener

2023-03-07 17:31 UTC, tldahlgren reviewed
Confirmed the two version sha256.

2023-03-07 17:45 UTC, adamjstewart requested changes

2023-03-07 17:45 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-openmesh/package.py
> +        depends_on("cmake", when=f"platform={platform}", type="build")
```suggestion
    depends_on("cmake", type="build")
```
Dependencies are additive. This will make cmake required on all platforms, and a recent version of cmake specifically on Windows.

2023-03-08 15:11 UTC, adamjstewart approved these changes

2023-03-08 15:11 UTC, merged