Update MDAnalysis and addition of MDAnalysisTests
LLNL/spack pull request #36052
Opened 2023-03-12 21:53 UTC by RMeli

Reasons for deprecation of older versions:
* https://github.com/MDAnalysis/mdanalysis/issues/4020#issuecomment-1437503739
* There is no explicit dependency on `py-mdanalysis@:1`
    * Only one other package depends on `py-mdanalysis`
* Allows simplification of the package to ease support of future versions

2023-03-12 22:12 UTC, adamjstewart requested changes
I prefer to sort dependencies in the order they appear in pyproject.toml (and sort "when" by newest to oldest) because it makes it easier to review and make sure they match, but that's entirely optional, not a requirement.

2023-03-12 22:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mdanalysis/package.py
> +    depends_on("py-numpy@1.21.0:", when="@2.4.0:", type=("build", "run"))
```suggestion
    depends_on("py-numpy@1.20.0:", when="@2.4.0:", type=("build", "run"))
```

2023-03-12 22:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mdanalysis/package.py
> +    depends_on("hdf5", when="+extra_formats", type=("build", "run"))
```suggestion
    depends_on("py-h5py@2.10:", when="+extra_formats", type=("build", "run"))
```

2023-03-12 22:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mdanalysis/package.py
> +    depends_on("py-chemfiles", when="@2.4.0:+extra_formats", type=("build", "run"))
```suggestion
    depends_on("py-chemfiles@0.10:", when="@2.4.0:+extra_formats", type=("build", "run"))
```

2023-03-12 22:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mdanalysis/package.py
> +    depends_on("py-pyedr", when="@2.4.0:+extra_formats", type=("build", "run"))
```suggestion
    depends_on("py-pyedr@0.7.0:", when="@2.4.0:+extra_formats", type=("build", "run"))
```

2023-03-12 22:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mdanalysis/package.py
> +    depends_on("py-pytng", when="@2.4.0:+extra_formats", type=("build", "run"))
```suggestion
    depends_on("py-pytng@0.2.3:", when="@2.4.0:+extra_formats", type=("build", "run"))
```

2023-03-13 12:12 UTC, RMeli commented
Thanks for the review @adamjstewart

> I prefer to sort dependencies in the order they appear in pyproject.toml

This is my preference too and tried it before opening this PR. However, it was causing the diffs to be quite large in this case. I can change them once you are happy with the PR?

2023-03-13 16:48 UTC, adamjstewart approved these changes
Should be good now. Don't worry too much about the diffs. I can merge this as is, or you can reorder the deps now, or you can reorder the deps after the next release once v1 and older is removed, up to you.

2023-03-13 19:57 UTC, RMeli commented
Ok, in such case I'll do it a part of the major cleanup when removing the deprecated versions. I do plan to keep this package up to date. Thanks!

2023-03-13 20:01 UTC, merged