llnl.util.filesystem: add iterative deepening based search
LLNL/spack pull request #36083
Opened 2023-03-13 09:42 UTC by haampie

When locating files for externals in say `/usr`, sometimes Spack is
stuck in a slow `os.walk("/usr")`. Typically the relevant files are at
low depth, so it makes sense to locate files through iterative deepening
and early exit. The `FindFile` class implements this, using scandir and
fnmatch directly: `FindFile("/usr", "libhello.so*).run()`

Ping @scheibelp, maybe you can try this on your favorite slow filesystem

2023-03-14 12:08 UTC, haampie commented
I think the only thing that's missing now is case insensitive search for platforms with case insensitive filenames. :thinking:

2023-03-20 20:50 UTC, scheibelp requested changes
I have a few requests

2023-03-20 20:50 UTC, scheibelp commented on lib/spack/llnl/util/filesystem.py
> +def find_first(root: str, *file_patterns: str, bfs_depth: int = 2) -> Optional[str]:
This should follow the idioms established by`find`/`find_libraries`/...: `file_patterns` should be a `str` or a `list` of strings vs. a varargs.

2023-03-20 20:50 UTC, scheibelp commented on lib/spack/spack/test/llnl/util/filesystem.py
> +        f.write("contents")
The contents don't matter, so I suggest using `llnl.util.filesystem.touch`

2023-03-20 20:50 UTC, scheibelp commented on lib/spack/spack/test/llnl/util/filesystem.py
> +    tmpdir.join("a").ensure(dir=True).join("a").ensure(dir=True).join("a").ensure(dir=True)
(minor) FWIW I think this can be written as `tmpdir.join("a", "a", "a").ensure(dir=True)`

2023-03-20 21:50 UTC, haampie commented on lib/spack/spack/test/llnl/util/filesystem.py
> +    tmpdir.join("a").ensure(dir=True).join("a").ensure(dir=True).join("a").ensure(dir=True)
the more you know!

2023-03-21 17:01 UTC, scheibelp requested changes
I have a couple of suggestions for improving the test.

2023-03-21 17:01 UTC, scheibelp commented on lib/spack/spack/test/llnl/util/filesystem.py
> +    tmpdir.join("d", "a").ensure(dir=True)
Suggestion: add an empty directory at depth 1 (less than the default `bfs_depth`)

2023-03-21 17:01 UTC, scheibelp commented on lib/spack/spack/test/llnl/util/filesystem.py
> +    assert fs.find_first(root, "nonexisting") is None
Suggestion, since the `bfs_depth` is configurable, and it looks like your tests are organized around creating directories above/below that, I recommend explicitly setting bfs_depth in the tests (in case someone decides to change the default value later, this test won't be affected).

2023-03-21 17:01 UTC, scheibelp commented on lib/spack/llnl/util/filesystem.py
> +    """
It might be worth mentioning that this doesn't follow symlinks (the other `find` methods defined in this module don't do that, but perhaps they should.

2023-03-27 08:49 UTC, haampie commented on lib/spack/llnl/util/filesystem.py
> +    """
Hm, I don't think this is necessary, it says it's like the `find` command w/o other flags.

2023-03-27 16:34 UTC, scheibelp approved these changes

2023-03-27 16:42 UTC, merged