py-pdf2image: new package
LLNL/spack pull request #36088
Opened 2023-03-13 15:16 UTC by heerener

2023-03-16 23:25 UTC, tldahlgren reviewed
Confirmed the two sha256.

2023-03-18 22:09 UTC, adamjstewart requested changes

2023-03-18 22:09 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pdf2image/package.py
> +    depends_on("py-pillow", type=("build", "run"))
```suggestion
    depends_on("pil", type=("build", "run"))
```
We have a virtual dependency for this.

2023-03-20 15:33 UTC, adamjstewart approved these changes

2023-03-20 15:33 UTC, merged