py-pint-xarray: new package
LLNL/spack pull request #36106
Opened 2023-03-14 13:55 UTC by heerener

2023-03-16 22:43 UTC, tldahlgren reviewed
Confirmed both version sha256.

2023-03-16 22:44 UTC, tldahlgren commented
Added python gurus as reviewers.

2023-03-18 22:04 UTC, adamjstewart requested changes

2023-03-18 22:04 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pint-xarray/package.py
> +    depends_on("py-setuptools", type="build")
```suggestion
    depends_on("py-setuptools@42:", type="build")
```

2023-03-18 22:04 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pint-xarray/package.py
> +
```python
depends_on("python@3.8:", when="@0.3:", type=("build", "run"))
```

2023-03-20 15:34 UTC, adamjstewart approved these changes

2023-03-20 15:34 UTC, merged