Added lcc
LLNL/spack pull request #36100
Opened 2023-03-14 06:05 UTC by cnegre

Adding LCC package

2023-03-16 23:13 UTC, tldahlgren requested changes
There's a typo and a couple of suggestions/fixes.

2023-03-16 23:13 UTC, tldahlgren commented on var/spack/repos/builtin/packages/lcc/package.py
> +    version("main", branch="main", prefered=True)
```suggestion
    version("main", branch="main", preferred=True)
```

2023-03-16 23:13 UTC, tldahlgren commented on var/spack/repos/builtin/packages/lcc/package.py
> +        if "+shared" in spec:
This should correspond to a variant.  See https://spack.readthedocs.io/en/latest/packaging_guide.html#boolean-variants.

2023-03-16 23:13 UTC, tldahlgren commented on var/spack/repos/builtin/packages/lcc/package.py
> +            args.append("-DBUILD_SHARED_LIBS=OFF")
There are also some helpers that can simplify this (e.g., `self.define_from_variant`), see https://spack.readthedocs.io/en/latest/build_systems/cmakepackage.html#adding-flags-to-cmake.

2023-03-20 22:59 UTC, tldahlgren approved these changes
Confirmed the branch exists and the two version sha256 are correct.  Attempt to install seemed to take too long but `spack spec` succeeded.

2023-03-20 23:01 UTC, tldahlgren requested changes, later dismissed
Looks like a bunch of unrelated commits were pulled into this PR.  Please drop the unrelated commits.

2023-03-21 03:45 UTC, tgamblin commented on var/spack/repos/builtin/packages/lcc/package.py
> +    depends_on("cmake@3.10:", type="build")
@cnegre: note that I updated this per your `CMakeLists.txt` file

2023-03-21 03:48 UTC, tgamblin commented on var/spack/repos/builtin/packages/lcc/package.py
> +    version("1.0.0", sha256="750ce09e809a4e85ae3219fd537dc84a923fe3d3683b26b5d915eccfd1f0120c")
Also it's not needed for this PR, but you should make stable tarball for these (and call `v1.0.1` `v1.0.1`, not `cmake` as it says in your releases).  See https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/

2023-03-21 03:49 UTC, tgamblin commented
@spackbot run pipeline

2023-03-21 18:32 UTC, tldahlgren approved these changes
Re-confirmed I can successfully build `lcc@main` (with Todd's changes).

2023-03-21 18:32 UTC, merged