py-reportseff: add new package
LLNL/spack pull request #36113
Opened 2023-03-14 16:01 UTC by erimar77

2023-03-16 21:42 UTC, tldahlgren reviewed
Confirmed the sha256.

2023-03-16 21:42 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-reportseff/package.py
> +# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
```

2023-03-16 21:43 UTC, tldahlgren commented
Adding python gurus as reviewers.

2023-03-18 21:59 UTC, adamjstewart requested changes

2023-03-18 21:59 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-reportseff/package.py
> +    depends_on("python@3.7:", type=("build", "run"))
```suggestion
    depends_on("python@3.7:3", type=("build", "run"))
```

2023-03-18 21:59 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-reportseff/package.py
> +    depends_on("py-poetry-core", type="build")
```suggestion
    depends_on("py-poetry-core@1:", type="build")
```

2023-03-18 21:59 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-reportseff/package.py
> +    depends_on("py-click@6.7:", type=("build", "run"))
Missing dep:
```python
depends_on("py-importlib-metadata@4.8.2:4", when="^python@:3.7", type=("build", "run"))
```

2023-03-21 03:16 UTC, adamjstewart approved these changes

2023-03-21 03:17 UTC, merged