py-setuptools-git-versioning: new package
LLNL/spack pull request #36123
Opened 2023-03-15 00:03 UTC by angus-g

2023-03-16 21:04 UTC, tldahlgren reviewed
Confirmed the sha256.

2023-03-16 21:05 UTC, tldahlgren commented
Adding python gurus as reviewers.

2023-03-18 21:57 UTC, adamjstewart requested changes

2023-03-18 21:57 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-setuptools-git-versioning/package.py
> +    depends_on("py-setuptools", type="build")
```suggestion
    depends_on("py-setuptools", type=("build", "run"))
```

2023-03-18 21:57 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-setuptools-git-versioning/package.py
> +    depends_on("py-toml", when="python@:3.10", type=("build", "run"))
```suggestion
    depends_on("py-toml@0.10.2:", when="python@:3.10", type=("build", "run"))
```

2023-03-19 23:31 UTC, adamjstewart approved these changes

2023-03-20 00:02 UTC, merged