universal: New package
LLNL/spack pull request #36168
Opened 2023-03-16 16:20 UTC by eschnett

Universal: a header-only C++ template library for universal number arithmetic

2023-03-16 17:32 UTC, tldahlgren requested changes

2023-03-16 17:32 UTC, tldahlgren commented on var/spack/repos/builtin/packages/universal/package.py
> +    version("3.59.1", sha256="771d64cf51862fdc7c54de585eafac67",
This is not the correct checksum.  I'm getting the following:  

```suggestion
    version("3.59.1", sha256="0d9346b828af4ac1af2eabceaba20ba4c1208ce8afa9a2a7bdba3a382555f700",
```

2023-03-16 17:39 UTC, tldahlgren commented
Why not just use the `3.59` tagged branch (https://github.com/stillwater-sc/universal/releases/tag/v3.59)?

2023-03-17 17:53 UTC, eschnett commented
The version with `3.58b` in the file name self-identifies as `3.59.1` in the source code. Since people will never see the file name I thought that the version number in the source code is more appropriate. I'll update to the newer version.

2023-03-20 22:35 UTC, tldahlgren approved these changes
Confirmed the sha256, rest LGTM

2023-03-20 22:36 UTC, merged