henson: point Pybind11 to correct python
LLNL/spack pull request #36285
Opened 2023-03-21 22:51 UTC by anigmetov

Explicitly set PYTHON_EXECUTABLE to correct python. Without that python bindings can be compiled against a wrong version of python.

2023-03-21 22:55 UTC, mrzv approved these changes

2023-03-22 03:04 UTC, mrzv submitted a review, later dismissed

2023-03-22 07:58 UTC, alalazo commented
@spackbot fix style

2023-03-22 08:05 UTC, alalazo requested changes
I think you can simplify the function by writing it like:
```python
def cmake_args(self):
    args = [self.define_from_variant("python", "python")]
    if self.spec.satisfies("+python"):
        args += [self.define("PYTHON_EXECUTABLE", self.spec["python"].command.path)]
    return args
```
Beware of typos above, since I didn't try the function - just entered it in the UI

2023-03-24 07:54 UTC, alalazo commented
Closing in favor of #36398

2023-03-24 07:54 UTC, closed without merging