Osu/add pmi versions
LLNL/spack pull request #36324
Opened 2023-03-22 13:58 UTC by MatthewLieber

Adds a variant for users to choose their pmi version and add a None option to the process_managers variant

2023-03-27 09:46 UTC, alalazo requested changes

2023-03-27 09:46 UTC, alalazo commented on var/spack/repos/builtin/packages/mvapich/package.py
> +        values=disjoint_sets(("auto",), ("None",), ("slurm",), ("hydra", "gforker", "remshell"))
Please don't. If you want to have an identifier for an empty set, just remove the line below:
```python
.phoibit_empy_set()
```

2023-03-27 12:45 UTC, natshineman commented
I think there is some confusion here. Our default case is to have this set to auto (this is the behaviour when unset). There is an actual option to configure called `--with-pm=none` that indicates the user is explicitly disabling a process manager. This is a non-standard use case, but needed for sites like LLNL where they plan to run an alternative launcher/resouce manager that is not directly supported in MVAPICH. So "none" here is actually an explicit disable of the process manager, rather than an empty set.

2023-03-27 12:52 UTC, alalazo commented
@natshineman Not sure I follow, but my point is more trivial. Let's not use `None` (uppercase first letter, used by this package only) but remove `proihibit_empy_set`. That will make `none` a possible value (used by many other packages). 

Besides, it's not really clear to me what is the difference between "explicitly disabling process managers" and "the set of allowed process managers is empty".

2023-03-27 13:00 UTC, natshineman commented
@alalazo we can do that. I think that the difference within the context of building our package is primarily semantic. If you were to build MVAPICH outside of spack you would have to specify `./configure --with-pm=none ..` to get this behaviour. Just running `./configure ..` would give you `--with-pm=auto`.  I think that Matt was trying to avoid confusion with the Python empty set so that a user familiar with this process would not assume that setting it to empty would result in the default value (auto) being used, as it would in the configure script. So while you are correct that the allowed set of process managers is empty, we have typically approached this from the viewpoint of our standard configure system.

However, when in Spack. @MatthewLieber please make that change and add the logic to convert an empty set from spack to the `--with-pm=none` option in configure.

2023-03-28 17:45 UTC, alalazo approved these changes
Thanks!

2023-03-28 17:46 UTC, merged