Rename p2300 variant with stdexec for pika package
LLNL/spack pull request #36322
Opened 2023-03-22 13:39 UTC by aurianer

We now rename the variant in pika since the senders/receivers implementation moved from https://github.com/brycelelbach/wg21_p2300_execution to https://github.com/NVIDIA/stdexec.

2023-03-22 21:13 UTC, tldahlgren approved these changes, later dismissed
Looks like all the associated references to `p2300` in the package were changed and I can't find any built-in packages or CI stacks that explicitly utilize the original variant name.

2023-03-22 21:14 UTC, tldahlgren commented
Let me know if you want this merged now or if I should give time for one or more of the other maintainers to review the change.

2023-03-24 09:55 UTC, aurianer commented
it's not urgent so we can wait for @msimberg to review it, thank you :)

2023-03-24 14:33 UTC, msimberg requested changes
Just comment on updating the description of the `stdexec` variant. Looks good otherwise!

2023-03-24 14:33 UTC, msimberg commented on var/spack/repos/builtin/packages/pika/package.py
> +        description="Use stdexec reference implementation for sender/receiver functionality",
```suggestion
        description="Use stdexec for sender/receiver functionality",
```

2023-03-27 09:23 UTC, msimberg approved these changes

2023-03-27 09:24 UTC, merged