[py-mizani] added version 0.8.1
LLNL/spack pull request #36500
Opened 2023-03-28 16:19 UTC by qwertos

Depends on: #36499

2023-03-28 17:04 UTC, tldahlgren reviewed
Confirmed the sha256.

2023-03-28 18:48 UTC, adamjstewart requested changes

2023-03-28 18:48 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mizani/package.py
> +    depends_on("py-setuptools-scm@6.2:", type="build", when="@0.8.1:")
```suggestion
    depends_on("py-setuptools-scm@6.2:+toml", type="build", when="@0.8.1:")
```

2023-03-28 18:50 UTC, adamjstewart submitted a review, later dismissed

2023-04-05 17:09 UTC, qwertos commented
I guess I shouldn't use github's rebase feature...

2023-04-05 17:18 UTC, adamjstewart approved these changes

2023-04-05 17:19 UTC, adamjstewart commented
Yep, GitHub's rebase feature is broken at the moment, @alalazo reported the same thing

2023-04-05 17:22 UTC, adamjstewart commented
https://github.com/orgs/community/discussions/51948

2023-04-05 20:57 UTC, merged