MDAnalysis 2.4.3
LLNL/spack pull request #36541
Opened 2023-03-30 06:00 UTC by RMeli

Update MDAnalysis and MDanalysisTests versions.

2023-03-30 23:09 UTC, tldahlgren reviewed
Confirmed the two version sha256.

2023-03-31 02:03 UTC, adamjstewart requested changes

2023-03-31 02:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mdanalysis/package.py
threadpoolctl missing type=build/run

analysis variant missing tidynamics dep

would be easier to review this package if the deps were sorted the same as pyproject.toml, but this part is optional

2023-03-31 18:43 UTC, adamjstewart approved these changes

2023-03-31 18:47 UTC, merged