New: py-dalib, py-qdldl, py-qpsolvers; Update: py-ecos, py-scs, py-osqp
LLNL/spack pull request #36549
Opened 2023-03-30 15:11 UTC by meyersbs

```mermaid
graph TD;
  'py-dalib'-->'py-qpsolvers';
  'py-qpsolvers'-->'py-ecos';
  'py-qpsolvers'-->'py-osqp';
  'py-osqp'-->'py-qdldl';
  'py-qpsolvers'-->'py-scs';
```

2023-03-30 15:12 UTC, meyersbs commented
@spackbot fix style

2023-03-30 22:54 UTC, tldahlgren reviewed
Confirmed the 7 version sha256.  Deferring merge decision to @adamjstewart and or @pradyunsg

2023-03-31 01:38 UTC, adamjstewart requested changes

2023-03-31 01:38 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-osqp/package.py
>      depends_on("py-future", type=("build", "run"))
Future is no longer needed

2023-03-31 01:38 UTC, adamjstewart commented
Love the dependency graph! I wonder if we could teach spackbot to automatically add this to PRs...

2023-03-31 11:46 UTC, meyersbs commented
> Love the dependency graph! I wonder if we could teach spackbot to automatically add this to PRs...

The dependency graphs help keep @qwertos sane when we're working internally.

2023-03-31 14:33 UTC, adamjstewart approved these changes

2023-03-31 14:34 UTC, merged