New package: py-qiskit-ibm-provider and more
LLNL/spack pull request #36559
Opened 2023-03-30 18:45 UTC by qwertos

- py-rustworkx: New package
- py-ipyvue: New package
- py-websocket-client: Added version 1.5.1
- py-contextvars: New package
- py-ipyvuetify: New package
- py-qiskit-terra: Added version 0.23.3
- py-qiskit-ibm-provider: New package

2023-03-30 18:45 UTC, qwertos commented
@spackbot fix style

2023-03-30 20:28 UTC, tldahlgren reviewed
Confirmed the 7 version sha256.

2023-03-30 20:29 UTC, tldahlgren commented
Deferring python dependency assessment and  merge decision to @adamjstewart and or @pradyunsg

2023-03-31 01:31 UTC, adamjstewart requested changes

2023-03-31 01:31 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-contextvars/package.py
> +    depends_on("python@3.6:", type=("build", "run"))
Where do you see this? I would just remove this line, Spack only supports 3.7+ anyway

2023-03-31 01:31 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ipyvue/package.py
> +    depends_on("py-setuptools", type="build")
Missing ipywidgets dep. Also, is npm required to build?

2023-03-31 01:31 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ipyvuetify/package.py
> +    depends_on("py-ipyvue@1.5:2", type=("build", "run"))
```suggestion
    depends_on("py-ipyvue@1.5:1", type=("build", "run"))
```
Is npm required to build?

2023-03-31 01:31 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-qiskit-ibm-provider/package.py
> +    url = "https://github.com/Qiskit/qiskit-ibm-provider/archive/refs/tags/0.4.0.tar.gz"
https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#pypi-vs-github

2023-03-31 01:31 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-qiskit-terra/package.py
> +        depends_on("py-importlib-metadata@:4", when="^python@:3.7", type=("build", "run"))
Missing singledispatch dep

2023-03-31 01:31 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-qiskit-terra/package.py
tweedledum is no longer required

2023-04-04 20:15 UTC, qwertos commented
@spackbot fix style

2023-04-05 15:47 UTC, qwertos commented
I'm going to simplify and resubmit

2023-04-05 15:47 UTC, closed without merging