e4s ci: add mgard
LLNL/spack pull request #36584
Opened 2023-03-31 17:40 UTC by eugeneswalker

E4S CI: add `mgard`

FYI @robertu94 @wspear

2023-04-03 11:11 UTC, robertu94 commented
I looked at the error here.  CMake sets the default `CMAKE_CUDA_ARCHITECTURE` for Nvidia cuda compilers if there is a cuda driver, but since there isn't necessarily a GPU in the build environment it isn't initialized here.  The fix is to add `CUDA_ARCH_STRING` to the mgard `cmake_args` function.

Additionally, 1.5.0, was released last Friday.  I just confirmed that it works for me locally with LibPressio.  Use this commit for 1.5.0 `a8a04a86ff30f91d0b430a7c52960a12fa119589`

2023-04-11 23:47 UTC, robertu94 submitted a review, later dismissed

2023-04-12 03:42 UTC, alalazo requested changes
There are a few erros in `mgard` that seem legit :slightly_frowning_face:

2023-04-12 14:58 UTC, eugeneswalker commented
> There are a few erros in `mgard` that seem legit 🙁

Ooops, should have waited for our updates to `mgard` to be merged. They are merged now and I just rebased on them. Should succeed this time. Thanks!

2023-04-13 18:37 UTC, wspear approved these changes, later dismissed

2023-04-24 20:31 UTC, wspear approved these changes

2023-04-24 21:35 UTC, alalazo approved these changes

2023-04-24 21:35 UTC, merged