Add versions of opencoarray
LLNL/spack pull request #36626
Opened 2023-04-03 22:28 UTC by hpcnpatel

Add versions of Opencoarray in the package.py file

2023-04-04 07:34 UTC, alalazo requested changes

2023-04-04 07:34 UTC, alalazo commented on var/spack/repos/builtin/packages/fgsl/package.py
> +    version("1.5.0", sha256="5013b4e000e556daac8b3c83192adfe8f36ffdc91d1d4baf0b1cb3100260e664")
I cannot verify v1.5.0:
![Screenshot from 2023-04-04 09-34-25](https://user-images.githubusercontent.com/4199709/229720869-0510d99c-61d8-4655-a3ec-e70a41818a35.png)

2023-04-04 11:47 UTC, hpcnpatel commented on var/spack/repos/builtin/packages/fgsl/package.py
> +    version("1.5.0", sha256="5013b4e000e556daac8b3c83192adfe8f36ffdc91d1d4baf0b1cb3100260e664")
done

2023-04-11 14:28 UTC, alalazo approved these changes

2023-04-11 14:29 UTC, merged