dealii: add support for 9.4.1 and 9.4.2
LLNL/spack pull request #36627
Opened 2023-04-04 06:36 UTC by luca-heltai

We forgot to bump the versions for the last two minor releases. No other changes are needed.

2023-04-04 07:18 UTC, alalazo approved these changes

2023-04-12 05:21 UTC, alalazo requested changes
![Screenshot from 2023-04-12 07-21-13](https://user-images.githubusercontent.com/4199709/231358188-88da60c7-8de2-41b4-a7df-f5cb99cf3629.png)

2023-04-30 11:50 UTC, luca-heltai commented
Incorporates here also changes from #37229. There is an additional one that was missing for hdf5.

2023-04-30 11:54 UTC, luca-heltai commented
@alalazo, this should now be fixed, including the comments from #37229. I'm sorry about beeing so slow in responding.

2023-05-02 08:48 UTC, alalazo commented
@luca-heltai No worries, thank you for your contribution!

2023-05-02 08:49 UTC, alalazo approved these changes

2023-05-02 08:49 UTC, merged