Packages/ophidia server
LLNL/spack pull request #36632
Opened 2023-04-04 13:39 UTC by SoniaScard

Update Ophidia Server release to 1.7.4

2023-04-04 13:58 UTC, eldoo submitted a review, later dismissed

2023-04-06 18:02 UTC, tldahlgren requested changes
Confirmed the new sha256.  Do have some issues with changing the `maintainers` syntax and a suggestion for deprecating the old version.

2023-04-06 18:02 UTC, tldahlgren commented on var/spack/repos/builtin/packages/ophidia-server/package.py
> +    maintainers = ["eldoo", "SoniaScard"]
Why change this?  The previous (newer) syntax for `maintainers` is preferred.  

(https://spack.readthedocs.io/en/latest/packaging_guide.html#maintainers)

2023-04-06 18:02 UTC, tldahlgren commented on var/spack/repos/builtin/packages/ophidia-server/package.py
> +    version("1.7.4", sha256="30128c99ae089ab766141397ea5098ac930cfe10d09b289ed120f6581d8bb07d")
Normally versions are retained or at least deprecated before being removed (see https://spack.readthedocs.io/en/latest/packaging_guide.html#deprecating-old-versions).

2023-04-06 18:02 UTC, tldahlgren commented on var/spack/repos/builtin/packages/ophidia-server/package.py
> +    version("1.7.4", sha256="30128c99ae089ab766141397ea5098ac930cfe10d09b289ed120f6581d8bb07d")
You could restore `1.7.2` and add `, url="https://github.com/SoniaScard/ophidia-server/archive/refs/tags/v1.7.2.tar.gz"` along with `deprecated=True`.

2023-04-06 18:10 UTC, tldahlgren commented on var/spack/repos/builtin/packages/ophidia-server/package.py
> +    version("1.7.4", sha256="30128c99ae089ab766141397ea5098ac930cfe10d09b289ed120f6581d8bb07d")
I think this package is new enough we could proceed without restoring `1.7.2`.  Just let me know what you want to do about this change.

2023-04-06 20:41 UTC, SoniaScard commented on var/spack/repos/builtin/packages/ophidia-server/package.py
> +    version("1.7.4", sha256="30128c99ae089ab766141397ea5098ac930cfe10d09b289ed120f6581d8bb07d")
Yes, we could proceed without restoring 1.7.2 version.

2023-04-06 20:44 UTC, tldahlgren approved these changes

2023-04-06 21:11 UTC, merged