Intel TBB: Add variant to disable tests
LLNL/spack pull request #36782
Opened 2023-04-11 15:52 UTC by kwryankrattiger

It seem like the tests are not compatible on system with non-standard BLAS providers, like `cray-libsci`, and fail to build due to hard-coded flags `-lcblas` and missing flags that are assumed to be implicit like `-ldl`. If an Intel maintainer can fix those issues that is probably better, but in lieu of that I propose adding a flag to disable the tests so that Intel TBB can

2023-04-11 16:29 UTC, kwryankrattiger commented
@spackbot fix style

2023-04-11 18:26 UTC, rscohn2 approved these changes
Looks good. Thanks

2023-04-11 18:44 UTC, eugeneswalker approved these changes

2023-05-10 21:46 UTC, kwryankrattiger commented
@spackbot run pipeline

2023-05-29 10:56 UTC, alalazo requested changes
I don't think we should add a variant for running unit tests during build (it enters the hash). It would be better to rely on `self.run_tests` which is set to `True` when user asked to run unit test from cli.

2023-05-29 10:56 UTC, alalazo commented on var/spack/repos/builtin/packages/intel-tbb/package.py
> +    )
```suggestion
```

2023-05-29 10:56 UTC, alalazo commented on var/spack/repos/builtin/packages/intel-tbb/package.py
> +                self.define_from_variant("TBB_TEST", "test"),
```suggestion
                self.define_from_variant("TBB_TEST", self.run_tests),
```

2024-11-27 09:28 UTC, alalazo commented
@kwryankrattiger Would you be fine with closing this one?

2024-11-27 13:34 UTC, kwryankrattiger commented
I need to review this again. If it is a build failure then we need a way to not build the tests. I don't know if controlling build flags with runtime options in Spack is a great idea the more I think about it.

2024-11-27 13:51 UTC, alalazo commented
> I need to review this again.

@kwryankrattiger No rush, I'll keep this one open

2025-06-15 08:06 UTC, alalazo commented
We should reopen this PR at / migrate to https://github.com/spack/spack-packages

2025-12-15 18:53 UTC, closed without merging