Enable installer test
LLNL/spack pull request #36792
Opened 2023-04-11 21:59 UTC by markus-ferrell

Removes assertion verifying lock behavior in the installer test. This assertion doesn't hold up when locking is disabled and isn't core to the test meaning.

2023-04-12 03:53 UTC, alalazo requested changes

2023-04-12 03:53 UTC, alalazo commented on lib/spack/spack/test/installer.py
> -    assert os.path.isfile(spack.store.db.prefix_fail_path)
The comment is not up to date. Also, while I kind of agree that this isn't core to the test meaning, we now need a test that verifies the lock is there when locking is enabled.

2023-07-18 16:57 UTC, alalazo commented on lib/spack/spack/test/installer.py
> -    assert os.path.isfile(spack.store.db.prefix_fail_path)
@markus-ferrell Can you update the comment at line 566 to briefly explain why we skip the second assertion on Windows (lock is a no-op)

2023-07-18 17:52 UTC, markus-ferrell commented on lib/spack/spack/test/installer.py
> -    assert os.path.isfile(spack.store.db.prefix_fail_path)
@alalazo I added in a comment like you suggested.

2023-07-18 20:41 UTC, alalazo approved these changes

2023-07-18 20:42 UTC, merged