r-git2r: add v0.31.0
LLNL/spack pull request #36864
Opened 2023-04-14 03:02 UTC by alecbcs

Add r-git2r v0.31.0. 
 
**Test Plan:**
Built successfully using `gcc@10.4.0` on Debian 11.

2023-04-15 12:29 UTC, alalazo approved these changes, later dismissed

2023-04-15 19:24 UTC, glennpj requested changes
The new version depends on `r@3.4:` so that will need to be added.

2023-04-16 21:50 UTC, alecbcs commented
> The new version depends on `r@3.4:` so that will need to be added.

Added! Thanks for the heads up!

2023-04-18 20:07 UTC, glennpj approved these changes

2023-04-18 20:08 UTC, merged