r-highr: add v0.10
LLNL/spack pull request #36867
Opened 2023-04-14 03:02 UTC by alecbcs

Add r-highr v0.10. 
 
**Test Plan:**
Built successfully using `gcc@10.4.0` on Debian 11.

2023-04-15 12:28 UTC, alalazo approved these changes, later dismissed

2023-04-15 19:26 UTC, glennpj requested changes
The new version depends on `r@3.3.0:' so that will need to be added.

2023-04-16 21:50 UTC, alecbcs commented
> The new version depends on `r@3.3.0:' so that will need to be added.

Added! Thanks for the heads up @glennpj!

2023-04-18 20:06 UTC, glennpj approved these changes

2023-04-18 20:06 UTC, merged