Update Qthreads recipe to support latest package versions
LLNL/spack pull request #37029
Opened 2023-04-19 17:48 UTC by janciesko

Updates the `Qthreads` recipe to support versions `1.17` and `1.18`. Bumps requirement for `hwloc` to `2.x`.

2023-05-02 19:51 UTC, janciesko commented
This should be ready.

2023-05-29 11:24 UTC, alalazo requested changes

2023-05-29 11:24 UTC, alalazo commented on var/spack/repos/builtin/packages/qthreads/package.py
> +    depends_on("hwloc@1.5:2", when="@:1.16 +hwloc")
Is this:
```suggestion
    depends_on("hwloc@1.5:2", when="@1.16 +hwloc")
```
what you meant?

2023-05-29 11:24 UTC, alalazo commented on var/spack/repos/builtin/packages/qthreads/package.py
> +    depends_on("hwloc@2", when="@:1.18 +hwloc")
```suggestion
    depends_on("hwloc@2", when="@1.17: +hwloc")
```

2024-02-22 06:53 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2024-02-22 06:53 UTC, closed without merging