acts: new version 23.[3-5].0, 24.0.0
LLNL/spack pull request #37055
Opened 2023-04-20 15:11 UTC by wdconinc

- https://github.com/acts-project/acts/compare/v23.2.1...v23.3.0:
  - `py-onnxruntime@1.12.0:` now required when `+onnx`, previous versions conflict with `1.13:` (https://github.com/acts-project/acts/pull/1835)
- https://github.com/acts-project/acts/compare/v23.3.0...v23.4.0
  - `actsvg@0.4.29:` now required when `+svg`
- https://github.com/acts-project/acts/compare/v23.4.0...v23.5.0
  - `actsvg@0.4.30:` now required when `+svg`
- https://github.com/acts-project/acts/compare/v23.5.0...v24.0.0
  - nothing relevant

2023-04-20 20:57 UTC, tldahlgren submitted a review, later dismissed
Confirmed the commits exist (in association with the versions).  Deferring merge decision to @HadrienG2 .

2023-04-21 06:23 UTC, HadrienG2 approved these changes

2023-07-05 17:44 UTC, wdconinc commented
@spackbot fix style

2023-07-05 17:47 UTC, wdconinc commented on var/spack/repos/builtin/packages/acts/package.py
> +        when="@19.4.0:24 +examples",
```suggestion
```

2023-07-05 17:51 UTC, wdconinc commented
We're starting to run a bit behind in ACTS versions supported in spack. This aims to do a bit of catchup.

I've removed the blockers due to audit on not-yet-merged PRs, and added conflicts for those variants while the relevant PRs are merged. @HadrienG2 Could you give another review?

2023-07-05 17:51 UTC, wdconinc commented on var/spack/repos/builtin/packages/acts/package.py
> +    depends_on("podio @0.6", when="@25: +edm4hep")
```suggestion
    depends_on("podio @0.6:", when="@25: +edm4hep")
```

2023-07-06 03:42 UTC, HadrienG2 approved these changes
Thanks for the awesome continued support work!

2023-07-06 20:43 UTC, becker33 requested changes
Can you update this for mlpack now that #38277 is merged?

2023-07-06 21:02 UTC, wdconinc commented on var/spack/repos/builtin/packages/acts/package.py
> +    conflicts("+mlpack", when="@25:", msg="mlpack@3.1.1: required but not yet available")
```suggestion
    depends_on("mlpack@3.1.1:", when="+mlpack")
```

2023-07-10 18:27 UTC, tldahlgren approved these changes, later dismissed
Confirmed all new version commits, rest LGTM.

2023-08-01 14:39 UTC, wdconinc commented
Thanks to @Zehvogel in #39189 for the 28.0.0 addition and ping to this PR. I've added the necessary hash here, as well as the newer version of actsvg required. Maybe this can get reviewed again and pushed?

It's over 3 months old and I don't think it includes any showstoppers. It would be nice to get `py-onnxruntime` working instead of adding a conflict, but that has turned out to be hardly trivial.

2023-08-01 15:57 UTC, HadrienG2 approved these changes

2023-08-01 16:28 UTC, tldahlgren reviewed
Re-confirmed version commits/sha256.

2023-08-01 16:29 UTC, tldahlgren approved these changes
LGTM

2023-08-01 16:31 UTC, tldahlgren commented
Looks like this PR cannot be merged until @becker33 releases his change request.

2023-08-04 23:47 UTC, becker33 approved these changes

2023-08-04 23:47 UTC, merged