spec.format: fix bug in dependency hash formatting
LLNL/spack pull request #37073
Opened 2023-04-20 19:59 UTC by becker33

Fixes #37018

`Spec("bar").concretized().format("{^foo.hash})` formatting was returning the hash of `bar` rather than the hash of `foo`.

2023-04-21 09:52 UTC, alalazo requested changes
LGTM, but can we add a regression test?

2023-04-21 10:53 UTC, haampie commented
Maybe a parametrized test that tests both `{prop}` and `{^x.prop}` for all props?

2023-04-27 17:44 UTC, becker33 commented
@spackbot fix style

2023-04-27 20:38 UTC, becker33 commented
@alalazo @haampie I had to tinker with the test a bit to get it properly parametrized, I think this should be good.

2023-04-28 21:32 UTC, alalazo approved these changes
![Screenshot from 2023-04-28 23-32-17](https://user-images.githubusercontent.com/4199709/235257846-596d12ad-0fbf-4efe-ac7d-c26a320f8bdb.png)

2023-04-28 21:33 UTC, merged