visit: python 3.9 and above acceptable
LLNL/spack pull request #37071
Opened 2023-04-20 18:55 UTC by cessenat

Visit compiles fine with Python 3.9.
I got it work with
`spack install visit@3.3.3 %gcc ^python@3.9.6+shared ^silo@4.11 ^mpich ^openblas ^mesa+opengl ^qt~doc
`on Ubuntu 20.04 with gcc 9.0.3 .

2023-04-20 19:23 UTC, cyrush commented
Hi @cessenat, we have another PR for VisIt 3.3.3 support:

https://github.com/spack/spack/pull/37034

That includes some additional patching logic. 

Can we, add the Python 3.9 support in a follow up PR after #37034 is merged?

2023-04-20 20:15 UTC, tldahlgren submitted a review, later dismissed
Confirmed the sha256.  Deferring merge decision to @cyrush .

2023-04-21 16:25 UTC, cessenat commented
> Hi @cessenat, we have another PR for VisIt 3.3.3 support:
> 
> #37034
> 
> That includes some additional patching logic.
> 
> Can we, add the Python 3.9 support in a follow up PR after #37034 is merged?

Sure, good idea.

2023-04-28 10:53 UTC, alalazo requested changes
The comment above the change is outdated, (and can be removed

2023-04-28 16:17 UTC, cessenat commented
> The comment above the change is outdated, and can be removed

I'm not sure if you want me to change anything.
I assert visit works fine with python 3.9 and vtk 8.

2023-04-28 16:46 UTC, alalazo commented
@cessenat Sorry, for some reason I was thinking 3.8 and above. But I see that 3.8 is still skipped, so don't mind my comment.

2023-04-28 16:46 UTC, alalazo approved these changes

2023-04-28 16:47 UTC, alalazo commented
If this one is fine with @cyrush I'll merge it

2023-05-01 20:47 UTC, cyrush approved these changes

2023-05-02 08:18 UTC, merged