Add Xalt to builtins.
LLNL/spack pull request #37094
Opened 2023-04-22 00:30 UTC by jflics6460

Adds most recent version of Xalt to builtin packages.

2023-04-24 16:36 UTC, tldahlgren approved these changes
Confirmed the sha256.

2023-04-24 16:36 UTC, tldahlgren commented on var/spack/repos/builtin/packages/xalt/package.py
> +# ----------------------------------------------------------------------------
Please remove these boiler plate comments.

2023-04-24 16:36 UTC, tldahlgren requested changes
Needs the how-to install and edit comments removed.

2023-04-24 16:48 UTC, tldahlgren commented
I am unable to build the package.  It appears to have issues with the `configure` phase:

```
Unable to install XALT without setting --with-config=...
[spack-build-out.txt](https://github.com/spack/spack/files/11312746/spack-build-out.txt)

See the xalt.readthedocs.io for details
```

[spack-build-out.txt](https://github.com/spack/spack/files/11312758/spack-build-out.txt)

2023-04-24 16:53 UTC, tldahlgren commented
This is actually a duplicate of https://github.com/spack/spack/pull/35736.

2025-06-06 12:04 UTC, haampie commented
Hi @jflics6460, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2026-01-04 01:52 UTC, closed without merging