add ascent 0.9.1 release
LLNL/spack pull request #37139
Opened 2023-04-23 17:03 UTC by cyrush

2023-04-23 23:33 UTC, eugeneswalker requested changes

2023-04-23 23:33 UTC, eugeneswalker commented on var/spack/repos/builtin/packages/ascent/package.py
> +    version("0.9.1", tag="v0.9.0", submodules=True, preferred=True)
Shouldn't `@0.9.1` have `tag="v0.9.1"` ?

2023-04-24 16:29 UTC, tldahlgren commented on var/spack/repos/builtin/packages/ascent/package.py
> +    version("0.9.1", tag="v0.9.0", submodules=True, preferred=True)
Great catch!

2023-04-24 16:30 UTC, tldahlgren reviewed
Confirmed that the `0.9.1` tag exists, which will be relevant when the correction is made.

2023-04-24 23:09 UTC, cyrush commented on var/spack/repos/builtin/packages/ascent/package.py
> +    version("0.9.1", tag="v0.9.0", submodules=True, preferred=True)
yes, sorry :-(

2023-04-24 23:19 UTC, eugeneswalker approved these changes

2023-04-25 19:54 UTC, tldahlgren approved these changes

2023-04-25 19:54 UTC, merged