New: py-ax-platform; Update: py-botorch, py-gpytorch, py-linear-operator, py-pyro-ppl, py-typeguard
LLNL/spack pull request #37143
Opened 2023-04-24 13:20 UTC by meyersbs

```mermaid
graph TD;
  'py-ax-platform'-->'py-botorch';
  'py-ax-platform'-->'py-typeguard';
  'py-botorch'-->'py-linear-operator';
  'py-botorch'-->'py-pyro-ppl';
  'py-botorch'-->'py-gpytorch';
```

2023-04-24 13:22 UTC, meyersbs commented
@spackbot fix style

2023-04-24 13:26 UTC, meyersbs commented
@spackbot fix style

2023-04-24 13:31 UTC, meyersbs commented
Something weird with style checks; first it says something's wrong, then it passes without making changes.

2023-04-24 15:04 UTC, adamjstewart requested changes
Glad someone else is using these packages!

2023-04-24 15:04 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ax-platform/package.py
> +    depends_on("py-botorch@0.8.3:", type=("build", "run"))
I think you need to set the `ALLOW_BOTORCH_LATEST` env var in order to support newer botorch

2023-04-24 15:04 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ax-platform/package.py
> +    depends_on("py-plotly@5.12.0:", when="^py-ipywidgets@8.0.0:", type=("build", "run"))
```suggestion
    depends_on("py-plotly@5.12.0:", type=("build", "run"))
```
Always required

2023-04-24 15:04 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ax-platform/package.py
> +    depends_on("py-typeguard@2.13.3:", type=("build", "run"))
```suggestion
    depends_on("py-typeguard@2.13.3", type=("build", "run"))
```

2023-04-24 15:04 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-botorch/package.py
> +    depends_on("py-setuptools@:47", when="@:0.6.4", type='build')
```suggestion
    depends_on("py-setuptools@:47", when="@:0.6.4", type="build")
```
To fix style (not sure why it didn't work)

2023-04-24 15:04 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-botorch/package.py
> +    depends_on("py-linear-operator@0.3.0:", when="@0.8.3:", type=("build", "run"))
Need to set `ALLOW_LATEST_GPYTORCH_LINOP` env var in order to use newer gpytorch/linear-operator

2023-04-24 16:26 UTC, tldahlgren reviewed
Confirmed the sha256 for all 9 versions.

2023-04-25 12:22 UTC, meyersbs commented on var/spack/repos/builtin/packages/py-ax-platform/package.py
> +    depends_on("py-botorch@0.8.3:", type=("build", "run"))
How should I handle this? A variant to set that flag, defaulting to false?

2023-04-25 13:33 UTC, meyersbs commented
@spackbot fix style

2023-04-25 13:34 UTC, meyersbs commented
@spackbot fix style

2023-04-25 16:40 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ax-platform/package.py
> +    depends_on("py-botorch@0.8.3:", type=("build", "run"))
Nope, just always set it

2023-04-25 17:13 UTC, adamjstewart requested changes

2023-04-25 17:13 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-plotly/package.py
>      depends_on("py-setuptools", type="build")
Missing build dep on jupyterlab

2023-04-25 17:13 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-plotly/package.py
>      depends_on("py-decorator@4.0.6:", when="@:2.2.0", type=("build", "run"))
Missing build/run dep on packaging

2023-04-25 18:08 UTC, adamjstewart requested changes

2023-04-25 18:08 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-plotly/package.py
> +    depends_on("py-jupyterlab@:2.9,3.1:", when="@5.14.1", type="build")
`~=` means the exact opposite of what you think it means:
```suggestion
    depends_on("py-jupyterlab@3", when="@5:", type="build")
```

2023-04-25 18:17 UTC, meyersbs commented
Apparently Monday brain has carried over into Tuesday... Thanks for all of your feedback!

2023-04-25 18:38 UTC, adamjstewart approved these changes

2023-04-26 01:53 UTC, merged