Feature/topiary
LLNL/spack pull request #37157
Opened 2023-04-24 16:41 UTC by snehring

A pipeline

2023-04-25 02:02 UTC, tldahlgren reviewed
Confirmed the version branches, sha256, and commits as well as home pages.

2023-04-25 02:02 UTC, tldahlgren commented on var/spack/repos/builtin/packages/generax/package.py
> +    version("2.0.1", commit="edff1caca0fe3f691c386e4b9a990f391dbdcc60", submodules=True)
Are you sure this is the commit you want as it appears to be associated with `2.0.2` based on the diff (https://github.com/BenoitMorel/GeneRax/commit/edff1caca0fe3f691c386e4b9a990f391dbdcc60)?

This is the corresponding commit that updates that line to `2.0.1`:  https://github.com/BenoitMorel/GeneRax/commit/7d16df4c0125c24df9247a7be68ac51f19d68fee.  While this is the commit associated with the `2.0.1` release: https://github.com/BenoitMorel/GeneRax/commit/0623dae55dd602a60faae63e9991fa8d41782456.

2023-04-25 02:46 UTC, snehring commented
I did a lot of squashing in this mess after debugging some things. It's extremely likely I messed that up. I'll fix it up tomorrow.

2023-04-28 15:10 UTC, adamjstewart requested changes

2023-04-28 15:10 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ete3/package.py
> +    depends_on("py-lxml", type=("build", "run"))
These 3 are optional, not sure if we want to make variants for these or just always require them

2023-04-28 15:10 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-itolapi/package.py
> +    depends_on("py-requests@2.0:3.0", type=("build", "run"))
```suggestion
    depends_on("py-requests@2", type=("build", "run"))
```

2023-04-28 15:10 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-opentree/package.py
> +    depends_on("py-setuptools", type="build")
```suggestion
    depends_on("py-setuptools", type=("build", "run"))
```
Technically it's not used at run-time, but the `setup.py` lists it under `install_requires`, so `pip check` will complain if setuptools isn't found. Might be worth opening a PR to move it to `setup_requires`.

2023-04-28 15:10 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pastml/package.py
> +
Python 3.8+

2023-04-28 15:10 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-topiary/package.py
Let's name this `py-topiary-asr`. There's already a different topiary package on PyPI. Also see https://github.com/harmslab/topiary/blob/86913d42417bf45ca262e7740672c61a3ed85455/setup.py#L41

2023-04-28 15:10 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-topiary/package.py
> +    depends_on("py-numpy", type="run")
```suggestion
    depends_on("py-numpy@:1.21", type="run")
```

2023-04-28 15:10 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-topiary/package.py
> +    depends_on("py-pandas", type="run")
Missing xlrd and openpyxl from requirements.txt

2023-04-28 15:10 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-topiary/package.py
> +    depends_on("py-matplotlib", type="run")
Missing biopython

2023-04-28 15:10 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-topiary/package.py
> +    depends_on("py-mpi4py", type="run")
Where does mpi4py come from? Also, these should all be `type=("build", "run")`

2023-04-28 15:10 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-topiary/package.py
> +    depends_on("raxml-ng@1.1:", type="run")
Might be worth adding a comment to explain where these came from

2023-04-28 15:10 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-topiary/package.py
> +                "topiary/raxml/_raxml.py",
```suggestion
                join_path("topiary", "raxml", "_raxml.py"),
```

2023-04-28 15:29 UTC, snehring commented on var/spack/repos/builtin/packages/py-ete3/package.py
> +    depends_on("py-lxml", type=("build", "run"))
I think I was running into build errors without including these.

2023-04-28 15:32 UTC, snehring commented on var/spack/repos/builtin/packages/py-topiary/package.py
> +    depends_on("py-mpi4py", type="run")
The mpi4py dep isn't documented. There's a couple places in the mpi parts of this that import it iirc, at the very least in https://github.com/harmslab/topiary/blob/main/topiary/_private/mpi/_get_hosts.py

2023-04-28 18:58 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-topiary-asr/package.py
> +    depends_on("py-numpy", type=("build", "run"))
```suggestion
    depends_on("py-numpy@:1.21", type=("build", "run"))
```

2023-04-29 15:22 UTC, adamjstewart approved these changes

2023-04-29 21:52 UTC, merged