py-sacrebleu
LLNL/spack pull request #37159
Opened 2023-04-24 16:45 UTC by Sangu-Mbekelu

2023-04-24 17:05 UTC, Sangu-Mbekelu commented
@spackbot fix style

2023-04-25 20:10 UTC, tldahlgren reviewed
Confirmed the homepage, branch, and version.  Just a couple of minor points, especially the copyright year).

2023-04-25 20:10 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-sacrebleu/package.py
> +# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
```

2023-04-25 20:10 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-sacrebleu/package.py
> +        touch = which("touch")
This line isn't needed.  Every package automatically gets access to Spack's `touch()` along with other commands from https://spack.readthedocs.io/en/latest/llnl.util.html#module-llnl.util.filesystem that do a little extra work.

2023-04-25 20:11 UTC, tldahlgren requested changes
Please fix the ending copyright year.

2023-04-25 21:54 UTC, adamjstewart approved these changes, later dismissed
LGTM once @tldahlgren's changes are made

2023-04-28 03:47 UTC, adamjstewart approved these changes

2023-07-10 19:16 UTC, tldahlgren approved these changes

2023-07-10 19:16 UTC, merged

2023-07-10 19:17 UTC, tldahlgren commented
FWIW. I'm getting an odd error that doesn't appear to be related to the package AFAICT when  I try to install it:

```
$ spack install py-sacrebleu
==> Error: VersionBase('7')
```