Update package.py for totalview for latest release 2023.1.6
LLNL/spack pull request #37167
Opened 2023-04-24 20:41 UTC by elliebinkley

Update package.py for totalview for latest release 2023.1.6
Fix URLS for previous releases that were causing a failure on spack install. 
Update maintainers to include Larry Burley ( elliebinkley)

2023-04-26 17:48 UTC, petertea approved these changes
I've worked with Larry on this and understanding why my previous commit did not seem to work in a new environment.  We found that the URL did not work with a relative name, so adding back the format(os.getcwd()) was in fact necessary.  The changes look good to me.

2023-05-18 21:21 UTC, dshrader approved these changes

2023-05-29 09:32 UTC, alalazo requested changes

2023-05-29 09:32 UTC, alalazo commented on var/spack/repos/builtin/packages/totalview/package.py
> +#
```suggestion
```

2023-05-29 09:32 UTC, alalazo commented on var/spack/repos/builtin/packages/totalview/package.py
> +    maintainers = ["dshrader", "petertea", "elliebinkley"]
Please keep the directive, instead of using a list

2024-02-22 06:54 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2024-02-22 06:54 UTC, closed without merging