r-loo: add v2.6.0
LLNL/spack pull request #37205
Opened 2023-04-26 03:40 UTC by alecbcs

Add r-loo v2.6.0. 
 
**Test Plan:**
Built successfully using `gcc@10.4.0` on Debian 11.

2023-04-26 16:33 UTC, tldahlgren approved these changes
Confirmed the sha256.  Deferring merge decision to @glennpj .

2023-04-27 00:11 UTC, glennpj requested changes

2023-04-27 00:11 UTC, glennpj commented on var/spack/repos/builtin/packages/r-loo/package.py
> +    depends_on("r+X", type=("build", "run"))
Let's leave the `r+X` at the top.

2023-04-27 00:34 UTC, glennpj approved these changes

2023-04-27 00:34 UTC, merged