adding hwloc-gpu variant
LLNL/spack pull request #37266
Opened 2023-04-28 03:39 UTC by MatthewLieber

Adds a variant that by default fixes issues where building on nodes with gpus and then trying to run on nodes with out them will fail.

Thanks to Ron Rahaman @PACE/GaTech for the report

2023-04-28 14:10 UTC, natshineman submitted a review, later dismissed
This should be good to merge.

2023-05-01 13:45 UTC, MatthewLieber commented
Can the checks please be rerun?  It looks like it might be stuck as it has been pending all weekend.

2023-05-10 14:32 UTC, MatthewLieber commented
@alalazo All the checks have passed can we please get this merged in?

2023-05-10 14:41 UTC, alalazo requested changes

2023-05-10 14:41 UTC, alalazo commented on var/spack/repos/builtin/packages/mvapich2/package.py
> +    variant("hwloc-graphics", default=False, description="Enables hwloc graphics")
Can we do:
```suggestion
    variant("hwloc_graphics", default=False, description="Enables hwloc graphics")
```
for consistency with other variants?

2023-05-10 14:41 UTC, alalazo commented on var/spack/repos/builtin/packages/mvapich2/package.py
> +        if "~hwloc-graphics" in self.spec:
Do we need to enable anything explicitly if this variant is active?

2023-05-10 15:09 UTC, MatthewLieber commented on var/spack/repos/builtin/packages/mvapich2/package.py
> +        if "~hwloc-graphics" in self.spec:
Nothing needs to be done explicitly if they activate the variant.

2023-05-10 15:14 UTC, alalazo approved these changes

2023-05-29 11:00 UTC, alalazo commented
@MatthewLieber Can you rebase this PR? It seems stuck in CI and apparently I don't have enough permissions to rebase it myself.

2024-02-22 06:56 UTC, alalazo commented
Closing (the PR seems to have been force pushed in a wrong way, and never fixed)

2024-02-22 06:56 UTC, closed without merging