Bioc updates
LLNL/spack pull request #37297
Opened 2023-04-29 01:57 UTC by glennpj

Update Bioconductor packages for Bioconductor 3.17.

2023-05-02 02:58 UTC, tldahlgren commented
Of the 192 packages/versions, #37090 is required for (fetching) the following new versions:

- r-biocio@1.10.0
- r-biocversion@3.17.1
- r-ggtree@3.8.0
- r-gviz@1.44.0

2023-05-02 03:00 UTC, tldahlgren requested changes
Unless I'm missing something, I think there's one more package that needs to be updated (i.e., `r-ggfun`) in addition to the dependency on the recent `r` package update.

2023-05-02 03:00 UTC, tldahlgren commented on var/spack/repos/builtin/packages/r-ggtree/package.py
> +    depends_on("r-ggfun@0.0.9:", type=("build", "run"), when="@3.8.0:")
@glennpj I think you're missing the update to `r-ggfun` to `0.0.9`.

2023-05-02 16:08 UTC, glennpj commented on var/spack/repos/builtin/packages/r-ggtree/package.py
> +    depends_on("r-ggfun@0.0.9:", type=("build", "run"), when="@3.8.0:")
That is part of #37296.

2023-05-18 19:03 UTC, tldahlgren commented
After updating the branch (via "Update branch" button) to include the required PRs I can confirm all *BUT* `r-aneufinder@1.28.0`.  When I tried to fetch it, I get:

```
spack fetch r-aneufinder@1.28.0 
==> Error: concretization failed for the following reasons:

   1. Cannot satisfy 'r@3.0:'
```

2023-05-23 15:24 UTC, glennpj commented
That is odd. I will look into it.

2023-05-23 16:02 UTC, glennpj commented
The issue was with the `r-ecp` package. The dependency in the DESCRIPTION file is 
> Depends:	R (≥ 3.00), Rcpp

That got propagated to the Spack recipe but `3.00` is not a valid version. The only thing that depends on `r-ecp` is `r-aneufinder`. I committed a fixed `r-ecp` to solve this.

2023-05-23 18:39 UTC, tldahlgren approved these changes
Confirmed I can now fetch the previously "problematic" package version.

2023-05-23 18:40 UTC, merged