spack install --make: shortcut for `depfile`
LLNL/spack pull request #37405
Opened 2023-05-03 13:38 UTC by haampie

`spack install --make` is the equivalent of `spack env depfile -o
Makefile && make -j... -k`.

I just have to figure out how to best forward `install` flags to the
spack invocation in the makefile.

This is a convenient way to get dynamic parallelism across packages instead of
per-package parallelism.

2023-05-03 13:51 UTC, haampie commented
@eugeneswalker this is not _very_ usable given the TODO above, but it's a start

2023-05-03 13:57 UTC, eugeneswalker commented
> @eugeneswalker this is not _very_ usable given the TODO above, but it's a start

Looks great! Will be nice to be able to forward `--cache-only` to make via this invocation!

2023-08-25 22:13 UTC, tgamblin requested changes

2023-08-25 22:13 UTC, tgamblin commented on lib/spack/spack/cmd/install.py
> +        f.write(makefile)
does the makefile have to live here, or can it live in `temp`?

2023-12-12 14:23 UTC, bollig commented
Bumping this. We are seeing errors on the [build runner for Amazon Linux ](https://github.com/spack/gitlab-runners/actions/runs/7172771743/job/19530679568) which uses this patch.

2025-06-15 08:18 UTC, alalazo commented
I guess this is outdated after the recent work on supporting parallel installs?

2025-12-17 08:31 UTC, closed without merging