hdf5: Support MPItrampoline, Clang
LLNL/spack pull request #37439
Opened 2023-05-04 19:52 UTC by eschnett

This addresses the issue in https://github.com/spack/spack/issues/37430, both for HDF5 1.14 and HDF5 1.12. It also corrects a problem found by modern versions of Clang

Closes https://github.com/spack/spack/issues/37430.

2023-05-04 20:48 UTC, hyoklee approved these changes
Thank you for the patch, @eschnett !

I could confirm that patch works: https://github.com/hyoklee/spack/actions/workflows/hdf5_mpi.yml

2023-05-05 13:19 UTC, eschnett commented
@spackbot help

2023-05-05 13:19 UTC, eschnett commented
@spackbot run pipeline

2023-05-05 18:32 UTC, hyoklee approved these changes

2023-05-10 20:22 UTC, hyoklee approved these changes

2023-05-28 06:53 UTC, alalazo requested changes

2023-05-28 06:53 UTC, alalazo commented on var/spack/repos/builtin/packages/hdf5/package.py
> +    patch("mpi.14.patch", when="@1.14:")
Can we add a comment, above each patch directive, to explain briefly what the patch does , why it is needed and where it was taken from?

2024-03-08 05:21 UTC, alalazo commented on var/spack/repos/builtin/packages/hdf5/package.py
> +    patch("mpi.14.patch", when="@1.14:")
@eschnett

2025-04-18 07:45 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2025-04-18 07:45 UTC, closed without merging