py-dotmap
LLNL/spack pull request #37683
Opened 2023-05-15 19:17 UTC by gnericblu

2023-05-30 15:44 UTC, adamjstewart requested changes

2023-05-30 15:44 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-dotmap/package.py
> +    depends_on("py-setuptools", type=("build", "run"))
```suggestion
    depends_on("py-setuptools", type="build")
```
Not needed at run-time

2023-05-30 15:44 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-dotmap/package.py
> +    homepage = "https://pypi.org/project/dotmap/"
If the pypi page is the homepage you don't need to define it, `pypi` will

2024-02-17 22:08 UTC, alecbcs commented
Going to close this PR due to a lack of follow up from review feedback. @gnericblu happy to reopen if you still want to get this merged and have the time to work on it.

2024-02-17 22:08 UTC, closed without merging

2024-02-18 09:00 UTC, adamjstewart commented
Superseded by #42665 anyway