py-jarvis-util: add a new package
LLNL/spack pull request #37729
Opened 2023-05-17 01:49 UTC by hyoklee

Jarvis-util is a Python library which contains various utilities to aid with creating shell scripts within Python. This library contains wrappers for executing shell commands locally, SSH, SCP, MPI, argument parsing,and various other random utilities.

  This package is required for upcoming Hermes 1.0.0 package, which will be released soon.

2023-05-17 21:18 UTC, lukemartinlogan approved these changes

2023-05-17 21:20 UTC, lukemartinlogan approved these changes
This all looks correct.

2023-05-17 21:42 UTC, tldahlgren reviewed
Confirmed the home page and version sha256.  Adding @adamjstewart since this is a new python package.

2023-05-17 21:45 UTC, tldahlgren commented
> This all looks correct.

Great!  I'll take that to also mean you're fine with being a maintainer (https://spack.readthedocs.io/en/latest/packaging_guide.html#maintainers) for the package. 😉

2023-05-17 22:45 UTC, lukemartinlogan commented
> > This all looks correct.
> 
> Great! I'll take that to also mean you're fine with being a maintainer (https://spack.readthedocs.io/en/latest/packaging_guide.html#maintainers) for the package. 😉

Yes! :)

2023-05-18 20:39 UTC, adamjstewart requested changes

2023-05-18 20:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-jarvis-util/package.py
> +    depends_on("py-pyaml")
```suggestion
    depends_on("py-psutil", type=("build", "run"))
    depends_on("py-pyaml", type=("build", "run"))
```

2023-05-18 20:46 UTC, lukemartinlogan submitted a review, later dismissed

2023-05-18 20:54 UTC, adamjstewart approved these changes

2023-05-18 21:28 UTC, merged