py-attrs: add 23.1.0
LLNL/spack pull request #37817
Opened 2023-05-22 09:09 UTC by manuelakuhn

https://github.com/python-attrs/attrs/tree/23.1.0

2023-05-22 16:49 UTC, tldahlgren reviewed
Confirmed the sha256, deferring merge decision to @adamjstewart

2023-05-22 19:39 UTC, adamjstewart requested changes

2023-05-22 19:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-attrs/package.py
> +    depends_on("py-hatch-fancy-pypi-readme", when="@23.1.0:", type="build")
Missing importlib-metadata

2023-05-22 20:58 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-attrs/package.py
> +    depends_on("py-hatch-fancy-pypi-readme", when="@23.1.0:", type="build")
Sorry, overlooked it. Thanks!

2023-05-25 01:21 UTC, adamjstewart approved these changes

2023-05-25 01:21 UTC, merged