tests/upcxx: convert to new stand-alone test process
LLNL/spack pull request #37832
Opened 2023-05-22 19:13 UTC by tldahlgren

Converted package to use the new stand-alone test process.

```
spack  -v test run upcxx
==> Spack test lfdjen76frtsusqwmilcb47h5sazgawm
==> Testing package upcxx-2023.3.0-rmzaksi
==> [2023-05-22-12:11:09.823437] test: test_upcxx_install: checking UPC++ compiler+link for all installed backends
==> [2023-05-22-12:11:09.825698] '/usr/WS1/dahlgren/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/upcxx-2023.3.0-rmzaksi47t4raqazklcvkhrockwcplsl/bin/test-upcxx-install.sh'
========
Testing the UPC++ install at /usr/WS1/dahlgren/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/upcxx-2023.3.0-rmzaksi47t4raqazklcvkhrockwcplsl
========
========
SUCCESS
========
/usr/WS1/dahlgren/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/upcxx-2023.3.0-rmzaksi47t4raqazklcvkhrockwcplsl/bin/upcxx -codemode=debug -threadmode=seq -network=smp test-upcxx-2966910.cpp -o test-upcxx-2966910
/usr/WS1/dahlgren/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/upcxx-2023.3.0-rmzaksi47t4raqazklcvkhrockwcplsl/bin/upcxx -codemode=debug -threadmode=seq -network=udp test-upcxx-2966910.cpp -o test-upcxx-2966910
/usr/WS1/dahlgren/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/upcxx-2023.3.0-rmzaksi47t4raqazklcvkhrockwcplsl/bin/upcxx -codemode=debug -threadmode=seq -network=ibv test-upcxx-2966910.cpp -o test-upcxx-2966910
/usr/WS1/dahlgren/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/upcxx-2023.3.0-rmzaksi47t4raqazklcvkhrockwcplsl/bin/upcxx -codemode=debug -threadmode=par -network=smp test-upcxx-2966910.cpp -o test-upcxx-2966910
/usr/WS1/dahlgren/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/upcxx-2023.3.0-rmzaksi47t4raqazklcvkhrockwcplsl/bin/upcxx -codemode=debug -threadmode=par -network=udp test-upcxx-2966910.cpp -o test-upcxx-2966910
/usr/WS1/dahlgren/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/upcxx-2023.3.0-rmzaksi47t4raqazklcvkhrockwcplsl/bin/upcxx -codemode=debug -threadmode=par -network=ibv test-upcxx-2966910.cpp -o test-upcxx-2966910
/usr/WS1/dahlgren/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/upcxx-2023.3.0-rmzaksi47t4raqazklcvkhrockwcplsl/bin/upcxx -codemode=opt -threadmode=seq -network=smp test-upcxx-2966910.cpp -o test-upcxx-2966910
/usr/WS1/dahlgren/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/upcxx-2023.3.0-rmzaksi47t4raqazklcvkhrockwcplsl/bin/upcxx -codemode=opt -threadmode=seq -network=udp test-upcxx-2966910.cpp -o test-upcxx-2966910
/usr/WS1/dahlgren/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/upcxx-2023.3.0-rmzaksi47t4raqazklcvkhrockwcplsl/bin/upcxx -codemode=opt -threadmode=seq -network=ibv test-upcxx-2966910.cpp -o test-upcxx-2966910
/usr/WS1/dahlgren/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/upcxx-2023.3.0-rmzaksi47t4raqazklcvkhrockwcplsl/bin/upcxx -codemode=opt -threadmode=par -network=smp test-upcxx-2966910.cpp -o test-upcxx-2966910
/usr/WS1/dahlgren/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/upcxx-2023.3.0-rmzaksi47t4raqazklcvkhrockwcplsl/bin/upcxx -codemode=opt -threadmode=par -network=udp test-upcxx-2966910.cpp -o test-upcxx-2966910
/usr/WS1/dahlgren/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/upcxx-2023.3.0-rmzaksi47t4raqazklcvkhrockwcplsl/bin/upcxx -codemode=opt -threadmode=par -network=ibv test-upcxx-2966910.cpp -o test-upcxx-2966910
PASSED: Upcxx::test_upcxx_install
==> [2023-05-22-12:11:33.686322] Completed testing
==> [2023-05-22-12:11:33.686521] 
======================= SUMMARY: upcxx-2023.3.0-rmzaksi ========================
Upcxx::test_upcxx_install .. PASSED
============================= 1 passed of 1 parts ==============================
============================== 1 passed of 1 spec ==============================
```

2023-05-22 22:22 UTC, bonachea commented
Hi @tldahlgren - 

I saw the new test support was added to develop (congrats!)
Thanks for this PR - I plan to carefully test it and review this week.

-D

2023-05-22 22:31 UTC, tldahlgren commented
> Hi @tldahlgren -
> 
> I saw the new test support was added to develop (congrats!) Thanks for this PR - I plan to carefully test it and review this week.
> 
> -D

Thanks Dan.  Looking forward to your feedback on this and the `gasnet` PR.

2023-05-23 02:50 UTC, bonachea requested changes
Made one minor cosmetic request, otherwise LGTM!

2023-05-23 02:50 UTC, bonachea commented on var/spack/repos/builtin/packages/upcxx/package.py
> +        """checking UPC++ compiler+link for all installed backends"""
Minor quibble - UPC++ is a library and does not technically provide a compiler, this string was/is referring to compilation using the UPC++ header files (and subsequent linkage against the libraries).

```suggestion
        """checking UPC++ compile+link for all installed backends"""
```

2023-05-23 22:09 UTC, bonachea approved these changes

2023-05-28 08:43 UTC, alalazo approved these changes

2023-05-28 08:44 UTC, merged