Guard for define in netcdf 4.9.0 and later.
LLNL/spack pull request #37853
Opened 2023-05-23 13:11 UTC by danlipsa

This code is already available in ParaView 5.11.0 so no patching needed there.

2023-05-23 13:12 UTC, danlipsa commented
@kwryankrattiger @vicentebolea Please review

2023-05-23 16:05 UTC, vicentebolea requested changes
proposed change in ver; looks good otherwise. Thanks for the contribution @danlipsa :+1:

2023-05-23 16:05 UTC, vicentebolea commented on var/spack/repos/builtin/packages/paraview/package.py
> +    patch("exodusII-netcdf4.9.0.patch", when="@:5.10.1")
```suggestion
    patch("exodusII-netcdf4.9.0.patch", when="@:5.10.2")
```

This patch did not seem to make it to the 5.10.2 release.

2023-05-23 17:08 UTC, danlipsa commented on var/spack/repos/builtin/packages/paraview/package.py
> +    patch("exodusII-netcdf4.9.0.patch", when="@:5.10.1")
True, I didn't see that version in spack so I did added it. I'll add it.

2023-05-29 20:52 UTC, vicentebolea approved these changes

2023-06-07 13:42 UTC, danlipsa commented
@vicentebolea @kwryankrattiger Lets merge this, if you guys have merge permissions.

2023-06-07 19:18 UTC, kwryankrattiger approved these changes

2023-06-07 19:20 UTC, merged