nwchem: remove -mtune=native flags
LLNL/spack pull request #37892
Opened 2023-05-24 19:01 UTC by zzzoom

Spack injects compiler arch flags sourced from archspec according to the spec's target. NWChem's `makefile.h` overrides some of those flags with `-mtune=native` and `-mcpu=native` so this PR removes them. The PR also turns on verbose mode to show what's being run.

@edoapra please review

2023-05-24 19:13 UTC, edoapra requested changes
This change is adequate only for version 7.0.2 and earlier.
From version 7.2.0, it is better to have the following environment variable setting
```
USE_HWOPT=n
```

2023-05-25 05:00 UTC, zzzoom commented
Fixed

2023-05-25 16:49 UTC, edoapra requested changes
Is USE_HWOPT=n set for 7.2.0 and later?

2023-05-25 18:37 UTC, edoapra commented
This might be the change needed ... is it going to work for versions >=7.2.0 or just for version=7.2.0?
```
--- a/var/spack/repos/builtin/packages/nwchem/package.py
+++ b/var/spack/repos/builtin/packages/nwchem/package.py
@@ -72,6 +72,7 @@ def install(self, spec, prefix):
         )
         if self.spec.satisfies("@7.2.0:"):
             args.extend(["NWCHEM_MODULES=all python gwmol"])
+            args.extend(["USE_HWOPT=n"])
         else:
             args.extend(["NWCHEM_MODULES=all python"])
             # archspec flags are injected through the compiler wrapper
```

2023-05-25 19:02 UTC, zzzoom commented
Oh, sorry, I assumed that it would default to off when unset. Yes, your suggestion should work for future versions.

2023-05-25 19:03 UTC, edoapra submitted a review, later dismissed

2023-05-26 17:45 UTC, zzzoom commented
Also filtering intel's `-xHost` now.

2023-05-26 17:47 UTC, edoapra commented
I would recommend user switching to the last 7.2.0 where all these compiler issue should address by `USE_HWOPT` instead of working with 7.0.2

2023-05-26 18:39 UTC, zzzoom commented
It's mostly documenting my time spent wondering why nwchem 7.0.2 in our spack 0.19 based user environment kept throwing SIGILLs for no apparent reason. Better here than in some obscure knowledge base where nobody else will benefit.

2023-05-26 22:12 UTC, edoapra commented
> It's mostly documenting my time spent wondering why nwchem 7.0.2 in our spack 0.19 based user environment kept throwing SIGILLs for no apparent reason. Better here than in some obscure knowledge base where nobody else will benefit.

That's exactly my point: better to use the latest version 7.2.0 to verify if indeed `USE_HWOPT=n` takes care of anything that could cause `SIGILL` termination.

2023-06-07 01:01 UTC, edoapra commented
@alalazo Could you have a look at this pull request?
Thanks

2023-06-07 07:02 UTC, alalazo approved these changes

2023-06-07 07:02 UTC, merged