py-cutadapt: add 4.4, 4.3, 4.2 versions
LLNL/spack pull request #37929
Opened 2023-05-25 21:02 UTC by A-N-Other

Adding the three latest versions of `py-cutadapt`, excluding 4.2rc1.

4.4 requires `py-dnaio@0.10:`, so have also updated this dependency.

2023-05-25 22:30 UTC, tldahlgren reviewed
Confirmed the version sha256, deferring merge decision to maintainers, esp. @adamjstewart

2023-05-26 22:00 UTC, adamjstewart requested changes

2023-05-26 22:00 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cutadapt/package.py
>      depends_on("py-setuptools-scm@6.2:", type="build", when="@2.0:")
```suggestion
    depends_on("py-setuptools-scm@6.2:+toml", type="build", when="@2.0:")
```

2023-05-26 22:00 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cutadapt/package.py
>      depends_on("py-cython@0.29.20:", type=("build", "run"))
```suggestion
    depends_on("py-cython@0.29.20:", type="build")
```

2023-05-26 22:00 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-dnaio/package.py
>      version("0.3", sha256="47e4449affad0981978fe986684fc0d9c39736f05a157f6cf80e54dae0a92638")
cython is a dependency only at build-time

2023-05-27 19:27 UTC, adamjstewart approved these changes

2023-05-27 19:27 UTC, merged