`py-nvidia-dali`: update versions up to v1.26.0
LLNL/spack pull request #38022
Opened 2023-05-31 12:51 UTC by thomas-bouvier

This is a work in progress as I need some feedback on how we should handle the dependency on `cuda`.

2023-05-31 16:33 UTC, thomas-bouvier commented
I need some guidance on how to handle the dependency on `cuda`. I defined multiple versions for DALI containing either suffix `-cuda110` or `-cuda120`, mapping to `cuda@11` and `cuda@12` respectively. How can I pick the correct dependency? Maybe something like the following:

```python
if "cuda120" in self.version:
    depends_on("cuda@12", type=("build", "run"))
elif "cuda110" in self.version:
    depends_on("cuda@11", type=("build", "run"))
```

Maybe I should instead define two variant for `+cuda11` and `+cuda12`? In that case, how to map the correct `url` in the version, as the latter is also dependent on the platform architecture?

Pinging @adamjstewart for advice. Thanks!

2023-06-01 19:50 UTC, adamjstewart requested changes

2023-06-01 19:50 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-nvidia-dali/package.py
> +            preferred=False,
False is the default, you can remove this line from all versions where it isn't True

2023-06-01 19:50 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-nvidia-dali/package.py
> +    depends_on("cuda@11", when="@1.26.0-cuda110", type=("build", "run"))
I would do a for-loop over versions so that this applies to all versions. Unfortunately there isn't an easier way to do this.

2023-06-01 19:50 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-nvidia-dali/package.py
>      depends_on("python@3.6:3.10", type=("build", "run"))
```suggestion
    depends_on("python@3.6:3.11", when="@1.23:", type=("build", "run"))
    depends_on("python@3.6:3.10", when="@:1.22", type=("build", "run"))
```

2023-06-08 03:52 UTC, adamjstewart approved these changes

2023-06-08 03:52 UTC, merged