Installations: don't set group permissions when they match what is desired
LLNL/spack pull request #38036
Opened 2023-05-31 22:47 UTC by scheibelp

@dvdgomez

When installing a package Spack will (in some cases) attempt to set group permissions on the install prefix even when the configuration does not specify a group.

In a context where setting group permissions is forbidden, this can lead to an error. To avoid the error, skip `chgrp` when the permissions of a created directory match what we would set.

2023-06-24 10:51 UTC, alalazo requested changes
LGTM, but can we add a unit test?

2023-06-30 22:01 UTC, scheibelp commented
> LGTM, but can we add a unit test?

@alalazo thanks for the suggestion, how does the added test look? I was originally thinking of testing `mkdirp` (or even as high up as `install`) but all permissions setting should go through this (and chmod too, but apparently that is not causing a problem in this user's case).

2023-07-05 07:52 UTC, alalazo approved these changes

2023-07-05 07:54 UTC, merged

2023-08-18 12:00 UTC, haampie reviewed
This change is not correct

2023-08-18 12:00 UTC, haampie commented on lib/spack/llnl/util/filesystem.py
> +    if os.stat(path).st_gid == gid:
This change is wrong. Should be `lstat` in case of `not follow_symlinks`.