py-jupyterlab: add 4.0.1 incl. new dependencies
LLNL/spack pull request #38102
Opened 2023-06-03 02:28 UTC by manuelakuhn

https://github.com/jupyterlab/jupyterlab/tree/v4.0.1
(explicit definition of import_modules not needed, all versions build with "--test=root")

https://github.com/jupyterlab/hatch-jupyter-builder/tree/v0.8.3
https://github.com/jupyter-server/jupyter_server/tree/v2.6.0
https://github.com/jupyter-server/jupyter_server_terminals/tree/v0.4.4
(does not build on its own because it would need a dependency on py-jupyter-server which would create a cyclic dependency)
https://github.com/jupyter/jupyter_events/tree/v0.6.3
https://github.com/python-jsonschema/jsonschema/tree/v4.17.3
https://github.com/ypcrts/fqdn/tree/v1.5.1
https://github.com/bolsote/isoduration/tree/20.11.0
https://github.com/naimetti/rfc3339-validator/tree/v0.1.4
https://pypi.org/project/rfc3986-validator/#files
https://github.com/plinss/uri-template/tree/v1.2.0
https://github.com/madzak/python-json-logger/tree/v2.0.7
https://github.com/mkorpela/overrides/tree/7.3.1
https://pypi.org/project/jupyter-lsp/#files
https://github.com/jupyterlab/jupyterlab_server/tree/v2.22.1

2023-06-04 22:46 UTC, adamjstewart requested changes

2023-06-04 22:46 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-python-json-logger/package.py
>      depends_on("py-setuptools")
```suggestion
    depends_on("py-setuptools", type="build")
```

2023-06-04 22:50 UTC, adamjstewart commented
Confirmed that this builds on macOS arm64 and actually runs! Previous versions crashed with no useful error message. Thanks for updating this package!

2023-06-05 09:15 UTC, manuelakuhn commented
Strange for me versions 3 build and run fine.

2023-06-05 18:54 UTC, adamjstewart commented
It was only on macOS arm64.

2023-06-05 18:54 UTC, adamjstewart approved these changes

2023-06-05 18:54 UTC, merged