py-llvmlite: add 0.40.0, update llvm dependency information
LLNL/spack pull request #38171
Opened 2023-06-05 13:35 UTC by A-N-Other

Following on from https://github.com/spack/spack/pull/37949#issuecomment-1568344663, here's a PR updating `py-llvmlite` to `@0.40.0`. As per https://github.com/numba/llvmlite#compatibility, I've updated the `llvm` dependency line to include versions up to `llvm@:14`.

Side note separate to this PR specifically:
`llvm` itself does not build (for me anyway) with `gcc@13`, which is currently 'preferred' for new Spack installs. I've got this going with `gcc@12` in the end. Currently falls over with:
```
     38220    In file included from /opt/software/.spack/build/root/spack-stage-llvm-14.0.6-hvq7mn3lxvoxtpowrv7753pgpelngowa/spack-src/openmp/libomptarget/plugins/amdgpu/dynamic_hs
              a/hsa.cpp:14:
  >> 38221    /opt/software/.spack/build/root/spack-stage-llvm-14.0.6-hvq7mn3lxvoxtpowrv7753pgpelngowa/spack-src/openmp/libomptarget/include/Debug.h:75:24: error: use of undeclared
               identifier 'getenv'
     38222        if (char *EnvStr = getenv("LIBOMPTARGET_INFO"))
     38223                           ^
  >> 38224    /opt/software/.spack/build/root/spack-stage-llvm-14.0.6-hvq7mn3lxvoxtpowrv7753pgpelngowa/spack-src/openmp/libomptarget/include/Debug.h:76:28: error: no member named '
              stoi' in namespace 'std'
     38225          InfoLevel.store(std::stoi(EnvStr));
     38226                          ~~~~~^
  >> 38227    /opt/software/.spack/build/root/spack-stage-llvm-14.0.6-hvq7mn3lxvoxtpowrv7753pgpelngowa/spack-src/openmp/libomptarget/include/Debug.h:89:24: error: use of undeclared
               identifier 'getenv'
     38228        if (char *EnvStr = getenv("LIBOMPTARGET_DEBUG"))
     38229                           ^
  >> 38230    /opt/software/.spack/build/root/spack-stage-llvm-14.0.6-hvq7mn3lxvoxtpowrv7753pgpelngowa/spack-src/openmp/libomptarget/include/Debug.h:90:25: error: no member named '
              stoi' in namespace 'std'
     38231          DebugLevel = std::stoi(EnvStr);
     38232                       ~~~~~^
     38233    4 errors generated.
```

2023-06-05 16:26 UTC, tldahlgren reviewed
Confirmed the sha256, deferring to @adamjstewart and or @pradyunsg for merge decision.

2023-06-05 16:29 UTC, tldahlgren commented
Looks like there are problems building the package for three CI stacks (e.g., https://gitlab.spack.io/spack/spack/-/jobs/7309197).

2023-06-05 16:47 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-llvmlite/package.py
>      depends_on("python@3.7:3.10", type=("build", "run"), when="@0.38.0:")
0.40.0 also introduces [python 3.11 support](https://github.com/numba/llvmlite/pull/869), which wasn't there for 0.39:
```suggestion
    depends_on("python@3.8:3.11", type=("build", "run"), when="@0.40.0:")
    depends_on("python@3.7:3.10", type=("build", "run"), when="@0.38.0:0.39")
```

2023-06-05 16:57 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-llvmlite/package.py
> +    depends_on("llvm@11.0:14~flang", when="@0.37.0:")
The table at https://github.com/numba/llvmlite#compatibility just seems incorrect. LLVM 12-14 support was only [added](https://github.com/numba/llvmlite/commit/7b977a6ff830356dba253ba9b18a070f79df75b7) in 0.40.
```suggestion
    depends_on("llvm@11.0:14~flang", when="@0.40.0:")
    depends_on("llvm@11.0:11~flang", when="@0.37.0:0.39")
```

2023-06-05 17:08 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-llvmlite/package.py
> +    depends_on("llvm@11.0:14~flang", when="@0.37.0:")
Reported https://github.com/numba/llvmlite/issues/956

2023-06-05 21:53 UTC, wdconinc commented
Confirmed that with these changes I can build `py-llvmlite` against `llvm@14` with `gcc@12`:
```console
==> In environment py-llvmlite
==> Root specs
py-pandas@2.0.2

==> Installed packages
-- linux-ubuntu23.04-skylake / gcc@12.2.0 -----------------------
llvm@14.0.6  py-llvmlite@0.40.0
==> 2 installed packages
```

@A-N-Other I'd remove the "Side note" in the PR description and file it as a bug report instead. Here it won't see any resolution, and it might even look as though the PR isn't fully functional yet.

2023-06-06 14:50 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-llvmlite/package.py
> +    depends_on("llvm@11.0:14~flang", when="@0.37.0:")
Addressed in https://github.com/numba/llvmlite/pull/958, i.e. only LLVM 11 or 14 are supported for 0.40 though 12 and 13 may work. This will require another small modification to the dependencies to exclude LLVM 12 and 13.

2023-06-06 14:58 UTC, wdconinc requested changes

2023-06-06 14:58 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-llvmlite/package.py
> +    depends_on("llvm@11.0:11~flang", when="@0.37.0:0.39")
```suggestion
    depends_on("llvm@11,14~flang", when="@0.40.0:")
    depends_on("llvm@11~flang", when="@0.37.0:0.39")
```

2023-06-06 15:34 UTC, wdconinc approved these changes
Looks good to me know.

2023-06-08 03:42 UTC, adamjstewart requested changes

2023-06-08 03:42 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-llvmlite/package.py
> +    depends_on("llvm@11,14~flang", when="@0.40.0:")
A lot of the stuff below can be simplified (`@9.0.0:9.0` is equivalent to `@9.0`, only need to add the `~flang` constraint once) but we should at least fix this:
```suggestion
    depends_on("llvm@14:~flang", when="@0.41:")
    depends_on("llvm@11:14~flang", when="@0.40")
```

2023-06-08 21:10 UTC, adamjstewart approved these changes

2023-06-08 21:10 UTC, merged