[py-clean-text] added version 0.6.0
LLNL/spack pull request #38271
Opened 2023-06-08 19:32 UTC by qwertos

2023-06-09 00:19 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-clean-text/package.py
> +    depends_on("python@3.7:", type=("build", "run"), when="@0.6.0:")
Spack only supports python@3.7: anyway, so these two lines can be removed.

2023-06-09 00:19 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-clean-text/package.py
> +    depends_on("py-emoji@1.0:1", type=("build", "run"), when="@0.6.0:")
Can you please switch `type` and `when`? Also This can be shortened to
```suggestion
    depends_on("py-emoji@1", when="@0.6:", type=("build", "run"))
```

2023-06-09 00:19 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-clean-text/package.py
> +    depends_on("py-ftfy@6.0:6", type=("build", "run"))
This also can be shortened to
```suggestion
    depends_on("py-ftfy@6", type=("build", "run"))
```

2023-06-09 17:14 UTC, adamjstewart requested changes
Other suggestions are optional, setuptools isn't 😃

2023-06-09 17:14 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-clean-text/package.py
>      depends_on("py-setuptools", type="build")
Setuptools isn't required. It's only used if you run the setup.py file. Spack instead runs pip which directly invokes poetry based on the pyproject.toml file, it never runs setup.py.

2023-06-12 10:03 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-clean-text/package.py
> +    depends_on("python@3.7:", type=("build", "run"), when="@0.6.0:")
correction here on my side: spack supports `python@3.6:` (although for python we only support `python@3.7:`). So you can remove the python@3.6 line if you want.

2023-06-15 16:47 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-clean-text/package.py
> +    depends_on("python@3.7:", type=("build", "run"), when="@0.6.0:")
You could remove both, this isn't a dependency of any Spack style dependencies.

2023-08-07 23:52 UTC, adamjstewart approved these changes

2023-08-07 23:52 UTC, merged