CMake Builder: Filter defines for posix paths
LLNL/spack pull request #38389
Opened 2023-06-14 14:39 UTC by johnwparent

CMake requires that posix paths be provided on the command line. This presents an issue on Windows as Windows like paths can easily slip into a CMake define through attributes like `.libs` or `.directories` or `.prefix`.
Handling this from the package recipes would place a burden on all users to have to consider this Windows oddity and would generally make packages less readable/easy to develop.
Instead we can handle this from the CMake builder class.
If a definition is a valid path, we format it as a posix path. Additionally, we now inform CMake that such attributes are in fact paths instead of the current behavior of defaulting to strings.

2023-06-14 14:39 UTC, johnwparent commented
@jpopelar this is the PR I had mentioned the other day.

2023-07-04 10:28 UTC, haampie commented on lib/spack/llnl/util/filesystem.py
> +    ret = True
Please don't do this... use `return ...`.

2023-07-04 10:30 UTC, haampie commented on lib/spack/spack/build_systems/cmake.py
> +        def is_cmake_bool(value):
Why are you changing this in this PR?

2023-07-04 10:35 UTC, haampie commented
This is the wrong approach imho, cause you're forcing an interpretation on values, which may not always be correct, and if it's not correct, there is no convenient workaround.

Generally I feel like all these Windows PRs are ad-hoc changes that slowly but steadily increase the cyclomatic complexity, which is not desirable...

Why don't you implement it like we handle booleans? Check whether the value is a path type. Then fix issues at the root where strings are passed instead of paths.

2023-07-04 10:36 UTC, haampie requested changes
See above.

2023-07-04 17:06 UTC, johnwparent commented
> This is the wrong approach imho, cause you're forcing an interpretation on values, which may not always be correct, and if it's not correct, there is no convenient workaround.


> Generally I feel like all these Windows PRs are ad-hoc changes that slowly but steadily increase the cyclomatic complexity, which is not desirable...

I don't find this comment to be constructive or actionable. If you have a problem with Windows development at large, this is not the correct place to air grievances unrelated to this PR. If you'd like to have a larger, productive discussion about Spack on Windows development, feel free to reach out me directly or use the maintainers, or even better the Spack on Windows channel on Slack.

I'll note that a change being ad-hoc does not exclude it from also being correct, workable, and needed due to the various intricacies of introducing support for a platform that is entirely different from others, which all share the common unix ancestor, into a codebase that in many places, just naively assumes posix. This Pr is of that type. While you may not agree with the way I go about checking whether a passed in string is posix (which we can discuss), this fix is necessary for Windows, and regardless of our path modeling in Spack, the endpoints where Spack shells out to other utils/the system are _exactly_ where this needs to be handled.

> Why don't you implement it like we handle booleans? Check whether the value is a path type. Then fix issues at the root where strings are passed instead of path objects.

Because that would effectively be a no-op. Exactly 0 packages import pathlib, so checking for a `Path` type would not solve the problem unless we refactored every single CMake packages AND enforced that all future CMake packages only use pathlib. 
I can see where, if this check was wrong, and we thought a vanilla string was a path type, calling it a path in CMake would be wrong, wheras the reverse is not true. Simply having pathlib `as_posix` a non path is a no-op for such strings, and in the cases that it isn't (there is a backslash), those paths should not be passed to CMake as is anyway.

2023-07-05 08:05 UTC, haampie commented
> If you'd like to have a larger, productive discussion about Spack on Windows development

I think this would be good. I agree the PR is not the place to discuss that, at the same time I don't know where else to express my concerns...

> Exactly 0 packages import pathlib

```
>>> type(spec.prefix)
spack.util.prefix.Prefix
```

This is used a lot.

```
>>> type(spec.package.libs.directories[0])
str
```

This could return a path object, similarly for headers.

Wouldn't that capture the majority of the cases?

2025-09-04 20:09 UTC, closed without merging