REGALE library package
LLNL/spack pull request #38444
Opened 2023-06-16 15:24 UTC by danielecesarini

This PR contains a package for the REGALE library

2023-06-26 11:22 UTC, alalazo requested changes

2023-06-26 11:22 UTC, alalazo commented on var/spack/repos/builtin/packages/regale/package.py
> +        args = [arg for arg in args if arg]
Why is this needed? Can't we just:
```suggestion
```
?

2023-06-26 11:22 UTC, alalazo commented on var/spack/repos/builtin/packages/regale/package.py
> +        args += [self.define_from_variant("BUILD_SHARED_LIBS", "shared")]
We can return a list literal for better readability

2023-07-06 10:42 UTC, danielecesarini commented on var/spack/repos/builtin/packages/regale/package.py
> +        args += [self.define_from_variant("BUILD_SHARED_LIBS", "shared")]
done

2023-07-12 08:00 UTC, danielecesarini commented
@alalazo if you are able to merge this PR by the end of today would be great (if the code is ok). Thanks

2023-07-12 08:21 UTC, alalazo approved these changes

2023-07-12 08:21 UTC, merged