A fix for packages/the-silver-searcher build errors against gcc@10 and newer
LLNL/spack pull request #38506
Opened 2023-06-21 12:57 UTC by mkszuba

See Issue #25664 . Technically speaking this could happen with older gcc versions too were -fno-common included in CFLAGS, however gcc-10 this is the default.

The patch may or may not apply cleanly to older silversearcher versions, I haven't checked.

2023-06-21 13:00 UTC, mkszuba commented
FYI, while I would in general be happy to maintain Spack packages unfortunately I no longer use GitHub unless I really have to so it isn't presently possible.

2024-11-27 10:25 UTC, alalazo requested changes
Apologies for the late review, let me know if you're still interested in this PR.

2024-11-27 10:25 UTC, alalazo commented on var/spack/repos/builtin/packages/the-silver-searcher/package.py
> +    patch("fno-common.patch", when="@2.2.0")
Can you add a brief comment above the `patch` directive explaining:
1. What is the effect of the patch
2. Why it is needed
3. Where it was taken from

?

2025-06-15 08:27 UTC, closed without merging

2025-06-15 08:27 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen at / migrate to https://github.com/spack/spack-packages if you want to continue work on this.