Handle cc optimization flags explicitly
LLNL/spack pull request #38538
Opened 2023-06-23 14:53 UTC by snehring

Also allows the package specified -O flag to win over user flag in specific situation.

I noticed in #38517 that the ordering of compiler flags changed as a result of #37376 causing (at the very least) apptainer to fail to install when user provided cflags included -O2. Beforehand the user cflags would appear pretty early in the gcc invocation emitted by the cc wrapper, and package specified cflags would be near the end, leading to the package provided cflags overriding the user provided ones. 

Obviously this isn't what spack users intend in all cases, hence the change. However, some packages do seem to require their specified flags to compile, apptainer being one of them. There are parts of apptainer that need -O0 to compile correctly otherwise the application fails to compile.

This PR adds a case for -O* in the argument parsing and a condition where if -O0 is specified by the package we let it win out vs the user provided optimization flag.

I'm not married to this implementation, the best way to handle this might be disregarding user provided cflags as a package level, but as it stands this does break some unknown number of packages.

I'm going to make this a draft PR, because I'm not that familiar with the cc wrapper or convinced this is the correct place to fix it necessarily.

Fixes #38517

2023-06-23 15:18 UTC, snehring commented
Unit test'll need fixed at least due to the argument shuffling around

2023-06-23 21:42 UTC, snehring commented
@spackbot re-run pipeline

2023-06-23 23:00 UTC, becker33 requested changes
We should not be ignoring user flags without raising an error

2023-06-23 23:26 UTC, tgamblin commented
@snehring have you seen issues like this with other packages, or is this *specifically* a thing with `-O0` and `apptainer`?  I'm curious whether we want to just add an option (or a special flag handler) on the package that allows this to be overridden on a per-package basis.

2023-06-23 23:36 UTC, snehring commented
@tgamblin apptainer is all I noticed so far. I'm guessing it's something in the seccomp go stuff, but it's pretty difficult to muddle through this build process. I imagine the number of packages is small if more than apptainer. It's an edge case for sure.

2023-06-27 17:54 UTC, snehring commented
Well, not specifically -O0, but soapdenovo2 fails to install with anything other than -O3, which was silently overridden previously.

2023-06-27 19:01 UTC, bramoore commented
There are a number of other packages that mix and match optimization levels within a build.  As examples: WRF and SuperLU both have variations of a "NOOPT" set of flags that get used to build certain files without optimization.

2023-06-30 10:41 UTC, haampie commented
Another example is libgcrypt which requires `-O0`

See for example

https://github.com/torvalds/linux/blob/e55e5df193d247a38a5e1ac65a5316a0adcc22fa/crypto/jitterentropy.c#L53-L55

That can usually be solved by passing user flags to the *build system* instead of the compiler wrapper. That's what I did in #35135.

2023-07-11 15:32 UTC, snehring commented
Yeah, that all makes sense. I'll address the two issues I've found so far at the package level.

2023-07-11 15:32 UTC, closed without merging