fairmq: Add v1.7.0
LLNL/spack pull request #38550
Opened 2023-06-26 12:51 UTC by dennisklein

2023-06-26 12:57 UTC, alalazo requested changes
We can use a conditional variant in this case

2023-06-26 12:57 UTC, alalazo commented on var/spack/repos/builtin/packages/fairmq/package.py
> +    variant("autobind", default=True, description="Override the channel autoBind default")
```suggestion
    variant("autobind", default=True, when="@1.7:", description="Override the channel autoBind default")
```

2023-06-26 12:57 UTC, alalazo commented on var/spack/repos/builtin/packages/fairmq/package.py
> +
```suggestion
```

2023-06-26 13:27 UTC, dennisklein commented on var/spack/repos/builtin/packages/fairmq/package.py
> +    variant("autobind", default=True, description="Override the channel autoBind default")
cool, thx for the hint! done

2023-06-26 13:29 UTC, alalazo approved these changes

2023-06-27 09:18 UTC, ChristianTackeGSI approved these changes

2023-06-27 12:19 UTC, merged