util-linux: add v2.39.1, fix macOS build
LLNL/spack pull request #38677
Opened 2023-07-01 20:31 UTC by adamjstewart

Flags from https://github.com/Homebrew/homebrew-core/blob/fa810a0920918f77b50dfa233e92df6a762c2937/Formula/util-linux.rb

2023-07-01 21:09 UTC, adamjstewart commented
@spackbot fix style

2023-07-03 07:47 UTC, haampie requested changes

2023-07-03 07:47 UTC, haampie commented on var/spack/repos/builtin/packages/util-linux/package.py
> +                    "--enable-libuuid",
It's `--disable-libuuid` earlier. Drop this?
```suggestion
```

2023-07-03 21:33 UTC, adamjstewart commented
@spackbot fix style

2023-07-04 08:47 UTC, haampie approved these changes

2023-07-04 08:47 UTC, merged