`spack deconcretize` command
LLNL/spack pull request #38803
Opened 2023-07-09 18:21 UTC by becker33

`spack concretize` concretizes only the root specs that are not concrete in the environment.

`spack concretize -f` eliminates all cached concretization data and reconcretizes the entire environment.

with this PR, `spack deconcretize foo` will eliminate cached concretization data for `foo`. This will allow users greater control over changes to their environments without requiring the environment to remain perfectly static.

The structure of the `spack deconcretize` command is modeled after the `uninstall` command.

2023-07-09 19:17 UTC, alecbcs commented
With the addition of `deconcretize`, I wonder if we shouldn't stick both `concretize` and `deconcretize` under `spack env` as sub commands.  I think doing so will help with users more intuitively understand the commands and how they apply to Spack environments as opposed to environment-less installations.

2023-11-07 07:59 UTC, tgamblin requested changes

2023-11-07 07:59 UTC, tgamblin commented on lib/spack/spack/cmd/deconcretize.py
> +        " will be ignored",
This wraps around on an 80-col terminal 

```suggestion
        help="deconcretize only specific environment roots",
```

2023-11-07 07:59 UTC, tgamblin commented on lib/spack/spack/cmd/deconcretize.py
> +def get_deconcretize_list(args, specs, env):
doctoring should say something about this returning a list of *roots* to deconcretize.  Also type hints would be nice here... 

```suggestion
def get_deconcretize_list(
    args: argparse.Namespace,
    specs: List[spack.spec.Spec],
    env: Environment
) -> List[spack.spec.Spec]:
```

2023-11-07 07:59 UTC, tgamblin commented on lib/spack/spack/cmd/deconcretize.py
> +            to_deconc = [e for e in env_specs if any(d.satisfies(s) for d in e.traverse())]
maybe a comment saying that we find any root that depends on matching specs?

2023-11-07 07:59 UTC, tgamblin commented on lib/spack/spack/environment/environment.py
>          # spec has to be a root of the environment
can these be made into a docstring?

2023-11-07 07:59 UTC, tgamblin commented on lib/spack/spack/environment/environment.py
> +                del self.concretized_user_specs[index]
This isn't correct, right? Each `del` invalidates later indices b/c it modifies the list... is there a test for deconcretizing something with two concrete matches?

```suggestion
            filtered = [
                spec, h
                for spec, h in zip(self.concretized_user_specs, self.concretized_order)
                if h != dag_hash
            ]
            self.concretized_user_specs, self.concretized_order = zip(*filtered)
```

2023-11-10 22:49 UTC, tgamblin approved these changes

2023-11-10 22:55 UTC, merged