Fix cdash reporter time stamps (#38818).
LLNL/spack pull request #38825
Opened 2023-07-10 18:18 UTC by vbrunini

The cdash reporter is created before packages are installed so save the starttime then instead of the endtime.

2023-12-05 16:11 UTC, zackgalbreath submitted a review, later dismissed

2023-12-05 19:10 UTC, tldahlgren reviewed
Line 272 needs to be changed to`testing["endtime"] = self.endtime`

2023-12-05 19:13 UTC, tldahlgren requested changes
Weird.  I thought stand-alone tests were working at one point but haven't checked the history enough to see what happened.

The end time for stand-alone testing also needs to be properly logged for the cdash report.

2023-12-06 01:53 UTC, tldahlgren commented
> Line 272 needs to be changed to`testing["endtime"] = self.endtime`

@vbrunini Would you prefer I do this in a separate PR?

2023-12-06 21:11 UTC, psakievich commented
@tldahlgren @vbrunini is out for a few weeks on leave but I'm sure he's fine with it. Let me see if I can make the change to the PR.

2023-12-07 02:19 UTC, psakievich commented
@tldahlgren I don't have push access to this branch. If you can make the change and push feel free to.  I'm not a full maintainer so you may have access even though I don't.

2023-12-07 18:36 UTC, tldahlgren approved these changes

2023-12-07 19:32 UTC, merged

2023-12-07 19:37 UTC, tldahlgren commented
Rats.  I forgot to disable auto merge.

2023-12-07 19:52 UTC, tldahlgren commented
@psakievich @zackgalbreath Is the revert or a PR with a 1-line fix better?

2023-12-07 19:54 UTC, psakievich commented
1-line fix is probably my preference. the revert will have to add two extra commits to the git history

2023-12-07 20:12 UTC, tldahlgren commented
> 1-line fix is probably my preference. the revert will have to add two extra commits to the git history

Looks a bit too challenging to try to create a PR that cherry picks Victor's commit plus the endtime changes without a revert.  I definitely don't want to lose the history of his change/commit.  By adding this there are two extra commits instead of one but IMO it's more important to make sure he gets credit for his commit.