DLA-Future: ensure umpire~cuda~rocm when ~cuda~rocm
LLNL/spack pull request #38835
Opened 2023-07-11 09:44 UTC by RMeli

Ensure `umpire~cuda~rocm` is used when `~cuda~rocm`.

Related to https://github.com/LLNL/Umpire/pull/827.

2023-07-11 11:28 UTC, RMeli commented on var/spack/repos/builtin/packages/dla-future/package.py
> +    depends_on("umpire~examples~cuda~rocm", when="~cuda~rocm")
```suggestion
    depends_on("umpire~examples)
    depends_on("umpire~cuda~rocm", when="~cuda~rocm")
```

2023-07-11 12:54 UTC, rasolca requested changes

2023-07-11 12:54 UTC, rasolca commented on var/spack/repos/builtin/packages/dla-future/package.py
> +    depends_on("umpire~cuda~rocm", when="~cuda~rocm")
```suggestion
    depends_on("umpire~cuda", when="~cuda")
    depends_on("umpire~rocm", when="~rocm")
```

2023-07-12 06:28 UTC, albestro approved these changes

2023-07-12 07:11 UTC, merged