adios2: add aws variant
LLNL/spack pull request #38857
Opened 2023-07-11 22:07 UTC by vicentebolea

This was added at ADIOS2 2.9.0

2023-07-12 01:01 UTC, tldahlgren requested changes
See previous comment about the when argument.

2023-07-12 01:01 UTC, tldahlgren commented on var/spack/repos/builtin/packages/adios2/package.py
> +    )
Given the PR description it sounds like you probably want to add `when="@2.9:",` argument to the variant.

2023-07-12 18:14 UTC, tldahlgren approved these changes

2023-07-12 18:14 UTC, merged

2023-08-19 02:51 UTC, ax3l commented
Huh, that's cool!