lm-sensors: respect compiler choice
LLNL/spack pull request #38890
Opened 2023-07-14 05:27 UTC by boomanaiden154

Currently lm-sensors defaults to the compiler specified in the Makefile (gcc) rather than the one specified in the spec. This patch appends the CC flag to the make invocation with the spec compiler to fix this behavior.

2023-07-14 13:06 UTC, G-Ragghianti commented
Hi, thanks for catching this.  I have tested your patch, and it does indeed affect the compiler that is used, but I've so far been unable to get it to build using intel@2021 or or to run correctly using oneapi@2023 compilers.  I also found that the ETCDIR needs to be passed to "make" in the build stage or else it will try to read from /etc/sensors3.conf.  Have you been able to get "sensors" to run using another compiler?

2023-07-14 20:25 UTC, boomanaiden154 commented
It worked fine for me build with clang 16 and I'm not seeing any issues with a missing `/etc/sensors3.conf`. Maybe we need to add in some `conflicts()` or `requires()` in the build to specify what compilers work?

2023-07-26 14:32 UTC, haampie requested changes

2023-07-26 14:32 UTC, haampie commented on var/spack/repos/builtin/packages/lm-sensors/package.py
> +        targets.append("CC={0}".format(self.compiler.cc))
```suggestion
        targets.append("CC={0}".format(spack_cc))
```

Sorry for the late review, but you wanna use the (awkward) spack_cc global, which points to the compiler wrapper, whereas `self.compiler.cc` points to the underlying compiler.

2023-07-27 06:08 UTC, haampie approved these changes

2023-07-27 10:13 UTC, G-Ragghianti approved these changes

2023-07-27 17:58 UTC, merged