drop redundant rpaths post install
LLNL/spack pull request #38976
Opened 2023-07-18 20:06 UTC by haampie

In particual this should automatically drop redundant rpaths in `patchelf`

2023-07-18 20:17 UTC, haampie commented
@spackbot rebuild everything

2023-07-18 21:12 UTC, haampie commented
@spackbot run pipeline

2023-07-18 21:20 UTC, haampie commented
@spackbot rebuild everything

2023-07-19 08:28 UTC, alalazo requested changes
LGTM. Only minor requests

2023-07-19 08:28 UTC, alalazo commented on lib/spack/spack/hooks/drop_redundant_rpaths.py
> +def should_keep(p: bytes):
Can we use slightly more readable variable names:
```suggestion
def should_keep(path: bytes):
```
?

2023-07-19 08:28 UTC, alalazo commented on lib/spack/spack/hooks/drop_redundant_rpaths.py
> +    Returns True if the file was modified, False otherwise."""
Docstring is outdated. The function returns a tuple

2023-07-19 08:28 UTC, alalazo commented on lib/spack/spack/hooks/drop_redundant_rpaths.py
> +def _drop_redundant_rpaths(f) -> Optional[Tuple[bytes, bytes]]:
```suggestion
def _drop_redundant_rpaths(file: IO) -> Optional[Tuple[bytes, bytes]]:
```

2023-07-19 08:28 UTC, alalazo commented on lib/spack/spack/hooks/drop_redundant_rpaths.py
> +def drop_redundant_rpaths(path: str) -> Optional[Tuple[bytes, bytes]]:
Missing docstring

2023-07-19 08:28 UTC, alalazo commented on lib/spack/spack/hooks/drop_redundant_rpaths.py
> +            tty.debug(f"Patched rpath in {rel_path} from {old!r} to {new!r}")
:+1:

2023-07-19 08:43 UTC, haampie commented on lib/spack/spack/hooks/drop_redundant_rpaths.py
> +def _drop_redundant_rpaths(f) -> Optional[Tuple[bytes, bytes]]:
Here I'd just stick to `f`, we use `with open(...) as f` everywhere, and `file` is easily confused with "path to file"

2023-07-19 08:46 UTC, alalazo submitted a review, later dismissed

2023-07-19 08:48 UTC, alalazo approved these changes

2023-07-19 09:11 UTC, haampie commented
Surprisingly, the full rebuild was :heavy_check_mark:

2023-07-19 09:48 UTC, merged