py-pytest-html: Add version 3.2.0
LLNL/spack pull request #38989
Opened 2023-07-19 12:19 UTC by Jordan474

Add py-pytest-html 3.2.0.

Also add a conflict directive to avoid [an incompatibility](https://github.com/pytest-dev/pytest-html/issues/553) between `py-pytest@3.1.1` and newer `py-pytest@7.2.0:`. And add a test to cover this issue.

Before this patch you'd get:

```console
$ spack --version
0.21.0.dev0 (a99eaa954150778624f23459bafd49ce0397b099)
$ spack load py-pytest-html
$ python3 -m pytest --version
Traceback (most recent call last):
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/python-3.10.12-oosqvl7zhzincpummxpzn2d2gqxt34xg/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/python-3.10.12-oosqvl7zhzincpummxpzn2d2gqxt34xg/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/py-pytest-7.3.2-cexmvpxyecfhjcpjrackdys2ieeysthw/lib/python3.10/site-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/py-pytest-7.3.2-cexmvpxyecfhjcpjrackdys2ieeysthw/lib/python3.10/site-packages/_pytest/config/__init__.py", line 189, in console_main
    code = main()
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/py-pytest-7.3.2-cexmvpxyecfhjcpjrackdys2ieeysthw/lib/python3.10/site-packages/_pytest/config/__init__.py", line 147, in main
    config = _prepareconfig(args, plugins)
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/py-pytest-7.3.2-cexmvpxyecfhjcpjrackdys2ieeysthw/lib/python3.10/site-packages/_pytest/config/__init__.py", line 328, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/py-pluggy-1.0.0-bkdui37d6joaajjxa24vsksyfwrrublp/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/py-pluggy-1.0.0-bkdui37d6joaajjxa24vsksyfwrrublp/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/py-pluggy-1.0.0-bkdui37d6joaajjxa24vsksyfwrrublp/lib/python3.10/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/py-pytest-7.3.2-cexmvpxyecfhjcpjrackdys2ieeysthw/lib/python3.10/site-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/py-pluggy-1.0.0-bkdui37d6joaajjxa24vsksyfwrrublp/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/py-pluggy-1.0.0-bkdui37d6joaajjxa24vsksyfwrrublp/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/py-pytest-7.3.2-cexmvpxyecfhjcpjrackdys2ieeysthw/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1077, in pytest_cmdline_parse
    self.parse(args)
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/py-pytest-7.3.2-cexmvpxyecfhjcpjrackdys2ieeysthw/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1366, in parse
    self._preparse(args, addopts=addopts)
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/py-pytest-7.3.2-cexmvpxyecfhjcpjrackdys2ieeysthw/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1249, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/py-pluggy-1.0.0-bkdui37d6joaajjxa24vsksyfwrrublp/lib/python3.10/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/python-3.10.12-oosqvl7zhzincpummxpzn2d2gqxt34xg/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/python-3.10.12-oosqvl7zhzincpummxpzn2d2gqxt34xg/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/py-pytest-7.3.2-cexmvpxyecfhjcpjrackdys2ieeysthw/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/.../spack/linux-ubuntu22.04-skylake/gcc-11.3.0/py-pytest-html-3.1.1-hhlwraizrwicneboermmg6ft7p37544k/lib/python3.10/site-packages/pytest_html/plugin.py", line 22, in <module>
    from py.xml import html
ModuleNotFoundError: No module named 'py.xml'; 'py' is not a package
```

2023-07-19 12:48 UTC, Jordan474 commented
EDIT: The `conflicts` directive did not fix all version combinations, the addition of the `py-py` dependency seems to work better.

2023-07-19 20:25 UTC, tldahlgren reviewed
Confirmed the version sha256.

2023-07-20 16:44 UTC, adamjstewart requested changes

2023-07-20 16:44 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pytest-html/package.py
>      depends_on("py-setuptools-scm", type="build")
Build deps need to be updated:
```toml
requires = [
  "setuptools >= 42",
  "setuptools_scm[toml] >= 3.5.0",
  "setuptools_scm_git_archive >= 1.1",
  "wheel >= 0.33.6",
]
```

2023-07-20 16:44 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pytest-html/package.py
> +    depends_on("py-py@1.8.2:", when="^py-pytest@7.2.0:", type=("build", "run"))
```suggestion
    depends_on("py-py@1.8.2:", type=("build", "run"))
```
I would just make this unconditional, that's how it's listed in `setup.py`

2023-07-21 08:59 UTC, Jordan474 commented
I think there is something shady going on with dependency ordering.

First, there is a python module name collision between `import py` as `py.py` in `py-pytest` and, `import py.xml` as `py/{xml.py,__init__.py}` in `py-py`. Not great, but if  `py-py` is in `PYTHONPATH` before `pytest`, this seems ok.

But then, I don't understand Spack's dependency ordering:
- sometimes depending on if you add or remove the `when` in `depends_on("py-py@1.8.2:", when="^py-pytest@7.2.0:", type=("build", "run"))`, you get different `PYTHONPATH` order, consistently
- sometimes the order changes between `spack install --fresh py-pytest-html` and `spack install --fresh py-pytest-html ^py-pytest@7.3.2` maybe inconsistently 

So I still get the `ModuleNotFoundError: No module named 'py.xml'; 'py' is not a package` error from time to time, but I cannot find what causes the bad order, or how to control it.

2023-07-21 09:37 UTC, Jordan474 commented
I didn't expect this fix to go down a rabbit hole...

If there is no way to control PYTHONPATH order, I'm beginning to think it is safer to constrain to pytest@:7.1 [pending pytest-html@4.0.0](https://github.com/pytest-dev/pytest-html/pull/555#issuecomment-1577157303).

Maybe add 4.0.0rc4 as non-preferred ?

2023-07-22 04:33 UTC, adamjstewart commented
Oh, that's fun. I think the reason that no one else has complained is that the `py.py` file that comes with pytest 7.2+ will normally get overridden by the `py/__init__.py` file that comes with py, assuming that they're installed in the same directory. Since Spack installs them to different directories, we're completely dependent on the order of PYTHONPATH to control which gets used.

I don't think there's going to be a reliable way to control the order of this, especially if you have a root package that depends on all 3 of these packages. So I agree with the decision to pin to pytest 7.1 and older until the pytest-html 4.0 release.

2023-07-24 07:58 UTC, Jordan474 commented
I added the conflict. I wasn't sure about it until I found the install-test would pass but then `spack load` would set the faulty `PYTHONPATH` order:

```console
$ spack install --fresh --test root py-pytest-html ^py-pytest@7.3.2
[... install ok ... test ok ...]

$ ( spack load py-pytest-html/...; pytest -VV )
[...]
ModuleNotFoundError: No module named 'py.xml'; 'py' is not a package
```

I'll edit the PR description.

2023-07-30 20:00 UTC, adamjstewart approved these changes

2023-07-30 20:01 UTC, merged