qt: fedora patch missing includes in qtlocation
LLNL/spack pull request #38987
Opened 2023-07-19 10:32 UTC by melven

Fix compilation problems (for me just with GCC 13) due to missing `#include <cstdint>`.

2023-08-10 07:38 UTC, alalazo requested changes

2023-08-10 07:38 UTC, alalazo commented on var/spack/repos/builtin/packages/qt/package.py
> +    patch(
Can you add a brief comment above the `patch` directive explaining:
1. What is the effect of the patch
2. Why it is needed

?

2023-08-10 15:00 UTC, melven commented on var/spack/repos/builtin/packages/qt/package.py
> +    patch(
Added a comment with explanation, see code above.

2023-08-11 06:09 UTC, alalazo approved these changes

2023-08-11 06:10 UTC, merged