Fix Spack freeze on install child process unexpected exit
LLNL/spack pull request #39015
Opened 2023-07-20 15:08 UTC by Jordan474

When a Spack install process stops unexpectedly, Spack would indefinitely wait on `child_result = parent_pipe.recv()`.

I've seen those "unexpected errors" happening in Spack's boiler plate error handling code (#39017), or when the child process is killed by a signal (kill, abort, etc.).

This PR closes the write end of the pipe so the read end can raise `EOFError` when the child process dies. See [python's non-duplex pipe usage example](https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing.connection) (look for `w.close()`).

I've also added a fallback to report any uncaught exit/signal failures of the child process.

Fixes #39016.

2023-07-20 15:16 UTC, Jordan474 commented
One way to reproduce the freeze it to make specific mistake in a recipe to trigger a specific bug in spack's boiler plate error handling code(*):
- replace `def install(self, spec, prefix):` by `def install(self, invalid):` in a `Package` recipe (`lsof` for example)

(*) I will open a separate PR to fix this error

2023-08-09 16:19 UTC, alalazo requested changes
Thanks, this looks great to me. I have only a minor request on the naming side. @haampie Do you want to have a look at this one too?

2023-08-09 16:19 UTC, alalazo commented on lib/spack/spack/build_environment.py
> +    parent_pipe, child_pipe = multiprocessing.Pipe(duplex=False)
Since `duplex is False`, would you mind renaming these:
```suggestion
    read_pipe, write_pipe = multiprocessing.Pipe(duplex=False)
```
?

2023-08-10 11:12 UTC, alalazo approved these changes

2023-08-18 06:14 UTC, alalazo commented
I tested this on several parallel installs, unsing depfile, trying to exit and error in various ways. It seems to behave correctly.

2023-08-18 07:40 UTC, haampie approved these changes

2023-08-18 07:41 UTC, merged