py-rdflib: add 6.3.2
LLNL/spack pull request #39065
Opened 2023-07-24 13:24 UTC by manuelakuhn

https://github.com/RDFLib/rdflib/tree/6.3.2

2023-07-24 18:01 UTC, tldahlgren reviewed
Confirmed the version sha256.

2023-07-30 20:07 UTC, adamjstewart requested changes

2023-07-30 20:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-rdflib/package.py
> +    depends_on("py-isodate@0.6:0", when="@6.3:", type=("build", "run"))
```suggestion
    depends_on("py-isodate@0.6", when="@6.3:", type=("build", "run"))
```
See https://python-poetry.org/docs/dependency-specification/#caret-requirements

2023-07-30 20:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-rdflib/package.py
> +    depends_on("python@3.7:", when="@6:6.2", type=("build", "run"))
Could remove this line

2023-07-31 08:20 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-rdflib/package.py
> +    depends_on("py-isodate@0.6:0", when="@6.3:", type=("build", "run"))
Thanks

2023-07-31 08:33 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-rdflib/package.py
> +    depends_on("python@3.7:", when="@6:6.2", type=("build", "run"))
Done

2023-07-31 18:49 UTC, adamjstewart approved these changes

2023-07-31 18:50 UTC, merged