add wrf4.5.1
LLNL/spack pull request #39291
Opened 2023-08-07 06:49 UTC by IncubatorShokuhou

Add support for [wrf 4.5.1](https://github.com/wrf-model/WRF/releases/tag/v4.5.1).  Have been tested with gcc-9.5.0

2023-08-07 17:15 UTC, tldahlgren requested changes
How did you calculate this checksum?  According to `spack checksum wrf 4.5.1`, I get `91d7dc84f6a41e1243f0b56b2f2c86b10d860610a2c686dfea599aecab02e8f8`.

2023-08-09 00:22 UTC, IncubatorShokuhou commented
> spack checksum wrf 4.5.1

I did `sha256sum ./v4.5.1.tar.gz` and get `9d557c34c105db4d41e727843ecb19199233c7cf82c5369b34a2ce8efe65e2d1`. I'm not sure if this operation is correct. Additionally, could you tell me the difference between doing it this way and directly using `spack checksum wrf 4.5.1`? Furthermore, why is it that I can successfully install it using the SHA256 value obtained from `sha256sum v4.5.1.tar.gz`?

2023-08-09 20:28 UTC, tldahlgren approved these changes
Confirmed the version sha256.

2023-08-09 20:30 UTC, tldahlgren commented
> > spack checksum wrf 4.5.1
> 
> I did `sha256sum ./v4.5.1.tar.gz` and get `9d557c34c105db4d41e727843ecb19199233c7cf82c5369b34a2ce8efe65e2d1`. I'm not sure if this operation is correct. Additionally, could you tell me the difference between doing it this way and directly using `spack checksum wrf 4.5.1`? Furthermore, why is it that I can successfully install it using the SHA256 value obtained from `sha256sum v4.5.1.tar.gz`?

Hmmm.  You're correct.  I must have been in the wrong window/branch when I checked. 🤦

2023-08-09 20:31 UTC, tldahlgren commented
Will defer the merge to give time for @MichaelLaufer and or @ptooley to comment since they're the maintainers.

2023-08-13 17:55 UTC, MichaelLaufer approved these changes
LGTM. Thanks @IncubatorShokuhou !

2023-08-14 07:20 UTC, merged