[py-gradio] New package
LLNL/spack pull request #39304
Opened 2023-08-07 20:47 UTC by qwertos

2023-08-08 22:15 UTC, adamjstewart requested changes

2023-08-08 22:15 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-gradio/package.py
> +    depends_on("py-pillow", type=("build", "run"))
```suggestion
    depends_on("pil", type=("build", "run"))
```
We have a virtual dep for this

2023-08-17 16:31 UTC, qwertos commented
Drafting until dependencies get accepted

2023-08-18 16:18 UTC, adamjstewart commented
You can always include multiple packages in a single PR if they are co-dependent

2023-08-29 17:50 UTC, adamjstewart approved these changes

2023-08-29 17:51 UTC, adamjstewart commented
Let me know when this is "Ready for review" and I'll merge.

2023-08-29 17:51 UTC, qwertos commented
All set

2023-08-29 18:08 UTC, merged