Adds the recipe for miniocli.
LLNL/spack pull request #39318
Opened 2023-08-08 03:26 UTC by dipietrantonio

2023-08-08 06:33 UTC, alalazo requested changes
Can you fix style? Normally we'd do it with @spackbot, but when submitting from an organization, you cannot allow us to act on your behalf

2023-08-08 07:01 UTC, dipietrantonio commented
Hi @alalazo, sure. I will fix the style on every PR I opened, where needed. I am in the process of pushing all our local additions and improvements back to this repo. I will iterate over all the PR again in the following days. Thanks for taking the time to review them!

2023-08-09 01:46 UTC, dipietrantonio commented
Hi @alalazo, I have fixed almost all style errors. The last one seems to be about the license. To me it looks ok though, like the one on top of other recipes. Can you tell me what's wrong?

While we are at it, what should the license be for Pawsey-created packages?

2023-08-09 06:42 UTC, alalazo commented on var/spack/repos/builtin/packages/miniocli/package.py
> +# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
```

2023-08-09 06:43 UTC, alalazo commented on var/spack/repos/builtin/packages/miniocli/package.py
> +# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
> Can you tell me what's wrong?

See above

> While we are at it, what should the license be for Pawsey-created packages?

License should be the same on every package that is contributed

2023-08-09 07:12 UTC, alalazo approved these changes

2023-08-09 07:43 UTC, merged