Adds dependency on libbeagle.
LLNL/spack pull request #39311
Opened 2023-08-08 01:44 UTC by dipietrantonio

2023-08-08 06:47 UTC, alalazo submitted a review, later dismissed
Code LGTM from a Spack point of view. I'll wait for @snehring comments before merging.

2023-08-08 16:23 UTC, snehring requested changes

2023-08-08 16:23 UTC, snehring commented on var/spack/repos/builtin/packages/beast2/package.py
> +    depends_on("libbeagle", type=("build", "link", "run"), when="+beagle")
I believe `type="run"` is sufficient here. We don't really build or link anything in this package as it's a prebuilt java package.

2023-08-09 03:44 UTC, snehring approved these changes

2023-08-09 06:33 UTC, alalazo approved these changes

2023-08-09 06:33 UTC, merged