Added conmon variant build to singularityce
LLNL/spack pull request #39326
Opened 2023-08-08 07:19 UTC by pelahi

- also added new version entry

2023-08-08 07:39 UTC, alalazo requested changes
You can check style locally by running:
```
$ spack style [--fix]
```

2024-02-22 08:03 UTC, alalazo requested changes
Can you please rebase, if you're still interested in the PR, or close the PR?[^1]

[^1]: When submitting from an organization we can't help shepherding PRs, since we (maintainers) are not allowed to edit the PR branch.

2024-02-22 08:03 UTC, alalazo commented on var/spack/repos/builtin/packages/singularityce/package.py
> +        super(SingularityBase, self).do_stage(mirror_only)
```suggestion
        super().do_stage(mirror_only)
```

2024-03-01 07:33 UTC, pelahi commented
Hi @alalazo I will be swamped for the next two weeks but will return to this as I may have further updates based on newer singularityce versions.

2024-11-26 10:56 UTC, alalazo commented
@pelahi

2024-11-29 03:06 UTC, pelahi commented
Hi @alalazo , I can try updating the PR but I am surprised other centres have not encountered this issue and desire this feature. I will need to update the PR to better reflect the changes in spack recipes for newer versions of spack. I will thus close this PR and open another

2024-11-29 03:06 UTC, closed without merging