Added everybeam recipe
LLNL/spack pull request #39322
Opened 2023-08-08 06:42 UTC by pelahi

2023-08-08 07:09 UTC, alalazo requested changes
I left a few initial comments

2023-08-08 07:09 UTC, alalazo commented on var/spack/repos/builtin/packages/everybeam/package.py
> +    patch('cmake.oskar.patch', when='@0.2.0')
Can you add a brief comment above the `patch` directives explaining:
1. What is the effect of the patch
2. Why it is needed
3. Where it was taken from

?

2023-08-08 07:09 UTC, alalazo commented on var/spack/repos/builtin/packages/everybeam/package.py
> +        spec = self.spec
```suggestion
```

2023-08-08 07:09 UTC, alalazo commented on var/spack/repos/builtin/packages/everybeam/package.py
> +    variant('tests', default=False, description='Build tests')
This shouldn't be a variant, if it doesn't change the nature of the binaries being produced.

2023-08-08 07:09 UTC, alalazo commented on var/spack/repos/builtin/packages/everybeam/package.py
> +    variant('lobes', default=False, description='Download and install the LOBEs coefficient files')
Is there any easy way to avoid delegating CMake for the download?

2023-08-08 07:09 UTC, alalazo commented on var/spack/repos/builtin/packages/everybeam/package.py
> +    depends_on('py-sphinx')
Do we want to have a variant for documentation?

2024-02-22 07:16 UTC, alalazo commented
Are you still interested in the PR?

2024-03-01 07:31 UTC, pelahi commented
Hi @alalazo , sorry I've been swamped by other things and will be for the next two weeks. I return to this in late March.

2024-11-26 10:54 UTC, alalazo commented
@pelahi

2024-11-29 03:04 UTC, pelahi commented
Hi @alalazo apologies for the delay. The software is in flux but looks like now have a better handle on useful builds of it from the astro community. Likely we'll do a new PR with syntax updated for later versions of spack.

2024-11-29 03:04 UTC, closed without merging