Do not treat warnings as errors during compilation.
LLNL/spack pull request #39325
Opened 2023-08-08 07:16 UTC by dipietrantonio

The package won't compile with newer compilers because warnings are converted to errors. Hence, disable such conversion.

2023-08-08 08:11 UTC, dennisklein requested changes
Thx! I approve the change, however, we need it conditionally on the version - see my inline comment.

2023-08-08 08:11 UTC, dennisklein commented on var/spack/repos/builtin/packages/libzmq/package.py
> +        config_args.append("--disable-Werror")
Please add a version condition >= 4.2.3 (see https://github.com/zeromq/libzmq/commit/08289d8f3346fad4e271a06d0b4e7a5ca3f304d6).

2023-08-09 07:20 UTC, dipietrantonio commented on var/spack/repos/builtin/packages/libzmq/package.py
> +        config_args.append("--disable-Werror")
Done.

2023-08-09 07:32 UTC, alalazo approved these changes
@dennisklein Can you double check?

2023-08-09 13:39 UTC, dennisklein approved these changes

2023-08-09 13:57 UTC, merged