nwchem: make sure to link both single and double precision fftw libraries.
LLNL/spack pull request #39333
Opened 2023-08-08 08:46 UTC by dipietrantonio

With the previous version of the recipe I would get linking errors due to missing `-lfftw3f`.

2023-08-08 09:08 UTC, alalazo requested changes

2023-08-08 09:08 UTC, alalazo commented on var/spack/repos/builtin/packages/nwchem/package.py
> +            args.extend(["LIBFFTW3=%s" % fftw.joined(" ")])
Can you explain what was the error before, which line got added and which one is being used now?

2023-08-09 07:11 UTC, dipietrantonio commented
Hi @alalazo, 

The error I get with the original recipe is a link stage one:

```
  >> 40186    /usr/bin/ld: D3dBs-new.F:(.text+0x1381): undefined reference to `sfftw_execute_dft_'
  >> 40187    /usr/bin/ld: D3dBs-new.F:(.text+0x13a8): undefined reference to `sfftw_execute_dft_c2r_'
  >> 40188    /usr/bin/ld: D3dBs-new.F:(.text+0x144b): undefined reference to `sfftw_execute_dft_'
  >> 40189    /usr/bin/ld: D3dBs-new.F:(.text+0x148d): undefined reference to `sfftw_execute_dft_'
  >> 40190    /usr/bin/ld: D3dBs-new.F:(.text+0x14c5): undefined reference to `sfftw_execute_dft_c2r_'
[...]
```
indicating that the single precision library is not linked. As a quick fix to solve this I had done the following:

```
args.extend(["LIBFFTW3=%s -lfftw3f" % fftw.ld_flags])
```
and that works. Of course, hardcoding that value isn't great, so I thought the proposed solution here would work. Turns out that I had made a mistake while testing this PR and it actually does not work either. 

Looking at the log I see
```
 'USE_FFTW3=y' 'LI
BFFTW3=/scratch/pawsey0001/cdipietrantonio/stack-20230708/2023.07/software/linux-sles15-zen3/gcc-12.2.0/fftw-3.3.10-o2l6h6k4aujjws3btuuc2uvll7tr25k5/lib/libfftw3.so' 'FFTW3_INCLUDE=/scratch/pawsey0001/cdipietrantonio/stack-20230708/2023.07/software/linux-sles15-zen3/gcc-12.2.0/fftw-3.3.10-o2l6h6k4aujjws3btuuc2uvll7tr25k5/include
```

So, only the double precision library is linked. I guess this is the same output for `fftw.ld_flags`.

How do we fix this?

2023-08-09 07:45 UTC, alalazo commented
You can do the following:
```python
if "fftw" in spec:
    fftw = spec["fftw:double,float"].libs
```
With that syntax I think `ld_flags` should be working correctly (I believe it is documented somewhere, but can't find a link to the docs right now :sweat: ).

2023-08-09 10:46 UTC, dipietrantonio commented
Hi @alalazo , thanks to your comment I found the solution to this issue. Check out the last commit.

2023-08-09 12:03 UTC, alalazo approved these changes

2023-08-09 12:03 UTC, merged