restore config locks
LLNL/spack pull request #39356
Opened 2023-08-09 11:18 UTC by dguibert

fixes https://github.com/flatironinstitute/nixpack/issues/40

With https://github.com/spack/spack/commit/53ae969aa008c8fb358f33b9b961beb5512999ff, config:locks is no longer used to create Lock. This patch restores this and allow to create database locks to a custom directory.

Database locks have been introduced by https://github.com/spack/spack/commit/53ae969aa008c8fb358f33b9b961beb5512999ff
We could either use config:locks on them or create the lock in a custom directory. To avoid much trouble, the later has been chosen.

The CI fails with: "Database" gets multiple values for keyword argument "upstream_dbs"  [misc]
But it's not introduced by this patch.

2023-08-09 11:27 UTC, alalazo requested changes
Can you explain what is the issue you are facing in Spack? 

This PR doesn't make much sense to me, since it reads (again) from a global variable values that should be injected in the constructor.  If there is a value that is wrong for the store or DB etc. it should be fixed where the object is created, not in the class constructor by reading a global variable.

2023-08-09 11:36 UTC, alalazo commented
> With https://github.com/spack/spack/commit/53ae969aa008c8fb358f33b9b961beb5512999ff, config:locks is no longer used to create Lock. 

Why do you say this? See:

https://github.com/spack/spack/blob/af8c392de2a5c7c1b1ca1448964dbd4bab87c43a/lib/spack/spack/database.py#L345-L351

which creates a `LockConfiguration` from a `Configuration` object and:

https://github.com/spack/spack/blob/af8c392de2a5c7c1b1ca1448964dbd4bab87c43a/lib/spack/spack/store.py#L209-L233

which uses it to construct the store. The PR you mention had the only purpose of decoupling the internal design. Before the PR we couldn't construct a lock without having a global configuration object available.

2023-08-09 12:02 UTC, alalazo commented on lib/spack/spack/store.py
> +        next_db = spack.database.Database(db_root,
> The CI fails with: "Database" gets multiple values for keyword argument "upstream_dbs" [misc]
> But it's not introduced by this patch.

Are you sure?

2023-08-09 14:49 UTC, dguibert commented
> Can you explain what is the issue you are facing in Spack?

I'm facing this issue https://github.com/flatironinstitute/nixpack/issues/40, paths are read-only, locks are not needed.

> This PR doesn't make much sense to me, since it reads (again) from a global variable values that should be injected in the constructor. If there is a value that is wrong for the store or DB etc. it should be fixed where the object is created, not in the class constructor by reading a global variable.

Ok, thank you to clarify. So obviously the modifications here are wrong.

I think that DataBase and FileCache objects are not instantiated with the global config:locks setting, right?

2023-08-09 14:56 UTC, dguibert commented on lib/spack/spack/store.py
> +        next_db = spack.database.Database(db_root,
sorry, missed that

2023-08-09 14:58 UTC, alalazo commented
> I think that DataBase and FileCache objects are not instantiated with the global config:locks setting, right?

No, they should be instantiated like that - and they generally are. It might be though that some code path got an accidental bug during the refactor, so I'm trying to understand that. 

The modification interposes a factory layer that translates the global `config:locks` settings in:

https://github.com/spack/spack/blob/af8c392de2a5c7c1b1ca1448964dbd4bab87c43a/lib/spack/spack/store.py#L236-L238

where `spack.config.config` is the global configuration contaning `config:locks`.

2023-08-09 15:10 UTC, alalazo commented
> I'm facing this issue https://github.com/flatironinstitute/nixpack/issues/40, paths are read-only, locks are not needed.

@dguibert It would be great if you could extract a Spack only reproducer for that. That would help me a lot triaging and eventually fixing the bug.

2023-08-09 16:16 UTC, dguibert commented
> > I'm facing this issue [flatironinstitute/nixpack#40](https://github.com/flatironinstitute/nixpack/issues/40), paths are read-only, locks are not needed.
> 
> @dguibert It would be great if you could extract a Spack only reproducer for that. That would help me a lot triaging and eventually fixing the bug.

I'll try... I've updated the branch:
- misc_cache was not taking into account config:locks

2024-02-22 08:06 UTC, alalazo commented
Any luck trying to get a reproducer in Spack?

2024-02-22 13:38 UTC, dguibert commented
> Any luck trying to get a reproducer in Spack?

Nope, this seems to be related to the way nixpack has overload the Store class. I can't reproduce this  in Spack.

So I'm closing it.

2024-02-22 13:38 UTC, closed without merging