py-xarray: add v2023.7.0
LLNL/spack pull request #39418
Opened 2023-08-14 09:35 UTC by genric

2023-08-18 15:32 UTC, adamjstewart requested changes

2023-08-18 15:32 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-xarray/package.py
>      depends_on("python@3.6:", when="@0.14:", type=("build", "run"))
setuptools-scm@7: is required now

2023-08-18 15:32 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-xarray/package.py
>      depends_on("py-zarr", when="+io", type=("build", "run"))
pydap only `when="^python@:3.9"`

2023-08-21 15:16 UTC, genric commented on var/spack/repos/builtin/packages/py-xarray/package.py
>      depends_on("python@3.6:", when="@0.14:", type=("build", "run"))
done

2023-08-21 15:16 UTC, genric commented on var/spack/repos/builtin/packages/py-xarray/package.py
>      depends_on("py-zarr", when="+io", type=("build", "run"))
done

2023-08-23 00:13 UTC, adamjstewart approved these changes

2023-08-23 00:13 UTC, merged