podman: add fuse variant
LLNL/spack pull request #39442
Opened 2023-08-15 12:50 UTC by bryanherman

Podman has two storage drivers that it looks for, fuse-overlayfs and vfs. According to the docs:

> --storage-driver=value Storage driver. The default storage driver for UID 0 is configured in containers-storage.conf(5) in rootless mode), **and is vfs for non-root users when fuse-overlayfs is not available**. The STORAGE_DRIVER environment variable overrides the default. The --storage-driver specified driver overrides all.

This PR adds fuse-overlayfs as a runtime dependency. The executable `fuse-overlayfs` has to specified in the `storage.conf` file as the `mount_program` to take advantage. I wasn't sure to make the fuse variant default to `True` because of the way the docs are worded. I kept as `False` to not disturb other installations.

2023-08-15 12:52 UTC, bryanherman commented
This is also important context from https://docs.podman.io/en/latest/markdown/podman.1.html:

The Overlay file system (OverlayFS) is not supported with kernels prior to 5.12.9 in rootless mode. The fuse-overlayfs package is a tool that provides the functionality of OverlayFS in user namespace that allows mounting file systems in rootless environments. It is recommended to install the fuse-overlayfs package. In rootless mode, Podman automatically uses the fuse-overlayfs program as the mount_program if installed, as long as the $HOME/.config/containers/storage.conf file was not previously created. If storage.conf exists in the homedir, add mount_program = "/usr/bin/fuse-overlayfs" under [storage.options.overlay] to enable this feature.

The Network File System (NFS) and other distributed file systems (for example: Lustre, Spectrum Scale, the General Parallel File System (GPFS)) are not supported when running in rootless mode as these file systems do not understand user namespace. However, rootless Podman can make use of an NFS Homedir by modifying the $HOME/.config/containers/storage.conf to have the graphroot option point to a directory stored on local (Non NFS) storage.

**With a Spack installation, a user must have a `storage.conf` and add the full path to `fuse-overlayfs` as the `mount_program`.**

2023-08-28 14:01 UTC, bryanherman commented
@haampie can you take a look? or is there someone i should reach out to for a review?

2024-10-16 01:36 UTC, bernhardkaindl requested changes
.

2024-10-16 02:08 UTC, bernhardkaindl requested changes
Build results on Ubuntu 22.04.4 LTS:
One failed spec:
- `podman+fuse`
### `podman+fuse`:
```py

2 errors found in build log:
     9     autoreconf: configure.ac: not using Gettext
     10    autoreconf: running: aclocal -I opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-5jvtfpdq7c64lojw64r3grrtu5dwcjq2/share/aclocal --for
           ce -Im4
     11    autoreconf: configure.ac: tracing
     12    autoreconf: configure.ac: creating directory build-aux
     13    autoreconf: configure.ac: not using Libtool
     14    autoreconf: running: opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/autoconf-2.69-p4umyptwwz7gvx5enjeqgje7kjs3gyhx/bin/autoconf --include=/home/b
           kaindl/spack.4/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-5jvtfpdq7c64lojw64r3grrtu5dwcjq2/share/aclocal --force
  >> 15    configure.ac:31: error: possibly undefined macro: AC_DEFINE
     16          If this token and others are legitimate, please use m4_pattern_allow.
     17          See the Autoconf documentation.
  >> 18    configure.ac:33: error: possibly undefined macro: AC_MSG_ERROR
     19    autoreconf: opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/autoconf-2.69-p4umyptwwz7gvx5enjeqgje7kjs3gyhx/bin/autoconf failed with exit status: 1

See build log for details:
  .stage/spack-stage-fuse-overlayfs-1.10-kpbuan26xfoan4oybv5ifqb3zvmkd7hc/spack-build-out.txt

==> Warning: Skipping build of podman-4.5.1-kv2ffvkh7aztroawv36rzwvelarebxfq since fuse-overlayfs-1.10-kpbuan26xfoan4oybv5ifqb3zvmkd7hc failed
==> Error: Terminating after first install failure: ProcessError: Command exited with status 1:
    'opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/autoconf-2.69-p4umyptwwz7gvx5enjeqgje7kjs3gyhx/bin/autoreconf' '-ivf' '-I' 'opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-5jvtfpdq7c64lojw64r3grrtu5dwcjq2/share/aclocal'

```
Please fix the failed specks and check the changes.
Then push the changes to the PR branch and change the PR status to 'Ready for review'.
This message has been generated and submitted automatically by https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py
```py
~/build-quality-tools/build_pr_changes.py -b podman+fuse -ma
```

2024-10-16 02:18 UTC, bernhardkaindl requested changes
Build results on Ubuntu 22.04.4 LTS:
One failed spec:
- `podman+fuse`
### `podman+fuse`:
```py

2 errors found in build log:
     9     autoreconf: configure.ac: not using Gettext
     10    autoreconf: running: aclocal -I opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-5jvtfpdq7c64lojw64r3grrtu5dwcjq2/share/aclocal --for
           ce -Im4
     11    autoreconf: configure.ac: tracing
     12    autoreconf: configure.ac: creating directory build-aux
     13    autoreconf: configure.ac: not using Libtool
     14    autoreconf: running: opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/autoconf-2.69-p4umyptwwz7gvx5enjeqgje7kjs3gyhx/bin/autoconf --include=/home/b
           kaindl/spack.4/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-5jvtfpdq7c64lojw64r3grrtu5dwcjq2/share/aclocal --force
  >> 15    configure.ac:31: error: possibly undefined macro: AC_DEFINE
     16          If this token and others are legitimate, please use m4_pattern_allow.
     17          See the Autoconf documentation.
  >> 18    configure.ac:33: error: possibly undefined macro: AC_MSG_ERROR
     19    autoreconf: opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/autoconf-2.69-p4umyptwwz7gvx5enjeqgje7kjs3gyhx/bin/autoconf failed with exit status: 1

See build log for details:
  .stage/spack-stage-fuse-overlayfs-1.10-kpbuan26xfoan4oybv5ifqb3zvmkd7hc/spack-build-out.txt

==> Warning: Skipping build of podman-4.5.1-kv2ffvkh7aztroawv36rzwvelarebxfq since fuse-overlayfs-1.10-kpbuan26xfoan4oybv5ifqb3zvmkd7hc failed
==> Error: Terminating after first install failure: ProcessError: Command exited with status 1:
    'opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/autoconf-2.69-p4umyptwwz7gvx5enjeqgje7kjs3gyhx/bin/autoreconf' '-ivf' '-I' 'opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-5jvtfpdq7c64lojw64r3grrtu5dwcjq2/share/aclocal'

```
Please fix the failed specks and check the changes.
Then push the changes to the PR branch and change the PR status to 'Ready for review'.
This message has been generated and submitted automatically by https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py
```py
~/build-quality-tools/build_pr_changes.py -b podman+fuse -may
```

2024-10-16 03:22 UTC, bernhardkaindl requested changes
.

2024-10-16 03:23 UTC, bernhardkaindl requested changes
Build results on Ubuntu 22.04.4 LTS:
One failed spec:
- `podman+fuse`
### `podman+fuse`:
```py

2 errors found in build log:
     9     autoreconf: configure.ac: not using Gettext
     10    autoreconf: running: aclocal -I opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-5jvtfpdq7c64lojw64r3grrtu5dwcjq2/share/aclocal --for
           ce -Im4
     11    autoreconf: configure.ac: tracing
     12    autoreconf: configure.ac: creating directory build-aux
     13    autoreconf: configure.ac: not using Libtool
     14    autoreconf: running: opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/autoconf-2.69-p4umyptwwz7gvx5enjeqgje7kjs3gyhx/bin/autoconf --include=/home/b
           kaindl/spack.4/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-5jvtfpdq7c64lojw64r3grrtu5dwcjq2/share/aclocal --force
  >> 15    configure.ac:31: error: possibly undefined macro: AC_DEFINE
     16          If this token and others are legitimate, please use m4_pattern_allow.
     17          See the Autoconf documentation.
  >> 18    configure.ac:33: error: possibly undefined macro: AC_MSG_ERROR
     19    autoreconf: opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/autoconf-2.69-p4umyptwwz7gvx5enjeqgje7kjs3gyhx/bin/autoconf failed with exit status: 1

See build log for details:
  .stage/spack-stage-fuse-overlayfs-1.10-kpbuan26xfoan4oybv5ifqb3zvmkd7hc/spack-build-out.txt

==> Warning: Skipping build of podman-4.5.1-kv2ffvkh7aztroawv36rzwvelarebxfq since fuse-overlayfs-1.10-kpbuan26xfoan4oybv5ifqb3zvmkd7hc failed
==> Error: Terminating after first install failure: ProcessError: Command exited with status 1:
    'opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/autoconf-2.69-p4umyptwwz7gvx5enjeqgje7kjs3gyhx/bin/autoreconf' '-ivf' '-I' 'opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-5jvtfpdq7c64lojw64r3grrtu5dwcjq2/share/aclocal'

```
Please fix the failed specks and check the changes.
Then push the changes to the PR branch and change the PR status to 'Ready for review'.
This message has been generated and submitted automatically by https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py
```py
~/build-quality-tools/build_pr_changes.py -b podman+fuse -may
```

2025-05-07 07:20 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2025-05-07 07:20 UTC, closed without merging