AOCL spack recipes for 4.1 release w. new AOCL-Utils library
LLNL/spack pull request #39489
Opened 2023-08-17 13:12 UTC by amd-toolchain-support

This adds version 4.1 of AOCL, including a new AOCL-Utils library.

License URLs have been updated, and various small tidyups have been made.

2023-08-22 18:40 UTC, tldahlgren reviewed
Confirmed the new homepage and version sha256s _except_ that of `aocl-sparse`.

2023-08-22 18:40 UTC, tldahlgren commented on var/spack/repos/builtin/packages/aocl-sparse/package.py
> +    version("4.1", sha256="68524e441fdc7bb923333b98151005bed39154d9f4b5e8310b5c37de1d69c2c3")
How is this checksum calculated?  

I'm getting `35ef437210bc25fdd802b462eaca830bfd928f962569b91b592f2866033ef2bb` from `spack checksum aocl-sparse`.

2023-08-22 18:41 UTC, tldahlgren requested changes
Please correct or clarify the sha256.

2023-08-22 18:52 UTC, amd-toolchain-support commented on var/spack/repos/builtin/packages/aocl-sparse/package.py
> +    version("4.1", sha256="68524e441fdc7bb923333b98151005bed39154d9f4b5e8310b5c37de1d69c2c3")
That checksum was apparently "calculated" by an error in fixing a conflict in our internal tree. Apologies

2023-08-22 19:02 UTC, tldahlgren approved these changes, later dismissed
LGTM.  Did you want to review this PR as well @adamjstewart ?

2023-08-22 23:07 UTC, adamjstewart commented
Nah, I don't use any of these packages. I'll trust your review.

2023-08-22 23:09 UTC, tldahlgren commented
Looks like there are style issues with an extra blank line:

```
==> Running black checks
--- var/spack/repos/builtin/packages/amdblis/package.py	2023-08-22 19:28:33.866762 +0000
+++ var/spack/repos/builtin/packages/amdblis/package.py	2023-08-22 19:28:46.273936 +0000
@@ -43,11 +43,10 @@
     version("2.2", sha256="e1feb60ac919cf6d233c43c424f6a8a11eab2c62c2c6e3f2652c15ee9063c0c9")
 
     variant("ilp64", default=False, when="@3.0.1:", description="ILP64 support")
     variant("aocl_gemm", default=False, when="@4.1:", description="aocl_gemm support")
     variant("suphandling", default=True, description="Small Unpacked Kernel handling")
-
 
     def configure_args(self):
         spec = self.spec
         args = super().configure_args()
 
would reformat var/spack/repos/builtin/packages/amdblis/package.py
Oh no! 💥 💔 💥
1 file would be reformatted, 7 files would be left unchanged.
  black found errors
==> Running flake8 checks
var/spack/repos/builtin/packages/amdblis/package.py:50: [E303] too many blank lines (2)
  flake8 found errors
  ```

2023-08-25 01:05 UTC, tldahlgren approved these changes
LGTM

2023-08-25 01:05 UTC, merged