preCICE: prepare for version 3
LLNL/spack pull request #39486
Opened 2023-08-17 09:26 UTC by fsimonis

This PR prepares the spack package of preCICE for the upcoming version 3.
The spec `precice@develop` now builds correctly again, which is necessary for the tests of `xsdk@1.0.0`.
Related to https://github.com/xsdk-project/xsdk-issues/issues/217

2023-08-17 09:42 UTC, fsimonis commented
Removed MakisH from reviewer list as he is currently on vacation.

2023-08-21 14:32 UTC, fsimonis commented
@balay This PR fixes the build issue https://github.com/xsdk-project/xsdk-issues/issues/217#issuecomment-1681224491.

Could you review / pick a reviewer?

2023-08-23 06:36 UTC, balay approved these changes, later dismissed
build works for me now. Thanks!

2023-08-23 07:07 UTC, alalazo commented on var/spack/repos/builtin/packages/precice/package.py
> +    )
Would it be possible to either assume these variants are on when e.g. `build_type=RelWithDebInfo` or collapse the variants into one with maybe a shorter name?

2023-08-23 10:15 UTC, fsimonis commented on var/spack/repos/builtin/packages/precice/package.py
> +    )
> Would it be possible to either assume these variants are on when e.g. build_type=RelWithDebInfo

These are deliberately detached from the build_type.

> or collapse the variants into one with maybe a shorter name

The two options have different use cases. Compiling debug log is useful for users to debug adapters on HPC systems, while assertions are useful to ensure internal correctness at the cost of performance.

Is there a technical reason to reduce the amount and size of variants?

If size matters, we could use:

```py
    variant(
        "log", default="info",
        description="Log severity to enable compilation up to",
        values=("info", "debug"),
        multi=False,
        when="@2.4:",
    )
    variant(
        "checked",
        default=False,
        description="Release build with assertions",
        when="@2.4:",
    )
```

These options don't make sense for `build_type=Debug`. Is there a way of defining `when="@2.4: build_type!=Debug"`? Essentially a `~variant` for multi-value variants?

2023-08-23 11:01 UTC, alalazo commented on var/spack/repos/builtin/packages/precice/package.py
> +    )
> Is there a technical reason to reduce the amount and size of variants?

No, it's only kind of inconvenient to have variants which are 20-25 chars long. I like more `+checked` and `log=info|debug`. 

> Is there a way of defining when="@2.4: build_type!=Debug"? Essentially a ~variant for multi-value variants?

There is, but it's not pretty. See [here](https://spack.readthedocs.io/en/latest/packaging_guide.html#overriding-variants). Essentially, you can <kbd>Ctrl+C</kdb> <kbd>Ctrl+V</kdb> the variant and change the when clause only to state when this is allowed (`build_type=Release`, `build_type=RelWithDebInfo`, etc.)

2023-08-23 15:48 UTC, fsimonis commented on var/spack/repos/builtin/packages/precice/package.py
> +    )
To simplify it a bit, I used boolean variants `debug_log` and `checked`, specified overrides for the `build_type=Debug`, and defined `conflicts`.

This allows me to provide a clear error message for the unsupported case.

2023-08-24 07:08 UTC, alalazo requested changes
Minor changes, you cannot redefine defaults for variants.

2023-08-24 07:08 UTC, alalazo commented on var/spack/repos/builtin/packages/precice/package.py
> +    )
```suggestion
```

2023-08-24 07:08 UTC, alalazo commented on var/spack/repos/builtin/packages/precice/package.py
> +    )
```suggestion
```

2023-08-24 07:11 UTC, alalazo commented
To be clear, either using conflicts as you do here (but removing the code above) or doing:
```
variant(
    "debug_log",
    default=False,
    description="Enable debug log in non-debug builds",
    when="@2.4: build_type=Release",
)
variant(
    "debug_log",
    default=False,
    description="Enable debug log in non-debug builds",
    when="@2.4: build_type=RelWithDebInfo",
)
```
without conflicts are valid options. The difference is that in the latter case you won't have the `debug_log` variant in the spec when `build_type=Debug`.

2023-08-24 08:53 UTC, fsimonis commented
> The difference is that in the latter case you won't have the debug_log variant in the spec when build_type=Debug.

I think this is the best way forward. :+1:

2023-08-24 10:34 UTC, fsimonis commented on var/spack/repos/builtin/packages/precice/package.py
> +    )
Solved via 7fe9104bae6959e0b4ca65045cde409416ac4357

2023-08-24 10:34 UTC, fsimonis commented on var/spack/repos/builtin/packages/precice/package.py
> +    )
Solved via 7fe9104bae6959e0b4ca65045cde409416ac4357

2023-08-24 10:36 UTC, fsimonis commented
I used a loop and f-string literals to prevent copy-paste. I haven't seen this in other packages. Is this going against some guidelines I am not aware of?

2023-08-24 11:23 UTC, alalazo approved these changes

2023-08-24 18:04 UTC, merged