Add mesh management tools from ISCD
LLNL/spack pull request #39490
Opened 2023-08-17 14:47 UTC by jcortial-safran

2025-05-22 08:31 UTC, jcortial-safran commented
@alalazo @haampie Would it be possible to get some feedback for this PR ?

2025-05-27 10:09 UTC, alalazo requested changes

2025-05-27 10:09 UTC, alalazo commented on var/spack/repos/spack_repo/builtin/packages/iscdtoolbox_commons/package.py
> +        return args
Isn't this enough:
```suggestion
    def cmake_args(self):
        return = [self.define_from_variant("OPENMP", "openmp")]
```
?

2025-05-27 10:09 UTC, alalazo commented on var/spack/repos/spack_repo/builtin/packages/iscdtoolbox_commons/package.py
> +    patch("user-defined-prefix-path.patch")
Can you add a brief comment above the `patch` directive explaining:
1. What is the effect of the patch
2. Why it is needed
3. Where it was taken from

?

2025-05-27 10:09 UTC, alalazo commented on var/spack/repos/spack_repo/builtin/packages/iscdtoolbox_elasticity/package.py
> +    patch("user-defined-prefix-path.patch")
Can you add a brief comment above the `patch` directive explaining:
1. What is the effect of the patch
2. Why it is needed
3. Where it was taken from

?

2025-05-27 10:09 UTC, alalazo commented on var/spack/repos/spack_repo/builtin/packages/iscdtoolbox_elasticity/package.py
> +    depends_on("iscdtoolbox_commons ~openmp", when="~openmp")
```suggestion
    depends_on("iscdtoolbox-commons +openmp", when="+openmp")
    depends_on("iscdtoolbox-commons ~openmp", when="~openmp")
```
?

2025-05-27 10:09 UTC, alalazo commented on var/spack/repos/spack_repo/builtin/packages/mmg/package.py
> +    depends_on("iscdtoolbox_elasticity", when="+elas")
```suggestion
    depends_on("iscdtoolbox-elasticity", when="+elas")
```
?

2025-06-02 17:06 UTC, jcortial-safran commented on var/spack/repos/spack_repo/builtin/packages/mmg/package.py
> +    depends_on("iscdtoolbox_elasticity", when="+elas")
It seens that the package names cannot have `-` anymore. Is that correct ?

2025-06-02 17:06 UTC, jcortial-safran commented on var/spack/repos/spack_repo/builtin/packages/iscdtoolbox_elasticity/package.py
> +    depends_on("iscdtoolbox_commons ~openmp", when="~openmp")
It seens that the package names cannot have - anymore. Is that correct ?

2025-06-04 10:56 UTC, jcortial-safran commented on var/spack/repos/spack_repo/builtin/packages/iscdtoolbox_commons/package.py
> +    patch("user-defined-prefix-path.patch")
Comment added

2025-06-04 10:56 UTC, jcortial-safran commented on var/spack/repos/spack_repo/builtin/packages/iscdtoolbox_elasticity/package.py
> +    patch("user-defined-prefix-path.patch")
Comment added

2025-06-04 10:58 UTC, jcortial-safran commented on var/spack/repos/spack_repo/builtin/packages/mmg/package.py
> +    depends_on("iscdtoolbox_elasticity", when="+elas")
Nevermind, Thanks for the fix.

2025-06-04 10:58 UTC, jcortial-safran commented on var/spack/repos/spack_repo/builtin/packages/iscdtoolbox_elasticity/package.py
> +    depends_on("iscdtoolbox_commons ~openmp", when="~openmp")
Nevermind, Thanks for the fix.

2025-06-06 12:04 UTC, haampie commented
Hi @jcortial-safran, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2025-06-07 08:18 UTC, closed without merging