py-particle: new versions through 0.23.0
LLNL/spack pull request #39547
Opened 2023-08-21 00:09 UTC by wdconinc

New versions through 0.23.0 (with new PDG release). No build system changes. Release notes: https://github.com/scikit-hep/particle/releases

2023-08-21 08:18 UTC, vvolkl approved these changes

2023-08-21 19:19 UTC, tldahlgren reviewed
Confirmed the three version sha256.

2023-08-23 00:25 UTC, adamjstewart requested changes
Missing dep on `py-deprecated`

2023-08-24 21:22 UTC, adamjstewart approved these changes

2023-08-24 21:22 UTC, merged