py-ffmpeg-python: new package
LLNL/spack pull request #39678
Opened 2023-08-29 14:54 UTC by qwertos

2023-08-29 18:35 UTC, tldahlgren reviewed
Confirmed the homepage and version sha256.  Adding @adamjstewart since it is a python package.

2023-08-29 21:01 UTC, adamjstewart requested changes

2023-08-29 21:01 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ffmpeg-python/package.py
> +    depends_on("py-setuptools", type="run")
setuptools should be a build dep, missing build dep on pytest-runner, missing build/run dep on future

2024-02-17 22:21 UTC, alecbcs commented
@qwertos do you have time to address the review feedback or should we close this PR?

2024-11-27 13:12 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2024-11-27 13:12 UTC, closed without merging