variorum: add v0.7.0, dev
LLNL/spack pull request #39681
Opened 2023-08-29 16:18 UTC by slabasan

- update to latest Spack practices
- add latest releases
- integrate with archspec for CPU detection
- add support for building on Nvidia and AMD GPU architectures

2023-08-29 16:52 UTC, becker33 requested changes

2023-08-29 16:52 UTC, becker33 commented on var/spack/repos/builtin/packages/variorum/package.py
> +            cmake_args.append("-DVARIORUM_WITH_ARM_CPU=OFF")
```suggestion
            cmake_args.append("-DVARIORUM_WITH_AMD_CPU=OFF")
            cmake_args.append("-DVARIORUM_WITH_AMD_GPU=OFF")
            cmake_args.append("-DVARIORUM_WITH_ARM_CPU=ON")
```

2023-08-29 16:52 UTC, becker33 commented on var/spack/repos/builtin/packages/variorum/package.py
> +        elif "+hip" in spec:
```suggestion
        elif "+rocm" in spec:
```

2023-08-29 16:52 UTC, becker33 commented on var/spack/repos/builtin/packages/variorum/package.py
> +        cpu_uarch = self.spec.target
```suggestion
        target = self.spec.target
        cpu_vendor = target.microarchitecture.vendor
        cpu_uarch = target.microarchitecture.name
```

2023-08-29 16:52 UTC, becker33 commented on var/spack/repos/builtin/packages/variorum/package.py
```suggestion
    supported_amd_targets = ["zen2"]
    supported_arm_targets = ["neoverse_n1"]
    supported_ibm_targets = ["power9le"]
    supported_intel_targets = [
        "sandybridge",
        "ivybridge",
        "haswell",
        "broadwell",
        "skylake",
        "cascadelake",
        "icelake",
    ]
    for arch in archspec.cpu.TARGETS:
        if arch not in supported_amd_targets + supported_arm_targets + supported_ibm_targets + supported_intel_targets:
            conflicts(f"target={target}")
```

Then below in the `cmake_args` method you can just check the vendor.

If the non-supported targets are a valid build target when building for GPU, you can switch the conflicts statement above to `conficts(f"target={target}", when="~cuda~rocm")`

2023-08-29 16:52 UTC, becker33 commented on var/spack/repos/builtin/packages/variorum/package.py
> +        if cpu_vendor == "AuthenticAMD" and cpu_uarch in supported_amd_targets:
These are going to overwrite the values you set above for the gpu architectures. It seems like there are two options based on what I don't know about the package.

Either, you build for both the GPU and the CPU. In that case, change this block to only modify the CPU values, and the block above modifies the GPU values (and needs an `else` case to turn them all off).

If you only build for one, then these should all be `elif` on the same code block as the GPU settings above.

2024-11-27 13:14 UTC, alalazo commented
Is this something we still want to merge, besides the version updates that in the meanwhile got outdated?

2025-05-19 18:59 UTC, slabasan commented
This PR can be closed, it is being replaced by #50448.

2025-05-19 18:59 UTC, closed without merging