Added py-yt-dlp module
LLNL/spack pull request #39708
Opened 2023-08-30 18:08 UTC by fernandoGubiMarques

Ping @hyviquel

2023-08-30 23:56 UTC, tldahlgren reviewed
Confirmed the homepage and version sha256.  Adding python package guru as a reviewer.

2023-09-02 21:13 UTC, adamjstewart requested changes

2023-09-02 21:13 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-yt-dlp/package.py
> +    depends_on("py-setuptools", type=("build", "run"))
```suggestion
    depends_on("py-setuptools@51:", type="build")
```

2023-09-02 21:13 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-yt-dlp/package.py
> +    depends_on("python@3.7:", type=("build", "run"))
This line isn't needed, Spack only supports Python 3.7+ anyway

2023-09-02 21:13 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-yt-dlp/package.py
> +    depends_on("ffmpeg+openssl", type="run")
Missing a ton of deps:
```
mutagen
pycryptodomex
websockets
brotli; platform_python_implementation=='CPython'
brotlicffi; platform_python_implementation!='CPython'
certifi
```

2024-02-17 22:10 UTC, alecbcs commented
Going to close this PR due to a lack of response from review feedback. @fernandoGubiMarques happy to reopen if you still want to get this merged and have time to work on it.

2024-02-17 22:10 UTC, closed without merging