Add cuda as a variant to opa-psm2
LLNL/spack pull request #39754
Opened 2023-09-01 17:08 UTC by rfeki

Enable cuda support on opa-psm2 by setting PSM_CUDA to 1 if the "+cuda" variant is requested.

2023-09-12 17:46 UTC, jack-morrison requested changes
@rfeki, I think this looks pretty good. 

One small request. It looks like [opa-psm2 with CUDA support should be built using CUDA 8.0 or later](https://github.com/cornelisnetworks/opa-psm2/blob/ad5dd1bed7ba38809ef02e76278ad636194efdfc/README#L109).

If this is correct, do you mind adding a [`depends_on`](https://spack.readthedocs.io/en/latest/packaging_guide.html#depends-on) for this?

Should be something like:
```
depends_on("cuda@8:", when="+cuda")
```

I believe this ought to keep Spack from attempting to build opa-psm2 with an older CUDA.

2023-09-18 17:09 UTC, rfeki commented
@jack-morrison Done.

2023-09-18 19:23 UTC, jack-morrison approved these changes

2023-09-18 19:28 UTC, becker33 approved these changes

2023-09-18 19:28 UTC, merged