Adding dynaconf module
LLNL/spack pull request #39762
Opened 2023-09-02 16:19 UTC by GeorgeJuniorGG

Ping @hyviquel

2023-09-06 21:58 UTC, tldahlgren reviewed
Confirmed the homepage and version sha256.  Adding @adamjstewart since he's the python package maintainer and more thorough regarding dependencies, etc.

2023-09-11 20:07 UTC, adamjstewart requested changes

2023-09-11 20:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-dynaconf/package.py
> +    depends_on("python@3.8:", type=("build", "run"))
Missing build dep:
```python
    setup_requires=["setuptools>=38.6.0"],                                               
```

2023-09-27 16:56 UTC, GeorgeJuniorGG commented on var/spack/repos/builtin/packages/py-dynaconf/package.py
> +    depends_on("python@3.8:", type=("build", "run"))
Just added it, thanks!

2023-10-02 19:56 UTC, tldahlgren approved these changes
LGTM

2023-10-02 19:57 UTC, tldahlgren commented
I'm able to successfully build the package.

2023-10-03 11:23 UTC, adamjstewart approved these changes

2023-10-03 11:23 UTC, merged