Add pyepics package
LLNL/spack pull request #39763
Opened 2023-09-02 17:00 UTC by MarcoMontevechiFilho1

As part of UNICAMP's project with professor @hyviquel

2023-09-06 21:44 UTC, tldahlgren reviewed
Confirmed the homepage and version sha256.  Adding @adamjstewart since he's the python package maintainer.

2023-09-11 20:06 UTC, adamjstewart requested changes

2023-09-11 20:06 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-epics/package.py
> +class PyEpics(PythonPackage):
Package name should be `py-pyepics`

2023-09-11 20:06 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-epics/package.py
> +    url = "https://files.pythonhosted.org/packages/6c/cd/f97b676b6903e6f88bfced3817964559c20a1e3c6cd5244fa188f76fff75/pyepics-3.5.1.tar.gz"
https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#id2

2023-09-11 20:06 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-epics/package.py
> +    depends_on("py-setuptools", type="build")
```suggestion
    depends_on("py-setuptools", type=("build", "run"))
```

2024-02-17 22:16 UTC, alecbcs commented
Going to close this PR due to a lack of response after review feedback. @marcomontevechi1 happy to reopen if you still want to get this merged and have time to work on it.

2024-02-17 22:16 UTC, closed without merging