adds noisepy-seis along with its dependencies
LLNL/spack pull request #39764
Opened 2023-09-02 19:17 UTC by francislz

FYI Professor @hyviquel

2023-09-02 22:07 UTC, adamjstewart requested changes
If you're new to Python packaging it's helpful to read https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html

2023-09-02 22:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-aiobotocore/package.py
>      version("1.2.1", sha256="58cc422e65fc89f7cb78eca740d241ac8e15f39f6b308cc23152711e8a987d45")
Need to add upper bounds on deps

2023-09-02 22:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-annotated-types/package.py
> +    depends_on("py-typing-extensions@4.1.1:", type=("build", "run"))
```suggestion
    depends_on("py-hatchling", type="build")
    depends_on("py-typing-extensions@4:", when="^python@:3.8", type=("build", "run"))
```

2023-09-02 22:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-datetimerange/package.py
> +    depends_on("py-typepy@1.3.1", type=("build", "run"))
```suggestion
    depends_on("py-python-dateutil@2.4.2:2", type=("build", "run"))
    depends_on("py-typepy@1+datetime", type=("build", "run"))
```

2023-09-02 22:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-mbstrdecoder/package.py
> +    depends_on("py-chardet", type=("build", "run"))
```suggestion
    depends_on("py-setuptools@61:", type="build")
    depends_on("py-chardet@3.0.4:5", type=("build", "run"))
```

2023-09-02 22:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-noisepy-seis/package.py
> +    depends_on("py-setuptools", type=("build", "run"))
```suggestion
    depends_on("python@3.9:3.10", type=("build", "run"))
    depends_on("py-hatchling", type="build")
    depends_on("py-hatch-vcs", type="build")
```

2023-09-02 22:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-noisepy-seis/package.py
> +    depends_on("py-pydantic-yaml@1.1.1:", type=("build", "run"))
Many of these are missing upper bounds:
```toml
dependencies = [
    "DateTimeRange>=2.0.0,<3.0.0",
    "numpy>=1.22.0, <2.0.0",
    "h5py>=3.8.0,<4.0.0",
    "pandas>=1.5.3,<2.0.0",
    "numba>=0.57.0,<1.0.0",
    "pyasdf>=0.7.5,<1.0.0",
    "pycwt>=0.3.0a22,<1.0.0",
    "diskcache>=5.6.1,<6.0.0",
    "fsspec>=2023.4.0,<2024.0.0",
    "s3fs==2023.4.0,<2024.0.0",
    "zarr>=2.14.2,<3.0.0",
    "aiobotocore==2.5.2", # "2.5.3 is broken"
    "pydantic==2.0.0",
    "PyYAML==6.0",
    "pydantic-yaml==1.0",
]
```

2023-09-02 22:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pycwt/package.py
> +    depends_on("py-tqdm@4.62.3:", type=("build", "run"))
Deps are incorrect:
```toml
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
dependencies = [
    "numpy>=1.24, <2",
    "scipy>=1.10, <2",
    "matplotlib>=3.7, <4",
    "tqdm>=4.65, <5"
]
requires-python = ">=3.8"
```

2023-09-02 22:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pydantic-core/package.py
> +    depends_on("py-typing-extensions@4.6.3:", type=("build", "run"))
Deps are incorrect:
```toml
requires = [
    'maturin>=1,<2',
    'typing-extensions >=4.6.0,!=4.7.0'
]
dependencies = [
    'typing-extensions >=4.6.0,!=4.7.0'
]
```

2023-09-02 22:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pydantic-yaml/package.py
> +    depends_on("py-typing_extensions@4.5.0:", type=("build", "run"))
Deps are incorrect

2023-09-02 22:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pydantic/package.py
>      depends_on("py-typing-extensions@3.7.4.3:", type=("build", "run"))
Deps are incorrect

2023-09-02 22:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-s3fs/package.py
Deps need to be updated

2023-09-02 22:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-typepy/package.py
> +    depends_on("py-mbstrdecoder", type=("build", "run"))
Deps are incorrect

2023-09-03 16:39 UTC, francislz commented
@adamjstewart Thanks for the review ! I changed the PR to make a simpler contribution and get myself used with Python packaging first. Sorry for the trouble.

2023-09-05 23:45 UTC, adamjstewart requested changes

2023-09-05 23:45 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-obspy/package.py
> +    depends_on("py-setuptools", type="build")
Requires Python 3.8+

Missing deps:
```python
INSTALL_REQUIRES = [                                                                     
    'numpy>=1.20',                                                                       
    'scipy>=1.7',                                                                        
    'matplotlib>=3.3',                                                                   
    'lxml',                                                                              
    'setuptools',                                                                        
    'sqlalchemy',                                                                        
    'decorator',                                                                         
    'requests',                                                                          
]      
```

2024-02-17 22:12 UTC, closed without merging

2024-02-17 22:12 UTC, alecbcs commented
Going to close this PR due to a lack of response from review feedback. @francislz  happy to reopen if you still want to get this merged and have time to work on it.