acts: impose cxxstd variant on geant4 dependency
LLNL/spack pull request #39767
Opened 2023-09-03 20:25 UTC by wdconinc

When ACTS builds the Geant4 example, it injects both the `-std=gnu++20` from ACTS and the `-std=c++17` from Geant4, which leads to build failures.

<details><summary>build failure details</summary>
<pre>
#45 840.7      920     [ 70%] Building CXX object Examples/Algorithms/Geant4/CMakeFiles/A
#45 840.7              ctsExamplesGeant4.dir/src/SensitiveSurfaceMapper.cpp.o
#45 840.7      921     cd /tmp/root/spack-stage/spack-stage-acts-28.0.0-tgwsfgpujxgirqwdo
#45 840.7              vpgvmeykwgi5jxl/spack-build-tgwsfgp/Examples/Algorithms/Geant4 && 
#45 840.7              /opt/spack/lib/spack/env/gcc/g++ -DACTS_CONCEPTS_SUPPORTED -DACTS_
#45 840.7              ENABLE_LOG_FAILURE_THRESHOLD -DACTS_LOG_FAILURE_THRESHOLD=MAX -DAc
#45 840.7              tsExamplesGeant4_EXPORTS -DBOOST_SPIRIT_USE_PHOENIX_V3 -DDD4HEP_US
#45 840.7              E_XERCESC -DG4LIB_BUILD_DLL -DG4UI_USE_QT -DG4UI_USE_TCSH -DG4VIS_
#45 840.7              USE_OPENGL -DG4VIS_USE_OPENGLQT -DG4VIS_USE_OPENGLX -DG4VIS_USE_QT
#45 840.7              3D -DG4VIS_USE_RAYTRACERX -DG4VIS_USE_TOOLSSG_QT_GLES -DG4VIS_USE_
#45 840.7              TOOLSSG_X11_GLES -DPTL_BUILD_DLL -DQT_3DCORE_LIB -DQT_3DEXTRAS_LIB
#45 840.7               -DQT_3DINPUT_LIB -DQT_3DLOGIC_LIB -DQT_3DRENDER_LIB -DQT_CORE_LIB
#45 840.7               -DQT_GAMEPAD_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT
#45 840.7              _OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -I/tmp/root/spa
#45 840.7              ck-stage/spack-stage-acts-28.0.0-tgwsfgpujxgirqwdovpgvmeykwgi5jxl/
#45 840.7              spack-src/Examples/Algorithms/Geant4/include -I/tmp/root/spack-sta
#45 840.7              ge/spack-stage-acts-28.0.0-tgwsfgpujxgirqwdovpgvmeykwgi5jxl/spack-
#45 840.7              src/Core/include -I/tmp/root/spack-stage/spack-stage-acts-28.0.0-t
#45 840.7              gwsfgpujxgirqwdovpgvmeykwgi5jxl/spack-build-tgwsfgp/Core -I/tmp/ro
#45 840.7              ot/spack-stage/spack-stage-acts-28.0.0-tgwsfgpujxgirqwdovpgvmeykwg
#45 840.7              i5jxl/spack-src/Examples/Framework/include -I/tmp/root/spack-stage
#45 840.7              /spack-stage-acts-28.0.0-tgwsfgpujxgirqwdovpgvmeykwgi5jxl/spack-sr
#45 840.7              c/Fatras/include -I/tmp/root/spack-stage/spack-stage-acts-28.0.0-t
#45 840.7              gwsfgpujxgirqwdovpgvmeykwgi5jxl/spack-src/Plugins/FpeMonitoring/in
#45 840.7              clude -I/tmp/root/spack-stage/spack-stage-acts-28.0.0-tgwsfgpujxgi
#45 840.7              rqwdovpgvmeykwgi5jxl/spack-src/Examples/Detectors/TelescopeDetecto
#45 840.7              r/include -I/tmp/root/spack-stage/spack-stage-acts-28.0.0-tgwsfgpu
#45 840.7              jxgirqwdovpgvmeykwgi5jxl/spack-src/Examples/Detectors/DD4hepDetect
#45 840.7              or/include -I/tmp/root/spack-stage/spack-stage-acts-28.0.0-tgwsfgp
#45 840.7              ujxgirqwdovpgvmeykwgi5jxl/spack-src/Plugins/DD4hep/include -I/tmp/
#45 840.7              root/spack-stage/spack-stage-acts-28.0.0-tgwsfgpujxgirqwdovpgvmeyk
#45 840.7              wgi5jxl/spack-src/Plugins/TGeo/include -I/tmp/root/spack-stage/spa
#45 840.7              ck-stage-acts-28.0.0-tgwsfgpujxgirqwdovpgvmeykwgi5jxl/spack-src/Pl
#45 840.7              ugins/Identification/include -isystem /opt/software/linux-debian12
#45 840.7              -x86_64_v2/gcc-12.2.0/geant4-11.1.2.east-ibfn3k7msz7ubtjd2aserdlyl
#45 840.7              7kpmbsp/include/Geant4 -isystem /opt/software/linux-debian12-x86_6
#45 840.7              4_v2/gcc-12.2.0/boost-1.82.0-52hnlpxsrir4ac7lhd6znsxnscwfcvvg/incl
#45 840.7              ude -isystem /opt/software/linux-debian12-x86_64_v2/gcc-12.2.0/eig
#45 840.7              en-3.4.0-kgxjkle2vrkqlsinu3wfvmesakl2xdrt/include/eigen3 -isystem 
#45 840.7              /opt/software/linux-debian12-x86_64_v2/gcc-12.2.0/root-6.28.04-nz5
#45 840.7              jnp5voyds75o2r7chipss4ohl45k3/include/root -isystem /opt/software/
#45 840.7              linux-debian12-x86_64_v2/gcc-12.2.0/intel-tbb-2020.3-h2uvzxumkgbg4
#45 840.7              lrr6zyjrd4ls4gij7th/include -isystem /opt/software/linux-debian12-
#45 840.7              x86_64_v2/gcc-12.2.0/clhep-2.4.6.4-7pma6e3oe6dlg7tmad43jduw3q6hhdo
#45 840.7              u/include -isystem /opt/software/linux-debian12-x86_64_v2/gcc-12.2
#45 840.7              .0/expat-2.5.0-47cmm7nehipjtvcs3s6lnoowdq4t762a/include -isystem /
#45 840.7              opt/software/linux-debian12-x86_64_v2/gcc-12.2.0/libice-1.0.9-qpb6
#45 840.7              z5ugi2zohrtfjmlodqvahfufmaee/include -isystem /opt/software/linux-
#45 840.7              debian12-x86_64_v2/gcc-12.2.0/libsm-1.2.3-tl36bdjawdzqdxvhbdvj4wqq
#45 840.7              esi6ob5d/include -isystem /opt/software/linux-debian12-x86_64_v2/g
#45 840.7              cc-12.2.0/xproto-7.0.31-z4sp2ngysh6onjxoljpoaqfzp3za7xu6/include -
#45 840.7              isystem /opt/software/linux-debian12-x86_64_v2/gcc-12.2.0/libxext-
#45 840.7              1.3.3-3ogdhs3x4krwvukcbcrepxmncw2qzbpu/include -isystem /opt/softw
#45 840.7              are/linux-debian12-x86_64_v2/gcc-12.2.0/libxmu-1.1.4-rkphukygsbr4h
#45 840.7              ets7cq7hg43adsfuzkd/include -isystem /opt/software/linux-debian12-
#45 840.7              x86_64_v2/gcc-12.2.0/libxt-1.1.5-efk4c52y2q4z6sps2x7roqzgx2xnjpax/
#45 840.7              include -isystem /opt/software/linux-debian12-x86_64_v2/gcc-12.2.0
#45 840.7              /qt-5.15.9-yyzwpqgarhuy7wvf3tunm6pqezy3ju2u/include -isystem /opt/
#45 840.7              software/linux-debian12-x86_64_v2/gcc-12.2.0/qt-5.15.9-yyzwpqgarhu
#45 840.7              y7wvf3tunm6pqezy3ju2u/include/QtCore -isystem /opt/software/linux-
#45 840.7              debian12-x86_64_v2/gcc-12.2.0/qt-5.15.9-yyzwpqgarhuy7wvf3tunm6pqez
#45 840.7              y3ju2u/./mkspecs/linux-g++ -isystem /opt/software/linux-debian12-x
#45 840.7              86_64_v2/gcc-12.2.0/qt-5.15.9-yyzwpqgarhuy7wvf3tunm6pqezy3ju2u/inc
#45 840.7              lude/QtGui -isystem /opt/software/linux-debian12-x86_64_v2/gcc-12.
#45 840.7              2.0/mesa-22.1.6-wvkgm3s4wgoclk323lmohtw2xfjoofcm/include -isystem 
#45 840.7              /opt/software/linux-debian12-x86_64_v2/gcc-12.2.0/qt-5.15.9-yyzwpq
#45 840.7              garhuy7wvf3tunm6pqezy3ju2u/include/QtWidgets -isystem /opt/softwar
#45 840.7              e/linux-debian12-x86_64_v2/gcc-12.2.0/qt-5.15.9-yyzwpqgarhuy7wvf3t
#45 840.7              unm6pqezy3ju2u/include/QtOpenGL -isystem /opt/software/linux-debia
#45 840.7              n12-x86_64_v2/gcc-12.2.0/qt-5.15.9-yyzwpqgarhuy7wvf3tunm6pqezy3ju2
#45 840.7              u/include/QtPrintSupport -isystem /opt/software/linux-debian12-x86
#45 840.7              _64_v2/gcc-12.2.0/qt-5.15.9-yyzwpqgarhuy7wvf3tunm6pqezy3ju2u/inclu
#45 840.7              de/Qt3DCore -isystem /opt/software/linux-debian12-x86_64_v2/gcc-12
#45 840.7              .2.0/qt-5.15.9-yyzwpqgarhuy7wvf3tunm6pqezy3ju2u/include/QtNetwork 
#45 840.7              -isystem /opt/software/linux-debian12-x86_64_v2/gcc-12.2.0/qt-5.15
#45 840.7              .9-yyzwpqgarhuy7wvf3tunm6pqezy3ju2u/include/Qt3DExtras -isystem /o
#45 840.7              pt/software/linux-debian12-x86_64_v2/gcc-12.2.0/qt-5.15.9-yyzwpqga
#45 840.7              rhuy7wvf3tunm6pqezy3ju2u/include/Qt3DRender -isystem /opt/software
#45 840.7              /linux-debian12-x86_64_v2/gcc-12.2.0/qt-5.15.9-yyzwpqgarhuy7wvf3tu
#45 840.7              nm6pqezy3ju2u/include/Qt3DInput -isystem /opt/software/linux-debia
#45 840.7              n12-x86_64_v2/gcc-12.2.0/qt-5.15.9-yyzwpqgarhuy7wvf3tunm6pqezy3ju2
#45 840.7              u/include/QtGamepad -isystem /opt/software/linux-debian12-x86_64_v
#45 840.7              2/gcc-12.2.0/qt-5.15.9-yyzwpqgarhuy7wvf3tunm6pqezy3ju2u/include/Qt
#45 840.7              3DLogic -isystem /opt/software/linux-debian12-x86_64_v2/gcc-12.2.0
#45 840.7              /xerces-c-3.2.4-g233npbtqnly6pxggbwrsuplsamqbyqb/include -isystem 
#45 840.7              /opt/software/linux-debian12-x86_64_v2/gcc-12.2.0/zlib-1.2.13-4qrm
#45 840.7              ahtit7zrirqtj3u43g6fetkuhhev/include -isystem [...]

2023-09-03 21:23 UTC, wdconinc commented
@spackbot fix style

2023-09-04 00:21 UTC, sethrj approved these changes

2023-09-04 03:36 UTC, HadrienG2 approved these changes

2023-09-04 05:58 UTC, alalazo requested changes
```
PKG-DIRECTIVES: 1 issue found
1. acts: wrong variant used for a dependency in a 'depends_on' directive
    invalid values for variant "cxxstd" in package "geant4": ['20'] in package 'geant4'
    in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/acts/package.py
```

2023-09-04 12:45 UTC, wdconinc commented
I know this fails audit because geant4 needs cxxstd 20 support, which means xerces-c, vecgeom, boost etc needs cxxstd 20 support. I'm working on that too, but IMHO this audit rule is stricter than needed when it blocks fixes of build failures by requiring a cascade of additional support...

Here's one of them already:
-
https://github.com/spack/spack/pull/39769

2023-09-04 13:06 UTC, alalazo commented
> I'm working on that too, but IMHO this audit rule is stricter than needed when it blocks fixes of build failures by requiring a cascade of additional support...

I don't agree with that. It's not the audit that blocks the fixes, the audit spotted an issue. Can't you filter out that directive, added in a for loop, and add it back when you'll add C++20 support ?

2023-09-04 14:11 UTC, sethrj commented
@wdconinc The original issue you're having might also be an error in how ACTS is linking against Geant4: since it uses cmake, it should be using the target properties
```cmake
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
```
set by the Geant4 config.

It's likely that ACTS is mistakenly adding `Geant4_CXX_FLAGS` to its own list of C++ flags, which would add both the c++17 flags and whatever flags CMake sets.

2023-09-04 17:12 UTC, wdconinc commented
Here's the sequence of other PRs to avoid having to put a workaround in place here:
- #39777
- #39784
- #39785

2023-10-01 14:50 UTC, wdconinc commented
All dependencies of this PR are now satisfied and merged (see comment https://github.com/spack/spack/pull/39767#issuecomment-1705550894 above), and this now passes all audit checks.

2023-10-01 21:55 UTC, sethrj commented
Requires @alalazo to dismiss stale review.

2023-10-02 03:49 UTC, alalazo approved these changes

2023-10-02 03:49 UTC, merged