Update of robotframework package
LLNL/spack pull request #39772
Opened 2023-09-04 02:42 UTC by nanborges

-  Updating the package url and also the versions and dependencies
-  Task given from professor @hyviquel, at UNICAMP

2023-09-05 23:53 UTC, adamjstewart requested changes

2023-09-05 23:53 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-robotframework/package.py
> +    url = "https://files.pythonhosted.org/packages/c6/37/fc94979077241a09f31f347cbae401c9f62705eadd441a392285537e603c/robotframework-6.1.1.zip"
https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#id2

2023-09-05 23:53 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-robotframework/package.py
> +    It has simple plain text syntax and it can be extended easily with generic and custom libraries. You can learn more about ROBOT FRAMEWORK here: https://robotframework.org/
These lines are too long, we have a 100 char limit

2023-09-05 23:53 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-robotframework/package.py
> -    version("3.2.1", sha256="9805faa0990125ff2c9689b673448d5f47e78470e7a8e95af1606a775fa8379f")
We don't normally remove older versions without first deprecating them

2023-09-05 23:53 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-robotframework/package.py
> +    depends_on("python@3.6:", type=("build", "run"))
Spack only supports Python 3.7+ anyway so this line isn't necessary

2024-02-17 22:12 UTC, alecbcs commented
Going to close this PR due to a lack of response from review feedback. @nanborges happy to reopen if you still want to get this merged and have time to work on it.

2024-02-17 22:12 UTC, closed without merging