Add pytorch-randaugmnet package
LLNL/spack pull request #39781
Opened 2023-09-04 14:36 UTC by sthalles

FYI @hyviquel

2023-09-06 21:15 UTC, tldahlgren reviewed
Confirmed the homepage and version sha256.  Adding @adamjstewart since he is the python package maintainer.

2023-09-11 20:05 UTC, adamjstewart requested changes

2023-09-11 20:05 UTC, adamjstewart commented on var/spack/repos/builtin/packages/pytorch-randaugment/package.py
> +class PytorchRandaugment(PythonPackage):
Package name should be `py-randaugment`

2023-09-11 20:05 UTC, adamjstewart commented on var/spack/repos/builtin/packages/pytorch-randaugment/package.py
> +    url = "https://files.pythonhosted.org/packages/ac/a3/0d76507a2048b38fe9cc77f85b8ac008543b0c2c237feb5a1a1a882d46aa/randaugment-1.0.2.tar.gz"
https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#id2

2023-09-11 20:05 UTC, adamjstewart commented on var/spack/repos/builtin/packages/pytorch-randaugment/package.py
> +    depends_on("python", type=("build", "run"))
This is already added by the base class and can be removed

2023-09-11 20:05 UTC, adamjstewart commented on var/spack/repos/builtin/packages/pytorch-randaugment/package.py
> +    depends_on("py-torchvision", type=("build", "run"))
Package does not depend on torch/torchvision

2024-02-17 22:14 UTC, alecbcs commented
Going to close this PR due to a lack of response after review feedback. @sthalles happy to reopen if you still want to get this merged and have time to work on it.

2024-02-17 22:14 UTC, closed without merging