add timewarrior
LLNL/spack pull request #39783
Opened 2023-09-04 15:52 UTC by ieremies

Add the TimeWarrior package.

@hyviquel

2023-09-06 01:15 UTC, tldahlgren requested changes
The package.py file is in the wrong directory.

2023-09-06 01:15 UTC, tldahlgren commented on var/spack/repos/builtin/packages/package.py
This package should be in a `time-warrior` subdirectory of `var/spack/repos/builtin/packages`.

2023-09-06 01:17 UTC, tldahlgren commented on var/spack/repos/builtin/packages/package.py
You can see this in the documentation at https://spack-tutorial.readthedocs.io/en/latest/tutorial_packaging.html#creating-the-package-file, though that package is in `tutorial` repository instead of `builtin`.

2024-02-17 22:13 UTC, alecbcs commented
Going to close this PR due to a lack of response after review feedback. @ieremies happy to reopen if you still want to get this merged and have time to work on it.

2024-02-17 22:13 UTC, closed without merging