Add OMPC Bench Merge package.
LLNL/spack pull request #39791
Opened 2023-09-05 01:35 UTC by VitoriaDMP

@hyviquel

2023-09-06 00:40 UTC, tldahlgren reviewed
Confirmed the home page and version sha256.

2023-09-06 00:41 UTC, tldahlgren commented
Adding @adamjstewart since he's the python package guru/maintainer.

2023-09-11 20:02 UTC, adamjstewart requested changes

2023-09-11 20:02 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ompcb-merge/package.py
> +    url = "https://github.com/VitoriaDMP/ompcb-merge/raw/master/ompcb-merge-1.0.tar.gz"
I would rather use the official download source than a random file on GitHub.

2023-09-11 20:02 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ompcb-merge/package.py
> +class PyOmpcbMerge(PythonPackage):
Why is it called ompcb-merge and not ompcbench?

2023-09-11 20:02 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ompcb-merge/package.py
> +    depends_on("py-click@8.0:", type=("build"))
Seems to be missing a lot of deps

2024-11-27 13:16 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2024-11-27 13:16 UTC, closed without merging