coin3d: apply upstream patches to fix build on Centos 8
LLNL/spack pull request #39839
Opened 2023-09-06 08:05 UTC by aumuell

fixes undefined references to dlerror, dlopen, dlsym, dlclose and XDefaultScreenOfDisplay, XScreenNumberOfScreen, XCreatePixmap, XFree, XFreePixmap, XCloseDisplay, XOpenDisplay

2023-09-06 08:11 UTC, aumuell commented
@spackbot fix style

2023-09-11 20:26 UTC, alalazo requested changes
```console
$ spack stage coin3d@4.0.0
==> Fetching https://mirror.spack.io/_source-cache/archive/e4/e4f4bd57804b8ed0e017424ad2e45c112912a928b83f86c89963df9015251476.tar.gz
==> Fetching https://github.com/coin3d/coin/commit/962e613609ba93301999f83e283b7f489dfac503.patch?full_index=1
==> Fetching https://github.com/coin3d/coin/commit/9a36b15d66c5e340cd8695415ce5867ad07ee2bb.patch?full_index=1
==> Fetching https://github.com/coin3d/coin/commit/58a1b4c3e968f96d3a2091fa5cb625f360ce6811.patch?full_index=1
==> Error: sha256 checksum failed for /tmp/culpo/spack-stage/spack-stage-patch-a7c41cb67e44d43138524185a0688e2e64afb1f40e917c09195739fcfb998a92/962e613609ba93301999f83e283b7f489dfac503.patch?full_index=1
Expected a7c41cb67e44d43138524185a0688e2e64afb1f40e917c09195739fcfb998a92 but got 33da720d6ff50916403320c47c72600737bdfb4113a4d527bc3fa9e8fe368f49. File size = 676 bytes. Contents = b'From 962e613609b...AJOR_VERSION 4)\n'
```

2023-09-12 08:41 UTC, aumuell commented
Sorry, after editing the patch urls I did not think about checking the patch contents again... Should be fixed now.

2023-09-18 15:16 UTC, alalazo approved these changes

2023-09-18 15:16 UTC, merged