Dakota 6.18 Upgrade
LLNL/spack pull request #39882
Opened 2023-09-07 22:32 UTC by tdrayna

- Removed older versions due to change from SNL internal gitlab to GitHub
- Does not support 6.16 or 6.17 due to bug in git submodules

2023-09-07 22:35 UTC, tdrayna commented on var/spack/repos/builtin/packages/dakota/package.py
> +    depends_on("eigen")
I'm not 100% sure if this is needed.

2023-09-11 15:38 UTC, alalazo requested changes

2023-09-11 15:38 UTC, alalazo commented on var/spack/repos/builtin/packages/dakota/package.py
> -    version("6.3", sha256="0fbc310105860d77bb5c96de0e8813d75441fca1a5e6dfaf732aa095c4488d52")
Can we deprecate these versions instead of removing them directly?

2023-09-11 16:02 UTC, tdrayna commented on var/spack/repos/builtin/packages/dakota/package.py
> -    version("6.3", sha256="0fbc310105860d77bb5c96de0e8813d75441fca1a5e6dfaf732aa095c4488d52")
Possibly. But I don't think these downloads are available anymore from the old URL:

https://dakota.sandia.gov/sites/default/files/distributions/public/dakota-6.12-release-public.src.tar.gz

2023-09-11 16:05 UTC, tdrayna commented on var/spack/repos/builtin/packages/dakota/package.py
> -    version("6.3", sha256="0fbc310105860d77bb5c96de0e8813d75441fca1a5e6dfaf732aa095c4488d52")
You can get older versions from github.com but the .gitmodules file will need to be patched after fetching.

2023-09-11 16:06 UTC, alalazo commented on var/spack/repos/builtin/packages/dakota/package.py
> -    version("6.3", sha256="0fbc310105860d77bb5c96de0e8813d75441fca1a5e6dfaf732aa095c4488d52")
If we did our mirroring correctly they might still be available through https://mirror.spack.io

2023-09-11 16:07 UTC, alalazo commented on var/spack/repos/builtin/packages/dakota/package.py
> -    version("6.3", sha256="0fbc310105860d77bb5c96de0e8813d75441fca1a5e6dfaf732aa095c4488d52")
![Screenshot from 2023-09-11 18-06-51](https://github.com/spack/spack/assets/4199709/fcc8d249-3661-45a1-b7de-d484fd6fc141)

2023-09-11 16:07 UTC, tdrayna commented on var/spack/repos/builtin/packages/dakota/package.py
> -    version("6.3", sha256="0fbc310105860d77bb5c96de0e8813d75441fca1a5e6dfaf732aa095c4488d52")
Oh, ok. I can make this fix then. I'll try to get to it today.

2023-09-11 17:17 UTC, tdrayna commented on var/spack/repos/builtin/packages/dakota/package.py
> -    version("6.3", sha256="0fbc310105860d77bb5c96de0e8813d75441fca1a5e6dfaf732aa095c4488d52")
Quick question:

Is there a spack way to specify the url based on the version? I'm seeing one package that defines a `url_for_version` function.

2023-09-11 20:05 UTC, alalazo approved these changes

2023-09-11 20:06 UTC, merged