armpl-gcc: add macOS support and map rocky9 to RHEL-9
LLNL/spack pull request #39893
Opened 2023-09-08 11:56 UTC by annop-w

2023-09-11 15:56 UTC, alalazo requested changes

2023-09-11 15:56 UTC, alalazo commented on var/spack/repos/builtin/packages/armpl-gcc/package.py
> +        return "darwin"
The name of this function is kind of misleading now. `darwin` is the platform, not the OS.

2023-09-11 15:56 UTC, alalazo commented on var/spack/repos/builtin/packages/armpl-gcc/package.py
> +        )
Can we use f-strings here?

2023-09-15 12:22 UTC, annop-w commented on var/spack/repos/builtin/packages/armpl-gcc/package.py
> +        return "darwin"
Done.

2023-09-15 12:22 UTC, annop-w commented on var/spack/repos/builtin/packages/armpl-gcc/package.py
> +        )
Done.

2023-09-26 10:27 UTC, annop-w commented
@alalazo Could you please give this a quick look ? Thank  you.

2023-10-11 21:24 UTC, annop-w commented
@alalazo Do you have any more comment on this one ? We'll have an update for the next release pretty soon. So, it would be great to have this one in.

2023-10-13 14:39 UTC, closed without merging