new package: py-langchain
LLNL/spack pull request #39903
Opened 2023-09-09 01:01 UTC by julianolm

# 🦜️🔗 LangChain
⚡ Building applications with LLMs through composability ⚡
Official Repo: https://github.com/langchain-ai/langchain

2023-09-11 21:22 UTC, adamjstewart requested changes

2023-09-11 21:22 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-langchain/package.py
> +    depends_on("py-pytest")
Not required deps

2023-09-11 21:22 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-langchain/package.py
> +
Missing build dep:
```toml
[build-system]
requires = ["poetry-core>=1.0.0"]
```

2023-09-11 21:22 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-langchain/package.py
> +    depends_on("python@3.8:", type=("build", "run"))
```suggestion
    depends_on("python@3.8.1:3", type=("build", "run"))
```

2023-09-11 21:22 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-langchain/package.py
> +    depends_on("py-numpy", type=("build", "run"))
Missing version requirements, see https://python-poetry.org/docs/dependency-specification/ for docs. Can you also keep these in the same order as `pyproject.toml`? Makes it easier for me to review.
```toml
[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
pydantic = ">=1,<3"
SQLAlchemy = ">=1.4,<3"
requests = "^2"
PyYAML = ">=5.3"
numpy = "^1"
dataclasses-json = "^0.5.7"
tenacity = "^8.1.0"
aiohttp = "^3.8.3"
async-timeout = {version = "^4.0.0", python = "<3.11"}
numexpr = "^2.8.4"
langsmith = "~0.0.21"
```

2024-02-17 22:18 UTC, closed without merging

2024-02-17 22:18 UTC, alecbcs commented
Going to close this PR due to a lack of response after review feedback. @julianolm happy to reopen if you still want to get this merged and have time to work on it.