Always apply Python unixcompilers.py `rpath` fix, not just on cray
LLNL/spack pull request #39929
Opened 2023-09-11 20:21 UTC by climbfuji

## Description

Based on the conversation in the spack slack channel (https://spackpm.slack.com/archives/C5W7NKZJT/p1694393880262699), it was concluded that it would be safe to unconditionally apply the patch for the `rpath` linker flag in spack's Python installation, not just when the system is detected as Cray. The need for this came up when building on a Cray that was detected as a "new" Cray due to its `craype` version, but that still required using the Cray compiler wrappers.

Since there are no compilers in spack that understand `-R` but don't understand `-Wl,-R`, it's safe to apply this patch regardless of the platform.

Actual change: rename `var/spack/repos/builtin/packages/python/cray-rpath-3.1.patch` as `var/spack/repos/builtin/packages/python/rpath-non-gcc.patch` and apply unconditionally.

## Testing

Tested on the Navy's Narwhal machine (Cray) and a couple of other HPCs (non Cray) with GNU and Intel.

2023-09-11 21:57 UTC, adamjstewart requested changes

2023-09-11 21:57 UTC, adamjstewart commented on var/spack/repos/builtin/packages/python/package.py
> +    patch("rpath-non-gcc.patch")
```suggestion
    patch("rpath-non-gcc.patch", when="@:3.11")
```
The distutils module will be removed in Python 3.12 so there won't be anything to patch.

2023-09-11 22:02 UTC, adamjstewart approved these changes

2023-09-12 17:45 UTC, alecbcs commented
@spackbot run pipeline

2023-09-20 16:47 UTC, scheibelp commented
@spackbot run pipeline

2023-09-20 23:51 UTC, scheibelp commented
@spackbot run pipeline

2023-09-22 19:56 UTC, scheibelp commented
@spackbot run pipeline

2023-09-26 08:38 UTC, merged