[add] py-graphene-tornado: new recipe, required by py-cylc-uiserver
LLNL/spack pull request #39985
Opened 2023-09-13 13:54 UTC by LydDeb

2023-09-13 16:41 UTC, tldahlgren reviewed
Confirmed the homepage and version sha256.  Adding python package maintainer.

2023-09-13 22:31 UTC, manuelakuhn reviewed
Depends on #39988 and #39984

2023-09-13 22:31 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-graphene-tornado/package.py
> +    depends_on("python@3.6:", type=("build", "run"))
Spack only support `python@3.7:` anyway, so this line is not needed.

2023-09-13 22:31 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-graphene-tornado/package.py
> +    depends_on("py-graphene@2.1:2", type=("build", "run"), when="@:2")
Because there is only one version in this package, the `when` statement is not needed here.

2023-09-13 22:31 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-graphene-tornado/package.py
> +    depends_on("py-pytest", type=("build", "run"))
This is only listed in `setup_requires` and not in `install_requires` and so should only be a `build` dependency.

2023-09-26 10:12 UTC, manuelakuhn submitted a review, later dismissed

2023-09-26 13:29 UTC, adamjstewart requested changes

2023-09-26 13:29 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-graphene-tornado/package.py
> +    depends_on("py-werkzeug@0.12.2", type=("build"))
```suggestion
    depends_on("py-jinja2@2.10.1:", type=("build", "run"))
    depends_on("py-tornado@5.1.0:", type=("build", "run"))
    depends_on("py-werkzeug@0.12.2", type=("build", "run"))
```

2023-10-09 09:34 UTC, manuelakuhn approved these changes

2023-10-14 17:24 UTC, adamjstewart approved these changes

2023-10-14 17:25 UTC, merged