Per-os-config feature -- third time is the charm?
LLNL/spack pull request #40018
Opened 2023-09-14 15:20 UTC by marcmengel

The previous pull requests for this #16834 and   #31028 got funky after rebasing, so doing a fresh branch. 

This is an implementation for Feature requests  #31026, and #2700  fixed for latest version.
 
It just adds an Operating System Release (i.e. "scientific7" "almalinux9") config branch along the lines of the the
platform one ("linux" "MacOs").   Many configs (i.e. packages.yaml) are more specific than just platform, and this
lets you support multiple OS versions in one spack tree.

2023-09-14 17:14 UTC, gartung submitted a review, later dismissed

2023-09-27 16:51 UTC, marcmengel commented
@scheibelp  -- pinging you to include this in your more general scope cleanup/changes.

2023-09-27 19:27 UTC, scheibelp requested changes
I have a couple preliminary requests:

* No need for tests
* OS scope should live inside platform scope

Also, It might make sense to augment https://spack.readthedocs.io/en/latest/configuration.html#platform-specific-scopes with a mention of OS-specific scopes (the list itself doesn't need to expand, I think the text that follows can explain there is another level).

Other considerations (these aren't problems, I'm just making note):

* Correct behavior of `highest_precedence_non_platform_scope` seems to be preserved (I would say that OS scopes should be excluded as well as platform scopes, which this would seem to do)
* Augmenting of command line scopes with per-OS scope (analogous to platform) seems reasonable
* Overall, I think this will improve behavior of Spack on shared filesystems (we have other plans that should also help, like removing the `~` scope and just using a scope associated with the Spack instance, but for people who use the same spack instance on a shared FS across different system logins, this should be useful)

2023-09-27 19:27 UTC, scheibelp commented on lib/spack/spack/test/cmd/config.py
> +    )
Note this test should likely be rearranged if it's intent is similar to `test_config_add_override`.

I'm of the opinion that this additional scope does not require its own test (the other tests already establish proper precedency rules for scopes, and this PR just adds another scope).

2023-09-27 19:27 UTC, scheibelp commented on lib/spack/spack/config.py
> +        _add_os_scope(cfg, ConfigScope, name, path)
I believe all scopes added here are reflected in `spack config --help`, which is why the unit tests are failing: they suggest running `spack commands --update-completion` (if you commit and push that, the unit tests should pass).

2023-09-27 19:27 UTC, scheibelp commented on lib/spack/spack/test/conftest.py
> +        for name in ["site", os.path.join("site", oss), "system", "user"]
Were you seeing errors without this?

I'm inclined to say it should be removed: not every scope we manage for general usage of spack needs to exist for the tests. Also, the ordering of this list reflects the ordering of precedence, which does not match the order in general spack (i.e. the OS-level config would normally have precedency over all these scopes in general usage of spack, but here, it is lower priority than system/user-level scope).

2023-09-27 19:27 UTC, scheibelp commented on lib/spack/spack/config.py
> +    cfg.push_scope(scope_type(os_name, os_path))
(minor) I'm of a mind to say that the OS-level scope should sit inside the platform directory, since I think it would be confusing to separately have a `linux` and a `rhel8` directory (i.e. if a user is `ls`ing these files). I think to support that, you can amend the `path` that is passed in.

2023-09-27 19:42 UTC, marcmengel commented on lib/spack/spack/test/conftest.py
> +        for name in ["site", os.path.join("site", oss), "system", "user"]
I added the test because the automated checks were whining about coverage.(although that didn't help). 
I'll pull them back out.

2023-09-27 22:03 UTC, marcmengel commented on lib/spack/spack/config.py
> +    cfg.push_scope(scope_type(os_name, os_path))
Moved it inside the platform directory.

2023-09-29 20:29 UTC, scheibelp commented
I'm having some ongoing discussions with folks about how we want to customize this:

* In at least one case at our own site, OS alone is not enough to distinguish the scope and we'd actually like to use a `platform-os-target` scope (logging in to the different systems, we *are* able to distinguish them with target). I think if we updated this to be specific down to the target level it would meet both our needs
* I'm chatting with @becker33 about other ways we might want to customize this

My goal is to have a clear path forward on this by the end of October 9 (this is delayed in part because I plan to be out next week).

2023-09-29 21:43 UTC, marcmengel commented
Actually, yes, doing platform, platform/os, platform/os/target  (mirroring the "spack arch" platform-os-target triple) has a
pleasing symmetry to it...  Here is that much, anyhow.

2023-11-01 14:56 UTC, marcmengel commented
Re-requesting review, as this now does all three of the platform/os/target subdirectories.

2023-11-01 19:22 UTC, gartung approved these changes, later dismissed

2023-11-16 21:22 UTC, greenc-FNAL commented
@scheibelp Ping?

2023-11-29 14:33 UTC, greenc-FNAL commented
@spackbot style

2023-11-29 15:03 UTC, greenc-FNAL commented
@scheibelp Ping?

2023-11-29 15:09 UTC, haampie commented
@spackbot help

2023-11-29 15:52 UTC, greenc-FNAL commented
@scheibelp Are we good to go here? I've fixed the style issue (whitespace only) and the only remaining failure is code coverage, but I believe you said tests weren't necessary? I'm not quite sure why GitHub keeps claiming that the branch can't be rebased, since I was able to rebase via `git` CLI without issue.

2024-03-26 17:51 UTC, greenc-FNAL commented
@scheibelp Hello?

2024-03-26 18:04 UTC, scheibelp commented
I have been getting a weekly reminder for this and it continually is not at the front of my queue.

The soonest I can guarantee looking at this is in two weeks (April 8th).

Changing the config storage location can have unexpected side effects, so I need to put some effort into chasing down the possible issues.

One thing that would need to change in this PR (in addition to a re-sync) is updating the docs at https://spack.readthedocs.io/en/latest/configuration.html#platform-specific-scopes

2024-03-26 21:55 UTC, greenc-FNAL commented
@scheibelp Understood, and thank you. PR has been re-synced, and documentation has been updated.

2024-04-09 01:25 UTC, scheibelp requested changes
One documentation request; also, I looked through the code base for references to platform scopes and see a couple:

* bootstrap.config._bootstrap_config_scopes appears to replicate some logic from spack.config.create/_add_platform_scope, I'm not sure if this should change: The issues that prompt the existence of this PR would also possibly benefit from per-target bootstrapping config, so I suggest refactoring it here.
* I also think we should update config.SCOPES_METAVAR - this is for help-display purposes, so this is more about what scope we should tell users to edit by default.

Other than that, I see no problems with adding these scopes

2024-04-09 01:25 UTC, scheibelp commented on lib/spack/spack/config.py
> +    cfg.push_scope(scope_type(scope_name, scope_path))
(no change needed)

Originally I was thinking of reducing this from 3 scopes to two:

* `platform/` (we keep this because it's what we had before)
* `platform/os` - get rid of this becuase...
* `platform/os/target` - this should handle the prior two (we only keep the first because there may be preexisting config in there)

However, users might want to manually edit the `os/` scope (or the base scope) for config that should apply for different systems.

2024-04-09 01:25 UTC, scheibelp commented on lib/spack/docs/configuration.rst
> +#. ``defaults/<platform>/<os>/<target>``
Of these 3, I think we can just document the last (`defaults/<platform>/<os>/<target>`): any automatic modifications will occur to this scope vs. the other two.

We can briefly mention `defaults/<platform>` (and `os/`) as an available scope after this list

2024-07-23 18:25 UTC, greenc-FNAL commented
@scheibelp Could you confirm what action is needed to finalize this, please? I'm seeing:
1. Update `config.SCOPES_METAVAR`
2. Refactor `bootstrap.config._bootstrap_config_scopes` to take advantage of the improvements herein.
3. Minor improvements to `configuration.rst` per https://github.com/spack/spack/pull/40018#discussion_r1556652965

Is that it, or am I missing and/or inventing anything?

2024-07-23 20:50 UTC, greenc-FNAL commented
@scheibelp I believe we have satisfied all outstanding comments; a final review would be appreciated.

2024-08-06 14:23 UTC, greenc-FNAL commented
Rebased only.

2024-08-21 15:17 UTC, greenc-FNAL commented
Rebased only.

2024-08-23 15:15 UTC, greenc-FNAL commented
@scheibelp Bump?

2025-01-22 18:27 UTC, greenc-FNAL commented
@spackbot help

2025-03-10 02:33 UTC, closed without merging