ipm: new package
LLNL/spack pull request #40069
Opened 2023-09-19 09:16 UTC by Christoph-TU

Depends on #39881 

This is the package for the MPI profiler IPM. 

IPM comes with a Perl script which parses the generated XML files during profiling. For this script, I added an optional runtime dependency on Ploticus, for which I already wrote a package here #39881. Since Ploticus is not widely used anymore, there might be another way to include this dependency without creating its own package. However, this dependency is not crucial on its own, and it might also be an option to leave the installation of Ploticus to the end user.

2023-09-19 09:21 UTC, Christoph-TU commented on var/spack/repos/builtin/packages/ipm/package.py
> +    homepage = "https://github.com/nerscadmin/IPM"
The GitHub page of IPM links to http://ipm-hpc.org/, but this page currently can't be reached. However, there seems to be an old version of the website available at https://ipm-hpc.sourceforge.net/ which provides some information about IPM.

2023-09-19 09:22 UTC, Christoph-TU commented on var/spack/repos/builtin/packages/ipm/package.py
> +    patch("remove_MPI_2COMPLEX_and_MPI_2DOUBLE_COMPLEX.patch", when="+coll_details")
I couldn't determine exactly when MPI_2COMPLEX and MPI_2DOUBLE_COMPLEX were removed from the standard, so I removed them regardless of the MPI version. On another note, Open MPI still supports these two datatypes, but I could not find a way to include this condition in the 'when' clause.

2023-09-19 18:54 UTC, tldahlgren approved these changes
Confirmed the homepage, branch, and tag exist.

2023-09-19 19:46 UTC, tldahlgren commented on var/spack/repos/builtin/packages/ipm/package.py
> +    patch("remove_MPI_2COMPLEX_and_MPI_2DOUBLE_COMPLEX.patch", when="+coll_details")
Unfortunately I don't think we have a way to indicate the equivalent of "when not `^openmpi`.

2023-09-19 19:48 UTC, tldahlgren commented
Audit checks indicate you need to add another package:

```
1m 51s
Run . share/spack/setup-env.sh
PKG-DIRECTIVES: 2 issues found
1. ipm: unknown package 'ploticus' in 'depends_on' directive
     in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/ipm/package.py
2. ipm: dependency on ploticus cannot be satisfied by known versions of ploticus
    happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/ipm/package.py
```

2023-09-19 19:48 UTC, tldahlgren requested changes
Package requires the addition of another package for `ploticus`.

2023-09-26 16:07 UTC, Christoph-TU commented
@spackbot re-run pipeline

2023-09-26 16:19 UTC, Christoph-TU commented
@spackbot commands

2023-09-26 16:20 UTC, Christoph-TU commented
@spackbot rebuild everything

2023-09-27 12:32 UTC, Christoph-TU commented
@tldahlgren Ploticus is now present in the development branch.

2023-10-02 18:45 UTC, tldahlgren approved these changes
I'm able to successfully build the package.

2023-10-02 18:46 UTC, merged