Add support for C++23 in pika and pika-algorithms packages
LLNL/spack pull request #40078
Opened 2023-09-19 15:26 UTC by aurianer

Needs #40080 and #40081 to be merged first

2023-09-19 15:42 UTC, aurianer commented
I will try to separate those changes in different PRs at it changes different packages, so this PR is in standby

2023-09-19 17:33 UTC, msimberg requested changes

2023-09-19 17:33 UTC, msimberg commented on var/spack/repos/builtin/packages/pika/package.py
> +    cxxstds = ("17", "20", "23")
Same as in fmt:
```suggestion
    cxxstds = ("17", "20", conditional("23", when="^cmake@3.20.3:"))
```

2023-09-20 14:46 UTC, aurianer commented on var/spack/repos/builtin/packages/pika/package.py
> +    cxxstds = ("17", "20", "23")
This was not working, I just added the conflict as harmen suggested on the [spack slack](https://spackpm.slack.com/archives/C5W7NKZJT/p1695220888836349?thread_ts=1695220270.038299&cid=C5W7NKZJT)

2023-09-20 14:54 UTC, msimberg submitted a review, later dismissed

2023-09-20 15:09 UTC, msimberg approved these changes

2023-09-20 15:28 UTC, merged