Shadow3: add Shadow3 package
LLNL/spack pull request #40095
Opened 2023-09-20 02:39 UTC by luccabavia

Add Shadow3 package, a ray tracing modelling sogftware used for x ray optics.

2023-09-24 13:59 UTC, alalazo commented
@spackbot fix style

2023-09-24 14:13 UTC, adamjstewart requested changes

2023-09-24 14:13 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-shadow3/package.py
> +    url = "https://files.pythonhosted.org/packages/11/29/c330f8ed5fa1d77927105bb6884a928d74ac9ec89e03181f3084a6cdb361/shadow3-23.9.19-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
Can we use a .tar.gz file here? See https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#id2

2023-09-24 14:13 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-shadow3/package.py
> +    depends_on("py-setuptools", type="build")
Missing build/run dep on numpy

2024-02-17 22:17 UTC, alecbcs commented
Going to close this PR due to a lack of response after review feedback. @luccabavia happy to reopen if you still want to get this merged and have time to work on it.

2024-02-17 22:17 UTC, closed without merging