Add python wrappers for CUDA
LLNL/spack pull request #40208
Opened 2023-09-26 11:45 UTC by stefano-corda

This MR adds the python wrappers for CUDA (https://developer.nvidia.com/cuda-python).

2023-09-26 11:53 UTC, haampie commented
@spackbot style

2023-09-26 11:53 UTC, haampie commented
@spackbot fix style

2023-09-26 13:49 UTC, adamjstewart requested changes

2023-09-26 13:49 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cuda-python/package.py
> +    depends_on("python@3.8:", type=("build", "run"))
Python 3.7 is also supported in 11.8.0. I would just remove this line, Spack supports Python 3.7+ anyway

2023-09-26 13:49 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cuda-python/package.py
> +    depends_on("py-future", type=("build", "run"))
Future isn't used by this library

2023-09-26 13:49 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cuda-python/package.py
> +    depends_on("py-pyparsing", type=("build", "run"))
Can't tell whether or not pyparsing is used at build-time, but it's definitely not used at run-time

2023-09-26 13:49 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cuda-python/package.py
> +    depends_on("py-numpy@1.21.1:", type=("build", "run"))
These are only used for testing, they aren't required. You can remove them.

2023-09-26 13:49 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cuda-python/package.py
> +    depends_on("py-pyclibrary@0.1.7:", type=("build", "run"))
I only see this used at build-time, I don't think it's needed at run-time

2023-09-26 13:49 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cuda-python/package.py
> +        env.prepend_path("LD_LIBRARY_PATH", self.spec["cuda"].prefix.lib)
```suggestion
        env.prepend_path("LD_LIBRARY_PATH", self.spec["cuda"].libs.directories[0])
```
Sometimes it's lib, sometimes it's lib64

2023-09-26 13:49 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyclibrary/package.py
> +    depends_on("python@3.8:", type=("build", "run"))
I don't think Python 3.8+ is required. You are missing these build/run deps though:
```python
install_requires = ['future', 'pyparsing>=2.3.1,<3'],
```

2023-09-26 13:49 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyclibrary/package.py
> +from spack.pkg.builtin.boost import Boost
This isn't used

2023-09-26 13:49 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyclibrary/package.py
> +    """Pyclibrary"""
```suggestion
    """C binding automation."""
```

2023-09-26 13:49 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pytest-benchmark/package.py
> +    )
Can you put the newer version first and remove the `preferred=True`? Spack automatically prefers the newest stable release

2025-05-07 07:23 UTC, alalazo commented
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this.

2025-05-07 07:23 UTC, closed without merging