py-libEnsemble: add v1.0.0
LLNL/spack pull request #40203
Opened 2023-09-26 02:54 UTC by shuds13

2023-09-26 10:46 UTC, manuelakuhn reviewed
- `py-numpy`, `py-psutil`, `py-tomli` and `py-pyyaml` have a minimum version requirement in `py-libensemble@1.0.0`:
"numpy>=1.21", "psutil>=5.9.4", "tomli>=1.2.1", "pyyaml>=6.0"
(see [setup.py#l72](https://github.com/Libensemble/libensemble/blob/v1.0.0/setup.py#L72))

- "pydantic<2":
    ```
    - depends_on("py-pydantic@:2", type=("build", "run"), when="@0.10:")
    + depends_on("py-pydantic@:1", type=("build", "run"), when="@0.10:")
    ```

- Regarding the variants: since `py-libensemble@0.10.2` none of them is listed in `setup.py` anymore. `mpi` is at least mentioned in the documentation.
If they are not used anymore you can add a `when="..."` argument to the variant as well. If they still are, can you add a comment where this is documented or where they come from?

optional: 
- switch the order of `type` and `when` to make it consistent with the other python packages (`when` before `type`)

2023-09-26 19:16 UTC, shuds13 commented
I've added comments on the variants. We will make setup.py match up in future releases.

2023-09-26 21:18 UTC, shuds13 commented
@manuelakuhn

I'm hoping this is acceptable now if style checks pass.

2023-09-26 21:41 UTC, manuelakuhn approved these changes
LGTM. Thanks!

2023-09-26 21:59 UTC, manuelakuhn requested changes
Sorry, I did not look properly and missed something:
you have added the version requirement on the dependencies now to all older releases as well. According to the `setup.py`s they should only be restricted for `py-libensemble@1.0.0` (and probably newer)

2023-09-26 21:59 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-libensemble/package.py
> +    depends_on("py-psutil@5.9.4:", when="@0.7.1:", type=("build", "run"))
```suggestion
    depends_on("py-numpy@1.21:", when="@1:", type=("build", "run"))
    depends_on("py-numpy", type=("build", "run"))
    depends_on("py-psutil@5.9.4:", when="@1:", type=("build", "run"))
    depends_on("py-psutil", when="@0.7.1:", type=("build", "run"))
```

2023-09-26 21:59 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-libensemble/package.py
> +    depends_on("py-pyyaml@6.0:", when="@0.10:", type=("build", "run"))
```suggestion
    depends_on("py-tomli@1.2.1:", when="@1:", type=("build", "run"))
    depends_on("py-tomli", when="@0.10:", type=("build", "run"))
    depends_on("py-pyyaml@6.0:", when="@1:", type=("build", "run"))
    depends_on("py-pyyaml", when="@0.10:", type=("build", "run"))
```

2023-09-27 19:41 UTC, shuds13 commented
@manuelakuhn I committed the suggestions. Is there still an issue?

2023-09-27 20:13 UTC, manuelakuhn approved these changes

2023-09-28 16:04 UTC, shuds13 commented
@manuelakuhn maybe someone can re-trigger the one failure. I'm guessing its some system thing.

2023-09-28 20:26 UTC, manuelakuhn commented
@spackbot run pipeline

2023-09-28 22:54 UTC, jlnav approved these changes

2023-10-03 10:48 UTC, adamjstewart approved these changes

2023-10-03 10:48 UTC, merged