modeltest-ng: adding new version, swapping maintainer
LLNL/spack pull request #40217
Opened 2023-09-26 22:12 UTC by snehring

Also allows for aarch64 compiles

2023-09-27 13:14 UTC, bernhardkaindl reviewed
The gcc-12.1.1 of gcc-toolset-12 of Rocky Linux 8.8 runs into this Internal Compiler Error (ICE):

Maybe you could add a 
```py
   conflicts("%gcc@12", when="target=aarch64:")
```
for the ICE:
```py
     439    /tmp/bkaindl/spack-stage/spack-stage-modeltest-ng-20220721-4bl5be4kjdrkk2bdfjw52a4nrzwtaq34/spack-src/libs/pll-modules/libs/libpll/src/parsimony.c: In function 'pl
            l_parsimony_build':
  >> 440    /tmp/bkaindl/spack-stage/spack-stage-modeltest-ng-20220721-4bl5be4kjdrkk2bdfjw52a4nrzwtaq34/spack-src/libs/pll-modules/libs/libpll/src/parsimony.c:204:19: internal
             compiler error: in vect_transform_reduction, at tree-vect-loop.cc:7469
     441      204 | PLL_EXPORT double pll_parsimony_build(pll_parsimony_t * pars,
     442          |                   ^~~~~~~~~~~~~~~~~~~
     443    Please submit a full bug report, with preprocessed source.
     444    See <https://bugs.rockylinux.org/> for instructions.
```
```ml
rpm -qf /opt/rh/gcc-toolset-12/root/usr/bin/gcc
gcc-toolset-12-gcc-12.2.1-7.4.el8.aarch64
```

2023-09-27 14:16 UTC, bernhardkaindl requested changes

2023-09-27 14:16 UTC, bernhardkaindl commented on var/spack/repos/builtin/packages/modeltest-ng/package.py
Please add a conflict for the ICE with gcc@12.2.1 on aarch64 (see my comment):
```suggestion
   # 40217: ICE by gcc-toolset-12-gcc-12.2.1-7.4.el8.aarch64 of Rocky Linux 8.8:
   conflicts("%gcc@12.2.1", when="target=aarch64:")
```

2023-09-27 16:20 UTC, snehring commented on var/spack/repos/builtin/packages/modeltest-ng/package.py
Was able to reproduce this on alma. I don't readily have a real rhel box or any other distros installed on aarch64 to see if it's just the rebuilds or only rhel, but I'm fine with this.

2023-09-27 16:24 UTC, snehring commented
oop, should have let my aarch64 with gcc@12.2.0 finish. That breaks too. Let me see if 12.3 fixes it.

2023-09-29 18:19 UTC, bernhardkaindl approved these changes

2023-09-29 18:19 UTC, merged