binutils: Make external find set ~headers to fix llvm build
LLNL/spack pull request #40214
Opened 2023-09-26 20:10 UTC by bernhardkaindl

Fixes #29350:

- `llvm` needs `binutils+headers` for `plugin-api.h` which most distros don't install
  and therefore make `spack external find binutils` detect `binutils~headers`.
  
  This forces `spack` to build `binutils` even when `binutils` have been imported
  from the system. This fixes the build of `llvm` in #29350.

- Also check for installed gold linker and set +gold/~gold

2023-12-21 17:34 UTC, naromero77 commented
I have run into this same issue with LLVM. I don't understand the patch though and will wait for @alalazo to provide a proper review.

2024-06-05 19:07 UTC, bonachea commented
Ping @alalazo is this ever going to be fixed? 

binutils external detection remains still broken in spack:develop, which breaks LLVM and other packages on important systems (e.g. HPE Cray EX, where the binutils provided by the SLES15 distro is missing the `plugin-api.h` header, and possibly other things).

Currently the external detection for `binutils` effectively lies to Spack about what variants are installed, without verifying anything, leading to breakage of packages who need specific binutils variants. We need `binutils` external detection to either be fixed to correctly detect which variants are _actually_ installed, or otherwise disable binutil's external detection entirely to make it stop lying about what's available.

CC: @arezaii

2024-06-06 06:14 UTC, alalazo requested changes

2024-06-06 06:14 UTC, alalazo commented on var/spack/repos/builtin/packages/binutils/package.py
> +        return "~headers" + variants
We shouldn't blindly return `~headers`, but try instead to check if anything like `binutils-dev` was installed. Also, even if we do so, we won't be able to automatically detect changes in the system.

2024-06-06 20:47 UTC, bonachea commented on var/spack/repos/builtin/packages/binutils/package.py
> +        return "~headers" + variants
@alalazo wrote:
> We should ... check if anything like `binutils-dev` was installed. 

I agree that would be the ideal behavior for `determine_variants`. Are you offering to implement that? (I lack the necessary `binutils` expertise)

> Also, even if we do so, we won't be able to automatically detect changes in the system.

IIUC this property is basically true of all spack externals, so that's fundamental. 

Towards your larger point, I agree the implications of unconditionally returning `~headers` is not ideal. IIUC it means that dependent packages who request `binutils+headers` will force concretization that rebuilds `binutils`, which _might_ be unnecessary for the small fraction of systems that have a external install of `binutils` that includes headers (and if for some unrelated reason that build fails, users with a `binutils-dev` package installed still have the option to manually edit the external to add the relevant variant). 

However the status quo of unconditionally returning `+headers` seems far worse: dependent packages like LLVM who request `binutils+headers` because they actually need it are instead handed a non-compliant external `binutils`, and then fail to build in messy ways, with the obscure root cause that Spack's auto-detection lied to them about the external's variants. This problem wasted several weeks of developer time before we identified the real root cause; IMHO this should be fixed so others need not go through that exercise.

2024-06-06 23:25 UTC, bernhardkaindl commented on var/spack/repos/builtin/packages/binutils/package.py
> +        return "~headers" + variants
@bonachea 👍 💯% agreed! We need to stop wasting user time:

> This problem wasted several weeks of developer time before we identified the real root cause; IMHO this should be fixed so others need not go through that exercise.

Exactly. It is the responsibility of those who what to claim +headers is available to check that it is available. The default has to be `~headers`:

Only 3 packages request binutils.*+headers: llvm, tau, apex. If people building those and gain so much that they would not want to build binutils+headers in spack, it is on those people to do check that the needed headers are available. As long as the found binutils have not proven all headers (not just `plugin-api.h`) are installed and working to build those packages, `~headers` has to be set.

Adding `+headers` is an optional feature for later.
This fix for `~headers` is the failsafe default that we should not even argue against to merge now:

Mind that, compared to the build time that building `llvm` requires, building `binutils` (just in doubt) is not even noticeable because `binutils+headers` builds so quickly compared to the failing `llvm` build.

It's a no-brainer to merge this PR as it.

Given from the many people like @naromero77, @wyphan (header detection in #30954, but that is an incremental later change) with #29350 #31706, and @bonachea now, we have enough to take action an merge this fix finally.

2024-06-07 18:37 UTC, alalazo commented on var/spack/repos/builtin/packages/binutils/package.py
> +        return "~headers" + variants
@bernhardkaindl Do you have time to add some heuristic check to decide whether to stick `~headers` or `+headers`? I might have time in ~2 weeks. 

> Adding +headers is an optional feature for later.

Meh, I understand this gets past the problem above, but I already see the next issue incoming "Why Spack detects `binutils~headers` when I have headers installed"? 

Right now Spack does the right thing on detection, in the sense that it doesn't add information about headers. 

It does imo the wrong thing during concretization, in the sense that externals _without_ any information on the `headers` variant will be good candidate for _both_ `~headers` and `+headers`. I tried to advocate for the opposite approach (an external with missing information about a variant shouldn't be considered when the variant is required explicitly, no matter the value), with this proof of concept #36179 but I lost the battle.

That said, I agree if we want to add proper detection for the variant, it just shouldn't be hard-coded `~headers`.

2024-06-07 18:40 UTC, alalazo commented on var/spack/repos/builtin/packages/binutils/package.py
> +        return "~headers" + variants
@bonachea This is slightly ot, but I'm genuinely curious about your workflow. May I ask why and how you end up with binutils detected? Are generally you preferring to use externals rather than building, or there was any other motivation for that?

2024-06-07 19:15 UTC, alalazo commented on var/spack/repos/builtin/packages/binutils/package.py
> +        return "~headers" + variants
`bfd.h` seems a good representative header file

2024-06-07 19:16 UTC, bonachea commented on var/spack/repos/builtin/packages/binutils/package.py
> +        return "~headers" + variants
> @bonachea This is slightly ot, but I'm genuinely curious about your workflow. May I ask why and how you end up with binutils detected? Are you generally preferring to use externals rather than building/reusing binaries, or there was any other motivation for that?

@alalazo: When I'm starting on a new system I always start with `spack external find`, which is [documented here for end-users](https://spack.readthedocs.io/en/latest/packages_yaml.html#automatically-find-external-packages). This is easy to type and locates ALL the detectable system packages, and has the following benefits: 
1. It reduces Spack build times by not rebuilding software you already have
2. It reduces the space footprint on systems with tight disk quotas
3. It's basically mandatory on tightly-integrated HPC systems like Crays where much of the critical software cannot be built correctly by Spack (often because it's closed-source, or the Spack package lacks critical site-specific tweaks)
4. It avoids [security problems documented here](https://spack.readthedocs.io/en/latest/getting_started.html#openssl) with fundamental security packages like `openssl`

The cynical answer to your implied question is "If think it's a bad idea for folks to detect binutils as an external, then you should disable its external detection". IMHO even that "solution" would be greatly preferable to the debacle caused by the current, critically defective detection logic.

I'll also note that adopting this PR as-is today (or simply disabling binutils external detection entirely) doesn't prevent anyone from implementing robust external variant detection _later_. IOW it solves the immediate pressing problem that's impacting many users, until that preferred upgrade is potentially applied later. To put it another way, if your building is on fire, first put out the fire, and maybe later look into installing a sprinkler system.

2024-06-07 19:20 UTC, bonachea approved these changes

2024-06-07 20:38 UTC, alalazo commented on var/spack/repos/builtin/packages/binutils/package.py
> +        return "~headers" + variants
> The cynical answer to your implied question is "If think it's a bad idea for folks to detect binutils as an external, then you should disable its external detection". IMHO even that "solution" would be greatly preferable to the debacle caused by the current, critically defective detection logic.

I didn't imply any question, cynicism is in the eye of the beholder :wink: Also, the current detection isn't wrong in any way - it just doesn't detect `headers`. The [docs](https://spack.readthedocs.io/en/latest/packages_yaml.html#external-packages) say this about externals:

   _Each external should specify a spec: string that should be as well-defined as reasonably possible. If a package lacks a spec component, such as missing a compiler or package version, then Spack will guess the missing component based on its most-favored packages, and it may guess incorrectly._

Tight quota has never been in my thought, so TIL.

> It's basically mandatory on tightly-integrated HPC systems like Crays [ ... ]

We have:
```console
$ spack external read-cray-manifest
```
specifically for Cray. To my understanding, this should give a much more accurate result.

---

**TL;DR** I didn't think I'd generate so much churn, asking to add a few lines of code to make this PR correct and mergeable. So, in the end I installed the sprinkler myself, in https://github.com/spack/spack/pull/40214/commits/8e1ac7ce8b16ab68dc31752ed6e04da5b0e719ee Hope nobody minds.

If you confirm this works I'll merge the PR.

2024-06-07 20:56 UTC, bonachea approved these changes
@alalazo wrote:
> ...
> I installed the sprinkler myself, in [8e1ac7c](https://github.com/spack/spack/commit/8e1ac7ce8b16ab68dc31752ed6e04da5b0e719ee) Hope nobody minds.
> 
> If you confirm this works I'll merge the PR.

Fix confirmed on NERSC Perlmutter:
```
perlmutter$ spack external find binutils
==> The following specs have been detected on this system and added to <redacted>/packages.yaml
binutils@2.40  binutils@2.41.0

perlmutter$ grep -A6 binutils $SPACK_USER_CONFIG_PATH/packages.yaml 
    externals:
    - spec: binutils@2.40~gold~headers
      prefix: /opt/cray/pe/cce/17.0.0/binutils/x86_64/x86_64-pc-linux-gnu
    - spec: binutils@2.41.0~gold~headers
      prefix: /usr
```
Thanks for the quick turnaround!

2024-06-07 21:00 UTC, alalazo approved these changes

2024-06-08 00:08 UTC, merged