RIOS: add recent versions
LLNL/spack pull request #40243
Opened 2023-09-28 21:31 UTC by gillins

This PR adds in recent versions of RIOS and handles new dependency on `cloudpickle` for most recent release.

2023-10-03 11:17 UTC, adamjstewart requested changes

2023-10-03 11:17 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-rios/package.py
> +    depends_on("py-cloudpickle", type=("build", "run"), when="@1.4.16:")
Seems like an optional dependency. Should we add a variant to control this? Something like `+parallel`?

2023-10-03 11:17 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-rios/package.py
>      version("1.4.10", sha256="7f11b54eb1f2ec551d7fc01c039b60bf2c67f0c2fc5b2946f8d986d6a9bc7063")
The new URL has a different checksum:
```suggestion
    version("1.4.10", sha256="6324acccc6018f9e06c40370bc366dc459890e8c09d26e0ebd245f6fd46dad71")
```

2023-10-04 00:48 UTC, gillins commented
Thanks @adamjstewart I think I've now covered these changes?

2023-10-06 18:52 UTC, adamjstewart approved these changes

2023-10-06 18:52 UTC, merged