py-tuiview: add recent versions of tuiview
LLNL/spack pull request #40244
Opened 2023-09-28 21:52 UTC by gillins

and remove old Qt4 version

2023-10-03 11:14 UTC, adamjstewart requested changes

2023-10-03 11:14 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-tuiview/package.py
> -    version("1.1.7", sha256="fbf0bf29cc775357dad4f8a2f0c2ffa98bbf69d603a96353e75b321adef67573")
Usually we deprecate versions before removing them in the next minor release. Any reason you have to remove it now?

2023-10-03 11:14 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-tuiview/package.py
>      depends_on("py-numpy", type=("build", "run"))
```suggestion
    depends_on("py-numpy", type=("build", "link", "run"))
```
We also seem to include the header files

2023-10-03 11:14 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-tuiview/package.py
> +    depends_on("gdal+python", type=("build", "run"))
```suggestion
    depends_on("gdal+geos+python", type=("build", "run"))
```
This is checked in `setup.py`

2023-10-04 00:48 UTC, gillins commented
Thanks @adamjstewart is this good to go now?

2023-10-06 18:48 UTC, adamjstewart approved these changes

2023-10-06 18:49 UTC, merged