fix ck build for 5.6.1
LLNL/spack pull request #40304
Opened 2023-10-03 20:50 UTC by afzpatel

2023-10-04 04:46 UTC, srekolam approved these changes

2023-10-05 11:09 UTC, afzpatel commented
@spackbot rerun pipeline

2023-10-05 17:09 UTC, srekolam approved these changes

2023-10-05 17:12 UTC, afzpatel commented
@spackbot rerun pipeline

2023-10-05 18:03 UTC, afzpatel commented
@tldahlgren this pr is ready to be reviewed

2023-10-09 17:20 UTC, tldahlgren requested changes
Please use `satisfies` for checking spec's version.

2023-10-09 17:20 UTC, tldahlgren commented on var/spack/repos/builtin/packages/composable-kernel/package.py
> +        if "@5.6.1:" in self.spec:
You should be using `satisfies` here:

```suggestion
        if self.spec.satisfies("@5.6.1:"):
```

2023-10-09 17:20 UTC, tldahlgren commented on var/spack/repos/builtin/packages/composable-kernel/package.py
> +            if "@5.6.1:" in self.spec:
Same here for use of `satisfies()`.

2023-10-09 17:20 UTC, tldahlgren commented on var/spack/repos/builtin/packages/composable-kernel/package.py
> +        if "@5.6.1:" in self.spec:
See docs for checking specs at https://spack.readthedocs.io/en/latest/packaging_guide.html#testing-spec-constraints.

2023-10-11 06:44 UTC, srekolam approved these changes

2023-10-11 21:42 UTC, tldahlgren approved these changes
LGTM

2023-10-11 21:43 UTC, merged