gcc: add program_suffix variant
LLNL/spack pull request #40317
Opened 2023-10-04 17:06 UTC by arekfu

This PR introduces a variant in the `gcc` package to control [the `--program-suffix` configure option](https://gcc.gnu.org/install/configure.html), which can be used to append an arbitrary suffix to all the generated executables (so that you can have `g++-13` instead of `g++`).

I have reformatted the modified code with `black`, but I was unable to run the unit tests.

2023-10-04 17:07 UTC, arekfu commented
Tagging @alalazo and @michaelkuhn as per `spack maintainers`.

2023-10-04 17:54 UTC, haampie commented
But why? :)

2023-10-04 19:21 UTC, arekfu commented
> But why? :)

Ah yes, sorry :) The typical use case is allowing different `gcc` versions to coexist in the same binary dir. For Spack, it is relevant for constructing views with more than one `gcc` version.

2023-10-04 19:24 UTC, haampie commented
But it will clash on other files, right? Like runtime support libs.

2023-10-04 19:31 UTC, tgamblin requested changes

2023-10-04 19:31 UTC, tgamblin commented on var/spack/repos/builtin/packages/gcc/package.py
> +        return f"gcc{program_suffix}"
You unfortunately can't assume that `command` isn't going to be called on an older installation of the package that doesn't have the variant.

```suggestion
        program_suffix = spec.variants.get("program_suffix")
        suffix = program_suffix.value if program_suffix and program_suffix.value != "none" else ""
        return f"gcc{suffix}"
```

2023-10-04 19:31 UTC, tgamblin commented on var/spack/repos/builtin/packages/gcc/package.py
> +            options.append("--program-suffix={0}".format(program_suffix))
```suggestion
            options.append(f"--program-suffix={program_suffix}")
```

2023-10-04 19:32 UTC, tgamblin commented
I could see people wanting this for modules -- just to have the version-specific exe in `PATH`.  Not opposed as long as default is `False`.

2023-10-06 07:54 UTC, michaelkuhn requested changes
This breaks installation for me:
```
==> Error: TypeError: 'str' object is not callable

$SPACK/var/spack/repos/builtin/packages/gcc/package.py:969, in write_rpath_specs:
        966            return
        967
        968        gcc = self.spec["gcc"].command
  >>    969        lines = gcc("-dumpspecs", output=str).splitlines(True)
        970        specs_file = join_path(self.spec_dir, "specs")
        971
        972        # Save a backup
```
It looks like `command` should return an `Executable` instead of a string.

2023-10-17 08:52 UTC, arekfu commented
PR updated.

2023-10-17 20:10 UTC, michaelkuhn requested changes
Still fails:
```
$ spack install gcc~bootstrap build_type=Release program_suffix=13
==> Installing gcc-13.2.0-nn26yfqo325wcegdufta463abbiegign [24/24]
[...]
==> Ran patch() for gcc
==> gcc: Executing phase: 'autoreconf'
==> gcc: Executing phase: 'configure'
==> gcc: Executing phase: 'build'
==> gcc: Executing phase: 'install'
==> Error: ProcessError: gcc13: No such file or directory
    Command: 'gcc13' '-dumpspecs'
```
How did you test this?

2023-10-18 10:20 UTC, arekfu commented
Sorry, I messed up my test (I have several Spack repos around and used the wrong one). This should be fine now.

2025-06-15 09:56 UTC, alalazo commented
Closing, since there has been no activity in a while and we moved the package repository. Feel free to reopen at / migrate to https://github.com/spack/spack-packages if you want to continue work on this.

2025-06-15 09:56 UTC, closed without merging