[py-langchain] New package
LLNL/spack pull request #40364
Opened 2023-10-06 17:28 UTC by qwertos

2023-10-06 19:58 UTC, tldahlgren submitted a review, later dismissed
Confirmed the homepage and both version sha256.

2023-10-06 19:59 UTC, tldahlgren commented
Adding python maintainer.

2023-10-08 15:26 UTC, adamjstewart requested changes

2023-10-08 15:26 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-langchain/package.py
> +    depends_on("py-poetry-core", type="build")
```suggestion
    depends_on("py-poetry-core@1:", type="build")
```

2023-10-25 17:07 UTC, manuelakuhn reviewed
Missing dependency:
```
async-timeout = {version = "^4.0.0", python = "<3.11"}
```

Optional:
- you can sort the dependencies newest to oldest as we do it for the versions.

Remark: there is also another PR for this package (for a different version) in #39903

2023-10-25 17:07 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-langchain/package.py
> +    depends_on("py-langsmith@0.0.7", when="@0.0.235", type=("build", "run"))
```suggestion
    depends_on("py-langsmith@0.0.7:0", when="@0.0.235", type=("build", "run"))
```
In to `pyproject.toml` it was specified as `langsmith = "^0.0.7"`

2023-10-25 17:07 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-langchain/package.py
> +    depends_on("py-langsmith@0.0.11", when="@0.0.262:", type=("build", "run"))
```suggestion
    depends_on("py-langsmith@0.0.11:0.0", when="@0.0.262:", type=("build", "run"))
```
In to `pyproject.toml` it was specified as `langsmith = "~0.0.11"`

2025-05-07 07:25 UTC, closed without merging

2025-05-07 07:25 UTC, alalazo commented
Repository layout changed for Spack v1.0 Please resubmit the PR if you're still interested in the package. Closing for now.