Updating patch to enable flag mcode-object-version=none
LLNL/spack pull request #40367
Opened 2023-10-06 19:39 UTC by renjithravindrankannath

Updating patch to enable flag mcode-object-version=none for device-libs when it is built as part of llvm-amdgpu

2023-10-09 02:56 UTC, srekolam requested changes
i think the option  -Xclang -mcode-object-version=none is applicable for only +rocm-device-libs variant ..in the other case ,it is already doing that. So please have this patch applicable for only +rocm-device-libs .
Also, please add a comment so that this is understood as to why this patch is required. the patch name doesnot provide much info on the need.

2023-10-12 17:22 UTC, srekolam approved these changes

2023-10-13 04:32 UTC, renjithravindrankannath commented
Hi @tldahlgren , Could you please review and approve if it looks good.

2023-10-16 15:39 UTC, srekolam commented
@tldahlgren can you please review this PR . Thanks.

2023-10-16 17:24 UTC, tldahlgren approved these changes
LGTM

2023-10-16 17:25 UTC, merged

2023-10-17 07:15 UTC, srekolam reviewed
this PR mistakenly removed def cmake_args(self) in hsakmt-roct/package.py