allow packages to request no submodules be updated
LLNL/spack pull request #40409
Opened 2023-10-10 13:56 UTC by tjfulle

When a package returns a falsey from a call to a submodule function, do not update submodules (otherwise *all* submodules are updated).

closes #4048

2023-12-21 09:24 UTC, tgamblin requested changes

2023-12-21 09:24 UTC, tgamblin commented on lib/spack/spack/fetch_strategy.py
> +            if submodules:
Can you:
1. Extend the test added in #27293 to include this case
2. Update the type signature for the `submodules` arg of `version()` in directives.py?

I think (2) should be something like:

```python

SubmoduleCallback = Callable["spack.package_base.PackageBase", Union[str, List[str]]]

@directive("versions")
def version(
    ...,
    submodules: Union[SubmoduleCallback, bool] = False,
```

2024-01-12 17:13 UTC, tgamblin commented
@spackbot fix style

2024-01-30 22:51 UTC, tjfulle commented
I can't make any sense of the errors in the prechecks.  I've run spack unit-test locally and can reproduce them, but I can't tell where they are coming from since they seem unassociated with the changes I made.

2024-02-15 23:48 UTC, tjfulle commented
@tgamblin and @psakievich : bump

2024-02-16 06:31 UTC, tgamblin approved these changes

2024-02-16 06:31 UTC, tgamblin commented
Thanks!

2024-02-16 06:36 UTC, merged