fix variant initialization logic to allow proper handling of values="*"
LLNL/spack pull request #40406
Opened 2023-10-10 13:45 UTC by tjfulle

Fix for #40405.

Closes: #40405

2023-10-31 21:37 UTC, alalazo requested changes
We need a regression test for this fix. Also, we should double check possible edge cases and differences between `values=str` and `values=*` - in case they should behave the same it's maybe preferable to have the same validator for both.

2023-12-22 06:25 UTC, psakievich commented
@alalazo I put together a quick test to compare the resulting differences between `str` and `"*"`.  Not sure if this is sufficient, or if there are additional corner cases you want to evaluate.

2023-12-22 06:32 UTC, psakievich commented
@spackbot fix style

2023-12-22 08:36 UTC, alalazo requested changes
A couple of minor requests, but otherwise LGTM

2023-12-22 08:36 UTC, alalazo commented on lib/spack/spack/test/variant.py
> +    wild_var.validate_or_raise(str_output)
Can't we use assertion here, instead of patching the objects?

2023-12-22 08:36 UTC, alalazo commented on lib/spack/spack/test/variant.py
> +def test_wild_card_valued_variants_equivalent_to_str():
(minor) Can you add a brief docstring explaining what is tested here (mainly that we can use `*` in directives as an alias to `str`)?

2023-12-22 15:10 UTC, alalazo approved these changes
Thanks!

2023-12-22 15:10 UTC, merged