py-bidscoin: add 4.1.1 and py-argparse-manpage: add new package
LLNL/spack pull request #40414
Opened 2023-10-10 16:26 UTC by manuelakuhn

https://github.com/Donders-Institute/bidscoin/tree/4.1.1
https://github.com/praiskup/argparse-manpage/tree/v4.5

2023-10-10 17:37 UTC, tldahlgren reviewed
Confirmed the new package's home page and all affected version sha256.

2023-10-14 17:36 UTC, adamjstewart approved these changes

2023-10-14 17:39 UTC, adamjstewart requested changes

2023-10-14 17:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-bidscoin/package.py
> +    depends_on("py-tomli@1.1:", when="@4: ^python@:3.10", type=("build", "run"))
Not in 4.0.0

2023-10-14 17:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-bidscoin/package.py
> +    depends_on("py-pyqt6", when="", type=("build", "run"))
when?

2023-10-16 18:42 UTC, manuelakuhn commented
Thank for cross-checking!

2023-10-20 11:55 UTC, adamjstewart approved these changes

2023-10-20 11:55 UTC, merged