acfl: use f-strings
LLNL/spack pull request #40433
Opened 2023-10-11 05:59 UTC by alecbcs

Update legacy `.format()` calls to f-strings.

2023-10-11 18:08 UTC, bernhardkaindl requested changes
@alecbcs While this is not your change, but since the f-string changes are not functionally important, I'd like to use this opportunity to make you aware that I ran into a problem while trying to check it.

On 22.04, the acfl recipe needs to download

https://developer.arm.com/-/media/Files/downloads/hpc/arm-compiler-for-linux/23-04-1/arm-compiler-for-linux_23.04.1_Ubuntu-22.04_aarch64.tar

That link even exists on:
https://developer.arm.com/downloads/-/arm-compiler-for-linux

But the file does not exist at the given path, I get the same error also in a regular web browser (while 20.04 appears to work):

```py
wget https://developer.arm.com/-/media/Files/downloads/hpc/arm-compiler-for-linux/23-04-1/arm-compiler-for-linux_23.04.1_Ubuntu-22.04_aarch64.tar
--2023-10-11 18:02:37--  https://developer.arm.com/-/media/Files/downloads/hpc/arm-compiler-for-linux/23-04-1/arm-compiler-for-linux_23.04.1_Ubuntu-22.04_aarch64.tar
Resolving developer.arm.com (developer.arm.com)... 104.126.37.153, 104.126.37.131
Connecting to developer.arm.com (developer.arm.com)|104.126.37.153|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://armkeil.blob.core.windows.net/developer//App_Data/MediaFiles/E/2/9/{E29DCCB4-1093-445F-9076-D2E0D672CC7D}arm-compiler-for-linux_23.04.1_Ubuntu-22.04_aarch64.tar [following]
--2023-10-11 18:02:38--  https://armkeil.blob.core.windows.net/developer//App_Data/MediaFiles/E/2/9/%7BE29DCCB4-1093-445F-9076-D2E0D672CC7D%7Darm-compiler-for-linux_23.04.1_Ubuntu-22.04_aarch64.tar
Resolving armkeil.blob.core.windows.net (armkeil.blob.core.windows.net)... 52.239.137.100
Connecting to armkeil.blob.core.windows.net (armkeil.blob.core.windows.net)|52.239.137.100|:443... connected.
HTTP request sent, awaiting response... 404 The specified blob does not exist.
2023-10-11 18:02:38 ERROR 404: The specified blob does not exist..
```

2023-10-11 21:19 UTC, annop-w commented
@bernhardkaindl Thank you for reporting the problem. I'll check with our team and have it fixed. I'll keep you updated.

2023-10-12 08:25 UTC, annop-w commented
@bernhardkaindl This is a known issue for our team and the link will be fixed at the same time as the next release soon.

2023-10-12 09:30 UTC, bernhardkaindl approved these changes

2023-10-12 09:30 UTC, merged