New package: cpr
LLNL/spack pull request #40509
Opened 2023-10-13 14:52 UTC by sethrj

Dependency of [XACC](https://github.com/eclipse/xacc).

2023-10-13 16:36 UTC, alecbcs requested changes
@sethrj this PR looks really good! Just a quick suggestion to clean up the args creation a bit.

2023-10-13 16:36 UTC, alecbcs commented on var/spack/repos/builtin/packages/cpr/package.py
> +        return args
```suggestion
        _force = "_FORCE" if self.spec.satisfies("@:1.9") else ""
        
        return [
            self.define("CPR_USE_SYSTEM_GTEST", True),
            self.define(f"CPR{_force}_USE_SYSTEM_CURL", True),
            self.define("CPR_ENABLE_SSL", True),
        ]

```

We can use `satisfies()` here to get around having to create a new version object which cleans up the syntax a bit.

2023-10-13 18:25 UTC, alecbcs commented
@spackbot fix style

2023-10-14 13:52 UTC, sethrj commented
@alecbcs requires reapproval

2023-10-14 15:31 UTC, alecbcs approved these changes
Confirmed SHAs. @sethrj thanks for adding this new package!

2023-10-14 15:31 UTC, merged