py-fenics-ufl: update version and add test
LLNL/spack pull request #40534
Opened 2023-10-15 08:34 UTC by garth-wells

2023-10-15 12:06 UTC, adamjstewart requested changes

2023-10-15 12:06 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-fenics-ufl/package.py
> +    depends_on("py-setuptools@58:", when="@2022.1.0:", type=("build", "run") )
setuptools 62+ now, also only needed at build time

2023-10-15 12:06 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-fenics-ufl/package.py
> +    depends_on("python@3.7:", when="@2016.2.0:2023.1.1.post0", type=("build", "run"))
You can remove this line, Spack only supports Python 3.7+ already

2023-10-15 12:06 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-fenics-ufl/package.py
>      depends_on("py-numpy@1.21:", type=("build", "run"))
Where does 1.21+ come from?

2023-10-16 07:47 UTC, garth-wells commented
@adamjstewart Thanks for the comments, I think this PR is ready now.

2023-10-16 11:52 UTC, adamjstewart approved these changes

2023-10-16 11:52 UTC, merged