Enable address sanitizer in rocm's llvm-amdgpu package.
LLNL/spack pull request #40570
Opened 2023-10-17 07:18 UTC by srekolam

this PR will enable the address sanitizer changes inside llvm-amdgpu package. 
each of the individual rocm packages will inturn need additional changes which will be done as part of the rocm-5.7.0 updates.

2023-10-18 04:51 UTC, renjithravindrankannath approved these changes

2023-10-19 03:41 UTC, srekolam commented
@tldahlgren , can you please review and let me know if this can be merged.

2023-10-19 03:50 UTC, srekolam commented
@tldahlgren , can you please let us know if you can review the changes and merge if this is okay.

2023-10-25 12:58 UTC, srekolam commented
@tldahlgren  can you please review this PR. Thanks.

2023-10-30 16:17 UTC, tldahlgren reviewed
Looking good.  I have a question about the addition (versus modification) of a patch directive and a recommendation to start switching to f-strings.

2023-10-30 16:17 UTC, tldahlgren commented on var/spack/repos/builtin/packages/llvm-amdgpu/package.py
> +    patch("adjust-openmp-bitcode-directory-for-llvm-link.patch", when="@5.2.0:5.6")
Did you mean to use only one patch directive here?

2023-10-30 16:17 UTC, tldahlgren commented on var/spack/repos/builtin/packages/llvm-amdgpu/package.py
> +            ),
FWIW. We're encouraging use of f-strings in the core so you could switch this here while you're making the change:

```suggestion
            url=g"https://github.com/RadeonOpenCompute/ROCR-Runtime/archive/rocm-{d_version}.tar.gz"
```

2023-10-31 10:12 UTC, srekolam commented on var/spack/repos/builtin/packages/llvm-amdgpu/package.py
> +    patch("adjust-openmp-bitcode-directory-for-llvm-link.patch", when="@5.2.0:5.6")
it is corrected now.

2023-10-31 15:50 UTC, tldahlgren commented on var/spack/repos/builtin/packages/llvm-amdgpu/package.py
> +            url="https://github.com/RadeonOpenCompute/ROCR-Runtime/archive/rocm-{d_version}.tar.gz",
Apologies if I forgot to include the `f` in my suggestions:

```suggestion
            url=f"https://github.com/RadeonOpenCompute/ROCR-Runtime/archive/rocm-{d_version}.tar.gz",
```

2023-10-31 15:51 UTC, tldahlgren requested changes
Apologies for forgetting to include the required `f` in the f-strings.

2023-10-31 15:51 UTC, tldahlgren commented on var/spack/repos/builtin/packages/llvm-amdgpu/package.py
> +            url="https://github.com/RadeonOpenCompute/ROCm-CompilerSupport/archive/rocm-{d_version}.tar.gz",
Same here. 🙍‍♀️ 

```suggestion
            url=f"https://github.com/RadeonOpenCompute/ROCm-CompilerSupport/archive/rocm-{d_version}.tar.gz",
```

2023-10-31 16:19 UTC, tldahlgren approved these changes

2023-11-01 01:09 UTC, merged