adds  cubew 4.8.1, cubelib 4.8.1 and cubegui 4.8.1, 4.8.2
LLNL/spack pull request #40612
Opened 2023-10-19 13:53 UTC by swat-jsc

2023-10-19 21:35 UTC, tldahlgren requested changes
Confirmed all new version sha256 but the maintainers directive needs to be used.

2023-10-19 21:35 UTC, tldahlgren commented on var/spack/repos/builtin/packages/cube/package.py
> +    maintainers = "swat-jsc"
This syntax is no longer supported.  You need to use the new directive described at docs at https://spack.readthedocs.io/en/latest/packaging_guide.html#maintainers.

2023-11-06 22:10 UTC, michaelkuhn approved these changes
LGTM

2023-11-07 22:40 UTC, tldahlgren approved these changes
Reconfirmed all of the new version sha256, rest LGTM.

2023-11-07 22:40 UTC, merged