ispc 1.21.1, LDFLAGS -lncurses
LLNL/spack pull request #40649
Opened 2023-10-22 05:36 UTC by ITCJ

2023-10-23 13:04 UTC, aumuell requested changes
Thank you for your contribution!

Could you please also update the versions for the dependency on LLVM like this?

-    depends_on("llvm@13:15", when="@1.19:")
+    depends_on("llvm@13:16", when="@1.21")
+    depends_on("llvm@13:15", when="@1.19:1.20")

2023-10-23 13:04 UTC, aumuell commented on var/spack/repos/builtin/packages/ispc/package.py
> +    version("1.21.1", sha256="99bbb1d1f15bc4433d6a63b5bb35b321af3e3af753c3b28a61850d1748e8a89f")
Can confirm this SHA for 1.21.1

2023-10-23 13:04 UTC, aumuell commented on var/spack/repos/builtin/packages/ispc/package.py
> +            env.append_flags("LDFLAGS", "-lncurses")
While this might fix the build on your system, it might break it on others. I would rather drop this change and propose to try #39662, as this seems to provide a more general solution to this problem

2023-10-30 11:20 UTC, alalazo commented
Superseded by #39662

2023-10-30 11:20 UTC, closed without merging