Python, R, Lua: don't traverse in setup_dependent_*
LLNL/spack pull request #40687
Opened 2023-10-24 14:09 UTC by haampie

Since `setup_dependent_*` is called on each edge, there should be no need to
traverse inside those functions.

2023-10-28 12:59 UTC, adamjstewart commented
#13926 contains all my thoughts on this. I'll trust your testing to make sure this doesn't break anything. Looks like Perl already avoids this.

2023-11-03 11:18 UTC, haampie commented
Moving this to 0.22 so we don't risk breaking packages just before a release.

2023-12-18 15:21 UTC, haampie commented
bump @adamjstewart

2024-11-25 20:50 UTC, becker33 requested changes

2024-11-25 20:50 UTC, becker33 commented on var/spack/repos/builtin/packages/python/package.py
> +        if not dependent_spec.package.extends(self.spec):
[minor] Is there a reason for this change? It seems like unnecessary package churn

2024-11-25 20:50 UTC, becker33 commented on var/spack/repos/builtin/packages/r/package.py
> -        env.set("R_LIBS", r_libs_path)
Shouldn't this have

```
        if dependent_spec.package.extends(self.spec):
            env.prepend_path("R_LIBS", join_path(dependent_spec.prefix, self.r_lib_dir))

2024-11-25 20:50 UTC, becker33 commented on var/spack/repos/builtin/packages/python/package.py
> -                env.prepend_path("PYTHONPATH", os.path.join(prefix, directory))
Doesn't this still need to run for `dependent_spec` itself?

```
for directory in {self.platlib, self.purelib}:
    env.prepend_path("PYTHONPATH", os.path.join(dependent_spec.prefix, directory))
```
could also add a gate condition in there for whether the directory exists.

2024-11-26 07:52 UTC, adamjstewart reviewed
Apparently I made pending comments 11 months ago but never finalized them.

2024-11-26 07:52 UTC, adamjstewart commented on var/spack/repos/builtin/packages/python/package.py
>          extension and any other python extensions it depends on.
This docstring should prob be updated

2024-11-26 07:52 UTC, adamjstewart commented on var/spack/repos/builtin/packages/python/package.py
>          extension and any other python extensions it depends on.
Same here, although it seems like this was already incorrect

2024-11-26 07:52 UTC, adamjstewart commented on var/spack/repos/builtin/packages/python/package.py
> -        # Add installation prefix to PYTHONPATH, needed to run import tests
I'm surprised this is no longer needed. How does `PYTHONPATH` get set to include this?

2025-12-17 08:34 UTC, closed without merging