conquest: add build system changes and library paths
LLNL/spack pull request #40718
Opened 2023-10-26 13:37 UTC by tkoskela

There's been a change in development to where files included by the makefile are kept and how they are included. This PR fixes the spack package to use them in future versions.

I also discovered on another system I was building on that I had to add the `ld_flags` of `fft` and `libxc` (in addition to `blas` and `scalapack`) to the Makefile to link them.

2023-10-26 16:43 UTC, ilectra approved these changes

2023-10-26 16:43 UTC, ilectra commented on var/spack/repos/builtin/packages/conquest/package.py
> +            makefile.filter("SYSTEM =.*", "SYSTEM = example")
You can also call `make` with an argument, like in https://github.com/OrderN/CONQUEST-release/blob/00329bba12b4621051d64d87d0232bda63e81443/.github/workflows/makefile.yml#L65 , if it's easier.

2023-10-27 09:48 UTC, ilectra approved these changes

2023-10-30 09:45 UTC, alalazo requested changes

2023-10-30 09:45 UTC, alalazo commented on var/spack/repos/builtin/packages/conquest/package.py
> +                make("SYSTEM = example")
Can we override just `build_targets` and `build_directory` instead of the entire phase?

2023-10-31 10:54 UTC, tkoskela commented on var/spack/repos/builtin/packages/conquest/package.py
> +                make("SYSTEM = example")
It looks like we can! Thanks for the suggestion

2023-10-31 21:30 UTC, alalazo commented on var/spack/repos/builtin/packages/conquest/package.py
> +    build_targets = ["SYSTEM = example"]
You can turn this into a `@property` and check the version

2023-11-13 11:13 UTC, alalazo approved these changes

2023-11-13 11:13 UTC, merged