Small changes for Beatnik 1.0 release
LLNL/spack pull request #40726
Opened 2023-10-26 19:50 UTC by patrickb314

Minor changes to beatnik spack specification for builing on CORAL systems with Spectrum MPI and to add a commit hash for the new 1.0 release. Also a minor change to silo removing an unneeded library search path addition.

2023-10-26 20:23 UTC, JStewart28 approved these changes
Everything looks good

2023-10-26 20:25 UTC, JStewart28 approved these changes

2023-10-26 20:26 UTC, JStewart28 commented
Everything looks good

2023-10-30 07:23 UTC, alalazo requested changes

2023-10-30 07:23 UTC, alalazo commented on var/spack/repos/builtin/packages/beatnik/package.py
> +    # Add proper versions and checksums here.
```suggestion
```

2023-10-30 07:23 UTC, alalazo commented on var/spack/repos/builtin/packages/silo/package.py
> +            # flags.append(spec["readline"].libs.search_flags)
Please, don't leave commented out code. Either remove or modify :slightly_smiling_face:

2023-10-30 16:39 UTC, patrickb314 commented on var/spack/repos/builtin/packages/silo/package.py
> +            # flags.append(spec["readline"].libs.search_flags)
Fixed, thanks.

2023-10-31 21:28 UTC, alalazo approved these changes

2023-10-31 21:28 UTC, merged