spack env activate: create & activate home environment without args
LLNL/spack pull request #40756
Opened 2023-10-28 10:34 UTC by haampie

This PR implements the concept of "home environment", which doesn't have to be
created explicitly. The aim is to lower the barrier for using environments.

To (create and) activate the home environment, run

```
$ spack env activate
```

This mimics the behavior of

```
$ cd
```

which brings you to your home directory.

The name `home` is not a reserved name, it's just that `spack env activate`
creates an environment named like that if it doesn't exist already.

2023-10-28 12:04 UTC, adamjstewart commented
Nice! Planning on using this myself since I only ever use a single environment.

2023-10-30 14:54 UTC, wyphan commented
Nice, perhaps add some kind of info message when automatically creating the `home` environment for the first time, and adjust the `spack env --help` message?

2023-10-30 16:11 UTC, haampie commented
@wyphan:

```
$ spack env activate 
Created and activated home environment in /home/harmen/spack/var/spack/environments/home
$ spack env activate --temp 
Created and activated temporary environment in /tmp/spack-okidjx4j
$ spack env activate 
Activated home environment in /home/harmen/spack/var/spack/environments/home
```

2023-10-30 16:22 UTC, haampie commented
Now with color

![Screenshot from 2023-10-30 17-19-12](https://github.com/spack/spack/assets/194764/7f5c25a8-3b60-4833-9c8a-498dd6fb5c76)

Maybe I should leave set SPACK_COLOR=always though in the shell wrapper...

2023-10-31 19:17 UTC, tgamblin commented
I like this.  It does make the tutorial easier to understand and can get people started with an initial environment easier.  How do you "reset" the `home` environment?  Do you just `spack env rm home`?

2023-10-31 22:22 UTC, tgamblin commented
Also, along the same lines, how do you use the `home` environment on the CLI?  Obviously this should work:

```
spack -e home add blah
```

but I wonder if there should be a shortcut?  We have:

```
  -D DIR, --env-dir DIR
                        run with an environment directory (ignore managed environments)
  -e ENV, --env ENV     run with a specific environment (see spack env)
  -E, --no-env          run without any environments activated (see spack env)
```

`-d` for `default` is taken. `-h` for `home` is obviously taken.  If you called the `home` environment `main` instead, you could steal the `-m` short argument from:

```
  -m, --mock            use mock packages instead of real ones
```

As `spack -m list` etc. is really just for debugging tests -- you can access the mock test packages from the CLI.  I seriously doubt anyone is using that for any production reason.  So you could do:

```
  --mock            use mock packages instead of real ones
  -m, --main        use main (default) environment (see spack env)
```

Which would enable:

```
spack -m install x y z
```

Thoughts?

2023-11-01 07:50 UTC, haampie commented
Or a long flag `spack --home ...`?

2023-11-02 11:03 UTC, haampie commented
Let's decide on this today @tgamblin? :)

2023-11-03 07:21 UTC, tgamblin commented
@haampie it LGTM though I’m still on the fence about home/main/default.i kind of like main and default better than home.

Do others have a preference?

2023-11-03 07:21 UTC, tgamblin submitted a review, later dismissed

2023-11-03 11:02 UTC, haampie commented
I like the parallel with the `cd` command, and there the jargon is `home folder`.

`main` makes me think of the default git branch, and there the commands are not really the same `git checkout x` vs `git checkout`.

`default` could work too, but I don't think a flag `spack --default` is very clear, if we would ever add that.

2023-11-03 12:22 UTC, tgamblin commented
Let’s go with `default` as I think it’s similar to the `default` nix profile. 

For the arg, let’s just skip the short arg for now.

2023-11-03 13:13 UTC, haampie commented
done

2023-11-05 15:02 UTC, tgamblin approved these changes
LGTM

2023-11-05 15:04 UTC, tgamblin requested changes
@haampie can we get more than 50% of the diff covered?

2023-11-05 17:59 UTC, haampie commented
It's covered by shell tests, does that run without coverage?

2023-11-06 06:52 UTC, tgamblin approved these changes

2023-11-06 06:53 UTC, merged