Update py-scikit-build-core to version 0.6.0
LLNL/spack pull request #40779
Opened 2023-10-30 15:27 UTC by chrisrichardson

2023-10-30 15:36 UTC, wdconinc requested changes
There are some changes to the requirements in the pyproject.toml at https://github.com/scikit-build/scikit-build-core/compare/v0.2.0...v0.6.0#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711

Relevant appears to be:
- `depends_on("py-importlib-metadata", when="@0.3.0: ^python@:3.7")`

2023-10-30 15:44 UTC, chrisrichardson commented
I thought Python 3.7 was deprecated in Spack. Do we need to add support for it when adding new versions of other packages? (I can see the point when adding *old* versions)

2023-10-30 16:04 UTC, wdconinc commented
Right you are. I keep mixing up the python versions supported in the package (https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/python/package.py) and the python versions supported by spack itself (https://spack.readthedocs.io/en/latest/getting_started.html). It's the former that's relevant here.

2023-10-31 00:50 UTC, tldahlgren reviewed
FYI. Confirmed the version sha256.

2023-10-31 01:54 UTC, wdconinc submitted a review, later dismissed

2023-11-02 19:10 UTC, adamjstewart commented
Personally I would still add the Python 3.7 dep since it hasn't been removed yet (I'll do that after SC). Also looks like a virtualenv dep is missing for testing.

2023-11-09 12:10 UTC, ma595 commented
@adamjstewart I have bumped to patch 0.6.1, could you please re-review?

2023-11-11 22:02 UTC, adamjstewart requested changes

2023-11-11 22:02 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-scikit-build-core/package.py
>      depends_on("py-pytest@7:", type="test")
Importlib-metadata no longer part of test in 0.5+

2023-11-11 22:02 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-scikit-build-core/package.py
> +    depends_on("py-virtualenv", type="test")
```suggestion
    depends_on("py-virtualenv", when="@0.6:", type="test")
```

2023-11-18 14:16 UTC, adrianjhpc approved these changes

2023-11-18 14:16 UTC, adrianjhpc approved these changes

2023-11-18 14:17 UTC, adrianjhpc approved these changes

2023-11-18 14:52 UTC, adamjstewart approved these changes

2023-11-21 19:14 UTC, wdconinc approved these changes

2023-11-21 19:16 UTC, wdconinc commented
I think in comparison with https://github.com/spack/spack/pull/41071, this PR is smaller (adds fewer versions), and already includes the virtualenv test requirement when 0.6:.

@adrianjhpc apologies, but looking forward to future PRs!

2023-11-21 19:17 UTC, merged