Don't let runtime env variables of compiler like deps leak into the build environment
LLNL/spack pull request #40916
Opened 2023-11-06 20:09 UTC by haampie

When depending on libllvm or libgcc as a build/link type dep, we don't want
their `setup_run_environment` changes to modify CC / CXX / F77 / FC, since
Spack determines the actual compiler and should manage those variables.

We still want module files to be generated with those CC / CXX / F77 / FC
variables, so it would be wrong to remove those variables from
`setup_run_environment`.

2023-11-06 20:58 UTC, haampie commented
@spackbot run pipeline

2023-11-06 22:29 UTC, trws approved these changes

2023-11-06 22:30 UTC, merged

2023-11-06 22:32 UTC, tgamblin requested changes
LGTM -- minor request and we're good

2023-11-06 22:32 UTC, tgamblin commented on lib/spack/spack/build_environment.py
> +                    # Don't let the runtime environment of comiler like dependencies leak into the
```suggestion
                    # Don't let the runtime environment of compiler-like dependencies leak into the
```

2023-11-06 22:32 UTC, tgamblin commented on lib/spack/spack/build_environment.py
> +                if self.context == Context.BUILD:
Add a `TODO` here to handle this better when we have proper "compiler" dependencies, mention this is a stopgap

2023-11-06 22:33 UTC, tgamblin commented
Heh ok looks like Tom beat me to it.  This is good -- we *DO* need to sort out how this will work with compiler deps.

2023-11-08 20:11 UTC, haampie commented on lib/spack/spack/build_environment.py
> +                    # Don't let the runtime environment of comiler like dependencies leak into the
Haven't you heard about the co-miler?

2024-02-16 08:31 UTC, nboelte commented
We used setup_run_environment() to clear modifications to PATH. This change breaks that. 

Is there any way we can now unset PATH modifications for a package? It is set by _make_runnable and can no longer be unset by setup_run_environment().