Package/alps create again
LLNL/spack pull request #40995
Opened 2023-11-10 08:40 UTC by Sinan81

Latest source file builds with newer python. Hence re-add the removed ALPS package.

2023-11-10 19:07 UTC, Sinan81 commented
@spackbot fix style

2023-11-11 18:16 UTC, Sinan81 commented
FYI @andredepinhovieira @ketsubouchi

2023-11-28 06:19 UTC, Sinan81 commented
@adamjstewart this package was removed by you due to obsolete python dependency. In this PR I've recreated it from scratch. Is this ok, or else is there a better way to restore a removed package?

2023-12-01 13:35 UTC, adamjstewart requested changes

2023-12-01 13:35 UTC, adamjstewart commented on var/spack/repos/builtin/packages/alps/package.py
> +            url = "https://alps.comp-phys.org/static/software/releases/alps-2.3.0-src.tar.gz"
If this is no longer supported, we can simplify this function to work for all versions.

2023-12-01 13:35 UTC, adamjstewart commented on var/spack/repos/builtin/packages/alps/package.py
> +        args.append("Boost_ROOT_DIR=" + self.spec["boost"].prefix)
Should this have a `-D`? I usually use `self.define(...)` for these.

2024-02-23 11:51 UTC, adamjstewart commented
Ping me when it's ready to review.

2024-02-23 18:47 UTC, Sinan81 commented
For some reason, the package build is failing. I built it many times before. i need to sort that out.

2024-12-18 02:52 UTC, Sinan81 commented
will push a new MR. closing

2024-12-18 02:52 UTC, closed without merging