add package hip-tensor
LLNL/spack pull request #40991
Opened 2023-11-09 20:43 UTC by afzpatel

2023-12-19 16:12 UTC, alalazo requested changes

2023-12-19 16:12 UTC, alalazo commented on var/spack/repos/builtin/packages/hip-tensor/package.py
> +        return args
I think you can remove this:
```suggestion
```

2023-12-19 16:12 UTC, alalazo commented on var/spack/repos/builtin/packages/hip-tensor/package.py
> +        depends_on("rocm-cmake@" + ver, when="@" + ver)
Can you use f-strings here?

2024-01-03 07:23 UTC, srekolam commented on var/spack/repos/builtin/packages/hip-tensor/package.py
> +    homepage = "https://github.com/ROCmSoftwarePlatform/hipTensor"
can you update the url to point to https://github.com/ROCm/hipTensor

2024-01-03 07:25 UTC, srekolam commented on var/spack/repos/builtin/packages/hip-tensor/package.py
> +    tags = ["rocm"]
can you update the homepage and git and url to https://github.com/ROCm/hipTensor ; https://github.com/ROCm/hipTensor.git ; https://github.com/ROCm/hipTensor/archive/refs/tags/rocm-5.7.0.tar.gz

2024-01-09 17:38 UTC, alalazo approved these changes

2024-01-09 17:39 UTC, merged