py-pyfftw: Fix older versions, add 0.13.1
LLNL/spack pull request #41037
Opened 2023-11-13 06:58 UTC by moloney

Previous versions were broken due to issue when installing directly from git repo root (maybe the expectation was that an "sdist" was built first?), fix by patching setup.py

Adds latest 0.13.1 release which switches from setup.py to pyproject.toml and doesn't need any fix.

2023-11-18 14:41 UTC, adamjstewart requested changes

2023-11-18 14:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyfftw/fix_setup.patch
> ++        'packages': ['pyfftw']
```suggestion
+        'packages': ['pyfftw', 'pyfftw.builders', 'pyfftw.interfaces']
```
You can see that this package list is supposed to be added below, but isn't for some reason. It looks like `pip install` runs `python setup.py egg_info` before it does anything else, which is why it is skipped.

2023-11-18 14:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyfftw/package.py
>      depends_on("py-numpy@1.6:", type=("build", "run"), when="@:0.10.4")
Build deps need to be updated:
```
    "setuptools<=59.4.0",
    "Cython>=0.29.18",
```
and:
```
        build_requires.append('cython>=0.29.18, <1.0')                                   
```
Same with numpy dep:
```
    numpy_requirement = 'numpy>=1.20, <2.0'                                              
```

2025-06-15 12:40 UTC, alalazo commented
Closing, since there has been no activity in a while and we moved the package repository. Feel free to reopen at / migrate to https://github.com/spack/spack-packages if you want to continue work on this.

2025-06-15 12:40 UTC, closed without merging