py-jsonpath-ng: version bump
LLNL/spack pull request #41078
Opened 2023-11-15 12:11 UTC by heerener

Pushing internal version bump to 1.5.3, adding 1.6.9 since I'm here anyway.

2023-11-16 00:59 UTC, tldahlgren requested changes
Confirmed one of the two version sha256.  There is no `1.6.9` so please correct the version directive for `1.6.0`.

2023-11-16 00:59 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-jsonpath-ng/package.py
> +    version("1.6.9", sha256="5483f8e9d74c39c9abfab554c070ae783c1c8cbadf5df60d561bc705ac68a07e")
There is no `1.6.9` version, I think you mean `1.6.0` (which DOES have that sha256).

2023-11-16 16:45 UTC, heerener commented on var/spack/repos/builtin/packages/py-jsonpath-ng/package.py
> +    version("1.6.9", sha256="5483f8e9d74c39c9abfab554c070ae783c1c8cbadf5df60d561bc705ac68a07e")
Oh, thanks for catching that! Indeed, typo.

2023-11-16 18:41 UTC, tldahlgren approved these changes
Thanks for the correction.  Will still defer merge decision to @adamjstewart as the python package guru.

2023-11-17 08:03 UTC, manuelakuhn approved these changes

2023-11-18 13:54 UTC, adamjstewart approved these changes

2023-11-18 13:54 UTC, merged