py-pygithub: new versions, dependencies
LLNL/spack pull request #41072
Opened 2023-11-14 22:23 UTC by wdconinc

This adds the most recent v1 version, and the latest version (v2). Updated dependencies (from requirements.txt). The `py-pyjwt@2.4.0:` requirement was to avoid a CVE in pyjwt, not for a technical reason.

2023-11-16 01:12 UTC, tldahlgren reviewed
FYI. Confirmed the two new version sha256.

2023-11-17 07:54 UTC, manuelakuhn submitted a review, later dismissed
Optional:
It makes reviewing easier if you specify the dependencies in the same order as they are listed in the package requirements (here of the newest package)

Other than that, LGTM

2023-11-17 18:47 UTC, wdconinc commented
> in the same order as they are listed in the package requirements

Reordered. Thanks for the suggestion.

2023-11-17 22:00 UTC, manuelakuhn submitted a review, later dismissed

2023-11-18 13:08 UTC, adamjstewart requested changes

2023-11-18 13:08 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pygithub/package.py
> +
Missing build dep on py-setuptools-scm

2023-11-18 15:12 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-pygithub/package.py
>      depends_on("py-setuptools", type="build")
```suggestion
    depends_on("py-setuptools", type="build")
    depends_on("py-setuptools-scm", type="build", when="@1.58.1:")
```

2023-11-18 15:13 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-pygithub/package.py
> +
In 4a806ef.

2023-11-18 15:34 UTC, adamjstewart approved these changes

2023-11-18 15:57 UTC, merged