add seissol package
LLNL/spack pull request #41176
Opened 2023-11-20 12:34 UTC by Thomas-Ulrich

WIP to add a SeisSol package

2023-11-20 12:57 UTC, Thomas-Ulrich commented
@alalazo  (or any other spack developer willing to help): is there a way in spack to run several times cmake/build/install with different arguments. E.g. for the seissol package, it would make sense to generate a bundle of executables with different equations and convergence_order. Is it possible?
```
cmake -DORDER=4
make install
cmake -DORDER=6
make install
```

2024-10-17 03:17 UTC, bernhardkaindl requested changes
```py
bin/spack install seissol~asagi~memkind~mpi~netcdf+convergence_order@1.1.2
==> Error: invalid values for variant 'convergence_order' in package seissol: 'True'
```

mpi.h is not found in most other variants.
```py
.stage/spack-stage-easi-1.3.0-h6twcqbfu2fsyjggtkc7m6xuucdmredi/spack-src/python_bindings/easi_wrapper.cpp:4:10: fatal error: mpi.h: No such file or directory
    4 | #include <mpi.h>
      |          ^~~~~~~
```

@Thomas-Ulrich Do you want to fix this PR?

2024-10-17 05:57 UTC, Thomas-Ulrich commented
Thank you.
Actually I never thought of compiling without mpi, but I will fix it. Thx for checking.

By the way, convergence_order is not a boolean:
```
   variant(
        "convergence_order",
        default="4",
        description="polynomial degree plus one",
        values=(str(v) for v in range(2, 9)),
        multi=False,
    )
 ```

2024-10-17 17:37 UTC, Thomas-Ulrich commented
I removed the mpi variant, and added a mpi dependency to easi with +python to fix the problem.

2024-10-23 12:29 UTC, bernhardkaindl reviewed
This command failed: `bin/spack install -v --fail-fast seissol+python`
<details><summary>Failed spec: seissol+python</summary>

### `seissol+python`:
<details><summary>Head of the raw log for seissol+python</summary>

```py
-- The CXX compiler identification is GNU 13.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/bkaindl/spack/lib/spack/env/gcc/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/bkaindl/spack/lib/spack/env/gcc/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Compiling SeisSol for CPU
-- GEMM_TOOLS are: LIBXSMM,PSpaMM
-- Memory alignment has been set to 32 B.
-- Vector size has been set to 32 B.
-- Version: develop-2024-10-13-189-g553df8f1be (dirty)
-- Last commit: 553df8f1be3cc4335b6cc86fb15f7974ff2133a1 at 2024-10-18T08:41:28+02:00
-- Found Python3: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/python-3.11.9-cecw2bsbqslg566j6vjq3gr67mnzzqlu/bin/python3.11 (found version "3.11.9") found components: Interpreter
-- Found Libxsmm_executable: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libxsmm-1.17-cp2k-cfkqusd5tkf3jjtoyjbjajcp3thpzuni/bin/libxsmm_gemm_generator
-- Found PSpaMM: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/py-pspamm-develop-m3wchuj7pjdjjnyrz2aimvao7dpbykyn/pspamm.py
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Found PkgConfig: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/pkgconf-2.2.0-7e2zajbz5u64wqdd7d4bz5yd5vmrlo4n/bin/pkg-config (found version "2.2.0")
-- Checking for module 'asagi'
--   Found asagi, version 1.0
-- Checking for module 'netcdf'
--   Found netcdf, version 4.9.2
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found MPI_C: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/openmpi-5.0.5-f23issskthtf5qqymj2ldsnl2ef4rahv/lib/libmpi.so (found version "3.1")
-- Found MPI_CXX: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/openmpi-5.0.5-f23issskthtf5qqymj2ldsnl2ef4rahv/lib/libmpi.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- Found NUMA: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/numactl-2.0.18-fpihslgxwrhnspc6mohfmeoq7dkxx7j3
-- Found HDF5: hdf5-shared (found version "1.14.5") found components: C HL
-- Performing Test METIS_TEST_RUNS
-- Performing Test METIS_TEST_RUNS - Success
-- Performing Test _METIS_64_BIT_INTEGER
-- Performing Test _METIS_64_BIT_INTEGER - Success
-- Found METIS: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/metis-5.1.0-cg6ar3m2p4ptq22tfszzcjzsnoauckxt/lib/libmetis.so
...

```
</details>
```py
          This deprecation is overdue, please update your project and remove deprecated
          calls to avoid build errors in the future.

          See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
          This deprecation is overdue, please update your project and remove deprecated
          calls to avoid build errors in the future.

          See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
  copying Lib/fontTools/cu2qu/cu2qu.py -> build/lib/fontTools/cu2qu
  copying Lib/fontTools/cu2qu/errors.py -> build/lib/fontTools/cu2qu
  copying Lib/fontTools/cu2qu/__init__.py -> build/lib/fontTools/cu2qu
  copying Lib/fontTools/cu2qu/cli.py -> build/lib/fontTools/cu2qu
  copying Lib/fontTools/ufoLib/filenames.py -> build/lib/fontTools/ufoLib
  copying Lib/fontTools/ufoLib/errors.py -> build/lib/fontTools/ufoLib
  copying Lib/fontTools/ufoLib/__init__.py -> build/lib/fontTools/ufoLib
  copying Lib/fontTools/ufoLib/converters.py -> build/lib/fontTools/ufoLib
  creating build/lib/fontTools/feaLib
  copying Lib/fontTools/feaLib/error.py -> build/lib/fontTools/feaLib
  copying Lib/fontTools/feaLib/variableScalar.py -> build/lib/fontTools/feaLib
  copying Lib/fontTools/feaLib/lookupDebugInfo.py -> build/lib/fontTools/feaLib
  creating build/lib/fontTools/otlLib
  copying Lib/fontTools/otlLib/error.py -> build/lib/fontTools/otlLib
  copying Lib/fontTools/otlLib/__init__.py -> build/lib/fontTools/otlLib
  copying Lib/fontTools/otlLib/maxContextCalc.py -> build/lib/fontTools/otlLib
  copying Lib/fontTools/varLib/mvar.py -> build/lib/fontTools/varLib
  copying Lib/fontTools/varLib/errors.py -> build/lib/fontTools/varLib
  copying Lib/fontTools/varLib/__init__.py -> build/lib/fontTools/varLib
  copying Lib/fontTools/varLib/plot.py -> build/lib/fontTools/varLib
  creating build/lib/fontTools/voltLib
  copying Lib/fontTools/voltLib/error.py -> build/lib/fontTools/voltLib
  copying Lib/fontTools/voltLib/__init__.py -> build/lib/fontTools/voltLib
  copying Lib/fontTools/voltLib/lexer.py -> build/lib/fontTools/voltLib
  copying Lib/fontTools/colorLib/unbuilder.py -> build/lib/fontTools/colorLib
  copying Lib/fontTools/colorLib/errors.py -> build/lib/fontTools/colorLib
  copying Lib/fontTools/colorLib/__init__.py -> build/lib/fontTools/colorLib
  copying Lib/fontTools/colorLib/table_builder.py -> build/lib/fontTools/colorLib
  copying build/lib/fontTools/cu2qu/cu2qu.py -> build/bdist.linux-x86_64/wheel/fontTools/cu2qu
  copying build/lib/fontTools/cu2qu/errors.py -> build/bdist.linux-x86_64/wheel/fontTools/cu2qu
  copying build/lib/fontTools/cu2qu/__init__.py -> build/bdist.linux-x86_64/wheel/fontTools/cu2qu
  copying build/lib/fontTools/cu2qu/cli.py -> build/bdist.linux-x86_64/wheel/fontTools/cu2qu
  copying build/lib/fontTools/ufoLib/filenames.py -> build/bdist.linux-x86_64/wheel/fontTools/ufoLib
  copying build/lib/fontTools/ufoLib/errors.py -> build/bdist.linux-x86_64/wheel/fontTools/ufoLib
  copying build/lib/fontTools/ufoLib/__init__.py -> build/bdist.linux-x86_64/wheel/fontTools/ufoLib
  copying build/lib/fontTools/ufoLib/converters.py -> build/bdist.linux-x86_64/wheel/fontTools/ufoLib
  creating build/bdist.linux-x86_64/wheel/fontTools/feaLib
  copying build/lib/fontTools/feaLib/error.py -> build/bdist.linux-x86_64/wheel/fontTools/feaLib
  copying build/lib/fontTools/feaLib/variableScalar.py -> build/bdist.linux-x86_64/wheel/fontTools/feaLib
  copying build/lib/fontTools/feaLib/lookupDebugInfo.py -> build/bdist.linux-x86_64/wheel/fontTools/feaLib
  creating build/bdist.linux-x86_64/wheel/fontTools/otlLib
  copying build/lib/fontTools/otlLib/error.py -> build/bdist.linux-x86_64/wheel/fontTools/otlLib
  creating build/bdist.linux-x86_64/wheel/fontTools/otlLib/optimize
  copying build/lib/fontTools/otlLib/optimize/gpos.py -> build/bdist.linux-x86_64/wheel/fontTools/otlLib/optimize
  copying build/lib/fontTools/varLib/mvar.py -> build/bdist.linux-x86_64/wheel/fontTools/varLib
  copying build/lib/fontTools/varLib/errors.py -> build/bdist.linux-x86_64/wheel/fontTools/varLib
  copying build/lib/fontTools/varLib/__init__.py -> build/bdist.linux-x86_64/wheel/fontTools/varLib
  copying build/lib/fontTools/varLib/plot.py -> build/bdist.linux-x86_64/wheel/fontTools/varLib
  creating build/bdist.linux-x86_64/wheel/fontTools/voltLib
  copying build/lib/fontTools/voltLib/error.py -> build/bdist.linux-x86_64/wheel/fontTools/voltLib
  copying build/lib/fontTools/voltLib/__init__.py -> build/bdist.linux-x86_64/wheel/fontTools/voltLib
  copying build/lib/fontTools/voltLib/lexer.py -> build/bdist.linux-x86_64/wheel/fontTools/voltLib
  copying build/lib/fontTools/colorLib/unbuilder.py -> build/bdist.linux-x86_64/wheel/fontTools/colorLib
  copying build/lib/fontTools/colorLib/errors.py -> build/bdist.linux-x86_64/wheel/fontTools/colorLib
  copying build/lib/fontTools/colorLib/__init__.py -> build/bdist.linux-x86_64/wheel/fontTools/colorLib
  copying [...]

2024-10-23 12:51 UTC, bernhardkaindl reviewed
It seems to always require Numpy:
https://seissol.readthedocs.io/en/latest/installing-dependencies.html
> Installing Dependencies[](https://seissol.readthedocs.io/en/latest/installing-dependencies.html#installing-dependencies)
> In order to run SeisSol, you need to first install:
>    Python (>= 3.5)
>    Numpy (>= 1.12.0)

- So it looks like it is better to make `+python` the only case and remove `~python`.

This command failed: `bin/spack install -v --fail-fast seissol~python`
<details><summary>Failed spec: seissol~python</summary>

### `seissol~python`:
<details><summary>Head of the raw log for seissol~python</summary>

```py
-- The CXX compiler identification is GNU 13.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/bkaindl/spack/lib/spack/env/gcc/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/bkaindl/spack/lib/spack/env/gcc/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Compiling SeisSol for CPU
-- GEMM_TOOLS are: LIBXSMM,PSpaMM
-- Memory alignment has been set to 32 B.
-- Vector size has been set to 32 B.
-- Version: develop-2024-10-13-189-g553df8f1be (dirty)
-- Last commit: 553df8f1be3cc4335b6cc86fb15f7974ff2133a1 at 2024-10-18T08:41:28+02:00
-- Found Python3: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/python-venv-1.0-44mwtelifjsiadwo2cwyasoe2y2zol5b/bin/python3.11 (found version "3.11.9") found components: Interpreter
-- Found Libxsmm_executable: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libxsmm-1.17-cp2k-cfkqusd5tkf3jjtoyjbjajcp3thpzuni/bin/libxsmm_gemm_generator
-- Found PSpaMM: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/py-pspamm-develop-m3wchuj7pjdjjnyrz2aimvao7dpbykyn/pspamm.py
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Found PkgConfig: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/pkgconf-2.2.0-7e2zajbz5u64wqdd7d4bz5yd5vmrlo4n/bin/pkg-config (found version "2.2.0")
-- Checking for module 'asagi'
--   Found asagi, version 1.0
-- Checking for module 'netcdf'
--   Found netcdf, version 4.9.2
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found MPI_C: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/openmpi-5.0.5-f23issskthtf5qqymj2ldsnl2ef4rahv/lib/libmpi.so (found version "3.1")
-- Found MPI_CXX: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/openmpi-5.0.5-f23issskthtf5qqymj2ldsnl2ef4rahv/lib/libmpi.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- Found NUMA: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/numactl-2.0.18-fpihslgxwrhnspc6mohfmeoq7dkxx7j3
-- Found HDF5: hdf5-shared (found version "1.14.5") found components: C HL
-- Performing Test METIS_TEST_RUNS
-- Performing Test METIS_TEST_RUNS - Success
-- Performing Test _METIS_64_BIT_INTEGER
-- Performing Test _METIS_64_BIT_INTEGER - Success
-- Found METIS: /home/bkaindl/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/metis-5.1.0-cg6ar3m2p4ptq22tfszzcjzsnoauckxt/lib/libmetis.so
...

```
</details>

```py
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
make[2]: *** [CMakeFiles/SeisSol-codegen.dir/build.make:99: src/generated_code/subroutine.h] Error 1
make[2]: Leaving directory '.stage/spack-stage-seissol-1.2.0-g7fiwl4o5o3mda6iv6rbxoyuzyed5lj2/spack-build-g7fiwl4'
make: *** [Makefile:139: all] Error 2
==> Error: ProcessError: Command exited with status 2:
    make -j64

     91        import numpy as np
     92    ModuleNotFoundError: No module named 'numpy'
  >> 93    make[2]: *** [CMakeFiles/SeisSol-codegen.dir/build.make:99: src/generated_code/subroutine.h] Error 1
     94    make[2]: Leaving directory '.stage/spack-stage-seissol-1.2.0-g7fiwl4o5o3mda6iv6rbxoyuzyed5lj2/spack-build-g7fiwl4'
  >> 95    make[1]: *** [CMakeFiles/Makefile2:126: CMakeFiles/SeisSol-codegen.dir/all] Error 2
     96    make[1]: Leaving directory '.stage/spack-stage-seissol-1.2.0-g7fiwl4o5o3mda6iv6rbxoyuzyed5lj2/spack-build-g7fiwl4'
  >> 97    make: *** [Makefile:139: all] Error 2
```

</details>



<details><summary>Expand the spec output `spack spec seissol~python`</summary>

```yaml
Input spec
--------------------------------
 -   seissol~python

Concretized
--------------------------------
 -   seissol@1.2.0%gcc@13.1.0+asagi~cuda~intel_gpu~ipo+memkind+netcdf~python~rocm convergence_order=4 dr_quad_rule=stroud equations=elastic gemm_tools_list=LIBXSMM,PSpaMM graph_partitioning_libs=parmetis number_of_mechanisms=3 plasticity_method=nb precision=double
[+]      ^asagi@1.0.1%gcc@13.1.0~examples+fortran~ipo+mpi+mpi3+numa~tests+threadsafe~threadsafe_counter+threadsafe_mpi link_type=shared max_dimensions=4
[+]          ^numactl@2.0.18%gcc@13.1.0
[+]      ^cmake@3.30.2%gcc@13.1.0~doc+ncurses+ownlibs~qtgui patches=dbc3892
[+]          ^curl@8.8.0%gcc@13.1.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 libs=shared,static tls=openssl
[+]              ^nghttp2@1.63.0%gcc@13.1.0
[+]              ^openssl@3.3.1%gcc@13.1.0~docs+shared certs=mozilla
[+]                  ^ca-certificates-mozilla@2023-05-30%gcc@13.1.0
[+]          ^ncurses@6.5%gcc@13.1.0~symlinks+termlib abi=none patches=7a351bc
[+]          ^zlib-ng@2.2.1%gcc@13.1.0+compat+new_strategies+opt+pic+shared
[+]      ^easi@1.5.0%gcc@13.1.0+asagi~ipo+python jit=impalajit,lua
[+]          ^impalajit@main%gcc@13.1.0~ipo+shared
[+]          ^lua@5.3.2%gcc@13.1.0~pcfile+shared fetcher=curl
[+]              ^readline@8.2%gcc@13.1.0 patches=bbf97f1
[+]              ^unzip@6.0%gcc@13.1.0 patches=881d2ed,f6f6236
[+]          ^py-pybind11@2.13.5%gcc@13.1.0+ipo
[+]              ^ninja@1.12.1%gcc@13.1.0+re2c
[+]                  ^re2c@3.1%gcc@13.1.0
[+]              ^py-setuptools@69.2.0%gcc@13.1.0
[+]          ^python@3.11.9%gcc@13.1.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib patches=13fa8bf,b0615b2,ebdca64,f2fd060
[+]              ^expat@2.6.3%gcc@13.1.0+libbsd
[+]                  ^libbsd@0.12.2%gcc@13.1.0
[+]                      ^libmd@1.0.4%gcc@13.1.0
[+]              ^gdbm@1.23%gcc@13.1.0
[+]              ^gettext@0.22.5%gcc@13.1.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz
[+]                  ^libiconv@1.17%gcc@13.1.0 libs=shared,static
[+]                  ^tar@1.34%gcc@13.1.0 zip=pigz
[+]                      ^pigz@2.8%gcc@13.1.0
[+]              ^libffi@3.4.6%gcc@13.1.0
[+]              ^libxcrypt@4.4.35%gcc@13.1.0~obsolete_api patches=4885da3
[+]              ^sqlite@3.46.0%gcc@13.1.0+column_metadata+dynamic_extensions+fts~functions+rtree
[+]              ^util-linux-uuid@2.40.2%gcc@13.1.0
[+]              ^xz@5.4.6%gcc@13.1.0~pic libs=shared,static
[+]          ^python-venv@1.0%gcc@13.1.0
[+]      ^eigen@3.4.0%gcc@13.1.0~ipo
[+]      ^gcc-runtime@13.1.0%gcc@13.1.0
[e]      ^glibc@2.35%gcc@13.1.0
[+]      ^gmake@4.4.1%gcc@13.1.0~guile
[+]      ^hdf5@1.14.5%gcc@13.1.0~cxx~fortran+hl~ipo~java~map+mpi+shared~subfiling~szip+threadsafe+tools api=default
[+]          ^pkgconf@2.2.0%gcc@13.1.0
[+]      ^libxsmm@1.17-cp2k%gcc@13.1.0~debug+generator~header-only~large_jit_buffer~shared blas=default
[+]          ^binutils@2.43.1%gcc@13.1.0+gas~gold~gprofng~headers~interwork+ld~libiberty~lto~nls~pgo+plugins compress_debug_sections=zlib libs=shared,static
[+]              ^diffutils@3.10%gcc@13.1.0
[+]      ^memkind@1.14.0%gcc@13.1.0
[+]          ^autoconf@2.72%gcc@13.1.0
[+]          ^automake@1.16.5%gcc@13.1.0
[+]          ^libtool@2.4.7%gcc@13.1.0
[+]              ^findutils@4.9.0%gcc@13.1.0 patches=440b954
[+]          ^m4@1.4.19%gcc@13.1.0+sigsegv [...]

2024-10-23 13:38 UTC, Thomas-Ulrich commented
Either you install python and its modules via spack with the +python and it won't fails (+python).
Or you use your own system, or anaconda python, and you ensure that it has the required modules (~python).

In your case, I suppose your system python does not have numpy.

2024-10-23 13:54 UTC, Thomas-Ulrich commented
after realizing that if arch=x86_64_v4,  self.spec.target.family == "x86_64", I've updated the package.

2024-10-23 14:28 UTC, bernhardkaindl requested changes
> Either you install python and its modules via spack with the +python >  > variant and it won't fail.
> Or you use your own system/anaconda python, and you have to ensure that it has the required modules (~python).
> In your case, I suppose your system python does not have numpy.

In `spack`, `~python` means that the Python support in the package is disabled, not that certain Python packages need to be provided by the host.

BTW/off-topic: Spack has a provision to use so-called "external" packages, by `spack external find <package>`. It adds "fake" packages to the spack package database that say that that package is provided (but by the host). But it does not work well (usually host packages are older and cause issues). I have not seen it used for Python dependencies yet. 

This is the only time that I've seen the idea to use python modules from the host, and "~python" has the meaning to disable Python, not use use python modules from host.

I think it will likely fail as soon as someone uses an environment that has a python package in that environment. Then, the python in the environment is that python (could work if that python was added with 

Do you want to use this "use Python from the host" mode?

From what I can see, it would be better to use this instead of the `~python` variant:
```py
spack external find python
==> The following specs have been detected on this system and added to /home/bkaindl/.spack/packages.yaml
python@3.10.12
```
Using that version of `python` would then force that environment to use the external Python:
```py
spack install seissol+reuse_host_scipy ^python@3.10.12
```
`+reuse_host_scipy` would disable the dependencies:
```py
# If +reuse_host_scipy is set, expect the host to have numpy and scipy, else spack adds them:
with when("~reuse_host_scipy"):
    with default_args(type="build"):
        depends_on("py-numpy@1.12:")
        depends_on("py-scipy")
        depends_on("py-matplotlib")
```
Would that be ok for you?

2024-10-23 14:54 UTC, bernhardkaindl commented
Hmm, that's not so easy either, as one has to make sure that the host's python is used and/or all +python variants are disabled (could be possible...), but there is even a python dependency in the build  itself:

This pulls python into the build because it is a Python package:
```py
depends_on("py-pspamm", when="gemm_tools_list=PSpaMM")
```
When this variant is active, you always will have to force it to use an external Python spack package.

The host python is hidden by `easi+python` which pulls spack's python into the build by default:

`bin/spack spec seissol+use-host-py | tee seissol+use-host-py.spec`:
```py
[+]      ^easi@1.5.0%gcc@13.1.0+asagi~ipo+python build_system=cmake build_type=Release generator=make jit=impalajit,lua arch=linux-ubuntu22.04-skylake[+]          ^impalajit@main%gcc@13.1.0~ipo+shared build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-skylake
[+]          ^lua@5.3.2%gcc@13.1.0~pcfile+shared build_system=makefile fetcher=curl arch=linux-ubuntu22.04-skylake
[+]              ^readline@8.2%gcc@13.1.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu22.04-skylake
[+]              ^unzip@6.0%gcc@13.1.0 build_system=makefile patches=881d2ed,f6f6236 arch=linux-ubuntu22.04-skylake
[+]          ^py-pybind11@2.13.5%gcc@13.1.0+ipo build_system=cmake build_type=Release generator=ninja arch=linux-ubuntu22.04-skylake
[+]              ^ninja@1.12.1%gcc@13.1.0+re2c build_system=generic arch=linux-ubuntu22.04-skylake
[+]                  ^re2c@3.1%gcc@13.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]              ^py-setuptools@69.2.0%gcc@13.1.0 build_system=generic arch=linux-ubuntu22.04-skylake
[+]          ^python@3.11.9%gcc@13.1.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060 arch=linux-ubuntu22.04-skylake
[+]              ^expat@2.6.3%gcc@13.1.0+libbsd build_system=autotools arch=linux-ubuntu22.04-skylake
[+]                  ^libbsd@0.12.2%gcc@13.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]                      ^libmd@1.0.4%gcc@13.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]              ^gdbm@1.23%gcc@13.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]              ^gettext@0.22.5%gcc@13.1.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-ubuntu22.04-skylake
[+]                  ^libiconv@1.17%gcc@13.1.0 build_system=autotools libs=shared,static arch=linux-ubuntu22.04-skylake
[+]                  ^tar@1.34%gcc@13.1.0 build_system=autotools zip=pigz arch=linux-ubuntu22.04-skylake
[+]                      ^pigz@2.8%gcc@13.1.0 build_system=makefile arch=linux-ubuntu22.04-skylake
[+]              ^libffi@3.4.6%gcc@13.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]              ^libxcrypt@4.4.35%gcc@13.1.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-ubuntu22.04-skylake
[+]              ^sqlite@3.46.0%gcc@13.1.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-ubuntu22.04-skylake
[+]              ^util-linux-uuid@2.40.2%gcc@13.1.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]              ^xz@5.4.6%gcc@13.1.0~pic build_system=autotools libs=shared,static arch=linux-ubuntu22.04-skylake
[+]          ^python-venv@1.0%gcc@13.1.0 build_system=generic arch=linux-ubuntu22.04-skylake
```

2024-10-23 14:58 UTC, Thomas-Ulrich commented
yes right, I guess it makes sense to remove the python variant then.

2024-10-23 15:00 UTC, bernhardkaindl commented
I have a refactor to not use it ready - I would push two commits:
- commit 1 with the attempt to use an external python
- commit 2 to remove the variant for external python

2024-10-23 15:09 UTC, bernhardkaindl reviewed
Build results on Ubuntu 22.04.4 LTS: These changed specs were found `gh pr diff`:
- `seissol`

The following specs were built (or installed) to check this PR:
### Using linux-ubuntu22.04-skylake / gcc@13.1.0:
<details><summary>Click on this line to unfold and refold the dependencies of this build


```py
seissol@1.1.2+asagi_gpu+memkind+netcdf build_system=cmake convergence_order=4 dr_quad_rule=stroud equations=elastic gemm_tools_list=LIBXSMM,PSpaMM graph_partitioning_libs=parmetis number_of_mechanisms=3 plasticity_method=nb precision=double
```
</summary>

Dependency tree (disabled variants are removed for the make the list the dependencies brief):
```py
seissol@1.1.2+asagi~cuda~intel_gpu~ipo+memkind+netcdf~rocm build_system=cmake build_type=Release convergence_order=4 dr_quad_rule=stroud equations=elastic gemm_tools_list=LIBXSMM,PSpaMM generator=make graph_partitioning_libs=parmetis number_of_mechanisms=3 plasticity_method=nb precision=double
    asagi@1.0.1+fortran+mpi+mpi3+numa+threadsafe_counter+threadsafe_mpi build_system=cmake link_type=shared max_dimensions=4
        numactl@2.0.18
    cmake@3.30.2+ncurses+ownlibs build_system=generic patches=dbc3892
        curl@8.8.0+nghttp2 libs=shared,static tls=openssl
            nghttp2@1.63.0
        ncurses@6.5+termlib abi=none patches=7a351bc
        zlib-ng@2.2.1+compat+new_strategies+opt+pic+shared
    easi@1.5.0+asagi+python build_system=cmake jit=impalajit,lua
        impalajit@main+shared build_system=cmake
        lua@5.3.2+shared build_system=makefile fetcher=curl
            unzip@6.0 build_system=makefile patches=881d2ed,f6f6236
        py-pybind11@2.13.5+ipo build_system=cmake generator=ninja
        python-venv@1.0 build_system=generic
    eigen@3.4.0 build_system=cmake build_type=RelWithDebInfo
    gcc-runtime@13.1.0 build_system=generic
    glibc@2.35
    gmake@4.4.1 build_system=generic
    hdf5@1.14.5+hl+mpi+shared+threadsafe+tools api=default build_system=cmake
        pkgconf@2.2.0
    libxsmm@1.17+generator-only_jit_buffer blas=default build_system=makefile
        binutils@2.43.1+gas+ld+plugins compress_debug_sections=zlib libs=shared,static
            diffutils@3.10
    memkind@1.14.0
        autoconf@2.72
        automake@1.16.5
        libtool@2.4.7
            findutils@4.9.0 patches=440b954
        m4@1.4.19+sigsegv patches=9dc5fbd,bfdffa7
            libsigsegv@2.14
    metis@5.1.0+int64+shared build_system=cmake patches=4991da9,93a7903,b1225da
    netcdf-c@4.9.2+blosc+mpi_zip+optimize-netcdf+pic+shared+szip+zstd patches=0161eb8
        bzip2@1.0.8+shared build_system=generic
        c-blosc@1.21.5+avx2 build_system=cmake
            lz4@1.10.0+pic build_system=makefile libs=shared,static
            snappy@1.2.1+pic+shared build_system=cmake
        libaec@1.0.6+shared build_system=cmake
        zstd@1.5.6+programs build_system=makefile compression=none libs=shared,static
    openmpi@5.0.5+atomics-hwloc-libevent-pmix+rsh+vt+wrapper-rpath fabrics=none romio-filesystem=none schedulers=none
        hwloc@2.11.1+libxml2-level-zero+pci libs=shared,static
            libpciaccess@0.17
                util-macros@1.20.1
            libxml2@2.10.3+pic+shared
        libevent@2.1.12+openssl
        openssh@9.8p1+gssapi
            krb5@1.21.2+shared
                bison@3.8.2
            libedit@3.1-20240808
        perl@5.40.0+cpanm+opcode+open+shared+threads build_system=generic
            berkeley-db@18.1.40+cxx+stl patches=26090f4,b231fcc
        pmix@5.0.3
    parmetis@4.0.3+int64+shared build_system=cmake patches=4f89253,50ed208,704b84f
    py-matplotlib@3.9.2 backend=agg build_system=python_pip
        freetype@2.13.3+pic+shared
        libpng@1.6.39 build_system=cmake libs=shared,static
        ninja@1.12.1+re2c build_system=generic
            re2c@3.1
        py-contourpy@1.3.0 build_system=python_pip
            meson@1.5.1 build_system=python_pip patches=0f0b1bd
        py-cycler@0.11.0 build_system=python_pip
        py-fonttools@4.39.4 build_system=python_pip
        py-kiwisolver@1.4.5 build_system=python_pip
            py-cppy@1.2.1 build_system=python_pip
        py-meson-python@0.16.0 build_system=python_pip
            py-pyproject-metadata@0.7.1 build_system=python_pip
        py-packaging@24.1 build_system=python_pip
            py-flit-core@3.9.0 build_system=python_pip
        py-pillow-simd@9.5.0.post1+jpeg+zlib build_system=python_pip
            libjpeg-turbo@3.0.3_decoder+pic build_system=cmake libs=shared,static
                nasm@2.16.03
        py-pip@23.1.2 build_system=generic
        py-pyparsing@3.1.2 build_system=python_pip
        py-python-dateutil@2.8.2 build_system=python_pip
            py-six@1.16.0 build_system=python_pip
        py-setuptools-scm@8.0.4+toml build_system=python_pip
            git@2.45.2+man+nls+perl+subtree
                libidn2@2.3.7
                    libunistring@1.2
                pcre2@10.44+multibyte
            py-tomli@2.0.1 build_system=python_pip
            py-typing-extensions@4.12.2 build_system=python_pip
        py-wheel@0.41.2 build_system=generic
        qhull@2020.2 build_system=cmake
            cmake@3.30.2+ncurses+ownlibs build_system=generic patches=dbc3892
                curl@8.8.0+nghttp2 libs=shared,static tls=openssl
                    openssl@1.1.1w+shared build_system=generic certs=mozilla
    py-numpy@2.1.2 build_system=python_pip patches=873745d
        openblas@0.3.28_fpcsr+dynamic_dispatch+fortran+locking+pic+shared build_system=makefile patches=d0b9276 symbol_suffix=none threads=none
        py-cython@3.0.11 build_system=python_pip
    py-pspamm@develop build_system=python_pip
    py-scipy@1.14.1 build_system=python_pip
        py-pythran@0.16.1 build_system=python_pip
            py-beniget@0.4.1 build_system=python_pip
            py-gast@0.5.4 build_system=python_pip
            py-ply@3.11 build_system=python_pip
    py-setuptools@69.2.0 build_system=generic
    python@3.11.9+bz2+crypt+ctypes+dbm+libxml2+lzma+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060
        expat@2.6.3+libbsd
            libbsd@0.12.2
                libmd@1.0.4
        gdbm@1.23
        gettext@0.22.5+bzip2+curses+git+libxml2+pic+shared+tar+xz
            libiconv@1.17 libs=shared,static
            tar@1.34 zip=pigz
                pigz@2.8 build_system=makefile
        libffi@3.4.6
        libxcrypt@4.4.35_api patches=4885da3
        openssl@3.3.1+shared build_system=generic certs=mozilla
            ca-certificates-mozilla@2023-05-30 build_system=generic
        readline@8.2 patches=bbf97f1
        sqlite@3.46.0+column_metadata+dynamic_extensions+fts+rtree
        util-linux-uuid@2.40.2
        xz@5.4.6 libs=shared,static
    yaml-cpp@0.6.2+pic+shared build_system=cmake
```
</details><details><summary>Click on this line to unfold and refold the dependencies of this build


```py
seissol@1.1.3+asagi_gpu+memkind+netcdf-host-py build_system=cmake convergence_order=4 dr_quad_rule=stroud equations=elastic gemm_tools_list=LIBXSMM,PSpaMM graph_partitioning_libs=parmetis number_of_mechanisms=3 plasticity_method=nb precision=double
```
</summary>

Dependency tree (disabled variants are removed for the make the list the dependencies brief):
```py
seissol@1.1.3+asagi~cuda~intel_gpu~ipo+memkind+netcdf~rocm~use-host-py build_system=cmake build_type=Release convergence_order=4 dr_quad_rule=stroud equations=elastic gemm_tools_list=LIBXSMM,PSpaMM generator=make graph_partitioning_libs=parmetis number_of_mechanisms=3 plasticity_method=nb precision=double
    asagi@1.0.1+fortran+mpi+mpi3+numa+threadsafe_counter+threadsafe_mpi build_system=cmake link_type=shared max_dimensions=4
        numactl@2.0.18
    cmake@3.30.2+ncurses+ownlibs build_system=generic patches=dbc3892
        curl@8.8.0+nghttp2 libs=shared,static tls=openssl
            nghttp2@1.63.0
        ncurses@6.5+termlib abi=none patches=7a351bc
        zlib-ng@2.2.1+compat+new_strate [...]

2024-10-23 15:16 UTC, bernhardkaindl approved these changes
Looks good to me, and as @Thomas-Ulrich is also a maintainer of `easi`, no further package maintainer approvals should be needed.

The change to libxsmm is a fix for the least PR on libxsmm that added the special version for CP2K that broke build of sessol and should not be the prefered version, thus adding 1.17 as it was requested originally in that PR:
```py
--- a/var/spack/repos/builtin/packages/libxsmm/package.py
+++ b/var/spack/repos/builtin/packages/libxsmm/package.py
@@ -28,7 +28,11 @@ class Libxsmm(MakefilePackage):
     version("main-2023-11", commit="0d9be905527ba575c14ca5d3b4c9673916c868b2")
     version("main", branch="main")
     version("1.17-cp2k", commit="6f883620f58afdeebab28039fc9cf580e76a5ec6")
-    version("1.17", sha256="8b642127880e92e8a75400125307724635ecdf4020ca4481e5efe7640451bb92")
+    version(
+        "1.17",
+        sha256="8b642127880e92e8a75400125307724635ecdf4020ca4481e5efe7640451bb92",
+        preferred=True,
+    )
     version("1.16.3", sha256="e491ccadebc5cdcd1fc08b5b4509a0aba4e2c096f53d7880062a66b82a0baf84")
     version("1.16.2", sha256="bdc7554b56b9e0a380fc9c7b4f4394b41be863344858bc633bc9c25835c4c64e")
     version("1.16.1", sha256="93dc7a3ec40401988729ddb2c6ea2294911261f7e6cd979cf061b5c3691d729d")
```

2024-10-23 15:20 UTC, Thomas-Ulrich commented
Thank you! The updated package is also fine from my side.

2024-10-24 12:36 UTC, merged