Clingo: patch clingo to allow for build with modern msvc
LLNL/spack pull request #41188
Opened 2023-11-20 21:28 UTC by johnwparent

MSVC 19.38.* removes `native_handle` from the standard API, patch clingo to avoid the use of this

PR into Clingo

2023-11-20 21:29 UTC, johnwparent commented
@alalazo Actual solution for MSC 19.38.***** clingo bootstrap issue

2023-11-20 21:49 UTC, alalazo commented on var/spack/repos/builtin/packages/clingo/package.py
> +    patch("clingo_msc_1938_native_handle.patch", when="msvc@19.38:")
```suggestion
    patch("clingo_msc_1938_native_handle.patch", when="%msvc@19.38:")
```

2023-11-23 07:36 UTC, haampie commented
Upstream is using https://github.com/potassco/clasp/commit/c84b07de81cc24e9ac411fc404c54a9a5120029c can you modify the patch accordingly?

2023-11-23 07:36 UTC, haampie requested changes
Change of patch

2023-12-13 18:58 UTC, haampie commented on var/spack/repos/builtin/packages/clingo/clingo_msc_1938_native_handle.patch
> ++++ b/clasp/clasp/mt/mutex.h
```suggestion
From c84b07de81cc24e9ac411fc404c54a9a5120029c Mon Sep 17 00:00:00 2001
From: Benjamin Kaufmann <benjamin.kaufmann@teufel.de>
Date: Wed, 22 Nov 2023 08:13:46 +0100
Subject: [PATCH] mt: Make condition_variable::native_handle() conditional.

* According to the C++ standard, the presence and semantics of
  std::condition_variable::native_handle (and native_handle_type) is
  implementation-defined. E.g., starting with VS 2022 17.8, Microsoft's
  implementation no longer provides them at all.
---
 clasp/mt/mutex.h | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/clasp/mt/mutex.h b/clasp/mt/mutex.h
index 2439888..ade899c 100644
--- a/clasp/mt/mutex.h
+++ b/clasp/mt/mutex.h
```

lets keep a reference?

2023-12-13 18:59 UTC, haampie approved these changes, later dismissed
nitpick above, but feel free to merge

2023-12-13 19:01 UTC, haampie commented on var/spack/repos/builtin/packages/clingo/clingo_msc_1938_native_handle.patch
> +Submodule clasp contains modified content
```suggestion
From c84b07de81cc24e9ac411fc404c54a9a5120029c Mon Sep 17 00:00:00 2001
From: Benjamin Kaufmann <benjamin.kaufmann@teufel.de>
Date: Wed, 22 Nov 2023 08:13:46 +0100
Subject: [PATCH] mt: Make condition_variable::native_handle() conditional.

* According to the C++ standard, the presence and semantics of
  std::condition_variable::native_handle (and native_handle_type) is
  implementation-defined. E.g., starting with VS 2022 17.8, Microsoft's
  implementation no longer provides them at all.
---
 clasp/mt/mutex.h | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

```

2023-12-13 19:01 UTC, haampie approved these changes

2023-12-15 17:18 UTC, kwryankrattiger commented
@spackbot run pipeline

2023-12-15 17:21 UTC, kwryankrattiger commented
Trying again, seems like a spurious failure. If that doesn't work we can probably force merge this...

2023-12-15 17:43 UTC, merged

2023-12-15 17:53 UTC, johnwparent commented
Thanks all!