Update py-cylc-flow (add version 8.2.3)
LLNL/spack pull request #41209
Opened 2023-11-21 21:42 UTC by climbfuji

## Description

I was adding the entire dependency tree for `cylc-flow` based on my slightly older version of spack, and when I cherry-picked the commits for spack develop I realized that @LydDeb recently went through the same exercise! Good news is that the packages we both added look more or less the same, so this PR only adds the latest version of `cylc-flow`, and adds the missing dependency on `graphviz` for visualizing the graphs (that's the first part of the `cylc-flow` tutorial, therefore it would make sense to me to add that as a dependency).

I built this locally on my macOS with apple-clang@3.1.6 and created/displayed a graph following the tutorial.

@LydDeb Let me know if you would like me to double up as maintainer for (some of) the packages. Thanks for adding this in the first place!

2023-11-23 14:00 UTC, LydDeb approved these changes

2023-11-23 14:06 UTC, LydDeb commented
I missed graphviz. Thanks for adding it @climbfuji  !
Of course, I would appreciate it if you help me maintain this recipe.

2023-11-25 15:32 UTC, adamjstewart requested changes

2023-11-25 15:32 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cylc-flow/package.py
metomi-isodatetime dep needs to be updated

2023-11-27 14:51 UTC, climbfuji commented on var/spack/repos/builtin/packages/py-cylc-flow/package.py
Indeed, I had
```
    depends_on("py-metomi-isodatetime@3:3.1", type=("build", "run"))
```
in my version of the package first. Is that what you were thinking of? I find the `!` syntax in the dependencies (https://github.com/cylc/cylc-flow/blob/ddeaa97c41af2cd26da2924f5d16b26e240d6876/setup.cfg#L71C5-L71C41) confusing.

EDIT: I believe what I have is correct. The epoch syntax refers to the package changing its versioning from YYYY.x.y (epoch 0) to x.y.z (epoch 1) ... https://github.com/metomi/isodatetime/tags

2023-11-27 23:22 UTC, climbfuji commented on var/spack/repos/builtin/packages/py-cylc-flow/package.py
Done, see https://github.com/spack/spack/pull/41209/commits/bb76db11c5558ccabf5124c15ac5c6d797287925 please.

2023-12-01 13:33 UTC, adamjstewart approved these changes

2023-12-01 13:33 UTC, merged