parser: don't use private python api
LLNL/spack pull request #41245
Opened 2023-11-24 09:25 UTC by haampie

and fix mypy issues

2023-11-24 10:32 UTC, alalazo requested changes
I get this profiling for a parsing benchmark:
![Screenshot from 2023-11-24 11-27-51](https://github.com/spack/spack/assets/4199709/bf172c5f-ea0a-49fb-ac32-6714b8dfb1d7)

which shows a ~10% slowdown. Can you reproduce that?

Also, the reduction in the number of lines is mostly due to being eager on error reporting, and underlying only the first error in the string being parsed:

![Screenshot from 2023-11-24 11-31-51](https://github.com/spack/spack/assets/4199709/fc583cea-b06f-46cd-a707-858635269411)

This doesn't seem related to the use of a private API.

2023-11-24 10:40 UTC, alalazo commented
On the private API, it's absolutely true that `scanner` is undocumented. On the other hand it has also being stable for the last 20+ years. There are multiple references mentioning the use of that API, for instance:
- O' Really "Python Cookbook" Chapter 2.18 "Tokenizing text"
- This [blog post](https://lucumr.pocoo.org/2015/11/18/pythons-hidden-re-gems/) from Armin Ronacher

This doesn't change the fact that `scanner` is not documented, but should give us some confidence that is not going away soon. If it is, and if using the public API causes the slow down above, we can always move to `finditer` when `scanner` changes or gets removed.

2023-11-24 10:51 UTC, alalazo commented
To just fix the mypy complaints with new versions of `mypy` I think this is all we need:
```diff
diff --git a/lib/spack/spack/parser.py b/lib/spack/spack/parser.py
index c69918b419..f37c17769a 100644
--- a/lib/spack/spack/parser.py
+++ b/lib/spack/spack/parser.py
@@ -206,11 +206,13 @@ def tokenize(text: str) -> Iterator[Token]:
     scanner = ALL_TOKENS.scanner(text)  # type: ignore[attr-defined]
     match: Optional[Match] = None
     for match in iter(scanner.match, None):
+        # The following two assertions are to help mypy
+        msg = ("unexpected value encountered during parsing. Please submit a bug report "
+               "at https://github.com/spack/spack/issues/new/choose")
+        assert match is not None, msg
+        assert match.lastgroup is not None, msg
         yield Token(
-            TokenType.__members__[match.lastgroup],  # type: ignore[attr-defined]
-            match.group(),  # type: ignore[attr-defined]
-            match.start(),  # type: ignore[attr-defined]
-            match.end(),  # type: ignore[attr-defined]
+            TokenType.__members__[match.lastgroup], match.group(), match.start(), match.end()
         )
 
     if match is None and not text:
```
It seems `mypy` cannot see through `iter(callable, None)` and thus doesn't understand that `Optional[Match]` cannot be `None` within the loop. Likewise for `lastgroup`, since `None` shouldn't be a valid value due to how we construct the regex.

2023-11-29 17:14 UTC, greenc-FNAL commented
Closes https://github.com/FNALssi/spack/pull/238

2025-12-17 08:29 UTC, closed without merging