add Packages `py-vl-convert-python` `py-cairosvg` `py-cssselect2`; update `py-altair`
LLNL/spack pull request #41250
Opened 2023-11-24 14:01 UTC by wu-kan

add Packages `py-vl-convert-python` `py-cairosvg` `py-cssselect2`; update `py-altair`

2023-11-25 16:05 UTC, adamjstewart requested changes
These packages seem to be independent of each other. In that case, each package should be in a separate PR: https://spack.readthedocs.io/en/latest/contribution_guide.html

2023-11-25 16:05 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-altair/package.py
> +            url="https://files.pythonhosted.org/packages/17/16/b12fca347ff9d062e3c44ad9641d2ec50364570a059f3078ada3a5119d7a/altair-5.1.2-py3-none-any.whl", expand=False)
We prefer to use sdists (tar.gz) over bdists (whl)

2023-11-25 16:05 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-altair/package.py
>      depends_on("python@3.7:", type=("build", "run"))
Deps need to be updated:
```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "altair"
authors = [{ name = "Vega-Altair Contributors" }]
dependencies = [
    "typing_extensions>=4.0.1; python_version<\"3.11\"",
    "jinja2",
    # If you update the minimum required jsonschema version, also update it in build.yml
    "jsonschema>=3.0",
    "numpy",
    # If you update the minimum required pandas version, also update it in build.yml
    "pandas>=0.25",
    "toolz",
    "packaging"
]
```

2023-11-25 16:05 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cairosvg/package.py
> +    depends_on("py-setuptools@40.6:", type="build")
Where does 40.6+ come from?

2023-11-25 16:05 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cairosvg/package.py
> +    depends_on("py-entrypoints", type=("build", "run"))
Where does entrypoints come from?

2023-11-25 16:05 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cairosvg/package.py
> +    depends_on("py-pillow", type=("build", "run"))
```suggestion
    depends_on("pil", type=("build", "run"))
```
We have a virtual dep for this

2023-11-25 16:05 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cssselect2/package.py
> +            url="https://files.pythonhosted.org/packages/9d/3a/e39436efe51894243ff145a37c4f9a030839b97779ebcc4f13b3ba21c54e/cssselect2-0.7.0-py3-none-any.whl", expand=False)
Should be using sdist, not bdist

2023-11-25 16:05 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cssselect2/package.py
> +            url="https://files.pythonhosted.org/packages/9d/3a/e39436efe51894243ff145a37c4f9a030839b97779ebcc4f13b3ba21c54e/cssselect2-0.7.0-py3-none-any.whl", expand=False)
Will need flit_core once you change this

2023-11-25 16:05 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-vl-convert-python/package.py
> +    depends_on("py-maturin", type=("build"))
```suggestion
    depends_on("py-maturin@1.1:1", type="build")
```

2023-11-26 06:35 UTC, wu-kan commented
> These packages seem to be independent of each other. In that case, each package should be in a separate PR: https://spack.readthedocs.io/en/latest/contribution_guide.html

OK, I will create PR for each packagpe

2023-11-26 06:35 UTC, closed without merging