py-pyomo: Update spec for newest major series
LLNL/spack pull request #41271
Opened 2023-11-27 16:31 UTC by mrmundt

A Pyomo user requested that the `py-pyomo` spec be updated for the newest major series. This requires two more small specs to be added (`py-enum34` and `py-numdifftools`).

2023-11-30 23:58 UTC, tldahlgren requested changes
Confirmed the homepages and version sha256 for the two new packages and the new homepage for `py-pyomo`.  Cannot confirmed the sha256 for 6.4.1 (I get a636a3a1c8314b8be85899cb6fac5d6a9a78fc75c6d58b74d3ec106ae5ed8f59) or 5.7.0 (`Error: Could not find any remote versions for py-pyomo`).

Please switch the latter to `https` protocol since that works and is preferred.

2023-12-01 13:58 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-enum34/package.py
enum34 is only needed for Python 3.3 and older, and we don't support that in Spack, so you can remove this.

2023-12-01 13:58 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyomo/package.py
> +    version("5.6.6", sha256="813e14a604b9d3ac63bdd0880c07f5f4e1b8f0a8a10345f1b42bee762219c001")
Do you really want to add every version or just the latest version? You can maintain all of these versions if you want to, but I'll only review the latest version to make sure that's correct.

2023-12-01 14:04 UTC, mrmundt commented on var/spack/repos/builtin/packages/py-enum34/package.py
Some of the versions in this spec are for Python 2.7:2.8. Can folks not install those using Spack?

2023-12-01 14:06 UTC, mrmundt commented on var/spack/repos/builtin/packages/py-pyomo/package.py
> +    version("5.6.6", sha256="813e14a604b9d3ac63bdd0880c07f5f4e1b8f0a8a10345f1b42bee762219c001")
Someone else originally added this spec (many years ago), and they added it for version 5.6.6. I don't know who that was or why, but one of our core principles at Pyomo is to maintain backwards compatibility. We don't want to break that person's usage of Spack to install Pyomo.

2023-12-01 14:29 UTC, mrmundt commented
> Confirmed the homepages and version sha256 for the two new packages and the new homepage for `py-pyomo`. Cannot confirmed the sha256 for 6.4.1 (I get a636a3a1c8314b8be85899cb6fac5d6a9a78fc75c6d58b74d3ec106ae5ed8f59) or 5.7.0 (`Error: Could not find any remote versions for py-pyomo`).
> 
> Please switch the latter to `https` protocol since that works and is preferred.

Those were whoopsies. Fixed.

2023-12-01 15:12 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-enum34/package.py
Not in the latest Spack release. If you go back a few releases, we used to support Python 2. Currently we only support Python 3.8+, same as https://devguide.python.org/versions/.

2023-12-01 15:32 UTC, mrmundt commented on var/spack/repos/builtin/packages/py-enum34/package.py
Alright, removed!

2023-12-06 14:39 UTC, adamjstewart requested changes

2023-12-06 14:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-numdifftools/package.py
> +    depends_on("py-setuptools", type="build")
```suggestion
    depends_on("py-setuptools@39.2:", type="build")
```

2023-12-06 14:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyomo/package.py
> +    def global_options(self, spec, prefix):
Note that `--global-option` was deprecated in pip 23.1 and may be removed someday. Nothing to change here, just a warning that we may need to prevent using newer pip versions someday.

2023-12-06 14:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyomo/package.py
> +    variant("cython", default=False, description="Enable cythonization of Pyomo.")
Is there any reason we shouldn't always do this? Not sure if we really need a variant

2023-12-06 14:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyomo/package.py
> +    variant("optional", default=False, description="Install optional dependencies. (Version 6.1+)")
```suggestion
    variant("tests", default=False, description="Install testing dependencies", when="@6.1:")
    variant(
        "docs", default=False, description="Install docs generation dependencies", when="@6.1:"
    )
    variant("optional", default=False, description="Install optional dependencies", when="@6.1:")
```

2023-12-06 14:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyomo/package.py
> +    depends_on("python@2.7:2.8,3.4:3.8", when="@5.6", type=("build", "run"))
Do you know for a fact that newer versions of Python won't work, or are they just not tested? `classifiers` just tells what was tested, not what actually works. I usually only use a lower bound unless I know something will break.

2023-12-06 14:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyomo/package.py
> +    depends_on("py-sphinx@2:", when="@6.1:+docs", type=("run"))
It's 5+ in the latest release

2023-12-06 14:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyomo/package.py
> +    depends_on("py-sphinx-rtd-theme@0.5:", when="@6.1:+docs", type=("run"))
It's 0.6+ in the latest version

2023-12-06 14:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyomo/package.py
> +    depends_on("py-matplotlib@3.6.2:", when="@6.1:+optional", type=("run"))
```suggestion
    depends_on("py-matplotlib@:3.6.0,3.6.2:", when="@6.1:+optional", type=("run"))
```
Or:
```python
depends_on("py-matplotlib", ...)
conflicts("^py-matplotlib@3.6.1")
```

2023-12-06 14:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyomo/package.py
> +    depends_on("py-plotly", when="@6.6:+optional", type=("run"))
Missing z3-solver, pywin32, casadi. Can you sort these in the same order as setup.py? Makes it easier to review.

2023-12-06 14:55 UTC, mrmundt commented on var/spack/repos/builtin/packages/py-pyomo/package.py
> +    variant("cython", default=False, description="Enable cythonization of Pyomo.")
We offer the variation when installing Pyomo (it's a custom build option), so this is to preserve that ability.

2023-12-06 14:56 UTC, mrmundt commented on var/spack/repos/builtin/packages/py-pyomo/package.py
> +    depends_on("python@2.7:2.8,3.4:3.8", when="@5.6", type=("build", "run"))
It's when official support for those versions was dropped within Pyomo. Frequently that also means introducing breaking changes (e.g., deleting "bandaid" code that made it work with that version).

2023-12-06 14:59 UTC, mrmundt commented on var/spack/repos/builtin/packages/py-pyomo/package.py
> +    def global_options(self, spec, prefix):
Yup, it's on our list of things to eventually address.

2023-12-06 15:30 UTC, mrmundt commented
@adamjstewart - Changes addressed!

2023-12-06 15:39 UTC, adamjstewart requested changes

2023-12-06 15:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/casadi/package.py
> +# ----------------------------------------------------------------------------
Can remove the stuff between `# ----`

2023-12-06 15:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/casadi/package.py
> +class Casadi(CMakePackage):
Any thoughts on whether this should build using CMake or pip? I would lean towards the latter since we're downloading from PyPI.

2023-12-06 15:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pywin32/package.py
> +    license("UNKNOWN")
Looks like PSF-2.0 according to the README

2023-12-06 15:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-z3-solver/package.py
> +    depends_on("py-setuptools", type="build")
```suggestion
    depends_on("py-setuptools@46.4:", type="build")
```
Missing dep on cmake

2023-12-06 15:39 UTC, adamjstewart commented
Most changes weren't addressed, did you forget to push the commit?

2023-12-06 16:08 UTC, mrmundt commented
@adamjstewart - Maybe now? I think I fixed all the issues.

2023-12-11 19:17 UTC, tldahlgren submitted a review, later dismissed
Confirmed the homepages that start with the protocol and all (new) version sha256s.

2023-12-11 19:19 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-pyomo/package.py
> +    homepage = "http://www.pyomo.org/"
Any chance of getting this switch to `https`?

2023-12-11 19:21 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-casadi/package.py
> +    homepage = "casadi.org"
Any chance of getting this switch to `https://web.casidi.org`?

2023-12-17 06:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-casadi/package.py
> +    depends_on("py-numpy", type="run")
I usually do `type=("build", "run")` so that `spack install --test=root` works.

2023-12-18 15:14 UTC, mrmundt commented
@tldahlgren , @adamjstewart - changes addressed. Sorry for the delay - last week was a disaster over here.

2023-12-23 20:41 UTC, adamjstewart approved these changes

2023-12-23 20:41 UTC, merged