Adding JUBE 2.6.0
LLNL/spack pull request #41272
Opened 2023-11-27 17:02 UTC by fspiga

Adding JUBE 2.6.0.

ChangeLog: https://apps.fz-juelich.de/jsc/jube/jube2/docu/release_notes.html#version-2-6-0

2023-11-30 23:50 UTC, tldahlgren requested changes
I am able to confirm version 2.6.0 sha256 but get a different value from `spack checksum` for version 2.6.1 (348ebeb4db0ea56889a5d13bf49e394fccc0992f620e8c0c61c40185db13ad64).

2023-12-01 13:55 UTC, adamjstewart submitted a review, later dismissed
Other than the checksum, the rest looks good

2024-03-13 22:12 UTC, RMeli commented on var/spack/repos/builtin/packages/jube/package.py
> +        sha256="32846616b01450e7ab678a1b3a7b34bcbb2311591a095d2b27e6d3a39110c07c",
```suggestion
        sha256="348ebeb4db0ea56889a5d13bf49e394fccc0992f620e8c0c61c40185db13ad64",
```

2024-04-11 21:18 UTC, tldahlgren approved these changes
Can now confirm both sha256s after adding the suggested fix through the web interface.

2024-04-11 22:01 UTC, merged