py-poetry: Add version 1.6.1
LLNL/spack pull request #41291
Opened 2023-11-28 10:13 UTC by LydDeb

Update py-poetry: add version 1.6.1.

Update  dependences:
* py-poetry-core
* py-dulwich
* py-installer
* py-keyring
* py-poetry-plugin-export
* py-cachecontrol

2023-11-30 10:36 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-cachecontrol/package.py
> +    depends_on("py-redis@2.10.5:", when="@0.13+redis", type="run")
```suggestion
    depends_on("py-redis@2.10.5:", when="+redis", type=("build", "run"))
```

2023-11-30 10:36 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-cachecontrol/package.py
> +    depends_on("py-filelock@3.8.0:", when="@0.13+filecache", type="run")
```suggestion
    depends_on("py-lockfile@0.9:", when="@0.12+filecache", type=("build", "run"))
    depends_on("py-filelock@3.8.0:", when="@0.13+filecache", type=("build", "run"))
```

2023-11-30 10:36 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-cachecontrol/package.py
> +    version("0.13.0", sha256="fd3fd2cb0ca66b9a6c1d56cc9709e7e49c63dbd19b1b1bcbd8d3f94cedfe8ce5")
There is also a newer patch version available (0.13.1) in case you want to add those instead.

2023-11-30 10:36 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-dulwich/package.py
>      depends_on("python@3.6.0:", when="@0.20.44:", type=("build", "run"))
Either remove these two python restrictions completely or add `python@3.7.0:` starting from version 0.21.4.1

2023-11-30 10:36 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-cachecontrol/package.py
> +    depends_on("py-requests@2.16.0:", when="@0.13", type=("build", "run"))
general remark:
It would be nice if you could sort the dependencies from newer to older/general like it is for `version` of the package.

2023-11-30 10:36 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-dulwich/package.py
>      depends_on("py-urllib3@1.25:", when="@0.20.46:", type=("build", "run"))
There is an ongoing discussion at the moment if python 3.7 should be supported or not, if you want to be on the safe side you can add `'typing_extensions` for `python_version<="3.7"'`

2023-11-30 10:36 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-poetry-core/package.py
>      depends_on("python@3.7:3", when="@1.1.0:", type=("build", "run"))
```suggestion
    depends_on("python@3.8:3", when="@1.7.0:", type=("build", "run"))
    depends_on("python@3.7:3", when="@1.1.0:", type=("build", "run"))
```

2023-11-30 10:36 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-poetry-plugin-export/package.py
> +    depends_on("python@3.8:3", when="@1.6", type=("build", "run"))
```suggestion
    depends_on("python@3.8:3", when="@1.6:", type=("build", "run"))
```
Also can you switch the order with the line above to have dependencies for newer versions first (for an example what I mean, see `py-poetry-core` dependency)?

2023-11-30 10:36 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-poetry-plugin-export/package.py
> +    depends_on("py-poetry-core@1.7:1", when="@1.6", type=("build", "run"))
Can you order the dependencies for newer versions first as we do for the version of the package?
```suggestion
    depends_on("py-poetry-core@1.7:1", when="@1.6", type=("build", "run"))
    depends_on("py-poetry-core@1.1:1", when="@1.0", type=("build", "run"))
```

2023-11-30 10:36 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-poetry/package.py
>      depends_on("python@3.7:3", when="@1.2.0:", type=("build", "run"))
depends_on("python@3.8:3", when="@1.6.0:", type=("build", "run"))

2023-11-30 10:36 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +    depends_on("py-cleo@2.0.0:2", when="@1.6.1", type=("build", "run"))
Can be simplified:
```suggestion
    depends_on("py-cleo@2", when="@1.6.1", type=("build", "run"))
```

2023-11-30 10:36 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +    depends_on("py-crashtest@0.4.1:0", when="@1.6.1", type=("build", "run"))
```suggestion
    depends_on("py-crashtest@0.4.1:0.4", when="@1.6.1", type=("build", "run"))
```
for poetry versions `0.x.y` have different rules as`1.v.w` see https://python-poetry.org/docs/dependency-specification/#caret-requirements

2023-11-30 10:36 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +    depends_on("py-crashtest@0.3.0:0.3", when="@:1.2", type=("build", "run"))
```suggestion
    depends_on("py-crashtest@0.3", when="@:1.2", type=("build", "run"))
```

2023-11-30 10:36 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +    depends_on("py-dulwich@0.21.2:0", when="@1.6.1", type=("build", "run"))
```suggestion
    depends_on("py-dulwich@0.21.2:0.21", when="@1.6.1", type=("build", "run"))
```

2023-11-30 10:36 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +    depends_on("py-installer@0.7.0:0", when="@1.6.1", type=("build", "run"))
```suggestion
    depends_on("py-installer@0.7.0:0.7", when="@1.6.1", type=("build", "run"))
```

2023-11-30 10:36 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-poetry/package.py
>      depends_on("py-requests-toolbelt@0.9.1:0.9", type=("build", "run"))
```suggestion
    depends_on("py-requests-toolbelt@0.9.1:0.9", when="@:1.2", type=("build", "run"))
```

2023-11-30 10:36 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +    depends_on("py-xattr@0.10.0:0", when="platform=darwin @1.6.1", type=("build", "run"))
```suggestion
    depends_on("py-xattr@0.10", when="platform=darwin @1.6.1", type=("build", "run"))
```

2023-11-30 10:36 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +    depends_on("py-trove-classifiers@2022.5.19:", when="@1.6.1", type=("build", "run"))
If you sort the dependencies in the same order as listed in `pyproject.toml` it makes reviewing much easier.

This is also true if you sort newer versions of a dependency before older.

2023-11-30 10:36 UTC, manuelakuhn commented on var/spack/repos/builtin/packages/py-poetry-plugin-export/package.py
> +        return url.format(letter, version)
Missing dependency: `poetry = "^1.6.0"`

2023-12-06 12:41 UTC, LydDeb commented
Thank you for the review @manuelakuhn

2023-12-06 15:30 UTC, adamjstewart requested changes

2023-12-06 15:30 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry-plugin-export/package.py
> -    # depends_on("py-poetry@1.2:1", type="run") # circular dependency
Isn't this circular dependency still an issue?

2023-12-06 15:30 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry/package.py
> +    depends_on("py-build@0.10.0:0", when="@1.6.1", type=("build", "run"))
```suggestion
    depends_on("py-build@0.10", when="@1.6.1", type=("build", "run"))
```
See https://python-poetry.org/docs/dependency-specification/#caret-requirements

2023-12-06 15:31 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-poetry-plugin-export/package.py
> -    # depends_on("py-poetry@1.2:1", type="run") # circular dependency
@alalazo poetry has a run-dep on poetry-plugin-export, and poetry-plugin-export has a run-dep on poetry. Would love to be able to model this correctly in the concretizer someday.

2023-12-17 05:58 UTC, adamjstewart approved these changes

2023-12-17 05:58 UTC, merged