py-sphinx-toolbox: new package
LLNL/spack pull request #41313
Opened 2023-11-29 09:17 UTC by LydDeb

Depends on PRs 
* [#41309](https://github.com/spack/spack/pull/41309)
* [#41310](https://github.com/spack/spack/pull/41310)
* [#41311](https://github.com/spack/spack/pull/41311)

2023-11-30 23:36 UTC, tldahlgren reviewed
FYI. Confirmed the homepage and version sha256.

2023-12-01 13:46 UTC, adamjstewart requested changes

2023-12-01 13:46 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-sphinx-toolbox/package.py
> +    depends_on("py-typing-inspect@0.6.0:", type=("build", "run"), when="python@:3.7")
```suggestion
    depends_on("py-typing-inspect@0.6.0:", type=("build", "run"), when="^python@:3.7")
```

2023-12-06 15:09 UTC, adamjstewart approved these changes

2024-01-16 19:52 UTC, tldahlgren approved these changes

2024-01-16 19:53 UTC, merged