py-python-pptx: new package
LLNL/spack pull request #41315
Opened 2023-11-29 09:31 UTC by LydDeb

2023-11-30 23:35 UTC, tldahlgren reviewed
FYI. Confirmed the homepage and 2 version sha256.

2023-12-01 10:20 UTC, manuelakuhn submitted a review, later dismissed

2023-12-01 14:04 UTC, adamjstewart requested changes

2023-12-01 14:04 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-python-pptx/package.py
> +    depends_on("py-pillow@3.3.2:", type=("build", "run"))
```suggestion
    depends_on("pil@3.3.2:", type=("build", "run"))
```
We have a virtual dep for this

2023-12-01 14:04 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-python-pptx/package.py
> +    depends_on("python@2:2.7,3.6:", type=("build", "run"))
Could just remove this line, Spack only supports Python 3.8+ anyway

2023-12-06 14:43 UTC, adamjstewart approved these changes

2023-12-06 14:43 UTC, merged