py-tldextract: new package
LLNL/spack pull request #41330
Opened 2023-11-29 14:48 UTC by LydDeb

2023-11-29 14:56 UTC, LydDeb commented
Depends on [py-requests-file](https://github.com/spack/spack/pull/41331)

2023-11-30 20:58 UTC, tldahlgren reviewed
FYI. Confirmed homepage and version sha256.

2023-12-01 08:38 UTC, manuelakuhn approved these changes, later dismissed
There is also a much newer version (5.1.1) available on Pypi in case you want to add this as well.

2023-12-01 14:59 UTC, adamjstewart requested changes

2023-12-01 14:59 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-tldextract/package.py
> +    depends_on("py-setuptools-scm@6.2+toml", when="@5.1.1", type="build")
```suggestion
    depends_on("py-setuptools-scm@6.2:+toml", when="@5.1.1", type="build")
```

2023-12-06 14:42 UTC, adamjstewart approved these changes

2023-12-06 14:42 UTC, merged