py-keras: add v3.0.0
LLNL/spack pull request #41356
Opened 2023-11-30 12:34 UTC by adamjstewart

Keras 3.0 represents a big step forward for installing Keras:

* Supports TF, JAX, and Torch backends
* No longer requires Bazel or Git to build
* All dependencies are properly documented

https://keras.io/keras_3/

2023-11-30 20:07 UTC, tldahlgren requested changes
I confirmed the py-namex sha256 and py-keras@3.0.0 but am getting different values for 2.14.0 and 2.13.1 and no sha256 for earlier py-keras versions (`Error: Could not find any remote versions for py-keras`).

2023-11-30 20:36 UTC, adamjstewart commented
@tldahlgren can you try again now?

2023-11-30 20:42 UTC, tldahlgren commented
> @tldahlgren can you try again now?

I can now confirm the sha256 for versions 2.6.0 through 3.0.0 but am getting nothing for 2.2.0 through 2.4.3.

2023-11-30 21:07 UTC, adamjstewart commented
Okay, should be right this time.

2023-11-30 21:16 UTC, tldahlgren submitted a review, later dismissed
Confirmed all py-keras sha256 are now correct.

2023-11-30 21:19 UTC, adamjstewart commented
Just needs #41362 for CI to pass.

2023-12-01 11:48 UTC, manuelakuhn reviewed
`pil` and `py-pydot` are still needed for `@:2`

2023-12-01 11:59 UTC, adamjstewart commented
Doesn't seem like they're required and they provide limited functionality, but I'm fine with adding them to older versions.

2023-12-01 12:12 UTC, manuelakuhn approved these changes
I think this is fine, unfortunately I cannot test anything because `py-dm-tree` does not build with `gcc@13`

2023-12-01 18:23 UTC, merged