root: sha256 change on latest version
LLNL/spack pull request #41401
Opened 2023-12-03 16:29 UTC by wdconinc

The ROOT 6.30.02 version sha256 added in https://github.com/spack/spack/pull/41289 appears incorrect or changed.

```console
$ curl -L https://root.cern/download/root_v6.30.02.source.tar.gz | sha256sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  176M  100  176M    0     0  7529k      0  0:00:23  0:00:23 --:--:-- 11.5M
7965a456d1ad1ee0d5fe4769bf5a8fec291af684ed93db0f3080a9c362435183  -
```

2023-12-03 16:42 UTC, wdconinc commented
@jmcarcell Can you comment on how you determined those sha256 checksums? It seems strange that you would find different sha256 checksums, so I'm wondering if you are looking at different files. Also, of course, please confirm the ones I'm getting so it's not a problem on my end.

2023-12-03 17:10 UTC, wdconinc commented
I think I see what's going on. Could it be that you're using the github tag archives?
```console
$ curl -L https://github.com/root-project/root/archive/refs/tags/v6-30-02.tar.gz | sha256sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  176M    0  176M    0     0  8352k      0 --:--:--  0:00:21 --:--:-- 6404k
51a09c86ffa94089abac76daa3adc20812efc6c93b427697b843b12d73e145de  -
```

Those github archives are not the ones used by spack. If a project has other archives they are usually preferred because automatic github archives can change (e.g. https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/, reverted for now after widespread uproar, but the link says all).

Also, version 6.26.12 is not even on the ROOT server, so that will result in a failed download. I'll remove that version again, and instead add 6.26.14, which is on the ROOT server (https://github.com/root-project/root/compare/v6-26-12...v6-26-14, just formatting diffs).

2023-12-03 19:39 UTC, jmcarcell approved these changes

2023-12-05 00:33 UTC, tldahlgren requested changes
Issue with only one of the version sha256s.

2023-12-05 00:33 UTC, tldahlgren commented on var/spack/repos/builtin/packages/root/package.py
> +    version("6.26.14", sha256="3b891ea23216234b90bf62397b036e9982607b687475f80d378e2f4bcb54a197")
I am getting "81045a35a1958906c3eadecd9b01127a6087dadc19385af8e92ae5c84f06ce35" for this version (from 'spack checksum').

2023-12-05 00:33 UTC, tldahlgren commented on var/spack/repos/builtin/packages/root/package.py
> +    version("6.26.14", sha256="3b891ea23216234b90bf62397b036e9982607b687475f80d378e2f4bcb54a197")
This is the only version in the package that I cannot confirm.

2023-12-05 00:42 UTC, wdconinc commented on var/spack/repos/builtin/packages/root/package.py
> +    version("6.26.14", sha256="3b891ea23216234b90bf62397b036e9982607b687475f80d378e2f4bcb54a197")
Yeah, not sure why I ended up with the wrong hash (how can hashes be so hard??). I'm now also getting:
```suggestion
    version("6.26.14", sha256="81045a35a1958906c3eadecd9b01127a6087dadc19385af8e92ae5c84f06ce35")
```

2023-12-06 02:20 UTC, tldahlgren approved these changes

2023-12-06 02:20 UTC, merged