dla-future: install bug fix
LLNL/spack pull request #41409
Opened 2023-12-04 09:25 UTC by yizeyi18

fixes #41408 . using std::int64_t needs include cstdint in gcc-13.

2023-12-05 15:01 UTC, msimberg commented on var/spack/repos/builtin/packages/dla-future/package.py
> +    patch("stdint.patch", when="@0.3.1 %gcc@13")
Thanks for taking care of this. Would you mind updating this to
```suggestion
    patch(
        "https://github.com/eth-cscs/DLA-Future/pull/1063/commits/efc9c176a7a8c512b3f37d079dec8c25ac1b7389.patch?full_index=1",
        sha256="7f382c872d89f22da1ad499e85ffe9881cc7404c8465e42877a210a09382e2ea",
        when="@:0.3 %gcc@13:",
    )
```
The patch applies for all versions up to and including 0.3.1 and is required with gcc 13 and newer. The patch comes from https://github.com/eth-cscs/DLA-Future/pull/1063 which is the upstream fix for the same problem.

2023-12-05 22:29 UTC, haampie commented on var/spack/repos/builtin/packages/dla-future/package.py
> +    patch("stdint.patch", when="@0.3.1 %gcc@13")
maybe use https://github.com/eth-cscs/DLA-Future/commit/1f7993860ed4e6d0342c7ecef40c343f28a87049 directly instead of the PR?

2023-12-06 08:29 UTC, alalazo requested changes

2023-12-06 08:29 UTC, alalazo commented on var/spack/repos/builtin/packages/dla-future/package.py
> +        "https://github.com/eth-cscs/DLA-Future/pull/1063/commits/efc9c176a7a8c512b3f37d079dec8c25ac1b7389.patch?full_index=1",
Why are we adding a URL for the patch, _and_ committed a patch to the repo that seems unused?

2023-12-06 09:33 UTC, yizeyi18 commented on var/spack/repos/builtin/packages/dla-future/package.py
> +        "https://github.com/eth-cscs/DLA-Future/pull/1063/commits/efc9c176a7a8c512b3f37d079dec8c25ac1b7389.patch?full_index=1",
First I tried to add the patch "unused" now, and msimberg suggested to use the patch from DLAF commit. Leaving the unused patch undeleted is my fault, I apologize fot it.

2023-12-06 15:38 UTC, alalazo commented on var/spack/repos/builtin/packages/dla-future/package.py
> +        "https://github.com/eth-cscs/DLA-Future/pull/1063/commits/efc9c176a7a8c512b3f37d079dec8c25ac1b7389.patch?full_index=1",
@yizeyi18 No worries, thanks for the PR.

2023-12-06 15:38 UTC, alalazo approved these changes

2023-12-06 15:55 UTC, merged