Update the Kakoune package to add the latest version
LLNL/spack pull request #41443
Opened 2023-12-06 02:38 UTC by taliaferro

Also added the compiler constraints for this version as [described in the README](https://github.com/mawww/kakoune#building).

2023-12-06 08:33 UTC, alalazo requested changes

2023-12-06 08:33 UTC, alalazo commented on var/spack/repos/builtin/packages/kakoune/package.py
> +    conflicts("%llvm@:11", when="@2023.08.05", msg="Clang version must be at least 11!")
Ranges include the upper bound:
```suggestion
    conflicts("%gcc@:10.2", when="@2023.08.05", msg="GCC version must be at least 10.3!")
    conflicts("%llvm@:10", when="@2023.08.05", msg="Clang version must be at least 11!")
```

2023-12-07 09:08 UTC, alalazo approved these changes

2023-12-07 09:09 UTC, alalazo commented
Ping me in a few days if there's no review from the maintainer.

2023-12-12 21:44 UTC, taliaferro commented
@alalazo -- I haven't heard back from the maintainer in a while; is there anything else you'd suggest here?

2023-12-12 22:02 UTC, merged

2023-12-12 22:02 UTC, alalazo commented
@taliaferro Nope, thanks for the PR!