damask: add version 3.0.0-alpha8
LLNL/spack pull request #41444
Opened 2023-12-06 05:34 UTC by MarDiehl

added support for newest version and tested locally

2023-12-06 15:07 UTC, adamjstewart requested changes
Only reviewed the Python bits.

2023-12-06 15:07 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-damask/package.py
>      )
Dependencies have specific versions required, at least in the latest version:
```
install_requires =
    pandas>=0.24                                                                                    # requires numpy
    numpy>=1.17                                                                                     # needed for default_rng
    scipy>=1.2
    h5py>=2.9                                                                                       # requires numpy
    vtk>=8.1
    matplotlib>=3.0                                                                                 # requires numpy, pillow
    pyyaml>=3.12
```

2023-12-06 15:18 UTC, MarDiehl commented on var/spack/repos/builtin/packages/py-damask/package.py
>      )
@adamjstewart: thanks!

2023-12-06 15:33 UTC, adamjstewart approved these changes
Python bits LGTM, will let someone else review the rest.

2023-12-22 20:26 UTC, naromero77 approved these changes
LGTM

2023-12-22 20:26 UTC, merged