New command list-scopes [--file] [--non-platform]
LLNL/spack pull request #41455
Opened 2023-12-06 14:23 UTC by greenc-FNAL

2025-03-24 20:04 UTC, greenc-FNAL commented
@tldahlgren I have (I believe) brought this PR up to date in the light of #48784. I'd be grateful if you could help me get this merged, please.

2025-03-24 21:32 UTC, tldahlgren reviewed
LGTM. I have a couple of questions. One is about the mutual exclusion of the options. The other is have you confirmed the outputs in the description are up-to-date?

2025-03-24 21:32 UTC, tldahlgren commented on lib/spack/spack/cmd/config.py
> +    stype = list_scopes_parser.add_mutually_exclusive_group(required=False)
I know there aren't a lot of scopes by default, but why are these mutually exclusive?

2025-03-24 21:51 UTC, tldahlgren commented on lib/spack/spack/test/cmd/config.py
> +    assert "user" in output
This test fails for me if `SPACK_DISABLE_LOCAL_CONFIG` is `true` when I run the tests.

2025-03-24 21:58 UTC, greenc-FNAL commented
> LGTM. I have a couple of questions. One is about the mutual exclusion of the options. The other is have you confirmed the outputs in the description are up-to-date?

Looking into removing mutual exclusion, and I have updated the description.

2025-03-24 22:00 UTC, greenc-FNAL commented on lib/spack/spack/cmd/config.py
> +    stype = list_scopes_parser.add_mutually_exclusive_group(required=False)
I think because the way I was originally obtaining non-platform scopes, they were `--file` by construction.

2025-03-24 22:00 UTC, tldahlgren requested changes

2025-03-24 22:00 UTC, tldahlgren commented on lib/spack/spack/cmd/config.py
> +        "--file",
Please add support for `-f` as short-hand for this option.

2025-03-24 22:31 UTC, tldahlgren commented on lib/spack/spack/test/cmd/config.py
> +    assert "user" in output
You might be able to get some inspiration from https://github.com/spack/spack/blob/8ac826cca892f9060ced53a071e78e0119dd8aca/lib/spack/spack/test/config.py#L1230.

2025-03-24 23:31 UTC, tldahlgren commented on lib/spack/spack/test/cmd/config.py
> +    assert f"site/{spack.platforms.host()}" in output
You probably don't want to add this. The session-level fixture `_use_test_platform()` causes the left hand side to be `site/test`.

2025-03-24 23:31 UTC, tldahlgren commented on lib/spack/spack/test/cmd/config.py
> +    del os.environ["SPACK_DISABLE_LOCAL_CONFIG"]
This will fail on a key error.

2025-03-25 14:48 UTC, greenc-FNAL commented on lib/spack/spack/test/cmd/config.py
> +    del os.environ["SPACK_DISABLE_LOCAL_CONFIG"]
Argh, thanks.

2025-03-25 14:53 UTC, greenc-FNAL commented on lib/spack/spack/test/cmd/config.py
> +    assert f"site/{spack.platforms.host()}" in output
What do you mean by, "session-level?" Is that unconditionally invoked for all tests, or as part of an in-test-file directive, or in test configuration, or on the command line? I'm not currently seeing the invocation mechanism, sorry.

2025-03-25 16:57 UTC, tldahlgren commented on lib/spack/spack/test/cmd/config.py
> +    assert f"site/{spack.platforms.host()}" in output
They apply to all test functions run during the test "session" (https://docs.pytest.org/en/stable/explanation/fixtures.html).

2025-03-26 14:24 UTC, greenc-FNAL commented
@tldahlgren I think I've addressed your comments, but if you have any tips on how to test either the inclusion/exclusion of platform scopes, or `--included`, I'd appreciate it.

2025-05-21 22:58 UTC, tldahlgren commented on lib/spack/spack/cmd/config.py
> +    list_scopes_parser = sp.add_parser("list-scopes", help="list defined scopes")
Can  this be simplified to `scopes` so `spack config scopes`?

2025-05-22 13:24 UTC, greenc-FNAL commented
This will need to be adjusted when platform scopes go away with #50603.

2025-05-22 13:25 UTC, greenc-FNAL commented
Also @tldahlgren @tgamblin Any chance this can be in 1.0? I think this would complement #50603 nicely.

2025-05-22 14:32 UTC, tldahlgren commented
> Also @tldahlgren @tgamblin Any chance this can be in 1.0? I think this would complement #50603 nicely.

Yes. I didn't get a chance yesterday to look closely at the alternative for fixing the unit test. But I'm planning to do that today.

2025-05-22 15:05 UTC, greenc-FNAL commented
@tldahlgren The pipeline https://gitlab.spack.io/spack/spack/-/pipelines/1095847 seems to indicate that `hep-generate` is not properly configured as a dependency of `hep-build`, because the latter failed while the former was still running. Help?

2025-05-22 15:16 UTC, greenc-FNAL commented
> > Also @tldahlgren @tgamblin Any chance this can be in 1.0? I think this would complement #50603 nicely.
> 
> Yes. I didn't get a chance yesterday to look closely at the alternative for fixing the unit test. But I'm planning to do that today.

Thanks for this. I think improving the test coverage is the only remaining task for this PR, no?

2025-05-22 18:30 UTC, greenc-FNAL commented
Would it be reasonable to take optional positional arguments which cause `spack config scopes` to list all the scopes that apply to a specific config type? Then `--file` would cause `include:almalinux9` to be displayed as `$spack/etc/spack/linux/almalinux9/packages.yaml` if that file were present when `spack config scopes --file packages` were invoked.

2025-05-23 00:56 UTC, tldahlgren commented on lib/spack/spack/cmd/config.py
> +    list_scopes_parser = sp.add_parser("list-scopes", help="list defined scopes")
Thanks!

2025-05-23 01:43 UTC, tgamblin commented
could we make it `-p / --paths` to be consistent with `spack find --paths`?  And maybe when you supply the arg it displays the paths next to the name?

2025-05-27 19:39 UTC, tldahlgren requested changes
See comments. Would like to see a unit test for the `-s | --show-paths` option. IMO it would be sufficient to make sure `os.path.join("etc", "spack", "defaults")` appears in the output.

2025-05-27 19:39 UTC, tldahlgren commented on lib/spack/spack/test/cmd/config.py
> +    assert "_builtin" not in output
It would be pretty straightforward to parameterize at least a couple of the new tests based on the (additional) options passed to the command, especially without additional checks.

On the chance you haven't done this before, there are two other tests in this module you can look to for reference (e.g., https://github.com/spack/spack/blob/c2e3b086fe2b22aab0d66d0c3cdc660de66761d6/lib/spack/spack/test/config.py#L480).

2025-05-27 19:39 UTC, tldahlgren commented on lib/spack/spack/test/cmd/config.py
> +    assert "_builtin" not in output
This would be more meaningful IMO if it checked to make sure that the scopes that are output all start with `include` (or `include:`).

2025-05-27 19:39 UTC, tldahlgren commented on lib/spack/spack/cmd/config.py
> +        path = section_path if section_path and os.path.exists(section_path) else f"{scope.path}/"
Should this be using `os.sep` in the `else` instead of `/`?

2025-05-27 19:39 UTC, tldahlgren commented on lib/spack/spack/test/cmd/config.py
> +    assert "_builtin" not in output
Given `--include` takes precedence over `---show-paths`, the same goes for `test_config_scopes_include_path`.

2025-05-27 19:39 UTC, tldahlgren commented on lib/spack/spack/cmd/config.py
> +        tty.warning(f"[section] ({args.section}) ignored without --show-path")
Unfortunately, `tty` uses `warn` instead of `warning`:

```suggestion
        tty.warn(f"[section] ({args.section}) ignored without --show-paths")
```

2025-05-27 19:39 UTC, tldahlgren commented on lib/spack/spack/cmd/config.py
> +        tty.warning(f"[section] ({args.section}) ignored without --show-path")
Would also like to see the shortcut (`-s`) here.

2025-05-27 20:56 UTC, greenc-FNAL commented on lib/spack/spack/test/cmd/config.py
> +    assert "_builtin" not in output
Of course, as soon as #50603 merges, this will no longer be true :-(

2025-05-27 21:30 UTC, tldahlgren commented on lib/spack/spack/cmd/config.py
> +        tty.warning(f"[section] ({args.section}) ignored without --show-path")
Thanks

2025-05-28 00:29 UTC, tldahlgren commented on lib/spack/spack/cmd/config.py
> +    )
Almost forgot to mention you can use the `add_mutually_exclusive_group()` method to allow the parser to handle the mutual exclusion for the options for you. Adding for these two arguments, you get:

```
$ spack config scopes -h
usage: spack config scopes [-hs] [-i | -p] [section]

positional arguments:
  section            tailor scope path information to the specified section
                     options: compilers, concretizer, definitions, env_vars, include, view, develop, mirrors, repos, packages, modules, config, upstreams, bootstrap, ci, cdash

options:
  -h, --help         show this help message and exit
  -i, --included     list only included scopes
  -p, --path-scopes  list only writable scopes with an associated path
  -s, --show-paths   show associated paths for appropriate scopes

$ spack config scopes -i -p
usage: spack config scopes [-hs] [-i | -p] [section]
spack config scopes: error: argument -p/--path-scopes: not allowed with argument -i/--included
```

2025-05-28 13:58 UTC, greenc-FNAL commented on lib/spack/spack/cmd/config.py
> +    )
I had mutually exclusive groups way back when, and then I removed them based on a suggestion from you (although I think the semantics of the relevant options were different). Included scopes are also path scopes, so when `-i` is specified the `-p` is redundant rather than inconsistent. I can certainly have them mutually exclusive in this case if you prefer, though.

What I'd like is for the non-option argument to be bound to the `-s` option if there's a way to do that, although having the presence of the non-option argument _imply_ `-s` would probably be sufficient.

2025-05-28 15:52 UTC, greenc-FNAL commented on lib/spack/spack/test/cmd/config.py
> +    assert "_builtin" not in output
The test now ensures that all included scopes contain `:`.

2025-05-28 19:16 UTC, greenc-FNAL commented
@tldahlgren pending your re-review, and Gitlab getting around to running the CI pipeline, I think this is ready to go.

2025-05-28 20:50 UTC, greenc-FNAL commented
@spackbot run pipeline

2025-05-28 23:12 UTC, tldahlgren approved these changes
LGTM.

2025-05-28 23:15 UTC, merged