geant4/geant4-data: add builtin_clhep variant and v10.0.4
LLNL/spack pull request #41478
Opened 2023-12-07 07:27 UTC by fwerner

This PR adds a historic version (that is still used by some of our simulation frameworks) and its data dependencies.

It also introduces a new variant, builtin_clhep, that builds the CLHEP version shipped with Geant4.

2023-12-07 17:36 UTC, tldahlgren approved these changes, later dismissed
Confirmed the new version sha256.  Will defer merge decision to @drbenmorgan.

2023-12-07 17:36 UTC, tldahlgren commented on var/spack/repos/builtin/packages/geant4/package.py
> +        if "+builtin_clhep" in spec:
We generally recommend use of `spec.satisfies()` for checking variants for reasons I'll paste below.  I realize in this case the odds of other packages having this variant are pretty low ATM so this is more of an FYI.

Per https://spack.readthedocs.io/en/latest/packaging_guide.html#testing-spec-constraints:

"The difference between the two functions is that `satisfies()` tests whether spec constraints overlap at all, while `in` tests whether a spec or any of its dependencies satisfy the provided spec."

2023-12-07 17:54 UTC, drbenmorgan reviewed
v10.0.4 is no longer maintained and hasn't been for getting on for a decade now and I'd prefer that official Spack doesn't include these (and even the inclusion of pre 10.6 versions is now somewhat historical anyway). Also pinging @wdconinc and @sethrj for their input.

2023-12-07 17:55 UTC, drbenmorgan commented
@tldahlgren, do you want to reassign to me - I can then handle updates/etc directly?

2023-12-07 17:59 UTC, sethrj requested changes
I think it's reasonable (but perhaps not great...) to add an old version of software, especially something with as long a lifetime as Geant4, but I don't think `builtin_clhep` should be an option. Spack should always build with external dependencies. If 10.0 can't, then you should instead condition the use of `SYSTEM_CLHEP` to be `spec.satisfies("@10.1:")`, and use the `vendors("clhep", when="@:10.0")` to inform spack that it's using a builtin.

2023-12-07 18:00 UTC, tldahlgren commented
> @tldahlgren, do you want to reassign to me - I can then handle updates/etc directly?

Feel free to coordinate on updates as you see fit.

As for assignments, our use has evolved to mean the account(s) that can merge a PR when it is ready.   So it's up to you what we do there.

2023-12-07 18:02 UTC, tldahlgren commented
> > @tldahlgren, do you want to reassign to me - I can then handle updates/etc directly?
> 
> Feel free to coordinate on updates as you see fit.
> 
> As for assignments, our use has evolved to mean the account(s) that have reviewed and have permissions to merge a PR when it is ready. So it's up to you what we do there.

I should also note, with the holidays coming up, that if the assignee is not available when a PR is merged, someone else with merge authority can also merge the PR.

2023-12-07 18:28 UTC, drbenmorgan commented
Thanks @sethrj, @tldahlgren!

I agree with @sethrj's requested fix for only using the system CLHEP. If 10.0 _doesn't_ work with Spack's CLHEP, then a patch should be added to the Geant4 recipe to allow this. If it's not possible at all, then I'd rather we don't merge this at all. 

Otherwise, if things are otherwise o.k., then I think we can go ahead. Perhaps we should also mark versions older than, say 10.6, as `deprecated`?

2023-12-07 18:35 UTC, fwerner commented
Many thanks for discussing this - and tolerating this old version. It helps very much in making our (admittedly poorly maintained) frameworks easy to install for users.

I have reverted the addition of the `builtin_clhep` variant as requested.

2023-12-07 18:38 UTC, fwerner commented on var/spack/repos/builtin/packages/geant4/package.py
> +        if "+builtin_clhep" in spec:
Many thanks for pointing this out.

I have removed that variant (and therefore the offending line) in the latest commit, so I will just remember this for the future. :+1:

2023-12-07 18:49 UTC, tldahlgren approved these changes, later dismissed
LGTM though recognize the version hasn't been flagged as deprecated as suggested by @drbenmorgan .

2023-12-08 09:52 UTC, drbenmorgan commented
@fwerner, sorry, just one more fix needed - VecGeom support was only introduced in 10.1, so the line:

```python
    variant("vecgeom", default=False, description="Enable vecgeom support")
```

Should be

```python
    variant("vecgeom", default=False, description="Enable vecgeom support",  when="@10.3:")
```

Other than that, good to go (we'll deal with adding `deprecated` to older versions in a separate PR).

2023-12-08 16:25 UTC, fwerner commented
> @fwerner, sorry, just one more fix needed - VecGeom support was only introduced in 10.1, so the line:
> 
> ```python
>     variant("vecgeom", default=False, description="Enable vecgeom support")
> ```
> 
> Should be
> 
> ```python
>     variant("vecgeom", default=False, description="Enable vecgeom support",  when="@10.3:")
> ```

Excellent, thank you for spotting that!

> Other than that, good to go (we'll deal with adding `deprecated` to older versions in a separate PR).

Many thanks!

2023-12-11 07:55 UTC, drbenmorgan approved these changes
All good, so LGTM!

2023-12-11 07:59 UTC, drbenmorgan commented
@sethrj, I think your changes have been addressed but if you could double check it's ready to go.

2023-12-11 13:21 UTC, sethrj approved these changes
LGTM! Thanks.

2023-12-11 13:21 UTC, merged