use updated MakefileBuilder syntax in code examples
LLNL/spack pull request #41533
Opened 2023-12-10 21:44 UTC by ChristopherChristofi

To prevent errors such as:

`==> Error: TypeError: edit() takes 3 positional arguments but 4 were given`

2023-12-11 08:51 UTC, alalazo requested changes
I think the documentation in these sections is written as if people are adding methods to the `*Package`. If they use a builder, the signature changes, as very briefly documented here:
- https://spack.readthedocs.io/en/latest/packaging_guide.html#overriding-an-entire-phase

at the end of the paragraph.

2023-12-13 02:07 UTC, ChristopherChristofi commented
Yes that makes sense, thank you. Will have a look at reverting the above to instead try include a brief note somewhere regarding the builder syntax requirement for certain Makefile examples and point to your recommended docs page

2024-03-08 05:44 UTC, alalazo commented
@ChristopherChristofi Is this still a work in progress, or can we close the PR?

2024-03-11 18:09 UTC, ChristopherChristofi commented
Thank you for the reminder. I think this can be closed, your suggested builder class docs solved the issue for me

2024-03-11 18:09 UTC, closed without merging