spack bootstrap --dev: EOL Python versions no longer supported
LLNL/spack pull request #41629
Opened 2023-12-13 06:54 UTC by adamjstewart

As discussed in https://github.com/spack/spack/pull/41031#issuecomment-1852697475, we decided to no longer support `spack bootstrap --dev` for EOL Python versions. Users have many alternative options:

* Run `spack style` with a newer version of Python
* Use pip to install development dependencies
* Use `@spackbot fix style` on their PR instead

Note that bootstrapping clingo/gpg with EOL Python versions is still supported and expected to work.

2023-12-13 08:43 UTC, haampie commented
Still need to bootstrap pytest...

2023-12-13 08:47 UTC, tgamblin commented
Simplification: do we need to bootstrap `pytest` on the run-only python versions (this is really just the RHEL8 UBI), or can we `pip` install it?

2023-12-13 08:57 UTC, adamjstewart commented
I don't think the majority of our developers (the kind who write unit tests) are developing Spack on a system where Python 3.6/3.7 is the only thing they have access to. I also hope our developers are capable of using Spack to install modern Python, or pip to install pytest.

2023-12-13 09:00 UTC, adamjstewart commented
Honestly, I don't mind maintaining support for installing style/test/dev deps with EOL Python under the condition that we test this in CI to ensure that it doesn't break. @alalazo added a test that is supposed to do exactly this. However, our experience has been that this test (the one I'm removing in this PR) doesn't fail on the PR that breaks a package recipe, but instead fails on develop, breaking PRs for everyone else. So we would need to fix this test first.

2023-12-13 09:05 UTC, tgamblin commented
> Honestly, I don't mind maintaining support for installing style/test/dev deps with EOL Python under the condition that we test this in CI to ensure that it doesn't break.

This would be great.

> However, our experience has been that this test (the one I'm removing in this PR) doesn't fail on the PR that breaks a package recipe, but instead fails on develop, breaking PRs for everyone else. So we would need to fix this test first.

@alalazo what's needed to get this working?

2023-12-13 09:22 UTC, alalazo commented
> However, our experience has been that this test (the one I'm removing in this PR) doesn't fail on the PR that breaks a package recipe, but instead fails on develop, breaking PRs for everyone else.

Hmm, this one was failing as far as I can tell. The other one, which is a copy of this one, was only run on core changes from a certain point on, and that's why we were not catching failures in package-only PRs

2023-12-13 09:33 UTC, alalazo commented
@tgamblin Note that proceeding with this PR wouldn't be that bad. As tools are evolving, the old versions of `mypy` etc. we have to use on Python 3.6 and Python 3.7 may not catch all the errors the CI would catch. So there would be cases where:
```
$ spack style --fix
```
would pass on Python 3.6 locally, but not on Python 3.11 in CI

2023-12-13 11:06 UTC, adamjstewart commented
Personally I only ensure that style tests pass for the latest version of Python, and only use the latest version of those style tools. A lot of style tools have dropped support for EOL Python, so it would be nice to do the same.

2023-12-13 11:23 UTC, adamjstewart commented
So I don't think RHEL platform python comes with pip, and if I install pip with dnf, it will likely install python too. Not sure what the easiest way to install pytest without Spack is on a barebones system.

2024-01-16 12:31 UTC, adamjstewart commented
Alternatively, we could remove testing with platform-python.

2024-03-02 14:57 UTC, tgamblin requested changes
We still need CI for RHEL8 platform python, and we need a way for tests to work there. Style stuff I do not mind requiring new versions for, but we really need pytest to work somehow.

2024-03-02 15:07 UTC, adamjstewart commented
Well, let me know when you figure out how to install pytest on rhel platform python without also installing python.

2024-03-10 10:22 UTC, adamjstewart commented
I'm no longer maintaining all Python packages, so whether or not a package change breaks CI is no longer of concern to me. I'll continue deprecating and removing things from packages I maintain and let others clean up the mess. Ideally, we should either stop supporting bootstrapping of development dependencies on EOL Python or actually test it in CI (even for package-only PRs), but I'll let someone else take over that.

2024-03-10 10:22 UTC, closed without merging