glib: replace url links with local files for patches
LLNL/spack pull request #41687
Opened 2023-12-14 20:20 UTC by tygoetsch

Spack FetchError: glib fails to build at LANL because Spack tries and fails to fetch some patches from gitlab.gnome.org due to proxy issues. Placing these patches in the package directory seems to solves this problem (tested on pop_os for v2.76.1 and v2.78.0 and sles15 for v2.78.0).

2023-12-14 20:31 UTC, michaelkuhn requested changes
I'm against this, we have too much stuff in the repository as it is. Why do they fail to download?

2023-12-14 20:40 UTC, michaelkuhn commented
@alalazo Shouldn't patches be mirrored? For some reason, some patches seem to be missing from `mirror.spack.io`.

2023-12-14 20:40 UTC, tygoetsch commented
The proxy server at Los Alamos National Laboratory refuses the connection to gitlab.gnome.org. Are you basing your comment on a hard limit you can't go beyond or something? The size of the current directory is about 52KB according to `du`. I don't know if there's a size limit on spack package directories, but I imagine that's not close to it.

2023-12-14 21:08 UTC, michaelkuhn commented
It's not really about the size, it's more about the number of files and the fact that we will never be able to remove those from Git history even if we remove the package versions and associated patches at some point.

2024-01-18 01:18 UTC, bernhardkaindl commented
LANL hindering your work you have to by blocking gitlab.gnome.org isn't sensible.

Michael would have to reverse his rejection into an approval for this PR to be mergeable again.

Can you just request access? Usually there should be an IT ticket system where you just report an issue and as justification, add this PR.

2024-01-18 01:30 UTC, bernhardkaindl requested changes
Agreeing with Michael Kuhn, I've to explain that spack should not carry patches that are not positively needed. The number of files is already large. Like he says, we'll not get rid of patch files for a long time once they are added.

As `spack` won't re-download already present sha256 files and also patches are such files, you can archive the sha256 download files from them from an open connection when you are behind the uncompromising proxy if your IT is not reachable to update its proxy list.

You can also request to be put into another zone where or get and special proxy password, there are many possible solutions for it. I was in a similar situation for a long time, but this is not the scaleable way to work around it.

As we've already considered this more than enough, and see no hope or reason to carry a mirror of patches (such users can do this outside of `spack`, as described) I'm going to close this PR as having given more tips to resolve this by other means.

2024-01-18 01:31 UTC, bernhardkaindl commented
@tygoetsch closing as described by me and Michael Kuhn. I've given a number of other way to address this for you.

2024-01-18 01:31 UTC, closed without merging

2024-02-27 15:50 UTC, tygoetsch commented
@bernhardkaindl I understand. Thank you for the explanation. I'll reach out to our network team to see if that can't be addressed. My PR was intended to address this for all sites that have proxy issues (or are air-gapped), but I can see the reasoning behind the rejection.