perl-moox-types-mooselike: New package
LLNL/spack pull request #41705
Opened 2023-12-14 22:58 UTC by EbiArnie

Adds MooX::Types::MooseLike

2023-12-19 11:28 UTC, alalazo requested changes

2023-12-19 11:28 UTC, alalazo commented on var/spack/repos/builtin/packages/perl-moox-types-mooselike/package.py
> +# Copyright 2023 EMBL-European Bioinformatics Institute
Can we stick to the standard copyright?

2023-12-20 11:55 UTC, EbiArnie commented on var/spack/repos/builtin/packages/perl-moox-types-mooselike/package.py
> +# Copyright 2023 EMBL-European Bioinformatics Institute
OK

2024-01-04 12:40 UTC, alalazo approved these changes

2024-01-04 12:40 UTC, merged