Only reuse externals when configured
LLNL/spack pull request #41707
Opened 2023-12-14 23:40 UTC by haampie

Users often learn the hard way that removing or modifying an external in
packages.yaml is not enough to avoid an external from getting pick up in
concretization.

Since this such a footgun, and gets reported almost every week on Slack,
I think it makes sense and is pretty clean to apply the same reuse rule
we already apply to build caches also to the local database: only reuse
those externals that are in config.

2023-12-15 00:13 UTC, becker33 reviewed
We should add this to the upcoming major changes pinned discussion.

Also, I think we should include a feature to add all the externals associated with a given spec to be added to the config. For example, if I specify `spack install foo ^bar/hash`. Under this feature I may get an error that `bar/hash` depends on an external that is no longer configured. We should have an easy one-liner from that point to add the relevant externals to my config.

2023-12-15 00:15 UTC, haampie commented
ping @alalazo

2023-12-15 18:20 UTC, becker33 commented
@haampie as I was thinking about this more last night, I realized this would require additional functionality to add the externals from the cray manifest file to the packages configuration in addition to the database. This might prove tricky, since the cray externals from the manifest can have dependency information, and we don't currently allow dependency information from externals in the packages config.

Allowing dependencies on externals looked challenging last time I looked at it, but I can take another stab at it now. The other option would be some more complex mapping between the externals in the database and the externals in the config. For example, externals in the db could store the yaml block in which they were defined, which would make identifying the correct external possible even if there are multiple satisfying externals

2023-12-15 19:05 UTC, haampie commented
I didn't think of the cray manifest at all, that's a bit of a blocker.

2023-12-16 09:58 UTC, haampie commented
@becker33 can't we keep track of how externals were added and use that to determine reuse or not?

I agree that migrating entries from db to config works, but doesn't really sound great.

I don't understand what you meant with that `foo ^bar/hash` example, that doesn't trigger reuse?

2023-12-16 10:32 UTC, alalazo commented
I'll add my thoughts on this:

1. This is in line with #35975 which was merged. Can't we merge this as is as an improvement on Linux?
2. On Cray, afaik, externals can be added from a JSON file that is on the system (and is structured in a way that is very similar to a DB) and from config files. We can monitor the JSON file AND the config files for the time being.
3. Migrating stuff from DB to `packages.yaml` is a very bad idea as a) we'll end up with a less powerful DB b) we'll get back entries that are the "concretization" of something that was in the DB already c) `packages.yaml` will be cluttered[^1]

As for a more long term way forward, I still advocate for **an intermediate DB** to store externals. That will:
1. Solve the one to many mapping we have now on externals (right now the same external on disk has potentially many different hashes  in the DB)
2. Allow the same semantic we use here and in #35975 (instead of satisfiability of an external abstract spec, we need to check if the external we want to reuse is in the intermediate DB - and don't consider it if it isn't)
3. Allow for automatic updates / cleaning procedures for externals (the intermediate DB is under Spack control, so can be updated whenever a change in configuration etc. is detected. Based on the intermediate DB we can have commands that update, with prompt, the user DB too).
4. (This is for us, not for users) Remove the weird concretization logic and ad-hoc rules we have for externals during concretization

[^1]: I think people will start, rightfully, to complain "Why Spack is messing with my `packages.yaml`"?

2023-12-16 10:53 UTC, haampie commented
> We can monitor the JSON file AND the config files for the time being.

we don't keep track what file was used

2023-12-17 03:41 UTC, psakievich commented
> users don't think of externals being "installed in the database" at all,
their externals are "installed on the system"

☝🏻 this times :100:.

Maybe this is crazy talk, but I wish externals could be implemented as an in-memory artifact rather than registering them in a database.  I'm sure in practice this is hard to do, but in principle that seems closer to reality.  An external is not a spack artifact, just a spack registration.  When system externals shift under us they usually affect low level specs that need require a lot of rebuilding when they change. Often times the best thing to do is just delete everything and start from scratch.

If the system changed then spack's database is not valid anymore wrt to the external even if nothing changed in spack. AND the only way spack will be able to detect these changes ATM is if the users tell it.

2023-12-20 08:32 UTC, haampie commented
So, what do we do here @becker33 / @alalazo?

I noticed that cray entries set `spec.origin = "external-db"` which ends up as part of an install record, so we do keep track after all.

2023-12-20 11:10 UTC, haampie commented
Pushed that change

2023-12-20 17:26 UTC, becker33 requested changes
This all looks perfect except it should have a test for `local=True` with a DB entry with `origin="external-db"`.

2023-12-20 18:27 UTC, becker33 approved these changes

2023-12-20 19:21 UTC, merged