hdf-eos2: support version @3.0, plus assorted fixes
LLNL/spack pull request #41782
Opened 2023-12-19 16:58 UTC by payerle

1) support for version @3.0
Unfortunately, download seems to require registration now so using manual_download mechanism for @3:

2) copying from hdf-eos5 patch from @vanderwb to enable use of Spack compiler wrappers instead of h4cc

3) Patching an issue in hdf-eos2 configure script.  The script will test for jpeg, libz libraries, succeed and append HAVE_LIBJPEG=1, etc to confdefs.h, and then abort because HAVE_LIBJPEG not set in running environment.

4) Add some LDFLAGS to build environment.  Otherwise seems to fail to build test script due to rpc dependence in HDF4.

2023-12-19 21:48 UTC, climbfuji requested changes
Thanks for creating this PR!

One specific comment about the auto_download/manual_download/version logic.

What kind of testing have you done for the other changes in this PR?

2023-12-19 21:48 UTC, climbfuji commented on var/spack/repos/builtin/packages/hdf-eos2/package.py
> +            can_auto_download = vrec[0].get("can_auto_download", False)
The package management for hdf-eos2 is obviously "unique" and creates its challenges.

I am wondering if it is wise to tie the `can_auto_download` logic to the version. These things could change I suppose? Would it be better to set the url in `url_for_version` based on the version requested, and also set `manual_download` based on the version? There wouldn't be any need for `can_auto_download` at all.

2024-02-17 03:31 UTC, climbfuji commented
@payerle Did you have a chance to look at my question/comment?

2024-02-17 18:26 UTC, payerle commented
I was offline the past week.  Will look into monday

On Fri, Feb 16, 2024, 10:31 PM Dom Heinzeller ***@***.***>
wrote:

> @payerle <https://github.com/payerle> Did you have a chance to look at my
> question/comment?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/spack/spack/pull/41782#issuecomment-1949627595>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AETE576MNHJ2DO347OJNWCTYUAQB7AVCNFSM6AAAAABA3P2N2CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNBZGYZDONJZGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-19 21:29 UTC, payerle commented
Sorry about the delay in responding.  I either complete missed your initial response from Dec, or it got lost/fell into a crack during the Christmas holidays.

With respect to your comments:

1) Assorted comments re download mechanism: Yes, package management is "unique"; it was bad enough for \@2 and has gotten worse with \@3.  I am not sure I understand to full extent of your suggestions here.

It was always my (probably overly optimistic) hope that the authors would setting on a standard naming convention, and I am still hoping that the filename for version 3.1 would be essentially the same as that for 3.0.  Hence my use of the url data member for the \@3 filename.    

I was using 'can_auto_download' field/variable because I was not sure if manual_download could be set on a per version basis, as I was under the impression spack wants it defined at the package class level and I did not think there was a spec available at that level.  So the PR _always_ sets manual_download to True, but gives a downloadable URL in url_for_version for the versions
with can_auto_download set (currently just the \@2 versions) --- this seems to work (I can fetch the two \@2 versions from spack, and \@3 will fail with appropriate warning unless the file is manually downloaded).  

I can change the name of 'can_auto_download' field/variable to 'manual_download' (and change the sense of the boolean), and can even change the basename fields to hardcode the version, etc., but it only makes things marginally cleaner in my opinion, and I am not counting on \@3.1 or whatever the next release is to match the "standards" set by \@3.0.

With respect to changes originally numbered 2-4 (e.g.  hdf-eos5 patch, configure patch, and LDFLAGS): 
I have really only tested that hdf-eos2  built with these changes on my system.  With the exception of the patch ported from hdf-eos5, all of these changes were necessary for hdf-eos2 to build on my system.  The patch from hdf-eos5 makes things cleaner, as otherwise there was an ugly (and potentially problematic) hack to get hdf-eos2 build to use h4cc as discussed in the hdf-eos5 PR 

Btw, thank you for taking on the role of maintainer for the package --- I am a HPC sys admin building out a sw library for my users, but do not actually _use_ the packages personally.  I wrote the original hdf-eos2 recipe, but not being an user do not really know how to use/test them well.

The LDFLAGS and related changes should be fairly safe; those are sort of expected fixes to compilation issues.

The patch to use standard spack compilers instead of h4cc also seems reasonably safe.

The patch to the configure script is a bit more suspect as that is not something that typically should be needed to compile code.
However,   I did a reasonable amount of debugging the (painful to read) configure script, and these all seemed necessary to me.  The configure script appears to successfully test for the presence of the libraries, and even outputted the appropriate HAVE_LIBJPEG=1 lines to confdefs.h, but then would check for the value of HAVE_LIBJPEG, etc. env var in the configure script, and abort because it was not set.  I am not sure how that ever worked.  My patch simply sets the environment variable in the context of the script when it is output to confdefs.h, so that the checks in the configure script behave properly.  This looks like a bug in the generation of the configure script, and so I believe this is also a valid and safe change.

2024-02-21 03:58 UTC, climbfuji commented
Thanks @payerle that's a lot of information. I think the best way forward is for me to test your changes on a macOS and a Linux system.

2024-02-27 17:35 UTC, hyoklee approved these changes

2024-02-28 15:34 UTC, climbfuji approved these changes

2024-03-04 20:08 UTC, alalazo approved these changes

2024-03-04 20:08 UTC, merged