Make license verification check stricter
LLNL/spack pull request #41800
Opened 2023-12-20 16:22 UTC by alalazo

Modifications:
- [x] Check for extra Copyright lines (which are redundant, as contributors always retain Copyright)
- [ ] Improve wording in the COPYRIGHT file
- [ ] Improve documentation wrt contributions
- [ ] Fix issues found by the stricter check

2023-12-20 16:24 UTC, alalazo commented
@EbiArnie @tgamblin fyi, the draft PR we talked about.

2023-12-21 13:06 UTC, EbiArnie requested changes

2023-12-21 13:06 UTC, EbiArnie commented on lib/spack/spack/cmd/license.py
> +            f"files extra Copyright lines:                {extra_copyright:d}",
files with extra Copyright lines:

2023-12-21 13:06 UTC, EbiArnie commented on lib/spack/spack/cmd/license.py
> +                    break
This won't catch this, I think:

```
# text of LLNL copyright
<empty line>
# another license
...
```

2023-12-21 13:06 UTC, EbiArnie commented on lib/spack/spack/cmd/license.py
> +            if line and "copyright" in line.lower():
According to Wikipedia, in the US at least, we should look for these:
"©" or the word "Copyright" or abbreviation "Copr."

Probably overengineering, though.

2024-01-08 13:57 UTC, alalazo commented on lib/spack/spack/cmd/license.py
> +            f"files extra Copyright lines:                {extra_copyright:d}",
Done

2025-05-07 07:28 UTC, closed without merging