perl-data-dumper: add new version
LLNL/spack pull request #41916
Opened 2024-01-01 19:34 UTC by ChristopherChristofi

2024-01-03 17:21 UTC, ChristopherChristofi commented
@spackbot run pipeline

2024-01-09 21:40 UTC, tldahlgren requested changes
Looks like the version URL is different for the latest (https://cpan.metacpan.org/authors/id/N/NW/NWCLARK/Data-Dumper-2.183.tar.gz).

You can add a `url_for_version` method or add the `url` argument to the `version` directive.  See the docs at https://spack.readthedocs.io/en/latest/packaging_guide.html#version-urls.

2024-03-11 18:02 UTC, ChristopherChristofi commented
Hello @tldahlgren, thank you for the suggested changes above.
As I mentioned in my other PR (https://github.com/spack/spack/pull/42157#discussion_r1520152438), when you get the chance,
please do let me know if you want me to complete this current new version perl-data-dumper PR as intended or change to instead have a look at altogether removing the existing perl-data-dumper package where found in spack?
as it is already present as a core perl module and should not be needed as a standalone spack package but has been used as a dependency for several spack packages:
```
$  corelist Data::Dumper

Data for 2019-05-22
Data::Dumper was first released with perl 5.005
```

2024-04-11 21:33 UTC, tldahlgren commented
> Hello @tldahlgren, thank you for the suggested changes above. As I mentioned in my other PR ([#42157 (comment)](https://github.com/spack/spack/pull/42157#discussion_r1520152438)), when you get the chance, please do let me know if you want me to complete this current new version perl-data-dumper PR as intended or change to instead have a look at altogether removing the existing perl-data-dumper package where found in spack? as it is already present as a core perl module and should not be needed as a standalone spack package but has been used as a dependency for several spack packages:
> 
> ```
> $  corelist Data::Dumper
> 
> Data for 2019-05-22
> Data::Dumper was first released with perl 5.005
> ```

Looks like the original package was added in January 26, 2019 so before it became part of the core.  Under the circumstances (and the fact the `perl` package only lists versions since `5.16.3`, my inclination is to remove it.  But that does mean the following packages would need to be checked and possibly have `perl` added as a dependency under the equivalent conditions:

- `aomp`
- `dakota`
- `llvm-amdgpu`
- `llvm-doe`
- `llvm`
- `roary`
- `rocm-openmp-extras`
- `sollve`

2025-06-06 12:04 UTC, haampie commented
Hi @ChristopherChristofi, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2026-01-04 01:52 UTC, closed without merging