perl-constant: add new package
LLNL/spack pull request #41912
Opened 2024-01-01 14:42 UTC by ChristopherChristofi

2024-01-02 23:36 UTC, alecbcs requested changes
Confirmed SHA. PR looks good to me. Just a quick request to update the license for 2024.

2024-01-02 23:36 UTC, alecbcs commented on var/spack/repos/builtin/packages/perl-constant/package.py
> +# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2024 Lawrence Livermore National Security, LLC and other
```

Update license for 2024.

2024-01-03 18:25 UTC, alecbcs approved these changes
Confirmed SHA. Looks good to me.

2024-01-03 18:26 UTC, merged

2024-01-16 01:06 UTC, ChristopherChristofi commented
```
Data for 2023-07-02
constant was first released with perl 5.004
```
Has been a core module since version 5.004, which pre-dates all end of life Perl releases available in spack