ncurses: fix 5.9 and 6.0 on modern compilers
LLNL/spack pull request #41982
Opened 2024-01-07 18:10 UTC by wdconinc

This fixes #41981, and now allows installation of ncurses 5.9 and 6.0 with gcc-13.

## cppflags -P for 5.9 too
Version 6.0 had already a patch to the Makefile to add `-P` to the cppflags to avoid a first error. This patch did not apply cleanly to 5.9, so instead of adding a patch this PR turns this into a flag_handler modification for both 5.9 and 6.0, with the same gcc@5: constraint as was already present for 6.0.

## c++14 for 5.9 and 6.0
Both versions 5.9 and 6.0 use [dynamic exception specifications](https://en.cppreference.com/w/cpp/language/except_spec) not allowed in c++17 (and deprecated since c++11). This PR modifies the flag_handler to pins the c++ standard to c++14 for both 5.9 and 6.0.

## const type conversion patch for 5.9
In addition to the above, and only for 5.9, a patch is needed that fixes some const-correctness issues in 5.9. No online repository with direct link is available, but the patch content and filename was kept the same as the [upstream mailing list report](https://lists.gnu.org/archive/html/bug-ncurses/2014-08/msg00008.html).

2024-01-09 00:39 UTC, becker33 commented
Does ncurses require cxx14+? The reason I ask is that this PR as written will prevent `ncurses@:5` from building with older compilers that support cxx11 but not cxx14.

2024-01-09 00:50 UTC, wdconinc commented
It doesn't require c++14 but I don't think we have a way to determine which c++ standards is the default, so we would only reduce it to c++14 if the default is 17 or higher.

2024-01-09 15:15 UTC, alalazo requested changes

2024-01-09 15:15 UTC, alalazo commented on var/spack/repos/builtin/packages/ncurses/package.py
> +    patch("0001-Fix-errors-in-type-conversion.patch", when="@:5")
Can you add a brief comment above the `patch` directive explaining:
1. What is the effect of the patch
2. Why it is needed
3. Where it was taken from

? That helps having context when reading the `package.py` file alone.

2024-01-10 17:44 UTC, wdconinc commented on var/spack/repos/builtin/packages/ncurses/package.py
> +    patch("0001-Fix-errors-in-type-conversion.patch", when="@:5")
```suggestion
    # avoid disallowed const_cast from T* to void* and use reinterpret_cast
    # Ref: https://lists.gnu.org/archive/html/bug-ncurses/2014-08/msg00008.html
    patch("0001-Fix-errors-in-type-conversion.patch", when="@:5")
```

2024-01-16 09:22 UTC, alalazo approved these changes

2024-01-16 09:23 UTC, alalazo commented
@becker33 Feel free to merge if it looks good to you

2024-01-18 00:16 UTC, bernhardkaindl approved these changes
Well-researched and well-described, thanks!

Has passed GitLab CI, I guess that it is built and used in GitLab CI too.

2024-01-18 00:20 UTC, wdconinc commented
> Has passed GitLab CI, I guess that it is built and used in GitLab CI too.

I didn't think this would be used in GitLab CI anywhere due to the old versions. Based on https://cache.spack.io/package/develop/ncurses/specs/ I think only 6.3 and 6.4 are actually built.

2024-01-29 14:18 UTC, merged