allow spec formatting in module name suffix
LLNL/spack pull request #41998
Opened 2024-01-09 00:27 UTC by simonLeary42

module projections allow spec formatting such as `^python{^python.version}`, but this is lacking in module suffixes. Added formatting to module suffixes, following `_check_tokens_are_valid`.

2024-01-09 15:09 UTC, alalazo commented
Module suffixes have been part of the configuration long before projections. Since projections are more general, are there use cases that still need suffixes and cannot be covered by projections?

2024-01-09 15:24 UTC, simonLeary42 commented
What I like about suffixes is that they scale well.

This smelly configuration:
```
      projections:
        sparsehash^cuda^python: '{name}/{version}+cuda{^cuda.version}+py{^python.version}'
        sparsehash^cuda: '{name}/{version}+cuda{^cuda.version}'
        sparsehash^python: '{name}/{version}+py{^python.version}'
        sparsehash: '{name}/{version}-{hash:3}'
        ^cuda^python: '{name}/{version}+cuda{^cuda.version}+py{^python.version}'
        ^cuda: '{name}/{version}+cuda{^cuda.version}'
        ^python: '{name}/{version}+py{^python.version}'
        all: '{name}/{version}'
```
can be replaced with this much more concise configuration:
```
      projections:
        sparsehash: '{name}/{version}-{hash:3}'
        all: '{name}/{version}'
all:
  suffixes:
    ^python: python{^python.version}
    ^cuda: python{^cuda.version}
```

2024-01-09 15:29 UTC, simonLeary42 commented
We add python and cuda versions to module names since python and cuda cannot currently be added to the module hierarchy, it avoids name clashes, and it's clearer to the user.

2024-01-09 15:47 UTC, alalazo commented
> What I like about suffixes is that they scale well.

Ok, that makes sense - they have a "all matches are applied in order" semantic rather than a "first match wins"

2024-01-09 17:01 UTC, simonLeary42 commented
Is there anything more I should do for this to be approved? I'm not sure what I can do about codecov failing.

2024-01-16 09:25 UTC, alalazo requested changes
Can you add regression tests for this PR?

2024-10-31 14:58 UTC, haampie commented
Closed by e5a602c1bb39555a5e1440bbe1268fc7aea08459

2024-10-31 14:58 UTC, closed without merging