star: updating to 2.7.11a
LLNL/spack pull request #42011
Opened 2024-01-09 15:37 UTC by A-N-Other

Bumping this module file to include the latest release. Installed and tested on `arch=linux-rocky8-icelake`

2024-01-09 15:48 UTC, alalazo approved these changes

2024-01-10 07:11 UTC, alalazo requested changes
Pipelines are failing when building the new version of `star`

2024-01-26 15:58 UTC, alalazo commented on var/spack/repos/builtin/packages/star/package.py
> +            if spec.satisfies("target=aarch64:"):
Given the name I wonder if:
```suggestion
            if spec.satisfies("platform=darwin target=aarch64: "):
```
is better. Which target do you have to make for `linux` on `aarch64`?

2024-01-26 16:00 UTC, A-N-Other commented
Thanks @alalazo

2024-01-29 09:45 UTC, alalazo commented
Apparently it didn't:
```
xxd -i parametersDefault > parametersDefault.xxd
/bin/sh: xxd: command not found
```

2024-01-30 22:19 UTC, A-N-Other commented
Finally working on the ARM testbeds @alalazo. Should be good to go.

2024-02-05 11:05 UTC, alalazo approved these changes

2024-02-05 11:06 UTC, merged