googletest: change the URL
LLNL/spack pull request #42027
Opened 2024-01-10 10:15 UTC by jmcarcell

The old URL doesn't work for v1.13 and 1.14, the new one does and the hashes are correct.

2024-01-10 12:43 UTC, sethrj approved these changes

2024-01-10 12:44 UTC, sethrj requested changes
The new URL doesn't work with older releases: I tested it with 1.10.0. You'll have to use `url_for_version`.

2024-01-10 13:02 UTC, jmcarcell commented
Added

2024-01-10 14:03 UTC, jmcarcell commented
Ok, finally found the issue with `version.satisfies` (which was being true in the first if). Now it can fetch v1.14.0 fine

2024-01-11 13:11 UTC, sethrj commented on var/spack/repos/builtin/packages/googletest/package.py
> +        if version >= Version("1.13"):
I think this might be a bug in Spack...

2024-01-11 13:12 UTC, sethrj approved these changes

2024-01-11 13:13 UTC, merged

2024-01-11 13:13 UTC, sethrj commented
Thanks for noticing this @jmcarcell !