Create reproducible tarballs in VCSFetchStrategy.archive
LLNL/spack pull request #42042
Opened 2024-01-11 10:57 UTC by haampie

Currently when you repeatedly create a bootstrap mirror that includes
`clingo-bootstrap@spack` you get different tarballs every time.

This PR ensures normalized tarballs like we do for binaries:

- normalize file permissions (in fact that was already inspired by git, so
  should be good)
- normalized file creation/modification time (timestamp 0)
- uid / guid = 0, no usernames
- normalized gzip header

2024-01-12 00:34 UTC, tgamblin requested changes
LGTM -- one question and a request.

1. Should `reproducible_tarfile_from_prefix()` take a parameter for the parent directory name of the tarfile, so that we could create a reproducible directory regardless of what the parent directory is called?
2. Can you add tests for `reproducible_tarfile_from_prefix()` to ensure that creating two tarballs of the same thing is reproducible?

2024-01-12 13:12 UTC, haampie commented
1. `path_to_name` is more generic and what I already have. We use that also in build cache tarballs to get posix paths relative to the file system root (`/path/to/opt/pkg-1.2.3-abcdef` -> `path/to/opt/pkg-1.2.3-abcdef`)
2. There are already various tests for that in `lib/spack/spack/test/bindist.py`, but OK, I've added something that's more of a unit test.

2024-01-12 16:47 UTC, haampie commented
Okay, so the only thing I'm not 100% sure about is reproducibility across platforms when dealing with symlinks.

Currently I'm copying the `os.readlink(...)` value verbatim in the tarball entry, which I guess is correct, since it's data.

But if you a symlink `x/y` that would translate to a tarball entry `x\\y` on Windows, even if the file `x/y` is in the current tarball.

For now I've documented the potential issue, don't think it's a big problem in practice.

2024-01-12 17:12 UTC, tgamblin commented
> But if you a symlink x/y that would translate to a tarball entry x\\y on Windows, so not bit-wise identical to the tarball created on a posix system, even if the target of the symlink is inside the tarball.

I'm not sure when we'd cross-build for windows.  I guess if we had windows systems sharing a filesystem with unix systems, and we tasked some unix systems with creating the tarballs for windows directories, we might care about this.

Since the windows tests are failing for what I think is a related reason, maybe we can ask @johnwparent how best to handle it.  I agree -- ideally the tarball would be *exactly* identical regardless of where its was created.

2024-01-15 17:49 UTC, haampie commented
So, hardlinks on Windows work, BUT symlinked dirs are problematic after roundtrip from the perspective of python:

1. Initially they are created with `0o777`
2. In the first tarfile they're stored as `0o755`
3. Then they are extracted with `0o666`
4. And in the second tarfile they end up with `0o644`

Maybe `tar.extractall(...)` is problematic.

2024-01-17 05:10 UTC, tgamblin approved these changes

2024-01-17 05:11 UTC, merged