visit: set minimum silo version to 4.11 for +conduit
LLNL/spack pull request #42072
Opened 2024-01-13 18:29 UTC by BenWibking

VisIt fails to build when +conduit is enabled when Silo 4.10 is used as a dependency. This sets the minimum Silo version to 4.11 when +conduit is specified.

2024-01-16 08:50 UTC, alalazo requested changes
If the constraint is not a requirement from the `visit` build system, we should fix `silo`

2024-01-16 08:50 UTC, alalazo commented on var/spack/repos/builtin/packages/visit/package.py
> +    depends_on("silo@4.11: +shared", when="+silo")
To me this means we should fix building `silo@4.10` with Spack, rather than overconstraining `visit`

2024-01-16 19:06 UTC, cyrush commented
@BenWibking can you share the build issue you see with Silo?

2024-01-16 20:25 UTC, BenWibking commented
This is the full spec:
```console
$ spack spec -I silo@4.10%gcc@11.4.0 ^hdf5@1.8.23
Input spec
--------------------------------
 -   silo@4.10%gcc@11.4.0
 -       ^hdf5@1.8.23

Concretized
--------------------------------
 -   silo@4.10.2%gcc@11.4.0+fortran+fpzip+hdf5+hzip+mpi+pic+shared~silex build_system=autotools patches=251244d,3a1e831,7b5a1dc,eb2a3a0,fa050e0 arch=linux-fedora_asahi_remix39-m1
[+]      ^autoconf@2.69%gcc@11.4.0 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-fedora_asahi_remix39-m1
[+]      ^autoconf-archive@2023.02.20%gcc@11.4.0 build_system=autotools arch=linux-fedora_asahi_remix39-m1
[+]      ^automake@1.16.5%gcc@11.4.0 build_system=autotools arch=linux-fedora_asahi_remix39-m1
[+]      ^gcc-runtime@11.4.0%gcc@11.4.0 build_system=generic arch=linux-fedora_asahi_remix39-m1
[e]      ^gmake@4.4.1%gcc@11.4.0~guile build_system=generic arch=linux-fedora_asahi_remix39-m1
[+]      ^gnuconfig@2022-09-17%gcc@11.4.0 build_system=generic arch=linux-fedora_asahi_remix39-m1
[+]      ^hdf5@1.8.23%gcc@11.4.0~cxx~fortran+hl~ipo+mpi+shared~szip~threadsafe+tools api=default build_system=cmake build_type=Release generator=make arch=linux-fedora_asahi_remix39-m1
[e]          ^cmake@3.27.7%gcc@11.4.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-fedora_asahi_remix39-m1
[e]          ^pkgconf@1.9.5%gcc@11.4.0 build_system=autotools arch=linux-fedora_asahi_remix39-m1
[+]      ^libtool@2.4.7%gcc@11.4.0 build_system=autotools arch=linux-fedora_asahi_remix39-m1
[+]      ^m4@1.4.19%gcc@11.4.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-fedora_asahi_remix39-m1
[e]          ^diffutils@3.10%gcc@11.4.0 build_system=autotools arch=linux-fedora_asahi_remix39-m1
[+]          ^libsigsegv@2.14%gcc@11.4.0 build_system=autotools arch=linux-fedora_asahi_remix39-m1
[+]      ^openmpi@4.1.6%gcc@11.4.0~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~internal-pmix~java~legacylaunchers~lustre~memchecker~openshmem~orterunprefix+romio+rsh~singularity+static+vt+wrapper-rpath build_system=autotools fabrics=none schedulers=none arch=linux-fedora_asahi_remix39-m1
[+]          ^hwloc@2.9.1%gcc@11.4.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-fedora_asahi_remix39-m1
[+]              ^libpciaccess@0.17%gcc@11.4.0 build_system=autotools arch=linux-fedora_asahi_remix39-m1
[+]                  ^util-macros@1.19.3%gcc@11.4.0 build_system=autotools arch=linux-fedora_asahi_remix39-m1
[+]              ^libxml2@2.10.3%gcc@11.4.0+pic~python+shared build_system=autotools arch=linux-fedora_asahi_remix39-m1
[+]                  ^libiconv@1.17%gcc@11.4.0 build_system=autotools libs=shared,static arch=linux-fedora_asahi_remix39-m1
[+]                  ^xz@5.4.1%gcc@11.4.0~pic build_system=autotools libs=shared,static arch=linux-fedora_asahi_remix39-m1
[+]          ^numactl@2.0.14%gcc@11.4.0 build_system=autotools patches=4e1d78c,62fc8a8,ff37630 arch=linux-fedora_asahi_remix39-m1
[e]          ^openssh@9.3p1%gcc@11.4.0+gssapi build_system=autotools arch=linux-fedora_asahi_remix39-m1
[+]          ^pmix@5.0.1%gcc@11.4.0~docs+pmi_backwards_compatibility~python~restful build_system=autotools arch=linux-fedora_asahi_remix39-m1
[+]              ^libevent@2.1.12%gcc@11.4.0+openssl build_system=autotools arch=linux-fedora_asahi_remix39-m1
[+]                  ^openssl@3.1.3%gcc@11.4.0~docs+shared build_system=generic certs=mozilla arch=linux-fedora_asahi_remix39-m1
[-]                      ^ca-certificates-mozilla@2023-05-30%gcc@11.4.0 build_system=generic arch=linux-fedora_asahi_remix39-m1
[+]      ^perl@5.38.0%gcc@11.4.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-fedora_asahi_remix39-m1
[+]          ^berkeley-db@18.1.40%gcc@11.4.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-fedora_asahi_remix39-m1
[+]          ^bzip2@1.0.8%gcc@11.4.0~debug~pic+shared build_system=generic arch=linux-fedora_asahi_remix39-m1
[+]          ^gdbm@1.23%gcc@11.4.0 build_system=autotools arch=linux-fedora_asahi_remix39-m1
[+]      ^readline@8.2%gcc@11.4.0 build_system=autotools patches=bbf97f1 arch=linux-fedora_asahi_remix39-m1
[+]          ^ncurses@6.4%gcc@11.4.0~symlinks+termlib abi=none build_system=autotools arch=linux-fedora_asahi_remix39-m1
[+]      ^zlib-ng@2.1.5%gcc@11.4.0+compat+opt build_system=autotools arch=linux-fedora_asahi_remix39-m1
```

The error is:
```
==> Installing silo-4.10.2-fkjp2f4c67t4fbzcqzdmgipyqgxc4m3x [30/30]
==> No binary for silo-4.10.2-fkjp2f4c67t4fbzcqzdmgipyqgxc4m3x found: installing from source
==> Using cached archive: /home/benwibking/spack/var/spack/cache/_source-cache/archive/3a/3af87e5f0608a69849c00eb7c73b11f8422fa36903dd14610584506e7f68e638.tgz
==> Applied patch /home/benwibking/spack/var/spack/repos/builtin/packages/silo/remove-mpiposix.patch
==> Applied patch /home/benwibking/spack/var/spack/repos/builtin/packages/silo/H5FD_class_t-terminate.patch
==> Applied patch /home/benwibking/spack/var/spack/repos/builtin/packages/silo/H5EPR_SEMI_COLON.patch
==> Applied patch /home/benwibking/spack/var/spack/repos/builtin/packages/silo/configure-AX_CHECK_COMPILE_FLAG.patch
==> Applied patch /home/benwibking/spack/var/spack/repos/builtin/packages/silo/mkinc-usr-bin-env-perl.patch
==> silo: Executing phase: 'autoreconf'
==> silo: Executing phase: 'configure'
==> silo: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j10' 'V=1'

126 errors found in build log:
     20      libtoolize: copying file 'config/lt~obsolete.m4'
     21      libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([config])' to configure.ac,
     22      libtoolize: and rerunning libtoolize and aclocal.
     23      autoreconf: running: /home/benwibking/spack/opt/spack/linux-fedora_asahi_remix39-m1/gcc-11.4.0/autoconf-2.69-befb
             4bdg6nqgtaisxlnruj6m7dkp67ll/bin/autoconf --include=/home/benwibking/spack/opt/spack/linux-fedora_asahi_remix39-m
             1/gcc-11.4.0/autoconf-archive-2023.02.20-odudq7v647kj52hlq7zjkmob7dqtxcza/share/aclocal --include=/home/benwibkin
             g/spack/opt/spack/linux-fedora_asahi_remix39-m1/gcc-11.4.0/libtool-2.4.7-rwnq67d35vnyfdaecvmxhzs2ajb45vom/share/a
             clocal --include=/usr/share/aclocal --force
     24      autoreconf: running: /home/benwibking/spack/opt/spack/linux-fedora_asahi_remix39-m1/gcc-11.4.0/autoconf-2.69-befb
             4bdg6nqgtaisxlnruj6m7dkp67ll/bin/autoheader --include=/home/benwibking/spack/opt/spack/linux-fedora_asahi_remix39
             -m1/gcc-11.4.0/autoconf-archive-2023.02.20-odudq7v647kj52hlq7zjkmob7dqtxcza/share/aclocal --include=/home/benwibk
             ing/spack/opt/spack/linux-fedora_asahi_remix39-m1/gcc-11.4.0/libtool-2.4.7-rwnq67d35vnyfdaecvmxhzs2ajb45vom/share
             /aclocal --include=/usr/share/aclocal --force
     25      autoreconf: running: automake --add-missing --copy --force-missing
  >> 26      configure.ac:367: installing 'config/compile'
  >> 27      configure.ac:170: installing 'config/missing'
     28      src/Makefile.am: installing 'config/depcomp'
     29      tests/Makefile.am:160: warning: variable 'bcastopen_SOURCES' is defined but no program or
  >> 30      tests/Makefile.am:160: library has 'bcastopen' as canonical name (possible typo)
     31      autoreconf: Leaving directory `.'
     32      ==> [2024-01-16-15:24:51.995745] Find (recursive): /var/tmp/benwibking/spack-stage/spack-stage-silo-4.10.2-fkjp2f
             4c67t4fbzcqzdmgipyqgxc4m3x ['config.sub', 'config.guess']
     33      ==> [2024-01-16-15:24:52.001922] Find complete: /var/tmp/benwibking/spack-stage/spack-stage-silo-4.10.2-fkjp2f4c6
             7t4fbzcqzdmgipyqgxc4m3x ['config.sub', 'config.guess']
     34      ==> silo: Executing phase: 'configure'
     35      ==> [2024-01-16-15:24:52.047266] Find (recursive): /var/tmp/benwibking/spack-stage/spack-stage-silo-4.10.2-fkjp2f
       [...]

2024-01-16 20:26 UTC, BenWibking commented
The full build logs are:
[spack-build-env.txt](https://github.com/spack/spack/files/13955411/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/13955412/spack-build-out.txt)

2024-01-16 20:38 UTC, cyrush commented
@markcmiller86  -- build issue with Silo 4.10 w/ spack.  Does this error ring a bell?

Since we usually build 4.10 w/o challenges -- sounds like this may be due to Spack defaults wutg Silo + MPI and HDF5 + MPI, but maybe something else is involved?

2024-01-16 20:44 UTC, markcmiller86 commented
> @markcmiller86 -- build issue with Silo 4.10 w/ spack. Does this error ring a bell?

Yes, but only when Silo 4.10 is used with newer HDF5 libs (HDF5 1.12 and above). 4.11 fixes the issues building Silo with newer HDF5s

> Since we usually build 4.10 w/o challenges -- sounds like this may be due to Spack defaulting to Silo + MPI and HDF5 + MPI, but maybe something else is involved?

Well, we usually build with a much older version of HDF5 though. I think its the *combination* of Silo 4.10 and newer HDF5s that is the problem. There is a semicolon termination issue in HDF5's error checking macros used in Silos block-based virtual file driver code. That got changed in newer versions of HDF5. Also, HDF5's VFD and filter plugin interfaces changed in newer HDF5s...also causing build issue for Silo 4.10. 

If you wanna use >=HDF5 1.12, you need to use Silo >= 4.11

2024-01-17 00:02 UTC, cyrush commented
@markcmiller86  thanks for the info!

2024-01-17 18:30 UTC, cyrush commented
I think the best way to approach this is to set a version constraint for Silo 4.10 to make sure it uses  <1.12 HDF5

2024-01-17 19:47 UTC, BenWibking commented
> I think the best way to approach this is to set a version constraint for Silo 4.10 to make sure it uses <1.12 HDF5

The build error I posted above is for `silo@4.10%gcc@11.4.0 ^hdf5@1.8.23`, so that will not fix the issue that I'm seeing.

2024-01-17 19:52 UTC, cyrush commented
@BenWibking Ok, in that case I think we are stuck in a bad spot with older versions. 

I support your changes to move forward with VisIt.

2024-01-17 19:54 UTC, cyrush approved these changes
I think this is a good practical path forward. 

@alalazo are you ok with this?

We know we can build VisIt with older versions with specific patches and constraints that aren't in spack. However the combos in spack make this very hard to pin down.

2024-01-17 20:00 UTC, markcmiller86 commented
> The build error I posted above is for `silo@4.10%gcc@11.4.0 ^hdf5@1.8.23`, so that will not fix the issue that I'm seeing.

Hmmm...you seem to be saying you were getting those posted Silo compilation errors with a 1.8 HDF5. Is that right? Ok, I went back and looked at that log. I see...

```
==> Applied patch /home/benwibking/spack/var/spack/repos/builtin/packages/silo/remove-mpiposix.patch
==> Applied patch /home/benwibking/spack/var/spack/repos/builtin/packages/silo/H5FD_class_t-terminate.patch
==> Applied patch /home/benwibking/spack/var/spack/repos/builtin/packages/silo/H5EPR_SEMI_COLON.patch
==> Applied patch /home/benwibking/spack/var/spack/repos/builtin/packages/silo/configure-AX_CHECK_COMPILE_FLAG.patch
==> Applied patch /home/benwibking/spack/var/spack/repos/builtin/packages/silo/mkinc-usr-bin-env-perl.patch
```

I worry some of these patches are needed only for newer HDF5's (1.12 and above). You were buildng with 1.8 and those patches appear to have been applied (unless spack issues `Applied` message even though it may have skipped).

2024-01-17 20:03 UTC, markcmiller86 commented
I believe this spack patch logic is incorrect...

https://github.com/spack/spack/blob/69d762ce6a7c38d0e50d569303c52ab821a0071a/var/spack/repos/builtin/packages/silo/package.py#L84

This is applying the patch based on Silo version. It isn't about Silo version. Its about HDF5 version. HDF5 library changed their semi-colon termination of some macros in newer hdf5's and older Silo doesn't know about that. 

I think this is the crux of the issue.

2024-01-17 20:04 UTC, BenWibking commented
> > The build error I posted above is for `silo@4.10%gcc@11.4.0 ^hdf5@1.8.23`, so that will not fix the issue that I'm seeing.
> 
> Hmmm...you seem to be saying you were getting those posted Silo compilation errors with a 1.8 HDF5. Is that right? Ok, I went back and looked at that log. I see...
> 
> ```
> ==> Applied patch /home/benwibking/spack/var/spack/repos/builtin/packages/silo/remove-mpiposix.patch
> ==> Applied patch /home/benwibking/spack/var/spack/repos/builtin/packages/silo/H5FD_class_t-terminate.patch
> ==> Applied patch /home/benwibking/spack/var/spack/repos/builtin/packages/silo/H5EPR_SEMI_COLON.patch
> ==> Applied patch /home/benwibking/spack/var/spack/repos/builtin/packages/silo/configure-AX_CHECK_COMPILE_FLAG.patch
> ==> Applied patch /home/benwibking/spack/var/spack/repos/builtin/packages/silo/mkinc-usr-bin-env-perl.patch
> ```
> 
> I worry some of these patches are needed only for newer HDF5's (1.12 and above). You were buildng with 1.8 and those patches appear to have been applied (unless spack issues `Applied` message even though it may have skipped).

Yes, I used HDF5 1.8 for that build.

That seems to me to be what's going on, based on the comments for these patches listed in the `silo/package.py` file:
https://github.com/spack/spack/blob/69d762ce6a7c38d0e50d569303c52ab821a0071a/var/spack/repos/builtin/packages/silo/package.py#L80

So maybe this can be fixed with HDF5 version restrictions on the Silo patches.

2024-01-17 21:18 UTC, markcmiller86 commented
> So maybe this can be fixed with HDF5 version restrictions on the Silo patches.

Yes, I believe that is correct. The H5FD_class_t-terminate.patch and H5EPR_SEMI_COLON.patch should only be applied to Silo 4.10.X for newer HDF5s. The other patches I think are ok regardless of HDF5 version, I think.

2024-01-29 14:21 UTC, alalazo commented
> So maybe this can be fixed with HDF5 version restrictions on the Silo patches.

Are there updates on :point_up: ?

2024-01-31 20:28 UTC, BenWibking commented
> > So maybe this can be fixed with HDF5 version restrictions on the Silo patches.
> 
> Are there updates on ☝️ ?

I will leave this to the Visit team to fix.

2024-01-31 20:36 UTC, cyrush commented
I am fine with merging this as is if it helps @BenWibking's cases. Not sure when we will be able to sort out the silo issues and get PRs in.

2024-01-31 21:05 UTC, alalazo approved these changes

2024-01-31 21:05 UTC, merged

2024-01-31 22:20 UTC, cyrush commented
thanks!