add py-vl-convert-python
LLNL/spack pull request #42073
Opened 2024-01-14 00:41 UTC by wu-kan

2024-01-17 13:34 UTC, adamjstewart requested changes
Do we also need to add the dependencies from `Cargo.toml` to avoid pip downloading things during the install?

2024-01-17 13:34 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-vl-convert-python/package.py
> +    depends_on("py-maturin", type="build")
```suggestion
    depends_on("py-maturin@1.1:1", type="build")

```

2024-01-20 03:46 UTC, wu-kan commented
I tried, but failed. And I find other packages also suffer from this (e.g., eza, py-tokenizers). Maybe we need a new `download_dependencies` phases in `spack.build_systems.cargo` and `spack.build_systems.python_maturin` …

2024-01-20 03:46 UTC, wu-kan commented
> Do we also need to add the dependencies from `Cargo.toml` to avoid pip downloading things during the install?

I tried, but failed. And I find other packages also suffer from this (e.g., eza, py-tokenizers). Maybe we need a new `download_dependencies` phases in `spack.build_systems.cargo` and `spack.build_systems.python_maturin` …

2024-01-20 03:53 UTC, wu-kan commented
Just for the `py-vl-convert-python` package, another solution is to use bdists (whl) over sdists (tar.gz).

2024-01-21 17:56 UTC, adamjstewart approved these changes, later dismissed

2024-01-21 17:56 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-vl-convert-python/package.py
> +    depends_on("cmake", type="build")  # some rust dependcies need this
```suggestion
    depends_on("cmake", type="build")  # some rust dependencies need this

```

2024-01-29 14:18 UTC, adamjstewart approved these changes

2024-01-29 14:18 UTC, merged