py-nglview: add new package
LLNL/spack pull request #42079
Opened 2024-01-14 15:49 UTC by w8jcik

2024-01-16 19:55 UTC, tldahlgren reviewed
FYI. Confirmed the homepage and version sha256.

2024-01-17 13:29 UTC, adamjstewart requested changes

2024-01-17 13:29 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-nglview/package.py
> +    depends_on("py-jupyter-packaging@0.7", type="build")
```suggestion
    depends_on("py-jupyter-packaging@0.7.9:0.7", type="build")
```

2024-01-17 13:29 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-nglview/package.py
> +    depends_on("py-versioneer", type="build")
```suggestion
    depends_on("py-versioneer-518", type="build")
```

2024-01-17 13:29 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-nglview/package.py
> +    depends_on("py-numpy", type="run")
Should be `type=("build", "run")` in order to get `spack install --test=root` to pass.

2024-01-17 14:02 UTC, w8jcik commented on var/spack/repos/builtin/packages/py-nglview/package.py
> +    depends_on("py-versioneer", type="build")
Sorry, I missed this version.

2024-01-21 16:49 UTC, adamjstewart requested changes

2024-01-21 16:49 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-nglview/package.py
> +    depends_on("py-jupyterlab-widgets", type="run")
bulid/run to get tests to pass

2024-01-21 17:58 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-nglview/package.py
> +    depends_on("py-jupyter-packaging@0.7.9:0.7", type=("build", "run"))
This one should be build-only

2024-01-21 18:33 UTC, w8jcik commented on var/spack/repos/builtin/packages/py-nglview/package.py
> +    depends_on("py-jupyter-packaging@0.7.9:0.7", type=("build", "run"))
Corrected

2024-01-21 18:33 UTC, w8jcik commented on var/spack/repos/builtin/packages/py-nglview/package.py
> +    depends_on("py-jupyterlab-widgets", type="run")
Corrected

2024-01-21 18:34 UTC, w8jcik commented
`spack install --test=root py-nglview` passes now.

2024-01-22 11:39 UTC, adamjstewart approved these changes

2024-01-22 11:39 UTC, merged

2024-01-22 11:42 UTC, d-beltran commented on var/spack/repos/builtin/packages/py-nglview/package.py
> +    depends_on("py-versioneer", type="build")
I am curious. Why did you have to use your own version of py-versioneer instead of the already implemented one?

2024-01-22 11:45 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-nglview/package.py
> +    depends_on("py-versioneer", type="build")
Because https://pypi.org/project/versioneer/ and https://pypi.org/project/versioneer-518/ are different projects