COUNTDOWN package
LLNL/spack pull request #42123
Opened 2024-01-17 17:09 UTC by danielecesarini

A SPACK recipe for COUNTDOWN project

2024-01-17 19:03 UTC, tldahlgren requested changes
Confirmed the homepage and version sha256; `spack spec` succeeds.  Please fix the `maintainers` syntax and remove the redundant variants.  The rest of the feedback is optional.

2024-01-17 19:03 UTC, tldahlgren commented on var/spack/repos/builtin/packages/countdown/package.py
> +    maintainers = ['f-tesser', 'danielecesarini']
We no longer use this syntax.  Please use the `maintainers` directive (see https://spack.readthedocs.io/en/latest/packaging_guide.html#maintainers).

2024-01-17 19:03 UTC, tldahlgren commented on var/spack/repos/builtin/packages/countdown/package.py
> +    variant("cuda", default=False, description="Build with CUDA")
This variant is already available since it is inherited from `CudaPackage`.

2024-01-17 19:03 UTC, tldahlgren commented on var/spack/repos/builtin/packages/countdown/package.py
> +    depends_on("cuda", when="+cuda")
This dependency is also inherited from `CudaPackage`.

2024-01-17 19:03 UTC, tldahlgren commented on var/spack/repos/builtin/packages/countdown/package.py
> +    variant("cpufreq_manual_set", default=True, description="Manual set of cpufreq interface")
It *might* be easier to maintain this package if the variants are listed in alphabetical order by name.

2024-01-17 19:03 UTC, tldahlgren commented on var/spack/repos/builtin/packages/countdown/package.py
> +                        "except for initialization and finalization")
These variant options, especially the `exc_all_mpi` variant, imply you might want to consider adding `conflict` directives so Spack can quickly report unsupported combinations.  See the docs at https://spack.readthedocs.io/en/latest/packaging_guide.html#conflicts-and-requirements.

2024-01-18 11:21 UTC, danielecesarini commented on var/spack/repos/builtin/packages/countdown/package.py
> +    maintainers = ['f-tesser', 'danielecesarini']
@d810de8

2024-01-18 11:23 UTC, danielecesarini commented on var/spack/repos/builtin/packages/countdown/package.py
> +    variant("cuda", default=False, description="Build with CUDA")
[e7451ed](https://github.com/spack/spack/pull/42123/commits/e7451ed8b033f86b649bdcdf31348a64c4743d1f)

2024-01-18 11:23 UTC, danielecesarini commented on var/spack/repos/builtin/packages/countdown/package.py
> +    depends_on("cuda", when="+cuda")
[e7451ed](https://github.com/spack/spack/pull/42123/commits/e7451ed8b033f86b649bdcdf31348a64c4743d1f)

2024-01-18 11:23 UTC, danielecesarini commented on var/spack/repos/builtin/packages/countdown/package.py
> +    variant("cpufreq_manual_set", default=True, description="Manual set of cpufreq interface")
[e7451ed](https://github.com/spack/spack/pull/42123/commits/e7451ed8b033f86b649bdcdf31348a64c4743d1f)

2024-01-18 11:23 UTC, danielecesarini commented on var/spack/repos/builtin/packages/countdown/package.py
> +                        "except for initialization and finalization")
[c48399e](https://github.com/spack/spack/pull/42123/commits/c48399e42031004cfe279e8d9bdded3002f61380)

2024-01-18 12:55 UTC, danielecesarini commented
I don't know how to fix: 

_black found errors_

2024-01-18 16:45 UTC, tldahlgren commented
> I don't know how to fix:
> 
> _black found errors_

You should be able to run the command below:

@spackbot fix style

2024-01-25 21:50 UTC, danielecesarini reviewed
Looks good to me.

2024-01-25 21:56 UTC, tldahlgren approved these changes

2024-01-25 21:56 UTC, merged