Update environments.rst
LLNL/spack pull request #42184
Opened 2024-01-19 12:17 UTC by aphecetche

I believe the current syntax in the doc is incorrect. At least it's not working for me...

2024-01-29 13:58 UTC, alalazo requested changes

2024-01-29 13:58 UTC, alalazo commented on lib/spack/docs/environments.rst
> +         when: arch.satisfies('x86_64:')
Hmm, this seems to be a wrong fix. What was failing in your case, when following the example?

2024-01-29 22:12 UTC, aphecetche commented on lib/spack/docs/environments.rst
> +         when: arch.satisfies('x86_64:')
to be fair, the error was not strictly in following the example, but trying to get the same package complete spec be different on different platforms : 

```
📦spack-tutorial.../spack-tutorial/errors [spack-tutorial] $ cat -p spack.yaml
spack:
  definitions:
  - root_spec: [root +x +opengl +http +pythia6 +spectrum generator=ninja cxxstd=17]
  - when: arch.satisfies('platform=linux')
  - root_spec: [root +aqua ~x ~tbb +opengl +http +pythia6 +spectrum generator=ninja cxxstd=17]
  - when: arch.satisfies('platform=darwin')
  specs:
  - $root_spec
  concretizer:
    unify: true
📦spack-tutorial.../spack-tutorial/errors [spack-tutorial] $ spack env activate .
==> Error:
```

```
📦ok...iles/spack-tutorial/ok [spack-tutorial] $ cat -p spack.yaml
spack:
  definitions:
  - root_spec: [root +x +opengl +http +pythia6 +spectrum generator=ninja cxxstd=17]
    when: arch.satisfies('platform=linux')
  - root_spec: [root +aqua ~x ~tbb +opengl +http +pythia6 +spectrum generator=ninja cxxstd=17]
    when: arch.satisfies('platform=darwin')
  specs:
  - $root_spec
  concretizer:
    unify: true
📦ok...iles/spack-tutorial/ok [spack-tutorial] $ spack env activate .
(no error here)
```

2024-01-30 08:02 UTC, alalazo commented on lib/spack/docs/environments.rst
> +         when: arch.satisfies('x86_64:')
I agree, but that is exactly my point. The first time you wrote it wrong, i.e. you have a YAML list with 4 items (and some items have just the `when` attribute, which makes them wrong):
```yaml
definitions:
  - root_spec: [root +x +opengl +http +pythia6 +spectrum generator=ninja cxxstd=17]
  - when: arch.satisfies('platform=linux')
  - root_spec: [root +aqua ~x ~tbb +opengl +http +pythia6 +spectrum generator=ninja cxxstd=17]
  - when: arch.satisfies('platform=darwin')
```
The second time you wrote it like in the docs and it works (only 2 items):
```yaml
definitions:
  - root_spec: [root +x +opengl +http +pythia6 +spectrum generator=ninja cxxstd=17]
    when: arch.satisfies('platform=linux')
  - root_spec: [root +aqua ~x ~tbb +opengl +http +pythia6 +spectrum generator=ninja cxxstd=17]
    when: arch.satisfies('platform=darwin')
```
So, in this PR you're introducing a typo :slightly_smiling_face:

2024-01-30 09:52 UTC, aphecetche commented on lib/spack/docs/environments.rst
> +         when: arch.satisfies('x86_64:')
hum. I'm confused. this PR is removing a `-`, not adding it, isn't it ? I must be missing something. The `when` is applying to the item above it, or below it ? 
In the doc https://spack.readthedocs.io/en/latest/environments.html  

<img width="730" alt="Capture d’écran 2024-01-30 à 10 48 47" src="https://github.com/spack/spack/assets/1566009/36306105-697d-4c4b-9ab0-d069e533be9e">

2024-01-30 09:59 UTC, alalazo commented on lib/spack/docs/environments.rst
> +         when: arch.satisfies('x86_64:')
The `when` in the doc is in the same YAML object as the `compilers` below it. Note that here we are discussing YAML parsing, not anything that is Spack specific.

2024-01-30 11:22 UTC, aphecetche commented on lib/spack/docs/environments.rst
> +         when: arch.satisfies('x86_64:')
ok, so it was just me confused by YAML. Thanks for the explanations. Closing this PR then.

2024-01-30 11:22 UTC, closed without merging