gobject-introspection: fine-grained glib dependency versions. add 1.79.1
LLNL/spack pull request #42222
Opened 2024-01-22 20:39 UTC by koysean

gobject-introspection's glib dependency seems to require matching minor versions: https://gitlab.gnome.org/GNOME/gobject-introspection/-/blob/main/meson.build?ref_type=heads#L131-138

I don't know a good way to programatically do this so I explicitly added fine-grained glib dependencies.

I also updated both glib and gobject-introspection to their most recent release versions, 2.79.1 and 1.79.1, respectively.

2024-01-22 20:59 UTC, michaelkuhn requested changes

2024-01-22 20:59 UTC, michaelkuhn commented on var/spack/repos/builtin/packages/glib/package.py
> +    version("2.79.1", sha256="b3764dd6e29b664085921dd4dd6ba2430fc19760ab6857ecfa3ebd4e8c1d114c")
This is not a release version but a development version. If there isn't an urgent reason to add this, we should skip it.

2024-01-22 20:59 UTC, michaelkuhn commented on var/spack/repos/builtin/packages/gobject-introspection/package.py
> +    version("1.79.1", sha256="f80ea33ee05ca48fb997952bb46131cfbdd3751f7f5da068888739cbeb2d5443")
I guess the same is true for gobject-introspection's development versions.

2024-01-22 20:59 UTC, michaelkuhn commented on var/spack/repos/builtin/packages/gobject-introspection/package.py
> +
These should be sorted like versions, that is, newest first. Also, do they have to be strict (`depends_on("glib@2.76", when="@1.76")`) or are newer glib versions ok?

2024-01-22 22:29 UTC, koysean commented
@michaelkuhn thanks for catching the development version. I've removed 1.79.1 and added 1.78.1 instead.

The meson.build sets the requirement for glib version `>=` the gobject-introspection version:
`glib_version = '>=2.@0@.@1@'.format(gi_versions[1], glib_micro_version)`

2024-01-23 21:04 UTC, michaelkuhn approved these changes
LGTM, thanks!

2024-01-23 21:05 UTC, merged