siesta-relmax3: Added siesta-relmax3 package
LLNL/spack pull request #42239
Opened 2024-01-23 10:08 UTC by kinagaki-fj

We added siesta relmax3 branch as a separate package because the dependent libraries and build procedure are very different from the mainstream.

2024-01-29 11:41 UTC, alalazo requested changes

2024-01-29 11:41 UTC, alalazo commented on var/spack/repos/builtin/packages/siesta-relmax3/package.py
> +    patch("fj_mod.patch")
Can you add a brief comment above the `patch` directive explaining:
1. What is the effect of the patch
2. Why it is needed
3. Where it was taken from

?

2024-01-29 11:41 UTC, alalazo commented on var/spack/repos/builtin/packages/siesta-relmax3/package.py
> +    the new optimizations and enhancements, and provide feedback on them.
Why a new package for a branch of a package we already have?

2025-06-06 12:05 UTC, haampie commented
Hi @kinagaki-fj, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2026-01-04 01:52 UTC, closed without merging