Bugfix: fix sticky variants in externals
LLNL/spack pull request #42253
Opened 2024-01-23 21:57 UTC by becker33

Fixes #42172

Currently, the concretizer does not preserve information about which variants were set explicitly on externals, which leads to concretization failures when an external specifies a sticky variant. This PR fixes the generation of facts for externals to preserve that information.

Includes regression test.

2024-01-23 22:07 UTC, becker33 commented
@spackbot fix style

2024-01-24 05:49 UTC, alalazo requested changes
Basically LGTM

2024-01-24 05:49 UTC, alalazo commented on lib/spack/spack/test/concretize.py
> +    def test_sticky_variant_in_external(self):
```suggestion
    @pytest.mark.regression("42172")
    def test_sticky_variant_in_external(self):
        """Tests that we can set sticky variants from an external spec."""
```

2024-01-24 05:49 UTC, alalazo commented on lib/spack/spack/test/concretize.py
> +    def test_sticky_variant_in_external(self):
Also, can we test setting the sticky variant both ways + not having it?

2024-01-24 23:43 UTC, becker33 commented
@spackbot fix style

2024-01-25 16:22 UTC, alalazo approved these changes

2024-01-25 16:22 UTC, merged