sfcgal: Add new versions and restrict versions of cgal dependency
LLNL/spack pull request #42278
Opened 2024-01-24 23:26 UTC by payerle

Added new versions @1.5.1 and @1.4.1 (sfcgal moved from github to gitlab)

Placed restrictions on what versions of cgal are supported for different cfcgal versions.  These restrictions are based on what was found in the version history at https://gitlab.com/sfcgal/SFCGAL/-/blob/v1.5.1/NEWS?ref_type=tags as well as the CMakeLists.txt for different versions.

@1.4 and @1.5 seem to require a specific version of cgal based on CMakeLists.txt

Earlier versions (@1.3.8:1.3.10) claim to support cgal@4.3: (but Spack recipe claims did not work until @4.7, so sticking with that as minimum).  CMakeList.txt suggests they support cgal@5 as well, but version history suggests otherwise. (I had issues building sfcgal@1.3.8 ^cgal@5.4 which looked like sfcgal did not support changes in cgal).

This might at least parially fix #41712

2024-01-29 09:56 UTC, alalazo requested changes
```
sfcgal: dependency on cgal@5.3 cannot be satisfied by known versions of cgal
    happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/sfcgal/package.py
    known versions of cgal are 5.5.2, 5.4.1, 5.1.5, 5.0.3, 5.0, 4.13, 4.12, 4.11, 4.9.1, 4.9, 4.7, 4.6.3
sfcgal: dependency on cgal@5.6 cannot be satisfied by known versions of cgal
    happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/sfcgal/package.py
    known versions of cgal are 5.5.2, 5.4.1, 5.1.5, 5.0.3, 5.0, 4.13, 4.12, 4.11, 4.9.1, 4.9, 4.7, 4.6.3
```

2024-01-29 09:56 UTC, alalazo commented
Besides that LGTM

2024-01-30 19:35 UTC, payerle commented
@alalazo
Sorry re the missing cgal versions; I was submitting several PRs and thought I submitted that one as well.  Just submitted now
(#42378)

2024-02-05 11:12 UTC, alalazo approved these changes

2024-03-08 06:08 UTC, merged