Add Maphyspp package and two dependencies : fabulous and paddle.
LLNL/spack pull request #42287
Opened 2024-01-25 16:51 UTC by fpruvost

See https://gitlab.inria.fr/solverstack/maphys/maphyspp

2024-01-25 18:57 UTC, tldahlgren reviewed
Confirmed the homepages, branches, and version directive's sha256s.

2024-01-25 18:57 UTC, tldahlgren commented on var/spack/repos/builtin/packages/fabulous/package.py
> +    depends_on("pkg-config", type='build')
Is this a hard dependency on `pkg-config` or would the `pkgconfig` virtual work too (so `pkgconf` could be picked up when appropriate)?

2024-01-25 18:57 UTC, tldahlgren commented on var/spack/repos/builtin/packages/fabulous/package.py
> +# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
Optional:  Would prefer the copyright end dat of `2024` in these packages but the checks will allow 2023 for the time being.

2024-01-25 18:57 UTC, tldahlgren commented on var/spack/repos/builtin/packages/maphyspp/package.py
> +    #variant("mumps", default=False, description="Compile examples and tests using mumps (sparse direct solver)") #FIXME
Do you plan to fix these commented out variants before or after the merge?  (Style checks will likely complain about the lack of a space after the comment marks.)

2024-01-25 18:57 UTC, tldahlgren commented on var/spack/repos/builtin/packages/fabulous/package.py
> +        ])
There are helper methods you can use for `CMakePackage`s, such as `self.define_from_variant()` (see the docs at https://spack.readthedocs.io/en/latest/build_systems/cmakepackage.html#adding-flags-to-cmake).

2024-01-25 18:59 UTC, tldahlgren commented on var/spack/repos/builtin/packages/fabulous/package.py
> +            "-DCMAKE_BUILD_TYPE=%s"    % ('Debug'  if '+debug'    in spec else 'Release'),
I'm not seeing a `debug` variant in this package.

2024-01-25 19:01 UTC, tldahlgren commented on var/spack/repos/builtin/packages/fabulous/package.py
> +            "-DCMAKE_BUILD_TYPE=%s"    % ('Debug'  if '+debug'    in spec else 'Release'),
Should this be coming from the `build_type`, where the options are:

```
$ spack info fabulous
...
    when build_system=cmake
      build_type [Release]      Debug, MinSizeRel, RelWithDebInfo, Release
          CMake build type
...
```

2024-01-25 19:06 UTC, tldahlgren commented on var/spack/repos/builtin/packages/paddle/package.py
> +            "-DPADDLE_ORDERING_PARMETIS=%s" % ('ON'    if '+parmets' in spec else 'OFF')
Typo, but I do recommend using the helper method for this.

```suggestion
            "-DPADDLE_ORDERING_PARMETIS=%s" % ('ON'    if '+parmetis' in spec else 'OFF')
```

2024-01-25 19:08 UTC, tldahlgren commented on var/spack/repos/builtin/packages/fabulous/package.py
> +            "-DCMAKE_BUILD_TYPE=%s"    % ('Debug'  if '+debug'    in spec else 'Release'),
You might want to constrain the build types if you only support `Debug` and `Release`.

2024-01-25 19:10 UTC, tldahlgren requested changes
Going to switch to request changes since a typo needs to be fixed at a minimum.

2024-01-25 19:15 UTC, tldahlgren commented
Note I also checked `spack spec maphyspp` and it succeeded.

2024-01-26 13:36 UTC, fpruvost commented
Hi, thanks for your review. 
I pushed a new version, in a single commit, trying to clean a maximum.
I see there are some style errors in the ci, should I submit a new version with black / spack style polishes ?

2024-01-26 13:39 UTC, fpruvost commented
Ok done, I pushed a new version with black applied.

2024-01-26 22:59 UTC, tldahlgren reviewed
LGTM.  

I suspect I forgot to mentioned the convention for listing branch version directives before numbered ones.  You can see an example at https://spack.readthedocs.io/en/latest/packaging_guide.html#fetching-from-code-repositories.

I'm okay with merging this PR as is if you would prefer to defer the change to another PR.  Just let me know.

2024-01-29 09:25 UTC, fpruvost commented
> I'm okay with merging this PR as is if you would prefer to defer the change to another PR. Just let me know.

Ok done, I pushed an updated version with branch version before numbered ones.

2024-01-29 18:06 UTC, tldahlgren approved these changes
Thanks for the updates!

2024-01-29 18:06 UTC, merged