py-textual: Added package py-textual
LLNL/spack pull request #42291
Opened 2024-01-25 20:07 UTC by alex391

2024-01-25 21:40 UTC, tldahlgren reviewed
FYI. Confirmed the homepage and version sha256.

2024-01-29 15:34 UTC, adamjstewart requested changes

2024-01-29 15:34 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-textual/package.py
> +
Needs:
```python
depends_on("python@3.8:3", type=("build", "run"))
```

2024-01-29 15:35 UTC, adamjstewart requested changes

2024-01-29 15:35 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-textual/package.py
> +    depends_on("py-markdown-it-py+linkify@2.1.0:", type=("build", "run"))
```suggestion
    depends_on("py-markdown-it-py+plugins+linkify@2.1.0:", type=("build", "run"))
```

2024-01-29 15:35 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-textual/package.py
> +    depends_on("py-mdit-py-plugins", type=("build", "run"))
Where do you see this dependency?

2024-01-29 16:29 UTC, alex391 commented on var/spack/repos/builtin/packages/py-textual/package.py
> +    depends_on("py-markdown-it-py+linkify@2.1.0:", type=("build", "run"))
The `+plugins` variant doesn't exist for py-markdown-it-py because it would introduce a circular dependency, which is why I have `depends_on("py-mdit-py-plugins", type=("build", "run"))` instead. Is there a better way to do that?

2024-01-29 16:31 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-textual/package.py
> +    depends_on("py-markdown-it-py+linkify@2.1.0:", type=("build", "run"))
Ah, interesting. I think your solution is fine. Just add a comment explaining this. @alalazo FYI another circular dependency issue with deps that are only needed at run-time.

2024-01-30 09:19 UTC, adamjstewart approved these changes

2024-01-30 09:19 UTC, merged