flook: add new package
LLNL/spack pull request #42302
Opened 2024-01-26 01:43 UTC by kinagaki-fj

2024-02-15 04:52 UTC, kinagaki-fj commented
@alalazo Thank you for all your reviews. I hope you will take a look at this one as well.

2024-02-19 09:11 UTC, alalazo requested changes
This doesn't build for me on:
* **Spack:** 0.22.0.dev0 (fd30ecb3265341660ccdf9cd3a83b3713e7cfe44)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

```console
[ ... ]
[+] /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu20.04-icelake/gcc-13.2.0/gmake-4.4.1-5wsrp5v5dux7n2u6uqlufskeoloz2nl2
==> Installing flook-0.8.1-jn3b5vstngdmfy4mnaqzm4umhmt2fycw [3/3]
==> No binary for flook-0.8.1-jn3b5vstngdmfy4mnaqzm4umhmt2fycw found: installing from source
==> No patches needed for flook
==> flook: Executing phase: 'edit'
==> flook: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8' 'liball'

6 errors found in build log:
     82     /home/culpo/PycharmProjects/spack/lib/spack/env/gcc/gcc -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o lutf8lib.o lutf8lib.c
     83     /home/culpo/PycharmProjects/spack/lib/spack/env/gcc/gcc -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o loadlib.o loadlib.c
     84     /home/culpo/PycharmProjects/spack/lib/spack/env/gcc/gcc -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o linit.o linit.c
     85     /home/culpo/PycharmProjects/spack/lib/spack/env/gcc/gcc -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o lua.o lua.c
     86     /home/culpo/PycharmProjects/spack/lib/spack/env/gcc/gcc -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o luac.o luac.c
     87     /home/culpo/PycharmProjects/spack/lib/spack/env/gcc/gfortran -c -o aot_fun_module.o -g -Iexternal/lua-5.3.5/src ../.././aotus/source/aot_fun_module.f90
  >> 88     lua.c:82:10: fatal error: readline/readline.h: No such file or directory
     89        82 | #include <readline/readline.h>
     90           |          ^~~~~~~~~~~~~~~~~~~~~
     91     compilation terminated.
  >> 92     make[4]: *** [<builtin>: lua.o] Error 1
     93     make[4]: *** Waiting for unfinished jobs....
     94     /home/culpo/PycharmProjects/spack/lib/spack/env/gcc/gfortran -c -o aotus_module.o -g -Iexternal/lua-5.3.5/src ../.././aotus/source/aotus_module.f90
     95     /home/culpo/PycharmProjects/spack/lib/spack/env/gcc/gfortran -c -o aot_path_module.o -g -Iexternal/lua-5.3.5/src ../.././aotus/source/aot_path_module.f90
     96     make[4]: Leaving directory '/tmp/culpo/spack-stage/spack-stage-flook-0.8.1-jn3b5vstngdmfy4mnaqzm4umhmt2fycw/spack-src/aotus/obj/external/lua-5.3.5/src'
  >> 97     make[3]: *** [Makefile:110: linux] Error 2
     98     make[3]: Leaving directory '/tmp/culpo/spack-stage/spack-stage-flook-0.8.1-jn3b5vstngdmfy4mnaqzm4umhmt2fycw/spack-src/aotus/obj/external/lua-5.3.5/src'
  >> 99     make[2]: *** [Makefile:55: linux] Error 2
     100    make[2]: Leaving directory '/tmp/culpo/spack-stage/spack-stage-flook-0.8.1-jn3b5vstngdmfy4mnaqzm4umhmt2fycw/spack-src/aotus/obj/external/lua-5.3.5'
  >> 101    make[1]: *** [../.././aotus/Makefile.smeka:68: lua-lib] Error 2
     102    make[1]: Leaving directory '/tmp/culpo/spack-stage/spack-stage-flook-0.8.1-jn3b5vstngdmfy4mnaqzm4umhmt2fycw/spack-src/aotus/obj'
  >> 103    make: *** [Makefile:67: lib-aotus] Error 2

See build log for details:
  /tmp/culpo/spack-stage/spack-stage-flook-0.8.1-jn3b5vstngdmfy4mnaqzm4umhmt2fycw/spack-build-out.txt

==> Updating view at /tmp/spack-hdmqiz3b/.spack-env/view
```

2025-04-18 08:19 UTC, alalazo commented
@kinagaki-fj Are you still interested in this, or should we close the PR?

2025-06-06 12:05 UTC, haampie commented
Hi @kinagaki-fj, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2025-06-15 14:54 UTC, alalazo commented
Closing, since we moved the package repository. Feel free to reopen at / migrate to https://github.com/spack/spack-packages if you want to continue work on this.

2025-06-15 14:54 UTC, closed without merging