Environments: add global config scope test for definitions
LLNL/spack pull request #42332
Opened 2024-01-27 02:00 UTC by tldahlgren

This PR adds a unit test comparing the old (pre-#33960) way of accessing environment definitions (only through the manifest) to the new way (through global configuration and only *after* the environment is activated).

2024-01-29 09:00 UTC, alalazo requested changes
I tried to checkout a version before #42058 and cherry-pick this test:
```console
$ git checkout 2af6597248a7fab88e5893767ca2a5f850803f85
$ git cherry-pick f6b2ff7de6bcd8237ed36c75f4df04dc17fd124a
$ git cherry-pick 032b13d3fd62eb68f561610bdc43c852c55e7032
```
The test is still passing, so this doesn't seem to be a regression test:
```
$ spack unit-test lib/spack/spack/test/env.py::test_env_defs_as_globals
============================================================================================================================== test session starts ==============================================================================================================================
platform linux -- Python 3.11.5, pytest-8.0.0, pluggy-1.4.0
rootdir: /home/culpo/PycharmProjects/spack
configfile: pytest.ini
plugins: xdist-3.5.0
collected 1 item                                                                                                                                                                                                                                                                

lib/spack/spack/test/env.py .                                                                                                                                                                                                                                             [100%]

============================================================================================================================= slowest 30 durations ==============================================================================================================================
0.04s teardown lib/spack/spack/test/env.py::test_env_defs_as_globals
0.02s call     lib/spack/spack/test/env.py::test_env_defs_as_globals
0.02s setup    lib/spack/spack/test/env.py::test_env_defs_as_globals
=============================================================================================================================== 1 passed in 0.13s ===============================================================================================================================
```

2024-01-29 09:02 UTC, alalazo commented
My guess is that, to make it a regression, the definitions must be included in the spack.yaml

2024-01-29 17:43 UTC, tldahlgren commented
> My guess is that, to make it a regression, the definitions must be included in the spack.yaml

That *and* to not have the approach taken in #33960 that depends on both the global configuration and the environment to get all of the required definitions.

2024-01-29 17:46 UTC, tldahlgren commented
> > My guess is that, to make it a regression, the definitions must be included in the spack.yaml
> 
> That _and_ to not have the approach taken in #33960 that depends on both the global configuration and the environment to get all of the required definitions.

That is assuming the goal is to get something that actually fails without the preferred approach.

2024-01-29 18:18 UTC, alalazo commented
> That is assuming the goal is to get something that actually fails without the preferred approach.

Not sure I get what you mean above... was #42058 a "fix" as the title suggest, or just a refactoring of something that was already fixed?

2024-01-29 18:27 UTC, tldahlgren commented
> > That is assuming the goal is to get something that actually fails without the preferred approach.
> 
> Not sure I get what you mean above... was #42058 a "fix" as the title suggests, or just a refactoring of something that was already fixed?

I just changed the title of that PR to hopefully be clearer.  

There was concern about the two-phased approach to get the `definitions` information that was briefly discussed in one of the core meetings.  That approach also had to be used in #40400 to get the `views` information.  It was decided to go back and change the handling of environment configuration information so that it is all available in the global scope instead.

2024-04-19 17:06 UTC, tldahlgren commented
Doesn't sound like this PR is capable of addressing the issue or I suppose adds value to the unit test suite.

2024-04-19 17:06 UTC, closed without merging