racon: new official repository (+ new versions)
LLNL/spack pull request #42411
Opened 2024-01-31 21:41 UTC by dguibert

2024-02-01 07:05 UTC, dguibert commented
@spackbot fix style

2024-02-28 17:51 UTC, tldahlgren requested changes
Confirmed all of the affected version sha256s.  Please move the new method to after all of the directives.

2024-02-28 17:51 UTC, tldahlgren commented on var/spack/repos/builtin/packages/racon/package.py
> +        return f"https://github.com/lbcb-sci/racon/archive/refs/tags/{version}.tar.gz"
Please move this method down.  The convention (for maintainability) is for methods to be implemented below all of the directives.  In this case that would put it around line 85.

2025-06-06 12:05 UTC, haampie commented
Hi @dguibert, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2025-06-06 12:58 UTC, closed without merging