py-charm4py: needs Cython<3.0
LLNL/spack pull request #42491
Opened 2024-02-05 13:01 UTC by tvandera

Charm4py does not work with Cython 3.x. See this [commit](https://github.com/UIUC-PPL/charm4py/commit/3587469674d2904053b35d3c62c7e09c579ab2c1) in [UUIC-PPL/charm4py](https://github.com/UIUC-PPL/charm4py).

2024-02-05 15:41 UTC, payerle commented
Looks good to me

2024-02-11 20:32 UTC, adamjstewart requested changes

2024-02-11 20:32 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-charm4py/package.py
> +    depends_on("py-cython@:3.0.0", type="build")
```suggestion
    depends_on("py-cython@:2", type="build")
```
Version ranges are inclusive in Spack

2024-02-17 20:16 UTC, adamjstewart approved these changes

2024-02-17 20:16 UTC, merged