new builtin package: py-biobb-gromacs
LLNL/spack pull request #42579
Opened 2024-02-08 11:03 UTC by d-beltran

2024-02-11 20:59 UTC, adamjstewart requested changes

2024-02-11 20:59 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-biobb-gromacs/package.py
> +    depends_on("py-biobb-common", type=("run"))
```suggestion
    depends_on("py-biobb-common@4.1.0", type=("build", "run"))
```

2024-02-11 20:59 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-biobb-gromacs/package.py
> +    # Dependencies
Missing build dep on setuptools

2024-02-12 09:21 UTC, d-beltran commented on var/spack/repos/builtin/packages/py-biobb-gromacs/package.py
> +    # Dependencies
done

2024-02-13 16:03 UTC, adamjstewart approved these changes

2024-02-13 16:03 UTC, merged