Add package zfit
LLNL/spack pull request #42667
Opened 2024-02-14 01:42 UTC by jonas-eschle

As requested by users, adding zfit to the spack repo.

Needs

2024-02-14 01:44 UTC, jonas-eschle commented
@spackbot help

2024-02-14 01:46 UTC, jonas-eschle commented
@spackbot fix style

2024-02-29 22:16 UTC, jonas-eschle commented
@adamjstewart tagging for review, as you've just merged similar libraries, you probably have a good expertise in this area

2024-02-29 22:20 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-zfit/package.py
> +    runtype = (
Much easier to use:
```python
with default_args(type=("build", "run")):
    depends_on("py-tensorflow@2.13", when="@0.15:0.17")
    ...
```

2024-03-02 00:49 UTC, jonas-eschle commented on var/spack/repos/builtin/packages/py-zfit/package.py
> +    runtype = (
Neat, refactored, thanks!

2024-03-02 04:36 UTC, jonas-eschle commented
Ready from my side, thanks for all the hard work your putting in with merging and maintaining @adamjstewart , it's highly appreciated!

2024-03-02 13:29 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-zfit/package.py
> +    ):  # TODO: remove "build" once fixed in spack that tests need "run", not "build"
If you put this comment on a different line you won't have to wrap the code on 3 lines

2024-03-02 13:34 UTC, adamjstewart requested changes

2024-03-02 13:34 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-zfit/package.py
> +    depends_on("py-setuptools", type="build")
Missing deps:
```toml
[build-system]
requires = [
    "setuptools>=42",
    "setuptools_scm[toml]>=3.4",
    "setuptools_scm_git_archive",
    "wheel"
]
```
You don't need wheel, it's already added by the base class.

2024-03-02 13:34 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-zfit/package.py
> +    depends_on("python@3.9:", type=("build", "run"))
```suggestion
    depends_on("python@3.8:3.11", type=("build", "run"))
```

2024-03-02 13:34 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-zfit/package.py
> +        depends_on("py-pydantic@1")
```suggestion
        depends_on("py-pydantic@:1")
```

2024-03-02 13:34 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-zfit/package.py
> +
Missing dep on py-attrs

2024-03-02 13:34 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-zfit/package.py
> +        depends_on("py-texttable")
Missing py-typing-extensions

2024-03-02 13:34 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-zfit/package.py
> +        depends_on("py-tensorflow-probability@0.20:0.21", when="@0.15:0.16")
0.15 is covered in two separate sections. Which one is correct?

2024-03-03 20:32 UTC, jonas-eschle commented
Fixed, refactored and styled, all should be fine now

2024-03-08 12:41 UTC, adamjstewart requested changes

2024-03-08 12:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-zfit/package.py
> +    depends_on("py-setuptools", type="build")
```suggestion
    depends_on("py-setuptools@42:", type="build")
```

2024-03-08 12:41 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-zfit/package.py
> +    depends_on("py-setuptools-scm@3.4:", type="build")
```suggestion
    depends_on("py-setuptools-scm@3.4:+toml", type="build")
```

2024-03-08 17:30 UTC, adamjstewart approved these changes

2024-03-08 18:04 UTC, merged