py-google-cloud-...: add new versions and few new packages
LLNL/spack pull request #42671
Opened 2024-02-14 03:20 UTC by w8jcik

Needed by `googlebatch` plugin of Snakemake 8.

2024-02-17 21:00 UTC, adamjstewart requested changes

2024-02-17 21:00 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-google-api-core/package.py
> +            depends_on("py-grpcio@1.33.2:1")
These all need `type="run"`, same below

2024-02-17 21:00 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-google-cloud-storage/package.py
> +        depends_on("py-google-crc32c", type=("build", "run"), when="@2.12:")
```suggestion
        depends_on("py-google-crc32c@1", type=("build", "run"), when="@2.12:")
```

2024-02-17 21:00 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-google-resumable-media/package.py
google-crc32c now has an upper bound

2024-02-17 21:00 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-grpcio-status/package.py
> +    version("1.52.0", sha256="602a3808d485a1b69e11d150a075e3e927f647f3a8b387ee3c3f01633445b2fc")
This release was yanked, I don't think we should add this version: https://github.com/grpc/grpc/issues/32306

2024-02-18 03:52 UTC, w8jcik commented on var/spack/repos/builtin/packages/py-grpcio-status/package.py
> +    version("1.52.0", sha256="602a3808d485a1b69e11d150a075e3e927f647f3a8b387ee3c3f01633445b2fc")
Replaced with newer version.

2024-02-18 04:00 UTC, w8jcik commented on var/spack/repos/builtin/packages/py-google-resumable-media/package.py
Added upper bound

2024-02-18 04:09 UTC, w8jcik commented on var/spack/repos/builtin/packages/py-google-api-core/package.py
> +            depends_on("py-grpcio@1.33.2:1")
Added

2024-02-18 09:14 UTC, adamjstewart approved these changes

2024-02-18 09:15 UTC, merged