add package py-jacobi
LLNL/spack pull request #42672
Opened 2024-02-14 03:43 UTC by jonas-eschle

Add the package py-jacobi

2024-02-14 03:54 UTC, jonas-eschle commented
@spackbot fix style

2024-02-14 04:13 UTC, jonas-eschle commented
Ready from my side

2024-02-17 20:39 UTC, adamjstewart requested changes

2024-02-17 20:39 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-jacobi/package.py
> +    depends_on("py-numpy", type="run")
```suggestion
    depends_on("py-setuptools@42:", type="build")
    depends_on("py-setuptools-scm@3.4:+toml", type="build")
    depends_on("py-numpy", type=("build", "run"))
```

2024-02-18 00:51 UTC, jonas-eschle commented
Thanks for the fix, that is indeed the right dependency with setuptools-scm

2024-02-18 09:17 UTC, adamjstewart approved these changes

2024-02-18 09:17 UTC, merged