Allow awscli-v2 to be installed without examples/ dir
LLNL/spack pull request #42773
Opened 2024-02-21 00:47 UTC by AlexanderRichert-NOAA

This PR adds a variant to awscli-v2 that uninstalls the examples/ directory, which contains 5-6k files that probably many users don't need (though the default is the current behavior, i.e., retaining it). Unfortunately I can't find a clean way to do this through installer options.

2024-02-21 01:49 UTC, AlexanderRichert-NOAA commented
@spackbot fix style

2024-02-21 03:35 UTC, climbfuji approved these changes
I didn't test it, but the code looks right to me and I support being able to remove those 5000-ish files. Thanks!

2024-02-23 11:45 UTC, adamjstewart requested changes

2024-02-23 11:45 UTC, adamjstewart commented on var/spack/repos/builtin/packages/awscli-v2/package.py
> +        )
```suggestion
        examples_dir = join_path(python_purelib, "awscli", "examples")
```
This varies a lot by platform/OS.

2024-02-24 15:25 UTC, adamjstewart approved these changes

2024-02-24 15:25 UTC, merged