vtk: Update proj dependency
LLNL/spack pull request #42797
Opened 2024-02-21 21:03 UTC by Chrismarsh

This PR enables up-to the newest version of `proj@9` to work with vtk, 

Test on macos and rehl.

@chuckatkins
@danlipsa

2024-02-23 18:28 UTC, becker33 requested changes
If this is "all released versions of proj" then why not use an open-ended range?

2024-02-23 18:31 UTC, Chrismarsh commented
I am not sure/if `proj@10` will be released and I'm not sure whether it will have breaking API changes, etc. So I felt staying at `7:9` and then dealing with it if/when `10` ever comes out was safe. 

Would you prefer `7:`?

2024-02-24 04:04 UTC, johnwparent commented
@danlipsa if you have the chance, can you verify this works on Windows? I'd like to keep VTK stable as much as possible.

2024-02-29 14:07 UTC, becker33 approved these changes

2024-02-29 14:07 UTC, merged