adds the ipyvuetify spack recipe
LLNL/spack pull request #42790
Opened 2024-02-21 17:21 UTC by jeremyfix

Brings in the ipyvuetify python package 
"
    Jupyter widgets based on vuetify UI components which implement Google's
    Material Design Spec with the Vue.js framework.
"

2024-02-23 12:03 UTC, adamjstewart requested changes

2024-02-23 12:03 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-ipyvuetify/package.py
> +    depends_on("py-pynpm", type=("build", "run"))
Missing some deps and versions, some types are incorrect:
```toml
[build-system]
requires = ["jupyter_packaging~=0.7.9", "jupyterlab~=3.0", "setuptools>=40.8.0", "wheel"]
```
```python
    install_requires=[                                                                   
        "ipyvue>=1.7,<2",                                                                
    ],     
```

2024-02-24 11:34 UTC, jeremyfix commented
Sorry for the cluttered list of commits , I rebased my branch but maybe not the right way ; 

If you prefer we reopoen a PR to have a cleaner history , just let me know and I shall reopen one ; 

For the versions @adamjstewart  , I'm not sure how to specify a version exclusion such as :  "jupyter_packaging~=0.7.9", "jupyterlab~=3.0". Hence, I specified it as 

```
depends_on("py-jupyter-packaging@0.7.10:", type=("build", "run"))
depends_on("py-jupyterlab@3.0.1:", type=("build", "run"))
```

2024-02-24 13:22 UTC, jeremyfix commented
I prefer closing my PR and resubmitting it , I completely messed up the history and I'm not satisfied with this.

2024-02-24 13:22 UTC, closed without merging