py-pyomo: update package (6.7.1)
LLNL/spack pull request #42795
Opened 2024-02-21 18:38 UTC by mrmundt

This PR updates the `py-pyomo` package to reflect the most recent Pyomo release (6.7.1).

2024-02-23 11:27 UTC, adamjstewart requested changes
Not sure if these changed or these have always been wrong

2024-02-23 11:27 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyomo/package.py
>      depends_on("py-sphinx-rtd-theme@0.5:", when="@6.1:+docs", type=("run"))
sphinx 5+ and sphinx-rtd-theme 0.6+ are now required

2024-02-23 11:27 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyomo/package.py
>      depends_on("py-plotly", when="@6.6:+optional", type=("run"))
All matplotlib versions work (other than 3.6.1)

2024-02-23 13:57 UTC, mrmundt commented on var/spack/repos/builtin/packages/py-pyomo/package.py
>      depends_on("py-sphinx-rtd-theme@0.5:", when="@6.1:+docs", type=("run"))
In Spack specifically?

2024-02-24 15:23 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyomo/package.py
>      depends_on("py-sphinx-rtd-theme@0.5:", when="@6.1:+docs", type=("run"))
According to the `setup.py`

2024-02-24 15:24 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-pyomo/package.py
> +    depends_on("py-sphinx@5:", when="@6.1:+docs", type=("run"))
I'm not actually sure if this is accurate. pyomo 6.1 requires sphinx@3:, not @5:. You should go back through the history and see when it changed. Same for other dependencies.

2024-02-26 16:14 UTC, adamjstewart approved these changes

2024-02-26 16:14 UTC, merged