Added conflicts and extra flags for dakota package
LLNL/spack pull request #42906
Opened 2024-02-28 15:02 UTC by fgava90

Dakota@6.12 and older cannot compile with gcc@12 and newer.
From gcc@12, argument mismatch is an error, dakota needs an extra flag to compile with gcc@10:

2024-02-28 15:04 UTC, fgava90 commented
should fix #41636

2024-10-16 22:51 UTC, bernhardkaindl requested changes
.

2024-10-16 23:40 UTC, bernhardkaindl requested changes
Build results on Ubuntu 22.04.4 LTS:
One failed spec:
- `dakota@6.18 %gcc@13`
### `dakota@6.18 %gcc@13`:
```py

108 errors found in build log:
external/trilinos/packages/teuchos/core/src/Teuchos_BigUInt.hpp:103:18: error: 'uint32_t' is not a member of 'std'
```
Build log:
```py
==> dakota: Executing phase: 'cmake'
-- Found Git: /usr/bin/git (found version "2.34.1") 
-- Dakota release version is: 6.18+
-- Dakota git revision is: f6cb33b51 (2023-05-23)
Naming binary dakota-6.18.0+.Linux.x86_64
-- The C compiler identification is GNU 13.1.0
...
```
Generated and submitted by https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py
```py
~/build-quality-tools/build_pr_changes.py -a -c gcc@13
```

2024-10-16 23:52 UTC, bernhardkaindl approved these changes
Build results on Ubuntu 22.04.4 LTS:
```py
bin/spack find --variants dakota | sed 's/~[a-z]*//g;s/ [a-z0-9_]*=[a-zA-Z0-9]*//g'  # Short variants: Hide disabled and value variants
-- linux-ubuntu22.04-skylake / gcc@9.5.0 ------------------------
dakota@6.12+mpi+python+shared
dakota@6.20.0+mpi+python+shared

-- linux-ubuntu22.04-skylake / gcc@10.5.0 -----------------------
dakota@6.12+mpi+python+shared
dakota@6.20.0+mpi+python+shared

-- linux-ubuntu22.04-skylake / gcc@11.4.0 -----------------------
dakota@6.12+mpi+python+shared
dakota@6.20.0+mpi+python+shared

-- linux-ubuntu22.04-skylake / gcc@12.3.0 -----------------------
dakota@6.20.0+mpi+python+shared
```
Generated and submitted by https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py
```py
~/build-quality-tools/build_pr_changes.py -b dakota -a
```

2024-10-17 01:12 UTC, merged