Make python dep optional for dakota
LLNL/spack pull request #42914
Opened 2024-02-28 18:59 UTC by alexrichert

This PR makes Python an optional dependency for Dakota.

2024-03-04 20:06 UTC, alalazo requested changes
Only a minor request

2024-03-04 20:06 UTC, alalazo commented on var/spack/repos/builtin/packages/dakota/package.py
> +            args.append(self.define("DAKOTA_PYTHON", False))
Can you try:
```suggestion
        args = [
            self.define_from_variant("BUILD_SHARED_LIBS", "shared"),
            self.define_from_variant("DAKOTA_PYTHON", "python")
        ]
```
?

2024-03-05 07:49 UTC, alexrichert commented
Adding v6.19 while I'm at it...

2024-03-05 11:56 UTC, alalazo approved these changes

2024-03-05 11:57 UTC, merged