Update package.py
LLNL/spack pull request #42941
Opened 2024-03-01 15:00 UTC by jfavre

Adding two variants 'fortran' and 'python' to enable language wrappings

2024-03-01 15:17 UTC, ayenpure commented
@jfavre Thanks for the changes, I'll approve them once the pipeline is successful

2024-03-02 12:18 UTC, mathstuf requested changes
The code is OK. Can `libcatalyst` show up somewhere in the commit message/MR description (something to make it appear in the merge results is fine).

2024-03-02 18:11 UTC, alecbcs commented
@jfavre thanks for the PR this looks great. In the future if you could title a PR with the name of the package modified and a short summary of the changes it makes it much easier to review.

@mathstuf does the modified title look good to you? (This will become the commit message when squashed.)

2024-03-02 20:48 UTC, mathstuf approved these changes

2024-03-03 01:55 UTC, alecbcs approved these changes
Looks good to me. @jfavre thanks for the nicely written PR!

2024-03-03 01:55 UTC, merged