py_cheap_repr: add initial package.py
LLNL/spack pull request #42944
Opened 2024-03-01 19:03 UTC by jmlapre

Add [`cheap_repr`](https://pypi.org/project/cheap-repr/) Python library.  Required by [`snoop`](https://pypi.org/project/snoop/).  PR for snoop incoming soon.

2024-03-02 13:36 UTC, adamjstewart requested changes

2024-03-02 13:36 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cheap-repr/package.py
> +    list_url = "https://pypi.org/simple/cheap-repr/"
https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#id2

2024-03-02 13:36 UTC, adamjstewart commented on var/spack/repos/builtin/packages/py-cheap-repr/package.py
> +    depends_on("py-setuptools-scm", type="build")
```suggestion
    depends_on("py-setuptools-scm+toml", type="build")
```

2024-03-04 22:03 UTC, jmlapre reviewed
Should be all fixed.

2024-03-06 19:56 UTC, jmlapre commented
@adamjstewart Can you take a look at this PR when you get a moment?  Thanks.

2024-03-08 12:45 UTC, adamjstewart approved these changes

2024-03-08 12:45 UTC, merged