container: don't map develop to latest
LLNL/spack pull request #42952
Opened 2024-03-02 01:23 UTC by wdconinc

As discussed in https://spackpm.slack.com/archives/C016VGW665P/p1709311731659219, `spack containerize` with `spack:container:images:spack:develop` produces a Dockerfile that starts with `FROM spack/ubuntu-jammy:latest as builder`, where `latest` is currently `0.21.1`. This PR removes the mapping from `develop` to `latest`.

I kept the mapping empty, and kept the `build_tags` code in `lib/spack/spack/container/images.py` for possible future mapping purposes.

2024-03-04 18:49 UTC, alalazo requested changes
There is one unit-test failing. Also, I think we can safely remove `build_tags` from the JSON file and the code.

2024-03-04 19:15 UTC, alalazo commented on lib/spack/spack/container/images.py
>      return build_image, build_tag
If I read correctly from the web UI, here you are returning `build_tag` without ever defining it. Should probably be:
```suggestion
    return build_image, spack_version
```

2024-03-04 21:58 UTC, wdconinc commented
Ok, passes unit tests now.

2024-03-05 09:46 UTC, alalazo approved these changes
Thanks! This was clearly a leftover from #40593

2024-03-05 09:47 UTC, merged