Document new environment variable expansion in projections
LLNL/spack pull request #42963
Opened 2024-03-02 21:13 UTC by psakievich

Adding docs and test for #42917

2024-03-02 22:35 UTC, alecbcs commented on lib/spack/docs/environments.rst
> +Projections also will permit environment variable and spack configuration variable
```suggestion
Projections also permit environment and spack configuration variable
```

@psakievich this is awesome! Totally optional suggestion to clean up the language a little. 😃

2024-03-03 02:07 UTC, alecbcs submitted a review, later dismissed
I'll defer to @alalazo or @tgamblin for a final review before merging but this looks great to me!

2024-03-04 07:08 UTC, alalazo requested changes
Thanks @psakievich Only a couple minor comments

2024-03-04 07:08 UTC, alalazo commented on lib/spack/spack/test/projections.py
> +    os.environ["FOO_ENV_VAR"] = "test-string"
Can you use `monkeypatch.setenv` here? Otherwise following tests will have a polluted environment.

2024-03-04 07:08 UTC, alalazo commented on lib/spack/spack/test/projections.py
> +    """test that env variables and spack config variables are expanded in projections"""
(Just OCD on my side) 
```suggestion
    """Test that env variables and spack config variables are expanded in projections"""
```

2024-03-04 16:16 UTC, psakievich commented
@spackbot fix style

2024-03-04 17:55 UTC, alalazo commented on lib/spack/spack/test/projections.py
> +import os
```suggestion
```

2024-03-04 17:58 UTC, alalazo approved these changes

2024-03-04 19:17 UTC, merged