package/py-wand_add_versions
LLNL/spack pull request #42972
Opened 2024-03-04 00:29 UTC by Sinan81

2024-03-04 18:43 UTC, alalazo requested changes

2024-03-04 18:43 UTC, alalazo commented on var/spack/repos/builtin/packages/py-wand/package.py
> +    version("0.6.13", sha256="f5013484eaf7a20eb22d1821aaefe60b50cc329722372b5f8565d46d4aaafcca"
Hmm, this looks like a syntax error.

2024-03-07 00:16 UTC, Sinan81 commented on var/spack/repos/builtin/packages/py-wand/package.py
> +    version("0.6.13", sha256="f5013484eaf7a20eb22d1821aaefe60b50cc329722372b5f8565d46d4aaafcca"
fixed.

2024-03-07 00:16 UTC, Sinan81 commented
bug fixed. please merge.

2024-03-08 06:36 UTC, alalazo approved these changes
I'll let @adamjstewart do a final review and merge the PR

2024-03-18 14:13 UTC, merged