sundials: add new version
LLNL/spack pull request #43008
Opened 2024-03-05 06:55 UTC by balos1

2024-03-05 16:20 UTC, gardner48 requested changes
Some minor variant updates for the new version

2024-03-05 16:20 UTC, gardner48 commented on var/spack/repos/builtin/packages/sundials/package.py
> +        default="2",
Is there a way to make the default version dependent so the previous default is retained in older versions?

2024-03-05 16:20 UTC, gardner48 commented on var/spack/repos/builtin/packages/sundials/package.py
> +        default="2",
Some other updates below:
* `logging-mpi` variant, `when` can be updated to `when="@6.2.0:6.7.0"`
* `generic-math` variant, add `when="@:6.7.0"`

2024-03-05 19:51 UTC, tldahlgren submitted a review, later dismissed
Confirmed the version sha256.

2024-03-06 18:05 UTC, gardner48 commented on var/spack/repos/builtin/packages/sundials/package.py
> +        default="2",
Updated `logging-mpi` and `generic-math`. There does not currently seem to be a way to have the default depend on the version.

2024-03-06 18:06 UTC, gardner48 approved these changes, later dismissed

2024-03-18 14:17 UTC, alalazo requested changes
There are build errors in CI (`int*` to `int` conversion):
```
 /tmp/root/spack-stage/spack-stage-dealii-9.5.1-glbt6ywp5brskvdbuo2
             zipmupzkvfjtb/spack-src/source/sundials/ida.cc:343:20: error: inva
             lid user-defined conversion from 'dealii::SUNDIALS::IDA<dealii::Ve
             ctor<double> >::reset(double, double, dealii::Vector<double>&, dea
             lii::Vector<double>&)::<lambda(SUNLinearSolver, SUNMatrix, N_Vecto
             r, N_Vector, int)>' to 'int (*)(SUNLinearSolver, SUNMatrix, N_Vect
             or, N_Vector, sunrealtype)' {aka 'int (*)(_generic_SUNLinearSolver
             *, _generic_SUNMatrix*, _generic_N_Vector*, _generic_N_Vector*, do
             uble)'} [-fpermissive]
```

2024-03-18 15:02 UTC, balos1 commented
> There are build errors in CI (invalid conversions):
> 
> ```
>  /tmp/root/spack-stage/spack-stage-dealii-9.5.1-glbt6ywp5brskvdbuo2
>              zipmupzkvfjtb/spack-src/source/sundials/ida.cc:343:20: error: inva
>              lid user-defined conversion from 'dealii::SUNDIALS::IDA<dealii::Ve
>              ctor<double> >::reset(double, double, dealii::Vector<double>&, dea
>              lii::Vector<double>&)::<lambda(SUNLinearSolver, SUNMatrix, N_Vecto
>              r, N_Vector, int)>' to 'int (*)(SUNLinearSolver, SUNMatrix, N_Vect
>              or, N_Vector, sunrealtype)' {aka 'int (*)(_generic_SUNLinearSolver
>              *, _generic_SUNMatrix*, _generic_N_Vector*, _generic_N_Vector*, do
>              uble)'} [-fpermissive]
> ```

I don't think deal.ii's current version is compatible with this new version of SUNDIALS. Should the deal.ii package be updated with a constraint?

2024-03-18 15:07 UTC, alalazo commented
@balos1 Yes, if dealii has wrong constraints they should be updated in this PR, to avoid breaking builds in CI. When CI is :heavy_check_mark: I'll merge.

2024-03-18 16:07 UTC, gardner48 requested changes

2024-03-18 16:07 UTC, gardner48 commented on var/spack/repos/builtin/packages/dealii/package.py
> +    depends_on("sundials@5:6.7", when="@9.3.4:+sundials")
I suspect as similar version constraint will be needed in the MFEM and AMReX packages as well (maybe some others I'm forgetting too).

2024-03-18 16:09 UTC, balos1 commented on var/spack/repos/builtin/packages/dealii/package.py
> +    depends_on("sundials@5:6.7", when="@9.3.4:+sundials")
IIRC they already pin the version in their spack packages, but we will see what the CI reports back.

2024-03-20 19:27 UTC, gardner48 approved these changes

2024-03-21 15:52 UTC, balos1 commented
@alalazo CI is all passing now.

2024-03-25 23:25 UTC, tldahlgren approved these changes

2024-03-25 23:27 UTC, tldahlgren commented
@alalazo Looks like your change request is blocking the merge.

2024-03-28 09:12 UTC, alalazo approved these changes

2024-03-28 09:12 UTC, merged