openscenegraph: patch for compatibility with ffmpeg@5:
LLNL/spack pull request #43051
Opened 2024-03-06 10:44 UTC by aumuell

add proposed upstream patch for compatibility with current ffmpeg

2024-03-06 12:03 UTC, aumuell commented
@spackbot fix style

2024-03-18 14:19 UTC, alalazo requested changes

2024-03-18 14:19 UTC, alalazo commented on var/spack/repos/builtin/packages/openscenegraph/package.py
> +    )
Can you add a brief comment above the `patch` directive explaining:
1. What is the effect of the patch
2. Why it is needed
3. Where it was taken from

?

2024-03-28 10:21 UTC, alalazo approved these changes

2024-03-28 10:21 UTC, merged