py-onnxruntime: add a dependency on git for when an old version is available
LLNL/spack pull request #43076
Opened 2024-03-07 13:23 UTC by jmcarcell

For example on CentOS 7, the system git will fail to correctly fetch the source because of git submodules. Apparently git submodules were introduced in 1.5.3 and on CentOS 7 I have 1.8.X so it should work but it seems it doesn't; with this change it didn't fail at fetching.

2024-03-18 14:07 UTC, alalazo requested changes
> Apparently git submodules were introduced in 1.5.3 and on CentOS 7 I have 1.8.X so it should work but it seems it doesn't; 

Can we check why this is failing first?

2024-03-18 14:07 UTC, alalazo commented on var/spack/repos/builtin/packages/py-onnxruntime/package.py
> +    depends_on("git")
The dependency is of type "build", and I think needs a lower bound on versions

2024-03-22 09:20 UTC, jmcarcell commented
I'm not sure now, it seems I can't reproduce. The day I did this after cloning all the files from the folders related to submodules were showing as modified in `git status` and then there was some error related to a file that doesn't exist but was in the repo,. Adding a git dependency certainly fixed it

2024-11-28 17:49 UTC, alalazo commented
Closing for now, based on https://github.com/spack/spack/pull/43076#issuecomment-2014676591 Feel free to reopen if you encounter the issue again.

2024-11-28 17:49 UTC, closed without merging