add later versions of packages
LLNL/spack pull request #43201
Opened 2024-03-14 21:34 UTC by LinaMuryanto

add later versions of packages for of py-deepdiff py-mysql-connector-python py-nbconvert py-pyqt5-sip py-pyqt5 py-scikit-image py-sqlalchemy py-tabulate py-texttable py-typing-extensions

2024-03-18 11:45 UTC, haampie commented on var/spack/repos/builtin/packages/py-mysql-connector-python/package.py
protobuf no longer a dependency

2024-03-18 11:48 UTC, haampie commented on var/spack/repos/builtin/packages/py-pyqt5/package.py
```depends_on("py-pyqt5-sip@12.13:12", when="@5.15.10:")```

2024-03-18 11:51 UTC, haampie commented on var/spack/repos/builtin/packages/py-scikit-image/package.py
```py-imageio@2.27:```
```py-lazy-loader@0.2:```
```py-packaging@21:```
```py-tifffile@2022.8.12:```

2024-03-18 11:51 UTC, haampie commented on var/spack/repos/builtin/packages/py-sqlalchemy/package.py
```py-typing-extensions@4.6:```

2024-03-18 11:52 UTC, haampie requested changes
Needs updates to bounds in deps

2024-03-18 19:06 UTC, LinaMuryanto commented on var/spack/repos/builtin/packages/py-mysql-connector-python/package.py
@hammpie do I just drop the depends_on() line for protobuf?

2024-03-18 19:12 UTC, LinaMuryanto commented on var/spack/repos/builtin/packages/py-sqlalchemy/package.py
same for this one. I am guessing that I need to put the 'when' attribute. correct?

2024-03-18 19:13 UTC, LinaMuryanto commented on var/spack/repos/builtin/packages/py-scikit-image/package.py
@haampie do I need to add 'when' clause for the above? if so, could you tell me how to find out the value for the when clause? thanks.

2024-03-19 20:46 UTC, LinaMuryanto commented
I am closing it. I do not know enough about these packages to make the changes.

2024-03-19 20:46 UTC, closed without merging