Deep git integration
LLNL/spack pull request #43256
Opened 2024-03-18 19:53 UTC by Pandapip1

Fixes https://github.com/spack/spack/issues/43252 (automatic upgrades are out of scope).

2024-03-18 19:54 UTC, Pandapip1 commented
@spackbot fix style

2024-03-26 18:36 UTC, Pandapip1 commented
@spackbot rerun

2024-03-28 08:26 UTC, alalazo requested changes

2024-03-28 08:26 UTC, alalazo commented on lib/spack/spack/main.py
> +    del status
I don't think we want this (require to have `git` available and potentially wait a long time on each command).

2024-03-28 11:28 UTC, alalazo commented
Closing, since we don't want to require `git` for using Spack. Also, reading #43252 it seems most of the issues were due to not being aware of a few features (e.g. customization of the install tree etc.)

2024-03-28 11:28 UTC, closed without merging