Cmake/add 3.28.4
LLNL/spack pull request #43347
Opened 2024-03-25 15:06 UTC by johnwparent

Last checked, `kokkos-kernels` conflicts with CMakes post 3.28, so in addition to bumping the patch version, also add `kokkos-kernel` CMake version conflict.

2024-03-25 15:10 UTC, lucbv requested changes
Can you explain a bit better what is happening here?
It would be good to have more details so that Kokkos Kernels 4.3.0 is compatible with this new cmake when it gets released in a couple of weeks...

2024-03-25 15:25 UTC, johnwparent commented
> Can you explain a bit better what is happening here? It would be good to have more details so that Kokkos Kernels 4.3.0 is compatible with this new cmake when it gets released in a couple of weeks...

Apologies, I honestly don't know exactly what's going wrong with `kokkos-kernels` itself and I don't have the bandwidth to investigate right now. I just know that post CMake 3.28 `kokkos-kernels` stopped compiling as expected (I'm pretty confident it's due to one of the changes in FindCuda but that's just based on a preliminary investigation) on our Gitlab CI, and it's prevented us from bumping our CMake version, which we need to do to unblock a few other PRs.

2024-03-25 15:35 UTC, lucbv commented
@johnwparent can you at least open an issue with instruction on how to reproduce and ideally the error that you saw otherwise we will be unlikely to be able to remove this conflict easily in the future. If you want to post a link to the CI that showed the issue that's a start.

2024-03-25 16:19 UTC, johnwparent commented
> @johnwparent can you at least open an issue with instruction on how to reproduce and ideally the error that you saw otherwise we will be unlikely to be able to remove this conflict easily in the future. If you want to post a link to the CI that showed the issue that's a start.

No problem, I'll file that issue as soon as I can get a good reproducer. Unfortunately our CI job logs expire after a time, so I'll need to preserve this in a more permanent fashion than a link. Are you folks ok with using docker to reproduce? Spack GL CI automatically generates repro environments with Docker images (OCI). Otherwise I can just include the build args and output in the issue.

I'm also reaching out to some of the other CMake folks to see if we have any better internal idea as to what's going on here, as we'd like to see `kokkos-kernel` building with modern CMake. If you'd like to coordinate more on that, please feel free to reach out to me via DM on the Spack Slack (I have the same username everywhere) or tag me in a channel post.

2024-03-26 08:06 UTC, haampie commented
>  I don't have the bandwidth

You could have opened an issue and let other people look at it like I asked months ago: https://github.com/spack/spack/pull/42358#issuecomment-1918869303


> Can you report / solve this issue @johnwparent?
> 
>     1. `kokkos-kernels` issue persists
>        https://gitlab.spack.io/spack/spack/-/jobs/9935785
>        `CMakeFiles/kokkoskernels.dir/build.make:3092: *** target pattern contains no '%'.  Stop.`
>        The generated Make rule looks like this
>        ```makefile
>        libkokkoskernels.so: CUDA::cuda_driver-NOTFOUND
>        ```
> 
>     2. `trilinos` issue persists:
>        ```
>        CMake Error in CMakeLists.txt:
>          IMPORTED_LOCATION not set for imported target "CUDA::cuda_driver"
>          configuration "Release".
>        ```

2024-04-18 18:03 UTC, johnwparent commented
closed for https://github.com/spack/spack/pull/43723

2024-04-18 18:03 UTC, closed without merging