Don't delete "spack develop" build artifacts after install
LLNL/spack pull request #43424
Opened 2024-03-28 19:00 UTC by scheibelp

This behavior was introduced in https://github.com/spack/spack/pull/41373

The new desired behavior is:

* Build artifacts for develop packages are not removed after a successful install
* ... but they can be deleted in any other context (e.g. `spack clean --stage`)

2024-03-28 20:14 UTC, tgamblin requested changes
I tested this and it looks mostly good. Two requests:

1. docstring request below.
2. I see a working symlink after I install a package successfully.  When I run `spack clean`, the stage is removed but the broken symlink remains. Can we remove that on destroy, as well?

2024-03-28 20:14 UTC, tgamblin commented on lib/spack/spack/spec.py
> +    def is_develop(self):
docstring would be good here.

2024-03-28 23:55 UTC, scheibelp commented
@tgamblin 

> docstring request below.

done

> I see a working symlink after I install a package successfully. When I run spack clean, the stage is removed but the broken symlink remains. Can we remove that on destroy, as well?

done and test updated

2024-03-29 16:33 UTC, tgamblin approved these changes

2024-03-29 16:36 UTC, merged