crtm: add noaa versions and package mods
LLNL/spack pull request #43635
Opened 2024-04-12 18:14 UTC by eugeneswalker

@AlexanderRichert-NOAA @BenjaminTJohnson @Hang-Lei-NOAA @climbfuji @edwardhartnett @t-brown

2024-04-13 03:13 UTC, climbfuji commented
@eugeneswalker is this PR making the spack develop version identical to our fork version?

2024-04-13 16:34 UTC, eugeneswalker commented
> @eugeneswalker is this PR making the spack develop version identical to our fork version?

I'm not sure this exactly matches the current state of that fork, but yes, these changes are coming from there.

2024-04-15 05:08 UTC, AlexanderRichert-NOAA requested changes
Please compare this against the jcsda version and note the differences. In particular, the netcdf-fortran dependency is not there for v2.4.1-jedi-- I'm assuming that needs to be there?

2024-04-15 15:56 UTC, eugeneswalker commented
> Please compare this against the jcsda version and note the differences. In particular, the netcdf-fortran dependency is not there for v2.4.1-jedi-- I'm assuming that needs to be there?

Just added the missing depends_on for netcdf-fortran and ecbuild for crtm@2.4.1-jedi.

2024-04-15 16:34 UTC, AlexanderRichert-NOAA approved these changes

2024-04-15 16:52 UTC, climbfuji requested changes
Can you please make this file identical with what's in our fork? This would be greatly appreciated. Otherwise someone will have to go and make another update right after your PR is merged. Thanks!

2024-04-15 19:29 UTC, eugeneswalker commented
> Can you please make this file identical with what's in our fork? This would be greatly appreciated. Otherwise someone will have to go and make another update right after your PR is merged. Thanks!

I left these two lines out because there is no `@v3.0.0-rc.1` version defined, so it's not clear to me what's going on here:
1. https://github.com/JCSDA/spack/blob/1daf6f1d5df35d80d68ac742c9395dfb76997872/var/spack/repos/builtin/packages/crtm/package.py#L37
2. https://github.com/JCSDA/spack/blob/1daf6f1d5df35d80d68ac742c9395dfb76997872/var/spack/repos/builtin/packages/crtm/package.py#L47

I left the line below out because crtm-fix would also then need to be updated to include the version `@2.4.0.1_emc` which is not present currently, and this update would include the additional logic for handling that build which I don't follow:
1. https://github.com/JCSDA/spack/blob/1daf6f1d5df35d80d68ac742c9395dfb76997872/var/spack/repos/builtin/packages/crtm/package.py#L41

I don't have the bandwidth to track this down and test it out now. If you want to push to this PR please feel free, or we could do it in a separate PR or else delay it until I have more time in future.

2024-04-15 19:59 UTC, climbfuji commented
> > Can you please make this file identical with what's in our fork? This would be greatly appreciated. Otherwise someone will have to go and make another update right after your PR is merged. Thanks!
> 
> I left these two lines out because there is no `@v3.0.0-rc.1` version defined, so it's not clear to me what's going on here:
> 
> 1. https://github.com/JCSDA/spack/blob/1daf6f1d5df35d80d68ac742c9395dfb76997872/var/spack/repos/builtin/packages/crtm/package.py#L37
> 2. https://github.com/JCSDA/spack/blob/1daf6f1d5df35d80d68ac742c9395dfb76997872/var/spack/repos/builtin/packages/crtm/package.py#L47
> 
> I left the line below out because crtm-fix would also then need to be updated to include the version `@2.4.0.1_emc` which is not present currently, and this update would include the additional logic for handling that build which I don't follow:
> 
> 1. https://github.com/JCSDA/spack/blob/1daf6f1d5df35d80d68ac742c9395dfb76997872/var/spack/repos/builtin/packages/crtm/package.py#L41
> 
> I don't have the bandwidth to track this down and test it out now. If you want to push to this PR please feel free, or we could do it in a separate PR or else delay it until I have more time in future.

Fair point. Let's merge this and I'll look at the rest later. Thanks!

2024-04-15 19:59 UTC, climbfuji approved these changes

2024-04-15 20:16 UTC, tldahlgren commented on var/spack/repos/builtin/packages/crtm/package.py
> +    )
I can't seem to confirm this version sha256 with `spack checksum`.  How was it calculated?

2024-04-15 20:22 UTC, tldahlgren approved these changes
Confirmed the commit and version sha256.

2024-04-15 20:22 UTC, tldahlgren commented on var/spack/repos/builtin/packages/crtm/package.py
> +            return "https://github.com/JCSDA/crtm/archive/refs/tags/{}.tar.gz".format(version)
FYI. We do encourage use of Python f-strings (https://docs.python.org/3/tutorial/inputoutput.html) when feasible, which we're moving to in the core.

2024-04-15 20:24 UTC, merged