enh: update zfit version to 0.20
LLNL/spack pull request #43695
Opened 2024-04-16 23:44 UTC by jonas-eschle

Upgrade zfit, requires also new TensorFlow and TensorFlow-Probability versions, see also https://github.com/spack/spack/pull/43688

2024-04-17 17:23 UTC, tldahlgren approved these changes
Confirmed version sha256.

2024-04-17 17:25 UTC, tldahlgren commented
Looks like there's a concretization problem:

```
1. py-zfit: dependency on py-tensorflow-probability@0.24 cannot be satisfied by known versions of py-tensorflow-probability
    happening in /home/runner/work/spack/spack/var/spack/repos/builtin/packages/py-zfit/package.py
    known versions of py-tensorflow-probability are 0.23.0, 0.22.1, 0.22.0, 0.21.0, 0.20.0, 0.19.0, 0.18.0, 0.12.1
```

2024-04-17 17:26 UTC, tldahlgren requested changes
Looks like there's a dependency on updating `py-tensorflow-probability` with the required version.

2024-04-17 20:05 UTC, jonas-eschle commented
Thanks for looking into it!

Yes, as mentioned, requires also new TensorFlow and TensorFlow-Probability versions (#43688)

Working on these, but TF is a tough beast sometimes. I'll update and ping again as soon they're ready

2024-04-29 23:10 UTC, tldahlgren approved these changes
Re-confirmed the sha256s.

2025-04-22 08:57 UTC, jonas-eschle commented
Closing, solved by #49349

2025-04-22 08:57 UTC, closed without merging