Compilers from externals: warn and continue on failure to parse
LLNL/spack pull request #43724
Opened 2024-04-18 15:48 UTC by becker33

Currently, malformed compilers from packages.yaml cause a fatal error.

This PR turns the error into a warning, and Spack will only fail if the constraints used require that compiler. For example, if `gcc` and `llvm+clang` are configured as externals and the configuration for `gcc` fails to convert to compiler config internally, `spack install foo%gcc` will still fail, but `spack install foo%clang` can succeed.

2024-04-18 20:42 UTC, tgamblin commented
LGTM but can we get a test?

2024-05-13 12:10 UTC, adrienbernede commented
@becker33 I would appreciate to see it merged ;).

2024-05-23 21:46 UTC, tgamblin requested changes

2024-05-23 21:46 UTC, tgamblin commented on lib/spack/spack/compilers/__init__.py
> +            msg = "Reading compiler from packages config section failed\n"
this should report the file and line from the specific file.  we have that info in the config.

2024-05-24 15:06 UTC, alalazo commented
@spackbot run pipeline

2024-05-24 17:51 UTC, scheibelp commented on lib/spack/spack/compilers/__init__.py
> +            msg = "Reading compiler from packages config section failed\n"
With a minor amount of hacking, I think it would be possible to retrieve the file (i.e. this would involve re-running these functions in all scopes of interest, then reporting an error for the scope with the failing entry/ies). The line number info is harder:

* For yaml syntax errors, a failure would have occurred before this and the parsing error would have contained that info (so in that case, it's already available)
* For other errors that occur after the files have been read into a config object (e.g. the `ruamel.yaml.comments.CommentedMap` object etc.), it's more difficult:
  * We don't retrieve this info anywhere that I know of (i.e. for other config errors), looking at it in this instance (e.g. for the `entry` read in the test I added) it does not appear to be useful (no origin file info, and line/column info appears strange)
  * I looked for some inspiration from `spack config blame` (in particular `print_flattened_configuration`) but that doesn't appear to assemble the info in a way that would be useful here (or in general, to be programmatically retrieved)

I think a generic function could be created that would be useful for printing info about many config errors, but I estimate that would take 10-15 hours (not counting review time) / ~100 SLOC.

2024-05-24 21:49 UTC, scheibelp commented
The issue as originally reported cannot be reproduced in the latest Spack (including the state of develop from the last day merged into this branch). For now I'm marking this as draft.

We may want to address https://github.com/spack/spack/pull/43724#discussion_r1613829048 though in a separate, more-generic PR.

2024-05-24 21:58 UTC, tgamblin requested changes

2024-05-24 21:58 UTC, tgamblin commented on lib/spack/spack/compilers/__init__.py
> +        except Exception as e:
This shouldn't be raising `Exception` but something more narrow.

2024-05-30 03:25 UTC, scheibelp commented
@becker33 @tgamblin closing this for now because it's not reproducible on develop. Feel free to reopen if there's something you want to extract from it.

2024-05-30 03:25 UTC, closed without merging