grads: fix libpng and g2c deps
LLNL/spack pull request #43909
Opened 2024-04-30 00:15 UTC by AlexanderRichert-NOAA

This PR:
 - allows grads@:2.2.2 to use hdf built with the v16 libpng API; currently, `./configure` prior to v2.2.3 uses `-lpng15` specifically. It builds successfully with libpng@1.6: (v16 API; the alternative would be something like `depends_on("hdf ^libpng@1.5")`).
 - changes `G2_VERSION` to `G2C_VERSION` in src/gacfg.c. This was the only way I could get it to compile with +grib2; @vanderwb let me know if I'm missing something here, like if it's related to G2C version or something.

2024-04-30 16:54 UTC, vanderwb requested changes
Aside from the one suggested change, this looks good to me. Thanks for the fixes!

2024-04-30 16:54 UTC, vanderwb commented on var/spack/repos/builtin/packages/grads/package.py
> +        if self.spec.satisfies("+grib2"):
Looking through the g2c repo, it seems that this constant was changed from `G2_VERSION` to `G2C_VERSION` in g2c@1.8.0. I'd suggest changing this satisfies to:

```
if self.spec.satisfies("^g2c@1.8.0:"):
```

2024-04-30 16:57 UTC, AlexanderRichert-NOAA commented on var/spack/repos/builtin/packages/grads/package.py
> +        if self.spec.satisfies("+grib2"):
Done. Thanks for checking into that!

2024-04-30 17:08 UTC, vanderwb approved these changes

2024-05-01 22:57 UTC, tldahlgren commented
@spackbot fix style

2024-05-01 22:58 UTC, tldahlgren approved these changes, later dismissed

2024-05-01 23:23 UTC, tldahlgren approved these changes

2024-05-02 16:42 UTC, merged