Update package.py for vacuumms 1.2.0
LLNL/spack pull request #43948
Opened 2024-05-02 02:53 UTC by frankwillmore

2024-05-02 03:53 UTC, frankwillmore commented
Update of spack package for new VACUUMMS version (1.2.0). Also, clarified license is MIT.

2024-05-02 16:35 UTC, tldahlgren requested changes
Confirmed the branch and all (affected) version sha256.  Just a couple of minor changes.

2024-05-02 16:35 UTC, tldahlgren commented on var/spack/repos/builtin/packages/vacuumms/package.py
> +    )
The packaging convention is to order version directives from newest to oldest so please reverse the ordering of these.  (See the first note in the docs at https://spack.readthedocs.io/en/latest/packaging_guide.html#versions-and-fetching.)

2024-05-02 16:35 UTC, tldahlgren commented on var/spack/repos/builtin/packages/vacuumms/package.py
> +        description="""voro++ location""",
Curious.  Why have double quotes for the description?

2024-05-03 01:42 UTC, frankwillmore commented on var/spack/repos/builtin/packages/vacuumms/package.py
> +    )
done

2024-05-03 18:06 UTC, tldahlgren approved these changes
Thanks.  And I'm glad you knew what I meant about the *extra* double quotes.

2024-05-03 18:06 UTC, merged