[Kokkos] fix deprecated code flag being ignored
LLNL/spack pull request #43947
Opened 2024-05-01 23:25 UTC by nmm0

Currently, the variant `+deprecated_code` generates an invalid CMake flag `KOKKOS_ENABLE_DEPRECATED_CODE`. We actually use deprecated code flags of the format `KOKKOS_ENABLE_DEPRECATED_CODE_4` (for the 4.x release series). The invalid flag is ignored, except for a warning on CMake's part.

This PR fixes the flag to set `KOKKOS_ENABLE_DEPRECATED_CODE_4`. In the future, we will need to update the mapping as we update our major releases.

2024-05-02 14:21 UTC, lucbv approved these changes

2024-05-02 15:00 UTC, cedricchevalier19 reviewed
So `deprecated_code` is still broken for older Kokkos (< 4) ?

It can make sense to not do anything for these soon to be deprecated versions, and putting a `conflict` for older version can break the concretizer.

Perhaps adding a comment about that can be useful.

2024-05-02 15:28 UTC, nmm0 commented
> It can make sense to not do anything for these soon to be deprecated versions, and putting a `conflict` for older version can break the concretizer.

A yes, good point I will add the conflict. We could do a mapping per major version but not sure how worth it it is.

2024-05-18 07:38 UTC, alalazo requested changes
This PR is blocked because of broken kokkos build in our pipelines. See, e.g.  https://gitlab.spack.io/spack/spack/-/pipelines/694667

2024-07-02 13:48 UTC, cedricchevalier19 commented
@alalazo Is it possible to increase the log size of the failed Trilinos build.

@nmm0 I think this version of Trilinos might require `cuda_lambda`.

2024-07-02 15:52 UTC, alalazo commented
@cedricchevalier19 Not sure about that. Possibly @scottwittenburg or @kwryankrattiger will know. In any case, I think you can:
```console
$ spack ci reproduce-build https://gitlab.spack.io/api/v4/projects/2/jobs/11720824/artifacts --working-dir /tmp/pipeline
```
and follow the instruction to reproduce locally (needs docker installed on the host).

2024-07-02 15:58 UTC, kwryankrattiger commented
Increasing the log size is not really an option unfortunately. We do upload the full logs from the build to the artifacts, here is the one for trilinos [spack-build-log.txt](https://gitlab.spack.io/spack/spack/-/jobs/11720824/artifacts/file/jobs_scratch_dir/logs/spack-build-out.txt)

2024-07-02 16:01 UTC, nmm0 commented
> Increasing the log size is not really an option unfortunately. We do upload the full logs from the build to the artifacts, here is the one for trilinos [spack-build-log.txt](https://gitlab.spack.io/spack/spack/-/jobs/11720824/artifacts/file/jobs_scratch_dir/logs/spack-build-out.txt)
> 
> Reproducing the build can also be quite helpful. Unfortunately this is failing in Cray, so unless you have access to a cray system that may be difficult.

Thank you , looks like the artifact log contains the error.

2025-06-06 12:05 UTC, haampie commented
Hi @nmm0, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2026-01-04 01:52 UTC, closed without merging