pkg-config: support apple-clang@15:
LLNL/spack pull request #44007
Opened 2024-05-04 22:16 UTC by alecbcs

Starting with `apple-clang@15:` int conversions are now treated as errors instead of warnings which breaks pkg-config support on MacOS Sonoma.

2024-05-06 07:33 UTC, haampie commented on var/spack/repos/builtin/packages/pkg-config/package.py
> +        for strict_compiler in ("%oneapi", "%cce", "%apple-clang@15:", "clang@15:"):
```suggestion
        for strict_compiler in ("%oneapi", "%cce", "%apple-clang@15:", "%clang@15:"):
```

or just use `if any(spec.compiler.satisfies(c) for c in ("oneapi", ...)`

2024-05-06 07:33 UTC, haampie requested changes
typo

2024-05-06 15:26 UTC, alecbcs commented
Fixed! @haampie thanks for the catch

2024-05-14 15:24 UTC, haampie approved these changes

2024-05-14 15:24 UTC, merged