docs: Fix method signature in autoreconf example
LLNL/spack pull request #44067
Opened 2024-05-07 19:04 UTC by Chrismarsh

This fixes the method signature in the autoools/autoreconf example to match the method sigature [that is expected](https://spack.readthedocs.io/en/latest/spack.build_systems.html#spack.build_systems.autotools.AutotoolsBuilder.autoreconf).

2024-05-07 19:48 UTC, johnwparent submitted a review, later dismissed

2024-05-07 21:48 UTC, alalazo requested changes
Builders have different signatures from packages. In the docs we usually refer to packages.
```console
$ grep "def autoreconf(self, spec, prefix)" -R var/ | wc -l
152
$ grep "def autoreconf(self, pkg, spec, prefix)" -R var/ | wc -l
5
```

2024-05-17 14:40 UTC, johnwparent approved these changes
This seems like a useful change to me, thanks @Chrismarsh for the docs contribution.

@alalazo I'll let you actually merge this since you have a better understanding of how we structure the docs than I do.

2024-05-17 16:16 UTC, alalazo approved these changes

2024-05-17 16:16 UTC, merged