bugfix: external detection for compilers with os but not target
LLNL/spack pull request #44156
Opened 2024-05-13 15:52 UTC by becker33

avoid calling `spec.target` when None.

When an external compiler package has an `os` set but no `target` set, Spack currently falls into a codepath that calls `spec.target` (which itself calls `spec.architecture.target.Microarchitecture`) when `spec.architecture.target` is None, throwing an error.

e.g.

```
packages:
  gcc:
    externals:
    - spec: gcc@12.3.1 os=rhel7
      prefix: /usr
```

2024-05-13 15:59 UTC, haampie approved these changes, later dismissed

2024-05-13 16:07 UTC, haampie commented
needs more fixing it seems

2024-05-23 22:36 UTC, tgamblin requested changes

2024-05-23 22:36 UTC, tgamblin commented on lib/spack/spack/compilers/__init__.py
>              target = host_platform.target("default_target").microarchitecture
```suggestion
        target = spec.architecture.target
        if not target:
            target = spack.platforms.host().target("default_target")
        target = target.microarchitecture
```

2024-05-23 23:34 UTC, tgamblin approved these changes

2024-05-24 00:13 UTC, merged

2024-05-24 07:45 UTC, alalazo commented
A fix is not really a fix without a regression test :slightly_smiling_face: