perl: update versions
LLNL/spack pull request #44186
Opened 2024-05-14 17:48 UTC by drkrynstrng

Updating available versions:

- Adding latest maintenance releases
- Updating preferred version to 5.38.2
- Adding latest development release 5.39.10
- Marking older, end-of-life releases as deprecated

2024-05-15 09:44 UTC, LydDeb approved these changes

2024-05-17 16:38 UTC, alalazo requested changes
Only minor requests

2024-05-17 16:38 UTC, alalazo commented on var/spack/repos/builtin/packages/perl/package.py
> +    version("5.36.0", sha256="e26085af8ac396f62add8a533c3a0ea8c8497d836f0689347ac5abd7b7a4e00a")
Can you mark these as `preferred=True`? This is needed so that `5.39.10` (develop version) won't be the second preferred.

2024-05-17 16:38 UTC, alalazo commented on var/spack/repos/builtin/packages/perl/package.py
> +    )
Wondering if we should directly remove these (since we have the next stable release)

2024-05-17 19:04 UTC, drkrynstrng commented on var/spack/repos/builtin/packages/perl/package.py
> +    version("5.36.0", sha256="e26085af8ac396f62add8a533c3a0ea8c8497d836f0689347ac5abd7b7a4e00a")
Oh, I see. Fixed.

2024-05-17 19:10 UTC, drkrynstrng commented on var/spack/repos/builtin/packages/perl/package.py
> +    )
Not sure. @LydDeb Is it useful to keep previous development releases?

2024-05-18 07:20 UTC, alalazo commented on var/spack/repos/builtin/packages/perl/package.py
> +    )
Well, I'll merge for now, we can still delete those later :wink:

2024-05-18 07:20 UTC, alalazo approved these changes

2024-05-18 07:21 UTC, merged