protobuf: update hash for patch needed when="@3.4:3.21"
LLNL/spack pull request #44210
Opened 2024-05-15 15:43 UTC by dmagdavector

Doing a download of the patch 'manually' via, e.g.

* `wget https://github.com/protocolbuffers/protobuf/pull/11032/commits/3039f932aaf212bcf2f14a3f2fd00dbfb881e46b.patch?full_index=1`

gets a different hash than what Spack currently expects:

```
$ sha256sum 3039f932aaf212bcf2f14a3f2fd00dbfb881e46b.patch\?full_index\=1
ae8639a308294bed85d3f6ebb7e005ee4fde6b2884d41cb75543191c9c5c98ef 3039f932aaf212bcf2f14a3f2fd00dbfb881e46b.patch?full_index=1
```

This old(er) version of Protobuf is pulled in by, _e.g._, py-torch (which seems to need older versions).

2024-05-15 15:45 UTC, dmagdavector commented
Per `git blame` the patch was originally added by @aumuell

2024-05-15 15:46 UTC, dmagdavector commented
See also https://spackpm.slack.com/archives/C5VL7V81G/p1715785679756449

2024-05-15 15:49 UTC, hyoklee approved these changes

2024-05-15 16:05 UTC, wdconinc commented
It seems https://github.com/protocolbuffers/protobuf/pull/11032/commits/3039f932aaf212bcf2f14a3f2fd00dbfb881e46b.patch?full_index=1 doesn't actually have the full index, as intended. That makes it an unstable target for a patch link. It becomes exponentially less likely that there is another increase in the number of characters in the index, but should we just upload a fixed file here to prevent future hash changes?

2024-05-16 09:08 UTC, haampie commented
Yeah, this is a small patch, better to add it to spack as a file.

2024-05-16 10:23 UTC, wdconinc commented
See also https://github.com/spack/spack/pull/44212

2024-05-17 19:20 UTC, wdconinc requested changes
With this suggestion, the link and hash should be stable.

2024-05-17 19:20 UTC, wdconinc commented on var/spack/repos/builtin/packages/protobuf/package.py
>          "https://github.com/protocolbuffers/protobuf/pull/11032/commits/3039f932aaf212bcf2f14a3f2fd00dbfb881e46b.patch?full_index=1",
Per discussion in https://github.com/spack/spack/pull/44212#issuecomment-2118169017:
```suggestion
        "https://github.com/protocolbuffers/protobuf/commit/3039f932aaf212bcf2f14a3f2fd00dbfb881e46b.patch?full_index=1",
```

2024-05-17 19:20 UTC, wdconinc commented on var/spack/repos/builtin/packages/protobuf/package.py
> +        sha256="ae8639a308294bed85d3f6ebb7e005ee4fde6b2884d41cb75543191c9c5c98ef",
which also changes the sha256:
```suggestion
        sha256="a779238fb7957514d4fb393410111419a964771e826ec2a8f09c21aa1efbb4d1",
```

2024-05-17 19:27 UTC, wdconinc approved these changes

2024-05-17 23:50 UTC, merged