RVS patch update for lib and lib64 yaml library path
LLNL/spack pull request #44287
Opened 2024-05-21 06:18 UTC by renjithravindrankannath

yaml library directory can be lib or lib64 based on the arch.
Updating patch to make compatible for both.

2024-05-21 06:26 UTC, srekolam approved these changes

2024-05-21 10:05 UTC, alalazo requested changes
Can you add a brief comment above the `patch` directives explaining:
1. What is the effect of the patch
2. Why it is needed
3. Where it was taken from

? Here you change an existing patch, it would be good to know why this change is needed and why wasn't it there before.

2024-05-21 16:39 UTC, renjithravindrankannath commented
> Can you add a brief comment above the `patch` directives explaining:
> 
> 1. What is the effect of the patch
> 2. Why it is needed
> 3. Where it was taken from
> 
> ? Here you change an existing patch, it would be good to know why this change is needed and why wasn't it there before.

Hi @alalazo , 
Thanks for looking into it.
The existing patch results in build failure on ubuntu24.04 since yaml-cpp library directory is just **lib**.
`root@ixt-rack-104:/spack# ls /spack/opt/spack/linux-ubuntu24.04-skylake_avx512/gcc-13.2.0/yaml-cpp-0.7.0-v2knemv7ffn2wuppbgdth7mcnryitufj
include  lib  share
`
It works with rhel, centos etc because yaml-cpp library directory is **lib64**.
`bash-5.1# ls /spack/opt/spack/linux-rhel9-skylake_avx512/gcc-11.2.1/yaml-cpp-0.7.0-djz473vo444yvo3as7tczdfdehajs7m7
include  lib64  share
`
This PR is primarily to make below reference generic across the distros. 
https://github.com/spack/spack/blob/9c88a48a731a53accfc88a52163f5fc3b26bac6e/var/spack/repos/builtin/packages/rocm-validation-suite/009-replacing-rocm-path-with-package-path.patch#L476

2024-05-30 07:02 UTC, alalazo approved these changes
Can we *please* upstream patches for next versions? It's kind of sad to see that thousands of lines of patches are needed for packages AMD owns:
```
$ wc -l var/spack/repos/builtin/packages/rocm-validation-suite/00*
   159 var/spack/repos/builtin/packages/rocm-validation-suite/005-cleanup-path-reference-donot-download-googletest-yaml.patch
   371 var/spack/repos/builtin/packages/rocm-validation-suite/006-library-path.patch
   407 var/spack/repos/builtin/packages/rocm-validation-suite/007-cleanup-path-reference-donot-download-googletest-yaml-library-path_5.3.patch
   532 var/spack/repos/builtin/packages/rocm-validation-suite/007-cleanup-path-reference-donot-download-googletest-yaml-library-path_5.6.patch
   606 var/spack/repos/builtin/packages/rocm-validation-suite/008-correcting-library-and-include-path-WITHOUT-RVS-BUILD-TESTS.patch
   539 var/spack/repos/builtin/packages/rocm-validation-suite/009-replacing-rocm-path-with-package-path-6.1.patch
   636 var/spack/repos/builtin/packages/rocm-validation-suite/009-replacing-rocm-path-with-package-path.patch
  3250 total
```

2024-05-30 07:06 UTC, merged