parallel: add version 20240522
LLNL/spack pull request #44368
Opened 2024-05-24 02:21 UTC by drkrynstrng

Adding latest GNU Parallel release version 20240522.

2024-06-05 00:58 UTC, drkrynstrng commented
@spackbot re-run pipeline

2024-06-06 09:15 UTC, alalazo approved these changes

2024-06-06 09:18 UTC, alalazo requested changes
There are legit issues in pipelines:
- https://gitlab.spack.io/spack/spack/-/jobs/11501806
- https://gitlab.spack.io/spack/spack/-/jobs/11501808
- https://gitlab.spack.io/spack/spack/-/jobs/11501807

2024-06-06 20:17 UTC, drkrynstrng commented
Okay, I'll look into the failed jobs.

2024-06-27 08:40 UTC, alalazo approved these changes

2024-06-27 08:42 UTC, alalazo requested changes

2024-06-27 08:42 UTC, alalazo commented on var/spack/repos/builtin/packages/parallel/package.py
> +    depends_on("gmake", type="build")
This is inherited from `AutotoolsPackage`:
```suggestion
```

2024-06-27 08:43 UTC, alalazo approved these changes

2024-06-27 19:29 UTC, drkrynstrng commented
For some reason it's failing to install in the aws-isc CI jobs. Based on the error messages, it looks like parallel is being run as a shell script instead of a Perl script when generating the Bash completions, but I haven't figured out why yet.

2024-07-01 23:03 UTC, closed without merging