py-hist: add v2.6.2 thru v2.7.2 (switch to hatchling)
LLNL/spack pull request #44387
Opened 2024-05-25 13:42 UTC by wdconinc

This PR adds v2.6.2-3, 2.7.0-2 of py-hist. It also adds the new package py-dask-histogram as a dependency.

2024-05-29 00:16 UTC, tldahlgren requested changes
Confirmed the homepage and version sha256s.  The dependencies don't seem to match the `pyproject.toml` files for some versions.

2024-05-29 00:16 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-dask-histogram/package.py
> +    depends_on("py-hatchling@1.8.0:", type="build")
FYI. You could drop the `.0` patch versions here and below.

2024-05-29 00:16 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-hist/package.py
> +            depends_on("py-iminuit@2:", type=("build", "run"))
For 2.6.2 and 2.6.3, these are relevant when the python version is < 3.11:

```
plot = [
    "matplotlib >=3.0",
    "mplhep >=0.2.16",
    "scipy >=1.4; python_version<'3.11'",
    "iminuit >=2; python_version<'3.11'",
]
```

2024-05-29 00:16 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-hist/package.py
>      depends_on("py-numpy@1.14.5:", type=("build", "run"))
For 2.7.2, this only applies when python version is < 3.12 and there's a new minimum for python >= 3.12:

```
dependencies = [
    "boost-histogram>=1.3.1,<1.5",
    "histoprint>=2.2.0",
    'numpy>=1.14.5;python_version<"3.12"',
    'numpy>=1.26.0b1;python_version>="3.12"',
    'typing-extensions>=4;python_version<"3.11"',
]
```

2024-05-29 00:31 UTC, wdconinc reviewed
I gotta think about these some more. I suspect these same restrictions should also apply earlier, but weren't active then because python@3.11 just wasn't out yet.

2024-05-29 00:31 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-dask-histogram/package.py
> +    depends_on("py-hatchling@1.8.0:", type="build")
```suggestion
    depends_on("py-hatchling@1.8:", type="build")
```

2024-05-29 00:31 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-hist/package.py
>      depends_on("py-numpy@1.14.5:", type=("build", "run"))
Thanks!
```suggestion
    depends_on("py-numpy@1.14.5:", type=("build", "run"), when="@:2.7.1")
    depends_on("py-numpy@1.14.5:", type=("build", "run"), when="@2.7.2: ^python@:3.11")
    depends_on("py-numpy@1.26:", type=("build", "run"), when="@2.7.2: ^python@3.12:")
```

2024-05-29 00:31 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-hist/package.py
> +            depends_on("py-iminuit@2:", type=("build", "run"))
```suggestion
            depends_on("py-scipy@1.4:", type=("build", "run"), when="@:2.6.1,2.7.0")
            depends_on("py-iminuit@2:", type=("build", "run"), when="@:2.6.1,2.7.0")
            depends_on("py-scipy@1.4:", type=("build", "run"), when="@2.6.2:2.6.3 ^python@:3.10")
            depends_on("py-iminuit@2:", type=("build", "run"), when="@2.6.2:2.6.3 ^python@:3.10")
```

2024-11-19 22:30 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-hist/package.py
> +    depends_on("py-numpy@1.26:", type=("build", "run"), when="@2.7.2: ^python@3.12:")
```suggestion
    depends_on("py-numpy@1.14.5:", type=("build", "run"), when="@:2.7.1,2.7.3:")
    depends_on("py-numpy@1.14.5:", type=("build", "run"), when="@2.7.2 ^python@:3.11")
    depends_on("py-numpy@1.26:", type=("build", "run"), when="@2.7.2 ^python@3.12:")
```

2024-11-19 22:31 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-hist/package.py
>      depends_on("python@3.7:", type=("build", "run"))
```suggestion
    depends_on("python@3.7:", type=("build", "run"))
    depends_on("python@3.8:", type=("build", "run"), when="@2.8.0:")
```

2024-11-19 22:31 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-hist/package.py
> +    depends_on("py-boost-histogram@1.3.1:1.4", when="@2.7.2:", type=("build", "run"))
```suggestion
    depends_on("py-boost-histogram@1.3.1:1.4", when="@2.7.2:", type=("build", "run"))
    depends_on("py-boost-histogram@1.3.1:1.5", when="@2.8.0:", type=("build", "run"))
```

2025-06-06 12:05 UTC, haampie commented
Hi @wdconinc, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2025-06-06 13:36 UTC, closed without merging