libxshmfence: add v1.3.1, v1.3.2
LLNL/spack pull request #44393
Opened 2024-05-25 17:59 UTC by wdconinc

This PR adds the newer versions of libxshmfence, and applies the same treatment as `util-macros` in #44388 for changing from bz2 to xz as archive format. This also ensures that updates will be found by `spack checksum`.

Test builds find the right urls (older are on spack mirrors).
```
==> Installing libxshmfence-1.2-ovebe7ohy3ipjd5zejxhzapb3yx5kx22 [34/37]
==> No binary for libxshmfence-1.2-ovebe7ohy3ipjd5zejxhzapb3yx5kx22 found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/d2/d21b2d1fd78c1efbe1f2c16dae1cb23f8fd231dcf891465b8debe636a9054b0c.tar.bz2
==> No patches needed for libxshmfence
==> libxshmfence: Executing phase: 'autoreconf'
==> libxshmfence: Executing phase: 'configure'
==> libxshmfence: Executing phase: 'build'
==> libxshmfence: Executing phase: 'install'
==> libxshmfence: Successfully installed libxshmfence-1.2-ovebe7ohy3ipjd5zejxhzapb3yx5kx22
  Stage: 1.44s.  Autoreconf: 0.00s.  Configure: 3.60s.  Build: 0.27s.  Install: 0.08s.  Post-install: 0.05s.  Total: 5.59s
[+] /opt/software/linux-ubuntu24.04-skylake/gcc-13.2.0/libxshmfence-1.2-ovebe7ohy3ipjd5zejxhzapb3yx5kx22
==> Installing libxshmfence-1.3.2-v6gwk4qda6rv5x4alclibzxmtfszyebl [35/37]
==> No binary for libxshmfence-1.3.2-v6gwk4qda6rv5x4alclibzxmtfszyebl found: installing from source
==> Fetching https://www.x.org/archive/individual/lib/libxshmfence-1.3.2.tar.xz
==> No patches needed for libxshmfence
==> libxshmfence: Executing phase: 'autoreconf'
==> libxshmfence: Executing phase: 'configure'
==> libxshmfence: Executing phase: 'build'
==> libxshmfence: Executing phase: 'install'
==> libxshmfence: Successfully installed libxshmfence-1.3.2-v6gwk4qda6rv5x4alclibzxmtfszyebl
  Stage: 1.70s.  Autoreconf: 0.00s.  Configure: 3.50s.  Build: 0.36s.  Install: 0.11s.  Post-install: 0.05s.  Total: 5.83s
[+] /opt/software/linux-ubuntu24.04-skylake/gcc-13.2.0/libxshmfence-1.3-eu42ddb2o25mneood5i6nsevqbqwhcwr
==> Installing libxshmfence-1.3.1-44xlbm2nngprxpua6u3h3guor527nqbd [37/37]
==> No binary for libxshmfence-1.3.1-44xlbm2nngprxpua6u3h3guor527nqbd found: installing from source
==> Fetching https://www.x.org/archive/individual/lib/libxshmfence-1.3.1.tar.xz
==> No patches needed for libxshmfence
==> libxshmfence: Executing phase: 'autoreconf'
==> libxshmfence: Executing phase: 'configure'
==> libxshmfence: Executing phase: 'build'
==> libxshmfence: Executing phase: 'install'
==> libxshmfence: Successfully installed libxshmfence-1.3.1-44xlbm2nngprxpua6u3h3guor527nqbd
  Stage: 1.64s.  Autoreconf: 0.00s.  Configure: 3.63s.  Build: 0.26s.  Install: 0.11s.  Post-install: 0.04s.  Total: 5.81s
[+] /opt/software/linux-ubuntu24.04-skylake/gcc-13.2.0/libxshmfence-1.3.1-44xlbm2nngprxpua6u3h3guor527nqbd
```

2024-05-28 19:11 UTC, tldahlgren requested changes
I can only confirm the version sha256s for the existing directives.  I get `Error: All fetchers failed` for the newer ones.

2024-05-28 19:20 UTC, wdconinc commented
> I get `Error: All fetchers failed` for the newer ones.

Ah, I think I see what is happening. `url_for_version` doesn't return anything at all for those newer versions. I can probably decorate it with a `@when`. I'll rerequest when I've tested this (and made sure not to hit the cache).

2024-08-02 20:39 UTC, wdconinc commented
I (finally) applied the fix in https://github.com/spack/spack/pull/44393, and this now fetches consistently for me (with `etc/spack/defaults/mirrors.yaml` removed to avoid hitting the source cache):
```console
root@codespaces-136366:/workspaces/spack# spack fetch libxshmfence@=1.3.2
==> Fetching https://www.x.org/archive/individual/lib/libxshmfence-1.3.2.tar.xz
root@codespaces-136366:/workspaces/spack# spack fetch libxshmfence@=1.3.1
==> Fetching https://www.x.org/archive/individual/lib/libxshmfence-1.3.1.tar.xz
root@codespaces-136366:/workspaces/spack# spack fetch libxshmfence@=1.3
==> Fetching https://www.x.org/archive/individual/lib/libxshmfence-1.3.tar.bz2
root@codespaces-136366:/workspaces/spack# spack fetch libxshmfence@=1.2
==> Fetching https://www.x.org/archive/individual/lib/libxshmfence-1.2.tar.bz2
```

This is now ready for review.

2024-08-06 02:04 UTC, tldahlgren requested changes
I am still not able to confirm  the version sha256s (without the change I suggest).

2024-08-06 02:04 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libxshmfence/package.py
> +            return spack.url.substitute_version(self.urls[0].replace("xz", "bz2"), version)
Please move this method to be the first one in the package, so *after* all directives (i.e., so after line 30).

2024-08-06 02:04 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libxshmfence/package.py
> +            return spack.url.substitute_version(self.urls[0].replace("xz", "bz2"), version)
I'd ditch the note comment and make the following changes, which work for all of the currently listed versions:

```suggestion
        url = super().url_for_version(version)
        if version <= Version("1.3"):
            return url.replace("xz", "bz2")

        return url
```

2024-08-06 02:11 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libxshmfence/package.py
> +            return spack.url.substitute_version(self.urls[0].replace("xz", "bz2"), version)
Note:  The original `self.spec.satisifes()` doesn't work in `url_for_version()` since spec is not concrete at that point.

2024-08-06 02:28 UTC, wdconinc commented
Made the changes but not tested them yet.

2024-08-06 16:16 UTC, wdconinc commented
With latest changes, this pulls the following files (when removing default mirrors, and clearing cache first):
```
root@codespaces-136366:/workspaces/spack# spack clean -a ; for v in 1.2 1.3 1.3.1 1.3.2 ; do spack fetch libxshmfence@=${v} ; done
==> Removing all temporary build stages
==> Removing cached downloads
==> Removing install failure marks
==> Removing cached information on repositories
==> Removing python cache files
==> Fetching https://www.x.org/archive/individual/lib/libxshmfence-1.2.tar.bz2
==> Fetching https://www.x.org/archive/individual/lib/libxshmfence-1.3.tar.bz2
==> Fetching https://www.x.org/archive/individual/lib/libxshmfence-1.3.1.tar.xz
==> Fetching https://www.x.org/archive/individual/lib/libxshmfence-1.3.2.tar.xz
```

2024-08-06 16:19 UTC, wdconinc commented
Similarly for hashes:
```
root@codespaces-136366:/workspaces/spack# spack clean -a ; for v in 1.2 1.3 1.3.1 1.3.2 ; do spack checksum libxshmfence ${v} ; done
==> Removing all temporary build stages
==> Removing cached downloads
==> Removing install failure marks
==> Removing cached information on repositories
==> Removing python cache files
==> Found 1 version of libxshmfence
==> Fetching https://www.x.org/archive/individual/lib/libxshmfence-1.2.tar.bz2

    version("1.2", sha256="d21b2d1fd78c1efbe1f2c16dae1cb23f8fd231dcf891465b8debe636a9054b0c")

==> Found 1 version of libxshmfence
==> Fetching https://www.x.org/archive/individual/lib/libxshmfence-1.3.tar.bz2

    version("1.3", sha256="b884300d26a14961a076fbebc762a39831cb75f92bed5ccf9836345b459220c7")

==> Found 1 version of libxshmfence
==> Fetching https://www.x.org/archive/individual/lib/libxshmfence-1.3.1.tar.xz

    version("1.3.1", sha256="1129f95147f7bfe6052988a087f1b7cb7122283d2c47a7dbf7135ce0df69b4f8")

==> Found 1 version of libxshmfence
==> Fetching https://www.x.org/archive/individual/lib/libxshmfence-1.3.2.tar.xz

    version("1.3.2", sha256="870df257bc40b126d91b5a8f1da6ca8a524555268c50b59c0acd1a27f361606f")

```

2024-08-06 17:56 UTC, tldahlgren approved these changes
Thanks!

2024-08-06 17:56 UTC, merged