xorg pkgs: update versions and homepage cgit -> gitlab
LLNL/spack pull request #44420
Opened 2024-05-28 19:01 UTC by wdconinc

This PR updates the versions in the first commit, and updates additional homepages from the cgit mirror to the primary gitlab service now in use.

2024-05-31 23:22 UTC, tldahlgren requested changes
Confirmed the new sha256s and all but 2 homepages.  The unconfirmed homepages have typos.  Also have a couple of questions.

2024-05-31 23:22 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libx11/package.py
> +    git = "https://gitlab.freedesktop.org/xorg/lib/libx11.git"
Curious.  Do you plan to add the ability to build a branch?

2024-05-31 23:22 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libxaw3d/package.py
> +    depends_on("xproto@7.0.22:")
(Asking for confirmation) Is this dependency new for the new versions?  Or does it apply to all listed versions?

2024-05-31 23:22 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libxmu/package.py
> +    depends_on("libxt@1.1:", when="@1.2.0:")
You don't need the `.0` patch version here.

2024-05-31 23:22 UTC, tldahlgren commented on var/spack/repos/builtin/packages/xev/package.py
> +    homepage = "https://gitalb.freedesktop.org/xorg/app/xev"
```suggestion
    homepage = "https://gitlab.freedesktop.org/xorg/app/xev"
```

2024-05-31 23:22 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libxxf86misc/package.py
> +    homepage = "https://gilab.freedesktop.org/xorg/lib/libXxf86misc"
```suggestion
    homepage = "https://gitlab.freedesktop.org/xorg/lib/libXxf86misc"
```

2024-05-31 23:27 UTC, wdconinc commented on var/spack/repos/builtin/packages/libx11/package.py
> +    git = "https://gitlab.freedesktop.org/xorg/lib/libx11.git"
No plans to add branches, but this was a way to add the gitlab repository there for easy copy & paste by whoever adds future new versions, so they can run compares of the configure.ac files. I didn't want to change the official homepage to the gitlab repository through.

2024-06-01 00:56 UTC, wdconinc commented on var/spack/repos/builtin/packages/libxaw3d/package.py
> +    depends_on("xproto@7.0.22:")
This is based on commit https://gitlab.freedesktop.org/xorg/lib/libxaw3d/-/commit/34b1fb5d114b6c763c06dd9618c3d8ca11662e34, and from my reading I think it should have applied all along and only became an error due to compilers changing warnings to errors. Upon close reading now, it's possible that this commit needs to be a patch for older versions in order to compile with newer clang.

2024-06-01 00:56 UTC, wdconinc commented on var/spack/repos/builtin/packages/libxmu/package.py
> +    depends_on("libxt@1.1:", when="@1.2.0:")
```suggestion
    depends_on("libxt@1.1:", when="@1.2:")
```

2024-06-13 23:44 UTC, alecbcs commented
@tldahlgren does this PR pass your checks for homepages and versions now?

2024-06-13 23:55 UTC, tldahlgren commented
> @tldahlgren does this PR pass your checks for homepages and versions now?

Thanks for the ping @alecbcs

2024-06-14 00:41 UTC, tldahlgren approved these changes
[Re]confirmed *all* homepages and new version sha256s.

2024-06-14 00:42 UTC, merged