OpenFOAM: Add missing dependency on readline
LLNL/spack pull request #44483
Opened 2024-06-01 17:48 UTC by RemiLacroix-IDRIS

The setSet tool has an optional dependency on readline. The build script will use the system readline if not provided by Spack.

2024-06-03 09:36 UTC, olesenm commented
I think for this to be complete, you may need to generate a etc/config.sh/readline file as well (sets `READLINE_ARCH_PATH`). Obviously the entire OpenFOAM config "system" is still a mess, but haven't yet found a good alternative.

2024-06-03 10:29 UTC, RemiLacroix-IDRIS commented
I'm not sure what you mean exactly by "complete". As far as I can tell the correct readline is used but that might not have been what you meant.

2024-06-03 11:03 UTC, olesenm commented
> I'm not sure what you mean exactly by "complete". As far as I can tell the correct readline is used but that might not have been what you meant.

There is a `wmake/scripts/have_readline`script that is invoked by the setSet/Allwmake. This is a ad hoc "finder" for detecting a readline library/include etc. If there is nothing particular set in the etc/config.sh/readline, it will just try its best to search the system paths. If readline is not available from the system, I suspect that it won't really work. This is to say, I'm not sure that your added dependency will actually change anything when building since OpenFOAM still won't know about the readline paths added by spack.

2024-06-03 12:29 UTC, RemiLacroix-IDRIS commented
> I'm not sure that your added dependency will actually change anything when building since OpenFOAM still won't know about the readline paths added by spack

Spack is very good at injecting paths, I can confirm that just by adding the dependency it picked the right readline for `setSet` and correctly set the rpath.

However I think you're right about this not working if there is no system readline. I will update my PR.

2024-10-16 16:19 UTC, bernhardkaindl requested changes
Build results on Ubuntu 22.04.4:
FIXME: (build logs not collected automatically).
The PR branch likely should also be rebased to the current develop.

2025-03-05 04:44 UTC, kftsehk commented
Hi, I just happened to look at `openfoam-org@12`, `openfoam@2406` and `openfoam@2412` in other PR.
Found the following packages provided by system (which sometimes doesn't if going very minimal)

- json-c
- libyaml
- libreadline
- ~lustre (lnetconfig/lustreapi, I think it is only there if you have lustre filesystem)~


**openfoam-org@12**
```shell
openfoam-org-12-cgbpustspcgispy54ai4tdp7ufpb4uqs$ cat <(fd -t x) <(fd '.*\.so.*') | sort -u | xargs ldd 2>/dev/null | grep -E ' (/usr)?/lib(64)?/' | awk '{print $1,$2,$3}' | sort | uniq -c
     41 libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
     24 libjson-c.so.5 => /lib/x86_64-linux-gnu/libjson-c.so.5
     24 liblnetconfig.so.4 => /usr/lib/liblnetconfig.so.4
     24 liblustreapi.so.1 => /usr/lib/liblustreapi.so.1
     39 libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6
     24 libreadline.so.8 => /lib/x86_64-linux-gnu/libreadline.so.8
     24 libyaml-0.so.2 => /lib/x86_64-linux-gnu/libyaml-0.so.2
```
**openfoam@2412**
```shell
openfoam-2412-ihbtj4bs5yu4e2khyh6j4wdt3xyrxstd$ cat <(fd -t x) <(fd '.*\.so.*') | sort -u | xargs ldd 2>/dev/null | grep -E ' (/usr)?/lib(64)?/' | awk '{print $1,$2,$3}' | sort | uniq -c
    451 libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
    434 libjson-c.so.5 => /lib/x86_64-linux-gnu/libjson-c.so.5
    434 liblnetconfig.so.4 => /usr/lib/liblnetconfig.so.4
    434 liblustreapi.so.1 => /usr/lib/liblustreapi.so.1
    450 libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6
    434 libreadline.so.8 => /lib/x86_64-linux-gnu/libreadline.so.8
    434 libyaml-0.so.2 => /lib/x86_64-linux-gnu/libyaml-0.so.2
```
**openfoam@2406**
```shell
openfoam-2406-p6lm4lolcmssijexesa67vacfxuu6hfs$ cat <(fd -t x) <(fd '.*\.so.*') | sort -u | xargs ldd 2>/dev/null | grep -E ' (/usr)?/lib(64)?/' | awk '{print $1,$2,$3}' | sort | uniq -c<(fd '.*\.so.*') | sort -u | xargs ldd 2>/dev/nu
    450 libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
    433 libjson-c.so.5 => /lib/x86_64-linux-gnu/libjson-c.so.5
    433 liblnetconfig.so.4 => /usr/lib/liblnetconfig.so.4
    433 liblustreapi.so.1 => /usr/lib/liblustreapi.so.1
    449 libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6
    433 libreadline.so.8 => /lib/x86_64-linux-gnu/libreadline.so.8
    433 libyaml-0.so.2 => /lib/x86_64-linux-gnu/libyaml-0.so.2
```

2025-05-07 07:37 UTC, alalazo commented
Repository layout changed for Spack v1.0 Please resubmit the PR if you're still interested in the package. Closing for now.

2025-05-07 07:37 UTC, closed without merging