package/perl-bio-ensembl-variation: add v110-v112
LLNL/spack pull request #44507
Opened 2024-06-03 01:51 UTC by teaguesterling

Adding the `perl-bio-ensembl-variation` corresponding to the `Bio::Ensembl::Variation` perl module.

2024-07-29 12:50 UTC, EbiArnie commented
This should also depend on perl-bio-ensembl.

2024-07-29 12:50 UTC, EbiArnie commented
Apart from that, looks good to me.

2024-07-29 22:25 UTC, teaguesterling commented
@EbiArnie Thank you for the review! Change made to add `perl-bio-ensembl` as a dependency.

2024-07-30 10:10 UTC, EbiArnie requested changes
See inline comments - installing with all variants did not work for me.

2024-07-30 10:10 UTC, EbiArnie commented on var/spack/repos/builtin/packages/perl-bio-ensembl-variation/package.py
> +    depends_on("perl-bioperl")
The dependencies for these seem to be missing:
perl-bio-bigfile
perl-bio-db-hts
perl-sereal

2024-07-30 10:10 UTC, EbiArnie commented on var/spack/repos/builtin/packages/perl-bio-ensembl-variation/package.py
> +    variant("scripts", default=False, description="Install addition scripts")
typo: additional

2024-07-30 10:10 UTC, EbiArnie commented on var/spack/repos/builtin/packages/perl-bio-ensembl-variation/package.py
> +                install("calc_genotypes", prefix.bin.calc_genotypes)
This doesn't work for me. It seems the 'build' phase is never run. Have you tried installing with "+ld"?


```
==> [2024-07-30-10:39:32.882665] Installing calc_genotypes to /home/arnie/spack/opt/spack/linux-ubuntu22.04-icelake/gcc-11.4.0/perl-bio-ensembl-variation-112-k3iegv4icjabt5bawm5bvsjqz6raxqlc/bin/calc_genotypes
==> Error: OSError: No such file or directory: 'calc_genotypes'

/home/arnie/r/ensembl-swenv-spack-internal/packages/perl-bio-ensembl-variation/package.py:60, in install:
         57        if spec.satisfies("+ld"):
         58            mkdirp(prefix.bin)
         59            with working_dir("C_code"):
  >>     60                install("calc_genotypes", prefix.bin.calc_genotypes)
```

Another thing:
This specifies a subdirectory of prefix.bin with the name calc_genotypes, but that dir does not exist.
Same for the next line.

I think it should be just `prefix.bin`.

2024-07-30 15:45 UTC, teaguesterling commented on var/spack/repos/builtin/packages/perl-bio-ensembl-variation/package.py
> +                install("calc_genotypes", prefix.bin.calc_genotypes)
Thanks for catching this! I think I refactored this into oblivion and didn't test it properly afterwords. There were two issues that needed to be addressed. The `build` phase needed to be explicitly declared in the `phases` list and `HTSLIB_DIR` environmental variable was missing. Setting those got it to work.

The `install` statement installed the file to the path `prefix.bin.calc_genotypes` as expected, however I think it's not idiomatic. I also realized that I missed handling the `scripts` variant, so likely I'd forgotten this package was a WIP still. Revising and testing to wrap it up.

2024-07-30 15:54 UTC, teaguesterling commented on var/spack/repos/builtin/packages/perl-bio-ensembl-variation/package.py
> +                install("calc_genotypes", prefix.bin.calc_genotypes)
It *also* turns out that this now depends on `perl-bio-ensembl-io` when running the tools installed with `+tools`. You may have a better/stronger opinion about how this is handled, so suggestions are more than welcome!

2024-07-30 15:57 UTC, teaguesterling commented
With this now depending on both `perl-bio-ensembl-io` and `perl-bio-bigfile`, it's probably a good idea to merge this after #44509. I have to merge the dependencies into this to make sure the package audit checks on dependent packages pass as expected.

2024-09-10 14:53 UTC, EbiArnie requested changes
Please update this and remove perl-bio-ensembl-io and perl-bio-bigfile.
Please depend on perl-bioperl@1.6.924
Please make sure that each package version depends on the same perl-bio-ensembl and perl-bio-ensembl-io version.

2024-09-10 22:38 UTC, teaguesterling commented
> Please update this and remove perl-bio-ensembl-io and perl-bio-bigfile.
> Please depend on perl-bioperl@1.6.924
> Please make sure that each package version depends on the same perl-bio-ensembl and perl-bio-ensembl-io version.

We finally made it to this one. Thank you for summarizing the changes!

2024-09-28 15:33 UTC, bernhardkaindl approved these changes, later dismissed
@EbiArnie, with the new updates, could you retract your "changes requested" flag by approving this PR?

I built it on Ubuntu 22.04

2024-09-28 16:32 UTC, bernhardkaindl reviewed
Built on Ubuntu 22.04 with the update sha

2024-09-28 16:32 UTC, bernhardkaindl approved these changes, later dismissed
Built on Ubuntu 22.04 with the updated sha.

@EbiArnie, with the new updates, could you retract your "changes requested" flag that prevents merging by approving this PR?

2024-10-01 14:51 UTC, EbiArnie commented
I finally found the time to do a proper review and run the test suite.
Apologies for taking so long.

I've found that this depends on two things that are not obvious.
One is Role::Tiny::With, this is not in Spack so far. 
The other is our own "sibling" repo, ensembl-funcgen, perl-bio-ensembl-funcgen in Spack.

Since funcgen is there, it should be added.
For Role::Tiny::With, this could also come later.

In addition, I found quite a few issues in the test suite. I don't think I will have the time to go into all of them.
They have a variety of causes - for example there is code in there for a data pipeline we run.
This code depends on ensembl-hive, but it's absolutely not necessary for anything else.
I think, test failures related to that should be ignored at the moment.

Other errors may be caused by code that's too new, that would most probably be the htslib version in this case.
Most often, the newer version will give better outputs, it's just that they don't match the test suite.

But, I think we can not fix all issues here. So let's go ahead regardless.

Please add the -funcgen dependency.
Then I would go ahead and merge. As future steps, we should add the package for Role::Tiny::With.
And since you care for VEP, I would try a triage issues there so that I don't debug too many things that are not needed for VEP.

2024-10-01 14:52 UTC, EbiArnie requested changes
Please add dependency for perl-bio-ensembl-funcgen

2024-10-01 15:13 UTC, bernhardkaindl approved these changes
@EbiArnie Thanks for the review

To get this done I added as asked for @teaguesterling:
```py
depends_on(f"perl-bio-ensembl-funcgen@{vers}", when=f"@{vers}", type="run")
```

2024-10-01 22:27 UTC, teaguesterling commented
> @EbiArnie Thanks for the review
> 
> To get this done, I added as asked for @teaguesterling:
> ```py
> depends_on(f"perl-bio-ensembl-funcgen@{vers}", when=f"@{vers}", type="run")
> ```

Thanks for catching that. I must've missed adding it or forgot to commit.

2024-10-02 14:20 UTC, EbiArnie approved these changes
OK

2024-10-02 14:21 UTC, merged