py-jproperties: add v1.0.1, v2.0.0, v2.1.0, v2.1.1
LLNL/spack pull request #44519
Opened 2024-06-03 03:04 UTC by teaguesterling

Add a few new and older versions of the `py-jproperties` package. Older versions are needed as dependencies for upcoming packages.

2024-06-03 03:44 UTC, teaguesterling commented
@spackbot fix style

2024-06-04 00:05 UTC, tldahlgren requested changes
Confirmed the homepage and version sha256s but I think the dependencies for the versions need a bit more work.

2024-06-04 00:05 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-jproperties/package.py
> +    depends_on("py-six@1.13:", type=("build", "run"))
Looks like `1.0.1` doesn't have this dependency.

While `2.0.0`'s `setup.py` has:
```
    install_requires=["six ~= 1.10"],
    setup_requires=["pytest-runner ~= 2.0"],
```
but only `six` listed in the egg's `requires.txt`.  The `six` requirement should correspond to `py-six@1.10:1`.

`2.1.0`'s `setup.py` has:
```
    install_requires=["six ~= 1.12"],
    setup_requires=["pytest-runner ~= 2.0"],
```
so `six` should correspond to `py-six@1.12:1`.

Finally, `2.1.1`'s `setup.py` has the build constraints:
```
    install_requires=["six ~= 1.13"],
    setup_requires=[
        "setuptools_scm ~= 3.3"
    ],
```
which corresponds to `py-six@1.13:1` plus the additional dependency of `py-setuptools-scm@3.3:3`. Though the egg's `requires.txt` only shows the six dependency.

2024-06-04 15:11 UTC, teaguesterling commented on var/spack/repos/builtin/packages/py-jproperties/package.py
> +    depends_on("py-six@1.13:", type=("build", "run"))
Thank you! Will add these in. I really appreciate the time to capture this. It helps me think through what to look for in future PRs.

2024-06-06 21:39 UTC, tldahlgren approved these changes
Thanks for the updates.

2024-06-06 21:40 UTC, merged