vep-cache: add v110,v111,v112
LLNL/spack pull request #44523
Opened 2024-06-03 03:38 UTC by teaguesterling

The VEP program requires a substantial amount of data which needs to be referenced either on the CLI or as ENV vars. Given spack's path management, this can be tricky as they are typically donwloaded by the VEP installer. Since the `vep` package may be installed differently, this makes things hard to deal with. This package separates out the downloading of caches (which can take a substantial amount of time) by using the saved VEP installer and then sets up the run environment to point to the right places.

This depends on the `vep` package which itself is still waiting on its dependencies to be merged in.

2024-07-29 13:45 UTC, EbiArnie requested changes

2024-07-29 13:45 UTC, EbiArnie commented on var/spack/repos/builtin/packages/vep-cache/package.py
> +            f"assemlby={assembly}" if species == "homo_sapiens" else "",
Typo "assemlby"

2024-07-29 13:45 UTC, EbiArnie commented on var/spack/repos/builtin/packages/vep-cache/package.py
> +        description="Which assembly of genome to use (only needed for homo sapiens",
Please ")".

2024-07-29 13:49 UTC, EbiArnie commented
If I'm not mistaken, this installs the cache into the directory of the vep package. Since you can point the vep application to the location of the cache, I would much prefer if the cache was in a directory for the vep-cache package.
I feel that one package should not modify anything in another packages directory (Though likely there are valid exceptions).
Do you think that would work too?

2024-07-30 20:06 UTC, teaguesterling commented
> If I'm not mistaken, this installs the cache into the directory of the vep package. Since you can point the vep application to the location of the cache, I would much prefer if the cache was in a directory for the vep-cache package. I feel that one package should not modify anything in another packages directory (Though likely there are valid exceptions). Do you think that would work too?

That's a good point. I think I was half-way to getting it there but paused working on it. It's been difficult for me to effectively test due to the download/unpack times so I put this aside for a while. I agree that nothing should actually be installed to the `vep` package directory. In this case, it may actually be worth going further and providing an example of how to install it into a custom path. 

I'll take a stab at simplifying and cleaning up the installation locations in the next week or so.

2024-08-25 03:42 UTC, teaguesterling commented
@spackbot fix style

2024-08-25 06:53 UTC, teaguesterling commented
@spackbot fix style

2024-10-17 09:02 UTC, EbiArnie commented
@teaguesterling This is still a draft. Are you preparing more changes? If not, please change this - otherwise I'm afraid this will be quite invisible.

2024-10-17 14:47 UTC, teaguesterling commented
Invisible to me as well, it seems! Thanks  for resurfacing this. I believe it's ready to go but have kept it in draft until I could properly test.

2024-10-17 23:22 UTC, teaguesterling commented
@spackbot fix style

2024-10-18 15:54 UTC, teaguesterling commented
@EbiArnie I've (finally) taken a moment to fix this and testing it now. Let me know if you agree with the approach and defaults.

2024-10-19 21:28 UTC, teaguesterling commented
@spackbot fix style

2024-11-01 13:31 UTC, EbiArnie requested changes
This does not work for me so far.

I fixed the things mentioned inline, but now I get this:
```
==> vep-cache: Executing phase: 'install'
==> [2024-11-01-13:19:50.691200] '/home/arnie/spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.4.0/tar-1.34-tp6wjifaj4umssq3shxbew2a6dgu5ys4/bin/tar' 'xzvf' 'homo_sapiens_vep_112_GRCh37.tar.gz' '-C' '/home/arnie/spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.4.0/vep-cache-112-di46ss33qpaehp6av2miy6j33marpo3v/share/vep'
tar (child): homo_sapiens_vep_112_GRCh37.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
/home/arnie/spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.4.0/tar-1.34-tp6wjifaj4umssq3shxbew2a6dgu5ys4/bin/tar: Child returned status 2
/home/arnie/spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.4.0/tar-1.34-tp6wjifaj4umssq3shxbew2a6dgu5ys4/bin/tar: Error is not recoverable: exiting now
==> Error: ProcessError: Command exited with status 2:
    '/home/arnie/spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.4.0/tar-1.34-tp6wjifaj4umssq3shxbew2a6dgu5ys4/bin/tar' 'xzvf' 'homo_sapiens_vep_112_GRCh37.tar.gz' '-C' '/home/arnie/spack/opt/spack/linux-ubuntu22.04-x86_64_v4/gcc-11.4.0/vep-cache-112-di46ss33qpaehp6av2miy6j33marpo3v/share/vep'
```

I tried to install this spec:
```
 -  vep-cache  assembly=grch37 species=homo_sapiens
 ```

2024-11-01 13:31 UTC, EbiArnie commented on var/spack/repos/builtin/packages/vep-cache/package.py
> +    depends_on("vep", type="build", when="~use_vep_installer")
We must depend on vep also when +use_vep_installer.
Otherwise vep and its installer isn't even downloaded.

2024-11-01 13:31 UTC, EbiArnie commented on var/spack/repos/builtin/packages/vep-cache/package.py
> +        cache_type = variants["source"].value
I think this must be assembly_source
```suggestion
        cache_type = variants["assembly_source"].value
```

2024-11-01 13:31 UTC, EbiArnie commented on var/spack/repos/builtin/packages/vep-cache/package.py
> +                version=cache["version"], species=cache["species"], assembly=cache["assembly"]
This needs the additional parameter source=cache["type"]:
```suggestion
                version=cache["version"], species=cache["species"], assembly=cache["assembly"], source=cache["type"]
```

2024-11-03 01:12 UTC, teaguesterling commented
@EbiArnie, thank you for making those corrections. As for the file not found issue, I was able to chase it down to Spack's behavior when `has_code = False` resulting in none of the resources being downloaded/handled either. I'm modifying the code to workaround (read: hack) that.

2024-11-03 16:28 UTC, teaguesterling commented
@EbiArnie In troubleshooting this, I also realized that somewhere along the way Spack has started enforcing checksums on any resources that it downloads. That's probably for the best, but ended up making the logic for bypassing the VEP installer even more complicated.

I've removed that code from this PR to get it functional. I've preserved the original PR in https://github.com/teaguesterling/spack/tree/packages/vep-cache_with_resources. This worked if you added the checksums, but that became too difficult to consider maintaining.

2024-11-03 16:59 UTC, teaguesterling commented
Some notes from testing:
```
$ spack add vep-cache
==> Adding vep-cache to environment vep
$ spack concretize
==> Concretized 1 spec:
 -   vujmzhe  vep-cache@112%gcc@11.4.0+env+fasta+indexed+match_vep_version assembly=latest assembly_source
...
$ spack install -v
...
==> Installing vep-cache-112-vujmzhewyfxv7w3iiae2bwjfmn2sbg5s [162/162]
==> No binary for vep-cache-112-vujmzhewyfxv7w3iiae2bwjfmn2sbg5s found: installing from source
==> No patches needed for vep-cache
==> vep-cache: Executing phase: 'install'
==> [2024-11-03-08:23:59.340751] '/home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/vep-112.0-c6sxx4ogknorlbcfb2n5jchr22te3pdz/share/vep/scripts/INSTALL.pl' '--AUTO' 'cf' '--NO_UPDATE' '--NO_TEST' '--CACHEDIR' '/home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/vep-cache-112-vujmzhewyfxv7w3iiae2bwjfmn2sbg5s/share/vep/homo_sapiens/112_GRCh38' '--CACHE_VERSION' '112' '--SPECIES' 'homo_sapiens' '--ASSEMBLY' 'GRCh38'
 - getting list of available cache files
 - downloading https://ftp.ensembl.org/pub/release-112/variation/indexed_vep_cache/homo_sapiens_vep_112_GRCh38.tar.gz
==> Error: Keyboard interrupt.
^C

# That was going to take too long. Let's try a different species...
$ spack change vep-cache species=danio_rerio
$ spack install -v
...
==> Installing vep-cache-112-qu44ftwfjshnsnjax47sf2nqhwm4odiu [162/162]
==> No binary for vep-cache-112-qu44ftwfjshnsnjax47sf2nqhwm4odiu found: installing from source
==> No patches needed for vep-cache
==> vep-cache: Executing phase: 'install'
==> [2024-11-03-08:32:33.290516] '/home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/vep-112.0-c6sxx4ogknorlbcfb2n5jchr22te3pdz/share/vep/scripts/INSTALL.pl' '--AUTO' 'cf' '--NO_UPDATE' '--NO_TEST' '--CACHEDIR' '/home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/vep-cache-112-qu44ftwfjshnsnjax47sf2nqhwm4odiu/share/vep/danio_rerio/112' '--CACHE_VERSION' '112' '--SPECIES' 'danio_rerio'
 - getting list of available cache files
 - downloading https://ftp.ensembl.org/pub/release-112/variation/indexed_vep_cache/danio_rerio_vep_112_GRCz11.tar.gz
 - unpacking danio_rerio_vep_112_GRCz11.tar.gz
 - converting cache, this may take some time but will allow VEP to look up variants and frequency data much faster
 - use CTRL-C to cancel if you do not wish to convert this cache now (you may run convert_cache.pl later)
2024-11-03 08:46:07 - Processing danio_rerio
2024-11-03 08:46:07 - Processing version 112_GRCz11
2024-11-03 08:46:07 - No unprocessed types remaining, skipping
2024-11-03 08:46:07 - All done!
 - downloading Danio_rerio.GRCz11.dna.toplevel.fa.gz
 - downloading Danio_rerio.GRCz11.dna.toplevel.fa.gz.fai
 - downloading Danio_rerio.GRCz11.dna.toplevel.fa.gz.gzi

The FASTA file should be automatically detected by the VEP when using --cache or --offline.
If it is not, use "--fasta /home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/vep-cache-112-qu44ftwfjshnsnjax47sf2nqhwm4odiu/share/vep/danio_rerio/112/danio_rerio/112_GRCz11/Danio_rerio.GRCz11.dna.toplevel.fa.gz"


All done
==> vep-cache: Successfully installed vep-cache-112-qu44ftwfjshnsnjax47sf2nqhwm4odiu

2024-11-04 11:33 UTC, EbiArnie approved these changes
This works for me.
I installed for species=danio_rerio, this worked fine.
I started the install for GRCh37, seemed to work fine too, although I did not have the patience to let it finish.

A future improvement may be to allow multiple species, although I'm not sure if many people actually need that.

A big thanks for your effort and persistence.

2024-11-04 11:33 UTC, EbiArnie commented on var/spack/repos/builtin/packages/vep-cache/package.py
> +    # This is a dummy value to get spack to resolve resources, which are not downloaded
I don't understand the comment.
There are no more resources - do we still need this?

2024-11-04 11:36 UTC, EbiArnie commented on var/spack/repos/builtin/packages/vep-cache/package.py
> +    # This is a dummy value to get spack to resolve resources, which are not downloaded
Going to merge this now, this is not terribly important.

2024-11-04 11:37 UTC, merged