podio: Make podio extend python once its possible
LLNL/spack pull request #44537
Opened 2024-06-04 08:53 UTC by tmadlener

Make the `podio` package `extend("python")` once it is possible due to a more standard install prefix for the podio python bindings, see https://github.com/AIDASoft/podio/pull/599

2024-06-04 09:24 UTC, jmcarcell approved these changes

2024-06-04 09:25 UTC, jmcarcell commented on var/spack/repos/builtin/packages/podio/package.py
> +    # See https://github.com/AIDASoft/podio/pull/580 that landed after 0.99
```suggestion
    # See https://github.com/AIDASoft/podio/pull/599 that landed after 0.99
```

2024-06-04 09:26 UTC, becker33 requested changes
The version ranges you use overlap on the `0.99` version, since Spack version ranges are inclusive on both ends. Can you please clarify which behavior should be for version 0.99 itself and either change to using `:0.98` or to `0.99.1:`?

2024-06-04 09:34 UTC, tmadlener commented
Thanks. Didn't catch that. This will only work with versions > 0.99, which should now also be reflected here.

2024-06-10 11:55 UTC, tmadlener commented
Is there anything that still needs to be addressed here?

2024-06-20 07:50 UTC, closed without merging