Alex391/py pyseer
LLNL/spack pull request #44543
Opened 2024-06-04 14:46 UTC by alex391

2024-06-04 17:34 UTC, tldahlgren requested changes
Confirmed homepages and sha256s.  The copyright year does not technically have to be up-to-date *this* year but recommend doing so anyway.

@adamjstewart What are your thoughts on this PR (esp., `py-glmnet-python` when have different `py-glmnet`)?

2024-06-04 17:34 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-glmnet-python/package.py
> +# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2024 Lawrence Livermore National Security, LLC and other
```

2024-06-04 17:34 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-pyseer/package.py
> +# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
```suggestion
# Copyright 2013-2024 Lawrence Livermore National Security, LLC and other
```

2024-06-04 17:47 UTC, adamjstewart submitted a review, later dismissed
I agree with all name choices, I would also pick these names.

2024-06-06 21:32 UTC, tldahlgren approved these changes

2024-06-06 21:34 UTC, merged