py-pyqtgraph: variant to choose qt backend
LLNL/spack pull request #44633
Opened 2024-06-08 22:05 UTC by melven

Similar to py-qtpy, allow to choose qt version/variant as backend...

2024-09-01 16:21 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-pyqtgraph/package.py
> +    variant("api", default="pyqt6", description="Default QT API", values=apis, multi=False)
Presumably `pyqt6` hasn't been supported for all versions. Use conditionals in `apis`. Use `_apis` to hide. Use `_pyqt_apis` to clarify what APIs these are.

2024-10-02 17:19 UTC, bernhardkaindl requested changes
@melven: Wouter requested these changes:

> Presumably pyqt6 hasn't been supported for all versions. Use conditionals in apis. Use _apis to hide. Use _pyqt_apis to clarify what APIs these are.

2025-06-06 12:05 UTC, haampie commented
Hi @melven, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2025-06-10 11:12 UTC, melven commented
Done

2025-06-10 11:12 UTC, closed without merging