Changed test method names and skipping non-applicable tests from old to new approach
LLNL/spack pull request #44705
Opened 2024-06-13 18:46 UTC by AcriusWinter

2024-06-13 21:02 UTC, tldahlgren commented on var/spack/repos/builtin/packages/vtk-m/package.py
> +            raise SkipTest("Package must be installed with 'examples'")
Be explicit that `examples` is a boolean variant:

```suggestion
            raise SkipTest("Package must be installed with '+examples'")
```

2024-06-13 21:05 UTC, AcriusWinter commented
spack test run vtk-m
==> Spack test 7x3itvd7jreqc4s2kgtokomt7azuwhw2
==> Testing package vtk-m-2.1.0-k4ixr3n
============================== 1 passed of 1 spec ==============================

2024-06-13 21:06 UTC, tldahlgren requested changes

2024-06-13 21:06 UTC, tldahlgren commented on var/spack/repos/builtin/packages/vtk-m/package.py
> +    def test_smoke_test(self):
This should not start with `test_` or it will be picked up as a separate stand-alone test from `test_build`.

2024-06-13 21:07 UTC, tldahlgren commented on var/spack/repos/builtin/packages/vtk-m/package.py
> +    def test_smoke_test(self):
```
======================= SUMMARY: vtk-m-2.1.0-rc2-3yf3jfg =======================
VtkM::test_build .. PASSED
VtkM::test_smoke_test .. PASSED
============================= 2 passed of 2 parts ============================
```

2024-06-13 21:17 UTC, tldahlgren commented on var/spack/repos/builtin/packages/vtk-m/package.py
> +    def test_smoke_test(self):
Or just drop `test_build` as we discussed offline.

2024-06-13 22:58 UTC, tldahlgren requested changes
Almost there.  A couple of minor changes.

2024-06-13 22:58 UTC, tldahlgren commented on var/spack/repos/builtin/packages/vtk-m/package.py
>      # Delegate in the vtk-m built smoke test
This comment can be removed as it no longer makes sense.

2024-06-13 22:58 UTC, tldahlgren commented on var/spack/repos/builtin/packages/vtk-m/package.py
> +    def test_smoke_test(self):
This method needs a doctoring so the test outputs the purpose.  Right now it's:

```
==> [2024-06-13-15:56:25.033873] test: test_smoke_test: unspecified purpose
```

2024-06-14 00:26 UTC, tldahlgren requested changes
IMO the test purpose needs to be clearer.

2024-06-14 00:26 UTC, tldahlgren commented on var/spack/repos/builtin/packages/vtk-m/package.py
> +        """Test vtk-m with +examples"""
Hmm.  I know it's currently clear from the name of the test but I have concerns from a maintainability standpoint.

So I would still prefer the docstring to be a bit more descriptive of what the test is doing, which is build and run the smoke test example.  

What if another test method is later added that also relies on `+examples` but someone forgets to fix the comment here?

2024-06-14 23:53 UTC, tldahlgren commented
> spack test run vtk-m ==> Spack test 7x3itvd7jreqc4s2kgtokomt7azuwhw2 ==> Testing package vtk-m-2.1.0-k4ixr3n ============================== 1 passed of 1 spec ==============================

Please paste the test summary so it shows the parts.

2024-06-14 23:58 UTC, AcriusWinter commented
========================= SUMMARY: vtk-m-2.1.0-k4ixr3n =========================
VtkM::test_smoke_test .. PASSED
============================= 1 passed of 1 parts ==============================

2024-06-15 00:00 UTC, tldahlgren approved these changes

2024-06-18 01:31 UTC, tldahlgren commented
Looks like CI succeeded (per contents of the link) but is being reported as failed.

@spackbot run pipeline

2024-06-18 01:39 UTC, tldahlgren commented
@spackbot run pipeline

2024-06-18 01:44 UTC, tldahlgren commented
@spackbot run pipeline

2024-06-18 01:49 UTC, tldahlgren commented
@spackbot run pipeline

2024-06-18 14:10 UTC, mvandenburgh commented
@spackbot run pipeline

2024-06-18 14:58 UTC, mvandenburgh commented
@spackbot run pipeline

2024-06-18 15:15 UTC, vicentebolea approved these changes

2024-06-18 15:40 UTC, merged