omega-h: reformatted from old test method to new test method
LLNL/spack pull request #44712
Opened 2024-06-13 23:30 UTC by AcriusWinter

2024-06-13 23:30 UTC, AcriusWinter commented
==> [2024-06-13-16:27:18.558863] Completed testing
==> [2024-06-13-16:27:18.558973] 
======================= SUMMARY: omega-h-9.34.13-mtisup2 =======================
OmegaH::test_osh_box .. PASSED
OmegaH::test_osh_scale .. PASSED
OmegaH::test_vtu .. PASSED
============================= 3 passed of 3 parts ==============================
============================== 1 passed of 1 spec ==============================

2024-06-14 10:40 UTC, cwsmith submitted a review, later dismissed
LGTM.  Thank you.

2024-06-14 15:20 UTC, tldahlgren requested changes
See comments

2024-06-14 15:20 UTC, tldahlgren commented on var/spack/repos/builtin/packages/omega-h/package.py
> +        exe(*options)
The original code is actually expecting `"adapting took"` in the output so the output should be captured and an `assert` added that that string is in the output.

2024-06-14 15:20 UTC, tldahlgren commented on var/spack/repos/builtin/packages/omega-h/package.py
> +    def test_vtu(self):
I would call this `test_osh2vtk` so someone familiar with the tests would recognize the executable that is being run in the test (and CDash) output.

2024-06-15 00:36 UTC, tldahlgren approved these changes
The API conversion works.  The failing test case appears to be an issue with the installation.

2024-06-15 00:36 UTC, tldahlgren commented
@cwsmith Do you want to look this PR over again?

2024-06-15 00:43 UTC, cwsmith approved these changes

2024-06-15 00:43 UTC, cwsmith commented
@tldahlgren @AcriusWinter Thank you for the update.  Where can I see the output from the failing test case?

2024-06-15 00:50 UTC, tldahlgren commented
> @tldahlgren @AcriusWinter Thank you for the update. Where can I see the output from the failing test case?

https://github.com/spack/spack/issues/44732#issuecomment-2169003304

2024-06-15 02:03 UTC, merged