Update py-mlflow versions
LLNL/spack pull request #44742
Opened 2024-06-17 13:47 UTC by elasto

2024-06-19 21:44 UTC, tldahlgren reviewed
Confirmed the 33 new versions though are they all really needed?

2024-06-19 23:21 UTC, tldahlgren requested changes
The dependencies need to be updated to be corrected for each version.

I only checked three so far and am seeing drifting version ranges and new dependencies.  For example, the initial list from `2.13.2`s `requires.txt` is:

``` 
Flask<4
alembic!=1.10.0,<2
cachetools<6,>=5.0.0
click<9,>=7.0
cloudpickle<4
docker<8,>=4.0.0
entrypoints<1
gitpython<4,>=3.1.9
graphene<4
importlib_metadata!=4.7.0,<8,>=3.7.0
markdown<4,>=3.3
matplotlib<4
numpy<2
opentelemetry-api<3,>=1.0.0
opentelemetry-sdk<3,>=1.0.0
packaging<25
pandas<3
protobuf<5,>=3.12.0
pyarrow<16,>=4.0.0
pytz<2025
pyyaml<7,>=5.1
querystring_parser<2
requests<3,>=2.17.3
scikit-learn<2
scipy<2
sqlalchemy<3,>=1.4.0
sqlparse<1,>=0.4.0
```

2024-06-20 09:09 UTC, elasto commented
> Confirmed the 33 new versions though are they all really needed?

No I just tested and used the version 2.8.0 and this is the one that I would like to be integrated if it is possible

2024-06-20 21:24 UTC, tldahlgren commented
> > Confirmed the 33 new versions though are they all really needed?
> 
> No I just tested and used the version 2.8.0 and this is the one that I would like to be integrated if it is possible

Sure.  Only include the versions that are wanted/needed and make sure the dependencies are correct for each.

2024-06-21 10:00 UTC, elasto commented
> > > Confirmed the 33 new versions though are they all really needed?
> > 
> > 
> > No I just tested and used the version 2.8.0 and this is the one that I would like to be integrated if it is possible
> 
> Sure. Only include the versions that are wanted/needed and make sure the dependencies are correct for each.

Yep sorry I would just add the 2.8.0 that I tested/used. I modified my commit according with the only the version 2.8.0

2024-06-21 19:53 UTC, elasto reviewed
Added just the py-mlflow version 2.8.0

2024-06-27 19:02 UTC, tldahlgren reviewed
Confirmed the new version's sha256.

2024-06-27 20:00 UTC, tldahlgren commented
I'm having problems staging the directory ATM to check dependencies.  If `spack` doesn't come back soon I'll do a manual download so I can check.

2024-07-02 07:26 UTC, elasto commented
Hi Tamara,
did you fix the staging issue ?

2024-07-02 19:31 UTC, tldahlgren requested changes
Looks like there are some dependency updated/additions needed for the new version based on `core-requirements.txt`:

```
alembic<2,!=1.10.0
...
Flask<4
...
pandas<3
...
sqlalchemy<3,>=1.4.0
gunicorn<22; platform_system != 'Windows'
...
pyarrow<14,>=4.0.0
...
psutil<6
``

2024-07-02 19:32 UTC, tldahlgren commented
> Hi Tamara, did you fix the staging issue ?

Not at the time but it worked for me now.  Thanks for the ping.

2025-06-06 12:05 UTC, haampie commented
Hi @elasto, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2025-11-26 08:32 UTC, closed without merging