Docs: Update stand-alone test information
LLNL/spack pull request #44755
Opened 2024-06-18 01:59 UTC by tldahlgren

This PR updates the stand-alone test documentation with changes that include:

- [ ] clarify stand-alone test parts

2024-06-20 08:10 UTC, alalazo requested changes
Docs not building: https://readthedocs.org/projects/spack/builds/24752925/

2024-06-20 19:04 UTC, tldahlgren commented
> Docs not building: https://readthedocs.org/projects/spack/builds/24752925/

Had a useful error message too.  Those literal end-strings...

2024-06-24 21:12 UTC, tldahlgren commented
This PR is hung on CI but it is a docs-only change so that check *should* be irrelevant.

2024-06-25 06:26 UTC, alalazo approved these changes
I did a quick pass over docs, and it lgtm. Feel free to merge if you're not seeking further comments / opinions.

2024-06-25 20:33 UTC, merged