openpmd-api: Changed from old test method to new test method
LLNL/spack pull request #44764
Opened 2024-06-18 18:15 UTC by AcriusWinter

2024-06-18 18:37 UTC, AcriusWinter commented
PASSED: OpenpmdApi::test_run_openpmd_ls
==> [2024-06-18-11:30:42.164845] Completed testing
==> [2024-06-18-11:30:42.164932]
===================== SUMMARY: openpmd-api-0.15.2-3xreexb ======================
OpenpmdApi::test_run_openpmd_ls .. PASSED
============================= 1 passed of 1 parts ==============================

2024-06-18 19:22 UTC, tldahlgren requested changes

2024-06-18 19:22 UTC, tldahlgren commented on var/spack/repos/builtin/packages/openpmd-api/package.py
> +        if self.spec.satisfies("0.11.0"):
This should be a version range and starting with the one in the comment.

There's more in the docs on version ranges at https://spack.readthedocs.io/en/latest/packaging_guide.html#version-ranges.

2024-06-18 19:22 UTC, tldahlgren commented on var/spack/repos/builtin/packages/openpmd-api/package.py
> +        exe = which(join_path(self.prefix.bin, "openpmd-ls"))
The original version of the code checks the output (see original lines 179, 183-184.

Therefore this is a test that does check that the executable runs correctly.

2024-06-20 22:06 UTC, tldahlgren approved these changes
Thanks.

2024-06-20 22:06 UTC, merged