libint: add version 2.9.0
LLNL/spack pull request #44776
Opened 2024-06-20 00:53 UTC by snehring

The second stage build process is  cmake from 2.6.0 on. It looks like they're in the process of switching to cmake with the first stage too, so we may be able to make this an actual CMakePackage in the future.

2024-06-20 04:17 UTC, snehring commented
not sure what to make of the build failures on power

2024-06-20 04:17 UTC, snehring commented
@spackbot re-run pipeline

2024-06-20 04:27 UTC, snehring commented
Ah, it's choking on unicode characters in some of the variable names

2024-06-20 05:12 UTC, snehring commented
Reproduced on `gcc@9.4.0` on x86_64. I'll see what I can do about it.

2024-06-20 08:05 UTC, alalazo requested changes

2024-06-20 08:05 UTC, alalazo commented on var/spack/repos/builtin/packages/libint/package.py
> +            with working_dir("build"):
Can we avoid changing dirs 2 times in a row?

2024-06-20 16:45 UTC, snehring commented
[Limitation](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67224) in gcc before version 10 I'm afraid.

2024-06-21 06:28 UTC, alalazo approved these changes

2024-06-21 06:29 UTC, alalazo commented
Waiting for @dev-zero to chime in. Ping me in a while to merge, in case nothing happens.

2024-06-24 06:36 UTC, merged