Extend the py-torch package to explicitly specify the location of FP16
LLNL/spack pull request #44816
Opened 2024-06-22 00:22 UTC by koparasy

Add a simple patch to the `cmake` file of torch. 

Torch when using `USE_SYSTEM_FP16` variable assumes  the FP16 headers to exist under a hard code path (`/usr/include/fp16.h`). We patch the cmake to check for an environment variable that sets the path of `fp16.h` and we set that variable in the torch package.py.

2024-06-29 19:31 UTC, adamjstewart requested changes
Has this patch been submitted upstream to PyTorch? I want to contribute back all fixes and get them to review patches like this. This prevents our build from diverging too far from upstream and makes it easier to report issues. It also helps us avoid having to update patches when the upstream code changes.

2024-06-29 19:34 UTC, koparasy commented
No, I can do so.

2024-06-29 19:45 UTC, adamjstewart commented
Ping me on the upstream discussion too.

2025-06-16 05:54 UTC, alalazo commented
Closing, since we moved the package repository. Feel free to reopen at / migrate to https://github.com/spack/spack-packages if you want to continue work on this.

2025-06-16 05:54 UTC, closed without merging