parse_specs: unify specs based on concretizer:unify
LLNL/spack pull request #44843
Opened 2024-06-24 18:10 UTC by becker33

Currently, `unify: ___` config only affects environments.

With this PR, it now affects any group of specs given to a command using the `parse_specs(*, concretize=True)` interface.

TODO:
- [x] implementation in `parse_specs`
- [x] tests
- [ ] ensure all commands that accept multiple specs and concretize use `parse_specs` interface

2024-11-01 21:11 UTC, tgamblin requested changes
One minor request and one for a future PR. In the future, `concretize_separately`, `concretize_together`, and `concretize_together_when_possible` should be one method in `spack.concretize`.  This PR gets us closer to that but not quite there, but I think that is fine b/c it's a localized change for `parse_specs`, and the bigger refactor would likely touch many more parts of the code.

2024-11-01 21:11 UTC, tgamblin commented on lib/spack/spack/cmd/__init__.py
> +
```suggestion
    env = ev.active_environment()
    spec_pairs = [(spec, env.matching_spec(abstract) if env else None) for spec in specs]
```

2024-11-01 23:37 UTC, tgamblin approved these changes

2024-11-01 23:49 UTC, merged

2024-11-02 09:06 UTC, alalazo commented on lib/spack/spack/concretize.py
> +def concretize_together(*spec_list, **kwargs):
Just wanted to note that in this file we added `**kwargs` and no type-hinting to new functions.

2024-11-18 10:13 UTC, alalazo commented on lib/spack/spack/environment/environment.py
> -        tty.msg(msg)
Was it intentional to remove this print :point_up: ? It was fairly useful in debugging pipeliines.