[py-wandb] Add wandb 0.17.3 for aarch64 and x86_64
LLNL/spack pull request #44908
Opened 2024-06-26 21:55 UTC by aurianer

2024-06-27 08:45 UTC, alalazo requested changes
Why are we not building the extension from sources?

2024-06-27 15:20 UTC, aurianer commented
I could but the previous version already there (0.13.9) was not building from source so I continued in this line. Additionally the latest release of wandb on github is not providing a checksum. So I would prefer to have one :)

2024-07-03 07:17 UTC, aurianer commented
so what do you think, should I build it from source?

2024-07-05 12:19 UTC, msimberg commented on var/spack/repos/builtin/packages/py-wandb/package.py
> +        )
Not knowing much about python, what's the reason these can't be taken directly from pypi?

2024-07-05 12:33 UTC, aurianer commented on var/spack/repos/builtin/packages/py-wandb/package.py
> +        )
This is the url from pypi (see https://pypi.org/project/wandb/0.17.3/#files)

2024-07-05 13:08 UTC, msimberg commented on var/spack/repos/builtin/packages/py-wandb/package.py
> +        )
Right, bear with me. I should ask a more basic question first: Does it need to be spelled out explicitly like this? I guess the version that is already there `0.13.9` just assumes that it's for x86?

@alalazo do you know if there are any helpers for dealing with python packages for non-x86 platforms? I suppose that's partly why you're asking to build from source, if possible.

2024-07-05 14:21 UTC, aurianer commented on var/spack/repos/builtin/packages/py-wandb/package.py
> +        )
So for the 0.13.9, the source distribution was available on pypi, installing it for arm means that it would be built from source. For the 0.17.3 release there is unfortunately no signed source distribution availble on pypi (and no signed one on github either), so I decided to go with the built distribution

2024-07-05 15:03 UTC, msimberg commented on var/spack/repos/builtin/packages/py-wandb/package.py
> +        )
Thanks for explaining!

Follow-up question 1: Would 0.16.6 be sufficient? It seems to have a source release with hashes on pypi?

Follow-up question 2: Is there reason to believe that pypi's hashes are more reliable than checking the hash of the source archive on GitHub and hardcoding that hash?

The signing of their releases on GitHub indeed seems a bit erratic... If I had a choice, I'd definitely go for unsigned sources over an unsigned binary.

2024-07-05 15:11 UTC, aurianer commented on var/spack/repos/builtin/packages/py-wandb/package.py
> +        )
1. I would have to ask swiss-ai, it's a requirement they needed for the pytorch uenv recipe I'm trying to build.
2. It assumes you trust the first download ;) but yes I can do that if the binaries are not the way to go. And in that case, should I just remove the pypi reference and just use git for all versions?

2024-07-11 09:54 UTC, aurianer commented on var/spack/repos/builtin/packages/py-wandb/package.py
> +        )
I tried building from source from the git repo archive and the installation is failing, I need to investigate further so I'll change this PR state to draft.

2025-06-16 05:55 UTC, alalazo commented
Closing, since we moved the package repository. Feel free to reopen at / migrate to https://github.com/spack/spack-packages if you want to continue work on this.

2025-06-16 05:55 UTC, closed without merging