mptensor: Changed skiptest, test name, and added docstring
LLNL/spack pull request #44909
Opened 2024-06-26 22:07 UTC by AcriusWinter

2024-06-26 22:10 UTC, AcriusWinter commented
INSTALLS:
```
$ spack install mptensor ~mpi
$ spack install mptensor +mpi
```

```Command exited with status 127:
    '/usr/WS2/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/openmpi-5.0.3-q3n3hhzcbss6wtibu7o7lprjsg6arnpq/bin/mpirun' '-n' '1' 'tensor_test.out'


1 error found in test log:
     68    ar rvu libmptensor.a ./index.o ./lapack/matrix_lapack.o ./mpi_wrapper.o ./rsvd.o ./scalapack/blacsgrid.o ./scalapac
           k/matrix_scalapack.o ./tensor.o
     69    make[1]: Leaving directory '/usr/WS2/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/mptensor-0.3.0-jov
           ee5sojqd5fs3c6xrr3wgaypcjhbfe/.spack/test/src'
     70    /usr/WS2/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/openmpi-5.0.3-q3n3hhzcbss6wtibu7o7lprjsg6arnpq
           /bin/mpic++ -c transpose.cc -L/usr/WS2/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/netlib-scalapack
           -2.2.0-7j6nmwmwg4ftaymnbtovnkvputdgkpzf/lib -L/usr/WS2/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/
           intel-oneapi-mkl-2024.0.0-prcfbp7aepegdny77xcclpaqndw3oyn7/mkl/2024.0/lib -L/lib64 -lscalapack -lmkl_intel_lp64 -lm
           kl_sequential -lmkl_core -lpthread -lm -ldl -std=c++11 -I../include
     71    /usr/WS2/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/openmpi-5.0.3-q3n3hhzcbss6wtibu7o7lprjsg6arnpq
           /bin/mpic++ -o tensor_test.out arithmetic.o contract.o eigh.o eigh_general.o eigh_rank2.o mpi_tool.o qr.o qr_rank2.
           o reshape.o set_slice.o slice.o svd.o tensor_test.o tensordot.o trace.o transpose.o ../src/libmptensor.a -L/usr/WS2
           /spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/netlib-scalapack-2.2.0-7j6nmwmwg4ftaymnbtovnkvputdgkpz
           f/lib -L/usr/WS2/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/intel-oneapi-mkl-2024.0.0-prcfbp7aepeg
           dny77xcclpaqndw3oyn7/mkl/2024.0/lib -L/lib64 -lscalapack -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm
            -ldl -std=c++11 -I../include
     72    ==> [2024-06-26-15:07:39.034562] '/usr/WS2/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/openmpi-5.0.
           3-q3n3hhzcbss6wtibu7o7lprjsg6arnpq/bin/mpirun' '-n' '1' 'tensor_test.out'
     73    tensor_test.out: error while loading shared libraries: libscalapack.so: cannot open shared object file: No such fil
           e or directory
  >> 74    FAILED: Mptensor::test_mpi: Command exited with status 127:
     75        '/usr/WS2/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/openmpi-5.0.3-q3n3hhzcbss6wtibu7o7lprjsg6
           arnpq/bin/mpirun' '-n' '1' 'tensor_test.out'
     76      File "/usr/workspace/spack/bin/spack", line 52, in <module>


See test log for details:
  /g/g16/.spack/test/c3wdmtlb5nwxmcdwrlgtyegaq7jqic3d/mptensor-0.3.0-jovee5s-test-out.txt

======================== 1 skipped, 1 failed of 2 specs ========================

See mptensor-0.3.0-qx4xpxf test results at:
  /g/g16/.spack/test/c3wdmtlb5nwxmcdwrlgtyegaq7jqic3d/mptensor-0.3.0-qx4xpxf-test-out.txt

See mptensor-0.3.0-jovee5s test results at:
  /g/g16/.spack/test/c3wdmtlb5nwxmcdwrlgtyegaq7jqic3d/mptensor-0.3.0-jovee5s-test-out.txt
==> Error: 1 test(s) in the suite failed.
```

2024-06-26 22:33 UTC, AcriusWinter commented
Note: The test didn't work originally, but these changes don't do anything that actually modifies the test. The docstring, test rename, and SkipTest match the new convention

2024-07-09 22:39 UTC, tldahlgren requested changes
See comments for specific changes.

2024-07-09 22:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/mptensor/package.py
> +            makefile.filter("CXXFLAGS =.*", "CXXFLAGS ={0}".format(self.compiler.cxx11_flag))
This cleanup should be done *once* in `setup_build_tests`.  See #38633 for a draft that makes this change.

2024-07-09 22:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/mptensor/package.py
> +        with working_dir(join_path(self.install_test_root, "tests"), create=False):
This should *not* be running from the installation test root.  Same recommendation to look at the draft PR for this work.

2024-07-09 22:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/mptensor/package.py
> +            make("LDFLAGS={0}".format(math_libs.ld_flags))
Doesn't this work as an f-string (instead of using `format`)?

2024-07-09 22:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/mptensor/package.py
> +            makefile.filter("g++", "{0}".format(spack_cxx), string=True)
Use an f-string instead of `format` here.

2024-07-09 22:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/mptensor/package.py
> +            makefile.filter("CXXFLAGS =.*", "CXXFLAGS ={0}".format(self.compiler.cxx11_flag))
Same comment about f-strings vs. `format`.

2024-07-09 23:22 UTC, tldahlgren commented
While I have issues with how this is implemented, the current outputs I am getting are:

```
$ spack -v test run mptensor
==> Spack test 43pimi7m5avyi3i4w3upoqot23wq23mp
==> Testing package mptensor-0.3.0-vp55bra
...
==> [2024-07-09-16:19:28.726417] test: test_mpi: test with +mpi
SKIPPED: Mptensor::test_mpi: Package must be installed with +mpi
==> [2024-07-09-16:19:28.728888] Completed testing
==> [2024-07-09-16:19:28.729027] 
======================= SUMMARY: mptensor-0.3.0-vp55bra ========================
Mptensor::test_mpi .. SKIPPED
============================= 1 skipped of 1 parts =============================
==> Testing package mptensor-0.3.0-avompyx
...
==> [2024-07-09-16:19:31.510350] test: test_mpi: test with +mpi
==> [2024-07-09-16:19:31.510798] Warning: The 'pkg.install_test_root' property is deprecated with removal expected v0.23. Use 'install_test_root(pkg)' instead.
==> [2024-07-09-16:19:31.511528] 'make' '-j16' 'clean'
...
==> [2024-07-09-16:19:33.849365] '$spack/opt/spack/linux-rhel8-x86_64_v3/gcc-12.1.1/openmpi-5.0.3-tssouwvohaz546p3n64yvo24aciub4sq/bin/mpirun' '-n' '1' 'tensor_test.out'
--------------------------------------------------------------------------
WARNING: Open MPI failed to open the /dev/knem device due to a local
error. Please check with your system administrator to get the problem
fixed, or set the smsc MCA variable to "^knem" to silence this warning
and run without knem support.

Open MPI will try to fall back on another single-copy mechanism if one
is available.  This may result in lower performance.

  Local host: borax5
  Errno:      2 (No such file or directory)
--------------------------------------------------------------------------
Usage: a.out N
Warning: assuming N=10
...
========================================
Test of mptensor PASSED !
PASSED: Mptensor::test_mpi
==> [2024-07-09-16:19:41.801623] Completed testing
==> [2024-07-09-16:19:41.801847] 
======================= SUMMARY: mptensor-0.3.0-avompyx ========================
Mptensor::test_mpi .. PASSED
============================= 1 passed of 1 parts ==============================
======================== 1 skipped, 1 passed of 2 specs ========================
```

2024-07-09 23:24 UTC, tldahlgren commented on var/spack/repos/builtin/packages/mptensor/package.py
> +        with working_dir(join_path(self.install_test_root, "tests"), create=False):
Where this is used, `self.install_test_root` needs to be replaced with `install_test_root(self)` as reflected in the warning:

```
Warning: The 'pkg.install_test_root' property is deprecated with removal expected v0.23. Use 'install_test_root(pkg)' instead.
```

2024-07-19 03:21 UTC, tldahlgren requested changes
Now that you cleaned up the cached Makefiles, you should be able to run the test from under the test stage directory.

2024-07-19 03:21 UTC, tldahlgren commented on var/spack/repos/builtin/packages/mptensor/package.py
> +        with working_dir(join_path(install_test_root(self), "tests"), create=False):
This needs to be using the files Spack copied from the cached directory.

2024-08-13 00:05 UTC, tldahlgren requested changes
See comments.

2024-08-13 00:05 UTC, tldahlgren commented on var/spack/repos/builtin/packages/mptensor/package.py
> +            mpiexec("-n", "1", "tensor_test.out")
At a minimum remove the comment; however, having `mpirun` and `mpiexec` can be "confusing"/"misleading".  Better to have the variable name match the executable (e.g., for `spack pkg grep`).  Suggest:

```suggestion
            mpirun = which(self.spec["mpi"].prefix.bin.mpirun)
            mpirun("-n", "1", "tensor_test.out")
```

2024-08-13 00:05 UTC, tldahlgren commented on var/spack/repos/builtin/packages/mptensor/package.py
> +    def test_mpi(self):
The name should relate to what is being tested, not the software used to launch the test.

2024-08-13 00:05 UTC, tldahlgren commented on var/spack/repos/builtin/packages/mptensor/package.py
> +            makefile.filter("CXXFLAGS =.*", "CXXFLAGS ={self.compiler.cxx11_flag}")
You need to add the `f` to the f-string.

2024-08-13 00:06 UTC, AcriusWinter commented on var/spack/repos/builtin/packages/mptensor/package.py
> +            makefile.filter("CXXFLAGS =.*", "CXXFLAGS ={self.compiler.cxx11_flag}")
```suggestion
            makefile.filter("CXXFLAGS =.*", f"CXXFLAGS ={self.compiler.cxx11_flag}")
```

2024-08-13 22:21 UTC, tldahlgren requested changes
See comments.

2024-08-13 22:21 UTC, tldahlgren commented on var/spack/repos/builtin/packages/mptensor/package.py
> +    def test_mptensor(self):
Adding the name of the package to `test_` is not descriptive of what is actually being tested.

2024-08-13 22:21 UTC, tldahlgren commented on var/spack/repos/builtin/packages/mptensor/package.py
> +        """test if mptensor works"""
The docstring isn't descriptive enough about what is actually being executed.

2024-08-13 22:21 UTC, tldahlgren approved these changes

2024-08-13 23:48 UTC, merged