Add huggingface hub versions
LLNL/spack pull request #44905
Opened 2024-06-26 17:10 UTC by aurianer

2024-06-27 09:15 UTC, alalazo requested changes

2024-06-27 09:15 UTC, alalazo commented on var/spack/repos/builtin/packages/py-huggingface-hub/package.py
> +    version("0.20.0", sha256="3b41e9e1cd8342d5e0b63f1921b6dbd03222215d2d4874f032a465421394e001")
Are all these versions really necessary, or can we just stick to the latest patch for each minor?

2024-06-27 09:15 UTC, alalazo commented on var/spack/repos/builtin/packages/py-huggingface-hub/package.py
> +    version("0.20.0", sha256="3b41e9e1cd8342d5e0b63f1921b6dbd03222215d2d4874f032a465421394e001")
Also, did you check if really nothing changed in the deps constraints?

2024-06-27 15:30 UTC, aurianer commented on var/spack/repos/builtin/packages/py-huggingface-hub/package.py
> +    version("0.20.0", sha256="3b41e9e1cd8342d5e0b63f1921b6dbd03222215d2d4874f032a465421394e001")
Right now we only need the latest version, so I can just add this one and I will add others progressively if needed.

2024-06-27 15:31 UTC, aurianer commented on var/spack/repos/builtin/packages/py-huggingface-hub/package.py
> +    version("0.20.0", sha256="3b41e9e1cd8342d5e0b63f1921b6dbd03222215d2d4874f032a465421394e001")
I didn't check the dependencies manually but I checked that it installs

2024-07-01 14:54 UTC, alalazo commented on var/spack/repos/builtin/packages/py-huggingface-hub/package.py
> +    version("0.20.0", sha256="3b41e9e1cd8342d5e0b63f1921b6dbd03222215d2d4874f032a465421394e001")
> Right now we only need the latest version, so I can just add this one and I will add others progressively if needed.

Yeah, let's do that

2024-07-02 11:32 UTC, aurianer commented
Updated, sorry for the delay

2024-07-03 06:35 UTC, alalazo approved these changes

2024-07-03 06:35 UTC, merged