care: add v0.13.0 and v0.12.0
LLNL/spack pull request #44936
Opened 2024-06-27 21:11 UTC by balos1

2024-06-27 21:17 UTC, davidbeckingsale requested changes
Please add @adayton1 as a maintainer.

2024-06-27 21:24 UTC, adayton1 commented on var/spack/repos/builtin/packages/care/package.py
> +    version(
There's now a 0.13.1 release as well.

2024-06-27 21:24 UTC, davidbeckingsale commented
Removing myself since Alan's here :)

2024-06-27 21:27 UTC, balos1 commented on var/spack/repos/builtin/packages/care/package.py
> +    version(
Added 👍

2024-06-27 21:41 UTC, adayton1 commented
v0.12.0 should depend on BLT v0.6.1 and v2024.02.0 versions of umpire, raja, and chai (it no longer depends directly on camp).

v0.13.0 should depend on BLT v0.6.2 and v2024.02.1 versions of umpire, raja, and chai.

v0.13.1 should depend on v2024.02.2 versions of raja and chai (umpire only has a v2024.02.1 release).

2024-06-27 21:45 UTC, adayton1 commented
> v0.12.0 should depend on BLT v0.6.1 and v2024.02.0 versions of umpire, raja, and chai (it no longer depends directly on camp).
> 
> v0.13.0 should depend on BLT v0.6.2 and v2024.02.1 versions of umpire, raja, and chai.
> 
> v0.13.1 should depend on v2024.02.2 versions of raja and chai (umpire only has a v2024.02.1 release).

If you want me to take care of updating the dependencies, let me know, though I will be on vacation starting on Monday for two weeks.

2024-06-27 23:53 UTC, tldahlgren approved these changes
Confirmed the three new commits.

2024-06-27 23:54 UTC, tldahlgren requested changes
According to @adayton1 there are dependency updates needed so I'll flag that here as needing to be done before the merge.

2024-06-27 23:54 UTC, balos1 commented
@adayton1 since you know the dependencies, yes, please go ahead and update them.

2024-06-28 23:36 UTC, adayton1 commented
> @adayton1 since you know the dependencies, yes, please go ahead and update them.

My apologies, I have not had time to complete this. But I'm thinking something like the following if you are eager to get this in:

```
    depends_on("cmake@3.8:", type="build")
    depends_on("cmake@3.9:", type="build", when="+cuda")
    depends_on("cmake@3.18:", type="build", when="@0.12.0:")
    depends_on("cmake@3.21:", type="build", when="@0.12.0:+rocm")

    depends_on("blt")
    depends_on("blt@0.6.2:", type="build", when="@0.13.0:")
    depends_on("blt@0.6.1:", type="build", when="@0.12.0:")
    depends_on("blt@0.4.0:", type="build", when="@0.3.1:")
    depends_on("blt@:0.3.6", type="build", when="@:0.3.0")
    conflicts("^blt@:0.3.6", when="+rocm")

    depends_on("camp", when="@:0.11.1")

    depends_on("umpire")
    depends_on("umpire@2024.02.1:", when="@0.13.0:")
    depends_on("umpire@2024.02.0:", when="@0.12.0:")

    depends_on("raja")
    depends_on("raja@2024.02.2:", when="@0.13.1:")
    depends_on("raja@2024.02.1:", when="@0.13.0:")
    depends_on("raja@2024.02.0:", when="@0.12.0:")

    depends_on("chai+enable_pick+raja")
    depends_on("chai@2024.02.2:", when="@0.13.1:")
    depends_on("chai@2024.02.1:", when="@0.13.0:")
    depends_on("chai@2024.02.0:", when="@0.12.0:")
```

2024-07-01 21:30 UTC, balos1 commented
I went ahead and added the dependencies @adayton1/

2024-07-01 21:34 UTC, white238 approved these changes
Thanks @balos1 and @adayton1 !

@tldahlgren since this followed what @adayton1 recommended can we get this merged?

2024-07-01 21:38 UTC, tldahlgren approved these changes
Re-confirmed commits and double-checked dependencies matching recommended.

2024-07-01 22:45 UTC, merged