librsvg: fix #44175
LLNL/spack pull request #44989
Opened 2024-07-01 22:49 UTC by teaguesterling

This removes the `librsvg` dependency from `cairo+svg`, which is not needed to build and creates a cyclic, unsatisfiable dependency. The `librsvg` dependency is needed to test Cairo's SVG functionality, but doesn't seem to affect anything else.

2024-07-02 18:59 UTC, teaguesterling commented
@spackbot rerun pipeline

2024-07-02 21:21 UTC, tldahlgren requested changes
There are additional checks of `+svg` (related to `darwin`) that should be removed since you're removing the variant.

I am curious if this change applies for all versions listed or from a certain version on.

@adamjstewart @tgamblin @alexrichert Are any of you interested in reviewing this PR?

2024-07-02 22:07 UTC, teaguesterling commented
We're not removing the variant here, but instead removing the `depends_on` that is associated with it as it is (as far as I can gather) unnecessary and causes spack to break. The change to the variant  line was just to fix a small typo.

2024-07-03 10:24 UTC, adamjstewart commented
At first I thought this was something I wanted to review, but then I realized I added the SVG variant to imagemagick (#41956), not to cairo (#14092). @iarspider may want to review this, but I've never used this feature, so I'll unsubscribe from this PR and let others handle the reviewing process.

2024-07-03 10:25 UTC, adamjstewart commented
Likely also fixes #24271.

2024-07-03 10:47 UTC, iarspider commented
LGTM

2024-07-03 20:51 UTC, tldahlgren commented
> We're not removing the variant here

🤦

2024-07-03 20:51 UTC, tldahlgren approved these changes

2024-07-03 20:52 UTC, merged