migraphx: Old to new test API
LLNL/spack pull request #44988
Opened 2024-07-01 22:39 UTC by AcriusWinter

2024-07-01 22:40 UTC, AcriusWinter commented
PASSED: Migraphx::test
==> [2024-07-01-15:40:31.442503] Completed testing
==> [2024-07-01-15:40:31.442700] 
======================= SUMMARY: migraphx-6.1.1-kzk2uav ========================
Migraphx::test .. PASSED
============================= 1 passed of 1 parts ==============================
============================== 1 passed of 1 spec ==============================

2024-07-12 18:57 UTC, tldahlgren requested changes
Typo and confused by what is meant to be run.

2024-07-12 18:57 UTC, tldahlgren commented on var/spack/repos/builtin/packages/migraphx/package.py
> +    def test_dirvers(self):
```suggestion
    def test_drivers(self):
```

2024-07-12 18:57 UTC, tldahlgren commented on var/spack/repos/builtin/packages/migraphx/package.py
> +        exe = which("migraphx-driver", "migraphx-hiprtc-driver")
What is the goal here?

2024-07-19 03:14 UTC, tldahlgren requested changes

2024-07-19 03:14 UTC, tldahlgren commented on var/spack/repos/builtin/packages/migraphx/package.py
> +        exe()
This doesn't look like a conversion of the original implementation but a re-write.  Does the original not work (after a re-write)?

2024-08-08 23:30 UTC, tldahlgren requested changes
See comments.

2024-08-08 23:30 UTC, tldahlgren commented on var/spack/repos/builtin/packages/migraphx/package.py
>          with working_dir(test_dir, create=True):
This is running from within the install prefix, which it is not supposed to do.

2024-08-08 23:30 UTC, tldahlgren commented on var/spack/repos/builtin/packages/migraphx/package.py
>          with working_dir(test_dir, create=True):
Also, that directory should already be there if the software was successfully installed (so `create=True` is irrelevant).

2024-08-08 23:30 UTC, tldahlgren commented on var/spack/repos/builtin/packages/migraphx/package.py
>          with working_dir(test_dir, create=True):
Is it not possible to run using the Executable form of `self.spec["migraphx"].prefix.bin.UnitTests`?

2024-08-12 23:25 UTC, tldahlgren requested changes
Looks good.  A minor fix.

2024-08-12 23:25 UTC, tldahlgren commented on var/spack/repos/builtin/packages/migraphx/package.py
> +        unit_tests = which("UnitTests")
Since the original is using the installed directory, the Executable should include the installation path.

2024-08-12 23:59 UTC, AcriusWinter commented on var/spack/repos/builtin/packages/migraphx/package.py
> +        unit_tests = which("UnitTests")
```suggestion
        unit_tests = which(self.prefix.bin.UnitTests)
```

2024-08-13 00:01 UTC, tldahlgren commented on var/spack/repos/builtin/packages/migraphx/package.py
> +        """Test drivers"""
```suggestion
    def test_unit_tests(self):
        """Run installed UnitTests"""
```

2024-08-13 00:03 UTC, tldahlgren approved these changes
LGTM, thanks.

2024-08-13 01:29 UTC, merged