rocm-opencl: old to new test API
LLNL/spack pull request #45065
Opened 2024-07-05 17:33 UTC by AcriusWinter

2024-07-05 17:34 UTC, AcriusWinter commented
OLD ERROR:
```
==> Spack test weeinjh3rwfbb62dalefohornoe46moj
==> Testing package rocm-opencl-6.1.1-gsd3frv
==> Error: TestFailure: 2 tests failed.


Failed to find executable 'ocltst'




Failed to find executable 'ocltst'
```

NEW ERROR:
```
'NoneType' object is not callable


1 error found in test log:
     47      File "/usr/WS2/lawrence31/spack/lib/spack/spack/install_test.py", line 720, in process_test_p
           arts
     48        test_fn(pkg)
     49      File "/usr/WS2/lawrence31/spack/var/spack/repos/builtin/packages/rocm-opencl/package.py", lin
           e 175, in test_rocm_opencl
     50      File "/collab/usr/gapps/python/build/spack-toss4.1/var/spack/environments/python/._view/75prb
           56irmif5ejtirjthpx6kq3gqo52/lib/python3.9/contextlib.py", line 137, in __exit__
     51        self.gen.throw(typ, value, traceback)
     52    ==> [2024-07-05-10:28:29.960324] test: test_rocm_opencl_perf: Test perf
  ^[[0;91m>> 53    FAILED: RocmOpencl::test_rocm_opencl_perf: 'NoneType' object is not callable^[[0m
     54      File "/usr/WS2/lawrence31/spack/bin/spack", line 52, in <module>
     55        sys.exit(main())
     56      File "/usr/WS2/lawrence31/spack/lib/spack/spack_installable/main.py", line 42, in main
     57        sys.exit(spack.main.main(argv))
     58      File "/usr/WS2/lawrence31/spack/lib/spack/spack/main.py", line 1069, in main
     59        return _main(argv)
```

2024-07-16 01:01 UTC, tldahlgren requested changes
This is a good start.  There are some basic changes noted in the comments.

2024-07-16 01:01 UTC, tldahlgren commented on var/spack/repos/builtin/packages/rocm-opencl/package.py
>          with working_dir(test_dir, create=True):
This should *not* be running under the installation prefix so that needs to be changed (if possible).

2024-07-16 01:01 UTC, tldahlgren commented on var/spack/repos/builtin/packages/rocm-opencl/package.py
> +                exe = which("ocltst")
This only needs to be done once in this case so you can move this above the `test_part()` context manager.

2024-07-16 01:03 UTC, tldahlgren commented on var/spack/repos/builtin/packages/rocm-opencl/package.py
> +                exe = which("ocltst")
Then you don't need to re-instantiate the `Executable` again at line 177.

2024-07-16 02:24 UTC, tldahlgren commented
@renjithravindrankannath @srekolam Are we getting the type of result one should expect from running the stand-alone tests (see below)?  If not, what are we missing?

After doing some digging to figure out what is going on and switch the test to run from the test stage ([commit](https://github.com/spack/spack/pull/45065/commits/e639b8bbdd1575498e6ec8e93f954c1c1822abbf)), I get the following results:

```
spack -v test run rocm-opencl
==> Spack test sbu5pgu7vvxkirq7ynv4v2667emz7ky5
==> Testing package rocm-opencl-6.1.1-ethb6s3
==> [2024-07-15-19:20:48.313700] test: test_ocltst: Run ocltst checks
==> [2024-07-15-19:20:48.316661] test: test_ocltst_runtime: check runtime
...

clGetDeviceIDs failed
FAILED: RocmOpencl::test_ocltst_runtime: Command exited with status 1:
...
==> [2024-07-15-19:20:48.440133] test: test_ocltst_perf: check perf
...

clGetDeviceIDs failed
FAILED: RocmOpencl::test_ocltst_perf: Command exited with status 1:
...
FAILED: RocmOpencl::test_ocltst
==> [2024-07-15-19:20:48.492940] Completed testing
==> [2024-07-15-19:20:48.493062] 
====================== SUMMARY: rocm-opencl-6.1.1-ethb6s3 ======================
RocmOpencl::test_ocltst_runtime .. FAILED
RocmOpencl::test_ocltst_perf .. FAILED
RocmOpencl::test_ocltst .. FAILED
============================= 3 failed of 3 parts ==============================
```

2024-07-17 07:46 UTC, srekolam commented
clGetDeviceIDs error is not seen in our environment as far as i remember. If this can be submitted as a issue and assigned, we can look into it further

2024-07-17 17:12 UTC, tldahlgren commented
> clGetDeviceIDs error is not seen in our environment as far as i remember. If this can be submitted as a issue and assigned, we can look into it further

@srekolam @renjithravindrankannath Do the changes to the test method otherwise look appropriate for all listed (or at least not deprecated) versions?

2024-07-18 06:04 UTC, renjithravindrankannath approved these changes
LGTM. With these changes `spack -v test run rocm-opencl` was able to run successfully in Ubuntu22, Rhel8 and Centos8.

2024-07-18 16:34 UTC, tldahlgren commented
> LGTM. With these changes `spack -v test run rocm-opencl` was able to run successfully in Ubuntu22, Rhel8 and Centos8.

Thank you for checking!

2024-07-18 16:35 UTC, tldahlgren approved these changes

2024-07-18 16:35 UTC, merged