hypre: old to new test API
LLNL/spack pull request #45066
Opened 2024-07-05 18:40 UTC by AcriusWinter

2024-07-05 18:40 UTC, AcriusWinter commented
Old Error:
```
==> Testing package hypre-2.31.0-xy5hhtl
==> Error: TestFailure: 2 tests failed.


Command exited with status 127:
    '/g/g16/lawrence31/.spack/test/q2mghiyopeegq445bo4acvuxtdhk4sk3/hypre-2.31.0-xy5hhtl/cache/hypre/src/examples/ex5big'
/g/g16/lawrence31/.spack/test/q2mghiyopeegq445bo4acvuxtdhk4sk3/hypre-2.31.0-xy5hhtl/cache/hypre/src/examples/ex5big: error while loading shared libraries: libHYPRE-2.31.0.so: cannot open shared object file: No such file or directory



1 error found in test log:
     45    ==> [2024-07-05-10:40:30.099630] test: test_ex5big: ensuring ./ex5big runs
     46    ==> [2024-07-05-10:40:30.100921] Expecting return code in [0]
     47    ==> [2024-07-05-10:40:30.101426] '/g/g16/lawrence31/.spack/test/q2mghiyopeegq445bo4acvuxtdhk4sk
           3/hypre-2.31.0-xy5hhtl/cache/hypre/src/examples/ex5big'
     48    /g/g16/lawrence31/.spack/test/q2mghiyopeegq445bo4acvuxtdhk4sk3/hypre-2.31.0-xy5hhtl/cache/hypre
           /src/examples/ex5big: error while loading shared libraries: libHYPRE-2.31.0.so: cannot open sha
           red object file: No such file or directory
     49    FAILED: Hypre::test_ex5big: Command exited with status 127:
     50        '/g/g16/lawrence31/.spack/test/q2mghiyopeegq445bo4acvuxtdhk4sk3/hypre-2.31.0-xy5hhtl/cache/
           hypre/src/examples/ex5big'
  >> 51    /g/g16/lawrence31/.spack/test/q2mghiyopeegq445bo4acvuxtdhk4sk3/hypre-2.31.0-xy5hhtl/cache/hypre
           /src/examples/ex5big: error while loading shared libraries: libHYPRE-2.31.0.so: cannot open sha
           red object file: No such file or directory
     52    
     53      File "/usr/WS2/lawrence31/spack/bin/spack", line 52, in <module>



Command exited with status 127:
    '/g/g16/lawrence31/.spack/test/q2mghiyopeegq445bo4acvuxtdhk4sk3/hypre-2.31.0-xy5hhtl/cache/hypre/src/examples/ex15big'
/g/g16/lawrence31/.spack/test/q2mghiyopeegq445bo4acvuxtdhk4sk3/hypre-2.31.0-xy5hhtl/cache/hypre/src/examples/ex15big: error while loading shared libraries: libHYPRE-2.31.0.so: cannot open shared object file: No such file or directory



1 error found in test log:
     100    ==> [2024-07-05-10:40:30.138580] test: test_ex15big: ensuring ./ex15big runs
     101    ==> [2024-07-05-10:40:30.139642] Expecting return code in [0]
     102    ==> [2024-07-05-10:40:30.140021] '/g/g16/lawrence31/.spack/test/q2mghiyopeegq445bo4acvuxtdhk4s
            k3/hypre-2.31.0-xy5hhtl/cache/hypre/src/examples/ex15big'
     103    /g/g16/lawrence31/.spack/test/q2mghiyopeegq445bo4acvuxtdhk4sk3/hypre-2.31.0-xy5hhtl/cache/hypr
            e/src/examples/ex15big: error while loading shared libraries: libHYPRE-2.31.0.so: cannot open 
            shared object file: No such file or directory
     104    FAILED: Hypre::test_ex15big: Command exited with status 127:
     105        '/g/g16/lawrence31/.spack/test/q2mghiyopeegq445bo4acvuxtdhk4sk3/hypre-2.31.0-xy5hhtl/cache
            /hypre/src/examples/ex15big'
  >> 106    /g/g16/lawrence31/.spack/test/q2mghiyopeegq445bo4acvuxtdhk4sk3/hypre-2.31.0-xy5hhtl/cache/hypr
            e/src/examples/ex15big: error while loading shared libraries: libHYPRE-2.31.0.so: cannot open 
            shared object file: No such file or directory
     107    
     108      File "/usr/WS2/lawrence31/spack/bin/spack", line 52, in <module>
     109        sys.exit(main())
     110      File "/usr/WS2/lawrence31/spack/lib/spack/spack_installable/main.py", line 42, in main
     111        sys.exit(spack.main.main(argv))
     112      File "/usr/WS2/lawrence31/spack/lib/spack/spack/main.py", line 1069, in main
```

New Error:
```
==> Testing package hypre-2.20.0-qricngq
==> Error: TestFailure: 2 tests failed.


Command exited with status 127:
    'ex5big'


1 error found in test log:
     38    mpicc -o ex15big ex15big.o -g -Wall -L/usr/WS2/lawrence31/spack/opt/spack/linux-rhel8-broadwell
           /gcc-10.3.1/hypre-2.20.0-qricngqyppqva4lovueipabrbpnkry2i/lib -lHYPRE -lm -lstdc++
     39    ld: warning: libmpi.so.40, needed by /usr/WS2/lawrence31/spack/opt/spack/linux-rhel8-broadwell/
           gcc-10.3.1/hypre-2.20.0-qricngqyppqva4lovueipabrbpnkry2i/lib/libHYPRE.so, may conflict with lib
           mpi.so.12
     40    PASSED: Hypre::test_hypre_build
     41    ==> [2024-07-05-11:37:13.932959] test: test_hypre_ex5big: Ensuring ex5big runs
     42    ==> [2024-07-05-11:37:13.934924] 'ex5big'
     43    ex5big: error while loading shared libraries: libHYPRE-2.20.0.so: cannot open shared object fil
           e: No such file or directory
  >> 44    FAILED: Hypre::test_hypre_ex5big: Command exited with status 127:
     45        'ex5big'
     46      File "/usr/WS2/lawrence31/spack/bin/spack", line 52, in <module>
     47        sys.exit(main())
     48      File "/usr/WS2/lawrence31/spack/lib/spack/spack_installable/main.py", line 42, in main
     49        sys.exit(spack.main.main(argv))
     50      File "/usr/WS2/lawrence31/spack/lib/spack/spack/main.py", line 1069, in main



Command exited with status 127:
    'ex15big'


1 error found in test log:
     90      File "/usr/WS2/lawrence31/spack/var/spack/repos/builtin/packages/hypre/package.py", line 408,
            in test_hypre
     91      File "/collab/usr/gapps/python/build/spack-toss4.1/var/spack/environments/python/._view/75prb
           56irmif5ejtirjthpx6kq3gqo52/lib/python3.9/contextlib.py", line 137, in __exit__
     92        self.gen.throw(typ, value, traceback)
     93    ==> [2024-07-05-11:37:13.978870] test: test_hypre_ex15big: Ensuring ex15big runs
     94    ==> [2024-07-05-11:37:13.981261] 'ex15big'
     95    ex15big: error while loading shared libraries: libHYPRE-2.20.0.so: cannot open shared object fi
           le: No such file or directory
  >> 96    FAILED: Hypre::test_hypre_ex15big: Command exited with status 127:
     97        'ex15big'
     98      File "/usr/WS2/lawrence31/spack/bin/spack", line 52, in <module>


See test log for details:
  /g/g16/lawrence31/.spack/test/q2mghiyopeegq445bo4acvuxtdhk4sk3/hypre-2.20.0-qricngq-test-out.txt

============================= 2 failed of 2 specs ==============================

See hypre-2.31.0-xy5hhtl test results at:
  /g/g16/lawrence31/.spack/test/q2mghiyopeegq445bo4acvuxtdhk4sk3/hypre-2.31.0-xy5hhtl-test-out.txt

See hypre-2.20.0-qricngq test results at:
  /g/g16/lawrence31/.spack/test/q2mghiyopeegq445bo4acvuxtdhk4sk3/hypre-2.20.0-qricngq-test-out.txt
==> Error: 2 test(s) in the suite failed.
```

2024-07-16 00:49 UTC, tldahlgren requested changes
Good start.  There's some reorganization and tightening of the code that can be done.  (See comments.)

2024-07-16 00:49 UTC, tldahlgren commented on var/spack/repos/builtin/packages/hypre/package.py
> +                exe("HYPRE_DIR={0}".format(self.prefix), "bigint")
Convert to f-string.

2024-07-16 00:49 UTC, tldahlgren commented on var/spack/repos/builtin/packages/hypre/package.py
> +                    if not os.path.exists("./" + exeName):
Good catch for skipping an executable.

To clean it up a bit, you could check for the path existing *before* calling `which()` or do what you've done in other PRs by skipping the test if `exe` is `None`.

2024-07-16 00:49 UTC, tldahlgren commented on var/spack/repos/builtin/packages/hypre/package.py
> +                exe("HYPRE_DIR={0}".format(self.prefix), "bigint")
Running `make` shouldn't be a test part (anymore) since one of the goals of the new API was to make test "recipes" more like build "recipes".

2024-07-16 00:49 UTC, tldahlgren commented on var/spack/repos/builtin/packages/hypre/package.py
> +                    exe()
The structure here should be very similar to that given in the docs (https://spack.readthedocs.io/en/latest/packaging_guide.html#saving-build-and-install-time-files) for `MyLibPackage`'s tests.

2024-07-19 02:52 UTC, tldahlgren requested changes
See comments.

2024-07-19 02:52 UTC, tldahlgren commented on var/spack/repos/builtin/packages/hypre/package.py
> +            exe(f"HYPRE_DIR={self.prefix}", "bigint")
As we discussed, this isn't supposed to be a separate test part anymore.

2024-07-19 02:52 UTC, tldahlgren commented on var/spack/repos/builtin/packages/hypre/package.py
> +                with working_dir(self._cached_tests_work_dir):
You really only need to use the `working_dir` context manager once for the build *and* running the tests.

2024-08-09 22:19 UTC, tldahlgren approved these changes

2024-08-11 08:28 UTC, merged