hypre-cmake: old to new test API
LLNL/spack pull request #45144
Opened 2024-07-09 21:30 UTC by AcriusWinter

2024-07-09 21:31 UTC, AcriusWinter commented
Old Error:
```
==> Error: TestFailure: 1 test failed.


Command exited with status 2:
    '/usr/bin/make' 'HYPRE_DIR=/usr/WS2/lawrence31/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/hypre-cmake-2.22.0-6y5p64ft4ipfu7m2i7gzdl3oxb6q6lb3' 'bigint'
mpicc -g -Wall -I/usr/WS2/lawrence31/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/hypre-cmake-2.22.0-6y5p64ft4ipfu7m2i7gzdl3oxb6q6lb3/include  -c ex5big.c
mpicc -o ex5big ex5big.o -g -Wall -L/usr/WS2/lawrence31/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/hypre-cmake-2.22.0-6y5p64ft4ipfu7m2i7gzdl3oxb6q6lb3/lib -lHYPRE -lm -lstdc++
ex5big.c(341): warning #181: argument of type "HYPRE_Int={int}" is incompatible with format "%lld", expecting argument of type "long long"
           printf("Iterations = %lld\n", num_iterations);
                                         ^

ex5big.c(375): warning #181: argument of type "HYPRE_Int={int}" is incompatible with format "%lld", expecting argument of type "long long"
           printf("Iterations = %lld\n", num_iterations);
                                         ^

ex5big.c(423): warning #181: argument of type "HYPRE_Int={int}" is incompatible with format "%lld", expecting argument of type "long long"
           printf("Iterations = %lld\n", num_iterations);
                                         ^

ex5big.c(477): warning #181: argument of type "HYPRE_Int={int}" is incompatible with format "%lld", expecting argument of type "long long"
           printf("Iterations = %lld\n", num_iterations);
                                         ^

ex5big.c(539): warning #181: argument of type "HYPRE_Int={int}" is incompatible with format "%lld", expecting argument of type "long long"
           printf("Iterations = %lld\n", num_iterations);
                                         ^

ld: cannot find -lHYPRE
make: *** [Makefile:116: ex5big] Error 1



1 error found in test log:
     52    
     53    ex5big.c(539): warning #181: argument of type "HYPRE_Int={int}" is incompatible with format "%lld", expecting a
           rgument of type "long long"
     54               printf("Iterations = %lld\n", num_iterations);
     55                                             ^
     56    
     57    ld: cannot find -lHYPRE
  >> 58    make: *** [Makefile:116: ex5big] Error 1
     59    
     60      File "/usr/WS2/lawrence31/spack/bin/spack", line 52, in <module>


See test log for details:
  /g/g16/lawrence31/.spack/test/akyzwcyzsq375pjbcxk4y5fbbtjbxz6v/hypre-cmake-2.22.0-6y5p64f-test-out.txt

============================== 1 failed of 1 spec ==============================
```

New Error:
```==> Error: TestFailure: 3 tests failed.


Command exited with status 2:
    '/usr/bin/make' 'HYPRE_DIR=/usr/WS2/lawrence31/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/hypre-cmake-2.22.0-6y5p64ft4ipfu7m2i7gzdl3oxb6q6lb3' 'bigint'


1 error found in test log:
     24               printf("Iterations = %lld\n", num_iterations);
     25                                             ^
     26    
     27    mpicc -o ex5big ex5big.o -g -Wall -L/usr/WS2/lawrence31/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/hypre-
           cmake-2.22.0-6y5p64ft4ipfu7m2i7gzdl3oxb6q6lb3/lib -lHYPRE -lm -lstdc++
     28    ld: cannot find -lHYPRE
     29    make: *** [Makefile:116: ex5big] Error 1
  >> 30    FAILED: HypreCmake::test_hypre_cmake_build: Command exited with status 2:
     31        '/usr/bin/make' 'HYPRE_DIR=/usr/WS2/lawrence31/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/hypre-cmake
           -2.22.0-6y5p64ft4ipfu7m2i7gzdl3oxb6q6lb3' 'bigint'
     32      File "/usr/WS2/lawrence31/spack/bin/spack", line 52, in <module>
     33        sys.exit(main())
     34      File "/usr/WS2/lawrence31/spack/lib/spack/spack_installable/main.py", line 42, in main
     35        sys.exit(spack.main.main(argv))
     36      File "/usr/WS2/lawrence31/spack/lib/spack/spack/main.py", line 1070, in main



'NoneType' object is not callable


1 error found in test log:
     74      File "/usr/WS2/lawrence31/spack/lib/spack/spack/install_test.py", line 720, in process_test_parts
     75        test_fn(pkg)
     76      File "/usr/WS2/lawrence31/spack/var/spack/repos/builtin/packages/hypre-cmake/package.py", line 112, in test_h
           ypre_cmake
     77      File "/collab/usr/gapps/python/build/spack-toss4.1/var/spack/environments/python/._view/75prb56irmif5ejtirjth
           px6kq3gqo52/lib/python3.9/contextlib.py", line 137, in __exit__
     78        self.gen.throw(typ, value, traceback)
     79    ==> [2024-07-09-14:28:18.860022] test: test_hypre_cmake_build: Ensuring ./ex5big runs
  >> 80    FAILED: HypreCmake::test_hypre_cmake_build: 'NoneType' object is not callable
     81      File "/usr/WS2/lawrence31/spack/bin/spack", line 52, in <module>
     82        sys.exit(main())
     83      File "/usr/WS2/lawrence31/spack/lib/spack/spack_installable/main.py", line 42, in main
     84        sys.exit(spack.main.main(argv))
     85      File "/usr/WS2/lawrence31/spack/lib/spack/spack/main.py", line 1070, in main
     86        return _main(argv)



'NoneType' object is not callable


1 error found in test log:
     123      File "/usr/WS2/lawrence31/spack/lib/spack/spack/install_test.py", line 720, in process_test_parts
     124        test_fn(pkg)
     125      File "/usr/WS2/lawrence31/spack/var/spack/repos/builtin/packages/hypre-cmake/package.py", line 119, in test_
            hypre_cmake
     126      File "/collab/usr/gapps/python/build/spack-toss4.1/var/spack/environments/python/._view/75prb56irmif5ejtirjt
            hpx6kq3gqo52/lib/python3.9/contextlib.py", line 137, in __exit__
     127        self.gen.throw(typ, value, traceback)
     128    ==> [2024-07-09-14:28:18.870486] test: test_hypre_cmake_build: Ensuring ./ex15big runs
  >> 129    FAILED: HypreCmake::test_hypre_cmake_build: 'NoneType' object is not callable
     130      File "/usr/WS2/lawrence31/spack/bin/spack", line 52, in <module>
     131        sys.exit(main())
     132      File "/usr/WS2/lawrence31/spack/lib/spack/spack_installable/main.py", line 42, in main
     133        sys.exit(spack.main.main(argv))
     134      File "/usr/WS2/lawrence31/spack/lib/spack/spack/main.py", line 1070, in main
     135        return _main(argv)


See test log for details:
  /g/g16/lawrence31/.spack/test/akyzwcyzsq375pjbcxk4y5fbbtjbxz6v/hypre-cmake-2.22.0-6y5p64f-test-out.txt

============================== 1 failed of 1 spec ==============================
```

2024-07-19 02:32 UTC, tldahlgren requested changes
See comments for needed changes.

2024-07-19 02:32 UTC, tldahlgren commented on var/spack/repos/builtin/packages/hypre-cmake/package.py
> +                make("HYPRE_DIR={0}".format(self.prefix), "bigint")
The convention is to no longer treat the build of tests as separate test parts.  

Rather do the build and run the tests as test_parts all within the working directory.

2024-07-19 02:32 UTC, tldahlgren commented on var/spack/repos/builtin/packages/hypre-cmake/package.py
> +                with test_part(self, "test_hypre_cmake_build", purpose=f"Ensuring {exe} runs"):
The original option `skip_missing=True` means these should be skipped if the program is not built.

2024-07-19 02:33 UTC, tldahlgren commented on var/spack/repos/builtin/packages/hypre-cmake/package.py
> +                make("HYPRE_DIR={0}".format(self.prefix), "bigint")
This should also be an f-string.

2024-08-09 18:22 UTC, tldahlgren commented on var/spack/repos/builtin/packages/hypre-cmake/package.py
> +                make("HYPRE_DIR={0}".format(self.prefix), "bigint")
> Rather do the build and run the tests as test_parts all within the working directory.

By this I meant like the `MyLibExample` in the docs at https://spack.readthedocs.io/en/latest/packaging_guide.html#saving-build-and-install-time-files.

2024-08-09 18:57 UTC, tldahlgren requested changes
See comments.

2024-08-09 18:57 UTC, tldahlgren commented on var/spack/repos/builtin/packages/hypre-cmake/package.py
> +
Drop this since you are basically performing the same check in lines 123-124.

2024-08-09 18:57 UTC, tldahlgren commented on var/spack/repos/builtin/packages/hypre-cmake/package.py
> +    def test_hypre_cmake(self):
The following is more descriptive (in case they want to add more tests in the future):

```suggestion
    def test_bigint(self):
```

2024-08-09 18:57 UTC, tldahlgren commented on var/spack/repos/builtin/packages/hypre-cmake/package.py
>          # Build copied and cached test examples
```suggestion
        # Build and run cached examples
```

2024-08-09 18:57 UTC, tldahlgren commented on var/spack/repos/builtin/packages/hypre-cmake/package.py
> +                    self, f"test_hypre_cmake_{exe_name}", purpose=f"Ensure {exe_name} runs"
To match more descriptive name:

```suggestion
                    self, f"test_bigint_{exe_name}", purpose=f"Ensure {exe_name} runs"
```

2024-08-09 18:57 UTC, tldahlgren commented on var/spack/repos/builtin/packages/hypre-cmake/package.py
> +                    program = which("./" + exe_name)
```suggestion
                    program = which(exe_name)
```

2024-08-09 22:44 UTC, tldahlgren approved these changes

2024-08-11 09:03 UTC, merged