libpressio: old to new test API
LLNL/spack pull request #45151
Opened 2024-07-09 22:48 UTC by AcriusWinter

2024-07-09 22:50 UTC, AcriusWinter commented
Old Error:
```
==> Error: TestFailure: 2 tests failed.


Command exited with status 2:
    '/usr/tce/bin/cmake' '--build' '.'
[ 50%] Building CXX object CMakeFiles/pressio_smoke_tests.dir/smoke_test.cc.o
In file included from /usr/WS2/lawrence31/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/libpressio-0.99.4-w2aykpzndxfkfgumx62ahr27ceo27ern/include/libpressio/libpressio_ext/cpp/metrics.h:7,
                 from /usr/WS2/lawrence31/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/libpressio-0.99.4-w2aykpzndxfkfgumx62ahr27ceo27ern/include/libpressio/libpressio_ext/cpp/compressor.h:5,
                 from /usr/WS2/lawrence31/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/libpressio-0.99.4-w2aykpzndxfkfgumx62ahr27ceo27ern/include/libpressio/libpressio_ext/cpp/libpressio.h:5,
                 from /g/g16/lawrence31/.spack/test/cdmofmmsapsjdmk3dd4advz622o3u7f3/libpressio-0.99.4-w2aykpz/cache/libpressio/test/smoke_test/smoke_test.cc:7:
/usr/WS2/lawrence31/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/libstdcompat-0.0.21-ng7ynaowixvjjmy5g3vrqveka5o6tf7o/include/std_compat/span.h:46:10: fatal error: span: No such file or directory
 #include <span>
          ^~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/pressio_smoke_tests.dir/build.make:76: CMakeFiles/pressio_smoke_tests.dir/smoke_test.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/pressio_smoke_tests.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2



1 error found in test log:
     95     /usr/WS2/lawrence31/spack/opt/spack/linux-rhel8-broadwell/gcc-10.3.1/libstdcompat-0.0.21-ng7ynaowixvjjmy5g3vrq
            veka5o6tf7o/include/std_compat/span.h:46:10: fatal error: span: No such file or directory
     96      #include <span>
     97               ^~~~~~
     98     compilation terminated.
     99     gmake[2]: *** [CMakeFiles/pressio_smoke_tests.dir/build.make:76: CMakeFiles/pressio_smoke_tests.dir/smoke_test
            .cc.o] Error 1
     100    gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/pressio_smoke_tests.dir/all] Error 2
  >> 101    gmake: *** [Makefile:136: all] Error 2
     102    
     103      File "/usr/WS2/lawrence31/spack/bin/spack", line 52, in <module>



Failed to find executable './pressio_smoke_tests'



See test log for details:
  /g/g16/lawrence31/.spack/test/cdmofmmsapsjdmk3dd4advz622o3u7f3/libpressio-0.99.4-w2aykpz-test-out.txt

============================== 1 failed of 1 spec ==============================
```
New Error:
```
==> Error: TestFailure: 2 tests failed.


Command exited with status 1:
    '/usr/tce/bin/cmake' '--build' '.'


1 error found in test log:
  >> 6    FAILED: Libpressio::test_build: Command exited with status 1:
     7        '/usr/tce/bin/cmake' '--build' '.'
     8      File "/usr/WS2/lawrence31/spack/bin/spack", line 52, in <module>



'NoneType' object is not callable


1 error found in test log:
     115        LIBPRESSIO_INSTALL_DOCS
     116    
     117    
     118    -- Build files have been written to: /g/g16/lawrence31/.spack/test/cdmofmmsapsjdmk3dd4advz622o3u7f3/libpressio
            -0.99.4-w2aykpz
     119    PASSED: Libpressio::test_cmake
     120    ==> [2024-07-09-15:49:44.283643] test: test_smoke: Run smoke test
  >> 121    FAILED: Libpressio::test_smoke: 'NoneType' object is not callable
     122      File "/usr/WS2/lawrence31/spack/bin/spack", line 52, in <module>
     123        sys.exit(main())
     124      File "/usr/WS2/lawrence31/spack/lib/spack/spack_installable/main.py", line 42, in main
     125        sys.exit(spack.main.main(argv))
     126      File "/usr/WS2/lawrence31/spack/lib/spack/spack/main.py", line 1070, in main
     127        return _main(argv)


See test log for details:
  /g/g16/lawrence31/.spack/test/cdmofmmsapsjdmk3dd4advz622o3u7f3/libpressio-0.99.4-w2aykpz-test-out.txt

============================== 1 failed of 1 spec ==============================

See libpressio-0.99.4-w2aykpz test results at:
  /g/g16/lawrence31/.spack/test/cdmofmmsapsjdmk3dd4advz622o3u7f3/libpressio-0.99.4-w2aykpz-test-out.txt
==> Error: 1 test(s) in the suite failed.
```

2024-07-10 01:47 UTC, tldahlgren requested changes
Calls to `cmake` and `make` should not be split out as separate test parts, especially not implicit ones since there is no guarantee that the `test_` methods are called in the order required to ensure they build test program(s).

2024-07-10 01:47 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libpressio/package.py
> +        if self.spec.satisfies("@0.88.2"):
This is not a range check.  The `:` is missing.

2024-07-10 01:47 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libpressio/package.py
> +        if self.spec.satisfies("@0.88.2"):
Not a range check.

2024-07-10 01:47 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libpressio/package.py
> +        if self.spec.satisfies("@0.88.2"):
Not a range check.

2024-07-19 01:49 UTC, tldahlgren requested changes
Looks really close.  Need to add the arguments to capture the outputs.

2024-07-19 01:49 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libpressio/package.py
> +        out = exe()
The output-related arguments are missing.  See the docs at https://spack.readthedocs.io/en/latest/packaging_guide.html#reading-expected-output-from-a-file for the missing arguments.

2024-07-19 01:51 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libpressio/package.py
>          args.append(
While you're here, this should also be using an f-string instead of format.

2024-07-19 01:51 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libpressio/package.py
>              "-DCMAKE_PREFIX_PATH={};{}".format(self.spec["libstdcompat"].prefix, self.prefix)
Same here for f-string.

2024-08-09 00:10 UTC, AcriusWinter commented
@spackbot run pipeline

2024-08-12 23:14 UTC, AcriusWinter commented on var/spack/repos/builtin/packages/libpressio/package.py
> +            raise SkipTest("Package must be installed as version @0.88.3 or later")
```suggestion
            return
```

2024-08-12 23:17 UTC, tldahlgren requested changes
see comments.

2024-08-12 23:17 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libpressio/package.py
> +            raise SkipTest("Package must be installed as version @0.88.3 or later")
This isn't part of running the test so shouldn't be raising that exception.

2024-08-12 23:17 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libpressio/package.py
> +        cmake = which("cmake")
This should be the command.

2024-08-12 23:17 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libpressio/package.py
> +        exe = which("./pressio_smoke_tests")
You don't really need `./` here.

2024-08-13 00:49 UTC, tldahlgren requested changes
Minor changes

2024-08-13 00:49 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libpressio/package.py
> +        exe = which("./pressio_smoke_tests")
```suggestion
        exe = which("pressio_smoke_tests")
```

2024-08-13 00:49 UTC, tldahlgren commented on var/spack/repos/builtin/packages/libpressio/package.py
> +        cmake = which("cmake")
```suggestion
        cmake = self.spec["cmake"].command
```

2024-08-13 01:25 UTC, tldahlgren approved these changes
Changes LGTM.

2024-08-14 22:58 UTC, tldahlgren commented
@robertu94 I'm going to go ahead and merge this PR since it focuses on converting from the deprecated to the new test API.  I assume it is okay for someone to resolve the test issues as needed in a follow on PR.

2024-08-14 22:59 UTC, merged