raja: new test API
LLNL/spack pull request #45184
Opened 2024-07-10 23:47 UTC by AcriusWinter

2024-07-10 23:47 UTC, AcriusWinter commented
Any insights on what is causing this would be appreciated:
```
==> Error: TestFailure: 7 tests failed.


'Raja' object has no attribute 'build_dirname'

/usr/WS2/lawrence31/spack/var/spack/repos/builtin/packages/raja/package.py:446, in test_examples:
        443                    reason = "test: checking output of {0} for {1}".format(exe, expected)
        444                    example_exe = which(exe)
        445                    out = example_exe([],output=str.split,error=str.split)
  >>    446                    check_outputs(expected,out)


'Raja' object has no attribute 'build_dirname'

/usr/WS2/lawrence31/spack/var/spack/repos/builtin/packages/raja/package.py:446, in test_examples:
        443                    reason = "test: checking output of {0} for {1}".format(exe, expected)
        444                    example_exe = which(exe)
        445                    out = example_exe([],output=str.split,error=str.split)
  >>    446                    check_outputs(expected,out)


'Raja' object has no attribute 'build_dirname'

/usr/WS2/lawrence31/spack/var/spack/repos/builtin/packages/raja/package.py:446, in test_examples:
        443                    reason = "test: checking output of {0} for {1}".format(exe, expected)
        444                    example_exe = which(exe)
        445                    out = example_exe([],output=str.split,error=str.split)
  >>    446                    check_outputs(expected,out)


'Raja' object has no attribute 'build_dirname'

/usr/WS2/lawrence31/spack/var/spack/repos/builtin/packages/raja/package.py:446, in test_examples:
        443                    reason = "test: checking output of {0} for {1}".format(exe, expected)
        444                    example_exe = which(exe)
        445                    out = example_exe([],output=str.split,error=str.split)
  >>    446                    check_outputs(expected,out)


'Raja' object has no attribute 'build_dirname'

/usr/WS2/lawrence31/spack/var/spack/repos/builtin/packages/raja/package.py:446, in test_examples:
        443                    reason = "test: checking output of {0} for {1}".format(exe, expected)
        444                    example_exe = which(exe)
        445                    out = example_exe([],output=str.split,error=str.split)
  >>    446                    check_outputs(expected,out)


'Raja' object has no attribute 'build_dirname'

/usr/WS2/lawrence31/spack/var/spack/repos/builtin/packages/raja/package.py:446, in test_examples:
        443                    reason = "test: checking output of {0} for {1}".format(exe, expected)
        444                    example_exe = which(exe)
        445                    out = example_exe([],output=str.split,error=str.split)
  >>    446                    check_outputs(expected,out)


'Raja' object has no attribute 'build_dirname'

/usr/WS2/lawrence31/spack/var/spack/repos/builtin/packages/raja/package.py:446, in test_examples:
        443                    reason = "test: checking output of {0} for {1}".format(exe, expected)
        444                    example_exe = which(exe)
        445                    out = example_exe([],output=str.split,error=str.split)
  >>    446                    check_outputs(expected,out)
```

2024-07-11 00:07 UTC, tldahlgren requested changes
I realize this is a DRAFT PR but flagging some needed changes anyway.

2024-07-11 00:07 UTC, tldahlgren commented on var/spack/repos/builtin/packages/raja/package.py
>          for exe, expected in checks:
IMO I'd rather see each test a separate test method, even if they call a common test execution method.

2024-07-11 00:07 UTC, tldahlgren commented on var/spack/repos/builtin/packages/raja/package.py
> +                    reason = "test: checking output of {0} for {1}".format(exe, expected)
This variable is not used.

2024-07-11 00:07 UTC, tldahlgren commented on var/spack/repos/builtin/packages/raja/package.py
> +                purpose=f"test: checking output of {exe} for {expected}",
`test: ` is already pre-pended to the test output so can be dropped here; otherwise, the log message for each test is `test: test: checking...`.

2024-07-11 00:07 UTC, tldahlgren commented on var/spack/repos/builtin/packages/raja/package.py
> +                with working_dir(self._extra_tests_path):
If you look at the value returned by this property, you'll see that it is running the test under the installation prefix, which should not be happening.

See if it is possible to run from the test stage directory.

2024-07-11 00:19 UTC, tldahlgren commented
> Any insights on what is causing this would be appreciated:
> 
> ```
> ==> Error: TestFailure: 7 tests failed.
> 
> 
> 'Raja' object has no attribute 'build_dirname'
> 

This is coming from the `build_relpath` property, which is being used by the `_extra_tests_path` property.  There are a number of problems with the paths related to using these checks as stand-alone tests.

2024-07-11 00:23 UTC, tldahlgren commented
The test output is also pointing out another deprecated method that needs to be fixed:

```
Warning: The 'pkg.install_test_root' property is deprecated with removal expected v0.23. Use 'install_test_root(pkg)' instead.
```

2024-07-11 00:33 UTC, tldahlgren commented on var/spack/repos/builtin/packages/raja/package.py
> -                skip_missing=True,
This option indicates you need to be skipping the test if the executable is missing.

2024-07-18 21:50 UTC, tldahlgren commented on var/spack/repos/builtin/packages/raja/package.py
> +    def test_dynamic(self):
```suggestion
    def test_dynamic_tile(self):
```

2024-07-18 22:25 UTC, tldahlgren requested changes
Looking better.  The test method names and docstrings need to be more descriptive and the line of sight test is missing.

2024-07-18 22:25 UTC, tldahlgren commented on var/spack/repos/builtin/packages/raja/package.py
> +        """Test tut matrix"""
The name and docstring/purpose aren't very descriptive.  It's really batched matrix multiple.

2024-07-18 22:25 UTC, tldahlgren commented on var/spack/repos/builtin/packages/raja/package.py
> +        """Test dynamic kernel"""
Would be better for these to be more in line with what is being run .. at least `dynamic tile`.

2024-07-18 22:25 UTC, tldahlgren commented on var/spack/repos/builtin/packages/raja/package.py
> +        """Test raja matrix"""
The name and docstring should be more descriptive since there's potential for lots of actions related to matrices as in `tiled matrix transpose`.

2024-07-18 22:25 UTC, tldahlgren commented on var/spack/repos/builtin/packages/raja/package.py
> +        """Test raja views"""
The name and docstring/purpose should reflect what is run not the first line of output being checked.  So needs to reflect it is a stencil offset layout.

2024-07-18 22:25 UTC, tldahlgren commented on var/spack/repos/builtin/packages/raja/package.py
> +        )
This is a duplicate of the test method at line 433 but should be the line-of-site example.

2024-08-14 00:33 UTC, tldahlgren requested changes
See comments.

2024-08-14 00:33 UTC, tldahlgren commented on var/spack/repos/builtin/packages/raja/package.py
> +    def run_raja(self, exe, expected):
Technically this is running a pre-installed example.

2024-08-14 00:33 UTC, tldahlgren commented on var/spack/repos/builtin/packages/raja/package.py
> +    def run_raja(self, exe, expected):
Also, this is a new method so should have a docstring.

2024-08-14 00:33 UTC, tldahlgren commented on var/spack/repos/builtin/packages/raja/package.py
> +        """Test line of sight example"""
The descriptions for this and the remaining test methods are good but could be better by alluding to the fact that the outputs are also checked.

2024-08-14 01:31 UTC, tldahlgren requested changes

2024-08-14 01:31 UTC, tldahlgren commented on var/spack/repos/builtin/packages/raja/package.py
> +        example_exe = which(exe)
This is supposed to be performed within `self._extra_tests_path`.

2024-08-14 01:33 UTC, tldahlgren approved these changes

2024-08-14 01:39 UTC, tldahlgren requested changes
Forgot I'd asked for a more descriptive method name.

2024-08-14 01:39 UTC, tldahlgren commented on var/spack/repos/builtin/packages/raja/package.py
> +    def test_views(self):
```suggestion
    def test_stencil_offset_layout(self):
```

2024-08-14 01:46 UTC, tldahlgren approved these changes

2024-08-14 03:36 UTC, merged