pumi: new test API
LLNL/spack pull request #45181
Opened 2024-07-10 22:16 UTC by AcriusWinter

2024-07-10 22:16 UTC, AcriusWinter commented
========================= SUMMARY: pumi-2.2.8-cnxm7rx ==========================
Pumi::test_partition .. PASSED
Pumi::test_refine .. PASSED
============================= 2 passed of 2 parts ==============================
============================== 1 passed of 1 spec ==============================

2024-07-10 22:40 UTC, AcriusWinter commented
==> Results for test suite 'awtnb3e4swtveiprhk67gjwbhfvykffx':
==> test specs:
==>   pumi-2.2.8-cnxm7rx PASSED
==>   pumi-2.2.6-6e6ejkq SKIPPED
======================== 1 passed, 1 skipped of 2 specs ========================

2024-07-10 22:43 UTC, tldahlgren requested changes
Really close.  Just a couple of simple fixes needed.

2024-07-10 22:43 UTC, tldahlgren commented on var/spack/repos/builtin/packages/pumi/package.py
> +        if self.spec.satisfies("@2.2.6"):
This is not a check of the range `@:2.2.6`.

2024-07-10 22:43 UTC, tldahlgren commented on var/spack/repos/builtin/packages/pumi/package.py
> +        print(f"{options}")
Remove the `print()` statements at lines 128, 130, and 132.

2024-07-10 22:43 UTC, tldahlgren commented on var/spack/repos/builtin/packages/pumi/package.py
> +        if self.spec.satisfies("@2.2.6"):
Not the correct range check.

2024-07-10 23:44 UTC, tldahlgren commented
```
$ spack -v test run pumi
==> Spack test hilvdhtv2cjwfqaz6vighup7rqovg6x5
==> Testing package pumi-2.2.8-l6wk753
==> [2024-07-10-16:42:41.077445] test: test_partition: Testing pumi mesh partitioning
...
MDS: reordering before writing smb files
PASSED: Pumi::test_partition
==> [2024-07-10-16:42:41.406248] test: test_refine: Testing pumi uniform mesh refinement
...
MDS: reordering before writing smb files
PASSED: Pumi::test_refine
==> [2024-07-10-16:42:41.808114] Completed testing
==> [2024-07-10-16:42:41.808307] 
========================= SUMMARY: pumi-2.2.8-l6wk753 ==========================
Pumi::test_partition .. PASSED
Pumi::test_refine .. PASSED
============================= 2 passed of 2 parts ==============================
============================== 1 passed of 1 spec ==============================
```

2024-07-10 23:45 UTC, tldahlgren approved these changes
Works for me.

2024-07-10 23:57 UTC, merged

2024-07-12 19:51 UTC, tldahlgren commented
@wspear Does this PR fix #38030 for you?