Turn compilers into nodes
LLNL/spack pull request #45189
Opened 2024-07-11 09:49 UTC by alalazo

:warning: **Work in progress** :warning: 

This is a long term feature branch, with the goal of having a first working implementation of compiler as dependencies.

2024-10-31 21:44 UTC, alalazo commented
@spackbot run pipeline

2024-12-04 20:15 UTC, marcmengel commented
This would be a far less compatability-breaking change if we did something like make `AutotoolsPackage` packages depend on `c` and `CMake` packages depend on `c++` by default, **if** they don't specify a language dependency themselves.   We could then also make `GoPackage` packages depend on `go`, have it be a virtual with an implementation compiler package, and add a proper similar case for Rust.    The PackageBase could have an expectedLanguage variable (set to None)  that the various subclasses could override for this...

2024-12-04 20:19 UTC, becker33 commented
> make AutotoolsPackage packages depend on c and CMake packages depend on c++ by default

It's simply not the case that you can infer the languages needed from the build system. Lots of packages use CMake for C or Fortran without using C++, and similarly plenty of Fortran packages use Autotools without needing a C component.

2024-12-04 20:21 UTC, marcmengel commented
But percentage-wise, I think it's a pretty good bet, such that 5 or 10 percent of your recipes would need to specify their language, rather than 100 percent.

2024-12-04 20:56 UTC, alalazo commented
@marcmengel We already added language dependencies for packages in the builtin repository in v0.23, see https://github.com/spack/spack/pull/45217, and backported a change to allow language deps to the latest patch version of Spack v0.22. This is to say that language deps per-se should not be breaking at all.

2024-12-04 21:12 UTC, marcmengel commented
Some of us have lots of recipes that aren't in the builtin repository...  So making them work in multiple versions of spack is hard when you have to add dependencies that you don't need in another version of spack...

2024-12-04 21:19 UTC, alalazo commented
@marcmengel That's what I'm saying: if you add language deps, they would still be working from v0.21, see the forward compatibility note in https://github.com/spack/spack/releases/tag/v0.21.3

2024-12-04 22:22 UTC, marcmengel commented
@alalazo So I still have to change all my recipes, rather than a few of them, but they will  work in 0.21 onward.  Got it.

2025-01-15 11:16 UTC, alalazo commented on lib/spack/spack/test/concretization/flag_mixing.py
> +    - spec: clang@19.1.0
This should be under `llvm` and be called `llvm+clang`

2025-01-23 16:23 UTC, haampie commented
- [ ] `spack compiler find` still outputs "Compilers are defined [...] compilers.yaml" even though those are now ignored.
- [ ] `spack config edit packages` opens an empty file `~/.spack/packages.yaml`, compilers are added to `~/.spack/linux/packages.yaml`. I don't see a need for `linux/` as a subdir.
- [ ] After spack migrates compilers.yaml -> packages.yaml, it also copies `packages:all: ...` config from defaults. That should not happen
- [ ] Warnings about duplicates compilers:
   - [ ] The message `duplicate gcc@13.3.0/2v5tyudx3gyd2zl7ivetuactclwruptu compiler found` refers to a hash, which makes users grep for it, but they won't find it -- probably a side effect of marking externals as concrete. Grepping for `gcc@13.3.0` also doesn't work because it's `gcc@=13.3.0`.
   - [ ] minor: the duplicate is due to apt update & outdated config. The system upgraded gcc 13.2 -> 13.3 but my config had 13.2 from before and 13.3 from later. Spack re-detects them as 13.3 twice and adds both to packages.yaml instead of de-duping.

2025-01-23 16:41 UTC, marcmengel commented
Putting the packages.yaml it in the platform-specific config sub-directory makes sense, esp. if one is sharing a home  area between, say, Linux and Mac hosts; they are unlikely to share compilers; but the site/os directory would make more sense to me as the default.

2025-01-23 16:48 UTC, haampie commented
Does not sound like a very common use case. Even on linux I would never mount $HOME into a container as it leads to tons of problems with dotfiles that just don't make sense in a different distro.

2025-01-27 17:40 UTC, marcmengel commented
So trying this in 1.0.0-alpha.3 many things work well, but I cannot figure out how to specify preferred compilers in an environment spack.yaml: 
putting %gcc@version in the spec: list gives an unexpected character error, and
 including '%gcc@version' in the packages: require: section for a package causes is to give a 'cannot satisfy a requirement for package 'x'. error,  with no  offending/unsatisfiable  requirements listed.

2025-01-27 17:45 UTC, marcmengel commented
Addendum:  adding a dependency in the spec: list  ('^gcc@version') does seem to work, at least partially...

2025-01-27 17:56 UTC, alalazo commented
> So trying this in 1.0.0-alpha.3 many things work well, but I cannot figure out how to specify preferred compilers in an environment spack.yaml

As a general guideline, in this branch C, C++ and Fortran become `virtual` dependencies, and `%` means "direct build dependency". To specify a preferred compiler you can either mention it in the list of preferred providers:
```yaml
packages:
  all:
    providers:    
      c: ["gcc", "llvm", "intel-oneapi-compilers"]
```
or if you want a stronger kind of preference:
```yaml
packages:
    all:
      prefer:
      - '%oneapi'
```

> Addendum: adding a dependency in the spec: list ('^gcc@version') does seem to work, at least partially...

Spec matrices are still subject to the limitation at the bottom in the description of the PR. Basically, right now using `%gcc` in a matrix is an error, if the spec it is applied to doesn't depend on C, C++ or Fortran. I think it's _fair_ if this limitation remains in the final version of the PR, because the fix required in the environment manifest is backward compatible, but this behavior is not cast in stone yet.

2025-01-30 17:03 UTC, becker33 requested changes
This is not a complete review, just checkpointing my thoughts so far.

2025-01-30 17:03 UTC, becker33 commented on etc/spack/defaults/packages.yaml
> +      c: [gcc, llvm, intel-oneapi-compilers, xl, aocc]
Is there a reason we are simultaneously removing `fj` from the preferred compilers list?

2025-01-30 17:03 UTC, becker33 commented on etc/spack/defaults/windows/packages.yaml
> +      cxx: [msvc]
Should we add a preferred fortran compiler for windows?

2025-01-30 17:03 UTC, becker33 commented on lib/spack/spack/build_systems/cached_cmake.py
> +        return f"{self.pkg.name}-{self.spec.architecture.platform}-{self.spec.dag_hash()}.cmake"
If we assume c/cxx dependencies in the builder as below, we can use them here to avoid changing the cache filename granularity

2025-01-30 17:03 UTC, becker33 commented on lib/spack/spack/provider_index.py
> +                spack.spec.SpecfileV5.from_node_dict(vpkg),
We should probably have an alias `spack.spec.SpecfileLatest` so that we don't have to update random other places in the code for every specfile version update.

2025-01-30 17:03 UTC, becker33 commented on lib/spack/spack/reporters/cdash.py
> +        if len(phases_encountered) == 1 and package.get("exception"):
It's a little concerning to me that we needed to change this -- is the comment above this no longer accurate?

2025-01-30 17:03 UTC, becker33 commented on lib/spack/spack/schema/packages.py
> +                        "Spack v0.26.",
Version numbers are out of date w.r.t. our release plan.

2025-01-30 17:03 UTC, becker33 commented on lib/spack/spack/spec_parser.py
> +            if self.ctx.accept(SpecTokens.COMPILER) or self.ctx.accept(
I think we should change the token name to `BUILDDEP` as well, since it isn't about compilers specifically anymore.

2025-01-30 17:03 UTC, becker33 commented on var/spack/repos/compiler_runtime.test/packages/compiler-wrapper
> +../../builtin/packages/compiler-wrapper/
For all of these symlinked compiler infrastructure packages in the tests, I think it would be better to have a separate repo of core mock package infrastructure and to load that repo and an additional repo as needed. I'm typing without checking the method signatures here, so treat this as pseudocode, but something like:

```
@pytest.fixture()
def mock_package_repo(...):
    def _setup_repos(repo_name):
        repos_root = spack.paths.repo_path
        with spack.repo.use_repositories(repos_root / test_repo_base, repos_root / repo_name):
            yield
            
    return _setup_repos

def test_compiler_runtime_foo(mock_packages_repo):
    mock_packages_repo(compiler_runtime.test)

    compiler_wrapper_pkg = spack.repo.PATH.get("compiler_wrapper")
```

I think this would be cleaner because it would eliminate the need for duplicated packages across repos in a way that ensures that tests that aren't about the compiler infrastructure don't have to consider it.

2025-01-30 22:34 UTC, becker33 requested changes
Still not a complete review

2025-01-30 22:34 UTC, becker33 commented on var/spack/repos/builtin/packages/vtk-h/package.py
> +        host_config_path = f"{socket.gethostname()}-{sys_type}-vtkh-{spec.dag_hash()}.cmake"
```suggestion
        host_config_path = f"{socket.gethostname()}-{sys_type}-{spec['cxx'].name}-vtkh-{spec.dag_hash()}.cmake"
```

2025-01-30 22:34 UTC, becker33 commented on var/spack/repos/builtin/packages/vasp/package.py
> +    requires("^nvhpc+mpi+lapack+blas", when="%nvhpc")
Can you explain more about why this change is necessary? I thought we could have self-referential dependencies like the one this is replacing.

2025-01-30 22:34 UTC, becker33 commented on var/spack/repos/builtin/packages/nvhpc/package.py
> +    required_libs = ["libnvc", "libnvf"]
This looks like something that should eventually split into separate attributes for c/fortran, but that doesn't need to be pulled into the scope of this PR

2025-01-30 22:34 UTC, becker33 commented on var/spack/repos/builtin/packages/ncurses/package.py
> +                flags.append(self["cxx"].standard_flag(language="cxx", standard="14"))
This feels clunky to use. Could we move this to set the language automatically based on the argument used to subscript self? I'm thinking analogous to the `blas_libs` and `lapack_libs` methods that key based on whether we subscript by `blas` or `lapack`.

2025-01-30 22:34 UTC, becker33 commented on var/spack/repos/builtin/packages/mapl/package.py
> +            gfortran_major_ver = int(self.spec["fortran"].version[0])
It looks like similar fixes need to be applied to line 377

2025-01-30 22:34 UTC, becker33 commented on var/spack/repos/builtin/packages/lvarray/package.py
> +        host_config_path = f"{hostname}-{self._get_sys_type(spec)}-{var}.cmake"
```suggestion
        host_config_path = f"{hostname}-{self._get_sys_type(spec)}-{self[cxx].name}-{var}.cmake"
```

2025-01-30 22:34 UTC, becker33 commented on var/spack/repos/builtin/packages/llvm-amdgpu/package.py
> +    stdcxx_libs = ("-lstdc++",)
Doesn't this depend on a compiler flag to `amdclang`, the same way it does for `clang`?

2025-01-30 22:34 UTC, becker33 commented on var/spack/repos/builtin/packages/libtheora/package.py
> +        devenv_path = os.path.join(self.pkg["msvc"].vs_root, "Common7", "IDE")
```suggestion
        devenv_path = os.path.join(self.pkg["c"].vs_root, "Common7", "IDE")
```
We already support the intel compilers on windows to some extent, but even if this isn't necessary now it's good future-proofing.

2025-01-30 22:34 UTC, becker33 commented on var/spack/repos/builtin/packages/intel-oneapi-runtime/package.py
> +    depends_on("intel-oneapi-compilers", type="build")
This is duplicate from line 24

2025-01-30 22:34 UTC, becker33 commented on var/spack/repos/builtin/packages/intel-oneapi-compilers/package.py
> +    provides("c", "cxx", "fortran")
Aren't these provided separately, rather than together?

2025-01-30 22:34 UTC, becker33 commented on var/spack/repos/builtin/packages/gcc-runtime/package.py
> +        gcc_pkg = self.spec["gcc"].package
```suggestion
        gcc_pkg = self["gcc"]
```

2025-01-30 22:34 UTC, becker33 commented on var/spack/repos/builtin/packages/esmf/package.py
> +        elif spec["fortran"].name == "gcc" and spec["c"].name in ["clang", "apple-clang"]:
I believe line 264 needs a similar fix.

2025-01-30 22:34 UTC, becker33 commented on var/spack/repos/builtin/packages/dyninst/package.py
> +    requires("^[virtuals=tbb] intel-tbb@2019.9:", when="@13.0.0:")
I don't understand the point of this change.

2025-01-30 22:34 UTC, becker33 commented on var/spack/repos/builtin/packages/dyninst/package.py
> +        elf = spec["elfutils"].prefix
If we're not supporting the old version that requires `libelf` anymore, we should remove it.

2025-01-30 22:34 UTC, becker33 commented on var/spack/repos/builtin/packages/cray-mvapich2/package.py
> +        if self.spec.dependencies(virtuals=("c",)):
We should check with HPE whether this package still exists, and if so whether the improvements made to `cray-mpich` will be applied here as well.

2025-01-30 22:34 UTC, becker33 commented on var/spack/repos/builtin/packages/conduit/package.py
> +        host_config_path = f"{socket.gethostname()}-{sys_type}-conduit-{spec.dag_hash()}.cmake"
```suggestion
        host_config_path = f"{socket.gethostname()}-{sys_type}-{self['cxx'].name}-conduit-{spec.dag_hash()}.cmake"
```

2025-01-30 22:34 UTC, becker33 commented on var/spack/repos/builtin/packages/ascent/package.py
> +        host_config_path = f"{socket.gethostname()}-{sys_type}-ascent-{spec.dag_hash()}.cmake"
```suggestion
        host_config_path = f"{socket.gethostname()}-{sys_type}-{self['cxx'].name}-ascent-{spec.dag_hash()}.cmake"
```

2025-01-31 06:55 UTC, alalazo commented on var/spack/repos/builtin/packages/vasp/package.py
> +    requires("^nvhpc+mpi+lapack+blas", when="%nvhpc")
No, this one says "depends on `nvhpc+mpi` etc. when depends on `nvhpc` type build". To clingo this means having the choice to add:
```
^[deptype=build] nvhpc+mpi etc.
```
or not to make the score better. Using `requires` instead enforces a constraint, without the possibility of adding a dependency.

2025-01-31 07:00 UTC, alalazo commented on var/spack/repos/builtin/packages/ncurses/package.py
> +                flags.append(self["cxx"].standard_flag(language="cxx", standard="14"))
> Could we move this to set the language automatically based on the argument used to subscript self? 

We can, but we should keep in mind 2 things:
1. Not sure if there is clear consensus on that + we need some object wrapper on package for temporary query state
2. We plan to add variants to virtuals in the future, so we need to figure out how this works for `depends_on("cxx std=11,14")`

2025-01-31 07:02 UTC, alalazo commented on var/spack/repos/builtin/packages/libtheora/package.py
> +        devenv_path = os.path.join(self.pkg["msvc"].vs_root, "Common7", "IDE")
It's not future proofing: not every compire will have a `vs_root` option (I guess "Visual Studio" root :slightly_smiling_face: )

2025-01-31 07:08 UTC, alalazo commented on var/spack/repos/builtin/packages/dyninst/package.py
> +    requires("^[virtuals=tbb] intel-tbb@2019.9:", when="@13.0.0:")
The dyninst package was a mess, so I decided to rework it, see https://github.com/spack/spack/pull/47637 which I hope gets in before this PR.

2025-02-02 18:23 UTC, becker33 submitted a review, later dismissed
Still incomplete review:

I think we need to be careful not to treat `prefer` as a drop-in replacement for `require` or a matrix in the test stacks.

2025-02-02 18:23 UTC, becker33 commented on share/spack/gitlab/cloud_pipelines/stacks/radiuss/spack.yaml
> +      - '%gcc@7.5.0'
This is not equivalent to using a matrix, because the matrix allows dependencies to differ and this does not. It's probably not important because mostly when dependencies need to differ it's so they can use gcc not avoid it, but it's not a pure translation.

2025-02-02 18:23 UTC, becker33 commented on share/spack/gitlab/cloud_pipelines/stacks/e4s-oneapi/spack.yaml
> +      - '%oneapi'
We should probably use a matrix so it's stronger than a preference here. Theoretically this could just build with gcc and call it a day.

2025-02-02 18:23 UTC, becker33 commented on share/spack/gitlab/cloud_pipelines/stacks/e4s-cray-rhel/spack.yaml
> +      - "%cce"
Should probably be applied as a matrix to be certain

2025-02-02 18:23 UTC, becker33 commented on share/spack/gitlab/cloud_pipelines/stacks/build_systems/spack.yaml
> +      - gcc
I like this as a paradigm for these better than the `prefer` option.

2025-02-03 17:46 UTC, alalazo commented on etc/spack/defaults/packages.yaml
> +      c: [gcc, llvm, intel-oneapi-compilers, xl, aocc]
No specific reason. If light of #48729 we might want to remove `xl` and `aocc` too above. If people are using those vendor-specific compilers, they should probably tweak the preferences anyhow, to get sensible concretization results.

2025-02-03 17:47 UTC, alalazo commented on etc/spack/defaults/windows/packages.yaml
> +      cxx: [msvc]
Hmm, not sure about this one. As far as I see nothing is tested in CI.

2025-02-04 06:29 UTC, alalazo commented on lib/spack/spack/reporters/cdash.py
> +        if len(phases_encountered) == 1 and package.get("exception"):
Why is it concerning? This happens because, we started using `--fake` installs in tests, and those produce a single phase install without an `exception` key.

We started using `--fake` installs everywhere because tests are now using the `builtin` gcc-runtime etc. to test the actual package, since modifications to it will affect all the concretizations.

2025-02-04 07:14 UTC, alalazo commented on var/spack/repos/compiler_runtime.test/packages/compiler-wrapper
> +../../builtin/packages/compiler-wrapper/
> For all of these symlinked compiler infrastructure packages in the tests, I think it would be better to have a separate repo of core mock package infrastructure and to load that repo and an additional repo as needed.

I disagree with this one. The runtimes in the mock repo are symlink to builtin, so we'll test the real packages, and that was the entire reason to start with symlinks. I preferred that to mocking because:
1. Runtimes are fundamental in concretization, 
2. Runtime packages are quite simple

Other symlinked packages are mock versions of `gcc` or other small build deps. They are not really self-contained and they depend on the runtimes. There I wish I could reuse more of `builtin`, in particular for the dependency injection, but so far I just have some duplication in the mock.

2025-02-04 07:22 UTC, alalazo commented on var/spack/repos/compiler_runtime.test/packages/compiler-wrapper
> +../../builtin/packages/compiler-wrapper/
> [ ... ] in a way that ensures that tests that aren't about the compiler infrastructure don't have to consider it.

I guess the point is that tests are by default incorporating compilers, and edge cases are tests where the compiler is not involved. Doing the opposite means having a mock which does not reflect what we do in reality (i.e. it does not account for the interaction with runtimes)

2025-02-04 09:44 UTC, alalazo commented on var/spack/repos/builtin/packages/esmf/package.py
> +        elif spec["fortran"].name == "gcc" and spec["c"].name in ["clang", "apple-clang"]:
Not sure about this one. As is it seems to reflect the previous logic.

2025-02-04 09:45 UTC, alalazo commented on var/spack/repos/builtin/packages/dyninst/package.py
> +        elf = spec["elfutils"].prefix
See https://github.com/spack/spack/pull/45189#discussion_r1936771535

2025-02-04 09:50 UTC, alalazo commented on share/spack/gitlab/cloud_pipelines/stacks/radiuss/spack.yaml
> +      - '%gcc@7.5.0'
I don't really understand this comment. In `radiuss` we have these compilers to choose from:
![Screenshot from 2025-02-04 10-47-58](https://github.com/user-attachments/assets/3f1bc09a-86f6-490d-af95-d221cb5fc993)

This was mostly to ensure that specifying a requirement was working.

2025-02-04 10:06 UTC, alalazo commented on share/spack/gitlab/cloud_pipelines/stacks/build_systems/spack.yaml
> +      - gcc
This is a hard requirement. Here it is mainly to ensure that this syntax works, but in case you have other compilers you want to use, then `prefer` is much better to avoid situations like:
```
$ spack -e . concretize
==> Starting concretization pool with 8 processes
==> Error: failed to concretize `r-rcpp` for the following reasons:
     1. bison: bison is likely miscompiled by oneapi compilers, see https://github.com/spack/spack/issues/37172
     2. bison: bison is likely miscompiled by oneapi compilers, see https://github.com/spack/spack/issues/37172
        required because conflict is triggered when %oneapi 
          required because intel-oneapi-compilers is a requirement for package c 
          required because intel-oneapi-compilers available as external when satisfying intel-oneapi-compilers@=2025.0.4 
        required because conflict constraint  
```
I guess what I'm saying is that being very hard on more constraints requires more boilerplate for the exceptions.

2025-02-04 10:43 UTC, alalazo commented on lib/spack/spack/build_systems/cached_cmake.py
> +        return f"{self.pkg.name}-{self.spec.architecture.platform}-{self.spec.dag_hash()}.cmake"
Done.

2025-02-04 10:43 UTC, alalazo commented on lib/spack/spack/provider_index.py
> +                spack.spec.SpecfileV5.from_node_dict(vpkg),
Done

2025-02-04 10:43 UTC, alalazo commented on lib/spack/spack/schema/packages.py
> +                        "Spack v0.26.",
Done

2025-02-04 10:44 UTC, alalazo commented on var/spack/repos/builtin/packages/vtk-h/package.py
> +        host_config_path = f"{socket.gethostname()}-{sys_type}-vtkh-{spec.dag_hash()}.cmake"
Done

2025-02-04 10:44 UTC, alalazo commented on var/spack/repos/builtin/packages/mapl/package.py
> +            gfortran_major_ver = int(self.spec["fortran"].version[0])
Done

2025-02-04 10:44 UTC, alalazo commented on var/spack/repos/builtin/packages/lvarray/package.py
> +        host_config_path = f"{hostname}-{self._get_sys_type(spec)}-{var}.cmake"
Done

2025-02-04 10:46 UTC, alalazo commented on var/spack/repos/builtin/packages/intel-oneapi-runtime/package.py
> +    depends_on("intel-oneapi-compilers", type="build")
Removed

2025-02-04 10:46 UTC, alalazo commented on var/spack/repos/builtin/packages/intel-oneapi-compilers/package.py
> +    provides("c", "cxx", "fortran")
Done. Not sure to what extent these can be used separately, but we can be more restrictive later.

2025-02-04 10:47 UTC, alalazo commented on var/spack/repos/builtin/packages/gcc-runtime/package.py
> +        gcc_pkg = self.spec["gcc"].package
Done

2025-02-04 10:49 UTC, alalazo commented on var/spack/repos/builtin/packages/conduit/package.py
> +        host_config_path = f"{socket.gethostname()}-{sys_type}-conduit-{spec.dag_hash()}.cmake"
Done

2025-02-04 10:49 UTC, alalazo commented on var/spack/repos/builtin/packages/ascent/package.py
> +        host_config_path = f"{socket.gethostname()}-{sys_type}-ascent-{spec.dag_hash()}.cmake"
Done

2025-02-04 11:00 UTC, alalazo commented on share/spack/gitlab/cloud_pipelines/stacks/e4s-oneapi/spack.yaml
> +      - '%oneapi'
I can _add_ a matrix, but a matrix alone would just enforce the compiler on the root node. Children might use another compiler and be fine.

To be noted that a strong preference needs to have a very good reason to avoid a constraint, e.g. an explicit requirement in some package. We can  improve the semantic of requirements, and I have a few ideas, but this can be done separately from this branch (i.e. it's orthogonal to compiler as deps).

2025-02-07 07:59 UTC, haampie commented
The spack.compilers module/package lgtm. Prompted me to try to get rid of the `compiler_environment` context manager, but that doesn't have to target this PR.

2025-02-18 15:01 UTC, alalazo commented on var/spack/repos/builtin/packages/dyninst/package.py
> +    requires("^[virtuals=tbb] intel-tbb@2019.9:", when="@13.0.0:")
#47637 was merged in the meanwhile

2025-02-21 08:34 UTC, alalazo commented on etc/spack/defaults/packages.yaml
> +      c: [gcc, llvm, intel-oneapi-compilers, xl, aocc]
To clarify:
1. The `packages:compilers` attribute makes no sense after this PR, and so it's deprecated
2. Since I had to report the list of compilers to the preferred virtuals, I left out `fj` which is basically never needed outside of a few very specific machines. 
3. Also, when `fj` is needed it's probably the preferred, so this default would be wrong anyhow

@haampie rightfully suggested to try to extract these kind of changes out of the PR, which we'll try to do to reduce the review surface here.

2025-02-21 09:18 UTC, haampie commented on lib/spack/spack/test/cmd/install.py
> +    print(content)
remove

2025-02-21 09:30 UTC, haampie commented on lib/spack/spack/test/graph.py
> +    print(graph_str)
remove

2025-02-21 12:19 UTC, haampie commented on lib/spack/spack/solver/asp.py
> +            unsolved_specs = result.unsolved_specs
drop from this PR

2025-02-21 12:40 UTC, haampie commented on lib/spack/spack/spec.py
> +        return self.format("{name}{@version} {variants}{ arch=architecture}{/hash:7}")
```suggestion
        return self.format("{name}{@version}{variants}{ arch=architecture}{/hash:7}")
```

2025-02-21 12:41 UTC, alalazo commented on lib/spack/spack/solver/asp.py
> +            unsolved_specs = result.unsolved_specs
https://github.com/spack/spack/pull/48964

2025-02-21 12:42 UTC, haampie commented on lib/spack/spack/spec.py
> +            changed |= self[name].constrain(other[name], deps=True)
why deps=True?

2025-02-21 12:50 UTC, haampie commented
```python
        name_conversion = {
            "llvm": "clang",
            "intel-oneapi-compilers": "oneapi",
            "llvm-amdgpu": "rocmcc",
            "intel-oneapi-compiler-classic": "intel",
            "acfl": "arm",
        }

                name_conversion = {
                    "clang": "llvm",
                    "oneapi": "intel-oneapi-compilers",
                    "rocmcc": "llvm-amdgpu",
                    "intel": "intel-oneapi-compiler-classic",
                    "arm": "acfl",
                }
```

move to a common place?

2025-02-22 13:24 UTC, alalazo commented on lib/spack/spack/spec.py
> +        return self.format("{name}{@version} {variants}{ arch=architecture}{/hash:7}")
Done

2025-02-22 14:04 UTC, alalazo commented on lib/spack/spack/solver/asp.py
> +            unsolved_specs = result.unsolved_specs
Dropped

2025-02-22 14:15 UTC, alalazo commented
@spackbot run pipeline

2025-02-26 06:52 UTC, alalazo commented
@spackbot run pipeline

2025-02-28 05:01 UTC, scheibelp commented on lib/spack/spack/solver/concretize.lp
> +     compiler(Compiler), language(Language),
It looks like `node_compiler` would be useful for summarizing this

2025-02-28 05:01 UTC, scheibelp commented on lib/spack/spack/solver/concretize.lp
> +  node_compiler(node(PackageID, Package), CompilerNode) : node_compiler(SourceNode, CompilerNode);
It looks like this would be willing to propagate `fflags` if the `c` compilers match (even if the Fortran compilers don't).

2025-02-28 05:01 UTC, scheibelp commented on lib/spack/spack/solver/asp.py
>                                  clauses.append(
Just below here, `virtual_on_edge` is only added for more-than-just-build dependencies. This means that reused specs cannot for example have `virtual_on_edge(..., gcc, c)` (and therefore no associated `node_compiler`). That doesn't affect anything I'm aware of in this PR, but will cause problems if I want to disable compiler mixing between new and reused packages.

So I think that is a modeling issue, but one that I could resolve after this PR.

2025-02-28 05:01 UTC, scheibelp commented on lib/spack/spack/solver/concretize.lp
> +     attr("version", node(Y, Compiler), Version),
(question) why does the associated compiler need a version (or rather, what goes wrong when you leave this off)?

2025-02-28 05:01 UTC, scheibelp commented on lib/spack/spack/solver/concretize.lp
> +   attr("dependency_holds", ParentNode, Child, _).
(question) can you explain what `edge_needed` is for? I only see it read in:

```
:- depends_on(ParentNode, ChildNode),
   not edge_needed(ParentNode, ChildNode),
   build(ParentNode).
```

so I assume it's used for some type of consistency enforcement, but it looks "really close" to `depends_on` to me.

2025-02-28 14:32 UTC, alalazo commented on lib/spack/spack/solver/concretize.lp
> +   attr("dependency_holds", ParentNode, Child, _).
For a dependency with a `^`, in the ASP problem, we just add a node to the imposed conditions. For instance, an explicit request like `libdwarf ^libelf` translates at some point into:
```prolog
imposed_constraint(104,"node","libdwarf").
imposed_constraint(104,"node","libelf").
imposed_constraint(104,"root","libdwarf").
```
The position of the edge is determined by a chain of rules, deriving these facts:
```
dependency_holds => depends_on
```
We prevent disjoint nodes to be in the final solution via `needed/1`. This is true here and in `develop`.

What is different in this branch, is that `%` changes meaning, and now means "direct dependency of". When we write something like `libdwarf %gcc` what we get is the following set of facts:
```prolog
imposed_constraint(98,"node","libdwarf").
imposed_constraint(98,"depends_on","libdwarf","gcc","build").
imposed_constraint(98,"build_requirement","libdwarf",build_requirement("node","gcc")).
```
In this case the `depends_on` is derived immediately from the request, and that's how we mark that as a direct dependency. Eventually, the dependency is also a "valid" dependency, and a `dependency_holds` fact will also be derived. Similarly to how we prevent disjoint node in develop to appear using `needed`, here we prevent spurious branch to appear using `edge_needed`, i.e. a `depends_on` with a corresponding `dependency_holds`. 

(It's slightly more complicated than this, due to all the cases one might encounter, but I hope you got the idea.)

2025-02-28 14:33 UTC, alalazo commented on lib/spack/spack/solver/concretize.lp
> +     attr("version", node(Y, Compiler), Version),
Just a leftover from a precedent encoding, will remove it.

2025-02-28 14:34 UTC, alalazo commented on lib/spack/spack/solver/concretize.lp
> +     compiler(Compiler), language(Language),
True, as you might have guessed `node_compiler` was added later, and I didn't see this simplification. Will change it.

2025-02-28 14:37 UTC, alalazo commented on lib/spack/spack/solver/asp.py
>                                  clauses.append(
> That doesn't affect anything I'm aware of in this PR, but will cause problems if I want to disable compiler mixing between new and reused packages.

I think this case should be solved by thinking in terms of runtimes, not of compilers.

2025-02-28 18:04 UTC, alalazo commented on lib/spack/spack/solver/concretize.lp
> +     attr("version", node(Y, Compiler), Version),
Fixed in https://github.com/spack/spack/pull/45189/commits/3f9dad588d6151f5fa9b042400833a5704d18f5c

2025-02-28 18:04 UTC, alalazo commented on lib/spack/spack/solver/concretize.lp
> +     compiler(Compiler), language(Language),
Fixed in https://github.com/spack/spack/pull/45189/commits/3f9dad588d6151f5fa9b042400833a5704d18f5c

2025-02-28 18:05 UTC, alalazo commented on lib/spack/spack/solver/concretize.lp
> +  node_compiler(node(PackageID, Package), CompilerNode) : node_compiler(SourceNode, CompilerNode);
Fixed in https://github.com/spack/spack/pull/45189/commits/7c0dad9c3589c23237e02ef9267d8f788891f7da

2025-03-03 07:41 UTC, tgamblin requested changes
@alalazo here's a partial review. This is looking great so far -- I don't really have that many questions/comments yet.

One thing I do think we should do is ping maintainers of compiler packages specifically to make sure their packages work for them.  We are far enough along that I think they can and should try the branch and ensure their packages install and build correctly.

2025-03-03 07:41 UTC, tgamblin commented on .github/workflows/unit_tests.yaml
> +          pip install --upgrade pip setuptools pytest pytest-xdist pytest-cov clingo
Is this expected to be permanent? Or will we eventually bootstrap this like before?

2025-03-03 07:41 UTC, tgamblin commented on etc/spack/defaults/packages.yaml
> +      fortran: [gcc, llvm]
Shouldn't this list include `intel-oneapi-compilers`, so that it's at least as preferred for `fortran` as it is for `c` and `cxx`?

I would also like to see `cce` in here.  I don't think `xl` or `aocc` really need to be in the lists.

2025-03-03 07:41 UTC, tgamblin commented on etc/spack/defaults/darwin/packages.yaml
> +    require: gcc
Doesn't this pretty much invalidate the preferences above?  Is the intent that on macos users will need to do `c::`, etc. to use a different compiler combination?

2025-03-03 07:41 UTC, tgamblin commented on lib/spack/spack/binary_distribution.py
> +        assert compiler is not None, "a compiler spec is expected"
Is this an assertion or should we throw an error for invalid format?   It doesn't seem like something we can guarantee in the code -- the inputs are essentially arbitrary.

2025-03-03 07:41 UTC, tgamblin commented on lib/spack/spack/binary_distribution.py
> +        )
This one makes me think we should consider merging content buildcache first, as it gets rid of the implicit version assumptions here and puts everything at a hash-based location.

2025-03-03 07:41 UTC, tgamblin commented on lib/spack/spack/binary_distribution.py
> +    if spec.original_spec_format() < 5:
same comment here on content-addressed buildcache. If we can avoid having an intermediate step (i.e. go from current -> content buildcache instead of current -> compiler deps -> content buildcache) then I think it would be good.

2025-03-03 07:41 UTC, tgamblin commented on lib/spack/spack/bootstrap/_common.py
>          spec_str += " %clang"
why still add this on windows and freebsd?

2025-03-03 07:41 UTC, tgamblin commented on var/spack/repos/builtin.mock/packages/compiler-wrapper
> +../../builtin/packages/compiler-wrapper/
This can't be a symlink, at least not when we split the package repo out.  Seems like a bug waiting to happen soon -- is there another way we could handle it?

2025-03-03 07:41 UTC, tgamblin commented on var/spack/repos/builtin/packages/compiler-wrapper/cc.sh
> +        fi
why's this needed?  If we are in `ld` mode, we shouldn't actually need a linker arg b/c we have been invoked as the linker.  I *think* `*_LINKER_ARG` should really be irrelevant in `ld` mode.

2025-03-03 07:41 UTC, tgamblin commented on var/spack/repos/builtin/packages/compiler-wrapper/package.py
> +       -Wl,-rpath         arguments for dependency /lib directories.
it also provides a mechanism to inject flags from specs -- for most packages the compiler wrapper handles that.

2025-03-03 07:41 UTC, tgamblin commented on var/spack/repos/builtin/packages/compiler-wrapper/package.py
> +        # their way to the default view
I actually think `libexec/spack` is good, but would this ever be in the default view?  It's a build dep.

2025-03-03 07:41 UTC, tgamblin commented on var/spack/repos/builtin/packages/compiler-wrapper/package.py
> +            sha256="84a26f8f37329bcdfb41d23a8a4f4c46efbede983eb73737135c95a4c126b5b7",
Does this SHA have to be maintained by us or is there some automation?  Tempted to say we should introduce some new package type after this PR that automates this hashing or at least simplifies the maintenance. Should there be a test for hash correctness (e.g. like we do for updating command completion)?

2025-03-03 07:41 UTC, tgamblin commented on var/spack/repos/builtin/packages/compiler-wrapper/package.py
> +        if dependent_spec.dependencies(virtuals=("c",)):
This is nice -- I think a `Spec.has_virtual_dependency(virtual: str) -> bool` helper method would make this and other calls more legible/maintainable.

2025-03-03 07:41 UTC, tgamblin commented on var/spack/repos/builtin/packages/acfl/package.py
> +    link_paths = {
I think the name `link_paths` is too generic -- how about `compiler_wrapper_link_paths`?

2025-03-03 07:41 UTC, tgamblin commented on lib/spack/spack/compilers/config.py
> +}
Probably after this PR: I think we should do alias packages for v1.0.

2025-03-03 07:41 UTC, tgamblin commented on lib/spack/spack/compilers/config.py
> +def find_compilers(
Is there a significant difference at this point between `spack compiler find` and `spack external find -t compilers`?  Could the former be an alias for the latter?

Looking through here I don't *think* I see anything special, except maybe executable names are specified differently for compilers.

2025-03-03 07:41 UTC, tgamblin commented on var/spack/repos/builtin.mock/packages/gcc-runtime
> +../../builtin/packages/gcc-runtime
this one also should probably not be a symlink once we split -- need a way to deal with this.

I thought about making this inherit from builtin, but I don't like that either, as then `builtin.mock` depends on `builtin` and we need the full repo to run CI.  I think this and the compiler wrapper should probably be very simplified versions of the real `gcc-runtime` and `cc`

2025-03-03 07:41 UTC, tgamblin commented on var/spack/repos/builtin.mock/packages/gcc/package.py
> +
Note for 1.0: we should ensure that all of these conventions for compiler packages are documented in the packaging guide and elsewhere (if needed).

2025-03-03 07:41 UTC, tgamblin commented on var/spack/repos/builtin.mock/packages/gcc/package.py
> +        assert self.spec.concrete, msg
```suggestion
        assert self.spec.concrete, "cannot retrieve C compiler [spec is not concrete]"
```

2025-03-03 07:41 UTC, tgamblin commented on var/spack/repos/builtin.mock/packages/gcc/package.py
> +        assert self.spec.concrete, msg
```suggestion
        assert self.spec.concrete, "cannot retrieve C++ compiler [spec is not concrete]"
```

2025-03-03 07:41 UTC, tgamblin commented on var/spack/repos/builtin.mock/packages/gcc/package.py
> +        assert self.spec.concrete, msg
```suggestion
        assert self.spec.concrete, "cannot retrieve Fortran compiler [spec is not concrete]"
```

2025-03-03 07:41 UTC, tgamblin commented on var/spack/repos/builtin.mock/packages/gcc/package.py
> +    def fortran(self):
can these three properties be combined into one function?

2025-03-03 07:41 UTC, tgamblin commented on var/spack/repos/builtin.mock/packages/llvm/package.py
> +    provides("c", "cxx", when="+clang")
I know this is the mock package, but remind me -- this does not have an effect on the runtimes, correct?  This just means that if I pick LLVM as my `c` compiler I also need to use it for `c++`, right?  And it won't put a `cxx` virtual on an edge unless the package actually depends on `cxx`, right?

What I want to avoid is that all the C programs inadvertently get the C++ runtime libraries -- if we eventually model `libstdc++` separately from other libs in the runtimes.  the `runtime_constraints` method should be able to assign runtime libs based on which vrituals were requested, right?

2025-03-03 07:41 UTC, tgamblin commented on var/spack/repos/builtin.mock/packages/llvm/package.py
> +        return result
these can be shortened/consolidated like the ones in `gcc`

2025-03-03 07:41 UTC, tgamblin commented on var/spack/repos/builtin.mock/packages/pkg-a/package.py
> +    depends_on("c", type="build")
Do all the mock packages actually need a language dependency?  I think some of them could go without, depending on how they are used in tests, right?

2025-03-03 07:41 UTC, tgamblin commented on var/spack/repos/builtin.mock/packages/gcc/package.py
> +    provides("cxx", when="languages=c++")
Should this actually be 3 lines to model providing C and C++ together?

```python
    provides("c", "cxx", when="languages=c,c++")
    provides("c", when="languages=c")
    provides("cxx", when="languages=c++")
```

2025-03-03 07:41 UTC, tgamblin commented on lib/spack/spack/compilers/libraries.py
> +        all_required_libs = list(self.spec.package.required_libs) + ["libc", "libc++", "libstdc++"]
I think `required_libs` could have a clearer name -- what about `rpath_detection_libs` or something like that?

Also, should the implicit RPATHs change based on what languages are used?  I *believe* they can.

2025-03-03 07:41 UTC, tgamblin commented on lib/spack/spack/cray_manifest.py
> +    return specs[0]
I wonder if this stuff could be integrated as more of an extension to `spack external find -t compilers`, and if `spack compiler find` could be a pure alias for that command.  I think the behavior is different right now if you go through `spack external find` vs. `spack compiler find` right?

2025-03-03 07:41 UTC, tgamblin commented on lib/spack/spack/database.py
> +            raise AttributeError("db version is not yet set")
I think this should say something about why -- e.g. "version not set -- DB has not been read yet"

2025-03-03 07:41 UTC, tgamblin commented on lib/spack/spack/database.py
> +    def raise_explicit_database_upgrade(self):
```suggestion
    def raise_explicit_database_upgrade_error(self):
```

2025-03-03 07:41 UTC, tgamblin commented on lib/spack/spack/directives.py
> -def _language(lang_spec_str: str, *, when: Optional[Union[str, bool]] = None):
awesome to see this removed

2025-03-03 07:41 UTC, tgamblin commented on lib/spack/spack/environment/environment.py
> +lockfile_format_version = 6
update docs too -- the lockfile docs go through the different spec schemas: https://spack.readthedocs.io/en/latest/spack.environment.html#spack-lock-format

2025-03-03 07:41 UTC, tgamblin commented on lib/spack/spack/modules/lmod.py
> +            candidates["cxx"].extend(node.dependencies(virtuals=("c",)))
`has_virtual_dependency()` would read better here too

2025-03-03 16:05 UTC, alalazo commented on .github/workflows/unit_tests.yaml
> +          pip install --upgrade pip setuptools pytest pytest-xdist pytest-cov clingo
In the meanwhile this got removed (it was part of a "TO BE REMOVED" commit).

2025-03-03 16:16 UTC, alalazo commented on etc/spack/defaults/packages.yaml
> +      fortran: [gcc, llvm]
I'll add `intel-oneapi`. Otoh, I wonder if these default "weak" preferences are still very relevant. But I guess we can tweak these values with a much smaller context in a following PR.

2025-03-03 16:22 UTC, alalazo commented on etc/spack/defaults/darwin/packages.yaml
> +    require: gcc
> Is the intent that on macos users will need to do c::, etc. to use a different compiler combination?

That's more of a consequence. The intent is to ship with the default that most users would use anyhow. The advantage of having a requirement is that I can activate static analysis  by default and have a slightly faster concretization.

2025-03-03 17:19 UTC, alalazo commented on lib/spack/spack/binary_distribution.py
> +        assert compiler is not None, "a compiler spec is expected"
This is just an assertion, and the attribute should be there by construction when we read specs from previous formats. Also, as a side note, this shouldn't matter anymore when https://github.com/spack/spack/pull/48713 is merged.

2025-03-03 17:20 UTC, alalazo commented on lib/spack/spack/binary_distribution.py
> +        )
The two PRs seems to not have a lot of conflicts, so any merge order is fine with me.

2025-03-03 17:23 UTC, alalazo commented on var/spack/repos/builtin.mock/packages/compiler-wrapper
> +../../builtin/packages/compiler-wrapper/
The point here is to use the same package as `builtin`, for both the `compiler-wrapper` and `gcc-runtime`. Do we have any idea where the mock repos will live after the split?

2025-03-03 17:24 UTC, alalazo commented on var/spack/repos/builtin/packages/compiler-wrapper/package.py
> +            sha256="84a26f8f37329bcdfb41d23a8a4f4c46efbede983eb73737135c95a4c126b5b7",
> Does this SHA have to be maintained by us or is there some automation? 

Right now it's "maintained by us" :slightly_smiling_face:

2025-03-03 17:29 UTC, alalazo commented on lib/spack/spack/compilers/config.py
> +def find_compilers(
> Could the former be an alias for the latter?

Initialization is also different. Spack external find will not search for a `compilers.yaml` if no compilers are found.

2025-03-03 17:31 UTC, alalazo commented on var/spack/repos/builtin.mock/packages/gcc-runtime
> +../../builtin/packages/gcc-runtime
> I think this and the compiler wrapper should probably be very simplified versions of the real gcc-runtime and cc

The idea was to use the real ones because:
1. They are already very simple
2. They are used almost in every DAG

Simplifying them further, or using different packages, would probably be less effective in immediately catching bugs related to these two packages.

2025-03-03 17:49 UTC, scheibelp commented on lib/spack/spack/solver/asp.py
>                                  clauses.append(
How would this work if I don't want to mix two compilers that share a runtime? Or for example `intel-oneapi-runtime` depends on `gcc-runtime`, and I may not want to mix those compilers.

To be clear, this is about forbidding the mixture of compilers that *could* mix: in terms of what we know about them, they are allowed to mix, but users need to be able to say they can't mix.

Also, regardless of whether this targets a use case, if this behavior inside of the concretizer is desired, I don't think this is the right way to achieve it (i.e. implicitly as a side effect of the overloading of the meaning of a build dependency).

2025-03-03 17:56 UTC, alalazo commented on var/spack/repos/builtin.mock/packages/llvm/package.py
> +    provides("c", "cxx", when="+clang")
> this does not have an effect on the runtimes, correct? This just means that if I pick LLVM as my c compiler I also need to use it for c++, right? And it won't put a cxx virtual on an edge unless the package actually depends on cxx, right?

All correct. But I can't, for instance, say that I want to use `gcc` together with `clang++` on a single node.

2025-03-03 17:57 UTC, alalazo commented on var/spack/repos/builtin.mock/packages/pkg-a/package.py
> +    depends_on("c", type="build")
There are mock packages without language deps

2025-03-04 04:51 UTC, alalazo commented on lib/spack/spack/solver/asp.py
>                                  clauses.append(
I'm confused by your comment.

> Just below here, virtual_on_edge is only added for more-than-just-build dependencies.

All I'm saying is: there are good reasons we don't add pure build dependencies to reused specs in `develop` (they might not be in the buildcache, we don't want to influence what needs to be built because of a build dep of something reused etc.). This doesn't change in this branch, and I think it shouldn't change also _after_ this branch. 

There are other ways to annotate information that don't involve pulling in build dependencies of reused specs in the ASP model.

> Or for example intel-oneapi-runtime depends on gcc-runtime, and I may not want to mix those compilers.

You can check, as an example, how those two runtimes cannot already be mixed in develop wrt fortran, by using a virtual dependency.

2025-03-04 05:51 UTC, alalazo commented on lib/spack/spack/modules/lmod.py
> +            candidates["cxx"].extend(node.dependencies(virtuals=("c",)))
Hmm, here I'm actually using the provider

2025-03-04 05:57 UTC, tgamblin commented on lib/spack/spack/modules/lmod.py
> +            candidates["cxx"].extend(node.dependencies(virtuals=("c",)))
ok ignore here.

2025-03-04 05:58 UTC, tgamblin commented on lib/spack/spack/modules/lmod.py
> +            candidates["cxx"].extend(node.dependencies(virtuals=("c",)))
would it be awful to have a method like `node.virtual_dependencies("c")`?

2025-03-04 06:01 UTC, tgamblin commented on etc/spack/defaults/darwin/packages.yaml
> +    require: gcc
> The advantage of having a requirement is that I can activate static analysis by default and have a slightly faster concretization.

How much faster are we talking?  I am not sure it's worthwhile if users have to remove default config to get a certain behavior.

2025-03-04 06:03 UTC, tgamblin commented on lib/spack/spack/binary_distribution.py
> +        assert compiler is not None, "a compiler spec is expected"
> should be there by construction when we read specs from previous formats

My point is really that you can't assert this. Yes, previous versions of Spack *should* have written this, but you don't know that you're not reading corrupt input -- e.g. a corrupt binary.  In that case the issue isn't Spack; it's the file, so the right response is some invalid format exception, not as assertion.

2025-03-04 06:04 UTC, tgamblin commented on var/spack/repos/builtin.mock/packages/compiler-wrapper
> +../../builtin/packages/compiler-wrapper/
Mock repos will be here, in the main repository. `builtin` will live in a separate git repository.

2025-03-04 06:14 UTC, tgamblin commented on var/spack/repos/builtin/packages/compiler-wrapper/package.py
> +            sha256="84a26f8f37329bcdfb41d23a8a4f4c46efbede983eb73737135c95a4c126b5b7",
How about:

```suggestion
    path = f"{pathlib.PurePath(__file__).parent}/cc.sh"
    url = f"file:///{path}"

    # FIXME (compiler as nodes): use a different tag, since this is only to exclude
    # this node from auto-generated rules
    tags = ["runtime"]

    license("Apache-2.0 OR MIT")

    if sys.platform != "win32":
        version(
            "1.0",
            sha256=hashlib.sha256(open(path, "rb").read()).hexdigest,
```

2025-03-04 06:16 UTC, tgamblin commented on var/spack/repos/builtin.mock/packages/gcc-runtime
> +../../builtin/packages/gcc-runtime
We need some solution because they're not going to be in Spack proper -- they will be in the separate core repository.

2025-03-04 06:18 UTC, tgamblin commented on var/spack/repos/builtin.mock/packages/llvm/package.py
> +    provides("c", "cxx", when="+clang")
I think that's fine -- I don't think it's actually easy to do that w/o playing weird path games. `g++` and `gcc` are almost always going to be in one `bin` dir, and so are `clang++` and `clang`. So I don't think it's reasonable to expect that you can mix C and C++ compilers.

2025-03-04 07:33 UTC, alalazo commented on var/spack/repos/builtin/packages/compiler-wrapper/package.py
> +            sha256="84a26f8f37329bcdfb41d23a8a4f4c46efbede983eb73737135c95a4c126b5b7",
Do we want to open a file and compute a sha256 each time we run Spack?

2025-03-04 07:35 UTC, alalazo commented on lib/spack/spack/database.py
> +    def raise_explicit_database_upgrade(self):
dde9e088d3e6df2e21ed09fe1f85a99f0268d916

2025-03-04 07:36 UTC, alalazo commented on lib/spack/spack/database.py
> +            raise AttributeError("db version is not yet set")
dde9e088d3e6df2e21ed09fe1f85a99f0268d916

2025-03-04 07:38 UTC, alalazo commented on var/spack/repos/builtin.mock/packages/gcc/package.py
> +    provides("cxx", when="languages=c++")
8a65c02e84770261a3ca25a74c656b89f4378864

2025-03-04 07:39 UTC, alalazo commented on var/spack/repos/builtin.mock/packages/gcc/package.py
> +        assert self.spec.concrete, msg
ef43173f75d75c91bd411b979963feec544a5438

2025-03-04 07:39 UTC, alalazo commented on var/spack/repos/builtin.mock/packages/gcc/package.py
> +        assert self.spec.concrete, msg
ef43173f75d75c91bd411b979963feec544a5438

2025-03-04 07:39 UTC, alalazo commented on var/spack/repos/builtin.mock/packages/gcc/package.py
> +        assert self.spec.concrete, msg
ef43173f75d75c91bd411b979963feec544a5438

2025-03-04 07:40 UTC, alalazo commented on var/spack/repos/builtin/packages/compiler-wrapper/package.py
> +        if dependent_spec.dependencies(virtuals=("c",)):
ef49dc66804020a67d35a5bba67b3d3ed2d6f079

2025-03-04 07:40 UTC, alalazo commented on var/spack/repos/builtin/packages/compiler-wrapper/package.py
> +       -Wl,-rpath         arguments for dependency /lib directories.
Improved docstring in 410b81dd1a565d738eeeb01fe9c9b5b758299ddd

2025-03-04 07:41 UTC, tgamblin requested changes
continuing the review...

2025-03-04 07:41 UTC, tgamblin commented on var/spack/repos/builtin/packages/vasp/package.py
> +    requires("^nvhpc+mpi+lapack+blas", when="%nvhpc")
I would really like us to allow the first syntax, because I think it's clearer.  It only means what you say to `clingo` because we made it so -- I think even if we have to special case this to turn circular `when` into a requirement, it's worth doing.

2025-03-04 07:41 UTC, tgamblin commented on var/spack/repos/builtin/packages/python/package.py
> +            return
why's this here?

2025-03-04 07:41 UTC, tgamblin commented on var/spack/repos/builtin/packages/python/package.py
> +            if not dependent_spec.dependencies(virtuals=(language,)):
`has_virtual_dependency(language)`

2025-03-04 07:41 UTC, tgamblin commented on var/spack/repos/builtin/packages/py-petsc4py/ldshared_319.patch
> ++            if flg not in ldcmd and (flg.find('/libexec/spack/') < 0)
```suggestion
+            if flg not in ldcmd and (flg.find('/lib/spack/env') < 0) and (flg.find('/libexec/spack/') < 0)
```

I would do it this way and upstream it to petsc -- so they have the change. This is not my favorite bit of petsc code... I wish they would not try to find spack

2025-03-04 07:41 UTC, tgamblin commented on var/spack/repos/builtin/packages/py-petsc4py/ldshared.patch
> ++        ldshared = [flg for flg in split_quoted(ldshared) if flg not in ldcmd and (flg.find('/libexec/spack')<0)]
make this worth with 1.0 and earlier versions -- then upstream it.

2025-03-04 07:41 UTC, tgamblin commented on var/spack/repos/builtin/packages/openmpi/package.py
> +            env.set(var_name, getattr(dependent_module, attr_name))
```suggestion
            if hasattr(dependent_module, attr_name):
                env.set(var_name, getattr(dependent_module, attr_name))
```

2025-03-04 07:41 UTC, tgamblin commented on var/spack/repos/builtin/packages/openfoam/package.py
> +        "intel-oneapi-compilers": "Icx",
Ok here is a potentially nasty issue -- some compilers can be provided different ways. In particular, `intel-oneapi-compilers` is provided by `intel-oneapi-compilers` *and* by intel-parallel-studio. So I think this is incomplete. How do we allow a user to refer to `oneapi` in any of its forms?

2025-03-04 07:41 UTC, tgamblin commented on var/spack/repos/builtin/packages/msvc/package.py
> +    def setup_dependent_build_environment(self, env, dependent_spec):
I think @johnwparent should look at the msvc logic here, and it would also be good if he could test out the branch.

2025-03-04 07:41 UTC, tgamblin commented on var/spack/repos/builtin/packages/mpich/package.py
> -    def die_without_fortran(self):
hooray! 🎉

2025-03-04 07:41 UTC, tgamblin commented on var/spack/repos/builtin/packages/mapl/package.py
> +    conflicts("^[virtuals=fortran] intel-oneapi-compilers")
another place where we need to conflict with intel-parallel-studio if it's the provider as well.  Need a better way to unify that.

2025-03-04 07:41 UTC, tgamblin commented on var/spack/repos/builtin/packages/lvarray/package.py
> +        compiler_str = f"{self['c'].name}-{self['c'].version}"
```suggestion
        c_compiler = self["c"]
        compiler_str = f"{c_compiler.name}-{c_compiler.version}"
```

2025-03-04 07:41 UTC, tgamblin commented on var/spack/repos/builtin/packages/intel-oneapi-runtime/package.py
> +        oneapi_pkg = self.spec["intel-oneapi-compilers"].package
can't this also come from `intel-parallel-studio`?

2025-03-04 07:41 UTC, tgamblin commented on var/spack/repos/builtin/packages/intel-oneapi-mpi/package.py
> +            env.set(var_name, getattr(dependent_module, attr_name))
```suggestion
            if hasattr(dependent_module, attr_name):
                env.set(var_name, getattr(dependent_module, attr_name))
```

2025-03-04 07:41 UTC, alalazo commented on etc/spack/defaults/packages.yaml
> +      fortran: [gcc, llvm]
I changed the defaults, let me know if they're good now, or if you want further changes.

2025-03-04 07:44 UTC, alalazo commented on var/spack/repos/builtin/packages/python/package.py
> +            if not dependent_spec.dependencies(virtuals=(language,)):
ef49dc66804020a67d35a5bba67b3d3ed2d6f079

2025-03-04 07:50 UTC, alalazo commented on var/spack/repos/builtin/packages/openfoam/package.py
> +        "intel-oneapi-compilers": "Icx",
Isn't `intel-parallel-studio` deprecated? Why do you say that `intel-parallel-studio` provides oneapi compilers?

2025-03-04 08:28 UTC, alalazo commented on var/spack/repos/builtin.mock/packages/gcc/package.py
> +    def fortran(self):
What would be the purpose here? To combine them in the package itself, or to have a unified way to refer to them in the caller?

If that's the latter we can do already:
```python
@property
def c_command(self):
    ...
```
and that would allow us to write `spec["c"].command`. On the other hand, we are discussing how to improve this API in https://github.com/spack/spack/issues/49202 , so I would rather discuss this change in a later PR, based on the outcome of the issue just linked.

2025-03-04 09:53 UTC, alalazo commented on var/spack/repos/builtin/packages/intel-oneapi-mpi/package.py
> +            env.set(var_name, getattr(dependent_module, attr_name))
No prob doing this, but to explain the rationale. Happy path to the left, and I guess I assumed the default is to have the attribute.

2025-03-04 10:00 UTC, alalazo commented on var/spack/repos/builtin/packages/intel-oneapi-runtime/package.py
> +        oneapi_pkg = self.spec["intel-oneapi-compilers"].package
No? Currently:
- `intel-parallel-studio` is completely deprecated, and needs to be removed. I didn't do anything to make it compatible with this PR.
- `intel-oneapi-compilers` provides the OneAPI compilers 
- `intel-oneapi-compilers-classic` provides the classic Intel compilers, and depends on `intel-oneapi-compilers` for the artifacts

Basically, I tried not to modify the modeling of Intel compilers from what is already done on `develop` - to avoid extraneous changes in the PR.

2025-03-04 10:06 UTC, alalazo commented on var/spack/repos/builtin/packages/python/package.py
> +            return
Cause all the logic below is not for Windows (setting the `compiler-wrapper`, setting `LDSHARED` and `LDCXXSHARED`).

2025-03-04 10:30 UTC, alalazo commented on var/spack/repos/builtin/packages/mapl/package.py
> +    conflicts("^[virtuals=fortran] intel-oneapi-compilers")
:thinking:

2025-03-04 10:54 UTC, alalazo commented on var/spack/repos/builtin/packages/openmpi/package.py
> +            env.set(var_name, getattr(dependent_module, attr_name))
3b4ea133d2a076afb424a3f4676c9ff54e977e8d

2025-03-04 10:54 UTC, alalazo commented on var/spack/repos/builtin/packages/intel-oneapi-mpi/package.py
> +            env.set(var_name, getattr(dependent_module, attr_name))
3b4ea133d2a076afb424a3f4676c9ff54e977e8d

2025-03-04 10:55 UTC, alalazo commented on var/spack/repos/builtin/packages/lvarray/package.py
> +        compiler_str = f"{self['c'].name}-{self['c'].version}"
5ffcd791a44762726c4bf9ddeea69a2a4d81a001

2025-03-04 12:58 UTC, alalazo commented on var/spack/repos/builtin/packages/vasp/package.py
> +    requires("^nvhpc+mpi+lapack+blas", when="%nvhpc")
Considering this is true also in `develop`, meaning that we can't:
```python
depends_on("openmpi+foo", when="^openmpi")
```
I propose to move the discussion outside of this PR. What changed here is just that `%` started meaning "has a direct dependency on" which triggers the behavior above.

2025-03-04 13:01 UTC, alalazo commented on var/spack/repos/builtin/packages/ncurses/package.py
> +                flags.append(self["cxx"].standard_flag(language="cxx", standard="14"))
Before doing anything here, it would be probably good to wait for the outcome of https://github.com/spack/spack/issues/49202 Using functions with arguments for standard flags seems in line with the new API for libraries at the moment.

2025-03-04 13:06 UTC, alalazo commented on share/spack/gitlab/cloud_pipelines/stacks/radiuss/spack.yaml
> +      - '%gcc@7.5.0'
Now this file is the same as in develop.

2025-03-04 13:07 UTC, alalazo commented on share/spack/gitlab/cloud_pipelines/stacks/e4s-oneapi/spack.yaml
> +      - '%oneapi'
This file changed, and now this is a requirement, so stronger than a preference.

2025-03-04 13:08 UTC, alalazo commented on share/spack/gitlab/cloud_pipelines/stacks/e4s-cray-rhel/spack.yaml
> +      - "%cce"
This changed to be a requirement also on develop

2025-03-04 13:24 UTC, alalazo commented on etc/spack/defaults/darwin/packages.yaml
> +    require: gcc
> How much faster are we talking?

A couple of seconds on the systems I have access to. Not a game changer.

2025-03-04 13:25 UTC, alalazo commented on lib/spack/spack/binary_distribution.py
> +        assert compiler is not None, "a compiler spec is expected"
I checked, and these modifications are not needed if we merge #48713 first

2025-03-04 13:30 UTC, alalazo commented on var/spack/repos/builtin/packages/compiler-wrapper/package.py
> +        # their way to the default view
No, unless `compiler-wrapper` is a root spec.

2025-03-04 13:54 UTC, alalazo commented on lib/spack/spack/cray_manifest.py
> +    return specs[0]
> I think the behavior is different right now if you go through spack external find vs. spack compiler find right?

Yes, there are a few slight differences on default search paths, which I maintained from `develop`

2025-03-04 18:21 UTC, scheibelp commented on lib/spack/spack/solver/asp.py
>                                  clauses.append(
> You can check, as an example, how those two runtimes cannot already be mixed in develop wrt fortran, by using a virtual dependency.

Are you talking about e.g. https://github.com/spack/spack/pull/48060? If so, that's not going to work for this use case (fortran compatibility isn't the key point). The use cases are as follows:

* X->Y as a link dep, user needs to be able to say that X and Y must have the same c compiler (even if there are two c compilers in the config that Spack thinks are compatible)
* For `X -> [c, cxx, fortran]` the user must be able to say that "they all come from binaries in `/a/single/prefix/with/one/gcc+fortran/implementation/`" (even if there is some other fortran compiler in the config)
  * In terms that might be more natural for this PR: the user must be able to associate c/fortran compilers and require that they always be used together

2025-03-04 19:07 UTC, alalazo commented on lib/spack/spack/solver/asp.py
>                                  clauses.append(
I'll try to be schematic, as I think we don't understand each other:
- What you ask can be done in multiple ways, as an extension of the current ASP encoding
- Adding build dependencies to reused spec is one wrong way to do it (would break most reuse semantic already in develop)

2025-03-04 19:14 UTC, scheibelp commented on lib/spack/spack/solver/asp.py
>                                  clauses.append(
> What you ask can be done in multiple ways, as an extension of the current ASP encoding

OK, can you describe one such way? I'm less optimistic than you about this.

> Adding build dependencies to reused spec is one wrong way to do it (would break most reuse semantic already in develop)

Right now, in terms of this PR, the only way I know how to say "package x used compiler y as a c compiler" is to look at `virtual_on_edge`. If we can do that another way, then that's fine with me (that being said, I'd wonder why you used `virtual_on_edge` to derive this concept for non-reused nodes).

2025-03-04 19:20 UTC, alalazo commented on lib/spack/spack/solver/asp.py
>                                  clauses.append(
> OK, can you describe one such way? I'm less optimistic than you about this.

You can use a fact that is specific to reused specs, without pulling in build deps. That's the same technique we use, in other contexts, e.g. to express libc compatibility, or runtime compatibility. We don't pull-in those libraries for concrete specs, but have a layer of indirection and some rule enforcing the behavior we need.

2025-03-05 09:47 UTC, alalazo commented on etc/spack/defaults/windows/packages.yaml
> +      cxx: [msvc]
Resolving, can be easily addressed in a following PR

2025-03-05 22:04 UTC, scheibelp commented
On the current tip of this branch, if I try to build a package against two compilers in an matrixed env, the concretization is only producing one distinct spec:

```
spack:
  specs:
  - matrix:
    - ["%oneapi", "%gcc"]
    - [umpire+mpi]
  concretizer:
    unify: when_possible
```

Or has the way to specify this changed? I assume with this PR it ought to be straightforward to get a distinct `umpire%oneapi` and `umpire%gcc`.

(This seems new - in the last day or so: up until then my problem has been disabling mixing between dependencies and how to achieve that on top of this, but now the roots themselves seem to be ignoring the compiler assignment)

2025-03-06 09:05 UTC, alalazo commented
> Or has the way to specify this changed? I assume with this PR it ought to be straightforward to get a distinct umpire%oneapi and umpire%gcc.

Did you realize you are asking for:
```yaml
unify: when_possible
```
and that one breaking change in this PR is that `%` now means "direct build dependency of"? So, to recap, you asked for:

1. umpire with gcc as a direct build dependency
2. umpire with oneapi as a direct build dependency
3. unify the specs as much as possible

Without further constraints, the concretizer produced a single spec using oneapi and gcc for different languages. <ins>This is not a bug that went in in the last few days, but just how dependencies work in requests like that.</ins>

Stated otherwise you _should not expect_ that in `develop` an environment like:
```
spack:
  specs:
  - hdf5 ^mpich
  - hdf5 ^zlib-ng
  concretizer:
    unify: when_possible
```
produces 2 specs on concretization. The situation is different when using:
```
unify: false
```


The fact that the environment is matrixed is not relevant to the discussion, since the matrix is just unrolled to:
```yaml
specs:
- umpire %gcc
- umpire %oneapi
```

That said, I demoted the optimization priority of virtual specs associated with language runtimes. This should help minimizing the boilerplate configuration needed in cases where e.g. the preferred `fortran-rt` runtime is `gcc-runtime`, but people asked for `%oneapi` (which implies a `intel-oneapi-runtime` as a provider of `fortran-rt`).

2025-03-06 16:33 UTC, marcmengel commented
Okay, so independent of it being a compiler dependency, if I *wanted* an environment to have both  specs
pkg1 ^pkg2 
pkg1 ^pkg3
installed, but to otherwise unify dependencies as much as possible, there is no way to say that?

2025-03-06 16:44 UTC, alalazo commented
@marcmengel If `pkg2` and `pkg3` are mutually incompatible, then `unify: when_possible` will produce 2 specs with a lot of common nodes, but if they are not mutually incompatible it will just concretize `pkg1 ^pkg2 ^pkg3`.

2025-03-07 11:14 UTC, haampie commented
I've moved the above discussion to #49361, since it's an instance of "lack of notion of compiler toolchain" which we yesterday decided was not a blocker for this PR.

2025-03-08 04:34 UTC, alalazo commented on lib/spack/spack/spec_parser.py
> +            if self.ctx.accept(SpecTokens.COMPILER) or self.ctx.accept(
It should be more DIRECT_BUILD_DEPENDENCY. In any case, I'd wait for a follow-up discussion on https://github.com/spack/spack/issues/44379#issuecomment-2703479190 to change this naming

2025-03-08 05:01 UTC, alalazo commented on var/spack/repos/builtin/packages/llvm-amdgpu/package.py
> +    stdcxx_libs = ("-lstdc++",)
This is just moving:

https://github.com/spack/spack/blob/50b56ee1ce0e7347cd1fb303757bb8f961834f3b/lib/spack/spack/compilers/aocc.py#L99-L101

2025-03-08 05:40 UTC, alalazo commented on lib/spack/spack/spec.py
> +            changed |= self[name].constrain(other[name], deps=True)
Forgot to reply here. That's because abstract specs are not depth=1 anymore, but can be depth=2. Think for instance:
```
mpileaks ^callpath %gcc@5
mpileaks ^callpath %gcc@6
```
The `gcc` is a direct dependency of callpath. I'll add some more unit tests to make this clear.

2025-03-08 06:37 UTC, alalazo commented on lib/spack/spack/spec.py
> +            changed |= self[name].constrain(other[name], deps=True)
See c0e0ad501768e32e598a661c786247dd7ac2da05

2025-03-08 06:53 UTC, alalazo commented on var/spack/repos/builtin.mock/packages/compiler-wrapper
> +../../builtin/packages/compiler-wrapper/
I guess this may stay, and when we split we'll copy the two packages (if we don't find a better solution)? Copying now is also feasible, but that will drop having builtin in sync with mock for these packages.

2025-03-08 07:00 UTC, alalazo commented on var/spack/repos/builtin.mock/packages/llvm/package.py
> +        return result
https://github.com/spack/spack/pull/45189#discussion_r1978882475

2025-03-08 07:58 UTC, alalazo commented on var/spack/repos/builtin/packages/compiler-wrapper/cc.sh
> +        fi
> we shouldn't actually need a linker arg b/c we have been invoked as the linker.

Here I tried to keep the modifications to `cc.sh` minimal. It's true what you say, but at that point also `rpath` is not needed in ld mode. This is a change that can also be done on develop directly, so I'd rather do that than conflate it here.

2025-03-08 09:42 UTC, alalazo commented on lib/spack/spack/modules/lmod.py
> +            candidates["cxx"].extend(node.dependencies(virtuals=("c",)))
What would be the purpose? To return `Optional[Spec]`?

2025-03-08 09:46 UTC, alalazo commented on var/spack/repos/builtin/packages/acfl/package.py
> +    link_paths = {
Done in a0e1e116c12abeb5f92d902336746ee8b59862ed

2025-03-08 10:55 UTC, alalazo commented on var/spack/repos/builtin/packages/compiler-wrapper/package.py
> +            sha256="84a26f8f37329bcdfb41d23a8a4f4c46efbede983eb73737135c95a4c126b5b7",
I'm not really a fan of opening a file and computing a sha256 each time we define this class. It's probably better to update manually for now.

2025-03-08 11:14 UTC, alalazo commented on var/spack/repos/builtin/packages/openfoam/package.py
> +        "intel-oneapi-compilers": "Icx",
See https://github.com/spack/spack/pull/45188 which will remove Intel packages that have been deprecated in 2023. 

In any case we don't have issues if two packages provide the same compiler, in the sense that it will either be:
```
pkg_a %provider1
```
vs.
```
pkg_b %provider2
```
for legacy compilers `%intel` is provided by `intel-oneapi-compilers-classic`.

2025-03-10 06:12 UTC, tgamblin commented on etc/spack/defaults/darwin/packages.yaml
> +    require: gcc
Ok I'd say let's *not* make this a requirement if it's a couple seconds out of more. Would making it a strong preference make more sense?  Or should we just remove the requirement and leave the toolchain semantics to #49361?

2025-03-10 06:14 UTC, tgamblin commented on var/spack/repos/builtin.mock/packages/compiler-wrapper
> +../../builtin/packages/compiler-wrapper/
Ok let's keep it as-is until the split. Can you add this to https://github.com/spack/spack/issues/47480?

2025-03-10 06:15 UTC, tgamblin commented on var/spack/repos/builtin/packages/compiler-wrapper/cc.sh
> +        fi
I guess my question here is why make the change at all?  It's an addition to the existing script -- was it needed for something?

2025-03-10 06:22 UTC, tgamblin commented on var/spack/repos/builtin/packages/compiler-wrapper/package.py
> +            sha256="84a26f8f37329bcdfb41d23a8a4f4c46efbede983eb73737135c95a4c126b5b7",
would something like this make more sense?

```diff
diff --git a/var/spack/repos/builtin/packages/compiler-wrapper/package.py b/var/spack/repos/builtin/packages/compiler-wrapper/package.py
index 06c51b0fda..d438ed3076 100644
--- a/var/spack/repos/builtin/packages/compiler-wrapper/package.py
+++ b/var/spack/repos/builtin/packages/compiler-wrapper/package.py
@@ -1,6 +1,7 @@
 # Copyright Spack Project Developers. See COPYRIGHT file for details.
 #
 # SPDX-License-Identifier: (Apache-2.0 OR MIT)
+import hashlib
 import pathlib
 import shutil
 import sys
@@ -31,8 +32,9 @@ class CompilerWrapper(Package):
     3. It provides a mechanism to inject flags from specs
     """

+    cc_path = f"{pathlib.PurePath(__file__).parent}/cc.sh"
     homepage = "https://github.com/spack/spack"
-    url = f"file:///{pathlib.PurePath(__file__).parent}/cc.sh"
+    url = f"file:///{cc_path}"

     # FIXME (compiler as nodes): use a different tag, since this is only to exclude
     # this node from auto-generated rules
@@ -41,11 +43,9 @@ class CompilerWrapper(Package):
     license("Apache-2.0 OR MIT")

     if sys.platform != "win32":
-        version(
-            "1.0",
-            sha256="84a26f8f37329bcdfb41d23a8a4f4c46efbede983eb73737135c95a4c126b5b7",
-            expand=False,
-        )
+        with open("cc_path", "rb") as cc:
+            cc_sha256 = hashlib.sha256(cc.read()).hexdigest()
+        version("1.0", sha256=cc_sha256, expand=False)
     else:
         version("1.0")
         has_code = False
```

2025-03-10 06:22 UTC, tgamblin commented on lib/spack/spack/compilers/config.py
> +def find_compilers(
ok let's keep changes on this PR to a minimum and maybe refine later -- doesn't seem worth holding up the PR over.

2025-03-10 06:23 UTC, tgamblin commented on var/spack/repos/builtin.mock/packages/gcc-runtime
> +../../builtin/packages/gcc-runtime
decided on a separate thread to leave this til we split the repo, but update https://github.com/spack/spack/issues/47480 so we don't forget.

2025-03-10 06:29 UTC, tgamblin commented on var/spack/repos/builtin.mock/packages/gcc/package.py
> +    def fortran(self):
Sorry I wasn't clear enough. I don't mean to get rid of the properties -- just DRY, e.g.:

```python
    def _compiler_exe(self, lang: str, compiler_name: str) -> Optional[str]:
        assert self.spec.concrete, f"cannot retrieve {lang} compiler [spec is not concrete]"
        if self.spec.external:
            return self.spec.extra_attributes["compilers"].get(lang, None)
        result = None
        if f"languages={lang}" in self.spec:
            result = os.path.join(self.spec.prefix.bin, compiler_name)
        return result

    @property
    def cc(self) -> Optional[str]:
        return self._compiler_exe("c", "gcc")

    @property
    def cxx(self) -> Optional[str]:
        return self._compiler_exe("c", "g++")

    @property
    def fortran(self) -> Optional[str]:
        return self._compiler_exe("c", "gfortran")
```

2025-03-10 06:29 UTC, tgamblin commented on var/spack/repos/builtin.mock/packages/llvm/package.py
> +        return result
https://github.com/spack/spack/pull/45189#discussion_r1986679415

2025-03-10 06:31 UTC, tgamblin commented on lib/spack/spack/modules/lmod.py
> +            candidates["cxx"].extend(node.dependencies(virtuals=("c",)))
yep but I don't think I care as much about this one.

2025-03-10 06:33 UTC, tgamblin commented on var/spack/repos/builtin/packages/compiler-wrapper/package.py
> +            sha256="84a26f8f37329bcdfb41d23a8a4f4c46efbede983eb73737135c95a4c126b5b7",
It's very easy to compute a sha256.  But sure, better to update it at fetch time like we do for repo-resident patches.  Maybe something to leave for immediately after this PR.  I don't like the maintenance burden of manually computing a hash for a file in the repo but ok let's leave it for now.

2025-03-10 06:34 UTC, tgamblin commented on var/spack/repos/builtin/packages/intel-oneapi-runtime/package.py
> +        oneapi_pkg = self.spec["intel-oneapi-compilers"].package
I think this falls in the realm of "need a compiler toolchain concept anyway so ok, let's close this here.

2025-03-10 06:41 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
>                                  clauses.append(
I'm with max on this one -- I think we can defer this to the larger toolchain/compiler resolution semantics discussion

2025-03-10 12:32 UTC, alalazo commented on var/spack/repos/builtin/packages/compiler-wrapper/cc.sh
> +        fi
Iirc we were hitting the lines:
```
linker_arg="${SPACK_LINKER_ARG}"

# Set up rpath variable according to language.
rpath="ERROR: RPATH ARG WAS NOT SET"
eval "rpath=\${SPACK_${comp}_RPATH_ARG:?${rpath}}"
```
below, in some cases, with packages needing a C++ compiler, but without a C compiler. This was causing errors. I didn't add a corresponding case for Fortran cause currently we don't have cases of packages depending only on Fortran.

My thought is that we can refactor this script in a separate PR with a much smaller scope, and see if we can set `linker_arg` etc. conditionally (and not require them to be set, when mode=ld).

2025-03-12 07:54 UTC, tgamblin requested changes
More questions as I'm moving through -- I think I will be done for real tomorrow.

2025-03-12 07:54 UTC, tgamblin commented on lib/spack/spack/aliases.py
> +}
```suggestion
LEGACY_COMPILER_TO_BUILTIN = {value, key for key, value in BUILTIN_TO_LEGACY_COMPILER.items()}

2025-03-12 07:54 UTC, tgamblin commented on lib/spack/spack/build_environment.py
> +    version_number, _ = archspec.cpu.version_components(compiler.version.dotted_numeric_string)
comment should be revised to remove the part about suffixes.

2025-03-12 07:54 UTC, tgamblin commented on lib/spack/spack/build_environment.py
> +
I'm a little torn on these -- they seem like they should be set by the compiler wrapper package, *except* that one relies on spack configuration.   I don't think we have any packages that talk to `config`, so maybe the second part of this does belong here.

2025-03-12 07:54 UTC, tgamblin commented on lib/spack/spack/build_environment.py
> +    for x in env_by_name["SPACK_ENV_PATH"]:
This variable probably deserves a rename -- ENV is overloaded and as of this PR the `lib/spack/env` directory it refers to no longer exists.

2025-03-12 07:54 UTC, tgamblin commented on lib/spack/spack/cmd/compiler.py
> +        colify(reversed(sorted(c.format("{name}@{version}") for c in compilers)))
We should probably display more than name and version now - I almost think we should just show output like `spack find`. But maybe it's something to leave for the toolchain PR.

2025-03-12 07:54 UTC, tgamblin commented on lib/spack/spack/spec.py
> +class CompilerSpec:
it looks like this is only used in `concretize.py` and in `package_prefs.py` -- do we even need it?  Can the other code not just interface with `Specs`?

2025-03-12 07:54 UTC, tgamblin commented on lib/spack/spack/spec.py
> +            # FIXME: atm allow '%' on abstract specs only if they depend on C, C++, or Fortran
I would delete this comment since we are making `%` mean direct dep.

2025-03-12 07:54 UTC, tgamblin commented on lib/spack/spack/spec.py
> +            changed |= self[name].constrain(other[name], deps=True)
might be worth commenting here that this doesn't handle constraining transitive dependencies with the same name as direct dependencies. That may never matter but it's not complete since we started allowing dupes.

2025-03-12 07:54 UTC, tgamblin commented on lib/spack/spack/spec.py
> +                # name is the same as the child name
this is true for constrain() and intersect() as well -- maybe somehow note that.

2025-03-12 07:54 UTC, tgamblin commented on lib/spack/spack/database.py
> +        )
This should advise the user that:
1. the migration is destructive
2. older spack cannot read the newer database
3. consider backing up first.

It might be good to automatically back up the old DB, too. I think users will thank us for that (and we might want it for debugging once this feature is live).

2025-03-12 07:54 UTC, tgamblin commented on lib/spack/spack/spec_parser.py
> +            if self.ctx.accept(SpecTokens.COMPILER) or self.ctx.accept(
`DIRECT_DEPENDENCY`

2025-03-12 07:54 UTC, tgamblin commented on lib/spack/spack/test/compilers/basics.py
> -    assert any(x == "-foo-flag foo-val" for x in compiler.flags["cflags"])
should this be translated for the new `packages.yaml` format?

2025-03-12 07:54 UTC, tgamblin commented on share/spack/gitlab/cloud_pipelines/configs/cray-rhel/x86_64_v3/packages.yaml
> +    - "target=x86_64_v3"
do we need both the target and require lines here? seems like just require would be fine.

2025-03-13 05:39 UTC, tgamblin commented on var/spack/repos/compiler_runtime.test/packages/compiler-wrapper
> +../../builtin/packages/compiler-wrapper/
I'm fine with the symlinks for now, but we need a better way to test this stuff once we split the repo out. I feel like there are only so many options:

1. mock this stuff up in the main spack repo
2. move these tests to the package repository (should we really have unit tests there?)
3. rely on builtin repo for some core tests? (seems clunky)
4. convert some of this to unit tests and some to integration tests that run in the builtin repo?

I can't decide and I think there's more to untangle there than we might think.  

I *do* think there is some merit to having simplified unit tests for the compilers and runtimes, so I kind of lean towards (1). I haven't thought it all the way through, though -- so let's treat this as a follow-on to this PR. We have to do something before splitting anyway.

2025-03-13 06:09 UTC, tgamblin requested changes
still moving along...

2025-03-13 06:09 UTC, tgamblin commented on var/spack/repos/builtin/packages/python/package.py
> +            filter_file(spack_cxx, self["cxx"].cxx, *filenames, **kwargs)
should `python` just use the `filter_compiler_wrappers()` directive?

2025-03-13 06:09 UTC, tgamblin commented on var/spack/repos/builtin/packages/python/package.py
> +            return
can you add a comment saying that the stuff below is wrapper specific? it's not clear from just the `if` statement.

2025-03-13 06:09 UTC, tgamblin commented on var/spack/repos/builtin/packages/nvhpc/package.py
> +    depends_on("gcc languages=c,c++,fortran", type="run")
I'm a little confused by this. `nvhpc` doesn't need `fortran` at all -- pretty sure it's written in C++. So only really needs `libstdc++` (and even then it expects that there is one on the system and doesn't RPATH or anything).  

It *does* rely on `libstdc++` as the C++ runtime library for compiled programs (much as intel compilers do) So I think we only really need c++ or c,c++ enabled here, and fortran shouldn't be required.

2025-03-13 06:09 UTC, tgamblin commented on var/spack/repos/builtin/packages/intel-oneapi-compilers/package.py
> +    required_libs = [
I still think this name (used only in implicit RPATH detection) is confusing.

2025-03-13 07:40 UTC, alalazo commented on var/spack/repos/compiler_runtime.test/packages/compiler-wrapper
> +../../builtin/packages/compiler-wrapper/
@tgamblin Note: here we are really talking about `gcc-runtime` and `compiler-wrapper`, which ultimately point to `builtin`. The other symlinks are from other test repo to `builtin.mock`, and are there to just DRY.

2025-03-13 10:14 UTC, alalazo commented on lib/spack/spack/spec_parser.py
> +            if self.ctx.accept(SpecTokens.COMPILER) or self.ctx.accept(
I agree with `DIRECT_DEPENDENCY` and this one is definitely an easy change. That said, if there are no strong opinions on doing it right now, I would reserve it for the next PR, where we'll change the semantic of `%` to be a direct dependency.

Doing the renaming here will be inline with what we want to do, but the feature won't be implemented, so it seems to me the change doesn't belong here. I would leave `COMPILER_*` for now, since parsing is still backward compatible with the compiler token.

2025-03-13 10:20 UTC, alalazo commented on var/spack/repos/builtin.mock/packages/compiler-wrapper
> +../../builtin/packages/compiler-wrapper/
Added an item in #47480 under "Assess Untangling Unit Tests"

2025-03-13 10:21 UTC, alalazo commented on var/spack/repos/builtin.mock/packages/gcc-runtime
> +../../builtin/packages/gcc-runtime
https://github.com/spack/spack/pull/45189#discussion_r1993206225

2025-03-13 11:30 UTC, alalazo commented on var/spack/repos/builtin.mock/packages/llvm/package.py
> +        return result
See https://github.com/spack/spack/pull/45189/commits/abaced6f3d9ec941dfeb5a68e8a9020f8552a561

2025-03-13 11:30 UTC, alalazo commented on var/spack/repos/builtin.mock/packages/gcc/package.py
> +    def fortran(self):
See https://github.com/spack/spack/pull/45189/commits/abaced6f3d9ec941dfeb5a68e8a9020f8552a561

2025-03-13 11:31 UTC, alalazo commented on var/spack/repos/builtin/packages/python/package.py
> +            return
See https://github.com/spack/spack/pull/45189/commits/0cae1bf29297f3456b8fad3fed5bc108f5372fc7

2025-03-13 11:32 UTC, alalazo commented on var/spack/repos/builtin/packages/py-petsc4py/ldshared_319.patch
> ++            if flg not in ldcmd and (flg.find('/libexec/spack/') < 0)
See 8b7a7462f0132ed2a59803c1fab41ee5aff95975

2025-03-13 11:33 UTC, alalazo commented on var/spack/repos/builtin/packages/py-petsc4py/ldshared.patch
> ++        ldshared = [flg for flg in split_quoted(ldshared) if flg not in ldcmd and (flg.find('/libexec/spack')<0)]
See 8b7a7462f0132ed2a59803c1fab41ee5aff95975 I didn't upstream it yet (though I'd say it would be better if they find a permanent solution that doesn't require hard-coding paths)

2025-03-13 12:39 UTC, wrwilliams commented on var/spack/repos/builtin.mock/packages/gcc/package.py
>      variant(
Should compiler plugin support be a variant for GCC (and also LLVM-based compilers)? In each case it is possible for the compiler (especially if external) to be installed without the headers/libs needed to build plugins. See without too much loss of generality #42497 for a relevant use case.

2025-03-13 13:26 UTC, alalazo commented on var/spack/repos/builtin.mock/packages/gcc/package.py
>      variant(
Is this a general question on `gcc`? Not sure what you mean here, since you commented on a mock package used for unit tests, and linked an issue talking about `python+tkinter` :thinking:

2025-03-13 13:35 UTC, wrwilliams commented on var/spack/repos/builtin.mock/packages/gcc/package.py
>      variant(
Sorry, I meant to put this on `var/spack/repos/builtin/packages/gcc/package.py`, and have updated the PR number to what should be correct (Score-P getting `+gcc-plugin` as a variant; life there becomes simpler if we can depend on `^gcc+plugin-support` or similar). So yes, a general `gcc` question.

2025-03-13 13:46 UTC, alalazo commented on var/spack/repos/builtin.mock/packages/gcc/package.py
>      variant(
Ok, so in this case the answer is yes. Since using this PR compilers become dependencies, you can enforce constraints like:
```python
requires("^gcc+plugin", when="^[virtuals=c,cxx] gcc")
```
meaning "whenever I'm using gcc as a C and C++ compiler, I require it to have the +plugin variant".

If you want to submit a separate PR to add that variant to `gcc`, that would be welcome :slightly_smiling_face:

2025-03-13 15:22 UTC, alalazo commented on lib/spack/spack/build_environment.py
> +
For what is worth I moved them here exactly because they depend on configuration, so I added another layer of indirection. This way the repo and Spack core are surely less coupled. 

A good example to see that would be moving that config option somewhere else in our yaml files. If we read config in `compiler-wrapper` we would need to do something to deal with backward incompatibilities of repos / spack versions before and after the change. In the current state of things, instead, we don't.

2025-03-13 15:25 UTC, alalazo commented on lib/spack/spack/build_environment.py
> +    for x in env_by_name["SPACK_ENV_PATH"]:
Do you have any preferred name? `SPACK_COMPILER_WRAPPER_PATH`?

2025-03-13 15:27 UTC, alalazo commented on lib/spack/spack/cmd/compiler.py
> +        colify(reversed(sorted(c.format("{name}@{version}") for c in compilers)))
Yeah, I would leave that for smaller, and more focused, PRs.

2025-03-13 15:34 UTC, alalazo commented on lib/spack/spack/spec.py
> +class CompilerSpec:
This might not be apparent, but it's what is used to avoid changing all the recipes that use `spec.compiler`. I'll check why it is still used in core code, the answer is possibly because it was not, but some rebasing reintroduced a couple of places.

If you want to check how this works, you can look at:
```python
class DeprecatedCompilerSpec
```
which a descriptor used to generate the value of `spec.compiler` on demand. We can change how the descriptor behaves later, to start issuing warnings, or to error out.

2025-03-13 15:47 UTC, alalazo commented on lib/spack/spack/spec.py
> +            # FIXME: atm allow '%' on abstract specs only if they depend on C, C++, or Fortran
I'm undecided on this one, but I think I would leave it for now, and remove in the PR where we change the parser. When we remove it, we also need to remove the check below.

Basically, this is just a place to catch early packages that do stuff like:
```
foo %gcc
```
with `foo` not depending on any of C, C++, and Fortran. The check is also not 100% correct, in the sense that for those packages it would also prevent doing `foo %cmake`, but I thought it was fine to leave it for a while.

Alternatives are to remove this block, and have concretization errors for:
```
foo %gcc
```
which would take longer and are currently not great. It's true, though, that packages that don't depend on any language are kind of rare, so let me know what you prefer between leave this FIXME, or remove it with the check below.

2025-03-13 15:58 UTC, alalazo commented on share/spack/gitlab/cloud_pipelines/configs/cray-rhel/x86_64_v3/packages.yaml
> +    - "target=x86_64_v3"
Using `target` makes the required target also the preferred one. It should help in case some package overrides the default requirements.

2025-03-14 12:37 UTC, alalazo commented
@spackbot rebuild everything (I need to regenerate a buildcache with the old lyout)

2025-03-14 12:40 UTC, alalazo commented
@spackbot commands

2025-03-14 12:40 UTC, alalazo commented
@spackbot rebuild everything

2025-03-17 10:53 UTC, alalazo commented on var/spack/repos/builtin/packages/nvhpc/package.py
> +    depends_on("gcc languages=c,c++,fortran", type="run")
I took this from nvidia docs (without investigating further): https://docs.nvidia.com/hpc-sdk/hpc-sdk-install-guide/index.html#prepare-to-install-on-linux 

> Linux installations require some version of the GNU Compiler Collection (including gcc, g++, and gfortran compilers) to be installed and in your $PATH prior to installing HPC SDK software.

2025-03-19 11:38 UTC, alalazo commented on etc/spack/defaults/darwin/packages.yaml
> +    require: gcc
Strong preference here: https://github.com/spack/spack/pull/45189/commits/6277ebae26b26a461cd4a782b3201b1340d9c459

2025-03-19 13:30 UTC, alalazo commented on lib/spack/spack/test/compilers/basics.py
> -    assert any(x == "-foo-flag foo-val" for x in compiler.flags["cflags"])
I don't think so. It should be covered by:
```
lib/spack/spack/test/concretization/flag_mixing.py::test_flag_order_and_grouping
```

2025-03-21 12:58 UTC, tgamblin commented on var/spack/repos/builtin/packages/intel-oneapi-compilers/package.py
> +    required_libs = [
Let's change this to `implicit_rpath_libs` and document it.

2025-03-21 13:03 UTC, tgamblin commented on lib/spack/spack/compilers/libraries.py
> +        all_required_libs = list(self.spec.package.required_libs) + ["libc", "libc++", "libstdc++"]
`implicit_rpath_libs`

2025-03-21 13:05 UTC, tgamblin commented on lib/spack/spack/build_environment.py
> +
can you add this to the untangling the repo list?

2025-03-21 13:06 UTC, tgamblin commented on lib/spack/spack/build_environment.py
> +    for x in env_by_name["SPACK_ENV_PATH"]:
I like that one.

2025-03-21 15:43 UTC, tgamblin commented on lib/spack/spack/binary_distribution.py
> +        assert compiler is not None, "a compiler spec is expected"
What about now that this is likely to go in first?

2025-03-21 16:07 UTC, tgamblin commented on var/spack/repos/builtin/packages/cmake/package.py
> -        return (flags, None, None)
do we not still need to do this for the fujitsu compiler?

2025-03-22 01:58 UTC, tgamblin requested changes
Ok I am done with a pass over the whole PR.  Overall this looks great -- I do not see anything that should hold up merging now that tests are passing and we have had people try this branch out quite a bit.

I do see places that we are going to need to note for decoupling the repo and for increasing the generality of the compiler deps support.  We should note that stuff and mark it to be done in a follow-on. I would prioritize decoupling the repo over complete generality but I don't know if that is possible -- right now the concretizer knows about the `compiler-wrapper`, the various runtime names, etc. I think we should try to minimize that and develop something that comes from the package API, but we will need to see what there is time for.

@alalazo: I tried to resolve earlier change requests that I think are done. Can you go through the remaining change requests (many of which I said are for later) and either document them as things to do later, or address/resolve/object to them? I do not think there are many remaining things to do before merging.

Thanks for all the work on this!

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/test/spec_syntax.py
> +    with pytest.raises(spack.solver.asp.UnsatisfiableSpecError) as exc_info:
why is this raising `UnsatisfiableSpecError` now? I actually think the unknown package error is more descriptive here.

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/test/concretization/requirements.py
> +    assert s.satisfies("%llvm")
should also test that this satisfies `%clang` as an alias.

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/test/concretization/core.py
> +            if "c" not in x or not x.name.startswith("dt-diamond"):
This is intended to omit the compilers, right? This is going to stop working once we allow bootstrapped compilers (and externals with deps).  That's ok but we should probably note it somewhere.

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/test/concretization/core.py
> +            # %gcc is preferred to clang in config, it will be used for most nodes
I wonder if we will need to rethink this. We can do it after, but we should discuss.  My first inclination when looking at this is that I would expect propagation of a requested compiler, even for mixed toolchains. I am not sure why I wouldn't want that.  Let's save the discussion for the toolchain concept PR, where I think it fits best.

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/test/concretization/core.py
> +    """Tests that a compiler can depend on itself to bootstrap."""
```suggestion
    """Tests that a compiler can depend on "itself" to bootstrap."""
```

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/solver/libc_compatibility.lp
> +%   not attr("compatible_libc", node(R, ReusedPackage), _, _).
why's this commented?

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> +    control.configuration.solver.opt_strategy = "usc,one,1"
I would love to know how this helped.

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> -
don't we still need virtual preferences?

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> +        self.gen.h1("Runtimes")
We should eventually call this something else -- e.g. injected constraints (i.e. injected from packages) as "runtime constraints" is more specific than what this really enables. Can be for after the PR though -- it is already more general than it was before.

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> +            # Add a dependency on the compiler wrapper
Couldn't wrapped compiler classes inject this instead? i.e. WrappedCompiler is the base class you use to get this, and *it* defines `runtime_constriants` to inject the wrapper. Not necessary for this PR -- there is already a note about the generality here.

I think this is related to decoupling the repo as well.  You should probably be able to build a repo that doesn't have a wrapper.

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> +        if using_libc_compatibility() and not CompilerPropertyDetector(c).default_libc():
there are a lot of calls to compilers here -- later we may want to consider parallelizing them up front so they don't slow down setup.  I haven't measured though... maybe they're insignificant but some of these (e.g. intel w/license server) can be slow.

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> +                f"duplicate {c.long_spec} compiler found. Edit your packages.yaml to remove it."
I think we shouldn't warn if the duplicate is coming from layered config.

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> +        # constraint_spec.name = placeholder
delete this?

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> +        return False
Another coupling between core and repo. Maybe this one should be a package property.

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> +    if "intel-oneapi-compilers" in spec and "intel-oneapi-runtime" not in spec:
We should make a note to make this less specific -- I think this is only called to determine reusability so maybe a case for a package property (maybe we need, e.g. `reusable` and `dependents_reusable`?) shortly after this PR.

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> +                    deps = {edge.spec.name for edge in s.edges_to_dependencies() if edge.direct}
when does this come up?

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/solver/concretize.lp
> +{ attr("version", node(ID, Package), Version) : pkg_fact(Package, version_satisfies(Constraint, Version)) }
Pretty sure the comment for this and the rule above is wrong now. What does this do?

I'm not seeing, in version semantics, where we say we can't have two versions assigned to a node. I see it for virtuals but not for regular nodes... did something get lost?

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/solver/concretize.lp
> +    CompilerNode1 != CompilerNode2.
I wonder if we could avoid hard-coding these and have them as package properties. Not in this PR but later.

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/solver/concretize.lp
> +    CompilerNode1 != CompilerNode2.
I wonder if we could avoid hard-coding these and have them as package properties.

2025-03-22 01:58 UTC, tgamblin commented on lib/spack/spack/solver/concretize.lp
> +
this also seems very hard-coded and needs generalization later for other runtimes.

2025-03-24 04:56 UTC, alalazo commented on var/spack/repos/builtin/packages/esmf/package.py
> +        elif spec["fortran"].name == "gcc" and spec["c"].name in ["clang", "apple-clang"]:
I'm resolving conversation. If we have issues on `esmf` we can fix later with a smaller scope PR.

2025-03-24 08:23 UTC, haampie commented on lib/spack/spack/solver/asp.py
> +            f"  not runtime(Package)"
```suggestion
            f"  not external({node_variable})"
```

The `compiler-wrapper` package needs to be a dependency of runtimes too (if they are compiled).

2025-03-24 09:32 UTC, alalazo commented on lib/spack/spack/build_environment.py
> +
Added a reference to this discussion in https://github.com/spack/spack/issues/47480#compiler-wrappers

2025-03-24 12:13 UTC, alalazo commented on lib/spack/spack/solver/asp.py
> +        self.gen.h1("Runtimes")
Yeah, I agree. We should probably come up with different names for "runtime" entities, and a generalization of the concept of "runtimes" in a following PR.  

We also need to consider `hip` as a use case when generalizing the model, since it introduces a runtime with a huge DAG, whereas up to now we kind of assume runtimes are relatively small, and extracted from a "compiler" package.

2025-03-24 12:17 UTC, alalazo commented on lib/spack/spack/solver/asp.py
> +                    deps = {edge.spec.name for edge in s.edges_to_dependencies() if edge.direct}
I expect this to come up mainly for packages that don't need a compiler:
```console
$ spack spec py-cinemasci %gcc
==> Error: 'py-cinemasci %gcc' cannot depend on gcc
```

2025-03-24 12:21 UTC, alalazo commented on lib/spack/spack/solver/concretize.lp
> +
This is needed to avoid that the solver could pull-in a better runtime from a buildcache, if the nodes to be built are using another compiler.

2025-03-24 15:52 UTC, alalazo commented on lib/spack/spack/bootstrap/_common.py
>          spec_str += " %clang"
Removed in 1de928060d13f635c132734f71d48cf957374110

2025-03-24 15:52 UTC, alalazo commented on lib/spack/spack/compilers/libraries.py
> +        all_required_libs = list(self.spec.package.required_libs) + ["libc", "libc++", "libstdc++"]
See c27eb174630e2b8a468da91abe47797a679873d9

2025-03-24 15:56 UTC, alalazo commented on lib/spack/spack/build_environment.py
> +    for x in env_by_name["SPACK_ENV_PATH"]:
See 0effc050aac546ba8593ade682fcb9e4920cb075

2025-03-24 15:57 UTC, alalazo commented on lib/spack/spack/spec.py
> +            changed |= self[name].constrain(other[name], deps=True)
See 20c69a74316b19d8ec7d8da9700146c37e4271fc

2025-03-24 15:57 UTC, alalazo commented on lib/spack/spack/spec.py
> +                # name is the same as the child name
See 20c69a74316b19d8ec7d8da9700146c37e4271fc

2025-03-24 15:58 UTC, alalazo commented on lib/spack/spack/database.py
> +        )
See dc3f98ed131a217e7e30c498fea192cae82dd50d

![Screenshot from 2025-03-24 16-58-16](https://github.com/user-attachments/assets/a43f1ab6-da2c-4f7d-b775-eca4822f9b51)

2025-03-24 16:08 UTC, alalazo commented on lib/spack/spack/aliases.py
> +}
I don't have strong objections, but for something that is this localized, and short, I would just avoid computations done each time we import `spack.aliases`.

2025-03-24 16:15 UTC, alalazo commented on var/spack/repos/builtin/packages/python/package.py
> +            filter_file(spack_cxx, self["cxx"].cxx, *filenames, **kwargs)
Maybe? I wouldn't change this here, since the changes above are just the minimum required to maintain the logic in `develop`

2025-03-24 16:15 UTC, alalazo commented on var/spack/repos/builtin/packages/intel-oneapi-compilers/package.py
> +    required_libs = [
See c27eb174630e2b8a468da91abe47797a679873d9

2025-03-24 16:31 UTC, alalazo commented on var/spack/repos/builtin/packages/cmake/package.py
> -        return (flags, None, None)
My understanding is that we don't need it anymore: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5954

2025-03-24 17:03 UTC, alalazo commented on lib/spack/spack/test/spec_syntax.py
> +    with pytest.raises(spack.solver.asp.UnsatisfiableSpecError) as exc_info:
Not sure about that. I intercepted the unknown package error to emit a better error message. Previously it was:
```
==> Error: Package 'spack.pkg.builtin.mock.doesnotexist' not found.
Use 'spack create' to create a new package.

Did you mean one of the following packages?
  svn-test
```
Now it says:
```
Error: cannot concretize 'doesnotexist', since 'doesnotexist' does not exist
```

2025-03-24 17:19 UTC, alalazo commented on lib/spack/spack/solver/libc_compatibility.lp
> +%   not attr("compatible_libc", node(R, ReusedPackage), _, _).
Forgot to delete. It should be substituted by the two errors above. The unit-test `test_cannot_reuse_host_incompatible_libc` should prevent regressions.

2025-03-24 17:21 UTC, alalazo commented on lib/spack/spack/solver/asp.py
> +    control.configuration.solver.opt_strategy = "usc,one,1"
_How_ I don't know :upside_down_face:  I just run some brute force timings with different options, and this one seemed to "regularize" times across radiuss specs + a few propagation tests

2025-03-24 17:26 UTC, alalazo commented on lib/spack/spack/solver/asp.py
> -
We have them, but not per-package, see `self.provider_defaults`.

2025-03-24 17:29 UTC, alalazo commented on lib/spack/spack/solver/asp.py
> +            # Add a dependency on the compiler wrapper
I agree with making this more general in a following PR.

2025-03-24 17:44 UTC, alalazo commented on lib/spack/spack/solver/concretize.lp
> +    CompilerNode1 != CompilerNode2.
Duplicate of https://github.com/spack/spack/pull/45189#discussion_r2008612051

2025-03-25 06:42 UTC, alalazo commented on lib/spack/spack/test/concretization/requirements.py
> +    assert s.satisfies("%llvm")
See d3e3b80f580b2d7628cdc3970778590d9baa49cb

2025-03-25 06:43 UTC, alalazo commented on lib/spack/spack/test/concretization/core.py
> +            if "c" not in x or not x.name.startswith("dt-diamond"):
See 404b06231da468390ae295da752e7e1f91a436a4

2025-03-25 06:43 UTC, alalazo commented on lib/spack/spack/test/concretization/core.py
> +    """Tests that a compiler can depend on itself to bootstrap."""
See 404b06231da468390ae295da752e7e1f91a436a4

2025-03-25 06:43 UTC, alalazo commented on lib/spack/spack/solver/libc_compatibility.lp
> +%   not attr("compatible_libc", node(R, ReusedPackage), _, _).
See 206b33c2e39c3547edc5edac284776d1bd6eb76c

2025-03-25 06:44 UTC, alalazo commented on lib/spack/spack/solver/asp.py
> +                f"duplicate {c.long_spec} compiler found. Edit your packages.yaml to remove it."
See 05557c8c5ccfea498516c908dd1dc37d282f724f

2025-03-25 06:44 UTC, alalazo commented on lib/spack/spack/solver/asp.py
> +        # constraint_spec.name = placeholder
See 6e40e32e83f9ca90ce65ad8858c529ceb599b482

2025-03-25 06:46 UTC, alalazo commented on lib/spack/spack/solver/concretize.lp
> +{ attr("version", node(ID, Package), Version) : pkg_fact(Package, version_satisfies(Constraint, Version)) }
This rule is now redundant with the one above, deleted in 78cc553879e338136d4bc2b4499077d4b7ff2785

2025-03-25 06:49 UTC, alalazo commented on lib/spack/spack/solver/concretize.lp
> +{ attr("version", node(ID, Package), Version) : pkg_fact(Package, version_satisfies(Constraint, Version)) }
> I'm not seeing, in version semantics, where we say we can't have two versions assigned to a node. I see it for virtuals but not for regular nodes... did something get lost?

This was not changed here. The rules are:
![Screenshot from 2025-03-25 07-48-17](https://github.com/user-attachments/assets/2a6b7410-43ee-4309-94bc-5b27f2f861c0)

2025-03-25 06:51 UTC, alalazo commented on lib/spack/spack/solver/asp.py
> +            f"  not runtime(Package)"
Let's save this one for when we add `hip` and friends, so we can work out the consequences there. Right now the runtimes we support follow this rule.

2025-03-25 08:10 UTC, alalazo commented on lib/spack/spack/environment/environment.py
> +lockfile_format_version = 6
See https://github.com/spack/spack/pull/45189/commits/1aa74bd6761ce18f128214957c723ae04c09037d

2025-03-25 19:31 UTC, tgamblin commented on lib/spack/spack/test/spec_syntax.py
> +    with pytest.raises(spack.solver.asp.UnsatisfiableSpecError) as exc_info:
Ok I guess we can leave this -- the does not exist pre-check is way faster than concretization, so I think it's still good to find some of this stuff beforehand.

2025-03-25 19:34 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> -
ah ok makes sense -- thanks

2025-03-25 20:04 UTC, tgamblin commented on lib/spack/spack/solver/asp.py
> +        self.gen.h1("Runtimes")
DAG may be huge but that's why this is nice ... it integrates with the resolver, so it's not like we have to add everything, right?  Anyway -- for later.

2025-03-25 20:07 UTC, tgamblin commented on lib/spack/spack/solver/concretize.lp
> +{ attr("version", node(ID, Package), Version) : pkg_fact(Package, version_satisfies(Constraint, Version)) }
ah ok awesome -- I missed the generalization of single-value attributes.  That's good.  Should virtuals not also have this? Something for later.

2025-03-25 20:08 UTC, tgamblin commented on lib/spack/spack/solver/concretize.lp
> +
ok that's interesting.  this should probably be documented

2025-03-25 22:07 UTC, tgamblin approved these changes, later dismissed

2025-03-26 01:03 UTC, tgamblin approved these changes
Re-approving with the `gdk-pixbuf` fix from #49690

2025-03-26 04:32 UTC, merged