rccl: new test API
LLNL/spack pull request #45241
Opened 2024-07-15 20:04 UTC by AcriusWinter

2024-07-15 20:04 UTC, AcriusWinter commented
1 error found in test log:
     176    [  FAILED  ] SendRecv.SinglePairs (144 ms)
     177    [----------] 1 test from SendRecv (144 ms total)
     178    
     179    [----------] 4 tests from Standalone
     180    [ RUN      ] Standalone.SplitComms_RankCheck
     181    Encountered HIP error (no ROCm-capable device is detected) at line 17 in file /var/t
            mp/lawrence31/spack-stage/spack-stage-rccl-6.1.1-5k4jec4u2kfdoruct733cyvpcjnh4ds3/sp
            ack-src/test/StandaloneTests.cpp
  >> 182    FAILED: Rccl::test_unit: Command exited with status 255:
     183        'rccl-UnitTests'
     184      File "/usr/WS2/lawrence31/spack/bin/spack", line 52, in <module>


See test log for details:
  /g/g16/lawrence31/.spack/test/mchvqwla3sficr54yckacrzlkzq6yj4u/rccl-6.1.1-5k4jec4-test-out.txt

============================== 1 failed of 1 spec ==============================

2024-07-15 20:27 UTC, tldahlgren requested changes
Can the tests be run from the test stage directory?

2024-07-15 20:27 UTC, tldahlgren commented on var/spack/repos/builtin/packages/rccl/package.py
>          test_dir = join_path(self.spec["rccl"].prefix, "bin")
The unit tests should not be run under the installation prefix.

2024-07-16 19:11 UTC, tldahlgren commented
@AcriusWinter There's also a conflict that needs to be resolved for this PR.

2024-08-12 16:53 UTC, tldahlgren approved these changes, later dismissed
Conversion to use new API, and not run under the installation prefix, is complete

The issue with the tests has to do with the installation though the correct executable, at least for the latest version, is being executed.

2024-08-12 23:50 UTC, AcriusWinter commented on var/spack/repos/builtin/packages/rccl/package.py
> +        unit_tests = which("rccl-UnitTests")
```suggestion
        unit_tests = which(self.prefix.bin.rccl-UnitTests)
```

2024-08-15 23:00 UTC, tldahlgren commented on var/spack/repos/builtin/packages/rccl/package.py
> +        """Run rccl-UnitTests"""
```suggestion
        """Run unit tests"""
```

2024-08-15 23:02 UTC, tldahlgren approved these changes
LGTM.

2024-08-16 04:03 UTC, merged