rust: rework external find to require both rustc and cargo
LLNL/spack pull request #45286
Opened 2024-07-17 23:54 UTC by wdconinc

In spack, `rust` installs both `rustc` and `cargo`. In most distributions, `cargo` is a separate package, though.

This PR modifies external detection to require *both* `rustc` and `cargo`. Until now it was just one of either. This seems to require the custom detection workflow, https://spack.readthedocs.io/en/latest/packaging_guide.html#custom-detection-workflow.

2024-07-17 23:56 UTC, wdconinc commented
Codespaces test on this branch, starting from `rustc` installed.
```console
root@codespaces-439960:/workspaces/spack# spack external find rust
==> No new external packages detected
root@codespaces-439960:/workspaces/spack# apt-get install cargo
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  cargo-doc
The following NEW packages will be installed:
  cargo
0 upgraded, 1 newly installed, 0 to remove and 102 not upgraded.
Need to get 6,110 kB of archives.
After this operation, 23.3 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 cargo amd64 1.75.0+dfsg0ubuntu1~bpo0-0ubuntu0.20.04 [6,110 kB]
Fetched 6,110 kB in 2s (3,444 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package cargo.
(Reading database ... 29083 files and directories currently installed.)
Preparing to unpack .../cargo_1.75.0+dfsg0ubuntu1~bpo0-0ubuntu0.20.04_amd64.deb ...
Unpacking cargo (1.75.0+dfsg0ubuntu1~bpo0-0ubuntu0.20.04) ...
Setting up cargo (1.75.0+dfsg0ubuntu1~bpo0-0ubuntu0.20.04) ...
root@codespaces-439960:/workspaces/spack# spack external find rust
==> The following specs have been detected on this system and added to /root/.spack/packages.yaml
rust@1.75.0
```

2024-07-17 23:58 UTC, wdconinc reviewed
@spackbot fix style

2024-07-18 02:25 UTC, wdconinc commented
> @spackbot fix style

Is @spackbot asleep?

2024-07-18 02:27 UTC, alecbcs commented
I've noticed @spackbot missing events as well recently. Not sure what's up.

2024-07-18 02:42 UTC, alecbcs commented on var/spack/repos/builtin/packages/rust/package.py
> +            return
```suggestion
        if not (rustc_candidates and cargo_candidates):
            return
```
I might suggest a slight swap here to make it easier to read.

2024-07-18 17:07 UTC, alecbcs requested changes
Two quick suggestions. Sorry I didn't notice these last night on my first brief look at the PR.

2024-07-18 17:07 UTC, alecbcs commented on var/spack/repos/builtin/packages/rust/package.py
> +        cargo_candidates = list(x for x in exes_in_prefix if os.path.basename(x) == "cargo")
```suggestion
        rustc_candidates = [x for x in exes_in_prefix if os.path.basename(x) == "rustc"]
        cargo_candidates = [x for x in exes_in_prefix if os.path.basename(x) == "cargo"]
```

Quick suggestion to simplify the syntax in the list comprehension.

2024-07-18 17:07 UTC, alecbcs commented on var/spack/repos/builtin/packages/rust/package.py
> +            return Spec.from_detection("rust@{0}".format(version_str)) if version_str else None
```suggestion
        output = Executable(rustc_candidates[0])("--version", output=str, error=str)
        match = re.match(r"rustc (\S+)", output)
        version_str = match.group(1) if match else None
        return Spec.from_detection(f"rust@{version_str}") if version_str else None
```

I'd drop the `for` loop that only ever executes once and instead just index the first value.

2024-07-18 17:38 UTC, wdconinc commented on var/spack/repos/builtin/packages/rust/package.py
> +        cargo_candidates = list(x for x in exes_in_prefix if os.path.basename(x) == "cargo")
I was wondering why that syntax is used in https://spack.readthedocs.io/en/latest/packaging_guide.html#custom-detection-workflow... We should update it there too then. Is this a remnant of old python syntax?

2024-07-18 17:59 UTC, alecbcs approved these changes
Looks good to me. Thanks @wdconinc

2024-07-18 20:19 UTC, merged