sz: new test API
LLNL/spack pull request #45363
Opened 2024-07-22 18:03 UTC by AcriusWinter

2024-07-22 18:06 UTC, AcriusWinter commented
========================= SUMMARY: sz-2.1.12.5-yzdbaqe =========================
Sz::test_2d_compression_sz .. FAILED
Sz::test_2d_decompression_sz .. FAILED
Sz::test_2d_float .. PASSED
Sz::test_3d_float .. FAILED
======================== 3 failed, 1 passed of 4 parts =========================
==> [2024-07-22-11:03:12.722164] 

See test results at:
  /g/g16/lawrence31/.spack/test/7lech4aytx2lfstyvo2yhshydwkn5ci5/sz-2.1.12.5-yzdbaqe-test-out.txt
==> Error: TestFailure: 3 tests failed.


Command exited with status 2:
    '/usr/bin/sz' '-z' '-f' '-i' '/g/g16/lawrence31/.spack/test/7lech4aytx2lfstyvo2yhshydwkn5ci5/sz-2.1.12.5-yzdbaqe/data/sz/testfloat_8_8_128.dat' '-M' 'REL' '-R' '1E-3' '-2' '8' '1024'


1 error found in test log:
     1    ==> Testing package sz-2.1.12.5-yzdbaqe
     2    ==> [2024-07-22-11:03:12.583848] test: test_2d_float: This test performs simple 2D compression/decompressio
          n (float)
     3    ==> [2024-07-22-11:03:12.586496] test: test_2d_compression_sz: testing 2D compression of sz
     4    ==> [2024-07-22-11:03:12.586858] '/usr/bin/sz' '-z' '-f' '-i' '/g/g16/lawrence31/.spack/test/7lech4aytx2lfs
          tyvo2yhshydwkn5ci5/sz-2.1.12.5-yzdbaqe/data/sz/testfloat_8_8_128.dat' '-M' 'REL' '-R' '1E-3' '-2' '8' '1024
          '
     5    /usr/bin/sz: invalid option -- 'z'
     6    Try `sz --help' for more information.
  >> 7    FAILED: Sz::test_2d_compression_sz: Command exited with status 2:
     8        '/usr/bin/sz' '-z' '-f' '-i' '/g/g16/lawrence31/.spack/test/7lech4aytx2lfstyvo2yhshydwkn5ci5/sz-2.1.12.
          5-yzdbaqe/data/sz/testfloat_8_8_128.dat' '-M' 'REL' '-R' '1E-3' '-2' '8' '1024'
     9      File "/usr/WS2/lawrence31/spack/bin/spack", line 52, in <module>
     10       sys.exit(main())
     11     File "/usr/WS2/lawrence31/spack/lib/spack/spack_installable/main.py", line 42, in main
     12       sys.exit(spack.main.main(argv))
     13     File "/usr/WS2/lawrence31/spack/lib/spack/spack/main.py", line 1070, in main



Command exited with status 2:
    '/usr/bin/sz' '-x' '-f' '-i' '/g/g16/lawrence31/.spack/test/7lech4aytx2lfstyvo2yhshydwkn5ci5/sz-2.1.12.5-yzdbaqe/data/sz/testfloat_8_8_128.dat' '-s' '/g/g16/lawrence31/.spack/test/7lech4aytx2lfstyvo2yhshydwkn5ci5/sz-2.1.12.5-yzdbaqe/data/sz/testfloat_8_8_128.dat.sz' '-2' '8' '1024' '-a'


1 error found in test log:
     54      File "/collab/usr/gapps/python/build/spack-toss4.1/var/spack/environments/python/._view/75prb56irmif5ejt
           irjthpx6kq3gqo52/lib/python3.9/contextlib.py", line 137, in __exit__
     55        self.gen.throw(typ, value, traceback)
     56    ==> [2024-07-22-11:03:12.614131] test: test_2d_decompression_sz: testing 2D decompression of sz
     57    ==> [2024-07-22-11:03:12.614432] '/usr/bin/sz' '-x' '-f' '-i' '/g/g16/lawrence31/.spack/test/7lech4aytx2lf
           styvo2yhshydwkn5ci5/sz-2.1.12.5-yzdbaqe/data/sz/testfloat_8_8_128.dat' '-s' '/g/g16/lawrence31/.spack/test
           /7lech4aytx2lfstyvo2yhshydwkn5ci5/sz-2.1.12.5-yzdbaqe/data/sz/testfloat_8_8_128.dat.sz' '-2' '8' '1024' '-
           a'
     58    /usr/bin/sz: invalid option -- 'x'
     59    Try `sz --help' for more information.
  >> 60    FAILED: Sz::test_2d_decompression_sz: Command exited with status 2:
     61        '/usr/bin/sz' '-x' '-f' '-i' '/g/g16/lawrence31/.spack/test/7lech4aytx2lfstyvo2yhshydwkn5ci5/sz-2.1.12
           .5-yzdbaqe/data/sz/testfloat_8_8_128.dat' '-s' '/g/g16/lawrence31/.spack/test/7lech4aytx2lfstyvo2yhshydwkn
           5ci5/sz-2.1.12.5-yzdbaqe/data/sz/testfloat_8_8_128.dat.sz' '-2' '8' '1024' '-a'
     62      File "/usr/WS2/lawrence31/spack/bin/spack", line 52, in <module>
     63        sys.exit(main())
     64      File "/usr/WS2/lawrence31/spack/lib/spack/spack_installable/main.py", line 42, in main
     65        sys.exit(spack.main.main(argv))
     66      File "/usr/WS2/lawrence31/spack/lib/spack/spack/main.py", line 1070, in main



name 'test_dat_dir' is not defined

/usr/WS2/lawrence31/spack/var/spack/repos/builtin/packages/sz/package.py:128, in test_3d_float:
        125        """This test performs simple 3D compression/decompression (float)"""
        126
        127        test_data_dir = self.test_suite.current_test_data_dir
  >>    128        with working_dir(test_dat_dir):
        129
        130            filename = "testfloat_8_8_128.dat"
        131            orifile = test_data_dir.join(filename)

See test log for details:
  /g/g16/lawrence31/.spack/test/7lech4aytx2lfstyvo2yhshydwkn5ci5/sz-2.1.12.5-yzdbaqe-test-out.txt

============================== 1 failed of 1 spec ==============================

2024-07-23 23:26 UTC, tldahlgren requested changes
See comments.

2024-07-23 23:26 UTC, tldahlgren commented on var/spack/repos/builtin/packages/sz/package.py
> +            exe = which("sz")
Since the original line 115 was for installed software, this should include the prefix path.

2024-07-23 23:26 UTC, tldahlgren commented on var/spack/repos/builtin/packages/sz/package.py
> +            with test_part(self, "test_2d_compression_sz", purpose="testing 2D compression of sz"):
The test part name needs to start with the name of the test method (eg, `test_2d_float_compression`) for proper results reporting.

2024-07-23 23:26 UTC, tldahlgren commented on var/spack/repos/builtin/packages/sz/package.py
> +                self, "test_2d_decompression_sz", purpose="testing 2D decompression of sz"
Same test subpart naming issue here.

2024-07-23 23:26 UTC, tldahlgren commented on var/spack/repos/builtin/packages/sz/package.py
> +            with test_part(self, "test_3d_compression_sz", purpose="testing 3D compression of sz"):
Same test subpart naming issue here and in the next subpart.

2024-07-23 23:26 UTC, tldahlgren commented on var/spack/repos/builtin/packages/sz/package.py
> +        with working_dir(test_dat_dir):
There is a typo in the variable name.

2024-07-23 23:26 UTC, tldahlgren commented on var/spack/repos/builtin/packages/sz/package.py
> +            exe = which("sz")
Same issue regarding ensuring the executable that is found is the installed one (i.e., one under the prefix).

2024-07-23 23:26 UTC, tldahlgren commented on var/spack/repos/builtin/packages/sz/package.py
>          """This test performs simple 2D compression/decompression (float)"""
The docstring is the brief description of the test so should be more concise (e.g., run simple 2D compression/decompression).

2024-07-23 23:26 UTC, tldahlgren commented on var/spack/repos/builtin/packages/sz/package.py
>          """This test performs simple 3D compression/decompression (float)"""
Same issue with making the docstring more concise.

2024-07-23 23:28 UTC, tldahlgren commented on var/spack/repos/builtin/packages/sz/package.py
> +            exe = which("sz")
From the test results you report above, you aren't running the tests against the installed software.

2024-07-24 17:31 UTC, AcriusWinter commented
==> [2024-07-24-10:30:24.144800] '/usr/bin/fi_info' '-l'
==> [2024-07-24-10:30:38.631426] test: test_2d_float: Run simple 2D compression/decompression
SKIPPED: Sz::test_2d_float: sz is not installed for version 2.1.12.5
==> [2024-07-24-10:30:38.633631] test: test_3d_float: Run simple 3D compression/decompression
SKIPPED: Sz::test_3d_float: sz is not installed for version 2.1.12.5
==> [2024-07-24-10:30:38.637573] Completed testing
==> [2024-07-24-10:30:38.637658] 
========================= SUMMARY: sz-2.1.12.5-yzdbaqe =========================
Sz::test_2d_float .. SKIPPED
Sz::test_3d_float .. SKIPPED
============================= 2 skipped of 2 parts =============================
============================= 1 skipped of 1 spec ==============================

2024-07-24 17:43 UTC, AcriusWinter commented
========================== SUMMARY: sz-2.1.9-62gwv5w ===========================
Sz::test_2d_float_compression_sz .. PASSED
Sz::test_float_2d_decompression_sz .. PASSED
Sz::test_2d_float .. PASSED
Sz::test_3d_float_compression_sz .. PASSED
Sz::test_3d_float_decompression_sz .. PASSED
Sz::test_3d_float .. PASSED
============================= 6 passed of 6 parts ==============================
======================== 1 skipped, 1 passed of 2 specs ========================

2024-07-24 22:10 UTC, tldahlgren approved these changes

2024-07-25 01:09 UTC, merged