upgrade apptainer: security fix
LLNL/spack pull request #45398
Opened 2024-07-23 09:31 UTC by walterdejong

apptainer 1.3.1 has a high severity security issue: CVE-2024-3727
Upgrade to 1.3.2 or preferably 1.3.3

2024-07-23 14:55 UTC, tldahlgren approved these changes
Confirmed the new version sha256s.

2024-07-23 14:56 UTC, tldahlgren commented
@snehring As a recent *significant* contributor, would you be interested in confirming that the only changes needed to add the new versions are the addition of the directives?

2024-07-23 14:59 UTC, tldahlgren commented
@walterdejong Can you add a comment in the `1.3.1` directive location saying the version should not be there and providing the link?  (That way we can note why we don't want someone coming along and adding the version back.)

2024-07-23 15:03 UTC, tldahlgren requested changes
Please add the comment.

2024-07-23 15:41 UTC, snehring commented
Yeah, just adding the versions should be sufficient, it doesn't look like any additional changes are needed. Confirmed the versions build and seem to function.

2024-07-23 17:17 UTC, tldahlgren commented
> Yeah, just adding the versions should be sufficient, it doesn't look like any additional changes are needed. Confirmed the versions build and seem to function.

Thanks.

2024-07-26 07:20 UTC, walterdejong commented
added comment for version 1.3.1

2024-07-26 15:51 UTC, tldahlgren approved these changes

2024-07-26 15:51 UTC, merged