Win: support proper meson dependent environments
LLNL/spack pull request #45414
Opened 2024-07-24 16:17 UTC by johnwparent

On Windows the `meson` executable is placed in the `Scripts` directory, so we need to add that to the PATH so consuming packages can access the meson executable.

Without this, `py-meson-python` will fail to build as it cannot find `meson`.
Alternatively, we can set the `MESON` environment variable to the meson executable, but this seems like a more robust option.

2024-07-24 16:59 UTC, eli-schwartz commented
I don't know how spack works internally here but I would have assumed there would be a way to generically say "this package's artifacts should be made available on $PATH". Having to manually touch `self.spec.prefix.scripts` and gate it specifically on Windows seems inefficient. :P

2024-07-24 17:17 UTC, johnwparent commented
> I don't know how spack works internally here but I would have assumed there would be a way to generically say "this package's artifacts should be made available on $PATH". Having to manually touch `self.spec.prefix.scripts` and gate it specifically on Windows seems inefficient. :P

This is _how_ that logic is achieved. By default, Spack will add `spec.prefix.bin` to the path for each package that is a build or link dep of the root spec at build time, and will additionally call these environmental setup methods for further configuration byeond the basic, generic operations we know work for every package. I can add a more granular check for if its a build or run dep requesting `meson`, but that's essentially just the same thing with a more pedantic conditional. 

It's gated on Windows because it's not necessary on other platforms where the `spec.prefix.bin` both exists and is handled by a default method. 

Regardless of whether its done here, or in the default setup run environment method, the logic/mechanism for doing so is the same, setting and environment variable to a given string.

The only other thing I can see us doing is refactoring this into the generic setup environment operation, when dealing with Python packages on Windows we perform this operation, which, to be clear, would be the exact same code, just elsewhere.

In what way is this inefficient?

2024-07-24 17:28 UTC, adamjstewart commented
We should do this globally for all packages in `lib/spack/spack/build_environment.py`.

2024-07-24 17:40 UTC, eli-schwartz commented
> The only other thing I can see us doing is refactoring this into the generic setup environment operation, when dealing with Python packages on Windows we perform this operation, which, to be clear, would be the exact same code, just elsewhere.
> I'm actually a fan of that idea, @scheibelp @adamjstewart thoughts?
> 
> In what way is this inefficient?

Basically, it is inefficient to do it specific to a package when you could do it in the generic setup environment operation. :)

2024-07-24 18:32 UTC, johnwparent commented
@adamjstewart 
> We should do this globally for all packages in `lib/spack/spack/build_environment.py`.

Even for non python packages that don't have a `Scripts` directory? 
Also thoughts on x-platform applicability?

2024-07-24 18:34 UTC, johnwparent commented
> it is that asking individual packages to own that logic is confusing 

Your initial comment made it seem like this was the issue you had, and this is a central tenant of package definitions, custom environment setup that is non generic, less so the generalizability of this specific issue.

2025-04-24 17:25 UTC, scheibelp requested changes
I think I see one issue, and I have a couple questions.

2025-04-24 17:25 UTC, scheibelp commented on var/spack/repos/builtin/packages/python/package.py
> +            env.prepend_path("PATH", self.spec.prefix)
Based on above comment, this should still return at the end of the block (so either a return should be added or the comment should change).

2025-04-24 17:25 UTC, scheibelp commented on var/spack/repos/builtin/packages/python/package.py
> +            env.prepend_path("PATH", self.spec.prefix)
(question) it looks like this is also preparing for `py-*` packages that put executables in the base prefix: is that something only `py-*` packages (on Windows) do?

2025-04-24 17:25 UTC, scheibelp commented on var/spack/repos/builtin/packages/python/package.py
> +            env.prepend_path("PATH", dependent_spec.prefix.scripts)
(question) PR description mentions "Scripts", this will do "scripts", which I assume will generally not matter since paths are not case sensitive on windows.

If the directory is expected to be called "Scripts", I have a slight inclination to refer to it that way.

2025-04-24 17:33 UTC, johnwparent commented on var/spack/repos/builtin/packages/python/package.py
> +            env.prepend_path("PATH", self.spec.prefix)
Is Python's setup dependent run environment invoked with another packages as `self`? If so I formulated this incorrectly. The intent was to inject Python's own base prefix into the path to expose a few tools that Python installs there that I've found some packages rely on (namely the `py` python launcher, which `icu4c` and similar packages need)

2025-04-24 17:34 UTC, johnwparent commented on var/spack/repos/builtin/packages/python/package.py
> +            env.prepend_path("PATH", dependent_spec.prefix.scripts)
> which I assume will generally not matter since paths are not case sensitive on windows.

I was indeed relying on this behavior, will refactor to refer to the correctly named directory.

2025-04-24 17:34 UTC, johnwparent commented on var/spack/repos/builtin/packages/python/package.py
> +            env.prepend_path("PATH", self.spec.prefix)
Good catch

2025-04-24 17:38 UTC, johnwparent commented on var/spack/repos/builtin/packages/python/package.py
> +            env.prepend_path("PATH", self.spec.prefix)
> is that something only py-* packages (on Windows) do?

Sorry, forgot to address this part. AFAIK Python doesn't install any tooling into the base prefix on non Windows platforms (I don't think there's as much peripheral tooling provided by non Windows in general as the tooling is usually to overcome Windows hurdles)

2025-04-24 17:44 UTC, johnwparent commented
@spackbot fix style

2025-04-24 18:02 UTC, scheibelp commented on var/spack/repos/builtin/packages/python/package.py
> +            env.prepend_path("PATH", self.spec.prefix)
> The intent was to inject Python's own base prefix into the path to expose a few tools that Python installs there that I've found some packages rely on (namely the py python launcher, which icu4c and similar packages need)

OK that should go into the `setup_run_environment` for `python`

> Is Python's setup dependent run environment invoked with another packages as self? If so I formulated this incorrectly. 

No, so this will add `spec[python].prefix`, but it should be in `setup_run_environment` because otherwise this will repeatedly add that to PATH for each dependent.

2025-04-24 18:02 UTC, scheibelp requested changes
Additional request from https://github.com/spack/spack/pull/45414#discussion_r2058975410

2025-04-24 20:39 UTC, johnwparent commented on var/spack/repos/builtin/packages/python/package.py
> +            env.prepend_path("PATH", self.spec.prefix)
> setup_run_environment

Is run environment established for build dep types?

2025-04-24 21:37 UTC, scheibelp commented on var/spack/repos/builtin/packages/python/package.py
> +            env.prepend_path("PATH", self.spec.prefix)
All `PythonPackage`s `extend` `python`, which imposes a `build/run` dependency on it, so they should always run `setup_run_environment` from `python` (the `build_environment` logic does that for `BUILDTIME_DIRECT` dependencies).

2025-04-24 21:44 UTC, johnwparent commented on var/spack/repos/builtin/packages/python/package.py
> +            env.prepend_path("PATH", self.spec.prefix)
Ah ok, I didn't realize `extend` had that effect, thanks! 
For packages that depend on, but do not extend python (icu4c for example), we'd still need the base prefix available during build time however.

2025-04-24 21:49 UTC, scheibelp commented on var/spack/repos/builtin/packages/python/package.py
> +            env.prepend_path("PATH", self.spec.prefix)
`icu4c` declares a build dependency on python (and in general anything that needs python exes at build time should do that).

2025-04-24 22:10 UTC, johnwparent commented on var/spack/repos/builtin/packages/python/package.py
> +            env.prepend_path("PATH", self.spec.prefix)
Ahh, wait, I realized you're only asking me to remove this from setup__dependent__run_environment, not build 🤦 

Sorry for the churn, edit made and pushed.

2025-04-25 17:05 UTC, scheibelp requested changes
One additional request

2025-04-25 17:05 UTC, scheibelp commented on var/spack/repos/builtin/packages/python/package.py
> +            env.prepend_path("PATH", self.spec.prefix)
`env.prepend_path("PATH", self.spec.prefix)` is now handled in `setup_run_environment`

2025-04-25 17:55 UTC, johnwparent commented on var/spack/repos/builtin/packages/python/package.py
> +            env.prepend_path("PATH", self.spec.prefix)
Ah I didn't realize that `setup_run_environment` was invoked for each build dep type for dependents. Good to know, thanks!

2025-04-25 20:34 UTC, scheibelp approved these changes

2025-06-06 12:05 UTC, haampie commented
Hi @johnwparent, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2026-01-04 01:53 UTC, closed without merging