c: new test API
LLNL/spack pull request #45469
Opened 2024-07-26 17:07 UTC by AcriusWinter

New standalone test API. Cannot give results as you cannot install the package.

2024-07-29 20:46 UTC, AcriusWinter commented
========================= SUMMARY: gcc-14.1.0-l7hmiu4 ==========================
Gcc::gcc .. NO_TESTS
Gcc::test_c_hello.c .. FAILED
Gcc::test_c .. FAILED
Gcc::test_g++_o_hello.c++.exe_hello.c++ .. PASSED
Gcc::test_hello.c++.exe .. PASSED
Gcc::test_g++_o_hello.cc.exe_hello.cc .. PASSED
Gcc::test_hello.cc.exe .. PASSED
Gcc::test_g++_o_hello.cpp.exe_hello.cpp .. PASSED
Gcc::test_hello.cpp.exe .. PASSED
Gcc::test_g++_std=c++11_o_hello_c++11.cc.exe_hello_c++11.cc .. PASSED
Gcc::test_hello_c++11.cc.exe .. PASSED
Gcc::test .. FAILED
Gcc::test_gfortran_o_hello.F.exe_hello.F .. PASSED
Gcc::test_hello.F.exe .. PASSED
Gcc::test_gfortran_o_hello.f90.exe_hello.f90 .. PASSED
Gcc::test_hello.f90.exe .. PASSED
================= 1 no_tests, 6 failed, 12 passed of 19 parts ==================

2024-08-12 16:16 UTC, tldahlgren requested changes
Same/similar issues to #45462 and #45470.

2024-08-12 16:16 UTC, tldahlgren commented on var/spack/repos/builtin/packages/c/package.py
> +            raise SkipTest(f"{os.environ['CC']} not found in {self.version}")
I don't *think* this can happen in that the environment variable is set to a valid path.

2024-08-12 16:16 UTC, tldahlgren commented on var/spack/repos/builtin/packages/c/package.py
> +            with test_part(self, f"test_c_{test}", f"Test {test}"):
Would prefer a more descriptive test part description, such as `build and run {test}`, since there is more involved than just running an executable.

2024-08-12 16:16 UTC, tldahlgren commented on var/spack/repos/builtin/packages/c/package.py
> +                filepath = test_source.join(test)
Interesting.  The `join` doesn't work.

2024-08-12 16:16 UTC, tldahlgren commented on var/spack/repos/builtin/packages/c/package.py
> +                comp_exe = which(join_path(self.prefix.bin, cc_exe))
Duplicates line 23.

2024-08-12 16:16 UTC, tldahlgren commented on var/spack/repos/builtin/packages/c/package.py
> +                    raise SkipTest(f"{str(cc_exe)} not found in {self.version}")
Duplicates lines 24-25 and I don't believe it is even necessary.

2024-08-12 16:16 UTC, tldahlgren commented on var/spack/repos/builtin/packages/c/package.py
> +                if compiled:
This is not the correct `run_test()` conversion.  The `run_test()` method would return `True` or `False` if the command succeeded but that isn't what you're going to get from running a command.

2024-08-12 16:16 UTC, tldahlgren commented on var/spack/repos/builtin/packages/c/package.py
> +                    expected = ["Hello world", "YES!"]
Since all of the tests run check for the same result, it is more efficient to move this to before the for-loop.

2024-08-12 16:16 UTC, tldahlgren commented on var/spack/repos/builtin/packages/c/package.py
> +                        raise SkipTest(f"{exe} not found in {self.version}")
The above command does not install the executable (i.e., into the installation prefix); rather, it builds it in the current directory.

2024-08-12 16:16 UTC, tldahlgren commented on var/spack/repos/builtin/packages/c/package.py
> +                    assert False, "Did not compile"
This is not needed/appropriate.

2024-08-12 16:19 UTC, tldahlgren approved these changes

2024-08-12 21:58 UTC, merged