fortran: new test API
LLNL/spack pull request #45470
Opened 2024-07-26 17:51 UTC by AcriusWinter

New standalone test API integration. Cannot provide tests results ATM due to being unable to install fortran package.

2024-07-29 20:42 UTC, AcriusWinter commented
========================= SUMMARY: gcc-14.1.0-l7hmiu4 ==========================
Gcc::gcc .. NO_TESTS
Gcc::test_gcc_o_hello.c.exe_hello.c .. PASSED
Gcc::test_hello.c.exe .. PASSED
Gcc::test .. PASSED
Gcc::test_g++_o_hello.c++.exe_hello.c++ .. PASSED
Gcc::test_hello.c++.exe .. PASSED
Gcc::test_g++_o_hello.cc.exe_hello.cc .. PASSED
Gcc::test_hello.cc.exe .. PASSED
Gcc::test_g++_o_hello.cpp.exe_hello.cpp .. PASSED
Gcc::test_hello.cpp.exe .. PASSED
Gcc::test_g++_std=c++11_o_hello_c++11.cc.exe_hello_c++11.cc .. PASSED
Gcc::test_hello_c++11.cc.exe .. PASSED
Gcc::test_fortran_hello.F .. PASSED
Gcc::test_fortran_hello.f90 .. PASSED
Gcc::test_fortran .. PASSED
====================== 1 no_tests, 18 passed of 19 parts =======================
============================== 1 passed of 1 spec ==============================

2024-08-10 00:52 UTC, tldahlgren requested changes
This PR has issues similar to those reported for https://github.com/spack/spack/pull/45462.

2024-08-10 00:52 UTC, tldahlgren commented on var/spack/repos/builtin/packages/fortran/package.py
> +                        check_outputs(expected, out)
These statements will never run.

2024-08-10 00:52 UTC, tldahlgren commented on var/spack/repos/builtin/packages/fortran/package.py
> +                        assert False, "Did not compile"
This is not the correct conversion from `self.run_test()` to directly compiling the program.

2024-08-10 00:52 UTC, tldahlgren commented on var/spack/repos/builtin/packages/fortran/package.py
> +                        assert False, "Did not compile"
This path won't be taken because there will always be output from the compilation process.

2024-08-10 00:52 UTC, tldahlgren commented on var/spack/repos/builtin/packages/fortran/package.py
> +                    exe = which(join_path(self.prefix.bin, exe_name))
The executable built above is compiled into the current directory, not installed as `self.prefix.bin` indicates.

2024-08-10 00:52 UTC, tldahlgren commented on var/spack/repos/builtin/packages/fortran/package.py
> +            raise SkipTest(f"{os.environ['FC']} not found in {self.version}")
🤔 Not sure this would ever happen in this case.

2024-08-10 01:12 UTC, tldahlgren approved these changes, later dismissed

2024-08-10 01:20 UTC, tldahlgren approved these changes

2024-08-11 20:32 UTC, merged