libxsmm: add version tag for aarch64 (for CP2K)
LLNL/spack pull request #45508
Opened 2024-07-30 22:03 UTC by RMeli

Add another version tag to main that support non-x86 architectures (see https://github.com/spack/spack/pull/41193).

The commit hash is the same used in CP2K (see https://github.com/cp2k/cp2k/pull/3577), since it has full functionality for ARM64 with respect to CP2K's needs.

Successfully tested on macOS 14.5:
```
spack install libxsmm@main-2024-07
```

2024-07-31 08:16 UTC, RMeli commented
@spackbot fix style

2024-08-06 06:34 UTC, alalazo requested changes
Errors in pieplines: https://gitlab.spack.io/spack/spack/-/jobs/12064731

2024-09-30 11:21 UTC, bernhardkaindl requested changes
@RMeli Reminder - Massimiliano found, this
> Errors in pipelines: https://gitlab.spack.io/spack/spack/-/jobs/12064731

It shows that the build(s - there are a number of fails, see "Related jobs on the jobs he links) of palace@0.12.0 in that pipeline that seem to be stemming from libxsmm, specifically from this build before in the same job:

linux-amzn2-x86_64_v3/oneapi-2023.2.0/libxsmm-main-2024-07

Can you fix this (or close this PR and re-open it later when ready)?

2024-09-30 11:31 UTC, RMeli commented
Happy to close now and re-visit when this is more pressing.

2024-09-30 11:31 UTC, closed without merging