Use ubuntu-22.04 as target for Debian 12 with acfl and armpl-gcc inst…
LLNL/spack pull request #45524
Opened 2024-07-31 15:03 UTC by dslarm

@paolotricerri 
@annop-w 

On Debian12, acfl and armpl-gcc fall back to installing rhel-7 binaries, which doesn't work - this patch makes them use ubuntu-22.04 binaries which do work.

2024-08-01 08:36 UTC, paolotricerri requested changes
I would add an entry into the _os_pkg_map that maps from debian12 to a *.deb package file.

2024-08-01 08:36 UTC, paolotricerri commented on var/spack/repos/builtin/packages/armpl-gcc/package.py
For Debian12, we want to install a *.deb package and, currently, the default is *.rpm. I would add an entry in the _os_pkg_map dictionary mapping debian12 to deb package files.

2024-08-12 10:35 UTC, dslarm commented on var/spack/repos/builtin/packages/armpl-gcc/package.py
My bad - I missed that. Corrected and have pushed another commit to the branch.

2024-08-12 12:27 UTC, paolotricerri commented
Looks good to me but I don't think I can merge. 

Maybe @alalazo can help?

Thanks

2024-08-12 12:30 UTC, alalazo approved these changes

2024-08-12 19:21 UTC, merged