dealii:v9.6-rc1
LLNL/spack pull request #45554
Opened 2024-08-02 08:48 UTC by luca-heltai

2024-08-11 22:54 UTC, jppelteret approved these changes

2024-08-12 00:21 UTC, masterleinad approved these changes

2024-08-16 20:03 UTC, Rombur commented
We need to something like:
```
 depends_on("kokkos@3.7:+cuda+cuda_lambda+cuda_constexpr+wrapper", when="@9.6:+kokkos~trilinos+cuda")
```
because deal.II 9.6 requires `cuda_constexpr` which is off by default.

2024-08-16 20:07 UTC, Rombur commented
I am not sure if we need to change something for Trilinos

2024-08-19 06:15 UTC, alalazo requested changes
Failures in pipelines (`cuda_constexpr`): https://gitlab.spack.io/spack/spack/-/jobs/12191568

2024-08-27 14:52 UTC, masterleinad commented
You need to fix the formatting
```
--- var/spack/repos/builtin/packages/dealii/package.py	2024-08-27 14:50:05.049501+00:00
+++ var/spack/repos/builtin/packages/dealii/package.py	2024-08-27 14:50:19.914640+00:00
@@ -199,11 +199,13 @@
     # TODO: next line fixes concretization with petsc
     depends_on("hdf5+mpi+hl+fortran", when="+hdf5+mpi+petsc")
     depends_on("hdf5+mpi+hl", when="+hdf5+mpi~petsc")
     depends_on("kokkos@3.7:", when="@9.5:+kokkos~trilinos")
     depends_on("kokkos@3.7:+cuda+cuda_lambda+wrapper", when="@9.5:9.5.99+kokkos~trilinos+cuda")
-    depends_on("kokkos@3.7:+cuda+cuda_lambda+cuda_constexpr+wrapper", when="@9.6:+kokkos~trilinos+cuda")
+    depends_on(
+        "kokkos@3.7:+cuda+cuda_lambda+cuda_constexpr+wrapper", when="@9.6:+kokkos~trilinos+cuda"
+    )
     # TODO: concretizer bug. The two lines mimic what comes from PETSc
     # but we should not need it
     depends_on("metis@5:+int64", when="+metis+int64")
     depends_on("metis@5:~int64", when="+metis~int64")
     depends_on("muparser", when="+muparser")
```

2024-08-27 14:58 UTC, luca-heltai commented
@masterleinad, as soon as #45812 is merged, we can add the required change also here.

2024-09-24 03:03 UTC, adamqc commented
@luca-heltai I need the `complex` variant to compile with complex value support. Could you please add it to the package? Please see #46539 for reference. Thanks!

2024-09-25 08:21 UTC, luca-heltai commented
The failing CI is unrelated to this PR (vtk fails building). Can we merge this?

2024-09-25 12:14 UTC, masterleinad commented on var/spack/repos/builtin/packages/dealii/package.py
> +    )
Don't we also need something like
```
depends_on("trilinos+cuda+cuda_constexpr", when "@9.6:+trilinos+cuda")
```
?

2024-10-23 22:59 UTC, eugeneswalker commented
Does `dealii@9.6.0` support `cuda@12`?

2024-10-25 19:49 UTC, masterleinad commented
> Does `dealii@9.6.0` support `cuda@12`?

Not via `DEAL_II_WITH_CUDA` but only through `Kokkos`.

2024-11-05 13:59 UTC, luca-heltai commented
Can we get this merged? I think the E4S build can disable vtk, if they want this to build. I'm not sure what the problem with vtk is, but it's not related to this PR.

2024-11-05 16:25 UTC, eugeneswalker commented
> Can we get this merged? I think the E4S build can disable vtk, if they want this to build. I'm not sure what the problem with vtk is, but it's not related to this PR.

Just pushed commit to set `dealii ~vtk` in CI stacks.

2024-11-06 15:55 UTC, eugeneswalker commented
More tweaks to E4S CI stacks here:
* https://github.com/spack/spack/pull/45554/commits/86a0ed8f278ffc368987639e90d3b3a8fb318232

1. E4S Neoverse V1: disable dealii due to build errors
* [dealii@9.6.0 /7kn4cfi %gcc@11.4.0 arch=linux-ubuntu22.04-neoverse_v1 E4S ARM Neoverse V1 ](https://gitlab.spack.io/spack/spack/-/jobs/13385628)
```
...
  >> 2904    /tmp/root/spack-stage/spack-stage-dealii-9.6.0-7kn4cfiil6krffy6c4l
             vjdrmztyhju3w/spack-src/include/deal.II/base/vectorization.h(1553)
             : error: identifier "vminq_f32" is undefined
     2905    
     2906    28 errors detected in the compilation of "/tmp/root/spack-stage/sp
             ack-stage-dealii-9.6.0-7kn4cfiil6krffy6c4lvjdrmztyhju3w/spack-src/
             source/dofs/dof_tools_sparsity.cc".
     2907    28 errors detected in the compilation of "/tmp/root/spack-stage/sp
             ack-stage-dealii-9.6.0-7kn4cfiil6krffy6c4lvjdrmztyhju3w/spack-src/
             source/dofs/dof_tools_constraints.cc".
  >> 2908    make[2]: *** [source/dofs/CMakeFiles/object_dofs_release.dir/build
             .make:247: source/dofs/CMakeFiles/object_dofs_release.dir/dof_tool
             s_sparsity.cc.o] Error 1
...
```

2. E4S OneAPI: Set `dealii ~vtk` due to issue with dependencies not being buildable by OneAPI
* [ taskflow@3.7.0 /rm3sdb3 %oneapi@2024.2.1 arch=linux-ubuntu22.04-x86_64_v3 E4S OneAPI ](https://gitlab.spack.io/spack/spack/-/jobs/13385607)
```
  >> 10    CMake Error at CMakeLists.txt:81 (message):
     11    
     12    
     13      Taskflow currently supports the following compilers:
     14    
     15        - g++ v7.0 or above
     16        - clang++ v6.0 or above
```

2024-11-11 16:59 UTC, balay commented
https://gitlab.spack.io/spack/spack/-/jobs/13482234
```

PLEASE append the compiler options "-save-temps -v", rebuild the application to get the full command which is failing and submit a bug report to https://software.intel.com/en-us/support/priority-support which includes the failing command, input files for the command and the crash backtrace (if any).
Stack dump:
0.      Program arguments: /opt/intel/oneapi/compiler/2024.2/bin/compiler/clang++ @/tmp/icpx0013442874BhV7Ra/icpxargkyxtt2
1.      <eof> parser at end of file
2.      Optimizer
```
>  -qopenmp-simd -std=c++17 -march=x86-64-v3 -mtune=generic -O2

perhaps check if `cflags=-O0 cxxflags-O0` will work around this compiler  failure? [or somehow disable ` -qopenmp-simd ` and see if that works?]

2024-11-11 18:45 UTC, balay commented on share/spack/gitlab/cloud_pipelines/stacks/e4s-oneapi/spack.yaml
> +  - dealii ~vtk ~taskflow # +vtk +taskflow: ^taskflow: CMake Error at CMakeLists.txt:81 (message): Taskflow currently supports the following compilers: g++ v7.0 or above, clang++ v6.0 or above
```suggestion
  - dealii ~vtk ~taskflow cflags=-O0 cxxflags=-O0 # +vtk +taskflow: ^taskflow: CMake Error at CMakeLists.txt:81 (message): Taskflow currently supports the following compilers: g++ v7.0 or above, clang++ v6.0 or above; use -O0 to work around compiler failure
```

2024-11-11 22:29 UTC, balay commented
The CI jobs are clean now!

I think this PR is ready for merge!

[assuming  my above CI change is acceptable (cc: @eugeneswalker ) and @alalazo can approve an clear the block on this PR]

2024-11-12 01:11 UTC, eugeneswalker commented
> I think this PR is ready for merge!
> 
> [assuming my above CI change is acceptable (cc: @eugeneswalker ) and @alalazo can approve an clear the block on this PR]

Looks good to me! Thanks for doing that!

2024-11-12 01:11 UTC, eugeneswalker approved these changes

2024-11-13 14:34 UTC, alalazo approved these changes

2024-11-13 14:34 UTC, merged