spack buildcache push: best effort
LLNL/spack pull request #45631
Opened 2024-08-08 13:02 UTC by haampie

* spack buildcache push for partially installed environments by default
  pushes all it can, and only dumps errors towards the end
* if --fail-fast is provided, error out before pushing anything if any
  of the packages is uninstalled
* oci build caches using parallel push now use futures to ensure pushing
  goes in best-effort style

2024-08-12 11:57 UTC, alalazo reviewed
Basically LGTM. I left a few minor comments. Will go for a full test drive of the PR now.

2024-08-12 11:57 UTC, alalazo commented on lib/spack/spack/cmd/buildcache.py
> +    """Executor that runs tasks sequentially in the current thread."""
Kind of nice that Python docs don't say this is the only function that needs to be implemented :slightly_smiling_face: Had to check the implementation to check that.

2024-08-12 11:57 UTC, alalazo commented on lib/spack/spack/cmd/buildcache.py
> +    """Executor that runs tasks sequentially in the current thread."""
(Comment) We can consider moving this class to a core module later, since it might be of more general use than just buildcaches.

2024-08-12 11:57 UTC, alalazo commented on lib/spack/spack/cmd/buildcache.py
> +        deptype = dt.RUN | dt.LINK | dt.TEST
Should we have `dt.TEST` in this conditional?

2024-08-12 11:57 UTC, alalazo commented on lib/spack/spack/cmd/buildcache.py
> +                    (s, spack.error.SpackError("package not installed")) for s in not_installed
Was this meant to be:
```suggestion
                    (s, PackageNotInstalledError("package not installed")) for s in not_installed
```
?

2024-08-12 11:57 UTC, alalazo commented on lib/spack/spack/cmd/buildcache.py
> +    """Raised when a spec is not installed but picked to be packaged."""
There is another error with the same name `spack.rewiring.PackageNotInstalledError`. Can we either unify the exceptions, or rename one of them?

2024-08-12 11:57 UTC, alalazo commented on lib/spack/spack/cmd/buildcache.py
> +        ) as tmpdir, _make_concurrent_executor() as pool:
(minor) We should update the var name for better reading:
```suggestion
        ) as tmpdir, _make_concurrent_executor() as executor:
```

2024-08-12 11:57 UTC, alalazo commented on lib/spack/spack/cmd/buildcache.py
> +        ) as tmpdir, _make_concurrent_executor() as pool:
Same

2024-08-12 11:57 UTC, alalazo commented on lib/spack/spack/test/cmd/buildcache.py
> +    with pytest.raises(Exception):
Is it worth being more specific here?

2024-08-12 12:41 UTC, haampie commented on lib/spack/spack/cmd/buildcache.py
> +        deptype = dt.RUN | dt.LINK | dt.TEST
Unclear... they can be runtime test deps for `spack test`

2024-08-12 12:43 UTC, alalazo commented on lib/spack/spack/cmd/buildcache.py
> +        deptype = dt.RUN | dt.LINK | dt.TEST
Ok, let's leave it in for the time being.

2024-08-12 13:19 UTC, alalazo requested changes
Found a small bug, see below.

2024-08-12 13:19 UTC, alalazo commented on lib/spack/spack/cmd/buildcache.py
> +            ", ".join(_format_spec(s) for s in elide_list(specs, 5)),
This is the only small bug I found. `elide_list` will inject the string `...` into the list, that when passed to `_format_spec` causes:
```console
$ spack -d buildcache push --fail-fast ./mirror4
==> [2024-08-12-15:13:16.809761] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/config.yaml
==> [2024-08-12-15:13:16.825393] Reading config from file /home/culpo/.spack/config.yaml
==> [2024-08-12-15:13:16.829261] Reading config from file /tmp/spack-9z6krkii/spack.yaml
==> [2024-08-12-15:13:16.841737] Using environment '/tmp/spack-9z6krkii'
==> [2024-08-12-15:13:16.860899] Imported buildcache from built-in commands
==> [2024-08-12-15:13:16.864174] Imported buildcache from built-in commands
==> [2024-08-12-15:13:16.864727] Using working directory /tmp as base for abspath
==> [2024-08-12-15:13:16.864840] Using working directory /tmp as base for abspath
==> [2024-08-12-15:13:16.864919] Using working directory /tmp as base for abspath
==> [2024-08-12-15:13:16.864995] Using working directory /tmp as base for abspath
==> [2024-08-12-15:13:16.865740] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/repos.yaml
==> [2024-08-12-15:13:16.867130] Reading config from file /home/culpo/PycharmProjects/spack/etc/spack/defaults/packages.yaml
==> [2024-08-12-15:13:17.083180] Selected 42 specs to push to file:///tmp/mirror4
==> [2024-08-12-15:13:17.083628] DATABASE LOCK TIMEOUT: 60s
==> [2024-08-12-15:13:17.083682] PACKAGE LOCK TIMEOUT: No timeout
Traceback (most recent call last):
  File "/home/culpo/PycharmProjects/spack/bin/spack", line 52, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack_installable/main.py", line 42, in main
    sys.exit(spack.main.main(argv))
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 1070, in main
    return _main(argv)
           ^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 1023, in _main
    return finish_parse_and_run(parser, cmd_name, args, env_format_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 1053, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 650, in _invoke_command
    return_val = command(parser, args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/cmd/buildcache.py", line 1305, in buildcache
    return args.func(args)
           ^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/cmd/buildcache.py", line 492, in push_fn
    raise PackagesAreNotInstalledError(not_installed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/cmd/buildcache.py", line 399, in __init__
    ", ".join(_format_spec(s) for s in elide_list(specs, 5)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/cmd/buildcache.py", line 399, in <genexpr>
    ", ".join(_format_spec(s) for s in elide_list(specs, 5)),
              ^^^^^^^^^^^^^^^
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/cmd/buildcache.py", line 342, in _format_spec
    return spec.cformat("{name}{@version}{/hash:7}")
           ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'cformat'. Did you mean: 'format'?

```

2024-08-12 14:51 UTC, haampie commented on lib/spack/spack/cmd/buildcache.py
> +    """Raised when a spec is not installed but picked to be packaged."""
don't think it's worth it.

2024-08-13 06:01 UTC, alalazo commented on lib/spack/spack/cmd/buildcache.py
> +    """Raised when a spec is not installed but picked to be packaged."""
Well, fair - we can deal with that when / if we need to catch both in the same file. Or use some module alias.

2024-08-13 06:11 UTC, alalazo approved these changes

2024-08-13 06:12 UTC, merged