apfel: add v3.1.1 (now CMakePackage)
LLNL/spack pull request #45661
Opened 2024-08-10 16:35 UTC by wdconinc

This PR adds apfel v3.1.1, which now uses CMake as a build system (release notes for [3.1.0](https://github.com/scarrazza/apfel/releases/tag/3.1.0)). No other changes to variants or dependencies.

Test builds:
```console
$ spack find -lv apfel
-- linux-ubuntu24.04-skylake / gcc@13.2.0 -----------------------
oxfk4j3 apfel@3.0.6+lhapdf+python build_system=autotools
p5vksv6 apfel@3.1.1~ipo+lhapdf+python build_system=cmake build_type=Release generator=make
n2vvide apfel@3.1.1~ipo~lhapdf~python build_system=cmake build_type=Release generator=make
```
with correct python installation prefix
```console
$ ls $(spack location -i /p5vksv6)/lib/python3.10/site-packages/apfel
apfel.py  _apfel.so
```

2024-08-10 16:48 UTC, wdconinc commented
@spackbot fix style

2024-08-12 09:07 UTC, alalazo requested changes

2024-08-12 09:07 UTC, alalazo commented on var/spack/repos/builtin/packages/apfel/package.py
> +class CMakeBuilder(spack.build_systems.cmake.CMakeBuilder):
You need to import these base classes. Other than that it LGTM.

2024-08-12 11:31 UTC, alalazo reviewed
To be consistent with the import

2024-08-12 11:31 UTC, alalazo commented on var/spack/repos/builtin/packages/apfel/package.py
> +class CMakeBuilder(spack.build_systems.cmake.CMakeBuilder):
```suggestion
class CMakeBuilder(cmake.CMakeBuilder):
```

2024-08-12 11:31 UTC, alalazo commented on var/spack/repos/builtin/packages/apfel/package.py
> +class AutotoolsBuilder(spack.build_systems.autotools.AutotoolsBuilder):
```suggestion
class AutotoolsBuilder(autotools.AutotoolsBuilder):
```

2024-08-12 11:45 UTC, wdconinc commented
> To be consistent with the import

Can style checks enforce this better? They didn't flag the missing import nor the overspecified builders, probably because they think the builders are accessible starting from `spack.`

There is a lot of variability in how this is done across package, including by at least one package defining the builders as subclasses of the package instead of other classes in the package module (`szx`).

2024-08-19 08:45 UTC, alalazo approved these changes

2024-08-19 08:45 UTC, merged