[WIP] Error message examples
LLNL/spack pull request #45800
Opened 2024-08-17 01:08 UTC by scheibelp

All the tests here fail (on purpose)

They are intended to test out error messages for cases where specs are over-constrained (all current tests added here do this by adding constraints to the package definition, but should probably also check mixing in config/command-line requirements).

2025-01-23 01:55 UTC, scheibelp commented
I think I've figured out a way to improve error messages for failed concretizations related to requirements - that is on account of updates to `concretize.lp` (note: changes to `error_messages.lp` don't seem to have an effect either way - that was me trying to figure out the purpose of those statements). I've updated the PR description with that in mind. 

Because I wanted to exercise CI, I made it so all the tests added here pass, so if you want to actually see the improved error messages, you'd have to tell pytest to dump output for successful tests (also covered in the PR description) - ideally I can come up with some sensible way to enforce the quality of messages automatically that is not too fragile.

2025-09-12 19:41 UTC, scheibelp commented on lib/spack/spack/solver/error_messages.lp
> +  %attr(Name, node(ID, Package), A1, A2, A3),
Note all the changes above this point in this file were me trying to figure out cause chaining and aren't essential to the PR (I was surprised I could effectively delete some of this and have the tests still pass).

2025-11-03 21:24 UTC, becker33 requested changes

2025-11-03 21:24 UTC, becker33 commented on lib/spack/spack/solver/error_messages.lp
> +  %attr(Name, node(ID, Package), A1, A2, A3),
I think that the `attr(` is redundant because we already have `condition_holds` and `impose_constraint`, so of course the attr must be true as well.

2025-11-03 21:24 UTC, becker33 commented on lib/spack/spack/solver/error_messages.lp
> +     Cause1 < Cause2.
That's an important addition independent of the rest of the PR...

2025-11-03 21:24 UTC, becker33 commented on lib/spack/spack/test/error_messages.py
> +def expect_failure_and_print(should_mention=None):
None of the working tests actually use the `should_mention` argument here -- should we be adding that to the tests to make them more specific?

2025-11-03 21:24 UTC, becker33 commented on lib/spack/spack/test/error_messages.py
> +        concretize_one("x1")
We should make these tests check more about the error message to make sure it stays good -- there's nothing here that actually tests for a good error message

2025-11-03 23:27 UTC, scheibelp commented on lib/spack/spack/test/error_messages.py
> +        concretize_one("x1")
I oriented the checking toward making sure the error message is not bad, vs. checking that it is good.

e..g `test_diamond_with_pkg_conflict1` full error message is:

```
     1. Cannot satisfy 'x4@4.0' 4(4.1)
        required because x3 depends on x4@4.0 
     2. Cannot satisfy 'x4@4.0' 2(4.1)
     3. Cannot satisfy 'x4@4.1' and 'x4@4.0'
        required because x2 depends on x4@4.1 
        required because x3 depends on x4@4.0 
```

the methods `expect_failure_and_print`/`check_error` filter out all the generic error message content and make sure there is something left. Are you thinking we should in fact just compare against that string (maybe minus ordering)? I thought that might make the tests fragile.

2025-11-03 23:27 UTC, scheibelp commented on lib/spack/spack/test/error_messages.py
> +def expect_failure_and_print(should_mention=None):
`test_null_variant_for_requested_version` uses this

EDIT: I think by "working" you mean "passing", `should_mention` is a reason the test fails, and it failing is useful to confirm that the error message is insufficient.

2025-11-04 01:04 UTC, scheibelp commented on lib/spack/spack/test/error_messages.py
> +        concretize_one("x1")
I could update that test to be like:

```
def test_diamond_with_pkg_conflict1(concretize_scope, test_repo):
    concretize_one("x2")
    concretize_one("x3")
    concretize_one("x4")

    important_points = [
        "x2 depends on x4@4.1",
        "x3 depends on x4@4.0",
    ]

    with expect_failure_and_print(should_mention=important_points):
        concretize_one("x1")
```

Is that the level of detail you are looking for in verification?

2025-11-04 02:07 UTC, becker33 commented on lib/spack/spack/test/error_messages.py
> +        concretize_one("x1")
Yes, that's what I was envisioning.

2025-11-04 21:40 UTC, scheibelp commented
@becker33 I think all your requests are addressed now. I also cleaned up some of the comments in the tests

It may be arguable whether `errmsg_requirements_external_mismatch` is sufficiently-improved here: it used to be

```
    1. cannot satisfy a requirement for package 't1'.
```

and now it is

```
     1. Cannot build t1, since it is configured `buildable:false` and no externals satisfy the request
```

better, but perhaps still not good.

2025-11-05 22:32 UTC, becker33 approved these changes

2025-11-05 23:57 UTC, merged

2025-11-06 14:46 UTC, alalazo commented on lib/spack/spack/solver/concretize.lp
> +  imposed_constraint(EffectID, "node_version_satisfies", Package, Version).
Some timing with requirements on would have been nice in this PR, so to know if there is any slow-down / speed-up to be expected.

2025-11-06 18:50 UTC, scheibelp commented on lib/spack/spack/solver/concretize.lp
> +  imposed_constraint(EffectID, "node_version_satisfies", Package, Version).
Apologies yes benchmarking would be useful: How do I do that? (i.e. how do I produce the before/after stats that you add to some PRs)?

This particular rule can be removed (although your comment likely does not apply to it specifically): I looked into it and this was originally added (in https://github.com/spack/spack/pull/45800/commits/75730ecc46d2de288522b2d944dc012fb0daf32a) for https://github.com/spack/spack/pull/45800/commits/344d77afdaa6429ba41fbcd086e714ccbe54b6a2, but an intervening merge removed that logic and it appears that as a result this doesn't actually improve error output for any of the tests (nor any that I can come up with)

2025-11-06 20:29 UTC, alalazo commented on lib/spack/spack/solver/concretize.lp
> +  imposed_constraint(EffectID, "node_version_satisfies", Package, Version).
> How do I do that? (i.e. how do I produce the before/after stats that you add to some PRs)?

We have a Spack extension here https://github.com/spack/spack-benchmark In the README you'll find the commands.

2025-11-13 05:24 UTC, alalazo commented
I noticed a general slowdown of concretization yesterday, with respect to the last time I measured on my machine. I performed a test on a reduced set of specs (just because it takes a lot of time to do the full test).

Here are the results of this PR compared to the previous commit on develop (ecde8095b0f2a2fba38eb59b28bcad34c178b336 vs 3949a273b19ee9aaf3e0e1637dc09c958d069e9c)

[benchmark.pr.csv](https://github.com/user-attachments/files/23516750/benchmark.pr.csv)
[benchmark.develop.csv](https://github.com/user-attachments/files/23516751/benchmark.develop.csv)
[radiuss-reduced.txt](https://github.com/user-attachments/files/23516752/radiuss-reduced.txt)

<img width="2000" height="1000" alt="comparison" src="https://github.com/user-attachments/assets/df53e20b-656b-4a8d-af33-6650427074a5" />

It seems this PR caused a general slowdown of concretization. For `spack solve hdf5 --timers` it's ~20% on my machine. I'll check if that can be improved with some small fix, but let me know if you can reproduce, or not.

2025-11-13 21:14 UTC, scheibelp commented
Benchmarking is reporting a regression for me comparing this with prior commit - the following is just the solve times (as the total times are much closer):

<img width="642" height="489" alt="image" src="https://github.com/user-attachments/assets/5ab32a34-c52d-4b55-86f0-35e19de41e1b" />

> it's ~20% on my machine.

Is this average output as part of `solve-benchmark`?
I see a 14% increase in total solve time across all benchmarked specs.

There is likewise a regression when comparing https://github.com/spack/spack/commit/ecde8095b0f2a2fba38eb59b28bcad34c178b336 with https://github.com/spack/spack/commit/417085841853d8d32580e86ac61ae3064d3e8092

2025-11-14 00:34 UTC, scheibelp commented
After https://github.com/spack/spack/commit/417085841853d8d32580e86ac61ae3064d3e8092, the only logic that isn't changing weights is 

```
{ choose_version(node(ID, Package), Version) : pkg_fact(Package, version_declared(Version)) }
 :- attr("node", node(ID, Package)).

attr("version", node(ID, Package), Version) :- choose_version(node(ID, Package), Version).
```

If I revert that part on top of 4170858, then the benchparks show no significant timing change. This part is useful for error messages, but it only needs to exist when mixing in `error_messages.lp`, so optimistically would only increase concretization times for failed concretizations; I had trouble with that in other parts of this PR, but it seems like a worthy thing to chase to improve the timing.

EDIT: my initial attempt at this in https://github.com/spack/spack/pull/51576 does not work.

2025-11-14 05:58 UTC, alalazo commented
> Is this average output as part of solve-benchmark?

No, it's the result of `spack solve hdf5 --timers`. I used that time to bisect the commit on my machine.

> the only logic that isn't changing weights is, [ ... ]

Yes, it's the two extra rules that increased the time. Once v1.1 is released, I'll try to check if profiling with latest development version of clingo helps identifying better what to change. Unfortunately, using development version of clingo is also prone to trip into bugs (see https://github.com/potassco/clingo/issues/583)

2025-11-19 03:56 UTC, hainest commented
I've found that this PR makes the concretizer hang when given a deprecated spec. For example,

```
$ git checkout develop   # currently 443e1e3e36
$ spack spec python@3.9.24
<hangs>

$ git checkout 3949a273b19ee9aaf3e0e1637dc09c958d069e9c^
$ spack spec python@3.9.24
==> Error: failed to concretize `python@3.9.24` for the following reasons:
     1. Cannot satisfy 'python@3.9.24'
     2. Cannot satisfy 'python@3.9.24'
        required because python@3.9.24 requested explicitly
```

If I manually update the python package to remove the deprecation, I get

```
$ git checkout develop
$ spack edit python
```
```patch
-    with default_args(deprecated=True):
+    with default_args(deprecated=False):
```
```
$ spack spec python@3.9.24
 -   python@3.9.24+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches:=0d98e93,4c24573,ebdca64,f2fd060 platform=linux os=linuxmint21 target=zen3 %c,cxx=gcc@12.3.0
...
```

I have confirmed this is not related to #51599 as I'm able to concretize openmpi without issue. It might be similar to #51279, but that issue was filed in early September before this PR was merged.

---
**Update**:
I found that this works, as well.

```
$ git checkout develop
$ spack spec --deprecated python@3.9.24
==> Warning: using "python@3.9.24" which is a deprecated version
 -   python@3.9.24+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches:=0d98e93,4c24573,ebdca64,f2fd060 platform=linux os=linuxmint21 target=zen3 %c,cxx=gcc@12.3.0
...
```

2025-11-21 07:53 UTC, alalazo commented
@hainest Can you check #51612 ? That should solve the performance regressions of this PR, and more. With that I get:
```console
$ time spack solve python@3.9.24
==> Error: failed to concretize `python@3.9.24` for the following reasons:
     1. Cannot satisfy 'python@3.9.24' 1(3.14.0)
     2. Cannot satisfy 'python@3.9.24' 4(3.14.0)
        required because python@3.9.24 requested explicitly 

real	0m21,530s
user	0m20,953s
sys	0m0,521s
```
Without instead:
```console
$ time spack solve python@3.9.24
^C
==> Error: Keyboard interrupt.
^C

real	1m30,229s
user	1m29,591s
sys	0m0,519s
```

2025-11-22 05:00 UTC, hainest commented
@alalazo I've not checked #51612, but #51611 fixes the issue with the concretizer hanging when using a deprecated spec.