Set up environment variables for ROCm during the build.
LLNL/spack pull request #45842
Opened 2024-08-21 03:05 UTC by dipietrantonio

Without them, the build fails when ROCm is not installed in the default location `/opt/rocm`.

@spackbot fix style

2024-08-21 05:02 UTC, dipietrantonio commented
@spackbot fix style

2024-08-21 05:54 UTC, dipietrantonio commented
Not sure why the Spack bot can't commit on my own branch. I installed it on my organisation's profile.

2024-08-26 13:02 UTC, cedricchevalier19 requested changes
This is not needed in the Kokkos recipe.

To me, it should be fixed by improving your spack configuration. Compiler definitions can load a module, for example. It will set the environment correctly.

2025-06-06 12:05 UTC, haampie commented
Hi @dipietrantonio, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2026-01-04 01:53 UTC, closed without merging