[neovim] add utf8proc dependency
LLNL/spack pull request #46064
Opened 2024-08-27 17:32 UTC by ashermancinelli

I believe utf8proc was added as a neovim dependency in neovim/neovim#26165 and is only in the master branch. This resolves my local build failures.

2024-08-29 12:58 UTC, albestro requested changes
Thanks for the fix!

I haven't tried it but it seems they actually added `utf8proc` as dependency here https://github.com/neovim/neovim/commit/32e16cb0b6b046ba45d3e14c0fdb0383ad8bee1e.

About a minimum version for `utf8proc`, apparently there is no explicit requirement (see https://github.com/neovim/neovim/blob/7588ff2d8986e343d440dc8e025b1b5d4d8974b5/src/nvim/CMakeLists.txt#L36). The bundled version is 2.9.0, but I think it is legit for the moment to not specify any (in case of problems we will restrict it later).

2024-08-29 12:58 UTC, albestro commented on var/spack/repos/builtin/packages/neovim/package.py
> +    with when("@master"):
```suggestion
    with when("@master:"):
```

2024-08-29 16:48 UTC, ashermancinelli commented on var/spack/repos/builtin/packages/neovim/package.py
> +    with when("@master"):
Is there ever a version greater than master (in neovim)? I presume I or someone else will add an explicit `when('@version:')` when a version that depends on utf8proc is released, but I don't understand what this changes semantically. Thanks for the review!

2024-08-30 10:17 UTC, albestro commented on var/spack/repos/builtin/packages/neovim/package.py
> +    with when("@master"):
You’re actually right, it’s a nonsense practice I was used to, because it would be an easy replacement with the next release.

2024-09-02 07:28 UTC, albestro approved these changes

2024-09-02 07:28 UTC, merged