Remove missing library
LLNL/spack pull request #46080
Opened 2024-08-28 14:10 UTC by etiennemlb

Siesta (netcdf-fortran/-c in fact) does not have a hdf5+fortran dependency. Thus spack will not produce libhdf5_fortran and trying to use it will fail (unless you have an external hdf5/reuse of a fdf5+fortran).

2024-08-28 14:13 UTC, etiennemlb commented
@BOUDAOUD34

2024-08-28 14:13 UTC, etiennemlb commented
@spackbot fix style

2024-09-28 11:21 UTC, bernhardkaindl reviewed
@BOUDAOUD34 could you review  this pr from @etiennemlb?

2024-09-30 08:57 UTC, alalazo requested changes
There's no dependency declared on `hdf5` - so accessing `hdf5` directly in the recipe and linking to it seems wrong. Please add a dependency on `hdf5` (or `hdf5+fortran`) as appropriate.

2024-10-01 07:17 UTC, etiennemlb commented
@alalazo you are quite right, I don't know how this ended up in develop.

2024-11-26 14:20 UTC, etiennemlb commented
@alalazo I added the change you requested ,can we merge that ?

2024-11-26 14:25 UTC, alalazo approved these changes

2024-11-26 14:30 UTC, alalazo commented
@etiennemlb Did you try building the recipe / are you using it in production ?

2024-11-26 16:00 UTC, etiennemlb commented
This is used at CINES.

2024-11-26 16:00 UTC, etiennemlb commented
And builds using develop

2024-11-26 19:23 UTC, alalazo commented
Hmm, I guess this recipe still has issues:

![Screenshot from 2024-11-26 20-22-08](https://github.com/user-attachments/assets/841f9f46-fa6d-4dd4-9d72-32417564945f)
Anyhow, this is not introduced by this PR - so I'll merge this, but ping me if you fix more building issues on this package.

2024-11-26 19:25 UTC, merged

2024-11-26 20:22 UTC, etiennemlb commented
If you can provide me with a reproducer for the build issue, I may fix take a look at it.

2024-11-26 21:01 UTC, alalazo commented
I just tried the default concretization on:
* **Spack:** 0.24.0.dev0 (0436929071e1391d2e3f81d290d50c3a592516a6)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake

using `gcc@10.5.0`