openmpi: update dependency wrt mpi standard versions
LLNL/spack pull request #46102
Opened 2024-08-29 06:16 UTC by balay

This PR updates  MPI standard version mapping to  OpenMPI versions, and fixes the following issue:

Without this change:
```
$ ./bin/spack spec ginkgo ^openmpi |grep openmpi@
 -       ^openmpi@1.7.4%gcc@14.0.1~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~internal-libevent~internal-pmix~java~lustre~memchecker~openshmem~orterunprefix~romio+rsh~singularity~sqlite3~static~thread_multiple+vt+wrapper-rpath build_system=autotools fabrics=none romio-filesystem=none schedulers=none arch=linux-fedora40-skylake
```
With this change:
```
$ ./bin/spack spec ginkgo ^openmpi |grep openmpi@
 -       ^openmpi@5.0.5%gcc@14.0.1~atomics~cuda~gpfs~internal-hwloc~internal-libevent~internal-pmix~java~lustre~memchecker~openshmem~romio+rsh~static+vt+wrapper-rpath build_system=autotools fabrics=none romio-filesystem=none schedulers=none arch=linux-fedora40-skylake
```
Ref: 2.1 (change in v1.3.0)
```
$ git grep -E '(MPI_VERSION|MPI_SUBVERSION)' v1.2.9 ompi/include/mpi.h.in
v1.2.9:ompi/include/mpi.h.in:#define MPI_VERSION 2
v1.2.9:ompi/include/mpi.h.in:#define MPI_SUBVERSION 0
$ git grep -E '(MPI_VERSION|MPI_SUBVERSION)' v1.3.0 ompi/include/mpi.h.in
v1.3.0:ompi/include/mpi.h.in:#define MPI_VERSION 2
v1.3.0:ompi/include/mpi.h.in:#define MPI_SUBVERSION 1
```
Ref: 2.2: (change in v1.7.3)
```
$ git grep -E '(MPI_VERSION|MPI_SUBVERSION)' v1.7.2 ompi/include/mpi.h.in
v1.7.2:ompi/include/mpi.h.in:#define MPI_VERSION 2
v1.7.2:ompi/include/mpi.h.in:#define MPI_SUBVERSION 1
$ git grep -E '(MPI_VERSION|MPI_SUBVERSION)' v1.7.3 ompi/include/mpi.h.in
v1.7.3:ompi/include/mpi.h.in:#define MPI_VERSION 2
v1.7.3:ompi/include/mpi.h.in:#define MPI_SUBVERSION 2
```
Ref: 3.0 (change in v1.7.5)
```
$ git grep -E '(MPI_VERSION|MPI_SUBVERSION)' v1.7.4 ompi/include/mpi.h.in
v1.7.4:ompi/include/mpi.h.in:#define MPI_VERSION 2
v1.7.4:ompi/include/mpi.h.in:#define MPI_SUBVERSION 2
$ git grep -E '(MPI_VERSION|MPI_SUBVERSION)' v1.7.5 ompi/include/mpi.h.in
v1.7.5:ompi/include/mpi.h.in:#define MPI_VERSION 3
v1.7.5:ompi/include/mpi.h.in:#define MPI_SUBVERSION 0
```
Ref: 3.1 (change` in v2.0.0)
```$ git grep -E '(MPI_VERSION|MPI_SUBVERSION)' v1.10.7 ompi/include/mpi.h.in
v1.10.7:ompi/include/mpi.h.in:#define MPI_VERSION 3
v1.10.7:ompi/include/mpi.h.in:#define MPI_SUBVERSION 0
$ git grep -E '(MPI_VERSION|MPI_SUBVERSION)' v2.0.0 ompi/include/mpi.h.in
v2.0.0:ompi/include/mpi.h.in:#define MPI_VERSION 3
v2.0.0:ompi/include/mpi.h.in:#define MPI_SUBVERSION 1
```

2024-08-29 13:48 UTC, hppritcha approved these changes

2024-09-03 13:35 UTC, balay commented
@alalazo perhaps this PR can be merged in

2024-09-05 14:00 UTC, balay commented
Checking @alalazo @eugeneswalker @tldahlgren - if you can merge in this PR

2024-09-05 14:09 UTC, alalazo requested changes
This seems wrong, in the current state of Spack. There is a proposal in https://github.com/spack/spack/issues/29915 to change the semantic, but in the meanwhile this needs to be changed.

2024-09-05 14:17 UTC, balay commented
> This seems wrong, in the current state of Spack. 

Sorry - I don't understand what additional fixes are needed here.

Current spack code results in broken builds (due to a bad openmpi version getting picked up)- and the above change works.

2024-09-05 14:30 UTC, balay commented
And wrt mapping the  OpenMPI version to MPI std versions - I've listed the map above [from OpenMPI sources]. Do you see a bug in translating that into spack spec in this PR?

2024-09-09 20:01 UTC, alalazo commented
@balay Currently these directives:
```
provides("mpi@:2.0", when="@:1.2")
provides("mpi@:2.1", when="@1.3.0:")
provides("mpi@:2.2", when="@1.7.3:")
provides("mpi@:3.0", when="@1.7.5:")
provides("mpi@:3.1", when="@2.0.0:")
```
constrain each other so, if you leave an open range, it means that _anything_ from v1.3.0 provides up to MPI 2.1. You need disjoint sets in the `when=` clauses to express what you want. I think those are:
```
provides("mpi@:2.0", when="@:1.2")
provides("mpi@:2.1", when="@1.3:1.7.2")
provides("mpi@:2.2", when="@1.7.3:1.7.4")
provides("mpi@:3.0", when="@1.7.5:1.10.7")
provides("mpi@:3.1", when="@2.0.0:")
```

2024-09-09 20:29 UTC, balay commented
> if you leave an open range, it means that anything from v1.3.0 provides up to MPI 2.

@alalazo prior code has "open range" - so I assumed this was the correct way.

I've updated the PR with the suggested  disjoint ranges. Thanks!

Perhaps @hppritcha can verify is this listing is appropriate.

2024-09-11 13:53 UTC, balay commented
Hoping the current PR changes are acceptable, and its ready-for-merge

2024-09-11 14:27 UTC, alalazo approved these changes

2024-09-11 16:01 UTC, eugeneswalker approved these changes

2024-09-11 16:13 UTC, merged