darshan-runtime: fix Job ID determination
LLNL/spack pull request #46148
Opened 2024-08-30 20:04 UTC by Technohacker

Regardless of the value assigned to the `scheduler` multi-variant, all checks would fail since they expected boolean variants instead

2024-09-05 16:17 UTC, shanedsnyder approved these changes

2024-09-05 16:18 UTC, shanedsnyder commented
Looks good to me, thanks for the fix @Technohacker !

2024-09-05 17:00 UTC, Technohacker commented
I recommend squash merging this PR because of that merge commit :sweat_smile:

2024-09-09 05:08 UTC, alalazo requested changes

2024-09-09 05:08 UTC, alalazo commented on var/spack/repos/builtin/packages/darshan-runtime/package.py
> +        if scheduler == "slurm":
```suggestion
        if spec.satisfies("scheduler=slurm"):
```
and similarly below

2024-09-09 14:20 UTC, Technohacker commented on var/spack/repos/builtin/packages/darshan-runtime/package.py
> +        if scheduler == "slurm":
Fixed, thanks!

2024-09-09 14:32 UTC, alalazo approved these changes

2024-09-09 16:53 UTC, merged