Deprecate `config:install_missing_compilers`
LLNL/spack pull request #46237
Opened 2024-09-05 14:37 UTC by alalazo

depends on https://github.com/spack/spack/pull/46221

The option `config:install_missing_compilers` is currently buggy, and has been for a while. Remove it, since it won't be needed when compilers are treated as dependencies.

2024-09-05 22:39 UTC, becker33 requested changes
There is a `compiler` attribute on `spack.installer.BuildTask` that I believe is only used to track behavior for compiler bootstrapping -- we should probably remove that attribute as well.

There is also a sequencing issue with this PR and https://github.com/spack/spack/pull/39136, we should think carefully about which rebase would be less unpleasant before merging these.

2024-09-06 06:14 UTC, alalazo commented
@becker33 I rebased the PR. At this point the PR mostly removes entire functions / methods, so it should be easy to check what needs to done in case of conflicts.  If we leave removing `BuildTask.compiler` etc. for #39136 I don't think there will be many conflicts among the two.

2024-09-09 17:17 UTC, becker33 requested changes
I think the `_add_compiler_package_to_config` method is unique to this feature, and we can remove it and all of its call-sites. The call sites are all conditions `if task.compiler`.

The `_modify_existing_task` is never called once this PR is merged, but the method itself hasn't been removed.

2024-09-09 17:17 UTC, becker33 commented on lib/spack/spack/solver/asp.py
> +            # If this is a compiler yet to be built infer libc from the Python process
I believe this condition is unreachable given this PR

2024-09-09 20:15 UTC, alalazo commented
@becker33 Review should be addressed

2024-09-10 17:34 UTC, becker33 approved these changes

2024-09-10 18:02 UTC, merged