msr-safe
LLNL/spack pull request #46289
Opened 2024-09-09 18:03 UTC by fleshling

msr-safe provides controlled userspace access to model-specific registers (MSRs). It allows system administrators to give register-level read access and bit-level write access to trusted users in production environments. This access is useful where kernel drivers have not caught up with new processor features, or performance constraints requires batch access across dozens or hundreds of registers.

In this package, msr-safe relies on the linux-external-modules package which is the Linux kernel configured to build out-of-branch kernel modules.

2024-09-13 21:02 UTC, scheibelp requested changes
I have a question/suggested-change about the (implicitly) preferred version of msr-safe, but other than that this looks good

2024-09-13 21:02 UTC, scheibelp commented on var/spack/repos/builtin/packages/msr-safe/package.py
> +        "linux-6.9.9-cleanup",
What is the purpose of this version?

It looks like this will come last (i.e. be treated like the newest possible version), because our sorting puts "linux" ahead of all numbers. The change in scheme is a bit confusing though.

That being said, `6.9.9` seems like quite a jump:

* is this referring to a linux version, or an msr-safe version? it should probably reflect the msr-safe version
* why is this separate repo (not the official msr-safe) the preferred version of msr-safe in Spack? It would be useful to explain what this provides over the official msr-safe, and it might make sense to make it conditional on a variant like:

```
variant("special_feature")
conflicts("@linux-6.9.9-cleanup", when="~special_feature")
```

2024-09-19 06:49 UTC, kyotsukete commented
@scheibelp

2024-09-19 07:06 UTC, scheibelp approved these changes

2024-09-19 17:50 UTC, scheibelp commented
@spackbot run pipeline

2024-09-23 22:04 UTC, merged