[py-pydantic] new version 2.7.4
LLNL/spack pull request #46307
Opened 2024-09-10 17:05 UTC by qwertos

#46306

2024-09-13 19:00 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-pydantic/package.py
> +    depends_on("py-annotated-types@0.4.0:", type=("build", "run"), when="@2.7.4:")
Missing dependency.

2024-10-08 07:05 UTC, bernhardkaindl requested changes
Depends on `py-annotated-types`, which does not exit as recipe.

2024-10-08 14:45 UTC, wdconinc commented
```
==> Installing py-annotated-types-0.7.0-7bnfgmww62j4e3huk2algxn2pjpiopjt [33/33]
==> No binary for py-annotated-types-0.7.0-7bnfgmww62j4e3huk2algxn2pjpiopjt found: installing from source
==> Fetching https://files.pythonhosted.org/packages/source/a/annotated_types/annotated_types-0.7.0.tar.gz
==> No patches needed for py-annotated-types
==> py-annotated-types: Executing phase: 'install'
==> py-annotated-types: Successfully installed py-annotated-types-0.7.0-7bnfgmww62j4e3huk2algxn2pjpiopjt
  Stage: 1.94s.  Install: 0.74s.  Post-install: 0.17s.  Total: 3.00s
[+] /opt/software/linux-ubuntu24.04-skylake/gcc-13.3.0/py-annotated-types-0.7.0-7bnfgmww62j4e3huk2algxn2pjpiopjt
```
and
```
$ python 
Python 3.11.9 (main, Sep 13 2024, 13:12:09) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import annotated_types
>>> annotated_types.__version__
'0.7.0'
```

2024-10-08 14:46 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-pydantic/package.py
> +    depends_on("py-annotated-types@0.4.0:", type=("build", "run"), when="@2.7.4:")
Added in 73a5353

2024-10-08 16:11 UTC, bernhardkaindl approved these changes
Build results on Ubuntu 22.04.4 LTS:
```py
bin/spack find --variants py-annotated-types@0.7.0%clang@15.0.7 py-annotated-types@0.7.0%clang@14.0.0 py-annotated-types@0.7.0%clang@14.0.0 py-annotated-types@0.7.0%gcc@9.5.0 py-annotated-types@0.7.0%gcc@8.4.0 py-annotated-types@0.7.0%gcc@13.1.0 py-annotated-types@0.7.0%gcc@12.3.0 py-annotated-types@0.7.0%gcc@11.4.0 py-annotated-types@0.7.0%gcc@11.4.0 py-annotated-types@0.7.0%gcc@10.5.0 py-pydantic@2.7.4%clang@15.0.7 py-pydantic@2.7.4%clang@14.0.0 py-pydantic@2.7.4%clang@14.0.0 py-pydantic@2.7.4%gcc@9.5.0 py-pydantic@2.7.4%gcc@8.4.0 py-pydantic@2.7.4%gcc@13.1.0 py-pydantic@2.7.4%gcc@12.3.0 py-pydantic@2.7.4%gcc@11.4.0 py-pydantic@2.7.4%gcc@11.4.0 py-pydantic@2.7.4%gcc@10.5.0
-- linux-ubuntu22.04-skylake / clang@14.0.0 ---------------------
py-annotated-types@0.7.0
py-pydantic@2.7.4~dotenv

-- linux-ubuntu22.04-skylake / clang@15.0.7 ---------------------
py-annotated-types@0.7.0
py-pydantic@2.7.4~dotenv

-- linux-ubuntu22.04-skylake / gcc@8.4.0 ------------------------
py-annotated-types@0.7.0
py-pydantic@2.7.4~dotenv

-- linux-ubuntu22.04-skylake / gcc@9.5.0 ------------------------
py-annotated-types@0.7.0
py-pydantic@2.7.4~dotenv

-- linux-ubuntu22.04-skylake / gcc@10.5.0 -----------------------
py-annotated-types@0.7.0
py-pydantic@2.7.4~dotenv

-- linux-ubuntu22.04-skylake / gcc@11.4.0 -----------------------
py-annotated-types@0.7.0
py-pydantic@2.7.4~dotenv

-- linux-ubuntu22.04-skylake / gcc@12.3.0 -----------------------
py-annotated-types@0.7.0
py-pydantic@2.7.4~dotenv

-- linux-ubuntu22.04-skylake / gcc@13.1.0 -----------------------
py-annotated-types@0.7.0
py-pydantic@2.7.4~dotenv
```
Generated by https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py
```py
build-quality-tools/build_pr_changes.py -may -c all
```

2024-10-08 16:19 UTC, merged