add support for hdf5 for geant4
LLNL/spack pull request #46312
Opened 2024-09-10 17:45 UTC by DingXuefeng

Hi, I added variant +hdf to allow geant4 to be compiled with support for HDF5 output format.

@drbenmorgan @sethrj

2024-09-10 18:18 UTC, drbenmorgan submitted a review, later dismissed
Looks good to me, thanks @DingXuefeng!

2024-09-10 18:44 UTC, sethrj requested changes

2024-09-10 18:44 UTC, sethrj commented on var/spack/repos/builtin/packages/geant4/package.py
> +    variant("hdf", default=False, description="Enable HDF5 support", when="@10.4:")
Can you spell this as `hdf5` to be more consistent with the other (dozens of) Spack packages?

```suggestion
    variant("hdf5", default=False, description="Enable HDF5 support", when="@10.4:")
```

2024-09-10 18:44 UTC, sethrj commented on var/spack/repos/builtin/packages/geant4/package.py
> +            options.append(self.define("GEANT4_USE_HDF5", True))
This should work and be more foolproof (explicitly setting it to "off" if disabled)
```suggestion
        options.append(self.define_from_variant("GEANT4_USE_HDF5", "hdf"))
```

2024-09-12 11:54 UTC, sethrj approved these changes
Thanks!

2024-09-12 12:34 UTC, merged