py-onnxruntime: add new versions
LLNL/spack pull request #46329
Opened 2024-09-11 16:15 UTC by joequant

Add new versions to py-onnxruntime

2024-09-11 19:21 UTC, tldahlgren reviewed
Confirmed the five new commits

2024-09-11 20:04 UTC, tldahlgren requested changes
The new version constraints on `py-numpy`, based on `requirements.txt` files, are:

- when `@1.19:` :  `py-numpy@1.21.6:`
- when `1.18.1:1.18.2`:   `py-numpy@1.21.6:1`

2024-09-11 20:17 UTC, wdconinc commented
Ort also doesn't typically support newer ONNX opsets than what was there at the time of Ort release, so I have locally something like this:
```py
    depends_on("py-onnx@:1.16", type=("build", "run"), when="@:1.18")
```

2024-09-19 23:51 UTC, wdconinc commented
@joequant Please address the comments so we can move forward on this PR since others want to either use this or reimplement it themselves (https://github.com/spack/spack/pull/46448#discussion_r1765176008).

2024-09-20 04:24 UTC, joequant commented
> @joequant Please address the comments so we can move forward on this PR since others want to either use this or reimplement it themselves ([#46448 (comment)](https://github.com/spack/spack/pull/46448#discussion_r1765176008)).

Okay let me fix

2024-09-20 04:33 UTC, joequant commented
> @joequant Please address the comments so we can move forward on this PR since others want to either use this or reimplement it themselves ([#46448 (comment)](https://github.com/spack/spack/pull/46448#discussion_r1765176008)).

@wdconinc Just put in the new constraints

2024-09-22 18:23 UTC, wdconinc commented
Conflicts require resolution after https://github.com/spack/spack/pull/46448.

2025-02-16 00:50 UTC, wdconinc approved these changes

2025-02-16 00:51 UTC, wdconinc commented
@tldahlgren Due to request changes, this needs your review again.

2025-02-19 20:02 UTC, tldahlgren approved these changes
@wdconinc Any objections to merging?

2025-02-19 20:02 UTC, merged

2025-02-19 20:03 UTC, wdconinc commented
> @wdconinc Any objections to merging?

Guess not.