DRAFT: hiop: Fix how ReSolve option is passed
LLNL/spack pull request #46378
Opened 2024-09-13 17:53 UTC by cameronrutherford

Was getting some cryptic errors building hiop~cuda and it looked like some extra whitespace was being added to the CMake line due to a stray CLI argument from an undefined `args.extend` input.

This should fix that issue - see error [pipeline](https://github.com/LLNL/hiop/actions/runs/10741214413/job/29791072221)

2024-09-19 14:38 UTC, cameronrutherford commented on var/spack/repos/builtin/packages/hiop/package.py
> +            args.extend(self.define_from_variant("HIOP_USE_RESOLVE", "cusolver_lu"))
Maybe there is a cleaner way to do this... It's functional and I am unsure if this was even necessary to resolve the bug we were seeing in the GitHub pipelines, but seems like a sensible change to remove additional whitespace in CMake line.

2024-09-19 23:51 UTC, cameronrutherford commented
The HiOp pipelines are now passing.

I noticed that there was a random whitespace in the CMake command before I noticed the "error" in the spack code here.

Makes me wonder if spack should auto-remove whitespace to cover edge cases like this?

2024-10-08 15:32 UTC, cameronrutherford commented
I don't know why CI is failing (test timed out?).

This change is sensible for builds without cuda. Cc @nychiang

2024-10-08 22:56 UTC, nychiang commented
@cameronrutherford 
it seems to me the argument `-DHIOP_USE_RESOLVE` is incorrectly defined.
The log shows the followings:
'''
'-' 'D' 'H' 'I' 'O' 'P' '_' 'U' 'S' 'E' '_' 'R' 'E' 'S' 'O' 'L' 'V' 'E' ':' 'B' 'O' 'O' 'L' '=' 'O' 'F' 'F' '-DHIOP_BUILD_STATIC:BOOL=ON' '-DBLAS_FOUND:BOOL=ON'
'''
Any thought about why this happens?

2024-10-09 00:21 UTC, cameronrutherford commented on var/spack/repos/builtin/packages/hiop/package.py
> +        with when("+cuda @:0.7.1"):
```suggestion
        with when("+cuda @0.7.1:"):
```

2024-10-09 00:22 UTC, cameronrutherford commented
> @cameronrutherford it seems to me the argument `-DHIOP_USE_RESOLVE` is incorrectly defined. The log shows the followings: ''' '-' 'D' 'H' 'I' 'O' 'P' '_' 'U' 'S' 'E' '_' 'R' 'E' 'S' 'O' 'L' 'V' 'E' ':' 'B' 'O' 'O' 'L' '=' 'O' 'F' 'F' '-DHIOP_BUILD_STATIC:BOOL=ON' '-DBLAS_FOUND:BOOL=ON' ''' Any thought about why this happens?

Not really sure... I noticed an issue with the syntax when I looked at the code again, but I think I am doing everything right. We shall see what CI says after this...

2024-11-08 03:48 UTC, cameronrutherford commented on var/spack/repos/builtin/packages/hiop/package.py
> +            args.extend(self.define_from_variant("HIOP_USE_RESOLVE", "cusolver_lu"))
```suggestion
            args.extend([self.define_from_variant("HIOP_USE_RESOLVE", "cusolver_lu")])
```
Maybe this fixes it

2025-03-10 02:06 UTC, cameronrutherford commented
@nychiang I am closing this, but I think it should be merged. CI passed on the last pipeline. Not sure why we never merged.

2025-03-10 03:11 UTC, pelesh commented
I think this got

2025-03-10 03:12 UTC, pelesh approved these changes
Looks good.

2025-04-11 16:55 UTC, alalazo requested changes

2025-04-11 16:55 UTC, alalazo commented on var/spack/repos/builtin/packages/hiop/package.py
> +            args.extend([self.define_from_variant("HIOP_USE_RESOLVE", "cusolver_lu")])
This is wrong. The context manager:
```
with when(...):
    ...
```
works at class level, and only for directives. What was this meant to do?

2025-04-11 17:18 UTC, cameronrutherford commented on var/spack/repos/builtin/packages/hiop/package.py
> +            args.extend([self.define_from_variant("HIOP_USE_RESOLVE", "cusolver_lu")])
```suggestion
        if self.spec.satisfies("+cuda @0.7.1:"):
            args.extend([self.define_from_variant("HIOP_USE_RESOLVE", "cusolver_lu")])
```

This is what we could change it to?

The idea is that `HIOP_USE_RESOLVE` is only an option in `@0.7.1:`, and then I think the `+cuda` requirement is redundant.

Now that I think about it, won't CMake just reference this as an unused variable in earlier versions? I assume that we can get away with lumping this into our other `args.extend` call if so.

2025-04-11 17:40 UTC, alalazo commented on var/spack/repos/builtin/packages/hiop/package.py
> +            args.extend([self.define_from_variant("HIOP_USE_RESOLVE", "cusolver_lu")])
> Now that I think about it, won't CMake just reference this as an unused variable in earlier versions?

Yes, it should

2025-04-11 20:45 UTC, cameronrutherford commented on var/spack/repos/builtin/packages/hiop/package.py
> +            args.extend([self.define_from_variant("HIOP_USE_RESOLVE", "cusolver_lu")])
Okay I simplified and moved this as discussed.

2025-04-11 20:47 UTC, cameronrutherford commented
Now it looks like this PR is basically a no-op after making adjustments based on review? @pelesh or @nychiang I've forgotten the context behind this PR, and so perhaps it isn't necessary anymore.

2025-04-11 20:48 UTC, cameronrutherford commented on var/spack/repos/builtin/packages/hiop/package.py
> +            args.extend([self.define_from_variant("HIOP_USE_RESOLVE", "cusolver_lu")])
Changing back turned this into a no-op of a PR... I think the issue is that when building `~cuda`, the option got mangled and CMake threw a fit. Unless a maintainer of hiop can remember why / reproduce the issue, or if there are build failures that need addressing, then I think we can close the PR.

2025-04-12 20:36 UTC, pelesh commented
> Now it looks like this PR is basically a no-op after making adjustments based on review? @pelesh or @nychiang I've forgotten the context behind this PR, and so perhaps it isn't necessary anymore.

It seems we cannot reproduce the issue addressed in this PR anymore. I suggest we close.

2025-04-12 22:04 UTC, closed without merging