add package for feelpp feelpp/spack#4
LLNL/spack pull request #46396
Opened 2024-09-14 21:24 UTC by prudhomm

add package for feelpp see  feelpp/spack#4

2024-09-15 16:28 UTC, vincentchabannes approved these changes

2024-10-12 10:57 UTC, bernhardkaindl requested changes
`feelpp` requires boost `+date_time+system` and maybe more which may be missing in the `depends_on` for Boost.

These are added by `Boost.with_default_variants` to cut down on the number of different Boost variants in `spack` builds.

I am trying to build it, so see if there are more issues.

The most maintainable fix for this issue appears to look somewhat like this:
```py
--- a/var/spack/repos/builtin/packages/feelpp/package.py
+++ b/var/spack/repos/builtin/packages/feelpp/package.py
@@ -4,6 +4,7 @@
 # SPDX-License-Identifier: (Apache-2.0 OR MIT)

 from spack.package import *
+from spack.pkg.builtin.boost import Boost


 class Feelpp(CMakePackage):
@@ -49,7 +50,8 @@ class Feelpp(CMakePackage):
     depends_on("cmake@3.21:", type="build")
     depends_on("llvm@14.0.0:")
     depends_on("mpi")
-    depends_on("boost@1.74: +filesystem+iostreams+mpi+multithreaded+shared")
+    depends_on(Boost.with_default_variants)
+    depends_on("boost@1.74: +mpi+multithreaded+shared")
     depends_on("petsc@3.20 +mumps+hwloc+ptscotch +suite-sparse+hdf5 +hypre+kokkos")
     depends_on("slepc")
     depends_on("cln@1.3.6")
```

Afther this, I get
```py
  >> 255     <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  >> 256     <string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
```
`feelpp` needs to be converted from `distutils` to use `setuptools` for Python3.12 and newer.

This means that it conflicts with newer Python versions 

The current falal error that breaks the build is:
```py
  >> feelpp/contrib/fmi4cpp/src/fmi4cpp/fmi2/xml/model_description_parser.cpp:5:10: fatal error: 'pugixml.hpp' file not found
     1884        5 | #include <pugixml.hpp>
     1885          |          ^~~~~~~~~~~~~
```
See the PR that I opened for this https://github.com/feelpp/FMI4cpp/pull/3 for details:

2024-10-12 12:10 UTC, bernhardkaindl requested changes
`feelpp` also appears to be missing `readline` to compile:
```py
In file included from ginsh_lexer.lpp:38:
/home/bkaindl/spack.2/.stage/spack-stage-feelpp-preset-5ewfr42h5iwso6b27cepj5yn3jkv6x6z/spack-src/feelpp/contrib/ginac/ginsh/ginsh.h:36:10: fatal error: 'readline/readline.h' file not found
   36 | #include <readline/readline.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
```
This needs at least a `depends_on("readline")` and maybe also a `cmake` `incude_directories` fix as well. (As workaround, it can be installed on the host, but that's not a fix).

Also, a `cmake` `incude_directories` fix for fftw3 appears to be needed:
```py
/home/bkaindl/spack.2/.stage/spack-stage-feelpp-preset-5ewfr42h5iwso6b27cepj5yn3jkv6x6z/spack-src/feelpp/feel/../feel/feeldiscr/fftmultiscale.hpp:49:10: fatal error: 'fftw3.h' file not found
   49 | #include <fftw3.h>
      |          ^~~~~~~~~`
```

2024-10-12 12:50 UTC, bernhardkaindl requested changes
See the hints in https://github.com/feelpp/spack/pull/5

2024-10-23 13:17 UTC, prudhomm commented
@bernhardkaindl thank you for your extensive work ! I made some other changes to support rocm, cuda, kokkos that I will push along side your propositions.

2025-05-07 07:45 UTC, alalazo commented
Can you update the PR to follow the recent change in the repository layout, or close it if not relevant anymore?

2025-06-06 12:06 UTC, haampie commented
Hi @prudhomm, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2026-01-04 01:53 UTC, closed without merging