geant4: add zlib variant
LLNL/spack pull request #46393
Opened 2024-09-14 17:41 UTC by DingXuefeng

Hi again.

See https://bugzilla-geant4.kek.jp/show_bug.cgi?id=2625 

Geant4 compiled with zlib-ng is not working well. The results sometimes are corrupted. I propose to add zlib variant and disable it by default so user use built-in zlib.

@drbenmorgan @sethrj

2024-09-14 17:50 UTC, wdconinc commented
If this is an issue with `zlib-ng` and not the older `zlib`, then you can also add a conflict (for the affected versions) with e.g.
```py
    conflicts("^[virtuals=zlib-api] zlib-ng", when="@:11.2")
```

2024-09-14 22:33 UTC, sethrj requested changes
This isn't right I think. "System" just means provided outside geant4, which should be provided by spack. You can house whatever version of zlib that works

2024-09-15 17:33 UTC, DingXuefeng commented
> This isn't right I think. "System" just means provided outside geant4, which should be provided by spack. You can house whatever version of zlib that works

> If this is an issue with `zlib-ng` and not the older `zlib`, then you can also add a conflict (for the affected versions) with e.g.
> 
> ```python
>     conflicts("^[virtuals=zlib-api] zlib-ng", when="@:11.2")
> ```

I agree, I'll I agree, I'll do some test and if older zlib-ng is okdo some test and if older zlib-ng is ok.

2024-09-16 15:21 UTC, sethrj commented
@DingXuefeng It would be very helpful to document what versions of Geant4 and zlib-ng produce the errors, and what errors those are. It would be great for someone else to try reproducing them as well.

2024-09-16 16:03 UTC, DingXuefeng commented
> If this is an issue with `zlib-ng` and not the older `zlib`, then you can also add a conflict (for the affected versions) with e.g.
> 
> ```python
>     conflicts("^[virtuals=zlib-api] zlib-ng", when="@:11.2")
> ```



> If this is an issue with `zlib-ng` and not the older `zlib`, then you can also add a conflict (for the affected versions) with e.g.
> 
> ```python
>     conflicts("^[virtuals=zlib-api] zlib-ng", when="@:11.2")
> ```

just confirmed geant4 with older zlib is fine

2024-09-16 16:06 UTC, DingXuefeng commented
> @DingXuefeng It would be very helpful to document what versions of Geant4 and zlib-ng produce the errors, and what errors those are. It would be great for someone else to try reproducing them as well.



> @DingXuefeng It would be very helpful to document what versions of Geant4 and zlib-ng produce the errors, and what errors those are. It would be great for someone else to try reproducing them as well.

Hi, the minimum reproducible example can be found at https://bugzilla-geant4.kek.jp/show_bug.cgi?id=2625 as attachment. Someone can take a look at it.

I'm not familiar with spack and don't know how to test different combinations of geant4 and zlib-ng easily. It's not easy to compare them one-by-one by hand. If someone can provide instructions I can do it.

2024-09-16 16:17 UTC, sethrj commented
@DingXuefeng in your reproducer, can you confirm that you used a spack-installed ROOT or verify that your ROOT implementation is using the exact same `zlib` as in your geant4 toolchain? If not, this is likely an error due to conflicting symbols/ABIs.

2024-09-16 16:48 UTC, sethrj reviewed
Actually I looked into this and it's not actually using ROOT to output via the file manager: there's a second implementation of ROOT's NTuple that looks really sketchy and that's what links against zlib. It wouldn't surprise me if there's a bug in there that depends on an implementation detail of zlib, so I think the conflict is probably right... or maybe it should just use `depends_on("zlib")` instead of `depends_on("zlib-api")`. Thoughts @wdconinc ? The implementation is in `externals/g4tools/include/toolx/zlib`.

2024-09-16 17:03 UTC, DingXuefeng commented
> Actually I looked into this and it's not actually using ROOT to output via the file manager: there's a second implementation of ROOT's NTuple that looks really sketchy and that's what links against zlib. It wouldn't surprise me if there's a bug in there that depends on an implementation detail of zlib, so I think the conflict is probably right... or maybe it should just use `depends_on("zlib")` instead of `depends_on("zlib-api")`. Thoughts @wdconinc ? The implementation is in `externals/g4tools/include/toolx/zlib`.



> Actually I looked into this and it's not actually using ROOT to output via the file manager: there's a second implementation of ROOT's NTuple that looks really sketchy and that's what links against zlib. It wouldn't surprise me if there's a bug in there that depends on an implementation detail of zlib, so I think the conflict is probably right... or maybe it should just use `depends_on("zlib")` instead of `depends_on("zlib-api")`. Thoughts @wdconinc ? The implementation is in `externals/g4tools/include/toolx/zlib`.

what I'm more surpised is if I change `analysis->Fill ... momentum.x()` into `analysis->Fill .. G4RandFlat::shoot()` the bug is gone. and if I use `position.x()` it's also gone. I'm a bit worried what really happened.

2024-09-16 17:34 UTC, wdconinc commented
> there's a second implementation of ROOT's NTuple that looks really sketchy

Oh boy... I don't know what to say. Other than "HEP: we don't want a dependency, but let's reimplement the functionality instead in these 160k lines." (I understand that there may be good reasons for this; @drbenmorgan please chime in)

I really don't want to push entire software stacks back to using a less performant `zlib` just because of a `G4RootFileManager` that isn't used by too many people (I suspect)... So, I think that `zlib-ng` should remain the default.

But making `zlib-ng` the default means we can't install a broken `analysis/root` until fixed upstream, because this is so undiscoverable and an obscure error. I would rather have users ask themselves why there is no `G4RootFileManager.hh` and enable `+analysis_root` which requires `^[virtuals=zlib-api] zlib`, than users getting stung by this bug.

So, I guess my suggestion is a variant `+analysis_root`, default false, when for broken versions (all?), and which causes a `filter_file` on `source/analysis/CMakeLists.txt` to comment the `include(root/sources.cmake)`.

Yes, I do get the irony that we are back to a variant.

2024-09-16 17:42 UTC, sethrj commented
The downside of the "filter" approach is that it's going to be different kind of obscure bug if "spack-installed geant4" is substantially different from "independently installed geant4" (even if that  means using a crummy version of zlib). Perhaps it would be better to insert a G4Exception call that says "hey, this installation is built against a buggy version of g4tools that doesn't support the modern version of zlib. please reinstall with an old zlib and `+analysis_root`)?

2024-09-17 17:10 UTC, DingXuefeng commented
so
```python
conflicts("^[virtuals=zlib-api] zlib-ng", when="@:11.2")
```
cannot pass CI. no idea why. How should we proceed?

2024-09-17 17:21 UTC, sethrj commented
I think the error is unrelated. Also, if you *have* managed to fix the bug in https://bugzilla-geant4.kek.jp/show_bug.cgi?id=2625 , then the best solution is to patch it via spack.

2024-09-17 19:26 UTC, DingXuefeng commented
> I think the error is unrelated. Also, if you _have_ managed to fix the bug in https://bugzilla-geant4.kek.jp/show_bug.cgi?id=2625 , then the best solution is to patch it via spack.

I did a few shot without success. It's too complicate.

For me seems zlib replacing zlib-ng should be an acceptable solution. zlib-ng itself said it's not recommeded to replace it system wide, so there can be some incompatibilities.

Disabling analysis root etc. is also very complex and need to modify c++ source code, not just CMakeLists.txt.

I propose we proceed to add conflictions as default. This would make my life easier. 

Yet you are right that even without warnings geant4 with zlib results can be wrong .. Geant4 did not implemnt CRC... so it's not reliable :( Maybe I need to fully abandon G4AnalysisManager..

2024-09-18 02:12 UTC, DingXuefeng commented
I found I can fix it simply with 
```bash
spack change geant4 ^zlib
```
without changing `spack/ .. /geant4/package.py`. for me now it's not a problem any more.

So now the question becomes shall we make some patches for the default situations so spack is open-box-ready. I'll see how barrand from geant4 proceeds and if he can fix the bug. The best would be to fix it with a patch.

2024-10-12 13:09 UTC, bernhardkaindl commented
@DingXuefeng, I don't understand this yet:

Is the patch needed for `zlib-ng`, but not for `zlib`?

If so, would it be fine to apply the change (in which ever way) dependent on if the virtual `zlib-api` uses `zlib-ng`?

In a function in the recipe, you/we could use: 
```py
if self.spec["zlib-api"].name == "zlib-ng":
   filter_file(....)  # Make the call compatible to zlib-ng   
```
Maybe this works too:
```py
   patch("geant4-9.5-wroot.patch", when="^zlib-ng")
```
For example, perl seems to do this:
```py
grep -r zlib-ng var/
var/spack/repos/builtin/packages/perl/package.py:    # Support zlib-ng 2.1.2 and above for recent Perl
var/spack/repos/builtin/packages/perl/package.py:    # Restrict zlib-ng to older versions for older Perl
var/spack/repos/builtin/packages/perl/package.py:    patch("zlib-ng.patch", when="@5.38 ^zlib-ng@2.1.2:")
var/spack/repos/builtin/packages/perl/package.py:    conflicts("^zlib-ng@2.1.2:", when="@:5.37")
```
Other packages also have some mention of `zlib-ng` to workaround issues, you might consider some of the other results of `grep -r zlib-ng var/` interesting.

2024-10-12 13:10 UTC, bernhardkaindl reviewed
@sethrj - @DingXuefeng, I don't understand this yet:

Is the patch needed for `zlib-ng`, but not for `zlib`?

If so, would it be fine to apply the change (in which ever way) dependent on if the virtual `zlib-api` uses `zlib-ng`?

In a function in the recipe, you/we could use: 
```py
if self.spec["zlib-api"].name == "zlib-ng":
   filter_file(....)  # Make the call compatible to zlib-ng   
```
Maybe this works too:
```py
   patch("geant4-9.5-wroot.patch", when="^zlib-ng")
```
For example, perl seems to do this:
```py
grep -r zlib-ng var/
var/spack/repos/builtin/packages/perl/package.py:    # Support zlib-ng 2.1.2 and above for recent Perl
var/spack/repos/builtin/packages/perl/package.py:    # Restrict zlib-ng to older versions for older Perl
var/spack/repos/builtin/packages/perl/package.py:    patch("zlib-ng.patch", when="@5.38 ^zlib-ng@2.1.2:")
var/spack/repos/builtin/packages/perl/package.py:    conflicts("^zlib-ng@2.1.2:", when="@:5.37")
```
Other packages also have some mention of `zlib-ng` to workaround issues, you might consider some of the other results of `grep -r zlib-ng var/` interesting.

2024-10-12 19:07 UTC, sethrj commented
@bernhardkaindl I think this is the classic case of the code relying on undefined behavior... what's there is wrong and should be patched, but we only *know* that it's wrong in the case of zlib-ng. There's no patch yet either way...

2024-11-26 15:50 UTC, DingXuefeng commented
> @bernhardkaindl I think this is the classic case of the code relying on undefined behavior... what's there is wrong and should be patched, but we only _know_ that it's wrong in the case of zlib-ng. There's no patch yet either way...

It seems the situation is quite clear now, check [the comment from barrand of Geant4](https://bugzilla-geant4.kek.jp/show_bug.cgi?id=2625#c21). To summarize:
- ROOT detects if data is compressed by `if (fObjlen > fNbytes-fKeylen) {`
- compressed data by `zlib-ng` has larger data-size compared with the raw data and thus is understood by ROOT as un-compressed, causing I/O corruption.
- 'zlib', instead, can properly compress the data to smaller size.

I think we need to set geant4 to use `zlib` instead of `zlib-ng`. It seems `zlib-ng` cannot compress geant4 generated momentum data. Very strange. but it happens. @sethrj @bernhardkaindl

2024-11-26 16:12 UTC, DingXuefeng commented
> > @bernhardkaindl I think this is the classic case of the code relying on undefined behavior... what's there is wrong and should be patched, but we only _know_ that it's wrong in the case of zlib-ng. There's no patch yet either way...
> 
> It seems the situation is quite clear now, check [the comment from barrand of Geant4](https://bugzilla-geant4.kek.jp/show_bug.cgi?id=2625#c21). To summarize:
> 
> * ROOT detects if data is compressed by `if (fObjlen > fNbytes-fKeylen) {`
> * compressed data by `zlib-ng` has larger data-size compared with the raw data and thus is understood by ROOT as un-compressed, causing I/O corruption.
> * 'zlib', instead, can properly compress the data to smaller size.
> 
> I think we need to set geant4 to use `zlib` instead of `zlib-ng`. It seems `zlib-ng` cannot compress geant4 generated momentum data. Very strange. but it happens. @sethrj @bernhardkaindl

I also noticed that baren fixed the bug. He checks if the compressed data is larger than the orignal data, he will simply put the original data. In this case, zlib-ng will also be usable. This bug fix shall probably be included in geant4 11.3 release.

2025-05-07 07:44 UTC, alalazo commented
Can you update the PR to follow the recent change in the repository layout, or close it if not relevant anymore?

2025-05-08 05:33 UTC, sethrj commented
I think we need another approach: either the right patch or just force `^zlib` when using this feature.

2025-05-08 05:33 UTC, closed without merging