dla-future: Adapt lapack/scalapack CMake variables for master branch and next version
LLNL/spack pull request #46570
Opened 2024-09-25 07:56 UTC by msimberg

2024-09-25 08:22 UTC, albestro submitted a review, later dismissed
Just for reference https://github.com/eth-cscs/DLA-Future/pull/1178/files#diff-4ae831b914b16acdcddf955a71fcbf934d89e0cb929ed6acf161fde7f5ff41db

2024-09-25 08:27 UTC, albestro commented on var/spack/repos/builtin/packages/dla-future/package.py
> +            add_dlaf_prefix = lambda x: x if spec.version <= Version("0.6") else "DLAF_" + x
just a more spack-pythonic way of saying the same thing.

```suggestion
            add_dlaf_prefix = lambda x: x if spec.satisfies(":0.6") else "DLAF_" + x
```

2024-09-25 08:54 UTC, albestro approved these changes

2024-09-25 08:56 UTC, albestro approved these changes

2024-09-25 09:09 UTC, rasolca approved these changes

2024-09-26 06:20 UTC, albestro requested changes

2024-09-26 06:20 UTC, albestro commented on var/spack/repos/builtin/packages/dla-future/package.py
> +            add_dlaf_prefix = lambda x: x if spec.satisfies(":0.6") else "DLAF_" + x
```suggestion
            add_dlaf_prefix = lambda x: x if spec.satisfies("@:0.6") else "DLAF_" + x
```

2024-09-26 07:09 UTC, albestro approved these changes

2024-09-26 07:33 UTC, merged