MSVC: Restore amalgamated compiler functionality
LLNL/spack pull request #46678
Opened 2024-09-30 23:20 UTC by johnwparent

At some point the compiler refactors broke the ability of MSVC to detect OneAPI as part of its amalgamated compiler modeling. This PR attempts to restore that.

2024-10-24 17:37 UTC, johnwparent commented
@spackbot fix style

2025-02-06 12:42 UTC, alalazo commented
@johnwparent Do you think it's worth to try this directly in #45189 ?

2025-02-06 18:39 UTC, johnwparent commented
> @johnwparent Do you think it's worth to try this directly in #45189 ?

Your compilers as nodes work will allow the utilization of multiple compilers in a DAG right? I.e. we could concretize to MSVC as the C/CXX provider and OneAPI as the Fortran? If so, then this work should be removed once your PR lands, it's simply a stopgap as we cannot currently detect oneAPI w/ MSVC on Windows (which we need for CI and general use). If that assumption is incorrect, then yes, I think it would be useful to at least test this in #45189

2025-02-06 18:46 UTC, alalazo commented
> Your compilers as nodes work will allow the utilization of multiple compilers in a DAG right? 

Yes, in the case you say `msvc` would be the provider for `c`, and `cxx`, and `intel-oneapi-compilers` the provider for `fortran`.

2025-02-06 18:56 UTC, johnwparent commented
> > Your compilers as nodes work will allow the utilization of multiple compilers in a DAG right?
> 
> Yes, in the case you say `msvc` would be the provider for `c`, and `cxx`, and `intel-oneapi-compilers` the provider for `fortran`.

Thanks, I was fairly sure that was the case but wanted to be sure. In that case this is purely a stop-gap for a bug until your compilers as nodes work is merged as that is the significantly cleaner solution to this problem. I'll annotate everything I do here with a clear indicator it can/should be removed once your work lands (I can also contribute a patch to your PR removing this if that makes things easier for you when the time comes)

2025-02-12 19:06 UTC, johnwparent commented
@spackbot fix style

2025-03-06 21:25 UTC, johnwparent commented
@spackbot fix style

2025-03-11 16:09 UTC, johnwparent commented
@alalazo any resistance to this landing?

2025-03-11 16:25 UTC, alalazo commented
We are kind of close to merge #45189 (next week maybe?) and this is in conflict with it - in the sense that my understanding is we shouldn't detect OneAPI compilers from `msvc`, but from `intel-oneapi-compilers`.

I'll leave the last word to @tgamblin , but can't we try to fix this on top of #45189 ? I'll have to do it anyhow, if this gets merged, unless we want to have a feature on develop for a week, and then regress.

2025-03-11 16:49 UTC, johnwparent commented
> We are kind of close to merge #45189 (next week maybe?) and this is in conflict with it - in the sense that my understanding is we shouldn't detect OneAPI compilers from `msvc`, but from `intel-oneapi-compilers`.
> 
> I'll leave the last word to @tgamblin , but can't we try to fix this on top of #45189 ? I'll have to do it anyhow, if this gets merged, unless we want to have a feature on develop for a week, and then regress.

So this is currently broken in develop, and we have users reporting they're unable to use one-api because of it. We've been hearing compiler as nodes is close for some time, I don't think it's reasonable to leave bugs in develop with no definitive end date, and this is actively hurting Windows adoption. 

To that end, as I understand it, compilers still won't work without C++ compilers right? If that's the case we still need this as we need a way to have msvc + intel fortran (with no C/C++). Currently, despite a valid oneAPI installation existing (and detectable from develop) compiler as nodes is unable to detect it.

> this is in conflict with it 

Does it actually conflict with the PR or just conceptually? If its just conceptually, I'd like this to land and be reverted when we can verify oneapi + msvc works with compiler as nodes in develop.

2025-03-14 00:03 UTC, scheibelp requested changes
I agree with all the functional changes. I'm leaving some requests for changes to the comments, which should match what we discussed earlier.

2025-03-14 00:03 UTC, scheibelp commented on lib/spack/spack/detection/path.py
> +
vestigial whitespace

2025-03-14 00:03 UTC, scheibelp commented on lib/spack/spack/detection/path.py
> +        # checking for all parent paths of our detected binaries will prevent this case
I think it will be clearest to shorten this and start by explaining the intended effect, I think the following achieves that:

"we also want to deprioritize paths if they contain a symlink in any parent (not just the basedir):  e.g. oneapi has "latest/bin", where "latest" is a symlink to 2025.0"

2025-03-14 00:03 UTC, scheibelp commented on var/spack/repos/builtin/packages/msvc/package.py
> +        # then use them to manually populate the MSVC compiler entries
Start with "This depends on oneapi being processed before msvc" then provide further explanation. If possible: shorten.

2025-03-14 00:03 UTC, scheibelp commented on var/spack/repos/builtin/packages/msvc/package.py
> +        # compilers as nodes lands
I think we agreed all the TODOs should reference PR numbers (where possible)

2025-03-14 17:13 UTC, johnwparent commented
@spackbot fix style

2025-03-14 19:54 UTC, scheibelp approved these changes

2025-03-14 20:36 UTC, merged