Update some package homepage URLS
LLNL/spack pull request #46683
Opened 2024-10-01 08:18 UTC by nboelte

Hi,

we used the "homepage" URLS from spack packages in our documentation and our static page generator complained about some of them (like 404 errors) and we fixed them. I thought it might be helpful to upstream those changes.

Best Wishes,
Niklas

2024-10-01 09:00 UTC, dacolombo approved these changes
Modifications to relion's package.py looks good to me

2024-10-01 12:14 UTC, RMeli requested changes

2024-10-01 12:14 UTC, RMeli commented on var/spack/repos/builtin/packages/openbabel/package.py
> +    homepage = "https://openbabel.org/docs/index.html"
```suggestion
    homepage = "https://openbabel.org/index.html"
```
Nice to see the new documentation live. I think the link above is better as `homepage`.

2024-10-01 13:15 UTC, RMeli approved these changes
OpenBabel LGTM, thanks.

2024-10-01 13:30 UTC, snehring approved these changes
pbmpi change is fine

2024-10-02 23:59 UTC, tldahlgren approved these changes
Confirmed all eight homepages exist.

2024-10-03 01:10 UTC, AlexanderRichert-NOAA approved these changes

2024-10-03 01:21 UTC, tldahlgren commented
Clicking `Update branch` to pick up a fix that should resolve the CI problem.

2024-10-03 01:50 UTC, bernhardkaindl approved these changes

2024-10-03 16:34 UTC, bernhardkaindl commented
Some jobs failed, but is apparently still running:
@spackbot re-run pipeline

2024-10-03 18:27 UTC, bernhardkaindl commented
@spackbot re-run pipeline

2024-10-03 18:28 UTC, alecbcs commented
@spackbot run pipeline

2024-10-03 21:00 UTC, merged

2024-10-04 14:16 UTC, bernhardkaindl commented
@spackbot re-run pipeline