Add support for version 1.2.4 of MALT
LLNL/spack pull request #46842
Opened 2024-10-07 13:21 UTC by svalat

Register version `1.2.4` and passed `1.2.3` of `malt` package.

2024-10-07 22:45 UTC, tldahlgren requested changes
Confirmed the new sha256s but not the older ones.  I made suggestions for fixing the older ones.

2024-10-07 22:45 UTC, tldahlgren commented on var/spack/repos/builtin/packages/malt/package.py
>      version("1.2.2", sha256="e19f49ad97bf2deedf0557eb00267f4dcf1c932c494dd07ada07fcdf5421935f")
Cannot confirm this with the new `url`.  The sha256 for this version at that url is now `543cace664203fd9eb6b7d4945c573a3e507a43da105b5dc7ac03c78e9bb1a10`.

2024-10-07 22:45 UTC, tldahlgren commented on var/spack/repos/builtin/packages/malt/package.py
>      version("1.2.1", sha256="0e4c0743561f9fcc04dc83457386167a9851fc9289765f8b4f9390384ae3618a")
The new `url` does not support this version.  One option is to add a `url` argument:

```suggestion
    version(
        "1.2.1",
        sha256="0e4c0743561f9fcc04dc83457386167a9851fc9289765f8b4f9390384ae3618a",
        url="https://github.com/memtt/malt/archive/v1.2.1.tar.gz",
   )
```

2024-10-10 10:02 UTC, bernhardkaindl approved these changes

2024-10-10 10:02 UTC, bernhardkaindl commented on var/spack/repos/builtin/packages/malt/package.py
>      version("1.2.2", sha256="e19f49ad97bf2deedf0557eb00267f4dcf1c932c494dd07ada07fcdf5421935f")
I fixed the checksums, using the checksum you found: I was able to build all versions now.

2024-10-10 11:06 UTC, bernhardkaindl approved these changes
Build results on Ubuntu 22.04.4 LTS after fix of on sha265sum:
```py
bin/spack find --variants malt %clang@15.0.7 malt %clang@14.0.0 malt %gcc@9.5.0 malt %gcc@8.4.0 malt %gcc@13.1.0 malt %gcc@12.3.0 malt %gcc@11.4.0 malt %gcc@10.5.0 malt~nodejs %clang@15.0.7 malt~nodejs %clang@14.0.0 malt~nodejs %gcc@9.5.0 malt~nodejs %gcc@8.4.0 malt~nodejs %gcc@13.1.0 malt~nodejs %gcc@12.3.0 malt~nodejs %gcc@11.4.0 malt~nodejs %gcc@10.5.0
-- linux-ubuntu22.04-skylake / clang@14.0.0 ---------------------
malt@1.2.1~ipo+nodejs~qt build_system=cmake build_type=Release generator=make
malt@1.2.2~ipo+nodejs~qt build_system=cmake build_type=Release generator=make
malt@1.2.3~ipo+nodejs~qt build_system=cmake build_type=Release generator=make
malt@1.2.4~ipo~nodejs build_system=cmake build_type=Release generator=make
malt@1.2.4~ipo+nodejs~qt build_system=cmake build_type=Release generator=make

-- linux-ubuntu22.04-skylake / clang@15.0.7 ---------------------
malt@1.2.1~ipo+nodejs~qt build_system=cmake build_type=Release generator=make
malt@1.2.2~ipo+nodejs~qt build_system=cmake build_type=Release generator=make
malt@1.2.3~ipo+nodejs~qt build_system=cmake build_type=Release generator=make
malt@1.2.4~ipo~nodejs build_system=cmake build_type=Release generator=make
malt@1.2.4~ipo+nodejs~qt build_system=cmake build_type=Release generator=make

-- linux-ubuntu22.04-skylake / gcc@8.4.0 ------------------------
malt@1.2.4~ipo~nodejs build_system=cmake build_type=Release generator=make

-- linux-ubuntu22.04-skylake / gcc@9.5.0 ------------------------
malt@1.2.4~ipo~nodejs build_system=cmake build_type=Release generator=make

-- linux-ubuntu22.04-skylake / gcc@10.5.0 -----------------------
malt@1.2.1~ipo+nodejs~qt build_system=cmake build_type=Release generator=make
malt@1.2.2~ipo+nodejs~qt build_system=cmake build_type=Release generator=make
malt@1.2.3~ipo+nodejs~qt build_system=cmake build_type=Release generator=make
malt@1.2.4~ipo~nodejs build_system=cmake build_type=Release generator=make
malt@1.2.4~ipo+nodejs~qt build_system=cmake build_type=Release generator=make

-- linux-ubuntu22.04-skylake / gcc@11.4.0 -----------------------
malt@1.2.1~ipo+nodejs~qt build_system=cmake build_type=Release generator=make
malt@1.2.2~ipo+nodejs~qt build_system=cmake build_type=Release generator=make
malt@1.2.3~ipo+nodejs~qt build_system=cmake build_type=Release generator=make
malt@1.2.4~ipo~nodejs build_system=cmake build_type=Release generator=make
malt@1.2.4~ipo+nodejs~qt build_system=cmake build_type=Release generator=make

-- linux-ubuntu22.04-skylake / gcc@12.3.0 -----------------------
malt@1.2.1~ipo+nodejs~qt build_system=cmake build_type=Release generator=make
malt@1.2.2~ipo+nodejs~qt build_system=cmake build_type=Release generator=make
malt@1.2.3~ipo+nodejs~qt build_system=cmake build_type=Release generator=make
malt@1.2.4~ipo~nodejs build_system=cmake build_type=Release generator=make
malt@1.2.4~ipo+nodejs~qt build_system=cmake build_type=Release generator=make

-- linux-ubuntu22.04-skylake / gcc@13.1.0 -----------------------
malt@1.2.1~ipo+nodejs~qt build_system=cmake build_type=Release generator=make
malt@1.2.2~ipo+nodejs~qt build_system=cmake build_type=Release generator=make
malt@1.2.3~ipo+nodejs~qt build_system=cmake build_type=Release generator=make
malt@1.2.4~ipo~nodejs build_system=cmake build_type=Release generator=make
malt@1.2.4~ipo+nodejs~qt build_system=cmake build_type=Release generator=make
```
Generated by https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py
```py
build-quality-tools/build_pr_changes.py -k malt -b malt,malt~nodejs -c all -ma
```

2024-10-10 23:16 UTC, tldahlgren approved these changes

2024-10-10 23:16 UTC, merged