Extrae: Add single mpi lib variant
LLNL/spack pull request #46918
Opened 2024-10-11 10:17 UTC by amd-toolchain-support

Extrae normally separates the C and MPI fortran interception libs, but for mixed C/Fortran applications a combined lib is needed.

2024-10-11 23:32 UTC, bernhardkaindl requested changes

2024-10-11 23:32 UTC, bernhardkaindl commented on var/spack/repos/builtin/packages/extrae/package.py
> +        config_args.extend(self.enable_or_disable("single-mpi-lib"))
Doh: There is no variable `config_args`.

`args` is the correct variable. Please test that it works...:
```suggestion
        args.extend(self.enable_or_disable("single-mpi-lib"))
```

2024-10-15 11:19 UTC, amd-toolchain-support commented
That's embarrassing!  @bernhardkaindl my apologies that should not have happened.   Your fix is of course correct and has been confirmed working with gcc 13.3.0 on rocky 9.

2024-10-16 17:22 UTC, bernhardkaindl approved these changes

2024-10-16 17:25 UTC, merged