py-jupyter-server: add v2.14.2
LLNL/spack pull request #46965
Opened 2024-10-14 18:04 UTC by wdconinc

This PR adds `py-jupyter-server`, v2.14.2, which fixes CVE-2023-39968, CVE-2023-40170, CVE-2023-49080 (all of which are medium or less severe). Versions before CVE-2022-29241 (high severity) are marked as deprecated.

Test build:
```
==> Installing py-jupyter-server-2.14.2-ecxgj7jqdvhmw6pnvmmme5ehudrjhalf [118/118]
==> No binary for py-jupyter-server-2.14.2-ecxgj7jqdvhmw6pnvmmme5ehudrjhalf found: installing from source
==> Fetching https://files.pythonhosted.org/packages/source/j/jupyter_server/jupyter_server-2.14.2.tar.gz
==> No patches needed for py-jupyter-server
==> py-jupyter-server: Executing phase: 'install'
==> py-jupyter-server: Successfully installed py-jupyter-server-2.14.2-ecxgj7jqdvhmw6pnvmmme5ehudrjhalf
  Stage: 0.76s.  Install: 1.06s.  Post-install: 1.85s.  Total: 3.93s
[+] /opt/software/linux-ubuntu24.10-skylake/gcc-14.2.0/py-jupyter-server-2.14.2-ecxgj7jqdvhmw6pnvmmme5ehudrjhalf
```

Test run:
```
$ jupyter-server 
[I 2024-10-14 12:57:39.053 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-10-14 12:57:39.068 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-10-14 12:57:39.072 ServerApp] Serving notebooks from local directory: /opt/spack/stage/wdconinc
[I 2024-10-14 12:57:39.072 ServerApp] Jupyter Server 2.14.2 is running at:
[I 2024-10-14 12:57:39.072 ServerApp] http://localhost:8888/?token=XX
[I 2024-10-14 12:57:39.073 ServerApp]     http://127.0.0.1:8888/?token=XX
[I 2024-10-14 12:57:39.073 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-10-14 12:57:39.075 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/wdconinc/.local/share/jupyter/runtime/jpserver-714884-open.html
```

2024-10-14 18:17 UTC, wdconinc commented
@spackbot fix style

2024-10-15 04:32 UTC, bernhardkaindl requested changes
pythonhosted currently does not appear (to my hosts in Europe) provide the redirect URL https://files.pythonhosted.org/packages/source/w/websocket-client/websocket-client-1.8.0.tar.gz (wget gets: 404 Not Found):

Instead, it only hosts the file at its actual download location that  
https://pypi.org/project/websocket-client/1.8.0/#files links to:

https://files.pythonhosted.org/packages/e6/30/fba0d96b4b5fbf5948ed3f4681f7da2f9f64512e1d303f94b4cc174c24a5/websocket_client-1.8.0.tar.gz

I don't know what's best, maybe have a look on what you get.
Should this package switch to github or provide this file with the actual file path as url?

2024-10-15 04:35 UTC, wdconinc commented
Seems to have gotten renamed again... https://files.pythonhosted.org/packages/source/w/websocket-client/websocket_client-1.8.0.tar.gz with underscore works again.

2024-10-15 12:32 UTC, wdconinc commented
> Seems to have gotten renamed again... https://files.pythonhosted.org/packages/source/w/websocket-client/websocket_client-1.8.0.tar.gz with underscore works again.

Ensured the underscored url works again:
```
07:10:57 wdconinc@menelaos ~/git/spack (develop *$%>) $ spack checksum --batch --verify py-websocket-client 1.8.0
==> Found 1 version of py-websocket-client
==> Fetching https://files.pythonhosted.org/packages/source/w/websocket_client/websocket_client-1.8.0.tar.gz
==> Verified 1 of 1
  
  1.8.0  [=] Correct
  
07:28:19 wdconinc@menelaos ~/git/spack (develop *$%>) $ spack checksum --batch --verify py-websocket-client 0.57.0
==> Found 1 version of py-websocket-client
==> Fetching https://files.pythonhosted.org/packages/source/w/websocket_client/websocket_client-0.57.0.tar.gz
==> Verified 1 of 1
  
  0.57.0  [=] Correct
  
07:28:23 wdconinc@menelaos ~/git/spack (develop *$%>) $ spack checksum --batch --verify py-websocket-client 1.7.0
==> Found 1 version of py-websocket-client
==> Fetching https://files.pythonhosted.org/packages/source/w/websocket-client/websocket-client-1.7.0.tar.gz
==> Verified 1 of 1
  
  1.7.0  [=] Correct
  
```

(Note: This worked locally without this change since I have https://github.com/spack/spack/pull/45668 in my local copy.)

2024-10-15 15:16 UTC, bernhardkaindl approved these changes
Build results on Ubuntu 22.04.4 LTS:
```py
bin/spack find --variants py-websocket-client@1.7.0 | sed 's/~[a-z]*//g;s/ [a-z0-9_]*=[a-zA-Z0-9]*//g'  # Short variants: Hide disabled and value variants
-- linux-ubuntu22.04-skylake / gcc@13.1.0 -----------------------
py-websocket-client@1.7.0
```

Generated by https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py
```py
~/build-quality-tools/build_pr_changes.py -b py-websocket-client@1.7.0 -may
```

2024-10-15 15:16 UTC, merged