vtk-m: Add sycl option to vtk-m package
LLNL/spack pull request #46996
Opened 2024-10-15 18:27 UTC by kmorel

2024-10-15 18:32 UTC, vicentebolea requested changes

2024-10-15 18:32 UTC, vicentebolea commented on var/spack/repos/builtin/packages/vtk-m/package.py
> +    patch("mr3272-bad-mir-table-method.patch")
```suggestion
    patch("mr3272-bad-mir-table-method.patch", when="@2:")
```

2024-10-15 18:49 UTC, kmorel commented on var/spack/repos/builtin/packages/vtk-m/package.py
> +    patch("mr3272-bad-mir-table-method.patch")
Good catch. I pushed a fix.

2024-10-15 19:30 UTC, vicentebolea approved these changes
Looks good! Thanks

2024-10-16 15:15 UTC, kmorel commented
Thanks, @vicentebolea.

It looks like I still missing an approving review. Do you know how I can get that? This is my first actual spack submission.

2024-10-16 16:01 UTC, bernhardkaindl requested changes
Edit: @kmorel Thank you very much for the explanation, and I'm sorry that I tried incorrect specs!

2024-10-16 17:04 UTC, kmorel commented
@bernhardkaindl Can you explain to a newbie where these specs are defined? Neither is a valid spec for the vtk-m package (nor were either valid before these changes). There is no way these passed any former version of the vtk-m package, and I have not asked for a spec of this nature anywhere.

2024-10-18 03:31 UTC, bernhardkaindl approved these changes
As the maintainer @vicentebolea approved, I'm ready to approve too.

2024-10-18 11:42 UTC, kmorel commented
Thanks for the help, @bernhardkaindl.

One hopefully finally question: What is left to merge in these changes. It looks like the merge is now waiting on some checks. Some are skilled and one says it is disabled for draft PRs. But, this PR is not marked as draft and I don't think I have permissions to launch any CI myself.

2024-10-18 12:43 UTC, bernhardkaindl commented
@spackbot run pipeline

2024-10-18 13:25 UTC, merged

2024-10-18 13:29 UTC, kmorel commented
Awesome! Thanks.