hicup: new package @0.9.2
LLNL/spack pull request #47008
Opened 2024-10-16 08:44 UTC by A-N-Other

Adding the `hicup` package with versions for the last two major releases and a option for the popular `combinations` git branch. Installed and tested on a `linux-rocky8-icelake` system.

2024-10-17 01:57 UTC, bernhardkaindl requested changes
Build results on Ubuntu 22.04.4 LTS:
6 failed specs:
- `hicup@0.9.2`
- `hicup@0.8.3`
- `hicup@combinations`
- `hicup~bowtie2+bowtie@0.9.2`
- `hicup~bowtie2+bowtie@0.8.3`
- `hicup~bowtie2+bowtie@combinations`
### `hicup@0.9.2`:
```py
     226    -------------------------- [ERROR MESSAGE] ---------------------------
  >> 227    <stdin>:1:10: fatal error: hb-ft.h: No such file or directory
     228    compilation terminated.
     229    --------------------------------------------------------------------
     230    ERROR: configuration failed for package 'textshaping'
     231    * removing 'opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-textshaping-0.3.6-fkvk35twytvz4jar373zdel2dfrsqvqp/rlib/R/library/textshaping'


```
Build log:
```py
==> r-textshaping: Executing phase: 'install'
==> [2024-10-17-01:57:23.669526] 'opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/bin/R' '--vanilla' 'CMD' 'INSTALL' '--library=opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-textshaping-0.3.6-fkvk35twytvz4jar373zdel2dfrsqvqp/rlib/R/library' '.stage/spack-stage-r-textshaping-0.3.6-fkvk35twytvz4jar373zdel2dfrsqvqp/spack-src'
** package 'textshaping' successfully unpacked and MD5 sums checked
** using staged installation
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf.spack:195: warning: overriding recipe for target '.c.o'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf:195: warning: ignoring old recipe for target '.c.o'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf.spack:197: warning: overriding recipe for target '.c.d'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf:197: warning: ignoring old recipe for target '.c.d'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf.spack:200: warning: overriding recipe for target '.m.d'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf:200: warning: ignoring old recipe for target '.m.d'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf.spack:202: warning: overriding recipe for target '.cc.o'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf:202: warning: ignoring old recipe for target '.cc.o'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf.spack:204: warning: overriding recipe for target '.cpp.o'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf:204: warning: ignoring old recipe for target '.cpp.o'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf.spack:206: warning: overriding recipe for target '.cc.d'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf:206: warning: ignoring old recipe for target '.cc.d'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf.spack:209: warning: overriding recipe for target '.cpp.d'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf:209: warning: ignoring old recipe for target '.cpp.d'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf.spack:212: warning: overriding recipe for target '.m.o'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf:212: warning: ignoring old recipe for target '.m.o'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf.spack:214: warning: overriding recipe for target '.mm.o'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf:214: warning: ignoring old recipe for target '.mm.o'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf.spack:216: warning: overriding recipe for target '.M.o'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf:216: warning: ignoring old recipe for target '.M.o'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf.spack:218: warning: overriding recipe for target '.f.o'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf:218: warning: ignoring old recipe for target '.f.o'
...

```
### `hicup@0.8.3`:
```py
     226    -------------------------- [ERROR MESSAGE] ---------------------------
  >> 227    <stdin>:1:10: fatal error: hb-ft.h: No such file or directory
     228    compilation terminated.
     229    --------------------------------------------------------------------
     230    ERROR: configuration failed for package 'textshaping'
     231    * removing 'opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-textshaping-0.3.6-fkvk35twytvz4jar373zdel2dfrsqvqp/rlib/R/library/textshaping'


```
Build log:
```py
==> r-textshaping: Executing phase: 'install'
==> [2024-10-17-01:57:23.669526] 'opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/bin/R' '--vanilla' 'CMD' 'INSTALL' '--library=opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-textshaping-0.3.6-fkvk35twytvz4jar373zdel2dfrsqvqp/rlib/R/library' '.stage/spack-stage-r-textshaping-0.3.6-fkvk35twytvz4jar373zdel2dfrsqvqp/spack-src'
** package 'textshaping' successfully unpacked and MD5 sums checked
** using staged installation
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf.spack:195: warning: overriding recipe for target '.c.o'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf:195: warning: ignoring old recipe for target '.c.o'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf.spack:197: warning: overriding recipe for target '.c.d'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf:197: warning: ignoring old recipe for target '.c.d'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf.spack:200: warning: overriding recipe for target '.m.d'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf:200: warning: ignoring old recipe for target '.m.d'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf.spack:202: warning: overriding recipe for target '.cc.o'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf:202: warning: ignoring old recipe for target '.cc.o'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf.spack:204: warning: overriding recipe for target '.cpp.o'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf:204: warning: ignoring old recipe for target '.cpp.o'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf.spack:206: warning: overriding recipe for target '.cc.d'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf:206: warning: ignoring old recipe for target '.cc.d'
opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/r-4.4.1-otahdl3wjn5ab6edwznxc6kydp22oabd/rlib/R/etc/Makeconf.spack:209: warning: overriding recipe for t [...]

2024-10-18 08:25 UTC, A-N-Other commented
@bernhardkaindl These install issues are with the `r-textshaping` dependency rather than with `hicup` per se. The `r-textshaping` GitHub suggests this issue ([here](https://github.com/r-lib/textshaping/issues/41) and [here](https://github.com/r-lib/textshaping/issues/21)) occurs when the `harfbuzz` and `fribidi` dependencies aren't installed, which the Spack package does include as the default `("build", "link")` types. All three package versions install fine for me on `rocky8` and we're a Ubuntu-free zone, so I can't really debug this.

2024-10-19 00:13 UTC, bernhardkaindl approved these changes
@A-N-Other, thanks for your analysis, it has led me on the path to resolve the issue!

I'll open a new PR for fixing the issues that occurred during the build test that I made.

You would run into those issues as well even on Rocky 8 if the host does not have `pkgconfig` installed and a second issue will occur if your build uses the new `freetype@2.13.3`. We already reverted the preferred version of `freetype` back to `freetype@2.13.2` because of the change in the external API with `2.13.3` in preparation for the release of `spack-0.23`, so that second issue would only occur on a fresh build from scratch on this current revision of this PR's base commit, not in the latest develop after this PR is merged. But, nonetheless, if/when we re-enable the preference of `freetype@2.13.3` after the release of `spack-0.23`, the build of `hicup` would on the future post-spack-0.23 develop branch would be affected by these dependency errors.

For the reasons that these issues will appar on any Linux given those conditions are present, I'll submit my fixes in a new PR.

Build results on Ubuntu 22.04.4 LTS (with these fixed as a base):
The following specs were checked (extracted from `gh pr diff`):
- `hicup@0.9.2`
- `hicup@0.8.3`
- `hicup@combinations`
- `hicup~bowtie2+bowtie@0.9.2`
- `hicup~bowtie2+bowtie@0.8.3`
- `hicup~bowtie2+bowtie@combinations`

These specs were installed (`~disabled` variants are hidden):
```py
bin/spack find --variants hicup@0.9.2 hicup@0.8.3 hicup@combinations hicup~bowtie2+bowtie@0.9.2 hicup~bowtie2+bowtie@0.8.3 hicup~bowtie2+bowtie@combinations | sed 's/~[a-z]*//g;s/ [a-z0-9_]*=[a-zA-Z0-9]*//g'
-- linux-ubuntu22.04-skylake / gcc@13.1.0 -----------------------
hicup@combinations+bowtie2 build_system=generic
hicup@combinations+bowtie build_system=generic
hicup@0.8.3+bowtie2 build_system=generic
hicup@0.8.3+bowtie build_system=generic
hicup@0.9.2+bowtie2 build_system=generic
hicup@0.9.2+bowtie build_system=generic
```
Generated by https://github.com/spack/build-quality-tools/blob/main/build_pr_changes.py
```py
~/build-quality-tools/build_pr_changes.py
```

2024-10-19 00:24 UTC, bernhardkaindl commented
@spackbot run pipeline

2024-10-19 00:53 UTC, merged

2024-10-19 01:21 UTC, bernhardkaindl commented
@A-N-Other:

JFYI: The PR #47091 is the new PR about fixing the build of the dependencies regarding pkgconfig and the handling of the new `freetype` version (now no longer the default for `spack-0.23`).