cbtf-argonavis-gui: Update Boost dependency
LLNL/spack pull request #47134
Opened 2024-10-22 13:28 UTC by hainest

2024-10-22 21:21 UTC, tldahlgren approved these changes

2024-10-22 21:21 UTC, tldahlgren commented
@jgalarowicz What are your thoughts on this change?

2024-10-24 06:40 UTC, bernhardkaindl requested changes
@hainest: This recipe (independent of the PR branch or checkout) never concretize for me - what's needed to concretize it?
```py
git clone -b thaines/cbtf_argonavis_gui_boost https://github.com/hainest/spack ~/spack.cbtf-argonavis-gui
Cloning into '~/spack.cbtf-argonavis-gui'...
remote: Enumerating objects: 567925, done.
remote: Total 567925 (delta 0), reused 0 (delta 0), pack-reused 567925 (from 1)
Receiving objects: 100% (567925/567925), 190.12 MiB | 24.47 MiB/s, done.
Resolving deltas: 100% (265823/265823), done.
$ cd ~/spack.cbtf-argonavis-gui/
~/spack.cbtf-argonavis-gui$ bin/spack spec cbtf-argonavis-gui
==> Error: failed to concretize `cbtf-argonavis-gui` for the following reasons:
     1. Cannot select a single "version" for package "cbtf-argonavis-gui"
```

2025-02-08 18:51 UTC, hainest commented
> @hainest: This recipe (independent of the PR branch or checkout) never concretize for me - what's needed to concretize it?
> 
> ```python
> git clone -b thaines/cbtf_argonavis_gui_boost https://github.com/hainest/spack ~/spack.cbtf-argonavis-gui
> Cloning into '~/spack.cbtf-argonavis-gui'...
> remote: Enumerating objects: 567925, done.
> remote: Total 567925 (delta 0), reused 0 (delta 0), pack-reused 567925 (from 1)
> Receiving objects: 100% (567925/567925), 190.12 MiB | 24.47 MiB/s, done.
> Resolving deltas: 100% (265823/265823), done.
> $ cd ~/spack.cbtf-argonavis-gui/
> ~/spack.cbtf-argonavis-gui$ bin/spack spec cbtf-argonavis-gui
> ==> Error: failed to concretize `cbtf-argonavis-gui` for the following reasons:
>      1. Cannot select a single "version" for package "cbtf-argonavis-gui"
> ```

It seems this package is broken from a dependency. I don't have the cycles to debug, so I'm abandoning these changes.

2025-02-08 18:51 UTC, closed without merging