Introduce support for ArmPL and ACfL 24.10
LLNL/spack pull request #47167
Opened 2024-10-23 11:44 UTC by paolotricerri

This patch introduces the possibility of installing armpl-gcc and acfl 24.10 through spack. It also addressed one issue observed after PR https://github.com/spack/spack/pull/46594

CC: @dslarm 

@spackbot fix style

2024-10-23 13:34 UTC, paolotricerri commented
Dear @alalazo and @tldahlgren,

 as you have probably seen some jobs fails but I am struggling to understand how to fix them. Would you be able to advice me on how to fix them? Is it related to the `version` calls I have at the top of my ACfL class package declaration?

Thanks

![Screenshot from 2024-10-23 14-32-30](https://github.com/user-attachments/assets/916c458e-0738-4d7a-9cd0-5b36514addab)

2024-10-24 07:39 UTC, paolotricerri commented
I have tried to reproduce the problem on a macos system (as the failed job seems to suggest that to me) but couldn't due to an error with openmpi-5.0.5

2024-10-29 19:43 UTC, tldahlgren commented
> I am wondering if it related to the changes in `get_os` function and with the new default OS returned being `Unknown-OS` which returns an empty package and so nothing gets added with the called to `version`. Do you think it could make sense?

Using `Unknown-OS` (with no corresponding handling) certainly isn't going to help.

2024-10-29 19:46 UTC, tldahlgren commented on var/spack/repos/builtin/packages/armpl-gcc/package.py
> +        "rpm": ("055d4b3c63d990942d453a8720d029be7e604646218ffc3262321683f51f23aa"),
Confirmed this version sha256.

2024-10-29 19:48 UTC, tldahlgren commented on var/spack/repos/builtin/packages/armpl-gcc/package.py
> +        "rpm": ("055d4b3c63d990942d453a8720d029be7e604646218ffc3262321683f51f23aa"),
And that the 24.04 rpm sha256 still works.

2024-10-29 20:00 UTC, tldahlgren commented on var/spack/repos/builtin/packages/acfl/package.py
> +            "defe9b8bd31d28aba1c8b8026295b6e277f221d1e387b16d8d86f4dea9b75c27",
I can confirm this sha256 though I'm running on a `rhel8` machine.

2024-10-29 21:17 UTC, tldahlgren requested changes

2024-10-29 21:17 UTC, tldahlgren commented on var/spack/repos/builtin/packages/acfl/package.py
> +    url = "https://developer.arm.com/-/cdn-downloads/permalink/Arm-Compiler-for-Linux/Version_24.10/arm-compiler-for-linux_24.10_Ubuntu-20.04_aarch64.tar"
Remove this property.  The version directives already contain their own `url` arguments.  Haven't investigated but when I commented it out I was able to get the correct (OS-specific) URL using `spack checksum`.

2024-10-29 21:17 UTC, tldahlgren commented on var/spack/repos/builtin/packages/acfl/package.py
> +            "7c685c5393345baff573dc53ea3bb84e6293f9e51808e168ececcf51efb45813",
Confirmed this one *after* commenting out the `url` property.

2024-10-31 21:50 UTC, tldahlgren approved these changes

2024-10-31 21:51 UTC, merged