packages: new versions (`diamond`, `py-alive-progress`, `py-bakta`, `py-deepsig-biocomp`), new packages (`py-pyhmmer`, `py-pyrodigal`))
LLNL/spack pull request #47277
Opened 2024-10-28 22:26 UTC by luke-dt

confirm that `py-bakta` v1.9.4 builds and runs correctly on my machine

2024-10-29 22:10 UTC, snehring approved these changes
diamond change is fine.

py-bakta seems to build without issue

2024-10-30 08:27 UTC, bendamasio reviewed
Hello @oschwengers and @snehring, I generated some build results:<br>
:information_source: `spack install` on the changed recipes of this PR was not successful[^1] on Ubuntu 22.04.4 LTS!<details><summary>Click here for a summary of the not successful builds.</summary>
These changed specs were found using [gh pr diff](https://cli.github.com):
- `diamond@2.1.10`
- `py-alive-progress@3.2.0`
- `py-bakta@1.9.4`
- `py-pyhmmer@0.10.15`
- `py-pyhmmer@0.10.14`
- `py-pyrodigal@3.5.2`
- `diamond@2.1.10`
- `diamond@2.1.9`
- `diamond@2.1.8`


<details><summary><b>Click here to show/hide the report on </b><tt>spack find</tt> for <tt>linux-ubuntu22.04-skylake / gcc@13.1.0</tt>.</summary><ol>

<li><details><summary>Click on this area to unfold/refold the dependency report of this build:

>```py
>diamond@2.1.8+blast~eigen~ipo+zstd build_system=cmake build_type=Release generator=make
>```
</summary>

>```py
>	blast-plus@2.16.0bzip2freetypegnutlsjpeglzoopensslpcreperlpngpython
>		bzip2@1.0.8
>			diffutils@3.10
>		cpio@2.15
>		freetype@2.13.2
>			pkgconf@2.2.0
>		gnutls@3.8.3brotli
>			brotli@1.1.0
>			gettext@0.22.5bzip2cursesgit
>				libxml2@2.10.3
>				tar@1.34 zip=pigz
>					pigz@2.8
>			libidn2@2.3.7
>				libunistring@1.2
>					libiconv@1.17
>			nettle@3.9.1
>				gmp@6.3.0cxx
>					autoconf@2.72
>						perl@5.40.0cpanmopcodeopenthreads
>							berkeley-db@18.1.40cxx,b231fcc
>							bzip2@1.0.8
>							gdbm@1.23
>								readline@8.2
>					automake@1.16.5
>					libtool@2.4.7
>						findutils@4.9.0
>				m4@1.4.19sigsegv,bfdffa7
>					diffutils@3.10
>					libsigsegv@2.14
>			pkgconf@2.2.0
>		libjpeg-turbo@3.0.3_decoder
>			cmake@3.30.2
>				curl@8.8.0 tls=openssl
>					nghttp2@1.63.0
>					openssl@3.3.1 certs=mozilla
>						ca-certificates-mozilla@2023-05-30
>				ncurses@6.5
>				zlib-ng@2.2.1compatnew_strategiesopt
>			gmake@4.4.1
>			nasm@2.16.03
>		libpng@1.6.39
>		lmdb@0.9.31
>		lzo@2.10
>		openssl@3.3.1 certs=mozilla
>			ca-certificates-mozilla@2023-05-30
>		pcre@8.45
>		perl@5.40.0cpanmopcodeopenthreads
>			berkeley-db@18.1.40cxx,b231fcc
>			gdbm@1.23
>		python@3.11.9bz2cryptctypesdbm,b0615b2,ebdca64,f2fd060
>			expat@2.6.3libbsd
>				libbsd@0.12.2
>					libmd@1.0.4
>			libffi@3.4.6
>			libxcrypt@4.4.35_api
>			readline@8.2
>			sqlite@3.46.0column_metadatadynamic_extensionsfts
>			util-linux-uuid@2.40.2
>			xz@5.4.6
>	cmake@3.30.5
>		curl@8.10.1 tls=openssl
>			nghttp2@1.63.0
>		ncurses@6.5
>	gcc-runtime@13.1.0
>	glibc@2.35
>	gmake@4.4.1
>	zlib-ng@2.2.1compat_strategiesopt
>	zstd@1.5.6programs
>
>```

</details>


<li><details><summary>Click on this area to unfold/refold the dependency report of this build:

>```py
>diamond@2.1.9+blast~eigen~ipo+zstd build_system=cmake build_type=Release generator=make
>```
</summary>

>```py
>	blast-plus@2.16.0bzip2freetypegnutlsjpeglzoopensslpcreperlpngpython
>		bzip2@1.0.8
>			diffutils@3.10
>		cpio@2.15
>		freetype@2.13.2
>			pkgconf@2.2.0
>		gnutls@3.8.3brotli
>			brotli@1.1.0
>			gettext@0.22.5bzip2cursesgit
>				libxml2@2.10.3
>				tar@1.34 zip=pigz
>					pigz@2.8
>			libidn2@2.3.7
>				libunistring@1.2
>					libiconv@1.17
>			nettle@3.9.1
>				gmp@6.3.0cxx
>					autoconf@2.72
>						perl@5.40.0cpanmopcodeopenthreads
>							berkeley-db@18.1.40cxx,b231fcc
>							bzip2@1.0.8
>							gdbm@1.23
>								readline@8.2
>					automake@1.16.5
>					libtool@2.4.7
>						findutils@4.9.0
>				m4@1.4.19sigsegv,bfdffa7
>					diffutils@3.10
>					libsigsegv@2.14
>			pkgconf@2.2.0
>		libjpeg-turbo@3.0.3_decoder
>			cmake@3.30.2
>				curl@8.8.0 tls=openssl
>					nghttp2@1.63.0
>					openssl@3.3.1 certs=mozilla
>						ca-certificates-mozilla@2023-05-30
>				ncurses@6.5
>				zlib-ng@2.2.1compatnew_strategiesopt
>			gmake@4.4.1
>			nasm@2.16.03
>		libpng@1.6.39
>		lmdb@0.9.31
>		lzo@2.10
>		openssl@3.3.1 certs=mozilla
>			ca-certificates-mozilla@2023-05-30
>		pcre@8.45
>		perl@5.40.0cpanmopcodeopenthreads
>			berkeley-db@18.1.40cxx,b231fcc
>			gdbm@1.23
>		python@3.11.9bz2cryptctypesdbm,b0615b2,ebdca64,f2fd060
>			expat@2.6.3libbsd
>				libbsd@0.12.2
>					libmd@1.0.4
>			libffi@3.4.6
>			libxcrypt@4.4.35_api
>			readline@8.2
>			sqlite@3.46.0column_metadatadynamic_extensionsfts
>			util-linux-uuid@2.40.2
>			xz@5.4.6
>	cmake@3.30.5
>		curl@8.10.1 tls=openssl
>			nghttp2@1.63.0
>		ncurses@6.5
>	gcc-runtime@13.1.0
>	glibc@2.35
>	gmake@4.4.1
>	zlib-ng@2.2.1compat_strategiesopt
>	zstd@1.5.6programs
>
>```

</details>


<li><details><summary>Click on this area to unfold/refold the dependency report of this build:

>```py
>diamond@2.1.10+blast~eigen~ipo+zstd build_system=cmake build_type=Release generator=make
>```
</summary>

>```py
>	blast-plus@2.16.0bzip2freetypegnutlsjpeglzoopensslpcreperlpngpython
>		bzip2@1.0.8
>			diffutils@3.10
>				libiconv@1.17
>		cpio@2.15
>			gmake@4.4.1
>		freetype@2.13.3
>			pkgconf@2.2.0
>		gnutls@3.8.3brotli
>			brotli@1.1.0
>				cmake@3.30.5
>					curl@8.10.1 tls=openssl
>						nghttp2@1.63.0
>							diffutils@3.10
>						openssl@3.3.1 certs=mozilla
>							ca-certificates-mozilla@2023-05-30
>							perl@5.40.0cpanmopcodeopenthreads
>								berkeley-db@18.1.40cxx,b231fcc
>								bzip2@1.0.8
>								gdbm@1.23
>									readline@8.2
>						pkgconf@2.2.0
>					ncurses@6.5
>					zlib-ng@2.2.1compat_strategiesopt
>			gettext@0.22.5bzip2cursesgit
>				libxml2@2.10.3
>				tar@1.34 zip=pigz
>					pigz@2.8
>			libidn2@2.3.7
>				libunistring@1.2
>			nettle@3.9.1
>				gmp@6.3.0cxx
>					autoconf@2.72
>					automake@1.16.5
>					libtool@2.4.7
>						findutils@4.9.0
>				m4@1.4.19sigsegv,bfdffa7
>					libsigsegv@2.14
>		libjpeg-turbo@3.0.3_decoder
>			nasm@2.16.03
>		libpng@1.6.39
>		lmdb@0.9.31
>		lzo@2.10
>		openssl@3.3.1 certs=mozilla
>			ca-certificates-mozilla@2023-05-30
>		pcre@8.45
>		perl@5.40.0cpanmopcodeopenthreads
>			berkeley-db@18.1.40cxx,b231fcc
>			gdbm@1.23
>		python@3.10.14bz2cryptctypesdbm,7d40923,ebdca64,f2fd060
>			expat@2.6.3libbsd
>				libbsd@0.12.2
>					libmd@1.0.4
>			libffi@3.4.6
>			libxcrypt@4.4.35_api
>			readline@8.2
>			sqlite@3.46.0column_metadatadynamic_extensionsfts
>			util-linux-uuid@2.40.2
>			xz@5.4.6
>	cmake@3.30.2
>		curl@8.8.0 tls=openssl
>			nghttp2@1.63.0
>		ncurses@6.5
>	gcc-runtime@13.1.0
>	glibc@2.35
>	gmake@4.4.1
>	zlib-ng@2.2.1compatnew_strategiesopt
>	zstd@1.5.6programs
>
>```

</details>


<li><details><summary>Click on this area to unfold/refold the dependency report of this build:

>```py
>diamond@2.1.10+blast~eigen~ipo+zstd build_system=cmake build_type=Release generator=make
>```
</summary>

>```py
>	blast-plus@2.16.0bzip2freetypegnutlsjpeglzoopensslpcreperlpngpython
>		bzip2@1.0.8
>			diffutils@3.10
>		cpio@2.15
>		freetype@2.13.2
>			pkgconf@2.2.0
>		gnutls@3.8.3brotli
>			brotli@1.1.0
>			gettext@0.22.5bzip2cursesgit
>				libxml2@2.10.3
>				tar@1.34 zip=pigz
>					pigz@2.8
>			libidn2@2.3.7
>				libunistring@1.2
>					libiconv@1.17
>			nettle@3.9.1
>				gmp@6.3.0cxx
>					autoconf@2.72
>						perl@5.40.0cpanmopcodeopenthreads
>							berkeley-db@18.1.40cxx,b231fcc
>							bzip2@1.0.8
>							gdbm@1.23
>								readline@8.2
>					automake@1.16.5
>					libtool@2.4.7
>						findutils@4.9.0
>				m4@1.4.19sigsegv,bfdffa7
>					diffutils@3.10
>					libsigsegv@2.14
>			pkgconf@2.2.0
>		libjpeg-turbo@3.0.3_decoder
>			cmake@3.30.2
>				curl@8.8.0 tls=openssl
>					nghttp2@1.63.0
>					openssl@3.3.1 certs=mozilla
>						ca-certificates-mozilla@2023-05-30
>				ncurses@6.5
>				zlib-ng@2.2.1compatnew_strategiesopt
>			gmake@4.4.1
>			nasm@2.16.03
>		libpng@1.6.39
>		lmdb@0.9.31
>		lzo@2.10
>		openssl@3.3.1 certs=mozilla
>			ca-certificates-mozilla@2023-05-30
>		pcre@8.45
>		perl@5.40.0cpanmopcodeopenthreads
>			berkeley-db@18.1.40cxx,b231fcc
>			gdbm@1.23
>		python@3.11.9bz2cryptctypesdbm,b0615b2,ebdca64,f2fd060
>			expat@2.6.3libbsd
>				libbsd@0.12.2
>					libmd@1.0.4
>			libffi@3.4.6
>			libxcrypt@4.4.35_api
>			readline@8.2
>			sqlite@3.46.0column_metadatadynamic_extensionsfts
>			util-linux-uuid@2.40.2
>			xz@5.4.6
>	cmake@3.30.5
>		curl@8.10.1 tls=openssl
>			nghttp [...]

2024-11-04 20:11 UTC, tldahlgren reviewed
Confirmed all new sha256s and the homepages of the two new packages.

2024-11-04 22:24 UTC, tldahlgren requested changes
I am bothered by the inconsistencies between different requirements of different files for several of the packages(noted here) *but* the most important issue is likely what appears to be a missing dependency.

Thoughts?

2024-11-04 22:24 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-bakta/package.py
> +    depends_on("trnascan-se@2.0.8:", when="@:1.5.1", type=("build", "run"))
FYI. v2.0.8 is still listed in `PKG-INFO`  despite `bakta/utils.py` showing 2.0.11 as the minimum.

2024-11-04 22:24 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-bakta/package.py
> +    depends_on("py-pyhmmer@0.10.0:", when="@1.8.2:1.9.3", type=("build", "run"))
FYI. v0.10.0 is still listed in `PKG-INFO` though `bakta/utils.py` shows 0.10.4.

2024-11-04 22:24 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-bakta/package.py
> +    depends_on("diamond@2.0.14:", when="@:1.8.2", type=("build", "run"))
FYI. v2.0.14 is still listed in `PKG-INFO` though you have the correct minimum based on `bakta/utils.py`.

2024-11-04 22:24 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-bakta/package.py
>      depends_on("infernal@1.1.4:", type=("build", "run"))
Is there a missing dependency on `cmscan` (though the package would need to be added)?  See `bakta/utils.py`:

```
DEPENDENCY_CMSCAN = (Version(1, 1, 4), Version(VERSION_MAX_DIGIT, VERSION_MAX_DIGIT, VERSION_MAX_DIGIT), VERSION_REGEX, 'CMscan', ('cmscan', '-h'), ['--skip-rrna', '--skip-ncrna', '--skip-ncrna-region'])
```

2024-11-04 22:24 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-bakta/package.py
> +    depends_on("blast-plus@2.12.0:", when="@:1.8.2", type=("build", "run"))
Interesting.  `PKG-INFO` says v2.12.0 applies *but* `bakta/utils.py` lists:

```
DEPENDENCY_BLASTN = (Version(2, 14, 0), Version(VERSION_MAX_DIGIT, VERSION_MAX_DIGIT, VERSION_MAX_DIGIT), VERSION_REGEX, 'Blastn', ('blastn', '-version'), ['--skip-ori'])
```

2024-11-04 22:24 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-bakta/package.py
> +    depends_on("amrfinder@3.10.23:", when="@1.5.1", type=("build", "run"))
FYI. v3.10.3 is still listed in `PKG-INFO` though `bakta/utils.py` shows the minimum version specified here.

2024-11-04 22:24 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-pyrodigal/package.py
> +    depends_on("py-cython@3.0:", type=("build", "run"))
Should this be `py-cython@3.0` given `pyproject.toml`'s `~=3.0`?

2024-11-04 22:24 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-pyrodigal/package.py
> +    depends_on("py-archspec@0.2.0:", type="build")
FYI. This does not appear in `pyproject.toml` but is `~=0.2.0` in `requires.txt`.

2024-11-04 22:24 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-deepsig-biocomp/package.py
> +    depends_on("py-tensorflow@2.2.0:", type=("build", "run"))
Is use of the `:` in these three packages are not consistent with `requirements.txt`'s:

```
biopython==1.78
Keras==2.4.3
tensorflow==2.2.0
```

Yet, `setup.py` supports lines 24 and 25 but no constraint on line 26:

```
    install_requires=[
        'biopython >= 1.78',
        'Keras >= 2.4.3',
        'tensorflow'
    ],
```

2024-11-07 15:10 UTC, luke-dt commented on var/spack/repos/builtin/packages/py-bakta/package.py
>      depends_on("infernal@1.1.4:", type=("build", "run"))
I don't know why the dependency is written this way, but `cmscan` is a [program that is part of `infernal`](https://github.com/EddyRivasLab/infernal/blob/f80cd7618636e44e3963f65625cea78c38a8d823/src/cmscan.c#L2). The version number listed appears to line up with `infernal` version numbers

2024-11-12 02:12 UTC, tldahlgren approved these changes

2024-11-12 02:13 UTC, merged