add nugraph packages
LLNL/spack pull request #47315
Opened 2024-10-29 19:19 UTC by vhewes

add the packages `ph5concat`, `py-numl` and `py-nugraph` for the NuGraph GNN workflow for neutrino physics event reconstruction.

2024-10-30 08:57 UTC, x64-Linux-Builder reviewed
(error in the report)

2024-10-31 20:32 UTC, x64-Linux-Builder requested changes

2024-10-31 20:32 UTC, x64-Linux-Builder commented on var/spack/repos/builtin/packages/ph5concat/package.py
> +    depends_on("hdf5+hl")
I guess some variant for parallel I/O (`+mpi`?) might be missing here and the version range is missing, e.g.:
```suggestion
    depends_on("hdf5+hl+mpi@1.10.4:")
```
I didn't check which version (`1.1.0` or `1.0.0`) caused this error, details later in the generated report (to be submitted)
```py
     82    checking for hdf5.h... yes
     83    checking whether HDF5 version is 1.10.4 or later... yes
     84    checking whether HDF5 parallel I/O is enabled... no
  >> 85    configure: error:
     86       -----------------------------------------------------------------------
     87         ph5concat requires parallel I/O feature enabled in HDF5. Abort.
     88       -----------------------------------------------------------------------
```

2024-10-31 20:39 UTC, bernhardkaindl requested changes
The dependencis seem to lack minimum versions, @x64-Linux-Builder found one for hdf5 and got an error on missing the dependency on parallel I/O variant of hdf5.

2024-10-31 20:58 UTC, x64-Linux-Builder requested changes
(broken report removed)

2024-10-31 21:12 UTC, x64-Linux-Builder requested changes
<details><summary>Hello @vhewes! I encountered an install failure of ph5concat+profiling@=1.1.0. Could you check it?</summary><br>

Hello @vhewes,

I am terribly sorry, but my attempt on the installation of `ph5concat+profiling@=1.1.0` failed in an automated build.

 But I've got a detailed report for you that may allow you to fix it based on the knowledge that you have about these recipes.



This command failed: `bin/spack install -v --fail-fast ph5concat+profiling@=1.1.0`
<details><summary>Click here to drill down to the logs from building the failed spec: ph5concat+profiling@=1.1.0</summary>

### `ph5concat+profiling@=1.1.0`:
<details><summary><b>Click here to expand the full build log</b> for ph5concat+profiling@=1.1.0</summary>

```py
==> ph5concat: Executing phase: 'autoreconf'
==> [2024-10-31-21:10:50.174827] Configure script not found: trying to generate it
==> [2024-10-31-21:10:50.174936] Warning: *********************************************************
==> [2024-10-31-21:10:50.174966] Warning: * If the default procedure fails, consider implementing *
==> [2024-10-31-21:10:50.174981] Warning: *        a custom AUTORECONF phase in the package       *
==> [2024-10-31-21:10:50.174993] Warning: *********************************************************
==> [2024-10-31-21:10:50.176012] '$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/autoconf-2.72-rpgi22ohfqtmhgyjnilv6pf5v5mdxne7/bin/autoreconf' '-ivf' '-I' '$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-jt3kkdxy2qbb3wfunlmutjlrujaupm23/share/aclocal'
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-jt3kkdxy2qbb3wfunlmutjlrujaupm23/share/aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory ./scripts
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/autoconf-2.72-rpgi22ohfqtmhgyjnilv6pf5v5mdxne7/bin/autoconf --include=$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-jt3kkdxy2qbb3wfunlmutjlrujaupm23/share/aclocal --force
autoreconf: running: $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/autoconf-2.72-rpgi22ohfqtmhgyjnilv6pf5v5mdxne7/bin/autoheader --include=$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-jt3kkdxy2qbb3wfunlmutjlrujaupm23/share/aclocal --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:139: installing './scripts/compile'
configure.ac:24: installing './scripts/install-sh'
configure.ac:24: installing './scripts/missing'
Makefile.am: installing './scripts/depcomp'
parallel-tests: installing './scripts/test-driver'
autoreconf: './scripts/install-sh' is updated
autoreconf: Leaving directory '.'
==> ph5concat: Executing phase: 'configure'
==> [2024-10-31-21:10:52.599072] Find (recursive): $PWD/.stage/spack-stage-ph5concat-1.1.0-asynetlqq6g6uvj5jddeoysumbszx65l/spack-src ['configure']
==> [2024-10-31-21:10:52.599867] Find complete: $PWD/.stage/spack-stage-ph5concat-1.1.0-asynetlqq6g6uvj5jddeoysumbszx65l/spack-src ['configure']
==> [2024-10-31-21:10:52.600130] FILTER FILE: $PWD/.stage/spack-stage-ph5concat-1.1.0-asynetlqq6g6uvj5jddeoysumbszx65l/spack-src/configure [replacing "^(\s*if test x-L = )("\$p" \|\|\s*)$"]
==> [2024-10-31-21:10:52.610486] FILTER FILE: $PWD/.stage/spack-stage-ph5concat-1.1.0-asynetlqq6g6uvj5jddeoysumbszx65l/spack-src/configure [replacing "^(\s*test x-R = )("\$p")(; then\s*)$"]
==> [2024-10-31-21:10:52.620381] FILTER FILE: $PWD/.stage/spack-stage-ph5concat-1.1.0-asynetlqq6g6uvj5jddeoysumbszx65l/spack-src/configure [replacing "^(\s*test \$p = "-R")(; then\s*)$"]
==> [2024-10-31-21:10:52.633704] '$PWD/.stage/spack-stage-ph5concat-1.1.0-asynetlqq6g6uvj5jddeoysumbszx65l/spack-src/configure' '--prefix=$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/ph5concat-1.1.0-asynetlqq6g6uvj5jddeoysumbszx65l' '--with-hdf5=$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/hdf5-1.14.5-zishieu4utlg6bl7bapq65r23cpznfje' '--with-mpich=$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-k3fzy37jjgnq5bar3vhlfdljatd3a3pr' '--enable-profiling'
configure: WARNING: unrecognized options: --with-mpich
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for sed handling option -i ... /usr/bin/sed -i''
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-k3fzy37jjgnq5bar3vhlfdljatd3a3pr/bin/mpicc exists and is executable... yes
checking for gcc... $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-k3fzy37jjgnq5bar3vhlfdljatd3a3pr/bin/mpicc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-k3fzy37jjgnq5bar3vhlfdljatd3a3pr/bin/mpicc accepts -g... yes
checking for $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-k3fzy37jjgnq5bar3vhlfdljatd3a3pr/bin/mpicc option to enable C11 features... none needed
checking whether $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-k3fzy37jjgnq5bar3vhlfdljatd3a3pr/bin/mpicc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-k3fzy37jjgnq5bar3vhlfdljatd3a3pr/bin/mpicc... gcc3
checking whether $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-k3fzy37jjgnq5bar3vhlfdljatd3a3pr/bin/mpic++ exists and is executable... yes
checking whether the compiler supports GNU C++... yes
checking whether $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-k3fzy37jjgnq5bar3vhlfdljatd3a3pr/bin/mpic++ accepts -g... yes
checking for $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-k3fzy37jjgnq5bar3vhlfdljatd3a3pr/bin/mpic++ option to enable C++11 features... none needed
checking dependency style of $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-k3fzy37jjgnq5bar3vhlfdljatd3a3pr/bin/mpic++... gcc3
checking how to run the C preprocessor... $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-k3fzy37jjgnq5bar3vhlfdljatd3a3pr/bin/mpicc -E
checking for MPI_Comm_rank... yes
checking for MPI_File_open... yes
checking for $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-k3fzy37jjgnq5bar3vhlfdljatd3a3pr/bin/mpicc options needed to detect all undeclared functions... none needed
checking whether access is declared... yes
checking for access... yes
checking whether unlink is declared... yes
checking for unlink... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for hdf5.h... yes
checking whether HDF5 version is 1.10.4 or later... yes
checking whether HDF5 parallel I/O is enabled... no
configure: error: 
   -------------------------------------------------------- [...]

2024-10-31 21:13 UTC, x64-Linux-Builder requested changes
<details><summary>Hello @vhewes! I encountered an install failure of ph5concat+profiling@=1.0.0. Could you check it?</summary><br>

Hello @vhewes,

I am terribly sorry, but my attempt on the installation of `ph5concat+profiling@=1.0.0` failed in an automated build.

 But I've got a detailed report for you that may allow you to fix it based on the knowledge that you have about these recipes.



This command failed: `bin/spack install -v --fail-fast ph5concat+profiling@=1.0.0`
<details><summary>Click here to drill down to the logs from building the failed spec: ph5concat+profiling@=1.0.0</summary>

### `ph5concat+profiling@=1.0.0`:
<details><summary><b>Click here to expand the full build log</b> for ph5concat+profiling@=1.0.0</summary>

```py
==> ph5concat: Executing phase: 'autoreconf'
==> [2024-10-31-21:10:56.628476] Configure script not found: trying to generate it
==> [2024-10-31-21:10:56.628570] Warning: *********************************************************
==> [2024-10-31-21:10:56.628620] Warning: * If the default procedure fails, consider implementing *
==> [2024-10-31-21:10:56.628634] Warning: *        a custom AUTORECONF phase in the package       *
==> [2024-10-31-21:10:56.628647] Warning: *********************************************************
==> [2024-10-31-21:10:56.629574] '$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/autoconf-2.72-p55cygagji6ftvvqchzq5ownmpgkumeh/bin/autoreconf' '-ivf' '-I' '$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-cxe3wwq7q6icfsywbtxznorhvvcxeavl/share/aclocal'
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-cxe3wwq7q6icfsywbtxznorhvvcxeavl/share/aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory ./scripts
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/autoconf-2.72-p55cygagji6ftvvqchzq5ownmpgkumeh/bin/autoconf --include=$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-cxe3wwq7q6icfsywbtxznorhvvcxeavl/share/aclocal --force
autoreconf: running: $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/autoconf-2.72-p55cygagji6ftvvqchzq5ownmpgkumeh/bin/autoheader --include=$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-cxe3wwq7q6icfsywbtxznorhvvcxeavl/share/aclocal --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:139: installing './scripts/compile'
configure.ac:24: installing './scripts/install-sh'
configure.ac:24: installing './scripts/missing'
Makefile.am: installing './scripts/depcomp'
parallel-tests: installing './scripts/test-driver'
autoreconf: './scripts/install-sh' is updated
autoreconf: Leaving directory '.'
==> ph5concat: Executing phase: 'configure'
==> [2024-10-31-21:10:58.965039] Find (recursive): $PWD/.stage/spack-stage-ph5concat-1.0.0-2qnpej2prhh4t5fi2axz3cjtdugc3nrt/spack-src ['configure']
==> [2024-10-31-21:10:58.965839] Find complete: $PWD/.stage/spack-stage-ph5concat-1.0.0-2qnpej2prhh4t5fi2axz3cjtdugc3nrt/spack-src ['configure']
==> [2024-10-31-21:10:58.966224] FILTER FILE: $PWD/.stage/spack-stage-ph5concat-1.0.0-2qnpej2prhh4t5fi2axz3cjtdugc3nrt/spack-src/configure [replacing "^(\s*if test x-L = )("\$p" \|\|\s*)$"]
==> [2024-10-31-21:10:58.976193] FILTER FILE: $PWD/.stage/spack-stage-ph5concat-1.0.0-2qnpej2prhh4t5fi2axz3cjtdugc3nrt/spack-src/configure [replacing "^(\s*test x-R = )("\$p")(; then\s*)$"]
==> [2024-10-31-21:10:58.985821] FILTER FILE: $PWD/.stage/spack-stage-ph5concat-1.0.0-2qnpej2prhh4t5fi2axz3cjtdugc3nrt/spack-src/configure [replacing "^(\s*test \$p = "-R")(; then\s*)$"]
==> [2024-10-31-21:10:58.998316] '$PWD/.stage/spack-stage-ph5concat-1.0.0-2qnpej2prhh4t5fi2axz3cjtdugc3nrt/spack-src/configure' '--prefix=$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/ph5concat-1.0.0-2qnpej2prhh4t5fi2axz3cjtdugc3nrt' '--with-hdf5=$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/hdf5-1.14.5-minmteibd4ukzfsxjz5ceo2djnncicbc' '--with-mpich=$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-gq2zevogc5l3nw5wizfbmgh4iyxhumwn' '--enable-profiling'
configure: WARNING: unrecognized options: --with-mpich
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for sed handling option -i ... /usr/bin/sed -i''
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-gq2zevogc5l3nw5wizfbmgh4iyxhumwn/bin/mpicc exists and is executable... yes
checking for gcc... $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-gq2zevogc5l3nw5wizfbmgh4iyxhumwn/bin/mpicc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-gq2zevogc5l3nw5wizfbmgh4iyxhumwn/bin/mpicc accepts -g... yes
checking for $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-gq2zevogc5l3nw5wizfbmgh4iyxhumwn/bin/mpicc option to enable C11 features... none needed
checking whether $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-gq2zevogc5l3nw5wizfbmgh4iyxhumwn/bin/mpicc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-gq2zevogc5l3nw5wizfbmgh4iyxhumwn/bin/mpicc... gcc3
checking whether $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-gq2zevogc5l3nw5wizfbmgh4iyxhumwn/bin/mpic++ exists and is executable... yes
checking whether the compiler supports GNU C++... yes
checking whether $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-gq2zevogc5l3nw5wizfbmgh4iyxhumwn/bin/mpic++ accepts -g... yes
checking for $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-gq2zevogc5l3nw5wizfbmgh4iyxhumwn/bin/mpic++ option to enable C++11 features... none needed
checking dependency style of $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-gq2zevogc5l3nw5wizfbmgh4iyxhumwn/bin/mpic++... gcc3
checking how to run the C preprocessor... $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-gq2zevogc5l3nw5wizfbmgh4iyxhumwn/bin/mpicc -E
checking for MPI_Comm_rank... yes
checking for MPI_File_open... yes
checking for $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-gq2zevogc5l3nw5wizfbmgh4iyxhumwn/bin/mpicc options needed to detect all undeclared functions... none needed
checking whether access is declared... yes
checking for access... yes
checking whether unlink is declared... yes
checking for unlink... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for hdf5.h... yes
checking whether HDF5 version is 1.10.4 or later... yes
checking whether HDF5 parallel I/O is enabled... yes
checking size of size_t... 8
checking size of hsize_t... 8
checking that gene [...]

2024-10-31 21:36 UTC, bernhardkaindl requested changes
According to this commit, support for hdf5@1.12.0 was added in `v1.1.0.pre`:
https://github.com/NU-CUCIS/ph5concat/commit/cdcb37f1425156ec2f102cf3ab16fdf8095c99c6
> check if H5Treclaim is defined (starting HDF5 1.12.0)
> [v1.1.0](https://github.com/NU-CUCIS/ph5concat/releases/tag/v1.1.0)
[v1.1.0.pre](https://github.com/NU-CUCIS/ph5concat/release/tag/v1.1.0.pre)

That means `1.0.0` won't support `hdf5@1.12:`, while `1.1.0` may support `hdf5@1.12:`, but apparently not up to `hdf5@1.14`.

See the proposed change in this review comment as an example: https://github.com/spack/spack/pull/47315#discussion_r1825132170

2024-10-31 21:57 UTC, x64-Linux-Builder requested changes
<details><summary>Hello @vhewes! I encountered an install failure of ph5concat@=1.0.0. Could you check it?</summary><br>

Hello @vhewes,

I am terribly sorry, but my attempt on the installation of `ph5concat@=1.0.0` failed in an automated build.

 But I've got a detailed report for you that may allow you to fix it based on the knowledge that you have about these recipes.



This command failed: `bin/spack install -v --fail-fast ph5concat@=1.0.0`
<details><summary>Click here to drill down to the logs from building the failed spec: ph5concat@=1.0.0</summary>

### `ph5concat@=1.0.0`:
<details><summary><b>Click here to expand the full build log</b> for ph5concat@=1.0.0</summary>

```py
==> ph5concat: Executing phase: 'autoreconf'
==> [2024-10-31-21:55:14.197710] Configure script not found: trying to generate it
==> [2024-10-31-21:55:14.197785] Warning: *********************************************************
==> [2024-10-31-21:55:14.197816] Warning: * If the default procedure fails, consider implementing *
==> [2024-10-31-21:55:14.197847] Warning: *        a custom AUTORECONF phase in the package       *
==> [2024-10-31-21:55:14.197859] Warning: *********************************************************
==> [2024-10-31-21:55:14.198790] '$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/autoconf-2.72-gworalzjwrk7ugirhhv2aoeg4eoprcim/bin/autoreconf' '-ivf' '-I' '$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-ov4dncrfzjcwoyzdsgx2wxbmulxmlvoy/share/aclocal'
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-ov4dncrfzjcwoyzdsgx2wxbmulxmlvoy/share/aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory ./scripts
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/autoconf-2.72-gworalzjwrk7ugirhhv2aoeg4eoprcim/bin/autoconf --include=$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-ov4dncrfzjcwoyzdsgx2wxbmulxmlvoy/share/aclocal --force
autoreconf: running: $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/autoconf-2.72-gworalzjwrk7ugirhhv2aoeg4eoprcim/bin/autoheader --include=$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/libtool-2.4.7-ov4dncrfzjcwoyzdsgx2wxbmulxmlvoy/share/aclocal --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:139: installing './scripts/compile'
configure.ac:24: installing './scripts/install-sh'
configure.ac:24: installing './scripts/missing'
Makefile.am: installing './scripts/depcomp'
parallel-tests: installing './scripts/test-driver'
autoreconf: './scripts/install-sh' is updated
autoreconf: Leaving directory '.'
==> ph5concat: Executing phase: 'configure'
==> [2024-10-31-21:55:16.572617] Find (recursive): $PWD/.stage/spack-stage-ph5concat-1.0.0-vhcvdepi2nev2ykpy2gypohqj6fk3yux/spack-src ['configure']
==> [2024-10-31-21:55:16.573303] Find complete: $PWD/.stage/spack-stage-ph5concat-1.0.0-vhcvdepi2nev2ykpy2gypohqj6fk3yux/spack-src ['configure']
==> [2024-10-31-21:55:16.573577] FILTER FILE: $PWD/.stage/spack-stage-ph5concat-1.0.0-vhcvdepi2nev2ykpy2gypohqj6fk3yux/spack-src/configure [replacing "^(\s*if test x-L = )("\$p" \|\|\s*)$"]
==> [2024-10-31-21:55:16.583254] FILTER FILE: $PWD/.stage/spack-stage-ph5concat-1.0.0-vhcvdepi2nev2ykpy2gypohqj6fk3yux/spack-src/configure [replacing "^(\s*test x-R = )("\$p")(; then\s*)$"]
==> [2024-10-31-21:55:16.592446] FILTER FILE: $PWD/.stage/spack-stage-ph5concat-1.0.0-vhcvdepi2nev2ykpy2gypohqj6fk3yux/spack-src/configure [replacing "^(\s*test \$p = "-R")(; then\s*)$"]
==> [2024-10-31-21:55:16.604793] '$PWD/.stage/spack-stage-ph5concat-1.0.0-vhcvdepi2nev2ykpy2gypohqj6fk3yux/spack-src/configure' '--prefix=$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/ph5concat-1.0.0-vhcvdepi2nev2ykpy2gypohqj6fk3yux' '--with-hdf5=$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/hdf5-1.10.11-voa6tkgpu2f6snsl5cqcavhhu7m2zk2t' '--with-mpich=$PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-rwi3oyfjvf6tfigmt6sb4dfsmb74onk6' '--disable-profiling'
configure: WARNING: unrecognized options: --with-mpich
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for sed handling option -i ... /usr/bin/sed -i''
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-rwi3oyfjvf6tfigmt6sb4dfsmb74onk6/bin/mpicc exists and is executable... yes
checking for gcc... $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-rwi3oyfjvf6tfigmt6sb4dfsmb74onk6/bin/mpicc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-rwi3oyfjvf6tfigmt6sb4dfsmb74onk6/bin/mpicc accepts -g... yes
checking for $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-rwi3oyfjvf6tfigmt6sb4dfsmb74onk6/bin/mpicc option to enable C11 features... none needed
checking whether $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-rwi3oyfjvf6tfigmt6sb4dfsmb74onk6/bin/mpicc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-rwi3oyfjvf6tfigmt6sb4dfsmb74onk6/bin/mpicc... gcc3
checking whether $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-rwi3oyfjvf6tfigmt6sb4dfsmb74onk6/bin/mpic++ exists and is executable... yes
checking whether the compiler supports GNU C++... yes
checking whether $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-rwi3oyfjvf6tfigmt6sb4dfsmb74onk6/bin/mpic++ accepts -g... yes
checking for $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-rwi3oyfjvf6tfigmt6sb4dfsmb74onk6/bin/mpic++ option to enable C++11 features... none needed
checking dependency style of $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-rwi3oyfjvf6tfigmt6sb4dfsmb74onk6/bin/mpic++... gcc3
checking how to run the C preprocessor... $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-rwi3oyfjvf6tfigmt6sb4dfsmb74onk6/bin/mpicc -E
checking for MPI_Comm_rank... yes
checking for MPI_File_open... yes
checking for $PWD/opt/spack/linux-ubuntu22.04-skylake/gcc-13.1.0/mpich-4.2.3-rwi3oyfjvf6tfigmt6sb4dfsmb74onk6/bin/mpicc options needed to detect all undeclared functions... none needed
checking whether access is declared... yes
checking for access... yes
checking whether unlink is declared... yes
checking for unlink... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for hdf5.h... yes
checking whether HDF5 version is 1.10.4 or later... yes
checking whether HDF5 parallel I/O is enabled... yes
checking size of size_t... 8
checking size of hsize_t... 8
checking that generated files are newer than configure... done
configure: cr [...]

2024-10-31 22:11 UTC, bernhardkaindl reviewed
Besides these build failures, the build appears to work with the suggested dependency updates:
```py
    depends_on("hdf5+hl+mpi@1.10.4:1.12", when="@1.1:")
    depends_on("hdf5+hl+mpi@1.10.4:1.11", when="@1.0")
```
However, if verion 1.0.0 is removed as it did not install any files in my build, the 2nd line can be removed it can be simplified as:
```py
    depends_on("hdf5+hl+mpi@1.10.4:1.12")
```
`@1.10.4:1.12` is based on the commit message that I saw, newer versions like 1.13 may bwork (not tested), but it did not build with 1.14.5.

2024-11-02 21:53 UTC, bernhardkaindl approved these changes, later dismissed
Hi @vhewes, I used a script to check PRs by building the changes of the PR, but it has become too time-consuming to continue and spurred some controversy (and most importantly, should be part of CI).

Meanwhile, it is usable and installable as an [extension script on top of the GitHub CLI](https://github.com/spack/gh-spack-pr).

If you are up for it, you can run it when logged in to a machine that can build your PR and has the branch of your PR checked out. I hope the README in the project and see the output of  `gh spack-pr --help` as well.

The GitHub CLI is generally a useful tool for working with PRs (even for only your PRs), and it is easy to install and authorize with the GitHub API.

PS: You can run the script yourself and pass the option `--comment`, which should enable it to build your currently checked-out PR branch and submit the build results as a comment.

PPS: [#pull-requests](https://spackpm.slack.com/archives/C03LVJYGZ7X) is a good way to ask for a review too and a [spack Q&A Telcon is coming up](https://github.com/spack/spack/wiki/Telcon%3A-2024-11-05) The meeting invitation (using Zoom) to join the meeting is the [#general](https://spackpm.slack.com/archives/C5W7NKZJT) Slack Channel of spack: [the invitation is sent each week](https://spackpm.slack.com/archives/C5W7NKZJT/p1730331138729659?thread_ts=1728337005.104389&cid=C5W7NKZJT)

For now, I've to take a step back on manual reviews, thus I've to unblock your PR:

Because I requested changes, to unblock your PR for other reviewers to merge it, can only override this by flagging this PR as an approval. Don't see this approval as an approval. It is only meant to not block other reviewers from reviewing/merging when they are fine with it.

2024-11-12 19:58 UTC, x64-Linux-Builder reviewed
:thumbsup::information_source: `spack install` on the changed recipes of this PR was successful[^1] on Ubuntu 22.04.4 LTS!<details><summary>Click here for a summary of the successful builds.</summary>
These changed specs were found using [gh pr diff](https://cli.github.com):
- `ph5concat+profiling@=1.1.0`
- `py-nugraph@=24.7.1`
- `py-nugraph@=24.7.0`
- `py-nugraph@=24.4.0`
- `py-nugraph@=24.2.0`
- `py-nugraph@=23.11.1`
- `py-nugraph@=23.11.0`
- `py-nugraph@=23.10.0`
- `py-numl@=24.7.1`
- `py-numl@=24.7.0`
- `py-numl@=24.6.0`
- `py-numl@=23.11.0`
- `py-numl@=23.9.0`
- `py-numl@=23.8.0`
- `py-numl@=23.7.0`
- `py-numl@=23.6.1`
- `py-numl@=23.6.0`
- `py-numl@=23.5.2`
- `py-numl@=23.5.1`
- `py-numl@=23.5.0`


<details><summary><b>Click here to show/hide the report on </b><tt>spack find</tt> for <tt>linux-ubuntu22.04-skylake / gcc@13.1.0</tt>.</summary><ol>

<li><details><summary>Click on this area to unfold/refold the dependency report of this build:

>```py
>ph5concat@1.1.0+profiling build_system=autotools
>```
</summary>

>```py
>	autoconf@2.72
>		m4@1.4.19sigsegv,bfdffa7
>			diffutils@3.10
>			libsigsegv@2.14
>		perl@5.34.0
>	automake@1.16.5
>	gcc-runtime@13.1.0
>	glibc@2.35
>	gmake@4.4.1
>	hdf5@1.12.3
>		cmake@3.30.5
>			curl@8.10.1 tls=openssl
>				nghttp2@1.63.0
>				openssl@3.3.1 certs=mozilla
>					ca-certificates-mozilla@2023-05-30
>			ncurses@6.5
>		openmpi@5.0.5atomics-hwloc-libevent-pmix-rpath
>			libevent@2.1.12openssl
>			numactl@2.0.18
>			openssh@9.8p1gssapi
>				krb5@1.21.3
>					bison@3.8.2
>					gettext@0.22.5bzip2cursesgit
>						tar@1.34 zip=pigz
>							pigz@2.8
>				libedit@3.1-20240808
>				libxcrypt@4.4.35_api
>			pmix@5.0.3
>		pkgconf@2.2.0
>	libtool@2.4.7
>		findutils@4.9.0
>	mpich@4.2.3 datatype-engine=auto device=ch4 netmod=ofi
>		hwloc@2.11.1-level-zero
>		libfabric@1.22.0 fabrics=sockets,tcp,udp
>		libpciaccess@0.17
>			util-macros@1.20.1
>		libxml2@2.10.3
>			xz@5.4.6
>		yaksa@0.3
>			autoconf@2.72
>				perl@5.40.0cpanmopcodeopenthreads
>					berkeley-db@18.1.40cxx,b231fcc
>			automake@1.16.5
>			python@3.13.0bz2ctypesdbm
>				bzip2@1.0.8
>				expat@2.6.3libbsd
>					libbsd@0.12.2
>						libmd@1.0.4
>				gdbm@1.23
>				gettext@0.22.5bzip2cursesgit
>					libxml2@2.10.3
>					tar@1.34 zip=pigz
>						pigz@2.8
>						zstd@1.5.6programs
>				libffi@3.4.6
>				openssl@3.3.1 certs=mozilla
>				readline@8.2
>				sqlite@3.46.0column_metadatadynamic_extensionsfts
>				util-linux-uuid@2.40.2
>				zlib-ng@2.2.1compatnew_strategiesopt
>	zlib@1.3.1optimize
>
>```

</details>


<li><details><summary>Click on this area to unfold/refold the dependency report of this build:

>```py
>py-nugraph@23.10.0
>```
</summary>

>```py
>	gcc-runtime@13.1.0
>	glibc@2.35
>	py-flit-core@3.9.0
>	py-matplotlib@3.9.2 backend=agg
>		freetype@2.13.3
>		libpng@1.6.39
>			cmake@3.30.5
>				curl@8.8.0 tls=openssl
>					nghttp2@1.63.0
>		ninja@1.12.1re2c
>			python@3.13.0bz2ctypesdbm
>			re2c@3.1
>		pkgconf@2.2.0
>		py-contourpy@1.3.0
>			meson@1.5.1
>		py-cycler@0.11.0
>		py-fonttools@4.39.4
>		py-kiwisolver@1.4.5
>			py-cppy@1.2.1
>		py-meson-python@0.16.0
>			py-pyproject-metadata@0.7.1
>		py-numpy@1.24.3
>			openblas@0.3.28_fpcsrdynamic_dispatchfortran
>			py-cython@0.29.36
>		py-packaging@24.1
>		py-pillow@11.0.0
>			libjpeg-turbo@3.0.3_decoder
>				nasm@2.16.03
>		py-pybind11@2.13.5ipo
>		py-pyparsing@3.1.2
>		py-python-dateutil@2.8.2
>			py-six@1.16.0
>		py-setuptools-scm@8.0.4toml
>			git@2.45.2mannlsperlsubtree
>				autoconf@2.72
>				automake@1.16.5
>				libidn2@2.3.7
>					libunistring@1.2
>				libtool@2.4.7
>				m4@1.4.19sigsegv,bfdffa7
>					libsigsegv@2.14
>				openssh@9.8p1gssapi
>					krb5@1.21.2
>						bison@3.8.2
>					libedit@3.1-20240808
>				pcre2@10.44
>			py-tomli@2.0.1
>		qhull@2020.2
>	py-numl@24.7.1
>		mpich@4.2.3 datatype-engine=auto device=ch4 netmod=ofi
>			findutils@4.9.0
>			hwloc@2.11.1-level-zero
>			libfabric@1.22.0 fabrics=sockets,tcp,udp
>			libpciaccess@0.17
>				util-macros@1.20.1
>			libxml2@2.10.3
>			yaksa@0.3
>		py-h5py@3.12.1mpi
>			hdf5@1.14.5
>			openmpi@5.0.5atomics-hwloc-libevent-pmix-rpath
>				libevent@2.1.12openssl
>				pmix@5.0.3
>			py-cython@3.0.11
>			py-mpi4py@4.0.0
>			py-pkgconfig@1.5.5
>				py-poetry-core@1.8.1
>		py-pandas@1.5.3
>			py-bottleneck@1.3.7
>				py-versioneer@0.29toml
>			py-numexpr@2.9.0
>			py-pytz@2023.3
>		py-particle@0.24.0
>			py-attrs@23.1.0
>				py-hatch-fancy-pypi-readme@23.1.0
>			py-hatch-vcs@0.4.0
>			py-hatchling@1.25.0
>				py-editables@0.5
>				py-pathspec@0.11.1
>				py-pluggy@1.5.0
>				py-trove-classifiers@2023.8.7
>					py-calver@2022.6.26
>			py-hepunits@2.3.2
>		py-plotly@5.20.0
>			py-jupyterlab@3.4.8
>				py-ipython@8.28.0
>					py-decorator@5.1.1
>					py-jedi@0.18.2
>						py-parso@0.8.4
>					py-matplotlib-inline@0.1.6
>					py-pexpect@4.9.0
>						py-ptyprocess@0.7.0
>					py-prompt-toolkit@3.0.43
>						py-wcwidth@0.2.7
>					py-pygments@2.18.0
>					py-stack-data@0.6.2
>						py-asttokens@2.4.0
>						py-executing@1.2.0
>						py-pure-eval@0.2.2
>					py-traitlets@5.14.3
>				py-jupyter-core@5.3.0
>					py-platformdirs@3.10.0
>				py-jupyter-packaging@0.12.0
>					py-deprecation@2.1.0
>					py-tomlkit@0.12.1
>				py-jupyter-server@1.21.0
>					py-anyio@3.6.2
>						py-sniffio@1.3.0
>					py-argon2-cffi@21.3.0
>						py-argon2-cffi-bindings@21.2.0
>							py-cffi@1.17.1
>								py-pycparser@2.21
>					py-jupyter-client@8.2.0
>					py-nbconvert@7.14.1serve
>						py-beautifulsoup4@4.12.3
>							py-soupsieve@2.4.1
>						py-bleach@6.0.0
>							py-webencodings@0.5.1
>						py-defusedxml@0.7.1
>						py-jupyterlab-pygments@0.2.2
>						py-mistune@2.0.5
>						py-nbclient@0.8.0
>						py-pandocfilters@1.5.0
>						py-tinycss2@1.2.1
>					py-nbformat@5.8.0
>						py-fastjsonschema@2.16.3
>						py-hatch-nodejs-version@0.3.1
>					py-pre-commit@3.6.0
>						py-cfgv@3.4.0
>						py-identify@2.5.24
>						py-nodeenv@1.8.0
>						py-virtualenv@20.26.5
>							py-distlib@0.3.7
>					py-prometheus-client@0.17.0
>					py-pyzmq@25.0.2
>						libzmq@4.3.5
>							libsodium@1.0.20
>						py-gevent@23.7.0
>							py-greenlet@2.0.2
>							py-zope-event@5.0
>							py-zope-interface@7.0.3
>					py-send2trash@1.8.3
>					py-terminado@0.17.1
>					py-websocket-client@1.8.0
>				py-jupyterlab-server@2.22.1
>					py-babel@2.15.0
>					py-json5@0.9.14
>					py-jsonschema@4.22.0-nongpl
>						py-jsonschema-specifications@2023.12.1
>						py-referencing@0.35.1
>						py-rpds-py@0.20.0
>							py-maturin@1.6.0
>								py-setuptools-rust@1.9.0
>									py-semantic-version@2.10.0
>							rust@1.81.0dev
>								libgit2@1.8.0 https=system
>									pcre@8.45
>								libssh2@1.11.0 crypto=openssl
>								rust-bootstrap@1.81.0
>				py-nbclassic@1.0.0
>					py-ipykernel@6.29.5
>						py-comm@0.1.4
>						py-debugpy@1.6.7
>					py-ipython-genutils@0.2.0
>					py-nest-asyncio@1.6.0
>					py-notebook-shim@0.2.3
>				py-notebook@6.5.4
>				py-tornado@6.3.3
>			py-tenacity@8.2.2
>		py-torch-geometric@2.5.3
>			py-aiohttp@3.9.5
>				py-aiosignal@1.2.0
>				py-charset-normalizer@3.3.0
>				py-frozenlist@1.3.1
>				py-multidict@6.0.4
>				py-yarl@1.9.2
>			py-jinja2@3.1.4
>				py-markupsafe@2.1.3
>			py-psutil@5.9.5
>			py-requests@2.32.3
>				py-certifi@2023.7.22
>				py-idna@3.4
>				py-urllib3@2.1.0
>			py-scikit-learn@1.5.2
>				py-joblib@1.2.0
>				py-threadpoolctl@3.1.0
>			py-scipy@1.14.1
>				py-pythran@0.16.1
>					py-beniget@0.4.1
>					py-gast@0.5.4
>					py-ply@3.11
>	py-pip@23.1.2
>	py-pynvml@8.0.4
>		py-setuptools@69.2.0
>	py-pytorch-lightning@2.0.7
>		py-fsspec@2024.5.0http
>		py-lightning-utilities@0.11.2
>		py-pyyaml@6.0.2libyaml
>			libyaml@0.2.5
>		py-setuptools@63.4.3
>		py-torch@2.5.0-protobuf_mlopenmpqnnpack
>			cpuinfo@2024-08-30
>			eigen@3.4.0 build_type=RelWithDebInfo
>			fp16@2020-05-14
>			fxdiv@2020-04-17
>			gloo@2023-12-03
>			intel-oneapi-mkl@2024.2.2
>				intel-tbb@2021.12.0
>			numactl@2.0.18
>			protobuf@3.13.0
>			psimd@2020-05-17
>			pthreadpool@2023-08-29
>		 [...]

2024-11-12 20:02 UTC, x64-Linux-Builder approved these changes

2024-11-12 20:03 UTC, bernhardkaindl approved these changes

2024-11-13 00:34 UTC, merged