Windows: Improve llvm/clang support
LLNL/spack pull request #47338
Opened 2024-10-30 22:02 UTC by jamessmillie

This PR fixes:

- An issue where spack attempted to use compiler wrappers for clang on Windows.
- `spack compiler find` to find `clang-cl.exe` on Windows for both C and CXX compilers rather than `clang/clang++`.
- the boost bootstrap argument for clang on windows.

2024-11-01 22:41 UTC, scheibelp reviewed
I have a few requests (mainly documentation, with one minor refactor request) and a couple questions (although one of the questions is potentially involved).

2024-11-01 22:41 UTC, scheibelp commented on var/spack/repos/builtin/packages/llvm/package.py
>          # during detection. clang-cl, clang-cpp, etc. are dev tools that we don't need to test
One request and one question here:

This comment should be updated

(question) We also might want to still reject `cl` on non-Windows (if `cl` is only ever present on Windows systems, then I'm wrong - could you check that?)

2024-11-01 22:41 UTC, scheibelp commented on lib/spack/spack/compilers/clang.py
> +        if sys.platform == "win32":
Can you add a comment that there are no compiler wrappers on windows, so this is to tell Spack that it needs to use the underlying compiler binaries directly?

(I'd say we might want to apply this for other compilers, but right now we only support msvc and - with this pr - clang, and we will be adding compiler wrappers for Windows soon)

2024-11-01 22:41 UTC, scheibelp commented on var/spack/repos/builtin/packages/llvm/package.py
> +                compilers.update(cxx=exe, c=exe)
While the `sorted` call ensures that we visit "clang" first, and also use `setdefault` (and therefore do not assign "clang" to "c"), I'd still be more comfortable if we updated the next two statements not to apply on `sys.platform == "win32"`.

2024-11-01 22:41 UTC, scheibelp commented on var/spack/repos/builtin/packages/llvm/package.py
> +        cxx_names = ["clang-cl"]
Doc request: I think it's worth explaining here how `clang-cl` differs from `clang`, namely that it can link with msvc-built binaries because it links against the MSVC C runtime; also (less important but still important) understanding of msvc arg syntax making it effectively a drop in replacement for `cl` when using MSBuild.

(question) Also, my understanding is that `clang-cl` links to `msvc` runtime libraries, so I'm wondering if this needs to be aware of an associated `msvc` and perform any env modifications that the Spack `msvc` compiler class does (i.e. in its own `setup_custom_environment`). Or, if `clang` handles this itself, and if there are multiple `msvc` versions available, does it choose the same one every time? If it's consistent, then I think no additional considerations here are necessary (I'm not sure how it would be though).

2024-11-05 20:56 UTC, jamessmillie commented on var/spack/repos/builtin/packages/llvm/package.py
>          # during detection. clang-cl, clang-cpp, etc. are dev tools that we don't need to test
as far as I can tell, clang-cl is only windows, but since someone took the time to add it to this list, I will maintain that login on non-windows OS.

2024-11-05 21:38 UTC, jamessmillie commented on var/spack/repos/builtin/packages/llvm/package.py
> +                compilers.update(cxx=exe, c=exe)
I updated, please let me know if that meets your expectations

2024-12-06 19:01 UTC, scheibelp requested changes
I think most of this we already agreed on in our conversation yesterday.

2024-12-06 19:01 UTC, scheibelp commented on var/spack/repos/builtin/packages/py-numpy/package.py
> -            env.set("CXX", f'"{self.compiler.cxx}"')
(question) I assume removing this isn't critical to this PR, but this code was unnecessary because of what `msvc.setup_custom_environment` does.

2024-12-06 19:01 UTC, scheibelp commented on share/spack/gitlab/cloud_pipelines/stacks/windows-vis/spack.yaml
> +  - boost+program_options+filesystem+thread+chrono+system+exception+test~shared
I recommend doing this in another PR: this addition isn't specifically testing the changes made in this PR (I think it's a good idea, but we might want to create a separate pipeline, or rename this one to reflect its expanded coverage).

2024-12-06 19:01 UTC, scheibelp commented on lib/spack/spack/compilers/clang.py
> +            for compiler in all_compilers():
IIRC we agreed this should document that as implemented, this can change the associated MSVC version unexpectedly. I think the current implementation is acceptable given that

* Tracking this properly requires modifying the compiler interface and
* that is in flux

Secondary question: have you confirmed that we can guarantee picking whatever MSVC we want when running `clang-cl` (i.e. that running the associated setvars script guarantees that we will not use resources associated with other MSVC versions, if they also happen to be installed, and in particular even if they are newer)?

2024-12-06 19:01 UTC, scheibelp commented on var/spack/repos/builtin/packages/py-meson-python/package.py
> +            env.set("CXX", windows_sfn(self.compiler.cxx))
In terms of running, the `sfn` should always be safe to use. It's worth noting though that:

  * This changes CC for every tool that may run during the build (not just `meson` or `python-meson`)
  * @johnwparent pointed out that some tools might examine the name/path of the compiler executable to make decisions

I'm OK with this as-is, but I think as a follow up we should investigate something that applies this change in a more targeted manner: when building any `X->py-meson-python`, we could modify the `pyproject.toml` of X

```
[tool.meson-python]
meson-args = ["--native-file=native.ini"]
```

The `--native-file` could set the C/C++ compiler to point to the `sfn`.

In the meantime, a TODO should be added.

2024-12-06 21:27 UTC, jamessmillie commented on var/spack/repos/builtin/packages/py-numpy/package.py
> -            env.set("CXX", f'"{self.compiler.cxx}"')
Correct

2024-12-06 23:23 UTC, jamessmillie commented on lib/spack/spack/compilers/clang.py
> +            for compiler in all_compilers():
> Secondary question: have you confirmed that we can guarantee picking whatever MSVC we want when running clang-cl (i.e. that running the associated setvars script guarantees that we will not use resources associated with other MSVC versions, if they also happen to be installed, and in particular even if they are newer)?

Yes. I have 2 versions of MSVC installed and I built numpy twice, changing my `compilers.yaml` in between builds to switch the first listed MSVC to the other version and the first one listed was selected both times, as seen in the meson-log.txt output for each build.

Run 1:
```
Note: including file:          C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.29.30133\include\vcruntime.h
```

Run 2:
```
Note: including file:          C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.39.33519\include\vcruntime.h
```

2024-12-19 19:31 UTC, scheibelp commented
@spackbot run pipeline

2025-08-11 01:55 UTC, closed without merging