mmg : add variant to install private headers for parmmg packaged
LLNL/spack pull request #47386
Opened 2024-11-03 15:24 UTC by prudhomm

add private variant to install private headers thanks to MMG_INSTALL_PRIVATE_HEADERS needed by parmmg

/cc @jcortial-safran

2024-11-04 10:17 UTC, jcortial-safran commented
I would prefer a more explicit variant name, e.g. `private_headers`.

The variant should be also appear as a dependency in the parmmg package : https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/parmmg/package.py

2024-11-04 15:08 UTC, jcortial-safran commented
Unless I am mistaken the option is only available for version 5.7.0 or later : https://github.com/MmgTools/mmg/commit/9f98ef4050a59b56e651e1641e07b2b1253917c0

 So the option should not be available for versions earlier than 5.7.0.

2024-11-05 01:56 UTC, tldahlgren submitted a review, later dismissed
LGTM.  @jcortial-safran ?

2024-11-05 08:21 UTC, jcortial-safran commented
> LGTM. @jcortial-safran ?

I have suggested a couple of minor changes.

2024-11-12 02:22 UTC, tldahlgren commented
Ping me with a comment here when this is ready to merge.

2024-12-15 20:04 UTC, prudhomm commented
@tldahlgren @jcortial-safran I believe I applied the required changes.

2024-12-16 09:43 UTC, jcortial-safran requested changes

2024-12-16 09:43 UTC, jcortial-safran commented on var/spack/repos/builtin/packages/mmg/package.py
> -        shared_active = self.spec.satisfies("+shared")
This line should not have been deleted. Please restore it, currently the recipe is broken.

2024-12-16 09:43 UTC, jcortial-safran commented on var/spack/repos/builtin/packages/mmg/package.py
> +    variant("private_headers", default=True, description="Enable private headers")
I would prefer the default value to be `False`.

2024-12-18 01:50 UTC, tldahlgren commented on var/spack/repos/builtin/packages/mmg/package.py
> +            )
If this option only applies for versions `@5.7:`, then you could pass that as a `when` argument to the variant then not bother with the check here.

2024-12-18 13:39 UTC, jcortial-safran commented
LGTM @tldahlgren

2024-12-18 13:39 UTC, jcortial-safran approved these changes

2024-12-19 03:11 UTC, tldahlgren approved these changes

2024-12-19 03:12 UTC, merged