pace: new package
LLNL/spack pull request #47561
Opened 2024-11-12 12:31 UTC by hjjvandam

The optional module ML-PACE in LAMMPS requires external code from https://github.com/ICAMS/lammps-user-pace.

This PR adds a Spack package to install Pace as a separate library, and modifies the LAMMPS package to build Pace as a dependency when ML-PACE is requested.
```bash
spack install lammps +ml-pace
```
installs LAMMPS with the ML-PACE module included.

2024-11-13 09:21 UTC, hjjvandam commented
Apparently there are failures in the "ci/gitlab-ci". There are two kinds of failures:
1. `aws-isc-build` and `e4s-power-build`: "Unable to create pipeline", "Job `e4s-power-generate` not found in parent pipeline or does not have artifacts!". There is also a tag "yaml invalid". 
2. `e4s-cray-rhel-build`:  Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/tmp/gitlab-runner-2/spack-stage/spack-stage-patch-b8d1f08a82329e493e040de2bde9d2291af173a0fe6c7deb24750cc22823c421/spack-src/49bdc3e26449634f150602a66d0dab34d09dbc0e.patch?full_index=1' '-d' '.'
Ad 1. Is this a Spack problem? I have no idea what yaml file this error refers to and my changes are architecture independent. So I cannot see how this error is related to my changes. Anyone got any ideas?
Ad 2. I don't know why patching the LAMMPS code failed. I didn't make any changes to LAMMPS. Also there is little information by the way of error messages as to what patch didn't like. What is the best way to proceed here?

2024-11-14 14:29 UTC, rbberger commented
@hjjvandam for this to work the CMake install of pace would have to place the necessary files into its install prefix and the LAMMPS ML-PACE Cmake needs to be able to consume those files. Right now it assumes access to the LAMMPS/pace source code. 

Right now you have to provide [LOCAL_ML-PACE](https://github.com/lammps/lammps/blob/develop/cmake/Modules/Packages/ML-PACE.cmake#L16) to a source location of PACE, otherwise it'll just try to download its known version fresh.

I've also started my own effort by providing ML-PACE as a LAMMPS plugin via Spack internally, which grabs both sources and builds a shared library that can be loaded at runtime.

But if it is possible to build PACE without LAMMPS sources, I'd prefer patching up the CMake in both projects.

Feel free to ping me in the LAMMPS/Spack slack.

2024-11-14 15:31 UTC, hjjvandam commented
@rbberger I am happy to discuss this topic, but how do I get onto the LAMMPS/Spack slack? Is there a way you can invite me to the channel? I have just joined Slack with hubertus dot vandam at uni-due dot de. My organization normally doesn't use Slack (although my previous organization does).

2024-11-14 15:50 UTC, rbberger commented
I'm "rberger" (one b) in both Spack and LAMMPS slack spaces. Just send me a direct message.

2024-11-19 04:11 UTC, rbberger commented
@hjjvandam After looking at the code and the `lammps-user-pace` CMake, there are still several key pieces still missing in `lammps-user-pace` for this to work. Right now it only produces `lib/libpace.a` in its install. What is needed for any other CMake project to consume is the following:
- something like `PACEConfig.cmake` generated during install that can be found by CMake via `find_package(PACE)`. See https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html#example-generating-package-files
- installation of the headers from `ML-PACE` in the install prefix, so that when linking to the PACE targets the `ML-PACE` files in LAMMPS can find them. The source tree of the `pace` spack package will disappear and isn't accessible after installation. You have to explicitly write them to the install prefix in your `install` target, ideally as part of your CMake.

2024-11-19 04:12 UTC, rbberger requested changes
CMake install of this project is currently insufficient for consumption by other projects.

2025-01-09 22:38 UTC, rbberger commented
@hjjvandam pushed a new version that makes use of the new tag https://github.com/ICAMS/lammps-user-pace/releases/tag/v.2023.11.25.fix2

2025-01-09 22:40 UTC, rbberger approved these changes
Now functional with new pace release and updated Spack package.

2025-01-09 23:21 UTC, tldahlgren approved these changes
Confirmed homepage, branch, and version commit for the new package.

2025-01-13 16:42 UTC, rbberger commented
@spackbot run pipeline

2025-01-13 17:28 UTC, merged