Adding MDI
LLNL/spack pull request #47636
Opened 2024-11-16 13:19 UTC by hjjvandam

The optional module MDI in LAMMPS requires external code from https://github.com/MolSSI-MDI/MDI_Library. MDI installs as a Python package.

This PR adds a Spack package to install Py-MDI as a separate library, and modifies the LAMMPS package to build Py-MDI as a dependency when MDI is requested.
```bash
spack install lammps +mdi

installs LAMMPS with the Py-MDI module included.

2024-11-18 14:57 UTC, rbberger commented on var/spack/repos/builtin/packages/py-mdi/package.py
> +        url="https://codeload.github.com/MolSSI-MDI/MDI_Library/tar.gz/refs/tags/v1.4.30",
Why not use git, tag and commit sha?

2024-11-18 14:57 UTC, rbberger commented on var/spack/repos/builtin/packages/lammps/package.py
> +    depends_on("py-mdi", when="+mdi", type="build")
Is it only a build dependency? I would guess you also want it at runtime for it to be available in Python.

2025-01-11 02:34 UTC, rbberger commented on var/spack/repos/builtin/packages/lammps/package.py
> +    depends_on("py-mdi", when="+mdi", type="build")
Also made it a run dependency.

2025-01-11 02:34 UTC, rbberger commented on var/spack/repos/builtin/packages/py-mdi/package.py
> +        url="https://codeload.github.com/MolSSI-MDI/MDI_Library/tar.gz/refs/tags/v1.4.30",
Updated to latest version with git tag and commit.

2025-01-11 03:14 UTC, rbberger approved these changes, later dismissed
Updated it myself. @tldahlgren I'd appreciate another set of eyes.

2025-01-13 17:32 UTC, tldahlgren reviewed
Confirmed the homepage and version commit.

2025-01-13 17:37 UTC, tldahlgren requested changes
A couple of `py-mdi` dependencies need to be constrained per `pyproject.toml`.

```
[build-system]
requires = ["setuptools>=42", "wheel", "cmake>=3.5.0", "packaging"]
```

2025-01-13 17:37 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-mdi/package.py
> +    depends_on("py-setuptools", type="build")
According to `pyproject.toml`, this should be `py-setuptools@42:`.

2025-01-13 17:37 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-mdi/package.py
> +    depends_on("py-wheel", type="build")
FWIW. This is already inherited from `PythonPackage`.

2025-01-13 17:37 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-mdi/package.py
> +    depends_on("cmake", type="build")
According to `pyproject.toml`, this should be `cmake@3.5:`.

2025-01-13 18:03 UTC, rbberger commented on var/spack/repos/builtin/packages/py-mdi/package.py
> +    depends_on("py-setuptools", type="build")
Fixed.

2025-01-13 18:03 UTC, rbberger commented on var/spack/repos/builtin/packages/py-mdi/package.py
> +    depends_on("py-wheel", type="build")
Removed.

2025-01-13 18:04 UTC, rbberger commented on var/spack/repos/builtin/packages/py-mdi/package.py
> +    depends_on("cmake", type="build")
Fixed.

2025-01-13 18:09 UTC, tldahlgren approved these changes, later dismissed
Thanks.

2025-01-13 18:13 UTC, tldahlgren commented
There are still conflicts with `lammps` that need to be resolved.

2025-01-13 18:55 UTC, tldahlgren approved these changes

2025-01-14 03:54 UTC, merged