new package: rocm-examples
LLNL/spack pull request #47695
Opened 2024-11-20 16:09 UTC by afzpatel

This package is a collection of hip and ROCm math library example tests.
A build-time test of all the examples can be run with --test=root option.

2024-12-03 08:37 UTC, srekolam requested changes
can you add the 6.2.4 checksum too, otherwise i am okay with the changes.

2024-12-05 07:43 UTC, renjithravindrankannath approved these changes
LGTM

2025-01-28 16:45 UTC, renjithravindrankannath approved these changes

2025-01-29 06:03 UTC, srekolam commented on var/spack/repos/builtin/packages/rocjpeg/package.py
> +    homepage = "https://rocm.docs.amd.com/projects/rocJPEG/en/latest/"
homepage= "https://github.com/ROCm/rocJPEG"
git="https://github.com/ROCm/rocJPEG.git"

2025-01-31 14:32 UTC, afzpatel commented
@tldahlgren could you please review thir PR?

2025-02-03 09:45 UTC, srekolam approved these changes

2025-02-03 21:10 UTC, tldahlgren approved these changes
Confirmed homepages and version sha256s.

2025-02-03 21:11 UTC, merged