Py-heat 1.5.0 incl. cuda, rocm support
LLNL/spack pull request #47710
Opened 2024-11-21 06:39 UTC by ClaudiaComito

- added release 1.5 
- added variants `cuda`, `cuda_arch` and `rocm` to reflect GPU support where hardware available
- **NEED HELP**: the `cuda_arch` variant isn't passed correctly to `depends_on(`py-torch ...`). On my system (JUWELS at Jülich) 
```
spack add py-heat +cuda cuda_arch=80
spack install
```
results in `Error: invalid values for variant 'cuda_arch' in package py-heat: '10'` no matter what I do.

However
```
spack add py-torch +cuda cuda_arch=80
spack install
```
works as expected.

Thanks in advance for helping us out!

2024-11-22 09:04 UTC, mrfh92 commented
@melven @svengoldberg as our spack-experts, do you immediately see whats the problem here? (if not, we will figure out ourselves)

2024-11-22 09:10 UTC, ClaudiaComito commented
@spackbot help

2024-11-22 09:49 UTC, svengoldberg commented
@mrfh92 I am sorry, I cannot really help you here...
@melven is probably not available this day. I would guess he can have a lool next week

2024-11-29 13:05 UTC, ClaudiaComito commented
I hope it's ok to ping @adamjstewart here who maintains the PyTorch recipe - not sure we can solve the problem on our own.  Thanks and apologies!

2024-11-29 13:54 UTC, adamjstewart commented
> NEED HELP: the cuda_arch variant isn't passed correctly to depends_on("py-torch ..."). On my system (JUWELS at Jülich)

Glad to see other JSC people here!

Try:
```console
> spack add py-heat ++cuda cuda_arch==80
```
This forces the variants to propagate through the entire DAG (for any packages with those variants). You can also set them globally in your `packages.yaml` or `spack.yaml`.

2024-12-02 11:36 UTC, ClaudiaComito commented
> ```
> spack add py-heat ++cuda cuda_arch==80
> ```

Thanks a lot @adamjstewart  - I still get the same error afterwards at `spack install`:
```
==> Error: invalid values for variant 'cuda_arch' in package py-heat: '10'
```

Where is that `10` coming from? FWIW installing py-torch with cuda_arch=80 works fine.

Thanks again for your help!

2024-12-02 23:12 UTC, adamjstewart commented
Can you also check the output of `spack config blame packages` to see if you have any config files somewhere that are adding that?

2025-04-11 09:26 UTC, ClaudiaComito commented
@adamjstewart thanks for the help and sorry it took me so long to get back to this. I've cleaned up my local env and don't run into the cuda_arch problem any more. Thanks for the hints.

I'm now running into this problem at py-mpi4py installation, again not sure if it's my env or something fundamentally wrong with the recipe. Many thanks in advance for checking this out!

```shell
==> Installing py-mpi4py-4.0.1-x4i2dneuglqvbgg5l37kbx4vee4a6bvp [73/77]
==> No binary for py-mpi4py-4.0.1-x4i2dneuglqvbgg5l37kbx4vee4a6bvp found: installing from source
==> Error: AttributeError: 'Spec' object has no attribute 'mpicc'

The 'py-mpi4py' package cannot find an attribute while trying to build from sources. You can fix this by updating the build recipe, and you can also report the issue as a build-error or a bug at https://github.com/spack/spack/issues

/p/scratch/haf/comito1/spack/var/spack/repos/builtin/packages/py-mpi4py/package.py:47, in setup_build_environment:
         46    def setup_build_environment(self, env):
  >>     47        env.set("MPICC", self.spec["mpi"].mpicc)


==> Warning: Skipping build of py-heat-1.5.0-dr3cwoml3kpmgt7geb3srtsvfmsawg7q since py-mpi4py-4.0.1-x4i2dneuglqvbgg5l37kbx4vee4a6bvp failed
```

2025-04-11 09:43 UTC, adamjstewart commented
^ @alalazo?

2025-04-11 15:01 UTC, ClaudiaComito commented
@spackbot request review

2025-04-11 15:10 UTC, mrfh92 approved these changes
@spackbot @ClaudiaComito to me, these changes look reasonable

2025-04-14 07:49 UTC, alalazo requested changes

2025-04-14 07:49 UTC, alalazo commented on var/spack/repos/builtin/packages/py-heat/package.py
> +    variant("cuda_arch", default="80", description="CUDA compute capability")
When overridden like this, `cuda_arch` is wrong, since it doesn't allow any value. What was the issue here, for which we can't inherit these variants from `CudaPackage`?

2025-04-24 10:02 UTC, ClaudiaComito commented on var/spack/repos/builtin/packages/py-heat/package.py
> +    variant("cuda_arch", default="80", description="CUDA compute capability")
thanks @alalazo . 

The initial version of this recipe (`class PyHeat(PythonPackage):`...) was building py-heat with py-torch-cpu by default. We would like to be able to build py-heat with the cuda or rocm version of py-torch, depending on the system.

I'm not sure what the best way of doing it is, I'm grateful for any help. Thanks!

2025-06-06 12:06 UTC, haampie commented
Hi @ClaudiaComito, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2025-06-10 11:56 UTC, closed without merging