Python package for venv's may find the wrong python executable as find_first will return first match.
LLNL/spack pull request #47712
Opened 2024-11-21 09:01 UTC by vucoda

Find - in order of importance - the python3 executable as find_first() return the first match.

2024-11-21 09:36 UTC, haampie commented
lgtm. I had on my list to make find_first accept a list of patterns and return on first match of any, which would simplify this a bit.

2024-11-21 23:50 UTC, vucoda commented
Preference would be python3.xx over python3 over python as the first found executable when using external/system python as multiple versions may exist in the same location  (e.g. python3 and python 2).  This can happen when bootstrapping spack from sources.

2024-11-22 08:02 UTC, haampie submitted a review, later dismissed

2024-11-22 09:34 UTC, haampie commented
Can you give an example of how it goes wrong though?

2024-11-22 10:13 UTC, vucoda commented
In spack 0.23.0 when I bootstrap from source on some systems where `/usr/bin/python` = python 2 and `/usr/bin/python3` is python 3, the `python-venv` `spack` package using find_first() may pick up /usr/bin/python as the executable, then calling `/usr/bin/python -m venv` will fail. the above commit makes sure to find python3.xx or python3 before python

2024-11-22 12:56 UTC, haampie requested changes
Ah okay. I'm inclined to say that the bug is in `find_first` then. If a dir contains multiple matches, the first match of the first patterns should be returned instead of the first file that matches any of the patterns.

My worry is that merging this as is may cause a very expensive recursive scan if the first patterns has no hits.

2025-06-06 12:06 UTC, haampie commented
Hi @vucoda, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2026-01-04 01:53 UTC, closed without merging