libftdi: new package
LLNL/spack pull request #47722
Opened 2024-11-21 15:01 UTC by davekeeshan

Initial commit of compile file required for libftdi, covers version 1.3 through 1.5

    libftdi - A library (using libusb) to talk to FTDI's UART/FIFO chips
    including the popular bitbang mode

2025-05-27 12:49 UTC, alalazo requested changes

2025-05-27 12:49 UTC, alalazo commented on var/spack/repos/builtin/packages/libftdi/package.py
> +    depends_on("libconfuse", type="build")
```suggestion
    depends_on("libusb")
    depends_on("libconfuse")
```
?

2025-05-27 16:47 UTC, davekeeshan commented
I have made the changes, but also had to update the file to match some of the flow changes recently

2025-06-06 12:06 UTC, haampie commented
Hi @davekeeshan, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2025-06-06 20:34 UTC, closed without merging