py-flowcept: add py-flowcept package
LLNL/spack pull request #47745
Opened 2024-11-22 18:59 UTC by mdorier

Installation tested on my Arm64 machine (Ubuntu on MacBook Pro M2 Max), with the `+kafka` and `+dask` variants.

@renan-souza I took the liberty of adding you as a maintainer of this package.

2024-11-25 18:17 UTC, renan-souza commented
> Installation tested on my Arm64 machine (Ubuntu on MacBook Pro M2 Max), with the `+kafka` and `+dask` variants.
> 
> @renan-souza I took the liberty of adding you as a maintainer of this package.

Sure, that's good. Thank you!

2024-11-28 09:20 UTC, alalazo requested changes

2024-11-28 09:20 UTC, alalazo commented on var/spack/repos/builtin/packages/3dtk/py-flowcept/package.py
> +    # the license, set checked_by to your Github username.
```suggestion
```

2024-11-28 09:20 UTC, alalazo commented on var/spack/repos/builtin/packages/3dtk/py-flowcept/package.py
> +    depends_on("py-dask@:2024.10.0+distributed", type=("build", "run"), when="+dask")
Here we can cleanup directives by:
```suggestion
    with default_args(type=("build", "run")):
        depends_on("py-flask-restful")
        depends_on("py-msgpack")
        depends_on("py-omegaconf")
        depends_on("py-pandas")
        depends_on("py-psutil")
        depends_on("py-py-cpuinfo")
        depends_on("py-pymongo")
        depends_on("py-redis")
        depends_on("py-requests")
        depends_on("py-confluent-kafka", when="+kafka")
        depends_on("py-tomli", when="+dask")
        depends_on("py-dask@:2024.10.0+distributed", when="+dask")
```
```

2025-02-27 15:14 UTC, mdorier commented
@alalazo anything against this PR being merged?

2025-03-17 10:05 UTC, alalazo approved these changes

2025-03-17 10:05 UTC, merged

2025-03-17 10:13 UTC, alalazo commented
I just reverted the merge. Can you double check adding the `package.py` in the correct directory structure? If you use `spack create` it should be done automatically.