Dev/python updates
LLNL/spack pull request #47856
Opened 2024-12-01 06:22 UTC by joequant

Update python packages for builds.

2024-12-02 02:37 UTC, wdconinc commented
@spackbot run pipeline

2024-12-02 21:15 UTC, tldahlgren reviewed
Confirmed the new sha256s and most dependencies.  Have a question about one dependency and cannot confirm the older sha256s for `py-pyproject-metadata`.

2024-12-02 21:15 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-pyproject-metadata/package.py
> +    depends_on("py-flit", type="build")
According to `pyproject.toml`, the dependency is on `py-flit-core`, not `py-flit` (which depends on `py-flit-core`:

```
requires = ["flit-core"]
```

Is there a reason you want to use `py-flit` instead?

2024-12-02 21:15 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-pyproject-metadata/package.py
>      version("0.6.1", sha256="b5fb09543a64a91165dfe85796759f9e415edc296beb4db33d1ecf7866a862bd")
I cannot confirm the sha256s for these versions with the new `pypi` value.

2024-12-02 21:15 UTC, tldahlgren requested changes
See previous comment.

2025-06-17 09:19 UTC, closed without merging

2025-06-17 09:19 UTC, alalazo commented
Closing, since moved the package repository. Feel free to reopen at / migrate to https://github.com/spack/spack-packages if you want to continue working on this.