Add support for espresso 4.2.x
LLNL/spack pull request #47864
Opened 2024-12-02 17:02 UTC by rfbgo

Primary goal here is to add new versions of espresso

I also added some basic package improvements while I was here..

2025-01-03 19:03 UTC, rfbgo commented
Can someone help me understand what needs to be done here to get this merged? Thanks!

2025-01-04 08:17 UTC, alalazo requested changes

2025-01-04 08:17 UTC, alalazo commented on var/spack/repos/builtin/packages/py-espresso/package.py
> +    conflicts("%gcc@11:", when="@:4.2")
Version range is inclusive, so this conflicts applies to all the 4.2.X versions. Reading the release notes, and the comment above here, it seems it is not what you want.

2025-01-04 08:17 UTC, alalazo commented on var/spack/repos/builtin/packages/py-espresso/package.py
> +        if self.spec.version >= Version("4.0.0") and self.spec.version < Version("4.2.0"):
```suggestion
        if self.spec.satisfies("@4.0:4.1"):
```

2025-01-04 08:19 UTC, alalazo commented
> Can someone help me understand what needs to be done here to get this merged? Thanks!

Hi @rfbgo! In general, PRs for packages just need some attention from a maintainer with merge-to-develop privileges. If it seems that a PR got unnoticed, you can either ping specific maintainers, when it makes sense, or post it in the `#pull-request` channel on our Slack.

2025-01-06 16:46 UTC, rfbgo commented on var/spack/repos/builtin/packages/py-espresso/package.py
> +    conflicts("%gcc@11:", when="@:4.2")
Great catch, thanks! Updated and ready for re-review

2025-01-06 19:43 UTC, alalazo approved these changes

2025-01-06 19:44 UTC, merged