Go build system: reduce resulting installation sizes
LLNL/spack pull request #47943
Opened 2024-12-05 17:59 UTC by alecbcs

We currently store all of the go modules of a build in the resulting package with the idea of providing those dependencies. However we don't currently map go dependencies all the way down the stack, and there's ongoing debate about how we'll support offline Go installs. In the meantime we should only provide the resulting statically linked binaries.

2025-01-24 22:17 UTC, tldahlgren requested changes
Patch coverage doesn't reflect the slight increase in patch coverage of `go.py` so no issue there. You just need to rebase to pick up Harmen's recent type checking changes.

2025-01-24 22:17 UTC, tldahlgren commented on var/spack/repos/builtin/packages/go/package.py
>          In most cases, extensions will only need to set GOPATH and use go::
Is this comment still relevant?

2025-01-27 15:58 UTC, alecbcs commented on var/spack/repos/builtin/packages/go/package.py
>          In most cases, extensions will only need to set GOPATH and use go::
Removed! Good catch thanks!

2025-01-27 19:31 UTC, tldahlgren commented
FYI. The only directly modified file has a net increase of 1.88% patch coverage.

2025-01-27 19:32 UTC, tldahlgren approved these changes
Thanks.

2025-01-27 19:32 UTC, merged