Add hp2p app definition
LLNL/spack pull request #47950
Opened 2024-12-05 21:26 UTC by rfbgo

2024-12-05 21:34 UTC, rfbgo commented
@spackbot fix style

2024-12-10 01:05 UTC, tldahlgren requested changes
Confirmed the version sha256. 

Please correct the home page property name. Switching to using f-strings for the args is encouraged but not required. You are also encouraged to add yourself as the maintainer for the package (https://spack.readthedocs.io/en/latest/packaging_guide.html#maintainers).

2024-12-10 01:05 UTC, tldahlgren commented on var/spack/repos/builtin/packages/hp2p/package.py
> +        args = ["CC={0}".format(spec["mpi"].mpicc), "CXX={0}".format(spec["mpi"].mpicxx)]
We now encourage use of Python f-strings (https://docs.python.org/3/tutorial/inputoutput.html) where appropriate.

2024-12-10 01:05 UTC, tldahlgren commented on var/spack/repos/builtin/packages/hp2p/package.py
> +    home = "https://github.com/cea-hpc/hp2p"
This needs to be the `homepage` property:

```suggestion
    homepage = "https://github.com/cea-hpc/hp2p"
```

2024-12-10 01:05 UTC, tldahlgren commented on var/spack/repos/builtin/packages/hp2p/package.py
> +    home = "https://github.com/cea-hpc/hp2p"
Confirmed the  homepage exists (when specified using `homepage`).

2024-12-10 02:53 UTC, rfbgo commented on var/spack/repos/builtin/packages/hp2p/package.py
> +        args = ["CC={0}".format(spec["mpi"].mpicc), "CXX={0}".format(spec["mpi"].mpicxx)]
Thanks for the feedback! Agreed and applied, ptal :)

2024-12-10 21:03 UTC, tldahlgren approved these changes
Thanks.

2024-12-10 21:03 UTC, merged