py-dask: fix py-versioneer version pin
LLNL/spack pull request #47980
Opened 2024-12-08 16:23 UTC by wdconinc

This PR fixes the `py-dask` build dependency on `py-versioneer` for releases after https://github.com/dask/dask/pull/10575.

2024-12-09 19:49 UTC, tldahlgren requested changes
Confirmed the `py-versioneer` dependency for the latest version BUT it looks like `py-click` should also be changed per `pyproject.toml`:

```
dependencies = [
    # NOTE: These are tested in `continuous_integration/test_imports.sh` If
    # you modify these, make sure to change the corresponding line there.
    "click >= 8.1",
    "cloudpickle >= 1.5.0",
    "fsspec >= 2021.09.0",
    "packaging >= 20.0",
    "partd >= 1.4.0",
    "pyyaml >= 5.3.1",
    "toolz >= 0.10.0",
    # importlib.metadata has the following bugs fixed in 3.10.9 and 3.11.1
    # https://github.com/python/cpython/issues/99130
    # https://github.com/python/cpython/issues/98706
    "importlib_metadata >= 4.13.0; python_version < '3.12' ",
]
```

2024-12-09 20:21 UTC, wdconinc commented
Good catch. I hadn't evaluated the other dependencies.

2024-12-11 19:46 UTC, tldahlgren submitted a review, later dismissed

2024-12-11 19:46 UTC, tldahlgren commented
@skosukhin Any objections to merging this PR?

2025-01-14 15:22 UTC, wdconinc commented
@skosukhin Would you be able to give this a quick review?

2025-01-14 15:27 UTC, skosukhin approved these changes
I would sort the lines by the version of the dependency. Otherwise, LGTM.

2025-01-14 15:27 UTC, skosukhin commented on var/spack/repos/builtin/packages/py-dask/package.py
> +    depends_on("py-versioneer@0.28+toml", type="build", when="@2023.4.1:2023.10.0")
```suggestion
    depends_on("py-versioneer@0.28+toml", type="build", when="@2023.4.1:2023.10.0")
    depends_on("py-versioneer@0.29+toml", type="build", when="@2023.10.1:")
```

2025-01-14 15:34 UTC, skosukhin approved these changes

2025-01-14 17:43 UTC, tldahlgren approved these changes

2025-01-14 17:44 UTC, merged