ginkgo: add v1.9.0
LLNL/spack pull request #47987
Opened 2024-12-09 16:47 UTC by MarcelKoch

2024-12-09 19:12 UTC, tldahlgren requested changes
Confirmed the branches exist. Please use the `commit` argument for that hash.

2024-12-09 19:12 UTC, tldahlgren commented on var/spack/repos/builtin/packages/ginkgo/package.py
> +    version("1.9.0", branch="20cfd68795f58078898da9890baa311b46845a8b")  # v1.9.0
```suggestion
    version("1.9.0", commit="20cfd68795f58078898da9890baa311b46845a8b")  # v1.9.0
```

2024-12-10 20:10 UTC, tldahlgren requested changes
Thank you for the update.

Confirmed the branches and commit but do not see how the new variant is being used in the package. If it isn't going to affect the build, the new variant should be removed.

2024-12-10 20:10 UTC, tldahlgren commented on var/spack/repos/builtin/packages/ginkgo/package.py
> +    variant("half_precision", default=True, description="Enable half-precision support")
Did you intend to use this in some way?  At this point the variant has no affect on the build.

2024-12-11 08:13 UTC, MarcelKoch commented on var/spack/repos/builtin/packages/ginkgo/package.py
> +    variant("half_precision", default=True, description="Enable half-precision support")
Yes, I added it now as a CMake option.

2024-12-11 19:52 UTC, tldahlgren commented
One stack exceeded time limit for generation. Trying again:

@spackbot run pipeline

2024-12-11 19:53 UTC, tldahlgren approved these changes

2024-12-11 23:53 UTC, merged