py-typer: add version 0.15.1 and "standard" optional dependencies
LLNL/spack pull request #48010
Opened 2024-12-10 17:03 UTC by lgarrison

https://github.com/fastapi/typer/tree/0.15.1

2024-12-12 18:28 UTC, lgarrison commented
@spackbot re-run pipeline

2024-12-14 20:31 UTC, lgarrison commented
@spackbot re-run pipeline

2024-12-19 02:09 UTC, tldahlgren requested changes
Confirmed the sha256 and dependencies. 

Don't need trailing `.0` in dependency ranges. Unclear, based on `pyproject.toml` if the new variant is needed but, if it is, then that directive should be listed *after* all version directives.

2024-12-19 02:09 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-typer/package.py
> +    variant("standard", default=True, description="Optional dependencies installed by default")
Please move the variant directive to below the version directives.

2024-12-19 02:09 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-typer/package.py
> +        depends_on("py-rich@10.11.0:", type=("build", "run"), when="+standard")
Slightly confused. According to the `pyproject.toml` file, these don't appear to be optional:

```
dependencies = [
    "click >= 8.0.0",
    "typing-extensions >= 3.7.4.3",
    "shellingham >=1.3.0",
    "rich >=10.11.0",
]
```

2024-12-19 02:09 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-typer/package.py
> +        depends_on("py-shellingham@1.3.0:", type=("build", "run"), when="+standard")
```suggestion
        depends_on("py-shellingham@1.3:", type=("build", "run"), when="+standard")
```

2024-12-19 02:09 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-typer/package.py
> +        depends_on("py-rich@10.11.0:", type=("build", "run"), when="+standard")
```suggestion
        depends_on("py-rich@10.11:", type=("build", "run"), when="+standard")
```

2024-12-19 15:14 UTC, lgarrison commented
Regarding the variant, it looks like `standard` is an optional dependency that only exists in the source, not the sdist! I think the custom `pdm_build.py` script is inserting those dependencies into the `pyproject.toml` at build time. Since we're using the sdist, I agree that this shouldn't be a variant. Thanks for catching that.

And thank you for the advice about `.0`; I wasn't sure if best practice was to match the exact version numbers from `pyproject.toml` as closely as possible, or whether to simplify/normalize version numbers. I'll do the latter going forward.

2024-12-19 18:34 UTC, tldahlgren approved these changes
Thanks.

2024-12-19 18:35 UTC, merged