add Arkouda server and client packages
LLNL/spack pull request #48054
Opened 2024-12-11 21:50 UTC by arezaii

Adds packages for the Arkouda server (`arkouda`) and Arkouda python client  (`py-arkouda`).

Depends on updates in https://github.com/spack/spack/pull/48020 and https://github.com/spack/spack/pull/48053

2025-01-15 05:51 UTC, tgamblin requested changes

2025-01-15 05:51 UTC, tgamblin commented on var/spack/repos/builtin/packages/py-arkouda/package.py
> +    #         depends_on("py-ipython")
Can this be removed until it's done? We typically don't want commented out code in the repo.

2025-01-16 05:38 UTC, tgamblin approved these changes

2025-01-16 05:39 UTC, merged

2025-01-16 17:27 UTC, bradcray commented
Thanks Todd!  Thanks Ahmad!  I know the Arkouda users are looking forward to this.