py-pymc3 - update to 3.11.6
LLNL/spack pull request #48089
Opened 2024-12-13 05:09 UTC by joequant

update to 3.11.6

2024-12-13 18:28 UTC, tldahlgren reviewed
Confirmed the sha256.

2024-12-13 19:38 UTC, tldahlgren requested changes
See comment

2024-12-13 19:38 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-pymc3/package.py
> +    version("3.11.6", sha256="9e930a1cfd2ee558892b4d92af043696c65a622b64098332687fd75c78f10bce")
Confirmed the sha256 but the dependencies below don't match what this version needs per `requirements.txt`:

```
arviz>=0.11.0
cachetools>=4.2.1
deprecat
dill
fastprogress>=0.2.0
numpy>=1.15.0,<1.22.2
pandas>=0.24.0
patsy>=0.5.1
scipy>=1.7.3,<1.8.0
semver>=2.13.0
theano-pymc==1.1.2
typing-extensions>=3.7.4
```

The minimum python is also `3.7` per this version's `setup.py`.

2025-06-06 12:07 UTC, haampie commented
Hi @joequant, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2025-06-17 09:26 UTC, alalazo commented
Closing, since moved the package repository. Feel free to reopen at / migrate to https://github.com/spack/spack-packages if you want to continue working on this.

2025-06-17 09:26 UTC, closed without merging