vecgeom: remove template kw for clang
LLNL/spack pull request #48095
Opened 2024-12-13 05:12 UTC by joequant

fixes to allow vecgeom to compile with clang

2024-12-13 10:57 UTC, sethrj requested changes
The policy of spack is make sure patches are merged upstream rather than maintained by spack. To that end could you please:
- Remove whitespace changes from your patch
- Submit it as a pull request to https://gitlab.cern.ch/VecGeom/VecGeom (or I can if you don't have the necessary account privileges)
- Wait for it to be merged so that we can get a git-generated patch file which comes directly from that server, e.g. `patch("https://...", sha256="...", when='...')`
- Reference the VecGeom PR in your updated spack recipe

Thanks!

2024-12-16 13:50 UTC, drbenmorgan commented
The fix should have been applied upstream already in https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/1251

2024-12-16 21:40 UTC, sethrj commented on var/spack/repos/builtin/packages/vecgeom/package.py
> +    patch("remove-template-kw.patch", when="@:1.2.10%clang")
Can you see if the following works for you:
```suggestion
    patch("https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/1251.patch", when="@:1.2.10%clang", sha256="72501ffa9a8c6136fbcbfa83a404fdd7ad4dbd144de06a937c5ae5456af60c0c")
```
Then you won't need to include the manual patch file.

2025-06-17 09:29 UTC, alalazo commented
Closing, since moved the package repository. Feel free to reopen at / migrate to https://github.com/spack/spack-packages if you want to continue working on this.

2025-06-17 09:29 UTC, closed without merging