py-networkx: add new versions up to 3.4.2
LLNL/spack pull request #48091
Opened 2024-12-13 05:10 UTC by joequant

add versions up to 3.4.2

2024-12-13 18:11 UTC, tldahlgren commented
@spackbot run pipeline

2024-12-13 22:47 UTC, wdconinc requested changes
Missing py-setuptools min version. Missing python min version changes. py-numpy min version incorrect, should be 1.24. Dependency versions for intermediate versions missing.

2024-12-14 01:08 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-networkx/package.py
> +        depends_on("python@3.8:", when="@2.7:", type=("build", "run"))
I'd move these up outside of the `+default` context manager. There are already py-setuptools and python dependencies defined there.

2024-12-14 01:11 UTC, wdconinc commented on var/spack/repos/builtin/packages/py-networkx/package.py
> +        # push numpy up to 2
This comment does not apply to the lower limits that follow
```suggestion
```

2024-12-14 01:11 UTC, wdconinc reviewed
Verified checksums.

2025-03-04 19:22 UTC, wdconinc commented
Moved to #49289.

2025-03-04 19:22 UTC, closed without merging