py-nose: remove setuptools version limit
LLNL/spack pull request #48093
Opened 2024-12-13 05:11 UTC by joequant

The setuptools version limit prevents installs for python that don't match <=3.11

2024-12-13 17:21 UTC, tldahlgren commented
> The setuptools version limit prevents installs for python that don't match <=3.11

So should the version limit still be applied only to builds with the older python versions?

2024-12-13 17:23 UTC, tldahlgren requested changes
See question and suggestion.

2024-12-13 17:23 UTC, tldahlgren commented on var/spack/repos/builtin/packages/py-nose/package.py
> +    depends_on("py-setuptools", type="build")
Given the PR description, perhaps this should be changed to the following?

```suggestion
    depends_on("py-setuptools@:57", type="build", when="^python@:3.11")
    depends_on("py-setuptools", type="build")
```

2025-06-06 12:07 UTC, haampie commented
Hi @joequant, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2025-06-17 09:27 UTC, alalazo commented
Closing, since moved the package repository. Feel free to reopen at / migrate to https://github.com/spack/spack-packages if you want to continue working on this.

2025-06-17 09:27 UTC, closed without merging