[WIP] package/alps from github
LLNL/spack pull request #48183
Opened 2024-12-18 05:10 UTC by Sinan81

Use alps sources from github.

2024-12-18 05:12 UTC, Sinan81 commented
running into this issue during cmake phase:
```
5 errors found in build log:                                                                                                                                                                                                                  
     94                                                                                                                                                                                                                                       
     95       with mis-matching arguments.                                                                                                                                                                                                    
     96     This warning is for project developers.  Use -Wno-dev to suppress it.                                                                                                                                                             
     97                                                                                                                                                                                                                                       
     98     -- tebd will not be built                                                                                                                                                                                                         
     99     -- Configuring done                                                                                                                                                                                                               
  >> 100    CMake Error at src/boost/CMakeLists.txt:347 (add_library):                                                                                                                                                                        
     101      No SOURCES given to target: boost_test_exec_monitor                                                                                                                                                                             
     102                                                                                                                                                                                                                                      
     103                                                                                                                                                                                                                                      
  >> 104    CMake Error at src/boost/CMakeLists.txt:303 (add_library):                                                                                                                                                                        
     105      No SOURCES given to target: boost                                                                                                                                                                                               
     106                                                                                                                                                                                                                                      
     107                                                                                                                                                                                                                                      
  >> 108    CMake Error at src/boost/CMakeLists.txt:306 (add_library):                                                                                                                                                                        
     109      No SOURCES given to target: boost_python                                                                                                                                                                                        
     110                                                                                                                                                                                                                                      
     111                                                                                                                                                                                                                                      
  >> 112    CMake Error at src/boost/CMakeLists.txt:346 (add_library):                                                                                                                                                                        
     113      No SOURCES given to target: boost_unit_test_framework                                                                                                                                                                           
     114                                                                                                                                                                                                                                      
     115                                                                                                                                                                                                                                      
  >> 116    CMake Error at src/boost/CMakeLists.txt:348 (add_library):                                                                                                                                                                        
     117      No SOURCES given to target: boost_prg_exec_monitor                                                                                                                                                                              
     118                                                                                                                                                                                                                                      
     119                                                                                                                                                                                                                                      
     120    CMake Generate step failed.  Build files cannot be regenerated correctly.     
 ```                                             `

2024-12-18 07:14 UTC, egull commented
Thanks. We'll look into it. ALPS likes to have control over the boost sources and compile them itself. That may be what's going wrong here. Will update as we find out what's going on.

2024-12-19 04:10 UTC, Sinan81 commented
Now, the build works fine. However, installation path for python files needs to configured.

2025-01-17 14:52 UTC, davide-q commented
> running into this issue during cmake phase:

That's the same as https://github.com/ALPSim/ALPS/issues/6

> Now, the build works fine. 

@Sinan81 How did you solve it?

> Thanks. We'll look into it. ALPS likes to have control over the boost sources and compile them itself. That may be what's going wrong here. Will update as we find out what's going on.

@egull please do let me know. Downloading them in the build phase might be a convenience in some circumstances, but not always feasible. This is preventing me from installing boost as I described on the issue linked above. Thanks!

2025-01-18 01:17 UTC, Sinan81 commented
TO-DO add resource statement for boost sources

2025-01-19 20:17 UTC, Sinan81 commented
@davide-q now `spack install alps` works fully, hence alps can be installed in one step from source with all the dependencies.

2025-01-19 20:30 UTC, Sinan81 commented on var/spack/repos/builtin/packages/alps/package.py
> +    maintainers("Sinan81")
@iskakof I'm wondering if you might be interested in being listed as maintainer here so that users can contact you for build issues.

2025-01-19 20:31 UTC, Sinan81 commented
@spackbot fix style

2025-01-20 07:35 UTC, alalazo requested changes

2025-01-20 07:35 UTC, alalazo commented on var/spack/repos/builtin/packages/alps/package.py
> +    Tags: Condensed Matter Physics, Computational Physics
What are these tags for? How do they relate to the `tags` class level attribute?

2025-01-20 07:35 UTC, alalazo commented on var/spack/repos/builtin/packages/alps/package.py
> +    }
Can't we build using Spack installed `boost`? Why do we need to expand the source files as resources?

2025-01-20 07:35 UTC, alalazo commented on var/spack/repos/builtin/packages/alps/package.py
> +    conflicts("^boost@1.88:", msg="update resource list above for newer boost versions")
:thinking:

2025-01-20 07:35 UTC, alalazo commented on var/spack/repos/builtin/packages/alps/package.py
> +        )
Why do we need the source dir of `boost`?

2025-01-21 04:33 UTC, Sinan81 commented on var/spack/repos/builtin/packages/alps/package.py
> +    Tags: Condensed Matter Physics, Computational Physics
not sure. It's just mean to be a list of keywords describing the usage domain of the software. can be removed.

2025-01-21 04:34 UTC, Sinan81 commented on var/spack/repos/builtin/packages/alps/package.py
> +    }
not sure. for some reason, the package needs the boost source files.

2025-01-21 04:36 UTC, Sinan81 commented on var/spack/repos/builtin/packages/alps/package.py
> +    conflicts("^boost@1.88:", msg="update resource list above for newer boost versions")
This is to prevent the build from failing if resource isn't defined for latest boost. This can removed if necessary. Alternatively, I can restrict the boost version in `depends_on(boost`.

2025-01-21 04:36 UTC, Sinan81 commented on var/spack/repos/builtin/packages/alps/package.py
> +        )
not sure. I'm not the developer of this software.

2025-01-21 04:38 UTC, Sinan81 commented on var/spack/repos/builtin/packages/alps/package.py
> +        )
if this option isn't provided, the alps package downloads latest version of boost automatically, which is not preferable from reproduceablity and consistency point of view.

2025-01-21 05:45 UTC, Sinan81 commented on var/spack/repos/builtin/packages/alps/package.py
> +    }
so I wanted to download boost src like this, but fore some reason it's not working, which doesn't make sense
```python 
    @run_before("cmake")
    def get_boost_src(self):
        boost_spec = self.spec["boost"]
        boost_pkg =  boost_spec.package
        # Get the URL for the specified version
        download_url = boost_pkg.url_for_version(boost_spec.version)
        checksum = boost_pkg.versions.get(version, {}).get('sha256', None)

        resource(
            when="@2:",
            name="boost_source_files",
            url=download_url,
            sha256=checksum,
            destination="",
            placement="boost_source_files",
        )
```

2025-01-21 05:46 UTC, Sinan81 commented on var/spack/repos/builtin/packages/alps/package.py
> +    }
when I debug, it seems like `get_boost_src` ins't run at al.

2025-01-21 05:47 UTC, Sinan81 commented
@spackbot fix style

2025-01-21 06:13 UTC, Sinan81 commented on var/spack/repos/builtin/packages/alps/package.py
> +    conflicts("^boost@1.88:", msg="update resource list above for newer boost versions")
now removed.

2025-01-21 07:24 UTC, alalazo commented on var/spack/repos/builtin/packages/alps/package.py
> +    }
`resource` is a directive, it makes sense only at class scope and cannot be used in an imperative way during a function call.

2025-01-21 08:01 UTC, Sinan81 commented on var/spack/repos/builtin/packages/alps/package.py
> +    maintainers("Sinan81")
can be done later. resolving.

2025-01-21 08:03 UTC, Sinan81 commented
@alalazo it's ready to merge but somehow it's blocked. it says "changes are requested" by I don't see anything.

2025-01-22 19:51 UTC, alalazo submitted a review, later dismissed

2025-01-22 19:51 UTC, alalazo commented on var/spack/repos/builtin/packages/alps/package.py
> +    resources = {
```suggestion
    # See https://github.com/ALPSim/ALPS/issues/6#issuecomment-2604912169 
    # for why this is needed
    resources = {
```

2025-01-22 19:52 UTC, alalazo approved these changes, later dismissed

2025-01-22 19:57 UTC, alalazo commented
@spackbot run pipeline

2025-01-22 19:58 UTC, alalazo commented
@spackbot fix style

2025-01-22 21:56 UTC, alalazo approved these changes

2025-01-22 21:57 UTC, merged

2025-01-23 00:04 UTC, davide-q commented
> now spack install alps works fully, hence alps can be installed in one step from source with all the dependencies.

Thanks for this one too @Sinan81 -- however it has several python related dependencies (such as numpy) and I've moved away from installing them with Spack so I can't test this one at the moment (at least not in my production environment, I should make a test spack environment which at the moment I don't have). However I am not sure how this can lead to a different outcome than installing manually and solving issue https://github.com/ALPSim/ALPS/issues/9 since that's a compiler error which should appear identical in Spack or manual cmake invocation

2025-01-24 17:56 UTC, davide-q commented
As far as I can tell, this does not compile with `gcc v12.2.0` but it does with `gcc v11.4.0`

@alalazo @Sinan81 I recommend testing this in a broader CI than my RH box and confirming or disproving my statement above. If confirmed you will want to make sure the `package.py` has the correct safeguards in place to avoid spack compiling alps with a version of the compiler known for not being able to properly build it.

2025-01-24 18:17 UTC, alalazo commented
@Sinan81 Can you check if we need further constraints?

2025-01-24 18:23 UTC, egull commented
In the mean time we on our end are testing this with gcc 12.4.0 to reproduce (and hopefully fix) the issue asap.

2025-01-24 18:31 UTC, davide-q commented
Thanks @egull and sorry for the typo, everybody. The problem is with gcc 14.2.0 (I have not tried anything in the 12.xxx tree)