Update TFEL package du to transition from `boost/python` to `pybind11`
LLNL/spack pull request #48237
Opened 2024-12-20 14:37 UTC by thelfer

- The `master` branch (future 5.1) is now using `pybind11` rather than `boost/python`.
- correct homepage

2025-01-04 10:07 UTC, alalazo requested changes

2025-01-04 10:07 UTC, alalazo commented on var/spack/repos/builtin/packages/mgis/package.py
> +        depends_on("py-pybind11", when="+python_bindings", type=("build", "link", "run"))
```
PKG-DIRECTIVES: 1 issue found
1. mgis: wrong variant in 'depends_on' directive
    variant python_bindings does not exist in mgis
    in /Users/runner/work/spack/spack/var/spack/repos/builtin/packages/mgis/package.py
```

2025-01-04 14:58 UTC, thelfer commented on var/spack/repos/builtin/packages/mgis/package.py
> +        depends_on("py-pybind11", when="+python_bindings", type=("build", "link", "run"))
@alalazo Thanks for reporting. I tried to make some fixes, but, it seems that I do need more help.

For instance, I added the following tests:

```python

       if "+python_bindings" in self.spec:

            with when("@5.1:"):
                args.append("-Dpybind11_DIR={0}".format(self.spec["py-pybind11"].prefix))
            
            with when("@2.0.4:5.0.99"):
                args.append("-DBOOST_ROOT={0}".format(self.spec["boost"].prefix))
                args.append("-DBoost_NO_SYSTEM_PATHS=ON")
                args.append("-DBoost_NO_BOOST_CMAKE=ON")
```

When I try to install the `master`, the second `with when` is activated and I don't understand why as the dependencies are correctly met:

```python
    with when("@5.1:"):
        depends_on("py-pybind11", when="+python_bindings", type=("build", "link", "run"))
        
    with when("@2.0.4:5.0.99"):
        # As boost+py has py runtime dependency, boost+py needs types link and run as well:
        depends_on(
            "boost+python+numpy+exception+container",
            when="+python_bindings",
            type=("build", "link", "run"),
        )
```

i.e. `pybind` is  correctly installed and not `boost`. Any idea ?

2025-01-05 18:15 UTC, thelfer commented on var/spack/repos/builtin/packages/mgis/package.py
> +        depends_on("py-pybind11", when="+python_bindings", type=("build", "link", "run"))
@alalazo After several try and guess, it seems that I now have two working packages in all cases, although the code is a bit inelegant. Do not hesitate if you have any better proposal

2025-01-06 07:31 UTC, alalazo commented on var/spack/repos/builtin/packages/tfel/package.py
> +        )
(Optional comment on style) This is probably better factored by grouping on:
```python
with when("+python_bindings"):
```
since, in that case, you'll see under the same block the different dependencies needed to activate the same functionality.

2025-01-06 07:31 UTC, alalazo commented on var/spack/repos/builtin/packages/tfel/package.py
> +            if "py-pybind11" in self.spec:
I would just:
```python
if self.spec.satisfies("@5.1:"):
    # Assume pybind11
else:
    # Assume Boost Python
```

2025-01-06 07:31 UTC, alalazo commented on var/spack/repos/builtin/packages/mgis/package.py
> +        )
(Optional) Similarly to the comment above, I would group on `python`

2025-01-06 07:31 UTC, alalazo commented on var/spack/repos/builtin/packages/mgis/package.py
> +            if "py-pybind11" in self.spec:
...and distinguish based on `@3.1:` or not

2025-01-06 07:32 UTC, alalazo commented on var/spack/repos/builtin/packages/mgis/package.py
> +        depends_on("py-pybind11", when="+python_bindings", type=("build", "link", "run"))
`when` can only be used with directives at class level, it can't be used within functions where you have a `spec` available.

2025-01-06 07:34 UTC, thelfer commented on var/spack/repos/builtin/packages/tfel/package.py
> +        )
Yes, I see. I need to make a minor release of `mgis` soon, I'll do that when I'll update the packages, if you don't mind.

2025-01-06 07:35 UTC, thelfer commented on var/spack/repos/builtin/packages/tfel/package.py
> +            if "py-pybind11" in self.spec:
I see, I'll try this in the next PR.

2025-01-06 07:36 UTC, thelfer commented on var/spack/repos/builtin/packages/mgis/package.py
> +        )
ok

2025-01-06 07:36 UTC, thelfer commented on var/spack/repos/builtin/packages/mgis/package.py
> +            if "py-pybind11" in self.spec:
ok

2025-01-06 07:37 UTC, thelfer commented on var/spack/repos/builtin/packages/mgis/package.py
> +        depends_on("py-pybind11", when="+python_bindings", type=("build", "link", "run"))
@alalazo ok, this wasn't clear to me, thanks for the clarification.

2025-01-06 07:44 UTC, thelfer commented
@alalazo I'll make another PR in the coming week associated with some minor versions of `TFEL` and `MGIS` (fix compilation with latest `gcc`). Would you mind approving this PR in the current state ?

2025-01-13 11:58 UTC, alalazo approved these changes
There are further improvements slated for a following PR

2025-01-13 11:59 UTC, merged