Reframe: 4.6.4, 4.7.0, 4.7.1, and 4.7.2
LLNL/spack pull request #48242
Opened 2024-12-20 17:16 UTC by robert-mijakovic

2024-12-21 20:01 UTC, vkarak requested changes
Thanks for updating the versions. 

ReFrame 4.7 introduces two more dependencies though: `py-filelock` and `py-tabulate`.

2025-01-04 10:03 UTC, alalazo requested changes
Can you address @vkarak review? Thanks!

2025-01-09 22:13 UTC, vkarak commented
@robert-mijakovic I tried to update your branch, but I couldn't. Here's the change:

```diff
diff --git a/var/spack/repos/builtin/packages/reframe/package.py b/var/spack/repos/builtin/packages/reframe/package.py
index 7cd5574508..ef022af2dc 100644
--- a/var/spack/repos/builtin/packages/reframe/package.py
+++ b/var/spack/repos/builtin/packages/reframe/package.py
@@ -138,6 +138,8 @@ class Reframe(Package):
     depends_on("py-pyyaml", when="@3.4.1:", type="run")
     depends_on("py-requests", when="@3.4.1:", type="run")
     depends_on("py-semver", when="@3.4.2:", type="run")
+    depends_on("py-filelock", when="@4.7:", type="run")
+    depends_on("py-tabulate", when="@4.7:", type="run")

     # extension dependencies
     depends_on("py-pygelf", when="+gelf", type="run")
```

I could open a PR to @robert-mijakovic's fork, but since the changes are minimal, I guess the suggestion is easier.

2025-02-07 08:44 UTC, robert-mijakovic commented
Guys, sorry for the delay. :)
I guess now everything is ok.

2025-02-07 10:54 UTC, vkarak approved these changes

2025-02-07 13:05 UTC, robert-mijakovic commented
Just one more thing about sanity_check_is_dir.
 `sanity_check_is_dir = ["bin", "config", "docs", "reframe", "unittests", "tutorials"]`.

Please note that 4.7.x releases are missing `config` and 4.6.x+ releases are missing tutorials.

2025-02-07 17:31 UTC, vkarak commented
> Just one more thing about sanity_check_is_dir.

I think for this one we should just have the minimal set which is `bin`, `reframe` and `docs` and is common to all versions.

2025-02-08 22:24 UTC, vkarak approved these changes

2025-02-10 07:25 UTC, alalazo approved these changes

2025-02-10 07:25 UTC, merged