hevea: new version 2.36 accepts ocaml 5 series
LLNL/spack pull request #48273
Opened 2024-12-23 16:59 UTC by cessenat

Hevea prior to 2.35 (included) demanded ocaml 4 series.

2025-01-04 09:52 UTC, alalazo requested changes

2025-01-04 09:52 UTC, alalazo commented on var/spack/repos/builtin/packages/hevea/package.py
> +    conflicts("ocaml@5.0.0:", when="@:2.35")
Can we express that as an additional `depends_on`:
```python
depends_on("ocaml@:xxx", when="@:2.35")
```
?

2025-01-05 10:12 UTC, cessenat commented on var/spack/repos/builtin/packages/hevea/package.py
> +    conflicts("ocaml@5.0.0:", when="@:2.35")
Sure. Done.

2025-01-06 07:16 UTC, alalazo commented on var/spack/repos/builtin/packages/hevea/package.py
> +    depends_on("ocaml@4.0.0:4.99.9", when="@:2.35")
This is different from the previous conflict, since it also imposes a lower bound (`ocaml` must be at major version 4). If this is the correct directive we can use just:
```suggestion
    depends_on("ocaml@4", when="@:2.35")
```
Also, shouldn't we impose a lower bound regardless of versions? It seems odd that `hevea@2.36` can use `ocaml@3` according to the directives.

2025-01-06 18:52 UTC, cessenat commented on var/spack/repos/builtin/packages/hevea/package.py
> +    depends_on("ocaml@4.0.0:4.99.9", when="@:2.35")
That's right. BTW prior to ocaml 4.8.0 configure should not set CC={self.compiler.cc}.
Maybe I shall open a PR for that later on.

2025-01-06 19:42 UTC, alalazo approved these changes

2025-01-06 19:57 UTC, merged