py-onnxruntime: set std=cxx20 for clang
LLNL/spack pull request #48289
Opened 2024-12-26 08:18 UTC by joequant

fix compile for clang >= 19

2025-01-04 09:46 UTC, alalazo requested changes

2025-01-04 09:46 UTC, alalazo commented on var/spack/repos/builtin/packages/py-onnxruntime/package.py
> +            env.set("SPACK_CXXFLAGS", "-std=c++20")
See https://github.com/spack/spack/pull/48291#discussion_r1902954562

2025-06-06 12:07 UTC, haampie commented
Hi @joequant, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2025-06-17 09:31 UTC, alalazo commented
Closing, since we moved the package repository. Feel free to reopen at / migrate to https://github.com/spack/spack-packages if you want to continue working on this.

2025-06-17 09:31 UTC, closed without merging