py-onnx: set stdcxx when clang
LLNL/spack pull request #48291
Opened 2024-12-26 08:20 UTC by joequant

fix compile error for clang >= 19

2025-01-04 09:46 UTC, alalazo requested changes

2025-01-04 09:46 UTC, alalazo commented on var/spack/repos/builtin/packages/py-onnx/package.py
> +            env.set("SPACK_CXXFLAGS", "-std=c++20")
Was this PR tested? This context manager only works for directives at class scope. It doesn't work in functions, where we can access `self.spec` and have conditionals like:
```python
if self.spec.satisfies("%clang@19:"):
```

2025-06-06 12:07 UTC, haampie commented
Hi @joequant, this package-related pull request can be migrated from `spack/spack` to `spack/spack-packages` using the [**migrate-pkg-prs utility**](https://github.com/spack/migrate-package-prs).

We encourage authors to run the migration script themselves to preserve author attribution.

You can migrate all your open pull requests at once, following the steps in the [documentation](https://github.com/spack/migrate-package-prs?tab=readme-ov-file#usage-instructions).

---

*This comment was posted automatically.*

2025-06-17 09:31 UTC, alalazo commented
Closing, since we moved the package repository. Feel free to reopen at / migrate to https://github.com/spack/spack-packages if you want to continue working on this.

2025-06-17 09:31 UTC, closed without merging